# THE TRANSITION IN THE YEAR 2000

> "It feels like something big is about to happen: graphs show us the yearly growth of populations, atmospheric concentrations of carbon dioxide, Web addresses, and Mbytes per dollar. They all soar up to an asymptote just beyond the turn of the century: The Singularity. The end of everything we know. The beginning of something we may never understand" [^1] - Danny Hillis

## PREMONITIONS

The coming of the year 2000 has haunted the Western imagination for the past thousand years. Ever since the world failed to end at the turn of the first millennium after Christ, theologians, evangelists, poets, and seers have looked to the end of this decade with an expectation that it would bring something momentous. No less an authority than Isaac Newton speculated that the world would end with the year 2000. Michel de Nostradamus, whose prophecies have been read by every generation since they were first published in 1568, forecast the coming of the Third Antichrist in July 1999.[^2] Swiss psychologist Carl Jung, connoisseur of the "collective unconscious," envisioned the birth of a New Age in 1997. Such forecasts may easily be ridiculed. And so can the sober forecasts of economists, such as Dr. Edward Yardeni of Deutsche Bank Securities, who expects computer malfunctions on the millennial midnight to "disrupt the entire global economy."[^3] But whether you view the Y2K computer problem as groundless hysteria ginned up by computer programmers and Information Technology consultants to stir up business, or as a mysterious instance of technology unfulding in concert with the prophetic imagination, there is no denying that circumstances at the eve of the millennium excite more than the usual morbid doubt about where the world is tending.

A sense of disquiet about the future has begun to color the optimism so characteristic of Western societies for the past 250 years. People everywhere are hesitant and worried. You see it in their faces. Hear it in their conversation. See it reflected in polls and registered in the ballot box. Just as an invisible, physical change of ions in the atmosphere signals that a thunderstorm is imminent even before the clouds darken and lightning strikes, so now, in the twilight of the millennium, premonitions of change are in the air. One person after another, each in his own way, senses that time is running out on a dying way of life. As the decade expires, a murderous century expires with it, and also a glorious millennium of human accomplishment. All draw to a close with the year 2000.

> For there is nothing covered that shall not be revealed, neither hid that shall not be known." - Matthew 10:26

We believe that the modern phase of Western civilization will end with it. This book tells why. Like many earlier works, it is an attempt to see into a glass darkly, to sketch out the vague shapes and dimensions of a future that is still to be. In that sense, we mean our work to be apocalyptic in the original meaning of the word. Apokalypsis means "unveiling" in Greek. We believe that a new stage in history - the Information Age - is about to be "unveiled."

> We are watching the beginnings of a new logical space, an instantaneous electronic everywhereness, which we may all access, enter into, and experience. We have, in short, the beginnings of a new kind of community. The virtual community becomes the model for a secular Kingdom of Heaven; as Jesus said there were many mansions in his FAther's Kingdom, so there are many virtual communities, each reflecting their own needs and desires. - Michael Grasso[^4]

## THE FOURTH STAGE OF HUMAN SOCIETY

The theme of this book is the new revolution of power which is liberating individuals at the expense of the twentiethcentury nationstate. Innovations that alter the logic of violence in unprecedented ways are transforming the boundaries within which the future must lie. If our deductions are correct, you stand at the threshold of the most sweeping revolution in history. Faster than all but a few now imagine, microprocessing will subvert and destroy the nationstate, creating new forms of social organization in the process. This will be far from an easy transformation.

The challenge it will pose will be all the greater because it will happen with incredible speed compared with anything seen in the past. Through all of human history from its earliest beginnings until now, there have been only three basic stages of economic life. (1) hunting-and-gathering societies; (2) agricultural societies; and (3) industrial societies. Now, looming over the horizon, is something entirely new, the fourth stage of social organization: information societies.

Each of the previous stages of society has corresponded with distinctly different phases in the evolution and control of violence. As we explain in detail, information societies promise to dramatically reduce the returns to violence, in part because they transcend locality. The virtual reality of cyberspace, what novelist William Gibson characterized as a "consensual hallucination," will be as far beyond the reach of bullies as imagination can take it. If the new millennium, the advantage of controlling violence on a large scale will be far lower than it has been at any time since before the French Revolution. This will have profound consequences. One of these will be rising crime. When the payoff for organizing violence at a large scale tumbles, the payoff from violence at a smaller scale is likely to jump. Violence will become more random and localized. Organized crime will grow in scope. We explain why.

Another logical implication of falling returns to violence is the eclipse of politics. There is much evidence that adherence to the civic myths of the twentiethcentury nationstate is rapidly eroding. The death of Communism is merely the most striking example. As we explore in detail, the collapse of morality and growing corruption among leaders of Western governments is not a random development. It is evidence that the potential of the nationstate is exhausted. Even many of its leaders no longer believe the platitudes they mouth. Nor are they believed by others.

### History Repeats Itself

This is a situation with striking parallels in the past. Whenever technological change has divorced the old forms from the new moving forces of the economy, moral standards shift, and people begin to treat those in command of the old institutions with growing disdain. This widespread revulsion often comes into evidence well before people develop a new coherent ideology of change. So it was in the late fifteenth century, when the medieval Church was the predominant institution of feudalism. Notwithstanding popular belief in "the sacredness of the sacerdotal office," both the higher and lower ranks of clergy were held in the utmost contempt-not unlike the popular attitude toward politicians and bureaucrats today. [^5]

We believe that much can be learned by analogy between the situation at the end of the fifteenth century, when life had become thoroughly saturated by organized religion, and the situation today, when the world has become saturated with politics. The costs of supporting institutionalized religion at the end of the fifteenth century had reached a historic extreme, much as the costs of supporting government have reached a senile extreme today.

We know what happened to organized religion in the wake of the Gunpowder Revolution. Technological developments created strong incentives to downsize religious institutions and lower their costs. A similar technological revolution is destined to downsize radically the nationstate early in the new millennium.
