# THE TRANSITION IN THE YEAR 2000

> "It feels like something big is about to happen: graphs show us the yearly growth of populations, atmospheric concentrations of carbon dioxide, Web addresses, and Mbytes per dollar. They all soar up to an asymptote just beyond the turn of the century: The Singularity. The end of everything we know. The beginning of something we may never understand" [^1] - Danny Hillis

## PREMONITIONS

The coming of the year 2000 has haunted the Western imagination for the past thousand years. Ever since the world failed to end at the turn of the first millennium after Christ, theologians, evangelists, poets, and seers have looked to the end of this decade with an expectation that it would bring something momentous. No less an authority than Isaac Newton speculated that the world would end with the year 2000. Michel de Nostradamus, whose prophecies have been read by every generation since they were first published in 1568, forecast the coming of the Third Antichrist in July 1999.[^2] Swiss psychologist Carl Jung, connoisseur of the "collective unconscious," envisioned the birth of a New Age in 1997. Such forecasts may easily be ridiculed. And so can the sober forecasts of economists, such as Dr. Edward Yardeni of Deutsche Bank Securities, who expects computer malfunctions on the millennial midnight to "disrupt the entire global economy."[^3] But whether you view the Y2K computer problem as groundless hysteria ginned up by computer programmers and Information Technology consultants to stir up business, or as a mysterious instance of technology unfulding in concert with the prophetic imagination, there is no denying that circumstances at the eve of the millennium excite more than the usual morbid doubt about where the world is tending.

A sense of disquiet about the future has begun to color the optimism so characteristic of Western societies for the past 250 years. People everywhere are hesitant and worried. You see it in their faces. Hear it in their conversation. See it reflected in polls and registered in the ballot box. Just as an invisible, physical change of ions in the atmosphere signals that a thunderstorm is imminent even before the clouds darken and lightning strikes, so now, in the twilight of the millennium, premonitions of change are in the air. One person after another, each in his own way, senses that time is running out on a dying way of life. As the decade expires, a murderous century expires with it, and also a glorious millennium of human accomplishment. All draw to a close with the year 2000.

> For there is nothing covered that shall not be revealed, neither hid that shall not be known." - Matthew 10:26

We believe that the modern phase of Western civilization will end with it. This book tells why. Like many earlier works, it is an attempt to see into a glass darkly, to sketch out the vague shapes and dimensions of a future that is still to be. In that sense, we mean our work to be apocalyptic in the original meaning of the word. Apokalypsis means "unveiling" in Greek. We believe that a new stage in history - the Information Age - is about to be "unveiled."

> We are watching the beginnings of a new logical space, an instantaneous electronic everywhereness, which we may all access, enter into, and experience. We have, in short, the beginnings of a new kind of community. The virtual community becomes the model for a secular Kingdom of Heaven; as Jesus said there were many mansions in his FAther's Kingdom, so there are many virtual communities, each reflecting their own needs and desires. - Michael Grasso[^4]

## THE FOURTH STAGE OF HUMAN SOCIETY

The theme of this book is the new revolution of power which is liberating individuals at the expense of the twentiethcentury nationstate. Innovations that alter the logic of violence in unprecedented ways are transforming the boundaries within which the future must lie. If our deductions are correct, you stand at the threshold of the most sweeping revolution in history. Faster than all but a few now imagine, microprocessing will subvert and destroy the nationstate, creating new forms of social organization in the process. This will be far from an easy transformation.

The challenge it will pose will be all the greater because it will happen with incredible speed compared with anything seen in the past. Through all of human history from its earliest beginnings until now, there have been only three basic stages of economic life. (1) hunting-and-gathering societies; (2) agricultural societies; and (3) industrial societies. Now, looming over the horizon, is something entirely new, the fourth stage of social organization: information societies.

Each of the previous stages of society has corresponded with distinctly different phases in the evolution and control of violence. As we explain in detail, information societies promise to dramatically reduce the returns to violence, in part because they transcend locality. The virtual reality of cyberspace, what novelist William Gibson characterized as a "consensual hallucination," will be as far beyond the reach of bullies as imagination can take it. If the new millennium, the advantage of controlling violence on a large scale will be far lower than it has been at any time since before the French Revolution. This will have profound consequences. One of these will be rising crime. When the payoff for organizing violence at a large scale tumbles, the payoff from violence at a smaller scale is likely to jump. Violence will become more random and localized. Organized crime will grow in scope. We explain why.

Another logical implication of falling returns to violence is the eclipse of politics. There is much evidence that adherence to the civic myths of the twentiethcentury nationstate is rapidly eroding. The death of Communism is merely the most striking example. As we explore in detail, the collapse of morality and growing corruption among leaders of Western governments is not a random development. It is evidence that the potential of the nationstate is exhausted. Even many of its leaders no longer believe the platitudes they mouth. Nor are they believed by others.

### History Repeats Itself

This is a situation with striking parallels in the past. Whenever technological change has divorced the old forms from the new moving forces of the economy, moral standards shift, and people begin to treat those in command of the old institutions with growing disdain. This widespread revulsion often comes into evidence well before people develop a new coherent ideology of change. So it was in the late fifteenth century, when the medieval Church was the predominant institution of feudalism. Notwithstanding popular belief in "the sacredness of the sacerdotal office," both the higher and lower ranks of clergy were held in the utmost contempt-not unlike the popular attitude toward politicians and bureaucrats today. [^5]

We believe that much can be learned by analogy between the situation at the end of the fifteenth century, when life had become thoroughly saturated by organized religion, and the situation today, when the world has become saturated with politics. The costs of supporting institutionalized religion at the end of the fifteenth century had reached a historic extreme, much as the costs of supporting government have reached a senile extreme today.

We know what happened to organized religion in the wake of the Gunpowder Revolution. Technological developments created strong incentives to downsize religious institutions and lower their costs. A similar technological revolution is destined to downsize radically the nationstate early in the new millennium.

> Today, after more than a century of electronic technology, we have extended our central nervous system itself in a global embrace, abolishing both space and time as far as our planet is concerned.[^6]

### The Information Revolution

As the breakdown of large systems accelerates, systematic compulsion will recede as a factor shaping economic life and the distribution of income. Efficiency will rapidly become more important than the dictates of power in the organization of social institutions. This means that provinces and even cities that can effectively uphold property rights and provide for the administration of justice, while consumding few resources, will be viable sovereignties in the Information Age, as they generally have not been during the last five centures. An entirely new realm of economic activity that is not hostage to physical violence will emerge in cyberspace. The most obvious benefits will flow to the "cognitive elite," who will increasingly operate outside political boundaries. They are already equally home in Frankfurt, London, New York, Buenos Aires, Los Angeles, Tokyo, and Hong Kong. Incomes will become more unequal within jurisdictions and more equal between them.

The Sovereign Individual explores the social and financial consequences of this revolutionary change. Our desire is to help you to take advantage of the opportunities of the new age and avoid being destroyed by its impact. If only half of what we expect to see happens, you face change of a magnitude with few precedents in history.

The transformation of the year 2000 will not only revolutionize the character of the world economy, it will do so more rapidly than any previous phase change. Unlike the Agricultural Revolution, the Information Revolution will not take millennia to do its work. Unlike the Industrial Revolution. its impact will not be spread over centuries. The Information Revolution will happen within a lifetime.

What is more, it will happen almost everywhere at once. Technical and economic innovations will no longer be confined to small portions of the globe. The transformation will be all but universal. And it will involve a break with the past so profound that it will almost bring to life the magical domain of the gods as imagined by the early agricultural peoples like the ancient Greeks. To a greater degree than most would now be willing to concede, it will prove difficult or impossible to preserve many contemporary institutions in the new millennium. When information societies take shape they will be as different from industrial societies as the Greece of Aeschylus was from the world of the cave dwellers.

## PROMETHEUS UNBOUND: THE RISE OF THE SOVEREIGN INDIVIDUAL

> I know of no more encouraging fact than the unquestionable ability of man to elevate his life by conscious endeavour - Henry David Thoreau

The coming transformation is both good news and bad. The good news is that the Information Revolution will liberate individuals as never before. For the first time, those who can educate themselves will be almost entirely free to invent their own work and realize the full benefits of their own productivity. Genius will be unleashed, freed from both the oppression of government and the drags of racial and ethnic prejudice. In the Information Society, no one who is truly able will be detained by the ill-formed opinions of others. It will not matter what most of the people on earth might think of your race, your looks, your age, your sexual proclivities, or the way you wear your hair. In the cybereconomy, they will never see you. The ugly, the fat, the old, the disabled will vie with the young and beautiful on equal terms in utterly color-blind anonymity on the new frontiers of cyberspace.

### Ideas Become Wealth

Merit, wherever it arises, will be rewarded as never before. In an environment where the greatest source of wealth will be the ideas you have in your head rather than physical capital alone, anyone who thinks clearly will potentially be rich. The Information Age will be the age of upward mobility. It will afford far more equal opportunity for the billions of humans in parts of the world that never shared fully in the prosperity of industrial society. The brightest, most successful and ambitious of these will emerge as truly Sovereign Individuals.

At first, only a handful will achive full financial sovereignty. But this does not negate the advantages of financial independence. The fact that not everyone attains an equally vast fortune does not mean that it is futile or meaningless to become rich. There are 25,000 millionaires for every billionaire. If you are a millionaire and not a billionaire, that does not make you poor. Equally, in the future, one of the milestones by which you measure your financial success will be not just how many zeroes you can add to your net worth, but whether you can structure your affairs in a way that enables you to realize full individual autonomy and independence. The more clever you are, the less propulsion you will require to achieve financial escape velocity. Persons of even quite modest means will soar, as the gravitational pull of politics on the global economy weakens. Unprecedented financial independence will be a reachable goal in your lifetime or that of your children.

At the highest plateau of productivity, these Sovereign Individuals will compete and interact on terms that echo the relations among the gods in Greek myth. The elusive Mount Olympus of the next millennium will be in cyberspace-a realm without physical existence that will nonetheless develop what promises to be the world's largest economy by the second decade of the new millennium. By 2025, the cybereconomy will have many millions of participants. Some of them will be as rich as Bill Gates, worth over $10 billion each. The cyberpoor may be those with an income of less than $200,000 a year. There will be no cyberwelfare. No cybertaxes and no cybergovernment. The cybereconomy, rather than China, could well be the greatest economic phenomenon of the next thirty years.

The good news is that politicians will no more be able to dominate, suppress, and regulate the greater part of commerce in this new realm than the legislators of the ancient Greek city-states could have trimmed the beard of Zeus. That is good news for the rich. And even better news for the not so rich. The obstacles and burdens that politics imposes are more obstacles to becoming rich than to being rich. The benefits of declining returns to violence and devolving jurisdictions will create scope for every energetic and ambitious person to benefit from the death of politics. Even the consumers of government services will benefit as entrepreneurs extend the benefits of competition. Consequently, much of the ingenuity of interjurisdictional competition was channeled into military endeavor. But the advant of the cybereconomy will bring competition on new terms to provision of sovereignty services. A proliferation of jurisdictions will mean proliferating experimentation in new ways of enforcing contracts and otherwise securing the safety of persons and property. The liberation of a large part of the global economy from political control will oblige all remaining forms of government to operate on more nearly market terms. They will ultimately have little choice but to treat populations in territories they serve more like customers, and less in the way that organized criminals treat the victims of a shakedown racket.

### Beyond Politics

What mythology described as the province of the gods will become a viable option for the individual -- a life outside the reach of kings and councils. First in scores, then in hundreds, and ultimately in the millions, individuals will escape the shackles of politics. As they do, they will transform the character of governments, shrinking the realm of compulsion and widening the scope of private control over resources.

The emergence of the sovereign individual will demonstrate yet again the strange prophetic power of myth. Conceiving little of the laws of nature, the early agricultural peoples imagined that "powers we should call supernatural" were widely distributed. These powers were sometimes employed by men, sometimes by "incarnate human gods" who looked like men and interacted with them in what Sir James George Frazer described in The Golden Bough as "a great democracy".[^7]

When the ancients imagined the children of Zeus living among them they were inspired by a deep belief in magic. They shared with other primitive agricultural peoples an awe of nature, and a superstitious conviction that nature's works were set in motion by individual volition, by magic. In that sense, there was nothing self-consciously prophetic about their view of nature and their gods. They were far from anticipating microtechnology. They could not have imagined its impact in altering the marginal productivity of individuals thousands of years later. They certainly could not have foreseen how it would shift the balance between power and efficiency and thus revolutionize the way that assets are created and protected. Yet what they imagined as they spun their myths has a strange resonance with the world you are likely to see.

### Alt.Abracadabra

The "abracadabra" of the magic invocation, for example. bears a curious similarity to the password employed to access a computer. In some respects, high-speed computation has already made it possible to mimic the magic of the genie. Early generations of "digital servants" already obey the commands of those who control the computers in which they are sealed much as genies were sealed in magic lamps. The virtual reality of information technology will widen the realm of human wishes to make almost anything that can be imagined seem real. Telepresence will give living individuals the same capacity to span distance at supernatural speed and monitor events from afar that the Greeks supposed was enjoyed by Hermes and Apollo. The Sovereign Individuals of the Information Age, like the gods of ancient and primitive myths, will in due course enjoy a kind of "diplomatic immunity" from most of the political woes that have beset mortal human beings in most times and places.

The new Sovereign Individual will operate like the gods of myth in the same physical environment as the ordinary, subject citizen, but in a separate realm politically. Commanding vastly greater resources and beyond the reach of many forms of compulsion, the Sovereign Individual will redesign governments and reconfigure economies in the new millennium. The full implications of this change are all but unimaginable.

### Genius and Nemesis

For anyone who loves human aspiration and success, the Information Age will provide a bounty. That is surely the best news in many generations. But it is bad news as well, The new organization of society implied by the triumph of individual autonomy and the true equalization of opportunity based upon merit will lead to very great rewards for merit and great individual autonomy. This will leave individuals far more responsible for themselves than they have been accustomed to being during the industrial period. It will also reduce the unearned advantage in living standards that has been enjoyed by residents of advanced industrial societies throughout the twentieth century. As we write, the top 15 percent of the world's population have an average per-capita income of $21,000 annually. The remaining 85 percent of the world have an average income of just $1,000. That huge, hoarded advantage from the past is bound to dissipate under the new conditions of the Information Age.

As it does, the capacity of nationstates to redistribute income on a large scale will collapse. Information technology facilitates dramatically increased competition between jurisdictions. When technology is mobile, and transactions occur in cyberspace, as they increasingly will do, governments will no longer be able to charge more for their services than they are worth to the people who pay for them. Anyone with a portable computer and a satellite link will be able to conduct almost any information business anywhere, and that includes almost the whole of the world's multitrillion-dollar financial transactions.

This means that you will no longer be obliged to live in a high-tax jurisdiction in order to earn high income. In the future, when most wealth can be earned anywhere, and even spent anywhere, governments that attempt to charge too much as the price of domicile will merely drive away their best customers. If our reasoning is correct, and we believe it is, the nationstate as we know it will not survive in anything like its present form.

## THE END OF NATIONS

Changes that diminish the power of predominant institutions are both unsettling and dangerous. Just as monarchs, lords, popes, and potentates fought ruthlessly to preserve their accustomed privileges in the early stages of the modern period, so today's governments will employ violence, often of a covert and arbitrary kind, in the attempt to hold back the clock. Weakened by the challenge from technology, the state will treat increasingly autonomous individuals, its former citizens, with the same range of ruthlessness and diplomacy it has heretofore displayed in its dealing with other governments. The advent of this new stage in history was punctuated with a bang on August 20, 1998, when the United States fired about $200 million worth of Tomahawk BGM-109 sea-launched cruise missiles at targets allegedly associated with an exiled Saudi millionaire, Osama bin Laden. Bin Laden became the first person in history to have his satellite phone targeted for attack by cruise missiles. Simultaneously, the United States destroyed a pharmaceutical plant in Khartoum, Sudan, in Bin Laden's honor. The emergence of Bin Laden as the enemy-in-chief of the United States reflects a momentous change in the nature of warfare. A single individual, albeit one with hundreds of millions of dollars, can now be depicted as a plausible threat to the greatest military power of the Industrial era. In statements reminiscent of propaganda employed during the Cold War about the Soviet Union, The United States president and his national security aides portrayed Bin Laden, a private individual, as a transnational terrorist and leading enemy of the United States.

The same military logic that has seen Osama bin Laden elevated to a position as chief enemy of the United States will assert itself in governments' internal relations with their subjects. Increasingly harsh techniques of exaction will be a logical corollary of the emergence of a new type of bargaining between governments and individuals. Technology will make individuals more nearly sovereign than ever before. And they will be treated that way. Sometimes violently, as enemies, sometimes as equal parties in negotiation, sometimes as allies. But however ruthlessly governments behave, particularly in the transition period, wedding the IRS with the CIA will avail them little. They will be increasingly required by the press of necessity to bargain with autonomous individuals whose resources will no longer be so easily controlled.

The changes implied by the Information Revolution will not only create a fiscal crisis for governments, they will tend to disintegrate all large structures. Fourteen empires have disappeared already in the twentieth century. The breakdown of empires is part of a process that will dissolve the nationstate itself. Government will have to adapt to the growing autonomy of the individual. Taxing capacity will plunge by 50~70 percent. This will tend to make smaller jurisdictions more successful. The challenge of setting competitive terms to attract able individuals and their capital will be more easily undertaken in enclaves than across continents.

We believe that as the modern nationstate decomposes, latter-day barbarians will increasingly come to exercise power behind the scenes. Groups like the Russian mafiya, which picks the bones of the former Soviet Union, other ethnic criminal gangs, nomenklaturas[^27], drug lords, and renegade covert agencies will be laws unto themselves. They already are. Far more than is widely understood, the modern barbarians have already infiltrated the forms of the nationstate without greatly changing its appearances. They are microparasites feeding on a dying system. As violent and unscrupulous as a state at war, these groups employ the techniques of the state on a smaller scale. Their growing influence and power are part of the downsizing of politics. Microprocessing reduces the size that groups must attain in order to be effective in the use and control of violence. As this technological revolution unfolds, predatory violence will be organized more and more outside of central control. Efforts to contain violence will also devolve in ways that depend more upon efficiency than magnitude of power.

### History in Reverse

The process by which the nationstate grew over the past five centuries will be put into reverse by the new logic of the Information Age. Local centers of power will reassert themselves as the state devolves into fragmented, overlapping sovereignties. [^8] The growing power of organized crime is merely one reflection of this tendency. Multinational companies are already having to subcontract all but essential work. Some conglomerates, such as AT&T, Unisys, and ITT, have split themselves into several firms in order to function more profitably. The nationstate will devolve like an unwieldy conglomerate, but probably not before it is forced to do so by financial crises.

Not only is power in the world changing, but the work of the world is changing as well. This means that the way business operates will inevitably change. The "virtual corporation" is evidence of a sweeping transformation in the nature of the firm, facilitaed by the drop in information and transaction costs. We explore the implications of the Information Revolution for dissolving corporations and doing away with the "good job." In the Information AGe, a "job" will be a task to do, not a position you "have." Microprocessing has created entirely new horizons of economic activity that transcend territorial boundaries. This transcendence of frontiers and territories is perhaps the most revolutionary development since Adam and Eve straggled out of paradise under the sentence of their Maker: "In the sweat of thy face shalt thou eat bread." As technology revolutionizes the tools we use, it also antiquates our laws, reshapes our morals, and alters our perceptions. This book explains how.

Microprocessing and rapidly improving communications already make it possible for the individual to choose where to work. Transactions on the Internet or the World Wide Web can be encrypted and will soon be almost impossible for tax collectors to capture. Tax-free money already compounds far faster offshore than onshore funds still subject to the high tax burden imposed by the twentiethcentury nationstate. After the turn of the millennium, much of the world's commerce will migrate into the new realm of cyberspace, a region where governments will have no more dominion than they exercise over the bottom of the sea or the outer planets. In cyberspace. the threats of physical violence that have been the alpha and omega of politics since time immemorial will vanish. In cyberspace, the meek and the mighty will meet on equal terms. Cyberspace is the ultimate offshore jurisdiction. An economy with no taxes. Bermuda in the sky with diamonds.

When this greatest tax haven of them all is fully open for business, all funds will essentially be offshore funds at the discretion of their owner. This will have cascading consequences. The state has grown used to treating its taxpayers as a farmer treats his cows, keeping them in a field to be milked. Soon, the cows will have wings.

### The Revenge of Nations

Like an angry farmer, the state will no doubt take desperate measures at first to tether and hobble its escaping herd. It will employ covert and even violent means to restrict access to liberating technologies. Such expedients will work only temporarily, if at all. The twentiethcentury nationstate, with all its pretensions, will starve to death as its tax revenues decline.

When the state finds itself unable to meet its committed expenditure by raising tax revenues, it will resort to other, more desperate measures. Among them is printing money. Governments have grown used to enjoying a monopoly over currency that they could depreciate at will. This arbitrary inflation has been a prominent feature of the monetary policy of all twentiethcentury states. Even the best national currency of the postwar period, the German mark, lost 71 percent of its value from January 1, 1949, through the end of June 1995. In the same period, the U.S. dollar lost 84 percent of its value.[^9] This inflation had the same effect as a tax on all who hold the currency. As we explore later, inflation as revenue option will be largely foreclosed by the emergence of cybermoney. New technologies will allow the holders of wealth to bypass the national monopolies that have issued and regulated money in the modern period.  Indeed, the credit crises that swept through Asia, Russia, and other emerging economies in 1997 and 1998 attest to the fact that national currencies and national credit ratings are anchronisms inimical to the smooth operation of the global economy. It is precisely the fact that the demands of sovereignty require all transactions within a jurisdiction to be denominated in a national currency that creates the vulnerability to mistakes by central bankers and attacks by speculators which precipitated deflationary crises in one jurisdiction after another. In the Information Age, individual will be able to use cybercurrencies and thus declare their monetary independence. When individuals can conduct their own monetary policies over the World Wide Web it will matter less or not at all that the state continues to control the industrial-era printing presses. Their importance for controlling the world's wealth will be transcended by mathematical algorithms that have no physical existence. In the new millennium, cybermoney controlled by private markets will supersede flat money issued by governments. Only the poor will be victims of inflation and ensuing collapses into deflation that are consequences of the artificial leverage which fiat money injects into the economy.

Lacking their accustomed scope to tax and inflate, governments, even in traditionally civil countries, will turn nasty. As income tax becomes uncollectable, older and more arbitrary methods of exaction will resurface. The ultimate form of withholding tax -- de facto or even overt hostage-taking will be introduced by governments desperate to prevent wealth from escaping beyond their reach. Unlucky individuals will find themselves singled out and held to ransom in an almost medieval fashion. Businesses that offer services that facilitate the realization of autonomy by individuals will be subject to infiltration, sabotage, and disruption. Arbitrary forfeiture of property, already commonplace in the United States, where it occurs five thousand times a week, will become even more pervasive. Governments will violate human rights, censor the free flow of information, sabotage useful technologies, and worse. For the same reasons that the late, departed Soviet Union tried in vain to suppress access to personal computers and Xerox machines, western governments will seek to suppress the cybereconomy by totalitarian means.

## RETURN OF THE LUDDITES

Such methods may prove popular among some population segments. The good news about individual liberation and autonomy will seem to be bad news to many who are not among the cognitive elite. The greatest resentment is likely to be centered among those of middle talent in currently rich countries. They particularly may come to feel that information technology poses a threat to their way of life. The beneficiaries of organized compulsion, including millions receiving income redistributed by governments, may [^9] resent the new freedom realized by Sovereign Individuals. Their upset will illustrate the truism that "where you stand is determined by where you sit."

> Sometimes I wondered how I could experience such deep misery over the fate of a handful of men I did not know, playing a game against another group of strangers in a ballpark hundreds of miles away. The answer is simple. I loved my teams. Although risky, caring was worth its price. Sports fired up my blood, excited me, made my heart pound. I liked having something at stake. Life was more vivid during a contenst. -- Craig Lambert

It would be misleading, however, to attribute all the bad feelings that will be generated in the coming transition crisis to the bald desire to live at someone else's expense. More will be involved. The very character of human society suggests that there is bound to be a misguided moral dimension to the coming Luddite reaction. Think of it as a bald desire fitted with a moral toupee. We explore the moral and moralistic dimensions of the transition crisis. Self-interested grasping of a conscious kind has far less power to motivate actions than does self-righteous fury. While adherence to the civic myths of the twentieth century is rapidly falling away, they are not without their true believers. Everyone who came of age in the twentieth century has been inculcated in the duties and obligations of the twentiethcentury citizen. The residual moral imperatives from industrial society will stimulate at least some neo-Luddite attacks on information technologies.

In this sense, this violence to come will be at least partially an expression of what we call "moral anachronism," the application of moral strictures drawn from one stage of economic life to the circumstances of another. Every stage of society requires its own moral rules to help individuals overcome incentive traps peculiar to the choices they face in that particular way of life. Just as a farming society could not live by the moral rules of a migratory Eskimo band, so the Information Society cannot satisfy moral imperatives that emerged to facilitate the success of a militant twentiethcentury industrial state. We explain why.

In the next few years, moral anachronism will be in evidence at the core countries of the West in much the way that it has been witnessed at the periphery over the past five centuries. Western colonists and military expeditions stimulated such crises when they encountered indigenous hunting-and-gathering bands, as well as peoples whose societies were still organized for farming. The introduction of new technologies into anachronistic settings caused confusion and moral crises. The success of Christian missionaries in converting millions of indigenous peoples can be laid in large measure to the local crises caused by the sudden introduction of new power arrangements from the outside. Such encounters recurred over and over, from the sixteenth century through the early decades of the twentieth century. We expect similar clashes early in the new millennium as Information Societies supplant those organized along industrial lines.

### The Nostalgia for Compulsion

The rise of the Sovereign Individual will not be wholly welcomed as promising new phase of history, even among those who benefit from it most. Everyone will feel some misgivings. And many will despise innovations that undermine the territorial nationstate. It is a fact of human nature that radical change of any kind is almost always seen as a dramatic turn for the worse. Five hundred years ago, the courtiers gathered around the duke of Burgundy would have said that unfolding innovations that undermined feudalism were evil. They thought the world was rapidly spiraling downhill at the very time that later historians saw an explosion of human potential in the Renaissance. Likewise, what may someday be seen as a new Renaissance from the perspective of the next millennium will look frightening to tired twentieth century eyes.

There is a high probability that some who are offended by the new ways as well as many who are disadvantaged by them, will react unpleasantly. Their nostalgia for compulsion will probably turn violent. Encounters with these new "Luddites" will make the transition to radical new forms of social organization at least a measure of bad news for everyone. Get ready to duck. With the speed of change outracing the moral and economic capacity of many in living generations to adapt, you can expect to see a fierce and indignant resistance to the Information Revolution, notwithstanding its great promise to liberate the future.

You must understand and prepare for such unpleasantness. A transition crisis lies ahead. Deflationary tribulations, such as the Asian contagion that swept through the Far East to Russia and other emerging economies in 1997 and 1998, will erupt sporadically as the dated national and international institution left over from the Industrial Era prove inadequate to the challenges of the new, dispersed, transnational economy. The new information and communication technologies are more subversive of the modern state than any political threat to its predominance since Columbus sailed. This is important because those in power have seldom reacted peacefully to developments that undermined their authority. They are not likely to now.

The clash between the new and the old will shape the early years of the new millennium. We expect it to be a time of great danger and great reward and a time of much diminished civility in some realms and unprecedented scope in others. Increasingly autonomous individuals and bankrupt, desperate governments will confront one another across a new divide. We expect to see a radical restructuring of the nature of sovereignty and the virtual death of politics before the transition is over instead of state domination and control of resources, you are destined to see the privatization of almost all services governments now provide. For inescapable reasons that we explore at length in this book, information technology will, destroy the capacity of the state to charge more for its services than they are worth to the people who pay for them.

> Governments will have to deal with what sovereignty means. -- Robert Martin

### Sovereignty Through Markets

To an extent that few would have imagined only a decade ago, individuals will achieve increasing autonomy over territorial nationstates through market mechanisms. All nationstates face bankruptcy and the rapid erosion of their authority. Mighty as they are, the power they retain is the power to obliterate, not to command. Their intercontinental missiles and aircraft carriers are already artifacts, as imposing and useless as the last warhorse of feudalism.

Information technology makes possible a dramatic extension of markets by altering the way that assets are created and protected. This is revolutionary indeed, it promises to be more revolutionary for industrial society than the advent of gunpowder proved to be for feudal agriculture. The transformation of the year 2000 implies the [^11] commercialization of sovereignty and the death of politics, no less than guns implied the demise of oath-based feudalism. Citizenship will go the way of chivalry.

We believe that the age of individual economic sovereignty is coming. Just as steel mills, telephone companies, mines, and railways that were once "nationalized" have been rapidly privatized throughout the world, you will soon see the ultimate form of privatization--the sweeping denationalization of the individual. The Sovereign Individual of the new millennium will no longer be an asset of the state, a de facto item on the treasury's balance sheet. After the transition of the year 2000, denationalized citizens will no longer be citizens at all, but customers.

### BANDWIDTH TRUMPS BORDERS

The commercialization of sovereignty will make the terms and conditions of citizenship in the nationstate as dated as chivalric oaths seemed after the collapse of feudalism. Instead of relating to a powerful state as citizens to be taxed, the Sovereign Individuals of the twenty-first century will be customers of governments operating from a "new logical space". They will bargain for whatever minimal government they need and pay for it according to contract. The governments of the Information Age will be organized along different principles than those which the world has come to expect over the past several centuries. Some jurisdictions and sovereignty services will be formed through "assortive matching," a system by which affinities, including commercial affinities, are the basis upon which virtual jurisdictions earn allegiance. In rare cases, the new sovereignties may be holdovers of medieval organizations, like the 900-year-old Sovereign Military Hospitaller Order of St. John of Jerusalem, of Rhodes and of Malta. More commonly known as the Knights of Malta, the order is an affinity group for rich Catholics, with 10,000 current members and an annual income of several billions. The Knights of Malta issues its own passports, stamps, and money, and carries on full diplomatic relations with seventy countires. As we write it is negotiating with the Republic of Malta to reassume possession of Fort St. Angelo. Taking possession of the castle would give the Knights the missing ingredient of territoriality that will enable it to be recognized as a sovereignty. The Knights of Malta could once again become a sovereign microstate, instantly legitimized by a long history. It was from Fort St. Angelo that the Knights of Malta turned back the Turks in the Great Siege of 1565. Indeed, they ruled Malta for many years thereafter, until they were expelled by Napolean in 1798. If the Knights of Malta were to return in the next few years, there could be no clearer evidence that the modern nationstate system, ushered in after the French Revolution, was merely an interlude in the longer sweep of history in which it has been the norm for many kinds of sovereignties to exist at the same time.

Still another and very different model for a postmodern sovereignty based on assortive matching is the Iridium satellite telephone network. At first glance, you may think it odd to treat a cellular telephone service as a kind of sovereignty. Yet Iridium has already received recogniztion as a virtual sovereignty by international authorities. As you may know, Iridium is a global cellular phone service that allows subscribers to receive calls on a single numbers, wherever they find themselves on the planet, from Featherston, New Zealand, to the Bolivian Chaco. To allow calls to be routed to Iridium subscribers anywhere on the globe, given the architecture of global telecoms, international telecom authorities had to agree to recognize Iridium as a virtual country, with its own country code: 8816. It is a short step logically from a virtual country coprising sattelite telephone subscribers to sovereignty for more coherent virtual communities on the World Wide Web that span borders. Bandwidth, or the carrying capacity of a communications medium, has been expanding faster than computational capacity multiplied after the invention of transistors. If this trend to greater bandwidth continues, as we believe likely, it is only a matter of a few years, soon after the turn of the millennium, until bandwidth becomes sufficiently capacious to make technically possible, the "metaverse," the alternative, cyberspace world imagined by the science fiction novelist Neal Stephenson. Stephenson's "metaverse" is a dense virtual community with its own laws. We believe it is inevitable that, as the cybereconomy becomes richer, its participants will seek and obtain exemption from the anachronistic laws of nation-states. The new cybercommunities will be at least as wealthy and competent at advancing their interests as the Sovereign Military Hospitaller Order of St. John of Jerusalem, of Rhodes and of Malta. Indeed, they will be more capable of asserting themselves because of far-reaching communications and information warfare capabilities. We explore still other models of fragmented sovereignty in which small groups can effectively lease the sovereignty of weak nation-states, and operate their own economic havens much as free ports and free trade zones are licensed to do today.

A new moral vocabulary will be required to describe the relations of Sovereign Individuals with one another and what remains of government. We suspect that as the terms of these new relations come into focus, they will offend many people who came of age as "citizens" of twentiethcentury nationstates. The end of nations and the "denationalization of the individual" will deflate some warmly held notions, such as "equal protection under the law" that presuppose power relations that are soon to be obsolete. As virtual communities gain coherence, they will insist that their members be held accountable according to their own laws, rather than those of the former nation-states in which they happen to reside. Multiple systems of law will again coexist over the same geographic area, as they did in ancient and medieval times.

Just as attempts to preserve the power of knights in armor were doomed to fail in the face of gunpowder weapons, so the modem notions of nationalism and citizenship are destined to be short-circuited by microtechnology. Indeed, they will eventually become comic in much the way that the sacred principles of fifteenth-century feudalism fell to ridicule in the sixteenth century. The cherished civic notions of the twentieth century will be comic anachronisms to new generations after the transformation of the year 2000. The Don Quixote of the twenty-first century will not be a knight-errant struggling to revive the glories of feudalism but a bureaucrat in a brown suit, a tax collector yearning for a citizen to audit.

## REVIVING LAWS OF THE MARCH

We seldom think of governments as competitive entities, except in the broadest sense, so the modern intuition about the range and possibilities of sovereignty has atrophied. In the past, when the power equation made more difficult for groups to assert a stable monopoly of coercion, power was frequently fragmented, jurisdictions overlapped, and entities of many different kinds exercised one or more of the attributes of sovereignty. Not infrequently, the nominal overlord actually enjoyed scant power on the ground. Governments weaker than the nationstates are now faced with sustained competition in their ability to impose a monopoly of coercion over a local territory. This competition gave rise to adaptations in controlling violence and attracting allegiance that will soon be new again.

When the reach of lords and kings was weak, and the claims of one or more groups overlapped at a frontier, it frequently happened that neither could decisively dominate the other. In the Middle Ages, there were numerous frontier or "march" regions where sovereignties blended together. These violent frontiers persisted for decades or even centuries in the border areas of Europe. There were marches between areas of Celtic and English control in Ireland; between Wales and England, Scotland and England, Italy and France, France and Spain, Germany and the Slav frontiers of Central Europe and between the Christian kingdoms of Spain and the Islamic kingdom of Granada. Such march regions developed distinct institutional and legal forms of a kind that we are likely to see again in the next millennium. Because of the competitive position of the two authorities, residents of march region seldom paid tax. What is more, they usually had a choice in deciding who's laws they were to obey, a choice that was exercised through such legal concepts as "avowal" and "distraint" that have now all but vanished. We expect such concepts to become a prominent feature of the law of Information Societies.

### Transcending Nationality

Before the nation-state, it was difficult to enumerate precisely the number of sovereignties that existed in the world because they overlapped in complex ways and many varied forms of organization exercised power. They will do so again. The dividing lines between territories tended to become clearly demarcated and fixed as borders in the nationstate system. They will become hazy again in the Information Age. In the new millennium, sovereignty will be fragmented once more. New entities will emerge exercising some but not all of the characteristics we have come to associate with governments.

Some of these new entities, like the Knights Templar and other religious military orders of the Middle Ages, may control considerable wealth and military power without controlling any fixed territory. They will be organized on principles that bear no relation to nationality at all. Members and leaders of religious corporations that exercised sovereign authority in parts of Europe in the Middle Ages in no sense derived their authority from national identity. They were of all ethnic backgrounds and professed to owe their allegiance to God, and not to any affinities that members of a nationality are supposed to share in common.

### Merchant Republics of Cyberspace

You will also see the reemergence of associations of merchants and wealthy individuals with semisovereign powers, like the Hanse (confederation of merchants) in the Middle Ages. The Hanse that operated in the French and Flemish fairs grew to encompass the merchants of sixty cities.[^10] The "Hanseatie League," as it is redundantly known in English (the literal translation is "Leaguely League"), was an organization of Germanic merchant guilds that provided protection to members and negotiated trade treaties. It came to exercise semisovereign powers in a number of Northern European and Baltic cities. Such entities will reemerge in place of the dying nationstate in the new millennium, providing protection and helping to enforce contracts in an unsafe world.

In short, the future is likely to confound the expectations of those who have absorbed the civic myths of twentiethcentury industrial society. Among them are the illusions of social democracy that once thrilled and motivated the most gifted minds. They presuppose that societies evolve in whatever way governments wish them to; preferably in response to opinion polls and scrupulously counted votes. This was never as true as it seemed fifty years ago. Now it is an anachronism, as much an artifact of industrialism as a rusting smokestack. The civic myths reflect not only a mindset that sees society's problems as susceptible to engineering solutions; they also reflect a false confidence that resources and individuals will remain as vulnerable to political compulsion in the future as they have been in the twentieth century. We doubt it. Market forces, not political majorities, will compel societies to reconfigure themselves in ways that public opinion will neither comprehend nor welcome. As they do, the naive view that history is what people wish it to be will prove wildly misleading.

It will therefore be crucial that you see the world anew. That means looking from the outside in to reanalyze much that you have probably taken for granted. This will enable you to come to a new understanding. If you fail to transcend conventional thinking at a time when conventional thinking is losing touch with reality, then you will be more likely to fall prey to an epidemic of disorientation that lies ahead. Disorientation breeds mistakes that could threaten your business, your investments, and your way of life.

> The universe rewards us for understanding it and punishes us for not understanding it. When we understand the universe, our plans work and we feel good. Conversely, if we try to fly by jumping off a cliff and flapping our arms, the universe will kill us.[^11] -- JACK COHEN AND IAN STEWART

### Seeing Anew

To prepare yourself for the world that is coming you must understand why it will be different from what most experts tell you. That involves looking closely at the hidden causes of change. We have attempted to do this with an unorthodox analysis we call the study of megapolitics. In two previous volumes, Blood in the Streets and *The Great Reckoning*, we argued that the most important causes of change are not to be found in political manifestos or in the pronouncements of dead economists, but in the hidden factors that alter the boundaries where power is exercised. Often, subtle changes in climate, topography, microbes, and technology alter the logic of violence. They transform the way people organize their livelihoods and defend themselves.

Notice that our approach to understanding how the world changes is very different from that of most forecasters. We are not experts in anything, in the sense that we pretend to know a great deal more about certain "subjects" than those who have spent their entire careers cultivating highly specialized knowledge. To the contrary, we look from the outside in. We are knowledgeable around the subjects about which we make forecasts. Most of all, this involves seeing where the boundaries of necessity are drawn. When they change, society necessarily changes, no matter what people may wish to the contrary.

In our view, the key to understanding how societies evolve is to understand factors that determine the costs and rewards of employing violence, Every human society, from the hunting band to the empire, has been informed by the interactions of megapolitical factors that set the prevailing version of the "laws of nature." Life is always and everywhere complex. The lamb and the lion keep a delicate balance, interacting at the margin. If lions were suddenly more swift, they would catch prey that now escape. If lambs suddenly grew wings, lions would starve. The capacity to utilize and defend against violence is the crucial variable that alters life at the margin.

We put violence at the center of our theory of megapolitics for good reason. The control of violence is the most important dilemma every society faces. As we wrote in *The Great Reckoning*:

> The reason that people resort to violence is that it often pays. In some ways, the simplest thing a man can do if he wants money is to take it. That is no less true for an army of men seizing an oil field than it is for a single thug taking a wallet. Power, as William Playfair wrote, "has always sought the readiest road to wealth, by attacking those who were in possession of it."
> The challenge to prosperity is precisely that predatory violence does pay well in some circumstances. War does change things. It changes the rules. It changes the distribution of assets and income. It even determines who lives and who dies. It is precisely the fact that violence does pay that makes it hard to control.[^12]

Thinking in these terms has helped us foresee a number of developments that better-informed experts insisted could never happen. For example, Blood in the Streets, published in early 1987, was our attempt to survey the first stages of the great megapolitical revolution now under way. We argued then that technological change was destabilizing the power equation in the world. Among our principal points:

- We said that American predominance was in decline, which would lead to economic imbalances and distress, including another 1929-style stock market crash. Experts were all but unanimous in denying that such a thing could happen. Yet within six months, in October 1987, would markets were convulsed by the most violentsell-off of the century.

- We told readers to expect the collapse of Communism. Again, experts laughed. Yet 1989 brought the events that "no one could have predicted." The Berlin Wall fell, as revvolutions swept away Communist regimes from the Baltic to Bucharest.

- We explained why the multiethnic empire that the Bolshevik nomenklatura inherited form the tsars would "inevitably crack apart." At the end of December 1991, the hammer-and-cycle banner was lowered over the Kremlin for the last time as the Soviet Union ceased to exist.

- During the height of the Reagan arms buildup, we argued that the world stood at the threshold of sweeping disarmament. This, too, was considered unlikely, if not preposterous. Yet the following seven years brought the most sweeping disarmament since the close of World War I.

- At a time when experts in North America and Europe were pointing to Japan for support of the view that governments can successfully rig markets, we said otherwise. We forecast that the Japanese financial assets boom would end in a bust. Soon after the fall of the Berlin Wall, the Japanese stock market crashed, losing almost half its value. We continue to believe that its ultimate low could match or exceed the 89 percent loss that Wall Street suffered at the bottom after 1929.

- At a point when almost everyone, from the middle-class family to the world's largest real estate investors, appeared to believe that property markets could only rise and not fall, we warned that a real estate bust was in the offing. Within four years, real estate investors throughout the world lost more than $1 trillion as property values dropped.

- Long before it was obvious to the experts, we explained in *Blood in the Streets* that the income of blue-collar workers had decreased and was destined to continue falling on a long-term basis. As we write today, almost a decade later, it has at last begun to dawn on a sleepy world that this is true. Average hourly wages in the United States have fallen below those achieved in the second Eisenhower administration. In 1993, average annualized hourly wages in constant dollars were $18,808. In 1957, when Eisenhower was sworn in for his second term, U.S, annualized average hourly wages were $18,903.

While the main themes of *Blood in the Streets* have proven remarkably accurate with the benefit of hindsight, only a few years ago they were considered rank nonsense by the guardians of conventional thinking. A reviewer in *Newsweek* in 1987 reflected the closed mental climate of late industrial society when he dismissed our analysis as "an unthinking attack on reason."

You might imagine that *Newsweek* and similar publications would have recognized with the passage of time that our line of analysis had revealed something useful about the way the world was changing. Not a bit, The first edition of *The Great Reckoning* was greeted with the same sniggering hostility that welcomed *Blood in the Streets*. No less an authority than the *Wall Street Journal* categorically dismissed our analysis as the nattering of "your dopey aunt."

This chuckling aside, the themes of *The Great Reckoning* proved less ludicrous than the guardians of orthodoxy pretended.

& We extended our forecast of the death of the Soviet Union, exploring why Russia and the other former Soviet republics faced a future of growing civil disorder hyperinflation, and falling living standards.

- We explained why the 1 990s would be a decade of downsizing, including for the first time a worldwide downsizing of governments as well as business entities.

- We also forecast that there would be a major redefinition of terms of income redistribution, with sharp cutbacks in the level of benefits. Hints of fiscal crisis appeared from Canada to Sweden, and American politicians began to talk of "ending welfare as we know it."

- We anticipated and explained why the "new world order" would prove to be a "new world disorder." Well before the atrocities in Bosnia engrossed the headlines, we warned that Yugoslavia would collapse into civil war.

- Before Somalia slid into anarchy, we explained why the pending collapse of governments in Africa would lead some countries there to be effectively placed into receivership.

- We forecast and explained why militant Islam would displace Marxism as the principal ideology of confrontation with the West. Years before the Oklahoma bombing and the attempt to blow up the World Trade Center, we explained why the United States faced an upsurge in terrorism.

- Before the headlines that told of the rioting that swept Los Angeles, Toronto, and other cities, we explained why the emergence of criminal subcultures among urban minorities was setting the stage for widespread criminal violence.

- We also anticipated "the final depression of the twentieth century," which began in Asia in 1989 and has been spreading back from the periphery toward the center of the global system. We said that the Japanese stock market would follow Wall Street's path after 1929, and that this would lead to credit collapse and depression. Although massive government intervention in Japan and elsewhere temporarily prevented markets from fully reflecting the deterioration of credit conditions, this only displaced and compounded economic distress, building pressures for competitive devaluations and a systemic credit collapse of the kind that imploded economies worldwide in the 1930s.

*The Great Reckoning* also spelled out a number of controversial theses that have not yet been confirmed, or have not reached the level of development that we forecast:

- We said that the Japanese stock market would follow Wall Street's path after 1929, and that this would lead to credit collapse and depression. Although unemployment rates in Spain, Finland, and a few other countries exceeded those of the 1930s, and a number of countries, including Japan, did experience local depressions, there has not yet been a systemic credit collapse of the kind that imploded economies worldwide in the 1930s.

- We argued that the breakdown of the command-and-control system in the former Soviet Union would lead to the spread of nuclear weapons into the hands of ministates, terrorists, and criminal gangs. To the world's good fortune, this has not come to pass, at least not to the degree that we feared. Press reports indicate that Iran purchased several tactical nuclear weapons on the black market, and German authorities foiled several attempts to sell nuclear materials. But there has been no announced deployment or use of nuclear weapons from the arsenals of the former Soviet Union.

- We explained why the "War on Drugs" was a recipe for subverting the police and judicial systems of countries where drug use is widespread, particularly the United States. With tens of billions of dollars in hidden monopoly profits piling up each year, drug dealers have the means as well as the incentive to corrupt even apparently stable countries. While the world media have carried occasional stories hinting at high-level penetration of the U.S. political system by drug money, the full story has not yet been told.

### Looking Where Others Don't

Notwithstanding the points where our forecasts were mistaken or seem mistaken in light of what is now known, the record stands to scrutiny. Much of what is likely to figure in future economic histories of the 1990s was forecast or anticipated and explained in *The Great Reckoning*. Many of our forecasts were not simple extrapolations or extensions of trends, but forecasts of major departures from what has been considered normal since World War II. We warned that the 1990s would be dramatically different from the previous five decades. Reading the news of 1991 through 1995, we see that the themes of *The Great Reckoning* were borne out almost daily.

We see these developments not as examples of isolated difficulties, trouble here, trouble there, but as shocks and tremors that run along the same fault line. The old order is being toppled by a megapolitical earthquake that will revolutionize institutions and alter the way thinking people see the world.

In spite of the central role of violence in determining the way the world works, it attracts surprisingly little serious attention. Most political analysts and economists write as if violence were a minor irritant, like a fly buzzing around a cake, and not the chef who baked it.

### Another Megapolitical Pioneer

In fact, there has been so little clear thinking about the role of violence in history that a bibliography of megapolitical analysis could be written on a single sheet of paper. In *The Great Reckoning*, we drew upon and elaborated arguments of an almost entirely forgotten classic of megapolitical analysis, William Playfair's An Enquiry into the Permanent Causes of the Decline and Fall of Powerful and Wealthy Nations, published in 1805. Were one of our departure points is the work of Frederic C. Lane. Lane was a medieval historian who wrote several penetrating essays on the role of violence in history during the1940s and 1950s. Perhaps the most comprehensive of these was "Economic Consequences of Organized Violence," which appeared in the Journal of Economic History in 1958. Few people other than professional economists and historians have read it, and most of them seem not to have recognized its significance. Like Playfair, Lane wrote for an audience that did not yet exist.

### Insights for the Information Age

Lane published his work on violence and the economic meaning of war well before the advent of the Information Age. He certainly was not writing in anticipation of microprocessing or the other technological revolutions now unfolding. Yet his insights into violence established a framework for understanding how society will be reconfigured in the Information Revolution.

The window Lane opened into the future was one through which he peered into the past. He was a medieval historian, and particularly a historian of a trading City, Venice, whose fortunes surged and sagged in a violent world. In thinking about how Venice rose and fell, his attention was attracted to issues that can help you understand the future. He saw the fact that how violence is organized and controlled plays a large role in determining "what uses are made of scarce resources.[^13]

We believe that Lane's analyses of the competitive uses of violence has much to tell us about how life is likely to change in the Information Age. But don't expect most people to notice, much less follow, so unfashionably abstract an argument. While the attention of the world is riveted on dishonest debates and wayward personalities, the meanderings of megapolitics continue almost unnoted. The average North American has probably lavished one hundred times more attention on 0. J. Simpson than he has on the new microtechnologies that are poised to antiquate his job and subvert the political system he depends on for unemployment compensation.

## THE VANITY OF WISHES

The tendency to overlook what is fundamentally important is not confined solely to the couch dweller watching television. Conventional thinkers of all shapes and sizes observe one of the pretenses of the nationstate-that the views people hold determine the way the world changes. Apparently sophisticated analysts lapse into explanations and forecasts that interpret major historical developments as if they were determined in a wishful way. A striking example of this type of reasoning appeared on the editorial page of the New York Times just as we were writing "Goodbye, NationState, Hello...What?," by Nicholas Colchester.[^14] Not only was the topic, the death of the nationstate, the very topic we are addressing, but its author presents himself as an excellent marker to illustrate how far removed our way of thinking is from the norm. Colehester is no simpleton. He wrote as editorial director of the Economist Intelligence Unit. If anyone should form a realistic view of the world it should be he. Yet his article clearly indicates in several places that "the coming of international government "is" now logically unstoppable."

Why? Because the nationstate is faltering and can no longer control economic forces.

In our view, this assumption verges on the absurd. To suppose that some specific new form of governance will emerge simply because another has failed is a fallacy. By that reasoning, Haiti and Zaire would long ago have had better government simply because what they had was so luminously inadequate.

Colchester's point of view; widely shared among the few who think about such things in North America and Europe, utterly fails to take into account the larger megapolitical forces that determine what types of political systems are actually viable. That is the focus of this book. When the technologies that arc shaping the new millennium are considered, it is far more likely that we will see not one world government, but microgovemment, or oven conditions approaching anarchy.

For every serious analysis of the role of violence in determining the rules by which everyone operates, dozens of books have been written about the intricacies of wheat subsidies, and hundreds more about arcane aspects of monetary policy. Much of this shortfall in thinking about the crucial issues that actually determine the course of history probably reflects the relative stability of the power configuration over the past several centuries. The bird that falls asleep on the back of a hippopotamus does not think about losing its perch until the hippo actually moves. Dreams, myths, and fantasies play a much larger role in informing the supposed social sciences than we commonly think.

This is particularly evident in the abundant literature of economic justice. Millions of words have been uttered and written about economic justice and injustice for each page devoted to careful analysis of how violence shapes society, and thus sets the boundaries within which economies must function. Yet formulations of economic justice in the modern context presuppose that society is dominated by an instrument of compulsion so powerful that it can take away and redistribute life's good things. Such power has existed for only a few generations of the modern period. Now it is fading away.

### Big Brother on Social Security

Industrial technology gave governments greater instruments of control in the twentieth century than ever before. For a time, it seemed inevitable that governments would become so effective at monopolizing violence as to leave little room for individual autonomy. Nobody at midcentury was looking forward to the triumph of the Sovereign Individual.

Some of the shrewdest observers of the mid-twentieth century became convinced on the evidence of the day that the tendency of the nationstate to centralize power would lead to totalitarian domination over all aspects of life. In George Orwell's *1984* (1949), Big Brother was watching the individual vainly struggle to maintain a margin of autonomy and self-respect. It appeared to be a losing cause. Friedrich von Hayek's *The Road to Serfdom* (1944) took a more scholarly view in arguing that freedom was being lost to a new form of economic control that left the state as the master of everything. These works were written before the advent of microprocessing, which has incubated a whole range of technologies that enhance the capacity of small groups and even individuals to function independently of central authority.

As shrewd as observers like Hayek and Orwell were, they were unduly pessimistic. History has unfolded its surprises. Totalitarian Communism barely outlasted the year 1984. A new form of serfdom may yet emerge in the next millennium if governments succeed in suppressing the liberating aspects of microtechnology. But it is far more likely that we will see unprecedented opportunity and autonomy for the individual. What our parents worried about may prove to be no problem at all. What they took for granted as fixed and permanent features of social life now seem destined to disappear. Wherever necessity sets boundaries to human choice, we adjust, and reorganize our lives accordingly.

### The Hazards of Forecasting

No doubt we put our small measure of dignity at risk in attempting to foresee and explain profound changes in the organization of life and the culture that binds it together. Most forecasts are doomed to make silly reading in the fullness of time. And the more dramatic the change they envision, the more embarrassingly wrong they tend to be. The world doesn't end. The ozone doesn't vanish. The coming Ice Age dissolves into global warming. Notwithstanding all the alarms to the contrary, there is still oil in the tank. Mr. Antrobus, the everyman of *The Skin of Our Teeth*, avoids freezing, survives wars and threatened economic calamities, and grows old ignoring the studied alarms of experts.

Most attempts to "unveil" the future soon turn out to be comic. Even where self-interest provides a strong incentive to clear thinking, forward vision is often myopic. In 1903, the Mercedes company said that "there would never be as many as 1 million automobiles worldwide. The reason was that it was implausible that as many as 1 million artisans worldwide would be trainable as chauffeurs."[^15]

Recognizing this should stop our mouths. It doesn't. We are not afraid to stand in line for a due share of ridicule. If we mistake matters greatly, future generations may laugh as heartily as they please, presuming anyone remembers what we said. To dare a thought is to risk being wrong. We are hardly so stiff and useless that we are afraid to err. Far from it. We would rather venture thoughts that might prove useful to you than suppress them out of apprehension that they might prove overblown or embarrassing in retrospect.

As Arthur C. Clarke shrewdly noted, the two overriding reasons why attempts to anticipate the future usually fall flat are "Failure of Nerve and Failure of Imagination."[^16] Of the two, he wrote, "Failure of Nerve seems to be the more common; it occurs when even given all of the relevant facts the would-be prophet cannot see that they point to an inescapable conclusion, Some of these failures are so ludicrous as to be almost unbelievable."[^17]

Where our exploration of the Information Revolution falls short, as it inevitably will, the cause will be due more to a lack of imagination than to a lack of nerve. Forecasting the future has always been a bold enterprise, one which properly excites skepticism. Perhaps time will prove that our deductions are wildly off the mark. Unlike Nostradamus, we do not pretend to be prophetic personalities. We do not foretell the future by stirring a wand in a bowl of water or by casting horoscopes. Nor do we write in cryptic verse. Our purpose is to provide you with a sober, detached analysis of issues that could prove to be of great importance to you.

We feel an obligation to set out our views, even where they seem heretical, precisely because they may not otherwise be heard. In the closed mental atmosphere of late industrial society, ideas do not traffic as freely as they should through the established media.

This book is written in a constructive spirit. It is the third we have written together, analyzing various stages of the great change now under way. Like Blood in the Streets and *The Great Reckoning*, it is a thought exercise. It explores the death of industrial society and its reconfiguration in new forms. We expect to see amazing paradoxes in the years to come. On the one hand, you will witness the realization of a new form of freedom, with the emergence of the Sovereign Individual. You can expect to see almost the complete liberation of productivity. At the same time, we expect to see the death of the modern nationstate. Many of the assurances of equality that Western people have grown to take for granted in the twentieth century are destined to die with it. We expect that representative democracy as it is now known will fade away, to be replaced by the new democracy of choice in the cybermarketplace. If our deductions are correct, the politics of the next century will be much more varied and less important than that to which we have become accustomed.

We are confident that our argument will be easy to follow, notwithstanding the fact that it leads through some territory that is the intellectual equivalent of the backwoods and bad neighborhoods. If our meaning is not entirely intelligible in places, that is not because we are being cute, or using the time-honored equivocation of those who pretend to foretell the future by making cryptic pronouncements. We are not equivocators. If our arguments are unclear, it is because we have failed the task of writing in a way that makes compelling ideas accessible. Unlike many forecasters, we want you to understand and even duplicate our line of thinking. It is based not upon psychic reveries or the gyrations of planets, but upon old-fashioned, ugly logic. For quite logical reasons, we believe that microprocessing will inevitably subvert and destroy the nationstate, creating new forms of social organization in the process. It is both necessary and possible for you to foresee at least some details of the new way of life that may be here sooner than you think.

### Ironies of a Future Foretold

For centuries, the end of this millennium has been seen as a pregnant moment in history. More than 850 years ago, St. Malachy fixed 2000 as the date of the Last Judgment. American psychic Edgar Cayce said in 1934 that the earth would shift on its axis in the year 2000, causing California to split in two and inundating New York City and Japan. A Japanese rocket scientist, Hideo Itokawa, announced in 1980 that the alignment of the planets in a "Grand Cross" on August 18, 1999, would cause widespread environmental devastation, leading to the end of human life on earth.'[^18]

Such visions of apocalypse make a plump target for ridicule. Alter all, the year 2000, while an imposing round number, is only an arbitrary artifact of the Christian calendar as adopted in the West. Other calendars and dating systems calculate centuries and millennia from different starting points. By the reckoning of the Islamic calendar, for example, A.D. 2000 will be the year 1378. As ordinary-sounding as a year can be. According to the Chinese calendar, which repeats itself every sixty years, A.D. 2000 is just another year of the dragon. It is part of a continuous cycle that extends millennia into the past. Yet there is more than theological investment in the year 2000. Its importance is undergirded not only by Christian tradition, but by the limitations of mid-century information technology. The so-called Y2K or year 2000 computer problem, a potentially devastating logic flaw in billions of lines of computer code, could approximate apocalyptic conditions by closing down essential elements of industrial society on the millennial midnight. Many computers and microprocessors use software preserved and recycled from the earliest days of computers, when memory space, at $600,000 per megabyte, was more valuable than gold. To save expensive space, the early programmers tracked dates with digit dates with only the last two numbers of the year. This convention of employing two-digit date fields was carried over into most software employed in mainframe computers, and even found wide use in personal computers and so-called embedded chips, microprocessors that are used to control amost everything, from VCRs to car ignition systems, security systems, telephones, the switching systems that control the telephone network, process and control systems in factorires, power plants, oil refines, chemical plants, pipelines and much more, Thus abbreviated into a two-digit field, the year 1999 would be "99." The trouble is what happens when 00 comes up for the year 2000. Many computers will read this as 1900. This may make it impossible for many unremediated computers and other digital devices to recognize the year 2000 in date fields.

The result will be a massive problem of data corruption that will provide an accidental illustration of a new potential for information warfare. In the Information Age, potential adversaries will be able to wreak havoc by detonating "logic bombs"that sabotage the functions of essential systems by corrupting the data upon which their functioning depends. As a military exercise, for example, you would not need to shoot down an airplane, if you could corrupt data crucial to its safe operation. Data corruption can do almost as much as physical weapons can to thwart the function of a modern society. That this has the potentially far-reaching consequences should be obvious on reflection. For example, the *Mail* of London reported on December 14, 1997, that airlines around the globe were planning to cancel hundreds of flights on January 1, 2000 out of fear that air traffic control systems could fail.[^19] Potential problems include not only the air traffic systems, but also date-sensitive functions built into the airplanes themselves. According to Boeing, many airplanes will require Y2K remediation. Many devices may have a problem if they try to log an event on an invalid date. The fly-by-wire computer-controlled systems that operate airplanes may malfunction if they are programmed to conclude that crucial maintenance was last performed in the year 1900. They may even go into an error loop and shut down.

The potentially lethal feedback effects of a logic time bomb that closes down noncompliant control sytems could make the turn of the millennium a memorable date for unpleasant reasons. Remember, you can be affected by many devices that go into an error loop and shut down even if you are lucky enough not to find yourself in midair when the new millennium begins.

You would be well advised to avoid an accident arising from non-Y2K compliant pacemakers, or simply inebriated millennial revelers, because if the pacemakers shut down, the phone system might also, so the ambulance might never come. Unless you live in Brazil or Ukraine, you are used to picking up the telephone or turning on the car phone and automatically getting a dial tone. Happily, you seldom have to concern yourself with the technical details of how the telephone system operates. But it turns out that phone network switches and routers are highly date dependent. All connections are logged to a date and time, which is crucial to calculating call duration for billing. If you happen to make a one-minute call at 11:59:30 on December 31, 1999, and at 12:00:00 the systems reads your call as having had a negative duration of more than 99 years, error loops and shutdowns are possible. While long-distance companies are spending great sums to upgrade their switches to make them year 2000 compliant, and local service providers presumably are too, if even a few smaller companies fail to comply and go down, the whole network could be affected. You will be lucky to get a dial tone on January 1, 2000.

In the words of the Y2K expert Peter de Jager, f we lose the ability to make a phone call, then we lose everything. We lose electronic fund transfers, we lose trading, we lose branch banking." And the follow-on consequences of Y2K failures could come to more than that.

Today, no one knows how pervasively crucial systems will crash because of the year 2000 problem. Embedded systems that cannot be reprogrammed but must be replaces if nonfunctional on date-sensitive basis are found in cards, trucks, and buses built after 1976. (Perhaps you won't be in an accident with vehicles driven by persons with noncompliant pacemakers, because their vehicles might not start.) Embedded systems are also widespread in all types of power plants, water and sewage systems, medical devices, military equipment, aircraft, offshore oil platforms, oil tankers, alarm systems, and elevators. While many assemblies of microprocessors perform no date-sensitive functions, they may nonetheless depend upon a clock, which may be Y2K senstive, for their internal operations.

## MAINFRAMES AND THE Y2K TIME BOMB

The large-scale command and control systems of government and major corporations that involve high transaction volumes on mainframe computers were the original focus of Y2K concern. Because they operate on big machines for which most software is decades old and mostly noncompliant, the original alarms about Y2K, first sounded by Peter de Jager early in the 1990s, have focused mainly on the need to upgrade operating systems for big, multiprocessing mainframes. Mr. de Jager voiced concern that there might not be enough programmers conversant with COBOL, the old mainframe language, to complete the necessary patches and reapirs to date-sensitive code, even if every company and government agency with a vulnerable system had begun a crash program several years ago. Since this has not happened, and many operators of date-sensitive information systems have only just begun to assess their vulnerability, you can predict with a high degree of confidence that many mainframe systems will not be prepared to operate smoothly into the year 2000.

This is certainly a major concern because there is really no alternative to computer processing as the economy is now structured. Most businesses that are large enough to require a mainframe to handle their transactions are dependent upon transaction volumes that could not be managed with old-fashioned nineteenth-century paperwork systems. If such businesses were forced to revert to shuffling paper they could expect to complete only a fraction of their normal transaction volume. The revenue shock from such a drop-off in business would endanger the survival of all but the most highly capitalized companies.

Almost everything related to money - invoicing, purchasing, and payroll systems, plus inventory controls and regulatory compliance - would be fouled up. Huge quantities of date would be lost as computers crash or spew out false data in response to the Y2K problem. In some cases, it would actually prove a blessing if systems crash immediately rather than corrupting their data on a compounding basis until massive malfunction draws attention to the problem. What happens to files when a backup utility copies files originating on 07/04/99 to an update on 01/04/00? Who knows? Will the computer interpret a payment made on January 4, "1900," for an insurance policy as a signal that the policy has been in default for a century, resulting in a canceled policy that is stricken from the file? Will banks and finance company computers seek to assess a hundred years of interest of loans that span the shift to the new millennium? Will your banks and brokerage firms retain accurate records of your account balances and give you timely access to your funds? These are just some of the interesting quandaries that you will confront because of the Y2K problem.

> "This is potentially the most destructive part of the year 2000 problem. This isn't the inconvenience part where your paycheck comes a few days late. This is the blood-in-the-streets part. - Dr. Leon Kappelman, Co-Chair Society For Information Management's Year 2000 Working Group

Also high on your list of concerns should be what happens if the electricity goes off because of Y2K-related malfunctions. Without electricity, even most systems that are not Y2K-impaired will not function: your refrigerator, your freezer, perhaps even your source of heat. Y2K compliance issues could effect safety-related access and control functions at nuclear power plants. For example, personnel at nuclear facilities wear dosimetry devices that measure the amount of radiation exposure they receive while in the plant. These devices are analyzed regularly, with the data on exposure amounts maintained on a computer system that controls personnel access to the facility. Obviously, if the controlling computers fail, they will make a hash of all the elaborate controls designed to insure safe operation and guarantee proper maintenance. But, more importantly, a Nuclear REgulatory Commission memo notes that many "non-safety-related, but important computer-based systems, primarily databases and data collection necessary for plant operation," are date sensitive.

The conventional generating plants are not less vulnerable to Y2K disruption. For one thing, coal-powered plants are susceptible to disruptions in the surface transporting system that brings the coal to the boilers. In the 1997-1998 winter heating season, operators of coal-fired electricity generation found themselves forced to reduce the output in some instances because of a slowdown in rail deliveries of Western coal arising from the merger of the Southern Pacific and Union Pacific railway systems. The problem arose because of incompatibilities between the computer control and dispatch systems employed by the two railroads. According to a Union Pacific spokesman, integrating the two systems became a "nightmare," in spite of the fact that Union Pacific Technologies has been considered an industry leader in developing computerized transportation control systems. As a result of the programming difficulties, the railroad was unable to accurately track the movements of its freight cars. The failure of Union Pacific to master the assimilation of Southern Pacific is a bad omen about what could happen when Y2K logic time bombs disrupt transportation, power generation, and other aspects of the economy.

The biggest worry about the electric grid, however, arises from the fact that the whole system is subject to sensitive monitoring and computer control to transfer electricty from areas of surplus generation to those with a deficit. This process must be carefully monitored by computer to prevent power surges and system failures. All the transfers of electricity are logged to time and date for duration, much like a telephone connection. While heavy-duty mechanical relays are used to make the connections, they are controlled by computer systems. These computer controls, essential for load balancing, may fail for the same reasons as the phone networks. In fact, the power load distribution-control systems in North America are networked together through T-1 lines and telephone microwave links. So if the phone network fails, you can expect the electricity to go down as well. And remember, as the experience in Canada in January 1998 confirms, once the electricity shuts down over a wide area, getting the system running again is a challenge. A blackout may last for an inconveniently long time.

## Y2K AND THE NUCLEAR ARSENAL

For modern economies to have the electricity turn off in the dead of winter would be disruptive and potentially health threatening, especially for those who depend upon electric heat and medical equipment. Yet the worst case scenario is even worse. According to John Koskinen, who heads President Clinton's Y2K Conversion Council, U.S. military arsenals may cease to function on the stroke of midnight, December 31, 1999. While indicating that he does not wish to touch off undue alarm, Koskinen adds, "It needs to be worried about." One concern about nuclear missiles "is if the data doesn't function and they actually go off."

Of course, this concern would apply with equal or greater force to Russian nuclear missiles. Russia's bankruptcy has made upgrades for Y2K compliance even more problematic than in the United States. And there is evidence that Russia is not yet taking Y2K conversion seriously. While one would pray that no accidental launches would occur, there should be little doubt that the turn of the year 2000 has a potential for aggravating global insecurity if for no other reason than that military communications systems in many countries may not function normally. As Koskinen puts it, "If you're sitting in a country and suddenly you can't quite figure out exactly what's happening, and your communications don't work as well, you get even more nervous." So put that on your list of Y2K worries. The logic time bomb could precipitate the launch of genuinely explosive bombs - a fact that highlights the danger from information warefare to centralized command and control systems.

If terrorists wish to strike any centralized system, they may pick December 31, 1999, as the date for action because it will be a time of maximum vulnerability of many systems. Not only will communications be strained at best, with the possibility that electricity may fail, vehicles may not start, policy, fire, and ambulance 911 service may not work, and so on, but many other functions you probably take for granted, such as air traffic control, may cease to function. No power means no water from the tap, Sewage systems would fail. Traffic lights could turn off. Within a few hours of a genuine breakdown in the transportation system, food in grocery stores would be shopped out. (Or looted.) On the basis of recent experience in American cities, you could suppose that no power, no water, no heat for many, no light, and fragmented communications with emergency services, including police and fire, all add up to no civilization. While no one can be sure what the impact of the Y2K problem may be, it could extend to looting and rioting in the streets, especially if it becomes known that there could be widespread failures to issue payroll, welfare and pension checks.

> "We shall not be what we have been, but we shall begin to be other."[^20] - Joachim de Fiore

Premonitions of doom about the new millenium do not necessarily rest upon theology tied to the Christian faith, but they do fit within the millennial tradition of Joachim de Fiore whose mediations convinced him that Christ was only "the second hinge of history"and that another was destined to unfold."[^21] So argues the philospher Michael Grosso, who suggests that the Information Revolution is piloting human history toward the realization of the prophetic vision of the Western world. He call this "technocalypse." Whether or not the development of technology is somehow informed by millennial visions, the Y2K phenomenon is an artifact of the predominant Western imagination of time. In a strange way, it could complement dreams, reveries and visions, or numerical interprations of visions, like Newton's gloss on the prophecies of Daniel. These intuitive leaps begin with a perspective that takes the birth of Christ to be the central fact of history. They are compounded by the psychological power of large round numbers, which every trader will recognize as having an arresting quality. The two thousandth year of our epoch cannot help but become a focus for the imagination of intuitive people.

A critic could easily make these premonitions seem silly, without even addressing the ambiguous and debatable theological notions of the Apocalypse and the Last Judgment that give these visions so much of their power. Interestingly, however, the Y2K computer glitch trumps the errors of arithmetic that otherwise might seem to devalue the importance of the year 2000 even within the Christian framework. The year 2000 has the potential to become an inflection point for the next stage of history simply because it brings forward the arrival of the new millennium. In strict logic, the next millennium will not begin until 2001. The year 2000 will be only the two thousandth year since Christ's birth. Or it would be had Christ been born in the first year of the Christian era. He was not. In 533, when Christ's birth replaced the founding date of Rome as the basis for calculating years according to the Western calendar, the monks who introduced the new convention miscalculated Christ's birth. It is now accepted that he was born in 4 B.C. On that basis, a full two thousand years since his birth will be completed sometime in 1997. Hence Carl Jung's apparently odd launch date for the start of a New Age.

Giggle if you will, but we do not despise or dismiss intuitive understandings of history. Although our argument is grounded in logic, not in revenues, we are awed by the prophetic power of human consciousness. Time after time, it redeems the visions of madmen, psychics, and saints. So it may be with the transformation of the year 2000. The date that has long been fixed in the imagination of the West looks to be the inflection point that at least half confirms that history has a destiny. We cannot explain why this should be, but nonetheless we are convinced that it is so.

Our intuition is that history has a destiny, and that free will and determinism are two versions of the same phenomenon. The human interactions that form history behave as though they were informed by a kind of destiny. lust as an electron plasma, a dense gas of electrons, behaves as a complex system, so do human beings. The freedom of individual movement by the electrons turns out to be compatible with highly organized collective behavior. As David Ohm said of an electron plasma, human history is "a highly organized system which behaves as a whole."

Understanding the way the world works means developing a realistic intuition of the way that human society obeys the mathematics of natural processes. Reality is nonlinear But most people's expectations are not. To understand the dynamics of change, you have to recognize that human society, like other complex systems in nature, is characterized by cycles and discontinuities. That means certain features of history have a tendency to repeat themselves, and the most important changes, when they occur, may be abrupt rather than gradual.

Among the cycles that permeate human life, a mysterious five-hundred-year cycle appears to mark major turning points in the history of Western civilization. As the year 2000 approaches, we are haunted by the strange fact that the final decade of each century divisible by five has marked a profound transition in Western civilization, a pattern of death and rebirth that marks new phases of social organization in much the way that death and birth delineate the cycle of human generations. This has been true since at least 500 B.C., when Greek democracy emerged with the constitutional reforms of Cleisthenes in 508 B.C. The following five centuries were a period of growth and intensification of the ancient economy, culminating in the birth of Christ in 4 B.C. This was also the time of the greatest prosperity of the ancient economy, when interest rates reached their lowest level prior to the modern period.

The next five centuries saw a gradual winding down of prosperity, leading to the collapse of the Roman Empire late in the fifth century A.D. William Playfair's summary is worth repeating: "When Rome was at its highest pitch of greatness. ... will be seen to be at the birth of Christ, that is, during the reign of Augustus, and by the same means it will be found declining gradually till the year 490."[^22] It was then that the last legions dissolved, and the Western world sank into the Dark Ages.

During the following five centuries, the economy withered, long-distance trade ground to a halt, cities were depopulated, money vanished from circulation, and art and literacy almost disappeared. The disappearance of effective law with the collapse of the Roman Empire in the West led to the emergence of more primitive arrangements for settling disputes. The blood feud began to be significant at the end of the fifth century. The first recorded incident of trial by ordeal occurred precisely in the year 500.

Once again, a thousand years ago, the final decade of the tenth century witnessed another "tremendous upheaval in social and economic systems." Perhaps the least known of these transitions, the feudal revolution, began at a time of utter economic and political turmoil. In *The Transformation of the Year One Thousand*, Guy Bois, a professor of medieval history at the University of Paris, claims that this rupture at the end of the tenth century involved the complete collapse of the remnants of ancient institutions, and the emergence of something new out of the anarchy feudalism.[^23] In the words of Raoul Glaber, "It was said that the whole world, with one accord, shook off the tatters of antiquity."[^24] The new system that suddenly emerged accommodated the slow revival of economic growth. The five centuries now known as the Middle Ages saw a rebirth of money and international trade, along with the rediscovery of arithmetic, literacy and time awareness.

Then, in the final decade of the fifteenth century, there was yet another turning point. It was then that Europe emerged from the demographic deficit caused by the Black Death and almost immediately began to assert dominion over the rest of the globe. The "Gunpowder Revolution," the "Renaissance," and the "Reformation" are names given to different aspects of this transition that ushered in the Modern Age. It was announced with a bang when Charles VIII invaded Italy with new bronze cannon. It involved an opening to the world, epitomized by Columbus sailing to America in 1492. This opening to the New World launched a push toward the most dramatic economic growth in the experience of humanity. It involved a transformation of physics and astronomy that led to the creation of modern science. And its ideas were disseminated widely with the new technology of the printing press.

Now we sit at the threshold of another millennial transformation. The large command and control systems inherited from the Industrial Era may break down like the one-horse shay on the stroke of the millennial midnight. Yet whether or not the Y2K logic bomb precipitates an immediate collapse of industrial society, its days are numbered. We expect the advent of the Information Society to utterly transform the world, in ways that this book is meant to explain. You would be perfectly within your rights to doubt this, since no cycle that repeats itself only twice in a millennium has demonstrated enough iterations to be statistically significant. Indeed, even much shorter cycles have been viewed skeptically by economists demanding more statistically satisfying proof. "Professor Dennis Robertson once wrote that we had better wait a few centuries before being sure" about the existence of four-year and the eight-to ten-year trade cycles.[^25] By that standard, Professor Robertson would have to suspend judgment for about thirty thousand years to be sure that the five-hundred-year cycle is not a statistical fluke. We are less dogmatic, or more willing to recognize that the patterns of reality are more complex than the static-and linear-equilibrium models of most economists.

We believe that the coming of the year 2000 marks more than another convenient division along an endless continuum of time. We believe it will be an inflection point between, the Old World and a New World to come. The Industrial Age is rapidly passing, and it's demise may, ironically, be accelerated by the fact that early computer memory was so expensive that it encouraged the widespread adoption of the two-digit date fields. When Hallerith punch cards could accomodate only eighty characters each, abbreviating dates seemed a prudent thing to do. Contrary to the expenctations of the early programmers, however, their abbreviation of the date field endured four decades until the end of the millennium as an accidental logic bomb that could destroy large part of Industrial society. The U.S. government's Office of Management and Budget described the problem in "Getting Federal Computers Ready for 2000,"a report dated February 7, 1997. The OMB concludes of computers: "Unless they are fixed or replaced, they will fail at the turn of the century in one of three ways: they will reject legitimate entries, or they will compute erroneous results, or they simply will not run." These three outcomes in combination could cripple Industrial society. Its technology of mass production is destined to be eclipsed by a new technology of miniaturization in any event. A near-term crisis will merely accelerate the process. With the new information technology has come a new science of nonlinear dynamics, one whose startling conclusions are mere strands that have yet to be woven together into a comprehensive worldview. We live in the time of the computer, but our dreams are still spun on the loom. We continue to live by the metaphors and thoughts of industrialism. Our politics still straddles the industrial divide between right and left, as mapped by thinkers like Adam Smith and Karl Marx, who died before almost everyone now living was born.[^28] The industrial worldview, incorporating the operating principles of industrial science, is still the "commonsense ' intuition of educated opinion. It is our thesis that the "common sense" of the Industrial Age will no longer apply to many areas as the world is transformed.

More than eighty-five years after the day in 1911 when Oswald Spengler was seized with an intuition of a coming world war and "the decline of the West," we, too, see "*a historical change of phase* occurring ... at the point preordained for it hundreds of years ago."[^26] Like Spengler, we see the impending death of Western civilization, and with it the collapse of the world order that has predominated these past five centuries, ever since Columbus sailed west to open contact with the New World. Yet unlike Spengler we see the birth of a new stage in Western civilization in the coming millennium.

[^1]: Danny Hillis, "The Millennium Clock," Wired, Special Edition, Fall 1995, p.48.

[^2]: Ericka Cheetham, The Final Prophecies of Nostradamus (New York: Putnam,1989), p.424.

[^3]: Dr. Edward Yardeni, Year 2000 Recession: "Prepare for the worst. Hope for the best," Version 5.0, May 13, 1998, B1.2.

[^4]: Michael Grasso, The Millenium Myth: Love and Death at the End of Time, Wheaton, Illinois: Quest Books, 1995.

[^5]: Johan Huizinga, The Waning of the Middle Ages, trans. E Hopman (London: Penguin Books, 1990), p.172.

[^6]: Marshall McLuhan, Understanding Media, New York: Signet, 196, p. 19.

[^7]: James George Frazer, The Golden Bough: A Study in Magic and Religion (New York: Macmillan, 1951), p.105.

[^8]: For more detail about fragmented sovereignties as a precursor and alternative to the nationstate, see Charles Tilly, Coercion, Capital and European States AD 990-1992 (Oxford: Blackwell, 1993).

[^9]: The German GPI index stood at 33.20 on December 31, 1948, and 112.90 on June 30, 1995, which represents a compound annual depreciation of 2.7 percent. The U.S. CPI stood at 24 on December31, 1948, and 152.50 on June 30, 1995. The cumulative U.S. inflation was 635 percent for the period.

[^10]: Janet L. Abu-Lughod, Before European Hegemony: The World System A.D.1250-1350 (Oxford: Oxford University Press, 1991), p.62.

[^11]: Jack Cohen and Ian Stewart, The Collapse of Chaos (New York: Viking, 1994).

[^12]: See James Dale Davidson and Lord William Rees-Mogg, *The Great Reckoning*, 2nd ed. (New York: Simon & Schuster, 1993), p. 53.

[^13]: Frederic C. Lane, "Economic Consequences of Organized Violence," The Journal ofEconomic History vol.18, no.4 (December 1958), p.402.

[^14]: Nicholas Colehester, "Goodbye NationState, Hello . . . What?," New York Times, July 17, 1994, p. E17.

[^15]: Norman Macrae, "Governments in Decline," Cato Policy Report, July/August 1992, p.10.

[^16]: Arthur C. Clarke, Profiles of the Future: An Enquiry into the Limits of the Possible (London: Victor Gollancz Ltd., 1962), p.13.

[^17]: Ibid.

[^18]: A. T. Mann, Millennium Prophecies: Predictions for the Year 2000 (Shafiesbury, England: Element Books, 1992), pp.88, 112, 117.

[^19]: Yardeni, op. cit., p. 45.

[^20]:  Cited in Frooso, op. cit., p. 40.

[^21]: Ibid

[^22]: William Playfair, An Inquiry into the Permanent Causes 0f the Decline and Fall of Powerful and Wealthy Nations: Designed to Show How the Prosperity of the British Empire May he Prolonged (London: Greenland and Norris, 1805), p.79.

[^23]: Guy Bois, The Transformation 0f the Year One Thousand: The Village ofLournard from Antiquity to Feudalism (Manchester, England: Manchester University Press, 1992).

[^24]: Ibid., p. 150.

[^25]: Quoted in S. B. Saul, The Myth 0f the Great Depression (London: Macmillan, 1985), p.10.

[^26]: Oswald Spengler, The Decline of the West, trans. Charles Francis Atkinson, quoted in I. F. Clark, The Pattern of Expectation, 1644-2001 (London: Jonathan Cape, 1979), p. 220.

[^27] Nomenklatunas are the entrenched elites that ruled the former Soviet Union and other state-run economies.

[^28]: Adam Smith died in 1790, Karl Marx in 1883.
