# Muutosvuosi 2000

> "Tuntuu siltä, että jotain suurta on tapahtumassa: kaaviot näyttävät väestön vuotuisen kasvun, hiilidioksidin ilmakehän pitoisuuksien nousun, verkkosivustojen lukumäärän ja megatavujen määrän per dollari. Kaikki nämä nousevat kohti asymptoottista rajaa, hieman vuosisadan vaihteen yli: Singulaarisuutta. Kaiken, mitä tunnemme, loppua. Jotakin, mitä emme ehkä koskaan ymmärrä." [^1] - Danny Hillis

## Ennakkoluulot

Vuoden 2000 saapuminen on kummitellut länsimaista mielikuvitusta viimeisen tuhannen vuoden ajan. Jo siitä lähtien, kun maailma ei päättynyt Kristuksen jälkeisen ensimmäisen vuosituhannen vaihteessa, teologit, evankelistit, runoilijat ja ennustajat ovat katsoneet tämän vuosikymmenen loppua odotuksella, että se toisi mukanaan jotain merkittävää. Ei vähäisempää auktoriteettia kuin Isaac Newton spekuloikin, että maailma päättyisi vuoteen 2000. Michel de Nostradamus, jonka ennustuksia on luettu joka sukupolvi siitä lähtien, kun ne julkaistiin ensimmäisen kerran vuonna 1568, ennusti Kolmannen Antikristuksen saapumista heinäkuussa 1999.[^2] Sveitsiläinen psykologi Carl Jung, "kokoelman alitajunnan" asiantuntija, kuvitteli Uuden aikakauden syntyvän vuonna 1997. Tällaiset ennusteet saattavat helposti herättää naurun. Niin myös taloustieteilijöiden vakavat ennusteet, kuten Dr. Edward Yardeni Deutsche Bank Securitiesista, joka odottaa tietokoneiden toimintahäiriöiden vuosituhannen keskiyön aikaan "häiritsevän koko globaalin talouden."[^3] Mutta olipa näkemyksesi Y2K-tietokoneongelmasta sitten perustelematonta hysteriaa, jonka ovat herättäneet tietokoneohjelmoijat ja IT-konsultit liiketoiminnan edistämiseksi, tai mystisenä tapauksena, jossa teknologia epäonnistuu yhtä aikaa profeetallisen mielikuvituksen kanssa, ei voi kiistää, että vuosituhannen aattona vallitsevat olosuhteet herättävät enemmän kuin tavanomaista synkkää epäilystä siitä, mihin suuntaan maailma on menossa.

Huoli tulevaisuudesta on alkanut värjätä niitä 250 vuotta kestäneitä länsimaisia optimismin sävyjä. Ihmiset kaikkialla ovat epäröiviä ja huolissaan. Näet sen heidän kasvoistaan. Kuule sen heidän keskusteluistaan. Näet sen heijastuvan mielipidemittauksissa ja äänestyyskuiluissa. Aivan kuten näkymätön, fysikaalinen ionien muutos ilmakehässä viestii myrskyn olevan tulossa jo ennen pilvien taittumista ja salaman iskemistä, niin nyt, vuosituhannen hämärässä hetkessä, ilmassa on ennakkoja muutoksesta. Yksi henkilö toisensa jälkeen, kukin omalla tavallaan, aistii, että aikaa on loppumassa kuolemassa olevalle elämäntavalolle. Kun vuosikymmen päättyy, sen mukana päättyy myös verinen vuosisata ja loistokas vuosituhannen inhimillisen saavutuksen aikakausi. Kaikki päättyvät vuoden 2000 myötä.

„Sillä kaikkea, mikä on peitetty, tulee paljastetuksi, eikä mitään, mikä on salattu, jää tuntematta.“ – Matthew 10:26

Uskomme, että länsimaisen sivilisaation moderni vaihe päättyy tähän. Tämä kirja kertoo miksi. Kuten monet aiemmat teokset, se on yritys nähdä peilinä hämärästi, hahmotella tulevaisuuden epäselviä muotoja ja ulottuvuuksia, jotka vielä ovat edessä. Tällä tavoin tarkoitamme teoksemme olevan apokalyptinen sanan alkuperäisessä merkityksessä. Apokalypsis tarkoittaa kreikaksi „paljastusta”. Uskomme, että uusi historiallinen vaihe – Informaatiokausi – on saavuttamassa paljastumistaan.

„Seuraamme uuden loogisen tilan alkua, hetkellistä elektronista kaikkiallaoloa, johon me kaikki voimme päästä käsiksi, astua sisään ja kokea. Meillä on siis uudenlaisen yhteisön alku. Virtuaaliyhteisöstä tulee malliesimerkki sekulaarille Taivaan valtakunnalle; kuten Jeesus sanoi, Isänsä valtakunnassa on monia kartanoita, niin on monia virtuaaliyhteisöjä, jotka heijastelevat omia tarpeitaan ja toiveitaan.” – Michael Grasso[^4]

## Ihmiskunnan neljäs vaihe

Tämän kirjan teema on uusi vallankumous, joka vapauttaa yksilöitä 1900-luvun kansallisvaltiota vastaan menettämällä sen edut. Innovaatiot, jotka muuttavat väkivallan logiikkaa ennennäkemättömillä tavoilla, muokkaavat niitä rajoja, joiden sisällä tulevaisuuden on määrä asettua. Jos johtopäätöksemme ovat oikeita, seisot historian laajimman vallankumouksen kynnyksellä. Nopeammin kuin harvat nykyään edes pystyvät kuvittelemaan mikroprosessoritekniikka kapinoi ja tuhoaa kansallisvaltion, synnyttäen samalla uusia sosiaalisen järjestäytymisen muotoja. Tämä muutos tulee olemaan kaikkein kaukana helppoudesta.

Haaste, jonka se aiheuttaa, on sitä suurempi, että se tapahtuu uskomattoman nopeasti verrattuna mihinkään menneisyydessä nähtyyn. Koko ihmiskunnan historian, sen varhaisimmista alkuajoista tähän päivään, aikana on ollut vain kolme perustasoa talouselämää: (1) metsästäjä-keräilijäyhteiskunnat; (2) maatalousyhteiskunnat; ja (3) teollisuusyhteiskunnat. Nyt horisontissa kohoaa jotain täysin uutta, neljäs sosiaalisen järjestäytymisen vaihe: tietoyhteiskunnat.

Jokainen edellinen yhteiskuntavaihe on vastannut omalla tavallaan hyvin erilaisia väkivallan kehittymisen ja hallinnan vaiheita. Kuten yksityiskohtaisesti selitämme, tietoyhteiskunnat lupaavat dramaattisesti vähentää väkivallan tuottoja, osittain siksi, että ne ylittävät paikallisuuden rajoitukset. Kyberavaruuden virtuaalitodellisuus, jonka kirjailija William Gibson kuvaili "konsensukseen perustuvaksi harhaksi", tulee olemaan niin kaukana kiusaajien ulottumattomissa kuin mielikuvitus pystyy häntä viemään. Uudella vuosituhannella väkivallan suuressa mittakaavassa hallitsemisen etu tulee olemaan huomattavasti alhaisempi kuin koskaan ennen Ranskan vallankumousta edeltävältä ajalta. Tällä on syvällisiä seurauksia. Yksi seurauksista on rikollisuuden kasvu. Kun väkivallan järjestämisen suurimittakaavaisesta toiminnoista saatava hyöty romahtaa, pienemmän mittakaavan väkivallan tuotto saattaa hypätä. Väkivalta muuttuu satunnaisemmaksi ja paikallisemmaksi, ja järjestäytynyt rikollisuus laajenee laajuudeltaan. Selitämme miksi.

Toinen looginen seuraus väkivallan tuottojen laskiessa on politiikan hälveneminen. On paljon todisteita siitä, että 1900-luvun kansallisvaltion kansalaismyyttien noudattaminen rappeutuu nopeasti. Kommunismin kuolema on vain näyttävin esimerkki. Kuten yksityiskohtaisesti tutkimme, länsimaisten hallitusten johtajien moraalin romahdus ja kasvava korruptio eivät ole satunnaisia kehityskulkuja, vaan ne osoittavat, että kansallisvaltion potentiaali on käytetty loppuun. Jopa monet sen johtajista eivät enää usko suostuttelulausekkeisiin, joita he toistavat, eivätkä muut usko heihin.

### History Repeats Itself

Tämä on tilanne, jossa on hämmästyttävät samankaltaisuudet menneisyydessä tapahtuneiden kanssa. Aina kun teknologinen muutos irroittaa vanhat muodot uusista talouden liikkeellepanevista voimista, myös moraalistandardit muuttuvat ja ihmiset alkavat suhtautua yhä halveksuvammin vanhojen instituutioiden johtajiin. Tämä laaja vastenmielisyys tulee usein esiin jo ennen kuin ihmiset kehittävät uutta johdonmukaista muutoksen ideologiaa. Näin kävi myöhäisellä viisitoista vuosisadalla, jolloin keskiaikainen kirkko oli feodalistisen järjestelmän hallitseva instituutio. Huolimatta yleisestä uskomuksesta "papin viran pyhyyteen" sekä korkeammat että alemmat papiston arvonimet olivat äärimmäisen halveksunnan kohteena – aivan kuten nykyäänkin yleinen asenne poliitikkoja ja byrokraatteja kohtaan. [^5]

Uskomme, että paljon voidaan oppia vertaamalla 1400-luvun lopun tilannetta, jolloin elämä oli täysin kyllästetty järjestäytyneellä uskonnolla, nykytilanteeseen, jolloin maailma on kyllästetty politiikalla. Uskonnollisten instituutioiden tukemisen kustannukset 1400-luvun lopulla olivat saavuttaneet historiallisesti ennennäkemättömän äärimmäisyyden – aivan kuten hallituksen tukemisen kustannukset ovat nykyään nousseet lähes hullun korkeiksi.

Me tiedämme, mitä järjestäytyneelle uskonnolle tapahtui ruuti- ja räjähdysvallankumouksen jälkeen. Teknologiset kehitykset loivat voimakkaat kannustimet supistaa uskonnollisia instituutioita ja alentaa niiden kustannuksia. Samankaltainen teknologinen vallankumous on määrä supistamaan kansallisvaltiota radikaalisti uuden vuosituhannen alkuvaiheessa.

> Tänään, yli vuosisadan sähköteknologian jälkeen, olemme laajentaneet keskushermostoamme globaalisti, kumoten niin tilan kuin ajankin suhteessa planeettaamme.[^6]

### Informaatiovallankumous

Suurten järjestelmien hajoamisen kiihtyessä systemaattinen pakko vähenee tekijänä, joka muokkaa talouselämän rakenteita ja tulojen jakaantumista. Tehokkuus tulee nopeasti voimaan enemmän kuin vallan vaatimukset sosiaalisten instituutioiden järjestämisessä. Tämä tarkoittaa, että maakunnat ja jopa kaupungit, jotka pystyvät tehokkaasti turvaamaan omaisuusoikeudet ja järjestämään oikeudenmukaisuuden samalla kuluttaen vain vähän resursseja, ovat elinkelpoisia itsenäisyyksiä informaatiokaudella – asia, jota ne eivät yleisesti ole olleet viimeisten viiden vuosisadan aikana. Kyberavaruuteen nousee täysin uusi taloudellisen toiminnan alue, joka ei ole orjuutunut fyysisen väkivallan vaikutukselle. Ilmeisimmät hyödyt siirtyvät "kognitiiviselle eliitille", jotka tulevat yhä enemmän toimimaan poliittisten rajojen ulkopuolella. He ovat jo yhtä kotona Frankfurtissa, Lontoossa, New Yorkissa, Buenos Airesissa, Los Angelesissa, Tokiossa ja Hongkongissa. Tulojen jakautuminen tulee muuttumaan siten, että ne ovat epätasaisempia toimivalta-alueiden sisällä, mutta tasaantuvat enemmän niiden välillä.

The Sovereign Individual tutkii tämän vallankumouksellisen muutoksen sosiaalisia ja taloudellisia seurauksia. Tavoitteenamme on auttaa sinua hyödyntämään uuden aikakauden tarjoamia mahdollisuuksia ja välttämään sen vaikutusten tuhoa. Jos edes vain puolet siitä, mitä odotamme tapahtuvan, toteutuu, edessäsi on muutos, jolla on hyvin vähän ennakkotapauksia historiassa.

Vuoden 2000 murros ei ainoastaan mullista maailman talouden luonnetta, vaan se tapahtuu nopeammin kuin mikään aiempi vaiheenvaihdos. Toisin kuin maatalousvallankumous, informaatiovallankumous ei vie vuosituhansia tehdäkseen vaikutuksensa. Toisin kuin teollinen vallankumous, sen vaikutus ei jakaannu vuosisatojen ajalle. Informaatiovallankumous tapahtuu elinaikana.

Lisäksi se tapahtuu melkein kaikkialla yhtä aikaa. Tekniset ja taloudelliset innovaatiot eivät enää rajoitu maapallon pieniin osiin. Muutos on lähes universaali. Ja siihen sisältyy murros menneisyydestä niin syvä, että se tuo lähes eloon jumalten taianomaisen valtakunnan, kuten varhaiset maatalousyhteisöt – esimerkiksi muinaiset Kreikkalaiset – kuvasivat sitä. Enemmän kuin useimmat nykyään myöntäisivät, monien nykyisten instituutioiden säilyttäminen uudella vuosituhannella osoittautuu vaikeaksi tai mahdottomaksi. Kun informaatiovaltakunnat muotoutuvat, ne eroavat teollisyhteiskunnista yhtä paljon kuin Aeschyluksen Kreikka erosi luolamiesyhteisöjen maailmasta.

## Prometheus unbound: The rise of the sovereign individual

> Enempää rohkaisevaa tosiasiaa kuin ihmisen kykyä nostaa elämäänsä tietoisen ponnistelun kautta en tiedä – Henry David Thoreau

Tuleva muutos on sekä hyviä että huonoja uutisia. Hyviä uutisia on se, että informaatiovallankumous vapauttaa yksilöt ennennäkemättömällä tavalla. Ensimmäistä kertaa ne, jotka pystyvät kouluttamaan itseään, ovat lähes täysin vapaita keksimään omaa työtään ja hyödyntämään oman tuottavuutensa kaikki hyödyt. Nerokkuus vapautuu, pois vapautuen sekä hallituksen sortojen että rotu- ja etnisten ennakkoluulojen kahleista. Informaatioyhteiskunnassa ketään, joka on todella kykenevä, ei vangita muiden huonosti muotoiltujen mielipiteiden vuoksi. Ei ole väliä, mitä suurin osa maapallon ihmisistä saattaa ajatella rodustasi, ulkonäöstäsi, iästäsi, seksuaalisista taipumuksistasi tai tavasta, jolla pidät hiuksiasi. Kybertaloudessa he eivät koskaan näe sinua. Rannel, lihava, vanha ja vammainen kilpailevat nuorten ja kauniiden kanssa tasavertaisesti täysin väriä näkemättömässä nimettömyydessä kyberavaruuden uusilla rajoilla.

### Ideas Become Wealth

Ansio, missä tahansa se ilmestyy, palkitaan ennennäkemättömällä tavalla. Ympäristössä, jossa suurin varallisuuden lähde eivät pelkästään fyysiset pääomat, vaan mielessäsi olevat ideat, kuka tahansa, joka ajattelee selvästi, voi potentiaalisesti tulla rikkaaksi. Informaatiokausi on nousua kuvaava aika. Se tarjoaa paljon tasavertaisemmat mahdollisuudet miljardeille ihmisille maailman osissa, jotka eivät koskaan täysin jakaneet teollisen yhteiskunnan vaurautta. Näistä kirkkaimmat, menestyneimmät ja kunnianhimoisimmat nousevat esiin todellisina suvereenina yksilöinä.

Aluksi vain harvat saavuttavat täyden taloudellisen itsenäisyyden. Mutta tämä ei kumoa taloudellisen riippumattomuuden etuja. Se, että kaikilla ei ole samanlaista valtavaa varallisuutta, ei tarkoita, että rikkaaksi tuleminen olisi turhaa tai merkityksetöntä. Jokaisesta miljardööristä on 25 000 miljonääriä. Jos olet miljonääri etkä miljardööri, se ei tee sinusta köyhää. Samoin tulevaisuudessa yksi merkkipaalu taloudellisen menestyksesi mittarina tulee olemaan ei pelkästään se, kuinka monta nollaa voit lisätä nettovarallisuuteesi, vaan myös se, pystytkö järjestämään asiasi siten, että voit saavuttaa täyden yksilöllisen autonomian ja riippumattomuuden. Mitä älykkäämpi olet, sitä vähemmän työntövoimaa tarvitset saavuttaaksesi taloudellisen pakonopeuden. Jopa melko vaatimattomilla varoilla omaavat henkilöt kohoavat, kun politiikan vetovoima globaalissa taloudessa heikkenee. Ennennäkemätön taloudellinen riippumattomuus on tavoitettavissa elämäsi aikana tai lasten elinaikana.

Tuottavuuden korkeimmalla tasanteella nämä suvereenit yksilöt kilpailevat ja vuorovaikuttavat sellaisilla ehdoilla, jotka muistuttavat kreikkalaisen mytologian jumalten välisiä suhteita. Seuraavan vuosituhannen katoava Olympoksen vuori sijaitsee kyberavaruudessa – olemassaoloton fyysisessä mielessä, mutta joka kehittyy siitä huolimatta lupaamaan maailman suurinta taloutta uuden vuosituhannen toisen vuosikymmenen aikana. Vuoteen 2025 mennessä kybertaloudessa on miljoonia osallistujia. Jotkut heistä ovat yhtä rikkaita kuin Bill Gates, joiden arvo ylittää 10 miljardin dollarin kullekin. Kyberköyhät saattavat olla niitä, joiden vuositulo on alle 200 000 dollaria. Kyberhyvinvointia ei ole. Ei kybertaksia eikä kyberhallintoa. Kybertalous, eikä Kiina, voi hyvin olla seuraavien kolmenkymmenen vuoden suurin taloudellinen ilmiö.

Hyviä uutisia on se, että poliitikot eivät tule enää pystyä hallitsemaan, tukahduttamaan ja säätelemään suurinta osaa kaupasta tässä uudessa ulottuvuudessa samalla tavalla kuin antiikin kreikkalaisten kaupunkivaltioiden lainsäätäjät olisivat voineet trimmaavat Zeuksen partaa. Tämä on hieno uutinen rikkaiden puolesta. Ja vielä parempi uutinen ei-niin-rikkaiden puolesta. Ne esteet ja taakko, joita politiikka asettaa, ovat enemmän esteitä rikkaaksi tulemiselle kuin siihen, että ollaan jo rikkaita. Väkivallan tuottojen alenemisen ja toimivaltioiden delegoinnin hyötytuotto tulee tarjoamaan mahdollisuuden jokaiselle energiselle ja kunnianhimoiselle ihmiselle hyötyä politiikan loppumisesta. Myös valtionpalveluiden kuluttajat hyötyvät, kun yrittäjät laajentavat kilpailun tuomia etuja. Tämän seurauksena suuri osa toimivaltioiden välisestä kekseliäisyydestä ohjautui sotilaalliseen toimintaan. Mutta kybertalouden edut tuovat kilpailua uusilla ehdoilla suvereniteettipalveluiden tarjoamiseen. Toimivaltioiden lisääntyminen tarkoittaa, että kokeillaan yhä uusia tapoja sopimusten täytäntöönpanossa ja muuten turvataan henkilöiden sekä omaisuuden turvallisuus. Suuren osan globaalin talouden vapauttaminen poliittisesta kontrollista pakottaa kaikki jäljellä olevat hallinnon muodot toimimaan yhä enemmän markkinaehtoisesti. Viime kädessä niillä jää vähän vaihtoehtoja kuin kohdella sille palveltavien alueiden väestöjä enemmän kuin asiakkaina ja vähemmän sillä tavoin kuin järjestäytyneet rikollisryhmät kohtelevat kiristysuhrejaan.

Beyond Politics

Se, mitä mytologia kuvaili jumalten maakunnaksi, tulee yksilölle muodostumaan käytännölliseksi vaihtoehdoksi – elämäksi, joka on kuninkaiden ja neuvostojen ulottumattomissa.

Ensiksi kymmeniä, sitten satoja ja lopulta miljoonia ihmisiä pääsevät irti politiikan kahleista. Tekemällä näin he muuttavat hallitusten luonnetta, kutistavat pakkokeinon alueita ja laajentavat yksityisen vallan keinoja resurssien hallinnassa.

Suvereenin yksilön nousu näyttää jälleen kerran myytin omituisen ennustavan voiman. Varhaiset maatalousyhteisöt, joiden ymmärrys luonnonlaeista oli vähäistä, kuvittelivat, että "voimia, joita meidän tulisi kutsua yliluonnollisiksi" levisi laajasti. Näitä voimia käyttivät joskus miehet, joskus "ruumiillistuneet ihmisten jumalat", jotka näyttivät miehiltä ja vuorovaikutuksessa heidän kanssaan siinä, mitä Sir James George Frazer kuvaili teoksessaan The Golden Bough:ksi "suureksi demokratiaksi".

Kun muinaiset kuvittelivat Zeuksen lasten asuvan keskuudessaan, heitä inspiroi syvä usko magiaan. He jakoivat muiden primitiivisten maatalousyhteisöjen kanssa luonnon kunnioituksen ja taikauskon, jonka mukaan luonnon ilmiöt laukaistaan yksittäisen tahdon – taian – toimesta. Siinä mielessä heidän näkemyksessään luonnosta ja jumalistostaan ei ollut mitään itse tietoisesti ennustavaa. He eivät osanneet aavistaa mikroteknologiaakaan. He eivät olisi voineet kuvitella sen vaikutusta yksilöiden marginaalituottavuuden muuttamiseen tuhansia vuosia myöhemmin. He eivät varmasti olisi osanneet ennakoida, kuinka se muuttaisi vallan ja tehokkuuden tasapainoa ja siten mullistaisi sitä, miten omaisuutta luodaan ja suojataan. Kuitenkin se, mitä he kuvittelivat kudotessaan myyttejään, resonoi kummallisesti sen maailman kanssa, jonka olet todennäköisesti näkemässä.

### Alt.Abracadabra

Esimerkiksi taikaloitsun "abracadabra" muistuttaa kummallisella tavalla sitä salasanaa, jolla tietokoneeseen päästään. Joillakin osa-alueilla nopea laskentateho on jo mahdollistanut djinnin taikuuden jäljittelyn. Varhaiset "digitaalisten palvelijoiden" sukupolvet tottelevat jo niiden ihmisten käskyjä, jotka hallitsevat niitä tietokoneita, joihin ne on "suljettu" – aivan kuten djinnit suljettiin taikalamppuihin. Tietotekniikan virtuaalitodellisuus laajentaa ihmisten toiveiden ulottuvuutta siten, että melkein kaikki, mitä voi kuvitella, voidaan saada näyttämään todelliselta. Telepresenssi antaa elävien ihmisten saman kyvyn ylittää etäisyyksiä yliluonnollisella nopeudella ja seurata tapahtumia kaukaa, aivan kuten kreikkalaiset uskoivat, että Hermes ja Apollo nauttivat. Information Ajan suvereenit yksilöt, kuten muinaisten ja primitiivisten myyttien jumalat, tulevat lopulta nauttimaan eräänlaisesta "diplomaattisesta immuniteetista" useimpia niitä poliittisia murheita vastaan, jotka ovat vaivanneet kuolevaisia ihmisiä useimpina aikoina ja paikoissa.

Uusi suvereeni yksilö toimii yhtä kuin myyttien jumalat samassa fyysisessä ympäristössä kuin tavallinen, alaistuva kansalainen, mutta poliittisesti omassa erillisessä ulottuvuudessaan. Hän hallitsee huomattavasti suurempia resursseja ja on monien pakottavien keinojen ulottumattomissa, minkä seurauksena hän uudelleenjärjestää hallitukset ja muuttaa talouksia uudella vuosituhannella. Tämän muutoksen täydelliset seuraukset ovat lähes käsittämättömiä.

### Genius and Nemesis

Kenelle tahansa, joka rakastaa ihmisen pyrkimystä ja menestystä, Information Age tarjoaa runsaasti mahdollisuuksia. Se on varmasti paras uutinen monen sukupolven aikana. Mutta se on myös huono uutinen: Yhteiskunnan uusi järjestäytyminen, joka seuraa yksilöllisen autonomian voittoa ja mahdollisuuksien todellista tasa-arvoa ansioiden perusteella, johtaa valtaviin palkintoihin ansioista sekä suureen yksilölliseen vapauteen. Tämä jättää yksilöt paljon vastuullisemmiksi itsestään kuin mitä teollisuusajan aikana on ollut tapana, ja se vähentää ansaitsemattomia etuja elintasossa, joista kehittyneiden teollisuusyhteiskuntien asukkaat ovat nauttineet koko 1900-luvun ajan. Kirjoittaessamme maailman 15 prosentin huipulla olevien ihmisten keskimääräiseksi vuosituloksi on noussut noin 21 000 dollaria, kun taas jäljelle jäävän 85 prosentin keskimääräinen tulo on vain 1 000 dollaria. Tuo valtavan kertyneenä oleva etulyöntiasema menneisyydestä on väistämättä katoamassa Information Ajan uusien olosuhteiden alla.

Aivan kuten nyt tapahtuu, valtioiden kyky jakaa tuloja laajassa mittakaavassa romahtaa. Tietotekniikka mahdollistaa dramaattisesti kasvaneen kilpailun eri lainkäyttöalueiden välillä. Kun teknologia on liikkuvaa ja tapahtumat siirtyvät yhä useammin kyberavaruuteen, hallitukset eivät enää pysty veloittamaan palveluistaan enemmän kuin ne ovat niille maksaville ihmisille todellisuudessa arvokkaita. Kuka tahansa, jolla on kannettava tietokone ja satelliittiyhteys, pystyy hoitamaan melkein minkä tahansa tietoliiketoiminnan missä tahansa – ja tämä kattaa lähes koko maailman useiden biljoonien dollarien rahataloustoimet.

Tämä tarkoittaa, että sinun ei enää tarvitse asua korkean verotuksen alueella ansaitaksesi suuria tuloja. Tulevaisuudessa, kun suurimman osan varallisuudesta voi ansaita ja jopa kuluttaa missä tahansa, hallitukset, jotka yrittävät periä liikaa asuinpaikkamaksuna, karkottavat vain parhaat asiakkaansa. Jos päättelymme pitää paikkansa – ja uskomme sen olevan totta – kansallisvaltio sellaisena kuin me sen nykyään tunnemme ei selviä edes lähellä nykyistä muotoaan.

## Kansakuntien loppu

Muutokset, jotka vähentävät merkittävien instituutioiden valtaa, ovat yhtä aikaa rauhoittamattomia ja vaarallisia. Aivan kuten kuninkaat, herrat, paavit ja mahtitilaiset taistelivat armottomasti säilyttääkseen tottuneet etuoikeutensa modernin aikakauden alkuvaiheissa, niin myös nykyiset hallitukset käyttävät väkivaltaa – usein salakavalalla ja mielivaltaisella tavalla – pyrkiessään hidastamaan ajan kulkua. Teknologian haasteen heikentämänä valtio kohtelee yhä itsenäisempiä yksilöitä, entisiä kansalaisiaan, samalla armottomuuden ja diplomatian asteikolla, jolla se tähän asti on toiminut muiden hallitusten kanssa.  

Tämän uuden vaiheen alkamista historiassa juhlittiin kovalla iskulla 20. elokuuta 1998, kun Yhdysvallat ampui noin 200 miljoonan dollarin edestä Tomahawk BGM-109 -merivaunuhyökkäysohjuksia kohteisiin, joiden väitettiin liittyvän maanpakoon joutuneeseen saudi-miljardööriin Osama bin Ladeniin. Bin Ladenistä tuli ensimmäinen henkilö historiassa, jonka satelliittipuhelin kohdistettiin hyökkäyksen kohteeksi ohjuksilla. Samanaikaisesti Yhdysvallat tuhosi lääketehtaan Khartoumissa, Sudanissa, Bin Ladenin kunniaksi. Bin Ladenin nousu Yhdysvaltojen pääviholliseksi heijastaa mullistavaa muutosta sodankäynnin luonteessa. Yksi yksittäinen henkilö, vaikkakin sellainen, jolla on satoja miljoonia dollareita, voidaan nyt esittää uskottavana uhana teollistumisen aikakauden suurimpaa sotilaallista voimaa kohtaan. Kylmän sodan aikana Neuvostoliittoa koskevaa propagandaakin muistuttavissa lausunnoissaan Yhdysvaltain presidentti ja hänen kansallisen turvallisuutensa avustajansa esittivät Bin Ladenin – yksityishenkilön – transnationaalisena terroristina ja Yhdysvaltojen johtavana vihollisena.

Sama sotilaallinen logiikka, joka on nostanut Osama bin Ladenin Yhdysvaltojen pääviholliseksi, tulee vaikuttamaan hallitusten sisäisiin suhteisiin alamaisiaan kohtaan. Yhä ankarammat rahankeräystekniikat tulevat olemaan looginen seuraus hallitusten ja yksilöiden välisen uudenlaisesta neuvottelutavasta. Teknologia tekee yksilöistä lähes täysin suvereeneja kuin koskaan ennen – ja heitä kohdellaan juuri sillä tavalla. Joskus väkivallallisesti vihollisina, joskus tasavertaisina neuvottelukumppaneina, joskus liittolaisina. Mutta riippumatta siitä, kuinka armottomasti hallitukset toimivat – erityisesti siirtymäkaudella, jolloin IRS yhdistetään CIA:han – se ei auta heitä paljoa. Heidän on entistä useammin pakko neuvotella itsenäisten yksilöiden kanssa, joiden resursseja ei enää saada näin helposti hallintaan.

Tietovaakauden tuomat muutokset eivät ainoastaan aiheuta hallituksille finanssikriisiä, vaan ne myös pyrkivät hajottamaan kaikki suuret rakenteet. Neljätoista imperiumia on jo kadonnut 1900-luvulla. Imperiumien romahtaminen on osa prosessia, joka lopulta liu'uttaa kansallisvaltion itsekin. Hallituksen on sopeuduttava yksilön kasvavaan itsemääräämisoikeuteen. Veronkeruukyky romahtaa 50–70 prosentilla, mikä puolestaan tekee pienemmistä oikeudellisista alueista menestyneempiä. Kyky tarjota kilpailevia ehtoja kykenevien yksilöiden ja heidän pääomansa houkuttelemiseksi on todennäköisesti helpommin toteutettavissa enklaveissa kuin mantereiden halki.

Uskomme, että modernin kansallisvaltion hajoamisen myötä nykyajan barbaarit tulevat entistä useammin harjoittamaan valtaa kulissien takana. Ryhmät, kuten Venäjän mafiya, joka raapii jäänteitä entisestä Neuvostoliitosta, muut etnilliset rikollisjengit, nomenklaturas[^27], huumepommit sekä kapinalliset salaiset virastot, muodostavat kokonaisuuden, jolla on omat sääntönsä – ja niin ne ovat jo nyt. Paljon enemmän kuin yleisesti ymmärretään, nykyajan barbaarit ovat jo tunkeutuneet kansallisvaltion muotoihin vaikuttamatta merkittävästi sen ulkonäköön. He ovat mikropesalaisia, jotka elävät kuolevan järjestelmän kustannuksella. Nämä ryhmät, väkivaltaisia ja säädytömiä kuin sotavaltio, soveltavat valtion keinoja pienemmällä mittakaavalla. Niiden kasvava vaikutusvalta ja voima ovat osa politiikan pienentymisprosessia. Mikroprosessointi pienentää sen koon, jonka ryhmien täytyy saavuttaa ollakseen tehokkaita väkivallan käytössä ja hallinnassa. Tämän teknologisen vallankumouksen edetessä saalistavaa väkivaltaa organisoidaan yhä enemmän keskitetyn kontrollin ulkopuolella, ja väkivallan hillitsemistä tähtäävät toimet keskittyvät entistä enemmän tehokkuuteen kuin vallan määrään.

### History in Reverse

Viiden vuosisadan aikana kehittynyt kansallisvaltio käännetään uuden tietokauden logiikan myötä taaksepäin. Paikalliset vallankeskukset nousevat uudelleen esiin, kun valtio hajaantuu fragmentoituneiksi, päällekkäisiksi suvereniteeteiksi.[^8] Organisoidun rikollisuuden kasvava voima on vain yksi tämän taipumuksen heijaste. Monikansallisten yritysten on jo ulkoistettava kaikki paitsi olennaiset työt. Jotkut konglomeraatit, kuten *AT&T*, *Unisys* ja *ITT*, ovat jakautuneet useiksi yrityksiksi toimiakseen kannattavammin. Kansallisvaltio hajaantuu kuin kömpelö konglomeraatti, mutta luultavasti ei ennen kuin se rajoitetaan talouskriisien pakottamana.

Ei ainoastaan maailman vallan rakenne muutu, vaan myös maailman työ muuttuu. Tämä tarkoittaa, että liiketoiminnan toimintatavat muuttuvat väistämättä. "Virtuaalinen yritys" on todiste perusteellisesta muutoksesta yhtiön luonteessa, jota helpottaa informaation ja transaktioiden kustannusten lasku. Tarkastelemme tietovaakauden vaikutuksia yritysten hajoamiseen ja "hyvien työpaikkojen" hävittämiseen. Tietokaudella "työ" tulee olemaan tehtävä, ei asema, jonka "omistat". Mikroprosessointi on luonut täysin uusia taloudellisen toiminnan horisonteja, jotka ylittävät alueelliset rajat. Tämä rajojen ja territorioterveyden ylittäminen on ehkä kaikkein vallankumouksellisin kehitys siitä lähtien, kun Adam ja Eeva ryntäsivät ulos paratiisista Luojaansa tuomitsemana: "Hikisesi hikoilussa sinun on syötävä leipää." Kun teknologia mullistaa työkalut, joita käytämme, se myös vanhentaa lakimme, muokkaa moraaliamme ja muuttaa käsityksiämme. Tämä kirja selittää miten.

Mikrosuorituskyky ja nopeasti kehittyvät viestintäjärjestelmät tekevät jo nyt siitä mahdollista, että yksilö voi valita, missä hän työskentelee. Internetissä tai World Wide Webissä tapahtuvat kaupat voidaan salata, minkä vuoksi veroviranomaisten on pian melkein mahdotonta saada näitä kiinni. Verovapaat varat kasautuvat jo nyt huomattavasti nopeammin ulkomaille sijoitettuna kuin mantereella olevat varat, joihin 1900-luvun kansallisvaltioiden asettama korkea verokuorma edelleen kohdistuu. Vuosituhannen vaihtuessa suuri osa maailman kaupasta siirtyy uuteen kyberavaruuden ulottuvuuteen, alueeseen, jolla hallituksilla ei ole yhtään enempää valtata asettaa kuin mitä ne käyttävät meren pohjaan tai ulkoplaneetoihin. Kyberavaruudessa aikaisesta mielenkiinnosta ja politiikan alusta asti vallinneet fyysisen väkivallan uhkat katoavat. Kyberavaruudessa heikko ja vahva kohtaavat tasa-arvoisin ehdoin. Kyberavaruus on ylin offshore-alue, talous ilman veroja. Bermuda taivaalla timantein.

Kun tämä kaikkien aikojen suurin veroparatiisi on täysin liiketoiminnan avoinna, kaikki varat ovat pohjimmiltaan ulkomaisia varoja omistajansa harkinnan mukaan. Tämä aiheuttaa ketjureaktioita. Valtiovalta on totutettu kohtelemaan veronmaksajiaan kuin maanviljelijä lehmänsä: hän pitää ne laitumella lypsettäväksi. Pian lehmillä on siivet.

### Kansojen kosto

Kuin vihainen maanviljelijä valtio ottaa epäilemättä aluksi epätoivottuja keinoja kahlehtiakseen ja hidastaakseen pakenemassa olevaa karjaansa. Se turvautuu salaisiin ja jopa väkivaltaisiin keinoihin rajoittaakseen pääsyn vapauttaviin teknologioihin. Tällaiset ratkaisut toimivat vain väliaikaisesti, jos yhtään. 1900-luvun kansallisvaltio, kaikista esittämistään vaatimuksistaan huolimatta, nälkiintyy, kun verotulot laskevat.

Kun valtio huomaa, ettei pysty keräämään sitoutuneita menojaan verotulojen kasvattamisella, se turvautuu muihin, vielä epätoivoisempiin keinoihin. Näihin kuuluu muun muassa rahan painaminen. Hallitukset ovat totutelleet nauttimaan valuuttamonopolista, jolla ne voivat milloin tahansa arvon laskea. Tätä mielivaltaista inflaatiota on pidetty yhtenä kaikkien 1900-luvun valtioiden rahapolitiikan keskeisenä piirteenä. Jopa parhaan jälkeisen ajanjakson kansallinen valuutta, Saksan markka, menetti arvostaan 71 prosenttia 1. tammikuuta 1949–kesäkuun loppuun 1995. Samalla ajanjaksolla Yhdysvaltain dollari menetti 84 prosenttia arvostaan.[^9] Tämä inflaatio vaikutti kuin vero kaikille valuuttaa pitäneille. Kuten myöhemmin tarkastelemme, inflaatio tulonlähteenä jää suurelta osin pois käytöstä kyberrahan myötä. Uudet teknologiat mahdollistavat varallisuuden omistajille sen, että he voivat ohittaa ne kansalliset monopolit, jotka ovat nykyaikana liikkeeseen laskeneet ja sääntäneet rahaa. Itse asiassa vuonna 1997–1998 Aasian, Venäjän ja muiden kehittyvien talouksien läpikäymät luottokriisit osoittavat, että kansalliset valuutat ja kansalliset luottoluokitukset ovat aikojen saatossa vanhentuneita, eivätkä ne edistä globaalia talouden sujuvaa toimintaa. Juuri se, että kansallisvaltioiden vaatimukset edellyttävät, että kaikkien yhden lainkäyttöalueen sisällä tapahtuvien kauppojen tulee olla nimettyjä kansallisella valuutalla, luo alttiutta keskuspankkien virheille ja spekulaattoreiden hyökkäyksille, jotka lopulta laukaisevat deflaatiokriisejä yhdestä lain toiseen. Information aikakaudella yksilöt pystyvät käyttämään kybervaluuttoja ja näin julistamaan rahallisen itsenäisyytensä. Kun yksilöt voivat toteuttaa omia rahapolitiikkojaan World Wide Webin kautta, on vähemmän merkitystä – tai ei lainkaan – että valtio jatkaa teollisaikaan kuuluvien painokoneiden kontrollointia. Näiden painokoneiden merkitys maailman varallisuuden hallinnassa ylitetään matemaattisten algoritmien toimesta, joilla ei ole fyysistä olemusta. Uudella vuosituhannella yksityisten markkinoiden hallitsemat kyberrahat syrjäyttävät fiat-rahan, jota hallitukset liikkeeseen laskivat. Vain köyhät jäävät inflaation ja siitä seurannaisen deflaatioon romahtamisen uhreiksi, mikä on seurausta siitä keinotekoisesta vipuvaikutuksesta, jonka fiat-raha pistää talouteen.



Ilman totuttua mahdollisuutta verottaa ja aiheuttaa inflaatiota, hallitukset – jopa perinteisesti sivilisoituneissa maissa – muuttuvat julmiksi. Kun tuloverojen kerääminen käyrystyy mahdottomaksi, vanhemmat ja mielivaltaisemmat riistomenetelmät nousevat jälleen esiin. Hallitukset, jotka ovat epätoivoisia estääkseen varallisuuden pakenemisen oman valta-alueensa ulkopuolelle, ottavat käyttöön äärimmäisimmän muodon veronpidätyksessä – käytännössä tai jopa avoimena panttivankien ottamisena. Onnettomat yksilöt riippumatta joutuvat erikoiskohteiksi ja pidetään lunnaina melkein keskiaikaisella tavalla. Yritykset, jotka tarjoavat palveluja, jotka helpottavat yksilöiden itsenäistymistä, altistuvat tunkeutumisen, sabotaasin ja häiriöiden kohteiksi. Mielivaltaiset omaisuuden riisutukset – jo tapahtuvat jo Yhdysvalloissa viisi tuhatta kertaa viikossa – leviävät entisestään. Hallitukset rikkovat ihmisoikeuksia, rajoittavat tiedon vapaata virtausta, sabotoivat hyödyllisiä teknologioita ja tekevät vielä pahempia. Niiden samaa syytä varten, minkä vuoksi myöhäinen Soviet Union yritti turhaan estää pääsyn henkilökohtaisiin tietokoneisiin ja Xerox-laitteisiin, länsimaiden hallitukset pyrkivät totalitaarisin keinoin tukahduttamaan kybertaloutta.

## Ludditesin paluu

Tällaiset menetelmät saattavat osoittautua suosituiksi joidenkin väestöryhmien keskuudessa. Hyvät uutiset yksilön vapautumisesta ja autonomiasta näyttävät monille, jotka eivät kuulu kognitiiviselle eliitille, olevan huonoja uutisia. Suurin tyytymättömyys keskittyy todennäköisesti nykyisten varakkaiden maiden keskitason lahjakkuutta omaavien joukkoon. He saattavat erityisesti alkaa kokea, että informaatioteknologia uhkaa heidän elämäntapaansa. Järjestäytyneen pakon hyötyjät, mukaan lukien miljoonat, jotka saavat hallitusten uudelleenjaettua tuloa, saattavat vastustaa Sovereign Individuals –ajattelun tuomaa uutta vapautta. Heidän tyytymättömyytensä kuvastaa totuutta, että "mihin seisot, määräytyy sen mukaan, missä istut."

> Joskus mietin, kuinka voisin kokea sellaista syvää kärsimystä, joka koskee pienen joukon miesten kohtaloa, joita en tuntenut, kun he pelasivat peliä toista joukkoa tuntemattomia vastaan isossa kentässä satojen kilometrien päässä. Vastaus on yksinkertainen. Rakastin joukkujani. Vaikka se oli riskialtista, välittäminen oli sen arvoista. Urheilu sai vereni kiehumaan, innoitti minua ja sai sydämeni lyömään kovemmin. Pidin siitä, että minulla oli panos. Elämä oli elävämpää kilpailun aikana.  
– Craig Lambert

Olisi kuitenkin harhaanjohtavaa katsoa, että kaikki tulevassa siirtymäkriisissä syntyvät huonot tuntemukset johtuvat yksinomaan paljaasta halusta elää toisen kustannuksella. Tilanteeseen liittyy paljon enemmän. Ihmiskunnan luonteen ominaisuudet viittaavat siihen, että tulevassa ludditeja koskevassa reaktiossa on väistämättä mukana vääristyneitä moraalisia ulottuvuuksia. Ajattele sitä niin kuin paljaata halua, johon on laitettu moraalinen peruukki. Tarkastelemme siirtymäkriisin moraalisia ja moraalismisia ulottuvuuksia. Itsekeskeinen, tietoisesti suuntautunut ahneus motivoi tekoja paljon vähemmän kuin itsesiveä oikeamielisyyden raivo. Sillä aikaa kun 1900-luvun kansalaismyytteihin nojaaminen alkavat nopeasti murentua, niitä ei kuitenkaan puutu todellisia uskovia. Jokainen, joka saavutti täysi-ikäisyyden 1900-luvulla, on opetettu 1900‑luvun kansalaisen velvollisuuksista ja vastuista. Teollisyhteiskunnan jäänteiset moraaliset imperatiivit stimuloivat ainakin joitakin neo‑ludditeja hyökkäyksiä informaatioteknologiaa vastaan.

Tässä mielessä tämä tuleva väkivalta tulee ainakin osittain ilmaisemaan sitä, mitä kutsumme "moraaliseksi anakronismiksi" – toisin sanoen sen moraalisten sääntöjen soveltamista, jotka on otettu yhdestä taloudellisen elämän vaiheesta toisen olosuhteisiin. Jokainen yhteiskunnan vaihe vaatii omat moraaliset sääntönsä, jotka auttavat yksilöitä välttämään juuri heidän kohtaamissaan valintatilanteissa yleisiä kannustinansaan liittyviä ansalankoja. Aivan kuten maanviljelysyhteiskunta ei voisi elää muuttoliikkeessä toimivan Eskimo-yhteisön moraalien mukaan, samoin Information Society ei kykene täyttämään niitä moraalisia vaatimuksia, jotka syntyivät militantin 1900-luvun teollivaltion menestyksen edistämiseksi. Selitämme miksi.

Seuraavina vuosina moraalinen anakronismi tulee näkyviin Lännen ydinkansojen keskuudessa samalla tavalla kuin sitä on viimeisten viiden vuosisadan aikana havaittu reuna-alueilla. Länsimaisten siirtolaisten ja sotaretkien aikana syntyi tällaisia kriisejä, kun he kohtasivat alkuperäiskansoja, jotka elivät metsästys-keräilyelämäntavan mukaisesti, sekä niitä kansoja, joiden yhteiskunnat olivat edelleen järjestäytyneet maanviljelyn pohjalta. Uusien teknologioiden tuominen anakronistisissa olosuhteissa aiheutti hämmennystä ja moraalisia kriisejä. Kristillisten lähetyssaarnaajien menestys, joilla he käänsivät miljoonia alkuperäiskansoja uskoon, voidaan suuressa määrin selittää niillä paikallisilla kriiseillä, joita ulkopuolelta yllättäen tuodut uudet valtarakenteet aiheuttivat. Tällaiset kohtaamiset toistuivat yhä uudelleen 1500-luvulta 1900-luvun alkuun, ja odotamme vastaavia ristiriitoja uuden vuosituhannen alussa, kun Information Society syrjäyttää teollisuusrakenteisiin perustuvat yhteiskuntajärjestelmät.

### Nostalgia pakottamisesta

Sovereign Individualin nousua ei tule täysin tervetulleeksi historiallisen uuden vaiheen lupauksena, edes niiden keskuudessa, jotka siitä hyötyvät eniten. Kaikki tuntevat jonkinlaista epävarmuutta, ja monet halveksivat innovaatioita, jotka heikentävät alueellista kansallisvaltiota. On inhimillisenä totuutena, että minkä tahansa radikaalin muutoksen nähdään lähes aina dramaattisena kääntymyksenä huonompaan suuntaan. Viisisataa vuotta sitten Burgundin herttuan ympärille kokoontuneet hovin jäsenet olisivat sanoneet, että kehittyvät innovaatiot, jotka murentavat feodalismia, ovat pahuutta. He ajattelivat maailman olevan nopeasti liukumassa alamäkeen juuri sillä hetkellä, kun myöhempien historioitsijoiden näkökulmasta renessanssissa koettiin inhimillisen potentiaalin räjähdys. Samoin se, mitä jonain päivänä voidaan nähdä uutena renessanssina seuraavan vuosituhannen näkökulmasta, vaikuttaa pelottavalta väsähtäneiden 1900-luvun silmissä.

On suuri todennäköisyys, että jotkut uusista tavoista loukkaantuvat sekä monet, jotka kokevat niitä haitallisiksi, reagoivat epämiellyttävästi. Heidän nostalgiansa pakottamisesta muuttuu todennäköisesti väkivaltaiseksi. Kohtaamiset näiden uusien "Luddiittien" kanssa tekevät siirtymisestä radikaaleihin uusiin sosiaalisen järjestäytymisen muotoihin ainakin osittain huonoja uutisia kaikille. Valmistaudu väistymään. Koska muutoksen vauhti ylittää monien elossa olevien sukupolvien moraalisen ja taloudellisen sopeutumiskyvyn, voit odottaa näkeväsi kiihkeää ja mustamielistä vastarintaa Information Revolutionia kohtaan, huolimatta sen suuresta lupauksesta vapauttaa tulevaisuus.

Sinun on ymmärrettävä ja varauduttava tällaisiin epämiellyttäviin tilanteisiin. Edessä on siirtymäkriisi. Deflatoriset koettelemukset – kuten aasialainen tartunta, joka repäisi läpi Kaukoidästä Venäjälle ja muihin nouseviin talouksiin vuosina 1997 ja 1998 – puhkeavat satunnaisesti, kun teollisaikakaudelta periytyneet vanhentuneet kansalliset ja kansainväliset instituutiot osoittautuvat riittämättömiksi uuden, hajautetun ja monikansallisen talouden haasteisiin.

Uudet tieto- ja viestintäteknologiat ovat modernia valtiota alistavampia kuin mikään sen hallitsevuuteen kohdistunut poliittinen uhka siitä lähtien, kun Columbus purjehti. Tämä on tärkeää, sillä vallassa olevat eivät ole harvoin reagoineet rauhallisesti sellaisiin kehityskulkiin, jotka ovat heikentäneet heidän auktoriteettiaan. He eivät todennäköisesti reagoi nyt rauhanomaisesti.

Uuden ja vanhan välinen ristiriita tulee muovaamaan uuden vuosituhannen varhaisia vuosia. Odotamme sen olevan aikaa suurta vaaraa ja suuria palkkioita, aikaa, jolloin tietyillä alueilla sivistys vähenee merkittävästi ja toisilla se laajenee ennennäkemättömälle tasolle. Yhä itsenäisemmät yksilöt ja konkurssiin menneet, epätoivoiset hallitukset kohtaavat toisensa uuden jakolinjan yli. Odotamme näkevämme radikaalin uudelleenjärjestelyn suvereniteetin luonteessa ja politiikan käytännöllisen kuoleman ennen siirtymän päättymistä; sen sijaan, että valtio dominoisi ja kontrolloisi resursseja, olet tuomittunut näkemään lähes kaikkien hallitusten nykyisten palveluiden yksityistämistä. Tieto- ja viestintäteknologia tuhoaa valtion kyvyn periä palveluistaan korkeampia maksuja kuin mitä ne ovat niiden maksajille todellisuudessa arvoltaan.

> Hallitusten täytyy selviytyä siitä, mitä suvereniteetti tarkoittaa. -- Robert Martin

### Suvereniteetti markkinoiden kautta

Siihen määrin, kuin harvat yhdentuhatta vuotta sitten olisivat osanneet kuvitella, yksilöt saavuttavat yhä enemmän autonomiaa alueellisten kansallisvaltioden yli markkinamekanismien kautta. Kaikki kansallisvaltiot ovat uhattuna konkurssilla ja niiden auktoriteetti rappeutuu nopeasti. Vaikka ne ovatkin mahtavia, niiden säilyttämä voima on kyky tuhota, ei käskynannon. Niiden mantereiden väliset ohjusjärjestelmät ja lentotukialukset ovat jo artefakteja – yhtä vaikuttavia ja hyödyttömiä kuin feodaalisen järjestelmän viimeinen sothevonen.

Tietotekniikka mahdollistaa markkinoiden dramaattisen laajenemisen muuttamalla tapaa, jolla omaisuutta tuotetaan ja suojellaan. Tämä on todellakin vallankumouksellista – se lupaa olla teollisyhteiskunnalle vielä mullistavampaa kuin ruudin käyttöönotto feodaaliviljelylle. Vuoden 2000 muutos merkitsee [^11] suvereniteetin kaupallistamista ja politiikan kuolemaa, aivan kuten aseet ennustivat valanperusteisen feodaalisuuden loppua. Kansalaisuus katoaa samalla tavalla kuin ritarillisuus.

Uskomme, että yksilöllisen taloudellisen suvereniteetin aikakausi on tulossa. Aivan kuten terästehtaat, puhelinyhtiöt, kaivosyritykset ja rautatiet, jotka aikoinaan olivat kansallistettuja, on nyt nopeasti yksityistetty ympäri maailmaa, pian näette yksityistämisen täydellisimmän muodon – yksilön laaja-alaisen denationalisaation. Uuden vuosituhannen suvereeni yksilö ei enää ole valtion omaisuutta, de facto esine valtiovarainhuoneen taseessa. Vuoden 2000 siirtymän jälkeen denationalisoidut kansalaiset eivät enää ole lainkaan kansalaisia, vaan asiakkaita.

Kaistanleveys päihittää rajat

Suvereniteetin kaupallistaminen tekee kansallisvaltion kansalaisuuden ehdoista yhtä vanhanaikaisia kuin ritarilliset valat vaikuttivat feodaalisuuden romahtamisen jälkeen. Sen sijaan, että ihmiset olisivat verovelvollisia vahvan valtion kansalaisina, 2000-luvun suvereeni yksilöt tulevat toimimaan asiakkaina hallituksissa, jotka operoivat "uudessa loogisessa tilassa". He neuvottelevat saadakseen tarvitsemansa minimaalisen hallinnon ja maksavat siitä sopimuksen mukaan. Tietoajan hallitukset organisoidaan eri periaatteiden mukaisesti kuin mitä maailma on tottunut viime vuosisatojen aikana.

Jotkut toimivaltiot ja suvereniteetit muodostetaan "assortatiivisen sovittamisen" kautta, järjestelmän avulla, jossa yhteenkuuluvuudet, mukaan lukien kaupalliset yhteenkuuluvuudet, muodostavat perustan, jonka varaan virtuaaliset toimivaltiot ansaitsevat uskollisuutta. Harvinaisissa tapauksissa uudet suvereniteetit voivat olla selviytyjiä keskiaikaisista järjestöistä, kuten 900 vuotta vanhasta Sovereign Military Hospitaller Order of St. John of Jerusalem, of Rhodes and of Malta –järjestöstä. Tunnetumpana nimellä Knights of Malta, kyse on rikkaiden katolilaisten yhteenkuuluvuusryhmästä, jonka jäsenmäärä on 10 000 ja vuositulot useiden miljardien luokkaa. Knights of Malta myöntää omat passinsa, postimerkkinsä ja rahansa, ja ylläpitää täysiä diplomaattisia suhteita seitsemänkymmeneen maahan. Kirjoittaessamme se neuvottelee Republic of Malta -tasavallan kanssa saadakseen takaisin Fort St. Angelo -linnoituksen hallintaansa. Linnoituksen haltuunotto antaisi Knightsille sen puuttuvan ainesosan alueellisuutta, joka mahdollistaisi sen tunnustamisen suvereniteetiksi.

Knights of Malta voisi jälleen nousta suvereeniksi mikrostaatiksi, välittömästi pitkän historian myötä laillistettuna. Fort St. Angelosta Knights of Malta torjuivat turkkilaiset vuoden 1565 Suurlepokseen aikana. Todellakin, he hallitsivat Maltaita monia vuosia sen jälkeen, kunnes Napoleoni karkotti heidät vuonna 1798. Jos Knights of Malta palaisi seuraavien vuosien aikana, ei voisi olla selvempää todisteita siitä, että moderni kansallisvaltiojärjestelmä, joka astui käyttöön Ranskan vallankumouksen jälkeen, oli vain jakso pitkässä historian virrassa, jossa monenlaisten suvereniteettien samanaikainen olemassaolo on ollut normaalia.

Toinen, aivan erilainen malli postmodernille suvereniteetille, joka perustuu assortatiiviseen sovittamiseen, on Iridium-satelliittipuhelinverkko. Ensisilmäyksellä saattaa vaikuttaa oudolta käsitellä matkapuhelinpalvelua ikään kuin se olisi suvereniteetti. Kuitenkin Iridium on jo saanut kansainvälisten viranomaisten tunnustuksen virtuaalisena suvereniteettina. Kuten tiedätte, Iridium on maailmanlaajuinen matkapuhelinpalvelu, joka mahdollistaa tilaajiensa vastaanottaa puheluita yhdellä numerolla, missä tahansa he ovat planeetalla – aina Featherstonista, Uudesta-Seelannista Bolivian Chacon. Jotta puhelut voitaisiin reitittää Iridium-tilaajille kaikkialla maailmassa, ottaen huomioon globaalin telekommunikaatioarkkitehtuurin, kansainvälisten telekom-viranomaisten oli sovittava tunnustavansa Iridium virtuaalisena maana, omalla maiden koodilla: 8816. Loogisesti ajatellen on lyhyt matka virtuaalimaan, joka koostuu satelliittipuhelintilaajista, kohti suvereniteettia entistä yhtenäisemmille virtuaaliyhteisöille World Wide Webissä, jotka ylittävät rajat.

Kaistanleveyden kasvun myötä viestintävälineiden kantokyky on kasvanut nopeammin kuin laskentateho moni kertaa transistoreiden keksimisen jälkeen. Jos tämä trendi kohti suurempaa kaistanleveyttä jatkuu, kuten uskomme sen olevan, on vain muutaman vuoden kysymys – pian vuosituhannen vaihtuessa – ennen kuin kaistanleveys tulee riittävän laajaksi tekemään teknisesti mahdolliseksi niin sanotun "metaverse"-maailman, vaihtoehtoisen kyberavaruuden, jonka science fiction -kirjailija Neal Stephenson on kuvannut. Stephensonin "metaverse" on tiheä virtuaaliyhteisö, jolla on omat lakinsa. Uskomme, että on väistämätöntä, että kyberekonomian vaurastuessa sen osallistujat pyrkivät ja saavat poikkeuksia kansallisvaltioiden anakronistisista laeista. Uudet kyberyhteisöt ovat vähintään yhtä varakkaita ja päteviä edistämään etujaan kuin Sovereign Military Hospitaller Order of St. John of Jerusalem, of Rhodes and of Malta –järjestö. Todellakin, ne pystyvät paremmin asettamaan itsensä, kiitos laajojen viestintä- ja tietovaltasodankäynnin mahdollisuuksien. Tarkastelemme vielä muitakin malleja hajanaisesta suvereniteetista, joissa pienet ryhmät voivat tehokkaasti vuokrata heikkojen kansallisvaltioiden suvereniteetin ja harjoittaa omia talousparatiisejaan aivan kuten nykyisin lisensoidaan vapaakauppaportteja ja vapaakauppa-alueita.



Uusi moraalinen sanasto tulee olemaan tarpeen kuvaamaan suvereenien yksilöiden välisiä suhteita ja sitä, mitä hallinnosta on jäljellä. Epäilemme, että kun näiden uusien suhteiden ehdot kirkastuvat, ne loukkaavat monia, jotka ovat kasvaneet "kansalaisina" kaksikymmentäluvun kansallisvaltioissa. Kansojen loppu ja yksilön "denationalisointi" vähentävät joitakin lämpimästi arvostettuja käsityksiä, kuten "tasavertaista suojaa lain edessä", jotka edellyttävät vallankäyttösuhteita, jotka ovat pian vanhentuneita. Kun virtuaaliyhteisöt saavat lisää yhteenkuuluvuutta, ne vaativat, että niiden jäseniä tullaan pitämään vastuullisina omien lakien mukaisesti, eikä entisten kansallisvaltioiden lakien mukaisesti, joissa he sattuvat olemaan. Moninkertaiset oikeusjärjestelmät tulevat jälleen elämään samalla maantieteellisellä alueella, kuten ne elivät muinoin ja keskiajalla.

Aivan kuten yritykset säilyttää haarniskaisiin pukeutuneiden ritarien voimaa olivat tuomittuja epäonnistumaan ruutiaseiden edessä, samoin modernit nationalismia ja kansalaisuutta koskevat käsitykset ovat määrätty lyhytpiiristymään mikroteknologian vuoksi. Itse asiassa ne tulevat lopulta muuttumaan koomikoksi, aivan kuten viidestoista vuosisadan feodaalin pyhät periaatteet laskivat pilkaan kuudennella vuosisadalla. Kaksikymmentäluvun hyvin arvostetut kansalaiset käsitykset tulevat uusille sukupolville koomikkana anakronismeina vuoden 2000 muodonmuutoksen jälkeen. 2000-luvun Don Quixote ei tule olemaan ritariritari, joka kamppailee feodaalin loistojen herättämiseksi, vaan toimistoherra ruskeassa puvussa, veronkerääjä, joka kaipaa kansalaista tarkastettavaksi.

## Rajaseutujen lakien elvyttäminen

Harvemmin ajattelemme hallituksia kilpailevina toimijoina paitsi kaikkein laajassa merkityksessä, joten nykyinen intuitio suvereniteetin laajuudesta ja mahdollisuuksista on atrofioitunut. Aiemmin, kun vallankäyttöä oli vaikeampaa ryhmille, jotka yrittivät tehdä vakaata pakko-monopolia, valta oli usein hajaantunutta, lainkäyttöalueet osittain päällekkäin, ja erilaiset toimijat harjoittivat yhtä tai useampaa suvereniteetin ominaisuutta. Ei ollut harvinaista, että nimellinen ylin valtias nautti todellisuudessa vain vähän valtaa käytännössä. Nyt kansallisvaltioita heikommat hallitukset kohtaavat jatkuvaa kilpailua kyvyssään asettaa paikalliselle alueelle pakko-monopolia. Tämä kilpailu on synnyttänyt sopeutumisratkaisuja väkivallan hallintaan ja lojaalisuuden houkuttelemiseen, jotka tulevat pian uudistumaan.

Kun herrasten ja kuninkaiden ulottuvuus oli heikko ja yhden tai useamman ryhmän vaatimukset osittain päällekkäin rajalla, tapahtui usein niin, ettei kumpikaan pystynyt ratkaisevasti hallitsemaan toisiaan. Keskiajalla oli lukuisia rajaseutuja eli "march"-alueita, joissa suvereniteetit sulautuivat yhteen. Nämä väkivaltaiset rajat säilyivät vuosikymmeniä tai jopa vuosisatoja Euroopan rajaseuduilla. Oli rajaseutuja kelttien ja englantilaisten hallintojen välillä Irlannissa; Walesin ja Englannin, Skotlannin ja Englannin, Italian ja Ranskan, Ranskan ja Espanjan, Saksan ja Keski-Euroopan slaavilaisten rajojen välillä sekä Espanjan kristillisten valtakuntien ja Granadan islamilaisen valtakunnan välillä. Tällaiset rajaseutualueet kehittivät omaleimaisia institutionaalisia ja oikeudellisia muotoja, joita todennäköisesti näemme uudelleen seuraavalla vuosituhannella. Kilpailevien auktoriteettien aseman vuoksi rajaseudun asukkailla oli yleensä mahdollisuus valita, kenen lakien mukaan heidän oli noudatettava, ja verojen maksaminen oli usein vähäistä. Tällainen valinnanvapaus toteutui oikeudellisten käsitteiden, kuten "avowalin" ja "distraintin", kautta – käsitteiden, jotka ovat lähes kadonneet nykyajassa. Odotamme, että tällaiset käsitteet nousevat uudelleen keskeisiksi piirteiksi informaatioyhteiskuntien oikeudessa.



### Kansallisuuden ylittäminen

Ennen kansallisvaltioita oli vaikea määritellä tarkasti, kuinka monta suvereniteettia maailmassa oli, sillä ne päällekkäistyivät monimutkaisilla tavoilla ja useat erilaiset organisaatiomallit käyttivät valtaa. Niin tulee käymään jälleen. Alueiden rajat taipuvat muodostumaan selkeiksi ja kiinteiksi kansallisvaltiojärjestelmässä, mutta ne hämärtyvät taas informaatiokaudella. Uudella vuosituhannella suvereniteetti jakautuu jälleen: uusia toimijoita syntyy, jotka harjoittavat joitakin, mutta eivät kaikkia niitä ominaisuuksia, joita olemme liittäneet hallituksiin.

Jotkut näistä uusista toimijoista, kuten Knights Templar ja muut keskiaikaisten uskonnollisten sotilaallisten järjestöjen kaltaiset tahot, saattavat hallita huomattavaa varallisuutta ja sotilaallista voimaa ilman, että ne hallitsevat mitään kiinteää aluetta. Niitä organisoidaan periaatteilla, jotka eivät liity lainkaan kansallisuuteen. Keskiajalla Euroopan osissa toimineiden uskonnollisten yhdistysten jäsenet ja johtajat, jotka käyttivät suvereenia valtaa, eivät missään määrin ammentaneet valtaansa kansallisesta identiteetistä. He edustivat kaikkia etnisiä taustoja ja julistivat kuuluvansa Jumalalle – eivätkä millekään sellaisille yhteisille siteille, joita kansallisuuteen kuuluvien odotetaan jakavan.

### Kyberavaruuden kaupparepublikat

Huomaat myös jälleen nousevan kauppiaiden ja varakkaiden yksilöiden yhdistysten ilmiön, joilla on osittainen suvereniteetti, kuten Hanse (kauppiaiden liitto) keskiajalla. Ranskalaisissa ja flaamilaisissa messuissa toiminut Hanse kasvoi kattamaan kuusikymmentä kaupunkia.[^10] "Hanseatie League", kuten sitä redundanttisti englanniksi kutsutaan (kirjaimellisesti "Leaguely League"), oli saksalaisgermaanisten kauppakuntien organisaatio, joka tarjosi jäsenilleen suojaa ja neuvotteli kauppasopimuksista. Se saavutti osittaisen suvereniteetin useissa Pohjois-Euroopan ja Itämeren kaupungeissa. Tällaiset toimijat nousevat uudelleen elävän kansallisvaltion tilalle uudella vuosituhannella, tarjoten suojaa ja auttaen sopimusten täytäntöönpanossa epävarmassa maailmassa.

Lyhyesti sanottuna tulevaisuus todennäköisesti hämmentää niitä, jotka ovat sisäistäneet 1900-luvun teollisen yhteiskunnan kansalaismyyttejä. Näihin kuuluu muun muassa sosiaalidemokratian harhakuvat, jotka kerran innostivat ja motivoivat lahjakkaimpia mieliä. Ne edellyttävät, että yhteiskunnat kehittyvät tavoilla, joita hallitukset haluavat, mieluiten mielipidemittauksien ja huolellisesti laskettujen äänestysten mukaisesti. Tämä ei ole koskaan ollut yhtä totta kuin viisikymmentä vuotta sitten – nyt se on anakronismi, yhtä paljon teollisuusajan artefakti kuin ruostuva savupiippari. Kansalaismyytit heijastavat eivät pelkästään asennetta, joka näkee yhteiskunnan ongelmat insinööritieteellisesti ratkaistavina, vaan myös väärää itseluottamusta siitä, että resurssit ja yksilöt pysyvät tulevaisuudessakin yhtä alttiina poliittiselle pakottamiselle kuin olivat 1900-luvulla. Emme usko sitä. Markkinavoimat, eivät poliittiset enemmistöt, pakottavat yhteiskunnat uudelleenjärjestäytymään tavoilla, joita julkinen mielipide ei ymmärrä eikä toivota. Naiivi ajatus siitä, että historia olisi sitä, mitä ihmiset haluavat sen olevan, osoittautuu sitten valtavasti harhaanjohtavaksi.

Siksi on ratkaisevan tärkeää, että näet maailman uudella tavalla. Tämä tarkoittaa sitä, että tarkastelet asioita ulkopuolelta sisäänpäin ja analysoit uudelleen paljon sitä, mitä olet todennäköisesti pitänyt itsestäänselvyyksinä. Näin pystyt saavuttamaan uuden ymmärryksen. Jos et onnistu ylittämään perinteistä ajattelua aikana, jolloin se menettää yhteyden todellisuuteen, joudut todennäköisemmin epäjärjestyksen epidemian uhriksi. Epäjärjestys synnyttää virheitä, jotka voivat uhata yritystäsi, sijoituksiasi ja elämäntapaasi.

> Universumi palkitsee meitä, kun ymmärrämme sitä, ja rankaisee, kun emme ymmärrä sitä. Kun ymmärrämme universumia, suunnitelmamme onnistuvat ja tunnemme olomme hyväksi. Vastaavasti, jos yritämme lentää hyppäämällä kalliolta ja vispaamalla käsiämme, universumi tappaa meidät.[^11] -- JACK COHEN AND IAN STEWART

### Seeing Anew

Valmistautuaksesi tulevaan maailmaan sinun on ymmärrettävä, miksi se tulee olemaan erilaista kuin mitä useimmat asiantuntijat kertovat. Tämä edellyttää, että tarkastelet läheisesti muutoksen piileviä syitä. Olemme pyrkineet tekemään tämän epätavanomaisella analyysillä, jota kutsumme megapolitiikan tutkimukseksi. Kahdessa aiemmassa osassa, Blood in the Streets ja *The Great Reckoning*, väitimme, että tärkeimmät muutoksen aiheuttajat eivät löydy poliittisista manifesteista tai kuolleiden taloustieteilijöiden julistuksista, vaan piilevistä tekijöistä, jotka muuttavat rajat, joilla valtaa käytetään. Usein hienovaraiset muutokset ilmastossa, topografiassa, mikrobeissa ja teknologiassa muuttavat väkivallan logiikkaa. Ne muokkaavat tapaa, jolla ihmiset järjestäytyvät elinkeinojensa ja puolustuksensa osalta.

Huomaa, että tapamme ymmärtää, miten maailma muuttuu, on hyvin erilainen verrattuna useimpien ennustajien lähestymistapaan. Emme ole asiantuntijoita missään – emmekä väitele tietävämme jossain tietyssä “aiheessa” paljon enemmän kuin ne, jotka ovat koko uransa ajan kehittäneet erittäin erikoistunutta osaamista. Päinvastoin, katsomme asioita ulkopuolelta sisään. Olemme perehtyneitä niihin aiheisiin, joista teemme ennusteita. Eniten tämä tarkoittaa sitä, että havainnoimme, missä välttämättömyyden rajat kulkevat. Kun nämä rajat muuttuvat, yhteiskunta muuttuu välttämättä, riippumatta siitä, mitä ihmiset vastakkaisesti toivovat.

Mielestämme yhteiskuntien kehityksen avain on ymmärtää ne tekijät, jotka määrittävät väkivallan käyttämisen kustannukset ja palkkiot. Jokainen ihmisten yhteisö, metsästysseurasta imperiumiin, on muovautunut megapoliittisten tekijöiden vuorovaikutuksesta, jotka asettavat vallitsevan version luonnon laeista. Elämä on aina ja kaikkialla monimutkaista. Karitsa ja leijona ylläpitävät herkkää tasapainoa, vuorovaikuttaen marginaalilla. Jos leijonat yhtäkkiä olisivat nopeampia, ne saisivat kiinni saaliista, joka nyt karkaa. Jos karitsat yhtäkkiä saisivat siivet, leijonat nälkiintyisivät. Kyky käyttää ja puolustautua väkivaltaa vastaan on ratkaiseva muuttuja, joka muuttaa elämää marginaalilla.

Asetamme väkivallan keskeiseksi megapoliittisen teoriamme osaksi hyvästä syystä. Väkivallan hallinta on jokaisen yhteiskunnan tärkein dilemma. Kuten kirjoitimme teoksessa *The Great Reckoning*:

> Syynä siihen, että ihmiset turvautuvat väkivaltaan, on se, että se usein kannattaa. Joissain suhteissa yksinkertaisin tapa hankkia rahaa on ottaa se. Tämä pätee yhtä lailla armeijaan, joka valtaa öljykentän, kuin yksittäiseen hirmuun, joka ryöstelee lompakon. Kuten William Playfair kirjoitti, "valta on aina etsinyt helpointa tietä vaurauteen hyökkäämällä niiden kimppuun, joilla sitä on hallussaan."

> Haaste vauraudelle on juuri se, että saalistava väkivalta todella maksaa joissain olosuhteissa. Sota muuttaa asioita. Se muuttaa säännöt. Se muuttaa omaisuuserien ja tulojen jakautumista. Se jopa määrittää, kuka elää ja kuka kuolee. Juuri se, että väkivallan käyttäminen kannattaa, tekee siitä vaikeasti hallittavaa.[^12]

Näin ajatellen on auttanut meitä ennakoimaan useita kehityskulkuja, joista paremmin perillä olevat asiantuntijat vakuuttivat, etteivät ne koskaan tapahtuisi. Esimerkiksi Blood in the Streets, joka julkaistiin varhain vuonna 1987, oli yrityksemme kartoittaa suuren megapoliittisen vallankumouksen ensimmäisiä vaiheita, jotka ovat nyt käynnissä. Väitimme silloin, että teknologinen muutos hajottaa maailman vallan suhteita. Pääpointtiimme kuuluivat muun muassa seuraavat seikat.

– Me sanoimme, että amerikkalainen ylivalta oli laskussa, mikä johtaisi taloudellisiin epätasapainoihin ja ahdinkoon – mukaan lukien toinen 1929-tyylinen pörssiromahdus. Asiantuntijat olivat lähes yksimielisiä kieltäessään, että tällaista voisi tapahtua. Kuitenkin kuuden kuukauden sisällä, lokakuussa 1987, markkinoita ravisteli vuosisadan väkivaltaisin myyntiaalto.

– Kerroimme lukijoille, että kommunismin romahdus olisi odotettavissa. Taas kerran asiantuntijat nauroivat. Kuitenkin vuosi 1989 toi ne tapahtumat, “joita kukaan ei olisi voinut ennustaa.” Berliinin muuri kaatui, kun vallankumoukset pyyhkäisivät kommunistiset hallinnot Itämereltä Bukarestiin.

– Selitimme, miksi monietninen imperiumi, jonka Bolshevikien nomenklatura oli perinyt tsaareilta, “väistämättä hajoaisi.” Joulukuun lopulla 1991 vasara–ja linkkulippu laskettiin alas Kremlin yllä viimeisen kerran, kun Neuvostoliitto lakkasi olemasta.

– Reaganin asevarustelun huippuvaiheessa väitimme, että maailma seisoi merkittävän asekotomuksen kynnyksellä. Myös tätä pidettiin epätodennäköisenä, ellei jopa naurettavana. Kuitenkin seuraavat seitsemän vuotta toivat ensimmäisen maailmansodan päättymisen jälkeen kaikkein laaja-alaisimman asekotomuksen.

– Aikana, jolloin Pohjois-Amerikan ja Euroopan asiantuntijat osoittivat Japaniin tukeakseen näkemystä siitä, että hallitukset voivat onnistuneesti manipuloida markkinoita, me sanoimme toisin. Ennustimme, että japanilaisten rahoitusvarojen buumi päättyisi romahdukseen. Pian Berliinin muurin kaatumisen jälkeen japanilainen pörssi romahduttiin, menettäen lähes puolet arvostaan. Uskomme yhä, että sen lopullinen pohja saattaa vastata tai jopa ylittää sen 89 prosentin pudotuksen, jonka Wall Street koki romahtamisen jälkeen vuonna 1929.

- Kun lähes kaikki – keskiluokkaisista perheistä aina maailman suurimpiin kiinteistösijoittajiin – näyttivät uskovan, että asuntomarkkinat voisivat vain nousta eikä laskea, varoimme, että kiinteistökupla on tulossa. Neljän vuoden sisällä maailmanlaajuisesti kiinteistösijoittajat menettivät yli 1 biljoonaa dollaria, kun kiinteistöjen arvot laskivat.

- Jo kauan ennen kuin asiantuntijoille kävi ilmi, olemme *Blood in the Streets* -teoksessamme selittäneet, että sinimustien työntekijöiden tulot olivat laskeneet ja niiden oli määrä jatkaa laskuaan pitkällä aikavälillä. Kun kirjoitamme tätä lähes vuosikymmenen kuluttua, maailman on vihdoin alkanut ymmärtää, että näin on. Yhdysvalloissa keskimääräiset tuntipalkat ovat laskeneet alle sen tason, jonka saavutettiin toisen Eisenhowerin hallinnon aikana. Vuonna 1993 keskimääräiset vuosittain laskutetut tuntipalkat vakioarvoissa olivat 18 808 dollaria, kun taas vuonna 1957, kun Eisenhower vannoi toiselle kaudelleen, Yhdysvalloissa vuosittain laskutetut keskimääräiset tuntipalkat olivat 18 903 dollaria.

- Vaikka *Blood in the Streets* -teoksen pääteemoista onkin käynyt uskomattoman tarkkoja jälkiviisauden valossa, vain muutama vuosi sitten niitä pidettiin tavallisen ajattelun vartijoiden toimesta täysipiippuisena hölynpölynä. Vuonna 1987 *Newsweek* -lehden arvostelija kuvasi myöhäisen teollistuneen yhteiskunnan suljettua mielentilaa hylkäädessään analyysimme "ajatuksettomana hyökkäyksenä järkeen."

- Voisit kuvitella, että *Newsweek* ja vastaavat julkaisut olisivat ajan myötä ymmärtäneet, että analyysimme oli paljastanut jotain hyödyllistä siitä, miten maailma muuttui. Ei ollenkaan. Ensimmäistä versiota *The Great Reckoning* -teoksesta tervehti sama nauraen halveksiva vihamielisyys, jolla myös *Blood in the Streets* otettiin vastaan. Ei vähempää auktoriteettia kuin *Wall Street Journal* hylkäsi kategorisesti analyysimme "sinun dopey tätisi puheeksi."

- Kaikki tämä naurun remakan ohi, *The Great Reckoning* -teoksen teemat osoittautuivat vähemmän naurettavilta kuin ortodoksian vartijat väittelivät.

Laajensimme ennustustamme Neuvostoliiton tuhosta ja pohdimme, miksi Venäjä sekä muut entiset neuvostotasavallat kohtasivat tulevaisuutta, jolle ominaisia olivat lisääntyvä sisäinen levottomuus, hyperinflaatio ja laskeva elintaso.

- Selitimme, miksi 1990-luku tulisi olemaan supistamisen vuosikymmen – ensimmäistä kertaa nähtiin maailmanlaajuinen hallitusten ja yritysten koon pienentäminen.

- Ennustimme myös, että tulonjaon ehtoja määriteltäisiin radikaalisti uudelleen, ja etuustasot leikattaisiin jyrkästi. Kryptavia merkkejä finanssikriisistä ilmeni Kanadasta Ruotsiin, ja amerikkalaiset poliitikot alkoivat puhua "hyvinvoinnin loppumisesta sellaisena kuin sen nykyään tunnemme."

- Odotimme ja selitimme, miksi "uusi maailmanjärjestys" osoittautuisi "uutena maailman sekasorroksi". Jo kauan ennen kuin Bosnian kauheudet hallitsivat uutisotsikoita, varoitimme, että Jugoslavia romahtaisi sisällissotaan.

- Ennen kuin Somalia luisui anarkiaan, selitimme, miksi Afrikassa hallitusten odotettu romahtaminen johtaisi siihen, että joissakin maissa hallinto asetettaisiin käytännössä vastaanottajamenettelyn piiriin.

- Ennustimme ja selitimme, miksi militantti islam syrjäyttäisi marxismin pääideologiana Länteen kanssa käydyssä vastakkainasettelussa. Vuosia ennen Oklahoma-pommitusta ja yritystä räjäyttää World Trade Center, selitimme, miksi Yhdysvallat kohtasi terrorismin lisääntymisen.

- Ennen kuin uutisotsikot kertoivat Los Angelesia, Torontoa ja muita kaupunkeja huiputtaneista mellakoista, selitimme, miksi rikollisten alakulttuurien nousu kaupunkivähemmistöjen keskuudessa loi perustan laajalle rikolliselle väkivallalle.

- Ennustimme myös *the final depression of the twentieth century*, joka alkoi Aasiassa vuonna 1989 ja on levittäytynyt reunalta kohti globaalin järjestelmän keskustaa. Sanottiin, että Japanin osakemarkkinat seuraisivat Wall Streetin mallia vuoden 1929 jälkeen, ja että tämä johtaisi luoton romahtamiseen ja lamaan. Vaikka massiivinen hallituksen interventio Japanissa ja muualla esti tilapäisesti markkinoita heijastamasta täysin luotto-olosuhteiden heikkenemistä, tämä vain siirsi ja pahensi taloudellista ahdinkoa, lisäten painetta kilpailullisille devalvaatioille ja systeemiselle luottoromahdukselle, jollaisen taloudet romahtivat maailmanlaajuisesti 1930-luvulla.

*The Great Reckoning* esitti myös useita kiistanalaisia teesejä, joita ei ole vielä vahvistettu tai jotka eivät ole saavuttaneet sitä kehitystasoa, jonka ennustimme:

- Sanottiin, että Japanin osakemarkkinat seuraisivat Wall Streetin mallia vuoden 1929 jälkeen, ja että tämä johtaisi luoton romahtamiseen ja lamaan. Vaikka työttömyysasteet Espanjassa, Suomessa ja muutamissa muissa maissa ylittivät 1930-luvun tasot, ja useat maat, mukaan lukien Japani, kokivat paikallisia lamia, systeemistä luottoromahdusta, jollainen romahti maailmanlaajuisesti 1930-luvulla, ei ole vielä tapahtunut.

Väitimme, että entisen Neuvostoliiton käskynannon ja valvonnan järjestelmän romahtaminen johtaisi ydinaseiden leviämiseen minivaltiolle, terroristien käsiin ja rikollisjengeihin. Onneksi maailmalle tämä ei ole toteutunut, ainakaan ei siinä mittakaavassa kuin pelkäsimme. Lehdistötiedotteiden mukaan Iran on ostanut useita taktisia ydinaseita mustalta markkinoilta, ja Saksan viranomaiset ovat estäneet useita yrityksiä myydä ydinmateriaaleja. Kuitenkin entisen Neuvostoliiton arsenaleista ei ole ilmoitettu ydinaseiden sijoittamisesta tai käytöstä.

Selitimme, miksi "War on Drugs" – huumausaineiden vastaista sotaa – pidettiin reseptinä, joka syrjäyttää niiden maiden poliisi- ja oikeusjärjestelmät, joissa huumeiden käyttö on laajalle levinnyttä, erityisesti Yhdysvalloissa. Niin suurten piilotettujen monopolivoittojen kera, joita kertyy vuosittain kymmeniä miljardeja dollareita, huumekauppiailla on sekä keinoja että kannustin korruptoida jopa näennäisesti vakaiden maiden järjestelmiä. Vaikka maailman media on toisinaan tuonut esiin tarinoita, jotka viittaavat huumerahojen korkean tason vaikutukseen Yhdysvaltojen poliittisessa systeemissä, koko tarinaa ei vielä ole kerrottu.

### Katsomassa siellä, missä muut eivät

Huolimatta niistä kohdista, joissa ennusteemme olivat virheellisiä tai vaikuttavat virheellisiltä nykyisen tiedon valossa, tilanne kestää tarkastelun. Paljon sitä, mikä todennäköisesti tulee esiintymään tulevissa 1990-luvun taloushistoriankirjoissa, ennustettiin, odotettiin ja selitettiin teoksessamme *The Great Reckoning*. Monet ennusteistamme eivät olleet pelkkiä trendien yksinkertaisia jatkumoita, vaan ennusteita merkittävistä poikkeuksista siitä, mitä on pidetty normaalina toisen maailmansodan jälkeen. Varoimme, että 1990-luku olisi dramaattisesti erilainen kuin edelliset viisi vuosikymmentä. Kun tarkastelemme vuosien 1991–1995 uutisia, näemme, että *The Great Reckoning* -teoksen teemat toteutuivat melkein päivittäin.

Näemme nämä kehityskulut eivät esimerkkeinä eristyksellisistä vaikeuksista tai ongelmista täällä ja siellä, vaan iskuina ja tärinöinä, jotka kulkevat saman vikaviivan varrella. Vanha järjestys romahtaa megapoliittisen maanjäristyksen seurauksena, joka mullistaa instituutiot ja muuttaa tapaamme, jolla ajattelevat ihmiset näkevät maailman.

Huolimatta siitä, että väkivallalla on keskeinen rooli maailman toiminnan määrittämisessä, se herättää yllättävän vähän vakavaa huomiota. Suurin osa poliittisista analyytikoista ja taloustieteilijöistä kirjoittaa ikään kuin väkivalta olisi pieni ärsyke, kuten kärpänen, joka surisee kakun ympärillä, eikä se ole se kokki, joka sen on leiponut.

### Toinen megapoliittinen pioneeri

Itse asiassa väkivallan roolista historiassa on ajateltu niin harvoin selkeästi, että jopa yhdelle paperisivulle voitaisiin koota bibliografia megapoliittisesta analyysista. Teoksessamme *The Great Reckoning* hyödynsimme ja laajensimme argumentteja lähes täysin unohtuneesta megapoliittisen analyysin klassikosta, William Playfairin teoksesta *An Enquiry into the Permanent Causes of the Decline and Fall of Powerful and Wealthy Nations*, joka julkaistiin vuonna 1805. Yksi lähtökohdistamme on Frederic C. Lanen työ. Lane oli keskiaikaista historiaa käsittelevä historioitsija, joka kirjoitti useita läpitunkevia esseitä väkivallan roolista historiassa 1940- ja 1950-luvuilla. Ehkä kattavin näistä oli "Economic Consequences of Organized Violence", joka julkaistiin *Journal of Economic History* -lehdessä vuonna 1958. Harvat muut kuin ammattilaiset, kuten taloustieteilijät ja historioitsijat, ovat lukeneet sen, eikä suurin osa heistä näyttänyt tunnistaneen sen merkitystä. Aivan kuten Playfairkin, Lane kirjoitti yleisölle, jota vielä ei ollut olemassa.

### Näkemyksiä informaatiokaudelle

Lane julkaisi työnsä väkivallasta ja sodan taloudellisesta merkityksestä hyvissä ajoin ennen informaatiokauden tuloa. Hän ei todellakaan kirjoittanut ennakoidessaan mikroprosessoinnin tai muiden nyt tapahtuvien teknologisten vallankumousten syntyä. Silti hänen näkemyksensä väkivallasta loivat perustan ymmärtää, miten yhteiskunta järjestetään uudelleen informaatiovallankumouksessa.

Se ikkuna, jonka Lane avasi tulevaisuuteen, oli sellainen, jonka kautta hän kurkisti menneisyyteen. Hän oli keskiaikaistaustainen historioitsija, erityisesti kauppakaupungin Venetsian tutkija, jonka kohtalo heilahtelee ja romahtaa väkivaltaisessa maailmassa. Pohtiessaan, miten Venetsia nousi ja taantui, hänen huomionsa kiinnittyi kysymyksiin, jotka voivat auttaa ymmärtämään tulevaisuutta. Hän näki, että väkivallan järjestäminen ja hallinta näyttelevät suurta roolia määritettäessä, "mikä käyttö saadaan harvinaisista resursseista." [^13]

Me uskomme, että Lane'n analyysit väkivallan kilpailullisista käytöistä kertovat meille paljon siitä, miten elämä todennäköisesti muuttuu tietotekniikan aikakaudella. Älä kuitenkaan odota, että suurin osa ihmisistä edes huomaisi – saati sitten seuraisi – näin epämuodollisen abstraktia argumentaatiota. Sillä kun maailman huomio on kiinnittynyt epärehellisiin kiistoihin ja omalaatuisiin persoonallisuuksiin, megapolitiikan harhailevat linjat jatkuvat lähes huomaamatta. Keskimääräinen pohjoisamerikkalainen on varmaankin kiinnittänyt sata kertaa enemmän huomiota O. J. Simpsoniin kuin uusiin mikroteknologioihin, jotka ovat valmiina vanhentamaan hänen työnsä ja horjuttamaan poliittista järjestelmää, johon hän turvautuu työttömyysturvaa varten.

## Toiveiden turhamaisuus

Keskittyminen siihen, mikä on perusolemuksellisesti tärkeää, ei rajoitu ainoastaan sohvakertoihin, jotka katsovat televisiota. Tavanomaiset ajattelijat kaikenlaisissa muodoissaan huomauttavat kansallisvaltion yhden oletuksen – sen, että ihmisten omaksumat näkemykset määräävät tavan, jolla maailma muuttuu. Ilmeisen hienostuneet analyytikot vaipuvat selityksiin ja ennusteisiin, jotka tulkitsevat merkittäviä historiallisia kehityskulkuja ikään kuin ne määräytyisivät toivomuksen mukaan. Huomiota herättävä esimerkki tällaista päättelyä oli juuri New York Timesin kannassa, kun kirjoitimme artikkelia "Goodbye, NationState, Hello...What?," jonka on kirjoittanut Nicholas Colchester. [^14] Aihe – kansallisvaltion kuolema – on täsmälleen se, jota käsittelemme, ja sen kirjoittaja esittäytyy erinomaisena mittarina havainnollistaakseen, kuinka kaukana ajattelumme on normista. Colchester ei ole mikään idiootti. Hän toimi Economist Intelligence Unitin toimitusjohtajana. Jos jonkun pitäisi muodostaa realistinen kuva maailmasta, sen olisi hänen. Hänen artikkelissaan käy useissa kohdissa selväksi, että "kansainvälisen hallituksen tuleminen on nyt loogisesti pysäyttämätöntä." 

Miksi? Koska kansallisvaltio horjuu eikä pysty enää hallitsemaan taloudellisia voimia.

Meidän näkemyksemme mukaan tämä oletus on lähes absurdia. Uskaltaa olettaa, että jokin tietty uusi hallintomuoto syntyisi pelkästään siksi, että toinen epäonnistuisi – se on harhaluulo. Tällaisella logiikalla Haitilla ja Zairella olisi ollut jo kauan sitten parempi hallinto, yksinkertaisesti siksi, että se, mitä heillä oli, oli niin ilmeisen puutteellista.

Colchesterin näkökulma – jota jakavat laajalti ne harvat, jotka näistä asioista pohtivat Pohjois-Amerikassa ja Euroopassa – jää täysin huomaamatta niitä suurempia megapoliittisia voimia, jotka määrittävät, minkä tyyppiset poliittiset järjestelmät ovat käytännössä mahdollisia. Tämä on tämän kirjan keskiössä. Kun otamme huomioon teknologiat, jotka muokkaavat uutta vuosituhatta, on paljon todennäköisempää, että emme näe yhtä maailmanhallintoa, vaan pikemminkin mikrohallituksia tai tiloja, jotka lähestyvät anarkiaa.

Jokaisen vakavan analyysin osalta, joka käsittelee väkivallan roolia sääntöjen määrittämisessä, joiden mukaan kaikki toimivat, on kirjoitettu kymmeniä kirjoja vehnätukien monimutkaisuudesta ja satoja lisää salaperäisistä rahoituspolitiikan osa-alueista. Paljonkin tästä kriittisten kysymysten ajattelun vajavaisuudesta, jotka oikeastaan määräävät historian kulun, johtuu todennäköisesti viimeisten vuosisatojen suhteellisesta vallan vakaudesta. Lintu, joka nukahtaa virtahevon selkään, ei ajattele menettävänsä pesäänsä ennen kuin virtahepo oikeasti liikkuu. Unet, myytit ja fantasiat näyttelevät paljon suurempaa roolia sen vaikuttamisessa, mitä pidämme "yhteiskuntatieteinä", kuin usein ajattelemme.

Tämä käy erityisen ilmi runsaasta taloudellisen oikeudenmukaisuuden kirjallisuudesta. Jokaisesta sivusta, joka on omistettu huolelliselle analyysille siitä, miten väkivalta muokkaa yhteiskuntaa ja siten asettaa rajat, joiden sisällä taloudet on toimittava, on lausuttu ja kirjoitettu miljoonia sanoja taloudellisesta oikeudenmukaisuudesta ja epäoikeudenmukaisuudesta. Kuitenkin modernin kontekstin taloudellisen oikeudenmukaisuuden määritelmät olettavat, että yhteiskuntaa hallitsee niin valtava pakottamisen väline, joka pystyy riistämään ja uudelleen jakamaan elämän hyvät asiat. Tällaista valtaa on ollut olemassa vain muutaman modernin sukupolven ajan. Nyt se on hälvenemässä.

### Big Brother on Social Security

Teollisuusteknologia antoi hallituksille 1900-luvulla enemmän kontrollivälineitä kuin koskaan aiemmin. Hetken aikaa näytti väistämättömältä, että hallitukset kehittyisivät niin tehokkaiksi väkivallan monopolisoimisessa, että yksilöllisyydelle jäisi vain hyvin vähän tilaa. Kenellekään keskitien aikaan ei näyttänyt luvattomalta Sovereign Individual -konseptin voitto.

Jotkut 1900-luvun puolivälin teräväjärkisimmistä tarkkailijoista tulivat sen päivän todisteiden perusteella vakuuttuneiksi siitä, että kansallisvaltioiden taipumus keskittää valtaa johtaisi totalitaariseen hallintaan kaikilla elämänalueilla. George Orwellin teoksessa *1984* (1949) Isoveli seurasi yksilöä turhaan, kun tämä kamppaili säilyttääkseen edes pienen marginaalin itsenäisyyttä ja itsearvostusta. Tilanne vaikutti olevan menetetty. Friedrich von Hayekin *The Road to Serfdom* (1944) esitti tieteellisemmällä otteella, että vapaus oli menettämässä arvonsa uuden taloudellisen kontrollin muotoon, joka jätti valtion kaiken hallitsijaksi. Nämä teokset on kirjoitettu ennen mikropiirien aikaa, minkä seurauksena on kehittynyt lukemattomia teknologioita, jotka parantavat pienryhmien ja jopa yksilöiden kykyä toimia itsenäisesti keskitetystä valvonnasta.

Vaikka Hayekin ja Orwellin kaltaiset tarkkailijat olivat teräviä, heidän näkemyksensä olivat liiankin pessimistisiä. Historia on tuonut mukanaan yllätyksiä. Totalitaarinen kommunismi selvisi tuskin vuoden 1984 yli. Uusi orjuuden muoto saattaa vielä nousta esiin seuraavan vuosituhannen aikana, jos hallitukset onnistuvat tukahduttamaan mikroteknologian vapauttavat puolet. On kuitenkin paljon todennäköisempää, että näemme ennennäkemättömiä mahdollisuuksia ja yksilön itsenäisyyttä. Se, mistä vanhempamme huolestivat, ei välttämättä osoittaudukaan ongelmaksi ollenkaan. Ne asiat, jotka he pitivät itsestäänselvyyksinä sosiaalisen elämän pysyvinä ja muuttumattomina piirteinä, näyttävät nyt olevan määrä kärjistyä pois.

### Ennustamisen vaarat

Ei epäilemättä otamme pientä annosta arvokkuuttamme riskiin yrittäessämme ennakoida ja selittää elämää ja sitä yhdistävää kulttuuria koskevia syvällisiä muutoksia. Useimmat ennusteet osoittautuvat ajan myötä naurettaviksi. Ja mitä dramaattisemmaksi he kuvittelevat muutoksen, sitä häpeällisemmin ne osoittautuvat vääriksi. Maailma ei lopu. Otsonikerros ei katoa. Tuleva jääkausi sulaa globaaliksi lämmöksi. Kaikista toisinviittauksista huolimatta säiliössä on edelleen öljyä. Herra Antrobus, teoksen *The Skin of Our Teeth* tavallinen mies, välttää jäätymistä, selviää sodista sekä uhattujen taloudellisten onnettomuuksien keskellä ja vanhenee huolehtimatta asiantuntijoiden tarkkaan harkituista varoituksista.

Lähes kaikki yritykset "paljastaa" tulevaisuus osoittautuvat pian koomisesti huvittaviksi. Jopa sellaisissa tapauksissa, joissa oma etu luo vahvan kannustimen selkeään ajatteluun, tulevaisuuden näkymät ovat usein likinäköisiä. Vuonna 1903 Mercedes-yhtiö totesi, että "maailmassa ei koskaan olisi noin miljoonaa autoa. Syynä oli se, että oli epätodennäköistä, että jopa miljoonaa artisanaattia maailmalla koulutettaisiin kuljettajiksi."[^15]

Tämän tiedostaminen pitäisi saada meidät vaienemaan. Mutta se ei tapahdu. Emme pelkää jonottaa saamamme osan pilkanharvoista huomautuksista. Jos teemme suuria virheitä, tulevat sukupolvet saattavat nauraa niin sydämellisesti kuin haluavat, olettaen että kukaan muistaa, mitä olimme sanoneet. Ajatuksen uskaltaminen merkitsee riskiä olla väärässä. Emme ole niin jäykkiä ja hyödytömiä, että pelkäisimme erehtymistä. Päinvastoin. Uskallamme ennemmin esittää ajatuksia, jotka saattavat osoittautua hyödyllisiksi sinulle, kuin tukahduttaisimme niitä pelossa, että ne myöhemmin näyttäisivät liioitelluilta tai kiusallisilta.

Kuten Arthur C. Clarke terävästi huomautti, kaksi pääsyytä siihen, miksi yritykset ennakoida tulevaisuutta yleensä epäonnistuvat, ovat "Failure of Nerve and Failure of Imagination."[^16] Näistä hän kirjoitti: "Failure of Nerve vaikuttaa olevan yleisempää; se ilmenee silloin, kun jopa kaikkien olennaisten faktojen valossa potentiaalinen profeetta ei kykene näkemään, että ne johtavat väistämättömään johtopäätökseen. Joissakin näistä epäonnistumisista ovat niin naurettavia, että ne ovat melkein uskomattomia."[^17]

Missä tietoveraation vallankumouksen tutkimuksemme jää puutteelliseksi – kuten se väistämättä tulee olemaan – syy johtuu enemmän mielikuvituksen puutteesta kuin hermojen heikkoudesta. Tulevaisuuden ennustaminen on aina ollut rohkea yritys, joka herättää oikeanlaista skeptisyyttä. Ehkä aika osoittaa, että johtopäätöksemme ovat hurjasti vinossa. Toisin kuin Nostradamus, emme teeskele profeettoja. Emme ennusta tulevaisuutta sekoittamalla taikasauvaa vesikulhossa tai laatimalla horoskooppeja. Emmekä myöskään kirjoita arvoituksellisessa runoudessa. Tarkoituksemme on tarjota sinulle vakaa, etäinen analyysi asioista, jotka saattavat osoittautua erittäin tärkeiksi sinulle.

Koemme velvollisuudeksemme esittää näkemyksemme, vaikka ne näyttäisivät harhaoppisilta, juuri siksi, että muuten niitä ei ehkä kuulla. Myöhäisteollisen yhteiskunnan suljetussa henkisessä ilmapiirissä ideat eivät liiku niin vapaasti kuin niiden pitäisi vakiintuneiden medioiden kautta.

Tämä kirja on kirjoitettu rakentavassa hengessä. Se on kolmas yhteinen teos, jossa analysoimme eri vaiheita nyt käynnissä olevassa suuressa muutoksessa. Kuten Blood in the Streets ja *The Great Reckoning*, se on ajatteluharjoitus. Kirja tutkii teollisyhteiskunnan kuolemaa ja sen uudelleenmuotoutumista uusiksi muodoiksi.

Odotamme näkevämme hämmästyttäviä paradokseja tulevina vuosina. Toisaalta tulet todistamaan uudenlaisen vapauden toteutumista, kun suvereenin yksilön aikakausi koittaa, ja voit odottaa näkeväs almost täydellisen tuottavuuden vapautumisen. Samanaikaisesti odotamme näkevämme modernin kansallisvaltion kuoleman. Monet länsimaisten ihmisten 1900-luvulla itsestäänselvyytenä pitämät tasa-arvon takeet ovat tuomittu häviämään sen mukana. Odotamme, että edustuksellinen demokratia sellaisena kuin sen nyt tunnemme, häipyy ja sen tilalle astuu kybermarkkinatalouden valinnan demokratia. Jos päätelmämme ovat oikeita, seuraavan vuosisadan politiikka tulee olemaan paljon monimuotoisempaa ja vähemmän merkittävää kuin se, mihin olemme totuneet.

Olemme varmoja, että argumenttimme on helppo seurata, huolimatta siitä, että se kuljettaa meidät alueille, jotka ovat älyllisesti vastaavia syrjäseuduilla ja huonoissa naapurustoissa. Jos merkityksemme ei ole kaikissa kohdissa täysin ymmärrettävä, se ei johdu siitä, että yritämme olla oikukkaita tai käyttää perinteistä kaksoiselämystä, jota ne käyttävät, jotka teeskentelevät ennustavansa tulevaisuutta salaperäisin lausuntoin. Emme ole kaksoiselämäisiä. Jos argumenttimme ovat epäselviä, se johtuu siitä, että emme ole onnistuneet kirjoittamaan tavalla, joka tekisi vakuuttavista ideoista helposti saavutettavia.

Toisin kuin monet ennustajat, haluamme, että ymmärrät ja jopa pystyt jäljentämään ajattelutapamme. Se perustuu ei psyykkisiin haaveisiin eikä planeettojen heiluntaan, vaan vanhanaikaiseen, rumaan logiikkaan.

Varsin loogisista syistä uskomme, että mikrotason prosessointi lopulta kumoaa ja tuhoaa kansallisvaltion, luoden samalla uusia sosiaalisen järjestäytymisen muotoja. On sekä välttämätöntä että mahdollista, että pystyt ennakoimaan ainakin osan niistä uusista elämäntavoista, jotka saattavat olla täällä ennen kuin ajattelet.

### Ennustetun tulevaisuuden ironioita

Vuosisatojen ajan tämän vuosituhannen loppua on pidetty historiallisen merkittävänä hetkenä. Yli 850 vuotta sitten St. Malachy määräsi vuoden 2000 viimeisenä tuomiopäivänä. Amerikkalainen psyykkinen ennustaja Edgar Cayce sanoi vuonna 1934, että maa siirtyisi akselillaan vuonna 2000, mikä aiheuttaisi Kalifornian jakautumisen kahdeksi ja tulvottaisi New Yorkin kaupungin sekä Japanin. Japanilainen rakettitieteilijä Hideo Itokawa ilmoitti vuonna 1980, että planeettojen asettuminen "Grand Cross" -muodostelmaan 18. elokuuta 1999 aiheuttaisi laajamittaista ympäristötuhoa, mikä johtaisi ihmiselämän loppumiseen maapallolla.[^18]

Tällaiset loppumaailma-ennustukset ovat runsaasti naurunaiheita. Kaiken kaikkiaan vuosi 2000, vaikka se onkin vaikuttava pyöreä luku, on vain mielivaltainen artefakti lännessä omaksutusta kristillisestä kalenterista. Muut kalenterit ja ajankirjoitusjärjestelmät laskevat vuosisatoja ja vuosituhansia eri lähtöpisteistä. Esimerkiksi islamilaisen kalenterin mukaan jKr. 2000 tulee olemaan vuosi 1378 – aivan tavalliselta kuulostava vuosi. Kiinan kalenterin mukaan, joka toistuu kuusikymmentä vuotta, jKr. 2000 on vain yksi vuosi lohikäärmevuosina. Se on osa jatkuvaa sykliä, joka ulottuu vuosituhansien takaa.

Kuitenkaan vuosi 2000 ei ole pelkästään teologisesti merkittävä. Sen tärkeys perustuu ei vain kristilliseen perinteeseen, vaan myös 1900-luvun puolivälin tietoteknologian rajoituksiin. Ns. Y2K- eli vuosi 2000 -tietokoneongelma, mahdollisesti tuhoisa looginen virhe miljardeissa tietokonekoodin riveissä, saattoi aiheuttaa loppumaisia olosuhteita sulkemalla teollisyhteiskunnan olennaiset osat vuosituhannen keskellä. Monet tietokoneet ja mikrokäsittelijät käyttävät ohjelmistoa, jota on säilytetty ja kierrätetty tietokoneiden varhaisilta päiviltä, jolloin muistitilan hinta – 600 000 dollaria per megatavu – oli arvokkaampaa kuin kulta. Kalliiden tilojen säästämiseksi varhaiset ohjelmoijat seurasivat päivämääriä vain kahden viimeisen numeron avulla. Tämä kaksinumeroinen päivämääräkenttäkonventio siirtyi useimpiin suurkokoinen tietokoneissa käytettyihin ohjelmistoihin, ja sitä käytettiin laajasti myös henkilökohtaisissa tietokoneissa ja niin kutsutuissa sulautetuissa piireissä, mikrokäsittelijöissä, joita käytetään lähes kaiken ohjaamiseen – VCR:istä auton sytytysjärjestelmiin, turvajärjestelmiin, puhelimiin, puhelinverkkoa ohjaaviin vaihtojärjestelmiin, tehdasteollisuuden prosessi- ja ohjausjärjestelmiin, voimalaitoksiin, öljynjalostamoihin, kemianteollisuuden laitoksiin, putkistoihin ja paljon muuhun. Näin lyhentyen kahden numeron kentäksi vuosi 1999 olisi "99". Ongelma on, mitä tapahtuu, kun vuodelle 2000 tulee "00". Monet tietokoneet tulkitsevat tämän vuonna 1900. Tämä saattaa tehdä mahdottomaksi monien korjaamattomien tietokoneiden ja muiden digitaalisten laitteiden tunnistaa vuotta 2000 päivämääräkentissä.

Tuloksena on massiivinen tietojen korruptioon liittyvä ongelma, joka antaa sattumanvaraisena esimerkkinä uuden mahdollisuuden informaatiovaikuttamiseen. Information Age -aikana potentiaaliset vastustajat pystyvät aiheuttamaan kaaosta räjäyttämällä "logiikkapommeja", jotka sabotoivat olennaisten järjestelmien toimintoja korruptoimalla tietoja, joihin niiden toiminta perustuu. Esimerkiksi sotaharjoituksena sinun ei tarvitsisi ampua alas lentokonetta, jos pystyisit korruptoimaan sen turvallisen toiminnan kannalta olennaiset tiedot. Tietojen korruptio voi tehdä lähes yhtä paljon kuin fyysiset aseet modernin yhteiskunnan toimintojen estämiseksi. Sen potentiaalisten laajojen seurauksien tulisi olla itsestään selvät, kun mietitään asiaa. Esimerkiksi *Mail* of London raportoi 14. joulukuuta 1997, että lentoyhtiöt ympäri maailmaa suunnittelivat satojen lentojen peruuttamista 1. tammikuuta 2000 peläten, että ilmatilan valvontajärjestelmät saattavat epäonnistua.[^19] Mahdollisiin ongelmiin kuuluu paitsi ilmatilan järjestelmien toiminta myös lentokoneisiin itsessään upotettujen päivämääräherkkien toimintojen häiriintyminen. Boeingin mukaan monissa lentokoneissa tarvitaan Y2K-korjaustoimenpiteitä. Monet laitteet saattavat kohdata ongelmia, jos ne yrittävät kirjata tapahtuman virheelliselle päivämäärälle. Lentokoneiden fly-by-wire -tietokoneohjatut järjestelmät saattavat toimia virheellisesti, jos ne on ohjelmoitu päättämään, että kriittistä huoltoa on viimeksi tehty vuonna 1900. Ne saattavat jopa mennä virhekiertoon ja sammua.

Logiikkaa sisältävän aikapommin mahdollisesti tappavat takaisinkytkentävaikutukset, jotka sulkevat ei-yhteensopivat ohjausjärjestelmät, voisivat tehdä vuosituhannen vaihdoksesta mielettömän ikävän päivämäärän. Muista, että monet laitteet, jopa jos on onnekas olla joutumatta keskelle ilmaa uuden vuosituhannen alkaessa, voivat mennä virhekiertoon ja sammua.

Olisi viisasta välttää onnettomuutta, joka johtuu Y2K-yhteensopimattomista sydämentahdistimista tai yksinkertaisesti humalaisista vuosituhannen juhlimaan osallistuvista ihmisistä, sillä jos sydämentahdistimet sammuvat, myös puhelinjärjestelmä saattaa sammuttaa, jolloin ambulanssi ei ehkä koskaan saavu. Ellet asu Brasiliassa tai Ukrainassa, olet tottunut nostamaan puhelimen tai käynnistämään matkapuhelimen ja saamaan automaattisesti soittoäänen. Onneksi sinun harvoin tarvitsee huolehtia teknisistä yksityiskohdista, miten puhelinjärjestelmä toimii. Kuitenkin kävi ilmi, että puhelinverkon kytkimet ja reitittimet ovat erittäin päivämääräriippuvaisia. Kaikki yhteydet kirjataan päivämäärän ja kellonajan mukaan, mikä on ratkaisevan tärkeää puheluiden keston laskemiseksi laskutusta varten. Jos satut soittamaan yhden minuutin puhelun 31. joulukuuta 1999 klo 11:59:30 ja järjestelmä 12:00:00 lukee puhelun keston olleen yli 99 vuotta negatiivisena, virhekiertoja ja sammumisia on mahdollista. Vaikka pitkän matkan yhtiöt käyttävät suuria summia päivittääkseen kytkimensä vuoden 2000 yhteensopiviksi ja paikalliset palveluntarjoajat todennäköisesti tekevät samoin, jos edes muutama pienempi yritys ei noudata vaatimuksia ja sammuu, koko verkko saattaa joutua vaikutuksen alaiseksi. Olet onnekas, jos saat soittoäänen 1. tammikuuta 2000.

Y2K-asiantuntijan Peter de Jagerin mukaan, "jos menetämme kykynsä soittaa puheluita, menetämme kaiken. Menetämme sähköiset rahansiirrot, menetämme kaupankäynnin, menemme haarapankkitoimintaan." Ja Y2K-aukkojen jatkoseuraukset voivat ulottua myös tätä pidemmälle.

Tänä päivänä kukaan ei tiedä, kuinka laajasti kriittiset järjestelmät kaatuvat vuoden 2000 ongelman takia. Upotetuissa järjestelmissä, joita ei voida uudelleenohjelmoida vaan jotka tulee vaihtaa, jos ne eivät toimi päivämääräherkällä perusteella, esiintyy ongelmia esimerkiksi 1976 jälkeen valmistetuissa korteissa, kuorma-autoissa ja busseissa. (Ehkä et joudu onnettomuuteen, jos sellaisten ajoneuvojen kuljettajat, joiden sydämentahdistimet eivät ole yhteensopivia, eivät lähde liikkeelle.) Upotettuja järjestelmiä esiintyy myös laajalti kaikissa teollisuuden voimalaitoksissa, vesi- ja jätevesijärjestelmissä, lääkintälaitteissa, sotavarusteissa, lentokoneissa, merellä toimivissa öljynporausalustoissa, öljytankkereissa, hälytysjärjestelmissä ja hisseissä. Vaikka monet mikroprosessoreita sisältävät kokoonpanot eivät suorita yhtään päivämääräherkkiä toimintoja, ne saattavat siitä huolimatta olla riippuvaisia kellosta, joka saattaa olla Y2K-herkkä, sisäisten toimintojensa kannalta.

## Mainframe-tietokoneet ja Y2K-aikabombu

Hallituksen ja suuryritysten laajamittaiset komentokeskukset, joissa käsitellään suuria transaktiomääriä mainframe-tietokoneilla, olivat alkuperäinen Y2K-huolenaihe. Koska näissä järjestelmissä käytetään valtavia koneita, joiden ohjelmistot ovat vuosikymmenten vanhoja ja usein eivät täytä nykyisiä vaatimuksia, Y2K-hälytykset – joita Peter de Jager ensimmäisen kerran nosti esiin 1990-luvun alussa – ovat keskittyneet pääasiassa tarvetta päivittää suurten, moniprosessoristen mainframejen käyttöjärjestelmiä.

Mr. de Jager ilmaisi huolensa siitä, ettei olisi riittävästi COBOLia hallitsevia ohjelmoijia, jotta tarvittavat korjaukset ja päivitykset päivämääräkriittiseen koodiin saataisiin valmiiksi, vaikka kaikkien haavoittuvien järjestelmien omaavat yritykset ja virastot olisivatkaan käynnistäneet kiireellisen korjausohjelman vuosia sitten. Koska näin ei ole tapahtunut ja monet päivämäärätietojärjestelmien käyttäjät ovat vasta alkamassa arvioida haavoittuvuuttaan, voidaan lähes varmuudella ennustaa, että monet mainframe-järjestelmät eivät ole valmiita toimimaan sujuvasti vuoden 2000 yli.

Tämä on ehdottomasti merkittävä huolenaihe, sillä nykyisen talouden rakenteessa tietokonelaskennan vaihtoehtoa ei oikeastaan ole. Suurin osa yrityksistä, jotka ovat tarpeeksi suuria edellyttääkseen mainframea transaktioidensa hallintaan, ovat riippuvaisia transaktiomääristä, joita ei voitaisi hallita vanhanaikaisilla 1800-luvun paperijärjestelmillä. Jos tällaiset yritykset joutuisivat palaamaan paperin käsittelyyn, ne pystyisivät suorittamaan vain murto-osan normaalista transaktiomäärästään, mikä aiheuttaisi tulojen romahtamisen ja vaarantaisi lähes kaikkien paitsi erittäin pääomavaltuisten yritysten hengissä pysymisen.

Melkein kaikki rahaan liittyvä – laskutus-, hankinta- ja palkkajärjestelmät sekä varastohallinta ja sääntelyn noudattaminen – sekoittuisi täysin. Suuret tietomäärät menisivät hukkaan, kun tietokoneet kaatuisivat tai alkaisivat tuottaa virheellisiä tietoja Y2K-ongelman vuoksi. Joissakin tapauksissa järjestelmien välitön kaatuminen voisi itse asiassa olla onnekas, sillä silloin tietojen korruptoituminen kertyisi harvemmin, ennen kuin massiivinen toimintahäiriö kiinnittäisi huomiota ongelmaan.

Mitä sitten tapahtuu, kun varmuuskopiointiohjelma kopioi 07/04/99 alun perin olevat tiedostot päivitykseen 01/04/00? Kuka tietää? Tulkitseeko tietokone esimerkiksi tammikuun 4. päivänä tehdyn maksun (merkittynä "1900") vakuutuspolitiikasta merkkinä siitä, että politiikka on ollut maksukyvyttömänä vuosisadan ajan ja siten peruutettu, jolloin se poistettaisiin tiedostoista? Pyrkivätkö pankkien ja rahoitusyhtiöiden tietokoneet laskemaan sataa vuoden korkoja lainoista, jotka ulottuvat uuden vuosituhannen siirtymään? Säilyttävätkö pankkisi ja välittäjäyrityksesi tarkat tiedot tiliesi saldosta ja tarjoavatko ne ajantasaisen pääsyn varoihisi? Nämä ovat vain muutamia mielenkiintoisia pulmia, joita kohtaat Y2K-ongelman vuoksi.

> "This is potentially the most destructive part of the year 2000 problem. This isn't the inconvenience part where your paycheck comes a few days late. This is the blood-in-the-streets part. - Dr. Leon Kappelman, Co-Chair Society For Information Management's Year 2000 Working Group"

Myös listallasi keskeisenä huolenaiheena tulisi olla se, mitä tapahtuu, jos sähkö katkeaa Y2K:hen liittyvien vikojen vuoksi. Ilman sähköä jopa useimmat järjestelmät, jotka eivät ole Y2K-vaurioituneita, eivät toimi – esimerkiksi jääkaappisi, pakastimesi, ehkä jopa lämmitysjärjestelmäsi. Y2K-yhteensopivuusongelmat saattavat vaikuttaa ydinvoimaloiden turvallisuuteen liittyviin sisäänpääsy- ja hallintatoimintoihin. Esimerkiksi ydinlaitoksissa työskentelevät henkilöt käyttävät dosimetrilaitteita, jotka mittaavat heidän saamaansa säteilyaltistusta laitoksessa ollessaan. Näitä laitteita analysoidaan säännöllisesti, ja altistustietoja säilytetään tietokonejärjestelmässä, joka hallitsee henkilöstön pääsyä laitokseen. Ilmiselvää on, että jos ohjaavat tietokoneet pettävät, kaikki turvallisen toiminnan ja asianmukaisen huollon takaamiseksi suunnitellut monimutkaiset hallintatoiminnot menevät sekaisin. Vielä tärkeämpää on se, että ydinenergiaa säätelevän viraston muistio huomauttaa, että monet "turvallisuuteen liittymättömät, mutta tärkeät tietokonepohjaiset järjestelmät – pääasiassa tietokannat ja tiedonkeruuta, joka on välttämätöntä laitoksen toiminnalle" – ovat ajallisesti herkkiä.

Tavanomaiset voimalaitokset eivät ole vähemmän alttiita Y2K-häiriöille. Esimerkiksi kivihiilivoimalat ovat herkkiä häiriöille pintakuljetusjärjestelmässä, joka toimittaa kivihiiltä kattiloihin. Vuoden 1997–1998 talven lämmityskaudella kivihiilivoimaloiden käyttäjät joutuivat joissakin tapauksissa vähentämään tuotantoaan, koska Länsi-Amerikasta peräisin olevan kivihiilen rautatiekuljetusten hidastuminen – jonka aiheutti Southern Pacificin ja Union Pacificin fuusio – vaikutti toimituksiin. Ongelma ilmeni, koska näiden kahden rautatieyrityksen käyttämiä tietokoneohjaus- ja lähetysjärjestelmiä ei ollut yhteensopivia. Union Pacificin edustajan mukaan järjestelmien integrointi muodostui "painajaiseksi", huolimatta siitä, että Union Pacific Technologiesia on pidetty alan edelläkävijänä tietokoneistetun kuljetushallinnan kehittämisessä. Ohjelmointivaikeuksien seurauksena rautatieyhtiö ei pystynyt tarkkaan seuraamaan rahtvaunujensa liikkeitä. Union Pacificin epäonnistuminen Southern Pacificin yhdistämisessä on huono ennusmerkki siitä, mitä voi tapahtua, kun Y2K-logiikan aikapommien aiheuttamat häiriöt vaikuttavat kuljetukseen, voimalaitoksiin ja muihin talouden osa-alueisiin.

Suurin huoli sähköverkosta sen sijaan johtuu siitä, että koko järjestelmä on herkästi valvottu ja tietokoneohjattu, jolloin sähköä siirretään ylijäämävoimalähteiden alueelta niille alueille, joilla on puutetta. Tätä prosessia on seurattava tarkasti tietokoneilla, jotta estetään virrankulutuspiikit ja järjestelmäkatkokset. Kaikki sähkön siirrot kirjataan ajan ja päiväyksen mukaan, aivan kuin ne olisivat puhelinkokouksia. Vaikka raskaita mekaanisia releitä käytetään yhteyksien luomisessa, niitä ohjaavat tietokonejärjestelmät. Nämä tietokoneohjausjärjestelmät, jotka ovat olennaisia kuormituksen tasaamisessa, saattavat pettää samoista syistä kuin puhelinverkot. Itse asiassa Pohjois-Amerikan voimalatauksen jakelunhallintajärjestelmät ovat yhdistetty T-1-linjojen ja puhelinmikroaaltoyhteyksien kautta, joten jos puhelinverkko pettää, voit odottaa myös sähkön katkeavan. Ja muista, kuten Kanadassa tammikuussa 1998 tapahtuneesta kokemuksesta käy ilmi, kun sähkö katkeaa laajalla alueella, järjestelmän käynnistäminen uudelleen on haastavaa – sähkökatkos voi kestää haitallisen pitkään.

## Y2K JA YDINASENAALIT

Modernien talouksien kannalta sähkökatkos keskellä talvea olisi erittäin häiritsevää ja mahdollisesti vaarantaa terveyden, erityisesti niiden osalta, jotka ovat riippuvaisia sähköisestä lämmityksestä ja lääkinnällisistä laitteista. Mutta pahin tapaus on vielä pahempi. John Koskinen, joka johtaa President Clintonin Y2K Conversion Councilia, on todennut, että Yhdysvaltain sotilasasevarastot saattavat lakata toimimasta täsmälleen keskiyöllä 31. joulukuuta 1999. Vaikka hän ei halua aiheuttaa liiallista paniikkia, Koskinen lisää: "Siitä on syytä olla huolissaan." Yksi huolenaihe ydinohjusjärjestelmien osalta on, "jos tiedot eivät toimi ja ne oikeasti laukaistaan."

Tietenkin tätä huolta koskisi yhtä tai jopa vielä suuremmalla voimalla myös Venäjän ydinohjuksia. Venäjän konkurssi on tehnyt Y2K-yhteensopivuusparannuksista entistä ongelmallisempia kuin Yhdysvalloissa, ja on viitteitä siitä, että Venäjä ei ole vielä ottanut Y2K-muunnosta vakavasti. Vaikka toivoisi, ettei tahattomia laukaisuja tapahtuisi, ei pitäisi epäillä, että vuoden 2000 vaihde voi pahentaa maailmanlaajuista epävakautta – jos vain siksi, että monien maiden sotilaskommunikaatiojärjestelmät eivät ehkä toimi normaalisti. Kuten Koskinen sanoo: "Jos istut maassa ja yhtäkkiä et oikein saa selvää, mitä tapahtuu, ja viestintäsi eivät toimi niin hyvin, hermostut entisestään." Lisää siis tämä Y2K-huoliesi listalle. Looginen aikapommi voi aiheuttaa aidosti räjähtävien pommejen laukaisun – se on tosiasia, joka korostaa tietovaikuttamisen vaaroja keskitettyihin komentajärjestelmiin.

Jos terroristit haluavat iskeä mihin tahansa keskitettyyn järjestelmään, he saattavat valita 31. joulukuuta 1999 toiminnan ajankohdaksi, koska silloin monien järjestelmien haavoittuvuus on suurimmillaan. Ei ainoastaan viestintä rasitu huipussaan, vaan sähkökatkokset, käynnistymättömät ajoneuvot, 911-palveluiden (poliisi-, pelastus- ja ambulanssipalveluiden) toimimattomuus ym. ovat mahdollisia. Lisäksi monet muut toiminnot, joita pidät itsestäänselvyyksinä, kuten ilmatieliikenteen valvonta, voivat lakata toimimasta. Ilman sähköä hanavesiä ei tule, viemärijärjestelmät pettäisivät ja liikennevalot sammuisivat. Muutamassa tunnissa aidosta liikennejärjestelmän romahtamisesta ruokakauppojen hyllyt loppuisivat (tai ryöstettäisiin). Viimeaikaisten kokemusten perusteella amerikkalaisissa kaupungeissa voisi olettaa, että ilman sähköä, vettä, riittävästi lämpöä monille, valoja ja toimivaa, yhtenäistä viestintää hätäpalveluiden (mukaan lukien poliisi ja palokunta) kanssa, sivilisaatiota ei voi ylläpitää. Vaikka kukaan ei voi olla varma, millainen vaikutus Y2K-ongelmalla voi olla, se voisi johtaa ryöstöihin ja mellakoihin kaduilla, erityisesti jos käy ilmi, että palkanmaksujen, sosiaaliturvan ja eläketarkastusten jakelussa voi esiintyä laajamittaisia epäonnistumisia.

> "Emme ole sitä, mitä olemme olleet, vaan alamme olla jotakin muuta."[^20] – Joachim de Fiore

Uhrin ennakkoajatukset uudesta vuosituhannesta eivät välttämättä perustu kristinuskoon sidottuun teologiaan, mutta ne sopivat hyvin Joachim de Fiore -nimisen ajattelijan milleniaaliseen perinteeseen, jonka pohdinnat vakuuttivat hänet siitä, että Kristus oli vain "historian toinen saranan kahva" ja että toinen olisi kohtalolla käynnistymässä.[^21] Näin argumentoikin filosofi Michael Grosso, joka ehdottaa, että Information Revolution ohjaa ihmiskunnan historiaa kohti länsimaisen maailman profeetallisen vision toteutumista. Hän kutsuu tätä ilmiötä "technocalypseksi." Riippumatta siitä, saako teknologian kehitys vaikutteita milleniaalivisioista vai ei, Y2K-ilmiö on seurausta länsimaisen ajan mielikuvituksen vallitsevasta käsityksestä. Kummallisella tavalla se voisi täydentää unelmia, haaveilua ja näkyjä tai näkyjen numeerisia tulkintoja, kuten Newtonin selitystä Danielin profetioista. Nämä intuitiiviset harppaukset alkavat näkökulmasta, jossa Kristuksen syntymää pidetään historian keskeisenä tapahtumana, ja niitä vaikuttaa myös suurten pyöreiden lukujen psykologinen voima, jonka jokainen kauppias tunnistaa vangitsevana ominaisuutena. Aikamme kahdentuhattavuosi ei voi olla muuta kuin intuitiivisten ihmisten mielikuvituksen keskipiste.

Kriitikko voisi helposti tehdä näistä ennakkoajatuksista naurettavia huomioimatta edes niitä epäselviä ja kiistanalaisia teologisia käsityksiä Tuomiosta ja Viimeisestä Tuomiosta, jotka antavat näille näkyille niiden voiman. Mielenkiintoista on kuitenkin se, että Y2K-tietokonevirhe ylittää ne aritmeettiset virheet, jotka muuten saattaisivat vaikuttaa vähentävän vuoden 2000 tärkeyttä jopa kristillisessä yhteydessä. Vuodella 2000 on potentiaalia muodostua käännekohdaksi historian seuraavalle vaiheelle yksinkertaisesti siksi, että se etenee uuden vuosituhannen saapumiseen. Tiukassa logiikassa seuraava vuosituhat alkaa vasta vuonna 2001. Vuosi 2000 on vain kahdentuhannen vuoden mittainen aika Kristuksen syntymästä – tai niin se olisi, jos Kristus olisi syntynyt kristillisen ajan ensimmäisenä vuonna. Hän ei ollut. Vuonna 533, kun Kristuksen syntymä korvasi Rooman perustamisajankohdan länsimaisen kalenterin mukaiseksi vuosien laskennassa, uusien käytäntöjen käyttöönottoon ryhtyneet munkit laskivat Kristuksen syntymän väärin. Nykyään hyväksytään, että hän syntyi vuonna 4 eaa. Tämän perusteella täyteen kahdentuhanteen vuotta hänen syntymästään on saatettu loppuun noin vuonna 1997. Näin ollen Carl Jungin näennäisesti outo käynnistymispäivä uuden aikakauden alulle.



Voit nauraa, jos haluat, mutta emme halveksi emmekä hylkää intuitiivista tapaa ymmärtää historiaa. Vaikka perustelumme pohjautuvat logiikkaan, eivätkä tuottoihin, olemme haltioissamme ihmisen tietoisuuden profeetallisesta voimasta. Ajan toisensa jälkeen se vahvistaa hulluuden, selvänäkijöiden ja pyhien visioita. Niin saattaa käydä myös vuoden 2000 murroksen kohdalla. Päivämäärä, joka on jo kauan vakiintunut lännen mielikuvituksessa, vaikuttaa olevan se käännekohta, joka ainakin osittain vahvistaa, että historiassa on oma kohtalonsa. Emme voi selittää, miksi näin tulisi olla, mutta olemme silti vakuuttuneita siitä, että se on niin.

Intuitionamme mukaan historiassa on kohtalo, ja vapaa tahto sekä determinismi ovat kaksi versiota samasta ilmiöstä. Ne ihmisten väliset vuorovaikutustilanteet, jotka muovaavat historiaa, käyttäytyvät ikään kuin niihin ohjaisi jokin kohtalon voima. Aivan kuten elektroniplasma, eli tiheä elektronikaasu, toimii monimutkaisena järjestelmänä, ihmiset käyttäytyvät samoin. Elektronien yksilöllisen liikkeen vapaus osoittautuu yhteensopivaksi erittäin organisoituneen kollektiivisen toiminnan kanssa. Kuten David Ohm totesi elektroniplasman yhteydessä, ihmishistoria on "erinomaisesti järjestäytynyt järjestelmä, joka toimii kokonaisuutena."

Maailman toimintatapojen ymmärtäminen tarkoittaa realistisen intuition kehittämistä siitä, miten ihmiskunta tottelee luonnollisten prosessien matematiikkaa. Todellisuus on epälineaarista, mutta useimpien ihmisten odotukset eivät senä ole. Muutoksen dynamiikan ymmärtämiseksi täytyy tunnustaa, että ihmiskunta – kuten muutkin luonnon monimutkaiset järjestelmät – on leimattu sykleihin ja katkoksiin. Tämä tarkoittaa, että tietyt historian piirteet ovat taipuvaisia toistumaan, ja tärkeimmät muutokset, kun ne tapahtuvat, voivat olla äkillisiä eikä asteittaisia.

Ihmisen elämään läpäisevien syklien joukossa salaperäinen viisisataan vuoden sykli vaikuttaa merkitsevän suuria käännekohtia länsimaisen sivilisaation historiassa. Vuoden 2000 lähestyessä meitä kummittelee outo tosiasia, että jokaisen viidellä jaollisen vuosisadan viimeinen vuosikymmen on merkinnyt syvällistä muutosta länsimaisessa sivilisaatiossa – kuoleman ja jälleensyntymisen kaavaa, joka piirtää uusia yhteiskunnallisen järjestäytymisen vaiheita aivan kuten kuolema ja syntymä määrittelevät ihmislukujen syklin. Tämä on ollut totta jo ainakin 500 eaa., jolloin kreikkalainen demokratia nousi esiin Cleisthenesin perustuslaillisilla uudistuksilla vuonna 508 eaa. Seuraavat viisi vuosisataa olivat kasvun ja antiikin talouden intensifikaation aikaa, joka huipentui Kristuksen syntymään vuonna 4 eaa. Se oli myös aika, jolloin antiikin talous saavutti suurimman vaurauden, kun korot olivat alhaisimmillaan ennen modernia aikakautta.

Seuraavien viiden vuosisadan aikana vauraus alkoi vähitellen hiipua, mikä johti Rooman valtakunnan romahtamiseen viimeistään 5. vuosisadalla jaa. William Playfairin yhteenveto on toistamisen arvoinen: "Kun Roma oli huipussaan, ... tullaan näkemään, että se oli Kristuksen syntymän aikaan, eli Augustus-hallituskauden aikana, ja samalla se havaittaisiin asteittain vähenevän vuoteen 490 asti."[^22] Juuri silloin viimeiset legioonat liukkuivat pois, ja Länsi maailma vaipui pimeisiin keskiaikaan.

<!-- new paragraph -->

Intuitionamme on, että historiassa on kohtalo, ja vapaa tahto sekä determinismi ovat kaksi versiota samasta ilmiöstä. Ne ihmisten väliset vuorovaikutustilanteet, jotka muodostavat historiamme, vaikuttavat ikään kuin niihin ohjaisi jokin kohtalon olemus. Aivan kuten elektroniplasma, eli tiheä elektronikaasu, toimii monimutkaisena järjestelmänä, toimii myös ihminen samalla tavalla. Elektronien yksilöllisen liikkeen vapaus on yhteensopivaa erittäin organisoituneen kollektiivisen toiminnan kanssa. Kuten David Ohm totesi elektroniplasman yhteydessä, ihmishistoria on "erinomaisesti järjestäytynyt järjestelmä, joka toimii kokonaisuutena."

Maailman toimintatapojen ymmärtäminen tarkoittaa realistisen intuition kehittämistä siitä, miten ihmiskunta noudattaa luonnollisten prosessien matematiikkaa. Todellisuus on epälineaarista, mutta useimpien ihmisten odotukset eivät ole. Muutoksen dynamiikan ymmärtämiseksi on tunnustettava, että ihmiskunta, kuten muutkin luonnon monimutkaiset järjestelmät, on leimattu sykleihin ja katkoksiin. Tämä tarkoittaa, että tietyt historian ominaisuudet toistuvat, ja tärkeimmät muutokset voivat tapahtua äkillisesti sen sijaan, että ne eteneisivät asteittain.

Yksi ihmisen elämän läpi kulkevista sykleistä on salaperäinen viisisataan vuoden sykli, joka näyttää merkitsevän suuria käännekohtia länsimaisen sivilisaation historiassa. Vuoden 2000 lähestyessä meitä kummittelee outo tosiasia, että jokaisen viidellä jaollisen vuosisadan viimeinen vuosikymmen on merkinnyt syvällistä muutosta länsimaisessa sivilisaatiossa – kuoleman ja jälleensyntymisen kaavaa, joka määrittää uusia yhteiskunnallisen järjestäytymisen vaiheita aivan kuten kuolema ja syntymä muovaavat ihmislukujen syklin. Tämä on ollut totta jo ainakin 500 eaa., jolloin kreikkalainen demokratia nousi esiin Cleisthenesin perustuslaillisilla uudistuksilla vuonna 508 eaa. Seuraavat viisi vuosisataa olivat antiikin talouden kasvun ja intensifikaation aikaa, joka huipentui Kristuksen syntymään vuonna 4 eaa. Se oli myös aika, jolloin antiikin talous saavutti suurimman vaurauden, kun korot olivat alhaisimmillaan ennen modernia aikakautta.

Seuraavien viiden vuosisadan aikana vauraus alkoi vähitellen hiipua, mikä johti Rooman valtakunnan romahtamiseen 400-luvun lopussa jaa. William Playfairin yhteenveto on toistamisen arvoinen: "Kun Roma oli huipussaan, ... tullaan näkemään, että se oli Kristuksen syntymän aikaan, eli Augustus-hallituskauden aikana, ja samalla se havaittaisiin asteittain vähenevän vuoteen 490 asti."[^22] Juuri silloin viimeiset legioonat liukkuivat pois, ja Länsi maailma vaipui pimeisiin keskiaikaan.

Seuraavien viiden vuosisadan aikana talous kuihtui, kaukana tapahtuva kauppa pysähtyi, kaupungit tyhjentyivät, raha katosi liikkeestä ja taide sekä lukutaito lähes hävisivät. Tehokkaan lain katoaminen Lännessä, kun Rooman valtakunta romahti, johti primitiivisempien riitojen ratkaisutapojen syntyyn. Veripääfeudi alkoi muodostua merkittäväksi viidennen vuosisadan lopulla, ja ensimmäinen kirjattu tapaus tuomiokeinnon käytöstä tapahtui juuri vuonna 500.

Vielä kerran, tuhannen vuoden takaa, 900-luvun viimeinen vuosikymppi todisti toisen kerran "valtavan murroksen sosiaalisissa ja taloudellisissa järjestelmissä." Ehkä näistä siirtymistä vähiten tunnettu, feodaalinen vallankumous, alkoi aikana, jolloin vallitsi täydellinen taloudellinen ja poliittinen kaaos. Teoksessaan *The Transformation of the Year One Thousand* University of Parisin keskiaikaisten historian professori Guy Bois väittää, että tämä murtuma 900-luvun lopulla merkitsi muinaisten instituutioiden jäännösten täydellistä romahtamista ja jotain uutta nousi anarkian keskeltä – feodalismista.[^23] Raoul Glaber sanoi: "Sanottiin, että koko maailma yhtenäisesti ravisteli pois antiikin raamit."[^24] Yhtäkkiä ilmestyvä uusi järjestelmä mahdollisti talouskasvun hitaan elpymisen; nyt keskiajaksi kutsutut viisi vuosisataa kokivat rahaa ja kansainvälistä kauppaa uudelleenheräämisen sekä aritmetiikan, lukutaidon ja ajantajun uudelleenlöytämisen.

Sitten, 1400-luvun viimeisellä vuosikymmenellä, tapahtui jälleen yksi käännekohta. Juuri silloin Eurooppa nousi Mustan Surman aiheuttamasta väestödellasta ja lähes heti alkoi osoittaa valtaansa muun maailman suhteen. "Ruutirevoluutio", "Renessanssi" ja "Reformaatio" ovat nimityksiä eri aspekteille tästä siirtymästä, joka toi mukanaan modernin aikakauden. Tilanne julkistettiin räjähtävästi, kun Charles VIII valloitti Italian uusilla pronssikanuunoilla. Siihen kuului avautuminen maailmaan, mikä huipentui siihen, että Columbus purjehti Amerikkaan vuonna 1492. Tämä Uuteen maailmaan johtanut avautuminen käynnisti työntövoiman kohti kaikkien aikojen dramaattisinta talouskasvua ihmiskunnan historiassa. Se sisälsi fysiikan ja astronomian muuttumisia, jotka johtivat modernin tieteen syntyyn, ja sen ajatukset levisivät laajasti uuden painokoneen teknologian ansiosta.

Nyt istumme toisen vuosituhannen mullistuksen kynnyksellä. Teolliseltä aikakaudelta periytyneet suuret käskyn- ja ohjausjärjestelmät saattavat romahtaa kuin yhden hevosen vetämä vaunu vuosituhannen keskiyöllä. Kuitenkin, olivatpa Y2K-logiikkapommi tai sen aiheuttama välitön teollisen yhteiskunnan romahtaminen mahdollista tai ei, sen päivät ovat laskettu. Odotamme, että tietoyhteiskunnan aikakausi muuttaa maailman täysin tavoilla, joita tätä kirjaa on tarkoitus selittää. Olisit täysin oikeutettu epäilemään tätä, sillä mikään vuosituhannessa vain kahdesti toistuva sykli ei ole osoittanut riittävästi toistoja ollakseen tilastollisesti merkittävä. Itse asiassa jopa huomattavasti lyhyemmät syklit ovat herättäneet taloustieteilijöiden skeptisyyttä, jotka vaativat tilastollisesti tyydyttävämpää näyttöä. "Professor Dennis Robertson kirjoitti kerran, että meidän olisi parempi odottaa muutama vuosisata ennen kuin olemme varmoja" nelivuotisista sekä kahdeksasta–kymmenenvuotisista kauppasykleistä.[^25] Tämän standardin mukaan professor Robertsonin tulisi lykätä tuomion tekemistä noin kolmekymmeneen tuhanteen vuoteen varmistaakseen, ettei viisisataa-vuotinen sykli ole tilastollinen onnettomuus. Emme ole dogmaattisia, vaan olemme valmiimpia tunnustamaan, että todellisuuden mallit ovat monimutkaisempia kuin useimpien taloustieteilijöiden staattiset ja lineaariset tasapainomallit.

Uskomme, että vuoden 2000 saapuminen merkitsee enemmän kuin vain toista kätevää jakolinjaa loputtoman ajan jatkumossa. Uskomme, että se tulee olemaan käännekohta vanhan maailman ja tulevan uuden maailman välillä. Teollinen aikakausi on nopeasti väistymässä, ja sen tuhoutuminen saattaa ironisesti nopeutua sen vuoksi, että varhaisen tietokonemuistin hinta oli niin korkea, että se kannusti laajaan kahden numeron päivämääräkenttien käyttöön. Kun Hallerithin reikäkortit pystyivät käsittelemään vain kahdeksankymmentä merkkiä kussakin, päivämäärien lyhentäminen vaikutti järkevältä. Vastoin varhaisten ohjelmoijien odotuksia kuitenkin heidän päivämääräkenttien lyhennyksensä kesti neljä vuosikymmentä aina vuosituhannen loppuun saakka, toimien tahattomana logiikkapommana, joka voisi tuhota suuren osan teollisesta yhteiskunnasta. Yhdysvaltain hallituksen Office of Management and Budget kuvaili ongelmaa raportissaan "Getting Federal Computers Ready for 2000," päivätty 7. helmikuuta 1997. Siinä todetaan tietokoneista: "Ellei niitä korjata tai vaihtaa, ne epäonnistuvat vuosituhannen vaihtuessa kolmella tavalla: ne hylkäävät oikeat syötteet, laskevat virheellisiä tuloksia, tai eivät yksinkertaisesti toimi." Nämä kolme lopputulosta yhdessä voisivat lamauttaa teollisen yhteiskunnan. Sen massatuotantoteknologia on määräytymässä uuden, mikroyksiköihin perustuvan pienentämisteknologian alle – lyhyen aikavälin kriisi vain nopeuttaa tätä prosessia. Uuden tietotekniikan myötä on syntynyt myös uusi ei-lineaarisen dynamiikan tiede, jonka hämmästyttävät johtopäätökset ovat vieläkin vain yksittäisiä säikeitä, joita on tarkoitus punoa yhteen kokonaisvaltaiseksi maailmankuvaksi. Elämme tietokoneiden aikaa, mutta unelmiamme kutotaan yhä kangaspuilla. Jatkamme elämäämme teollisuuden metaforien ja ajatusten mukaan. Politiikkamme edelleen jakautuu teollisen jakoviivan – oikean ja vasemman – välillä, kuten Adam Smithin ja Karl Marxin kaltaiset ajattelijat osoittivat, jotka kuolivat ennen kuin lähes kuka tahansa nykyään elävistä syntyi. Teollinen maailmankuva, joka sisällyttää teollistieteen toimintaperiaatteet, on yhä koulutettujen mielipiteiden "järkevä intuitio". Teesimme on, että teollisen aikakauden "järkevyys" ei enää päde monilla alueilla sen muuttuessa maailmaa.

Uskomme, että vuoden 2000 saapuminen merkitsee enemmän kuin vain toista kätevää jakolinjaa loputtomassa ajan jatkumossa. Uskomme, että se tulee olemaan käännekohta vanhan maailman ja tulevan uuden maailman välillä. Teollinen aikakausi on nopeasti väistymässä, ja sen tuhoutuminen saattaa ironisesti nopeutua sen vuoksi, että varhaisen tietokonemuistin hinta oli niin korkea, että se kannusti laajaan kahden numeron päivämääräkenttien käyttöön. Kun Hallerithin reikäkortit pystyivät käsittelemään vain kahdeksankymmentä merkkiä kussakin, päivämäärien lyhentäminen vaikutti järkevältä. Vastoin varhaisten ohjelmoijien odotuksia kuitenkin heidän päivämääräkenttien lyhennyksensä kesti neljä vuosikymmentä aina vuosituhannen loppuun saakka, toimien tahattomana logiikkapommana, joka voisi tuhota suuren osan teollisesta yhteiskunnasta. Yhdysvaltain hallituksen Office of Management and Budget kuvaili ongelmaa raportissaan "Getting Federal Computers Ready for 2000", päivätty 7. helmikuuta 1997. Raportissa todetaan: "Ellei niitä korjata tai vaihtaa, tietokoneet epäonnistuvat vuosituhannen vaihtuessa kolmella tavalla: ne hylkäävät oikeat syötteet, laskevat virheellisiä tuloksia tai eivät yksinkertaisesti toimi." Näiden kolmen seurauksen yhteisvaikutus voisi lamauttaa teollisen yhteiskunnan. Sen massatuotantoteknologia on määräytymässä uuden miniatyrisoinnin teknologian varaan joka tapauksessa. Lähiaikainen kriisi vain nopeuttaa tätä prosessia. Uuden tietotekniikan myötä on syntynyt myös uusi ei-lineaarisen dynamiikan tiede, jonka hämmästyttävät johtopäätökset ovat vieläkin vain säikeitä, jotka odottavat punottavansa yhteen kokonaisvaltaiseksi maailmankuvaksi. Elämme tietokoneiden aikaa, mutta unelmiamme kutotaan yhä kangaspuilla. Jatkamme elämäämme teollisuuden metaforien ja ajatusten mukaan. Politiikkamme edelleen jakautuu teollisen jakolinjan – oikean ja vasemman – välillä, kuten Adam Smithin ja Karl Marxin kaltaiset ajattelijat osoittivat, jotka kuolivat ennen kuin lähes kuka tahansa nykyään elävistä syntyi.[^28] Teollinen maailmankuva, joka sisältää teollisen tieteen toimintaperiaatteet, on yhä koulutettujen ihmisten "järkevä intuitio", mutta teesimme on, että teollisen aikakauden "yksiulotteinen järki" ei enää päde monilla alueilla maailmaa muuttuessa.



Yli kahdeksankymmentäviisi vuotta siitä päivästä vuonna 1911, jolloin Oswald Spenglerin mieleen iski intuitio tulevasta maailmansodasta ja "Lännen rappeutumisesta", mekin näemme "*historiallisen vaiheenvaihdoksen* tapahtuvan … juuri sillä hetkellä, joka sille oli ennalta määrätty satoja vuosia sitten."[^26] Spenglerin tavoin me näemme Lännen sivilisaation uhkaavan kuoleman ja siihen liittyvän maailmanjärjestyksen romahtamisen, joka on vallitseva näiden viiden vuosisadan aikana siitä lähtien, kun Columbus purjehti länteen avatessaan kontaktin uuteen maailmaan. Toisin kuin Spengler, me näemme kuitenkin Lännen sivilisaation uuden vaiheen syntymän tulevana vuosituhantena.

[^1]: Danny Hillis, "The Millennium Clock," Wired, Special Edition, Fall 1995, p.48.
[^2]: Ericka Cheetham, The Final Prophecies of Nostradamus (New York: Putnam,1989), p.424.
[^3]: Dr. Edward Yardeni, Year 2000 Recession: "Prepare for the worst. Hope for the best," Version 5.0, May 13, 1998, B1.2.
[^4]: Michael Grasso, The Millenium Myth: Love and Death at the End of Time, Wheaton, Illinois: Quest Books, 1995.

[^5]: Johan Huizinga, *The Waning of the Middle Ages*, kääntänyt E Hopman (London: Penguin Books, 1990), s. 172.

[^6]: Marshall McLuhan, Understanding Media, New York: Signet, 196, s. 19.

[^7]: James George Frazer, *The Golden Bough: A Study in Magic and Religion* (New York: Macmillan, 1951), s. 105.

[^8]: Lisätietoja hajanaisista suvereniteeteista kansallisvaltion edeltäjänä ja vaihtoehtona, katso Charles Tilly, *Coercion, Capital and European States AD 990-1992* (Oxford: Blackwell, 1993).

[^9]: Saksalainen GPI-indeksi oli 33,20 31. joulukuuta 1948 ja 112,90 30. kesäkuuta 1995, mikä vastaa 2,7 prosentin yhdistettyä vuotuista arvonalenemista. Yhdysvaltain kuluttajahintaindeksi (CPI) oli 24 31. joulukuuta 1948 ja 152,50 30. kesäkuuta 1995. Kumulatiivinen Yhdysvaltain inflaatio oli 635 prosenttia kyseisenä ajanjaksona.

[^10]: Janet L. Abu-Lughod, Before European Hegemony: The World System A.D.1250-1350 (Oxford: Oxford University Press, 1991), s. 62.

[^11]: Jack Cohen ja Ian Stewart, The Collapse of Chaos (New York: Viking, 1994).

[^12]: Katso James Dale Davidson ja Lord William Rees-Mogg, *The Great Reckoning*, 2. painos (New York: Simon & Schuster, 1993), s. 53.

[^13]: Frederic C. Lane, "Economic Consequences of Organized Violence," The Journal of Economic History, vol. 18, no. 4 (joulukuu 1958), s. 402.

[^14]: Nicholas Colehester, "Goodbye NationState, Hello . . . What?," New York Times, 17. heinäkuuta 1994, s. E17.

[^15]: Norman Macrae, "Governments in Decline," Cato Policy Report, heinä-/elokuu 1992, s. 10.

[^16]: Arthur C. Clarke, Profiles of the Future: An Enquiry into the Limits of the Possible (London: Victor Gollancz Ltd., 1962), s. 13.

[^17]: Ibid.

[^18]: A. T. Mann, Millennium Prophecies: Predictions for the Year 2000 (Shafiesbury, England: Element Books, 1992), s. 88, 112, 117.

[^19]: Yardeni, op. cit., s. 45.

[^20]: Viitattu teoksessa Frooso, op. cit., s. 40.

[^21]: Ibid

[^22]: William Playfair, An Inquiry into the Permanent Causes of the Decline and Fall of Powerful and Wealthy Nations: Designed to Show How the Prosperity of the British Empire May be Prolonged (London: Greenland and Norris, 1805), s. 79.

[^23]: Guy Bois, The Transformation of the Year One Thousand: The Village of Lournard from Antiquity to Feudalism (Manchester, England: Manchester University Press, 1992).

[^24]: Ibid., s. 150.

[^25]: Lainattu teoksesta S. B. Saul, The Myth of the Great Depression (London: Macmillan, 1985), s. 10.

[^26]: Oswald Spengler, The Decline of the West, trans. Charles Francis Atkinson, lainattu I. F. Clarkin teoksesta The Pattern of Expectation, 1644-2001 (London: Jonathan Cape, 1979), s. 220.

[^27]: Nomenklatunas ovat ne juurtuneet eliitit, jotka hallitsivat entistä Neuvostoliittoa ja muita valtion ohjauksessa toimivia talouksia.

[^28]: Adam Smith kuoli vuonna 1790, Karl Marx vuonna 1883.