# Muutoksen vaihe vuonna 2000

> "Vaikuttaa siltä, että jotain suurta on tapahtumassa: graafit näyttävät meille väestömäärien vuosittaisen kasvun, hiilidioksidin ilmakehän pitoisuuksien nousun, verkkosivujen määrän sekä megatavujen määrän per dollari. Kaikki ne kohoavat kohti asymptoottista rajaa, joka sijaitsee vuosisadan vaihteen juuri tuolla puolen: Singulariteetti. Kaiken tuntemamme loppu. Jotakin, mitä emme ehkä koskaan ymmärrä." [^1] - Danny Hillis

## Ennakkovaroitukset

Vuoden 2000 saapuminen on kummitellut länsimaista mielikuvitusta jo vuosituhannen ajan. Siitä lähtien, kun maailma ei päättynyt Kristuksen jälkeisen ensimmäisen vuosituhannen vaihteessa, teologit, evankelistit, runoilijat ja ennustajat ovat katseet suunnanneet tämän vuosikymmenen loppua kohti odotuksen kanssa, että se toisi mukanaan jotakin merkittävää. Ei kukaan muu auktoriteetti kuin Isaac Newton spekuloikin, että maailma päättyisi vuoteen 2000. Michel de Nostradamus, jonka ennustuksia on luettu joka sukupolvi siitä lähtien, kun ne julkaistiin ensimmäisen kerran vuonna 1568, ennusti kolmannen Antikristuksen saapuvan heinäkuussa 1999.[^2] Sveitsiläinen psykologi Carl Jung, "yhteisön tiedostamattoman" asiantuntija, kuvitteli uuden aikakauden syntymän vuonna 1997. Tällaiset ennustukset saattavat helposti herättää naurun. Samoin vakavat taloustieteilijöiden ennusteet, kuten Dr. Edward Yardenin – Deutsche Bank Securitiesin – arvaukset siitä, että tietokoneiden viat millenniaalikeskiyöllä "häiritsevät koko globaalin talouden," saattavat vaikuttaa epäuskottavilta.[^3] Mutta olipa näkemyksesi Y2K-tietokoneongelmasta sitten perustelemattoman hysterian tuloksena, jota ovat herättelemässä tietokoneohjelmoijat ja IT-konsultit liiketoiminnan hyödyntämiseksi, tai mysteerisenä ilmentymänä teknologiasta, joka toteutuu ennustuksellisen mielikuvituksen kanssa yhtenäisesti, ei voi kiistää, että vuosituhannen kynnyksellä vallitsevat olosuhteet herättävät enemmän kuin tavanomaista synkkää epäilyä siitä, mihin maailma on menossa.

Tulevaisuudesta huolestuneisuuden tunne on alkanut pilata länsimaisten yhteiskuntien 250 vuotta kuvaavaa optimismia. Ihmiset kaikkialla ovat epäröiviä ja huolissaan. Näet sen heidän kasvoillaan. Kuulit sen heidän keskusteluistaan. Se heijastuu kyselyissä ja rekisteröidään äänestyslaatikossa. Aivan kuten näkymätön, fysikaalinen ionien muutos ilmakehässä ilmoittaa myrskyn lähestymisestä jo ennen kuin pilvet tummuvat ja salamat iskevät, niin nyt, vuosituhannen hämärässä, muutosennusteet ovat ilmassa. Yksi ihminen toisensa jälkeen, kukin omalla tavallaan, aistii ajan hupenevan tietyssä, kuolevassa elämäntavassa. Kun vuosikymmen umpeutuu, murhaava vuosisata päättyy, samoin kuin loistava vuosituhannen mittainen inhimillinen saavutuskausi. Kaikki ovat loppumassa vuoden 2000 myötä.

> "Sillä mikään, mikä on piilotettu, ei pysy salassa, eikä mikään, mikä on kätketty, jää tuntematta." - Matteus 10:26

Uskomme, että länsimaisen sivilisaation moderni vaihe päättyy sen myötä. Tämä kirja kertoo miksi. Kuten monet aiemmat teokset, se on yritys nähdä lasin läpi sumuisesti, hahmotella vielä tulevan tulevaisuuden hämäräpiirteisiä muotoja ja ulottuvuuksia. Tässä mielessä tarkoitamme työmme olevan apokalyptinen alkuperäisessä merkityksessään: apokalypsis tarkoittaa kreikaksi "paljastamista". Uskomme, että uusi vaihe historiassa – informaatioaika – on kohta "paljastumassa".

> "Seuraamme uuden loogisen tilan alkuja, välitöntä elektronista kaikkiallaoloa, johon me kaikki voimme päästä, josta voimme tulla osaksi ja kokea. Meillä on lyhyesti sanottuna uudenlaisen yhteisön alku. Virtuaaliyhteisöstä tulee malli maalliselle Taivaan valtakunnalle; kuten Jeesus sanoi, että hänen Isänsä valtakunnassa oli monta kartanoa, niin on myös monia virtuaaliyhteisöjä, jotka heijastavat omia tarpeitaan ja toiveitaan." - Michael Grasso[^4]

## Ihmiskunnan neljäs vaihe

Tämän kirjan teema on uusi vallankumous, joka vapauttaa yksilöitä 1900-luvun kansallisvaltion kustannuksella. Innovaatioiden, jotka muuttavat väkivallan logiikkaa ennennäkemättömillä tavoilla, ovat muokkaamassa niitä rajoja, joiden sisällä tulevaisuuden on elettävä. Jos johtopäätöksemme pitävät paikkansa, olet menossa historian laajimman vallankumouksen kynnykselle. Nopeammin kuin harvat nyt edes kuvittelevat, mikroprosessointi tulee syrjäyttämään ja tuhoamaan kansallisvaltion, luoden samalla uusia sosiaalisen järjestäytymisen muotoja. Tämä muutos ei tule olemaan lainkaan helppo.



Haaste, jonka uusi kehitys tuo mukanaan, on entistäkin suurempi, sillä se tapahtuu uskomattoman nopeasti verrattuna kaikkeen aiemmin nähtyyn. Koko ihmiskunnan historiassa sen varhaisista alkuajoista tähän päivään asti on ollut vain kolme taloudellisen elämän perusvaihetta: (1) metsästys- ja keräilyyhteiskunnat; (2) maatalousyhteiskunnat; ja (3) teollisuusyhteiskunnat. Nyt horisontissa on jotain täysin uutta – sosiaalisen järjestäytymisen neljäs vaihe: informaatioyhteiskunnat.

Jokainen edelliseltä yhteiskuntavaiheelta on löytynyt selvästi erilaisia vaiheita väkivallan kehittymisessä ja hallinnassa. Kuten käymme yksityiskohtaisesti läpi, informaatioyhteiskunnat lupaavat dramaattisesti vähentää väkivallan tuottoja osin siksi, että ne ylittävät paikallisuuden rajoitteet. Kyberavaruuden virtuaalitodellisuus – mitä kirjailija William Gibson kuvaili "kansan yhteiseksi hallusinaatioksi" – tulee olemaan yhtä kaukana kiusaajien ulottumattomissa kuin mielikuvitus voi kantaa.

Uudella vuosituhannella etu kontrolloida väkivaltaa suuressa mittakaavassa tulee olemaan huomattavasti pienempi kuin milloin tahansa Ranskan vallankumousta edeltäneenä aikana. Tällä on syvälliset seuraukset. Yksi näistä on rikollisuuden kasvu. Kun suurimman mittakaavan väkivallan järjestämisen tuotto romahtaa, pienemmässä mittakaavassa tapahtuvan väkivallan tuotto todennäköisesti kasvaa. Väkivalta tulee muuttumaan satunnaisempaa ja paikallistettua, ja järjestäytynyt rikollisuus laajenee – selitämme miksi.

Toinen looginen seuraus väkivallan tuottojen laskusta on politiikan väheneminen. On runsaasti todisteita siitä, että 1900-luvun kansallisvaltion kansalaismyeetit rappeutuvat nopeasti; Kommunismin kuolema on vain ilmeisin esimerkki. Kuten tarkastelemme yksityiskohtaisesti, moraalin romahtaminen ja kasvava korruptio länsimaisten hallitusten johtajien keskuudessa eivät ole satunnaisia kehityssuuntia, vaan osoitus siitä, että kansallisvaltion potentiaali on käytetty loppuun. Jopa monet sen johtajista eivät enää usko niihin kuin lausuttui, eivätkä muut enää ota heitä vakavasti.

### Historia toistaa itseään

Tilanne, jossa on pettävistä yhtäläisyyksiä menneisyydessä, on nyt vallitseva. Aina kun teknologinen muutos erottaa vanhat muodot uusista talouden liikkeellepanevista voimista, moraalinen taso muuttuu ja ihmiset alkavat suhtautua halvemmin niihin, jotka hallitsevat vanhoja instituutioita. Tämä laaja leimaantuminen tulee usein esiin jo kauan ennen kuin ihmiset kehittävät uuden yhtenäisen muutoksen ideologian. Näin oli myöhään 1400-luvulla, jolloin keskiaikainen kirkko oli feodalismi-instituutioiden hallitseva voima. Huolimatta yleisestä uskomuksesta "papin viran pyhyydestä" sekä kirkon korkea- että matalarankaiset papsit saivat äärimmäistä halveksuntaa – aivan kuten nykyään poliitikkoja ja byrokraatteja kohtaan on.

Uskomme, että paljon voidaan oppia vertaamalla 1400-luvun lopun tilannetta, jolloin elämä oli täysin kyllästetty organisoituun uskontoon, nykytilanteeseen, jolloin maailma on kyllästetty politiikasta. Uskonnotettujen instituutioiden ylläpitokustannukset olivat 1400-luvun lopussa saavuttaneet historiallisesti äärimmäisen tason, aivan kuten hallituksen ylläpitokustannukset ovat saavuttaneet iäkkään äärimmäisen tason nykypäivänä.

Me tiedämme, mitä tapahtui organisoidulle uskonnolle Krutiiniräjähdyksen jäljiltä. Teknologiset kehitykset loivat vahvat kannustimet karsia uskonnollisia instituutioita ja alentaa niiden kustannuksia. Vastaavanlaisen teknologisen murroksen on tarkoitus radikaalisti pienentää kansallisvaltiota uuden vuosituhannen alkuvaiheessa.

> Tänä päivänä, yli vuosisadan sähköteknologian jälkeen, olemme laajentaneet keskushermostoamme globaalisti, poistamalla sekä tilan että ajan, mitä planeetallamme tulee kysymään.

### Informaatiomurros

Kun suurten järjestelmien romahdus kiihtyy, systemaattinen pakottaminen vähenee tekijänä, joka muovaa taloudellista elämää ja tulonjakautumista. Tehokkuudesta tulee nopeasti tärkeämpää kuin vallan määräykset sosiaalisten instituutioiden järjestämisessä. Tämä tarkoittaa, että maakunnat ja jopa kaupungit, jotka voivat tehokkaasti turvata omaisuusoikeuksia ja järjestää oikeudenhoitoa kuluttaen vain vähän resursseja, tulevat olemaan käyttökelpoisia itsenäisyyksiä Informaatiokaudella – toisin kuin yleensä on ollut viimeisten viiden vuosisadan aikana.

Täysin uusi taloudellisen toiminnan alue, joka ei ole sidottu fyysiseen väkivaltaan, tulee syntymään kyberavaruudessa. Käypiä hyötyjä saavuttaa selkeinä ne "kognitiiviset eliitit," jotka tulevat yhä enemmän toimimaan poliittisten rajojen ulkopuolella. He ovat jo nyt yhtä lailla kotona Frankfurtissa, Lontoossa, New Yorkissa, Buenos Airesissa, Los Angelesissa, Tokiossa ja Hongkongissa. Tulot tulevat eriytymään niiden sisällä, mutta tasaantumaan niiden välillä.

The Sovereign Individual tutkii tämän vallankumouksellisen muutoksen sosiaalisia ja taloudellisia seurauksia. Haluamme auttaa sinua hyödyntämään uuden aikakauden tarjoamia mahdollisuuksia ja välttämään sen vaikutuksista aiheutuvaa tuhoa. Jos edes puolet siitä, mitä odotamme näkevämme, toteutuu, edessäsi on poikkeuksellisen mittainen muutos, jolla on hyvin vähän ennakkotapauksia historiassa.

Vuoden 2000 muutos ei ainoastaan mullista maailman talouden luonnetta, vaan se tapahtuu nopeammin kuin mikään aiempi vaihemuutos. Toisin kuin maatalousvallankumous, tietoyhteiskunnan vallankumous ei vie vuosituhansia toteuttaakseen työnsä. Toisin kuin teollinen vallankumous, sen vaikutukset eivät puraudu vuosisatojen mittaan. Tietoyhteiskunnan vallankumous tapahtuu elämän aikana.

Mikä parasta, se toteutuu lähes kaikkialla samanaikaisesti. Teknologiset ja taloudelliset innovaatiot eivät enää rajoitu pieneen osaan maailmaa. Muutos on käytännössä universaali. Lisäksi se edustaa niin syvällistä irtautumista menneisyydestä, että se lähes herättää henkiin jumalten maagisen valtakunnan – sellaisena kuin varhaiset maatalousyhteisöt, esimerkiksi antiikin kreikkalaiset, sen kuvittelivat. Sen verran, että monet nykyään eivät olisi edes valmiita myöntämään, monet nykyaikaiset instituutiot osoittautuvat vaikeiksi tai mahdottomiksi säilyttää uudella vuosituhannella. Kun tietoyhteiskunnat muotoutuvat, ne eroavat teollisyhteiskunnista samalla tavalla kuin Aeschyluksen Kreikka poikkesi luolissa asuvien maailmasta.

## PROMETHEUS UNBOUND: THE RISE OF THE SOVEREIGN INDIVIDUAL

> En tiedä yhtään rohkaisevampaa faktaa kuin se, että ihminen kykenee nostamaan elämäänsä tietoisen ponnistelun avulla - Henry David Thoreau

Koittava muutos on sekä hyviä että huonoja uutisia. Hyvänä uutisena voidaan todeta, että tietoyhteiskunnan vallankumous vapauttaa yksilöt ennennäkemättömällä tavalla. Ensimmäistä kertaa ne, jotka kykenevät kouluttamaan itseään, ovat lähes täysin vapaita keksimään omia töitään ja saamaan täyden hyödyn omasta tuottavuudestaan. Neroisuus vapautuu, kun se pääsee vapaaksi sekä hallituksen sortamisesta että rodullisten ja etnisten ennakkoluulojen pidättelemästä. Tietoyhteiskunnassa ketään, joka on aidosti kykenevä, ei pidätetä muiden huonosti perusteltujen mielipiteiden vuoksi. Ei väliä, mitä suurin osa maan ihmisistä ajattelee rodustasi, ulkonäöstäsi, iästäsi, seksuaalisista taipumuksistasi tai siitä, miten käytät hiuksiasi. Kybertaloudessa he eivät koskaan näe sinua. Rouskuat, lihavat, vanhat ja vammaiset kilpailevat nuorten ja kauniiden kanssa tasavertaisesti täysin värinäkemättömässä anonymiteetissa kyberavaruuden uusilla rajoilla.

### Ideat muuttuvat vaurauteksi

Missä tahansa ansio ilmenee, sitä palkitaan ennennäkemättömällä tavalla. Ympäristössä, jossa varallisuuden suurin lähde on päässäsi pyörivät ideat eikä pelkkä fyysinen pääoma, jokainen selkeästi ajattelevainen ihminen voi teoriassa vaurastua. Tietoyhteiskunta tulee olemaan nousun aikakausi. Se tarjoaa paljon tasavertaisemmat mahdollisuudet miljardien ihmisten kesken niillä alueilla, jotka eivät koskaan jakaneet teollisyhteiskunnan vaurautta täysin. Näistä kirkkaimmat, menestyneimmät ja kunnianhimoisimmat nousevat todellisiksi Sovereign Individuaaleiksi.

Aluksi vain harvat saavuttavat täyden taloudellisen itsemääräämisoikeuden. Tämä ei kuitenkaan mitätöi taloudellisen riippumattomuuden etuja. Se, että kaikilla ei ole saman mittaista valtavaa rikkautta, ei tarkoita, että rikkaaksi tuleminen olisi turhaa tai merkityksetöntä. Jokaisesta miljardääristä on olemassa 25 000 miljoonaaria. Jos olet miljonääri etkä miljardääri, se ei tee sinusta köyhää. Samoin tulevaisuudessa yksi merkkipaalu, jonka perusteella mittaat taloudellista menestystäsi, ei ole ainoastaan se, kuinka monta nollaa voit lisätä nettovarallisuuteesi, vaan myös se, pystytkö järjestämään asioitasi siten, että saavutat täyden yksilöllisen autonomian ja itsenäisyyden. Mitä älykkäämpi olet, sitä vähemmän vauhtia tarvitset saavuttaaksesi taloudellisen karkuunpääsyn. Jopa vaatimattomilla varoilla olevat ihmiset nousevat, kun politiikan vetovoima globaalissa taloudessa heikkenee. Ennennäkemätön taloudellinen riippumattomuus on tavoitettavissa joko sinun elinaikanasi tai lapsiesi elinaikana.

Tuottavuuden korkeimmalla tasanteella nämä Sovereign Individuaalit kilpailevat ja toimivat suhteissa, jotka muistuttavat kreikkalaisen mytologian jumalten välisiä suhteita. Seuraavan vuosituhannen haihtuva Mount Olympus tulee löytymään kyberavaruudesta – alueesta, jolla ei ole fyysistä olemassaoloa, mutta joka silti kehittyy lupaavaksi maailman suurimmaksi taloudeksi uuden vuosituhannen toisen vuosikymmenen mennessä. Vuoteen 2025 mennessä kybertaloudessa on useita miljoonia osallistujia. Jotkut heistä ovat yhtä rikkaita kuin Bill Gates, arvoltaan yli 10 miljardin dollarin. Kyberköyhät taas saattavat olla niitä, joiden vuositulot ovat alle 200 000 dollaria. Kyberhyvinvointia ei ole. Ei ole kyberveroja eikä kyberhallitusta. Kybertalous voisi hyvin olla seuraavien kolmenkymmenen vuoden suurin taloudellinen ilmiö, ennemminkin kuin Kiina.

Hyvä uutinen on, että poliitikot eivät enää pysty hallitsemaan, sortamaan ja säätelemään suurinta osaa kaupankäynnistä tässä uudessa maailmassa samalla tavalla kuin antiikin kreikkalaisten kaupunkivaltioiden lainsäätäjät olisivat voineet pilkkoa Zeuksen partaa. Se on hyvä uutinen rikkaille. Ja vielä parempi uutinen vähemmän varakkaille. Politiikan aiheuttamat esteet ja taakat muodostavat enemmänkin hankaluuksia rikastua kuin olla varakas. Vähenemisen myötä väkivallan tuottamat tappiot ja alalta poistuvat toimivaltuudet tarjoavat mahdollisuuden jokaiselle energiselle ja kunnianhimoiselle ihmiselle hyötyä politiikan kuolemasta. Jopa julkisten palveluiden käyttäjät hyötyvät, kun yrittäjät levittävät kilpailun myötä sen hyödyt laajemmalle. Tämän seurauksena merkittävä osa eri toimivaltuuksien välisestä kilpailun nerokkuudesta on kanavoitunut sotilaallisiin pyrkimyksiin. Mutta kybertalouden etu tuo kilpailun täysin uusilla ehdoilla suvereniteettipalvelujen tuottamiseen. Useiden toimivaltuuksien leviäminen tarkoittaa kokeilunhaluisuuden lisääntymistä uusissa tavoissa panna sopimukset täytäntöön ja muilla tavoilla turvata ihmisten ja omaisuuden turvallisuus. Globaalin talouden vapautuminen poliittisesta kontrollista pakottaa kaikki jäljellä olevat hallituksen muodot toimimaan yhä enemmän markkinaehtojen mukaisesti. Lopulta niillä ei jää muuta vaihtoehtoa kuin kohdella alueillaan asuvia väestöjä enemmän kuin asiakkaita, eikä tavalla, jolla järjestäytyneet rikollisryhmät kohtelevat shakedown-huijauksen uhreja.

### Beyond Politics

Se, mitä mytologiassa kuvailtiin jumalten valtakuntana, tulee tulemaan yksilölle elinkelpoiseksi vaihtoehdoksi – elämäksi, joka on vapaa kuninkaiden ja neuvostojen ulottumattomiin. Aluksi kymmenesosina, sitten sadoina ja lopulta miljoonina yksilöt pääsevät irti politiikan kahleista. Samaan aikaan, kun he onnistuvat siinä, he muuttavat hallitusten luonnetta, kaventaen pakkomääräyksen valtakuntaa ja laajentaen yksityisen hallinnan mahdollisuuksia resursseihin.

Suvereenin yksilön synty osoittaa jälleen kerran myytin oudon profeetallisen voiman. Varhaiset maanviljelykansat, joilla ei juuri otettu huomioon luonnonlakeja, kuvittelivat, että "voimia, joita meidän tulisi kutsua yliluonnollisiksi", oli laajalti jaettu. Näitä voimia käytettiin toisinaan ihmisten toimesta, toisinaan "ruumiillistuneiden ihmisenjumalien" toimesta, jotka näyttivät ihmisiltä ja vuorovaikuttivat heidän kanssaan siinä, mitä Sir James George Frazer kuvaili The Golden Bough -teoksessaan "suureksi demokratiaksi".

Kun muinaiset kuvittelivat Zeuksen lapsia asuvan puolellaan, heitä innoitti syvä usko taikuuteen. He jakoivat muiden primitiivisten maanviljelykansojen kanssa ihmetystä luontoa kohtaan sekä maagisen vakaumuksen siitä, että luonnon ilmiöt olivat käynnistettyjä yksittäisten tahdonvoimien toimesta, taikuuden kautta. Tässä mielessä heidän näkemyksessään luonnosta ja jumalistostaan ei ollut mitään tietoisesti profeetallista. He eivät osanneet kuvitellakaan mikrotekniikkaa. He eivät olisi voineet kuvitella sen vaikutusta yksilöiden marginaalituottavuuden muuttamiseen tuhansia vuosia myöhemmin. He eivät todellakaan osanneet ennustaa, kuinka se siirtäisi tasapainoa vallan ja tehokkuuden välillä ja siten mullistaisi tavan, jolla omaisuuksia luodaan ja suojataan. Silti se, mitä he kuvittelivat myyttejään luodessaan, resonoi kummallisesti sen maailman kanssa, jonka todennäköisesti kohtaamme.

### Alt.Abracadabra

Esimerkiksi taikasanan "abracadabra" lausuminen kantaa kummallista samankaltaisuutta tietokoneeseen kirjautumiseen käytettävän salasanan kanssa. Joissakin suhteissa huippunopeassa laskennassa on jo mahdollista jäljitellä hengen taikuutta. Varhaiset "digitaalisten palvelijoiden" sukupolvet tottelevat jo niiden, jotka hallitsevat niitä tietokoneita, joissa ne on suljettu, aivan kuten henget tottelevat niitä, jotka hallitsevat taikalamppuja. Tietotekniikan virtuaalitodellisuus laajentaa inhimillisten toiveiden aluetta niin, että melkein kaikki, mitä voi kuvitella, näyttäisi todennäköisesti todelliselta. Etäolosuhteet antavat elävien yksilöiden saman kyvyn ylittää etäisyydet yliluonnollisella nopeudella ja valvoa tapahtumia kaukaa, aivan kuten kreikkalaisten mukaan Hermes ja Apollo pystyivät. Tietoaikakauden suvereenit yksilöt nauttivat lopulta eräänlaista "diplomaattista koskemattomuutta" useimmilta niiltä poliittisilta ongelmilta, jotka ovat vuosien ja paikkojen kuluessa kohdanneet kuolevaisia ihmisiä.

Uusi suvereeni yksilö toimii kuin mytologiassa jumalat samassa fyysisessä ympäristössä tavallisten, alaisten kansalaisten kanssa, mutta poliittisesti erillisessä maailmassa. Johtaen valtavasti suurempia resursseja ja ollen monien pakkojen ulottumattomissa, suvereeni yksilö uudelleen suunnittelee hallituksia ja muokkaa talouksia uudelleen uudella vuosituhannella. Tämän muutoksen täysimittaiset seuraukset ovat lähes käsittämättömiä.

### Genius and Nemesis

Kenelle tahansa, joka rakastaa ihmisen pyrkimystä ja menestystä, tietoaikakausi tarjoaa runsautta. Se on varmasti parhaat uutiset monelle sukupolvelle. Mutta se on myös huono uutinen. Uusi yhteiskunnan järjestäytyminen, joka seuraa yksilöllisen autonomian voittoa ja todellisesti ansioon perustuvan mahdollisuuksien tasa-arvon toteutumista, johtaa valtaviin palkkioihin ansioista ja suuresta yksilöllisestä autonomiasta. Tämä jättää yksilöt paljon vastuullisemmiksi itsestään kuin heillä on ollut teollisena aikana. Se myös vähentää ansaitsemattomia etuja elintasossa, joista kehittyneiden teollisuusyhteiskuntien asukkaat ovat nauttineet koko kahdenkymmentäntenä vuosisatana. Juuri nyt maailman 15 prosenttia väestöstä tienaa keskimäärin 21 000 dollaria vuodessa henkeä kohti. Jäljelle jäävä 85 prosenttia maailman väestöstä tienaa keskimäärin vain 1 000 dollaria. Se valtava, kertyneenä ollut etu menneisyydestä on sidottu hajoamaan tietoaikakauden uusien olosuhteiden alla.

As it does, the capacity of nationstates to redistribute income on a large scale will collapse.  
Mikäli näin tapahtuu, kansallisvaltioiden kyky uudelleenjakaa tuloja laajassa mittakaavassa romahtaa. Tietoteknologia mahdollistaa dramaattisesti lisääntyvän kilpailun eri toimivaltakuntien välillä. Kun teknologia on liikkuvaa ja tapahtumat suoritetaan kyberavaruudessa, kuten yhä useammin tulee tapahtumaan, hallitukset eivät enää kykene laskuttamaan palveluistaan enemmän kuin mihin niiden on arvoa maksavien ihmisten mielestä. Jokaisella, jolla on kannettava tietokone ja satelliittiyhteys, on mahdollisuus harjoittaa lähes mitä tahansa tietopohjaista liiketoimintaa missä tahansa – tämä kattaa lähes koko maailman monitriljoonaaristen rahoitustapahtumien hoitamisen.

This means that you will no longer be obliged to live in a high-tax jurisdiction in order to earn high income.  
Tämä tarkoittaa, että sinun ei enää tarvitse asua korkeaveroisessa toimivaltakunnassa saadaksesi korkeita tuloja.

In the future, when most wealth can be earned anywhere, and even spent anywhere, governments that attempt to charge too much as the price of domicile will merely drive away their best customers.  
Tulevaisuudessa, kun suurin osa varallisuudesta on mahdollista ansaita ja jopa kuluttaa missä tahansa, hallitukset, jotka pyrkivät perimään liikaa asuinpaikkamaksuja, karkottavat parhaita asiakkaitaan.

If our reasoning is correct, and we believe it is, the nationstate as we know it will not survive in anything like its present form.  
Jos päättelymme pitää paikkansa – ja uskomme sen olevan niin – kansallisvaltio sellaisena kuin me sen nykyään tunnemme, ei säily tulevaisuudessa olennaisesti nykyisessä muodossaan.

## Kansallisvaltioiden loppu

Changes that diminish the power of predominant institutions are both unsettling and dangerous.  
Muutokset, jotka heikentävät hallitsevien instituutioiden valtaa, ovat yhtä aikaa huolestuttavia ja vaarallisia.

Just as monarchs, lords, popes, and potentates fought ruthlessly to preserve their accustomed privileges in the early stages of the modern period, so today's governments will employ violence, often of a covert and arbitrary kind, in the attempt to hold back the clock.  
Aivan kuten kuninkaat, herrot, paavat ja vaikutusvaltaiset henkilöt taistelivat armottomasti säilyttääkseen perinteiset etuoikeutensa modernin ajan alkuvaiheissa, myös nykypäivän hallitukset tulevat käyttämään väkivaltaa – usein salakavalassa ja mielivaltaisessa muodossa – pyrkiessään hidastamaan ajan kulkua.

Weakened by the challenge from technology, the state will treat increasingly autonomous individuals, its former citizens, with the same range of ruthlessness and diplomacy it has heretofore displayed in its dealing with other governments.  
Teknologian asettaman haasteen vuoksi heikentyneenä valtio tulee kohdeloimaan yhä itsenäisempiä yksilöitä – entisiä kansalaisiaan – samalla armottomuuden ja diplomatian kirjoilla, jota se on tähän asti osoittanut toimiessaan muiden hallitusten kanssa.

The advent of this new stage in history was punctuated with a bang on August 20, 1998, when the United States fired about $200 million worth of Tomahawk BGM-109 sea-launched cruise missiles at targets allegedly associated with an exiled Saudi millionaire, Osama bin Laden.  
Tämän uuden historian vaiheen alkua merkitsi räjähdysmäisesti 20. elokuuta 1998, kun Yhdysvallat laukaisi noin 200 miljoonan dollarin arvoisia Tomahawk BGM-109 -merirannikolta laukattuja rantikiitoraketteja kohteisiin, joiden oletettiin olevan yhteydessä karkotettuun saudi-miljonääriin Osama bin Ladeniin.

Bin Laden became the first person in history to have his satellite phone targeted for attack by cruise missiles.  
Bin Ladenista tuli ensimmäinen henkilö historiassa, jota vastaan hyökkäyksiä kohdistettiin satelliittipuhelimen avulla.

Simultaneously, the United States destroyed a pharmaceutical plant in Khartoum, Sudan, in Bin Laden's honor.  
Samanaikaisesti Yhdysvallat tuhosi lääketehtaan Khartoumissa, Sudanin pääkaupungissa, Bin Ladenin kunniaksi.

The emergence of Bin Laden as the enemy-in-chief of the United States reflects a momentous change in the nature of warfare.  
Bin Ladenin nousu Yhdysvaltojen pääviholliseksi heijastaa mullistavaa muutosta sodankäynnin luonteessa.

A single individual, albeit one with hundreds of millions of dollars, can now be depicted as a plausible threat to the greatest military power of the Industrial era.  
Yksi yksittäinen henkilö, vaikka hänellä olisi satoja miljoonia dollareita, voidaan nyt esittää uskottavana uhkana teollisuusajan suurimmalle sotilasvallalle.

In statements reminiscent of propaganda employed during the Cold War about the Soviet Union, the United States president and his national security aides portrayed Bin Laden, a private individual, as a transnational terrorist and leading enemy of the United States.  
Kylmän sodan aikana Neuvostoliittoa koskevan propagandan tapaiset lausunnot saivat Yhdysvaltojen presidentin ja hänen kansallisen turvallisuutensa neuvonantajat esittämään Bin Ladenin yksityishenkilönä, transnationaalisena terroristeina ja Yhdysvaltojen johtavana vihollisena.

The same military logic that has seen Osama bin Laden elevated to a position as chief enemy of the United States will assert itself in governments' internal relations with their subjects.  
Samankaltainen sotilaallinen logiikka, joka on nostanut Osama bin Ladeniin aseman Yhdysvaltojen päävihollisena, tulee vaikuttamaan myös hallitusten sisäisiin suhteisiin kansalaisiinsa.

Increasingly harsh techniques of exaction will be a logical corollary of the emergence of a new type of bargaining between governments and individuals.  
Yhä ankarammat riistämistekniikat tulevat olemaan looginen seuraus uudenlaisen neuvottelutavan kehittymisestä hallitusten ja yksilöiden välillä.

Technology will make individuals more nearly sovereign than ever before.  
Teknologia tekee yksilöistä entistä enemmän itsenäisiä kuin koskaan aiemmin.

And they will be treated that way.  
Ja heitä kohdellaan juuri niin.

Sometimes violently, as enemies, sometimes as equal parties in negotiation, sometimes as allies.  
Joskus väkivaltaisesti vihollisina, toisinaan tasa-arvoisina neuvottelukumppaneina ja joskus liittolaisina.

But however ruthlessly governments behave, particularly in the transition period, wedding the IRS with the CIA will avail them little.  
Mutta riippumatta siitä, kuinka armottomasti hallitukset käyttäytyvät – erityisesti siirtymäkaudella – IRS:n ja CIA:n yhdistäminen ei tuota heille juurikaan hyötyä.

They will be increasingly required by the press of necessity to bargain with autonomous individuals whose resources will no longer be so easily controlled.  
Heidän on yhä entistä useammin pakko neuvotella itsenäisten yksilöiden kanssa, joiden resursseja ei enää saa niin vaivattomasti hallintaan.

The changes implied by the Information Revolution will not only create a fiscal crisis for governments, they will tend to disintegrate all large structures.  
Tietotekniikan vallankumouksen tuomat muutokset eivät ainoastaan aiheuta hallituksille julkista talouskriisiä, vaan ne pyrkivät myös hajottamaan kaikki suuret rakenteet.

Fourteen empires have disappeared already in the twentieth century.  
Jo neljätoista imperiumia on kadonnut jo 1900-luvulla.

The breakdown of empires is part of a process that will dissolve the nationstate itself.  
Imperiumien romahtaminen on osa prosessia, joka lopulta liu'uttaa kansallisvaltioiden olemuksen.

Government will have to adapt to the growing autonomy of the individual.  
Hallinnon on sopeuduttava yksilön kasvavaan autonomiaan.

Taxing capacity will plunge by 50–70 percent.  
Verotuskapasiteetti romahtaa 50–70 prosentilla.

This will tend to make smaller jurisdictions more successful.  
Tämä edistää pienten toimivaltakuntien menestystä.

The challenge of setting competitive terms to attract able individuals and their capital will be more easily undertaken in enclaves than across continents.  
Kyky asettaa kilpailukykyiset ehdot kykenevien yksilöiden ja heidän pääomansa houkuttelemiseksi on helpommin toteutettavissa suljetuissa oloissa kuin mantereiden laajuudella.

We believe that as the modern nationstate decomposes, latter-day barbarians will increasingly come to exercise power behind the scenes.  
Uskomme, että modernin kansallisvaltioiden hajoamisen myötä nykyajan barbaarit tulevat yhä useammin näyttelemään vallan kulissien takana.

Groups like the Russian mafiya, which picks the bones of the former Soviet Union, other ethnic criminal gangs, nomenklaturas[^27], drug lords, and renegade covert agencies will be laws unto themselves.  
Ryhmät, kuten venäläinen mafiya, joka kerää entisen Neuvostoliiton luita, muut etniset rikollisjengit, nomenklatura[^27], huumekuningattaret ja kapinalliset salaiset virastot, tulevat olemaan omia sääntöjään. Ne ovat jo sellaisia.

They already are.  
Ne ovat jo sellaisia.

Far more than is widely understood, the modern barbarians have already infiltrated the forms of the nationstate without greatly changing its appearances.  
Paljon enemmän kuin yleisesti ymmärretään, modernit barbaarit ovat jo tunkeutuneet kansallisvaltioiden muotoihin muuttamatta niiden ulkoasua merkittävästi.

They are microparasites feeding on a dying system.  
Ne ovat mikroparasiitteja, jotka ravitsevat kuolevaa järjestelmää.

As violent and unscrupulous as a state at war, these groups employ the techniques of the state on a smaller scale.  
Nämä ryhmät, yhtä väkivaltaisia ja armottomia kuin sodassa oleva valtio, käyttävät valtion keinoja pienemmässä mittakaavassa.

Their growing influence and power are part of the downsizing of politics.  
Niiden kasvava vaikutusvalta ja voima ovat osa politiikan kutistumista.

Microprocessing reduces the size that groups must attain in order to be effective in the use and control of violence.  
Mikroprosessointi pienentää sen koon, johon ryhmien on pyrittävä ollakseen tehokkaita väkivallan käytössä ja hallinnassa.

As this technological revolution unfolds, predatory violence will be organized more and more outside of central control.  
Kun tämä teknologinen vallankumous etenee, saalistava väkivalta järjestetään yhä enemmän keskitetyn kontrollin ulkopuolella.

Efforts to contain violence will also devolve in ways that depend more upon efficiency than magnitude of power.  
Pyrkimykset hillitä väkivaltaa siirtyvät myös toimintatavoihin, jotka perustuvat enemmän tehokkuuteen kuin vallan mittakaavaan.

### Historia taaksepäin

The process by which the nationstate grew over the past five centuries will be put into reverse by the new logic of the Information Age.  
Prosessi, jonka kautta kansallisvaltio kasvoi viimeisten viiden vuosisadan aikana, käännetään uudelleen tietotekniikan aikakauden uudella logiikalla.

Local centers of power will reassert themselves as the state devolves into fragmented, overlapping sovereignties.  
Paikalliset valta-alueet tulevat ottamaan takaisin asemansa, kun valtio hajoaa pirstaleisiin, päällekkäisiin itsenäisyysalueisiin.

[^8] The growing power of organized crime is merely one reflection of this tendency.  
Järjestäytyneen rikollisuuden kasvava valta on vain yksi tämän taipumuksen ilmentymä.

Multinational companies are already having to subcontract all but essential work.  
Monikansallisten yritysten on jo nyt alihankittava kaikki paitsi välttämättömän tärkeä työ.

Some conglomerates, such as AT&T, Unisys, and ITT, have split themselves into several firms in order to function more profitably.  
Jotkut konglomeraatit, kuten AT&T, Unisys ja ITT, ovat jakautuneet useiksi yrityksiksi kannattavamman toiminnan saavuttamiseksi.

The nationstate will devolve like an unwieldy conglomerate, but probably not before it is forced to do so by financial crises.  
Kansallisvaltio hajoaa kuin kömpelö konglomeraatti, mutta luultavasti ei ennen kuin sen pakotetaan siihen talouskriisien vuoksi.

Not only is power in the world changing, but the work of the world is changing as well.  
Maailman vallan lisäksi myös talouden työ luonne muuttuu.

This means that the way business operates will inevitably change.  
Tämä tarkoittaa, että liiketoiminnan toimintatavat muuttuvat väistämättä.

The "virtual corporation" is evidence of a sweeping transformation in the nature of the firm, facilitated by the drop in information and transaction costs.  
"Virtuaalinen yritys" on todiste laajamittaisesta muutoksesta yrityksen luonteessa, jota mahdollistavat tietojen ja transaktiokustannusten lasku.

We explore the implications of the Information Revolution for dissolving corporations and doing away with the "good job."  
Tarkastelemme tietotekniikan vallankumouksen vaikutuksia yritysten hajoamiseen ja "hyvien työpaikkojen" katoamiseen.

In the Information Age, a "job" will be a task to do, not a position you "have."  
Tietotekniikan aikakaudella "työ" tarkoittaa tehtävää, ei asemaa, jota sinulla olisi.

Microprocessing has created entirely new horizons of economic activity that transcend territorial boundaries.  
Mikroprosessointi on luonut täysin uusia taloudellisen toiminnan horisontteja, jotka ylittävät maantieteelliset rajat.

This transcendence of frontiers and territories is perhaps the most revolutionary development since Adam and Eve straggled out of paradise under the sentence of their Maker: "In the sweat of thy face shalt thou eat bread."  
Rajojen ja alueiden ylittäminen on ehkä maailmanhistorian vallankumouksellisin muutos siitä lähtien, kun Adam ja Eeva eksyivät paratiisista Luojansa tuomitsemana: "Hikin kautta kasvosi saat syödä leipää."

As technology revolutionizes the tools we use, it also antiquates our laws, reshapes our morals, and alters our perceptions.  
Kun teknologia vallankumouksellistaa käyttämämme työkalut, se myös vanhentaa lakimme, muokkaa moraaliamme ja muuttaa käsityksiämme.

This book explains how.  
Tämä kirja selittää kuinka näin tapahtuu.

Mikroprosessorit ja nopeasti kehittyvä viestintä mahdollistavat jo sen, että yksilö voi valita, missä hän työskentelee. Internetissä tai World Wide Webissä tapahtuvat rahansiirrot voidaan salata, ja verottajien on pian lähes mahdotonta saada niitä kiinni. Verovapaat varat kertyvät jo nyt huomattavasti nopeammin offshore-alueilla kuin mantereella, jossa varat joutuvat edelleen 1900-luvun kansallisvaltion asettaman korkean verorasituksen alaisiksi.

Vuosituhannen vaihdteen jälkeen suuri osa maailman kaupasta siirtyy uuteen kyberavaruuden ulottuvuuteen, alueeseen, jolla hallituksilla ei ole enempää valtaa kuin mitä ne käyttävät meren pohjan tai ulkoisten planeettojen suhteen. Kyberavaruudessa muinaisen ajan fyysisen väkivallan uhkat, jotka ovat olleet politiikan alfa ja omega, katoavat. Kyberavaruudessa sekä vaatimattomat että voimakkaat kohtaavat tasavertaisesti. Kyberavaruus on lopullinen offshore-oikeusalue – talous ilman veroja. Bermuda taivaalla timanttien kera.

Kun tämä kaikkien ylin veroparatiisi on täysin auki liiketoiminnalle, kaikki varat ovat pohjimmiltaan omistajiensa harkinnan mukaan offshore-varoja. Tällä on laaja-alaisia seurauksia. Valtio on kasvanut tottumaan siihen, että se kohtelee veronmaksajiaan kuin maanviljelijä lehmistönsä, pitäen ne laitumella lypsettäväksi. Pian lehmillä on siivet.

### The Revenge of Nations

Kuin raivostunut maanviljelijä valtio ryhtyy epätoivoisiin keinoihin aluksi sitoidakseen ja rajoittaakseen pakenemassa olevaa laumaansa. Se käyttää salaisia ja jopa väkivaltaisia keinoja rajoittaakseen pääsyn vapauttaviin teknologioihin. Tällaiset keinoasetelmat toimivat vain väliaikaisesti, ellei lainkaan. 1900-luvun kansallisvaltio, kaikine vaatimusineen, nälkiintyy, kun sen verotulot vähenevät.

Kun valtio huomaa, ettei se kykene kattamaan yhteiskunnallisia menojaan verotulojen avulla, se turvautuu muihin, vielä epätoivoisempiin keinoihin. Näihin kuuluu muun muassa rahan painaminen. Hallitukset ovat tottuneet nauttimaan monopolia valuutasta, jota ne voivat mielivaltaisesti devalvoida. Tämä mielivaltainen inflaatio on ollut keskeinen piirre kaikkien 1900-luvun valtioiden rahapolitiikassa. Jopa paras sotien jälkeinen kansallinen valuutta, saksalainen markka, menetti 71 prosenttia arvostaan 1. tammikuuta 1949–kuun loppuun 1995, ja samana ajanjaksona Yhdysvaltain dollari menetti 84 prosenttia arvostaan.[^9] Tämä inflaatio vaikutti samalla tavalla kuin vero kaikille, jotka pitävät kyseistä valuuttaa. Kuten myöhemmin tarkastelemme, inflaatio verovaihtoehtona torjutaan suurelta osin kyberrahan yleistymisen myötä. Uudet teknologiat mahdollistavat varallisuuden haltijoille sen, että he voivat ohittaa kansalliset monopolit, jotka ovat antaneet ja säännelleet rahaa modernin ajan aikana.

Juuri se, että suvereniteetin vaatimukset edellyttävät kaikkien tietyn lainkäyttöalueen sisäisten rahansiirtojen olevan kansallisessa valuutassa, luo sen haavoittuvuuden, että keskuspankkien virheet ja spekulanttien hyökkäykset voivat laukaista deflaatiokrisiisejä toisensa jälkeen. Informaatioaikakaudella yksilöt pystyvät käyttämään kybervaluuttoja ja näin julistamaan rahallisen itsenäisyytensä. Kun yksilöt voivat toteuttaa omia rahapolitiikkojaan World Wide Webin kautta, ei ole enää niin tärkeää – tai ei ollenkaan – että valtio jatkaa teollisaikaan kuuluvien rahatehtaiden hallintaa. Niiden merkitys maailman varallisuuden hallinnassa ylitetään matemaattisilla algoritmeilla, joilla ei ole fyysistä olemassaoloa. Uudella vuosituhannella yksityismarkkinoiden hallitsema kyberraha syrjäyttää hallitusten liikkeeseen laskeman fiat-rahan. Vain köyhät jäävät inflaation ja sitä seuraavien deflaatiokriisien uhreiksi, jotka ovat seurausta siitä keinotekoisesta vipuvaikutuksesta, jonka fiat-raha tuo talouteen.

Kun hallituksilla ei ole perinteistä mahdollisuutta verottaa ja inflaatoida, jopa perinteisesti sivilisoituneissa maissa, ne muuttuvat ilkivaltaisemmiksi. Tuloverojen keräämisen vaikeutuessa vanhemmat ja mielivaltaisemmat keinoasetelmat nousevat jälleen esiin. Lopullinen muoto pidätysverosta – de facto tai jopa avoimesta panttivankituksesta – otetaan käyttöön hallitusten taholta, jotka ovat epätoivoisia estääkseen varallisuuden pakenemisen niiden ulkopuolelle. Onnettomat yksilöt joutuvat yksittäistettyinä ja lunastuskorvauksena pidetyiksi lähes keskiaikaisella tavalla. Yritykset, jotka tarjoavat palveluita, jotka helpottavat yksilöiden itsenäisyyden toteuttamista, joutuvat tunkeutumisen, sabotaasin ja häiriöiden kohteeksi. Mielivaltaiset omaisuuden menetykset, jotka ovat jo nykyisin yleisiä Yhdysvalloissa – siellä niitä tapahtuu viisi tuhatta kertaa viikossa – lisääntyvät entisestään. Hallitukset rikkovat ihmisoikeuksia, sensuroivat tiedon vapaata virtausta, sabotoivat hyödyllisiä teknologioita ja vielä pahempaa. Sillä samoin kuin myöhäinen Neuvostoliitto pyrki turhaan tukahduttamaan henkilökohtaisten tietokoneiden ja Xerox-koneiden saatavuutta, länsimaiden hallitukset pyrkivät tukahduttamaan kybertaloutta totalitaarisilla keinoilla.

## RETURN OF THE LUDDITES

Tällaiset keinot saattavat osoittautua suosituiksi joidenkin väestöryhmien keskuudessa. Hyvät uutiset yksilöllisestä vapautumisesta ja itsenäisyydestä näyttävät monille, jotka eivät kuulu kognitiivisen eliitin joukkoon, pahilta uutisilta. Suurin vastustus tulee todennäköisesti keskitasoisten lahjakkuuksien keskuudessa nykyisissä rikkaissa maissa. He saattavat erityisesti alkaa kokea, että informaatioteknologia uhkaa heidän elämäntapaansa. Järjestettyä pakkokeinoa hyödyntävät, mukaan lukien miljoonat, joita hallitukset jakavat uudelleen, saattavat tuntea vastenmielisyyttä Sovereign Individuals -konseptin tuoman uuden vapauden vuoksi. Heidän tyytymättömyytensä havainnollistaa totuutta, että "missä seisot, määrittelee missä istut."

> Joskus mietin, kuinka voisin kokea niin syvää kurjuutta sellaisten miesten kohtalosta, joita en tuntenut, pelatessani peliä toista vieraiden joukkojen kanssa pallokentällä sadojen kilometrien päässä. Vastaus on yksinkertainen. Rakastin joukkuvojani. Vaikka se oli riskialtista, välittäminen oli sen arvoista. Urheilu sytytti verenkiertoni, innosti minua, sai sydämeni jyskyttämään. Pidin siitä, että minulla oli jotain panoksena. Elämä oli elävämpää kilpailun aikana. – Craig Lambert

Olisi kuitenkin harhaanjohtavaa liittää kaikkia tulevan siirtymäkriisin synnyttämiä huonoja tunteita ainoastaan ilmiselvään haluun elää toisen kustannuksella. Mukana on paljon muutakin. Ihmiskunnan luonne viittaa siihen, että tulevaan Luddite-reaktioon liittyy väistämättä erehtyneitä moraalisia ulottuvuuksia. Ajattele sitä niin, että kampaamaton halu on varustettu moraalisella peruukilla. Tarkastelemme siirtymäkriisin moraalisia ja moraalilain mukaisia ulottuvuuksia. Tietoisesti itsekkäästi ahneella toiminnalla on paljon vähemmän voimaa motivoida kuin itseoikeassa raivossa. Vaikka 1900-luvun kansalaismyytteihin sitoutuminen on nopeasti hälvenemässä, niitä ei voi täysin hylätä, sillä niihin liittyy edelleen aitoja uskovia. Jokainen, joka kasvoi 1900-luvulla, on kasvatettu noudattamaan 1900-luvun kansalaisen velvollisuuksia ja sitoumuksia. Teollisen yhteiskunnan jääneet moraaliset imperatiivit stimuloivat ainakin joitakin neo-ludditehyökkäyksiä informaatioteknologiaa vastaan.

Tässä mielessä tuleva väkivalta on ainakin osittain ilmentymä siitä, mitä kutsumme "moraaliseksi anakronismiksi", eli siitä, että yhden talouselämän vaiheen moraalisia sääntöjä sovelletaan toisen olosuhteisiin. Jokainen yhteiskunnan vaihe tarvitsee omat moraaliset sääntönsä auttaakseen yksilöitä välttämään juuri sitä elämäntapaa koskevia kannustuksen ansalankoja, joita he kohtaavat. Aivan kuten maatalousyhteisö ei voisi elää vaeltavan eskimon moraalisten sääntöjen mukaan, ei tietoyhteiskunta voi täyttää niitä moraalisia vaatimuksia, jotka syntyivät auttamaan 1900‑luvun sotilaallisesti kilpailukykyisen teollisuusvaltion menestystä. Selitämme miksi.

Seuraavien vuosien aikana moraalinen anakronismi tulee ilmenemään lännen ydinkansojen keskuudessa samalla tavoin kuin sitä on viimeisten viiden vuosisadan aikana havaittu reuna-alueilla. Länsimaiden siirtolaiset ja sotaretket herättivät tällaisia kriisejä, kun ne kohtasivat alkuperäiskansoja, jotka elivät metsästys‑ja keräilyyhteisöinä, samoin kuin kansoja, joiden yhteiskuntajärjestelmät olivat yhä pohjimmiltaan maatalouteen perustuvia. Uusien teknologioiden tuominen anakronistisiin ympäristöihin aiheutti sekavuutta ja moraalikriisejä. Kristillisten lähetyssaarnaajien menestys muuntaa miljoonia alkuperäiskansoja voidaan suurelta osin katsoa johtuvan paikallisista kriiseistä, joita ulkopuolelta äkillisesti tuodut uudet valtasuhteet laittoivat liikkeelle. Tällaiset kohtaamiset toistuivat yhä uudelleen 1500-luvulta aina 1900‑luvun alkuun saakka. Odotamme vastaavia yhteenottoja uuden vuosituhannen alussa, kun tietoyhteiskunnat syrjäyttävät teollisia perinteitä noudattavat yhteiskunnat.

### Kaipuu pakkokeinoihin

Itsenäisen yksilön nousua ei tulekaan kohdata täydellisenä lupaukseena uudesta historiallisen merkittävästä vaiheesta, edes niiden keskuudessa, jotka siitä eniten hyötyvät. Kaikilla tulee olemaan epäilyksiä, ja monet tulevat halveksimaan niitä innovaatioita, jotka heikentävät alueellisesti organisoitua kansallisvaltiojärjestelmää. Ihmistieteen perusolemuksena on, että mitä radikaalimpaa minkä tahansalaista muutosta pidetään, sitä lähes aina katsotaan olevan dramaattinen käänne kohti huonompaa. Viisisataa vuotta sitten burgundin herttuan ympärillä kerääntyneet hoviapulaiset olisivat sanoneet, että feodaalista järjestelmää murentavat uudet innovaatiot olivat pahoja. He uskoivat maailman nopeasti horjuvan alamäkeen juuri sillä hetkellä, kun myöhemmät historian kirjoittajat näkivät renessanssissa ihmispotentiaalin räjähdyksen. Samoin se, mitä jonain päivänä saatetaan nähdä uutena renessanssina seuraavan vuosituhannen näkökulmasta, tulee näyttämään pelottavalta väsähtäneille 1900‑luvun silmille.

On hyvin todennäköistä, että jotkut uusista tavoista loukkaantuvat ja monet niistä, joita ne haittaavat, reagoivat epämiellyttävästi. Heidän kaipunsa pakkokeinoihin voi todennäköisesti kääntyä väkivaltaiseksi. Kohtaamiset näiden uusien "Luddiittien" kanssa tekevät siirtymästä radikaaleihin uusiin sosiaalisiin järjestelmiin ainakin osittain huonoja uutisia kaikille. Valmistaudu väistymään. Muutoksen vauhti ylittää monien nykyisten sukupolvien moraalisen ja taloudellisen sopeutumiskyvyn, joten voit odottaa näkeväsi kiihkeää ja raivoisaa vastustusta tietoyhteiskuntaympäristön vallankumoukselle, huolimatta sen suuresta lupauksesta vapauttaa tulevaisuus.

Sinun on ymmärrettävä ja varauduttava tällaiseen epämiellyttävyyteen. Edessä on siirtymäkriisi. Deflatoriset koettelemukset, kuten Aasian kontagio, joka pyyhkäisi itäisestä ääripäästä Venäjälle ja muihin kehittyviin talouksiin vuosina 1997 ja 1998, puhkeavat satunnaisesti, sillä teolliselta aikakaudelta peräisin olevat kansalliset ja kansainväliset instituutiot osoittautuvat riittämättömiksi uuden, hajautuneen ja yli‑kansallisen talouden haasteisiin. Uudet informaatioteknologiat ja viestintätekniikat ovat modernia valtiota alakuloisempia kuin mikään poliittinen uhka sen hallitsevuudelle sen jälkeen, kun Columbus purjehti. Tämä on tärkeää, sillä niitä, jotka ovat vallassa, ei ole harvoin nähty reagoivan rauhallisesti kehitykseen, joka uhkaa heidän auktoriteettiaan. Näin ei todennäköisesti tapahdu nyt.

Uuden ja vanhan välinen yhteenotto muokkaa uuden vuosituhannen alkuvuosia. Odotamme sen olevan aikaa suurta vaarallisuutta ja suuria palkkioita, sekä aikoja, jolloin sivistys vähenee merkittävästi tietyillä alueilla, mutta toisilla se saavuttaa ennennäkemättömän mittakaavan. Yhä itsenäisemmät yksilöt ja konkurssiin ajautuneet, epätoivoiset hallitukset kohtaavat toisensa uuden jakolinjan yli. Odotamme näkevänne radikaalin uudelleenjärjestelyn suvereniteetin luonteessa ja politiikan lähes kuoleman ennen kuin siirtymä päättyy – sen sijaan, että valtio hallitsisi ja kontrolloisisi resursseja, näette lähes kaikkien hallitusten nykyisten palveluiden yksityistämistä. Tässä kirjassa käsiteltävien väistämättömien syiden vuoksi informaatioteknologia tuhoaa valtion kyvyn periä palveluistaan enemmän kuin mitä ne ovat maksaville ihmisilleen arvoltaan.

> Governments will have to deal with what sovereignty means. -- Robert Martin

### Suvereniteetti markkinoiden kautta

Siihen määrään, mitä useimmat eivät olisi edes kymmenen vuotta sitten osanneet kuvitella, yksilöt saavuttavat yhä enemmän itsenäisyyttä alueellisia kansallisvaltioita kohtaan markkinamekanismien avulla. Kaikki kansallisvaltiot ovat uhattuna konkurssi ja niiden auktoriteetin nopea rappeutuminen. Niin mahtavia kuin ne ovatkin, niiden säilyttämällä voimalla on kyky tuhoutua, ei käskyttää. Niiden mannertenväliset ohjustensa ja lentotukialustensa esineellisyys on jo nähtävissä – ne ovat yhtä vaikuttavia ja hyödyttömiä kuin feodaalisen ajan viimeinen sothevonen.

Informaatioteknologia mahdollistaa markkinoiden dramaattisen laajenemisen muuttamalla varallisuuden luomisen ja suojaamisen tapoja. Tämä on todellakin vallankumouksellista – se lupaa tekeytyä teollisyhteiskunnalle vieläkin mullistavammaksi kuin ruudin käyttöönotto oli feodaalisen maanviljelyn kannalta. Vuoden 2000 muutos merkitsee suvereniteetin kaupallistumista ja politiikan kuolemaa – aivan kuten aseiden käytön myötä valanperusteinen feodalismi päättyi. Kansalaisuus katoaa kuten ritarillisuus.

Uskomme, että yksilöllisen taloudellisen suvereniteetin aikakausi on tulossa. Aivan kuten aiemmin kansallistetut terästehtaat, puhelinyritykset, kaivosyhtiöt ja rautatiet on nyt nopeasti yksityistetty ympäri maailman, pian näet yksityistämisen viimeisen muodon – yksilön laajamittaisen denationalisoinnin. Uuden vuosituhannen suvereeni yksilö ei enää ole valtion omaisuutta tai de facto näky valtiovarannon taseella. Vuoden 2000 jälkeen denationalisoiduista kansalaisista tulee loppujen lopuksi asiakkaita.

### BANDWIDTH TRUMPS BORDERS

Suvereniteetin kaupallistuminen tekee kansallisvaltioiden kansalaisuuden ehdot yhtä vanhentuneiksi kuin ritarilaulujen valat tuntuivat feodaalijärjestelmän romahtamisen jälkeen. Sen sijaan, että kansalaiset nähdään voimakkaan valtion veronalaisina, 2000-luvun suvereenit yksilöt ovat hallitusten asiakkaita, jotka toimivat ”uudesta loogisesta tilasta”. He neuvottelevat itselleen tarvitsemansa vähimmän hallinnon ja maksavat siitä sopimuksen mukaan. Informaation aikakauden hallitukset tullaan organisoimaan aivan eri periaatteiden mukaisesti kuin mitä maailmassa on viime vuosisatoina odotettu. Joitakin lainkäyttöalueita ja suvereniteettipalveluita muodostuu ”assorttisen sovittamisen” kautta; tällöin yhteenkuuluvuustekijät – myös kaupalliset – ovat perusta, jonka varassa virtuaaliset lainkäyttöalueet ansaitsevat lojaalisuutta. Harvinaisissa tapauksissa uudet suvereniteetit voivat olla peräisin keskiaikaisista järjestöistä, kuten Sovereign Military Hospitaller Order of St. John of Jerusalem, of Rhodes and of Malta, joka tunnetaan paremmin nimellä Knights of Malta. Tämä järjestö on varakkaiden katolilaisten yhteenkuuluvaryhmä, jolla on 10 000 nykyjäsentä ja vuosittaiset tulot useista miljardeista. Knights of Malta myöntää omat passinsa, leimat ja rahansa sekä ylläpitää täysimittaisia diplomaattisia suhteita seitsemänkymmeneen maahan. Kirjoitushetkellä se neuvottelee Maltan tasavallan kanssa saadakseen Fort St. Angelon uudelleen hallintaansa. Linnan haltuunotto antaisi ritareille sen puuttuvan alueellisuuden ainesosan, joka mahdollistaisi sen tunnustamisen suvereniteetiksi. Knights of Malta voisi jälleen muodostua suvereeniksi mikrovaltioksi, välittömästi laillistettuna pitkän historian kautta.

Vielä toinen, hyvin erilainen malli postmodernille suvereniteetille, joka pohjautuu assorttiseen sovittamiseen, on Iridium-satelliittipuhelinverkko. Ensisilmäyksellä saattaa tuntua oudolta käsitellä matkapuhelinpalvelua eräänlaisena suvereniteettina, mutta Iridium on jo saanut kansainvälisten viranomaisten tunnustuksen virtuaalisena suvereniteettina. Kuten tiedät, Iridium on globaali matkapuhelinpalvelu, joka mahdollistaa tilaajiensa vastaanottaa puheluita yhdeltä numerolta, missä tahansa he ovatkin planeetalla – Featherstonista, Uudesta-Seelannista Bolivian Chacoon. Jotta puheluita voitaisiin ohjata Iridium-tilaajille kaikkialla, ottaen huomioon globaalin telekommunikaation arkkitehtuuri, kansainvälisten telealan viranomaisten on täytynyt sopia siitä, että Iridium tunnustetaan virtuaaliseksi maaksi omalla maan koodillaan: 8816. Loogisesti on pieni askel siirtyä virtuaalisesta maasta, joka koostuu satelliittipuhelintilaajista, kohti suvereniteettia, joka palvelee yhteensopivampia virtuaaliyhteisöjä World Wide Webissä, ylittäen kansainväliset rajat. Kaistanleveys – eli viestintävälineen kantokapasiteetti – on kasvanut nopeammin kuin laskentateho transistorien keksimisen jälkeen, ja jos tämä kehityssuunta jatkuu, kuten uskomme todennäköiseksi, on vain muutaman vuoden, pian vuosituhannen vaihdoksen jälkeen, kysymys siitä, että kaistanleveys on riittävän suuri mahdollistamaan teknisesti ”metaversumin” eli science fiction -kirjailija Neal Stephensonin kuvitteleman vaihtoehtoisen kyberavaruuden maailman. Stephensonin ”metaverse” on tiheä virtuaaliyhteisö, jolla on omat lakinsa. Uskomme, että väistämättömästi kybertalouden rikastuessa sen osallistujat hakevat ja saavuttavat poikkeuksen kansallisvaltioiden anakronistisista laeista. Uudet kyberyhteisöt tulevat olemaan vähintään yhtä varakkaita ja kyvykkäitä edistämään etujaan kuin Sovereign Military Hospitaller Order of St. John of Jerusalem, of Rhodes and of Malta – he ovat itse asiassa entistä paremmin kyvykkäitä itsensä puolustamiseen laajojen viestintä- ja tietovaltakilpailukyvyn ansiosta. Tarkastelemme vielä muitakin malleja hajanaisesta suvereniteetista, joissa pienet ryhmät voivat tehokkaasti vuokrata heikkojen kansallisvaltioiden suvereniteetin ja toimia omien taloudellisten turvapaikkojensa merkeissä, aivan kuten nykyään vapaakauppa- ja vapaakauppavyöhykkeet saavat luvan toimia.

Uuden moraalisen sanaston tulee nousta kuvaamaan suvereenien yksilöiden välisiä suhteita ja sitä, mitä hallituksesta jää jäljelle. Epäilemme, että kun näiden uusien suhteiden ehdot tarkentuvat, ne loukkaavat monia, jotka kasvoivat 1900-luvun kansallisvaltioiden kansalaisina. Kansojen loppu ja yksilön denationalisointi tasoittavat monia lämpimästi pidettyjä käsityksiä, kuten ”tasa-arvoinen suojelu lain edessä”, jotka edellyttävät vallan suhteita, jotka ovat pian vanhentuneita. Kun virtuaaliyhteisöt saavuttavat eheytensä, ne vaativat, että niiden jäseniä pidetään vastuullisina omien lakien mukaisesti, eivätkä entisten kansallisvaltioiden lakien mukaan, joissa he sattuvat asuttamaan. Useat oikeusjärjestelmät tulevat jälleen rinnakkain elämään samalla maantieteellisellä alueella, aivan kuten antiikin ja keskiaikojen aikoina.

Aivan kuten yritykset säilyttää haarniskassa olevien ritarien valta olivat tuomittuja epäonnistumaan ruudin aseiden edessä, niin modernit kansallisuus- ja kansalaisuuskäsitykset ovat tuomittuja lyhentymään mikroteknologian toimesta. Todellakin, ne tulevat lopulta muuttumaan koomikseiksi, samalla tavalla kuin 1400-luvun feodaalijärjestelmän pyhät periaatteet kohtasivat pilkan 1500-luvulla. 1900-luvun rakastetut kansalaisuuskäsitykset tulevat uusille sukupolville näyttämään koomisilta anakronismeilta vuoden 2000 muutoksen jälkeen. 2000-luvun Don Quixote ei enää ole ritarinomistautunut, joka kamppailee feodalijärjestelmän loistojen elvyttämiseksi, vaan byrokraatti ruskeassa puvussa, veronkerääjä, joka kaipaa tarkastettavaa kansalaista.

## REVIVING LAWS OF THE MARCH

Harvoin ajattelemme hallituksia kilpailevina toimijoina, paitsi hyvin laajassa merkityksessä, ja siksi nykyaikainen käsitys suvereniteetin laajuudesta ja mahdollisuuksista on nykivästynyt. Aiemmin, kun vallankumouksen tasapaino teki ryhmien on vaikeampaa saavuttaa vakaa pakottamisen monopoli, valta jakautui usein, lainkäyttöalueet olivat päällekkäisiä ja erilaiset toimijat harjoittivat yhtä tai useampaa suvereniteetin ominaisuutta. Ei harvoin nimellinen ylhällikkö todellisuudessa omistanut vain hyvin vähän valtaa. Vallanvaltioita heikommat hallitukset kohtaavat nyt jatkuvaa kilpailua kyvyssään määrätä paikallisen alueen pakottamisen monopolia. Tämä kilpailu on synnyttänyt sopeutumismekanismeja väkivallan hallintaan ja lojaalisuuden houkuttelemiseen, jotka tulevat pian olemaan uusia.

Kun herrasväen ja kuninkaiden ulottuvuus oli heikko ja yhden tai useamman ryhmän vaatimukset osasiivat mennä päällekkäin rajalla, tapahtui usein, ettei kumpikaan voinut ratkaisevasti dominoida toisiaan. Keskiajalla oli lukuisia rajaseutuja tai ”march” -alueita, joissa suvereniteetit sulautuivat yhteen. Nämä väkivaltaiset rajaseudut jatkuivat vuosikymmeniä tai jopa vuosisatoja Euroopan raja-alueilla; esimerkiksi Irlannissa kelttiläisen ja englantilaisen hallinnan alueet kohtasivat, samoin kuin Walesin ja Englannin, Skotlannin ja Englannin, Italian ja Ranskan, Ranskan ja Espanjan, Saksan ja Keski-Euroopan slaavilaisten sekä Espanjan kristillisten valtakuntien ja Granadan islamilaisen valtakunnan välillä. Tällaiset rajaseudut kehittivät omaleimaisia institutionaalisia ja oikeudellisia malleja, joita on todennäköisesti nähtävissä jälleen seuraavalla vuosituhannella. Kilpailuasetelman vuoksi kahden viranomaisen kohdalla rajaseudun asukkaat maksoivat harvoin veroja. Lisäksi heillä oli yleensä mahdollisuus valita, kenen lakeja he noudattaisivat – valinta, joka toteutui sellaisten oikeudellisten käsitteiden kuten “avowal” ja “distraint” avulla, jotka ovat nykypäivänä lähes kadonneet. Odotamme, että tällaiset käsitteet tulevat olemaan merkittävä osa informaatioteknologian aikakauden lainsäädäntöä.

Just as attempts to preserve the power of knights in armor were doomed to fail in the face of gunpowder weapons, so the modern notions of nationalism and citizenship are destined to be short-circuited by microtechnology. Indeed, they will eventually become comic in much the way that the sacred principles of fifteenth-century feudalism fell to ridicule in the sixteenth century. The cherished civic notions of the twentieth century will be comic anachronisms to new generations after the transformation of the year 2000. The Don Quixote of the twenty-first century will not be a knight-errant struggling to revive the glories of feudalism but a bureaucrat in a brown suit, a tax collector yearning for a citizen to audit.

A new moral vocabulary will be required to describe the relations of Sovereign Individuals with one another and what remains of government. We suspect that as the terms of these new relations come into focus, they will offend many people who came of age as “citizens” of twentieth‐century nationstates. The end of nations and the “denationalization of the individual” will deflate some warmly held notions, such as “equal protection under the law” that presuppose power relations that are soon to be obsolete. As virtual communities gain coherence, they will insist that their members be held accountable according to their own laws, rather than those of the former nation-states in which they happen to reside. Multiple systems of law will again coexist over the same geographic area, as they did in ancient and medieval times.

Just as attempts to preserve the power of knights in armor were doomed to fail in the face of gunpowder weapons, so the modern notions of nationalism and citizenship are destined to be short-circuited by microtechnology. Indeed, they will eventually become comic in much the way that the sacred principles of fifteenth-century feudalism fell to ridicule in the sixteenth century. The cherished civic notions of the twentieth century will be comic anachronisms to new generations after the transformation of the year 2000. The Don Quixote of the twenty-first century will not be a knight-errant struggling to revive the glories of feudalism but a bureaucrat in a brown suit, a tax collector yearning for a citizen to audit.

#### Aikajanat kohdilleen

Näiden kahden vastakkaisen rahateorian yhdistämiseksi ja niiden peruslähtökohtien ymmärtämiseksi on tärkeää tarkastella niiden eroja ja erityisesti sitä, missä määrin ne pitävät paikkansa ja milloin ne ovat virheellisiä. Tähän tarkoitukseen palatkaamme *Kansojen varallisuuteen*, jossa Adam Smith kuvaa teoksessaan vaihtokaupan ongelmaa ja miksi taloudessa luonnollisesti ilmaantuu myyntikelpoinen hyödykeraha ratkaisemaan tätä ongelmaa:

"Mutta kun työnjako alkoi kehittyä, vaihtamisen mahdollisuus oli usein huomattavan rajallista ja hankalaa. Oletetaan, että yhdellä henkilöllä on tiettyä hyödykettä enemmän kuin toisella, ja toinen olisi halukas luopumaan osasta ylijäämäänsä, mutta jos toisella ei ole mitään tarjottavaa vastineeksi, vaihtokauppaa ei voi tapahtua heidän välillään. Lihakauppiaalla on enemmän lihaa kuin mitä hän itse kykenee kuluttamaan, ja samalla oluenpanija ja leipuri olisivat valmiita ostamaan osan siitä vastineeksi omien ammattinsa tuotteista, mutta sillä hetkellä heillä ei ole mitään annettavaa vastineeksi, koska heillä on jo kaikki leipä ja olut käytettävissään. Tällaisessa tilanteessa kauppaa ei voi tehdä. Lihakauppias ei voi myydä sitä, mitä hänellä on, eikä toiset voi olla hänen asiakkaitaan. Tässä tilanteessa jokainen järkevä ihminen on pyrkinyt järjestämään asiansa siten, että hänellä on aina jonkin verran hyödykettä, jonka vastineeksi muutkin olisivat valmiita yhteistyöhön. On todennäköistä, että monia hyödykkeitä on historiallisesti pidetty tällaisina vaihdon perusteina. Aikaisemmin yhteisöissä on sanottu, että karja toimii yleisenä kaupankäynnin välineenä, ja vaikka sen käyttö olisi aluksi ollut epäkäytännöllistä, sen arvo perustui siihen, kuinka monta naudanlihaa sen vaihtamiseen käytettiin. Homeros kertoo, että Diomedeen haarniska maksoi vain yhdeksän härkää, mutta Glaucusuksen haarniska maksoi sata härkää. Suolaa on usein käytetty kaupankäynnin ja vaihdon välineenä Abyssiniassa; tietyillä Intian rannikoilla on käytetty simpukoita, Newfoundlandissa kuivattua Turskaa, Virginiassa tupakkaa, Länsi-Intian siirtokunnissa sokeria, joillakin alueilla vuodat ja nahkaa, ja nykyään Skotlannissa on jopa kylä, jossa käytetään leipomon tai pubin maksuvälineenä nauloja. Kuitenkin lopulta kaikkialla ihmiset ovat päätyneet suosimaan metalleja tähän vaihdon välineenä, koska ne eivät ainoastaan säily luonnollisesti hyvin, vaan niitä on myös helppo jakaa mihin tahansa pienempiin osiin ja yhdistää uudelleen – ominaisuus, jota mikään muu hyödyke ei omaa, ja joka on keskeisin vaatimuksena hyväksi kaupankäynnin ja kierrätyksen välineeksi."

Smithin noin 250 vuotta sitten esittämä kokonaiskuvaus vaikuttaa kestäneen hyvin ajan hammasta, ja hän oli pääosin oikeassa. Ensinnäkin hän totesi, että hyödykeraha syntyy luonnostaan, koska se ratkaisee halujen yhteensovittamisen ongelman työjaon ja erikoistumisen maailmassa. Toiseksi hän perusteli, miksi juuri jalometallit ovat osoittautuneet historiallisesti parhaiksi hyödykerahoiksi ainutlaatuisten ominaisuuksiensa vuoksi. Kyse ei ollut sattumasta, vaan siitä, että ihmiset ympäri maailmaa ovat päätyneet hyväksymään hopean ja kullan ihanteellisimpina rahan muotoina.

Diablo II -tietokonepelissä Stone of Jordan -sormusten luonnollinen muuntuminen rahaksi on tarjonnut havainnoitavan koeasetelman Smithin rahan syntyä koskevien näkemysten testaamiseksi. Tämä ja muut vastaavat asetelmat ovat todiste siitä, että rahallistumisprosessi on voitu havaita käytännössä sen sijaan, että se olisi jäänyt pelkästään teorian tasolle.

#### Luottorahateorian puutteet

Luottorahateorian kannattajilla on taipumus laajentaa käsityksiään liian pitkälle, jättäen usein huomiotta hyödykerahan merkityksen, ja he esittävät ylioptimistisen kuvan yhteiskunnan kyvystä ylläpitää joustavaa, luottopohjaista sosiaalista tilikirjaa suurissa mittakaavoissa ja pitkin aikaa. Ensimmäinen ongelma tällaisessa järjestelmässä liittyy kaupankäyntiin tilanteissa, joissa osa tuottajista tai kauppiaista on erittäin erikoistuneita. Vaikka lihakauppiaat, oluenpanijat ja leipurit pystyvät järjestämään vaihtoa esimerkiksi siten, että yksi kilo naudanlihaa vastaa kolmea tuoppia olutta, joka vastaa viittä leipää, entä kirurgien kaltaiset erikoistuneet palveluntarjoajat? Kirurgi tarvitsee leipää, joten voisiko hän tarjota leipurille jotain, jolla hän myöhemmin korvaa saamansa tuen? Kuinka monen leivän arvoinen leikkaus on, ja mistä leikkauksessa oikeastaan on kyse? Leikkaus- ja muut erikoislääkäripalvelut ovat erittäin arvokkaita, kapeiden markkinoiden palveluita, joita ei voida helposti vaihtaa tai joiden yhteiskunnallinen tarve on rajallinen. On selvää, että kaupankäynnin tehostamiseksi tarvitaan sarja standardoituja yksiköitä, ja historiallisesti tällaiset yksiköt ovat usein olleet sidoksissa tiettyyn luonnossa esiintyvään hyödykkeeseen, kuten tiettyyn määrään hopeaa tai annokseen viljaa. Muussa tapauksessa kansalaiset joutuisivat turvautumaan abstrakteihin vaihtokauppoihin, joissa käydään kauppaa erilaisilla luottovaatimuksilla ilman vakiintunutta laskentayksikköä. Historiallisesti, vaikka luottoa onkin käytetty kaupankäynnin välineenä, kyseinen luottoväline ilmaistaan usein myyntikelpoisina hyödykeyksiköinä, jotka ovat nousseet vaihdon välineiksi ominaisuuksiensa vuoksi.

Luottorahateoriaa voidaan kritisoida myös peliteoreettisilla vastaväitteillä. Mitä tapahtuu, kun joku poistuu yhteisöstä ja liittyy toiseen? Todennäköisesti ei ole koskaan ollut täysin erillisiä yhteisöjä, sillä maantieteellisesti lähellä olevat ihmisyhteisöt ovat olleet vähemmänkin satunnaisessa vuorovaikutuksessa toisensa kanssa jo ihmiskunnan alkuajoista lähtien. Tämä tarkoittaa, että varallisuuden siirtämiseksi yhteisöstä toiseen täytyy olla olemassa jonkinlaisessa fyysisemmässä tai yleismaailmallisemmassa muodossa. Luotto toimii hyvin yhteisön sisäisessä arkisessa kaupankäynnissä, mutta jos joku haluaa matkustaa kauemmas, hän tarvitsee varallisuutta perustavanlaatuisemmassa muodossa, jonka uusi yhteisö tunnustaisi lailliseksi. Luonnolliset rahat, kuten simpukankuoret, vilja ja hopea, ovat perinteisesti toimineet sellaisina välineinä.

Kolmas ongelma luottorahateoriassa on se, että se, mikä toimii hyvin pienissä yhteisöissä, ei välttämättä toimi suuressa mittakaavassa. Pieniin, luottamukseen perustuviin sosiaalisiin luottojärjestelmiin, jotka pohjautuvat henkilökohtaiseen tuntemukseen ja luottamukseen, ei voida soveltaa samalla tavalla kansallisvaltioihin, joissa hallitaan miljoonia pääosin tuntemattomia ihmisiä. Luottamukseen voidaan tukeutua vain silloin, kun tunnet toisen ihmisen ja luotat hänen sanaansa ja tekoihinsa. Kunnia on tärkeä käsite inhimillisessä vuorovaikutuksessa, mutta se ei sovi persoonattomaan byrokratiaan.

#### Rahan yhtenäisteoria

Hyödykeraha- ja luottorahateoriat näyttävät ensisijaisesti olevan ristiriitaisia, minkä vuoksi täyden teorian muodostamiseksi on tarpeen löytää niiden yhteinen logiikka eli perusta. Molemmat teoriat tarjoavat tapoja ylläpitää tilikirjaa ja laatia ”oikeanlaisia” kirjausmerkintöjä, mutta ne eroavat siinä, kuka tai mikä ylläpitää tätä tilikirjaa.

Luottorahateoriassa ihmiset ylläpitävät tilikirjojaan hyödyntämällä luottamukseen perustuvia menetelmiä. Pienissä yhteisöissä tämä voidaan usein tehdä epävirallisesti, ja tilikirjat voivat perustua sukulaisuuteen, ystävyyteen ja kunniaan. Suuremmissa yhteisöissä, joissa mukana on toisilleen vieraita ihmisiä, luottopohjainen kirjanpito keskitetään keskusvallalle ja sen laatimille sääntöjärjestelmille. Historiallisesti luottamuspohjaiset järjestelmät ovat kärsineet erilaisista ”nollauksista” ja arvon laskusta ajan myötä.

Hyödykerahateoriassa ihmiset pyrkivät puolestaan turvautumaan mahdollisimman vähäiseen luottamukseen, jolloin he antavat luonnon, eli fyysisten luonnollisten lakien, määrätä tilikirjan ylläpidosta. Tällöin hyvin myyntikelpoiset hyödykkeet vaihdetaan suoraan, ja tilikirjan kokonaissaldo määräytyy hyödykkeiden fyysisen hallussapidon mukaan. Yksikään ihmisen määräämä auktoriteetti ei pysty muuttamaan rahan arvoa mielivaltaisten kirjausmerkintöjen avulla, vaan sen on varmistettava, että rahan arvo säilyy – mikä onnistuu parhaiten luonnollisten lakien avulla.

Näiden kahden koulukunnan yhdistelmänä syntyy niin sanottu ”tilikirjarahateoria”, joka kuvaa molempien edellä mainittujen teorioiden syvempää yhteistä logiikkaa. Joustavan sosiaalisen luoton ja kerättävien esirahojen juuret ulottuvat ihmiskunnan alkuhistoriaan. Molemmissa tapauksissa yhteisöt ylläpitävät tilikirjojaan joko keskenään tai luottavat luonnonlakeihin, jotka mahdollistavat jonkinlaisen likvidin säästämisen samalla, kun ne ratkaisevat halujen yhteensovittamisen ongelman.

#### A new moral vocabulary will be required

Uuden moraalisen sanaston tarvitsee nousta kuvaamaan suvereenien yksilöiden välisiä suhteita ja sitä, mitä hallituksesta jää jäljelle. Epäilemme, että kun näiden uusien suhteiden ehdot tarkentuvat, ne loukkaavat monia, jotka kasvoivat 1900-luvun kansallisvaltioiden kansalaisina. Kansojen loppu ja yksilön denationalisointi tasoittavat lämpimästi pidettyjä käsityksiä, kuten ”tasa-arvoinen suojelu lain edessä”, jotka edellyttävät vallan suhteita, jotka ovat pian vanhentuneita. Kun virtuaaliyhteisöt saavuttavat eheytensä, ne vaativat, että niiden jäseniä pidetään vastuullisina heidän omien lakien mukaisesti sen sijaan, että noudatettaisiin entisten kansallisvaltioiden lakeja, joissa he sattuvat asuinpaikaksi. Useat oikeusjärjestelmät tulevat jälleen rinnakkain elämään samalla maantieteellisellä alueella, aivan kuten antiikin ja keskiaikojen aikoina.

#### Luottorahateorian puutteet

Luottorahateorian kannattajilla on taipumus laajentaa käsityksiään liian pitkälle, jättäen usein huomiotta hyödykerahan merkityksen, ja he esittävät ylioptimistisen kuvan yhteiskunnan kyvystä ylläpitää joustavaa, luottopohjaista tilikirjaa suuressa mittakaavassa ja pitkin aikaa. Ensimmäinen ongelma tällaisessa järjestelmässä liittyy tilanteisiin, joissa osa tuottajista tai kauppiaista on erittäin erikoistuneita. Vaikka lihakauppiaat, oluenpanijat ja leipurit pystyvät vaihdossa järjestelemään esimerkiksi siten, että yksi kilo naudanlihaa vastaa kolmea tuoppia olutta, joka vastaa viittä leipää, entä sitten kirurgien kaltaiset erikoistuneet palveluntarjoajat? Kirurgi tarvitsee leipää, joten voisiko hän tarjota leipurille jotain, jolla ratkaistaan leipäpula myöhemmin? Kuinka monen leivän arvoinen leikkaus on – ja mitä leikkauksessa oikeastaan tarkoitetaan? Erikoislääkäripalvelut ovat erittäin arvokkaita, kapean markkinaraon palveluita, joita ei voida helposti vaihtaa tai joilla ei ole laajaa yhteiskunnallista tarvetta. On siis selvää, että kaupankäynnin sujuvuuden takaamiseksi tarvitaan standardoituja laskentayksiköitä, ja historiallisesti tällaiset yksiköt ovat usein olleet sidoksissa tiettyyn luonnolliseen hyödykkeeseen, kuten tiettyyn määrään hopeaa tai tiettyyn annokseen viljaa. Muussa tapauksessa ihmiset joutuisivat turvautumaan abstrakteihin vaihtakauppoihin, joissa käytetään erilaisia luottovaatimuksia ilman vakiintunutta laskentayksikköä. Historiallisesti, vaikka luotto onkin ollut keskeinen kaupankäynnin väline, se on yleensä ilmaistu myyntikelpoisina hyödykeyksiköinä, jotka ovat nousseet vaihdon välineiksi niiden ominaisuuksien vuoksi.

Toiseksi luottorahateoriaa voidaan kritisoida peliteoreettisilla vastaväitteillä. Mitä tapahtuu, kun joku poistuu yhteisöstä ja liittyy toiseen? Todennäköisesti ei ole koskaan ollut täysin erillisiä yhteisöjä, sillä maantieteellisesti lähellä olevat ihmisyhteisöt ovat aina olleet ainakin satunnaisesti vuorovaikutuksessa toisensa kanssa. Tämä tarkoittaa, että varallisuuden siirtämiseksi yhteisöstä toiseen täytyy olla olemassa jonkinlaisessa fyysisemmässä tai yleismaailmallisemmassa muodossa. Luotto voi toimia hyvin yhteisön sisäisessä arkisessa kaupankäynnissä, mutta jos joku haluaa matkustaa pidemmälle, hän tarvitsee varallisuutta perustavanlaatuisemmassa muodossa, jonka uusi yhteisö tunnustaisi laillisena. Luonnolliset rahat, kuten simpukankuoret, vilja ja hopea, ovat perinteisesti toimineet sellaisina välineinä.

Kolmas ongelma luottorahateoriassa on se, että se, mikä toimii hyvin pienissä yhteisöissä, ei välttämättä toimi suuressa mittakaavassa. Pienet, henkilökohtaiseen luottamukseen perustuvat sosiaaliset luottojärjestelmät eivät ole sovellettavissa samalla tavalla kansallisvaltioihin, joissa hallitaan miljoonia pääosin tuntemattomia ihmisiä. Luottamukseen voidaan nojata vain, jos tunnet toisen ihmisen ja luotat hänen sanaansa ja tekoihinsa. Kunnia on olennainen käsite inhimillisessä vuorovaikutuksessa, mutta se ei sovi persoonattomaan byrokratiaan.

#### Rahan yhtenäisteoria

Hyödykeraha- ja luottorahateoriat vaikuttavat ensi silmäyksellä ristiriitaisilta, minkä vuoksi täydellisen teorian muotoilemiseksi on tarpeen löytää niiden yhteinen logiikka tai perusta. Molemmat teoriat tarjoavat keinoja ylläpitää tilikirjaa ja tehdä ”oikeanlaisia” kirjausmerkintöjä, mutta ne eroavat siinä, kuka tai mikä ylläpitää tätä tilikirjaa.

Luottorahateoriassa ihmiset ylläpitävät tilikirjojaan hyödyntämällä luottamukseen perustuvia menetelmiä. Pienissä yhteisöissä tämä voidaan usein tehdä epävirallisesti, ja tilikirjat saattavat perustua sukulaisuuteen, ystävyyteen ja kunniaan. Suuremmissa yhteisöissä, joissa mukana on toisilleen vieraita ihmisiä, luottopohjainen kirjanpito keskitetään jollekin keskusvallalle ja sen laatimille sääntöjärjestelmille. Historiallisesti luottamuspohjaiset järjestelmät ovat kärsineet erilaisista ”nollauksista” ja niiden arvo on laskenut ajan myötä.

Hyödykerahateoriassa taas ihmiset pyrkivät vähentämään luottamukseen perustuvia oletuksia antamalla mahdollisimman paljon valtaa luonnonlakien määrätä tilikirjan yllpitämisessä. Tällöin hyvin myyntikelpoiset hyödykkeet vaihdetaan suoraan, ja tilikirjan kokonaisarvo määräytyy niiden fyysisen hallussapidon mukaan. Yksikään inhimillinen auktoriteetti ei pysty muuttamaan rahan arvoa mielivaltaisten merkintöjen kautta, vaan arvon on säilyttävä luonnollisten lakien turvin.

Näiden kahden koulukunnan yhdistelmänä syntyy niin sanottu ”tilikirjarahateoria”, joka kuvaa niiden yhteistä syvempää logiikkaa. Joustavan sosiaalisen luoton ja luonnollisten hyödykerahojen juuret ulottuvat ihmiskunnan alkuajoista, jolloin yhteisöt ylläpitävät tilikirjojaan joko keskenään tai luottavat luonnonlakeihin, jotka takaavat jonkinlaisen likvidin säästämismuodon.

#### A new moral vocabulary will be required

Uuden moraalisen sanaston on noustava kuvaamaan suvereenien yksilöiden välisiä suhteita ja sitä, mitä hallituksesta jää jäljelle. Epäilemme, että kun näiden uusien suhteiden ehdot konkretisoituvat, ne loukkaavat monia, jotka kasvoivat 1900-luvun kansallisvaltioiden kansalaisina. Kansojen loppu ja yksilön denationalisointi tasoittavat monia lämpimästi pidettyjä käsityksiä, kuten ”tasa-arvoinen suojelu lain edessä”, jotka perustuvat vallan suhteisiin, jotka ovat pian vanhentuneita. Kun virtuaaliyhteisöt saavuttavat eheytensä, ne vaativat, että niiden jäseniä pidetään vastuullisina heidän omien lakien mukaisesti – eivätkä entisten kansallisvaltioiden lakien mukaan, joissa he sattuvat asuttamaan. Useita oikeusjärjestelmiä tulee jälleen rinnakkain elämään samalla maantieteellisellä alueella, aivan kuten antiikin ja keskiaikojen aikoina.

#### Luottorahateorian puutteet

Luottorahateorian kannattajat laajentavat usein näkemyksiään liian pitkälle, jättäen huomioimatta hyödykerahan merkityksen, ja ne maalaavat ylioptimistisen kuvan siitä, kuinka hyvin yhteiskunta pystyy ylläpitämään joustavaa, luottopohjaista sosiaalista tilikirjaa suuressa mittakaavassa ja pitkillä ajanjaksoilla. Ensimmäinen ongelma liittyy tilanteisiin, joissa osa tuottajista tai kauppiaista on hyvin erikoistuneita. Vaikka lihakauppiaat, oluenpanijat ja leipurit pystyvät järjestämään vaihtoa esimerkiksi siten, että yksi kilo naudanlihaa vastaa kolmea tuoppia olutta, joka puolestaan vastaa viittä leipää, entä kirurgien kaltaiset erikoistuneet palveluntarjoajat? Kirurgi tarvitsee leipää, joten voisiko hän tarjota leipurille jotakin, jolla hän myöhemmin hoitaa tämän leipäpulan? Kuinka monen leivän arvoinen leikkaus on, ja mitä leikkauksessa oikeastaan tarkoitetaan? Erikoislääkäripalvelut ovat erittäin arvokkaita, kapean markkinaraon palveluita, joita ei voida helposti vaihtaa tai joita ei yleisesti tarvita. On siis selvää, että kaupankäynnin tehostamiseksi tarvitaan standardoituja yksiköitä, ja historiallisesti tällaiset yksiköt ovat usein olleet sidoksissa tiettyyn luonnon esiintyvään hyödykkeeseen, kuten tiettyyn määrään hopeaa tai annokseen viljaa. Muussa tapauksessa ihmiset joutuisivat turvautumaan abstrakteihin vaihtokauppoihin ja käyttäisivät erilaisia luottovaatimuksia ilman vakiintunutta laskentayksikköä. Historiallisesti, vaikka luotto onkin ollut keskeinen kaupankäynnin väline, se ilmaistaan usein myyntikelpoisina hyödykeyksiköinä, jotka ovat nousseet vaihdon välineiksi niiden ominaisuuksien vuoksi.

#### Rahan yhtenäisteoria

Hyödykeraha- ja luottorahateoriat vaikuttavat ensi silmäyksellä ristiriitaisilta, minkä vuoksi täydellisen teorian muodostamiseksi on tarpeen löytää niiden yhteinen logiikka eli perusta. Molemmat teoriat tarjoavat keinoja ylläpitää tilikirjaa ja tehdä ”oikeanlaisia” kirjausmerkintöjä, mutta ne eroavat siinä, kuka tai mikä ylläpitää tätä tilikirjaa.

Luottorahateoriassa ihmiset ylläpitävät tilikirjojaan hyödyntämällä luottamukseen perustuvia menetelmiä. Pienissä yhteisöissä tämä voidaan usein tehdä epävirallisesti, jolloin tilikirjat voivat perustua sukulaisuuteen, ystävyyteen ja kunniaan. Suuremmissa yhteisöissä, joissa mukana on toisilleen vieraita ihmisiä, tällaiset luottopohjaiset kirjanpitojärjestelmät keskitetään tietyn keskusvallan ja sen sääntöjen alle. Historiallisesti nämä järjestelmät ovat kuitenkin kokeneet niin sanottuja ”nollauksia” ja arvonalentumisia ajan myötä.

Hyödykerahateoriassa taas ihmiset pyrkivät antamaan mahdollisimman vähän tilaa luottamukselle ja jättämään luonnon – eli fyysisten luonnollisten lakien – määrätä tilikirjan ylläpitämisestä. Tällöin hyvin myyntikelpoiset hyödykkeet vaihdetaan suoraan, ja tilikirjan kokonaisarvo määräytyy niiden fyysisen hallussaolon perusteella. Yksikään inhimillinen auktoriteetti ei pysty mielivaltaisesti vähentämään rahan arvoa kirjausmerkintöjen kautta, vaan sen on varmistettava, että arvo säilyy – mikä onnistuu parhaiten luonnollisten lakien turvin.

Näin muodostuu se, mitä voidaan kutsua ”tilikirjarahateoriaksi”, joka kuvastaa molempien edellä mainittujen teorioiden syvempää yhteistä logiikkaa. Joustavan sosiaalisen luoton ja luonnollisten hyödykerahojen juuret ulottuvat hyvin kauas ihmiskunnan alkuajoista; näissä järjestelmissä yhteisöt ylläpitävät tilikirjojaan joko keskenään tai luottavat luonnonlakeihin, jotka takaavat jonkinlaisen likvidin säästämisen samalla kun ne ratkaisevat halujen yhteensovittamisen ongelman.

### REVIVING LAWS OF THE MARCH

Harvoin ajattelemme hallituksia kilpailevina toimijoina, paitsi hyvin laajassa merkityksessä, ja siksi nykyaikainen käsitys suvereniteetin laajuudesta ja mahdollisuuksista on nykivästynyt. Aiemmin, kun vallan tasapainot tilanne teki vaikeaksi ryhmien saavuttaa vakaa pakottamisen monopoli, valta oli usein hajaantunutta, lainkäyttöalueet päällekkäisiä ja erilaiset toimijat harjoittivat yhtä tai useampaa suvereniteetin ominaisuutta. Usein nimellinen ylhällikkö omisti todellisuudessa hyvin vähän valtaa. Nykyään kansallisvaltioita heikommat hallitukset kohtaavat jatkuvaa kilpailua kyvyssään määrätä paikallisen alueen pakottamisen monopolia. Tämä kilpailu on johtanut uusiin sopeutumismekanismeihin väkivallan hallinnassa ja lojaalisuuden houkuttelemisessa, jotka tulevat pian olemaan uudelleen ajankohtaisia.

Kun herrasväen ja kuninkaiden vaikutusvalta oli heikkoa ja ryhmien vaatimukset saattoivat osua rajojen kohdalle, tapahtui usein, ettei kumpikaan osapuoli voinut ratkaisevasti dominoida toisiaan. Keskiajalla oli lukuisia rajaseutuja eli ”march”-alueita, joissa suvereniteetit sulautuivat yhteen. Nämä väkivaltaiset rajaseudut kestäivät vuosikymmeniä tai jopa vuosisatoja Euroopan rajoilla – esimerkiksi Irlannissa, missä kelttiläisen ja englantilaisen hallinnan alueet kohtasivat; Walesin ja Englannin, Skotlannin ja Englannin, Italian ja Ranskan, Ranskan ja Espanjan, Saksan ja Keski-Euroopan slaavilaisten sekä Espanjan kristillisten valtakuntien ja Granadan islamilaisen valtakunnan välillä. Tällaiset rajaseudut kehittivät omanlaisensa institutionaaliset ja oikeudelliset muodot, joita on todennäköisesti nähtävissä jälleen seuraavalla vuosituhannella. Kilpailuasetelman vuoksi kahden viranomaisen hallitsemissa rajaseuduissa asukkaat maksoivat harvoin veroja. Lisäksi heillä oli yleensä mahdollisuus valita, kenen lakeja he noudattaisivat – vaihtoehto, joka toteutui oikeudellisten käsitteiden kuten ”avowal” ja ”distraint” kautta, jotka ovat nyt lähes kadonneet. Odotamme, että tällaiset käsitteet tulevat olemaan merkittävä piirre informaatiotekniikan aikakauden laissa.

Just as attempts to preserve the power of knights in armor were doomed to fail in the face of gunpowder weapons, so the modern notions of nationalism and citizenship are destined to be short-circuited by microtechnology. Indeed, they will eventually become comic in much the way that the sacred principles of fifteenth-century feudalism fell to ridicule in the sixteenth century. The cherished civic notions of the twentieth century will be comic anachronisms to new generations after the transformation of the year 2000. The Don Quixote of the twenty-first century will not be a knight-errant struggling to revive the glories of feudalism but a bureaucrat in a brown suit, a tax collector yearning for a citizen to audit.

#### Aikajanat kohdilleen

Näiden kahden vastakkaisen rahateorian yhdistämiseksi ja niiden peruslähtökohtien ymmärtämiseksi on tärkeää tarkastella niiden eroja ja erityisesti sitä, missä määrin ne pitävät paikkansa ja milloin ne ovat virheellisiä. Tähän tarkoitukseen palatkaamme *Kansojen varallisuuteen*, jossa Adam Smith kuvaa teoksessaan vaihtokaupan ongelmaa ja miksi taloudessa luonnollisesti ilmaantuu myyntikelpoinen hyödykeraha ratkaisemaan tätä ongelmaa:

"Mutta kun työnjako alkoi kehittyä, vaihtamisen mahdollisuus oli usein huomattavan rajallinen ja hankala. Oletetaan, että yhdellä henkilöllä on tiettyä hyödykettä enemmän kuin toisella, ja toinen olisi halukas luopumaan osasta ylijäämistään, mutta jos toisella ei ole mitään tarjottavaa vastineeksi, vaihdanta ei voi tapahtua heidän välillään. Lihakauppiaalla on enemmän lihaa kuin mitä hän itse voi kuluttaa, ja samalla oluenpanija ja leipuri olisivat valmiita ostamaan osan siitä vastineeksi omista tuotteistaan, mutta sillä hetkellä heillä ei ole mitään annettavaa, koska heillä on jo kaikki leipä ja olut käytettävissään. Tällöin kauppaa ei yksinkertaisesti ole mahdollista tehdä. Lihakauppias ei voi myydä sen, mitä hänellä on, eikä toiset voi olla hänen asiakkaansa. Tässä tilanteessa jokainen järkevä ihminen on pyrkinyt järjestämään asiansa niin, että hänellä on aina tietty määrä hyödykettä, jonka muut ovat valmiita vastaanottamaan vastineeksi hänen tuotoksestaan. On todennäköistä, että monia hyödykkeitä on jo aiemmin ajateltu ja käytetty vastaavaan tarkoitukseen. Aikaisemmin yhteisöissä on sanottu, että karja toimii yleisenä kaupankäynnin välineenä, ja vaikka sen käyttö aluksi oli hyvin epäkäytännöllistä, sen arvo perustui siihen, kuinka monta naudanlihaa sen vaihtamiseen käytettiin. Homeros kertoo, että Diomedeen haarniska maksoi vain yhdeksän härkää, mutta Glaucusuksen haarniska maksoi sata härkää. Suolaa on usein käytetty kaupankäynnin välineenä Abyssiniassa; tietyillä Intian rannikoilla on käytetty simpukoita; Newfoundlandissa kuivattua Turskaa; Virginiassa tupakkaa; Länsi-Intian siirtokunnissa sokeria; joissakin muissa maissa vuodat ja nahkaa; ja nykyään Skotlannissa on kylä, jossa käytetään leipomoiden tai pubien maksuvälineenä nauloja. Kuitenkin lopulta kaikkialla ihmiset ovat päätyneet suosimaan metalleja tähän tarkoitukseen, koska ne eivät ainoastaan säily hyvin, vaan niitä on myös helppo jakaa mihin tahansa pienempiin osiin ja yhdistää uudelleen – ominaisuus, jota mikään muu hyödyke ei omaa, ja joka on keskeisin vaatimuksena kaupankäynnin ja kierrätyksen välineeksi."

Smithin noin 250 vuotta sitten esittämä kokonaiskuvaus vaikuttaa kestäneen hyvin ajan hammasta, ja hän oli pääosin oikeassa. Ensinnäkin hän totesi, että hyödykeraha syntyy luonnostaan, koska se ratkaisee halujen yhteensovittamisen ongelman työjaon ja erikoistumisen maailmassa. Toiseksi hän perusteli, miksi juuri jalometallit ovat historiallisesti osoittautuneet parhaiksi rahan muodoiksi niiden ainutlaatuisten ominaisuuksiensa vuoksi. Kyse ei siis ollut sattumasta, vaan siitä, että ihmiset ympäri maailmaa ovat päätyneet hyväksymään hopean ja kullan ihanteellisimpina hyödykerahoina.

Diablo II -tietokonepelissä Stone of Jordan -sormusten luonnollinen muuntuminen rahaksi on tarjonnut havainnoitavan koeasetelman Smithin rahan syntyä koskevien näkemysten testaamiseksi. Tämä ja muut vastaavat asetelmat ovat todiste siitä, että rahallistumisprosessi on voitu havaita käytännössä sen sijaan, että se olisi jäänyt pelkästään teorian tasolle.

#### Luottorahateorian puutteet

Luottorahateorian kannattajilla on taipumus laajentaa käsityksiään liian pitkälle, jättäen usein täysin huomiotta hyödykerahan merkityksen, ja he maalaavat ylioptimistisen kuvan siitä, kuinka hyvin yhteiskunta pystyy ylläpitämään joustavaa, luottopohjaista tilikirjaa suuressa mittakaavassa ja pitkillä ajanjaksoilla. Ensimmäinen ongelma liittyy tilanteisiin, joissa osa tuottajista tai kauppiaista on erittäin erikoistuneita. Vaikka lihakauppiaat, oluenpanijat ja leipurit pystyvät järjestämään vaihtoa siten, että esimerkiksi yksi kilo naudanlihaa vastaa kolmea tuoppia olutta, joka puolestaan vastaa viittä leipää, entä silloin, kun kyse on esimerkiksi kirurgien kaltaisista erikoistuneista palveluntarjoajista? Kirurgi tarvitsee leipää, joten voisiko hän tarjota leipurille jotakin, jolla hän myöhemmin kompensoi puutetta? Kuinka monen leivän arvoinen leikkaus on, ja mitä leikkauksella oikeastaan tarkoitetaan? Erikoislääkäripalvelut ovat erittäin arvokkaita, kapean markkinaraon palveluita, joita ei voida helposti vaihtaa tai joita ei yleisesti tarvita. On siis selvää, että kaupankäynnin tehostamiseksi tarvitaan standardoituja yksiköitä, ja historiallisesti tällaiset yksiköt ovat usein olleet sidoksissa tiettyyn luonnolliseen hyödykkeeseen, kuten tiettyyn määrään hopeaa tai tai annokseen viljaa. Muussa tapauksessa ihmiset joutuisivat turvautumaan abstrakteihin vaihtakauppoihin, joissa käytettäisiin erilaisia luottovaatimuksia ilman vakiintunutta laskentayksikköä. Historiallisesti, vaikka luottoa onkin käytetty kaupankäynnin välineenä, se ilmaistaan usein myyntikelpoisina hyödykeyksiköinä, jotka ovat nousseet vaihdon välineiksi niiden ominaisuuksien vuoksi.

#### Luottorahateorian puutteet

(Näin sanottuna)

#### Rahan yhtenäisteoria

Hyödykeraha- ja luottorahateoriat näyttävät ensi silmäyksellä olevan ristiriitaisia, minkä vuoksi täydellisen teorian muodostamiseksi on tarpeen löytää niiden yhteinen logiikka eli perusta. Molemmat teoriat tarjoavat keinoja ylläpitää tilikirjaa ja tehdä ”oikeanlaisia” kirjausmerkintöjä, mutta ne eroavat siinä, kuka tai mikä ylläpitää tätä tilikirjaa.

Luottorahateoriassa ihmiset ylläpitävät tilikirjojaan hyödyntämällä luottamukseen perustuvia menetelmiä. Pienissä yhteisöissä tämä voidaan usein toteuttaa epävirallisesti, jolloin tilikirjat saattavat perustua sukulaisuuteen, ystävyyteen ja kunniaan. Suuremmissa yhteisöissä, joissa mukana on toisilleen vieraita ihmisiä, tällaiset luottopohjaiset järjestelmät keskitetään tietyn keskusvallan ja sen sääntöjen alaisuuteen. Historiallisesti nämä järjestelmät ovat kohdanneet niin sanottuja ”nollauksia” ja niiden arvo on laskenut ajan myötä.

Hyödykerahateoriassa taas ihmiset pyrkivät vähentämään inhimilliseen luottamukseen perustuvia oletuksia antamalla luonnon – eli fyysisten luonnollisten lakien – määrätä tilikirjan ylläpidosta. Tällöin hyvin myyntikelpoiset hyödykkeet vaihdetaan suoraan, ja tilikirjan kokonaisarvo määräytyy niiden fyysisen hallussapidon perusteella. Yksikään ihmisen määräämä auktoriteetti ei pysty mielivaltaisesti alentamaan rahan arvoa kirjausmerkintöjen kautta, vaan arvon on säilyttävä luonnollisten lakien turvin.

Näin muodostuu se, mitä voidaan kutsua ”tilikirjarahateoriaksi”, joka paljastaa molempien edellä mainittujen teorioiden yhteisen syvemmän logiikan. Joustavan sosiaalisen luoton ja luonnollisten hyödykerahojen juuret ulottuvat hyvin kauas ihmiskunnan alkuajoista, silloin kun yhteisöt ylläpitävät tilikirjojaan joko keskenään tai luottavat luonnonlakeihin, jotka takaavat jonkinlaisen likvidin säästämisen samalla kun ne ratkaisevat vaihdannan ongelman.

#### A new moral vocabulary will be required

Uuden moraalisen sanaston on noustava kuvaamaan suvereenien yksilöiden välisiä suhteita sekä sitä, mitä hallituksesta jää jäljelle. Epäilemme, että kun näiden uusien suhteiden ehdot kirkastuvat, ne loukkaavat monia, jotka kasvoivat 1900-luvun kansallisvaltioiden kansalaisina. Kansojen loppu ja yksilön denationalisointi saattavat viimein tasoittaa joitakin lämpimästi pidettyjä käsityksiä, kuten ”tasa-arvoinen suojelu lain edessä”, jotka perustuvat vallan suhteisiin, jotka ovat pian vanhentuneita. Kun virtuaaliyhteisöt saavat eheytensä, ne vaativat, että niiden jäseniä pidetään vastuullisina omien lakien mukaisesti – eivät entisten kansallisvaltioiden lakien mukaan, joissa he sattuvat asuttamaan. Useat oikeusjärjestelmät tulevat jälleen rinnakkain elämään samalla maantieteellisellä alueella, aivan kuten antiikin ja keskiaikojen aikoina.



### Kansalaisuuden ylittäminen

Ennen kansallisvaltioiden aikaa maailman olemassa olevien suvereniteettien lukumäärän tarkka määrittäminen oli vaikeaa, koska ne päällekkäistyivät monimutkaisilla tavoilla ja erilaiset organisaatiomuodot harjoittivat valtaa. Näin käy taas. Alueiden väliset rajat muotoutuivat selkeästi merkittyinä ja kiinteinä kansallisvaltioiden järjestelmässä, mutta ne hämärtyvät jälleen tietoyhteiskunnan aikakaudella. Uudella vuosituhannella suvereniteetti pirstoutuu jälleen, ja uusia toimijoita syntyy, jotka hallitsevat joitakin – mutta eivät kaikkia – niitä ominaisuuksia, joita olemme alkaneet liittää hallituksiin.

### Kyberavaruuden kaupparepublikat

Huomaat myös, kuinka kauppiaiden ja varakkaiden henkilöiden yhdistykset, joilla on osittaisen suvereniteetin valtuudet, tulevat uudelleen esiin – kuten keskiajalla toimiva Hanse (kauppiaiden liitto). Ranskan ja Flaminian messuilla toimiva Hanse laajeni kattamaan kuusikymmentä kaupungin kauppiaita.[^10] "Hanseatie League" – kuten sitä englanniksi redundanssina kutsutaan (kirjaimellisesti "Leaguely League") – oli saksalaisten kauppaseurojen järjestö, joka tarjosi jäsenilleen suojaa ja neuvotteli kauppasopimuksia. Se saavutti osittaisen suvereniteetin valtuudet useissa Pohjois-Euroopan ja Itämeren kaupungeissa. Tällaiset toimijat nousevat uudelleen esiin kuolevan kansallisvaltion tilalle uudella vuosituhannella, tarjoten suojaa ja auttaen valvomaan sopimusten täytäntöönpanoa epävakaassa maailmassa.

Yhteenvetona voidaan todeta, että tulevaisuus todennäköisesti hämmentää niitä odotuksia, jotka ovat muotoutuneet 1900-luvun teollisyhteiskunnan kansallisten myyttien vaikutuksesta. Niihin sisältyvät esimerkiksi sosiaalidemokratian illuusiot, jotka aikoinaan innostivat jopa kaikkein lahjakkaita mieliä. Ne olettavat, että yhteiskuntia muovataan juuri siinä määrin kuin hallitukset haluavat – mieluiten reagoimaan mielipidetutkimuksiin ja huolellisesti laskettuihin ääniin. Tämä ei kuitenkaan ole koskaan ollut yhtä totta kuin viisikymmentä vuotta sitten; nykyään se on anakronismi, yhtä paljon teollisuuden artefakti kuin ruostava savupiippu. Kansalliset myytit paljastavat paitsi ajattelutavan, joka näkee yhteiskunnan ongelmat insinööritieteellisinä ratkaisukohteina, myös väärän itseluottamuksen siitä, että resurssit ja yksilöt pysyvät tulevaisuudessa yhtä alttiina poliittiselle pakottamiselle kuin 1900-luvulla. Me epäilemme sitä. Markkinavoimat, eivätkä poliittiset enemmistöt, pakottavat yhteiskunnat uudelleen muotoilemaan itsensä tavoilla, joita yleinen mielipide ei ymmärrä eikä toivota. Näin ollen naiivi näkemys siitä, että historia on juuri sitä, mitä ihmiset haluavat sen olevan, osoittautuu valtavasti harhaanjohtavaksi.

Siksi on ratkaisevan tärkeää, että opit katsomaan maailmaa uudella tavalla. Tämä tarkoittaa sitä, että tarkastelet asioita ulkopuolisesta näkökulmasta ja analysoit uudelleen paljon sitä, mitä olet saattanut pitää itsestäänselvyytenä. Näin voit saavuttaa uuden ymmärryksen. Jos et kykene ylittämään tavanomaista ajattelua aikana, jolloin tavanomainen ajattelu menettää yhteytensä todellisuuteen, joudut todennäköisemmin disorientaation epidemicin uhriksi. Desorientaatio synnyttää virheitä, jotka voivat uhata liiketoimintaasi, sijoituksiasi ja elämäntapaasi.

> Universumi palkitsee meidät siitä, että ymmärrämme sen, ja rankaisee meitä siitä, ettemme ymmärrä sitä. Kun ymmärrämme universumia, suunnitelmamme onnistuvat ja tunnemme olomme hyväksi. Toisaalta, jos yritämme lentää hyppäämällä kallion reunalta ja räpyttämällä käsivarsiamme, universumi tappaa meidät.[^11]  
> -- JACK COHEN AND IAN STEWART

### Uudella näkökulmalla

Valmistautuaksesi tulevaan maailmaan sinun on ymmärrettävä, miksi se tulee olemaan erilainen kuin mitä useimmat asiantuntijat kertovat. Tämä edellyttää tiivistä tarkastelua muutoksen piilevistä syistä. Olemme pyrkineet tekemään tätä epätavanomaisella analyysilla, jota kutsumme megapolitiikan tutkimukseksi. Kahdessa aiemmassa teoksessamme, Blood in the Streets ja *The Great Reckoning*, väitimme, että tärkeimmät muutosvoimat eivät löydy poliittisista manifestista tai kuolleiden taloustieteilijöiden lausunnoista, vaan piilevistä tekijöistä, jotka muuttavat niitä rajoja, joilla valtaa harjoitetaan. Usein hienovaraiset muutokset ilmastossa, maastonmuodoissa, mikrobeissa ja teknologiassa muuttavat väkivallan logiikkaa ja muokkaavat tapaa, jolla ihmiset järjestäytyvät toimeentulonsa ja itsensä puolustamisensa suhteen.

Huomaa, että tapamme ymmärtää, miten maailma muuttuu, on hyvin erilainen kuin useimpien ennustajien. Emme ole asiantuntijoita missään – emme teeskennellä tietävämme paljon enemmän tietyistä "aiheista" kuin ne, jotka ovat viettäneet koko uransa erittäin erikoistuneen tiedon parissa. Päinvastoin, katsomme ulkopuolelta sisään. Olemme perillä niistä aiheista, joista teemme ennusteita. Ennen kaikkea tämä tarkoittaa sitä, että havaitsemme, missä välttämättömyyden rajat on vedetty. Kun nämä rajat muuttuvat, myös yhteiskunta välttämättä muuttuu, riippumatta siitä, mitä ihmiset haluaisivat vastakkaiseksi.

Mielestämme keskeistä yhteiskuntien kehittymisen ymmärtämisessä on selvittää tekijät, jotka määrittävät väkivallan käytön kustannukset ja palkkiot. Jokainen ihmisyhteiskunta – olipa kyseessä metsästysjoukko tai imperiumi – on saanut muotonsa megapoliittisten tekijöiden vuorovaikutuksen kautta, jotka asettavat vallitsevan version "luonnonlaeista". Elämä on aina ja kaikkialla monimutkaista. Karitsa ja leijona ylläpitävät herkkää tasapainoa, vuorovaikuttaen reuna-alueilla. Jos leijonat yllättäen nopeutuisivat, ne saisivat kiinni saaliista, jotka nykyään pakenisivat. Jos karitsat kasvaisivat yhtäkkiä siivillään, leijonat nälkäisivät. Kyky hyödyntää ja puolustautua väkivaltaa vastaan on ratkaiseva muuttuja, joka vaikuttaa elämään reunoilla.

Asetamme väkivallan teoriamme keskiöön hyvällä syyllä. Väkivallan hallinta on kaikkein tärkein haaste, jonka jokainen yhteiskunta kohtaa. Kuten kirjoitimme teoksessamme *The Great Reckoning*:

  "Syynä siihen, että ihmiset turvautuvat väkivaltaan, on se, että se usein kannattaa. Joissain suhteissa yksinkertaisin tapa hankkia rahaa on ottaa se. Tämä pätee yhtä hyvin armeijalle, joka valtaa öljykentän, kuin yksittäiselle ryöstömiehelle, joka nappaa lompakon. Valta, kuten William Playfair kirjoitti, 'on aina etsinyt helpointa tietä varallisuuteen hyökkäämällä niihin, joilla sitä on hallussa.'"

  "Vaurauden haasteena on juuri se, että saalistava väkivalta tuottaa palkkioita tietyissä olosuhteissa. Sota muuttaa asioita. Se muuttaa säännöt. Se muuttaa varallisuuden ja tulonjaon. Se jopa määrittää, kuka elää ja kuka kuolee. Juuri se, että väkivalta kannattaa, tekee sen hallitsemisesta vaikeaa."

Näin ajateltuna olemme kyenneet ennakoimaan lukuisia kehityskulkuja, joiden tapahtumista paremmin perillä olevat asiantuntijat väittelivät, etteivät ne voisi koskaan toteutua. Esimerkiksi Blood in the Streets, joka julkaistiin vuoden 1987 alussa, oli yrityksemme kartoittaa suurimman megapoliittisen vallankumouksen ensimmäisiä vaiheita, joka nyt on käynnissä. Siinä argumentoimme, että teknologinen muutos oli epävakauttamassa maailman vallan jakaumaa. Keskeisimmät pointtimme olivat muun muassa:

• Me osoitimme, että amerikkalainen ylikansallisuus oli laskussa, mikä johtaisi taloudellisiin epätasapainoihin ja ahdinkoon, mukaan lukien toinen vuoden 1929–tyyppinen pörssiromahdus. Asiantuntijat olivat lähes yksimielisiä sen estämisestä, mutta kuuden kuukauden sisällä, lokakuussa 1987, markkinat kokenivat vuosisadan väkivaltaisimman myyntihäiriön.

• Kehotimme lukijoita odottamaan kommunismin romahdusta. Taas kerran asiantuntijat nauroivat, mutta vuonna 1989 tapahtui sellaisia asioita, joita "kukaan ei olisi voinut ennustaa." Berliinin muuri kaatui, kun vallankumoukset pyyhkäisivät kommunistisia hallintoja Itämereltä Bukarestiin asti.

• Selitimme, miksi monietninen imperiumi, jonka Bolshevik-nomenklatura periytyi tsaareilta, "epävarmasti särkyisi." Joulukuun 1991 lopussa vasara- ja alavaakerhon lippu laskettiin Kremlin ylle viimeisen kerran, kun Neuvostoliitto lakkaa olemasta.

• Reaganin asevarustelun huipulla väitimme, että maailma oli kynnyksellä laajamittaiselle aseiden vähentämiselle. Myös tätä pidettiin epätodennäköisenä, ellei jopa naurettavana, mutta seuraavat seitsemän vuotta toivat maailmalle suurimman aseiden vähentämisen ensimmäisen maailmansodan päättymisen jälkeen.

• Silloin, kun Pohjois-Amerikan ja Euroopan asiantuntijat osoittivat Japanaa esimerkkinä siitä, että hallitukset pystyvät onnistuneesti manipuloiimaan markkinoita, me sanoimme toisin. Ennustimme, että japanilaisten rahoitusvarojen nousukausi päättyisi romahdukseen. Pian Berliinin muurin kaatumisen jälkeen japanilainen pörssi romahdettiin, menettäen lähes puolet arvostaan. Uskomme edelleen, että sen lopullinen pohja voisi vastata tai jopa ylittää sen 89 prosentin tappion, jonka Wall Street koki vuoden 1929 jälkeen.

Näin ajateltuna olemme nähneet, kuinka väkivallan käytön kustannuksia ja palkkioita koskevien tekijöiden ymmärtäminen voi paljastaa yhteiskuntien elämän monimutkaisuuden ja sen, miten pienetkin muutokset pakottavat järjestelmän sopeutumaan.

• Siinä vaiheessa, kun lähes kaikki – keskiluokkalaisperheistä maailman suurimpiin kiinteistösijoittajiin – vaikuttivat uskovan, että kiinteistömarkkinat voisivat vain nousta eikä laskea, varoitimme, että kiinteistökupla oli tulossa. Neljän vuoden kuluessa kiinteistösijoittajat ympäri maailmaa menettivät yli 1 biljoonan dollarin verran, kun omaisuuksien arvot laskivat.

• Jo kauan ennen kuin asiantuntijoille kävi ilmi, selitimme kirjassamme *Blood in the Streets*, että sinimiehen työläisten tulot olivat laskeneet ja niiden oli määrä jatkaa laskuaan pitkässä juoksussa. Nykypäivänä, lähes vuosikymmenen kuluttua, on vihdoin alkanut uhruttaa kasvaa ymmärrys siitä, että näin on. Yhdysvalloissa keskimääräiset tuntipalkat ovat laskeneet alle toisen Eisenhowerin hallinnon aikaan saavutettujen tasojen. Vuonna 1993 keskimääräiset vakioarvoisina vuosittaiset tuntipalkat olivat 18 808 dollaria, kun taas vuonna 1957, toisen Eisenhowerin virkavalassa, ne olivat 18 903 dollaria.

• Vaikka *Blood in the Streets* -teoksen pääteemat ovat osoittautuneet poikkeuksellisen osuviksi jälkiviisauden valossa, vain muutama vuosi sitten niitä pidettiin konventionaalisen ajattelun vartijoiden toimesta täysin järjettöminä. Vuonna 1987 *Newsweek*-lehden arvostelija heijasti myöhäisen teollisyhteiskunnan suljettua mielentilaa hylkäämällä analyysimme "ajatuksettomana hyökkäyksenä järkeä vastaan."

• Voisit kuvitella, että *Newsweek* ja vastaavat julkaisut olisivat ajan myötä tunnustaneet analyysimme linjan paljastaneen jotakin hyödyllistä maailman muutoksista. Ei ollenkaan – *The Great Reckoning* -teoksen ensimmäinen painos otettiin vastaan samankaltaisella nauran täyttämällä vihamielisyydellä kuin *Blood in the Streets* -teos. Ei vähempää auktoriteettia kuin *Wall Street Journal* hylkäsi kategorisesti analyysimme nimittäen sitä "sinun töpö tätisi jutusteluna."

• Nauramisen sivuun jättäen, *The Great Reckoning* -teoksen teemat osoittautuivat vähemmän naurettaviksi kuin ortodoksian vartijat väittivät.

• Laajensimme ennustustamme Neuvostoliiton kuolemasta, selvittäen, miksi Venäjä ja muut entiset Neuvostotasavaltiot kohtasivat tulevaisuudessa kasvavaa sisäistä epäjärjestystä, hyperinflaatiota ja laskeneita elintasoja.

• Selitimme, miksi 1990-luku olisi vuosikymmen supistumista – mukaan lukien ensimmäistä kertaa hallitusten sekä yritysorganisaatioiden maailmanlaajuinen supistuminen.

• Ennustimme myös, että tulonjaon ehtoja määritettäisiin uudelleen merkittävästi ja etuuksien tasoa leikattaisiin jyrkästi. Verkossa annettuja merkkejä fiskalisen kriisin uhkista ilmestyi Kanadasta Ruotsiin, ja amerikkalaiset poliitikot alkoivat puhua "sosiaalisetuuksien lopettamisesta sellaisina kuin ne me nykyään tiedämme."

• Ennustimme ja selitimme, miksi "uusi maailmankunta" osoittautuisi "uudeksi maailman epäjärjestykseksi." Jo kauan ennen kuin Bosnian julmuudet valloittivat otsikot, varoitimme, että Jugoslavia romahtuisi sisällissotaan.

• Ennen kuin Somalia liukui anarkian tilaan, selitimme, miksi Afrikan hallitusten odotettu romahtaminen johtaisi joidenkin maiden käytännössä sijoittumiseen vastaanottajavalvonnan alaisuuteen.

Me ennustimme ja selitimme, miksi militant Islam syrjäyttäisi marxismia Länteen kohdistuvassa vastakkainasettelussa keskeisenä ideologiana. Vuosia ennen Oklahoma-pommi-iskuja ja yritystä räjäyttää World Trade Center, selitimme, miksi Yhdysvallat kohtasi terrorismin kasvua.

Ennen otsikoita, joissa kerrottiin Los Angelesin, Toronton ja muiden kaupunkien laajasta mellasta, selitimme, miksi rikollisten alakulttuurien kehittyminen kaupunkivähemmistöjen keskuudessa loi edellytykset laajalle levittäytyvälle rikolliselle väkivallalle.

Ennustimme myös "vinttivuosisadan viimeisen laman", joka alkoi Aasiassa vuonna 1989 ja on levinnyt reunalta kohti globaalin järjestelmän keskustaa. Me totesimme, että Japanin pörssi seuraisi Wall Streetin polkua vuoden 1929 jälkeen ja että tämä johtaisi luottokriisiin ja lamaan. Vaikka massiivinen hallituksen interventio Japanissa ja muualla esti väliaikaisesti markkinoita heijastamasta täydellisesti luotto-olosuhteiden heikkenemistä, tämä ainoastaan siirsi ja pahensi taloudellista ahdinkoa, luoden paineita kilpailullisiin devalvointeihin ja järjestelmälliseen luottokriisiin, jonka kaltaiset kriisit romahtivat maailmanlaajuiset taloudet 1930-luvulla.

*The Great Reckoning* esitti myös useita kiistanalaisia teesejä, joita ei ole vielä vahvistettu tai jotka eivät ole saavuttaneet ennustamaamme kehitystasoa:

- Me totesimme, että Japanin pörssi seuraisi Wall Streetin polkua vuoden 1929 jälkeen ja että tämä johtaisi luottokriisiin ja lamaan. Vaikka työttömyysasteet Espanjassa, Suomessa ja muutamissa muissa maissa olivat korkeammat kuin 1930-luvulla, ja vaikka useat maat, mukaan lukien Japani, kokivat paikallisia lamoja, järjestelmällistä luottokriisiä, jonka kaltaiset kriisit romahtivat maailmanlaajuiset taloudet 1930-luvulla, ei ole vielä tapahtunut.

- Me väitimme, että entisen Neuvostoliiton komentoon ja kontrolliin perustuvan järjestelmän hajoaminen johtaisi ydinaseiden leviämiseen minivaltioden, terroristien ja rikollisjengien käsiin. Onnen kohtaloa maailmalle, tätä ei ole toteutunut, ainakaan siinä määrin kuin pelkäsimme. Lehdistöraporttien mukaan Iran osti useita taktisia ydinaseita mustalta markkinalta, ja saksalaiset viranomaiset estivät useita yrityksiä myydä ydinmateriaaleja. Kuitenkin entisen Neuvostoliiton arsenaleista ei ole ilmoitettu ydinaseiden käyttöönotosta tai -käytöstä.

- Me selitimme, miksi "War on Drugs" oli resepti poliisi- ja oikeusjärjestelmien alistamiselle niissä maissa, joissa huumeiden käyttö on laajalle levinnyttä, erityisesti Yhdysvalloissa. Kun vuosittain kertyvissä piilomonopoliovoitoissa on kymmeniä miljardeja dollareita, huumekauppiailla on sekä resurssit että kannustin korruptoida jopa näennäisesti vakaita maita. Vaikka maailman media on ajoittain esittänyt tarinoita, jotka viittaavat huume-rahan korkeatasoiseen tunkeutumiseen Yhdysvaltain poliittiseen järjestelmään, koko tarinaa ei ole vielä kerrottu.

### Looking Where Others Don't

Huolimatta niistä kohdista, joissa ennustuksemme olivat väärässä tai vaikuttavat olevan virheellisiä nykyisten tietojen valossa, ennätyksemme kestää kriittisen tarkastelun. Paljon sitä, mikä saattaa todennäköisesti ilmestyä tulevissa 1990-lukujen taloushistoriankirjoituksissa, ennustettiin tai ennakoitiin ja selitettiin *The Great Reckoning* -teoksessa. Monet ennustuksistamme eivät olleet yksinkertaisia trendien jatkumoita tai laajennuksia, vaan ennustuksia merkittävistä poikkeamista siitä, mitä on pidetty normaalina toisen maailmansodan jälkeen. Varoimme, että 1990-luku olisi dramaattisesti erilainen kuin edelliset viisi vuosikymmentä. Lukemalla uutisia vuosilta 1991–1995 näemme, että *The Great Reckoning* -teoksen teemat toteutuivat melkein päivittäin.

Näemme nämä kehityskulut emmekä erillisinä vaikeuksien, ongelmien tai häiriöiden esimerkkeinä, vaan iskuina ja värinäinä, jotka kulkevat pitkin samaa murrekulmaa. Vanha järjestys kaatuu megapoliittisen maanjäristyksen seurauksena, joka mullistaa instituutiot ja muuttaa tapaamme nähdä maailmaa.

Huolimatta siitä, että väkivallalla on keskeinen rooli maailman toiminnan määrittämisessä, se herättää yllättävän vähän vakavaa huomiota. Suurin osa poliittisista analyytikoista ja taloustieteilijöistä kirjoittaa ikään kuin väkivalta olisi vain pieni ärsyttävä häiriö, esimerkiksi kärsä, joka surisee kakun ympärillä – eikä se olisi kokki, joka sen leipoi.

### Toinen megapoliittinen pioneeri

Itse asiassa väkivallan roolia historiassa on pohdittu niin vähän selkeästi, että kokoelma megapoliittisia analyysejä voitaisiin laatia yhdelle paperilevylle. Teoksessa *The Great Reckoning* hyödynsimme ja laajensimme lähes kokonaan unohtuneen megapoliittisen analyysin klassikon, William Playfairin teoksen An Enquiry into the Permanent Causes of the Decline and Fall of Powerful and Wealthy Nations, julkaistun vuonna 1805, argumentteja. Yksi lähtökohdistamme on Frederic C. Lanen työ. Lane oli keskiaikainen historioitsija, joka kirjoitti useita oivaltavia esseitä väkivallan roolista historiassa 1940- ja 1950-luvuilla. Ehkä kattavin näistä oli "Economic Consequences of Organized Violence", joka ilmestyi Journal of Economic History -lehdessä vuonna 1958. Harvat muut kuin ammattitaitoiset taloustieteilijät ja historioitsijat ovat lukeneet sen, eikä suurin osa heistä näytä olleen tietoisia sen merkityksestä. Aivan kuten Playfair, Lane kirjoitti yleisölle, jota ei vielä ollut olemassa.

### Oivalluksia informaatiokauteen

Lane julkaisi työnsä väkivallasta ja sodan taloudellisesta merkityksestä kauan ennen informaatiokauden yleistymistä. Hän ei todellakaan kirjoittanut ennakoimassa mikroprosessointia tai muita teknologisia vallankumouksia, jotka nyt ovat käynnissä. Kuitenkin hänen oivalluksensa väkivallasta loivat kehyksen ymmärtää, kuinka yhteiskunta uudelleenmääritellään informaatiovallankumouksessa.

Se ikkuna, jonka Lane avasi tulevaisuuteen, oli sellainen, jonka kautta hän kurkisteli menneisyyteen. Hän oli keskiaikainen historioitsija, erityisesti kauppakaupungin, Venetsian, historioitsija, jonka kohtalo nousi ja laski väkivaltaisen maailman keskellä. Pohdittaessa, kuinka Venetsia nousi ja kaatui, hänen huomionsa kiinnittyi kysymyksiin, jotka auttavat ymmärtämään tulevaisuutta. Hän huomasi, että se, miten väkivalta organisoidaan ja kontrolloidaan, näyttelee suurta roolia määritettäessä, "mihin harvinaisista resursseista hyödynnetään." [^13]

Uskomme, että Lanen analyysit väkivallan kilpailullisista käyttötavoista antavat paljon sanottavaa siitä, kuinka elämä muuttuu todennäköisesti informaatiokaudella. Mutta älä odota, että useimmat ihmiset kiinnittäisivät huomiota – puhumattakaan seuraisivat – näin epätyypillisen abstraktia esitettyä argumenttia. Kun maailman huomio on kiinnittynyt epärehellisiin keskusteluihin ja eksyneisiin persoonallisuuksiin, megapolitiikan harhailut jatkuvat lähes huomaamatta. Keskimääräinen pohjoisamerikkalainen on luultavasti antanut sata kertaa enemmän huomiota 0. J. Simpsonille kuin uusille mikroteknologioille, jotka ovat valmiina vanhentamaan hänen työnsä ja horjuttamaan sitä poliittista järjestelmää, johon hän turvautuu työttömyysturvan saamiseksi.

## TOIVEIDEN TURHAMUS

Tendenssi sivuuttaa se, mikä on pohjimmiltaan tärkeää, ei rajoitu ainoastaan televisiota katsoviin sohvakatsojiin. Kaikenlaiset tavanomaiset ajattelijat eri muodoissa huomauttavat kansallisvaltion teesauksesta – että ihmisten mielipiteet määrittävät, miten maailma muuttuu. Ilmeisesti hienostuneet analyytikot lipsahtavat selitys- ja ennustustapoihin, jotka tulkitsevat merkittäviä historiallisia kehityskulkuja ikään kuin ne määräytyisivät toiveikkaalla tavalla. Yksi silmiinpistävä esimerkki tällaisesta päättelystä ilmestyi New York Timesin kritiikkisivulle juuri sillä hetkellä, kun kirjoitimme "Goodbye, NationState, Hello...What?," Nicholas Colchesterin toimesta.[^14] Ei ainoastaan aihe – kansallisvaltion kuolema – ollut meidän käsiteltävänä, vaan sen kirjoittaja esittää itsensä erinomaisena mittarina havainnollistamaan sitä, kuinka kaukana ajattelumme on normaalista. Colehester ei ole mikään typerys. Hän kirjoitti toimittajana Economist Intelligence Unitissa. Jos kenenkään pitäisi muodostaa realistinen kuva maailmasta, sen pitäisi olla hän. Kuitenkin hänen artikkelinsa osoittaa selkeästi useissa kohdissa, että "kansainvälisen hallituksen saapuminen on nyt loogisesti pysäyttämätöntä."

Miksi? Koska kansallisvaltio horjuu eikä kykene enää hallitsemaan taloudellisia voimia.

Mielestämme tämä oletus on lähes absurdia. Oletus, että jokin tietty uusi hallinnon muoto syntyisi pelkästään siksi, että toinen on epäonnistunut, on virheellinen ajattelutapa. Tällä logiikalla Haitilla ja Zairessa olisi jo kauan sitten ollut parempi hallinto, koska heidän nykyinen järjestelmänsä on niin räikeän puutteellinen.

Colchesterin näkökulmaa – jota jakavat laajalti ne harvat, jotka Pohjois-Amerikassa ja Euroopassa ajattelevat tällaisista asioista – ei oteta lainkaan huomioon suurempia megapoliittisia voimia, jotka määräävät, millaiset poliittiset järjestelmät ovat todellisuudessa toimivia. Tämä on tämän kirjan painopiste. Kun tarkastellaan niitä teknologioita, jotka muovaavat uutta vuosituhatta, on paljon todennäköisempää, että näemme ei yhtä maailmanhallintoa, vaan pikemminkin mikrohallintoja tai olosuhteita, jotka lähestyvät anarkiaa.

Jokaisesta vakavasta analyysistä väkivallan roolista kaikkien toimintaa ohjaavien sääntöjen määrittämisessä on kirjoitettu kymmeniä kirjoja vehnäsubsidioiden hienovaraisista yksityiskohdista ja satoja lisää rahapolitiikan arkaisista seikoista. Suuri osa tästä ajattelun vajauksesta niistä ratkaisevista kysymyksistä, jotka todellisuudessa määräävät historian kulun, kuvastaa todennäköisesti sitä, että viimeisten useiden vuosisatojen voimarakenteen vakaus on ollut suhteellisen korkea. Lintu, joka nukahtaa virtahevon selässä, ei ajattele menettävänsä pesäänsä ennen kuin virtahepo itse liikkeelle ryhtyy. Unet, myytit ja fantasiat näyttelevät paljon suurempaa roolia sellaisten väitetysti yhteiskuntatieteiden muodostamisessa kuin yleisesti ajattelemme.

Tämä käy erityisen selvästi laajassa taloudellisen oikeudenmukaisuuden kirjallisuudessa. Miljoonia sanoja on sanottu ja kirjoitettu taloudellisesta oikeudenmukaisuudesta ja epäoikeudenmukaisuudesta jokaiselta sivulta, joka on omistettu huolelliselle analyysille siitä, miten väkivalta muokkaa yhteiskuntaa ja asettaa rajat, joiden puitteissa taloudet on toimittava. Kuitenkin modernin taloudellisen oikeudenmukaisuuden muotoilut edellyttävät, että yhteiskuntaa hallitsee niin voimakas pakottamisen väline, joka kykenee riistämään ja uudelleenjakamaan elämän hyvät asiat. Tällainen valta on ollut olemassa vain muutaman sukupolven ajan modernissa ajassa. Nyt se on kuihtumassa.

### Big Brother on Social Security

Teollisuusteknologia antoi hallituksille 1900-luvulla enemmän kontrollivälineitä kuin koskaan aiemmin. Hetken aikaa vaikutti väistämättömältä, että hallitukset tulevat olemaan niin tehokkaita väkivallan monopolisoimisessa, että yksilön autonomialle jää vain hyvin vähän tilaa. Keskivuosikasta kukaan ei odottanut Sovereign Individualin voittoa.

Jotkut 1900-luvun puolivälin terävimmistä tarkkailijoista tulivat päivän todisteiden perusteella vakuuttuneiksi siitä, että kansallisvaltion taipumus keskittää valtaa johtaisi totalitaariseen hallintaan kaikilla elämän osa-alueilla. George Orwellin teoksessa *1984* (1949) Big Brother seurasi yksilöä turhaan taistellen säilyttääkseen jonkin marginaalin itsenäisyyttä ja itsekunnioitusta – se näytti olevan tappio. Friedrich von Hayekin *The Road to Serfdom* (1944) esitti tieteellisemmän näkemyksen siitä, että vapaus menetti arvonsa uudenlaisen taloudellisen kontrollin vuoksi, joka jätti valtion kaiken hallitsijaksi. Nämä teokset kirjoitettiin ennen mikroprosessorien tuloa, jotka ovat mahdollistaneet lukuisten teknologioiden kehittymisen, parantaen pienten ryhmien ja jopa yksilöiden kykyä toimia itsenäisesti keskitetystä vallasta.

Vaikka Hayekin ja Orwellin kaltaiset tarkkailijat olivat teräviä, heidän pessimisyytensä oli yliampuvaa. Historia on tuonut omat yllätystensä käänteensä. Totalitaarinen kommunismi ei juuri kestänyt vuoden 1984 yli. Uusi orjuuden muoto saattaa vielä syntyä seuraavalla vuosituhannella, jos hallitukset onnistuvat tukahduttamaan mikroteknologian vapauttavat puolet. Mutta on paljon todennäköisempää, että näemme ennennäkemättömiä mahdollisuuksia ja yksilön autonomian lisääntymistä. Se, mistä vanhempamme olivat huolissaan, saattaa osoittautua täysin ongelmattomaksi. Mitä he pitivät itsestäänselvyyksinä kiinteinä ja pysyvinä piirteenä yhteiskunnallisessa elämässä, näyttää nyt olevan kohtalolta katoaa. Missä tahansa tarve asettaa rajoja ihmisen valinnoille, me sopeudumme ja järjestämme elämämme uudelleen sen mukaisesti.

### Ennustamisen vaarat

Epäilemättä riskannamme pienen määrän ihmisarvoamme yrittäessämme ennustaa ja selittää syviä muutoksia elämän järjestelyissä ja sitä yhdistävässä kulttuurissa. Useimmat ennusteet ovat tuomittuja muodostamaan naurettavaa luettavaa ajan kuluessa. Ja mitä dramaattisemmaksi ne kuvittelevat muutoksen, sitä nolommiksi ne yleensä osoittautuvat. Maailma ei pääty. Otsonikerros ei häviä. Tuleva jääkausi sulaa globaaliksi lämpenemiseksi. Kaikista toisin kuulutetuista varoituksista huolimatta säiliössä on edelleen öljyä.

Mr. Antrobus, teoksen *The Skin of Our Teeth* tavallinen mies, välttää jäätymisen, selviää sodista ja uhkaavista talouskatastrofeista ja vanhenee sivuamatta asiantuntijoiden tutkittuja varoituksia.

Suurin osa yrittämistämme "paljastaa" tulevaisuus osoittautuu pian koomiseksi. Vaikka oma etu rohkaisee klariin ajatteluun, tulevaisuuteen katsominen on usein lyhyinä näköistä. Vuonna 1903 Mercedes ilmoitti, että "maailmassa ei koskaan tule olemaan jopa miljoonaa autoa. Syynä oli se, että olisi epäuskottavaa, että jopa miljoonaa käsityöläistä voitaisiin kouluttaa kuljettajiksi."[^15]

Tämän tunnistaminen pitäisi estää meitä puhumasta liikaa, mutta se ei. Emme pelkää mennä jonossa saadaksemme osamme pilkasta. Jos teemme virheitä, tulevat sukupolvet saattavat nauraa sydämensä pohjasta, olettaen, että kukaan muistaa, mitä sanoimme. Rohkeus ajatella merkitsee sen riskin ottamista, että olemme väärässä. Emme ole niin jäykkiä ja hyödyttömiä, ettemme uskaltaisi erehtyä. Päinvastoin: mieluummin esimme ajatuksia, jotka saattavat osoittautua hyödyllisiksi sinulle, kuin pidätämme niitä huolestuneina siitä, että ne saattavat jälkikäteen vaikuttaa liioitelluilta tai nololta.

Kuten Arthur C. Clarke oivaltavasti huomautti, kaksi yleisintä syytä, miksi tulevaisuutta yrittävät ennakoivat yritykset usein epäonnistuvat, ovat "hermotusten puute ja mielikuvituksen puute."[^16] Näistä hän kirjoitti: "Hermosutusten puute vaikuttaa yleisemmältä; se ilmenee silloin, kun edes kaikista olennaisista faktoista huolimatta yritysprofeetta ei pysty näkemään, että ne viittaavat väistämättömään johtopäätökseen. Jotkut näistä epäonnistumisista ovat niin naurettavia, että ne lähes uskottavuudeltaan mahdottomia."[^17]

Missä tietoverkkovaallan tutkimuksemme jääkin vajaaksi – kuten se väistämättä tekee – syynä on enemmän mielikuvituksen puute kuin hermotusten puute. Tulevaisuuden ennustaminen on aina ollut rohkea hanke, joka herättää luonnostaan skepsistä. Ehkä aika näyttää, että päätelmämme ovat hurjasti väärässä. Toisin kuin Nostradamus, emme esitä olevamme profeettisia persoonia. Emme ennusta tulevaisuutta sekoittamalla taikasauvaa vesikulhoon tai laatimalla horoskooppeja. Emme myöskään kirjoita salaperäisellä runoudella. Tarkoituksemme on tarjota sinulle vakavaa, etäistä analyysiä asioista, jotka saattavat osoittautua sinulle suureksi merkitykseksi.

Koemme velvollisuudeksemme esittää näkemyksemme, vaikka ne saattavatkin vaikuttaa kerettiläisiltä, juuri siksi, että muuten niistä ei välttämättä kuuluisikaan. Myöhäisteollisen yhteiskunnan suljetussa mielentilassa ideoiden liikkuminen ei ole yhtä vapautunutta kuin sen pitäisi olla vakiintuneiden medioiden kautta.

Tämä kirja on kirjoitettu rakentavassa hengessä. Se on kolmas, jonka olemme yhdessä kirjoittaneet analysoiden suurta muutosta, joka parhaillaan on käynnissä. Kuten Blood in the Streets ja *The Great Reckoning*, se on ajatusharjoitus. Se tutkii teollisyhteiskunnan kuolemaa ja sen uudelleenjärjestäytymistä uusina muotoina. Odotamme näkevämme hämmästyttäviä paradokseja tulevina vuosina. Toisaalta tulet todistamaan uudenlaisen vapauden syntymistä, kun Itsenäisen yksilön aika koittaa. Voit odottaa näkeväsi lähes täydellisen tuottavuuden vapautumisen. Samalla odotamme modernin kansallisvaltion kuolemaa. Monet länsimaisten ihmisille jo kaksikymmentäluvulla itsestäänselvyytenä pidetyt tasa-arvon takeet ovat tuomittu olemaan kuolemassa sen mukana. Oletamme, että nykyisen edustuksellisen demokratian muoto hiipuu, ja sen tilalle astuu kybermarkkinoiden uudenlaiset valinnan demokratian muodot. Jos päättelymme osuu oikeaan, seuraavan vuosisadan politiikka tulee olemaan monimuotoisempaa ja vähemmän merkityksellistä kuin mikä meille on tullut tutuiksi.

Olemme varmoja, että argumenttimme ovat helposti seurattavissa, siitä huolimatta, että ne johtavat joidenkin alueiden läpi, jotka ovat älylliseltä vastaava takamaiden ja huonojen naapurustojen tasolla. Jos merkityksemme ei ole kaikissa kohdissa täysin ymmärrettävä, se ei johdu siitä, että yrittäisimme olla leikitteleviä tai käyttäisimme vanhaan tapaan kaksijakoisia ilmauksia, joita ne, jotka esittävät ennustavansa tulevaisuutta salaperäisillä lausunnoilla, käyttävät. Emme ole kaksoispuheilijoita. Jos argumenttimme ovat epäselviä, se johtuu siitä, että emme ole onnistuneet kirjoittamaan tavalla, joka tekisi vakuuttavista ideoista helposti lähestyttäviä. Toisin kuin monet ennustajat, haluamme, että ymmärrät ja jopa pystyt jäljentämään ajattelutapamme. Se perustuu ei psyykkisiin haaveisiin tai planeettojen liikkeisiin, vaan vanhanaikaiseen, rumaan logiikkaan. Varsin loogisista syistä uskomme, että mikrosuorituskyky lopulta kumoaa ja tuhoaa kansallisvaltion, luoden prosessin myötä uusia yhteiskunnallisen järjestäytymisen muotoja. On sekä tarpeellista että mahdollista, että osaat ennakoida ainakin joitakin yksityiskohtia uudesta elämäntavasta, joka saattaa olla täällä nopeammin kuin luulet.

### Ironies of a Future Foretold

Vuosisatojen ajan tämän vuosituhannen loppua on pidetty historiaa tarkoittavana hetkenä. Yli 850 vuotta sitten St. Malachy määräsi vuodeksi 2000 viimeiseksi tuomioksi. Amerikkalainen psyykkinen Edgar Cayce sanoi vuonna 1934, että maa siirtyisi akselillaan vuonna 2000, mikä aiheuttaisi Kalifornian jakautumisen kahteen osaan ja tulvaisi New Yorkin kaupungin ja Japanin. Japanilainen rakettitiedemies Hideo Itokawa ilmoitti vuonna 1980, että planeettojen asettuminen "Grand Crossiin" 18. elokuuta 1999 aiheuttaisi laajaa ympäristötuhoa, mikä johtaisi ihmisen elämän päättymiseen maapallolla.[^18]

Tällaiset maailmanlopun näkymät tekevät itsestään täydellisen kohteen pilkalle. Kaiken kaikkiaan vuosi 2000, vaikka se onkin vaikuttava pyöreä luku, on vain satunnainen ilmiö kristillisestä kalenterista, kuten lännessä on omaksuttu. Muut kalenterit ja ajankäyttöjärjestelmät laskevat vuosisatoja ja vuosituhansia eri lähtöpisteistä. Esimerkiksi islamilaisen kalenterin mukaan jKr. 2000 on vuosi 1378. Niin tavallisen kuulostava vuosi kuin se vaan voi olla. Kiinalaisen kalenterin mukaan, joka toistuu joka kuusikymmentä vuotta, jKr. 2000 on vain jälleen yksi lohikäärmeen vuosi. Se on osa jatkuvaa sykliä, joka ulottuu vuosituhansia taaksepäin. Kuitenkin vuoden 2000 merkitystä ei ole pelkästään teologinen panostus. Sen tärkeys perustuu paitsi kristilliseen perinteeseen myös puolivuosisadan tietotekniikan rajoitteisiin. Niin kutsuttu Y2K- eli vuosi 2000 -ongelma, potentiaalisesti tuhoisa logiikkavirhe miljardeissa tietokoodin riveissä, voisi jäljitellä maailmanlopun tiloja sulkemalla teollisyhteiskunnan elintärkeät osat melkein tuhatvuosisadan keskiyössä. Monet tietokoneet ja mikrosuorittimet käyttävät ohjelmistoja, jotka on säilytetty ja kierrätetty tietokoneiden varhaisilta ajoilta, jolloin muistitila maksoi 600 000 dollaria per megatavu – arvokkaampaa kuin kulta. Säästääkseen kallista tilaa varhaisohjelmoijat seurasivat päivämääriä vain vuoden viimeiset kaksi numeroa. Tämä tapo kahden numeron päivämääräkenttien käyttämisestä siirtyi useimpiin pääaikataulietokoneiden ohjelmistoihin ja levisi laajasti myös henkilökohtaisiin tietokoneisiin sekä niin kutsuttuihin upotettuihin siruihin – mikrosuorittimiin, joita käytetään ohjaamaan melkein kaikkea, VCR:istä auton sytytysjärjestelmiin, turvajärjestelmiin, puhelimiin, puhelinverkon hallintajärjestelmiin, tehtaan, voimalaitoksen, öljynjalostamon, kemiantehtaiden, putkistojen ja paljon muun hallintaan. Näin kahden numeron kenttään lyhennettynä vuosi 1999 olisi "99". Ongelma on, mitä tapahtuu, kun vuonna 2000 tulee "00". Monet tietokoneet tulkitsevat sen vuonna 1900. Tämä saattaa tehdä mahdottomaksi, että monet korjaamattomat tietokoneet ja muut digilaitteet tunnistaisivat vuoden 2000 päivämääräkentissä.



Tuloksena syntyy valtava tietojen korruptoitumisen ongelma, joka vahingossa havainnollistaa uutta potentiaalista informaatiovaaraa. Information aikakaudella mahdolliset vastustajat pystyvät aiheuttamaan tuhoa laukaisemalla "logiikkapommeja", jotka sabotoivat olennaisten järjestelmien toimintoja korruptoimalla niiden toiminnan kannalta kriittiset tiedot.

Esimerkiksi sotaharjoituksena sinun ei tarvitsisi kaataa lentokonetta, jos pystyisit korruptoimaan sen turvalliseen toimintaan välttämättömät tiedot. Tietojen korruptoituminen voi tehdä melkein yhtä paljon kuin fyysiset aseet modernin yhteiskunnan toimintojen estämiseksi. Sen potentiaalisesti kauaskantoiset seuraukset käyvät itsestään selviksi, kun siitä miettii. Esimerkiksi Londonin *Mail* -lehti raportoi 14. joulukuuta 1997, että lentoyhtiöt ympäri maailman suunnittelivat perumaan satoja lentoja 1. tammikuuta 2000 peläten, että ilmatilan valvontajärjestelmät pettäisivät.[^19]

Mahdollisiin ongelmiin kuuluvat paitsi ilmatilan hallintajärjestelmät, myös lentokoneisiin sisäänrakennetut päivämääräherkät toiminnot. Boeingin mukaan monet lentokoneet vaativat Y2K-muutoksia. Monissa laitteissa voi ilmetä ongelmia, jos ne yrittävät tallentaa tapahtuman virheelliselle päivämäärälle. Fly-by-wireilla ja tietokonehallinnoiduilla järjestelmillä, jotka ohjaavat lentokoneita, voi olla häiriöitä, jos ne on ohjelmoitu päättelemään, että kriittistä huoltoa on viimeksi tehty vuonna 1900.

Logiikkajaksojen mahdollisesti tappavat palautumisvaikutukset, jotka sulkevat Y2K-yhteensopimattomat ohjausjärjestelmät, voisivat tehdä vuosituhannen vaihdoksesta muistettavan epämiellyttävistä syistä. Muista, että monet laitteet, jotka menevät virhesilmukkaan ja sammuvat, voivat vaikuttaa sinuun, vaikka olisit onnekas ettet löytäisi itseäsi levossa, kun uusi vuosituhat alkaa.

Olisi viisasta välttää onnettomuuksia, jotka johtuvat Y2K-yhteensopimattomista tahdistimista tai yksinkertaisesti humalassa olevista millenniaalisten juhlia viettävistä, sillä jos tahdistimet sammuvat, puhelinjärjestelmäkin saattaa epäonnistua – jolloin ambulanssi ei ehkä koskaan saavu. Ellet asu Brasiliassa tai Ukrainassa, olet tottunut nostamaan puhelimen tai laittamaan matkapuhelimen päälle ja saamaan automaattisesti valintanauhan. Onneksi sinun harvoin tarvitsee pohtia puhelinjärjestelmän teknisiä yksityiskohtia, mutta kävi ilmi, että puhelinverkon kytkimet ja reitittimet ovat erittäin päivämääräriippuvaisia. Kaikki yhteydet kirjataan päivämäärän ja ajan mukaan, mikä on ratkaisevan tärkeää puheluiden keston laskemisessa laskutusta varten. Jos satut soittamaan yhden minuutin puhelun 31. joulukuuta 1999 klo 11:59:30 ja klo 12:00:00 järjestelmä tulkitsee puhelusi kestävän negatiivisesti yli 99 vuotta, virhesilmukoita ja sammumisia on mahdollista. Vaikka pitkän matkan yhtiöt käyttävät suuria summia päivittääkseen kytkimensä vuodelle 2000 yhteensopiviksi – ja paikalliset palveluntarjoajat todennäköisesti tekevät samoin – jos vain muutamat pienemmät yritykset eivät onnistu täyttämään vaatimuksia ja menevät alas, koko verkko voi kärsiä. Olet onnekas, jos saat valintanauhan 1. tammikuuta 2000.

Kuten Y2K-asiantuntija Peter de Jager sanoi: "If we lose the ability to make a phone call, then we lose everything. We lose electronic fund transfers, we lose trading, we lose branch banking." Ja Y2K-ongelmien jatkoseuraukset voivat ulottua vielä sitä pidemmälle.

Tänä päivänä kukaan ei tiedä, kuinka laajalti olennaiset järjestelmät kaatuvat vuoden 2000 ongelman vuoksi. Upotettuja järjestelmiä, joita ei voi uudelleenohjelmoida vaan jotka täytyy vaihtaa, jos ne eivät toimi päivämääräherkällä tavalla, löytyy 1976 jälkeen valmistetuista korteista, kuorma-autoista ja busseista. (Ehkä et joudu onnettomuuteen, jos kuljet ajoneuvoilla, joita ajavat henkilöt, joilla on Y2K-yhteensopimattomat tahdistimet, koska heidän ajoneuvonsa eivät ehkä käynnisty.) Upotettuja järjestelmiä löytyy myös kaikentyyppisistä voimalaitoksista, vesi- ja viemärijärjestelmistä, lääkintälaitteista, sotilasvarusteista, lentokoneista, merellä sijaitsevista öljyalustoista, öljytankkereista, hälytysjärjestelmistä ja hisseistä. Vaikka monet mikroprosessorikokoonpanot eivät suorita päivämääräherkkiä toimintoja, ne voivat silti olla riippuvaisia kelloista, jotka saattavat olla Y2K-herkkiä niiden sisäisessä toiminnassa.

## MAINFRAMES AND THE Y2K TIME BOMB

Hallinnon ja suuryritysten laajamittaiset komentojärjestelmät, jotka sisältävät suuria transaktiomääriä mainframe-tietokoneilla, olivat alkuperäinen Y2K-ongelman huolenaihe. Koska ne toimivat suurissa koneissa, joiden suurin osa ohjelmistosta on vuosikymmeniä vanhaa ja pääosin yhteensopimatonta, alkuperäiset Y2K-hälytykset, joita Peter de Jager antoi 1990-luvun alussa, ovat keskittyneet pääasiassa siihen, että käyttöjärjestelmät päivitetään suurille, moniprosessorisille mainframeille.

Hän ilmaisi huolensa siitä, että COBOLia, vanhaa mainframe-kieltä, osaavia ohjelmoijia ei ehkä olisi tarpeeksi suorittamaan välttämättömiä korjauspäivityksiä ja korjauksia päivämääräherkälle koodille, vaikka jokainen yritys ja virasto, jolla olisi altis järjestelmä, olisi aloittanut kiireellisen korjausohjelman useita vuosia sitten. Koska näin ei ole tapahtunut, ja monet päivämääräherkkien tietojärjestelmien operaattorit ovat vasta alkaneet arvioida haavoittuvuuttaan, voidaan ennustaa suurella varmuudella, että monet mainframe-järjestelmät eivät ole valmiita toimimaan sujuvasti vuoden 2000 jälkeen.

Tämä on ehdottomasti vakava huolenaihe, sillä nykyaikaisen talouden rakenteessa tietokoneprosessoinnille ei ole todellista vaihtoehtoa. Suurin osa yrityksistä, jotka ovat tarpeeksi suuria vaatiakseen mainframe-kapasiteettia transaktioihinsa, on riippuvaisia transaktiomääristä, joita vanhanaikaiset 1800-luvun paperijärjestelmät eivät pysty hallitsemaan. Jos tällaiset yritykset joutuisivat palaamaan paperien kasaamiseen, ne käsittelisivät vain murto-osan normaalista transaktiomäärästään. Tällainen tuloshokki laskusuuresta liiketoiminnassa uhkaisi lähes kaikkien paitsi erittäin pääomavaraisten yritysten selviytymistä.

Lähes kaikki rahaan liittyvä – laskutus, hankinta ja palkkajärjestelmät, sekä varastonhallinta ja sääntelyn noudattaminen – menisi sekaisin. Jyrkkiä määriä dataa katoaisi, kun tietokoneet kaatuisivat tai purskaisivat virheellistä dataa Y2K-ongelman seurauksena. Joissakin tapauksissa voisi jopa olla siunauksena, jos järjestelmät kaatuisivat heti sen sijaan, että ne korruptoisivat tietonsa kertyvässä tahdissa, kunnes massiivinen toimintahäiriö herättäisi huomion ongelmaan. Mitä tiedostoille tapahtuisi, kun varmuuskopiointiohjelma kopioi 07/04/99 alun tiedostoja päivitykseen 01/04/00? Kuka tietää? Tulkitseeko tietokone tammikuun 4. päivän "1900" maksuna tehdyn vakuutussopimuksen merkkinä siitä, että sopimus on ollut maksukyvyttömänä vuosisadan ajan, jolloin se perutaan ja poistetaan tiedostosta? Pyrkivätkö pankkien ja rahoituslaitosten tietokoneet laskemaan sadan vuoden korot lainoista, jotka ulottuvat vuosituhannen vaihdokseen? Pystyvätkö pankkisi ja välittäjäfirmasi säilyttämään tarkat tilitiedot ja antamaan sinulle ajankohtaista pääsyä varoihisi? Nämä ovat vain muutamia mielenkiintoisia pulmia, joihin joudut Y2K-ongelman vuoksi.

> "Tämä on potentiaalisesti vuoden 2000 ongelman tuhoisimmasta osasta. Tämä ei ole se vaivalloisuus, jolloin palkkasi tulee muutamia päiviä myöhässä. Tämä on se verenvuodatukseen johtava osio."  
> – Dr. Leon Kappelman, Society For Information Managementin Year 2000 Working Groupin yhteispuheenjohtaja



Myös korkealla huolistasi tulee olla se, mitä tapahtuu, jos sähkö katkeaa Y2K-ongelmien vuoksi. Ilman sähköä edes suurin osa järjestelmistä, jotka eivät ole Y2K-vaurioituneita, lakkaavat toimimasta – esimerkiksi jääkaappisi, pakastimesi ja ehkä jopa lämmitysjärjestelmäsi. Y2K-yhteensopivuusongelmat saattavat vaikuttaa ydinvoimaloiden turvallisuuteen liittyviin sisäänpääsy- ja ohjaustoimintoihin. Esimerkiksi ydinlaitosten henkilökunta käyttää dosimetrejä, jotka mittaavat hänen laitoksessa ollessaan altistunutta säteilyannosta. Näitä laitteita analysoidaan säännöllisesti, ja altistustietoja säilytetään tietokonejärjestelmässä, joka hallitsee henkilöstön pääsyä laitokseen. Ilmeisesti, jos ohjaavia tietokoneita pettää, ne sotkevat kaikki monimutkaiset, turvallista toimintaa ja asianmukaista huoltoa varten suunnitellut ohjausjärjestelmät. Vielä tärkeämpää on kuitenkin se, että YdinSääntelytoimikunnan muistio huomauttaa, että monet “ei-turvallisuuteen liittyvät, mutta tärkeät tietokonepohjaiset järjestelmät – pääasiassa tietokannat ja laitoksen toimintaan välttämättömät tietojen keruujärjestelmät” ovat päivämääräherkkiä.

Perinteiset voimalaitokset eivät ole vähemmän alttiita Y2K-häiriöille. Toisaalta hiilivoimalaitokset ovat herkkiä pintakuljetusjärjestelmän häiriöille, jotka toimittavat hiiltä kattiloihin. Vuoden 1997–1998 talvikauden lämmityskaudella hiilivoimalaitoksia pyörittäneiden operaattorien oli pakko joidenkin yksittäisten kohteiden osalta vähentää tuotantoaan, koska länsihiiltä kuljettavien rautatiejuna‑toimitusten tahti hidastui Southern Pacificin ja Union Pacificin rautatiejärjestelmien fuusion seurauksena. Ongelma ilmeni, koska kummankin rautatien käyttämissä tietokonepohjaisissa ohjaus- ja lähetysjärjestelmissä oli yhteensopimattomuuksia. Union Pacificin edustajan mukaan näiden kahden järjestelmän integrointi muuttui “painajaiseksi”, huolimatta siitä, että Union Pacific Technologiesia on pidetty teollisuuden johtajana tietokoneistetun kuljetusohjausjärjestelmän kehittämisessä. Ohjelmointiongelmien seurauksena rautatieyritys ei pystynyt tarkasti seuraamaan rahtvaunujensa liikkeitä. Union Pacificin epäonnistuminen Southern Pacificin järjestelmien yhdistämisessä on huono ennusmerkki siitä, mitä voi tapahtua, kun Y2K-logiikan aikapoikittimet häiritsevät liikennettä, sähköntuotantoa ja muita talouden osa-alueita.

Suurin huoli sähköverkostamme kuitenkin johtuu siitä, että koko järjestelmä on alttiina herkälle tietokonevalvonnalle ja ohjaukselle, jonka avulla siirretään sähköä ylijäämäntuotantoa tekeviltä alueilta niille, joilla on vajetta. Tätä prosessia on seurattava tarkasti tietokoneiden avulla, jotta vältetään jännitepiikit ja järjestelmäviat. Kaikki sähkön siirrot kirjataan tarkkojen aikaleimojen mukaisesti, aivan kuten puhelinyhteyden yhteydessä kirjattaisiin sen kesto. Vaikka yhteyksien muodostamiseen käytetään kestäviä mekaanisia releitä, näitä ohjataan tietokonejärjestelmillä. Nämä tietokoneohjaukset, jotka ovat olennaisia kuormantasaamisessa, saattavat pettää samasta syystä kuin puhelinverkot. Itse asiassa Pohjois-Amerikan sähkökuormanjakelun ohjausjärjestelmät on verkotettu yhteen T-1-linjoilla ja puhelinmikroaaloyhteyksillä, joten jos puhelinverkko pettää, voit odottaa myös sähkökatkoa. Ja muistathan, kuten Kanadassa tammikuussa 1998 koettiin, kun sähkö katkeaa laajalla alueella, järjestelmän käynnistäminen uudelleen on todellinen haaste – sähkökatkon kesto voi olla erityisen pitkä.

## Y2K JA YDINASEVARUSTO

Modernien talouksien kohdalla, jos sähkö katkeaa keskellä talvea, se aiheuttaa huomattavia häiriöitä ja voi uhata terveyttä, erityisesti niiden kohdalla, jotka ovat riippuvaisia sähkölämmöstä ja lääketieteellisestä laitteistosta. Mutta pahimmassa skenaariossa tilanne on vielä pahempi. John Koskinenin, joka johtaa President Clintonin Y2K Conversion Councilia, mukaan Yhdysvaltain sotilasasevarustot saattavat lakata toimimasta täsmälleen keskiyöllä 31. joulukuuta 1999. Vaikka hän ei halua aiheuttaa tarpeetonta paniikkia, Koskinen lisää: "Siitä on aihetta huoleen." Yksi huoli ydinmiinoista on, että "jos tiedot eivät toimi, ne saattavat oikeasti laukaistua."

Tietenkin tämä huoli koskisi yhtä voimakkaasti – tai voimakkaammin – Venäjän ydinmiinoja. Venäjän konkurssi on tehnyt Y2K-yhteensopivuuspäivityksistä vielä ongelmallisempia kuin Yhdysvalloissa, ja on olemassa viitteitä siitä, että Venäjä ei vielä ota Y2K-muutosta vakavasti. Vaikka toivoisi, ettei mitään onnettomia laukaisuja tapahtuisi, ei pitäisi olla epäilystäkään siitä, että vuosituhannen vaihtuminen voi pahentaa maailmanlaajuista epävarmuutta, edes vain siksi, että monien maiden sotilaalliset viestintäjärjestelmät eivät ehkä toimi normaalisti. Kuten Koskinen toteaa, "Jos istut maassa ja yhtäkkiä et pysty selvittämään, mitä on tapahtumassa, ja yhteytesi eivät toimi hyvin, hermostut vieläkin enemmän." Lisää siis tämä omaan huolien listalle Y2K:n osalta. Logiikan aikapoikittimet saattavat aiheuttaa tilanteen, jossa aidosti räjähtävät panssarimissiot laukaistaan – se korostaa tietoviisoinnin sodankäynnin vaaroja keskitettyjä komentojärjestelmiä kohtaan.

Jos terroristit haluavat iskeä mihin tahansa keskitettyyn järjestelmään, he saattavat valita päivämääräksi 31. joulukuuta 1999, koska se on aika, jolloin monien järjestelmien haavoittuvuus on suurimmillaan. Ei vain, että viestintä on äärimmäisen kuormittunutta, ja on mahdollista, että sähkö katkeaa, ajoneuvot eivät käynnisty, hätäkeskuspalvelut – kuten poliisi, palokunta ja ambulanssi (911) – eivät toimi, vaan monet muut toiminnot, joita pidät itsestäänselvyyksinä, kuten ilmakontrolli, lakkaavat toimimasta. Ilman sähköä hanavesi ei virtaa, viemärijärjestelmät epäonnistuvat ja liikennevalot saattavat sammua. Todellisen kuljetusjärjestelmän romahtamisen muutaman tunnin sisällä kauppojen ruoka loppuisi ostettavaksi (tai jopa ryöstettäisiin). Viimeaikaisten amerikkalaisten kaupunkien kokemusten perusteella voidaan olettaa, että ilman sähköä, vettä, lämpöä monille, valoja ja toimivia hätäpalveluja – kuten poliisia ja palokuntaa – samalla kun viestintä hajoaa – ei ole siviilisaatiota.

„Emme ole se, mitä olemme olleet, vaan aloitamme olemaan jotain muuta.”  
– Joachim de Fiore

Ennustukset uuden vuosituhannen tuhosta eivät välttämättä perustu kristilliseen teologiaan, mutta ne mahtuvat hyvin Joachim de Fioreen millenniaalisessa perinteessä, jonka meditaatiot vakuuttivat hänet siitä, että Kristus oli vain “historian toinen sarana” ja että toinen saranan tulisi avautua. Näin väittää filosofi Michael Grosso, joka ehdottaa, että tietovallankumous ohjaa ihmiskuntaa kohti länsimaisen maailman profeetallisen vision toteutumista. Hän kutsuu tätä ilmiötä “technocalypseksi.” Riippumatta siitä, vaikuttaako teknologian kehitystä millenniaaliset visiot, Y2K-ilmiö on predominantin länsimaisen ajankuvittelun artefakti. Outoinkin tavalla se voi täydentää unelmia, haaveita ja näkyjä – tai näkyjen numeerisia tulkintoja, kuten Newtonin selitykset Danielin ennustuksista. Nämä intuitiiviset harppaukset lähtevät näkökulmasta, jossa Kristuksen syntymää pidetään historian keskeisenä tapahtumana, ja niitä vahvistaa suurten pyöreiden lukujen psykologinen voima, jonka jokainen kauppias tunnistaa vaikuttavana. Ajamme kaksi tuhattain vuotta ei voi olla muuta kuin intuitiivisten ihmisten mielikuvituksen keskipiste.

Modernien talouksien kannalta, jos sähkö katkeaisi keskellä talvea, se aiheuttaisi merkittäviä häiriöitä ja voisi uhata terveyttä, erityisesti niiden osalta, jotka ovat riippuvaisia sähkölämmöstä ja lääketieteellisistä laitteista. Mutta pahimmassa skenaariossa tilanne on vielä pahempi. John Koskinenin mukaan, joka johtaa President Clintonin Y2K Conversion Councilia, Yhdysvaltain sotilasasevarustot saattavat lakata toimimasta täsmälleen keskiyöllä 31. joulukuuta 1999. Vaikka hän ei halua aiheuttaa tarpeetonta paniikkia, Koskinen lisää: "Siitä on aihetta huoleen." Yksi huoli ydinmiinoista on, jos tiedot eivät toimi ja ne oikeasti laukaistaan.

Tietenkin tämä huoli koskisi yhtä voimakkaasti – tai voimakkaammin – Venäjän ydinlöyjää. Venäjän konkurssi on tehnyt Y2K-yhteensopivuuspäivityksistä vielä ongelmallisempia kuin Yhdysvalloissa, ja on viitteitä siitä, että Venäjä ei vielä ota Y2K-muutosta vakavasti. Vaikka toivoisi, ettei mitään tahattomia laukaisuja tapahtuisi, ei saisi olla epäilystäkään siitä, että vuoden 2000 vaihtuessa monet maiden sotilaalliset viestintäjärjestelmät saattavat toimia poikkeuksellisesti. Kuten Koskinen toteaa, "Jos istut maassa ja yhtäkkiä et pysty täysin selvittämään, mitä tapahtuu, ja viestintäsi ei toimi yhtä hyvin, hermostut entisestään." Lisää siis tämä huoli Y2K-askelistallesi. Logiikan aikapoikittimet saattavat laukaista aidosti räjähtävien panssarimissioiden laukaisun – se korostaa tiedonvälityskamppailun vaaroja keskitettyjen komentojärjestelmien kohdalla.

Jos terroristit haluavat iskeä mihin tahansa keskitettyyn järjestelmään, he saattavat valita päivämääräksi 31. joulukuuta 1999, koska se on aika, jolloin monien järjestelmien haavoittuvuus on suurimmillaan. Viestintä on silloin parhaimmillaan äärirajoilla, mahdollisesti sähkö pettää, ajoneuvot eivät käynnisty, hätäpalvelut – kuten poliisi, palokunta ja ambulanssi – eivät toimi, ja monia oletusasenteisia toimintoja, kuten ilmakontrollia, voi lakata toimimasta. Ilman sähköä hanavesi ei virtaa, viemärijärjestelmät epäonnistuvat ja liikennevalot sammuvat. Todellisen kuljetusjärjestelmän romahtamisen muutaman tunnin sisällä kauppojen ruokavarastot hupenevat (tai niitä ryöstetään). Viimeaikaisten kokemusten perusteella amerikkalaisissa kaupungeissa voidaan olettaa, että ilman sähköä, vettä, lämpöä, valoa ja toimivia hätäpalveluja – ja kun yhteys hajoaa – siviilisaatio romahtaa.

Aivan kuin kirjoittaja voisi helposti näyttää nämä tuhon ennustukset naurettavina ilman, että edes käsitellään epäselviä ja kiistanalaisia teologisia käsityksiä Tuomiosta ja Viimeisestä Tuomiosta, jotka antavat näille visioille suurimman osan niiden voimasta. Mielenkiintoista on kuitenkin se, että Y2K-tietokonevika ylittää ne aritmeettiset virheet, jotka muuten saattaisivat vähentää vuoden 2000 merkitystä jopa kristillisessä viitekehyksessä. Vuosi 2000:lla on potentiaalia muodostua käännekohdaksi historian seuraavalle vaiheelle, yksinkertaisesti siksi, että se tuo uuden vuosituhannen saapumisen esiin. Tiukan logiikan mukaan seuraava vuosituhat ei ala ennen vuotta 2001. Vuosi 2000 olisi vain kaksituhatta vuotta Kristuksen syntymästä – tai niin se olisi, jos Kristus olisi syntynyt kristillisen ajan ensimmäisenä vuotena. Hän ei ollut. Vuonna 533, kun Kristuksen syntymä korvasi Rooman perustamispäivän Länsimaisen kalenterin mukaan, uutta käytäntöä esittelneet munkit laskivat Kristuksen syntymän väärin. Nyt on hyväksytty, että hän syntyi vuonna 4 eaa. Tämän perusteella täysi kaksituhatta vuotta hänen syntymästään täyttyy jossain vaiheessa vuonna 1997. Tämän vuoksi Carl Jungin näennäisesti outo käynnistymispäivä Uuden Ajan alulle on ymmärrettävä.

«Emme ole se, mitä olemme olleet, vaan aloitamme olemaan jotain muuta.»  
– Joachim de Fiore

Filosofi Michael Grosso väittää, että Tietovallankumous ohjaa ihmiskuntaa kohti länsimaisen maailman profeetallisen vision toteutumista – hän kutsuu tätä “technocalypseksi.” Riippumatta siitä, vaikuttaako teknologian kehitystä millenniaaliset visiot, Y2K-ilmiö on predominantin länsimaisen ajankuvitelman artefakti. Outoinkin tavalla se voi täydentää unelmia, haaveita ja näkyjä tai näiden numeerisia tulkintoja, kuten Newtonin selityksiä Danielin ennustuksista. Nämä intuitiiviset harppaukset alkavat näkökulmasta, joka pitää Kristuksen syntymää historian keskeisenä tapahtumana, ja ne vahvistuvat suurten pyöreiden lukujen psykologisella voimalla, jonka jokainen kauppias tunnistaa vaikuttavana. Ajanjaksonamme kaksi tuhatta vuotta ei voi olla muuta kuin keskipiste intuitiivisten ihmisten mielikuvitukselle.



Naurakaa, jos haluatte, mutta emme halveksi tai hylkää intuitiivisia ymmärryksiä historiasta. Vaikka argumenttimme perustuu logiikkaan – ei tuloihin – olemme vaikuttuneita inhimillisen tietoisuuden profeetallisesta voimasta. Kerta toisensa jälkeen se lunastaa hullujen, selvänäkijöiden ja pyhien näkemykset. Näin voi olla myös vuoden 2000 murroksessa. Lännen mielikuvissa kauan vakiintuneena päivämääränä oleva tämä päivä näyttää olevan se käännekohta, joka ainakin osittain vahvistaa, että historiassa on kohtalo. Emme pysty selittämään, miksi näin pitäisi olla, mutta olemme silti vakuuttuneita siitä.

Intuitionaamme on, että historiassa on kohtalo ja että vapaa tahto sekä determinismi ovat kaksi versiota samasta ilmiöstä. Ne inhimilliset vuorovaikutukset, jotka muovaavat historiaa, käyttäytyvät ikään kuin niitä ohjaisi jokin kohtalon voima. Samoin kuin tiheä elektronikaasu eli elektroniplasma kehittyy monimutkaisena järjestelmänä, niin myös ihmiset. Elektronien yksilöllisen liikkumisen vapaus osoittautuu yhteensopivaksi erittäin organisoituneen kollektiivisen käyttäytymisen kanssa. Kuten David Ohm totesi elektroniplasman osalta, ihmishistoria on "erittäin organisoitunut järjestelmä, joka käyttäytyy kokonaisuutena."

Maailman toiminnan ymmärtäminen edellyttää realistisen intuitiotavan kehittämistä siitä, miten ihmiskunta tottelee luonnonprosessien matemaattisia lakeja. Todellisuus ei ole lineaarista, mutta useimpien odotukset eivät ole sitä. Muutosten dynamiikan ymmärtämiseksi on tunnistettava, että ihmiskunta – kuten muutkin luonnon monimutkaiset järjestelmät – on sykleihin ja katkoksellisuuksiin jaettu. Tämä tarkoittaa, että tiettyjen historian piirteiden on taipumus toistua, ja tärkeimpien muutosten, kun ne tapahtuvat, voi olla äkillinen luonnos asteittaisen sijaan.

Ihmiselämän läpi kulkevissa sykleissä yksi salaperäinen viisisatakautinen sykli näyttää merkitsevän merkittäviä käännekohtia länsimaisen sivilisaation historiassa. Kun vuosi 2000 lähestyy, meitä kummittelee outo seikka, että jokaisen viidenettömän vuosisadan viime vuosikymmen on merkinnyt syvällistä murrosta länsimaisessa sivilisaatiossa – sellainen kuoleman ja jälleensyntymän malli, joka määrittelee uuden sosiaalisen järjestäytymisen vaiheen aivan kuten kuolema ja syntymä erottavat ihmissukupolvien sykliä. Tämä on totta ainakin siitä lähtien, kun kreikkalainen demokratia nousi Cleisthenesin perustusuudellisten uudistuskauden myötä vuonna 508 eaa. Seuraavat viisi vuosisataa olivat antiikin talouden kasvun ja intensiivistymisen aikaa, joka huipentui Kristuksen syntymään vuonna 4 eaa. Se oli myös aika, jolloin antiikin talouden suurin vauraus vallitsee, ja silloin korkotasot olivat alhaisimmillaan ennen modernia aikaa.

Seuraavien viiden vuosisadan aikana vauraus alkoi vähitellen kutistua, mikä johti Rooman imperiumin romahtamiseen myöhään viidennellä vuosisadalla ja joka kuvaili William Playfair tiivistämällä näin: "Kun Rooma oli suuruutensa huipulla... nähdään, että se oli Kristuksen syntymän aikaan, toisin sanoen Augustus-kauden aikana, ja samalla tavoin huomataan, että se alkoi vähitellen laskemaan arvoaan vuoteen 490 asti." Juuri silloin viimeiset legioonat hajoivat, ja Länsi-maailma uposi pimeään aikaan.

Seuraavien viiden vuosisadan aikana talous kuihtui, kaupan pitkän matkan vaihto pysähtyi, kaupungit vähenivät asukasluvultaan, raha katosi kierrosta ja taide sekä lukutaito lähes hävisivät. Rooman imperiumin romahtamiseen lännessä liittynyt tehokkaan lain puutetta johtanut järjestelmä sai aikaan primitiivisempiä tapoja erimielisyyksien ratkaisemiseksi. Verenvuodat alkoi saada merkitystä viidennen vuosisadan lopulla. Ensimmäinen kirjattu koetinkappaleprosessi tapahtui juuri vuonna 500.

Juuri tuhannen vuoden takaisessa olevassa ajassa kymmenennen vuosisadan viime vuosikymmen todisti jälleen "märkyttävän mullistuksen sosiaalisissa ja taloudellisissa järjestelmissä." Ehkä yksi tuntemattomimmista näistä siirtymistä – feodaalivallankumous – sai alkunsa täysin kaaoksen ja poliittisen myllerryksen aikaan. Guy Bois, Pariisin yliopiston keskiaikahistorian professori, teoksessaan The Transformation of the Year One Thousand väittää, että tämä ristiriita kymmenennen vuosisadan lopussa merkitsi antiikin instituutioiden jäänteiden täydellistä romahtamista ja uuden järjestelmän nousua anarkian keskeltä. Raoul Glaberin sanojen mukaan "sanottiin, että koko maailma, yhtenäisesti, ravistautui antiikin repeämistä." Uusi järjestelmä, joka yhtäkkiä nousi, mahdollisti talouskasvun hitaan uudelleen heräämisen. Nyt viisi vuosisataa, joita kutsutaan keskiajaksi, näyttelivät rahallistumisen ja kansainvälisen kaupan uudelleensyntymää yhdessä aritmetiikan, lukutaidon ja ajan tuntemuksen uudelleen löytämisen kanssa.

Sitten, vuosisadan viime vuosikymmenessä 1400-luvulla, koettiin jälleen käännekohta. Juuri silloin Eurooppa nousi demografisesta vajauksesta, jonka aiheutti Musta surma, ja alkoi lähes välittömästi osoittaa valtaansa maailman muualla. "Ampumapuheeräjäännös", "renessanssi" ja "uskonpuhdistus" ovat nimiä, jotka annetaan tälle siirtymälle, joka käynnisti modernin aikakauden. Se ilmoitettiin näyttävästi, kun Charles VIII hyökkäsi Italiaan uusien pronssikanuunoiden kera. Se merkitsi maailman avoimuutta, jota kirkasti Columbusin vuoden 1492 matka Amerikkaan. Tämä Uuden maailman avaaminen käynnisti työntelyn kohti ihmiskunnan historiassa esiintyvän dramaattisimman talouskasvun aikaa. Se sisälsi fysiikan ja tähtitieteen mullistumisen, joka johti modernin tieteen syntyyn. Ja sen ajatukset levisivät laajasti uuden painokoneen teknologian myötä.

Nyt seisomme jälleen uuden tuhannen vuoden muutoksen kynnyksellä. Teollisen aikakauden perintönä elävät suuret komentovalvontajärjestelmät saattavat romahtaa kuin yksirottainen kyläajan hihna tuhannen vuoden kesköstä. Olipa Y2K-looginen pommi sitten se, joka välittömästi saattaa aiheuttaa romahtavan tilan teollisessa yhteiskunnassa, sen päivät ovat laskettuja. Odotamme, että tietoyhteiskunnan saapuminen mullistaa maailman täysin tavoilla, joita tämä kirja pyrkii selittämään. Olisit täysin oikeutettu epäilemään tätä, sillä mikään tuhannen vuoden jaksossa kahdesti itsensä toistava sykli ei ole osoittanut tilastollisesti merkittävää toistuvuutta. Itse asiassa jopa paljon lyhyemmät syklit ovat herättäneet taloustieteilijöiden skeptisyyttä, jotka vaativat tilastollisesti vakuuttavampaa todistusaineistoa. "Professor Dennis Robertson kirjoitti kerran, että meidän olisi odotettava muutama vuosisata, ennen kuin voimme olla varmoja" nelivuotisista ja kahdeksan–kymmenvuotisista kauppasykleistä. Tällä standardilla professor Robertsonin olisi joutunut pidättäytymään arvostelusta noin kolmekymmentä tuhatta vuotta, jotta varmistettaisiin, ettei viisisatakautinen sykli ole tilastollinen sattuma. Me olemme vähemmän dogmaattisia tai valmiimpia tunnustamaan, että todellisuuden mallit ovat monimutkaisempia kuin useimpien taloustieteilijöiden staattiset ja lineaariset tasapainomallit.

Uskomme, että vuoden 2000 saapuminen merkitsee jotain enempää kuin vain yhtä yhteiskunnallista ajanjaksoa loputtoman ajan jatkumon kohdalla. Uskomme sen olevan käännekohta, Old Worldin ja tulevan New Worldin välillä. Teollinen aikakausi on nopeasti päättymässä, ja ironisesti sen loppumista saattaa kiihdyttää se, että varhaisen tietokonemuistin hinta oli niin korkea, että se kannusti laajamittaiseen kahden numeron päivämääräkenttien käyttöönottoon. Kun Hallerithin reikäkortit pystyivät käsittelemään vain kahdeksaa merkkiä, päivämäärien lyhentäminen tuntui järkevältä. Vastoin varhaisten ohjelmoijien odotuksia päivämääräkentän lyhentäminen kesti neljä vuosikymmentä tuhannen vuoden loppuun asti – tahattomana loogisena pommina, joka saattoi tuhota suuren osan teollisen yhteiskunnan osista. Yhdysvaltain hallituksen Office of Management and Budget kuvaili ongelmaa raportissaan "Getting Federal Computers Ready for 2000", joka on päivätty 7. helmikuuta 1997. OMB: n mukaan, ellei tietokoneita korjata tai vaihdeta, ne epäonnistuvat vuosisadan vaihtumalla yhdellä kolmesta tavalla: ne hylkäävät lailliset syötteet tai laskevat virheellisiä tuloksia, tai ne yksinkertaisesti eivät käynnisty. Nämä kolme lopputulosta yhdessä voisivat lamauttaa teollisen yhteiskunnan. Massatuotannon teknologia on tuomassa tilalleen uuden miniatyyrisaavutusteknologian joka tapauksessa. Lähiaikainen kriisi vain nopeuttaa prosessia. Uuden tietotekniikan myötä on synnyttänyt uusia epälineaarisen dynamiikan tieteitä, joiden hämmästyttävät johtopäätökset ovat vielä kutoutumatta kokonaisvaltaiseksi maailmankatsomukseksi. Elämme tietokoneiden aikaa, mutta unelmamme vielä kutovat kutojankudoksen päällä. Jatkamme edelleen teollisuuden metaforien ja ajatusten varassa. Poliitikkamme jakautuu yhä teollisuuden oikealle ja vasemmalle, kuten ajattelijat kuten Adam Smith ja Karl Marx karttoivat – jotka kuolivat ennen kuin melkein kukaan nykyään elävistä syntyi. Teollinen maailmankuva, johon sisältyvät teollisen tieteen toimintaperiaatteet, on yhä koulutettujen mielipiteiden "järkevän intuition" perusta. Teesimme on, että teollisen aikakauden "järkevä arkikäsitys" ei enää päde monilla alueilla, kun maailma muuttuu.

Uskomme, että vuoden 2000 saapuminen merkitsee enemmän kuin vain vielä yhtä kätevää jakajaa loputtomassa ajan jatkumossa. Uskomme, että se tuleekin olemaan käännekohta vanhan ja tulevan uuden maailman välillä. Teollinen aikakausi on nopeasti ohi, ja sen katoaminen saattaa ironisesti kiihtyä juuri siksi, että alkuperäisen tietokonemuistin hinta oli niin korkea, että se kannusti laajamittaista kahden numeron päivämääräkenttiä. Kun Hallerithin reikäkorteissa oli tilaa vain kahdeksalle merkille, päivämäärien lyhentäminen tuntui järkevältä. Varhaisten ohjelmoijien odotuksia vastaan tämä lyhennys säilyi neljä vuosikymmentä tuhannen vuoden loppuun asti, tahattomana loogisena pommina, joka saattoi tuhota suuren osan teollisesta yhteiskunnasta. Yhdysvaltain hallituksen Office of Management and Budget kuvaili ongelmaa raportissaan "Getting Federal Computers Ready for 2000" (7. helmikuuta 1997). OMB: n mukaan, ellei tietokoneita korjata tai vaihdeta, ne epäonnistuvat vuosisadan vaihtuessa kolmella tavalla: ne hylkäävät lailliset syötteet, laskevat virheellisiä tuloksia tai yksinkertaisesti eivät käynnisty. Nämä yhdistettyinä voisivat lamauttaa teollisen yhteiskunnan. Massatuotannon teknologia on määräytymässä räikeästi ohimenevän uuden miniatyyrisaavutusteknologian alla. Lähiaikainen kriisi vain nopeuttaa prosessia. Uuden tietotekniikan myötä on syntynyt epälineaarisen dynamiikan uusi tiede, jonka hämmästyttävät johtopäätökset ovat vasta kudottavana eri lankana kokonaisvaltaiseksi maailmankuvaksi. Elämme tietokoneiden aikaa, mutta unelmamme kutovat yhä vanhan kudontakoneen päällä. Jatkamme teollisuuden metaforien ja ajatusten varassa. Politiikkamme edelleen jakautuu teollisuustyön oikealle ja vasemmalle, kuten ajattelijat kuten Adam Smith ja Karl Marx – joiden elinaikoja lähes kukaan nykyään elävistä ei edes osaa kuvitella – ovat määritelleet. Teollinen maailmankuva, joka sisältää teollisen tieteen toimintaperiaatteet, on yhä koulutettujen yleisen "järkevän intuition" perusta. Teesimme on, että teollisen aikakauden "järkevä arkikäsitys" ei enää päde monilla aloilla, kun maailma muuttuu.

Me uskomme, että vuoden 2000 saapuminen merkitsee käännettä enemmän kuin vain yhtä kätevää osiota loputtoman ajan continuumissa. Uskomme sen olevan käännekohta, jonka myötä siirrymme vanhasta maailmasta kohti uutta. Teollinen aikakausi on nopeasti ohi, ja sen loppua saatetaan ironisesti nopeuttaa se, että varhaisen tietokonemuistin hinta oli niin korkea, että se kannusti laajalti käyttämään vain kahta numeron päivämääriä. Kun Hallerithin reikäkorteissa oli vain kahdeksan merkkiä, päivämäärien lyhentäminen vaikutti järkevältä. Vastoin alkuohjelmoijien odotuksia tämä lyhennys kesti neljä vuosikymmentä tuhannen vuoden loppuun asti, tahattomana loogisena pommina, joka voisi tuhota suuren osan teollisesta yhteiskunnasta. Yhdysvaltain hallituksen Office of Management and Budget kuvaili ongelmaa raportissaan "Getting Federal Computers Ready for 2000" (7. helmikuuta 1997), ja totesi: "Ellei niitä korjata tai vaihtaa, tietokoneet epäonnistuvat vuosisadan vaihtuessa kolmella tavalla: ne hylkäävät lailliset syötteet, laskentatulokset ovat virheellisiä tai ne eivät yksinkertaisesti käynnisty." Näiden kolmen lopputuloksen yhdistelmä voisi lamauttaa teollisen yhteiskunnan. Massatuotannon teknologia on määräytymässä uuden miniatyyrisaavutusteknologian varjossa; lähiaikainen kriisi vain nopeuttaa prosessia. Uuden informaatioteknologian myötä on syntynyt epälineaarisen dynamiikan tiede, jonka hämmästyttävät johtopäätökset ovat vasta kutoutumatta osaksi kokonaisvaltaista maailmankuvaa. Elämme tietokoneiden aikaa, mutta unelmamme vielä kutovat kutojankoneen päällä. Elämme edelleen teollisuuden metaforien varassa. Politiikkamme jakautuu yhä teollisuuden oikealle ja vasemmalle, kuten esimerkiksi Adam Smithin ja Karl Marxin määrittelemät ajattelijat – jotka kuolivat ennen kuin lähes kukaan nykyään elävistä syntyi. Teollinen maailmankuva, joka sisältää teollisen tieteen toimintaperiaatteet, on yhä koulutettujen yleinen "järkevän intuition" perusta. Teesimme on, että teollisen aikakauden "järkevä arkikäsitys" ei enää päde monilla alueilla, kun maailma muuttuu.

Uskomme, että vuoden 2000 saapuminen merkitsee enemmän kuin vain mukavan erottimen loputtoman ajan continuumissa. Uskomme sen olevan käännekohta vanhan ja tulevan uuden välillä. Teollinen aikakausi on nopeasti päättymässä, ja ironisesti sen loppua voi nopeuttaa se, että varhaisen tietokonemuistin hinta oli niin korkea, että se kannusti laajalti kahden numeron päivämääräkenttiä. Kun Hallerithin reikäkortit pystyivät käsittelemään vain kahdeksaa merkkiä, päivämäärien lyhentäminen vaikutti järkevältä. Vastoin alkuohjelmoijien odotuksia tämä lyhennys kesti neljä vuosikymmentä tuhannen vuoden loppuun asti – tahattomana loogisena pommina, joka voisi tuhota suuren osan teollisesta yhteiskunnasta. Yhdysvaltain hallituksen "Getting Federal Computers Ready for 2000" -raportti (7. helmikuuta 1997) totesi, että ellei tietokoneita korjata tai vaihtaa, ne epäonnistuvat vuosisadan vaihtuessa kolmella tavalla: ne hylkäävät lailliset syötteet, laskentatulokset ovat virheellisiä tai ne eivät yksinkertaisesti käynnisty. Nämä kolme yhdessä voisivat lamauttaa teollisen yhteiskunnan. Modernin tietotekniikan myötä on kuitenkin tullut uusi miniatyyrisaavutusteknologia, joka uhkaa korvata massatuotannon tekniikat – ja mahdollinen lyhytaikainen kriisi vain nopeuttaa tätä prosessia. Uuden tietotekniikan myötä on syntynyt epälineaarista dynamiikkaa koskeva tiede, jonka hämmästyttävät johtopäätökset ovat vielä kutoutumatta osaksi kokonaisvaltaista maailmankuvaa. Elämme tietokoneiden aikaa, mutta unelmamme vielä kutovat kutojankoneen päällä. Emme ole irti teollisuutta koskevista metaforistamme. Politiikkamme vielä jakautuu teollisuuden oikealle ja vasemmalle, kuten Adam Smithin ja Karl Marxin kaltaiset ajattelijat – jotka kuolivat ennen kuin lähes kuka nykyään elävistä syntyi. Teollinen maailmankuva, joka sisälsi teollisen tieteen periaatteet, on yhä koulutettujen "järkevän intuition" perusta. Meidän näkemyksemme mukaan teollisen aikakauden "järkevä arkikäsitys" ei enää sovellu monille aloille, kun maailma muuttuu.

Yli kahdeksankymmentäviisi vuotta siitä päivästä vuonna 1911, jolloin Oswald Spengleria valtasi intuitio tulevasta maailmansodasta ja "Lännen rappiosta", mekin näemme, että "*historinen vaiheenvaihto* tapahtuu... siinä pisteessä, joka sille oli ennalta määrätty satoja vuosia sitten."[^26] Kuin Spengler, näemme Lännen sivilisaation väistämättömän kuoleman ja sen myötä sen maailmanjärjestyksen romahtamisen, joka on hallinnut viimeisen viiden vuosisadan ajan siitä lähtien, kun Columbus purjehti länteen avatakseen contactin Uuteen Maailmaan. Mutta toisin kuin Spengler, me näemme uuden vaiheen syntymän Lännen sivilisaatiossa tulevan vuosituhannen aikana.

[^1]: Danny Hillis, "The Millennium Clock," Wired, Special Edition, Fall 1995, p.48.

[^2]: Ericka Cheetham, The Final Prophecies of Nostradamus (New York: Putnam,1989), p.424.

[^3]: Dr. Edward Yardeni, Year 2000 Recession: "Prepare for the worst. Hope for the best," Version 5.0, May 13, 1998, B1.2.

[^4]: Michael Grasso, The Millenium Myth: Love and Death at the End of Time, Wheaton, Illinois: Quest Books, 1995.

[^5]: Johan Huizinga, The Waning of the Middle Ages, trans. E Hopman (London: Penguin Books, 1990), p.172.

[^6]: Marshall McLuhan, Understanding Media, New York: Signet, 196, p. 19.

[^7]: James George Frazer, The Golden Bough: A Study in Magic and Religion (New York: Macmillan, 1951), p.105.

[^8]: For more detail about fragmented sovereignties as a precursor and alternative to the nationstate, see Charles Tilly, Coercion, Capital and European States AD 990-1992 (Oxford: Blackwell, 1993).

[^9]: The German GPI index stood at 33.20 on December 31, 1948, and 112.90 on June 30, 1995, which represents a compound annual depreciation of 2.7 percent. The U.S. CPI stood at 24 on December31, 1948, and 152.50 on June 30, 1995. The cumulative U.S. inflation was 635 percent for the period.

[^10]: Janet L. Abu-Lughod, Before European Hegemony: The World System A.D.1250-1350 (Oxford: Oxford University Press, 1991), s. 62.

[^11]: Jack Cohen and Ian Stewart, The Collapse of Chaos (New York: Viking, 1994).

[^12]: Katso James Dale Davidson and Lord William Rees-Mogg, *The Great Reckoning*, 2. painos (New York: Simon & Schuster, 1993), s. 53.

[^13]: Frederic C. Lane, "Economic Consequences of Organized Violence," The Journal of Economic History, vol. 18, no. 4 (joulukuu 1958), s. 402.

[^14]: Nicholas Colehester, "Goodbye NationState, Hello . . . What?," New York Times, 17. heinäkuuta 1994, s. E17.

[^15]: Norman Macrae, "Governments in Decline," Cato Policy Report, heinä-/elokuussa 1992, s. 10.

[^16]: Arthur C. Clarke, Profiles of the Future: An Enquiry into the Limits of the Possible (London: Victor Gollancz Ltd., 1962), s. 13.

[^17]: Ibid.

[^18]: A. T. Mann, Millennium Prophecies: Predictions for the Year 2000 (Shafiesbury, England: Element Books, 1992), s. 88, 112, 117.

[^19]: Yardeni, op. cit., s. 45.

[^20]: Viitattu teoksesta Frooso, op. cit., s. 40.

[^21]: Ibid

[^22]: William Playfair, An Inquiry into the Permanent Causes 0f the Decline and Fall of Powerful and Wealthy Nations: Designed to Show How the Prosperity of the British Empire May he Prolonged (London: Greenland and Norris, 1805), s. 79.

[^23]: Guy Bois, The Transformation 0f the Year One Thousand: The Village of Lournard from Antiquity to Feudalism (Manchester, England: Manchester University Press, 1992).

[^24]: Ibid., s. 150.

[^25]: Sitat teoksesta S. B. Saul, The Myth 0f the Great Depression (London: Macmillan, 1985), s. 10.

[^26]: Oswald Spengler, The Decline of the West, trans. Charles Francis Atkinson, sitat teoksesta I. F. Clark, The Pattern of Expectation, 1644-2001 (London: Jonathan Cape, 1979), s. 220.

[^27]: Nomenklatura on ne vakiintuneet eliitit, jotka hallitsivat entistä Neuvostoliittoa ja muita valtioiden ohjaamia talouksia.

[^28]: Adam Smith kuoli vuonna 1790, Karl Marx vuonna 1883.