# Kansallisvaltion elämä ja terveys

::: {.content-hidden when-format=latex}
*Democracy and Nationalism as Resource Strategies in the Age of Violence*
:::

> 'Kaiken tärkeimpänä menestys sodassa riippuu siitä, että rahaa on tarpeeksi hankkia kaiken tarvitun kattamiseksi.' [^163] - ROBERT DE BALSAC, 1502

## Historian romut

1989. marraskuun 9. ja 10. päivänä televisio välitti maailmalle kuvia riemukkaista itäberliiniläisistä, jotka purkivat Berliinin muurin raskain vasaroin. Yleisön joukosta nousseet nuoret yrittäjät kokosivat muuripalasia, joita myöhemmin markkinoitiin laajasti pääomahakuisten keskuudessa muistojena toimivina paperipainoina. Näiden jäänteiden kaupankäynti oli hyvin vilkasta vielä vuosia sen jälkeen. Juuri nyt, kun kirjoitamme, pienistä lehdistä saattaa vielä löytyä satunnaisia ilmoituksia, joissa myydään vanhaa itäsaksalaista betonia hinnoin, joita normaalisti pyydetään korkealaatuisesta hopeamalmista. Uskomme, ettei niiden, jotka ostivat Berliinin muurin paperipainoja, tarvitse kiirehtiä niiden myymisessä. Ne kantavat muistoesineitä jostakin suuremmasta kuin kommunismin romahdus. Uskomme, että Berliinin muuri muodostui historian merkittävämmäksi romukasaaksi siitä lähtien, kun San Giovannin muurit räjäytettiin lähes viiden vuosisadan takaa helmikuussa 1495.[^164]

Ranskankuninkaan Karl VIII:n San Giovannin raivaus oli ensimmäinen räjähdys krutorevoluution historiassa. Se merkitsi feodaalisen historian vaiheen loppua ja teollistumisen alkua, kuten aiemmin esittelimme. Berliinin muurien tuho merkitsee toista historiallista käännekohtaa – siirtymää teollisuusajasta uuteen informaatiokauteen. Ei koskaan ole nähty yhtä suurta symbolista tehokkuuden voittoa vallasta. Kun San Giovannin muurit kaatuivat, se oli räikeä osoitus siitä, että väkivallan taloudelliset tuotto-odotukset maailmassa olivat nousseet jyrkästi. Berliinin muurien kaatuminen kertoo jotain aivan muuta, nimittäin että väkivallan tuotto-odotukset ovat nyt laskeneet. Tämä on jotain, jonka huomaan vain harvat ovat edes alkaneet ymmärtää, mutta sillä on dramaattiset seuraukset.

Syistä, joita käsittelemme tässä luvussa, Berliinin muuri saattaa osoittautua paljon symbolisemmaksi koko teollisen kansallisvaltion aikakaudelle kuin sitä ymmärsivät Berliinissä sinä iltana tai miljoonat kaukaa katsovat. Berliinin muuri rakennettiin hyvin eri tarkoitukseen kuin San Giovannin muurit – sen tehtävänä oli estää sisäpuolella olevien ihmisten pako, eikä ulkopuolella olevien saalistajien pääsy sisään. Jo pelkkä tuo seikka on selkeä osoitus valtion vallan noususta 1400-luvulta 1900-lukuun. Ja monella muullakin tavalla.

Vuosisatojen ajan kansallisvaltio on tehnyt kaikki ulospäin suunnatut muurit tarpeettomiksi. Se, kuinka suuri monopoliasema valtio käytti pakottamisen keinoissa niillä alueilla, joilla se ensimmäisen kerran vakiintui, teki yhteiskunnasta sekä sisäisesti rauhallisemman että sotilaallisesti vaikuttavamman kuin mikään aiemmin nähty itsenäinen valtio. Valtio käytti osittain riivattoman väestön resursseja murskatakseen pienten hyökkääjien pyrkimykset. Näin kansallisvaltiosta tuli historian menestynein väline resurssien haltuunottoon – sen menestys perustui sen ylivoimaiseen kykyyn saada kansalaistensa varallisuus käyttöönsä.

> 'MTV on enemmän kuin musiikkivideoiden toimittaja – se on myös äänitetyön promootioväline. Se on ensimmäinen todella globaali verkko, ensimmäinen verkko, joka toimittaa yhtenäisen ohjelmavirran käytännössä jokaisessa maailman maassa. Prosessissaan MTV luo yhtenäisen, jaetun globaalin todellisuudentunteen katsojilleen, lapsille ja nuorille aikuisille. Tuoreet tutkimukset ovat osoittaneet, että nuoret ympäri planeettaa jakavat yhä enemmän paitsi yhteisiä pop-ikoneja ja makuja, myös yhteisiä odotuksia urastaan, jaettuja arvojoukkoja siitä, mikä on merkityksellistä elämässä ja mistä tulee pelätä, sekä yhteisen käsityksen siitä, että politiikka on vähemmän tärkeää kuin heidän omat kykynsä muokata tulevaisuuttaan.'[^165]  
Jim Taylor ja Watts Wacker, *The 500-Year Delta: What Happens After What Comes Next*

### 'Pidä tai jätä' (ellei olet rikas)

Ennen kuin siirtyminen kansallisvaltiosta Informaatiokauden uusien suvereniteettien muotoihin on saatu päätökseen, monet suurimpien ja vaikutusvaltaisimpien länsimaiden asukkaat, aivan kuten Itä-Berliinissä vuonna 1989, aikovat suunnitella reittinsä ulos. Niille sukupolville, jotka saavuttivat täysi-ikäisyyden ennen toista maailmansotaa tai kylmän sodan alkuvaiheessa, rajojen ylittäminen on traumaattista. Mutta uusille sukupolville, jotka hahmottavat maailmaa globaalimmasta näkökulmasta, syntymämaastaan luopuminen ei ole yhtä ajattelematonta päätöstä kuin sitä vanhemmille, kansallisvaltion ideologiaa omaksuneille.

Jim Taylor ja Watts Wacker raportoivat mielenkiintoisia tuloksia 20 000 keskiluokkaisen lukiolaisen massakyselystä viideltä mantereelta. Brainwaves Groupin, newyorkilaisen kuluttajatutkimusyrityksen, vuonna 1995–96 suorittamassa otannassa yhdeksän kymmenesosaa opiskelijoista oli sitä mieltä, että 'minun vastuullani on saada elämästäni, mitä haluan.' Vielä yllättävämpää on, että 'lähes puolet teinistä sanoi odottavansa lähteneensä syntymämaastaan tavoitteidensa tavoittelussa.'[^166]

Ehkä siksi, että hän on viritetty MTV-sukupolven asenteisiin, Bill Clinton, ensimmäinen presidenttikandidaatti, joka kampanjoi MTV:ssä, on pyrkinyt vaikeuttamaan amerikkalaisilta 'lähtemistä syntymämaastaan tavoitteidensa perässä.' Vuonna 1995 – suunnilleen sillä hetkellä, kun lukiolaiset ilmoittivat aikomuksistaan hakea itsenäisyyttä – Yhdysvaltain presidentti ehdotti poistumismaksun, 'Kapitalin Berliinimuurin', käyttöönottoa, joka edellyttäisi varakkaiden amerikkalaisten maksavan huomattavan lunnasmaksun päästäkseen irti rahavaroistaan.

Clintonin lunnasmaaksu ei ainoastaan muistuta myöhäisen Itä-Saksan valtion käytäntöä, jossa kansalaisia kohdellaan varoina; se tuo mieleen myös yhä drakonisemmat toimenpiteet, joita otettiin Rooman valtakunnan rappeutuessa taloudellisen aseman vahvistamiseksi. Seuraava ote *The Cambridge Ancient History* –teoksesta kertoo tarinan näin:

> Näin alkoi valtion raivokas pyrkimys puristaa väestö viimeiseen pisaraan. Koska taloudelliset resurssit jäivät vajaiksi, vahvat taistelivat varmistaakseen itselleen pääosuuden väkivallan ja säädytön tavoin, mikä sopi hyvin vallassa olevien alkuperään sekä sotilaan tapaan ryöstää. Lain täysi ankaruus päästi valloilleen väestöä vastaan. Sotilaat toimivat ulosmittaajina tai vaelsivat salaisena poliisina maassa. Niitä, jotka kärsivät eniten, olivat tietenkin omaisuuskunnassa. Heidän omaisuuteensa oli suhteellisen helppo päästä käsiksi, ja hätätilanteessa he olivat se luokka, jolta jotain voitiin usein ja nopeasti riistää.[^167]

Kun epäonnistuneilla järjestelmillä on siihen valta, ne usein asettavat rangaistusvelvoitteita niille, jotka pyrkivät pakenemaan. Taas lainataan *The Cambridge Ancient History* –teosta: 'Jos omaisuuskunta hautasi rahansa tai uhrasi kaksi kolmasosaa omaisuudestaan paetakseen tuomiovaltaa, tai meni niin pitkälle, että luovutti koko omaisuutensa vapautuakseen vuokravelasta, ja ei-omaisuuskunta pakeni, valtio vastasi lisäämällä painetta.'

Tätä on syytä muistaa tulevaisuutta suunniteltaessa. Menneiden valtiollisten järjestelmien hämärtyminen ei ole harvoin ollut kohteliasta ja järjestäytynyttä. Mainitsimme Rooman veronkerääjien inhottavat tavat kappaleessa 2. Länsi-Euroopan valtakuntien romahtamisen jälkeen esiintyneistä hylätyistä maatiloista (agri deserti), jotka kuvaavat vain pientä osaa laajemmasta ongelmasta. Itse asiassa riistoja esiintyi suhteellisen lievinä Gallian alueella ja nykyisten Luxemburgin sekä Saksan reunamailla. Rooman hedelmällisimmässä alueessa, Egyptissä – jossa maanviljely oli kastelujärjestelmien ansiosta tuottoisampaa – omistajien pakeneminen oli vielä suurempi ongelma. Kysymys siitä, yritetäänkö paeta – ultimum refugium, kuten latinaksi tiedettiin – muodostui lähes kaikkien omaisuutta omistavien yläpuolelle. Lähteet osoittavat, että 'Egyptin oraklille asetettujen tavallisten kysymysten joukossa kolme perusmuotoa olivat: "Tulanko madaraksi?" "Lähdenkö pakoon?" ja "Pysäytetäänkö pakenevani?"'[^168]

Clintonin ehdotus sanoo kyllä. Se on varhainen versio pakenemisen esteestä, joka todennäköisesti muuttuu entistä rasittavammaksi, kun kansallisvaltion taloudelliset resurssit hiipuvat. Tietenkin Yhdysvaltain ensimmäinen poistumiseste on harmittomampi kuin Erich Honeckerin betonista ja piikkilankasta koostuva ratkaisu. Se sisältää myös suuremman hintaherkkyyden, ja taakka kohdistuu vain "miljardööreihin", joiden verotettava omaisuus ylittää 600 000 dollaria. Siitä huolimatta sitä perusteltiin samankaltaisilla argumenteilla kuin Honecker aikanaan esitti myöhäisen Saksan demokraattisen tasavallan kuuluisimman julkisen rakennusprojektin puolustuksessa. Honecker väitti, että Itä-Saksan valtiolla oli merkittävä sijoitus potentiaalisissa pakolaisissa. Hän huomautti, että antamalla heidän lähteä vapaasti syntyisi taloudellinen epäedullisuus valtioille, jotka tarvitsivat heidän panostaan Itä-Saksassa.

Jos hyväksyt premissin, että ihmiset ovat tai heidän pitäisi olla valtion varoja, Honeckerin muuri oli järkevä. Berliini ilman muuria oli reikä kommunisteille, aivan kuten pakeneminen Yhdysvaltain verojen alaisuudesta oli reikä Clintonin IRS:lle. Clintonin argumentit miljardööreihin pakenemisesta – sen lisäksi että ne osoittivat poliitikon tyypillisen piittaamattomuuden lukujen eheydestä – olivat samankaltaisia kuin Honeckerin, mutta hieman vähemmän loogisia, koska Yhdysvaltain hallituksella ei todellisuudessa ole suurta taloudellista sijoitusta varakkaisiin kansalaisiin, jotka saattaisivat haluta paeta. Kyse ei ole siitä, että he olisi koulutettu valtion kustannuksella ja haluaisivat paeta harjoittamaan lakia muualla. Yli suuressa osassa niitä, joihin exit-vero koskisi, on luotu varallisuus omilla ponnistuksillaan ja vastoin – ei siksi, että Yhdysvaltain hallitus olisi ollut niissä osallisena.

Kun Yhdysvalloissa ylimpänä 1 prosenttina maksavat veronmaksajat nyt 28,7 prosenttia koko tuloverosta, kyse ei ole siitä, että rikkaat epäonnistuisivat maksamaan takaisin mitään todellista investointia, jonka valtio on mahdollisesti tehnyt heidän koulutukseensa tai taloudelliseen hyvinvointiinsa. Päinvastoin. Ne, jotka maksavat suurimman osan laskuista, maksavat valtavasti enemmän kuin minkään saamansa etujen arvo. Kun keskimääräinen vuotuinen veromaksu ylittää 125 000 dollaria, verot maksavat amerikkalaisille ylimmän 1 prosentin veronmaksajille paljon enemmän kuin he nykyään ymmärtävät. Oletetaan, että he saavuttaisivat jopa 10 prosentin tuoton kullakin maksamastaan ylimääräisestä verosta neljän vuosikymmenen aikana, niin jokainen 5 000 dollarin vuotuinen ylimääräinen veromaksu vähentäisi heidän nettovarallisuuttaan 2,2 miljoonalla dollarilla. 20 prosentin tuottotahdilla taas jokainen 5 000 dollarin ylimääräinen veromaksu vähentäisi nettovarallisuutta 44 miljoonalla dollarilla.

Vuosituhannen lähestyessä tiedonajan uudet megapoliittiset olosuhteet tekevät yhä selvemmäksi, että teollisuusaikakaudelta peritty kansallisvaltio on saalistava instituutio. Jokaisella kuluvalla vuodella se vaikuttaa yhä vähemmän vaurauden edistäjänä ja enemmän esteenä, josta yksilö haluaa paeta. Tämä on pakokeino, jonka epätoivoiset hallitukset eivät halua sallia. Länsimaisten hyvinvointivaltion vakaus ja jopa selviytyminen riippuvat niiden kyvystä jatkaa maailman kokonais tuotannon valtavan osan keräämistä uudelleenjaettavaksi tietylle äänestäjäjoukolle OECD-maissa. Tämä edellyttää, että tällä hetkellä rikkaiden maiden tuottavimpien kansalaisten maksamiin veroihin asetetaan supermonopolihinnat, satoja tai jopa tuhansia kertoja korkeammat kuin hallitusten vastineeksi tarjoamien palvelujen todelliset kustannukset.

## The life and death of the nationstate

Berlinin muurin murtuminen ei ollut vain näkyvä symboli kommunismin kuolemasta. Se edusti koko kansallisvaltioiden maailmanjärjestelmän tappiota ja tehokkuuden sekä markkinoiden voittoa. Historiassa vallankasvun vipuvarsi on siirtynyt. Uskomme, että vuoden 1989 Berlinin muurin murtuminen huipentaa kansallisvaltio-ajan päätöstä – erikoisen kahdensadan vuoden vaihetta, joka sai alkunsa Ranskan vallankumouksessa. Valtioita on ollut olemassa kuusi tuhatta vuotta, mutta ennen 1800-lukua ne muodostivat vain pienen osan maailman suvereniteeteista. Niiden nousu alkoi ja päättyi vallankumouksissa. Vuoden 1789 suuret tapahtumat ohjasivat Eurooppaa kohti aidosti kansallisia hallituksia, kun taas vuoden 1989 tapahtumat merkitsivät kommunismin kuolemaa ja markkinavoimien vallan noustua massiivisen valtakunnan yli. Nämä kaksi vallankumousta, tarkalleen kahden sadan vuoden eroilla, määrittävät aikakauden, jolloin kansallisvaltio oli hallitsevana suurvaltojen järjestelmässä. Suurvallat puolestaan hallitsivat maailmaa levittäen tai pakottaen valtiojärjestelmiä jopa kaikkein syrjäisimmille heimoalueille.

Valtion voitto väkivallan järjestämisen päävälineenä ei perustunut ideologiaan, vaan se oli välttämätöntä väkivallan kylmän logiikan vuoksi. Kuten usein sanomme, kyseessä oli megapoliittinen tapahtuma, jota määräsivät ei niin paljon teoreetikkojen ja valtiomiehen toiveet tai kenraalien liikkeet, vaan väkivallan salainen vipuvoima, joka veti historiaa eteenpäin aivan kuten Arkhimedes unelmoi liikuttavansa maailmaa.

Modernin aikakauden viimeiset kaksisataa vuotta ovat nähneet valtioiden olevan normi, mutta pidemmällä aikajanalla valtiot ovat olleet harvinaisia. Ne ovat aina edellyttäneet poikkeuksellisia megapoliittisia olosuhteita selviytyäkseen. Ennen modernia aikaa useimmat valtiot olivat niin sanottuja itämaisia despotismeja – maatalousyhteiskuntia aavikoilla, joiden selviytyminen perustuikin kastelujärjestelmien hallintaan. Jopa Rooman valtakunta, Egyptin ja Pohjois-Afrikan kautta, oli välillisesti hydraulinen yhteiskunta, mutta se ei ollut tarpeeksi kestävä. Rooma, kuten useimmat esimaailmalliset valtiot, kärsi lopulta kyvyttömyydestä pakottaa ihmisiä hyväksymään väkivallan monopolia, jonka kyky nälkään jättää ihmiset tarjoaa. Rooman valtio Afrikan ulkopuolella ei pystynyt katkaisemaan viljelyn veden saantia estämällä itsepäisten ihmisten pääsyä kastelujärjestelmään. Tällaiset hydrauliset järjestelmät antoivat väkivallalle enemmän vipuvoimaa kuin mikään muu esikauden megapoliittinen konfiguraatio. Ne, jotka hallitsivat vettä näissä yhteiskunnissa, pystyivät keräämään saaliin lähes samalla tasolla kuin modernit kansallisvaltiot omistavat osan kokonaisproduktiosta.[^169]

### Suuruusluokka tehokkuuden yläpuolella

Ampumaruuti mahdollisti valtioiden laajentumisen helpommin kuin pelkästään riisiviljelmien ja kuivien jokien laaksojen rajoissa pysyminen. Ampumaruutiaseiden luonne ja teollisen talouden piirteet loivat mittakaavaetuja sodankäynnissä, mikä johti korkeisiin ja kasvaviin tuottoihin väkivallan saralla. Kuten historioitsija Charles Tilly totesi, “[V]altioilla, joilla oli suurimmat pakottavat keinot, oli taipumus voittaa sodat; tehokkuus (tuotoksen suhde panokseen) oli toiseksi tärkeä, sen jälkeen kun vaikutus (kokonais tuotanto) otettiin huomioon.”[^170] Koska hallitukset olivat pääosin järjestäytyneet suuressa mittakaavassa, jopa harvat pienemmät suvereniteetit, kuten Monaco tai Andorra, tarvitsivat suurempien valtioiden tunnustusta itsenäisyytensä turvaamiseksi. Vain suuret hallitukset, joilla on jatkuvasti kasvava resurssien hallinta, pystyivät kilpailemaan taistelukentällä.

### Suuri vastaamaton kysymys

Tämä vie meidät yhteen modernin historian suurimpiin vastaamattomiin arvoituksiin: miksi suurvaltojen järjestelmän päättyessä kylmä sota asetti lopullisiksi kilpailijoikseen kommunistiset diktatuurit ja hyvinvointivaltiot. Tätä kysymystä on tutkittu niin vähän, että monet pitivät jopa uskottavana, kun Yhdysvaltain ulkoministeriön analyytikko Francis Fukuyama julisti 'historian loppua' Berliinin muurin murtuessa. Hänen työnsä herättämä innostunut yleisö otti liikaa asioita itsestäänselvyyksinä. Ilmeisesti kukaan – ei kirjailija itse eikä monet muut – ei ollut pysähtynyt kysymään peruskysymystä: mitkä yhteiset piirteet valtiollisessa sosialismissa ja hyvinvointivaltioden demokratiassa saivat ne lopullisiksi kilpailijoiksi maailmanvalloituksessa?

Tämä on tärkeä kysymys. Lukuisten suvereniteettijärjestelmien on tullut ja mennyt viimeisten viiden vuosisadan aikana, mukaan lukien absoluuttiset monarkiat, heimoyhteisöt, ruhtinaskirkot, paavin suora hallinto, sulttaanikunnat, kaupunkivaltiot ja anabaptistikoloniat. Nykyään useimmat olisivat yllättyneitä kuullessaan, että sairaanhoitoyhtiö, jolla on oma asevoimansa, olisi voinut hallita maata vuosisatojen ajan. Kuitenkin jotakin hyvin sellaista tapahtui. Kolmesataa vuotta vuodesta 1228 lähtien Jerusalemin Marian sairaalan teutonikkarit, myöhemmin yhdistyneinä Livonian miekkojen ritarikunnan kanssa, hallitsivat Itä-Prussiaa ja useita Itä-Euroopan alueita, mukaan lukien osia Liettuasta ja Puolasta. Sitten koitti ruutupulverin vallankumous. Muutamassa vuosikymmenessä teutonikkarit ajettiin pois kaikilta alueiltaan, ja niiden suurmestari menetti sotilaallisen merkityksensä – hänestä tuli yhtä vähäpätöinen sotilaallisesti kuin shakin mestari. Miksi? Miksi niin monet muut suvereniteettijärjestelmät kuihtuivat merkityksettömiksi, kun teollisuusajan lopun maailmanvallankamppailussa massademokratioita vastassa olivat valtiollisesti sosialistiset järjestelmät?

### Estämätön hallinta

Jos megapoliittista teoriaamme sovelletaan, vastaus on yksinkertainen. Se on lähes kuin kysyisi, miksi sumopainijat ovat yleensä lihavia. Vastaus on, että laiha sumopainija, vaikka hänen voima-paino-suhteensa olisi vaikuttava, ei pysty kilpailemaan jättimäisen kilpakumppaninsa kanssa. Kuten Tilly ehdottaa, tärkeämpää on "tehokkuus (kokonaistuotanto)" eikä "tuottavuus (tuotannon ja syötteen suhde)". Yhä väkivaltaisemmassa maailmassa ne järjestelmät, jotka hallitsivat viiden vuosisadan kilpailua, olivat välttämättä niitä, jotka mahdollistivat parhaan pääsyn niihin resursseihin, joita tarvittiin laajamittaisen sodankäynnin käynnistämiseen.

Miten tämä toimi?

Kommunismin tapauksessa vastaus on ilmeinen. Kommunismissa ne, jotka hallitsivat valtiota, hallitsivat melkein kaikkea. Jos olisit ollut Neuvostoliiton kansalainen kylmän sodan aikana, KGB olisi voinut ottaa hammasharjasi, mikäli se oli heidän tarkoitusperiensä mukainen – he olisivat voineet jopa viedä hampaitasi. Luotettavien arvioiden mukaan, jotka ovat saaneet lisää uskottavuutta Neuvostoliiton arkistojen avaamisen jälkeen vuonna 1992, myöhäisen Neuvostoliiton salapoliisi ja muut agentit ottivat 50 miljoonan ihmisen hengen 74 vuoden hallinnon aikana. Valtion sosialistinen järjestelmä pystyi mobilisoimaan kaiken, mikä sen rajojen sisällä oli olemassa, sotilaallisiin tarkoituksiin, niin ettei kukaan sen asukkaista todennäköisesti kyennyt vastustamaan sitä.

Länsimaiden demokratioiden tapauksessa tilanne on vähemmän ilmeinen, osin siksi, että olemme tottuneet ajattelemaan demokratiaa jyrkästi vastakohtana kommunismille. Teollisella ajalla nämä kaksi järjestelmää olivat tosiaan suuria vastakohtia, mutta informaatiokauden näkökulmasta niillä oli enemmän yhteisiä piirteitä kuin voisi epäillä. Molemmat mahdollistivat hallituksen esteettömän resurssien hallinnan. Erona oli se, että demokraattinen hyvinvointivaltio sijoitti vieläkin suuremmat resurssit valtion käsiin kuin valtion sosialistiset järjestelmät.

Tämä on selkeä esimerkki harvinaisesta ilmiöstä, jossa vähemmän on enemmän. Valtion sosialistinen järjestelmä perusti toimintansa doktriiniin, jonka mukaan valtio omistaa kaiken. Sen sijaan demokraattinen hyvinvointivaltio esitti vaatimuksensa vaatimattomammin ja käytti siten ylivoimaisesti houkuttelevampia kannustimia suuremman tuotannon mobilisoimiseksi. Sen sijaan, että alussa vaadittaisiin omistusoikeutta kaikkeen, Lännen hallitukset sallivat yksilöiden omistaa omaisuutta ja kerryttää varallisuutta. Sitten, kun varallisuus oli kertynyt, länsimaavaltio verotti siitä suuren osuuden. Korkeat kiinteistö-, tulos- ja perintöverot toimittivat demokraattiselle hyvinvointivaltiolle valtavia määriä resursseja verrattuna niihin, jotka valtion sosialistisista järjestelmistä olivat käytettävissä.

### Tehottomuutta siellä, missä se merkitsi

Kommunismiin verrattuna hyvinvointivaltio oli todellakin paljon tehokkaampi järjestelmä. Mutta verrattuna muihin varallisuuden kartuttamismekanismeihin, kuten aidosti laissez‑faaren ympäristöön, esimerkiksi Hong Kongiin, hyvinvointivaltio osoittautui tehottomaksi. Taas kerran, vähemmän oli enemmän. Juuri tämä tehottomuus teki hyvinvointivaltiosta ylivoimaisen teollisen aikakauden megapoliittisissa olosuhteissa.

Kun ymmärrät miksi, olet paljon lähempänä sitä, mitä Berliinin muurin romahdus ja kommunismin kuolema todella tarkoittavat. Kaukana siitä, että demokraattinen hyvinvointivaltio olisi näyttänyt voitokkaalta järjestelmältä, kuten laajalti on oletettu, se oli ennemminkin kuin havaitsisit, että toveriplasveli on kuollut vanhaan ikään. Sama megapoliittinen vallankumous, joka tappoi kommunismin, on todennäköisesti myös uhkaamassa ja tuhoamassa 1900-luvulla tuntemiamme demokraattisia hyvinvointivaltioita.

## Who controls government?

Avain tähän epätavanomaiseen johtopäätökseen piilee siinä, missä demokraattisen hallituksen valta todellisuudessa keskittyy. Kyseinen kysymys ei olekaan niin yksinkertainen kuin miltä se aluksi vaikuttaa. Modernilla aikakaudella kysymystä siitä, kuka hallitsee valtiota, on lähes aina esitetty poliittisena kysymyksenä. Siihen on annettu monia vastauksia, mutta lähes kaikissa tapauksissa on tunnistettu se poliittinen puolue, ryhmä tai jakautuma, joka hallitsi tietyn valtion valtaa tiettynä hetkenä. Olet kuullut kapitalistien hallitsemista hallituksista. Hallituksista, joita työväenluokka ohjaa. Hallituksista, joita hallitsevat katolilaiset sekä islamilaiset fundamentalistit. Hallituksista, joita ohjaavat heimot ja roturyhmät; hallituksista, joita hallitsevat hutut ja hallituksista, joita valkoiset ohjaavat. Olet myös kuullut hallituksista, joita ammatilliset ryhmät – esimerkiksi lakimiehet tai pankkiirit – ohjaavat. Olet kuullut hallituksista, joita maaseudun edut, suurkaupunkien koneistot sekä esikaupunkialueiden asukkaat ohjaavat. Ja olet varmasti kuullut hallituksista, joita poliittiset puolueet, kuten demokraatit, konservatiivit, kristilliset demokraatit, liberaalit, radikaalit, republikaanit ja sosialistit, ohjaavat.

Mutta et varmaankaan ole kuullut paljoa hallituksesta, jota hallitsevat sen asiakkaat. Taloushistorioitsija Frederic Lane loi perustan uudelle tavalle ymmärtää, missä hallituksen valta todellisuudessa sijaitsee, joissain hänen aiemmin käsitellyissä selkeissä eseissään väkivallan taloudellisista seurauksista. Ajatellessaan hallitusta taloudellisena yksikkönä, joka myy suojaa, Lane analysoi sen valtaa taloudellisista, eikä pelkästään poliittisista näkökulmista. Tässä näkemyksessä hallituksen hallintaan liittyy kolme perusvaihtoehtoa, jotka sisältävät periaatteellisesti erilaiset kannustinjärjestelmät: omistajat, työntekijät ja asiakkaat.

### Omistajat

Harvinaisissa tapauksissa, jopa nykyään, hallituksia ohjaa joskus yksittäinen omistaja, yleensä periytyvä johtaja, joka käytännössä omistaa maan. Esimerkiksi Brunein sulttaani kohtelee Brunein hallitusta jossain määrin kuin omistajuusyritystä. Tämä oli yleisempää keskiajan herroilla, jotka pitivät maa-alueitaan omistajuuksina optimoidakseen tulonsa.

Lane kuvaili 'tuotantoa tuottavan yrityksen omistajien' kannustimia seuraavasti:

> Kiinnostus maksimoida voittoja saattaisi ohjata häntä – samalla kun hinnat pysyvät ennallaan – pyrkimään kustannustensa vähentämiseen. Hän käyttäisi, kuten Englannin Henrik VII tai Ranskan Louis XI, mahdollisimman edullisia keinoja vahvistaakseen legitimiteettinsä, ylläpitääkseen sisäistä järjestystä ja häiritäkseen naapurivaltioiden prinssien toimia, jotta hänen oma sotilaallinen menonsa pysyisi alhaisena. Alhaistuneista kustannuksista, tai monopolinsa vakaudesta johtuvien kasvaneiden vaatimusten seurauksena, tai näiden yhdistelmänä, hän kerrytti ylijäämää... [^171]

Omistajiensa hallitsemilla valtioilla on vahvat kannustimet vähentää suojelun järjestämisen tai väkivallan monopolisoimisen kustannuksia tietyllä alueella. Mutta niin kauan kuin heidän valtansa on varma, heillä on vähän kannustimia alentaa asiakkailtaan perimänsä hinnan (vero) alle sen tason, joka optimoisi tulot. Mitä korkeampaan hintaan monopolisti pystyy vaikuttamaan ja mitä alhaisempia hänen todelliset kustannuksensa ovat, sitä suuremmat voitot hän tekee. Ihanteellisena talouspolitiikkana omistajiensa hallitsemalle valtiolle olisi valtava ylijäämä. Kun hallitukset pystyvät pitämään tulonsa korkeina mutta leikkaamaan kustannuksiaan, sillä on merkittävä vaikutus resurssien käyttöön. Työvoima ja muut arvokkaat tuotantopanokset, jotka muuten hukkuisivat tarpeettoman kalliin suojelun järjestämiseen, tulevat sen sijaan käytettäväksi investointeihin ja muihin tarkoituksiin. Mitä korkeammalle monarkki pystyy nostamaan voittojaan kustannuksia alentamalla, sitä enemmän resursseja vapautuu. Kun näitä resursseja käytetään investointeihin, ne toimivat kasvun vauhdittajina. Ja vaikka niitä käytettäisiin näkyvään kulutukseen, ne auttavat luomaan ja ylläpitämään uusia markkinoita, joita ei muuten syntyisi, jos resurssit jäisivät hukkaan tehottoman 'suojelun' tuottamiseen.

### Työntekijät

On helppo kuvata kannustimia, jotka ovat yleisiä työntekijöidensä hallitsemissa hallituksissa. Samankaltaiset kannustimet esiintyvät myös muissa työntekijöiden ohjaamissa organisaatioissa. Ensisijaisesti työntekijöiden johtamat organisaatiot suosivat politiikkaa, joka lisää työllisyyttä, ja vastustavat toimenpiteitä, jotka vähentävät työpaikkoja. Kuten Lane totesi: 'Kun työntekijät kokonaisuudessaan hallitsivat, heillä oli vähän kiinnostusta vähentää suojelupalveluihin perittyjä maksuja, eivätkä he pyrkinyt karsimaan merkittävää osaa kustannuksista, jotka muodostuivat työvoimakuluista eli heidän omista palkkoistaan. He arvostivat myös organisaation laajuuden maksimoimista.'[^172]

Työntekijöidensä ohjaamassa hallituksessa ei olisi juurikaan kannustimia joko leikata hallinnon kuluja tai alentaa asiakkailleen perittäviä hintoja. Kuitenkin tilanteissa, joissa esiintyy voimakasta hintavastustusta esimerkiksi korkeampia veroja vastaan, työntekijöiden ohjaamat hallitukset todennäköisemmin sallivat tulojensa jäädä alle menojensa kuin leikkaavat menojaan. Toisin sanoen, niiden kannustimet viittaavat siihen, että ne saattavat kallistua kroonisiin alijäämiin, mikä taas ei olisi omistajiensa hallitsemissa hallituksissa.

### Asiakkaat

Onko olemassa esimerkkejä hallituksista, joita asiakkaat hallitsevat? On. Lane sai inspiraationsa analysoida hallituksen ohjaamista taloudellisista näkökulmista keskiaikaisten kaupparepublikoiden, kuten Venetsiasta, esimerkin avulla. Siellä eräs tukkukauppiaiden ryhmä, jotka tarvitsivat suojelua, hallitsi käytännössä hallitusta vuosisatojen ajan. He olivat todellisia asiakkaita siinä suojelupalvelussa, jota hallitus tarjosi, eivätkä he toimineet omistajina. He maksoivat palvelusta eivätkä pyrkineet hyötymään hallituksen väkivallan monopolin käytöstä. Jos jotkut yrittivätkin, muut asiakkaat estivät sen pitkiksi ajoiksi.

Muita esimerkkejä asiakkaidensa ohjaamista hallituksista ovat demokratiat ja rajallisen äänioikeuden omaavat tasavallat, kuten muinaisten demokratioiden mallit tai Yhdysvaltain tasavalta sen perustamisajalla. Tuolloin vain ne, jotka maksoivat hallituksesta – noin 10 prosenttia väestöstä – saivat äänestää.

Asiakkaidensa hallitsemilla hallituksilla, kuten omistajiensa hallitsemilla, on kannustimia pienentää käyttömenojaan mahdollisimman paljon.

Mutta toisin kuin hallitukset, joita ohjaavat pelkästään omistajat tai työntekijät, asiakkaidensa hallitsemat hallitukset saavat kannustimia pitää peritsemänsä hinnat alhaisina. Siellä, missä asiakkaat määräävät, hallitukset ovat hoikkia ja yleensä häiritsemättömiä, niillä on vähäiset toimintakustannukset, minimaalinen työvoima ja matalat verot. Asiakkaidensa ohjaama hallitus asettaa verokannat ei optimoidakseen kerättävää määrää, vaan optimoidakseen sen osuuden, jonka asiakkaat saavat pitää itsellään.

Kuin tyypillisillä kilpailumarkkinoiden yrityksillä, myös asiakkaidensa kontrolloima monopoli olisi pakotettu pyrkimään tehokkuuteen. Se ei voisi periä veroina hintaa, joka ylittäisi kustannukset pelkän marginaalin verran.

## The role of democracy: Voters as employees and customers

Lane käsittelee demokratiaa tavanomaisella tavalla olettaen, että se tuo aina väkivallan käyttöä ja väkivaltaa tuottavat yritykset “kasvavasti asiakkaidensa valvonnan alle.”[^173] Tämä on ehdottomasti poliittisesti korrektia johtopäätöstä. Mutta onko se totta? Me emme usko niin. Tarkastellaanpa tarkemmin, miten modernit demokratia toimivat.

Ensinnäkin niillä on vain vähän ominaisuuksia niistä kilpailluista teollisuudenaloista, joissa asiakkaat selkeästi kontrolloivat vaihtosuhteita. Yksi seikka on, että demokraattiset hallitukset käyttävät tyypillisesti vain murto-osan kokonaismenoistaan suojapalveluihin, jotka ovat niiden ydintoimintaa. Esimerkiksi Yhdysvalloissa osavaltiot ja paikallishallitukset käyttävät vain 3,5 prosenttia kokonaismenoistaan poliisitoimintaan, tuomioistuimiin ja vankiloihin. Kun sotilaallinen menotus lisätään, suojeluun varattu osuus tuloista on silti vain noin 10 prosenttia. Toinen paljastava seikka siitä, että massademokratia ei ole kokonaan asiakkaidensa hallinnassa, on se, että nykyinen poliittinen kulttuuri – periytyen teolliselta ajalta – näkisi järkyttävänä, jos ratkaisevilla kysymyksillä tehtävät päätökset todella perustuivat laskuja maksavien kansalaisten etuihin. Kuvittele, millainen kohu syntyisi, jos yhdysvaltalainen presidentti tai brittiläinen pääministeri ehdottaisi, että enemmistö veroja maksavista kansalaisista saisi päättää, mitkä hallituksen ohjelmat jatkuvat ja ketkä työntekijäryhmät irtisanotaan. Tämä loukkaisi syvästi odotuksia siitä, miten hallituksen tulisi toimia – tavalla, joka ei herättäisi samanlaista vastareaktiota verrattuna siihen, että hallituksen työntekijät saisivat määräää, kenen veroja korotetaan.

Kuitenkin, kun siihen pysähtyy ajattelemaan, asiakkaiden ollessa todellisuudessa ohjaamossa olisi järjetöntä, etteivät he saisi haluamaansa. Jos menisit kauppaan ostamaan huonekaluja ja myyjät ottaisivat rahasi vastaan, mutta sitten sivuuttaisivat pyyntösi ja kyselisivät muilta, kuinka rahasi kannattaisi käyttää, suuttuisitkin oikein. Et pitäisi normaalia tai oikeutettuna sitä, että kaupan työntekijät väittäisivät sinun eivät ansaitse huonekaluja ja että ne tulisi sen sijaan lähettää jollekin, jota he pitävät arvoltaan parempana. Se, että jotakin tällaista tapahtuu valtiollisessa asioinnissa, osoittaa, kuinka vähän sen "asiakkailla" todellisuudessa on valtaa.

Mikä tahansa mittapuuta käyttäen, demokraattisen hallinnon kustannukset ovat nousseet hallitsemattomiksi – toisin kuin normaalissa tilanteessa, jossa asiakkaiden mieltymykset pakottavat myyjät toimimaan tehokkaasti. Useimmat demokratioiden hallitukset toimivat kroonisten alijäämien kanssa. Tämä on veropolitiikan ominaispiirre, jossa työntekijöiden etu määrää valtaa. Hallitukset näyttävät olevan erityisen vastustuskykyisiä toimintojensa kustannusten vähentämiselle. Lähes kaikissa maissa on huudettu, että poliittisia ohjelmia, kerran käynnistettyjä, on hyvin vaikea kaventaa. Hallituksen työntekijän erottaminen on käytännössä lähes mahdotonta. Itse asiassa yksi entisaikojen valtion omistamien toimintojen yksityistämisestä saatavista pääeduista on, että yksityinen hallinto tekee tarpeettoman työvoiman karsimisen paljon helpommaksi – Britanniasta Argentiinaan uudet yksityiset johtajat ovatkin usein päässeet irrottamaan 50–95 prosenttia entisistä valtion työntekijöistä.

Ajattele myös perustaa, jonka mukaan hallituksen suojauspalveluiden verotukselliset ehdot hinnoitellaan. Suurin osa ajasta et löytäisi viitteitä siitä, että kilpailulliset vaikutteet vaikuttaisivat verokantoihin, joiden mukaan hallituksen palvelut hinnoitellaan. Jopa satunnaiset keskustelut verojen alentamisesta, jotka ovat häirinneet normaalia poliittista keskustelua viime vuosina, paljastavat, kuinka kaukana demokraattinen hallinto on yleensä ollut asiakkaidensa valvonnasta. Matalampia veroja kannattavat ovat joskus väittäneet, että hallituksen tulot kasvaisivat itse asiassa, koska aiemmin asetetut verokannat olivat niin korkeat, että ne actually lannistivat taloudellista toimintaa.

He eivät kuitenkaan pyrkineet korostamaan kilpailua eri oikeudenkäyttöalueiden välillä, vaan jotain paljon hämmästyttävämpää. He eivät esittäneet, että koska Hongkongin verokannat olivat vain 15 prosenttia, Yhdysvalloissa tai Saksassa niiden ei pitäisi olla korkeampia kuin 15 prosenttia – päinvastoin. Verokeskusteluissa oletettiin yleensä, että veronmaksajan edessä oleva kompromissi ei ollut liiketoiminnan harjoittaminen yhdessä oikeudenkäyttöalueessa tai toisessa, vaan se oli valinta rangaistuksellisten verojen alaisen liiketoiminnan ja kevyempien verorasitusten väliltä. Sinulle kerrottiin, että tuottavat yksilöt, joita saalistava verotus rasittaa, lähtisivät jättämään työpöytänsä ja menisivät pelaamaan golfia, ellei heidän verorasituksensa helpottautuisi.

Se, että tällainen argumentti edes voi nousta esiin, osoittaa, kuinka kaukana demokraattisten hyvinvointivaltioiden asettamat suojauskustannukset ovat kilpailullisesta perusasennosta. Progressiivisen tuloverotuksen ehdot, jotka kehittyivät jokaisessa tämäntyyppisessä järjestelmässä 1900-luvun aikana, ovat dramaattisesti erilaiset kuin ne hinnoitteluperiaatteet, joita asiakkaat suosisivat. Tämä käy helposti ilmi vertaamalla monopolisesti tarjotun suojelun tukemiseksi asetettuja veroja puhelinpalveluiden tariffimaksuihin, jotka olivat vuoroin monopoliasemassa useimmissa paikoissa. Asiakkaat riisuttuisivat raivosta, jos puhelinyritys yrittäisi veloittaa puheluista samalla perusteella kuin tuloveroja asetetaan. Kuvittele, että puhelinyritys lähettäisi laskun 50 000 dollarilla soitetusta puhelusta Lontooseen, vain siksi että pääsit tekemään 125 000 dollarin kaupan keskustelun aikana. Et sinä etkä kukaan muu järkevä asiakas maksaisi sitä – mutta juuri näin tulojen verotus perustuu kaikissa demokraattisissa hyvinvointivaltioissa.

Kun tarkastelet teollisuusdemokratioiden toimintaperiaatteita, on loogisempaa käsitellä niitä hallintomuotoina, joita heidän työntekijänsä ohjaavat. Massademokratian ajatteleminen työntekijöiden hallitsemana auttaa selittämään, miksi hallituksen politiikan muuttaminen on niin vaikeaa. Monin tavoin hallitusta pyöritetään työntekijöiden etujen mukaisesti. Esimerkiksi useimpien demokratioiden julkiset koulut vaikuttavat jatkuvasti toimimattomilta ja korjaamattomilta. Jos asiakkaat todella ohjaisivat järjestelmää, he löytäisivät itse helpommin uusia politiikkasuuntia. Ne, jotka maksavat demokraattisesta hallinnosta, harvoin määrittelevät, mihin hallitus käyttää varojaan. Sen sijaan hallinto toimii osuuskuntana, joka on sekä omaisuuden ulkopuolella että toimii luonnollisena monopolina. Hinnat eivät juurikaan vastaa kustannuksia, ja palvelun laatu on yleisesti alhainen verrattuna yksityisen sektorin toimintaan. Asiakkaiden valitusten korjaaminen on vaikeaa. Lyhyesti sanottuna massademokratia johtaa siihen, että hallituksen „työntekijät” ohjaavat sitä.

Mutta odota. Saatat sanoa, että useimmissa oikeudenkäyttöalueissa äänestäjiä on paljon enemmän kuin niitä, jotka ovat hallituksen palkkalistoilla. Miten tällaisissa olosuhteissa työntekijöiden olisi mahdollista hallita? Hyvinvointivaltio syntyi juuri tämän arvoituksen ratkaisemiseksi. Koska työntekijöitä ei muuten ollut tarpeeksi toimivan enemmistön muodostamiseksi, yhä useampia äänestäjiä lisättiin käytännössä palkkalistoille saadakseen erilaisten siirtoetuuksien maksuja. Näin siirtoetuuksia ja tukia saivat pseudo-hallituksen työntekijät, joiden ei tarvinnut joka päivä raportoitua töihin. Tämä oli teollisen ajan megapoliittisen logiikan määräämä ratkaisu.

Kun pakottavan voiman suuruus on tärkeämpää kuin resurssien tehokas käyttö – kuten oli ennen vuotta 1989 – lähes mahdotonta on, että useimpia hallituksia ohjaisivat heidän asiakkaansa. Myöhäisen Neuvostoliiton esimerkki havainnollisti hyvin, että vielä muutama vuosi sitten valtioiden oli mahdollista harjoittaa suurta valtaa maailmassa, vaikka ne tuhosivatkin resursseja massiivisella tasolla. Kun väkivallan tuotto on korkea ja sitä nousee, määrä tarkoittaa enemmän kuin tehokkuus. Suuremmat toimijat pärjäävät yleensä pienempiä vastaan. Ne hallitukset, jotka pystyvät tehokkaammin mobilisoimaan sotilaalliset resurssit – vaikka se tapahtuisi monien niiden hukkaamisen kustannuksella – pärjäävät paremmin niiden kanssa, jotka käyttävät resursseja tehokkaammin.

Ajattele, mitä tämä tarkoittaa. Se väistämättä merkitsee sitä, että kun määrä on tärkeämpää kuin tehokkuus, asiakkaiden ohjaamien hallitusten ei voida odottaa menestyvän ja usein ne eivät kestä. Tällaisissa olosuhteissa sotilaallisesti tehokkaimmat toimijat ovat niitä, jotka keräävät sodan varalle eniten resursseja. Kuitenkin hallitukset, joita todella ohjaavat asiakkaat, jotka maksavat laskunsa, eivät todennäköisesti saa vapaita valtuuksia ryhtyä ryömimään kaikilta.

Asiakkaat haluavat normaalisti nähdä, että heidän maksamansa hinnat tuotteista tai palveluista – suojelusta lukien – laskevat ja pysyvät kurissa. Jos Länsi-demokratioita olisi hallinnut asiakkaiden valta kylmän sodan aikana, tämä yksin olisi heikentänyt niiden sotilaallista kilpailukykyä, koska se lähes varmasti olisi rajoittanut resurssivirtoja hallitukseen. Muista, että siellä, missä asiakkaat hallitsevat, sekä hinnat että kustannukset ovat tiukassa kurissa. Mutta näin ei juuri tapahtunut. Hyvinvointivaltiot osoittautuivat selvästi kylmän sodan kulutuskilpailun voittajiksi. Eri linjojen kommentoijat mainitsivat osatekijänä voittoon heidän kykynsä käyttää Neuvostoliiton varoja konkurssiin saakka.



Juuri tämä seikka korostaa sitä, kuinka demokratian tehottomuudet tekivät siitä megapoliittisesti hallitsevan aikana, jolloin väkivallan tuoton nousu oli kirjaimellisesti räjähdysmäistä. Massiiviset sotilasmenot – kaikine hukkaan heitetynä – edustavat selvästi alioptimaalista pääoman käyttöönottoa yksityisen hyödyn nimissä. Aiemmin ehdotimme, että vaikka hyvinvointi-valtiot olivat taloudellisesti tehokkaita verrattuna valtiollis-sosialistisiin järjestelmiin, ne ovat paljon vähemmän tehokkaita varallisuuden luomisessa kuin laissez-faire-kolmiot, kuten Hong Kong. Ironista kyllä juuri tämä hyvinvointi-valtion tehottomuus verrattuna esteettömämpään vapaaseen markkinajärjestelmään teki siitä menestyvän teollisuuden megapoliittisissa olosuhteissa.

Miten demokratian aiheuttama tehottomuus sitten edistyi sen menestyksessä väkivallan aikakaudella? Näennäisen paradoksin selvittäminen edellyttää kahden asian tunnistamista:

1. Modernin suvereniteetin menestyksen ydin ei ollut varallisuuden luomisessa, vaan armeijan voiman rakentamisessa, joka pystyi käyttämään ylivoimaista väkivaltaa mitä tahansa muuta valtiota vastaan. Rahaa tarvittiin siihen, mutta raha itsessään ei voita taistelua. Haasteena ei ollut luoda järjestelmää, jossa olisi ollut tehokkain talous tai nopein kasvu, vaan järjestelmä, joka pystyisi keräämään enemmän resursseja ja ohjaamaan ne sotavoimiin. Luonteeltaan sotilasmenoissa rahalliset tuotot ovat hyvin alhaiset tai niiden puuttuminen on tyypillistä.

2. Helpoin tapa saada lupa sijoittaa varoja sellaiseen toimintaan, jolla on vähän tai ei lainkaan suoraa rahallista tuottoa – kuten verojen maksamiseen – on pyytää lupa joltain muulta kuin siltä henkilöltä, jonka rahaa himottavat. Yksi niistä tavoista, joilla hollantilaiset onnistuivat ostamaan Manhattanin 23 dollarin arvoisilla helmineuloilla, oli se, että juuri ne intiaanit, joille he tekivät tarjouksen, eivät olleet niitä, jotka itse omistivat sen asianmukaisesti. Kuten markkinoinnin ammattilaiset sanovat, 'getting to yes' on paljon helpompaa tällaisilla ehdoilla. Oletetaan esimerkiksi, että tämän kirjan kirjoittajina haluaisimme sinun maksavan kopion hintana – etkä sen kansikuvan hintaa – vaan 40 prosenttia vuosituloistasi. Olisimme paljon todennäköisemmin saaneet luvan, jos olisimme kysyneet joltakulta muulta ettemme sinulta. Itse asiassa olisimme vakuuttavampia, jos pystyisimme turvautumaan useiden tuntemattomien ihmisten suostumukseen. Voisimme järjestää tilapäisen vaalin, kuten H. L. Mencken kuvaili – vähemmän liioitellen kuin hän ehkä olisi ajatellut – 'varhaisena varastettujen tavaroiden huutokauppana'. Ja tehdäksemme esimerkin entistä realistisemmaksi, olisimme valmiita jakamaan osan sinulta keräämistämme varoista näille nimettömille sivustakatselijoille heidän tukensa vastineeksi.

Tämä oli se rooli, johon moderni demokratian hyvinvointi-valtio muotoutui. Se oli ylivoimainen järjestelmä teollisella aikakaudella juuri siksi, että se oli sekä tehokas että tehoton siellä, missä sillä oli merkitystä. Se yhdisti yksityisomistuksen tehokkuuden ja varallisuuden luomisen kannustimet mekanismiin, joka mahdollisti pohjimmiltaan rajoittamattoman pääsyn siihen varallisuuteen. Demokratia piti varallisuuden tuottajien taskut avoimina. Se menestyi sotilaallisesti aikana, jolloin väkivallan tuottojen nousu oli huipussaan, juuri siksi, että se vaikeutti tehokkaasti asiakkaiden mahdollisuuksia rajoittaa hallituksen keräämiä veroja tai muita keinoja rahoittaa sotilaallisten resurssien menoja, kuten esimerkiksi inflaation avulla.

### Miksi asiakkaat eivät voineet dominoida

Ne, jotka modernin ajan aikana maksoivat "suojelusta", eivät olleet asemassa evätä suvereenilta resursseja – edes kollektiivisesti toimien – koska se yksinkertaisesti altistaisi heidät toisten, mahdollisesti vihamielisempien valtioiden ylivoimalle. Tämä oli itsestään selvä näkökohta kylmän sodan aikana. Asiakkaat eli veronmaksajat, jotka kantivat suhteettoman suuren osan johtavien länsimaisten teollisuusvaltioiden hallituksen kustannuksista, eivät olleet kyvykkäitä kieltäytymään raskaita veroja maksamasta. Tällöin seurauksena olisi ollut se, että he altistuisivat täydelliselle takavarikoimiselle Neuvostoliiton tai muun aggressiivisen, väkivaltaa järjestäävän ryhmän toimesta.

### Teollistuminen ja demokratia

Kun tarkastellaan pidemmälle aikavälille, massademokratia saattaa osoittautua anakronismiksi, joka ei selviä kauaa teollisen aikakauden päättymisen jälkeen. Tietenkin massademokratia ja kansallisvaltio nousivat yhdessä Ranskan vallankumouksen myötä 1700‑luvun lopulla, todennäköisesti reaktiona reaali- tulojen jyrkkään nousuun. Tulot olivat alkaneet kasvaa merkittävästi Länsi-Euroopassa noin vuonna 1750, osittain lämpimämpien säiden seurauksena. Tämä kehityskausi osui samaan aikaan teknologisen innovaation kanssa, joka syrjäytti käsityöläisten pätevät työt laitteilla, joita pystyivät käyttämään epäammattilaiset – jopa naiset ja lapset. Uusi teollinen laitteisto nosti epäammattilaisten tuloja ja tasaannutti tulonjakoa.

Merkittävin vallankumousta laukaisuttanut tekijä ei ehkä ollutkaan, kuten usein ajatellaan, se ajattelematon idea siitä, että ihmiset kapinoivat parantuvien olosuhteiden myötä. Vielä tärkeämpää saattaa olla se, että kun tulot olivat nousseet tietylle tasolle, varhaismoderneissa valtioissa kävi lopulta käytännölliseksi ohittaa aiemmin neuvotellut yksityiset välikädet ja vaikutusvaltaiset magnaatit sekä siirtyä "suoraan hallittuun" järjestelmään, jossa kansallinen hallitus toimi suoraan yksittäisten kansalaisten kanssa verottaen heitä yhä korkeammilla veroprosenteilla ja vaatimalla huonosti korvattua sotilaspalvelusta vastineeksi erilaisista eduista.[^174]

Koska nousevalla keskiluokalla oli pian tarpeeksi rahaa verotukseen, ei enää ollut yhtä välttämätöntä kuin aiemmin, että hallitsijat neuvottelevat vaikutusvaltaisten maanomistajien tai suurten kauppiaiden kanssa, jotka historioitsija Charles Tillyn mukaan olivat „tilassa estää voimakkaan valtion muodostuminen”, joka „kaapaisi heidän varansa ja rajoittaisi heidän liiketoimintaansa.”[^175] On helppo ymmärtää, miksi hallitukset onnistuivat paremmin keräämään resursseja, kun ne kohtelivat miljoonia kansalaisia yksilöinä sen sijaan, että ne joutuisivat neuvottelemaan suhteellisen harvojen herrojen, herttuoiden, kreiviensä, piispaiden, sopimuspalkkasotureiden, vapaiden kaupunkien ja muiden osavaltaisten yksiköiden kanssa, joiden kanssa Euroopan valtioiden hallitsijoiden oli ennen 1700‑luvun puoliväliä pakko neuvotella.

Nousevat reaalitulot mahdollistivat hallituksille strategian, jossa entistä enemmän resursseja saatiin heidän kontrolliinsa. Vähäiset summat, jotka miljoonilta perittiin veroina, pystyivät tuottamaan enemmän tuloja kuin muutama voimakkaiden henkilöiden maksama suurempi summa. Lisäksi monien kanssa on huomattavasti helpompi toimia kuin harvojen, jotka yleensä eivät ole valmiita luovuttamaan rahaa ja pystyvät paremmin vastustamaan.

Loppujen lopuksi tyypillisellä maanviljelijällä, pienkauppiaalla tai työntekijällä oli äärimmäisen pieni määrä resursseja verrattuna itse valtioon. Tavallisen yksityishenkilön ei olisi ollut edes kaukaa mahdollista, että hän olisi voinut neuvotella valtion kanssa veroprosentin alentamisesta tai vastustaa hallituksen suunnitelmia ja politiikkaa, jotka uhkasivat hänen etujaan, ainakin Ranskan vallankumousta edeltävänä aikana Länsi-Euroopassa. Juuri tätä kuitenkin vahvat yksityiset suurmiehet olivat tehneet vuosisatojen ajan ja jatkaisivat tekemistään. He vastustivat ja neuvotelivat hallitsijoiden kanssa tehokkaasti, rajoittaen heidän kykyään kaapata resursseja.

> „Sotaan lähteminen nopeutti siirtymistä epäsuorasta hallinnosta suoraan hallintaan. Melkein mikään sotaa käyvä valtio huomaa, ettei se pysty maksamaan ponnisteluistaan sekä kertyneistä varoistaan että nykyisistä tuloistaan. Melkein kaikki sodankäyvät valtiot lainaa laajasti, nostavat veroja ja kaappaavat taistelun keinot – mukaan lukien miehet – epäröiviltä kansalaisilta, joilla on muita käyttötarkoituksia resursseilleen.”[^176]  
> – CHARLES TILLY

Puolan esimerkki 1700‑luvun puolivälistä havainnollistaa tätä täydellisesti. Vuonna 1760 Puolan kansallisarmeijassa oli kahdeksantoista tuhatta sotilasta. Tämä määrä oli mitätön verrattuna naapurivaltojen, kuten Itävallan, Preussin ja Venäjän, armeijoihin, joista vähintään yksi pystyi hallitsemaan säännöllisen armeijan, jonka joukko oli 100 000 sotilasta. Itse asiassa Puolan kansallisarmeija vuonna 1760 oli pieni jopa verrattuna muihin Puolan aseistetun alan yksiköihin, sillä Puolan aateliston yhdistetyt joukot olivat kolmekymmentä tuhatta miestä.[^177]

Jos Puolan kuningas olisi pystynyt olemaan suoraan vuorovaikutuksessa miljoonien yksittäisten puolalaisten kanssa ja verottamaan heitä suoraan sen sijaan, että hän olisi ollut rajoittunut saamaan resursseja epäsuorasti vaikutusvaltaisten puolalaismagnattien panostusten kautta, on vähäinen kiistämättä, että Puolan keskushallinto olisi voinut kerätä huomattavasti enemmän tuloja ja siten rahoittaa suuremman armeijan.

Tavallisia ihmisiä vastaan, jotka eivät pystyneet toimimaan yhdessä miljoonien muiden tavallisten kansalaisten kanssa, keskusviranomaiset osoittautuivat kaikkialla vastustamattoman voimakkaiksi. Vuonna 1760 Puolan kuninkaalla ei kuitenkaan ollut mahdollisuutta verottaa kansalaisiaan suoraan, vaan hänen täytyi turvautua herroihin, varakkaisiin kauppiaisiin ja muihin merkittäviin henkilöihin, jotka muodostivat pienen ja yhtenäisen ryhmän. He pystyivät toimimaan yhdessä estääkseen kuningasta ottamasta heidän resurssejaan haltuunsa ilman heidän suostumustaan. Koska puolalaisella aatelistolla oli huomattavasti enemmän joukkoja kuin kuninkaalla, hänellä ei ollut mitään varaa vaatia mitään enempää.

Kävi ilmi, että sotilaallinen haitta, joka syntyi varakkaiden ja vaikutusvaltaisten esteiden kiertämättä jättämisestä resurssien keräämisessä, oli ratkaiseva Väkivallan aikakaudella. Muutamassa vuodessa Puola lakasi olemasta itsenäinen valtio, kun sen valloittivat Itävalta, Preussi ja Venäjä – kolme maata, joiden armeijat olivat monta kertaa suuremmat kuin Puolan pieni joukko. Kussakin näistä maissa hallitsijat löysivät keinoja ohittaa varakkaiden kauppiaiden ja aateliston kyky rajoittaa heidän resurssiensa riistämistä.

### Ranskan vallankumouksen jälkeen

Ranskan vallankumous johti vieläkin suurempaan armeijoiden kokojen kasvuun, mikä osoitti demokraattisen strategian voiman, kun väkivallan tuottojen määrä kasvoi. Vallankumouksesta lähtien solmitut sopimukset merkitsivät ennennäkemättömän astetta vähemmistöjen elämään puoltavan osallistumisen lisääntymistä vastineeksi siitä, että tavalliset kansalaiset osallistuivat sotiin palkkasotilaisten sijaan ja maksoivat kasvavan vero-rasituksen nousevista tuloistaan.

Kuten Tilly sanoi,

> Valtion vaikutusalue laajeni paljon sen sotilaallista ydintä pidemmälle, ja kansalaiset alkoivat vaatia siltä laajasti suojaa, oikeudenmukaista tuomioistuinjärjestelmää, tuotantoa ja jakelua. Kun kansalliset lainsäädäntöelimet laajensivat toimivaltaansa verotuksen hyväksynnän tuolle puolen, ne joutuivat vaatimusten kohteeksi kaikkien hyvin organisoituneiden ryhmien taholta, joiden etuja valtio vaikutti tai saattoi vaikuttaa. Suora hallinto ja massapohjainen kansallinen politiikka kehittyivät rinnakkain ja vahvistivat toisiaan voimakkaasti.[^178]

Sama logiikka, joka päti 1700-luvulla, pysyi voimassa aina vuoteen 1989 asti, jolloin Berliinin muuri kaatui. Teollistumisen edetessä epäpätevien töiden palkat nousivat jatkuvasti, minkä seurauksena massademokratiasta tuli entistä tehokkaampi tapa optimoida resurssien hyödyntämistä. Tämän seurauksena hallituksen vaatimukset kasvoivat, lisäten keskimääräisessä teollisuusmaassa vuosituloihin kohdistuvia vaatimuksia noin 0,5 prosentilla koko 1900-luvun ajan.

Ennen vuotta 1989 demokratia nousi teollisessa aikakaudessa sotilaallisesti tehokkaimmaksi hallintomuodoksi juuri siksi, että demokratia teki valtion resurssien haltuunoton asettamisesta tehokkaita rajoja vaikeaksi tai mahdottomaksi. Antelias hyvinvointietujen tarjoaminen kaikille houkutteli enemmistön äänestäjistä käytännössä hallituksen työntekijöiksi. Tämä muodostui johtavaksi poliittiseksi piirteeksi kaikissa johtavissa teollisuusmaissa, sillä äänestäjät olivat heikossa asemassa valvoessaan hallitusta suojelupalveluiden asiakkaina. He eivät ainoastaan kohtanneet kommunististen järjestelmien aggressiivista uhkaa, jotka pystyivät tuottamaan valtavia resursseja sotilaallisiin tarkoituksiin, koska valtio hallitsi koko taloutta, vaan todellista veronmaksajien kontrollia hallituksen toiminnassa oli toisestakin syystä käytännössä mahdotonta.

Miljoonat tavalliset kansalaiset eivät pysty toimimaan tehokkaasti yhdessä suojellakseen omia etujaan. Yhteistyön esteet ovat korkeat, ja yksittäisen henkilön saama hyöty ryhmän yhteisten etujen puolustamisesta on minimaalinen, minkä seurauksena miljoonat tavalliset kansalaiset eivät onnistu yhtä hyvin pidättelemään varallisuuttaan hallitukselta kuin pienemmät, parempien kannustimien omaavat ryhmät.

Muut tekijät säilyvät samoina, niin odottaisitkin, että massademokratiassa hallitus ottaa haltuunsa suuremman osan kokonaisresursseista kuin oligarkiassa tai järjestelmässä, jossa suvereniteetti on hajautunutta ja suurmiehet käyttävät sotilaallista valtaansa ja mobilisoivat omia armeijoitaan – kuten se tapahtui kaikkialla varhaisessa modernissa Euroopassa ennen 1700-lukua.

Näin ollen yksi ratkaiseva, vaikka harvoin tutkittu syy länsimaiden demokratian kasvuun on neuvottelukustannusten suhteellinen merkitys aikana, jolloin väkivallan tuotto kasvoi. Resurssien kerääminen harvoilta oli aina kalliimpaa kuin monilta.

Suhtalaisen pieni, eliittinen rikkaiden ryhmä edustaa yhtenäisempää ja tehokkaampaa kokonaisuutta kuin suuri kansalaisten joukko. Pienellä ryhmällä on vahvemmat kannustimet toimia yhdessä, ja se on lähes väistämättä tehokkaampi suojelemaan etujaan kuin massaryhmä.'[^179] Ja vaikka useimmat ryhmän jäsenet päättäisivät olla yhteistyössä missään yhteisessä toiminnassa, muutamat rikkaat saattavat kyetä käyttämään riittävästi resursseja asian hoitamiseksi.

Demokraattisen päätöksenteon myötä valtio pystyi käyttämään valtaa paljon kokonaisemmin miljoonien ihmisten yli, joiden on ollut vaikea toimia kollektiivisesti omaksi edukseen, kuin se kykenee vaikuttamaan pienempään ryhmään, joka pystyy helpommin ylittämään keskittyneiden etujen puolustamisen organisatoriset haasteet. Demokratialla oli vieläkin vakuuttavampi etu: se loi legitimisoivan päätössäännön, joka salli valtion hyödyntää varakkaiden resursseja ilman, että heidän suostumustaan tarvittaisiin suoraan. Lyhyesti sanottuna demokratia päätösmekanismina oli erinomaisesti sovitettu teollisajan megapoliittisiin olosuhteisiin. Se täydensi valtiota, sillä se mahdollisti sotilaallisen voiman keskittymisen niiden käsiin, jotka sitä johtivat, aikana jolloin käytettävän voiman määrä oli tärkeämpää kuin sen mobilisointitehokkuus.

Tämä osoitettiin ratkaisevasti Ranskan vallankumouksessa, joka kasvatti sotilaallisen voiman määrää taistelukentällä. Sen jälkeen kilpailukykyisillä valtioilla ei ollut muuta vaihtoehtoa kuin yhtenäistää toimintansa samankaltaiseksi, jolloin legitimiteetti sidottiin lopulta demokraattiseen päätöksentekoon. Yhteenvetona voidaan todeta, että demokraattinen valtio menestyi viimeisten kahden vuosisadan aikana näistä piilossa olleista syistä:

1. Väkivallan tuottamat hyödyt nousivat, mikä teki voiman suuruudesta tärkeämmän hallintaperiaatteen kuin tehokkuus.  
2. Tulot nousivat riittävästi elintason yläpuolelle, jolloin valtiolle tuli mahdollista kerätä suuria määriä kokonaisresursseja ilman pakkoa neuvotella vastustavien vaikutusvaltaisten aatelisten kanssa.  
3. Demokratia osoittautui riittävästi yhteensopivaksi vapaiden markkinoiden toiminnan kanssa, mikä puolestaan edisti kasvavien varallisuuden määrien tuottamista.  
4. Demokratia helpotti hallituksen joutumista sen "työntekijöiden" valtaan, mikä varmisti, että menojen, mukaan lukien sotamenojen, leikkaaminen olisi vaikeaa.  
5. Demokratia päätöksentekoperiaatteena osoittautui tehokkaaksi vastalääkkeeksi varakkaiden halulle toimia yhdessä rajoittaakseen valtioiden mahdollisuuksia verottaa tai muuten suojella omaisuuttaan hyökkäyksiltä.

Demokratiasta tuli sotilaallisesti voittava strategia, koska se mahdollisti valtioon keskittämisen enemmän resursseja. Verrattuna muihin suvereniteetin muotoihin, joiden laillisuus perustuivat muihin periaatteisiin – kuten feodaaliseen verotukseen, kuninkaiden jumalalliseen oikeuteen, yritysten uskonnolliseen velvollisuuteen tai rikkaiden vapaaehtoisiin lahjoituksiin – massademokratia osoittautui sotilaallisesti tehokkaimmaksi, sillä se oli varmin keino kerätä resursseja teollisessa taloudessa.

> 'Kansa, kulttuurisesti määritelty yhteisö, on moderniuden korkein symbolinen arvo; sille on annettu lähes pyhät ominaisuudet, joita vain uskonto voi vastata. Itse asiassa tämä lähes pyhä luonne saa juurensa uskonnosta. Käytännössä kansasta on tullut joko moderni, maallinen uskonnon korvike tai sen voimakkain liittolainen. Nykyajan aikana kansakunnan tuottamia yhteisöllisiä tunteita arvostetaan suuresti ja niitä pidetään ryhmälojaalisuuden perustana... Että moderni valtio usein hyötyisi tästä, ei pitäisi yllättää ottaen huomioon sen ylimmän tason valta.'[^180] - JOSEPH R. LLOBERA

## Nationalismi

Samoin voidaan sanoa nationalismista, josta tuli massademokratian luonnollinen jatkumo. Valtioissa, jotka pystyivät hyödyntämään nationalismia, havaittiin mahdollisuuksia mobilisoida suurempia armeijoita pienemmällä kustannuksella. Nationalismi oli keksintö, joka mahdollisti valtion sotilaallisen vaikuttavuuden mittakaavan kasvattamisen. Kuten itse politiikka, myös nationalismi on suurelta osin moderni ilmiö. Sosiologi Joseph Llobera on rikkaasti dokumentoidussa kirjassaan nationalismin noususta osoittanut, että kansa on kuvitteellinen yhteisö, joka syntyi suurelta osin tapana mobilisoida valtion valtaa Ranskan vallankumouksen aikana. Kuten hän toteaa: 'Nykyajan merkityksessä kansallinen tietoisuus on ollut olemassa vasta Ranskan vallankumouksesta lähtien, siitä ajasta, jolloin vuonna 1789 Perustajankokous rinnastui Ranskan kansaan.'[^181]

Nationalismi helpotti vallan mobilisointia ja suurten ihmisjoukkojen hallintaa. Valtiot muodostuivat korostamalla niitä yhteisiä piirteitä, joita ihmiset jakoivat – erityisesti puhuttua kieltä – mikä mahdollisti hallinnon ilman välikäsien puuttumista. Tämä yksinkertaisti byrokraattisia tehtäviä: määräykset, jotka julkistetaan yhdellä kielellä, voidaan toimeenpanna nopeammin ja selkeämmin kuin ne, jotka on käännettävä lukuisille kielille. Nationalismi pyrki siis laskemaan suurten alueiden hallinnollisia kustannuksia. Ennen nationalismin aikaa moderni valtio tarvitsi apunaan herroja, herttuoja, kreivejä, piispejä, vapaita kaupunkeja sekä muita yritys- ja etnilliselle yhteisölle tyypillisiä välikäsiä – veronkiskojista sotilasurakoitsijoihin ja palkkasotureihin – kerätäkseen tuloja, kasvattaakseen armeijoitaan ja hoitaakseen muita hallinnollisia tehtäviä.

Nationalismi laski myös ratkaisevasti sotilashenkilöstön mobilisointikustannuksia kannustamalla ryhmäidentifikaatioon valtion etujen kanssa. Ryhmämunan hyödynnettäessä valtion eduksi oli niin merkittävä etu, että useimmat valtiot – jopa väitetysti internationalistinen Neuvostoliitto – yhtenäistyivät nationalismin täydentävänä ideologiana.

Pidemmässä perspektiivissä nationalismikin on yhtä paljon poikkeavuus kuin valtio itse. Kuten historioitsija William McNeill on dokumentoinut, polyetniset suvereniteetit olivat aikoinaan normi.[^182]

McNeillin sanoin, 'Ajatus siitä, että hallituksella olisi oikeus hallita ainoastaan yhden etnisen ryhmän kansalaisia, alkoi kehittyä Länsi-Euroopassa keskiajan loppua kohti.'[^183] Yksi varhaisista nationalistisista entiteeteistä oli Preussin liitto (Preussicher Bund), joka muodostettiin vuonna 1440 vastustamaan Teutonivallan – eli teutonisen ritarikunnan – vallankäyttöä. Joitakin ritarikunnan ominaisuuksia on aiemmin korostettu radikaalina esimerkkinä suvereniteetista, joka eroaa kansallisvaltiosta. Teutoninen ritarikunta oli eräänlainen annettu yhdistys, jonka jäsenistä melkein kukaan ei ollut syntyperäistä Preussiassa. Sen päämaja siirtyi useaan otteeseen Bremestä ja Lübeckistä Jerusalemiin, Akreen, Venetsiaan ja edelleen Marienbergiin Vistulan varrella. Eräänä aikana se hallitsi Burzenlandin aluetta Transilvaniassa. Ei siis ole yllättävää, että näin valtioista poikkeava suvereniteetti herätti varhaisen yrityksen mobilisoida kansallistunnetta vallan järjestämisen välineeksi. Osoituksena siitä, kuinka erilainen varhainen nationalismi oli myöhempiin muotoihin verrattuna, saksankieliset Preussin liiton aateliset vetoomusivat Puolan kuninkaalle asettamaan Preussan Puolan hallintaan – pääasiassa siksi, että jo silloin Puolan kuningas oli suhteellisen heikko monarkki, jolta ei odotettu hallitsevan yhtä ankarasti kuin Teutoninen ritarikunta.

Varhaisina ilmenemisissään nationalismi astui kuvaan juuri ennen ruuti- ja pölyvallankumousta. Se jatkoi kehitystään varhaismodernin valtion myötä ja sai kvanttisen harppauksen merkityksessään Ranskan vallankumouksen aikaan. Uskomme, että nationalismia voiman ideana on jo alkanut hiipua. Se saavutti luultavasti huippunsa Woodrow Wilsonin yrityksessä antaa jokaiselle Euroopan etniselle ryhmälle oma valtionsa ensimmäisen maailmansodan lopulla. Nyt se on reaktionäärinen voima, joka roihuaa paikoissa, joissa tulot ovat laskeneet ja näkymät heikentyneet, kuten esimerkiksi Serbiassa.

Kuten myöhemmin tarkastelemme, odotamme nationalismin olevan merkittävä yhdistävä teema matalasti koulutettujen ihmisten keskuudessa, jotka ovat nostalgisia pakotetun järjestelyn aikoihin, kun hyvinvointivaltio romahtaa Länsi-demokratiassa. Et ole vielä nähnyt mitään. Useimmille länsimaalaisille kommunismin kuoleman seuraukset ovat vaikuttaneet suhteellisen lieviltä. Olet nähnyt sotilaallisen menojen laskun, alumiinihintojen jyrkän pudotuksen ja uuden lähteen jääkiekkoilijoiden hankkimisessa NHL:lle. Se on hyvä uutinen – uutinen, josta suurin osa 1900-luvulla täysi-ikäisiksi nousseista voi taputtaa, erityisesti jos he ovat jääkiekon ystäviä. Suurin osa uutisista, jotka osoittautuvat vähemmän suosituiksi, on vielä edessä.

Teollisajan myötä megapoliittiset olosuhteet, joita demokratia aikanaan täytti, ovat nopeasti katoamassa. Siksi on epäilyttävää, säilyykö massademokratia ja hyvinvointivaltio pitkään informaatiokauden uusissa megapoliittisissa olosuhteissa.

> 'Kongressi ei ollut demokratian temppeli, vaan lainvaihdon kauppapaikka.' - ALBERTO FUJIMORI, presidentti of Peru

Niin tosiaan tulevaisuuden historioitsijat saattavat raportoida, että olemme jo nähneet ensimmäisen postmodernin vallankaappauksen – Peru kongressin uskomattoman lukitsemisen vuonna 1993. Tämä ei todellakaan ollut tapahtuma, joka olisi herättänyt paljoa suopeaa huomiota johtavissa teollisissa demokratioissa. Mutta se saattaa ajan saatossa osoittautua merkityksellisemmäksi kuin perinteiset analyytikot arvailevat. Harvat, jotka siitä ovat ajatelleet, kokevat sen vain toisena vallanhankintana, joka on tullut ärsyttävän tutuksi Latinalaisen Amerikan historiassa. Me näemme sen kuitenkin ehkä ensimmäisenä askeleena delegitimoida hallintomuoto, jonka välitön megapoliittinen tarkoitus on alkanut kadota siirtyessä informaatiokauteen. Fujimorin kongressin sulkeminen on oire lopullisesta poliittisten lupausten menettämästä arvosta. Vastaava kohtalo voisi kohdata myös muita parlamentteja, kun niiden luottamus on kulutettu.

Teknologian muutos, joka rappeuttaa teollisuutta, on jumittanut monen maan hallitukset järjestelmiin, jotka eivät enää toimi – tai toimivat huonosti. Erityisesti lainsäätäjät näyttävät yhä enemmän epätoimivilta. Ne säätävät lakeja, jotka saattoivat olla vain typeriä vielä viisikymmentä vuotta sitten, mutta ovat tänään vaarallisia. Tämä oli erityisen ilmeistä Peruissa, jossa valtion sisäinen suvereniteetti oli melkein romahtanut vuoteen 1993 mennessä.

> 'Hyökkäykset, sieppaukset, raiskaukset ja murhat ovat kulkeneet käsi kädessä yhä aggressiivisempien ajo- ja liikennekäyttäytymismallien sekä turvattomien katujen kanssa. Poliisi on vähitellen menettänyt kontrollin tilanteesta, ja jotkut sen jäsenet ovat joutuneet skandaalien keskelle ja kehittyneet kokeneiksi rikollisiksi… Ihmiset ovat vähitellen totutelleet elämään lain ulkopuolella. Varkaudet, laittomat takavarikoinnit ja tehtaiden kaappaukset ovat tulleet jokapäiväisiksi ilmiöiksi.'[^184] - HERNANDO DE SOTO

### Peru raunioina

Eräässä mielessä Peru ei enää vuonna 1993 ollut moderni kansallisvaltio. Sillä oli yhä lippu ja armeija, mutta suurin osa sen instituutioista oli raunioina. Jopa vankilat olivat joutuneet vankien käsiin. Tämän hajaantumisen taustalla oli useita syitä, mutta useimmat asiantuntijoiden selitykset eivät tavoittaneet ydintä. Peru oli varhaisessa vaiheessa teknologisen muutoksen uhri, joka tehden suljetuista talouksista toimimattomia ja heikentäen keskusvallan auktoriteettia kaikkialla. Nämä megapoliittiset paineet pahentuivat, koska päätöksentekoelimet, kuten Perun kongressi, vääristyneiden kannustimien vuoksi kerryttivät yhteen juuri ne ongelmat, jotka niiden olisi pakko ratkaista.

Perun edustuksellinen demokratia oli kuin pari ladattuja noppia. Valtion suurenemisen päätösmekanismina se oli vertaansa vailla. Mutta kun uudet olosuhteet vaativat vallan delegoimista, ne sisäiset vinoumat, jotka tekivät demokratiasta hyödyllisen vanhoissa megapoliittisissa olosuhteissa, muuttuivat yhä toimimattomammiksi. Kongressin hyväksymät lait tuhosivat nopeasti kaiken arvon pohjan ja lain kunnioituksen. Kuten de Soto kiteytti teoksessaan *The Other Path*, 'Pienet eturyhmät riitelevät keskenään, aiheuttavat konkurssitilanteita, sekoittavat virkamiehiä. Hallitukset jakavat etuoikeuksia. Lain avulla annetaan ja poistetaan paljon enemmän kuin moraali sallii.' [^185]

Sellainen kongressi kuin Perussa, joka on täysin alistunut erityisryhmien etujen vallassa, omaa samanlaisen moraalisen arvovaltaisuuden kuin ryöstäjien väijy, jotka huutokaupassa myyvät varastettua omaisuutta. Se teki vapaasta markkinataloudesta laittoman ja siten teki laista naurettavan.

Kuten de Soto kirjoittaa Fujimorin aikaisesta ajasta:

> Täydellinen päämäärien ja keinojen kumoaminen on kääntänyt perulaisen yhteiskunnan elämän ylösalaisin siihen pisteeseen, että on tekoja, jotka, vaikka virallisesti rikollisina, eivät enää herätä kollektiivisessa tiedostuksessa tuomitsemista. Esimerkiksi salakuljetus on tästä yksi tapaus. Kaikki, aristokraattisesta naisesta nöyrimmin mieheen, hankkivat salakuljetettuja tavaroita. Kenelläkään ei ole niukkuutta siinä; päinvastoin, sitä pidetään eräänlaisena haasteena yksilölliselle kekseliäisyydelle tai kostonaan valtiota vastaan. Tämä väkivallan ja rikollisuuden tunkeutuminen jokapäiväiseen elämään on kulkenut käsi kädessä kasvavan köyhyyden ja puutteen kanssa. Yleisesti ottaen perulaisten todellinen keskitulo on laskenut tasaisesti viimeisten kymmenen vuoden aikana ja on nyt 20 vuotta sitten ollut sen tasolla.[^186]

De Soto kuvaili sitä, kuinka groteskin oikeusjärjestelmän hylkääminen mustalle markkinalle, joka oli jo käynnissä ennen Fujimorin sitä, että hän lukitsi kongressin, oli 'näkymätön vallankumous.'

Me olemme myönteisiä vapaakaupan eduista, mutta paljon vähemmän myönteisiä siinä lupauksessa, että yhteiskunta, jossa laki on yhtä rappeutunutta kuin raha, olisi mahdollista. Maailma, jonka de Soto kuvaili Perussa ennen vuotta 1993, oli "Clockwork Orange" –maailma, jossa liian keskitetyt ja toimimattomat valtion instituutiot kirjaimellisesti tuhosivat kansalaisyhteiskuntaa.

Juuri tätä Fujimori aikoi muuttaa. Hän oli onnistunut leikkaamaan inflaatiota sammuttamalla rahapainot. Hän onnistui myös irtisanomaan viisikymmentä tuhatta valtion työntekijää ja vähentämään joidenkin tukien määrää. Hän oli ottanut askeleen kohti budjetin tasapainottamista. Hänen uudistusohjelmansa sisälsi laajat suunnitelmat vapaiden markkinoiden luomiseksi ja teollisuuden yksityistämiseksi. Kuitenkin, kuten entisessä Neuvostoliitossa, suurin osa Fujimorin uudistuksen tärkeistä elementeistä odotti vielä hyväksyntää vuonna 1993 – mukaan lukien ensimmäinen suuri yksityistämiskierros, joka koski valtion pankkeja, kaivosyhtiöitä ja utiliteetteja. Sen sijaan, että nämä välttämättömät ehdotukset olisi toimeenpantu, Perun kongressi, aivan kuten Moskovassa Yeltsinin uudistuksia haastanut venäläinen kongressi, pyrki palaamaan menneeseen. Heidän suunnitelmansa oli palauttaa tuet tyhjältä valtion kassasta, täydentää palkkalistaa ja suojella kaikkia vakiintuneita etuja – erityisesti byrokratiaa – aivan kuten voit odottaa työntekijöidensä hallitsemalta hallitukselta.

Fujimori väitti, että Perun kongressi laiskottelisi ja olisi korruptoitunutta, mikä lähes kaikki hyväksyivät. Hän lisäsi, että kongressin laiskottelu ja korruptio estivät Perun romahtaneen talouden uudistamisen ja vaikeuttivat väkivaltaisten huumeterroristien sekä nihilististen Sendero Luminoso (Shining Path) –gerillojen hyökkäyksen torjumista.

### 70 prosentin ratkaisu

Fujimori sulki siis kongressin – teko, joka saattoi viitata siihen, että hän oli autoritäärinen kuten moni varhaisempi latinamerikkalainen johtaja. Mutta me ajattelimme, ja myös totesimme silloin, että Fujimori oli osannut oikein tunnistaa perimmäisen esteen uudistukselle. Amerikan toimituskirjoittajien ja valtiollisen osaston virkamiesten ylenpalttiset, viralliset kehräykset Perun kongressista eivät olleet Perun kansan näkemyksen mukaisia. Sillä aikaa kun pohjoisamerikkalaiset jatkoivat ikään kuin Perun kongressi olisi vapauden ja sivistyksen ruumiillistuma, perulaiset kannustivat. Presidentti Fujimorin suosio nousi yli 70 prosenttiin, kun hän lähetti kongressin kotiin. Myöhemmin hänet valittiin toiselle kaudelle murskavoittajina. Suurin osa kansalaisista näki heidän lainsäädäntöelimensä ennemminkin esteenä hyvinvoinnilleen kuin ilmaisuna heidän oikeuksistaan. Vuonna 1994 Perun reaalinen talouskasvu nousi 12,9 prosenttiin – planeetan korkeimmaksi.

### Poliittisten lupauksien deflaatio

Koimme Perun kaaoksen enemmänkin merkkinä laajemman siirtymäkriisin alkuvaiheesta kuin paluuna menneisyyden diktatuurien aikaan. Voit odottaa näkeväsi huonon hallinnon kriisejä monissa maissa, kun poliittiset lupaukset turpoavat ja hallitukset kuluttavat luottokykynsä loppuun. Lopulta on aika syntyä uusille institutionaalisille muodoille, jotka pystyvät turvaamaan vapauden uusissa teknologisissa olosuhteissa samalla kun ne ilmentävät ja elävöittävät kaikkien kansalaisten yhteisiä etuja.

Vain harvat ovat alkaneet pohtia teollishallinnon joidenkin instituutioiden ja postteollisen yhteiskunnan megapolitiikan yhteensopimattomuutta. Riippumatta siitä, tunnustetaanko nämä ristiriidat avoimesti vai eivät, niiden seuraukset tulevat käymään yhä ilmeisemmiksi, kun poliittisten epäonnistumisten esimerkit kasaantuvat ympäri maailmaa. Modernin ajan hallintoinstituutiot heijastavat vuosisatoja vanhoja megapoliittisia olosuhteita. Informaatioaika vaatii uusia edustuksen mekanismeja kroonisen toimimattomuuden ja jopa yhteiskunnallisen romahduksen välttämiseksi.

Kun Berliinin muuri kaatui vuonna 1989, se ei ainoastaan merkinnut kylmän sodan loppua; se oli myös ulkoinen merkki hiljaisesta maanjäristyksestä maailman valtarakenteiden perustoiminnoissa. Se merkitsi pitkän väkivallan tuoton nousukauden päättymistä. Kommunismin romahtaminen, jonka ennustimme jo vuonna 1987 teoksessamme Blood in the Streets ja vielä aikaisemmin kuukausittaisessa uutiskirjeessämme Strategic Investment, ei ollut pelkästään ideologian hylkäämistä. Se oli ulkoinen merkki merkittävästä kehityssuunnasta väkivallan historiassa viimeisten viiden vuosisadan aikana. Jos analyysimme pitää paikkansa, yhteiskunnan järjestäytymisen on muututtava heijastamaan kasvavia mittakaavan epäedullisuuksia väkivallan käytössä. Ne rajat, joiden sisällä tulevaisuuden on sijaittava, on nyt määritelty uudelleen.

[^163]: Lainattu Tillyltä, op. cit., s.84.

[^164]: Katso John Keegan, *A History of Warfare* (Lontoo: Hutchinson, 1993), s. 321.

[^165]: Jim Taylor ja Watts Wacker, The 500-Year Delta: What Happens After What Comes Next. New York: HarperCollins, 1997, s. 38–39.

[^166]: Ibid., s. 39.

[^167]: The Cambridge Ancient History, op. cit., s. 263–64.

[^168]: Cook et al., op. cit., s. 268.

[^169]: Lisätietoja hydraulisten yhteiskuntien logiikasta, katso Karl A. Wittfogel, *Oriental Despotism: A Comparative Study of Total Power* (New Haven: Yale University Press, 1957).

[^170]: Tilly, op. cit., s. 28.

[^171]: Lane, 'Consequences of Organized Violence,' op. cit., s. 406.

[^172]: Ibid.

[^173]: Ibid., s. 412.

[^174]: Tilly, op. cit., s.96–126.

[^175]: Ibid., s.130.

[^176]: Ibid., s.110.

[^177]: Tämä esimerkki ibid.:stä, s.139.

[^178]: Ibid., s.115.

[^179]: Katso Mancur Olson, *The Logic of Collective Action* (Cambridge: Harvard University Press, 1965).

[^180]: Josep R. Llobera, *The God of Modernity: The Development of Nationalism in Western Europe* (Oxford: Berg Publishers, 1994), s. ix–x.

[^181]: Sama lähde, s. xiii.

[^182]: Katso William McNeill, *Polyethnicity and National Unity in World History* (Toronto: University of Toronto Press, 1986).

[^183]: Sama lähde, s. 7.

[^184]: Hernando de Soto, *The Other Path* (New York: Harper & Row, 1989).

[^185]: Ibid.

[^186]: Ibid., p.6.