# Kansallisvaltion elämä ja terveys

::: {.content-hidden when-format=latex}
*Democracy and Nationalism as Resource Strategies in the Age of Violence*
:::

> "Kaikista tärkeintä on, että sodassa menestyminen riippuu siitä, että on tarpeeksi rahaa varmistaa kaikkea, mitä hankkeelle tarvitaan." [^163] - ROBERT DE BALSAC, 1502

## Historian romut

9. ja 10. marraskuuta 1989 televisio lähetti maailmalle kuvia innostuneista itäberliiniläisistä, jotka purkivat Berliinin muuria vasaroilla. Rohkeiden yrittäjien joukosta joukossa nousti esiin halukkuus kerätä muurista paloja, joita myöhemmin markkinoitiin laajalle pääomallisille keräilyesineinä – esimerkiksi muistoesineinä toimivina paperipainoina. Näiden raunioiden kauppaa hoiti intensiivisesti vuosia sen jälkeen. Vielä kirjoittaessamme voi satunnaisesti törmätä pienlehtien ilmoituksiin, joissa myydään vanhaa Itä-Saksan betonia sellaisina paloina, joiden hinnat ovat yleensä korkealuokkaisen hopeamalmion ohjaamia. Uskomme, että Berliinin muurin paperipainojen ostaneiden ei kannata kiirehtiä niiden myymistä. He omistavat muistoesineitä jostain suuremmasta kuin kommunismin romahtamisesta. Uskomme, että Berliinin muuri muodostui historian merkittävimmäksi romuparvoksi siitä lähtien, kun San Giovannin muurit räjäytettiin lähes viisi vuosisataa aiemmin, helmikuussa 1495.[^164]

Ranskalaisskuningas Charles VIII:n toimesta San Giovannin murskaaminen oli ensimmäinen laukaisu Ampumamyrskyräjähdyksessä. Se merkitsi feodaalivaiheen loppua ja teollistumisen aikakauden alkua, kuten aiemmin esittelimme. Berliinin muurin tuhoaminen merkitsee yhtä historiallisen käännekohdan hetkeä, siirtymää teollisesta aikakaudesta uuteen tiedon aikakauteen. Ei ole koskaan nähty niin suurta symbolista tehokkuuden voittoa valtaa vastaan. Kun San Giovannin muurit kaatuivat, se oli selkeä osoitus siitä, että taloudelliset tuotto-odotukset väkivallan suhteen olivat nousseet jyrkästi. Berliinin muurin kaatuminen kertoo jotain täysin erilaista – nimittäin sen, että väkivallan tuottojen osuus on nyt laskussa. Tämä on ilmiö, jonka merkitystä harva on edes alkanut tunnistaa, mutta jolla on dramaattisia seurauksia.

Joissain tässä luvussa käsiteltävien seikkojen takia Berliinin muuri saattaa osoittautua paljon symbolisemmaksi kuvaamaan koko teollisen kansallisvaltion aikakautta kuin mitä sinäkin berliiniläisten tai kaukana olevien miljoonien katsojien sinä iltana ymmärsivät. Berliinin muuri rakennettiin aivan eri tarkoitusta varten kuin San Giovannin muurit – se suunniteltiin estämään sisäpuolella olevien ihmisten pakeneminen sen sijaan, että se estäisi ulkopuolisten pedonkaltaisten pääsyä sisään. Jo pelkkä tuo seikka kertoo paljon siitä, kuinka valtion valta on kasvanut 1400-luvulta 1900-lukuun – ja useammallakin tavalla.

Vuosisatojen ajan kansallisvaltio teki kaikista ulospäin suuntautuneista muureista tarpeettomia. Korkea monopoli, jota valtio käytti niillä alueilla, joilla se ensin valtaansa vakiinnutti, sai nämä muurit olemaan sekä sisäisesti rauhallisempia että sotilaallisesti pelottavampia kuin mikään aiemmin nähty suvereniteetti. Valtio käytti suurimmaksi osaksi suureksi osaksi aseistamattoman väestön tuottamia resursseja murskatakseen pienimuotoiset saalistajat. Kansallisvaltio muodostui historian menestyneimmäksi työkaluksi resurssien haltuun ottamisessa. Sen menestys perustui siihen, että se kykeni paremmin keräämään kansalaistensa vaurautta.

> "MTV on enemmän kuin musiikkivideotoimittaja – se on myös äänitysteollisuuden promootiotyökalu. Se on ensimmäinen todella globaali verkko, ensimmäinen verkko, joka toimittaa äärettömän ohjelmavirran lähes jokaiseen maailman maahan. Tämän prosessin myötä MTV luo yleisölleen, lapsille ja nuorille aikuisille, yhteisen globaalin todellisuuden tunteen. Uusimman tutkimuksen mukaan nuoret ympäri planeettaa jakavat yhä useammin paitsi yhteisiä pop-ikoneja ja makuja, myös yhteisiä odotuksia urastaan, yhteisiä arvojoukkoja siitä, mikä elämässä on merkityksellistä ja mistä tulee pelätä, sekä yhteisen mielentilan siitä, että politiikalla on vähemmän merkitystä kuin heidän omilla kyvyillään vaikuttaa tulevaisuuteensa."[^165] - Jim Taylor ja Watts Wacker, The 500-Year Delta: What Happens After What Comes Next

### "Rakasta sitä tai lähde (ellei olet rikas)"



Ennen kuin siirtyminen kansallisvaltiosta uuden tietoyhteiskunnan suvereniteetteihin on saatu päätökseen, monet suurimpien ja vaikutusvaltaisimpien länsimaiden asukkaat – aivan kuten Itä-Berliinissä vuonna 1989 toimineet vastaavat – suunnittelevat keinoja päästä eroon hallinnostaan. Siihen sukupolveen, jotka ovat saavuttaneet täysi-ikäisyyden ennen toista maailmansotaa tai kylmän sodan alkuvuosina, rajojen ylittäminen on traumaattista. Mutta uusille sukupolville, jotka hahmottavat maailmaa globaalimmasta näkökulmasta, syntymämaansa hylkääminen ei ole se käsittämätön päätös, joka vanhemmille, kansallisvaltion ideologiaan syvästi juurrutuneille henkilöille olisi.

Jim Taylor ja Watts Wacker raportoivat kiehtovista tuloksista, jotka saatiin massakyselystä 20 000 keskiluokkaiselta lukiolaiselta viideltä maanmantereelta. Brainwaves Groupin, New Yorkin kuluttajatutkimusyhtiön, vuonna 1995–96 tehdyn otannan mukaan yhdeksestä kymmenestä opiskelijasta oli samaa mieltä siitä, että “minun vastuullani on saada elämästäni se, mitä haluan.” Vielä hämmästyttävämpää onkin, että “lähes puolet teini-ikäisistä sanoi odottavansa, että he jättäisivät syntymämaansa tavoitellessaan päämääriään.”[^166]

Ehkä siksi, että hän on viritetty MTV-sukupolven asenteisiin, Bill Clinting – ensimmäisenä presidenttikandidaattina, joka kampanjoi MTV:llä – on pyrkinyt vaikeuttamaan amerikkalaisten mahdollisuuksia “hylätä syntymämaansa tavoitellakseen omia päämääriään”. Vuonna 1995, suunnilleen samaan aikaan, kun lukiolaiset julkistivat aikomuksensa hakea itsenäisyyttä, Yhdysvaltain presidentti ehdotti lähtöveron käyttöönottoa, “kapinallista Berliinin muuria pääomalle”, joka vaatisi varakkailta amerikkalaisilta huomattavan lunnauksen, jotta he voisivat paeta kantaessaan edes osan rahoistaan.

Clintingin lunnas ei vain muistuta myöhäisen Itä-Saksan valtion politiikkaa, jossa kansalaisia kohdellaan omaisuutena; se tuo myös mieleen yhä drakonisemmat toimenpiteet, joilla pyrittiin vahvistamaan heikentyvän Rooman valtakunnan taloudellista asemaa. Seuraava lainaus teoksesta *The Cambridge Ancient History* kertoo tarinan:

> Näin valtio aloitti raivoisan yrityksen puristaa väestönsä viimeiseen pisaraan asti. Koska taloudelliset resurssit jäivät vajaiksi tarpeelliseen nähden, vahvimmat taistelivat varmistaakseen itselleen pääosan väkivaltaisin ja säädytöntä keinoin, mikä heijasti vallassa olevien alkuperää ja sotilaiden ryöstöperinnettä. Lain täydellinen ankaruus päästiin valloilleen väestöön. Sotilaat toimivat huutovelkureina tai vaelsivat salaisina poliiseina maassa. Niistä, jotka kärsivät eniten, olivat tietenkin omaisuuden omistajat. Heidän omaisuutensa haltuunotto oli suhteellisen helppoa, ja hätätilanteessa juuri heistä voitiin usein ja nopeasti saada jotakin ulos.[^167]

Kun epäonnistuneet järjestelmät pystyvät siihen, ne asettavat usein rangaistavia taakoja niille, jotka pyrkivät pakenemaan. Toistamme lainauksen teoksesta *The Cambridge Ancient History*:

> Jos omaisuuden omistajat hautasivat rahansa, tai uhrasivat kaksi kolmasosaa omaisuudestaan paetakseen viranhallintoa, tai menivät niin pitkälle, että luopuivat kokonaan omistuksestaan päästäkseen vuokratasojen kahleista, ja jos omaisuudenomistukseen ei kuuluvat pakenivat, valtio vastasi kiristämällä painostusta.

Tämä on hyvä pitää mielessä suunnitelmia tehdessäsi. Aikaisempien valtiojärjestelmien hiipuminen ei ole harvoin ollut kohteliasta tai järjestäytynyttä. Mainitsimme luvussa 2 Rooman veronkantajien inhottavat tavat. Suuret määrät agri deserti eli hylättyjä maatiloja Länsi-Euroopassa Rooman valtakunnan romahtamisen jälkeen heijastivat vain pientä osaa laajemmasta ongelmasta. Todellisuudessa vallankumoukselliset veronkorotukset olivat suhteellisen lieviä Gallassa, ja rajaseuduilla nykyisten Luxemburgin ja Saksan alueilla tilanne oli samankaltainen. Rooman hedelmällisimmässä alueessa, Egyptissä, missä maanviljely oli tuottavampaa kastelun ansiosta, omistajien pakeneminen oli vielä suurempi ongelma. Kysymys siitä, kannattaako yrittää pakoa – ultimum refugium, kuten sitä latinaksi kutsuttiin – muodostui lähes kaikkien omaisuudenomistajien ylivoimaiseksi pohdinnaksi. Tietueiden mukaan “Egyptin oraakkelille esitettiin tavallisesti kolme standardikysymystä: 'Tulenko hakemaan torpparuutta?', 'Pakoanko?' ja 'Pakoneni estetäänkö?'”[^168]

Clintingin ehdotus vastaa kyllä. Se on varhainen versio pakoa vaikeuttavasta esteestä, jonka odotetaan kasvavan raskaammaksi kansallisvaltion taloudellisten resurssien hupenemisen myötä. Tietenkin Yhdysvaltojen ensimmäinen lähtöeste on lempeämpi kuin Erich Honeckerin betoninen ja piikkilankaeste. Se sisältää myös suuremman hintaherkkyyden, sillä taakka kohdistuu vain “miljardööreihin”, joiden verotettava omaisuus ylittää 600 000 dollaria. Siitä huolimatta sitä oikeutettiin samankaltaisilla argumenteilla kuin Honeckerin kerran esittämät puolustukset myöhäisen Saksan demokraattisen tasavallan kuuluisimmasta julkisesta rakennusprojektista. Honecker väitti, että Itä-Saksan valtiolla oli merkittävä investointi potentiaalisiin pakolaisiin. Hän huomautti, että heidän vapaa lähtönsä loisi taloudellisen haitan valtiolle, joka tarvitsi heidän panostaan Itä-Saksassa.

Jos hyväksyt premissin, että ihmiset ovat tai heidän tulisi olla valtion omaisuutta, Honeckerin muuri oli looginen. Berliini ilman muuria tarjosi aukon kommunisteille, aivan kuten pakomatka Yhdysvaltojen verotoimivallan ulkopuolelle oli aukko Clintonin IRS:lle. Clintingin argumentit pakenevista miljardööreistä, lukuun ottamatta poliitikon tavanomaista välinpitämättömyyttä lukujen eheyttä kohtaan, olivat tyyppiltään samanlaisia kuin Honeckerin, mutta hieman vähemmän loogisia, koska Yhdysvaltain hallituksella ei todellisuudessa ole merkittävää taloudellista investointia varakkaisiin kansalaisiin, jotka saattaisivat yrittää paeta. Kyse ei ole siitä, että heidät olisi koulutettu valtion kustannuksella ja haluaisi paeta harjoittamaan lakia jossain muualla. Ylivoimainen enemmistö niistä, joihin lähtövero kohdistuisi, on luonut vaurautensa omalla työllään ja huolimatta – ei siksi, että Yhdysvaltain hallituksella olisi ollut siihen vaikutusta.

Koska Yhdysvalloissa ylimmän 1 prosentin veronmaksajat maksavat nyt 28,7 prosenttia koko tuloverosta, kyse ei ole siitä, etteivätkö rikkaat maksaisi takaisin mitään aitoa investointia, jonka valtio olisi voinut tehdä heidän koulutukseensa tai taloudelliseen vaurauteensa. Päinvastoin. Ne, jotka maksavat suurimman osan kuluista, maksavat valtavasti enemmän kuin saavat etuja vastineeksi. Kun keskimääräinen vuosiveromaksu ylittää 125 000 dollaria, ylimmän 1 prosentin amerikkalaisten veronmaksajien kustannukset ovat huomattavasti suuremmat kuin he nykyään tajuavat. Jos he voisivat tienata jopa 10 prosentin tuoton jokaisesta ylimääräisestä 5 000 dollarin veromaksusta neljänkymmenen vuoden aikana, jokainen 5 000 dollarin vuosittainen ylimääräinen veromaksu heikentäisi heidän nettovarallisuuttaan 2,2 miljoonalla dollarilla. 20 prosentin tuottotahdolla jokainen 5 000 dollarin ylimääräinen vero vähentäisi nettovarallisuutta 44 miljoonalla dollarilla.

Kun vuosituhat lähestyy, uuden tietoyhteiskunnan megapoliittiset olosuhteet tekevät yhä selvemmäksi, että teollisuusaikakaudelta peritty kansallisvaltio on saalistava instituutio. Jokaisella kuluvalla vuodella se vaikuttaa yhä vähemmän vaurauden lähteenä ja enemmän esteenä, josta yksilö haluaa paeta. Kyseessä on pakokeino, jonka epätoivoiset hallitukset eivät haluaisi sallia. Läntisten hyvinvointivaltioiden vakaus – jopa niiden selviytyminen – on riippuvainen niiden kyvystä jatkaa maailman koko tuotannon valtavan osan keräämistä ja siirtämistä uudelleen jakamiseksi tietylle äänestäjäjoukolle OECD-maissa. Tämä edellyttää, että nykyisten rikkaiden maiden tuottavimpien kansalaisten verot asetetaan erittäin korkealle tasolle, satoja tai jopa tuhansia kertoja korkeammalle kuin niiden palvelujen todelliset kustannukset, joita hallitukset antavat vastineeksi.

## THE LIFE AND DEATH OF THE NATIONSTATE



Berliinin muurin kaatuminen ei ollut vain näkyvä symboli kommunismin kuolemasta. Se oli tappio koko kansallisvaltiojärjestelmälle ja tehosta sekä markkinoille nojautuneiden järjestelmien voitto. Historian taustalla vaikuttava vallan vipuosa on siirtynyt. Uskomme, että vuonna 1989 tapahtunut Berliinin muurin kaatuminen huipentaa kansallisvaltioajan, tuhat vuotta kestäneen, mutta erityisen kaksisadan vuoden vaiheksen, joka alkoi Ranskan vallankumouksella. Valtiot ovat olleet olemassa kuusi tuhatta vuotta, mutta ennen 1800‑lukua ne edustivat vain pientä osaa maailman itsehallinnollisista kokonaisuuksista. Niiden nousu ja tuho liittyivät vahvasti vallankumouksiin. Vuoden 1789 suuret tapahtumat asettivat Euroopan todellisten kansallishallitusten polulle, ja vuoden 1989 tapahtumat merkitsivät kommunismin kuolemaa sekä markkinavoimien ylivaltaa massavallan yli. Nämä kaksi, tarkalleen kaksisataa vuotta ergottavat vallankumoukset määrittelevät aikakauden, jolloin kansallisvaltio oli keskeinen toimija suurvaltojen järjestelmässä, ja nämä suurvallat hallitsivat maailmaa levittäen tai asettaen valtiollisia järjestelmiä jopa kaikkein syrjäisimmille heimoalueille.

### Magnitude over Efficiency

Ruuti mahdollisti valtioiden helpomman laajentumisen riisimaille ja karuille jokilaaksoille asettamansa rajoituksen ulkopuolelle. Ruutipohjaisten aseiden luonne ja teollisen talouden piirteet loivat mittakaavaetuja sodankäyntiin. Tämä johti siihen, että väkivallan tuotto – tai kokonaisvaikuttavuus – nousi merkittävästi. Kuten historioitsija Charles Tilly totesi, 
> "Valtiot, joilla on suurin pakottava voima, voittavat sodat; tehokkuus (tuotoksen suhde panokseen) jää toissijaiseksi suhteessa vaikuttavuuteen (kokonaistuotto)." [^170]

### The Great Unanswered Question

Tämä nostaa meidät yhteen modernin historian yhteen suureen, vielä ratkaisemattomaan arvoitukseen: miksi kylmä sota, joka päättyi suurvaltojen järjestelmään, asetti viimeisiksi kilpailijoiksi kommunistiset diktatuurit ja hyvinvointivaltioiden demokratiat? Tätä kysymystä on tutkittu niin vähän, että monille vaikutti jopa uskottavalta, kun ulkoministeriön analyytikko Francis Fukuyama julisti ”historian lopun” Berliinin muurin kaatumisen jälkeen. Innostunut yleisö otti ilmiölle liian paljon annettuna – ilmeisesti kukaan, ei edes itse kirjoittaja, ei ollut pohdinut perustavanlaatuista kysymystä: mitkä yhteiset piirteet valtiollisessa sosialismissa ja hyvinvointivaltioiden demokratioissa johtivat siihen, että ne muodostivat viimeisenä toimivana kilpailijana maailmanvalloituskamppailussa?

Tämä on tärkeä kysymys. Lukuisten eri suvereniteettijärjestelmien – esimerkiksi ehdottomien monarkioiden, heimoalueiden, ruhtinaskirkojen, paavin suorahallinnon, sulttaanikuntien, kaupunkivaltioden ja anabaptististen siirtokuntien – nousu ja tuho ovat kulkeneet edestään viimeisten viiden vuosisadan aikana. Nykyään useimmat olisivat yllättyneitä kuullessaan, että sairaanhallintayritys, jolla on omat asevoimat, on voinut hallita maata vuosisatojen ajan. Silti jotain sellaista todella tapahtui: kolmesataa vuotta vuoden 1228 jälkeen Jerusalemissa sijaitsevan St. Mary's Hospitalin teutoniritarit – myöhemmin yhtenäistyneet Livonia Swordin ritareiden kanssa – hallitsivat Itä-Prussiaa sekä useita Itä-Euroopan alueita, mukaan lukien osia Liettuasta ja Puolasta. Sitten koittivat ruutin vallankumoukset. Muutamassa vuosikymmenessä teutoniritarit karkotettiin kaikilta alueiltaan, ja heidän suuremestarinsa menetti sotilaallisen merkityksensä, ollen enää yhtä merkityksetön kuin shakkimestari. Miksi? Miksi niin monet muut suvereniteettijärjestelmät kuihtuivat merkityksettömiksi, samalla kun teollisen aikakauden lopulla käynyt suuri maailmanvallasta kilpaileva kamppailu asetti massademokratioita vastakkain valtiollisesti sosialististen järjestelmien kanssa?

### Unimpeded Control

Jos megapolitiikan teoriamme pitää paikkansa, vastaus on selvä. Se on kuin kysyisi, miksi sumopainijat yleensä ovat lihavia. Vastaus on yksinkertainen: laiha sumopainija, vaikka hänen voimasuhteensa olisi vaikuttava, ei pysty kilpailemaan jättimäisen painavan kilpailijansa kanssa. Kuten Tilly totesi, tärkeämpää on "vaikuttavuus (kokonaistuotto)" kuin "tehokkuus (tuotoksen suhde panokseen)." [^170]

Miten tässä onnistuttiin?

Kommunismin tapauksessa vastaus on ilmeinen. Kommunismissa ne, jotka hallitsivat valtiota, hallitsivat melkein kaikkea. Jos olisit ollut Neuvostoliiton kansalainen kylmän sodan aikana, KGB olisi voinut ottaa hammasharjasi, jos se olisi todettu hyödylliseksi heidän tarkoituksiinsa. He olisivat voineet ottaa hampaasi. Uskottavien arvioiden mukaan, jotka ovat vieläkin uskottavampia sen jälkeen kun entisten neuvostovaltioiden arkistot avattiin vuonna 1992, salainen poliisi ja muut myöhemmin Neuvostoliiton toimineiden agenttien toimesta Neuvostoliiton seitsemänkymmentäneljävuotisen hallinnon aikana menetettiin 50 miljoonaa ihmishenkeä. Valtiollinen sosialistinen järjestelmä pystyi mobilisoimaan sen sisällä olevat kaikenlaiset resurssit sotilaallisiin tarkoituksiinsa, ilman että kukaan siellä asuva olisi kyseenalaistanut sitä.

Länsidemokratioiden tapauksessa tarina on vähemmän ilmeinen, osittain siksi, että olemme tottuneet ajattelemaan demokratiaa jyrkästi vastakohtana kommunismille. Teollisen aikakauden näkökulmasta nämä kaksi järjestelmää olivat todellakin suuria vastakohtia. Mutta informaatiokyvypäivän näkökulmasta niillä oli enemmän yhteistä kuin saattaisit epäillä. Molemmat mahdollistivat valtion rajoittamattoman resurssien hallinnan. Ero oli siinä, että demokraattinen hyvinvointivaltio joutui antamaan vieläkin enemmän resursseja valtion käsiin kuin valtiolliset sosialistiset järjestelmät.

Tämä on selkeä esimerkki harvinaisesta ilmiöstä, jossa vähemmällä on enemmän. Valtiollinen sosialistinen järjestelmä perustuikin oppiin, jonka mukaan valtio omisti kaiken. Demokraattinen hyvinvointivaltio sen sijaan esitti maltillisempia vaatimuksia ja käytti siksi parempia kannustimia suuremman tuotannon mobilisoimiseksi. Sen sijaan, että hallitus vaatisi alusta asti kaikkea, länsimaiden hallitukset antoivat yksilöiden omistaa omaisuutta ja kerätä varallisuutta. Vasta sen jälkeen, kun varallisuus oli kertynyt, länsimaiden kansallisvaltiot verottivat siitä suuren osan. Korkeat kiinteistö-, tulos- ja perintöverot toimittivat demokraattiselle hyvinvointivaltioon valtavia määriä resursseja verrattuna siihen, mitä valtiollisissa sosialistisissa järjestelmissä oli käytettävissä.

### Tehottomuus siellä missä se merkitsi

Kommunismiin verrattuna hyvinvointivaltio oli totisesti paljon tehokkaampi järjestelmä. Mutta verrattuna muihin varallisuuden kartuttamisen järjestelmiin, kuten aitoon laissez-faire -kautta edustavaan Hong Kongiin, hyvinvointivaltio oli tehoton. Tässäkin tapauksessa vähemmällä oli enemmän. Juuri tämä tehottomuus teki hyvinvointivaltiosta ylivoimaisen teollisen aikakauden megapoliittisissa olosuhteissa.

Kun ymmärrät miksi, olet paljon lähempänä sitä, mitä Berliinin muurin murtuminen ja kommunismin kuolema todella tarkoittavat. Se, että demokraattinen hyvinvointivaltio ei välttämättä tule olemaan voitokas järjestelmä – kuten on laajalti oletettu – on enemmän kuin se, että katsotaan veljeksi syntynyttä kaksosta, joka kuolee vanhana. Sama megapoliittinen vallankumous, joka tappoi kommunismin, uhkaa myös heikentää ja tuhota demokraattiset hyvinvointivaltiot sellaisina kuin ne mekin 1900-luvulla tunsimme.

## KUKA HALLITSEE VALTIOTA?

Avain tähän epätavanomaiseen johtopäätökseen piilee siinä, että tunnustetaan, mistä demokraattisen hallituksen kontrolli kumpuaa. Kyse on asiasta, joka ei olekaan niin yksinkertainen kuin ensi vaikutelmalta vaikuttaisi. Modernilla aikakaudella kysymystä siitä, kuka hallitsee valtiota, on lähes aina käsitelty poliittisena kysymyksenä. Siihen on annettu monia vastauksia, mutta lähes yksimielisesti ne sisälsivät sen tunnistamisen, mikä poliittinen puolue, ryhmä tai murtue hallitsi tietyn valtion kontrollia tietyllä hetkellä. Olet kuullut kapitalisteja hallitsevista hallituksista. Hallituksista, joita työväenluokka hallitsee. Hallituksista, joita hallitsevat katoliset ja islamilaiset fundamentalistit. Hallituksista, joita hallitsevat heimot ja rodulliset ryhmät; hallituksista, joita hallitsevat hutut ja hallituksista, joita hallitsevat valkoiset. Olet myös kuullut ammattiluokkien, kuten lakimiesten tai pankkiirien, hallitsemista hallituksista. Olet kuullut maaseutujohtoisista hallituksista, suurkaupunkien konemaisista järjestelmistä ja esikaupunkien asukkaiden hallitsemista hallituksista. Ja olet varmasti kuullut poliittisten puolueiden eli Demokraattien, Konservatiivien, Christian Democratien, Liberalaisten, Radikaalien, Republikaanien ja Sosialistien hallitsemista hallituksista.

Mutta et luultavasti ole kuullut paljoa hallituksesta, jota hallitsevat sen asiakkaat. Taloushistorioitsija Frederic Lane loi perustan uudelle tavalla ymmärtää, mistä hallituksen kontrolli kumpuaa, joissakin hänen ytimekkäissä esseissään väkivallan taloudellisista seurauksista, joita käsiteltiin aiemmin. Ajatellessaan valtiota taloudellisena yksikkönä, joka myy suojaa, Lane alkoi analysoida hallituksen kontrollia taloudellisin, ei poliittisin termein. Tässä näkökulmassa hallituksen kontrollissa on kolme perusvaihtoehtoa, joista jokaisessa on pohjimmiltaan hyvin erilaiset kannustinjärjestelmät: omistajat, työntekijät ja asiakkaat.

### Proprietors

Harvinaisissa tapauksissa, jopa nykyään, hallitukset saattavat olla yksittäisen omistajan vallassa, yleensä periytyvän johtajan, joka käytännössä omistaa maan. Esimerkiksi Brunein sulttaani kohtelee Brunein hallitusta jossain määrin kuin yksityisomistuksessa olevaa yritystä. Tämä ilmiö oli yleisempää keskiajan herroilla, jotka pitivät feodaali-alueitaan omistajuuksina optimoidakseen tulonsa.

Lane kuvaili "tuotantoa harjoittavan yrityksen omistajien" kannustimia seuraavasti:

> Intressi maksimoida voitot ohjaisi häntä, samalla kun hän säilyttäisi hinnat, pyrkimään alentamaan kustannuksiaan. Hän käyttäisi – kuten Henry VII Englannista tai Louis XI Ranskasta – mahdollisimman edullisia keinoja vahvistaakseen legitimiteettiään, ylläpitääkseen sisäjärjestystä ja häiritäkseen naapuriprinssejä siten, että hänen omat sotilaalliset menonsa pysyisivät alhaisina. Alentuneista kustannuksista, tai sen monopolinsa tiukkuuden mahdollistamien lisämaksujen kautta, tai näiden yhdistelmästä, hän kerrytti ylijäämän... [^171]

Omistajien hallitsemissa valtioissa on vahvat kannustimet laskea suojelun tarjoamisen tai alueellisen väkivallan monopolisoinnin kustannuksia. Mutta niin kauan kuin heidän valtaansa on turvattu, heillä on vain vähän motivaatiota alentaa asiakkailtaan perittävää hintaa (veroa) alle sen tason, joka optimoi tulot. Mitä korkeammalle monopolisti voi hinnoitella palvelunsa ja mitä alhaisemmat hänen todelliset kustannuksensa ovat, sitä suuremmat voitot hän tekee. Omistajien hallitsemalle valtiolle ihanteellisena fiskaalipolitiikkana olisi valtava ylijäämä. Kun hallitukset pystyvät pitämään tulonsa korkeina mutta leikkaamaan kustannuksiaan, sillä on suuri vaikutus resurssien käyttöön. Työvoima ja muut arvokkaat tuotantopanokset, jotka muuten jäisivät hukkaan tarjoamaan tarpeettoman kallista suojaa, tulevat sen sijaan käytettäväksi investointeihin ja muihin tarkoituksiin. Mitä enemmän monarkki voi nostaa voittoaan kustannuksia leikkaamalla, sitä enemmän resursseja vapautuu. Kun näitä resursseja käytetään investointeihin, ne toimivat kasvun lisäkappaleena. Ja vaikka niitä käytettäisiin näkyvään kulutukseen, ne auttavat luomaan ja elvyttämään uusia markkinoita, joita muuten ei synty, jos resursseja hukattaisiin tuottamaan tehottomaa "suojelua".

### Employees

On helppo kuvata kannustimia, jotka vallitsevat hallituksissa, joissa työntekijät hallitsevat. Ne olisivat samankaltaiset kuin muissakin työntekijöiden hallitsemissa organisaatioissa. Ensisijaisesti työntekijöiden johtamat organisaatiot suosivat yleensä politiikkoja, jotka lisäävät työllisyyttä, ja vastustavat toimia, jotka vähentävät työpaikkoja. Kuten Lane totesi, 

> "Kun työntekijät yhteisesti hallitsivat, heillä ei ollut juurikaan kiinnostusta minimoida suojelusta perittyjä määriä, eikä lainkaan vähentää sitä suurta osaa kustannuksista, jotka muodostuvat työvoimakuluista eli heidän omista palkoistaan." [^172]

Työntekijöiden hallitsema hallitus harvoin saa kannustimia joko leikkaamaan hallituksen kustannuksia tai alentamaan asiakkailtaan peritettävää hintaa. Kuitenkin, missä olosuhteet aiheuttavat voimakasta hintavastustusta, esimerkiksi korkeampia veroja vastaan, työntekijöiden hallitsemissa hallituksissa on todennäköisempää, että niiden tulot putoavat alle menonsa kuin että menoja leikataan. Toisin sanoen niiden kannustimet viittaavat siihen, että ne saattavat olla alttiita kroonisille alijäämille, toisin kuin omistajien hallitukset eivät.

### Customers

Onko esimerkkejä hallituksista, joita hallitsevat niiden asiakkaat? Kyllä. Lane sai taloudellista inspiraatiota hallituksen kontrollin analysoimiseen keskiaikaisten kauppakansakuntien, kuten Venetsian, esimerkeistä. Siellä joukko tukkukauppiaita, jotka tarvitsivat suojaa, hallitsi käytännössä hallitusta vuosisatojen ajan. He olivat aidosti asiakkaat sille suojelupalvelulle, jota hallitus tarjosi, eivätkä omistajia. He maksoivat palvelusta eivätkä pyrkineet hyötymään hallituksen väkivallan monopolin kontrollista. Jos joku yritti, muut asiakkaat estivät heitä tekemästä niin pitkän aikaa. Muita esimerkkejä asiakkaiden hallitsemista hallituksista ovat demokraatit ja tasavallat, joissa on rajoitettu äänioikeus, kuten antiikin demokraatiat tai Amerikan republikaaninen järjestelmä sen perustamisajalla. Tuolloin vain ne, jotka maksivat hallituksesta, noin 10 prosenttia väestöstä, saivat äänestää.

Hallituksilla, joita hallitsevat niiden asiakkaat – kuten omistajien hallituksilla – on kannustimet vähentää toimintakustannuksiaan mahdollisimman paljon.

--- 

UTF-8 encoding varmistettu.



Mutta toisin kuin hallitukset, joita hallitsevat joko omistajat tai työntekijät, asiakkaidensa valvomat hallitukset saavat kannustimia pitää kerättävien maksujen hinnat alhaisina. Siellä, missä asiakkaat ovat vallassa, hallitukset ovat niukkoja ja yleensä huomaamattomia, niiden toimintakustannukset ovat alhaiset, työllisyys vähäistä ja verot pienet. Asiakkaiden hallitsema hallitus asettaa verokannat ei optimoidakseen kerättävänsä rahaa, vaan optimoidakseen sen määrän, jonka asiakkaat saavat pitää itsellään.

Kuten kilpailullisilla markkinoilla toimivat tyypilliset yritykset, jopa asiakkaidensa hallitsema monopoli olisi pakotettu siirtymään tehokkuuden suuntaan. Se ei pystyisi perimään hintoja verojen muodossa, jotka ylittäisivät sen kustannukset enemmän kuin aivan pienellä marginaalilla.

## Demokratian rooli: Äänestäjät työntekijöinä ja asiakkaina

Lane käsittelee demokratiaa perinteisesti olettaen, että se tuo väkivaltaa käyttävät ja väkivaltaa synnyttävät yritykset "yhä enemmän asiakkaidensa hallintaan."[^173] Tämä on toki poliittisesti korrektia johtopäätöstä. Mutta onko se totta? Me emme usko niin. Tarkastellaanpa tarkkaan, miten nykyaikaiset demokratioita toimivat.

Ensinnäkin niissä on vain vähän niitä ominaisuuksia, joita kilpailullisilla teollisuudenaloilla, joissa kaupan ehdot ovat selkeästi asiakkaiden hallinnassa, esiintyy. Yksi seikka on, että demokraattiset hallitukset käyttävät tyypillisesti vain täysin vähäisen osan kokonaismenoistaan suojelupalveluihin, joka on niiden ydintoiminta. Esimerkiksi Yhdysvalloissa osavaltiot ja paikallishallitukset käyttävät vain 3,5 prosenttia kokonaismenoistaan poliisin, sekä oikeuslaitosten ja vankiloiden tarjoamiseen. Lisää sotilasmenoihin, niin suojeluun käytetty osuus tuloista on silti vain noin 10 prosenttia.

Toinen paljastava vihje siitä, ettei massademokratia ole asiakkaidensa hallittavissa, on se, että nykyinen poliittinen kulttuuri, teollisuusajan perintönä, pitäisi skandaalina, jos ratkaisevista kysymyksistä tehtäisiin politiikkaa, joka perustuisi niiden ihmisten etuihin, jotka maksavat laskut. Kuvittele, millaista kohua herättäisi, jos Yhdysvalloissa presidentti tai Britannian pääministeri ehdottaisi, että se joukko kansalaisia, jotka maksavat suurimman osan veroista, saisi päättää, mitkä hallituksen ohjelmat jatkuvat ja ketkä työntekijäryhmät irtisanotaan. Tämä loukkaisi syvästi sitä, mitä odotetaan, että hallituksen tulisi toimia, tavalla, jolla hallituksen työntekijöiden salliminen päättää, kenen veroja nostetaan, ei loisi vastaavaa ärtymystä.

Mutta kun sitä mietit, kun asiakkaat todellakin ohjaavat tilannetta, olisi järjetöntä, jos he eivät saisi sitä, mitä haluavat. Jos menisit kauppaan ostamaan huonekaluja, ja myyjät ottaisivat rahasi mutta sitten alkaa sivuuttaa pyyntöjäsi ja kysellä muilta, miten rahasi käytettäisiin, olisit hyvin oikeutettu suuttumaan. Et katsoisi sitä normaalina tai perusteltuna, jos kaupan työntekijät väittelisivät, ettet oikeastaan ansaitsisi huonekaluja, vaan että ne tulisi sen sijaan lähettää jollekin, jota he pitävät arvokkaampana. Se, että jotain hyvin samanlaista tapahtuu hallituksen kanssa asioidessa, osoittaa kuinka vähän sen "asiakkailla" todellisuudessa on valtaa.

Minkä tahansa mittarin mukaan demokraattisen hallinnon kustannukset ovat nousseet täysin hallitsemattomiin, toisin kuin tyypillisessä tilanteessa, jossa asiakkaiden mieltymykset pakottavat myyjät toimimaan tehokkaasti. Useimmissa demokratioissa on jatkuvia alijäämiä. Tämä on julkisen talouden piirre, joka liittyy työntekijöiden kontrolliin. Hallitukset näyttävät olevan merkittävästi vastustuskykyisiä leikkaamaan toimintojensa kustannuksia. Melkein kaikkialla maailmassa esitetty yleinen valitus nykyaikaisesta hallituksesta on, että kerran vakiintuneet poliittiset ohjelmat voidaan supistaa vain suurella vaikeudella. Hallituksen työntekijän erottaminen on käytännössä mahdotonta. Itse asiassa yksi entisaikaisista etuuksista, jotka syntyvät valtion omistamien toimintojen yksityistämisestä, on se, että yksityinen kontrolli yleensä tekee huomattavasti helpommaksi turhan työvoiman karsimisen. Britanniasta Argentiinaan on ollut yleistä, että uudet yksityisjohtajat vähentävät entisten valtion työntekijöiden määrää 50–95 prosenttiin.

Ajattele myös perustaa, jonka mukaan hallituksen suojelupalveluiden taloudelliset ehdot hinnoitellaan. Lähinnä etsisit turhaan viitteitä kilpailullisista vaikutteista verokannoissa, joiden perusteella hallituksen palvelut hinnoitellaan. Jopa satunnaiset verojen laskemisesta käydyt keskustelut, jotka ovat keskeyttäneet normaalia poliittista keskustelua viime vuosina, paljastavat, kuinka kaukana demokraattinen hallinto on yleensä ollut asiakkaidensa kontrollista. Verojen alentamisen puolustajat ovat joskus väittäneet, että hallituksen tulot itse asiassa kasvaisivat, koska aiemmin verokannat oli asetettu niin korkeiksi, että ne lannistivat taloudellista aktiivisuutta.

Se, mitä he normaalisti halusivat korostaa, ei ollut kilpailu eri oikeudellisten alueiden välillä, vaan jotain huomattavasti hämmästyttävämpää. He eivät väittäneet, että koska Hongkongin verokannat olivat vain 15 prosenttia, niin Yhdysvalloissa tai Saksassa verokantojen ei pitäisi olla yli 15 prosenttia. Päinvastoin. Verokeskusteluissa oletettiin yleensä, että maksajan edessä oleva kompromissi oli ei siitä, että liiketoimintaa harjoitettaisiin yhdessä tai toisessa alueella, vaan siitä, että liiketoimintaa harjoitettaisiin rangaistustasoilla tai otettaisiin lomaa. Sinulle kerrottiin, että tuottavat ihmiset, jotka ovat alttiina saalistavalle verotukselle, luopuisivat asioistaan ja menisivät golfaamaan, jos heidän verorasituksensa ei helpotettaisi.

Se, että tällainen argumentti edes voi nousta esiin, osoittaa kuinka kaukana demokratisten hyvinvointivaltioiden asettamat suojelukustannukset ovat kilpailullisesta pohjasta. Progressiivisen tuloverotuksen ehdot, jotka nousivat esiin jokaisessa demokratian hyvinvointivaltiossa 1900-luvun aikana, ovat dramaattisesti erilaiset kuin hinnoitteluehdot, jotka asiakkaat suosisivat. Tämä käy helposti ilmi vertaamalla verotusta, jota asetetaan monopolisesti tarjotun suojelun tukemiseksi, puhelinpalvelun tariffien kanssa, joka oli asti äskettäin monopoli useimmilla paikoilla. Asiakkaat räjähtäisivät vihasta, jos puhelinyritys yrittäisi periä puhelut maksujen perusteella samalla tavalla, jolla tuloverot asetetaan. Kuvittele, että puhelinyritys lähettäisi laskun 50 000 dollarin suuruisena puhelusta Lontooseen, vain siksi, että päätit juuri keskustelussasi tehdä 125 000 dollarin diilin. Sinä et etkä mikään muu asiakas oikeassa mielessä maksaisi sellaista. Mutta juuri tällaisella perusteella tuloverot asetetaan jokaisessa demokratian hyvinvointivaltiossa.

Kun tarkastelet tarkkaan niitä ehtoja, joiden pohjalta teolliset demokratiat ovat toimineet, on loogisempaa pitää niitä hallintomuotona, jota heidän omat työntekijänsä hallitsevat. Massademokratian ajatteleminen työntekijöiden hallitsemana auttaa selittämään, miksi hallituksen politiikan muuttaminen on niin vaikeaa. Monin tavoin hallitusta näyttää toimivan työntekijöiden eduista. Esimerkiksi useimpien demokratioiden valtiokoulut vaikuttavat kroonisesti toimimattomilta korjaamattomasti. Jos asiakkaat todella olisivat ohjauspöydässä, heillä olisi helpompi asettaa uusia linjauksia. Ne, jotka maksavat demokraattisesta hallituksesta, eivät harvoin määrittele, mihin hallituksen varoja käytetään. Sen sijaan hallitus toimii osuuskunnan tavoin – se on sekä yksityisomistuksen ulkopuolella että toimii luonnollisena monopolina. Hinnat eivät juurikaan seuraa kustannuksia, palvelun laatu on yleisesti ottaen alhainen verrattuna yksityissektorin toimintaan ja asiakkaiden valitusten korjaaminen on vaikeaa. Lyhyesti sanottuna massademokratia johtaa siihen, että hallitusta hallitsevat sen "työntekijät".

Mutta odota. Saatat ajatella, että useimmissa lainkäyttöalueissa äänestäjiä on huomattavasti enemmän kuin niillä, jotka ovat hallituksen palkkalistoilla. Miten työntekijöiden voisi tällaisissa olosuhteissa olla mahdollista hallita? Hyvinvointivaltio syntyi juuri vastaamaan tähän dilemmaihin. Koska työntekijöitä ei muulloin ollut tarpeeksi muodostamaan toimivaa enemmistöä, yhä useampi äänestäjä siirrettiin käytännössä palkkalistoille saadakseen erilaisia siirtoetuja. Käytännössä siirtoetuuksia ja tukia saaneet muuttuivat eräänlaisiksi pseudo-hallituksen työntekijöiksi, jotka eivät joutuneet raportoimaan päivittäin työpaikalle. Tämä oli seurausta teollisaikaa kuvaavasta megapoliittisesta logiikasta.

Kun pakottavan voiman laajuus on tärkeämpää kuin resurssien tehokas käyttö – kuten oli tilanne ennen vuotta 1989 – on lähes mahdotonta, että useimmat hallitukset olisivat asiakkaidensa hallinnassa. Kuten myöhäisen Neuvostoliiton esimerkki osoitti niin hyvin, vielä muutama vuosi sitten valtioilla oli mahdollista käyttää suurta valtaa maailmassa, vaikka ne hukkasivat resursseja massiivisesti. Kun väkivallan tuotto on korkea ja nouseva, laajuus merkitsee enemmän kuin tehokkuus. Suuremmat toimijat yleensä pärjäävät paremmin pienempiä vastaan, ja hallitukset, jotka pystyvät mobilisoimaan sotilaalliset resurssit tehokkaammin – vaikka se merkitsisi niiden monien hukkaamista – pärjäävät useimmiten paremmin kuin ne, jotka hyödyntävät resursseja tehokkaammin.

Ajattele, mitä tämä tarkoittaa. Se merkitsee väistämättä, että kun laajuus on tärkeämpää kuin tehokkuus, asiakkaiden hallitsemat hallitukset eivät voi pärjätä, eikä niillä usein ole edes selvää mahdollisuutta selviytyä. Tällaisissa olosuhteissa sotilaallisesti menestyvimmät toimijat ovat niitä, jotka pystyvät keräämään eniten resursseja sotaa varten. Kuitenkin hallitukset, joita todella hallitsevat laskunsa maksavat asiakkaat, eivät todennäköisesti saa täydellistä vapautta ryhtyä kaikkien taskuihin kerätäkseen resursseja.

Yleisesti ottaen asiakkaat haluavat nähdä maksamiensa tuotteiden tai palveluiden – suojelunkin mukaan – hintojen laskevan ja pysyvän kurissa. Jos länsimaat olisivat olleet asiakkaiden hallinnassa kylmän sodan aikana, se yksinään olisi tehnyt niistä sotilaallisesti heikompia kilpailijoita, koska se käytännössä rajoittaisi resurssien virtaa hallitukseen. Muista, että kun asiakkaat hallitsevat, myös hinnat ja kustannukset olisivat tiukassa kurissa. Mutta juuri näin ei tapahtunut. Hyvinvointivaltiot osoittautuivat kylmän sodan kulutuskilpailussa selkeiksi voittajiksi. Lukuisten eri alojen kommentoijat mainitsivat tekijäksi sen, että nämä valtiot pystyivät käytännössä kuluttamaan Neuvostoliiton resursseja konkurssiin.

Juuri tämä tosiasia korostaa sitä, miten demokratian tehottomuus teki siitä megapoliittisesti hallitsevan aikana, jolloin väkivallan tuotto oli nousussa. Massiiviset sotilasmenot, kaikine hukassaan menevinä, edustavat selvästi alitehokasta pääoman sijoitusta yksityiseen hyötyyn. Aiemmin ehdotimme, että vaikka hyvinvointivaltiot olivatkin taloudellisesti tehokkaita verrattuna valtiollis-sosialistisiin järjestelmiin, ne ovat huomattavasti vähemmän tehokkaita varallisuuden luomisessa kuin laissez‑fairesuhteiset alueet, kuten Hong Kong. Ironista kyllä juuri tämä demokraattisen hyvinvointivaltion tehottomuus suhteessa vapaamarkkinajärjestelmään teki siitä menestyvän teollisaikana, kun maailmanlaajuiset olosuhteet vaikuttivat.

Kuinka demokratian synnyttämä tehottomuus siis vaikutti sen menestykseen Väkivallan aikakaudella? Avain tämän näennäisen paradoksin ratkaisemiseen piilee kahdessa seikassa:

1. Modernin ajan suvereniteetin menestys ei perustunut varallisuuden luomiseen, vaan sellaisen sotilaallisen voiman rakentamiseen, joka pystyy käyttämään ylivoimaista väkivaltaa toista valtiota vastaan. Tähän tarvittiin rahaa, mutta raha itsessään ei voi voittaa taistelua. Haasteena oli luoda järjestelmä, joka ei keskittyisi vain talouden tehokkuuteen tai nopeaan kasvuun, vaan joka pystyisi keräämään enemmän resursseja ja ohjaamaan ne sotilaalliseen käyttöön. Luontaisesti sotilasmenoalueella taloudelliset tuotot ovat alhaiset tai olemattomia.

2. Helpoin tapa saada lupa sijoittaa varoja toimintoihin, joilla on vähän tai ei lainkaan suoraa taloudellista tuottoa – esimerkiksi veromaksuihin – on pyytää lupa joltain muulta kuin siltä henkilöltä, jonka rahaa halutaan. Yksi keino, jolla hollantilaiset pystyivät ostamaan Manhattanin 23 dollarin arvoisilla helmillä, johtui siitä, että ne intiaanit, joille he tekivät tarjouksen, eivät olleet niitä, jotka oikeastaan omistivat saaren. "Getting to yes", kuten markkinointialan ihmiset sanovat, on paljon helpompaa tällaisissa olosuhteissa. Kuvitellaan esimerkiksi, että tämän kirjan tekijöinä haluaisimme sinun maksavan kopion sijaan 40 prosenttia vuosituloistasi. Saamme paljon todennäköisemmin luvan, jos pyytäisimme lupa vaikka joltain muulta emmekä sinulta. Itse asiassa olisimme paljon vakuuttavampia, jos voisimme nojautua useiden sellaisten henkilöiden suostumukseen, joita et edes tunne. Voisimme järjestää ad hoc -vaalit – kuten H. L. Mencken kuvaili – hieman liioittelematta, ikään kuin "edistyksellisenä huutokauppana varastetuista hyödykkeistä." Ja tehdäksemme esimerkistä realistisemman, sopisimme jakavamme osan sinulta keräämistämme varoista näiden nimettömien ohikulkijoiden kanssa heidän tukensa vastineeksi.

Juuri tätä tehtävää varten moderni demokraattinen hyvinvointivaltio kehittyi. Se oli teollisuusaikana vertaansa vailla oleva järjestelmä, koska se oli siellä sekä tehokas että tehottomasti toimiva juuri siellä, missä sillä piti olla. Se yhdisti yksityisomistuksen tehokkuuden ja varallisuuden luomisen kannustimet mekanismiin, joka mahdollisti pohjimmiltaan rajoittamattoman pääsyn tuohon varallisuuteen. Demokratia piti varallisuuden tuottajien taskut auki. Se onnistui sotilaallisesti nousuvien väkivallan tuottojen huippuvaiheessa juuri siksi, että se teki asiakkaiden vaikeaksi rajoittaa tehokkaasti niiden keräämiä veroja tai muita keinoja, joilla resursseja rahoitetaan sotilaalliseen menoon – esimerkiksi inflaation avulla.

### Why Customers Could Not Dominate

Ne, jotka maksoivat "suojelusta" modernin ajan aikana, eivät olleet asemassa, edes kollektiivisesti toimien, menestyksekkäästi kieltämään resursseja suvereenilta, sillä se olisi vain paljastanut heidät muiden, mahdollisesti vihamielisempien valtioiden ylivoimaisuuden alle. Tämä oli ilmeinen seikka kylmän sodan aikana. Johtavien länsimaiden teollisuusvaltioissa hallituksen kustannuksista suhteettoman suuren osan kärsivät asiakkaat eli veronmaksajat eivät olleet asemassa kieltäytymään maksamasta raskaita veroja, sillä seurauksena heidät olisi altistettu Neuvostoliiton tai muun väkivaltaa järjestää pystyvän aggressiivisen ryhmän täydelliselle takavarikoinnille.

### Industrialism and Democracy

Pitkällä aikavälillä massademokratia saattaa osoittautua anakronismina, joka ei säily pitkään teollisen aikakauden päättymisen jälkeen. Massademokratia ja kansallisvaltio nousivat yhdessä ranskalaisen vallankumouksen myötä 1700-luvun lopulla, luultavasti vastauksena reaali- tulojen nousuun. Länsi-Euroopassa tulot alkoivat nousta merkittävästi noin vuonna 1750, osittain lämpimämmän sään seurauksena. Tämä ajoittui teknologisen innovaation kauteen, jolloin käsityöläisten ammattitaitoiset työt syrjäytettiin laitteilla, joita pystyivät käyttämään kouluttamattomat työntekijät, jopa naiset ja lapset. Uusi teollinen laitteisto nosti kouluttamattomien työntekijöiden palkkoja ja tasa-arvoisti tulojen jakautumista.

Merkittävin vallankumousta laukaiseva tekijä ei ehkä ollut, kuten usein ajatellaan, se vääristynyt ajatus, että ihmiset kapinoivat, kun olosuhteet paranevat. Tärkeämpää on se, että kun tulot nousivat tietylle tasolle, varhaismoderni valtio sai lopulta käytännölliseksi ohittaa aiemmat yksityiset välittäjät ja vaikutusvaltaiset magnaatit, joiden kanssa se oli neuvotellut resursseista, ja siirtyä "suoraan hallitsevaan" järjestelmään, jossa kansallinen hallitus toimi suoraan yksittäisten kansalaisten kanssa, verottaen heitä yhä korkeammilla prosenteilla ja vaatimalla huonosti palkattua sotilaspalvelusta vastineeksi erilaisista etuista.[^174]

Koska nousevalla keskiluokalla oli pian riittävästi rahaa verotettavaksi, valtioiden ei enää ollut yhtä välttämätöntä, kuten aiemmin, neuvotella vaikutusvaltaisten maanomistajien tai suurten kauppiaiden kanssa, jotka – kuten historioitsija Charles Tilly kirjoitti – olivat “asemaamassa estääkseen voimakkaan valtion synnyn”, joka “riistäisi heidän omaisuutensa ja tukahduttaisi heidän kauppansa.”[^175] On helppo ymmärtää, miksi hallitukset onnistuivat paremmin purkamaan resursseja, kun ne toimivat miljoonien kansalaisten kanssa erikseen sen sijaan, että ne neuvottelevat suhteellisen pienen määrän herrojen, herttuaiden, kreiviensä, piispaiden, sopimuspalkkasotilaiden, vapaiden kaupunkien ja muiden puolisuvereenien toimijoiden kanssa, joiden kanssa Euroopan valtioiden hallitsijat olivat velvollisia neuvottelemaan ennen 1700-luvun puoliväliä.

Nousevat reaali- tulot mahdollistivat hallituksille strategian, joka siirsi enemmän resursseja niiden kontrolliin. Pienet, miljoonilta kerättävät verosummat pystyivät tuottamaan enemmän tuloja kuin suuremmat summat, jotka maksettiin muutamalta vaikutusvaltaiselta henkilöltä. Lisäksi monien kanssa oli huomattavasti helpompi toimia kuin harvojen, jotka yleensä eivät halunneet luopua rahoistaan ja olivat paremmin asemoituneita vastustamaan verojen korotuksia.

Loppujen lopuksi tyypillisellä maanviljelijällä, pienellä kauppiaalla tai työntekijällä oli lähes merkityksettömät resurssit verrattuna valtion resursseihin. Ei ollut edes kaukana mahdollista, että tyypillinen yksityishenkilö Länsi-Euroopassa Ranskan vallankumouksen aattona olisi voinut tehokkaasti neuvotella valtion kanssa veroasteensa alentamiseksi tai vastustaa tehokkaasti hallituksen suunnitelmia ja politiikkaa, jotka uhkasivat hänen etujaan. Mutta juuri näin vaikutusvaltaiset yksityiset magnaatit ovat tehneet vuosisatojen ajan ja jatkavat edelleen: he vastustivat ja neuvotteleivat tehokkaasti hallitsijoiden kanssa, rajoittaen heidän kykyään ryhtyä resursseille.

> "Going to war accelerated the move from indirect to direct rule. Almost any state that makes war finds that it cannot pay for the effort from its accumulated reserves and current revenues. Almost all warmaking states borrow extensively, raise taxes, and seize the means of combat-including men-from reluctant citizens who have other uses for their resources."[^176] - CHARLES TILLY

Esimerkki puolalaisista puolikymmenesadan puolivälissä korostaa tätä täydellisesti. Vuonna 1760 puolalaisen kansallisen armeijan joukot muodostivat kahdeksantoista tuhatta sotilasta. Tämä oli vähäinen joukko verrattuna naapurisvaltojen – esimerkiksi Itävallan, Preussin ja Venäjän – hallitsijoiden komentamiin armeijoihin, joista vähimmäiselläkin oli kyky hallita pysyvää armeijaa, joka koostui 100 000 sotilaasta. Itse asiassa vuonna 1760 puolalainen kansallinen armeija oli pieni myös verrattuna muihin aseellisiin yksiköihin Puolassa. Puolalaisten aateliston yhteenlaskettu voima oli kolmekymmentä tuhatta miestä.[^177]

Jos Puolan kuningas olisi voinut olla suoraan vuorovaikutuksessa miljoonien yksittäisten puolalaisten kanssa ja verottaa heitä suoraan sen sijaan, että hän olisi ollut rajoitettu keräämään resursseja epäsuorasti voimakkaiden puolalaisten mahtavien aatelisten panosten kautta, on harva epäilystä siitä, että Puolan keskushallitus olisi pystynyt keräämään huomattavasti enemmän tuloja ja siten rahoittamaan suuremman armeijan.

Verrattuna tavallisiin kansalaisiin, jotka eivät kyenneet toimimaan yhdessä miljoonien muiden tavallisten ihmisten kanssa, keskushallinto osoittautui kaikkialla vastustamattoman mahtavaksi. Mutta Puolan kuninkaalla ei vuonna 1760 ollut vaihtoehtoa verottaa kansalaisiaan suoraan. Hän joutui neuvottelemaan lordien, varakkaiden kauppiaiden ja muiden merkittävien henkilöiden kautta, jotka muodostivat pienen, yhtenäisen ryhmän. He pystyivät – ja myös toimivat – yhdessä estääkseen kuningasta ryhtymästä ottamaan heidän resurssejaan ilman suostumustaan. Koska puolalaisella aatelistolla oli paljon enemmän joukkoja kuin hänellä, kuningas ei ollut missään asemassa vaatimaan suoria veroja.

Kävi ilmi, että sotilaallinen haitta, joka johtui rikkaiden ja vaikutusvaltaisten ohittamisen epäonnistumisesta resurssien keräämisessä, oli ratkaiseva Väkivallan aikakaudella. Muutamassa vuodessa Puola lakatti itsenäisenä maana. Sitä valloitettiin Itävallan, Preussan ja Venäjän invaasioiden toimesta – kolmen maan armeijat, joiden koko oli moninkertaisesti suurempi kuin Puolan pienen voiman – ja kussakin näissä maissa hallitsijat löysivät keinoja ohittaa varakkaiden kauppiaiden ja aateliston kyky rajoittaa heidän resurssiensa haltuunottoa.

### Ranskan vallankumouksen jälkeen

Ranskan vallankumous johti vielä suurempaan armeijoiden koon kasvuun, mikä osoitti demokraattisen strategian vahvuuden, kun väkivallan tuotto kasvoi. Vallankumouksen jälkeen solmitu kompromissihallinto tarjosi ennennäkemättömän määrän osallistumista tavallisten ihmisten elämään vastineeksi heidän osallistumisestaan sotiin palkkasotilaisten sijasta sekä kasvavien tulojen aiheuttaman verotaakan maksamisesta.

Kuten Tilly sanoi,

> Valtion vaikutusala laajeni paljon sen sotilaallisesta ydinalueesta, ja sen kansalaiset alkoivat tehdä vaatimuksia siitä erittäin laajasti suojelun, riitauttamisen, tuotannon ja jakelun osalta. Kun kansalliset lainsäätäjät laajenivat omilla alueillaan paljon verotuksen hyväksymisen ulkopuolelle, heistä tuli kaiken hyvin järjestäytyneiden ryhmien vaatimusten kohteena, joiden etuja valtio vaikutti tai pystyi vaikuttamaan. Suora hallinto ja massallinen kansallinen politiikka kehittyivät yhdessä ja vahvistivat toisiaan voimakkaasti.[^178]

Sama logiikka, joka päsi kahdeksastoista vuosisadalla, pysyi voimassa aina vuoteen 1989 saakka, jolloin Berliinin muuri kaatui. Teollisen aikakauden edetessä vähäpalkkaisen työn tulot jatkoivat nousuaan, mikä teki massademokratiasta entistä tehokkaamman keinon optimaalisen resurssien keräämisen kannalta. Tämän seurauksena hallitus kasvoi yhä enemmän, lisäten keskimääräisessä teollisuusmaassa sen kokonaisvaatimuksiin noin 0,5 prosenttia vuosituloista koko 1900-lukua ajan myötä.

Ennen vuotta 1989 teollisuusaikana demokratia nousi sotilaallisesti tehokkaimmaksi hallintomuodoksi juuri siksi, että demokratia teki valtion resurssien haltuunotosta tehokkaiden rajoitusten asettamisen vaikeaksi tai mahdottomaksi. Yleinen ja antelias sosiaaliturvan tarjoaminen kaikille houkutteli enemmistön äänestäjiä käytännössä muuttumaan hallituksen työntekijöiksi. Tämä muodostui kaikissa johtavissa teollisuusmaissa hallitsevaksi poliittiseksi piirteeksi, koska äänestäjät olivat heikossa asemassa kontrolloidakseen hallitusta tehokkaasti roolissaan suojelupalvelujen asiakkaina. He kohtasivat paitsi kommunististen järjestelmien aggressiivisen uhan, jotka pystyivät tuottamaan suuria määriä resursseja sotilaallisia tarkoituksia varten valtion kontrolloidessa koko taloutta, myös todellista veronmaksajavalvontaa hallituksesta oli toisesta syystä käytännössä mahdotonta.

Miljoonat tavalliset kansalaiset eivät pysty toimimaan yhdessä tehokkaasti suojellakseen omia etujaan. Koska heidän yhteistyönsä esteet ovat suuret ja yksittäisen henkilön tuotto ryhmän yhteisten etujen menestyksekkäästä puolustamisesta on minimaalinen, miljoonat tavalliset kansalaiset eivät onnistu rajoittamaan varojensa luovuttamista hallitukselle yhtä hyvin kuin pienemmät ryhmät, joilla on suotuisammat kannustimet.

Muut seikat pysyvät ennallaan, odotettaisiin siis, että massademoskratiassa hallitus saadessa käsiinsä suuremman osan kokonaisresursseista kuin oligarkiassa tai järjestelmässä, jossa suvereniteetti on pirstaleista ja jossa magnaatit käyttävät sotilaallista voimaansa ja varustavat omat armeijansa – kuten se tapahtui kaikkialla varhaisessa modernissa Euroopassa ennen kahdeksantoista vuosisataa.

Näin ollen yksi keskeinen, vaikka harvoin tarkasteltu syy demokratian kasvuun länsimaissa on neuvottelukustannusten suhteellinen merkitys aikana, jolloin väkivallan tuotto kasvoi. Resurssien kerääminen harvoilta oli aina kalliimpaa kuin niiden ottaminen monilta.

Suhteellisen pieni, eliittinen rikas ryhmä muodostaa yhtenäisemmän ja tehokkaamman kokonaisuuden kuin suuri kansanjoukko. Pieni ryhmä kannustaa yhteistyöhön vahvemmin ja on lähes väistämättä tehokkaampi suojelemaan etujaan kuin massajoukko.'[^179] Ja vaikka suurin osa ryhmän jäsenistä päättäisi olla tekemättä yhteistyötä yhteisen toiminnan eteen, muutama rikas voi silti pystyä käyttämään tarpeeksi resursseja työn hoitamiseen.

Demokraattisen päätöksenteon avulla kansallisvaltio pystyi harjoittamaan valtaansa paljon täydellisemmin miljoonien ihmisten yli, jotka eivät pystyneet helposti toimimaan kollektiivisesti omaksi edukseen, kuin se pystyi neuvottelemaan paljon pienemmän määrän kanssa, jotka pystyivät helpommin voittamaan organisaatio-ongelmat keskittyneiden etujensa puolustamisessa. Demokratialla oli vieläkin vakuuttavampi etu: se loi legitimisoivan päätöksentekosäännön, joka mahdollisti valtion hyödyntää varakkaiden resursseja ilman, että heidän lupaansa tarvittaisiin suoraan neuvotellen. Lyhyesti sanottuna demokraattinen päätöksentekomekanismi sopi erinomaisesti teollistuneen aikakauden megapoliittisiin olosuhteisiin. Se täydensi kansallisvaltiota, koska se mahdollisti sotivoiman keskittymisen hallitsijoidensa käsiin aikana, jolloin käytetty voima oli tärkeämpää kuin sen mobilisoinnin tehokkuus.

Tämä käy ilmi ratkaisevasti Ranskan vallankumouksessa, joka kasvatti sotilaallisen voiman määrää taistelukentällä. Sen jälkeen muut kilpailevat kansallisvaltiot joutuivat lähes pakotetuiksi omaksumaan vastaavanlaisen järjestelmän, jonka legitiimiyteen sidottiin lopulta demokraattinen päätöksenteko. Yhteenvetona voidaan todeta, että demokraattinen kansallisvaltio menestyi viimeisten kahden vuosisadan aikana näiden piilotettujen syiden vuoksi:

1. Väkivallan tuotto kasvoi, mikä teki voiman määrän hallintaperiaatteena tärkeämmäksi kuin sen mobilisoinnin tehokkuus.
2. Tulot nousivat tarpeellisesta yläpuolelle niin, että valtio pystyi keräämään suuria määriä kokonaisresursseja ilman, että sen tarvitsi neuvotella vastustavien vaikutusvaltaisten magnattien kanssa.
3. Demokratia osoittautui riittävän yhteensopivaksi vapaiden markkinoiden kanssa, mikä edisti kasvavien varallisuuksien syntyä.
4. Demokratia helpotti hallituksen hallintaa sen "työntekijöiden" toimesta, mikä varmisti, että menojen, mukaan lukien sotamenojen, rajoittaminen olisi vaikeaa.
5. Demokratia päätöksentekosääntönä osoittautui tehokkaaksi vastalääkkeeksi rikkaiden kyvylle toimia yhdessä rajoittaakseen kansallisvaltion mahdollisuuksia verottaa tai muulla tavoin suojella heidän omaisuuttaan tunkeutumiselta.

Demokratia nousi sotilaallisesti voittavaksi strategiaksi, koska se mahdollisti enemmän resurssien keskittämisen valtion käsiin. Verrattuna muihin suvereniteetin malleihin, joiden legitimiteetti perustui muihin periaatteisiin – kuten feodaaliseen veroon, kuninkaiden jumalalliseen oikeuteen, yritysten uskonnolliseen velvollisuuteen tai rikkaiden vapaaehtoisiin panoksiin – massademokratiasta tuli sotilaallisesti tehokkain, sillä se oli varmin keino kerätä resursseja teollistuneessa taloudessa.

> "The nation, as a culturally defined community, is the highest symbolic value of modernity; it has been endowed with a quasi-sacred character equaled only by religion. In fact, this quasi-sacred character derives from religion. In practice, the nation has become either the modern, secular substitute of religion or its most powerful ally In modern times the communal sentiments generated by the nation are highly regarded and sought after as the basis for group loyalty... That the modern state is often the beneficiary should hardly be surprising given its paramount power"[^180] - JOSEPH R. LLOBERA

### Nationalismi

Sama pätee myös nationalismiin, joka muodostui massademokratian luonnolliseksi jatkumoksi. Ne valtiot, jotka osasivat hyödyntää nationalismia, huomasivat pystyvänsä liittämään suurempia armeijoita pienemmillä kustannuksilla. Nationalismi oli keksintö, joka mahdollisti sen, että valtio pystyi laajentamaan sotilaallista tehokkuuttaan. Kuten politiikka itsessään, myös nationalismi on pääosin moderni keksintö. Kuten sosiologi Joseph Llobera on runsaasti dokumentoidussa teoksessaan nationalismin noususta osoittanut, kansa on kuvitteellinen yhteisö, joka syntyi suurelta osin valtion vallan mobilisoimisen tapana Ranskan vallankumouksen aikana. Kuten hän sanoo, "modernin käsitteen mukainen kansallistieto on ollut olemassa vasta Ranskan vallankumouksen jälkeen, siitä ajasta lähtien kun vuonna 1789 Constituent Assembly yhtenäisti Ranskan kansan Ranskan kansakunnaksi."[^181]

Nationalismi teki vallan mobilisoimisesta ja suuren väkimäärän hallinnasta helpompaa. Kansallisvaltiot muodostuivat korostamalla niitä piirteitä, jotka ihmisillä oli yhteisiä, erityisesti puhuttua kieltä. Tämä helpotti hallintoa ilman välikäsiä ja yksinkertaisti byrokratian tehtäviä. Yksi kielellä julkistettavat asetukset voidaan tiedottaa nopeammin ja vähemmällä sekaannuksella kuin ne, jotka on käännettävä lukemattomille kielille. Nationalismi pyrki siis alentamaan laajojen alueiden hallinnan kustannuksia. Ennen nationalismin aikaa varhaismoderni valtio tarvitsi apua esimerkiksi herroilta, herttaamilta, kreivilta, pisboeilta, vapaista kaupungeista ja muilta yritys- sekä etnisiltä välikäsiltä – veroviljelijöiltä, sotisopimuskauppiailta ja palkkasotureilta – verotulojen keräämiseen, armeijoiden nostamiseen ja muihin hallintotehtäviin.

Nationalismi myös ratkaisevasti alentoi sotilaallisen henkilöstön mobilisointikustannuksia kannustamalla ryhmätunnistusta valtion etujen kanssa. Ryhmäidentiteetin sitomisen valtion etuihin oli niin merkittävä etu, että useimmat valtiot, jopa väitetysti internationalistinen Neuvostoliitto, yhtenäistyivät nationalismiin täydentävänä ideologiana.

Pitkässä tarkastelussa nationalismi on yhtä paljon poikkeavuus kuin valtio itse. Kuten historioitsija William McNeill on dokumentoinut, monietnisiä suvereniteetteja oli aikoinaan arkipäivää.[^182]

McNeillin sanoin: "Ajatus siitä, että hallituksen tulisi oikeutettomasti hallita vain yhden etnisen ryhmän kansalaisia, alkoi kehittyä Länsi-Euroopassa keskiajan lopulla."[^183] Varhaisena nationalistisenä toimijana oli Preussin liitto (Preussicher Bund), joka muodostettiin vuonna 1440 vastalauseena Teutonijärjestyksen hallinnolle. Joitakin järjestyksen piirteitä korostettiin aiemmin äärimmäisenä esimerkkinä suvereniteetista, joka poikkesi kansallisvaltiosta. Teutonijärjestys oli eräänlainen perussopimuksella toimiva yhtiö, jonka jäsenistä lähes kukaan ei ollut kotoisin Preussista. Sen päämaja vaihteli eri aikoina Bremenistä ja Lübeckistä Jerusalemiin, Acreen, Venetsiaan ja edelleen Vistulan Marienbergiin. Aikoinaan se hallitsi Burzenlandin aluetta Transilvaniassa. Ei ole yllättävää, että näin valtioihin niin erilaisessa suvereniteetissa toimineesta järjestyksestä tuli yksi varhaisimmista yrityksistä mobilisoida kansallistunnetta vallan järjestämiseksi. Kuitenkin osoituksena siitä, kuinka erilainen varhainen nationalismi oli myöhempiin muotoihin verrattuna, saksankieliset Preussin liiton aateliset kertoivat vetoavansa Puolan kuninkaalle asettamaan Preussan Puolan hallintaan, lähinnä siksi, että jo silloin Puolan kuningas oli suhteellisen heikko hallitsija, jolta ei odotettu hallitsevan samalla tiukkuudella kuin Teutonijärjestys.

Varhaisessa vaiheessaan nationalismi nousi esiin juuri ennen ruuti-ammantulkintaansa ja kehittyi edelleen varhaismodernin valtion myötä, saavuttaen kvanttimekaanisen harppauksen merkityksessään Ranskan vallankumouksen aikaan. Uskomme, että nationalismi voimana on jo alkanut hiipua. Se saavutti todennäköisesti huippunsa Woodrow Wilsonin pyrkiessä antamaan jokaiselle Euroopan etniselle ryhmälle oman valtionsa ensimmäisen maailmansodan lopulla. Nykyään se on reaktiivinen voima, joka kuumenee alueilla, joilla tulot laskevat ja näkymät heikkenevät, kuten Serbiassa.

Kuten myöhemmin tarkastelemme, odotamme nationalismin olevan keskeinen yhteisöteema matalapalkkaisten ihmisten keskuudessa, jotka ovat nostalgisia pakottamisen muodoista, kun hyvinvointivaltio romahtaa länsimaisissa demokratioissa. Et ole vielä nähnyt mitään. Useimmille länsimaalaisille kommunismin kuolemasta seuraavat seuraukset ovat vaikuttaneet suhteellisen harmittomilta. Olet nähnyt sotakulut laskeneen, alumiinihintojen romahtaneen ja uuden lähteen NHL:n jääkiekkopelaajille. Tämä on hyviä uutisia. Se on uutisia, joista useimmat 1900-luvulla aikuiseksi tulleet voisivat ylistää, erityisesti jääkiekkofanina. Suurin osa siitä uutismateriaalista, joka näyttäytyy vähemmän suosituksi, on vielä edessä.



Teollisen aikakauden myötä ne megapoliittiset olosuhteet, joita demokratia aiemmin täytti, alkavat nopeasti hävitä. Siksi on epäilyttävää, että massademokratia ja hyvinvointivaltio selviäisivät kauan uuden, Information aikakauden megapoliittisissa olosuhteissa.

> "Congress was not a temple of democracy it was a market for bartering laws." - ALBERTO FUJIMORI, president of Peru

Tulevaisuuden historioitsijat saattavatkin raportoida, että olemme jo nähneet ensimmäisen postmodernin vallankaappauksen – Peruussa vuonna 1993 tapahtuneen merkittävän kongressin lukitsemisen. Tämä ei ollut juuri mikään tapahtuma, joka olisi kerännyt paljon myönteistä huomiota johtavissa teollisissa demokratioissa. Mutta ajan myötä sen merkitys saattaa osoittautua enemmän, kuin tavanomaiset analyytikot ennustavat. Harvat, jotka siitä ovat miettineet, pitävät sitä vain yhtenä valtaotteena, josta Latinalaisen Amerikan historiassa on tullut masentavan tuttu. Me taas näemme sen mahdollisesti ensimmäisenä askeleena delegitimoida hallintomuoto, jonka välitön megapoliittinen perustelu on alkanut kadota siirryttäessä Information aikakauteen. Fujimorin kongressin sulkeminen on oire lopullisesta poliittisten lupauksien arvon heikkenemisestä. Samankaltainen kohtalo voisi odottaa muita lainsäädäntöelimiä, kun niiden luottamus loppuu.

Teollisuuden murenemista edistävä teknologian murros on loukannut monia maita valtioilla, joiden hallinto ei enää toimi – tai toimii hyvin huonosti. Erittäin erityisesti lainsäädäntöelimet näyttävät olevan yhä toimimattomampia. Ne valmistavat lakeja, jotka saattaisivat olla vain typeriä viisikymmentä vuotta sitten, mutta ovat nykyisin vaarallisia. Tämä oli peruussa vuoden 1993 tilanteessa erityisen ilmeistä, jolloin valtion sisäinen suvereniteetti oli melkein romahtanut.

> "Attacks, kidnappings, rapes and murders have coincided with increasingly aggressive driving habits and unsafe streets. The police have gradually lost control of the situation and some of their members have been involved in scandals and become seasoned criminals . . . People have gradually grown used to living outside the law. Theft, illegal seizure and factory takeovers have become everyday occurrences."[^184] - HERNANDO DE SOTO

### Peru raunioina

Tietyllä tavalla Peru ei enää vuonna 1993 ollut moderni kansallisvaltio. Sillä oli vielä lippu ja armeija, mutta suurin osa sen instituutioista oli raunioina. Myös vankilat oli vallattu vangeilta. Tämä hajoaminen voidaan jäljittää lukuisiin syihin, mutta useimmat asiantuntijoiden yritykset selittää sitä eivät osaa osua ydinkohtaan. Peru oli varhainen uhri teknologisen muutoksen seurauksena, joka tekee suljetuista talouksista toimimattomia ja heikentää keskitettyä auktoriteettia kaikkialla. Nämä megapoliittiset rasitukset pahentuvat, koska päätöksentekoinstituutiot, kuten Perun kongressi, ovat perverseihin kannustimiin loukussa, mikä saa ne kasaamaan juuri ne ongelmat, jotka niiden tulisi ratkaista.

Perun edustuksellinen demokratia oli kuin pari lastattuja noppia. Valtion voimaa kasvattavana päätöksentekomekanismina se oli ylivoimainen. Mutta kun uudet olosuhteet vaativat vallan devalvoimista, ne sisäiset vinoumat, jotka tekivät demokratiasta niin hyödyllisen vanhoissa megapoliittisissa olosuhteissa, muuttuvat yhä toimimattomammiksi. Itse kongressin hyväksymät lait tuhosivat nopeasti kaiken minkä varaan lait voisivat perustua – arvoa tai kunnioitusta kohtaan. Kuten de Soto totesi teoksessaan *The Other Path*:  
"Small interest groups fight among themselves, cause bankruptcies, implicate public officials. Governments hand out privileges. The law is used to give and take away far more than morality permits." [^185]  
Perun kaltaisessa kongressissa, joka on täysin erityisryhmiin alistunut, on kaiken moraalisen arvokkuuden puute verrattuna muihin ryhmiin, jotka myyvät varastettuja tavaroita huutokaupassa. Se teki vapaasta markkinasta laittoman ja siten teki laista naurettavan. De Soto kuvaa pre-Fujimorin aikaa seuraavasti:

> A complete subversion of ends and means has turned the life of Peruvian society upside down, to the point that there are acts which, although officially criminal, are no longer condemned by the collective consciousness. Smuggling is a case in point. Everyone, from the aristocratic lady to the humblest man, acquires smuggled goods. No one has scruples about it; on the contrary, it is viewed as a kind of challenge to individual ingenuity or as revenge against the state. This infiltration of violence and criminality into everyday life has been accompanied by increasing poverty and deprivation. In general terms, Peruvians' real average income had declined steadily over the last ten years and is now at the level of twenty years ago. Mountains of garbage pile up on all sides. Night and day, legions of beggars, car washers, and scavengers besiege passersby, asking for money. The mentally ill swarm naked in the streets, stinking of urine. Children, single mothers, and cripples beg for alms on every corner. The traditional centralism of our society has proved clearly incapable of satisfying the manifold needs of a country in transition.[^186]

De Soto kuvaili kongressin lukitsemistä Fujimorin aikana tapahtuneen järkyttävän laillisen talouden luopumisena mustalle markkinalle "näkymättömänä vallankumouksena."

Olemme positiivisia vapaakaupan hyödyistä, mutta paljon vähemmän innoissamme sellaisen yhteiskunnan lupauksesta, jossa laki on heikentynyt yhtä paljon kuin raha. Se maailma, jonka de Soto kuvaili Perussa ennen vuotta 1993, oli kuin "Clockwork Orange" –maailma, jossa liiallisesti keskitetyt ja toimimattomat hallinnolliset instituutiot kirjaimellisesti tuhosivat kansalaisyhteiskuntaa.

Juuri tätä Fujimori pyrki muuttamaan. Hän oli leikkaanut inflaatiota sammuttamalla painokoneet. Hän oli myös onnistunut erottamaan viisikymmentä tuhatta valtion työntekijää ja karsimaan joitakin tukia. Hän oli aloittanut budjetin tasapainottamisen. Hänen uudistussuunnitelmansa sisälsivät kattavat suunnitelmat vapaiden markkinoiden luomiseksi ja teollisuuden yksityistämiseksi. Mutta kuten entisessä Neuvostoliitossa, suurin osa Fujimorin uudistusten tärkeistä osatekijöistä ei ollut vielä käytössä vuonna 1993, mukaan lukien ensimmäinen erä valtion pankkien, kaivosyhtiöiden ja hyödykkeiden laajamittaisesta yksityistämisestä. Sen sijaan, että nämä välttämättömät ehdotukset olisi saatu voimaan, Perun kongressi – kuten Moskovassa Yeltsinin uudistuksia haastanut Venäjän kongressi – pyrki taaksepäin. Heidän suunnitelmansa oli palauttaa tuet tyhjästä valtiovarastosta, lisätä palkkalistaa ja suojella kaikkia vakiintuneita etuja, erityisesti byrokratiaa – juuri sitä, mitä odottaisit työntekijöidensä hallitsemalta hallitukselta.

Fujimori väitti, että Perun kongressi oli uuvuttu ja korruptoitunut, mikä oli lähes kaikkien mielestä ilmiselvää. Hän lisäksi toteutti, että kongressin epäröinti ja korruptio tekivät mahdottomaksi uudistaa Perun romahtavaa taloutta tai torjua väkivaltaista hyökkäystä narkoteroristeilta ja nihilistisiltä Sendero Luminoso (Shining Path) -gerilla-joukoilta.

### 70 prosentin ratkaisu

Joten Fujimori sulki kongressin, teko, joka olisi voinut viitata siihen, että hän oli yhtä autoritaarinen kuin monet aiemmat Latinalaisen Amerikan johtajat. Mutta me ajattelimme – ja niin myös silloin puhuimme – että Fujimori oli tunnistanut oikein keskeisen esteen uudistukselle. Amerikkalaisten lehdistösikirjoittajien ja State Departmentin virkamiesten ylistykset Perun kongressista eivät vastanneet Perun kansan mielipidettä. Sillä aikaa kun pohjoisamerikkalaiset jatkoivat kuin Perun kongressi olisi ollut vapauden ja sivistyksen ruumiillistuma, perulaiset innostuivat. Presidentti Fujimorin suosio nousi yli 70 prosenttiin, kun hän lähetti kongressin kotiin. Hänet valittiin myöhemmin toiselle kaudelle jyrkän voiton merkeissä. Suurin osa kansalaisista näki lainsäädäntönsä enemmänkin esteenä hyvinvoinnilleen kuin oikeuksiensa ilmentymänä. Vuonna 1994 Perun reaalinen talouskasvu saavutti 12,9 prosenttia, mikä oli maailman korkein.

### Poliittisten lupauksien deflaatio

Me näimme Perun sekasorroja vähemmän paluuna menneisyyden diktatuureihin ja enemmänkin varhaisena osana laajempaa siirtymäkriisiä. Voit odottaa näkeväsi monissa maissa huonoa hallinnointia koskevia kriisejä, kun poliittiset lupaukset "puhkeavat" ja hallitukset loppuvat luotosta. Lopulta on kehitettävä uusia instituutioita, jotka kykenevät turvaamaan vapauden uusissa teknologisissa olosuhteissa samalla, kun ne ilmentävät ja elävöittävät kaikkien kansalaisten yhteisiä etuja.

Harva on alkanut pohtia joidenkin teollisen hallinnon instituutioiden ja jälkitteollisen yhteiskunnan megapolitiikan välistä yhteensopimattomuutta. Olipa nämä ristiriidat nimenomaisesti myönnettyjä tai ei, niiden seuraukset käynevät yhä ilmeisemmiksi, kun poliittisten epäonnistumisten esimerkit kasaantuvat ympäri maailmaa. Modernilla ajalla syntyneet hallintorakenteet heijastavat yhden tai useamman vuosisadan megapoliittisia olosuhteita. Information aikakausi vaatii uusia edustuksen mekanismeja välttääkseen kroonista toimimattomuutta ja jopa yhteiskunnan romahdusta.

Kun Berliinin muuri kaatui vuonna 1989, se ei ainoastaan merkinnyt kylmän sodan loppua, vaan myös ulkoista merkkiä hiljaisesta maanjäristyksestä maailman vallan perustuksissa. Se oli loppu pitkälle kestäneelle väkivallan tuottojen nousun ajalle. Kommunismin kaatuminen, jonka ennustimme jo vuonna 1987 teoksessamme *Blood in the Streets* ja jopa aikaisemmin kuukausittaisessa uutiskirjeessämme *Strategic Investment*, ei ollut vain ideologian hylkäämistä. Se oli ulkoinen merkki viimeisten viiden vuosisadan tärkeimmästä kehityksestä väkivallan historiassa. Jos analyysimme pitää paikkansa, yhteiskunnan järjestäytymisen on määrä muuttua heijastamaan väkivallan käytön kasvavia mittakaavaepäteisyyksiä. Ne rajat, joiden sisällä tulevaisuuden on määrä olla, on piirretty uudelleen.

[^163]: Quoted in Tilly, op. cit., p.84.

[^164]: Katso John Keegan, *A History of Warfare* (London: Hutchinson, 1993), s.321.

[^165]: Jim Taylor ja Watts Wacker, The 500-Year Delta: What Happens After What Comes Next. New York: HarperCollins, 1997, s. 38–39.

[^166]: Ibid., s. 39.

[^167]: The Cambridge Ancient History, op. cit., s.263–64.

[^168]: Cook et al., op. cit., s.268.

[^169]: Lisätietoja hydraulisten yhteiskuntien logiikasta, katso Karl A. Wittfogel, *Oriental Despotism: A Comparative Study of Total Power* (New Haven: Yale University Press, 1957).

[^170]: Tilly, op. cit., s.28.

[^171]: Lane, "Consequences of Organized Violence," op. cit., s.406.

[^172]: Ibid.

[^173]: Ibid., s.412.

[^174]: Tilly, op. cit., s. 96–126.

[^175]: Ibid., s. 130.

[^176]: Ibid., s. 110.

[^177]: Tämä esimerkki op. cit., s. 139.

[^178]: Ibid., s. 115.

[^179]: Katso Mancur Olson, *The Logic of Collective Action* (Cambridge: Harvard University Press, 1965).

[^180]: Josep R. Llobera, *The God of Modernity: The Development of Nationalism in Western Europe* (Oxford: Berg Publishers, 1994), s. ix–x.

[^181]: Ibid., s. xiii.

[^182]: Katso William McNeill, *Polyethnicity and National Unity in World History* (Toronto: University of Toronto Press, 1986).

[^183]: Ibid., s. 7.

[^184]: Hernando de Soto, *The Other Path* (New York: Harper & Row, 1989).

[^185]: Ibid.

[^186]: Ibid., s. 6.