# informaatiokauden megapoliittisuus

:::{.content-hidden when-format=latex}
*Tehokkuuden voitto vallasta*
:::

> "...yhä enenevässä määrin Yhdysvaltojen taloutta ohjaa tietokoneistetun informaation voima – ei työvoima tai massatuotanto – ja se voittaa sotia maailmassa, johon on kytketty 500 TV-kanavaa. Tietokoneistettu informaatio on olemassa kyberssa – uudessa ulottuvuudessa, joka on luotu tietoverkkojen, satelliittien, modeemien, tietokantojen ja julkisen Internetin loputtomalla toistolla."[^187]: - NEIL MUNRO

30. joulukuuta 1936 autotyöntekijät, jotka vaativat korkeampia palkkoja, valtasivat väkisin kaksi General Motorsin päätehdasta Flintissä, Michiganissa. He pysäyttivät koneet, sammutti kokoonpanolinjat ja ottivat tilaa itselleen. Tehtaissa työskentelevät, joiden tehtävänä oli operoida tuotantoprosesseja, istuivat alas aloittaen teollisen vastakkainasettelun, joka kestäisi useita viikkoja. Tämä draama huipentui väkivaltaisiin mellakoihin ja poliisin, Michiganin varuskuntaisten sekä eri hallinnon tasojen poliittisten vaikuttajien jatkuvasti vaihtuviin kannattajiin. Huomatessaan, ettei heidän vaatimuksiaan päästy tavoittelemaan, liitto ryhtyi jälleen lakkoon 1. helmikuuta 1937.

Liittoaktivistit valtasivat väkisin GM:n Chevrolet-tehtaan Flintissä. Sulkemalla ja valtaamalla General Motorsin keskeiset tehtaat työntekijät lamaannuttivat yhtiön tuotantokyvyn. Kolmannen tehtaan valtaamisen jälkeisen kymmenen päivän aikana GM valmisti Yhdysvalloissa vain 153 autoa.

Käymme läpi 60 vuotta vanhan uutispilotin, jotta nykyisten megapoliittisten olosuhteiden vallankumousta voitaisiin asettaa selkeämpään kontekstiin. GM:n istumatyölakko tapahtui joidenkin tämän kirjan lukijoiden elinaikana. Uskomme kuitenkin, että istumatyölakot osoittautuvat anakronistisiksi informaation aikakaudella, aivan kuten aikoinaan orjat, jotka vaivautuivat autiomaan halki vieden mukanaan valtavia kiviä faaraoiden hautapyramideja varten. Vaikka työväenliitot ja niiden pelottelutaktiikat muodostivat teollisuusaikana kiistattoman osan yhteiskunnan maisemaa, ne perustuivat erityisolosuhteisiin, jotka ovat nyt nopeasti katoamassa. Informaatiotien aikakaudella ei tule olemaan Chevroletteja eikä UAW:n kaltaisia liittoja lakkoilemassa.

Hallintojen kohtalo seuraa liittojen kohtaloa alamäessä. 1900-luvun yhteiskuntaa määrittäneen institutionalisoidun pakottamisen muoto ei enää tule olemaan mahdollinen. Tekniikka nopeuttaa syvällistä muutosta kiristyksen ja suojelun logiikassa.

> "… ei ole mitään omistusoikeutta, valtakuntaa, erillistä minun ja sinun – vaan jokaiselle kuuluu se, mitä hän pystyy saamaan, ja niin kauan kuin hän sen voi pitää."[^188]: -THOMAS HOBBES

### Kiristys ja suojelu

Kautta historian väkivalta on ollut kuin tikari, joka on kohdistettu talouden ytimeen. Kuten Thomas Schelling oivallisesti totesi, "kyky satuttaa – tuhota asioita, joita joku arvostaa, aiheuttaa kipua ja surua – on eräänlainen neuvotteluvoima, jota ei ole helppo käyttää, mutta jota käytetään usein. Alamaailmassa se toimii kiristyksen, ulkonauhinnan ja kidnappauksen perustana, kaupallisessa maailmassa boikotteja, lakkoja ja sulkutiloja varten... Se on usein myös siviili- ja sotilaallisen kurinpidon perusta; jumalatkin käyttävät sitä kurinpidon toteuttamiseen."[^189]: Valtion kyky verottaa itseään riippuu samoista haavoittuvuuksista kuin yksityiset kiristystoimet. Vaikka emme yleensä ajattele sitä näin, se osuus omaisuudesta, jota hallitaan ja käytetään pakottavasti – rikollisuuden ja hallinnon keinoin – tarjoaa karkean mittarin megapoliittisesta tasapainosta kiristyksen ja suojelun välillä. Jos teknologia tekisi omaisuuserien suojelemisesta vaikeaa, rikollisuus levittäytyisi laajasti, ja samoin liitotoiminta. Tällaisissa olosuhteissa hallituksen tarjoama suojelu vaatisi lisäpalkkiota. Verot olisivat korkeat. Missä verot ovat alhaiset ja työpaikoilla palkat määräytyvät markkinavoimien eivätkä poliittisen puuttumisen tai pakottamisen kautta, teknologia on kallistanut tasapainon suojelun puolelle.

Teknologinen epätasapaino kiristyksen ja suojelun välillä saavutti ääripäänsä 1900-luvun kolmannen vuosineljänneksen lopussa. Joissakin kehittyneissä länsimaisissa yhteiskunnissa hallitukset ottivat haltuunsa yli enemmistön resursseista. Suuren osan väestön tuloista määräytyi joko yksipuolisesti määräyksellä tai pakottamisen, kuten lakkojen tai muun väkivallan uhkauksien vaikutuksesta. Hyvinvointivaltio ja ammattiliitto olivat molemmat teknologian synnyttämiä ilmiöitä, jotka jakoivat kokenut vallan voiton tehokkuutta vastaan 1900-luvulla. Ne eivät olisi voineet syntyä ilman sotilaallisia ja siviiliteknologioita, jotka teollisella aikakaudella nostivat väkivallan tuottoja.

Omaisuuserien luomiskykyyn liittyy aina tietty haavoittuvuus kiristykselle. Mitä enemmän omaisuutta on luotu tai hallussa, sitä korkeampi hinta jollain tapaa on maksettava – joko maksamalla kaikille, joilla on mahdollisuus käyttää väkivaltaa kiristämiseen, tai hankkimalla sotilaallinen voima, joka kykenee murskaamaan minkä tahansa raakuuden yrityksen.

> 'Väkivaltaa ei enää kuulua sinun maassasi, eikä tuhoa tai tuhlausta sinun rajoillasi...' - ISAIAH 60:1

### Suojelun matematiikka

Nyt väkivallan tikari saattoi pian tylsiä. Tietotekniikka lupaa muuttaa dramaattisesti suojelun ja kiristyksen välistä tasapainoa, tehden omaisuuserien suojaamisesta monissa tapauksissa huomattavasti helpompaa ja kiristyksestä vaikeampaa. Information Ageden teknologia mahdollistaa omaisuuserien luomisen, jotka ovat monien pakottamisen muotojen ulottumattomissa. Tämä uusi asymmetria suojelun ja kiristyksen välillä perustuu perusmatematiikan totuuteen: kertominen on helpompaa kuin jakaminen. Vaikka tämä totuus on hyvin perustavanlaatuinen, sen laajat seuraukset olivat piilossa ennen mikroprosessoreiden aikakautta. Korkeanopeuslaitteet ovat mahdollistaneet viime vuosikymmenen aikana miljardeja kertoja enemmän laskutoimituksia kuin mitä on tehty koko jälleen aiemmassa maailman historiassa. Tämä laskentatehon harppaus on antanut meille ensimmäistä kertaa mahdollisuuden ymmärtää joitakin kompleksisuuden universaaleja ominaisuuksia. Tietokoneet osoittavat, että monimutkaisia järjestelmiä voidaan rakentaa ja ymmärtää vain alhaalta ylöspäin. Alkulukujen kertominen on yksinkertaista, mutta suurten alkulukujen tuloksen hajoittaminen niiden peruselementeiksi on käytännössä mahdotonta. Kevin Kelly, *Wired*-lehden päätoimittaja, ilmaisee asian näin: 'Useiden alkulukujen kertominen suuremmaksi tuloksi on helppoa; jokainen alakoululainen pystyy siihen. Mutta maailman supertietokoneet tukahduttuvat yrittäessään selvittää tulosta sen yksinkertaisiksi alkuluvuiksi.'[^190]

### Kompleksisten järjestelmien logiikka

Kybertalous muotoutuu väistämättä tämän syvällisen matemaattisen totuuden vaikutuksesta. Se ilmenee jo selvästi voimakkaissa salausalgoritmeissa. Kuten myöhemmin tässä luvussa selvitetään, nämä algoritmit mahdollistavat uuden, suojatun kybertalousalueen luomisen, jossa väkivallan käyttövoima on huomattavasti heikentynyt. Kiristykseen ja suojeluun kohdistuva tasapaino kallistuu dramaattisesti suojelun puolelle. Tämä edistää sellaisen talouden syntyä, joka luottaa enemmän spontaanisti mukautuviin mekanismeihin ja vähemmän tietoiseen päätöksentekoon ja resurssien jakamiseen byrokratian kautta. Uusi järjestelmä, jossa suojelu on etusijalla, on hyvin erilainen kuin teollisuusajan pakottamisen varassa syntynyt järjestys.

### Käsky- ja hallintajärjestelmät ovat primitiivisiä

Kirjoitimme teoksessa *The Great Reckoning*, että tietokone mahdollistaa meille 'näkemään' monien järjestelmien aiemmin näkymättömän kompleksisuuden.[^243] Kehittynyt laskentateho ei ainoastaan auta meitä ymmärtämään kompleksisten järjestelmien dynamiikkaa paremmin, vaan mahdollistaa myös näiden kompleksisuuksien hyödyntämisen tuottavilla tavoilla. Tavallaan kyse ei ole edes valinnasta, vaan väistämättömyydestä, mikäli talous haluaa edetä jäykän keskushallinnan vaiheesta eteenpäin. Tällainen järjestelmä, joka perustuu lineaarisiin suhteisiin, on pohjimmiltaan primitiivinen. Hallituksen resurssien siirto johtaa väistämättä siihen, että arvokkaat, monimutkaiset käyttötarkoitukset jäävät vähemmälle, kun taas matala-arvoiset primitiiviset käyttötarkoitukset kasvavat. Tämä prosessi on rajoitettu samalla matemaattisella epäsymmetrialla, joka estää suurten alkulukujen tulon purkamisen. Saaliin jakaminen voi olla vain primitiivistä.

### Kaikki muuttuu yhä monimutkaisemmaksi

Joka paikkaa katsotkin universumissa, näet järjestelmien kehittyvän yhä monimutkaisemmiksi niiden kehittyessä. Tämä pätee tähtitieteessä. Sama on totta myös lätäköissä. Jätä sadevesi rauhaan matalassa paikassa, niin se kasvaa monimutkaisemmaksi. Kaikenlaiset edistyneet järjestelmät ovat kompleksisia sopeutuvia järjestelmiä ilman keskitettyä auktoriteettia. Jokainen luonnossa esiintyvä monimutkainen järjestelmä – josta markkinatalous on ilmeisin sosiaalinen ilmentymä – perustuu hajautettuihin kyvykkyyksiin. Järjestelmät, jotka toimivat tehokkaimmin laajimmassa mahdollisessa olosuhteiden kirjossa, saavat kestävyyden spontaanista järjestyksestä, joka kykenee vastaanottamaan uusia mahdollisuuksia. Itse elämä on tällainen monimutkainen järjestelmä. Miljardit mahdollisia geenien yhdistelmiä tuottavat yksittäisen ihmisen, ja niiden järjestäminen sekoittaisi minkä tahansa byrokratian.

Kaksikymmentäviisi vuotta sitten tämä olisi voinut olla vain intuitiivinen havainto. Tänään se on osoitettavissa. Mitä lähempänä tietokoneet tuovat meidät tekoelämän matematiikan ymmärtämiseen, sitä paremmin ymmärrämme myös todellisen elämän matematiikkaa, joka on biologisen monimutkaisuuden matematiikkaa. Näitä monimutkaisuuden salaisuuksia, joita hyödynnetään informaatioteknologian kautta, voidaan käyttää talouksien uudelleen muokkaamiseen yhä monimutkaisemmiksi muodoiksi. Internet ja World Wide Web ovat jo omaksuneet orgaanisen järjestelmän ominaisuuksia, kuten Kevin Kelly ehdottaa *Out of Control: The New Biology of Machines, Social Systems, and the Economic World* -teoksessaan.[^191] Hänen sanojensa mukaan luonto on "ideatehdas. Elintärkeitä, postteollisia paradigmaa piileekin jokaisessa viidakon muurahaismäessä... Biologian massasiirron tapahtuminen koneisiin saisi meidät hämmästymään. Kun synnynnäisen ja tehdyn liitto on täydellinen, valmistuksemme oppivat, sopeutuvat, parantavat itseään ja kehittyvät. Tämä on voima, josta emme ole vielä juurikaan edes uneksineet."[^192]

Todellakin, "biologian massasiirron" seuraukset tulevat olemaan laaja-alaiset. Sosiaalisissa järjestelmissä on aina ollut vahva taipumus jäljitellä vallitsevan teknologian ominaisuuksia – tämä ymmärsi Marx. Jättimäiset tehtaat saapuivat suuren hallituksen aikaan, ja mikroprosessointi pienentää instituutioita. Jos analyysimme pitää paikkansa, informaatiokauden teknologia lopulta luo talouden, joka kykenee hyödyntämään monimutkaisuuden etuja paremmin.

Kuitenkin tällaisten muutosten megapoliittiset ulottuvuudet ovat niin vähän ymmärrettyjä, että vaikka useimmat ovat tunnustaneet sen matemaattisen merkityksen, monet ovat tehneet sen anakronistisella tavalla. On yksinkertaisesti vaikea täysin omaksua ja sisäistää se, että seuraavien vuosien teknologinen muutos vanhentaa suurimman osan modernin maailman poliittisista muodoista ja käsitteistä. Esimerkiksi myöhäisen fyysikon Heinz Pagels kirjoitti visionäärisessä *The Dreams of Reason* -teoksessaan: "Olen vakuuttunut siitä, että ne kansakunnat ja ihmiset, jotka hallitsevat monimutkaisuuden uutta tiedettä, tulevat seuraavan vuosisadan taloudellisiksi, kulttuurisiksi ja poliittisiksi supervalloiksi."[^193] Se on vaikuttava ennuste. Uskomme kuitenkin, että ennuste on virheellinen – ei siksi, että se olisi väärin ymmärretty, vaan juuri siksi, että se osoittautuu vielä osin oikeammaksi kuin tohtori Pagels uskalsi ilmaista. Yhteiskunnat, jotka uudelleen järjestäytyvät monimutkaisemmiksi sopeutuviksi järjestelmiksi, menestyvät ilman muuta; kun näin tapahtuu, ne eivät kuitenkaan todennäköisesti muutu kansakunniksi – saati sitten "poliittisiksi supervalloiksi." Todennäköisimmät välittömät hyötyjät sosiaalisten järjestelmien lisääntyneestä monimutkaisuudesta ovat uuden vuosituhannen suvereenit yksilöt.

Pagelsin ennustetta voisi verrata siihen, kuin viidensadan sukupolven takaisen metsästäjälauman shamaani sanoisi miehilleen, jotka kumartuvat nuotion ympärillä: "Olen vakuuttunut, että ensimmäinen lauma, joka hallitsee uuden kasteluryhmäistämisen tieteen, saa enemmän vapaa-aikaa tarinankerrontaan kuin edes ne järven rannalla kalastavat, jotka nappavat isot kalat." Vaikka hän oli oikeassa monimutkaisuuden merkityksen suhteen, Pagels unohti yhden kaikki perusasian: kun väkivallan logiikka muuttuu, yhteiskunta muuttuu.

## väkivallan logiikka

Jotta ymmärtäisit miten ja miksi, on tarpeen keskittyä useisiin megapolitiikan näkökulmiin, joihin harvemmin kiinnitetään huomiota. Näitä asioita käsitteli historioitsija Frederic C. Lane, jonka väkivallan ja sodan taloudellisen merkityksen tutkimuksia käsitellään muualla tässä teoksessa. Kun Lane kirjoitti tämän vuosisadan puolivälissä, tiedon yhteiskuntaa ei ollut millään tapaa vielä nähtävillä. Näissä olosuhteissa hän saattoi hyvin olettaa, että kilpailu väkivallan käyttämisestä maailmassa olisi saavuttanut lopullisen vaiheensa kansallisvaltion ilmestyessä. Hänen teoksistaan ei käy ilmi, että hän olisi ennakoinut mikroprosessorointia tai uskonut, että olisi teknologisesti mahdollista luoda varoja kybertasolla, fyysisen olemassaolon ulkopuolisessa maailmassa. Lane ei sanonut mitään siitä, mitä seurauksia olisi, jos suuria määriä kauppaa voitaisiin käytännössä tehdä lähes täysin väkivallan vaikutuksen ulkopuolella.

Vaikka Lane ei ennakoinut nykyisin kehittyviä teknologisia vallankumouksia, hänen ymmärryksensä väkivallan monopolisoitumisen eri vaiheista menneisyydessä oli niin selkeää, että sillä on ilmeinen sovellettavuus nousevaan tietoyhteiskunnan vallankumoukseen. Lanen tutkimus väkivaltaisen keskiaikaisen maailman parissa herätti hänen kiinnostuksensa niiden kysymysten suhteen, joita tavanomaiset taloustieteilijät ja historioitsijat ovat usein laiminlyöneet. Hän huomasi, että tapa, jolla väkivalta järjestetään ja sitä kontrolloidaan, vaikuttaa suuresti siihen, mihin niukkoja resursseja käytetään.[^194]: Lane tunnisti myös, että vaikka väkivallan tuotantoa yleensä ei pidetä osana taloudellista tuotosta, väkivallan hallinta on ratkaisevaa taloudelle. Hallituksen ensisijainen tehtävä on tarjota suojaa väkivallalta. Kuten hän ilmaisi,

'Jokainen taloudellinen toimija tarvitsee suojaa ja maksaa siitä, suojaa pääomansa tuhoutumiselta tai aseellisen valtaan joutumiselta sekä työnsä väkivaltaiselta häiriintymiseltä. Erittäin järjestäytyneissä yhteiskunnissa tämän hyödyn, suojan, tuottaminen on yksi erityistä yhdistystä tai yritystä, jota kutsutaan hallitukseksi. Todellakin, yksi hallitusten erottuvimmista ominaisuuksista on niiden pyrkimys luoda laki ja järjestys käyttämällä itse voimaa ja kontrolloimalla eri keinoin muiden käyttämää voimaa.'[^195]

Tämä on asia, joka ilmeisesti on liian perustavaa, jotta se tulisi oppikirjoihin tai osaksi kansalaiskeskustelua, joka oletettavasti määrää politiikan suuntia. Mutta se on myös liian perustavaa, jotta sitä voi sivuuttaa, jos haluaa ymmärtää nousevan tietoyhteiskunnan vallankumouksen kulkua. Elämän ja omaisuuden suojaaminen on todellakin ratkaiseva tarve, joka on hankaloittanut kaikkia koskaan olleita yhteiskuntia. Se, kuinka torjutaan väkivallan hyökkäykset, on historian keskeinen pulma. Sitä ei voi ratkaista helposti, huolimatta siitä, että suojaa voidaan tarjota useammallakin tavalla.

### Iän päättyminen

Kirjoittaessamme information aikakauden megapoliittiset seuraukset alkavat vasta tuntua. Viime vuosikymmenten taloudellinen murros on siirtynyt valmistettujen tavaroiden ensisijaisuudesta informaation ja laskennan etusijaan, konevoimasta mikrokäsittelyyn, tehtaan sijaan työpisteeseen, massatuotannosta pieniin tiimeihin tai jopa yksin työskenteleviin henkilöihin. Yritysten koon pienentyessä työpaikan sabotaasin ja kiristysyritysten mahdollisuudet myös vähenevät. Pienimuotoisemmat toiminnot on huomattavasti vaikeampi järjestää ammattiliittojen toimesta.

Mikroteknologia mahdollistaa sen, että yritykset voivat olla pienempiä ja liikuttelevampia kohteita. Monet harjoittavat palveluita tai valmistavat tuotteita, joilla on merkityksettömän pieni luonnonvarasisältö. Periaatteessa tällaisia liiketoimintoja voitaisiin harjoittaa lähes missä tahansa planeetalla, sillä ne eivät ole sidottuja tiettyyn sijaintiin, kuten kaivokseen tai satamaan. Ajan myötä ne altistuvat myös verotukselle paljon vähemmän, olipa kyse sitten ammattiliitoista tai poliitikoiden asettamista veroista. Vanha kiinalainen kansanviisaus kuuluu: 'Kaikista kolmekymmentäkuudesta tavasta päästä pulasta paras on – lähteä.'[^196]

Information aikakaudella tätä itämaista viisautta sovelletaan vaivattomasti. Jos toiminta muuttuu yhdellä alueella liiallisen vaatimustason vuoksi epämukavaksi, sen on paljon helpompi muuttaa toiselle. Itse asiassa, kuten alla tarkastelemme, information aikakaudella on mahdollista luoda virtuaalisia yrityksiä, joiden kotipaikka missä tahansa lainkäyttöalueella määräytyy täysin spot-markkinoiden mukaan. Yön yli tapahtuva pyrkimys kiristää yritystä – joko hallitusten tai muiden tahojen toimesta – voisi johtaa siihen, että virtuaalisen yrityksen toiminnot ja varat pakenisivat kyseiseltä lainkäyttöalueelta valon nopeudella.

Mikroteknologian kasvava integrointi teollisuusprosesseihin tarkoittaa, että jopa ne yritykset, jotka edelleen harjoittavat valmistettujen tuotteiden liiketoimintaa laajoilla mittakaavoilla, eivät ole enää yhtä alttiita väkivallan tuomaan vipuvaikutukseen kuin ennen. Esimerkkinä tästä on rajatulle Autotyöntekijäliiton pitkäaikaisen lakon romahtaminen Caterpillar-yhtiötä vastaan, joka keskeytettiin vuoden 1995 viimeisinä päivinä lähes kahden vuoden jälkeen. Toisin kuin 1930-luvun kokoonpanolinjat, nykyisessä Caterpillar-tehtaassa työskentelee huomattavasti enemmän osaavia työntekijöitä. Ulkomaisten kilpailijoiden paineessa Caterpillar ulkoisti suuren osan matalapalkkaisesta työstä, sulki tehottomat tuotantolaitokset sekä käytti lähes kaksi miljardia dollaria konetyökalujen tietokoneistamiseen ja kokoonpanorobottien asentamiseen. Jopa lakko itsessään auttoi vauhdittamaan työvoimaa säästäviä tehokkuustoimia. Yritys väittää nyt tarvitsevansa kaksituhatta työntekijää vähemmän kuin lakon alkaessa.[^197]

Megapoliittinen tuotantoprosessi on muuttunut dramaattisemmin kuin useimmat uskovat. Tämä muutos ei vielä näy täysin selvästi, osittain siksi, että aina on viive megapoliittisten olosuhteiden vallankumouksen ja siihen väistämättömästi liittyvien institutionaalisten muutosten välillä. Lisäksi mikroprosessointiteknologian nopea kehitys tarkoittaa, että näköpiirissä ovat jo tuotteet, joiden megapoliittiset seuraukset voidaan ennakoida ennen niiden syntymistä. Ne tulevat luomaan täysin erilaisen maailman.

## Kapitalistien hyväksikäyttö työntekijöiden toimesta

Teknologian laatu lähes koko 1900-lukua teki tehtaiden väkivaltaisesta kaappaamisesta tai istuntastrikistä vaikeasti vastattavan taktiikan omistajille ja johtajille. Kuten historioitsija Robert S. McElvaine totesi, istuntastriki "tekisi työnantajien vaikeaksi hajottaa strikiä tekemättä samoin omalle kalustolleen."[^198] Käytännössä työntekijät pitivät omistajien pääomaa panttihintaan. Alla esiteltävistä syistä johtuen suuremmat teollisuusyritykset osoittautuivat ammattiliitoille helpommiksi tavoitteiksi kuin pienemmät yritykset. Vuonna 1937 General Motors oli ehkä maailman johtava teollisuusyritys. Sen tehtaat kuuluivat historian suurimpiin ja kalleimpiin koneistokokoelmiin, työllistäen tuhansia työntekijöitä. Jokainen tunti, jokainen päivä, jonka GM:n laitokset joutuivat seisomaan, maksoi yritykselle pienen omaisuuden menetyksen. Viikkoja kestänyt työtaistelu, kuten vuoden 1936–37 talvella, johti nopeasti kasvaviin tappioihin.

### Tarjonnan ja kysynnän vastustaminen

Kykenemättä valmistamaan autoja kolmannen tehtaan kaappauksen jälkeen, GM antautui pian liiton vaatimuksille. Kyse ei ollut lainkaan työvoiman kysynnän ja tarjonnan mukaisesta taloudellisesta päätöksestä – ei todellakaan. Kun General Motors myönsi liiton vaatimukset, Yhdysvalloissa oli työttömänä yhdeksän miljoonaa henkilöä, mikä vastasi 14 prosenttia työvoimasta. Suurin osa heistä olisi mielellään saanut työpaikan GM:ltä. Heillä oli taidot täyttää kokoonpanolinjan tehtävät, vaikka tämä ei usein käy ilmi nykyisistä kuvauksista. Hienovarainen etiketti peitti suoraviivaisen analyysin työvoimasuhteista teollisuuskauden aikana. Yksi sen oletuksista oli, että tehdastyöpaikat erityisesti 1900-luvun puolivälissä olisivat ammattitaitoisia töitä. Tämä ei pidä paikkaansa. Suurin osa tehdastyöpaikoista olisi voinut hoitaa melkein kuka tahansa, joka pystyi saapumaan ajoissa. Työpaikoissa vaadittiin vain vähän tai ei lainkaan koulutusta – ei edes lukutaitoa tai kirjoitustaitoa. Vielä 1980-luvulla suuri osa General Motorsin työntekijöistä oli joko lukutaidottomia, laskutaitottomia tai molempia. Kuten 1990-luvulle saakka tyypilliselle kokoonpanolinjan työntekijälle annettiin vain yhden päivän perehdytys ennen työtehtäviin siirtymistä, on selvää, että yhden päivän aikana opittavaa ei voi kutsua ammattitaidoksi.

Mutta vuonna 1937, kun sekä epäkuuluisat että pätevät työntekijät seisoivat kerjäämässä töitä, GM:n tehdastyöntekijät onnistuivat pakottamaan työnantajansa antamaan palkankorotuksen. Heidän menestyksensä johtui paljon enemmän väkivallan dynamiikasta kuin työvoiman kysynnän ja tarjonnan suhteesta. Maaliskuussa 1937, GM-konfrontaation ratkaisua seuraavana kuukautena, Yhdysvalloissa järjestettiin vielä 17 istumalakkoa. Useimmat niistä onnistuivat. Samankaltaisia tapahtumia esiintyi kaikissa teollistuneissa maissa. Työntekijät ottivat tehtaat yksinkertaisesti haltuunsa ja lunastivat ne takaisin omistajilleen. Se oli erittäin yksinkertainen taktiikka, ja useimmissa tapauksissa se oli sekä kannattavaa että hauskaa osallistujille. Eräs istumalakkoon osallistunut kirjoitti: 'Minulla on mahtava aika, jotain uutta, jotain erilaista, paljon purtavaa ja musiikkia.'[^199]

Vuoden 1936–37 GM:n istumalakko ja muut sen ajan väkisin toteutetut tehdasvallaukset olivat esimerkkejä ilmiöstä, jonka kuvaamme teoksessa *Blood in the Streets* nimellä 'pääoman hyödyntäminen työntekijöiden toimesta.' Tämä ei ollut se näkökulma, jonka Pete Seeger asetti musiikkiinsa surumielisissä kappaleissaan. Mutta ellet aio ryhtyä kansanlaulajaksi työväenmaassa, niin tärkeintä ei ole niinkään suosittu tulkinta, vaan sen perimmäinen todellisuus. Missä tahansa historiaa tarkastelet, sieltä löytyy yleensä kerros järkeistelyä ja teeskentelyä, joka kätkee alleen minkä tahansa systemaattisen kiristyksen todelliset megapoliittiset perustukset. Jos otat nämä järkeistelmät sellaisinaan, et todennäköisesti ymmärrä, mitä todella tapahtuu.

## Kiristyksen logiikan selvittäminen

Jotta pystyt tunnistamaan nykyisen siirtymän tietoyhteiskuntaan liittyvät megapoliittiset vaikutukset, sinun täytyy karsia pois turha puhe ja keskittyä yhteiskunnan todelliseen väkivallan logiikkaan. Se on kuin paljastaisi ylikypsän sipulin kerrokset. Se saattaa saada sinut itkellemään, mutta älä katso pois. Tutkimme ensin työpaikalla tapahtuvaa kiristyksen logiikkaa, minkä jälkeen laajennamme analyysiä koskemaan laajempia kysymyksiä, jotka liittyvät varojen luomiseen ja suojaan sekä modernin hallituksen luonteeseen. Enemmän kuin useimmat uskovat, hallitusten menestys, kuten myös ammattiliittojen, oli suoraan yhteydessä siihen vipuvoimaan, joka oli saatavilla kiristykseen. Tuo vipuvoima oli paljon pienempi 1800-luvulla kuin 1900-luvulla. Seuraavalla vuosituhannella se laskee melkein katoamisrajaan.

Koko hallituksen logiikka ja vallan luonne ovat muuttuneet mikroprosessoinnin myötä. Tähän saattaa aluksi vaikuttaa liioitellulta, mutta katso tarkkaan. 1900-luvulla hallitusten menestys on kulkenut käsi kädessä työväenliittojen menestyksen kanssa. Ennen tätä vuosisataa suurin osa hallituksista pakkosi paljon vähemmän resursseja kuin nykyiset radikaalit hyvinvointivaltiot, joihin olemme tottuneet. Samoin liitot olivat ennen tätä vuosisataa pieniä tai merkityksettömiä tekijöitä talouselämässä. Työntekijöiden kyky pakottaa työnantajansa maksamaan yli markkinahinnan palkat riippui samoista megapoliittisista olosuhteista, jotka mahdollistivat hallitusten periä 40 prosenttia tai enemmän talouden tuotannosta veroina.

Työpaikan kiristyksiä ennen 1900-lukua

Ammattiyhdistysten kiristyksen nousu ja tuho kapitalistien keskuudessa selittyvät helposti tuotantoprosessin muuttuvien megapoliittisten olosuhteiden kautta. Vuonna 1776, kun Adam Smith julkaisi *The Wealth of Nations*, työpaikalla tapahtuvaan kiristykseen liittyvät olosuhteet olivat riittävän epäsuotuisat, että työntekijöiden tekemät 'yhdistymiset' "nostaa työnsä hintaa" olivat harvoin toteuttamiskelpoisia. Suurin osa valmistusyrityksistä oli pieniä ja perheomisteisia. Suurempaa teollista toimintaa oli vasta alkamassa, mikä ei estänyt väkivaltaan turvautumismahdollisuuksia, mutta antoi niille vain vähän vipuvoimaa. Itse asiassa Smithin aikana ja vielä 1800-luvulle saakka yhdistyksiä pidettiin yleisesti laittomina yhdistymisinä Iso-Britanniassa, Yhdysvalloissa ja muissa common law -maissa. Adam Smith kuvaili näitä lakkoyrityksiä seuraavin sanat: 'Heidän tavalliset tekosyynsä ovat joskus korkeammat ruokatavaroiden hinnat; toisinaan taas se suuri voitto, jonka heidän isäntänsä saavat heidän työstään… He turvautuvat aina kovaäänisimpään meluun, ja joskus kaikkein järkyttävimpään väkivaltaan ja ilkivaltaan.'[^200] Huolimatta tästä työntekijät "hyötyvät hyvin harvoin noista myrskyisistä yhdistymisistä" – paitsi "johtajien rankaisemisessa tai tuhoamisessa."[^201]

1800-luvulla teollisuuden mittakaavaedut ja yritysten koko kasvoivat, mutta suurin osa yksilöistä jatkoi edelleen itsenäistä työskentelyä maanviljelijöinä tai pienyrittäjinä, ja Adam Smithin kuvaamia yhdistysmielisiä organisoitumisyrityksiä nähtiin "yleisesti päättyvän tyhjyyteen."[^202] Ammattiyhdistysten laillinen ja poliittinen asema muuttui vasta, kun yritystoiminnan mittakaava kasvoi. Ensimmäiset yhdistykset, jotka onnistuivat organisoitumaan, olivat korkeasti koulutettujen käsityöläisten yhdistyksiä, jotka yleensä järjestäytyivät ilman laajamittaista väkivaltaa. He tyytyivät palkankorotuksiin, jotka vastasivat heidän korvaamiseen liittyviä marginaalikustannuksia. Alankoulutettujen työntekijöiden yhdistykset taas olivat toisenlainen tarina. Ne hyödynsivät suurempiin yrityksiin siirtymistä kohdistamalla organisoitumispyrkimyksiinsä juuri sellaiset teollisuudenalat, jotka olivat erityisen alttiita kiristykselle – joko siksi, että niiden toiminta oli laajassa mittakaavassa tai koska toimintojen luonne altisti omistajansa fyysiselle sabotoinnille. Tätä kuvioa vahvistivat havainnot Newcastlesta aina Argentiinaan asti.[^203]

Yksi varhainen esimerkki väkivaltaisista työliikkeistä Yhdysvalloissa oli hyökkäys Chesapeake and Ohio -kanavaan vuonna 1834. Toisin kuin useimmat varhaisen 1800-luvun yritykset, C&O-kanava ei ollut rajattu eikä helposti suojattu operaatio. Alkuperäisen suunnitelman mukaan sen olisi pitänyt ulottua 342 mailia, ja siinä olisi ollut 3 000 jalan korkeusero alemmasta Potomac-joesta ylempään Ohio-joeseen.[^204] Tällaisen kaivannon kaivaminen oli valtava työ, joka ei koskaan juuri valmistunut. Kuitenkin suuri määrä työntekijöitä oli palkattu tekemään työtä, ja osa heistä huomasi pian, että kanavaa oli helppo heikentää. Ilman säännöllistä kunnossapitoa kanavan lukot ja kanavat saattoivat tuhoutua yksinkertaisesti huolimattoman käytön, rankkasateiden aiheuttamien tulvien tai vetämättömien veneiden kolhujen vuoksi. Lakkojen aikana oli vaivalloista estää, että lakon aikana vastustajat asettuisivat tukemaan vesiväylää uponneilla veneillä tai muulla romun kaltaisella aineksella. Varhaisina vuonna 1834 C&O-kanavalla irlantalaisten työntekijöiden jengien välinen mellakka johti yritykseen hyödyntää tilanne ja kaapata kanava, mutta yritys epäonnistui ja kuolleita oli viisi, kun presidentti Andrew Jackson lähetti liittovaltion joukkoja Ft. McHenrystä hajottamaan työntekijöitä.

Kaivokset ja rautatiet tarjosivat myös varhaisia kohteita yhdistysten aktivismille Amerikassa. Kuten C&O-kanava, myös ne olivat erittäin alttiita sabotoinnille. Esimerkiksi kaivokset saattoivat tulvota tai niiden sisäänkäyntiä saattoi tukita. Pelkästään maanalaisista kaivoksista malmin kuljetuksessa käytettyjen aasin tappaminen loi omistajille hankalasijan. Samalla tavalla rautatievaunujen pitkät reitit suuttuivat lähes vartioitaviksi. Ammattiyhdistysten väkivaltaiset toimijat hyökkäsivät suhteellisen helposti kaivoksiin ja rautateihin, tehden niillä huomattavaa taloudellista vahinkoa. Tällaiset hyökkäykset yleistyivät, kun pyrittiin organisoimaan tehokkaita yhdistyksiä. Näillä pyrkimyksillä oli yleensä suurin intensiteettinsä silloin, kun deflaation myötä reaalipalkat nousivat. Omistajien yrittäessä säätää nimellispalkkojaan, tämä usein laukaisi protesteja, jotka johtuivat väkivallasta. Tällaisia tapauksia oli laajasti vuoden 1873 paniikin jälkeisessä laman aikana.[^203]

Joulukuussa 1874 itäisen Pennsylvanian antrasiittikivihiilialueilla syttyi avoin sota. Amattiliitot järjestivät väkivaltaisen lakkojoukon salaseuran, Ancient Order of Hiberniansin, nimissä. Tätä joukkoa kutsuttiin myös «Molly Maguires» -nimellä irlantilaisen vallankumouksellisen mukaan, ja ryhmä oli tunnettu hiilialueiden terrorisoimisesta sekä siitä, että se esti halukkaita kaivostyöläisiä työskentelemästä. Sabotaasi, omaisuuden tuhoaminen, suora murha ja salamurha syytettiin kaikilta sen jäseniltä.[^205]

Myös rautatieliikenteen työntekijöiden keskuudessa esiintyi toistuvaa väkivaltaa. Esimerkiksi heinäkuussa 1877 puhalsi vakavia mellakoita, joiden tavoitteena oli tuhota sekä Pennsylvania Railroadsin että Baltimore & Ohio Railroadsin omaisuus. Työntekijät valtasivat kytkimet, repivät raiteet, sulkivat junakaluston alueet, lamauttivat veturit, sabotoivat junia, ryöstivät niitä ja vielä pahempaa. Pittsburghissa Pennsylvania Railroadsin pyörärakennukset sytytettiin tuleen, ja sisällä oli satoja ihmisiä. Kymmeniä kuoli, kaksi tuhatta junakalustoa palettiin ja ryöstiin, konepaja tuhottiin, samoin kuin jyvävarastokori ja 125 veturia. Liittovaltion joukot puuttuivat tilan palauttamiseksi.[^206]

Vaikka näitä varhaisia lakkoja tulkittiin sympaattisesti sosialistien ja liittoaktivistien toimesta, ne eivät inspiroineet juurikaan yleisön tukea. Vaikka kaivostoiminta ja rautatieliikenne ovat itsestään haavoittuvia aloja, laajemmat makrotaloudelliset olosuhteet eivät vielä suotuneet siihen, että työntekijät voisivat systemaattisesti kiristää kapitalisteja. Yritysten mittakaava oli liian pieni mahdollistamaan järjestelmällistä kiristystä. Vaikka haavoittuvia toimialoja oli, ne työllistivät vain pienen osan väestöstä, jolloin painostuksen tuomat edut eivät jakautuneet laajalti. Ilman tällaista tukea lakkoja ei ollut kestäviä, sillä omistajat saattoivat luottaa hallituksen suojeluun. Vaikka liitot joskus yrittivät uhkailun keinoin estää paikallisia viranomaisia toimeenpanemasta määräyksiä, nämäkin pyrkimykset olivat harvoin onnistuneita. Jopa kaikkein väkivaltaisimmat lakot saatiin yleensä sotilaallisilla keinoilla tukahdutettua muutaman päivän tai viikon kuluessa.

### Kiristys tehtiin helpoksi

Information Agea varten on opittava, että liittojen pyrkimykset saavuttaa palkat markkinatasoa korkeammalla olivat harvoin onnistuneita, kun yritysten koko oli pieni. Ei edes ne liiketoimintalinjat, jotka olivat selvästi alttiita sabotaasille – kuten kanavat, rautatiet, raitiovaunut ja kaivokset – pystytty hallitsemaan helposti. Tämä ei johtunut siitä, että liitot epäröivät käyttää väkivaltaa; päinvastoin, väkivaltaa käytettiin runsaasti, joskus jopa korkeaprofiilisia henkilöitä vastaan. Esimerkiksi tapauksessa, jota amerikkalainen työliike juhlitsi «kaivostyöläisten kostona», Idaho’n kuvernööri Frank Steunenberg, joka oli vastustanut kaivostyöläisten yritystä blokkata Coeur d’Alenen alueen omaisuutta, salamurhattiin bomballa, jonka liitto palkkasi sopimusmurhaajan heiteltäväksi.[^207] Mutta jopa murha ja murhapuheet eivät yleensä riittäneet saavuttamaan liiton tunnustusta ennen kuin 1900-luvun alussa syntyi suuria tehtaita ja massatuotantoyrityksiä.

Jotta voidaan ymmärtää, miksi ammattiliittojen olosuhteet muuttuivat niin radikaalisti 1900-luvulla, on tarkasteltava tuotantoteknologian ominaispiirteitä. Jokin selvästi muuttui, kun varhaisen 1900-luvun sinikaulusyöntekijöiden tehtaissa työskentely räjähti nopeasti. Tämä muutos teki talouden eturivin yrityksistä erityisen alttiita kiristykselle. Itse asiassa teollisuusteknologian fyysiset ominaisuudet lähes houkuttelivat työntekijöitä käyttämään pakottamista kapitalistien kiristämiseksi. Pohdi seuraavia seikkoja:

1. *Suurimmassa osassa teollisuustuotteita oli korkea luonnonvarojen sisältö.* Tämä sitoi tuotannon tiettyihin paikkoihin, lähes samalla tavalla kuin kaivoksia on sijoitettava malmiesiintymien kohdalle. Tehtaat, jotka sijaitsivat lähellä kuljetuskeskuksia ja joilla oli vaivaton pääsy varaosatoimittajiin sekä raaka-aineisiin, nauttivat merkittävistä toimintakustannusetuista. Tämä helpotti hallitsevien tahojen, kuten hallitusten ja liittojen, mahdollisuuksia kerätä osan näistä eduista itselleen.

2. *Kasvavat mittakaavaedut johtivat erittäin suuriin yrityksiin.* Varhaisen 1800-luvun tehtaat olivat suhteellisen pieniä. Mutta kun tuotannon mittakaava kasvoi kokonaistuotantolinjojen myötä 1900-luvulla, tuotantoprosessiin osallistuvien laitosten koko ja kustannukset nousivat nopeasti. Tämä teki niistä helpompia kohteita monella tavalla. Esimerkiksi merkittävät mittakaavaedut kulkivat käsi kädessä pitkien tuotesyklien kanssa, jotka loivat vakaampia markkinoita. Tämä puolestaan houkuttelee yritysten petollista kohdistamista, koska se viittaa siihen, että vähemmällä ponnistuksella voidaan saavuttaa pitkäaikaisia etuja.

3. *Kilpailevien yritysten määrä johtavilla toimialoilla laski jyrkästi.* Teollisuusaikana ei ollut harvinaista, että vain kourallinen yrityksiä kilpailee miljardeja dollareita arvostavilla markkinoilla. Tämä edesauttoi sitä, että näistä yrityksistä tuli liittojen kiristyksen kohteita – on paljon helpompi hyökätä viittä yritystä vastaan kuin viittä tuhatta. Itse yritysten keskittyminen oli itsessään tekijä, joka helpotti kiristystä, sillä yritykset, joita pakotettiin maksamaan monopoli palkkoja, eivät todennäköisesti kohtanneet kovaa kilpailua niiltä, joita ei kuormitettu yli markkinoiden työvoimakustannuksilla. Siten liitot pystyivät keräämään huomattavan osan kyseisten yritysten voitoista ilman, että ne joutuivat välittömästi konkurssin uhkaan – ilmiselvästi, jos työnantajat olisivat aina menettäneet konkurssin, kun heidät pakotettiin maksamaan yli markkinoiden palkkoja, työntekijöiden eduksi kiristyksestä olisi ollut vain hyvin vähän.

4. *Vapautetun investoinnin pääomavaatimukset nousivat yritysten mittakaavan mukana.* Tämä paitsi kasvatti pääoman haavoittuvuutta ja suurensi tehtaiden sulkemisen kustannuksia, myös teki yhä epätodennäköisemmäksi, että modernin tehtaan omistusoikeus pysyisi yhden yksilön tai perheen hallussa – ellei perimyksen kautta sellaisen, joka oli käynnistänyt liiketoiminnan pienemmässä mittakaavassa. Jotta valtavia työkalujen ja isojen tehtaiden käyttöön liittyviä kustannuksia voitaisiin kattaa, satojen tai tuhansien ihmisten varallisuus oli kootava yltiömäisesti yhtenäiseksi pääomamarkkinoilla. Tämä teki hajautuneista ja lähes nimettömistä omistajista entistä vaikeammin omaisuuden puolustajia – heillä ei ollut muuta vaihtoehtoa kuin turvautua ammattimaisiin johtajiin, jotka harvoin omistivat paljon yrityksen osakkeita. Johtajien käyttö alaisina heikensi yritysten kykyä vastustaa kiristystä, sillä heillä ei ollut vahvoja kannustimia vaarantaa henkiään tai ruumistaan yrityksen omaisuuden suojelemiseksi. Heidän ponnistelunsa eivät vastanneet sitä militanssia, joka on tyypillistä pienimuotoisissa liiketoiminnoissa, kun niiden omaisuutta uhataan.

5. *Suurempi yrityskoko merkitsi sitä, että suurempi osa koko työvoimasta työllistettiin harvemmissa yrityksissä kuin koskaan aiemmin.* Joissain tapauksissa kymmeniä tuhansia työntekijöitä työskenteli yhdessä yrityksessä. Sotilaallisesta näkökulmasta omistajia ja johtajia ohittivat määrällisesti alaiset – suhteet, kuten 30:1 tai vielä huonommat, olivat yleisiä. Tämä epäedullisuus kasvoi yritysten koon myötä, sillä valtava määrä työntekijöitä yhdessä paikassa pystyi anonyymisti käyttämään väkivaltaa. Tällaisissa tilanteissa työntekijöillä ei todennäköisesti ollut merkittäviä henkilökohtaisia yhteyksiä tehtaan omistajiin, mikä puolestaan madalsi omistajien omaisuusoikeuksien merkitystä heidän mielestään.

6. *Massamuotoinen työllisyys harvemmissa yrityksissä oli laaja yhteiskunnallinen ilmiö.* Tämä vahvisti entisestään niitä megapoliittisia etuja, joita liitoilla oli verrattuna 1800-luvun Amerikan tilanteeseen, jolloin suurin osa ihmisistä työskenteli itsenäisesti tai pienissä yrityksissä. Vuonna 1940 amerikkalaisesta työvoimasta 6 prosenttia oli sinikaulusyöntekijöitä.[^208] Tämän seurauksena tuki pönkittäville kiristyshankkeille palkkojen nostamiseksi levisi laajalti niiden keskuudessa, jotka kuvittelivat hyötyvänsä siitä. Tämä käy ilmi esimerkiksi vuonna 1938–39 tehdystä tutkimuksesta, jossa 1 700 Akronin, Ohion, asukkaan mielipiteet yritysten omaisuudesta paljastivat, että 68 prosentilla CIO:n kumi-työntekijöistä oli hyvin vähän tai ei lainkaan sympatiaa yritysten omaisuutta kohtaan, 'kun taas vain yhdellä prosentilla oli vahva tuki yritysten omaisuusoikeuksille.'[^209] Toisaalta yksikään liikemies, edes pienyrittäjä, ei sijoittunut samaan kategoriaan "vahvasta vastustuksesta yritysten omaisuutta kohtaan", vaan 94 prosenttia sai arvioita, jotka osoittivat erittäin vahvaa tukea omaisuusoikeuksille.[^210]

7. *Kokonaistuotantolinjateknologia oli luontaisesti jaksollista.* Se, että koko tuotantoprosessi perustuikin osien liikkumiseen ja kokoamiseen kiinteässä järjestyksessä, loi lisäalttiuksia häiriöille. Käytännössä kokonaistuotantolinja toimi kuin sisäpuolinen rautatie – jos jommankumman raiteen osan voisi tukita tai jos yksittäisen osan saatavuus katkeaisi, koko prosessi pysähtyisi.

8. *Kokonaistuotantolinjateknologia standardisoi työn.* Tämä vähensi tuotosten vaihtelua erilaisten taitotasoisten henkilöiden välillä, jotka työskentelivät samoilla työkaluilla. Todellisuudessa tehtaan suunnittelun kriittisenä tavoitteena oli luoda järjestelmä, jossa niin nerokas kuin hölmökin peräkkäisillä vuoroilla tuottaisivat saman tuotteen. Mitä voisi kutsua "tyhmiksi" koneiksi, suunniteltiin kykenemään tuottamaan vain yhtä tuotetyyppiä. Tämä teki jopa Cadillacin ostajan osalta tarpeettomaksi kysyä sitä, ketkä tuotantolinjalla työskentelevät – sillä kaikki tuotteet oli tarkoitus olla samanlaisia, riippumatta työntekijöiden eri taidoista ja älykkyydestä.

Se, että taitamattomat työntekijät pystyivät kokonaistuotantolinjalla tuottamaan saman tuotteen kuin kykenevämmät henkilöt, edisti tasa-arvoista ajattelutapaa, sillä se vaikutti siltä, että kaikkien taloudelliset panokset olivat yhtäläisiä. Yrittäjämäiset taidot ja henkinen ponnistelu näyttivät olevan vähemmän merkityksellisiä. Modernin tuotannon taika näyttikin piilevän itse koneissa; vaikka niitä ei todellakaan olisi voitu suunnitella jokaisen toimesta, ne huomasivat silti olevan lähes kaikkien saavutettavissa henkisesti. Tämä lisäsi uskottavuutta fiktiolle, jonka mukaan taitamatonta työvoimaa "hyödynnettiin" tehtaiden omistajien toimesta, joita voitaisiin jättää ulkopuolelle ilman, että mitään menetettäisiin, paitsi he itse. "Me opimme, että voimme ottaa tehtaan haltuun", totesi eräs General Motorsin lakkoaja. "Me jo tiesimme, kuinka niitä pyöritetään. Jos General Motors ei ole varovainen, yhdistämme pian kaksi ja kaksi."[^211]

Nämä teollisuusteknologian piirteet johtivat yhtäaikaisesti työväenliittojen syntyyn, joiden tehtävänä oli hyödyntää kiristysmahdollisuuksia, sekä suurempien hallitusten kasvuun, jotka keräsivät suuria veroja suurteollisuuslaitoksista. Tätä ilmiötä ei tapahtunut vain satunnaisesti, vaan kaikkialla, missä suurteollisuus juurtui. Ajan myötä liitot nousivat koristeellisesti käyttämään väkivaltaa saadakseen palkat nousuun markkinatasoa yli; ne pystyivät tähän, koska teollisuustalot olivat kalliita, näkyviä, liikkumattomia ja kustannuksiltaan erittäin suuria – niitä ei voinut juuri piilottaa, eikä niitä voinut siirtää, ja jokainen käyttökelvottomana vietetty hetki tarkoitti sitä, että niiden valtavia kustannuksia ei voinut jakaa.

Kaiken kaikkiaan nämä tekijät tekivät teollisuustalouksista helppoja kohteita kiristykseen – se on vieläkin ilmeisempää työväenliittojen historiassa kuin 1900-luvun vallitseva ideologia saattaisi antaa ymmärtää. Kunnianimoitu taloustieteilijä Henry Simons kuvailee asiaa vuodelta 1944 seuraavasti:

---

[^208]: Lähde: [Footnote content remains unchanged]
[^209]: Lähde: [Footnote content remains unchanged]
[^210]: Lähde: [Footnote content remains unchanged]
[^211]: Lähde: [Footnote content remains unchanged]

Työjärjestäminen ilman suuria pakottamisen ja pelottelun voimia on epärealistinen abstraktio. Liitot omaavat nyt tällaiset voimat; ne ovat aina omaanneet ja tulevat aina omaamaan, kunhan ne pysyvät nykyisessä muodossaan. Kun voima on pieni tai sen hallinta on epävarmaa, se on käytettävä avoimesti ja laajasti; kun se on suuri ja haastamaton, se muuttuu hallituksen voimaksi, jota pidetään itsevarmasti, arvostetaan kunnioittavasti ja jota harvoin näytetään räikeästi.[^212]

Simonsin analyysi on ollut tarkka, mutta hän oli kuitenkin väärässä ratkaisevassa asiassa.

Hän oletti, että liitot "aina tulevat omaamaan" sitä, mitä hän kuvaili "suurina pakottamisen ja pelottelun voimina." Todellisuudessa liitot ovat häipymässä – ei pelkästään Yhdysvalloissa ja Isossa-Britanniassa, vaan myös muissa kypsissä teollisissa yhteiskunnissa. Syynä liittojen häipymiseen – mitä Simons jäi huomaamatta, ja mitä jopa monet liittojen järjestäjät eivät ymmärrä – on se, että siirtyminen informaatioyhteiskuntaan on muuttanut megapoliittisia olosuhteita ratkaisevissa suhteissa, mikä terävästi lisää omaisuuden turvaa. Mikroteknologia on jo alkanut murtaa sen ulkomusteen, joka tukee hyvinvointivaltiota, koska jopa kaupallisella sektorilla se luo hyvin erilaiset kannustimet kuin teollisuusaikana.

1. *Informaatioteknologian luonnonvarojen sisältö on merkityksetöntä.* Se tarjoaa harvoin, ellei lainkaan, sisäisiä sijainnin etuja. Suurin osa informaatioteknologiasta on erittäin kannettavaa. Koska se voi toimia paikasta riippumatta, informaatioteknologia lisää ideoiden, ihmisten sekä pääoman liikkuvuutta. General Motors ei voinut pakata kolmea kokoonpanolinjaansa Flinton kaupungissa Michiganissa ja lähteä lentämään pois, mutta ohjelmistoyritys voi. Omistajat voivat ladata algoritmejaan kannettaviin tietokoneisiin ja nousta seuraavalle lennolle. Tällaisilla yrityksillä on lisäksi lisäkannustin paeta korkeita veroja tai liittojen vaatimuksia monopoli‐palkoista. Pienemmillä yrityksillä on taipumus olla enemmän kilpailijoita. Jos sinulla on kymmeniä tai jopa satoja kilpailijoita houkuttelemassa asiakkaitasi, et voi olla varaa maksaa poliitikoille tai työntekijöillesi paljon enemmän kuin he todellisuudessa ovat. Jos yrittäisit tehdä näin yksin, kustannuksesi olisivat korkeammat kuin kilpailijoilla, ja menisit konkurssiin. Merkittävien käyttöetuuksien puuttuminen tietyssä paikassa tarkoittaa, että pakottavat organisaatiot – kuten hallitukset ja liitot – saavat väistämättä vähemmän vipuvoimaa hyödyntää saadakseen osan näistä eduista itselleen.

2. *Informaatioteknologia vähentää yritysten mittakaavaa.* Tämä johtaa pienempään yrityskokoon, mikä tarkoittaa suurempaa määrää kilpailijoita. Kasvava kilpailu vähentää mahdollisuuksia kiristää palkkoja tai nostaa veroja, koska fyysisesti on hallittava suurempi määrä kohteita, jotta edut saataisiin ylivoimaisiksi. Informaatioteknologian mahdollistama yritysten keskimääräisen koon jyrkkä lasku on jo vähentänyt alaisena työskentelevien määrää. Esimerkiksi Yhdysvalloissa laajasti raportoitu arvio vuodelta 1996 oli, että jopa 30 miljoonaa henkilöä työskenteli yksin omissa yrityksissään. Näiden 30 miljoonan ei ole kovin todennäköistä lakottaa itseään vastaan. Vähän vähemmän uskottava on, että lisämiljoonat, jotka työskentelevät pienissä yrityksissä, joissa on vain muutama työntekijä, yrittäisivät kiristää työnantajiaan maksamaan yli markkinahinnan. Informaatioaikana työntekijöiltä, jotka pyrkivät palkkojensa nostamiseen kiristyksen kautta, puuttuu teollinen etu ylivoimaisissa määrissä, mikä teki heistä aiemmin voimakkaan tekijän tehtaissa. Mitä vähemmän henkilöä yrityksessä on, sitä vähemmän on mahdollisuuksia anonyymiin väkivaltaan. Tästä syystä kymmenen tuhatta työntekijää jaettuna viihsan yrityksen kesken muodostaisi pienemmän uhan yrityksen omaisuudelle kuin kymmenen tuhatta työntekijää yhdessä yrityksessä, vaikka työntekijöiden ja omistajien suhde pysyisi samana.



3. *Yritysten koon supistuminen tarkoittaa myös sitä, että yrityksen työntekijöiden pyrkimykset saada yli markkinatasojen maksetut palkat eivät todennäköisesti kerää laajaa yhteiskunnallista tukea, kuten ne tekivät teollisuuskaudella*. Amattiliitot, jotka pyrkivät kiristämään työnantajiaan, joutuvat paljon todennäköisemmin tilanteeseen, joka muistuttaa 1800-luvun kanavan työntekijöiden, rautatieyhtiöiden työntekijöiden ja kaivosmiesten tilannetta. Jopa siellä, missä muutamat suurteolliset yritykset säilyvät teollisuuskauden jäänteinä, ne toimivat kontekstissa, jossa työllisyys on laajasti hajautunutta pienissä yrityksissä. Pienten yritysten ja pienviljelijöiden yltäkylläisyys viittaa suurempaan yhteiskunnalliseen tukeen omaisuusoikeuksia kohtaan, vaikka halu tulon uudelleenjakoon säilyisikin muuttumattomana.

4. *Tietotekniikka laskee pääomakustannuksia, mikä lisäksi yleensä lisää kilpailua helpottamalla yrittäjyyttä ja antamalla yhä useamman ihmisen työskennellä itsenäisesti*. Alemmat pääomavaatimukset paitsi vähentävät sisäänpääsyn esteitä, myös pienentävät "uloskäynnin esteitä". Toisin sanoen ne viittaavat siihen, että yrityksillä on todennäköisesti vähemmän varoja suhteessa tuloihinsa ja siksi kyky kestää tappioita heikkenee. Ne eivät ainoastaan pysty turvautumaan pankkilainoihin yhtä paljon, vaan tietoyhteiskunnan yrityksillä on myös vähemmän fyysisiä varoja kerättäväksi.

5. *Tietotekniikka lyhentää tuotesykliä*. Tämä johtaa tuotteiden nopeampaan vanhentumiseen. Myös tämä efekti tekee mahdollisista yli markkinatasojen saavutetuista palkankorotuksista lyhytaikaisia hyötyjä. Erittäin kilpailluilla markkinoilla liian korkeat palkat voivat johtaa suoraan työpaikkojen nopeaan vähenemiseen ja jopa yrityksen konkurssiin. Pyrkimys ansaita tilapäisesti korkeampia palkkoja vaarantamatta työpaikkaa on kuin polttaisi huonekalujasi saadaksesi taloon vain muutaman asteen lisää lämpöä.

6. *Tietotekniikka ei etene peräkkäin, vaan samanaikaisesti ja hajautetusti*. Toisin kuin kokoonpanolinja, tietotekniikka pystyy hoitamaan useita prosesseja yhtäaikaisesti. Se hajauttaa toimintoja verkostoihin, mahdollistaen redundanssin ja korvaavuuden työasemien välillä, joita voi olla tuhansia tai jopa miljoonia ympäri maapallon. Yhä useammissa toiminnoissa on mahdollista, että ihmiset tekevät yhteistyötä ilman, että he koskaan joutuvat olemaan fyysisesti samassa tilassa. Virtuaalitodellisuuden ja videoneuvottelujen kehittyessä yleistyvän myös toiminnallisten järjestelmien hajauttaminen ja etätyöskentely. Tämä on tietoyhteiskunnan vastine keskiaikaisten kiltaorganisaatioiden vallan murtamiselle, ns. "sammuttamiselle". Se, että yhä harvempi työskentelee yhdessä savuisissa tehtaissa, ei ainoastaan riistä entisiltä työntekijöiltä sitä etua, jota he aiemmin nauttivat pääoman "kaatamisessa", vaan tekee yhä vaikeammaksi erottaa työpaikalla hyväksytyn kiristyksen ja rikollisena pidetyn kiristysyrityksen toisiaan.

Aiemmin vain ne henkilöt, jotka ovat työskennelleet yhdessä ja olleet saman yrityksen palveluksessa yhteisessä ympäristössä, ovat saaneet käyttää väkivaltaa tulojen nostamiseksi. Mutta jos "työpaikkaa" ei enää ole keskuspaikkana ja suurin osa toiminnoista on hajautettu alihankkijoiden ja etätyöntekijöiden kesken, on käytännössä hyvin vähän eroa siihen, millä tavalla yrityksen asiakkailta tai "työnantajilta" pyritään kiristämään rahaa.

Esimerkiksi: onko etätyöntekijä, joka uhkaa tartuttaa yrityksen tietokoneet viruksella saadakseen ylimääräistä rahaa, lakkoileva työntekijä vai internet-kiristystekijä?

Either option will ultimately prove to be a distinction without difference. Kohdennettujen yritysten reagointi on kuitenkin todennäköisesti lähes samanlaista joka tapauksessa. Teknologiset ratkaisut tietosabotaasille, kuten parannettu salaus ja verkkoturvallisuus, jotka lieventäisivät ulkopuolisen hakkeroijan aiheuttamaa uhkaa, kumoaisivat samalla tyytymättömän työntekijän tai alihankkijan mahdollisuuden aiheuttaa vahinkoa niille tahoille, joiden kanssa hän säännöllisesti tai satunnaisesti toimii. Tietenkään saatettaisiin ehdottaa, että työntekijä tai etätyöntekijä voisi aina ilmoittautua toimistolle ja osallistua siellä perinteisempään lakkoon. Mutta edes tämä ei välttämättä ole niin yksinkertaista kuin tietoyhteiskunnan aikakaudella ensimmäisenä näyttäisi. Tietotekniikan kyky ylittää paikallisuus ja hajauttaa taloudellisia toimintoja tarkoittaa, että työntekijöiden ja työnantajien ei tarvitse edes enää olla samassa lainkäyttöalueessa. Tässä ei puhdasuutena käsitellä eroa esimerkiksi Mayfairn ja Peckhamin kaupunginosissa, vaan pikemminkin työnantajien Bermudoilla ja etätyöntekijöiden New Delhissä ilmenevää eroavaisuutta.

Lisäksi, jos intialaiset innostuisivat kertomuksista General Motorsin suurista lakkoista vuosina 1936–37 ja päättäisivät matkustaa Bermudoille lakkoon osallistumista varten, he saattaisivat saapuessaan huomata, ettei missään ole olemassa fyysistä toimistoa. Suuri mainosyritys *Chiat/Day* on jo ryhtynyt purkamaan pääkonttoriaan. Sen työntekijät – tai alihankkijat – pitävät yhteyttä toisiinsa puheluiden jatkokäsittelyn ja Internetin avulla. Kun on tarpeen kokoontua osaamistiimejä koordinoimaan tiliprojekteja, he vuokraavat hotellin kokoushuoneita. Projektin jälkeen he poistuvat. Se, että mikrosuorituskyky vapauttaa tuotantoprosessin kiinteästä kokoonpanolinjasta, vähentää merkittävästi sitä vipuvaraa, jota aiemmin pakottavat instituutiot, kuten ammattiliitot ja hallitukset, saivat nauttia. Jos kokoonpanolinja olisi kuin rautatieliikenne tehtaan sisällä, jonka voisi helposti haltuun ottaa istumalakolla, kyberavaruus puolestaan on rajaton, fyysisestä olemassaolosta vapaa kokonaisuus – sitä ei voida valloittaa tai pidättää panttirahan kaltaisena. Tietoyhteiskunnan aikakaudella työntekijöiden asema, jotka pyrkivät käyttämään väkivaltaa vipuvaarana saadakseen korkeampia tuloja, on huomattavasti heikompi kuin sitä olivat General Motorsin istumalakossa toimineilla työntekijöillä vuosina 1936–37.

7. *Mikrosuorituskyky yksilöi työtä. Teollisuusteknologia standardoi työn.*  
Jokainen, joka käyttää samoja työkaluja, tuottaisi saman lopputuloksen. Mikroteknologia on alkanut korvata ‘tyhmiä’ koneita älykkäämmällä teknologialla, joka pystyy erittäin vaihtelevaan tulokseen. Sama työkalujen käyttäjien kasvava tuotostenvaihtelu kantaa mukanaan syvällisiä seurauksia – monia niistä käsittelemme tulevissa luvuissa. Yksi tärkeimmistä on se, että kuin tuotoksessa on vaihtelua, myös tulot vaihtelevat. Useimmalla niistä aloista, joilla taidot vaihtelevat, arvosta vastaa usein vain harva tuottaja. Tämä on tyypillistä erittäin kilpailluilla markkinoilla. Esimerkiksi urheilussa miljoonat nuoret ympäri maailmaa pelaavat erilaisia jalkapalloversioita, mutta 99 prosenttia jalkapallo-otteluiden seuraamiseen käytettävästä rahasta maksetaan pienen osan pelaajien esityksistä. Samoin maailma on täynnä lupaavia näyttelijöitä, mutta vain suhteellisen harva nousee tähdiksi. Vastaavasti vuosittain julkaistaan kymmeniä tuhansia kirjoja, mutta suurin osa rojaltituloista menee vain pienen määrän parhaiten myyviä kirjailijoiden käsiin – valitettavasti emme ole niiden joukossa.

Saman varusteiden käyttäjien laaja vaihtelu tuotoksissa muodostaa vielä yhden esteen kiristämiselle, sillä se synnyttää merkittävän neuvotteluongelman siitä, kuinka jakaa palkkiot. Kun suhteellisen pieni osa osallistujista tuottaa suurimman osan arvosta, on matemaattisesti lähes mahdotonta, että he jäisivät paremmin voikin pakotetun lopputuloksen seurauksena, joka tasoittaa tulot. Yksi ohjelmoija saattaa keksiä algoritmin robotin ohjaamiseen, joka osoittautuu miljoonien arvoiseksi, kun taas toinen, käyttäen identtisiä välineitä, saattaa kirjoittaa ohjelman, jolla ei ole arvoa. Tuottavampi ohjelmoija ei todennäköisemmin halua, että hänen tulonsa sidotaan toverinsa tuloihin – aivan kuten Tom Clancy ei suostu keskiarvoistamaan kirjansa rojaltimaksuja meidän kanssamme.

Jo varhaiset tietoyhteiskuntaa koskevat vaiheet ovat tehneet jo selväksi, että taidot ja henkiset kyvyt ovat ratkaisevia tekijöitä taloudellisessa tuotoksessa – paljon selvemmin kuin vuonna 1975. Tämä on jo haihduttanut teollisuuskauden aikana vallinneen, kerran ylpeiden pääomallisten kiristämisen oikeutuksen työntekijöiden taholta. Ajatus siitä, että kouluttamaton työvoima loisi itse asiassa arvoa, joka näennäisesti menisi epäsuhtaisesti pääomallisyrityksille ja yrittäjille, on nyt anakronismi. Ei ole edes uskottavaa fiktiota tietotekniikassa; kun ohjelmoija istuu koodin pariin, on liian suora yhteys hänen taitojensa ja luoman tuotteen välillä, jotta voisi erehtyä siitä, kuka on vastuussa. On kiistaton tosiasia, että lukutaidottomalla tai puolilukutaidottomalla ei voisi ohjelmoida tietokonetta, ja samoin kenenkään ei voida sanoa varastaneensa arvoa sellaisista ohjelmista, joita on koottu muiden toimesta. Tästä syystä työntekijöiden ‘riiston’ huudot kuullaan nykyään pääasiassa siivoojien keskuudessa.

IT-teknologia osoittaa selvästi, ettei matalan osaamisen ihmisten haasteena ole se, että heidän työkykyään hyödynnettäisiin epäoikeudenmukaisesti, vaan se, että he pelkäävät etteivät kykene tuottamaan todellista taloudellista lisäarvoa. Kuten Kevin Kelly ehdottaa kirjassaan *Out Of Control*, informaatiokauden "Upstart"-autoyritys saattaa olla "tasan kymmenen ihmisen" idea, jotka ulkoistavat suurimman osan osistaan ja silti valmistavat autoja, jotka on räätälöity vielä huolellisemmin ja enemmän ostajien toiveita mukaillen kuin mikään, mitä Detroitista tai Tokiosta on tähän mennessä nähty:

"Autot, jokainen räätälöity asiakkaan mukaisesti, tilataan laajan asiakasverkon toimesta ja lähetetään heti valmistuttuaan. Auton korin muotiluotokset muotoutuvat nopeasti tietokoneohjattujen lasereiden avulla, ja niihin syötetään asiakaspalautteen ja kohdemarkkinoinnin tuottamia suunnitelmia. Joustava robottirivistö kokoaa autot. Robottien huolto ja parannukset ulkoistetaan robottiyritykselle."[^213]

### "Ääniä kantavat työkalut"

Yhä enemmän ei-osaavaa työtä pystytään tekemään automatisoitujen koneiden, robottien ja laskentajärjestelmien, kuten digitaalisten avustajien, toimesta. Kun Aristoteles kuvaili orjia "ääniä kantavina työkaluina", hän tarkoitti sillä ihmisiä. Lähempänä tulevaisuutta "ääniä kantavat työkalut", kuten satujen henget, pystyvät puhumaan, noudattamaan ohjeita ja jopa hoitamaan monimutkaisiakin tehtäviä. Nopeasti kasvava laskentateho on jo synnyttänyt useita alkeellisia puheentunnistuksen sovelluksia, kuten handsfree-telepuhelimia ja tietokoneita, jotka suorittavat matemaattisia laskelmia suullisten ohjeiden perusteella. Puheesta tekstiksi muuntavia tietokoneita markkinoitiin jo myöhään vuonna 1996, kuten kirjoitamme nyt. Kun kuvioiden tunnistuskyky paranee, puhesynteesaattorilla varustetut tietokoneet tulevat toimimaan verkkojen kautta suorittaen lukuisia tehtäviä, joita aiemmin hoitivat ihmiset – puhelinoperaattorit, sihteerit, matkatoimistojen työntekijät, hallinnolliset avustajat, shakkimestarit, vahinkokäsittelijät, säveltäjät, joukkovelkakirjakauppiaat, kybersodankäynnin asiantuntijat, aseanalyytikot tai jopa katuviisas flirttaaja, joka vastaa 900-numeron puheluihin.

Carnegie-Mellon -yliopiston Michael Mauldin on ohjelmoinut tekoälypersoonallisuuden nimeltä Julia, joka pystyy huijaamaan melkein kenen tahansa, jonka kanssa hän keskustelee Internetissä. Lehdistötiedotteiden mukaan Julia on nokkela nainen, joka elää elämäänsä roolipelissä Internetissä. Hän on älykäs, hauska ja rakastaa flirttailla. Hän on myös eräänlainen jääkiekon asiantuntija ja pystyy keksimään täydellisen sarkastisen kommentin hetkessä. Julia, kuitenkin, ei ole nainen. Hän on botti, tekoäly, joka on olemassa vain Internetin eteerissä."[^214]

Tekoälyn ja digitaalisten palvelijoiden ohjelmoinnissa jo saavutettu hämmästyttävä kehitys jättää vähän epäilystäkään siitä, että monia käytännön sovelluksia on vielä edessä. Näillä on merkittäviä megapoliittisia seurauksia.

### Yksilö kokonaisuutena

Kehittyneiden monikäyttöisten „ääntä omaavien työkalujen” kehittäminen luo mahdollisuuden yksilön hajaantumiseen useisiin samanaikaisiin toimintoihin. Yksilö ei enää ole yksiselitteinen, vaan hänestä voi muodostua jopa kymmenien tai jopa tuhansien toimintoja suorittava kokonaisuus älykkäiden agenttien välityksellä. Tämä ei ainoastaan paranna merkittävästi lahjakkaimpien ihmisten tuottavuuskykyä, vaan se tekee Suvereenista yksilöä myös potentiaalisesti paljon pelottavamman sotilaallisesti kuin koskaan aiemmin.

Yksilö ei ainoastaan pysty moninkertaistamaan toimintojaan hyödyntämällä käytännössä rajoittamatonta määrää älykkäitä agentteja, vaan hän pystyy jopa toimimaan kuolemansa jälkeen. Ensimmäistä kertaa yksilö kykenee hoitamaan monimutkaisia tehtäviä, vaikka hän olisi biologisesti kuollut. Ei enää ole mahdollista, että vihollinen sodassa tai rikollinen pystyisi täysin sammuttamaan yksilön kyvyn kostaa tappamalla hänet. Tämä on yksi historian vallankumouksellisimmista innovaatioista väkivallan logiikassa.

### Insights for the Information Age

Elämän suurimmat muutokset tapahtuvat muuttujissa, joita kukaan ei seuraa. Toisin sanottuna, pidämme itsestäänselvyytenä niitä muuttujia, joiden vaihtelu on ollut hyvin vähäistä vuosisatojen tai jopa satojen sukupolvien ajan. Suurimmassa osassa historiaa, ellei ihmiskunnan suurimmassa osassa, suojelun ja kiristyksen välinen tasapaino on heilahdellut kapealla rajalla, missä kiristys on aina ollut etulinjassa. Nyt tämä on muuttumassa. Tietotekniikka luo pohjan perustavanlaatuiselle muutokselle tekijöissä, jotka määrittävät väkivallan käytön kustannukset ja palkkiot. Se, että älykkäät agentit ovat saatavilla tutkimaan ja ehkä kostamaan jollain tavalla niitä, jotka aloittavat väkivallan, on vain vihje tästä uudesta näkymästä suojelussa. Kahdenkymmenenviiden vuotta sitten seuraava lausunto olisi ollut vain yksittäisen kammottajan murinaa: ‘Jos tapaat minut, pyyhin rahasi pankkitileiltäsi ja annan ne Nepalissa toimiville hyväntekeväisyysjärjestöille.’ Vuosituhannen vaihteen jälkeen tilanne ei välttämättä ole enää sama. Se, osoittaako se käytännön uhkana, määräytyy ajan ja paikan tekijöiden mukaan. Ja vaikka potentiaalisen rikollisen tilit osoittautuisivatkin läpäisemättömiksi, älykkäiden agenttien armeijalla olisi varmasti muitakin kalliita häiriöitä, joita se voisi määrätä kostoksi rikoksesta. Mieti sitä.

### New Alternatives in Protection

Teknologia, joka tietokoneajan myötä on avannut lukuisia uusia suojan parantamisen keinoja, tarjoaa vaihtoehtoja, jotka usein murentavat sitä lähes monopolistista suojan ja kiristyksen asemaa, josta hallitukset ovat nauttineet kahden viime vuosisadan ajan. Vaikka uusia teknologisia kikkailuja ei olisi, on aina ollut vaihtoehtoja suojautumiseen – eivätkä kaikki niistä ole jääneet hallitusten monopoliksi.

Henkilö, joka kokee itsensä uhatuksi, voi yksinkertaisesti karata. Kun maailma oli nuori ja horisontit olivat avoinna, pakeneminen oli yleinen vaihtoehto. Kun ihmiset pelkäävät menettävänsä omaisuutta varkauden tai ilkivallan vuoksi, he voivat päättää hankkia vakuutuksia näiden riskien kattamiseksi. Vaikka kiroukset ja loitsut ovatkin heikkoja suojan muotoja, ne ovat toisinaan pelastaneet henkiä ja karkottaneet varkaiden tekoja – erityisesti yhteiskunnissa, joissa saalistajat ovat taikauskoisia. Arvokkaat esineet voi myös suojata piilottamalla ne; tämä menetelmä toimii joskus, kun se on toteutettavissa. Omaisuutta voidaan haudata, lukita, sijoittaa korkeiden muurien taakse ja varustaa sireeneillä sekä elektronisilla valvontalaitteilla. Kuitenkaan ihmisen tai omaisuuden piilottaminen ei aina ole ollut käytännöllistä.

Kaikista historiallisista suojelukeinoista yksi on kuitenkin hallinnut muita – kyky vastata väkivallan uhkaan väkivallalla, eli kutsua käyttöön suurempi voima yllättämään kenet tahansa, joka yrittäisi hyökätä tai varastaa omaisuuttasi. Kysymys on: mistä hakea tällainen palvelu ja miten motivoida ketään ottamaan hengen ja raajojen riskin auttaakseen sinua taistelemaan niitä väkivaltaisia ilkivallantekijöitä vastaan? Joskus lähellä olevat sukulaiset ovat vastanneet tähän tarpeeseen. Joskus heimoon tai klaanin perustuvat ryhmät ovat toimineet epävirallisena poliisina, jotka reagoivat kenen tahansa jäsentensä kohtaan kohdistuvaan väkivaltain verenvuodatuksin. Joskus palkkasoturit tai yksityiset vartijat ovat olleet käytössä hyökkäysten torjumiseksi – mutta eivät aina niin tehokkaasti kuin toivoisi. Tietokoneajan uudet älykkäät agentit, vaikka heidän toimintansa rajoittuisikin suurelta osin kyberavaruuteen, tarjoavat uuden vaihtoehdon, jossa heidän lojaalisuutensa eroaa kiistattomasti palkkasotureiden, yksityisten vartijoiden ja jopa kaukaisten sukulaisten vastaavista.

### Valtaoikojen paradoksit

Väkivallan käyttöä väkivallan suojaamiseksi on täynnä paradokseja. Aiemmin vallitsevina olosuhteina mikä tahansa ryhmä tai elin, jota voisit käyttää onnistuneesti suojellaksesi henkesi ja varallisuutesi hyökkäyksiltä, omistaisi samalla kyvyn ottaa se itse haltuunsa. Tämä on haittapuoli, jolle ei ole yksinkertaista ratkaisua. Normaalisti voisit luottaa kilpailuun estämään taloudellisia palveluntarjoajia jättämästä asiakkaidensa toiveita huomiotta. Mutta väkivallan kohdalla suora kilpailu johtaa usein vastoinmielisiin tuloksiin. Aiemmin kahden potentiaalisen suojeluelimen toimittaessa omat joukkojensa nappaamiseen tulos muistuttaa enemmän sisällissotaa kuin suojausta. Kun etsit suojaa väkivallan varalta, et yleensä halua lisätä väkivallan määrää vaan sen vähentämistä – ehdoilla, jotka eivät salli suojauspalvelua vastaanottavien asiakkaiden ryöstöä.

> "...aikana, jolloin miehet elävät ilman yhteistä valtaa, joka saisi heidät kaikki kunnioittamaan, he ovat siinä tilassa, jota kutsutaan sodaksi: ja sellaisena sodana, joka on jokaisen miehen sodan jokaisen miehen kanssa, missä miehet elävät ilman muuta turvaa kuin mitä heidän oma voimansa ja heidän omat keksintönsä heille tarjoavat." - THOMAS HOBBES

### Monopolia ja anarkiaa

Juuri siksi anarkia eli, kuten Hobbes kuvaili, 'kaikkien sota kaikkia vastaan' ei ole harvoin ollut tyydyttävä järjestely. Paikallinen väkivallan käytön kilpailu on yleensä tarkoittanut korkeampien suojelukustannusten maksamista ja vähemmän suojelua. Ajoittain markkinajärjestelmää ajavat vapaat ajattelijat ovat ehdottaneet, että yksin markkinamekanismit riittäisivät omaisuusoikeuksien valvomiseen ja elämän suojelemiseen, ilman minkäänlaista suvereniteettia.[^215]: Joitakin analyysejä on tehty tyylikkäästi, mutta tosiasia on, että vapaan markkinan tarjoamat poliisi- ja oikeuspalvelut eivät ole osoittautuneet toimiviksi teollistumisen megapoliittisissa olosuhteissa. Vain primitiiviset yhteisöt, joissa käyttäytyminen on erittäin stereotyyppistä ja väestö on pientä ja homogeenista, ovat kyenneet selviytymään ilman hallituksia, jotka tarjoaisivat paikallisesti monopolisoitua suojelua väkivallan keinoin.

Esimerkkejä anarkistisista yhteiskunnista, jotka ovat metsästäjä-keräilijäheimojen yläpuolella, on harvoja ja ne ovat muinaisia. Ne kuuluvat kaikki eristetyimpien sadeveden kerääjien yksinkertaisimpiin talouksiin – esimerkiksi pre-muslimidessa Afganistanissa eläneisiin kafireihin, joidenkin pimeiden aikojen irlantilaisten heimojen joukkoon, joidenkin intiaanibändien joukkoon Brasiliassa, Venezuelassa ja Paraguayssa sekä muihin alkuperäiskansoihin eri puolilla maailmaa. Näiden hallituksen ulkopuolisen suojelun järjestämistapoja tietävät vain äärimmäisiä tapauksia tutkineet asiantuntijat. Jos haluat oppia niistä lisää, viitamme Muistiinpanoissamme useisiin kirjoihin, joissa on tarkempia tietoja.[^216]: Primitiiviset ryhmät pystyivät toimimaan ilman erillistä väkivallan erikoistunutta organisaatiota vain siksi, että ne olivat pieniä, suljettuja ja eristäytyneitä. Ne saattoivat turvautua tiiviisiin sukulaisuussuhteisiin puolustaakseen itseään rajoitetuin mittakaavoin – eikä heille kohdistuisi muuta väkivaltaista uhkaa. Kun ne kohtasivat suurempia uhkia, joita valtiot organisoivat, ne ylittyivät ja joutuivat ulkopuolisten ryhmien monopolisoiman hallinnon alle. Näin on käynyt kerta toisensa jälkeen. Missä tahansa yhteiskunnat ovat muodostuneet ryhmien ja heimojen yläpuolelle, erityisesti silloin, kun kauppareitit toivat eri kansoja kosketuksiin, on aina noussut väkivallan asiantuntijoita ryöstämään kaiken ylijäämän, jonka rauhallisemmat ihmiset pystyivät tuottamaan. Kun teknologiset olosuhteet nostivat väkivallan tuottoa, ne tuomitsivat yhteiskunnat, jotka eivät olleet järjestäytyneet ohjaamaan suuria resursseja sodankäyntiin.

> "Mitkä ruhtinaat toimittivat poliisipalveluita? Mitkä olivat kiristyshurjia tai jopa ryöstäjiä? Ryöstäjä voisi itseasiassa nousta poliisin päälliköksi heti, kun hän säännöllisti otti osuutensa, sovitti sen maksukykyynsä, puolusti omaa aluettaan muita ryöstäjiä vastaan ja ylläpiti alueellista monopoliaan tarpeeksi kauan – tai kun perinteen mukaisesti saatiin se lailliseksi."[^217]: - FREDERIC C. LANE

### Hallitus suojelun myyjänä

Kuten olemme useaan otteeseen sanoneet, hallituksen keskeisin taloudellinen tehtävä niitä maksavien veronmaksajien näkökulmasta on suojella ihmishenkeä ja omaisuutta. Kuitenkin hallitus toimii usein kuin järjestäytynyt rikollisuus, perimällä resursseja sen toiminta-alueella olevilta ihmisiltä kunniamaininnan tai ryöstön muodossa. Hallitus ei ole pelkästään suojelupalvelu; se on myös suojelupalaute. Vaikka hallitus tarjoaa suojaa muiden aiheuttamaa väkivaltaa vastaan, se perii asiakkailtaan maksun myös siltä vahingolta, jonka se muuten itse aiheuttaisi. Ensimmäinen toimi on siis taloudellinen palvelu, kun taas toinen on kiristystoimintaa. Käytännössä näiden kahden "suojelun" erottaminen voi olla vaikeaa. Hallitukset, kuten Charles Tilly on todennut, voidaan ehkä parhaiten ymmärtää "suurimpina järjestäytyneen rikollisuuden esimerkkeinä."[^218]

Jopa parhaankin hallituksen toimintaan sisältyi yleensä jonkinlaista sekoitusta taloudellista suojelupalvelua ja kiristystä. Historiallisesti molempia toimintoja olisi voitu optimoida, jos hallitus olisi voinut määrätä lähes monopolin väkivallan käytöstä niillä alueilla, joilla se toimii. Siinä tapauksessa, kun yksi aseistettu ryhmä pystyi vakiinnuttamaan valta-asemansa väkivallan käytössä, se tarjoama suojelupalvelu oli tavallisesti huomattavasti laadukkaampaa kuin mitä useiden kilpailevien suojelutoimistojen taisteltaessa samasta alueesta olisi voitu saada.

### Luonnollinen monopoli maassa

Paikallisen väkivallan käytön monopolin saavuttaminen ei ainoastaan mahdollistanut hallitukselle tehokkaampaa suojaa potentiaalisille asiakkaille toisten aloittamaa väkivaltaa vastaan, vaan se myös alensi huomattavasti hallituksen toimintakustannuksia. Kuten Lane totesi, "Väkivaltaa käyttävä ja sitä hallitseva teollisuus oli luonnollinen monopoli, ainakin maalla. Alueellisissa rajoissa sen tuottamaa palvelua pystyttiin tuottamaan paljon edullisemmin monopolin toimesta."[^219] Näin ollen "monopoli väkivallan käytössä yhtenä yhtenäisenä alueena mahdollisti suojaa tuottavan yrityksen parantaa tuotettaan ja vähentää kustannuksiaan."[^220] Tällainen hallinnollinen organisaatio pystyi tarjoamaan enemmän suojaa vähemmällä kululla, mikäli sen ei tarvitsisi käydä jatkuvia sotilaallisia toimenpiteitä kilpailevien ryhmien torjumiseksi, jotka pyrkivät perimään suojelumaksuja sen asiakkailta.

Mahdollisuus, että informaatioteknologia rentouttaa oletusta siitä, että suvereniteetin on perustuttava alueelliseen monopoliin, on jo herättänyt poliittisten teoreetikkojen huomion. Tämä on teema kirjassa *Beyond Sovereignty: Territory and Political Economy in the Twenty-First Century*, jonka on kirjoittanut David J. Elkins. Elkins toistaa väitöksiämme, joiden mukaan monopolihallitukset ovat tuomittuja välittymästään hajoamaan, aivan kuten uskonnolliset monopolit hajosivat 1500-luvun jälkeisinä vuosina. Hän kirjoittaa: "Olemme ennen olettaneet, että uskonnoilla tulisi olla oma alueensa eli 'piirinsä'. Kun kansakunnat korvasivat universaalit uskonnot elämän ja kuoleman suvereenina tuomareina, uskonnon 'koheenssi' ja 'rajoitettuus' väistyivät nykyiseksi tutuiksi uskovien sekoittumisiksi samalla alueella. Sen sijaan emme suostu hyväksymään kansakuntien – tai maakuntien – sekoittumista, vaikka uskonkin, että tämä oletus on murentumassa."[^221]

Hän jatkaa väittäen, yhtenevästi meidän näkemyksemme kanssa, että suvereniteetin alueelliset monopolit voidaan purkaa ilman anarkiaa, kuten esimerkiksi Kanadan liittovaltion järjestelmässä kansallisen ja maakuntahallituksen välisellä suvereniteetin jakautumisella ja joidenkin Tyynenmeren saarten yhteishallintoa kuvaavalla kondominihallituksella, jossa ranskalainen ja brittiläinen suvereniteetti jaettiin. Näin ollen, vaikka alueellisia suvereniteetin monopoleja harvoin puretaan väkivalloin, ne voidaan purkaa sopimuksin.

Elkinsin mukaan – ja me olemme samaa mieltä – "alueellinen kansakunta on ollut kuin nipuke tai kori, johon osat elämästämme on sovitettu. Se on samanlainen kuin taloustieteellinen käsite hyödykepakettina – et voi helposti saada tuotteita yksittäin, vaan ne täytyy ottaa kokonaisuutena. Ravintolassa voi tilata à la carte – mutta identiteettejemme osalta meidän on hyväksyttävä se, minkä kansakunnat ovat yhdessä koonneet, mikä vastaa table d'hôtea. ... Hallinto à la carte vaikuttaa luonnolliselta 2000-luvun kansalaisille."[^222]

Ei mikään kehitys tule vaikuttamaan dramaattisemmin suvereniteetin hajottumiseen ja à la carte -hallinnon nousuun kuin kybertalouden synty, joka ylittää kokonaan fyysiset rajat.

> "Kun taajuudet nousevat ja aallonpituudet laskevat, digitaalinen suorituskyky paranee eksponentiaalisesti. Kaistanleveys kasvaa, virrankulutus pienenee, antennin koko pienenee, häiriöt romahtavat, virheradat laskevat jyrkästi." - George Gilder

## telekosmin laki kumoaa kansojen lait

Emme ole ainoita, jotka näkevät, että kaistanleveys (tai viestintävälineiden kantokyky) on tuomittu päihittämään aluevaltion. Jim Taylor ja Watts Wacker, *The 500-Year Delta: What Happens After What Comes Next* -kirjan kirjoittajat, eivät määrittele argumenttiaan meidän tavallamme, mutta he myöntävät, että "pääsy luo globalismia, ja globalismi häiritsee poliittisia järjestelmiä, tehden rajakäsitteestä vanhentuneen. Kun rajat katoavat, verotuksen käsite, joka tukee hallituksia, muuttuu yhä hauraammaksi... Kun rajat katoavat, niin myös oikeuteen – käsitykseen siitä, että koska synnyit tietyssä paikassa, sinulla on oikeus siihen taloudelliseen etuun, jota siihen paikkaan liittyy – romahtaa, ja kun se romahtaa, kansakunnan etuoikeudet romahtavat sen mukana. Ja kaiken tämän edetessä ne arvot, jotka kansakunnan perusta ovat – maanaerollisuus, demokratia, valtio, sulatusuuni, yhdentyminen, vastuullinen osallistuminen, mitä tahansa ne olisivatkaan missä tahansa maassa, jossa asut – joutuvat historian romukoppaan."[^223]

Ilman, että he sanoisivat sitä suoraan, hekin aistivat, että historia on liikkeessä kohti suvereenin yksilön vapautumista. Kuten he sanovat, "horisontissa odottaa paljon puhtaampaa individualismin muotoa kuin nykyinen demokratia sallii."[^224]

Miten tämä tapahtuu? Taylor ja Wacker näkevät voimakkaan dynamiikan vaikuttavan.

Yksinkertainen totuus on, että laajemman kansallisrakkauden – rakkauden omaa kansakuntaansa kohtaan, isänmaallisuuden – ylläpitäminen ei ole enää erityisen hyödyllinen asenne. Globalisoituneessa yhteiskunnassa menestyvät kansalaiset valitsevat perustuen suoraan poliittisiin, sosiaalisiin ja taloudellisiin identiteetteihinsä – eivätkä vain ihmisiin, jotka ovat heidän kaltaisiaan – vaan sen perusteella, miten nuo valinnat liittyvät heihin itseensä. He järjestäytyvät sen mukaisesti ja maksimoivat vapauden tietää, mennä, tehdä ja olla. Ne kansakunnat ja yritykset, jotka eivät tee niin vaan jatkavat taaksepäin taistelemista nostalgiaan nojautuvilla toimenpiteillä, rappeutuvat.[^225]

Fyysisten rajojen arvonalenema, jota vuosittainen kaistanleveyden kolminkertaistuminen ja Internetin sekä World Wide Webin geometrinen kasvu edustavat, kiihtyy hallitusten välikäsien poistamisprosessia. Itse asiassa, jos kaistanleveyden vuotuinen kolminkertaistuminen jatkuisi vuoteen 2012 asti, se tarkoittaisi miljardinkertaista kasvua vuodesta 1993 alkaen, jolloin George Gilder ehdotti ensimmäisenä, että kaistanleveyden kasvu kertyisi vieläkin nopeammin kuin mikroprosessoreiden kapasiteetin. Jos näin käy – kuten uskomme tapahtuvan, tuomalla esiin viimeisimmät edistysaskeleet integroidussa optiikassa – luotettavan viestintäkyvyn yltäkylläisyys johtaisi uskomattomaan kasvuun kyberkaupassa. Aaltosimiloinnin avulla yksittäinen kuitu, ihmisen karvaa ohuena, kykenee kuljettamaan biljoona bittiä sekunnissa.[^226] Toisin sanoen, yksi kuituoptinen kaapeli voisi kantaa 25 kertaa enemmän bittejä kuin kaikkien maailman viestintäverkkojen kokonaiskuorma. Laajennuskapasiteetti on hämmästyttävä. Tällaisen viestintäkyvyn vapauttaminen saa aikaan sen, että huomattavasti enemmän rahaa käytetään viestintään, koska se tulee niin edulliseksi. Myös vakiintuneet mediat, kuten erikoistunut puhelin- ja televisiopalvelu, muuttuvat ajan myötä anakronistisiksi. World Wide Web tarjoaa jokaiselle tietokoneelle rikkaamman signaalimassojen sekoituksen kuin nykyään verkko-TV, ja kun kaistanleveysvallankumous etenee, se vetää yhä enemmän ihmisiä mukaan rajattomaan virtuaalimaailmaan, jossa verkko-yhteisöt ja kyberkauppa kukoistavat – maailmaan, jossa on riittävästi graafista tiheyttä muodostamaan “metaversumi”, se vaihtoehtoinen, kyberavaruuteen perustuva todellisuus, jonka tieteiskirjailija Neal Stephenson on kuvitellut. Stephensonin “metaversumi” on virtuaaliyhteisö, jolla on omat lakinsa, prinssinsä ja pahiksensa.[^227] Kun yhä enemmän taloudellista toimintaa siirtyy kyberavaruuteen, valtioiden rajojen sisäinen monopolivaltansa arvo kutistuu, mikä antaa valtioille kasvavan kannustimen antaa itselleen fransiseja ja hajottaa suvereniteettiaan.

Aivan kuten nykyiset kansallisvaltiot ovat kannustettuja isännöimään vapaakauppaportteja, vapaakauppa-alueita ja zona francoja, ne tulevat saamaan myöhemmin myös kannustimia vuokrata suvereniteettiaan. Olemme jo keskustelleet hyvin edistyneistä neuvotteluista Maltan tasavallan ja 900-vuotiaasta Sovereign Military Hospitaller Order of St. John of Jerusalem, of Rhodes and of Malta – yleisesti tunnetusta Maltan ritarikunnasta – siitä, miten Fort St. Angelon suvereniteetti palautettaisiin järjestölle. Odotamme näiden neuvottelujen päättyvän onnistuneesti. Muita vastaavia aloitteita seuraa: jotkut kansallisvaltiot luovuttavat suvereniteettiaan pieniltä pesäkkeiltä ja syrjäisiltä alueilta kokonaan uusille yhteenkuuluvuuksille ja virtuaaliyhteisöille. Itse asiassa ei ole epätodennäköistä, että kaupalliset toimijat, kuten turvallisuusyritykset ja hotelliketjut, tulevat huutamaan tulevaisuudessa suvereniteetista pienillä maankappaleilla. Wackenhut, Pinkerton ja Argenbright saattavat tulevaisuudessa tarjota hybridiportaittain järjestettyjä suljettuja eläkeläisyhteisöjä ja verovapaita alueita houkuttelevissa ilmastoissa ympäri maailman. Uskonnolliset tahot – kuten Maltan ritarikunta, mutta kaikkia mahdollisia kirkkokuntia silmällä pitäen – yrittävät omilla tavoillaan tuoda taivaan ruumiillistumisen tiettyihin syrjäisiin maailman nurkkiin. Jopa varakkaat yksilöt ja perheet tulevat omistamaan omia maanosia, joissa he voivat harjoittaa rajoitettua suvereniteettia, liittää omat leimansa ja passinsa sekä ylläpitää omaa verkkosivua.

## Monopoly and plunder

Huomaa, että kannustimet jakaa tai vuokrata suvereniteettia maksua vastaan ovat hyvin erilaiset kuin ne, joita historiallisesti ovat kohdanneet hallitsijat, joilla on ollut paikallinen pakottamisen monopolinsä ja jotka ovat joutuneet sotilaallisen kilpailun alaisiksi. Vuokrattu suvereniteetti ei ole epävakaampaa kuin esimerkiksi vapaakauppa-alueen isännöinti. Sen sijaan sotilaallinen valtaosaaminen, kuten kamppailu sotapäälliköiden ja sissiryhmien välillä, vaikuttaa suoraan siihen, ovatko hallitusmiehet enemmän halukkaita suojelemaan niitä kansalaisia, jotka kuuluvat niiden piiriin, vai ryöstämään heitä. Kun vastassa olevat ryhmät kamppailevat ja neuvottelevat epävakaassa tasapainossa, saalistavan väkivallan kannustimet kasvavat. Ryöstöstä tulee houkuttelevampaa. Koska voima on vähemmän vakaata ja paikallinen pakottamisen monopolikin heikompi, niiden, joilla on mahdollisuus käyttää väkivaltaa, ennakoitava aikahorisontti lyhenee. ‘Vuoren kuningas’ saattaa seistä niin liukkaalla pohjalla, ettei hän voi odottaa selviävänsä tarpeeksi kauan saadakseen osansa merkittävistä hyödyistä, joita väkivallan hillitsemisestä lopulta syntyy. Tällaisessa tilanteessa vähän estäisi niitä, jotka komennusasemassa toimivat niin kuin hallitus, käyttämästä valtaansa kansan pelottamiseen ja ryöstämään heitä.

Voiman logiikka siis osoittaa, että mitä enemmän kilpailevia aseistettuja ryhmiä toimii missä tahansa alueella, sitä todennäköisemmin ne turvautuvat saalistavaan väkivallan käyttöön. Ilman yhtä ylivoimaista voimaa estämässä itsenäistä väkivaltaa, se tyypillisesti lisääntyy, ja monet taloudellisen ja sosiaalisen yhteistyön hyödyt menevät kokonaan hukkaan.

Väkivallan täysivaltaisuuden aiheuttamat tuhot kaaoksen olosuhteissa näkyvät Kiinan kohtalona 1920-luvulla sotaherrahallinnon alla. Tämä on tarina, jonka kerroimme teoksessamme **The Great Reckoning**. Kilpailevat sotaherrat aiheuttivat valtavia vahinkoja alueilla, joilla ei ollut yhtä yksittäistä, ylivoimaista voimaa hillitsemään heitä. Samankaltaisia kertomuksia, jotka havainnollistavat tätä seikkaa, on esitetty elävässä värimaailmassa *CNN*:n uutiskamppailijoiden toimesta, jotka uhmaavat Mogadishun Somalian kaduilla. Somalian sotaherrat, joita lempinimellä kutsutaan "teknikoiksi", toivat kaaosta tuohon surulliseen maahan ennen kuin Yhdysvallat johti massiivista sotilaallista interventiota niiden hillitsemiseksi. Kun Yhdysvaltojen joukkojen ylivoimainen voima vedettiin pois, teknikot ottivat aseensa jälleen esiin ja kaaos palasi. Washington Postin raportissa todettiin:

> '[P]ickup-kuorma-autot, joissa on ilmapuolustusaseita, raivaavat jälleen pölyisiä, raunioituneita katuja. Myös riehakkaat nuoret, jotka kuljettavat hartioillaan Kalashnikov-ryksejä ja pukeutuvat T-paitoihin, vaativat rahaa ohitse ajavista autoista ja busseista tilapäisillä tienpätkillä. Yksi militsian hallitsemista naapurustoista on niin voimakkaasti aseistettu, että paikalliset kutsuvat sitä "Bosnia-Herzegovinaksi." Tämän päivän Mogadishun karuilla kaduilla liikkuminen muistuttaa häikäisevästi vuoden 1992 aikoja, jolloin rivimaiset militsiat syöksivät Somalian kaaokseen ja nälänhädän, mikä johti Yhdysvaltojen johtamaan sotilaalliseen interventioon. Taas kerran Mogadishuun matkustavien on vuokrattava auto täynnä aseistettuja rosvoja, toivoen saavansa suojaa sadalla dollarilla päivässä, siihen lisättynä lounastauko.[^228]

Televisiosta pian näkemäsi esimerkit Somaliasta, Ruandasta ja muista maista tarjoavat teknivärimaista todistusaineistoa siitä, että väkivaltaisen aluehallinnasta kilpaileva taistelu ei tuota samalla välittömiä taloudellisia etuja kuin muut kilpailumuodot. Päinvastoin, kaaoksen vallassa toimivilla kulkureikäjillä ja ryöstäjillä ei ole edes heikkoja kannustimia suojella tuottavaa toimintaa, joiden ansiosta jopa diktaattoreiden tiukka ote voi toisinaan keventyä, kun heidän hallintonsa on varmaa.

> 'Modernin ajan yhteiskuntaa, erityisesti lännessä, leimaa tietynlainen monopolisaation taso: yksilöiltä evätään vapaa pääsy sotilaallisiin aseisiin, jotka on varattu keskitetylle toimivaltaiselle viranomaiselle, ja samalla yksilöiden omaisuuden tai tulojen verotus keskittyy samanlaisen keskusyhteisön käsiin. Näin keskusviranomaiselle virtaavat taloudelliset keinot ylläpitävät sen sotilaallista monopoliasemaansa, joka puolestaan vahvistaa verotuksen monopolia. Kumpikaan ei missään mielessä ole toisensa edellä; ne ovat saman monopolian kaksi puolta. Jos toinen katoaa, toinen seuraa siitä automaattisesti; monopolihallintoa voi toisinaan täräyttää enemmän toiselta puolelta kuin toiselta.'[^229]  
– NORBERT ELIAS

## Suojelun kehitys



Lane kehitti näkemyksen, jota olemme myöhemmin väärinkäyttäneet kuvitellessamme, miten informaatiokausi saattaa kehittyä. Hän väitti, että länsimaisten talouksien historia pimeän ajan jälkeen voidaan tulkita neljän väkivallan organisoimisen kilpailun ja monopolin vaiheena. Vaikka Lane pysyy suurelta osin hiljaa niistä megapoliittisista tekijöistä, joita me pidämme vaikuttavina hallitusten toiminnan mittakaavaan, hänen analyysinsä väkivallan taloudellisista ulottuvuuksista osuu läheisesti yhteen sen argumentin kanssa, jonka esittelimme teoksissa *Blood in the Streets* ja **The Great Reckoning** sekä muuallakin tässä teoksessa.

Olemme jo analysoineet joitakin megapoliittisia tekijöitä, jotka vaikuttivat länsimaisten yhteiskuntien kehitykseen Rooman tuhon jälkeen. Lane tarkasteli myös tätä ajanjaksoa ja keskittyi kilpailun taloudellisiin seurauksiin, kun pyrittiin monopolisoimaan väkivaltaa. Hän erotti neljä keskeistä vaihetta talouksien toiminnassa viimeisen tuhannen vuoden aikana, joista kukin kuvastaa erilaista väkivallan järjestäytymisen vaihetta.[^244]

### Pimeästä aikakaudesta eteenpäin

Ensimmäinen vaihe on se, jota voi kutsua "anarkiaksi ja ryöstöksi", ja se merkitsi tuhannen vuotta sitten tapahtunutta feodaalista vallankumousta. Vaikka Lane ei tarkenna yhtään ajanjakson alkamispäivää, laskutoimitukset määrittävät hänen ensimmäisen aikakautensa rajan varsin selkeästi, ja hänen kuvauksensa "anarkiasta ja ryöstöstä" vaikuttaa vastaavan olosuhteita pimeän ajan jälkeisessä siirtymässä, jolloin väkivallan käyttö oli "äärimmäisen kilpailullista, jopa maalla."[^230] Hän ei kerro syytä, mutta kun väkivalta on "äärimmäisen kilpailullista", sillä on yleensä merkittäviä esteitä vallan projisoinnille etäisyydelle; sotilaallisessa mielessä puolustus korostuu hyökkäyksen sijaan.

Kuten luvussa 3 selitimme, tämä "anarkian ja ryöstön" vaihe osui samaan aikaan, kun maatalouden tuottavuus laski haitallisten ilmastollisten muutosten vuoksi. Koska teknologia tarjosi tuolloin vain vähän tehokkaita mittakaavaetuja väkivallan monopolisoimisen turvaamiseksi, potentiaalisten hallitsijoiden välinen kilpailu oli laajalle levinnyttä. Taloudellinen toiminta tukahduttiin.

Talouden heikkous pahensi vakaan järjestyksen luomisen ongelmaa. Paikallisen väkivaltamonopolin saavuttaminen vaati liian suuria sotilaallisia kustannuksia suhteessa talouskierron vaatimattomaan arvoon. Ilman kykyä panna tehokasta monopolia taloudellisesti kannattavalle alueelle aseistetut ratsarit uhkasivat ja ryöstivät, tarjoten samalla vain vähän 'suojelua' asiakkailleen.

### Feodalismi

'Toinen vaihe alkaa, kun muodostuu pieniä alueellisia tai maakunnallisia monopoleja. Sitten maataloustuotanto kasvaa, ja suurin osa ylijäämästä kerätään äskettäin vakiintuneiden väkivallan monopoleista.'[^231]: Silti ylijäämä tässä toisessa vaiheessa, jonka tunnistamme varhaiskeskiaikaan, on suhteellisen vaatimaton. Talouskasvua pidätetään alhaisena skaalaetujen puutteeseen liittyvän väkivallan järjestämisessä, mikä pitää paikallisten monopolien valvonnan sotilaalliset kustannukset korkeina. Mutta kun kustannukset pysyvät korkeina, pienvaltioiden veloittama suojeluhinta nousee, sillä taloudellinen toiminta laajenee anarkian karsimisen myötä.

Toisen vaiheen myöhäisvaiheessa monet tributinvastaajat houkuttelevat asiakkaita erikoistarjouksilla maatalous- ja kauppayrityksille. He tarjoavat suojelua alhaisilla hinnoilla niille, jotka tuovat uusia maa-alueita viljelyyn, sekä erityisiä poliisipalveluita kaupankäynnin edistämiseksi, kuten Champagnen kreivien järjestämiä messuja kauppiaille. Toisin sanoen, kun he pystyivät saavuttamaan riittävän hallinnan alueestaan uskottavasti neuvotellakseen, paikalliset sotapäälliköt tekivät kuten kauppiaat, jotka haluavat kasvattaa markkinaosuuttaan: he alensivat palveluidensa hintoja houkutellakseen asiakkaita. Myöhemmin sotapäälliköt käyttivät lisätaloudellisesta toiminnasta kertyneitä resursseja hallintansa vahvistamiseen laajemmille alueille. Kun kontrolli oli vakiintunut, he alkoivat nauttia entistä enemmän monopolin eduista; heidän sotilaalliset kustannuksensa poliisitoiminnassa alenivat, ja he pystyivät nostamaan veloittamansa hinnan ilman huolta siitä, että se tekisi heidän palvelustaan vähemmän houkuttelevia.

Tässä monimutkaisessa länsimaisen historian vaiheessa väkivaltaa käyttävät, keskiaikaiset herrat ja monarkit, saivat suurimman osan elannon yllä elämistä ohittavasta ylijäämästä. Kauppiaita oli vähän. Menestyneimpiä olivat ne, jotka pystyivät parhaiten välttämään tai minimoimaan verot, maksut ja muut kulut, joita vaadittiin 'suojelupalveluista' maksettaessa.

### Varhaismoderni aika

Kolmas vaihe saavutetaan, kun kauppiaat ja maanomistajat, jotka eivät ole erikoistuneet väkivallan käyttöön, 'saavat enemmän osaa talouden ylijäämästä kuin feodaalien haltijat ja monarkit.... Tässä kolmannessa vaiheessa väkivallan käyttöön erikoistuneet yritykset saavat vähemmän ylijäämää kuin ne yritykset, jotka ostavat suojelua hallituksilta.'[^233] Koska menestyvät kauppiaat ovat todennäköisemmin sijoittamassa voittonsa uudelleen kuin kuluttamassa niitä, kyseisen aikakauden kauppiaiden korkeammat voitot johtivat itsensä vahvistavaan kasvuun.

### Tehdasaika

Lane yhdistää siirtymisen kolmannesta vaiheesta neljänteen siihen, että teknologiset ja teolliset innovaatiot alkoivat olla tärkeämpiä tekijöitä voittojen saavuttamisessa kuin suojelukustannusten alentaminen. Lane viittaa tällä 1750-luvulta eteenpäin, jolloin teknologian luonne alkoi näytellä selvästi hallitsevaa roolia alueiden vauraudessa. Äärimmäisessä tapauksessa, jopa alueet, joilla ei ollut lainkaan hallitusta – kuten esimerkiksi joidenkin Uuden-Seelannin osien tilanne ennen vuotta 1840 – eivät todennäköisesti nousseet korkeaan vaurauteen pelkästään siksi, etteivät ne maksaneet veroja. Tuolloin teollisen teknologian innovaatiot olivat voittojen saavuttamisessa tärkeämpiä kuin mikään säästö, joka olisi mahdollista saada laskemalla suojelukustannuksia jopa nollaan. Valtion koon kasvaessa hallitusten alun perin kehittämät luotto- ja rahoitusmekanismit, joilla kerättiin resursseja sotilaallisiin operaatioihin, tulivat saataville suurempien yritysten rahoittamiseen.

Vaikka Lane ei sitä eksplisiittisesti sano, teknologisten etujen keskittyminen tietylle alueelle vähensi eri oikeusalueiden välistä kilpailua ja mahdollisti sen, että 'väkivallan käyttöön erikoistuneet yritykset' – eli hallitukset – pystyivät veloittamaan korkeampia hintoja. Kun eri oikeusalueiden kilpailijoiden välillä vallitsee suuria teknologisia kuiluja, kuten teollisuusajan aikana oli, ne yrittäjät, jotka toimivat parhaan teknologian omistamilla alueilla, tekevät yleensä enemmän rahaa, vaikka heidänkin saattaakin joutua maksamaan korkeampia veroja ja muita kustannuksia hallituksilleen.

### Ryöstö hymy kasvoilla

Teollisuusajan hallituksilla oli hurmaava monopoliasema hyväksikäyttöön. Niiden todelliset kustannukset elämän ja raajojen suojelemiselle olivat lähes olemattomat verrattuna perimiinsä hintoihin (verot). Silti ne toimivat sellaisessa ulottuvuudessa, jossa kilpailu oli niin vääristynyttä, että ne pystyivät harjoittamaan paljon enemmän ryöstöä kuin suojelua – tämä jäi lähes huomaamatta. Se oli harvinainen hetki historiassa.

Teollistumisen megapoliittisten olosuhteiden hallitsemassa anarkiassa saman alueen sisällä tapahtuva suojauspalveluiden kilpailu oli teknologisesti epärealistista. Ainoa tapa saavuttaa tehokas suojaus näissä oloissa oli hallita suurempi väkivallan käyttökyky. Siksi ei juuri hyötyä ollut yrittää erottaa tarkemmin sitä osaa verojen summasta, joka Lane sanojen mukaan meni "maksetuksi palvelusta" siitä "toisesta osasta, jota on kiusittu kutsumaan ryöstöksi."[^234] Erotus oli kyllä tarpeeksi todellinen, mutta koska veroja piti joka tapauksessa maksaa, sen täydelliseen eriyttämiseen ei palvellut muuta kuin morbidean uteliaisuuden tyydyttäminen. Kuten Lane totesi, riippumatta siitä, mikä osa veroista on ryöstöä, ne ovat hinta, jonka on maksettava "välttääkseen vakavampia tappioita."[^235]

### Tulojen nousu teollistumisen aikana

Osa syystä siihen, että tätä dilemmaa siedettiin kahden viime vuosisadan ajan kansallisvaltion hallituksen alla, oli se, että tulot nousivat dramaattisesti, erityisesti niillä lainkäyttöalueilla, joille suurin osa teollisesta kehityksestä rajoittui. OECD-hallituksia johtaneet tahot ottivat lähes joka vuosi suuremman osan tuloista. Ryöstön lisääntymisen rinnalla seurasi kuitenkin vielä suurempi vauraus sekä kasvava varallisuuden eriarvoisuus maailman muuhun osaan verrattuna. Tällaisissa olosuhteissa verotuksen lisääntymistä vastaan esitetyt vastalauseet olivat väistämättä marginaalisia eikä pystyneet estämään tapahtumien loogista etenemistä. Todellakin, kuten aiemmissa luvuissa on esitetty, teollistuvan kansallisvaltion sotilaallinen selviytyminen riippui pitkälti siitä, että sen kansalaisten resurssivaatimuksiin ei voitu asettaa tehokkaita rajoja.

Jokaisessa teollisessa valtiossa politiikat kulkivat suunnilleen samaan suuntaan. Toisen maailmansodan jälkeisen teollistumisen huipulla marginaalisten tuloverojen osuus nousi jopa 90 prosenttiin tai korkeammalle. Tämä oli paljon aggressiivisempi valtion oikeuden vaatia resursseja kuin edes varhaisten hydraulisten sivilisaatioiden itämaiset despotit olivat valmiita tekemään. Kuitenkin teollinen ryöstö seurasi omaa logiikkaansa. Suuri osa siitä määräytyi 1900-luvun ensimmäisen puoliskon teollisteknologian luonteen perusteella, kuten aiemmin kuvasimme.

Tämä teknologia teki lähes väistämättömäksi sen, että valtio takavarisi ja uudelleenjakoaisi suuren osan tuloista, jolloin suuri osa ryöstön taakasta kohdistuisi pieneen joukkoon kapitalisteja. Suurin osa teollisista prosesseista oli vahvasti riippuvaisia luonnonvaroista ja siten sidottuja niiden sijaintipaikkoihin. Terästehtaan, kaivoksen tai sataman siirtäminen oli mahdollista vain valtavin kustannuksin tai ei ollenkaan. Tällaiset laitokset olivat siksi pysyviä kohteita, joita oli helppo verottaa. Omaisuus-, yritys- ja eroamisverot kasvoivat jyrkästi tämän vuosisadan aikana. Myös tuloverot nousivat ensin kapitalisteilta, mutta lopulta myös työntekijöiltä itseltään. Suurten teollisuusyritysten synty teki laajasta tuloverosta käytännöllisen: palkkoja voitiin peritä suoraan lähteestä, kun veroviranomaiset koordinoivat perinnän teollisuusyritysten kirjanpito-osastojen kanssa. Otamme tämän nykyään itsestäänselvyytenä, mutta verojen kerääminen tehdasporteilla oli paljon yksinkertaisempaa kuin maaseudulle liikkuminen puristamaan osia miljoonien itsenäisten käsityöläisten ja maanviljelijöiden voitoista.

Yhteenvetona teollisteknologia vaikutti siten, että verotus muotoutui rutiininomaisemmaksi, ennustettavammaksi ja vähemmän henkilökohtaisesti vaaralliseksi kuin monina aikaisemmissa ajanjaksoissa. Siitä huolimatta se otti suhteessa enemmän yhteiskunnan resursseista kuin mikään aiempi suvereniteetin muoto.

### Mitä suojellaan?

Se, että yhteiskunnat pystyivät rikastumaan samalla kun verojen kokonaisosuus tuloista nousi merkittävästi, herättää kysymyksen siitä, millaista suojaa hallitukset tarjosivat teollisille talouksille. Mitä ne suojasivat? Vastaus: ennen kaikkea teollisuustiloja, joiden pääomakustannukset olivat korkeat ja jotka olivat merkittävästi alttiita hyökkäyksille. Suurten teollisuusyritysten olemassaolo ei olisi ollut mahdollista epäjärjestyksessä, jossa kilpailullinen väkivalta olisi ollut kovaakin – vaikka kilpailun tuloksena olisi ollut hallituksen ottaman tuotannon osuudesta supistuminen.

Juuri tästä syystä pääomavaltaiset toiminnot ovat taloudellisesti kannattamattomia sekä yhdysvaltalaisissa slumeissa että kolmannen maailman yhteiskunnissa, joissa tilannekohtaista väkivaltaa esiintyy runsaasti. Teollinen yhteiskunta kokonaisuudessaan pystyi etenemään, koska tietynlainen järjestys saatiin perustettua ja ylläpidettyä. Yrityksiä kohdattiin säännöllisten, ennakoitavissa olevien kiristysyritysten uhrina, eikä niitä rikkoinut satunnainen väkivalta.

Jopa teollisuuden huipulla oli aina liioiteltua puhua hallituksesta, joka käyttäisi "voimamonopolia". Kaikki hallitukset pyrkivät ylläpitämään tällaista monopolia, mutta kuten olemme nähneet, teollisuusyritysten työntekijät havaitsivat usein pystyvänsä käyttämään väkivaltaa työnantajiaan vastaan. Niin kauan kuin yleisöllä on edes jonkin verran aseita käytössään tai häiriintynyt väkijoukko pystyy fyysisesti kaatamaan linja-auton tai heittämään kiviä poliisille, hallintaan päässeet eivät täysin monopolioi voimaa. He hallitsevat ainoastaan ylivoimaista voimaa siinä määrin, että useimmille on taloudellisesti kannattamatonta kilpailla heidän kanssaan nykyisissä olosuhteissa.

> Verkkoon perustuva hallitus voi toimia vain kansalaisten suostumuksella. Siksi minkä tahansa verkkohallituksen on tarjottava kansalaisilleen todellisia etuja, jos se haluaa heidän pysyvänsä mukana. Nämä edut eivät välttämättä ole pelkästään henkilökohtaisia hyödykkeitä tai palveluita, vaan laajemman sääntelyjärjestelmän tuomia etuja: puhdas, läpinäkyvä markkinapaikka, jossa on selkeät säännöt ja seuraamukset, tai valvottu yhteisö, jossa lapset voivat luottaa tapaamiinsa ihmisiin, koska yksityisyys on suojattu.[^236]: - *Esther Dyson*

### Tietoaika

Tietoaika tuo mukanaan viidennen vaiheen kilpailun kehityksessä väkivallan käytössä lännessä. Lane ei ennakoinut tätä vaihetta. Tämä viides vaihe käsittää kilpailun kyberavaruudessa, areenalla, jota mikään "väkivaltaa käyttävä yritys" ei voi monopolisoida. Se ei ole monopolisoitavissa, koska se ei ole alueellisesti rajattu.

Vaikka Lainen argumentti sisältää tavanomaiset sodanjälkeiset oletukset kansallisvaltion väistämättömyydestä, hän huomasi seikan, joka tulee olemaan ratkaisevampi tulevaisuuden ymmärtämisessä kuin se olisi saattanut näyttää neljäkymmentä tai viisikymmentä vuotta sitten. Se on se, että hallitukset eivät ole koskaan pystyneet luomaan vakaita pakottamisen monopoleja avoimella merellä. Mieti sitä: kenenkään hallituksen lait eivät ole koskaan koskeneet yksinomaan sitä aluetta. Tämä on äärimmäisen tärkeää ymmärtää, kun tarkastellaan, miten väkivallan ja suojelun järjestäytyminen kehittyy talouden siirtyessä kyberavaruuteen, jolla ei ole fyysistä olemassaoloa. Sillä samalla syillä, jotka Lane huomautti – nimittäin että mikään hallitus ei ole koskaan pystynyt monopolisoimaan meren väkivaltaa – on vielä epätodennäköisempää, että hallitus voisi menestyksellisesti monopolisoida äärettömän, fyysisten rajojen puuttuvan alueen.

## Kilpailu ilman anarkiaa

Aiemmin, kun olosuhteet estivät yksittäistä väkivallan käyttöön erikoistunutta toimijaa luomasta monopolia, seurauksena oli anarkiaa ja ryöstöä. Tietoyhteiskunta on kuitenkin muuttanut perusteellisesti ne teknologiset periaatteet, joiden alla väkivaltaa järjestetään. Toisin kuin menneisyydessä, jolloin suojelupääoman monopoloinnin puute tietyllä alueella johti korkeampiin sotilaskustannuksiin ja alhaisempaan taloudelliseen tuottoon, se, että hallitukset eivät voi monopolisoida kyberavaruutta, merkitsee itse asiassa matalampia sotilaskustannuksia ja korkeampia taloudellisia tuottoja. Tämä johtuu siitä, että tieto- ja viestintäteknologia luo uuden ulottuvuuden suojelulle. Ensimmäistä kertaa historiassa se mahdollistaa sellaisten omaisuuserien luomisen ja suojaamisen, jotka sijaitsevat täysin minkä tahansa yksittäisen hallituksen alueellisen väkivallan monopolista ulkopuolella.

> 'Maat, joissa poliittisen vallan ja hallinnon yksiköt ovat moninaiset, eikä keskitettyä, vakaata ja kiistämätöntä valvontakeskusta ole, joutuvat kehittämään omat toimintaratkaisunsa sellaisten rajojen aiheuttamien ongelmien ratkaisemiseksi.'[^237]: - REES DAVIES

### Vertaus rajaan

Kyberavaruus on yhdessä mielessä teknologisesti suojatun rajaseudun vastine, sellaisen alueen, jota keskiajalla esiintyi raja-alueilla. Aiemmin, kun lordien ja kuninkaiden vaikutusvalta oli heikko ja yhden tai useamman vaatimukset raja-alueella limittyivät, vallassa oli jotain kilpailullista hallintoa. Katsaus siihen, miten tällaiset rajaseudut toimivat, voisi antaa oivalluksia siitä, miten vastaavat rajalait tai niiden kaltaiset säännöt saattaisivat siirtyä kyberavaruuteen.

Andorra on säilynyt eräänlaisena fossiloituneena rajaseutuna Ranskan ja Espanjan välillä – megapoliittisten olosuhteiden artefaktina, jotka vaikeuttivat kumpaakin kuningaskuntaa hallitsemaan toisiaan kyseisellä kylmällä ja lähes tavoittamattomalla 190 neliömailan alueella Pyreneillä. Vuonna 1278 solmittiin sopimus, jolla jakautui Andorran suzeraanisuus paikallisten ranskalaisten ja espanjalaisten feodaaliherrien, Foixin ranskankreivin ja Urgelin espanjanpiispan, kesken. Kumpikin nimitti yhden kahdesta „viquieristä”, jotka käyttivät säästeliäästi Andorran hallinnon minimaalista valtaa, pääasiassa johtamalla pientä andorralaista militiää, nykyistä poliisivoimaa. Kreivin rooli on jo kauan sitten mennyt historiaan, ja nykyään Ranskan hallitus huolehtii hänen tehtävistään Pariisista käsin. Sen velvollisuuksiin kuuluu muun muassa vastaanottaa puolet Andorran vuotuisesta tributista – summa, joka on pienempi kuin yhden kuukauden vuokra halvassa asunnossa. Urgelin piispo saa edelleen oman osuutensa tributista aivan kuten hänen esi-isänsä tekivät keskiajalla.

Jaetun tributin viittaa siihen, että Andorrassa on ollut kaksi ”valvontaoikeudellista ja -vallan lähdettä” sen sijaan, että olisi ollut vain yksi. Andorralaisten siviilioikeudelliset valitukset on perinteisesti tehty joko Urgelin piispan korkeakoululle tai Pariisin cassation-tuomioistuimeen.

Andorran epäselvä asema johti siihen, että melkein mitään lakeja ei säädetty. Andorra on nauttinut lähes olemattomasta hallituksesta eikä verotusta ole ollut yli seitsemänsataa vuotta. Nykyään tämä saa sen vetovoimaisemmaksi veroparatiisina. Kuitenkin vielä sukupolvi sitten Andorra oli kuuluisasti köyhä. Aikoinaan tiheä metsäisyys oli vuosien saatossa hävinnyt asukkaiden pyrkiessä pysymään lämpiminä ankaroissa talvissa. Koko alue peittyy lumihankeen marraskuusta huhtikuuhun joka vuosi, ja jopa kesällä Andorra on niin kylmä, että viljelyä tapahtuu vain eteläisillä rinteillä. Jos tämä kuvaus vaikuttaa epämiellyttävältä, olet juuri oppinut sen menestyksen salaisuuden: Andorra selviytyi feodaalisena pesänä kansallisvaltion aikakaudella juuri siksi, että se oli syrjäinen ja käytännössä ilman varallisuutta.

Aikoinaan oli lukuisia keskiaikaisia rajaseutuja, joissa eri suvereniteetit sulautuivat toisiinsa. Näitä väkivaltaisia rajoja esiintyi vuosikymmenten tai joskus jopa vuosisatojen ajan Euroopan raja-alueilla, ja useimmat niistä olivat köyhiä. Kuten aiemmin mainitsimme, Irlannissa oli rajaseutuja kelttiläisen ja englantilaisen hallinnon välillä; Walesin ja Englannin, Skotlannin ja Englannin, Italian ja Ranskan, Ranskan ja Espanjan, Saksan ja Keski-Euroopan slaavilaisten rajaseutujen sekä kristillisten Espanjan kuningaskuntien ja islamilaisen Granadan välillä. Näiden rajaseutujen kohdalla kehittyivät erottuvat institutionaaliset ja oikeudelliset muodot, joiden on hyvin todennäköistä ilmestyä uudelleen seuraavana vuosituhannella.

Koska kahden auktoriteetin kilpailuasema oli heikko ja kumpikin oli heikko, hallitsijat käänsivät toisinaan puoleensa vapaaehtoisia alaisistaan asettumaan rajavyöhykkeille kasvattaakseen valtansa ulottuvuutta. Melkein itsestäänselvyytenä alaiset houkuteltiin muuttamaan rajavyöhykkeelle verovapauden avulla. Ottaen huomioon kilpailun herkät rajat, mikäli jompikumpi auktoriteetti rajavyöhykkeellä yrittäisi määrätä veroja, se vaikeuttaisi seuraajiensa toimeentuloa ja antaisi kaikille syyn kääntyä sen kilpailijan puolelle. Siksi rajavyöhykkeen asukkailla oli yleensä vapaus valita, kenen lakeja he noudattavat. Tämä valinta perustui kilpailevien auktoriteettien heikkouteen; kyse ei ollut ideologisesta eleestä.

Käytännön ongelmia kuitenkin ilmeni, jotka oli ratkaistava. Feodaaliaikana maayrittäjät, jotka omistivat kiinteistöjä nimellisen rajaviivan molemmin puolin, kohtasivat vakavan velvollisuuksien ristiriidan. Esimerkiksi Skotlannin ja Englannin rajalla toimiva herra, jolla oli omaisuutta molemmissa kuningaskunnissa, saattoi teoreettisesti joutua suorittamaan sotilaspalveluksen kummallekin osapuolelle sodan sattuessa. Tämän ristiriitaisen velvoitteen ratkaisemiseksi lähes jokainen feodaalihierarkian jäsen pystyi valitsemaan, kenen lakeja noudattaa oikeudellisen prosessin, nimeltään tunnustus, kautta.

Tietoteknologia luo vastaavat mahdollisuudet kilpailukykyiseen valintaan, kun taloudellisia aktiviteetteja sijoitetaan, mutta siinä on tärkeitä eroja. Yksi niistä on, että toisin kuin keskiaikaisten rajayhteiskuntien kohdalla, kyberavaruus tulee lopulta olemaan yksi taloudellisesti rikkaimmista alueista. Siksi se tulee todennäköisemmin laajenemaan sen sijaan, että se supistuisi. Harvat keskiaikaisen yhteiskunnan ydinalueen asukkaat olisivat halunneet muuttaa rajojen äärelle ilman vahvoja houkuttimia, usein uskonnollisten velvoitteiden mukana, koska tällaiset alueet olivat yleensä väkivaltaisia ja köyhiä. Siksi ne eivät toimineet magneetteina, jotka vetävät resursseja auktoriteettien hallinnasta – kyberavaruus tekee niin.

Toiseksi, uusi rajavyöhyke ei tule olemaan duopoli, mikä yleensä kannustaa kahden auktoriteetin väliseen salaliittoon tavoitellessaan kompromissia rajavaatimuksistaan. Keskiajalla tällaiset kompromissit eivät olleet tehokkaita kahdesta syystä: usein kilpailevien auktoriteettien välillä oli teräviä kulttuurieroja, ja vielä tärkeämpää, heiltä puuttui fyysinen kapasiteetti määrätä sovitusta ratkaisusta, sillä heidän sotilaallinen voimansa maassa oli riittämätön. Kansallisvaltion aikakaudella, jolloin kansalliset auktoriteetit pystyivät käyttämään riittävästi sotilaallista voimaa ratkaisujen asettamiseen, useimmat rajavyöhykkeet ja epäselvät rajat katosivat ja rajojen vakioinnista tuli normi. Tämä on vakaa ratkaisu, jos väkivallan duopolistit kohtaavat mahdollisuuden jakaa valtaansa yhtenäisillä alueilla. Kybertalouden taloudellisen toiminnan sijoittamisesta käyty kilpailu ei kuitenkaan käykään kahden auktoriteetin vaan satojen auktoriteettien välillä ympäri maailmaa. Aluevallioiden olisi lähes mahdotonta luoda tehokasta kartellia pitääkseen verokannat korkeina – sama syy, miksi salaliittoa monopolihintojen saavuttamiseksi markkinoilla, joissa on satoja kilpailijoita, ei kannata.

Näyttöä tästä on Seychelleillä, pienessä Intian valtameren maassa, joka on ottanut käyttöön uuden sijoituslain, jota Yhdysvaltain viranomaiset kuvailevat 'Welcome Criminals' -laiksi. Lain mukaan kuka tahansa, joka sijoittaa 10 miljoonaa dollaria Seychelleille, saa paitsi takuun suojasta luovutuksia vastaan, myös diplomaattisen passin. Vastoin Yhdysvaltain hallituksen väitteitä tarkoitetut edunsaajat eivät kuitenkaan ole huumekauppiaita, jotka ovat yleensä tärkeämpien hallitusten suojassa, vaan itsenäisiä yrittäjiä, jotka ovat ajautuneet poliittisesti epäsovinnaiksi. Seychelleillä lain ensimmäinen mahdollinen edunsaaja on valkoinen eteläafrikkalainen, joka rikastui kiertämällä entisen apartheid-asiatuksen taloudelliset pakotteet. Nyt hän kohtaa uuden eteläafrikkalaisen hallituksen taloudellisen koston uhan ja on valmis maksamaan Seychelleille suojasta.[^238]

Riippumatta yksittäistapauksen ansioista, esimerkki osoittaa, miksi hallitusten yritykset ylläpitää maassa suojelemiseen tarkoitettua kartellia ovat tuomittuja epäonnistumaan.

Toisin kuin keskiaikaisella rajalla, jossa kilpailu käytiin vain kahden viranomaisen välillä, kyberkaupan raja muodostuu sadoista oikeusalueista, ja lukumäärän odotetaan nousevan nopeasti tuhansiin.

Virtuaalisen yrityksen aikakaudella yksilöt valitsevat sijoittaa tulonhankintatoimintansa siihen oikeusalueeseen, joka tarjoaa parhaan palvelun alhaisimmilla kustannuksilla. Toisin sanoen suvereniteetti kaupallistuu. Toisin kuin keskiaikaiset rajayhteisöt, jotka useimmiten olivat köyhiä ja väkivaltaisia, kyberavaruus ei tule olemaan kumpikaan. Se kilpailu, johon tietotekniikka ajaa hallituksia osallistumaan, ei ole sotilaallista kilpailua, vaan kilpailua taloudellisen palvelun – aidon suojelun – laadussa ja hinnassa. Lyhyesti sanottuna hallitusten on annettava asiakkaille sitä, mitä he haluavat.

### Väkivallan vähentynyt hyödyllisyys

Tämä ei tietenkään tarkoita, että hallitukset luopuisivat väkivallan käyttämisestä – päinvastoin. Pikemminkin väkivallan vaikutusvalta heikkenee merkittävästi. Yksi mahdollinen hallitusten reaktio olisi tehostaa väkivallan käyttöä paikallisissa yhteyksissä kompensoidakseen sen globaalin merkityksen laskua. Mitä tahansa hallituksetkin tekevätkin, ne eivät kykene kyllästämään kyberavaruutta väkivallalla samalla tavalla kuin ne kyllästivät monopolisoimiensa alueiden maantieteellisiä tiloja väkivallalla modernissa maailmassa. Riippumatta siitä, kuinka monta hallitusta yrittää tunkeutua kyberavaruuteen, ne eivät tule olemaan siinä siellä kypsempiä tai vaikutusvaltaisempia kuin kukaan muu.

Ironisesti kansallisvaltioiden yritykset käydä "tietosotia" hallitakseen tai estääkseen pääsyn kyberavaruuteen nopeuttaisivat todennäköisesti vain niiden omaa tuhoa. Suurten järjestelmien rappeutumisen taipumus on jo voimakas, johtuen mittakaavaetujen katoamisesta ja siihen liittyvistä kasvavista kustannuksista, jotka syntyvät rikkoutuvien sosiaalisten ryhmien koossa pitämisestä. Tietosotien ironia on siinä, että ne saattavat aiheuttaa teollisen aikakauden hauraiden järjestelmien kohdalla paljon iskun, jopa enemmän kuin nousevan tietotalouden itsessään.

Niin kauan kuin olennaiset tietotekniikan järjestelmät jatkavat toimintaansa, kyberkauppa voi edetä rinnakkain tietosotien kamppailujen kanssa tavalla, jota alueellisessa sodassa ei koskaan voisi tapahtua. Et voisi kuvitella miljoonien kaupallisten transaktioiden tapahtuvan etulinjassa yhdessä 1900-luvun sodassa. Virtuaaliset sodat eivät myöskään kuluta kyberavaruuden kapasiteettia useiden toimintojen isännöimiseksi, ja koska virtuaalista todellisuutta ei ole olemassa, lähellä olemisen vaaraa on vähän – eikä räjähtelevän virtuaalirähinän osuminen ole käytännössä mahdollista.

### Suurten järjestelmien haavoittuvuus

Tietosotien vaarat kohdistuvat enimmäkseen suuriin teollisiin järjestelmiin, jotka toimivat keskitetyn komennon ja hallinnan alaisuudessa. Yhdysvaltojen ja muiden johtavien kansallisvaltioiden sotilaalliset viranomaiset suunnittelevat ja pelkäävät tietosabotageja, joilla voisi olla vakavia seurauksia suurten järjestelmien toimintakyvyn lamaannuttamiseen. Kyberhyökkäys voisi sulkea puhelinvaihdesataman, häiritä ilmatilihoitoa tai sabotoida pumppujärjestelmää, joka säätelee veden virtausta kaupunkiin. Ohjelmoitu virus saattaisi jopa sammuttaa perinteisiä tai ydinvoimaloita, katkaista osia sähköverkosta. Näennäisesti "logiikkapommit" voisivat sotkea valtavan määrän tietoa, josta herkin on keskitettyjä hallintajärjestelmiä, jotka ohjaavat teollisen aikakauden perintönä säilyneitä haavoittuvia, suuria järjestelmiä. Paitsi jos kaikki tietotekniikka tuhoutuisi massiivisesti ja kattavasti – mikä pysäyttäisi maailman talouden – kyberkauppa ja virtuaalitodellisuus pysyvät hallituksen kyvyn ulottumattomissa tukahduttaa, saati monopolisoida.

Jopa yksi tietotekniikan heikkouksista – ilmeinen tietovarastojärjestelmien altistuminen rappeutumiselle ja tuhoutumiselle – on suurelta osin ratkaistu uuden arkistointiteknologian avulla. Uusi järjestelmä, nimeltään "High-Density read-only Memory" eli "HD-ROM", hyödyntää tietokoneavusteisissa valmistusjärjestelmissä käytettyjä ionimyllyjä arkistojen luomiseksi tyhjiössä. Tallennuskapasiteetti on nyt jopa 25 000 megatavua neliötuumaa kohden. Toisin kuin aiemmat järjestelmät, jotka olivat alttiita varhaiselle rappeutumiselle ja iskuille, HD-ROMiin tallennettu data lupaa säilyä pitkään. Yksi HD-ROMin kehittäjistä, Bruce Lamartine, toteaa: 'Se on käytännössä tunkeutumaton ajan kulutusta, lämpö- ja mekaanisia iskuja tai elektromagneettisia kenttiä vastaan, jotka ovat niin tuhoisia muihin tallennusvälineisiin nähden.'[^239] – Jopa ydinterroristien räjähdyksen seurauksena elintärkeää tietoa, kuten digirahan koodeja, ei välttämättä sotkeudu tai tuhoudu, vaikka kybertalouden sujuva toiminta olisi siihen riippuvainen.

> "Modernit armeijat ovat niin riippuvaisia tiedosta, että niitä voidaan sokaista ja kuulostaa voiton saavuttamiseksi ilman perinteistä taistelua."[^240]: - COL. ALAN CAMPEN, *U.S.A.F* (Ret.)

## Superpowers of virtual warfare

Sotaa käyvien valtioiden oletukset menettävät yhä enemmän megapoliittista järkevyyttään sitä mukaa, kun sodankäynnin tiedon merkitys kasvaa. Koska kyberavaruudella ei ole fyysistä olemassaoloa, se ei ole alue, jolla fyysisessä maailmassa tunnetut suuruusluokat kantaisivat määräävää merkitystä. Ei ole väliä, kuinka monta ohjelmoijaa osallistui käskyjärjestyksen määrittelyyn – ainoa ratkaiseva tekijä on se, toimiiko ohjelma. Itsehallitseva yksilö voi todellakin merkitä yhtä paljon kyberavaruudessa kuin valtio, jolla on paikka *YK:ssa*, oma lippu ja maassa sijoitettu armeija. Pelkästään taloudellisesta näkökulmasta jotkut itsehallitsevat yksilöt hallitsevat sijoitettavissa olevia tuloja satojen miljoonien dollareiden vuosimäärässä, summia, jotka ylittävät joidenkin konkurssiin ajautuneiden valtioiden omaehtoisen kulutusvallan. Mutta siinä ei ole kaikki. Virtuaalisessa sodankäynnissä, jota käydään tiedon manipuloinnin kautta, jotkut yksilöt saattavat nousta yhtä suureksi tai jopa suuremmaksi kuin monet maailman valtiot. Yksi outo nero, joka työskentelee digitaalisten palvelijoiden kanssa, voisi teoreettisesti saavuttaa saman vaikutuksen kybersodassa kuin valtio. *Bill Gates* todennäköisesti voisi.

Tässä mielessä itsenäisen yksilön aikakausi ei ole vain iskulause. Hakkeri tai pieni joukko matemaatikkoja – puhumattakaan yrityksestä kuten *Microsoft* tai melkein mistä tahansa tietokoneohjelmistoyrityksestä – voisi periaatteessa tehdä mitä tahansa tai kaikkia niitä asioita, jotka *Pentagon's Cyber War Task Force*:lla on hihassaan. Silicon Valleyn ja muualla on satoja yrityksiä, joilla on jo suurempi kyky käydä kybersotaa kuin 90 prosentilla nykyisistä valtioista.

Oletus siitä, että hallitukset jatkavat maan päällä tapahtuvan elämän monopolisointia, kun vaihtoehtoisia suojan tarjoamisen kanavia aukeaa kaikkialta, on anakronismi. Todennäköisempi lopputulos on, että valtioita on uudelleen järjestettävä niiden alttiuden vähentämiseksi tietokoneviruksille, logiikkapoileille, infektoituneille johdoille ja ansalaukoille tarkoitetuille ohjelmille, joita *U.S. National Security Agency* tai joku teinihakkeri voisi valvoa.

Cyberspace:n megapoliittinen logiikka viittaa siihen, että maailman laajamittaista infrastruktuuria tällä hetkellä hallitsevat keskitetyt komentokeskukset on korvattava monikeskuksisilla turvallisuusmalleilla, joissa on hajautetut kyvyt, jotta niitä ei voi helposti siepata tai estää tietokoneviruksen toimesta. Uusia ohjelmistotyyppejä, joita kutsutaan agorisiksi avoimiksi järjestelmiksi, tulee korvaamaan teollisaikana peritty kommentoimista ja -ohjausta toteuttava ohjelmisto. Vanha ohjelmisto jakoi laskentatehon jäykien prioriteettien mukaisesti samalla tavoin kuin entisen Neuvostoliiton Gosplanin keskussuunnittelijat jakoivat tavaraa rataratojen kuljetusvaunuihin tiukkojen sääntöjen mukaan. Uusia järjestelmiä hallitsevat algoritmit, jotka jäljittelevät markkinamekanismeja jakaen resursseja tehokkaammin sisäisen huutoprosessin kautta, joka muistuttaa aivojen kilpailuprosesseja. Sen sijaan, että jättimäiset tietokonemonopolit suorittaisivat tärkeitä komentokeskus-tehtäviä, nämä toiminnot hajautetaan uudella vuosituhannella.

Ei ole parempaa esimerkkiä hajautettujen verkostojen kestävyydestä verrattuna keskitettyihin komentokeskuksiin kuin Digital Equipmentin esimerkki sen Palo Alton tutkimuslaboratoriossa. Eräs insinööri avasi oven kaappiin, joka isännöi yhtiön omaa tietoverkkoa. Kevin Kellyn mukaan insinööri dramaattisesti „rypisti kaapelin sen sisuksista. Verkko reititti ympärilleen rikkomuksen eikä horjunut hetkeäkään.”[^241]:

Informaatiokausi ei ainoastaan helpota kilpailua kyberavaruudessa ilman anarkiaa, vaan se johtaa väistämättä teollisaikaisten jäänteiden, kuten koulujen ja yliopistojen kaltaisten instituutioiden uudelleenjärjestelyyn. Tällainen uudelleenkonfigurointi on välttämätöntä, jotta järjestelmät olisivat vähemmän alttiita ilkivallalle, joka voi kohdistua keneltä tahansa missä tahansa. Juuri kuten teollisaika johti keskiajalta perittyjen instituutioiden uudelleenjärjestelyyn, niin teollisaikaa jäljelle jääneet laitokset saattavat rapautua pienoismuodossa tavoilla, jotka heijastavat mikroteknologian logiikkaa.

Tarve suojautua tietoliikenneväylällä liikkuvilta rosvoilta edellyttää laajamittaista julkisen ja yksityisen avaimen salausalgoritmien käyttöönottoa. Nämä algoritmit mahdollistavat jo nyt sen, että mikä tahansa henkilö voi omalla tietokoneellaan salata viestin huomattavasti turvallisemmin kuin Pentagon olisi sukupolvi sitten voinut sulkea laukaisukoodinsa. Nämä tehokkaat, murtamattomat salauksen muodot tulevat olemaan välttämättömiä rahoitustapahtumien suojaamiseksi hakkereilta ja varkailta.

Ne tulevat olemaan tarpeellisia myös muusta syystä. Yksityiset rahoituslaitokset ja keskuspankit tulevat omaksumaan murtamattomat salausalgoritmit, kun ne huomaavat, että Yhdysvaltain hallituksella – eikä se välttämättä ole yksin – on kyky murtaa nykyiset pankkiohjelmistot ja tietojärjestelmät niin, että ne kirjaimellisesti joutuvat bankrotiksi tai että kenen tahansa pankkitili tyhjennetään lähes mistä tahansa. Ei ole teknologista syytä, miksi yksittäinen henkilö tai mikään maa jättäisi talletuksensa tai rahansiirtonsa Yhdysvaltain National Security Agencyn, KGB:n seuraajien tai minkä tahansa vastaavan, laillisen tai laittoman, järjestön armojen varaan.

Hallitusten läpäisemättömät salausalgoritmit eivät ole vain unelmointia. Ne ovat jo saatavilla shareware-versiona Internetissä. Kun matalalla kiertoradalla toimivat satelliittijärjestelmät ovat täysin käyttövalmiita, edistyneitä henkilökohtaisia tietokoneita käyttävät yksilöt, joiden antennit ovat kooltaan eivät suurempia kuin kannettavissa puhelimissa, pystyvät kommunikoimaan missä tahansa maapallolla ilman tarvetta käyttää puhelinverkkoa. Hallituksella ei ole aiempaa mahdollisuutta monopolisoida kyberavaruutta – aluetta, jolla ei ole lainkaan fyysistä olemassaoloa – kuin keskiaikaisilla ritareilla olisi ollut valta hallita teollisuusajan raskaalla ratsuvälineellä tehtyjä kauppatapahtumia.

### Suojautuminen hiiviskelyllä

Tietoyhteiskunnat sijoittavat valtavia resursseja saalistuksen ulkopuolelle. Kun kyberavaruus yhä enemmän isännöi rahoitustapahtumia ja muita kaupankäynnin muotoja, siellä käytetyt resurssit ovat enemmän tai vähemmän immuuneja tavallisille ryöstöille ja varkauksille. Tällöin saalistajat eivät pysty hyödyntämään yhtä suurta osaa resursseista kuin he tekevät nykyään ja ovat tehneet 1900-luvun suurimman osan aikana.

Välttämättä hallituksen suojaus suuren osan maailman varallisuudesta muuttuu tarpeettomaksi. Hallituksella ei ole parempaa asemaa suojella pankkitiliä kyberavaruudessa kuin sinulla itselläsi. Koska hallitusta tarvitaan vähemmän, sen suhteellinen hinta laskee todennäköisesti tämän seurauksena yksinään. Muita vaikutustekijöitäkin on.

Uuden vuosituhannen aikana, kun merkittävä ja kasvava osa rahoitustapahtumista tapahtuu kyberavaruudessa, yksilöillä on mahdollisuus valita, mihin lainkäyttöalueeseen ne rekisteröidään. Tämä luo intensiivistä kilpailua hallituksen palveluiden (eli perittävien verojen) hinnoittelusta ei-monopolistisella pohjalla. Tämä on vallankumouksellista. Kuten George Melloan väitti *The Wall Street Journalissa*, ainoa instituutio, joka on onnistunut parhaiten vastustamaan maailmanlaajuista kilpailua, on hyvinvointivaltio. "Wharton Schoolin ja Australian National Universityn tutkijoiden tekemässä tutkimuksessa käsiteltiin tulojen siirtoihin kohdistuvia voimia. Geoffrey Garrett ja Deborah Mitchell päättelivät, että 'käytännössä ei ole todisteita siitä, että lisääntynyt markkinaintegraatio olisi asettanut laskupaineita heidän perustavanlaatuisimmille hyvinvointiohjelmilleen.' Päinvastoin, he kirjoittavat, 'hallitukset ovat aina vastanneet kansainvälisille markkinoille integroitumisen lisääntymiseen kasvattamalla tulojen siirtoja.'[^242] Kybertalouden aika tuo vihdoin hyvinvointivaltion alttiiksi aidoille kilpailuasetelmille. Se muuttaa suvereniteettien luonnetta ja muuttaa talouksia, sillä suojelun ja kiristyksen tasapaino kallistuu entistä voimakkaammin suojelun puolelle kuin koskaan ennen.

[^187]: Neil Munro, 'Pentagonin uusi painajainen: elektroninen Pearl Harbor,' *Washington Post*, 16. heinäkuuta 1995, s. C3.

[^188]: Thomas Hobbes, Leviathan, luku 13 'Ihmisen luonnollinen tila koskien heidän onnellisuuttaan ja kurjuuttaan.'

[^189]: Thomas Schelling, *Arms and Influence* (New Haven: Yale University Press, 1966).

[^190]: Kevin Kelly, *Out of Control: The New Biology of Machines, Social Systems, and the Economic World* (Reading, Mass.: Addison-Wesley, 1995), sivut 45–46.

[^191]: Ibid., sivut 2–4.

[^192]: Ibid., s. 4.

[^193]: Heinz Pagels, The Dreams ofReason (New York: Bantam Books, 1989), lainattuna Roger Lewinin teoksesta Complexity: Life at the Edge of Chaos (New York: Macmillan, I992), s. 10.

[^194]: Lane, 'Economic Consequences of Organized Violence,' op. cit, s. 402.

[^195]: Frederic C. Lane, 'The Economic Meaning of War and Protection,' teoksessa Venice and History: The Collected Papers of Frederic C. Lane (Baltimore: The Johns Hopkins Press, 1966), ss. 383–84.

[^196]: Shi Mai'an ja Lao Guanzhong, Outlaws of the Marsh, kääntänyt Sidney Shapiro (Bloomington: Indiana University Press, 1981), s. 12.

[^197]: George E Will, 'Farewell to Welfare States,' *Washington Post*, December 17, 1995, s. C7.

[^198]: Robert S. MeElvaine, *The Great Depression: America, 1929-1941* (New York: Times Books, 1984), s. 292.

[^199]: Ibid., s. 293.

[^200]: Smith, op. cit., s. 75.

[^201]: Ibid., s. 76.

[^202]: Ibid.

[^203]: Yksi ensimmäisistä järjestäytyneistä argentiinalaisista liitoista oli rautatieliitto vuonna 1887. Katso Carmelo Mesa-Lago, *Social Security in Latin America: Pressure Groups, Stratification, and Inequality* (Pittsburgh: University of Pittsburgh Press, 1978), s. 161.

[^204]: Lisätietoja C&O-kanavan suunnittelusta ja rakentamisesta löytyy teoksesta Robert J. Brugger, *Maryland: A Middle Temperament 1634-1980* (Baltimore: The Johns Hopkins Press, 1990), s. 202–203f.

[^205]: Irving J. Sloan, *Our Violent Past: An American Chronicle* (New York: Random House, 1970), s. 177

[^206]: Lisätietoja vuoden 1877 rautatieriitojen väkivallasta on saatavilla ibid. sekä Bruggerin op. cit., s. 341–344.

[^207]: Sloan, op. cit., s.202. Katso myös S. S. Boynton, 'Miners' Vengeance,' *Overland Monthly*, vol. 22 (1893), s. 303–7

[^208]: Benjamin Schwartz, 'American Inequality: Its History and Scary Future,' *New York Times*, 19. joulukuuta 1995, s. A25

[^209]: MeElvaine, op. cit., s.293

[^210]: Ibid.

[^211]: Ibid.

[^212]: Henry C. Simons, 'Some Reflections on Syndicalism,' *Journal of Political Economy* maaliskuu 1944, s. 22.

[^213]: Kelly, op. cit., s. 191–92.

[^214]: Gayle Ni. Hanson, 'A Riveting Account of 'Life' in Postmodernist Cyberspace,' *Washington Times*, 24. joulukuuta 1995, s. B7.

[^215]: Tiivis johdanto anarkian akateemiseen tutkimukseen löytyy teoksesta Gordon Tullock (toim.), *Explorations in the Theory of Anarchy* (Blacksburg, Va.: Virginia Polytechnic Institute and State University, 1972). Katso myös Murray N. Rothbard, *Power and Market.. Government and the Economy* (Menlo Park, Calif., 1970); sekä Robert Nozick, *Anarchy, State and Utopia* (New York: Basic Books, 1974).

[^216]: Katso Pierre Clastres, *Society Against the State: The Leader as Servant and the Humane Uses of Power Among the Indians of the Americas* (New York: Urizen Books, 1977); sekä Jones, op. cit.

[^217]: Lane, *Economic Consequences of Organized Violence*, op. cit., s. 403.

[^218]: Charles Tilly, *War Making and State Making as Organized Crime*, teoksessa Peter B. Evans, Dietrich Rueschemeyer ja Theda Skocpol, Bringing the State Back In (Cambridge: Cambridge University Press, 1985), s. 169.

[^219]: Ibid.

[^220]: Lane, *Economic Consequences of Organized Violence*, op. cit., s. 402.

[^221]: David J. Elkins, Beyond Sovereignty: Territory and Political Economy in the Twenty-First Century. Toronto: University of Toronto Press, 1995, ss. 13–14.

[^222]: Ibid., s. 29

[^223]: Jim Taylor ja Watts Wacker, The 500-Year Delta: What Happens After What Comes Next. New York: *HarperCollins*, 1997, s. 40.

[^224]: Ibid., s. 67

[^225]: Ibid., ss. 41–42

[^226]: George Gilder, 'Fiber Keeps Its Promise: Get Ready. Bandwidth Will Triple Each Year for the Next 25, Creating Trillions in New Wealth.' *Forbes ASAP*, 7. huhtikuuta 1997

[^227]: Katso Neal Stephenson, *Snow Crash*. New York: *Bantam Books*, 1993

[^228]: Keith B. Richburg, 'Two Years After U.S. Landing in Somalia, It's Back to Chaos,' *Washington Post*, 4. joulukuuta 1994, s. Al.

[^229]: Viitattu teoksessa Tilly, Coercion, Capital and European States, op. cit., s. 85.

[^230]: Lane, 'Economic Consequences of Organized Violence,' op. cit., s. 411.

[^231]: Ibid.

[^232]: Sama.

[^233]: Sama, s.412.

[^234]: Sama, s.403.

[^235]: Sama, s.404.

[^236]: Esther Dyson, Release 2.1: A Design for Living in the Digital Age. New York: Broadway Books, 1998, s. 131

[^237]: Rees Davies, 'Frontier Arrangements in Fragmented Societies: Ireland and Wales,' teoksessa Robert Bartlett ja Angus MacKay (toim.), *Medieval Frontier Societies* (Oxford: Oxford University Press, 1992), s. 80.

[^238]: Katso Thomas W. Lippman, 'Seychelles Offers Investors Safe Haven for $10 Million,' *Washington Post*, 31. joulukuuta 1995, s. A27.

[^239]: Katso 'ROM of Ages,' *Wired*, tammikuu 1996, s. 52.

[^240]: Lainattu James Adamsin teoksesta, 'Dawn of the Cyber Soldiers,' *The Sunday Times* (London), 15. lokakuuta 1995, s. 3–5.

[^241]: Kelly, op. cit., s. 19.

[^242]: George Melloan, 'Welfare State Reform Is Mostly Mythological,' *The Wall Street Journal*. 14. lokakuuta 1996, s. A19.

[^243]: Katso luvusta 8 kirjasta *The Great Reckoning*, 'Linear Expectations in a Nonlinear World: How the Telescope Led Us to Compute; how the Computer Can Help Us to See.'

[^244]: Huomaa, että Lanen neljä väkivallan käytön kilpailun ja monopolin vaihetta ovat erilaiset kuin ne neljä vaihetta, jotka määrittelemme taloudellisen elämän järjestäytymiseksi – nimittäin keräily, maanviljelys, teollisuus ja tietoaika.