# Paikallisuuden ylittäminen

:::{.content-hidden when-format=latex}

*Kyberekonomian nousu*

:::

> 'Todellinen ongelma on kontrolli. Internet on liian laajalle levinnyt, jotta yksittäinen hallitus voisi sitä helposti hallita. Luomalla saumattoman, globaalin talousvyöhykkeen – anti-suverenin ja sääntelemättömän – Internet kyseenalaistaa kansallisvaltion peruskäsityksen.'[^245] - JOHN PERRY BARLOW

Tietoyhteystie, jota monet kutsuvat "Information Superhighwayksi", on muodostunut yhdeksi digiajan alkuvaiheiden tuttuimmista metaforoista. Se on merkittävä paitsi sen kaikkialla läsnäolon vuoksi, myös siksi, että se paljastaa laajalti levinnyttä väärinkäsitystä kyberekonomiasta. Tie on loppujen lopuksi teollistettu versio jalkakäytävästä – verkosto fyysistä liikkumista varten, jolloin kuljetetaan ihmisiä ja tavaroita. Tietotalous ei kuitenkaan ole kuin tie, rautatie tai putkisto. Se ei kuljeta tai siirrä tietoa pisteestä toiseen samalla tavalla kuin *Trans-Canada Highway* kuljettaa raskaita kuorma-autoja Albertasta New Brunswickiin. Sitä, mitä maailma kutsuu "Information Superhighwayksi", ei pidetä ainoastaan kuljetusreittinä – se on itse päämäärä.

Kyberavaruus ylittää paikallisuuden rajat. Se tarkoittaa käytännössä välitöntä datan jakamista kaikkialla ja ei missään samanaikaisesti. Nouseva tietotalous perustuu miljoonia tietokoneita käyttävien miljoonien käyttäjien välisiin yhteyksiin ja niiden jatkuvaan uudelleenjärjestelyyn. Sen ydin piilee uusissa mahdollisuuksissa, jotka näistä yhteyksistä syntyvät. Kuten John Perry Barlow totesi, 'Mitä netti tarjoaa on lupaus uudesta sosiaalisesta tilasta, globaalista ja anti-suverenista, jossa kuka tahansa, missä tahansa, voi ilmaista muulle ihmisyydelle sen, mitä hän uskoo, ilman pelkoa. Näissä uusissa medioissa on ennakkoisolmua älyllisestä ja taloudellisesta vapaudesta, joka saattaisi kumota kaikki maan autoritaariset vallat.'[^246]

Kyberavaruus, aivan kuten Homeroksen jumalien mielikuvitusmaailma, on omaa luokkaansa erillään tutusta maatilojen ja tehtaan maailmasta. Sen seuraukset eivät kuitenkaan tule olemaan vain mielikuvituksellisia, vaan ne ovat todellisia. Paljolti enemmän kuin monet nykyään ymmärtävät, tiedon välitön jakaminen on kuin liuotin, joka liuottaa suuria instituutioita. Se ei pelkästään muuta väkivallan logiikkaa, kuten olemme jo tutkineet, vaan muuttaa radikaalisti myös tiedon ja transaktiokustannusten rakenteita, jotka määrittävät, miten yritykset organisoituvat ja miten talous toimii. Odotamme, että mikrokäsittely muuttaa maailman taloudellisen järjestäytymisen.

> 'Nykyään on mahdollista, painuvaisemmin kuin koskaan aiemmin maailmankirjan historiassa, että yritys sijoittuisi mihin tahansa, käyttäisi resursseja mistä tahansa ja tuottaisi tuotteen, joka voidaan myydä missä tahansa.' - *MILTON FRIEDMAN*

## The tyranny of place

Se, että hiipuvan teollisuusajan ensimmäinen yritys mielessämme hahmottaa informaatiotaloutta valtavana julkisena rakennushankkeena, kertoo kuinka syvästi ajattelumme juurtuu menneiden aikojen paradigmoihin. Se on kuin kuulisikin kahdeksantoista vuosisadan lopun maanviljelijöiden kuvailevan tehdasta "tilana, jossa on katto". Kuitenkin "supermoottoritien" metafora paljastaa vielä enemmän: se osoittaa, kuinka voimakkaasti olemme orjassa paikallisuuden tyrannian alle. Vaikka teknologia mahdollistaa paikkarajoitteiden ylittämisen, vapautuksemme välineelle annetaan lempinimi, joka kuvaa sitä reittinä paikasta toiseen. Aivan kuten lohet, joita ohjaa kotiintunnetta, tietoisuutemme on edelleen syvästi jäänneleimautunut paikallisuuden käsityksiin.

Koko tähänastisen historian ajan taloudet ovat olleet sidoksissa paikalliseen maantieteelliseen alueeseen. Suurin osa ennen 1900-lukua eläneistä ihmisistä vietti päivänsä käytännössä vangittuna kotiarestina, harvoin astuen muutaman päivän kävelymatkaa syntymäpaikastaan. Minkä tahansa matkan tekeminen vaati sukupolvien työpanosta. Vain satunnaisesti jokin kriisi, sota, rutto tai epäsuotuisan ilmaston muutos stimuloi laajamittaista muuttoliikettä. Ihmisten siirtäminen kurjasta kylästä vaati jotain spektaakkelia ja kiireellisyyttä – mitään vähempää ei kyennyt saamaan ihmisiä pakkaamaan tavaransa ja lähtemään etsimään parempaa elämää.

Vasta viime aikoihin asti ne harvat, jotka etsivät mahdollisuuksia oman asuinalueensa ulkopuolelta, usein nousivat kuuluisuuteen. Mieti vaikka, että Marco Polo on yhä tunnettu siitä, että hän kuljeskeli Euraasian mantereen halki vieraillakseen Suuren Khaanin hovissa. Hän oli aikalaisensa poikkeus. Harvat muut esiteollisilta ajoilta peräisin olevat matkakertomukset ovat säilyneet. Yksi laajasti luetuista on *Mandeville's Travels*, joka kirjoitettiin ranskaksi vuonna 1357 ja on merkittävä siksi, että sen on ilmeisesti koonnut joku, joka ei todennäköisesti koskaan poistunut Euroopasta. Mandeville esittää ihastuttavia ja usein mielikuvituksellisia yksityiskohtia elämästä ympäri maapalloa, mukaan lukien vihje siitä, että monilla etiopialaisilla on vain yksi jalka: '[J]alka on niin suuri, että se varjostaa koko ruumiin auringon alla, kun he makaavat ja lepäävät.'[^247] On selvää, että harvat Mandevillen aikalaiset, jotka lukivat hänen suositun tarinansa, todennäköisesti tiesivät, ettei hänen etiopialaisella "Isojalalla" ollut mitään todellisuuspohjaa.

Vasta uuden ajan alkaessa, kun 1400-luvun lopulla alkoivat tutkimusmatkat, mantereen väliset jatkuvat kontaktit käynnistyivät. Rohkeat kapteenit, kuten Christopher Columbus ja Vasco da Gama, jotka lähtivät valloittamaan mausteiden kauppaa, olivat niin poikkeuksellisia, että heidän muistonsa säilyi jokaisessa kirjallisessa kotitaloudessa lähes viiden vuosisadan ajan.

Maanviljelyn alkumisesta aina nykypäivään asti elämää leimasi liikkumattomuus. Tämä on lähes unohtunut nykyään, erityisesti "Uuden maailman" eurooppalaisten siirtokuntien osalta, joissa liikkuminen on joustavampaa ja jokainen tarkastelee asioita maahanmuuttajan näkökulmasta. Pohjois-Amerikan peruskoulussa korostetaan usein, että siirtokunnat tulivat Euroopasta etsimään vapautta ja mahdollisuuksia, mikä on totta. Sitä, mitä harvoin kerrotaan, on kuitenkin se, kuinka vastahakoisia useimmat ihmiset olivat matkustamaan, vaikka he joutuivatkin kotona elämään äärimmäisessä köyhyydessä. Vain kaikkein yritteliäimmät tai epätoivoisimmat köyhistä lähtevät muuttamaan. Seitsemästoista vuosisadan puolivälissä Londonin maineikkaassa rangaistuslaitoksessa Bridewellissa vangitut kapinoivat osoittaakseen "haluttomuuttaan lähteä Virginiaan."[^248] Vuonna 1720 Pariisin kaduilla purkautui mellakoita, kun vapautettiin harjottajia, varkaita ja murhaajia, jotka oli määrä ulosvientiin Louisianaan.

### Kapeat näkymät

Fyysiset kommunikaation ja kuljetuksen vaikeudet, joita useimmissa tilanteissa ja paikoissa pahensivat rajoittuneet kielitaitotaidot, pitivät ihmistoiminnan fokuksen kapeana ja paikallisena. Vielä 1900-luvun alussa oli yleistä löytää kiinalaisia kyliä, joiden välimatka oli vain noin kahdeksan kilometrin (noin viiden mailin) päässä toisistaan, mutta joissa puhuttiin keskenään täysin ymmärtämättömiä murteita, jopa rannikkoalueilla. Melkein kaikkien talouksien paikallinen organisointi aiheutti kapeiden markkinoiden ja menetettyjen mahdollisuuksien rangaistuksen. Tuotekustannukset pysyivät korkeina rajoitetun kilpailun vuoksi ja erikoistuneiden taitojen saatavuus oli minimaalista. Tulojen ollessa niin alhaisia, että ne raapivat juuri köyhyyden reunoja, eikä ulkopuolista pääomaa tai tehokkaita vakuutusmarkkinoita ollut saatavilla, pienviljelijät suurimmassa osassa maailmaa jäivät köyhyyden ansaan. Olemme tarkastelleet joitakin niitä vaikeuksia, joita suljetun kyläelämän rajoitukset asettivat maanviljelijöiden eteen. Jopa nyt, kun kirjoitamme tätä, vähintään miljardi ihmistä—enimmäkseen Aasiassa ja Afrikassa—kamppailee selviytyäkseen alle dollarin päivätuloilla.

## "kaikki politiikka on paikallista"

Enemmän kuin yleisesti ymmärretään, ihmisten ja heidän omaisuutensa liikkumattomuus on vaikuttanut siihen, miten näemme maailman. Jopa ne, jotka vaikuttavat olevan valmiita myöntämään, että maa on pieni paikka 1900-luvun loppuna, ajattelevat yhä vanhentuneiden teollispoliittisten käsitysten rajoissa. Tätä korostaa 1980-luvulla ympäristöaktivistien keskuudessa noussut iskulause: 'ajattele globaalisti, toimi paikallisesti.' Se on käsky, joka heijastaa politiikan logiikkaa – logiikkaa, joka on aina perustunut paikallisiin valtaetuuksiin.

Kaikki maantieteelliset piirteet, jotka toimivat vallankäytön esteinä tai helpottajina, ovat paikallisia. Jokainen joki, jokainen vuori, jokainen saari on paikallinen. Ilmasto on paikallinen. Lämpötila, sateet ja kasvuehdot vaihtelevat, kun kiipeät vuorelle ja sen yli. Jokainen mikrobikin kiertää jossain – eikä jossain muussa.

Ei ole ihme, että paikan tyrannia läpäisee käsityksemme siitä, miten yhteiskunnan tulee organisoidaan ja toimia. Ne valtaetuudet, jotka ovat antaneet yhdelle tai toiselle ryhmälle paikallisen yksinvaltaisen aseman väkivallan suhteen, ovat aina saaneet alkunsa jossain ja haihtuneet siellä, missä suurten poliittisten kokonaisuuksien rajat vedetään. Siksi maailmankuntaa ei ole koskaan syntynyt.

Vaikka paikan merkitystä vallankäytössä ei ole harvoin ilmaistu suoraan, jotkut ihmistoiminnan palkkioiden uudelleenjakoa kannattavat alkoivat jo 1930-luvulla aistia, että paikan vaikutusvalta on vähentymässä. He näkivät modernissa liikenteessä sosiaalisen tilan jakautumisen hyvin palkattujen ja köyhien välillä. Tätä pelkoa kuvaa John Dos Passos teoksessaan *The Big Money*:  
'The "vag" sits on the edge of the highway, broken, hungry. Overhead, flies a transcontinental plane filled with highly paid executives. The upper class has taken to the air, the lower class to the road: there is no longer any bond between them, they are two nations.'  

[^249]: Tämä on toinen tapa sanoa, että parantunut liikenne vähensi kiristyksen vaikutusvaltaa pelkästään lisäämällä niitä paikkoja, joista menestyvät ihmiset voivat valita olinpaikkansa. Todellakaan alle moottoritietä kulkevalla kulkijalla ei ollut mahdollisuutta vaatia lahjoitusta yläpuolella lentäviltä.

Ne taipumukset, joita Dos Passos havaitsi 60 vuotta sitten, ovat vain entistä selkeämpiä.

### Mass transit

Vuonna 1995 miljoona ihmistä ylitti jossain päin maailmaa rajoja joka päivä. Tämä on hämmästyttävä muutos menneisyyteen verrattuna. Ennen kaksikymmentäluokkaa matkustaminen oli niin harvinaista, että useimmat rajat olivat vain etupiirejä – eivät esteitä liikkumiselle. Passiakin ei ollut olemassa. Merenkulku-alusten, junien ja muiden kehittyneempien liikennevälineiden kehitys lisäsi liikkumista dramaattisesti. Tämä liikkuminen kuitenkin alkoi joutua tiukempaan valvontaan valtioiden toimesta, joiden valta kasvoi samoilla liikenne- ja viestintäteknologian parannuksilla, jotka tekivät siviilimatkustamisesta edullisempaa ja helpompaa. Myös elokuvien ja erityisesti television saapuminen auttoi merkittävästi horisonttien avaamisessa sekä matkustamisen ja maahanmuuton vauhdittamisessa. Siitä huolimatta sosiaalisen ja taloudellisen järjestäytymisen perusoletukset ovat tähän asti pysyneet tiiviisti paikallisessa kontekstissa.

> '... jotta välttäisimme sitä hermojen heikkoutta, josta historia vaatii armottomasti rangaistuksen. Meidän on uskaliaasti seurattava kaikkia teknisiä ekstrapolaatioita niiden loogiseen loppuun.'[^250]: - ARTHUR C. CLARKE

## The error of minimal expectations

Mielikuvituksen maantieteellinen kahle on yhä niin kireä, että jotkut vuonna 1995 Internetiä tarkastelleet asiantuntijat päättelivät sen omaavan vain vähän kaupallista potentiaalia ja lähes mitään merkitystä muuta kuin sähköisenä keskustelu- ja pornografia-alustana. Kyseenalaistajat, jotka epäilevät kyberavaruuden taloudellista tärkeyttä, ovat informaatiokauden koloneli Blimpsejä. Heidän itse tyydyksensä kilpailee 1930-luvun brittiläisen valtakunnan etuoikeuksien kanssa imperiumin laskua kohdatessa. Aina kun eliitit kokevat uhan, heidän ensireaktionsa on kieltäytyminen. Tämä käy ilmi siitä optimistisesta toivosta, että Internet ei koskaan muutu merkittäväksi – joskus jopa niiden viranomaisten taholta, joiden pitäisi tietää paremmin. Viittasimme aiemmin David Klinen ja Daniel Bursteinin teokseen *Road Warriors: Dreams and Nightmares Along the Information Highway*. Heidän aliarviointinsa Verkon taloudellisesta potentiaalista on jälleen yksi todiste siitä, että teknisesti perillä oleminen ei ole sama asia kuin teknologian seurausten ymmärtäminen.[^251]

Jopa menneisyyden teknisesti arvostetuimmat havainnoijat eivät usein onnistuneet ymmärtämään uusien teknologioiden vaikutuksia. Vuonna 1878 koolle kutsuttu brittiläinen parlamentaarinen valiokunta, joka tarkasteli Thomas Edisonin hehkulampun näkymiä, totesi Edisonin ideoiden olevan 'riittävän hyvät transatlanttisille ystävillemme, … mutta eivät ansaitse käytännöllisten tai tieteellisten miesten huomiota.'[^252]  
Thomas Edison itse oli suurten näkemysten mies, mutta hän ajatteli, että keksimäänsä fonografiaa käyttäisivät lähinnä liikemiehet diktaatiossa.

Vain lyhyen ajan ennen kuin Wrightin veljekset todistivat lentokoneiden kykenevän lentämään, arvovaltainen amerikkalainen tähtitieteilijä Simon Newcomb osoitti auktoriteettimaisesti, miksi ilma-aluksesta raskaampi lento oli mahdotonta. Hän totesi: 'Se, että mikään tunnetuista aineista, koneiden muodoista ja voimien muodoista ei voi yhdistyä käytännölliseksi koneeksi, joka mahdollistaisi miesten lentävän pitkiä matkoja ilmassa, vaikuttaa kirjoittajasta yhtä täydelliseltä kuin minkä tahansa fyysisen ilmiön todistaminen voi olla mahdollista.'[^253]

Heti lentokoneiden alkuaikojen jälkeen toinen kuuluisa tähtitieteilijä, William H. Pickering, selitti yleisölle, miksi kaupallinen matkustaminen ei koskaan pääse liikkeelle: 'Yleisessä mielessä kuvitellaan usein jättimäisiä lentokoneita, jotka ryntäävät Atlantin yli ja kuljettavat lukemattomia matkustajia tavalla, joka muistuttaa modernien höyryalusien toimintaa. … On selvää, että nykyisillä laitteillamme ei ole toivoa kilpailla vetorallinopeudessa kumpaankaan, joko höyryvetureihimme tai autoihimme.'[^254]

Olemme aiemmin maininneet toisen villin virheellisen ennustuksen uuden teknologian potentiaalista – 1900-luvun alussa Mercedesin valmistajien ennustuksen, että maailmassa ei koskaan olisi yli miljoonaa autoa. He tunsivat autoja paremmin kuin melkein kukaan muu, mutta heidän arvionsa autojen vaikutuksesta yhteiskuntaan eivät voisi olla osittain enää paikkansa pitäviä.

Tämän tietämättömien väärinkäsitysten perinteen valossa ei olekaan yllättävää, että monet havainnoijat jäävät jälkeen ymmärtämästä uuden tietotekniikan tärkeimpiä seurauksia – sitä, että se ylittää paikan sitomisen tyrannian. Uusi teknologia luo ensimmäistä kertaa äärettömän, ei-maallisen alueen taloudelliselle toiminnalle. Se avaa vaihtoehdon tutkia kyber-talouden uusia rajoja, 'ajatella globaalisti ja toimia globaalisti.' Tämä luku selittää miksi.

## Paikan ulkopuolella

Tiedon käsittely ja käyttö korvaavat nopeasti fyysiset tuotteet ja muuttavat niitä merkittäväksi voiton lähteeksi. Tämä aiheuttaa suuria seurauksia.  
Tietotekniikka irrottaa tulonhankintapotentiaalin minkään tietyn maantieteellisen sijainnin omistuksesta.  
Koska yhä suurempi osa tuotteiden ja palveluiden arvosta syntyy lisäämällä niihin ideoita ja tietoa, yhä pienempi osa lisäarvosta jää paikallisten toimivaltioiden vangiksi.  
Ideat voidaan muodostaa missä tahansa ja välittää globaalisti valon nopeudella.  
Tämä tarkoittaa väistämättä, että tietotalous on dramaattisesti erilainen kuin tehtaan aikakauden talous.

Myönnämme kriitikoille, että luettelo tehtävistä, joita olisit voinut tehdä Internetin kautta vuonna 1996, saattaa tuntua arkiselta.  
Lopulta netistä puutarha-aiheisen artikkelin lukeminen tai pitkän matkan päässä olevan viinikassin ostaminen ei ole mitään uskomattoman vallankumouksellista.  
Kuitenkin kyber-talouden potentiaalia ei voida arvioida pelkästään sen alkuvaiheen perusteella, aivan kuten autojen potentiaalia yhteiskunnan muuttajana ei olisi voitu arvioida sen perusteella, mitä ympärilläsi nähtiin vuonna 1900.  
Odotamme, että kyber-talous kehittyy useiden vaiheiden kautta.

1. Tietoyhteiskunnan primitiivisimmät ilmenemismuodot hyödyntävät verkkoa pelkästään tietovälineenä, joka helpottaa muuten tavallisia teollisuusaikakauden liiketoimia. Tässä vaiheessa verkko on enimmäkseen eksoottinen toimitusjärjestelmä luetteloille. Esimerkiksi *Virtual Vineyards*, yksi ensimmäisistä kyberskauppiaista, myy viiniä yksinkertaisesti verkkosivun kautta World Wide Webissä. Tällaiset liiketoimet eivät vielä suoraan horjuta vanhoja instituutioita. Ne käyttävät teollisuusaikakauden valuuttaa ja tapahtuvat tunnistettujen oikeudellisten alueiden puitteissa. Näillä internetin käyttötavoilla ei ole juuri lainkaan merkittävää poliittista vaikutusta.

2. Välivaiheessa internet-kaupankäynti hyödyntää informaatioteknologiaa tavoilla, jotka olisivat olleet mahdottomia teollisuusaikana, esimerkiksi etäkirjanpidossa tai lääketieteellisessä diagnosoinnissa. Alla esitellään lisää esimerkkejä näistä uusista, edistyneeniä laskentatehoa hyödyntävistä sovelluksista. Verkko-kaupan toinen vaihe toimii yhä vanhan institutionaalisen ympäristön puitteissa, käyttäen kansallisia valuuttoja ja alistuessaan valtioiden oikeudelliseen auktoriteettiin. Verkkoa myynnissä hyödyntävät kauppiaat eivät vielä käytä sitä voittojensa hoitamiseen, vaan ainoastaan tulojen ansaitsemiseen. Internet-liiketoiminnasta saadut voitot ovat edelleen veronalaisia.

3. Kehittyneemmässä vaiheessa siirrytään todelliseen kyberkauppaan. Liiketoimet eivät ainoastaan tapahdu verkon välityksellä, vaan ne alkavat muuttaa tapahtumapaikkaansa valtioiden oikeudellisten rajojen ulkopuolelle. Maksut suoritetaan kybervaluutassa, voitot kirjataan kyberpankeihin ja investoinnit tehdään kybervälittäjien kautta. Monet liiketoimet eivät ole veronalaisia. Tässä vaiheessa kyberkaupassa alkaa ilmetä merkittäviä suurimittakaavaisia poliittisia vaikutuksia, kuten aiemmin on jo kuvattu. Hallitusten perinteiset valtaoikeudet talouden aloilla muuttuvat verkon uuden logiikan myötä. Ylittävien lainkäyttöalueiden sääntelyvalta romahtaa, oikeudelliset alueet hajautuvat, yritysrakenteet muuttuvat ja samalla työelämän luonne sekä työllisyyskin muuttuvat. Tämä esitys tietoyhteiskunnan vallankumouksen vaiheista on vain pintaraapaisu siitä, mitä voisi olla laajimmin ulottuva taloudellinen muutos.

## Kaupankäynnin globalisaatio

Tietoyhteiskunnassa nykyiset suurimmat oikeudelliset edut rappeutuvat nopeasti teknologian vuoksi, ja tilalle ilmestyy uusia etuja. Laskeneiden viestintäkustannusten ansiosta läheisyyden tarve liiketoiminnan välttämättömänä ehtona on vähentynyt. Vuonna 1946 oli teknisesti mahdollista, että Lontoossa asuva sijoittaja asetti orderin New Yorkissa toimivalle välittäjälle, mutta ainoastaan suurimmat ja vakuuttavimmat liiketoimet oikeuttaisivat siihen: kolmen minuutin puhelinsoitto New Yorkin ja Lontoon välillä maksoi 650 dollaria. Nykyään vastaavan puhelun hinta on 0,91 dollaria. Yhteensä interkontinentaalipuhelun hinta on romahtanut yli 99 prosentilla puolen vuosisadan aikana.

### Konvergentti viestintä

Pian ero mantereiden välisen chatin ja paikallisen puhelun välillä saattaa olla vähäinen. Samoin eroja puhelimesi, tietokoneesi ja televisiosi välillä voi ilmetä vain vähäisenä. Kaikki näistä laitteista tulevat olemaan interaktiivisia viestintälaitteita, joita erottavat helpommin ergonomiset kuin toiminnalliset ominaisuudet. Voit käydä äänikeskustelua Internetin välityksellä käyttäen henkilökohtaisen tietokoneesi mikrofoneja ja kaiuttimia. Tai voit katsoa elokuvan. Voit puhua televisiollesi ja kommunikoida valtavia määriä dataa sen tarjoaman viihdeverkon kautta. Keskeinen teollisuusajan ero eri viestintämuotojen välillä hajoaa ja kustannukset romahtavat, jolloin yhä useammat palvelut laskuttavat sinua käyttötunnin mukaan sen sijaan, että viestiesi kohde määrittäisi hinnan. Keskustelu tai datansiirto missä tahansa maailmassa maksaa vain vähän enemmän kuin paikallinen puhelu maksoi useimmissa lainkäyttöalueissa vuonna 1985.

### Langaton Internet

Matalan kiertoradan satelliitit ja muut langattoman teknologian ratkaisut lähettävät suoria syötteitä edestakaisin suoraan taskussasi olevaan hälytinlaitteeseen, kannettavaan tietokoneeseen tai työasemaan ilman, että niiden täytyy olla yhteydessä paikalliseen puhelinverkkoon tai TV-kaapelijärjestelmään. Lyhyesti sanottuna Internet tulee olemaan johdoton. Ensiaskeleet tuohon suuntaan ovat todennäköisesti epävarmoja, johtuen varhaisten langattomien medioiden hitaasta datansiirto-nopeudesta ja vaikeuksista "kuulla" heikkoja signaaleja tilaajalaitteista, joista osa on mobiileja ja akkujen voimalla toimivia. Näitä teknisiä ongelmia kuitenkin pyritään ratkaisemaan.

### Liiketoimintaa ilman rajoja

Jatkuva laskentatehon laajeneminen johtaa parempaan pakkausteknologiaan, mikä nopeuttaa datavirtaa. Yleisesti hyväksytyt nykyiset julkisen avaimen ja yksityisen avaimen salausalgoritmit mahdollistavat palveluntarjoajille – kuten satelliittijärjestelmien – sisällyttää laskutustoiminnon osaksi palvelua, mikä madaltaa kustannuksia. Samanaikaisesti palvelun kanssa myyjät pystyvät veloittamaan henkilökohtaisissa tietokoneissa varattuja tilejä samalla tavalla kuin *France Telecom* veloittaa pariisilaisista puhelinlaatikoissa käytetyistä 'smart cards'.

### Puhelimesta tulee pankki

Ero on siinä, että lähitulevaisuudessa voit ansaita krediittejä tilillesi monenlaisten tapahtumien yhteydessä ja kantaa puhelinlaatikkoasi mukanasi. Tietokoneestasi tulee pankkisi sivuliike ja maailmanlaajuisten rahanvälitysjärjestelmien konttori sekä vastaava kuin pariisilainen kioski, josta ostat nimettömän puhelinkorttisi. Ja kuten 150 'smart card' -maksupuhelinta, jotka ovat hyödyttömiä varkaille, jos ne avataan lipalla, tietokonettasi voisi ryöstää vain henkilö, joka kykenee murtamaan tai manipuloimaan kehittynyttä tietokonekoodia – mikä jättäisi pelkät puomaa osaavat rikolliset ulkopuolelle. Kunnollisella salauksella mitään tietokoneessasi ei voitaisi purkaa tai väärinkäyttää.

Vuosituhannen vaihteessa pystyt tekemään liiketoimia melkein missä tahansa Etelämantereen pohjoispuolella – missä tahansa on käytössä kiinteä- tai digitaalinen matkapuhelinverkko, interaktiiviset kaapelitelevisiojärjestelmät, satelliitti tai muut langattomat lähetysjärjestelmät. Voit puhua, siirtää dataa ja matkustaa virtuaalitodellisuuden avulla yli rajojen ja esteiden vapaasti. Aluekoodeilla puhujan sijainnin määrittäminen korvautuu todennäköisesti universaaleilla pääsynumeroilla, jotka tavoittavat sen tahon, jonka kanssa haluat kommunikoida missä tahansa planeetalla.

### Kiinan ymmärtäminen

Et ainoastaan pysty puhumaan ja lähettämään faksia. Ajan myötä pystyt lyhentämään monivuotista oppimisprosessia ja keskustelemaan kiinaksi shanghailla olevan tehtaan isännän kanssa. Ei enää ole niin ratkaisevaa, ettet puhu hänen kieltään tai murretta. Hänen sanansa saattavat olla kiinaksi, mutta kuulet ne – Transcending Locality I 8 – karkeasti käännettynä englanniksi. Hän kuulee keskustelusi kiinaksi. Ajan myötä välittömän käännösteknologian käyttökyky lisää kilpailua merkittävästi alueilla, joilla kielen ja idiomien esteet ovat tähän asti olleet merkittäviä. Kun niin tapahtuu, ei ole väliä, että Kiinan hallitus ei ehkä toivo, että puhelu toteutettaisiin.

### Customized media

Maailman lähestyessä toisiaan sinulla on nyt suurempi mahdollisuus kuin koskaan aiemmin räätälöidä oma paikkasi siinä. Jopa mediaan säännöllisesti saama tieto on sinulle räätälöityä. Massamedia muuttuu yksilölliseksi mediaksi. Jos olet ensisijaisesti kiinnostunut shakista tai olet innokas kissaihminen, pystyt ohjelmoimaan iltaledustuksesi niin, että se sisältää sinulle tärkeää tietoa kissoista tai shakista. Et enää ole Dan Ratherin tai BBC:n armoilla siitä, mitä uutisia sinulle esitetään. Pystyt valitsemaan uutiset, jotka on koottu ja muokattu ohjeidesi mukaisesti.

### From mass to customized production

Jos uutiset ovat hitaita, voit selata virtuaalista katalogia World Wide Webissä. Jos näet housut, joista pidät lähes, voit säätää hihansuuman leveyden tehdessäsi tilauksesi. Ne leikataan mittatilaustyönä ja räätälöidään kehosi mukaan Malesiassa toimivien robottien toimesta valokuvista, jotka on skannattu tietokoneeseesi ja lähetetty internetin kautta.

### Cyberbroking

Voit käyttää kyberrahaa sekä sijoituksiin että palvelujen ja tuotteiden maksamiseen. Jos asut sellaisella lainkäyttöalueella, kuten Yhdysvalloissa, joka tiukasti säätelee sijoitusvaihtoehtojasi, voit valita harjoittaa toimintaasi sellaisessa lainkäyttöalueessa, joka sallii vapaasti laajan sijoitusvalikoiman hyödyntämisen. Asutpa sitten Clevelandissa tai Belo Horizonteissa, voit hoitaa sijoitustoimintaasi Bermudoilla, Cayman-saarilla, Rio de Janeirossa tai Buenos Airesissa. Missä tahansa oletkin, digitaalisten resurssien käyttö laajenee kybertalouden kehittyessä. Voit hyödyntää asiantuntijajärjestelmiä sijoitustesi valintaan sekä kybertilinpitäjiä ja -kirjanpitäjiä seuraamaan reaaliajassa omaisuutesi kehitystä.

### Virtuaalikulttuuri

Kun et tarkastele tuotto- ja tappiotietoja, voit tehdä virtuaalikierroksen Louvressa. Matkallasi saattaa tulla tarpeelliseksi maksaa rojaltimaksu, joka vastaa kolmasosaa pennistä Bill Gatesille tai jollekin yhtä näkevälle henkilölle, joka on ostanut museon virtuaalitodellisuusoikeudet. Samaan aikaan kun pohdit, oliko Mona Lisalla ongelmia hampaidensa kanssa, tietokoneesi voi ladata *The Romance of the Western Chamber* -käännöksen. Halutessasi henkilökohtainen viestintäjärjestelmäsi lukee tekstin ääneen kuin vanhan ajan runonlaulaja, ja moniajo-ohjelmat sallivat suorittaa useita tehtäviä samanaikaisesti.

### Verkosta lainkäyttöalueita

Jos klassikoista saatu inspiraatiosi innostaa, voit perustaa virtuaalisen yrityksen markkinoimaan kuuluisan kirjallisuuden dramaattisia tuotantoja katsottavaksi kolmiulotteisessa verkkonäytössä suoraan verkkokalvoille. Sen sijaan, että kuvat heijastuivat ilmaan, ne projisoidaan suoraan katsojien verkkokalvoille alhaisen energian lasereilla, jotka vaihtuvat viisikymmentä tuhatta kertaa sekunnissa. Tämä teknologia, jonka kehitystyötä jo vetää *MicroVision of Seattle, Washington*, mahdollistaa sen, että monet laillisesti sokeat saavat nähdä. Ennen projektin aloittamista voisit antaa digitaaliselle avustajallesi käskyn kartoittaa tämänhetkiset suojelusopimustarjoukset valmistuslaitoksille Malesiassa, Kiinassa, Perussa, Brasiliassa ja Tšekissä. Kun valitset sijainnin, voit perustaa yrityksesi Bahama-saarten alueella tunnissa, kiitos *St. George’s Trust Companyn*. Ohjeidesi mukaisesti yrityksen kaikki likvidit varat siirretään kybertilille kyberpankissa, joka on samanaikaisesti rekisteröity Newfoundlandissa, Kaimansaarten, Uruguayn, Argentiinan ja Liechtensteinin alueelle. Jos jokin näistä lainkäyttöalueista yrittää peruuttaa toimintavaltuutuksensa tai takavarikoida tallettajien varoja, varat siirretään automaattisesti toiseen lainkäyttöalueeseen valon nopeudella.

## Kvalitatiiviset edistysaskeleet

Monia niitä transaktioita, joita pian pystyt suorittamaan kyberavaruudessa, olisi ollut teollisella aikakaudella mahdotonta toteuttaa – eikä pelkästään siksi, että ne ylittävät kielimuurin. Digitaalisten avustajien lähettäminen etsimään kääntämättömiä artikkeleita unkarilaisista tieteellisistä julkaisuista on laadultaan erilaista kuin keskustelu kirjastonhoitajan kanssa. Osallistuminen Oxfordin ohjaukseen viiden tuhannen mailin etäisyydeltä ei ole sama kuin ohjaukseen osallistuminen, kun nukut kuuden mailin päässä Carfaxista. Ja *Hotel de Paris, Monte Carlo* -ravintolan ruletin pelaaminen on uudenlaista kokemusta, kun voit tehdä sen virtuaalitodellisuuden välityksellä juhlissa Punté del Estessä, Uruguayssa.

### Kybervierailu kyberlääkäriin

Lyhyessä ajassa – nopeammin kuin monet asiantuntijat nykyään uskovatkaan mahdolliseksi – toiminnot siirtyvät kybertalouteen, jossa teknologiat yhdistyvät uudella tavalla ylittääkseen paikan tyrannian ja teollistuneen talouden vanhentuneet instituutiot. Pian, jos tunnet vatsakipua, voit kuulla digitaalisen lääkärin neuvoja – asiantuntijajärjestelmää, jolla on tietosanakirjamainen tieto oireista, vaivoista ja vasta-aineista. Se pääsee käsiksi salattuna olevaan sairaushistoriaasi, kysyy esimerkiks, ilmeneekö kipu syömisen jälkeen vai ennen aterioita, onko se terävää vai tylsää, jatkuvaa vai ajoittaista. Mitä tahansa kysymyksiä lääkärit esittävätkin, digitaalinen lääkäri esittää ne. Se saattaa todeta, että juot liikaa viiniä tai ei tarpeeksi. Saatat ohjata kyberasiantuntijan luo. Jos tarvitset leikkausta, Bermudan kyberkirurgi voi suorittaa sen etäleikkauksena erikoislaitteiden avulla, jotka tekevät mikroskooppisia viiltoja.

### Elämä ja kuolema: tiedonkäsittely

Tämä saattaa kuulostaa scifiä muistuttavalta. Kuitenkin monet kybersiirto-operaatioihin liittyvät osatekijät ovat jo käytössä, ja toisten osalta niiden odotetaan toimivan siihen mennessä, kun luet tämän kirjan. *General Electric* on ottanut käyttöön uuden magneettikuvantamiseen perustuvan hoitolaitteen (MRT) 15 sairaalassa maailmanlaajuisesti. Laitteelle on arvioitu kolmen vuoden tutkimus- ja kehitysvaihe, jonka jälkeen sen odotetaan leviävän nopeasti ja vakiintuvan normiksi monenlaisissa leikkauksissa. Tämä on yksi, mutta hyvä esimerkki siitä, miten teknologia muuttaa yhteiskuntaa.

Suurin osa meistä tuntee magneettikuvantamislaitteet (MRI), joissa magneettikuvaustekniikkaa käytetään pehmytkudosten kuvien tuottamiseen diagnostisia tarkoituksia varten. Ne tarjoavat parempia kuvia pehmytkudoksista kuin röntgenkuvat tai ultraääni, ja niistä on tullut olennainen osa moderneja diagnostiikkamenetelmiä, erityisesti syöpien yhteydessä. Niillä on kuitenkin tällä hetkellä kaksi merkittävää rajoitusta. Laite putkessa ei salli vapaata pääsyä potilaaseen, ja koneiden teho on rajallinen.

### Kybersuomennusleikkaus

*General Electric* on suunnitellut magneettikuvantamislaitteet uudelleen siten, että niitä voidaan käyttää sekä diagnoosiin että hoitoon. Laitteen tehoa on nostettu viisi kertaa. Käytännössä putki on leikattu kahtia, jolloin potilas makaa kahden donitsin muotoisen yksikön välissä sen sijaan, että hän olisi täysin suljettu. Sen sijaan, että ensin otettaisiin kuva ja sitten suoritettaisiin leikkaus sen perusteella, kirurgi pystyy näkemään tekemisensä reaaliajassa. MRT yhdistetään ei-invasiiviseen tai vähemmän invasiiviseen leikkaukseen mikrotekniikoiden avulla. Sen sijaan, että iskutettaisiin suuria viiltoja viiltoinstrumenteilla, kirurgi tekee mikrosiivtoja koetinlaitteilla ja pystyy näkemään niiden paljastamat yksityiskohdat operoidessaan. Hän suorittaa leikkauksen kuvan avulla sen sijaan, että katsoisi suoraan kehoon. Periaatteessa koetinlaitteet voidaan ohjata etänä, ja niiden avulla pystytään tuhoamaan kasvaimia erittäin tarkkuutta omaavilla laser- tai kryogeenisilla lämmitys- ja jäädytyslaitteilla.

Tämä mahdollistaa operaatioita, jotka ovat nyt mahdottomia, erityisesti neurokirurgiassa, missä kasvaimet sijaitsevat usein hyvin lähellä aivojen elintärkeitä osia. Se mahdollistaa myös toistuvat leikkaukset, kun perinteisen kirurgisen toimenpiteen aiheuttamaa traumaa ei voida toistaa ilman kohtuutonta vahinkoa. Jotkut tutkijat uskovat, että pehmeiden kudosten leikkauksen veitsi voidaan katsoa vanhentuneeksi jäännökseksi jo vuonna 2010. Paljon pelkoa ja jälkisinä iskuna ilmenevää epävarmuutta poistuu leikkaustoimenpiteistä, jos näin käy. Ilmeisesti tämä on erittäin hyviä uutisia potilaalle. Operaatioita, joiden suorittaminen kestää nykyään tunteja ja joita seuraa sairaalassa vietetyt päivät tai jopa viikot, voidaan tehdä vain puolessa tunnissa – eikä niitä välttämättä tarvitse tehdä sairaalassa lainkaan. Itse asiassa kirurgi ja potilas eivät ehkä koskaan edes kohtaa toisensa samassa huoneessa. Mutta mitä tämä tekee sairaaloille ja kirurgeille?

### Vähemmän mikrokirurgeja, enemmän operaatioita

Käymme läpi kirurgian vallankumousta. Koulutuksessa kolmasosa nuorista kirurgeista ei ole oppinut tarvittavia mikrokirurgia-taitoja, toinen kolmasosa osaa juuri ja juuri sen, ja loput kolmasosasta tulevat erinomaisiksi. Samankaltaiset osuudet esiintyvät myös vanhempien kirurgeiden uudelleenkoulutuskursseilla. Vähemmät kirurgit pystyvät suorittamaan enemmän operaatioita lyhyemmässä ajassa. On todennäköistä, että terveydenhuollon vakuutusyhtiöt ja leikkauksia hakevat henkilöt vaativat jokaiselta kirurgilta tarkkoja tulosstatistiikkoja, jotka vaihtelevat melko laajasti. Potilaat haluavat mennä niille kirurgeille, joiden tulokset ovat parhaat, erityisesti henkeä uhkaavissa tilanteissa. Joissakin tapauksissa parhaat kirurgit saattavat operoida etäyhteydellä; he voivat suorittaa koko operaation toisella toimivaltiolla, jossa verot ovat alhaisempia eikä tuomioistuimet kunnioita kohtuuttomia vikatvastuutaan koskevia vaatimuksia.

### Digitaaliset lakimiehet

Ennen kuin kokenut kirurgi sitoutuu suorittamaan leikkauksen, hän todennäköisesti kääntyy digitaalisen lakimiehen puoleen laatimaan välittömän sopimuksen, joka määrittelee ja rajoittaa vastuun kasvaimen koon ja ominaisuuksien perusteella – tiedot, jotka paljastuvat magneettikuvantamislaitteen näyttämissä kuvissa. Digitaaliset lakimiehet toimivat informaationhakujärjestelminä, jotka automatisoivat sopimuslausekkeiden valinnan hyödyntäen tekoälyprosesseja, kuten neuroverkkoja, räätälöidäkseen yksityisiä sopimuksia kansainvälisten oikeudellisten vaatimusten mukaisiksi. Suurimmissa ja tärkeimmissä transaktioissa osapuolet eivät ainoastaan etsi sopivia liikekumppaneita, vaan myös etsivät optimaalisia kotipaikkoja transaktioilleen.

### Hätäkonsultaatio

Jatkaakseen kybersuivauksen esimerkkiä, informaatioteknologian aikakausi nostaa kirurgian korkeimmat taidot etusijalle, kuten lähes kaikillakin muillakin aloilla. Potilaat ovat olleet valmiita maksamaan tällaisen lisämaksun niin kauan kuin on ollut veitsiä. Mutta tiedon rajoitukset ja se, kuinka hankalaa on etsiä hätätilanteessa paikallista kirurgia, tekivät kirurgian markkinoista hyvin epätäydelliset. Ne tulevat olemaan vähemmän epätäydelliset informaatioteknologian aikakaudella. Potilas, joka tarvitsee leikkauksen 24 tunnin kuluttua – tai ehkä jopa 45 minuutin kuluttua – voisi antaa digitaalisille avustajille toimeksiannon etsiä kymmenen parasta maailmanlaajuista kirurgia, jotka pystyvät suorittamaan etäleikkauksen, tarkastella heidän onnistumisprosenttejaan vastaavissa tapauksissa ja pyytää tarjouksia juuri hänen tapaustaan varten vastaavilta digitaalisilta palvelijoilta. Kaiken tämän voisi selvittää hetkessä. Tämän seurauksena suosituimpien 10 prosentin kirurgien osuus maailmanlaajuisessa leikkausmarkkinassa kasvaa huomattavasti. MRT-laite yhdessä mikrokirurgian tekniikoiden kanssa nostaa heidän työnsä lisämaksua, ja vähemmän taitavat kirurgit keskittyvät jäljelle jääviin paikallisiin markkinoihin.

Tämä elämän ja kuoleman esimerkki antaa viitteitä siitä, millaisia vallankumouksellisia seurauksia voi olla talouksien vapauttamisesta paikkariippuvuuden tirannasta. Joku saattaa väittää, ettei General Electricin MRT-laitetta ole tarkoitettu käytettäväksi pitkällä matkalla. Ehkä, mutta se ohittaa pointin. Pian se – tai sen kaltainen laite – tulee olemaan olemassa. Kun leikkaukset tehdään paremmin kirurgien, jotka katsovat näyttöä sen sijaan, että katsoisivat potilasta suoraan, merkitystä sille, missä kirurgi ja hänen näyttönsä sijaitsevat, ei enää ole niin paljon kuin nykyään. Yhä useammat palvelut muuntuvat siten, että informaatioteknologia mahdollistaa sen, että kuka tahansa maapallon kolkasta voi olla yhteydessä toiseen jopa niin herkissä asioissa kuin kirurgiassa. Toiminnoissa, joissa vaaditaan vähemmän tarkkaa laitteistoa ja joissa epäonnistumisriski on pienempi, kybertalous kukoistaa entistä nopeammin.

> "The financial policy of the welfare state requires that there be no way for the owners of wealth to protect themselves." - ALAN GREENSPAN

## Pakottamisen arvonalentuminen

Lähes jokaisella kilpailevalla alalla – mukaan lukien suurin osa maailman monitriljoonadollarisesta sijoitustoiminnasta – transaktioiden siirtyminen kyberavaruuteen tulee johtumaan lähes hydraulisesta paineesta – pyrkimyksestä välttää saalistavaa verotusta, mukaan lukien se vero, jonka inflaatio kohdistaa jokaiseen, joka pitää varallisuuttaan kansallisessa valuutassa.

### Suojeluräpin välttäminen

Ei tarvitse pohdiskella pitkään informaatiokauden megapolitiikkaa ymmärtääkseen, että varakkaimpien teollisuusmaiden kansalaisille oikeuksien mukaisesti määräämät saalistavat verot ja inflaatio tulevat olemaan naurettavan epäkilpailukykyisiä kyberavaruuden uudella rajalla. Vain pian vuosituhannen vaihdoksen jälkeen kuka tahansa, joka maksaa tuloveroja nykyisin määrätyillä veroasteilla, tulee itse valintansa mukaisesti maksamaan 50 prosenttia. Kuten Frederic C. Lane totesi, historia osoittaa, että 'rajamailla ja korkeilla merillä, joissa kukaan ei hallinnut väkivallan käyttöä pysyvästi, kauppiaat välttelivät maksamasta sellaisia perimisiä, jotka olivat niin korkeita, että suojelusta voitiin saada halvemmalla muilla keinoilla.'[^255]

Kybertalous tarjoaa juuri tällaisen vaihtoehdon. Yksikään hallitus ei kykene monopolisoi sitä. Ja siihen sisältyvät informaatioteknologiat tarjoavat halvempaa ja tehokkaampaa suojaa rahoitusomaisuudelle kuin useimpikaan hallitus on koskaan ehtinyt tarjota.

### Yhdistekoron musta magia

Muista, että jokainen 5 000 dollarin vuotuisista veromaksuista, joita maksat neljänkymmenen vuoden ajan, vähentää nettovarallisuuttasi 2,2 miljoonalla dollarilla – oletuksena, että saisit pääomallasi vain 10 prosenttia tuottoa. 20 prosentin tuotolla yhdistetty tappio kasvaa noin 44 miljoonaan dollariin. Korkeatuloisille henkilöille maassa, jossa verotus on raskasta, saalistavan verotuksen elinikäiset kumulatiiviset tappiot ovat järkyttävät. Useimmat menettävätkin enemmän kuin heillä koskaan oli.

Tämä kuulostaa mahdottomalta, mutta matematiikka on selkeää. Voit varmentaa sen itse taskulaskimella. Yhdysvalloissa ylimmän 1 prosentin veronmaksajien keskimääräinen liittovaltion tulovero on yli 125 000 dollaria vuodessa. Pienen osan tästä, 45 000 dollaria vuodessa, hinnalla olisi mahdollista asua Sveitsin yksityisen verosopimuksen alaisena ja nauttia lain ja järjestyksen palveluista, joita tarjoaa ehkä maailman rehellisin poliisi- ja oikeusjärjestelmä. Tästä näkökulmasta ylimääräiset 80 000 dollaria vuodessa maksettua tuloveroa voisi hyvin luokitella kunnianosoitukseksi tai ryöstöksi. 45 000 dollaria on ehdottomasti huomattava summa lain ja järjestyksen ylläpidosta, kun otetaan huomioon, että poliisisuojaa pidetään julkisena hyödykkeenä. Teoriassa julkiset hyödykkeet voidaan laajentaa lisäkäyttäjille marginaalikustannuksin nolla. Sveitsiläiset ilahtuvat siitä, että maksat neuvotellun kiinteän veron 45 000 dollaria (50 000 Sveitsin frangia) vuodessa, sillä he saavat siitä vuosittain 45 000 dollarin voiton jokaiselta miljonääriltä, joka liittyy mukaan.

Verrattuna tällaiseen sveitsiläiseen vaihtoehtoon, Yhdysvaltain verokannoilla maksettujen liittovaltion tuloverojen elinikäiset tappiot olisivat 705 miljoonaa dollaria siltä sijoittajalta, joka saavuttaa keskimäärin 20 prosentin tuoton. Muista kuitenkin, että tämä olettaa 45 000 dollarin vuotuiset veromaksut. Verrattuna veroparatiisiin kuten Bermudalle, jossa tulovero on nolla, elinikäinen tuhannen dollarin verojen menetys amerikkalaisilla veroilla olisi noin 1,1 miljardia dollaria.

Saatat vastata, että 20 prosentin vuotuinen tuotto on korkea. Epäilemättä olisit oikeassa. Mutta ottaen huomioon Aasian hämmästyttävä kasvu viime vuosikymmeninä, monet maailman sijoittajat ovat saavuttaneet tuon tai vielä parempia tuottoja. Hongkongin kiinteistösijoituksissa kertynyt yhdistetty tuottoprosentti vuodessa on ollut yli 20 prosenttia vuodesta 1950 lähtien. Jopa joissakin talouksissa, jotka eivät ole laajalti tunnettuja kasvustaan, on tarjonnut helppoja mahdollisuuksia korkeisiin voittoihin. Olisit voinut saada keskimääräisen reaalituoton yli 30 prosenttia vuodessa Yhdysvaltain dollarimääräisten talletusten kautta paraguaylaisissa pankeissa viimeisten kolmen vuosikymmenen aikana. Korkeat sijoitustuotot ovat helpommin saavutettavissa joillakin alueilla kuin toisilla, mutta taitavat sijoittajat voivat varmasti saavuttaa yli 20 prosentin tuotot hyvissä vuosissa, vaikka he eivät jatkuvasti vastaisikaan George Sorosin tai Warren Buffetin esityksiä.

Ilmiselvää on, että mitä korkeampi tuotto pääomallasi voisi olla, sitä suuremmat ovat saalistavan tuloverotuksen ja pääomatuloverotuksen vaihtoehtoiskustannukset. Johtopäätös siitä, että menetys on valtava – jopa suurempi kuin se varallisuus, jonka koskaan kertyisit – ei kuitenkaan riipu siitä, pystytkö saavuttamaan hurjaannuttavia tuottoprosentteja. Joidenkin Yhdysvalloissa toimivien sijoitusrahastojen keskimääräiset vuotuiset tuotot ovat olleet yli 10 prosenttia yli puolen vuosisadan ajan. Jos et pysty saamaan parempaa tuottoa ja kuulut amerikkalaisten ylimmän 1 prosentin joukkoon, nettovarallisuutesi pienenee yli 33 miljoonalla dollarilla vain siitä tuloverosta, mitä maksat yli 45 000 dollarin vuoden verorajasta. Verrattuna alueeseen, jossa tuloveroa ei ole, menetys on 55 miljoonaa dollaria.

### $55 ennemminkin kuin 55 miljoonaa dollaria

Jos taloustieteilijöiden voiton maksimointia koskevat oletukset pitävät paikkansa – kuten uskommekin niiden yleensä tekevän – yksi varmemmista ennusteista on, että useimmat ihmiset toimisivat pelastaakseen 55 miljoonaa dollaria, jos siihen olisi mahdollisuus. Näin meidän ennusteemme on. Kun korkoa korolle laskun musta magia kirkastuu menestyneiden korkeaveroisten maiden ihmisten mielissä, he alkavat panostaa aidosti eri oikeusalueiden palveluihin, aivan kuten nyt he vertailevat autoja tai vakuutusten hintoja. Jos epäilet sitä, pysäytä vain satunnaisesti ihmisiä New Yorkin tai Toronton kaduilla ja kysy, muuttaisivatko he Bermudoille 55 miljoonan dollarin tähden. Kysymys vastaa itsestään. Se asettaa pulman, joka muistuttaa sitä, jonka Mark Twain kuviteli päättävässään, viettäisikö hän yön Lillian Russellin kanssa täysin alastomana vai kenraali Grantin kanssa täydellisessä univormussa. Hän ei miettinyt kauan. Kypsissä hyvinvointivaltioissa, erityisesti Yhdysvalloissa, reagointi saattaa olla hitaampaa – mutta vain siksi, etteivät he vielä ymmärrä kohtaamaansa valintatilannetta. Ajan myötä he tulevat tietoisiksi siitä. Sinä tai kuka tahansa, jota motivoi halu elää parempaa elämää, huomaat houkutuksen vähentää tappioita, joita saattaisit kärsiä saalistavan verotuksen seurauksena. Sinun tarvitsee ainoastaan kirjata tapahtumasi kybertilaan. Tämä on tietenkin monilla oikeusalueilla laiton teko. Vanhoja lakeja harvoin pystyy vastustamaan uusi teknologia. 1980-luvulla Yhdysvalloissa oli laitonta lähettää faksiviestejä – Yhdysvaltain postitoimisto piti fakseja ensiluokkaisena postina, johon se väitti muinaista monopolia. Tällainen määräys annettiin, toistaen vaatimus, että kaikki faksisiirrot ohjattaisiin lähimpään postitoimistoon säännöllisen postin toimitusta varten. Miljardit faksiviestejä myöhemmin on epäselvää, noudattiko kukaan tätä lakia; jos noudatettaisiin, se olisi ollut ohimenevää. Kehittyvän kybertalouden edut ovat vielä vakuuttavammat kuin postitoimiston ohittaminen faksin lähettämisessä.

Laajalti yleistyvät julkisen ja yksityisen avaimen salausteknologiat mahdollistavat pian monien taloudellisten toimien suorittamisen missä tahansa. Kuten *Strategic Investmentin* teknologia-toimittaja James Bennet on kirjoittanut:

> 'Lakien ja erityisesti verokoodien täytäntöönpano on tullut voimakkaasti riippuvaiseksi viestinnän ja transaktioiden valvonnasta. Kun seuraavat loogiset askeleet on otettu, ja ulkomaiset pankkipaikat tarjoavat viestintäpalveluita kovalla RSA-salauksella suojatun sähköpostin muodossa, käyttäen julkisen avaimen järjestelmistä johdettuja tilinumeroita, taloudelliset transaktiot tulevat olemaan melkein mahdottomia valvoa pankissa tai viestinnässä. Vaikka veroviranomaiset sijoittaisivat naamioidun agentin ulkomaiselle pankille tai murtaisivat pankkitiedot, he eivät pysty tunnistamaan tallettajia.'[^256]

Sellaiseen asteeseen, jota ennen ei ollenkaan ollut mahdollista, yksilöt pystyvät määrittämään, missä he harjoittavat taloudellista toimintaansa ja kuinka paljon tuloveroa he mielellään maksavat. Monet informaatiokauden transaktiot eivät tarvitse lainkaan olla sidottuja mihinkään alueelliseen suvereniteettiin. Ne, jotka ovat, löytävät yhä useammin tiensä paikkoihin kuten Bermudalle, Cayman-saarille, Uruguayhin tai vastaaviin oikeudellisiin alueisiin, jotka eivät määrää tuloveroja tai muita kalliita kaupankäyntimaksuja.

[^256]: James Bennet, *Strategic Investment*  


### Monopolista kilpailuun

Hallitukset ovat tottuneet määräämään 'suojauspalveluja', jotka ovat, kuten Frederic C. Lane sanoo, 'huonolaatuisia ja järkyttävän ylihinnoiteltuja.'[^257] Tämä tapa veloittaa paljon enemmän kuin mitä hallituksen palvelut todellisuudessa ovat arvoltaan kehittyi vuosikymmenten monopoliaseman kautta. Verot nostettiin raa'asti kaikilta, joiden uskottiin pystyvän maksamaan – juuri siksi, että hallituksilla oli monopoli tai lähes monopoli pakottamisessa. Tämä monopoliperinne kohtaa syvällisesti kyberkaupan uudet megapoliittiset mahdollisuudet.

Salaus tekee kyberavaruuden tapahtumien suojaamisesta vaivatonta. Tehokkaan salausohjelman, kuten *PGP*:n, kustannukset ovat pienemmät kuin sen komissio, jonka täyden palvelun välittäjä perii sadan osakkeen kaupasta. Silti se tekee lähes mistä tahansa tapahtumasta näkymättömiä ja immuuneja hallituksille ja varkaille useiksi vuosiksi. Information Ageden uusi teknologia suojaa kyberomaisuuksia käytännössä vähekkäin kustannuksin. Vain 55 dollarilla – eikä 55 miljoonalla – kybertalouden osallistujat saavat parempaa todellista suojaa omaisuudelleen kuin mitä teollisella aikakaudella tai aiemmin ollenkaan on koettu. Helppokäyttöiset salausalgoritmit ja mahdollisuus vertailla maanpäällisiä asuinpaikkoja tapahtuvia kauppoja tarjoavat tehokkaan suojan suurinta raivokasta lähdettä, kansallisvaltioita itseään, vastaan.

Tämä ei kuitenkaan tarkoita, että alueelliset hallitukset jäisivät täysin kelkasta. Ne pystyvät edelleen hyödyntämään henkilökohtaisiin vahinkoihin liittyviä haavoittuvuuksia periäkseen pääveroja tai jopa pitämään varakkaita yksilöitä suoran kiristysten alaisina. Ne pystyvät myös pakottamaan kulutusverojen keräämisen. Silti suoja – tärkein hallitusten tarjoama palvelu – asetetaan entistä kilpailukykyisemmälle pohjalle. Vähemmän suojaan liittyvistä kustannuksista tulee olla käytettävissä, jotta poliittiset viranomaiset voisivat takavarikoida ja uudelleen kohdentaa niitä. Teknologiset innovaatiot siirtävät suuren ja kasvavan osan maailman varallisuudesta hallitusten ulottumattomaksi. Tämä vähentää kaupan riskejä ja laskee jyrkästi historioitsija Janet Abu-Lughodin sanojen mukaan 'kaikkien kustannusten osuutta', jotka muuten joutuisi kohdistamaan 'kuljetusveroihin, alttauksiin tai yksinkertaiseen kiristykseen.'[^258]

Historiassa on ollut harvinaista, että hallitukset ovat todella olleet kilpailevien toimijoiden rajoittamia. Niissä harvoissa tapauksissa, kun jotakin tällaista on tapahtunut, hallitukset olivat heikkoja ja teknologiat samanlaisia eri toimivaltioiden välillä. Kuten Lane totesi, keskeinen tekijä tällaisissa olosuhteissa vaikuttavassa kannattavuudessa on usein eri yrittäjien maksamien suojauskustannusten ero. Keskiaikainen kauppias, jonka piti maksaa kaksikymmentä tietullia tuodakseen tavaransa markkinoille, ei voinut kilpailla kauppiaan kanssa, jonka piti maksaa vain neljä tietullia toimittaakseen samat tavarat asiakkaalle. Samankaltaiset olosuhteet ovat määrätty palaamaan Information Ageden myötä. Kannattavuus määräytyy jälleen ei niinkään teknologisen edun, vaan menestyksen perusteella siinä, kuinka hyvin pystyt minimoimaan ne kustannukset, jotka sinun on pakko maksaa suojauksesta.

Tämä uusi talousdynaamismi on suoraan ristiriidassa teollisaikojen perintönä jääneen hallituksen halun kanssa asettaa monopolihintoja sen suojauspalveluille. Mutta pitikö rakastaa tai inhoa, vanha järjestelmä ei ole elinkelpoinen uuden tietoyhteiskunnan kilpaillussa ympäristössä. Jokainen hallitus, joka vaatii kansalaisiltaan raskaita veroja, joita kilpailijat eivät maksa, varmistaa vain, että voitot ja varallisuus eivät jää kotimaan sisälle, vaan virtaavat jonnekin muualle. Siksi kehittyneiden hyvinvointivaltioden epäonnistuminen verojen pitkäaikaisessa leikkaamisessa on itsekorjaava ilmiö. Liian paljon verottavat hallitukset tekevät asumisesta heidän vaikutusalueellaan konkurssin uhkaavan rasitteen.

> "... kuten kuningas suvereeniensä nojalla voi tehdä rahaa mistä aineesta ja muodosta kuin hän haluaa ja asettaa siitä standardin, samoin hän voi muuttaa rahoaan sisällöltään ja ulkonäöltään, nostaa tai alentaa sen arvoa, tai täysin hylätä ja kumota sen"[^259]: - ENGELSKISTÄ OIKEUDENPÄÄTÖKSEN NOPESTA, 1604

## Seignioragen kuolema

Hallitukset eivät menetä ainoastaan kykyään verottaa lukuisia tulo- ja pääomamuotoja, vaan niiltä on määrätty myös rahaan kohdistuvan pakottamisvallan katoaminen. Aiemmin megapoliittiset muutokset ovat olleet yhteydessä rahan luonteen muutoksiin.

- Kolikoiden käyttöönotto auttoi käynnistämään muinaisen talouden viisisadan vuoden laajenemissyklin, joka huipentui Kristuksen syntymään ja modernin ajan ennennäkemättömän matalimpien korkojen aikaan.

- Pimeiden aikojen koittaessa rahantuotantolaitokset lähes suljettiin kokonaan. Vaikka roomalainen rahakierto jatkui, rahamäärät vähenivät kaupan kanssa yhdessä itseään vahvistavassa alaspäin suuntautuvassa kierteessä.

- Feodaalinen vallankumous osui aikaan, jolloin raha, kolikot, vaihtokirjeet ja muut kaupallisten tapahtumien selkeyttämiseen tarkoitetut välineet otettiin uudelleen käyttöön. Erityisesti Euroopan hopeantuotannon nousu uusista Rammelsbergin kaivoksista Saksassa edisti kolikoiden kierron lisääntymistä, mikä osaltaan sujuvoitti kaupankäyntiä.

- Suurin rahavallankumous ennen tietoyhteiskuntaa tapahtui teollistumisen myötä. Varhaisnykyaikainen valtio vahvisti valtaansa Tuhkan vallankumouksessa. Valvontansa kasvaessa valtio asetti yhä tiukemmat säännöt rahasta ja alkoi nojata teollistumisen tunnusomaisiin teknologioihin, kuten painokoneeseen. Massatuotannon ensimmäinen väline, painokone, on ollut laajasti käytössä hallitusten toimesta modernina aikana paperirahan massatuotannossa.

Paperirahat ovat selkeästi teollinen tuote. Ennen painokoneen keksimistä olisi ollut epäkäytännöllistä kopioida kuitteja tai todistuksia, joista olisi sitten muodostunut paperirahaa. Eihän scriptoriottautuneet munkit varmasti käyttäisi aikaansa piirtäessään viisikymppisiä seteleitä. Paperirahat vaikuttivat myös merkittävästi valtion valtaan – ne tuottivat voittoa valuutan arvon heikentämisen kautta ja antoivat samalla valtiolle vaikutusvaltaa määritellä, kuka sai kerryttää varallisuutta. Kuten Abu-Lughod totesi: 'kun valtio tukee paperirahaa hyväksyttynä valuuttana, mahdollisuudet kerätä pääomaa vastoin tai erillään valtiokoneistosta vaikeutuvat.' [^260]:

## Cybercash

Nyt merkitsee informaatiokauden koittaminen uutta rahan luonteen vallankumousta. Kun kyberkauppa käynnistyy, se johtaa väistämättä kyberrahaan. Tämä uusi rahamuoto muuttaa pelin säännöt kaventamalla maailmantalouksien mahdollisuuksia määrätä, kuka voi nousta suverenneiksi yksilöiksi. Tämän muutoksen keskeinen tekijä on tietotekniikan vaikutus: se vapauttaa varallisuuden haltijat pakkoosteuksilta, jotka syntyvät inflaatiosta. Pian maksat lähes mistä tahansa verkkokaupan tapahtumasta samanaikaisesti, kun teet sen, käyttäen kyberrahaa.

Tämä uusi digitaalinen rahamuoto on määrä näyttelemään keskeistä roolia kyberkaupassa. Se koostuu salatuista lukujonoista, jotka muodostuvat sadoista numeroista koostuvista alkuluvuista. Uniikki, anonyymi ja tarkastettavissa oleva raha mahdollistaa suurimmatkin kaupat. Se on myös jaollinen jopa pisara-arkoisimmaksi arvon murto-osaksi. Sitä voidaan vaihtaa näppäimen painalluksella monitriljoonat dollarien tukkumarkkinoilla ilman rajoja.

### Soittaminen ilman dollareita

Lopulta tämä uusi kyberraha denationalisoituu. Kun suvereenit yksilöt voivat käydä kauppaa rajojen yli maailmassa, jolla ei ole fyysistä olemusta, heidän ei enää tarvitse sietää hallitusten pitkäaikaista, toistuvaa käytäntöä, jossa ne heikentävät rahansa arvoa inflaation kautta. Miksi heidän pitäisi? Rahan hallinta muuttuu vallan saleista globaalille markkinapaikalle. Jokainen henkilö tai yritys, jolla on pääsy kyberavaruuteen, pystyy helposti vaihtamaan minkä tahansa valuutan, jota uhkaa arvon lasku. Toisin kuin nykyään, ei ole tarvetta käyttää laillista maksuvälinettä. Itse asiassa, jos kaupat ulottuvat ympäri maailmaa, on todennäköistä, että ainakin yksi osapuoli jokaisessa liiketoimessa joutuu käsittelemään valuuttaa, joka ei ole hänelle laillinen maksuväline.

### Vaihdannan haittojen vähentyminen

Kybertaloudessa voit käydä kauppaa minkä tahansa välineen kanssa, jota haluat käyttää. Myöhäisellä Nobel-palkinnon voittaneella taloustieteilijällä *E. A. Hayekillä* oli näkemys, jonka mukaan 'ei ole selvää eroa rahan ja ei-rahan välillä.' Hän kirjoitti: 'vaikka oletamme yleensä, että rahaa ja ei-rahaa erottaa terävä raja – ja lainkaan yritetäänkin tehdä sitä – rahallisten tapahtumien syy-seuraussuhteiden osalta selkeää eroa ei ole. Havaintomme on pikemminkin jatkuvuus, jossa erilaisilla likviditeetin asteilla varustetut esineet, joiden arvot voivat vaihdella itsenäisesti, liukuvat toistensa sekaan siinä määrin, missä ne toimivat rahana.'[^261] Digitaalinen raha maailmanlaajuisissa tietoverkoissa tekee jokaisesta esineestä Hayekin likviditeettijatkumon varrella likvidimmän – paitsi hallituksen paperin. Yksi seuraus on, että vaihtokauppa tulee olemaan paljon käytännöllisempää. Yhä useampia esineitä ja palveluita tarjotaan erityisinä tarjouspyyntöinä muiden esineiden ja palveluiden vastineeksi. Näitä potentiaalisia liiketoimia mainostetaan laajasti ympäri maailmaa Netissä, mikä lisää niiden likviditeettiä moninkertaisesti.

Yksi vaihtokaupan pääasiallisista haitoista on aina ollut se, kuinka vaikeaa on saada täsmälleen saman tarpeen omaava henkilö vastaamaan toisen tarjousta, kun toinen etsii juuri sitä, mitä ensimmäinen ehdotti vaihdettavaksi. Alkeellinen vaihtokauppa kompastui siihen, että paikallisilla markkinoilla on lähes mahdotonta saada täsmällisesti parit osapuolia, jotka haluavat vaihtaa keskenään. Käteinen ylitti vaihtokaupan rajoitukset, ja sen edut pysyvät vakuuttavina useimmissa liiketoimissa. Kuitenkin laskentatehon valtavat kasvuvedot ja kaupan globalisoituminen kyberavaruudessa vähentävät myös vaihtokaupan haittoja. Mahdollisuus löytää joku, jolla on juuri toisinpäin vastavuoroiset toiveet kuin sinulla, kasvaa dramaattisesti, kun voit hakea välittömästi koko maailman laajuudelta sen sijaan, että rajoittaisit etsintäsi vain paikallisiin verkostoihin.

### Ei väärentämisaltis

Vaikka paperirahoja säilyy varmasti liikkeessä jäljellä olevana vaihtovälineenä köyhille ja tietokoneiden osaamattomille, suurten arvoa edustavien transaktioiden raha yksityistetään. Kybervaluuttaa ei enää nimellistetä pelkästään kansallisten yksikköjen mukaan kuten teollisuuskauden paperiraha, vaan se määritellään todennäköisesti kullan grammojen tai unssien perusteella – yhtä hienojakoisena kuin kulta itsessään – tai se voidaan määritellä muiden todellisten arvon säilyttäjien mukaan. Vaikka eri hinnoittelumittareita käytettäisiin tai jotkut transaktiot pysyisivät nimellistettyinä kansallisissa valuutoissa, kybervaluutta palvelee kuluttajia paljon paremmin kuin koskaan kansallistettu raha. Nopeasti kehittyvä laskentateho vähentää lähes kokonaan vaikeudet säätää hintoja eri vaihtovälineiden välillä. Jokainen transaktio sisältää salattujen satojen numerojen alkulukujonojen siirron. Toisin kuin kultakannan aikana hallitusten liikkeelle laskemat paperirahakuitit, joita voitiin kopioida tahdon mukaan, uuden digitaalisen kultakannan – tai sen vaihtovaihtoehtojen – väärennys on lähes mahdotonta sen perustavan matemaattisen syyn takia, että useiden satojen numeroiden alkulukujen tulon purkaminen on käytännössä mahdotonta. Kaikki kuitit ovat todistettavasti uniikkeja.

Perinteisten valuuttojen, kuten 'punnan' ja 'peson', nimet heijastavat sitä, että ne alun perin syntyivät mittaamalla tiettyjen arvokkaiden metallien painoa. Punnan sterling oli aikoinaan sterlinghopean paino. Lännen paperiraha alkoi varastotilitositteina tai tallelaskinoteina tiettyjen arvokkaiden metallien määristä. Näiden kuitien liikkeelle laskeneet hallitukset huomasivat pian, että niitä voitiin painaa paljon enemmän kuin niitä voitiin todellisuudessa lunastaa metallivarannoistaan. Tämä oli helppoa, sillä yksikään hopea- tai kultatodistus ei paljastanut omistajalleen mitään tietoa todellisesta metallivarannosta. Sarjanumeroiden lisäksi kaikki kuitit näyttivät samanlaisilta – se seikka kiinnosti paitsi väärennettäjiä, myös poliitikkoja ja pankkiireja, jotka pyrkivät hyötymään rahavarannon laajentamisesta.

Kybervaluutan väärennys tällä tavalla on käytännössä mahdotonta, virallisena tai epävirallisena. Digitaalisten kuitien verifioitavuus hylkää tämän klassisen keinon, jolla varallisuutta olisi voitu riistää inflaation kautta. Informaatioaikakauden uusi digitaalinen raha palauttaa vaihtovälineen hallinnan varallisuuden omistajille, jotka haluavat säilyttää sen, sen sijaan että se päätyisi valtiolle, joka pyrkii karkaamaan sen salassa.

### Transaktiokustannukset 'ilmaiselle' rahalle

Tämän uuden kybervaluutan käyttö vapauttaa sinut merkittävästi valtion vallasta. Aiemmin mainitsimme maailman kansallisvaltioiden synkän historian heidän rahojaan arvon säilyttämisessä viimeisen puolen vuosisadan ajan. Yksi yhtään valuuttaa ei ole kärsinyt pienempää inflaatiotappiota toisen maailmansodan jälkeen kuin Saksan markka. Siitä huolimatta 71 prosenttia sen arvosta katosi 1. tammikuuta 1949 ja kesäkuun 1995 lopun välillä. Tänä aikana maailmanvarantovaluutta, Yhdysvaltain dollari, menetti arvostaan 84 prosenttia.[^262]: Tämä on mitta siitä varallisuudesta, jonka hallitukset riistivät hyödyntämällä alueellisia yksinoikeuksiaan laillisena maksuvälineenä.

Huomaa, ettei valuutan arvon heikkenemiselle tai elinkustannusten nimellisen nousun odottamiselle joka vuosi ole mitään sisäsyntyistä välttämättömyyttä. Päinvastoin. Säästöjen ostovoiman ylläpitämisen tekninen haaste on vähäpätöinen. Tämä käy ilmi pelkästään tarkastelemalla kullan pitkän aikavälin ostovoimaa.

Ajanjaksolla 1. tammikuuta 1949 – kesäkuun loppuun 1995, kun parhaat kansallistetut valuutat menettivät lähes kolme neljäsosaa arvostaan, kullan ostovoima nousi itse asiassa. Kuten tohtori Roy W. Jastrom dokumentoi teoksessaan *The Golden Constant*, kulta on säilyttänyt ostovoimansa vain hienovaraisin vaihteluin niin pitkälle kuin luotettavia hintatietoja on saatavilla – Englannin osalta jopa vuoteen 1560 asti.

Kultaan sidotut kansalliset valuutat ovat myös säilyttäneet ostovoimansa, kun sotilaalliset kiireellisyydet eivät olleet hallitsevia. Esimerkiksi Britannian punta sterlingin arvo nousi, sen sijaan että laskisi, suhteellisen rauhallisen 1800-luvun aikana, vaikka se oli vain heikosti sidottu kultaan. Tietoajan uudet, valtavat poliittiset ja teknologiset olosuhteet mahdollistavat nyt vahvan yhteyden – toisin kuin kultakannan heikko yhteys – sillä kuluttajien käytettävissä on nyt entistä parempaa informaatiota ja laskentatehoa.

> 'Uhka siitä, että heidän koko liiketoimintansa katoaisi nopeasti, jos he epäonnistuivat täyttämään odotukset (ja miten mikä tahansa valtion organisaatio varmasti käyttäisi tilaisuutta hyväkseen raaka-ainehintojen kanssa leikkiessään!) tarjoaisi paljon vahvemman suojan kuin mikään, mitä voitaisiin kehittää valtion monopolia vastaan'[^263]: - *FRIEDRICH A. VON HAYEK*

### Privatizing Money

Friedrich von Hayek väitti vuonna 1976, että kilpailevien yksityisten valuuttojen käyttö poistaisi inflaation.[^264]: Ilman lainkäyttöalueen sisäisiä laillisen maksuvälineen vaatimuksia, jotka pakottaisivat hyväksymään inflaatiota kärsivän valuutan, Hayekin mukaan markkinakilpailu pakottaisi yksityiset valuuttojen liikkeellelaskijat säilyttämään vaihtovälineidensä arvon. Jokainen yksityisen valuutan liikkeellelaskija, joka ei pysty ylläpitämään sen arvoa, menettäisi pian asiakkaansa. Salatun kyberkahan kehitys tuo Hayekin logiikan elävästi esiin.

"Free banking" -teoria, kuten sitä kutsutaan, ei ole pelkästään hypoteettinen akateeminen spekulaatio. Yksityiset kilpailevat valuutat kiersivät Skotlannissa 1700-luvun alusta vuoteen 1844 saakka. Tuona aikana Skotlannissa ei ollut keskuspankkia, ja pankkitoimialle pääsemiseen liittyi hyvin vähän sääntöjä tai rajoituksia. Yksityiset pankit ottivat talletuksia ja liikkeelle laskivat omia valuuttojaan, joita taataankin kullan palkkiolla. Kuten professori Lawrence White on dokumentoinut, tämä järjestelmä toimi hyvin – se oli vakaampi ja siihen liittyi vähemmän inflaatiota kuin Englannissa samana aikana käytetty hyvin säännelty ja poliittisesti latautunut pankki- ja rahajärjestelmä.[^265]: Financial Timesin Michael Prowse tiivisti Skotlannin vapaan pankkitoiminnan kokemuksen seuraavasti: 'Huijausta oli vähän. Ei ollut todisteita liiallisesta setelien liikkeellelaskusta. Pankeilla ei yleensä ollut joko liian suuria tai liian pieniä varantoja. Pankkiruuhkia esiintyi harvoin eikä ne levinneet tarttuvasti. Vapaat pankit ansaitsivat kansalaisten kunnioituksen ja loivat vakaan perustan talouskasvulle, joka ylitti Englannissa kyseisellä ajanjaksolla koetun kasvun.'[^266]:

Mikä toimi hyvin 1700- ja 1800-lukujen teknologisissa olosuhteissa, toimii vielä paremmin 2000-luvun teknologialla. Pian sinulla on mahdollisuus käydä kauppaa yksityiseltä yritykseltä tulevalla digitaalisella rahalla, jota liikkeelle lasketaan samalla tavalla kuin *American Express* liikkeelle laskee matkustustarkistuksia käteiselle kuitteina. Instituutio, jolla on suurempi maine kuin millään valtiolla – esimerkiksi johtava kaivosyhtiö tai *Swiss Bank Corporation* – voisi luoda salattuja kuitteja tiettyjen kullan määrien tai jopa yksilöllisten palkkien osalta, joita tunnistetaan molekulaaristen allekirjoitusten avulla ja mahdollisesti koristellaan hologramein. Näitä kuitteja vaihdellaan sitten rahana, melkein ilman mahdollisuutta väärentämiselle tai inflaatiolle.

Uusi digitaalinen kulta ratkaisee monet käytännön ongelmat, jotka ovat aiemmin estäneet kullan suoran käytön rahana. Enää ei ole hankalaa, kömpelöä tai vaarallista käydä kauppaa suurilla kullan summilla. Digitaaliset kuitit eivät ole liian painavia kantaa, sillä niiden ainoa fyysinen olemassaolo näkyy hienostuneina tietokonekoodin kuvioina. Myöskään digitaalisten kuittien jakaminen tarpeeksi pieniksi yksiköiksi, jotta jopa mikromaksuja voisi suorittaa, ei ole vaikeaa. Fyysisen kullan ohuen lastun, joka olisi tarpeeksi pieni maksamaan yhden chiclet-purukumin, voisi pian helposti sekoittaa yhteen sen, joka kustantaisi kahden chicletin hinnan. Mutta tietokoneelle näiden digirahan nimellisarvojen erottaminen on yhtä helppoa kuin erottaa kirkan, pienoishirven ja sarvikuonon kokoisia yksiköitä.

Digitaalisen rahan kyky toteuttaa mikromaksuja mahdollistaa uusien liiketoimintamallien syntymisen, joita aiemmin ei olisi voinut olla olemassa – erityisesti sellaisia, jotka erikoistuvat matalan arvon informaation jakeluun. Tiedon myyjät saavat tästä nyt korvauksen suoraveloituksilla toimivien rojaltimaksujärjestelmien kautta, jotka voittavat aiemmin huolestuttavat transaktiokustannukset. Kun laskutuskustannukset ylittävät transaktion arvon, kyseistä kauppaa todennäköisesti ei synny. Kyberrahan käyttö mahdollistaa erittäin edullisen, samanaikaisen laskutuksen, jossa tileiltä veloitetaan käytön mukaan. Esimerkiksi kuvitellessasi, saatat maksaa rojaltina kolmasosan pennistä Bill Gatesille tai kenelle tahansa, joka omistaa Louvre-museon virtuaalitodellisuusoikeudet – ja tämä kerrotaan tuhannella tavalla. Virtuaalitodellisuus luo lähes rajattomat lisensointimahdollisuudet, joista kuitenkin peritään vain mikrorojaltimaksuja. Eräänä päivänä pystyt toistamaan vuoden 1969 World Series –ottelun kolmannen pelin ja maksamaan mikrorojaltimaksuja pelaajille, joiden kuvia käytetään saadaksesi virtuaalitodellisuutesi näyttämään todelliselta.

## Inflaation poistaminen

Huolimatta näistä mahdollisuuksista, uuden digirahan seurauksista merkittävin tulee varmasti olla inflaation loppu ja rahoitusjärjestelmän velkatason keveneminen. Taloudelliset vaikutukset ovat syvälliset. Kuten esitimme teoksissa *Blood in the Streets* ja *The Great Reckoning*, kahdennen vuosisadan inflaation nousu oli tiiviisti sidoksissa maailman valtasuhteisiin. Kasvavat väkivallan tuotot määräsivät jyrkästi korkeampia sotilaallisia menoja, mikä puolestaan vaati entistä aggressiivisempia toimia varallisuuden riistämiseksi. Hallitukset huomasivat voivansa käytännössä määrätä vuosittaista varallisuusveroa kaikille, joilla oli saldot omissa kansallisissa valuutoissaan. Tätä vuosittaista varallisuusveroa valuuttanhaltijoilta voidaan myös pitää transaktiomaksuna, jolla käyttäjät saavat pitää varallisuutensa kätevässä muodossa liikkeellelaskijoiden tarjoamana.[^269]

Inflaation ajatteleminen transaktiomaksuna valuutan pitämisen mukavuudesta saattaa tuntua erikoiselta, mutta mieti sitä tarkkaan. Teollisuuden aikakaudella totumme ajatukseen, että valuutan tarjoaminen on palvelu, josta suoraan ei makseta, minkä vuoksi unohdimme helposti sen, että dollarien, pesojen, punnan ja frangien liikkeellelaskijat – toisin sanoen hallitukset – vaativat meidän maksavan, ja maksamaan kalliisti – inflaation kautta. Tämän inflaatiomaksun vuotuinen osuus vaihteli viimeisen puolivuosisadan aikana saksalaisen markan kohdalla alhaisimmillaan 2,7 prosentista aina lähes 100 prosenttiin. Esimerkiksi vuosien 1960 ja 1991 välillä, kun presidentti Menem käynnisti Argentiinan valuuttaneuvoston uudistuksen, inflaatio poisti seitsemäntoista nollaa peräkkäisistä argentiinalaisista valuuttaversioista. Jos kaikki maailman varallisuus olisi muunnettu vuonna 1960 argentiinalaisiksi pesoiksi ja haudattu, niiden kaivaminen esiin vuonna 1991 ei olisi ollut vaivan arvoista.

Argentiinan esimerkki on ennakoiva merkki seuraavalle vuosituhannelle. Muita valtioita ei enää pääse pakoon inflaation empaattisia vaikutuksia, aivan kuten Argentiina ei enää voi. Inflaatiolla oli toinen vetovoimatekijä teollisuuden aikana, jolloin hinnat ja palkat olivat alaspäin jäykkiä. Maltillinen inflaatio lisäsi tuotantoa alentamalla reaalipalkkoja, ja hinnat saattoivat kärsiä muiden maiden tuomasta luottorajoituksesta. Yksityistä rahaa ei voida inflaatata kilpailupaineiden vuoksi.

Inflaation loppuminen poistaa ne verhoillut voitot, joita inflaatio aiemmin antoi valuutan monopolistisille liikkeellelaskijoille. Jos kaikki rahan liikkeellelaskun peittämä voitto häviää, tarvitaan uusi maksutapa, jolla liikkeellelaskijat saadaan korvattua suoraan. Uuden rahajärjestelmän käyttö sisältää siten todennäköisesti selkeämmin ilmaistun transaktiomaksun, ehkä noin 1 prosentin vuotuisena. Tämä on pieni hinta verrattuna siihen vuosittaiseen inflaatiopolitiikkaan, joka valtioiden toimesta on asetettu 2,7 prosentista aina 99 prosenttiin. Sitäkin enemmän, kun on todennäköistä, että yleiset hinnat tulevaisuudessa laskevat, kun monopolit rappeutuvat ja kilpailu kiristyy maailmanlaajuisesti.

### Contracting leverage

Digitaalisen rahan käyttöönotto ei ainoastaan lopeta inflaatiota lopullisesti, vaan se supistaa myös vipuvaikutusta maailman pankkijärjestelmissä. Kyky, jolla ihmiset kaikkialla pystyvät ohittamaan sääntelyviranomaiset ja siirtämään varojaan suoraan Internetin kautta, on täysin ennennäkemätön seuraus markkinoiden globalisaatiosta. Tämä ilmiö on minkään hallituksen säädettävissä. Kun hallitukset eivät enää voi devalvoa valuuttaa painamalla rahaa tai huijata säästäjiä laajentamalla luottoa vangituissa pankkijärjestelmissä mielivaltaisesti, ne menettävät suuren osan epäsuorasta kyvystään saada resursseja käsiinsä.

### Higher interest rates

Tämä luo ilmeisen dilemma suurimmalle osalle länsimaisia hallituksia. Ne kohtaavat jyrkkiä verotulojen laskuja ja rahajärjestelmästä käytännössä häviävän vipuvaikutuksen. Samanaikaisesti ne säilyttävät teollisuusajan perintönä saamansa rahoittamattomat velat ja turhuttuneet odotukset sosiaalisista menoista. Tuloksena on voimakas finanssikriisi, johon liittyy monia epämiellyttäviä sosiaalisia sivuvaikutuksia – näitä tarkastelemme myöhemmissä luvissa. Tämän siirtymäkriisin taloudellisiin seurauksiin todennäköisesti kuuluu kertaluonteinen nousu reaalikoroissa. Velallisille tulee tiukentua, kun vanhan järjestelmän pitempiaikaiset velat likvidoidaan, ja helpotetuilla luotoilla varustetut lainat hupenevat.

### Altered by competition

Kilpailun vaikutuksesta tapahtuu muutoksia.

Hallitukset, jotka kohtaavat vakavaa kilpailua valuuttamonopolioilleen, pyrkivät todennäköisesti asettamaan alhaisempia hintoja maksullisille kybervaluutoille kiristämällä luotonantoa ja tarjoamalla säästäjille korkeampia reaalituottoja käteisvaroista kansallisissa valuutoissa. Jotkut hallitukset saattavat jopa pyrkiä käyttämään kultaa rahana toisen keinona vastata yksityisvaluuttojen kilpailuun, ajatellen saavansa korkeampia rahapainovoittoja löyhästi kontrolloidulla 1800-luvun kultakannalla kuin jos ne sallisivat kansallisen valuuttansa kokonaan syrjäytyä kaupallisen kybervaluutan toimesta. Kaikki hallitukset eivät kuitenkaan reagoi samalla tavalla. Ne, joiden alueilla tietokoneiden käyttö ja nettiin osallistuminen ovat vähäisiä, saattavat valita vanhanaikaisen hyperinflaation kybertalouden alkuvaiheissa. Tämä ei mahdollista näiden hallitusten saada kiinni rikkaiden käteisvaroista, vaan se purkaa resursseja niiltä, joilla on vähän varallisuutta tai pääsyä kybertalouteen. Tällaisia taktiikoita käyttävät hallitukset saattavat kuitenkin ottaa kansainvälisesti lainoja kybervaluutassa.

Toiset hallitukset saattavat sopeutua informaatiotalouden tarjoamiin mahdollisuuksiin ja helpottaa paikallisia transaktioita kybervaluutassa. Ne lainkäyttöalueet, jotka ensimmäisinä tunnustavat digitaalisten allekirjoitusten pätevyyden ja tarjoavat paikallisen tuomioistuimen toimeenpanon kybervelkojen maksamattomuuden vuoksi, hyötyvät suhteettomasta pitkäaikaisen pääomalainojen myöntämisen noususta. Ilmiselvää on, ettei kybervaluuttaa ole saatavilla pitkäaikaisiin luottoihin alueilla, joilla paikalliset tuomioistuimet asettavat rangaistuksia tai sallivat velallisten maksukyvyttömyyden ilman oikaisumahdollisuutta.

### Tuottokuilu

Luottojen kriisien, kansallisten rahaviranomaisten kilpailullisten sopeutumisien ja kybervaluutan lainanannossa esiintyvien varhaisten siirtymävaikeuksien yhdistelmä johtaa tuottokuiluun informaatiotalouden alkuvaiheissa. Kybervaluutta maksaakin todennäköisesti alempia korkoja kuin kansalliset valuutat ja kantaa mahdollisesti myös nimenomaisia transaktiokuluja. Näitä ilmeisiä haittoja digitaalisten rahavarojen hallussapidossa tasapainottaa parantunut suoja tappioita vastaan, joita aiheutuu saalistavien verojen ja inflaation vuoksi. Koska se on todennäköisesti kultaan sidottu, kybervaluutta hyötyy myös kullan arvonnoususta. Kullan hinta nousee todennäköisesti merkittävästi suhteessa muihin hyödykkeisiin, riippumatta siitä, mikä vaihtoehtoinen hallituksen politiikka on vallalla. Miksi? Kullan reaalihinta nousee lähes aina deflaation aikana. Deflaatio heijastaa lopulta likviditeetin puutetta. Kulta on likviditeetin ylin muoto.

### Teollisajan deflaatio

Korkeammat reaalikorkot kaikkialla kiihdyttävät kalliiden, tuottamattomien toimintojen likvidointia ja vähentävät tilapäisesti kulutusta. Käsittelimme luottokiertojen logiikkaa ja niiden purkautumista kirjassa *Blood in the Streets* ja *The Great Reckoning*, joten emme toista näitä argumentteja tässä. Riittää sanottakoon, että deflaatiopainotteinen ympäristö saattaa jatkua jonkin aikaa, aiheuttaen pahemmat seuraukset Pohjois-Amerikan ja Länsi-Euroopan kalliiden teollisuustalouksien osalta kuin Aasian ja Latinalaisen Amerikan matalakustanteisten talouksien.

### Alhaisempia korkoja pitkällä aikavälillä

Vaikka kybertalouden syntymisen alkuvaiheen seurauksena todennäköisesti nousevat korot, pitkäaikainen vaikutus on täysin päinvastainen. Säästäjien verojen jälkeiset tuotot kasvavat jyrkästi, kun resurssit pääsevät hallitusten otteesta. Resurssien käytön tehokkuuden dramaattinen parantuminen ja pääoman vapautuminen etsimään maailmanlaajuisesti korkeimpia tuottoja pitäisi nopeasti kompensoida siirtymäkriisin alkuvaiheessa menetetyn tuotannon.

### Sijoittajien kontrolli pääomasta

Tavanomaiset ajattelijat, jotka tarkastelevat argumenttiamme tässä vaiheessa, päätyisivät siihen, että johtavien valtioiden tulonjakaantumisen romahdus tuhoaisi maailman taloudellisesti. Älä usko sitä. Emme kiistä tosiasiaa, että siirtymäkriisi olisi todennäköinen. Mutta näkemys siitä, että valtio parantaisi talouden toimintaa massiivisella resurssien uudelleenjaolla, on aikamatka, lähes uskonasia, joka vastaa keskiajan lopun laajalle levinneitä taikauskomuksia, joiden mukaan paastoaminen ja ruoskiminen olivat hyödyllisiä yhteisölle. Ei tule unohtaa, että hallitukset tuhlaavat resursseja suuressa mittakaavassa. Resurssien tuhlaaminen tekee sinut köyhäksi. Resurssien käytön tehokkuuden dramaattinen paraneminen syntyy, kun hallitusten perinteisesti haltuunotto tuloksista siirtyy sen sijaan todellisten lahjakkuuksien hallintaan.

Kymmeniä miljardeja, lopulta satoja miljardeja dollareita hallitsee satoja tuhansia, sitten miljoonia suvereenisia yksilöitä. Nämä maailman varallisuutta hoitavat uudet johtajat osoittautuvat todennäköisesti paljon taitavammiksi resurssien hyödyntämisessä ja investointien toteuttamisessa kuin poliitikot. Ensimmäistä kertaa historiassa megapoliittiset olosuhteet antavat kykenevimmille sijoittajille ja yrittäjille – eivät väkivallasta erikoistuneille – lopullisen vallan pääoman yli. Ei ole kohtuuttoman odottaa, että tämän hajautetun, markkinavoimaisen investoinnin tuottoprosentit voisivat olla kaksinkertaiset tai jopa kolminkertaiset verrattuna niihin vaatimattomiin tuottoihin, joita kansallisvaltioiden poliittisesti ohjatut budjettijaot ovat tarjonneet. Ei ollut epätavallista, että 1900-luvun viimeisten vuosikymmenten lopulla minkä tahansa maan hallituksen investoinneista löytyi esimerkkejä, joiden tulokset olivat olennaisesti negatiivisia. Viitimme virallisiin venäläisiin tilastoihin uudistetun *The Great Reckoning* -kirjan marraskuulta 1992, joissa ehdotettiin, että koko Venäjän talous “oli arvoltaan vain 30 miljardia dollaria, alle kolmasosa raaka-aineidensa arvosta. Johtuen tästä, Venäjän talouden kokonaistuotos kolminkertaistuisi yli, jos kotimainen valmistus- ja palvelutalous suljettaisiin kokonaan. Sen sijaan, että se lisäisi arvoa, se vähentäisi sitä.” [^267]

Merkittäviä tehokkuushyötyjä voisi syntyä, kun saalistukseen ja sen saaliista elämiseen käytettyjen resurssien osuutta vähennetään. Jos suojelun hinnoittelu asetettaisiin kilpailulliselle pohjalle niin, että paikalliset monopolit kilpailisivat asiakkaista hinnan ja laadun perusteella, potentiaalisesti valtavia tehokkuushyötyjä voitaisiin saavuttaa. Tällöin odotettavissa olisi huomattavasti alhaisemmat verolakien määräykset sekä vähemmän resurssien ja vaivan tuhlausta poliittisessa toiminnassa, joka ei enää tuottaisi entuudestaan valtavia osinkoja.

Luopuisivatko äänestäjät mielellään poliittisista tuotoista, joihin he ovat tottuneet? Tätä kysymystä käsittelemme laajasti muualla, mutta yksinkertainen vastaus on, että meillä ei ehkä ole valinnanvaraa. Kukaan ei nykyään protestoi sateesta tai kuivuudesta, vaikka ne olisivat taloudellisesti vahingollisia tai epämiellyttäviä. Edes rikollisluonteiset eivät ota köyhiä panttivankeina ja vaadi valtavaa maksua kuolemantuomiolla. Jos poliitikoiden olisi mahdotonta saada resursseja uudelleenjaon mahdollistamiseksi, yleisö saattaisi reagoida rationaalisesti ja unohtaa politiikan – aivan kuten hyväntahtoiset ihmiset lakkasivat järjestämästä katumuksen marssia, kun keskiaika päättyi.

[^267]:  
[^268]:  



[^245]: Perry Barlow, 'Thinking Locally, Acting Globally,' *Time*, 15. tammikuuta 1996, s. 57.

[^246]: Ibid.

[^247]: M. C. Seymour, toim., Mandeville: Travels (Oxford: *Oxford University Press*, 1968), s. 122.

[^248]: R. C. Johnson, 'The Transportation of Vagrant Children from London to Virginia, 1618-1622,' teoksessa H. S. Reinmuth, toim., Early Stuart Studies (Minneapolis: *University of Minnesota Press*, 1970), s. ~43–44, lainattu Jutte, op. cit., s. 168.

[^249]: John Dos Passos, The Big Money (New York: *Harcourt, Brace & Co.*, 1936).

[^250]: Clarke, op. cit., s. 29.

[^251]: Lainattu teoksessa Kline and Burstein, op. cit., s. ~05.

[^252]: Clarke, op. cit., s. 20.

[^253]: Ibid.

[^254]: Ibid., s. 21.

[^255]: Lane, 'Economic Consequences of Organized Violence', op. cit., s.404.

[^256]: James Bennet, 'The Information Revolution and the Demise of the Income Tax', Strategic Investment, marraskuu 1994, s.11–12.

[^257]: Lane, 'Economic Consequences of Organized Violence', op. cit., s.404.

[^258]: Abu-Lughod, op. cit., s.177.

[^259]: Lainattu Henry Mark Holzerin teoksesta *Governments' Money Monopoly* (New York: Books in Focus, 1981), s.4.

[^260]: Abu-Lughod, op. cit., s.332.

[^261]: Friedrich A. von Hayek, *The Denationalization of Money* (Lontoo: Institute of Economic Affairs, 1976), s.47.

[^262]: Katso luku 1, huomautus 6.

[^263]: Hayek, op. cit., s.40.

[^264]: Ibid.

[^265]: Katso Lawrence White, *Free Banking in Britain* (Lontoo: *Institute of Economic Affairs*, 1995).

[^266]: Michael Prowse, 'Bring Back Gold,' *Financial Times*, 5. helmikuuta 1996, s. 12.

[^267]: Davidson ja Rees-Mogg, op. cit., s. 203.

[^268]: Lane, 'Economic Consequences of Organized Violence,' op. cit., s. 413.

[^269]: Inflaatio oli teollisuuskaudella vieläkin houkuttelevampaa silloin, kun hinnat ja palkat eivät mukautuneet alaspäin. Kohtuullinen inflaatio lisäsi tuotantoa alentamalla reaalipalkkoja ja -hintoja.

::: {.content-visible when-format=latex}

\setsubtitle{Tulonhankintakyvyn vallankumous maailmassa ilman työpaikkoja}

:::