# Demokratian hämärä hetki

> "Demokraattiset poliittiset järjestelmät ovat historiallisesti suhteellisen uusia. Ne olivat lyhytaikaisesti olemassa Kreikassa ja Roomassa, ja ilmestyivät uudelleen 1700-luvulla, alle 200 vuotta sitten. ... Hylkäyksen sykli on nyt saattanut taas alkaa."[^430] - *WILLIAM PFAFF*

Ei ole mikään salaisuus, että demokratia on ollut suhteellisen harvinaista ja lyhytaikaista hallitusten historiassa. Niinä aikoina – sekä muinaisina että nykyaikaisina – missä demokratia on vallinnut, sen menestys on perustunut megapoliittisiin olosuhteisiin, jotka vahvistivat joukkojen sotilaallista voimaa ja merkitystä. Historiantutkija Carroll Quigley tutki näitä ominaisuuksia teoksessaan *Weapons Systems and Political Stability*.[^431]

Ne ovat sisältäneet seuraavia:

1. **Halpoja ja laajalle levinneitä aseita**. Demokratia kukoistaa yleensä silloin, kun hyödyllisten aseiden hankkimiskustannukset ovat alhaiset.

2. **Aseet, joita amatöörit voivat käyttää tehokkaasti**. Demokratia on todennäköisempää, kun kuka tahansa voi käyttää tehokkaita aseita ilman pitkiä koulutusaikoja.

3. **Sotilaallinen etu suuressa määrässä taisteluun osallistuvia jalkaväkisotilaita**. Kuten Quigley huomauttaa, '[J]alkaväen hallitsevuuden kaudet ovat olleet kausia, jolloin poliittinen valta on ollut laajemmin jakautunut yhteisössä ja demokratialle on ollut paremmat mahdollisuudet menestyä.'[^432]

Tämä ei ole millään tavalla kattava luettelo niistä edellytyksistä, joiden puitteissa demokratia voi olla mahdollinen. Jos se olisi, demokratia ei olisi noussut voitokkaaksi järjestelmäksi 1900-luvun lopulla. Voidaan väittää, että aseet olivat teollistuneen aikakauden hämärtyessä kalliimpia kuin koskaan. Monet tehokkaimmista aseista edellyttivät ehdottomasti asianmukaista erikoistumista, jotta niitä pystyttiin käyttämään tehokkaasti. Lisäksi Yhdysvaltojen, sen liittolaisten ja Irakin välillä käyty Persianlahden sota todisti, kuinka haavoittuvia suuret jalkaväkirykmentit ovat – vaikka ne olisivatkaan juovien ja syvävakaiden puolustustukikohtien suojissa. Joten miksi demokratia näennäisesti kykenee kukoistamaan näissä olosuhteissa 1900-luvun viimeisinä vuosina?

## Demokratia, kommunismin veljellinen kaksonen?

Luvussa 5 esitimme paradoksaalisen selityksen, nimittäin että demokratia kukoisti kommunismin veljellisenä kaksosena juuri siksi, että se mahdollisti valtion esteettömän resurssien hallinnan. Tämä johtopäätös saattaa vaikuttaa typerältä teollistuneen aikakauden 'järkevästä ajattelusta'. Emme kiellä, että teollisyhteiskunnan puitteissa demokraattiset järjestelmät ja kommunismi olivat äärimmäisiä vastakohtia. Kuitenkin, kun niitä tarkastellaan megapoliittisesta näkökulmasta – tai informaation aikakauden näkökulmasta – näillä kahdella järjestelmällä oli enemmän yhteisiä piirteitä kuin olisi voinut olettaa.

Tilanteessa, jossa asevarustelu oli groteskein kalliilla, demokratiasta tuli päätöksentekomekanismi, joka maksimoi valtion resurssien hallinnan. Aivan kuten valtiollinen sosialismi, demokraattiset järjestelmät tarjosivat valtavia summia rahoittaakseen massiivisen sotilasjärjestelmän. Erotuksena oli se, että demokraattinen hyvinvointivaltio siirsi vielä enemmän resursseja valtion käsiin kuin valtiolliset sosialistiset järjestelmät kykenivät – mikä on merkittävää, koska valtiolliset sosialistiset ja kommunistiset järjestelmät väittivät omistavansa käytännössä jokaisen arvokkaaksi katsotun omaisuuserän.

Objektiivisesti tarkasteltuna demokraattinen valtio toimi pelkästään resurssien keräysmekanismina paremmin kuin valtiollinen sosialismi rikastaakseen valtiota. Kuten aiemmin selitimme, demokratia tarjosi sotilaalle huomattavasti enemmän rahaa, sillä se oli yhteensopiva yksityisomistuksen ja kapitalistisen tuottavuuden kanssa.

Valtiollinen sosialistinen järjestelmä perusti toimintansa siihen oppiin, että valtio omisti kaiken. Demokraattinen hyvinvointivaltio taas asetti aluksi rajoitetummat vaatimukset; se väitti sallivansa yksityisomistuksen, vaikkakin ehdollisessa muodossa, ja näin se pystyi hyödyntämään tehokkaampia kannustimia tuotannon mobilisoimiseen. Sen sijaan, että kaikki hoidettaisiin huonosti alusta alkaen, länsimaiden demokraattiset hallitukset antoivat yksilöiden omistaa omaisuutta ja kerryttää varallisuutta. Vasta tämän jälkeen kansallisvaltiot puuttuivat asiaan verottamalla suuren osan siitä.

Sana "Large" tulee kirjoittaa isolla. Esimerkiksi vuonna 1996 Yhdysvalloissa liittovaltion elinkaariverokanta oli 73 senttiä dollarilta. Yritysten omistajille, jotka saivat tulonsa osinkoina, verokanta oli 83 senttiä dollarilta. Ja jokaiselle, joka pyrki jättämään tai antamaan rahaa lapsenlapsilleen, liittovaltion verokanta oli 93 senttiä dollarilta. Kun lisäksi otetaan huomioon osavaltion ja paikalliset verot, demokraattinen hallinto kaikilla tasoilla takavarikoi leijonanosaisen jokaisesta Yhdysvalloissa ansaitusta dollarista. Saalistavat verokannat tekivät demokraattisesta valtiosta käytännössä kumppanin, jolla oli kolme neljäsosaa – yhdeksän kymmenesosaa – kaikista tuloista. Tämä ei tietenkään ollut sama asia kuin valtiollinen sosialismi, mutta se oli läheinen sukulaisuus.

Demokraattinen valtio selvisi pidempään, koska se oli joustavampi ja kykeni keräämään paljon enemmän resursseja verrattuna niihin, jotka olivat saatavilla Moskovassa tai Itä-Berliinissä.

"Inefficiency, where it counted"

Olemme kuvanneet demokratian megapoliittisia etuja voimakkaan hallituksen päätöksentekosääntönä nimellä "tehottomuutta siellä, missä se merkitsi." Verrattuna kommunismiin, hyvinvointivaltio oli todellakin paljon tehokkaampi järjestelmä. Mutta verrattuna aitoon laissez-faire -keikkaan, kuten Hong Kongiin, hyvinvointivaltio osoittautui tehottomaksi. Hong Kongin kasvuvauhdit olivat upeita, mutta niiden ydinosa piili juuri siinä, että Hong Kongin asukkaat – eivät hallitus – pystyivät kertaamaan 85 prosenttia nopeamman kasvun tuomista hyödyistä.

Tietenkin Hong Kong ei ole demokratia. Itse asiassa se edustaa sellaista ajatusmallia oikeudellisesta järjestelmästä, jonka odotamme kukoistavan informaatiokaudella. Teollisuusajalla Hong Kongilla ei ollut tarpeen olla demokratia, sillä se vapautui epämiellyttävästä velvollisuudesta kerätä resursseja tukemaan pelottavaa sotilaallista rakennelmaa. Hong Kong oli ulkopuolelta puolustettu, joten se pystyi ylläpitämään todella vapaata taloutta.

Nimenomaan kyky kerätä resursseja teki demokratiasta ylimpää teollisuuskauden megapoliittisissa olosuhteissa. Massademokratia kulki käsi kädessä teollistumisen kanssa. Kuten Alvin Toffler on sanonut, massademokratia "on massatuotannon, massajakelun, massakulutuksen, massakoulutuksen, massamedian, massaviihteen ja kaiken muun poliittinen ilmentymä."[^433]

Kun informationaalinen teknologia syrjäyttää massatuotannon, on luonnollista odottaa massademokratian hämärtymistä. Se ratkaiseva megapoliittinen pakote, joka sai massademokratian triumpfoimaan teollisuusajalla, on kadonnut. Siksi on vain ajan kysymys, ennen kuin massademokratia kulkee samalle tielle kuin sen sisarpuoli, kommunismi.

### Massademokratia ei sovi informaatiokauteen

Hetken pohdinta osoittaa, että informaatiokauden teknologia ei itsessään ole massatekniikkaa. Sotilaallisessa merkityksessä, kuten olemme todenneet, se avaa mahdollisuuksia "älyaseisiin" ja "informaatiovaaraan", missä "logiikkapommit" voisivat sabotoida keskitettyjä komentokeskuksia. Tietotekniikka ei ainoastaan viittaa erikoistuneiden operoimien aseiden täydellisyyteen, vaan vähentää myös sodankäynnin ratkaisevaa tehokkuutta, parantaen puolustuksen suhteellista asemaa. Mikroteknologia mahdollistaa merkittäviä yksilöiden sotilaallisia voimanlisäyksiä samalla, kun se vähentää massojen jalkaväkirykmenttien merkitystä.

Kuten *Rand Corporation* raportoi puolustusministerille: "Yhdistetyillä verkoilla voi olla alttiutta hyökkäyksille ja häiriöille, ei ainoastaan valtioiden vaan myös ei-valtiollisten toimijoiden, mukaan lukien hajanaiset ryhmät ja jopa yksittäiset henkilöt, toimesta."[^434] Tämä viittaa siihen, että kybersota tuo esiin keskitettyjen järjestelmien mittakaavaetuustehottomuudet.

Randin asiantuntijoiden mukaan "tietoperusteiset menetelmät tekevät maantieteellisestä etäisyydestä merkityksettömän; mantereen Yhdysvalloissa sijaitsevat kohteet ovat yhtä haavoittuvia kuin teatterialueen agentit."[^435] Aiemmin suuren, supervallan kansallisvaltioiden, kuten Yhdysvaltojen, alueella asuminen toi turvallisuuden tunnetta, mutta informaatiokaudella vallan keskittymisen logiikka saattaa kääntyä päinvastaiseksi. Peoria saattaa sijaita kaukana mistä tahansa mahdollisesta sotilasrintamasta, mutta se ei enää ole turvassa kyberhyökkäyksiltä lähes mistä tahansa potentiaalisesta vastustajasta. Asuminen supervallan rajoissa tarkoittaa käytännössä asettumista suoraan kohteeseen. Sen sijaan, että paikallisyhteisöt yhdistyisivät, ne voivat parantaa turvallisuuttaan hajautumalla. Kybersodan tulo lisää keskitettyjen komentokeskusten haavoittuvuutta samalla, kun se parantaa hajautettujen järjestelmien kilpailukykyä.

Näiden mekanismien aiheuttama palautesilmukka voi nopeuttaa hajautumisprosessia. Randin asiantuntijoiden mukaan, jotta kansallisvaltioiden myöhemmissä vaiheissa kehittyneiden komentokeskusten kyberhyökkäyshalttuutta voitaisiin vähentää, hallituksen on pakko lisätä "uusien ohjelmistojen salausmenetelmien hyödyntämistä." Tämä tekee pääosin yksityissektorin järjestelmistä huomattavasti vähemmän alttiita sabotaasille ja kiihdyttää kovien salaustekniikoiden kaupallista leviämistä, mikä auttaa vapauttamaan ne valtion hallinnasta. Myös tämä antaa potkua hajautumiselle. Kuten aiemmin argumentoitimme, se vauhdittaa resurssien leviämistä kyberavaruuteen, jonne ne ovat politiikan ulottumattomissa.

Lopulta tämä tarkoittaa massademokratian loppua, erityisesti sen hallitsevassa muodossa, eli edustuksellisessa huonossa hallinnossa, olipa kyse sitten kongressimallisesta tai parlamentaarisesta järjestelmästä.

## virheellisen edustuksen megapolitiikka

Kun megapoliittiset olosuhteet muuttuvat merkittävästi, kuten ne nyt muuttuvat, myös hallinnon järjestäytyminen muuttuu väistämättä. Itse asiassa edustuksellisen hallinnon muoto on perinteisesti ollut raakavoiman jakautumisen tulos. Tämä käy ilmi juuri siitä, että edustajat valitaan maantieteellisten alueiden perusteella sen sijaan, että heidät valittaisiin jotenkin muulla tavoin.

Ajattelepa hetki. Periaatteessa lainsäädäntöelin olisi yhtä demokraattinen, jos sen jäsenet valittaisiin minkä tahansa mielivaltaisen väestönjakautumisen mukaan. Parlamenttikaistat tai kongressin vaalipiirit voisivat perustua syntymäpäiviin tai jopa aakkosjärjestykseen. Jokainen, joka on syntynyt 1. tammikuuta, voisi äänestää yhdestä ehdokaslistasta. Toisia, jotka ovat syntyneet 2. tammikuuta, toisesta. Tai jokainen, jonka nimi alkaa kirjaimista "Aa"–"Af", voisi valita yhdestä ehdokaslistasta, ja niitä, joiden nimet alkavat kirjaimella "Ag", toisesta. Ja niin edelleen.

Tällaista järjestelmää ei nykyään ole useista syistä. Ensimmäinen ja riittävä syy on se, että 1700-luvulla se oli teknologisesti epäkäytännöllinen. Vielä tärkeämpää on kuitenkin se, että syntymäpäivä- tai aakkosperusteiset vaalipiirit eivät olisi heijastaneet – eivätkä edes lähestyneet – sitä raakavoiman jakautumista, jonka äänestyksen piti silloin ilmetä. Henkilöitä, joilla ei ollut muuta yhteistä kuin sama syntymäpäivä tai nimensä ensimmäiset muutama kirjain, olisi ollut äärimmäisen vaikea koota mihinkään yhtenäiseksi voimakeskukseksi.

### Miksi maantieteelliset poikkileikkaukset ovat tärkeämpiä?

Äänestys todella alkoi sotilaallisen kisajärjestelyn välittäjänä. Ja niin se on edelleenkin, vaikkakin verhottuna ilmentymänä. Tällaiset kisat voidaan järjestää maantieteellisten rajojen mukaan, ja harvemmin sukulaisuuden tai uskonnon perusteella. Niitä ei voi järjestää syntymäpäivien tai nimikirjainten perusteella. Eivätkä ne myöskään järjesty tehokkaasti ammattien mukaan, paitsi jos ammatit rajoittuvat periytyviin ammattikuntiin, kuten intialaiseen kastijärjestelmään, tai ryhmittyvät paikallisesti samalla tavalla kuin maanviljelijät Iowassa.

Nykyisten edustuksen kaavojen ydinajatus on, että ne edustavat maantieteellisesti kertyneitä etuja sen sijaan, että ne perustuisivat johonkin muuhun ulottuvuuteen. Historiallisesti sotilaallinen menestys perustui alueen hallintaan. Kaikki sotilaalliset uhkat ovat syntyneet paikallisesti. Edustukselliset järjestelmät on suunniteltu tarjoamaan erilainen foorumi tämän vallan ilmaisemiseen. Se, että ne väistämättä suosivat paikallisia erityisetuja, on seurausta edustuksen kaavan rakenteesta. Maantieteelliset äänestäjäryhmät ohjaavat edustajia antamaan erityisryhmille etuja yleisten etujen kustannuksella, joita kaikkien maan asukkaiden tulisi jakaa.

### Uusia mahdollisuuksia edessä

Kuten Public Choice -taloustieteilijöiden analyysit ovat osoittaneet, näennäisesti pienet muutokset vaalirakenteessa tai äänestyksen laskentatavassa vaikuttavat merkittävästi ja ennustettavasti lopputulokseen.[^436] Siksi nykyajan poliittisten ilmiöiden opiskelijoiden on oltava syvällisiä perustuslakien opiskelijoita. Tämä on yksi seikoista, joka johdatti meidät katsomaan perustuslakien ulkopuolelle, kohti lopullista metaperustusta, jonka muovaavat kyseisen ympäristön vallitsevat megapoliittiset tekijät.

Teknologinen muutos on jo pyyhkäissyt pois osan niistä perustuksista, jotka rajoittivat äänestyksen maantieteellisiin äänestäjäpiireihin. Kun modernit edustukselliset järjestelmät kehittyivät kahdeksastoista ja yhdeksästoista vuosisadalla, lähes kaikki viestintä oli paikallista. Suurin osa ihmisistä eli ja kuoli muutaman mailin säteestä syntymäkaupungistaan, ja kaiken heidän kaupankäyntinsä ja viestintänsä käytiin paikallisesti. Tänään viestintä on välitöntä maailmanlaajuisesti. Voit tehdä kauppaa viidentuhannen mailin päästä olevankin ihmisen kanssa lähes yhtä vaivattomasti kuin naapurin kanssa. Yhä enemmän talous ylittää maantieteelliset rajoitukset. Yhteiskunta on paljon liikkuvampaa.

Niin myös vauraus on merkittävä tietoyhteiskunnassa. Toisin kuin terästehdasta, tietokoneohjelmaa ei voi helposti joutua sidotuksi paikallisen poliittisen prosessin vaikutuspiiriin. Terästehdasta sen sijaan on tuskin mahdollista siirtää, kun lainsäätäjät päättävät verottaa sitä tai säänellä sen omistajia. Tietokoneohjelman voi lähettää modeemin kautta valon nopeudella minne tahansa maailmassa, ja sen omistaja voi pakata kannettavansa ja lähteä matkalle. Myös tämä heikentää maantieteellisten vaalipiirien megapoliittisia perustuksia.

Analyysimme näkökulmasta merkittävä ongelma, joka kaikissa edustuksellisissa demokraatioissa on yhteinen, on se, että niiden maantieteelliset vaalipiirit ovat väistämättä yli-edustettuina teollisajan yritysten etujen suhteen. "Häviäjät" eli jäljelle jääneet äänestäjät muodostavat ihanteellisen ryhmän, sillä he ovat maantieteellisesti keskittyneitä ja poliittisesti avuntarvitsijoita. Teollisen demokratian historia tämän vahvistaa: uusien teollisuudenalojen "voittajat" olivat kroonisesti ali-edustettuina lainsäädäntöelimissä jopa teollisen aikakauden huippuvuosina 1930-luvulla.[^437] Poliitikkojen taipumus edustaa vakiintuneita, olemassa olevia kilpailijoita – ei niitä uusia yrityksiä tai niiden potentiaalisia asiakkaita, joita voisi vielä syntyä – on luultavasti edustuksellisen hallinnon synnynnäinen ominaispiirre. Kuten Mancur Olson esitti teoksessaan *The Rise and Decline of Nations*, pitkäikäiset teollisuudenalat pyrkivät muodostamaan tehokkaampia "jakaantumiskoalitioita" lobbausta ja poliittisen etujen ajamisesta varten.[^438]

Tämä ongelma suurenee mittaamattomasti tietoyhteiskunnan taloutta tarkasteltaessa. Uuden talouden luovat toimijat ovat entistä laajemmin maantieteellisesti hajautuneita, joten heidän on epätodennäköistä muodostaa riittävästi tiivis keskittymä saadakseen lainsäätäjien huomion, kuten tapahtuu Skotlannin lohenpyydystäjien tai Saskatchewanin vehnäviljelijöiden kohdalla. Todellisuudessa monet uuden talouden dynaamisista henkilöistä eivät todennäköisesti ole edes kaikkein laajemman lainkäyttöalueen kansalaisia, mikä tarkoittaa, että heillä on vain vähän ''ääntä'' edustuksellisten demokratioiden lainsäädäntöprosesseissa. Esimerkkinä voidaan mainita amerikkalaisten matematiikan tohtoreiden maineettomat yritykset estää ulkomaisten matemaatikkojen työpaikat Yhdysvalloissa.[^439] Heidän ulkomaantappoiset esityksensä Kongressille estääkseen työnantajia palkkaamasta ansioiden perusteella saavat liian todennäköisesti huomiota, sillä teollisen aikakauden jäänne, vanhentunut maantieteellinen edustus, ei ota huomioon ulkomaisia matemaatikkoja eikä muita tärkeitä hyvinvoinnin edistäjiä, jotka eivät ole äänestäjiä.

'Miksi ihmiset uskovat demokraattisten instituutioiden laillisuuteen? Tämän kysymyksen vastaaminen on melkein yhtä vaikeaa kuin selittää, miksi ihmiset uskovat tiettyihin uskonnollisiin dogmoihin, sillä kuten uskonnollisissa uskomuksissa, ymmärryksen, epäilyn ja uskon taso vaihtelee laajasti yhteiskunnassa ja ajan myötä.'[^440]  
— JUAN J. LINZ

Harvat ovat alkaneet järjestelmällisesti pohtia teknologian muutoksen seurauksia, jotka rapauttavat teollisuutta ja muuttavat tulonjakoa. Ilmiselvästi demokratia ei todennäköisesti ole muuta kuin resepti laillistetulle loiseläimisyydelle, jos tulot hajaantuvat yhtä laajasti kuin tietoyhteiskunnassa voi tapahtua. Vielä harvemmat ovat huomanneet teollisen hallinnon instituutioiden ja jälkeisteollisen yhteiskunnan megapoliittisuuden välillä piilevän yhteensopimattomuuden. Olipa nämä ristiriidat nimenomaisesti tunnustettuja tai eivät, niiden seuraukset tulevat yhä näkyvämmiksi, kun poliittisen epäonnistumisen esimerkit kasaantuvat ympäri maailmaa. Modernin ajan hallintoinstituutiot heijastavat yhden tai useamman vuosisadan takaisia megapoliittisia olosuhteita; ne selvisivät maaseutuyhteiskunnasta kaupunkiteollisuuteen siirtymisestä, mutta tietoyhteiskunta saattaa edellyttää uusia edustusmekanismeja, jotta voidaan välttää krooninen epätoimivuus ja jopa neuvostotyyppinen romahtaminen.

Voit odottaa näkeväsi monissa maissa epäonnistuneen hallinnon kriisejä, kun poliittiset lupaukset paisuvat ja hallitukset loppuvat luotosta sekä institutionaalisesta tuesta. Lopulta on synnyttävä uusia institutionaalisia muotoja, joiden on kyettävä turvaamaan vapaus uusissa teknologisissa olosuhteissa samalla kun ne antavat äänen ja elämän yksilöiden yhteisille intresseille.

Kaikki tämä viittaa siihen, että 1900-luvulla tunnistamamme massa-demokratia päättyy. Kysymys kuuluu: mikä nousee sen tilalle? Jos ainoa vaihtoehto massa-demokratialle olisi diktatuuri, jossa yksilöllä ei ole sananvaltaa omassa kohtalossaan, voisi olla houkuttelevaa liittyä neo-luddiittien 'kapinaan tulevaisuutta vastaan'.

### Uudet instituutiot

Onneksi diktatuuri ei ole ainoa vaihtoehto massa-demokratialle. Informaatioteknologia mahdollistaa vaihtoehdon. Sen sijaan, että kollektiivinen valinta rajoitetussa ympäristössä, kuten "massatuotannon, massakulutuksen, massakoulutuksen, massamedian, massaviihteen ja muun muun rajoissa", olisi pakollista, informaatioteknologia mahdollistaa aitoa kuluttajavalintaa räätälöidyissä suvereniteettipalveluissa. Tämä onnistuu, koska massatasolla toimiminen ei enää ole välttämätöntä. Uskomme, että Information Age -teknologia synnyttää uusia hallintomuotoja – aivan kuten maatalousvallankumous ja myöhemmin teollistumisaika loivat omat erottuvat yhteiskunnalliset järjestelmänsä.

Millaiset tällaiset uudet instituutiot voisivat olla? Ymmärtääksesi, unohda kaikki, mitä olet lukenut harhaanjohtavasti nimetyistä "poliittisen tieteen" teksteistä. Uuden ajan hallintoa instituutiot ylittävät perinteisen ajattelun rajat. Edistys näihin uusiin instituutioihin on jo alkanut. Ne ovat osittain tunnustamattomia improvisaatioita alikäytettyjen varojen – suvereniteetin hyötyjen – uudelleen järjestämiseksi. Maailman kansallisvaltiot, jotka hermostuneina katsovat taakseen itsenäistymispyrkimyksiä ja voimakkaita devoluutiovoimia, ovat yhdistäneet voimansa luodakseen mahdollisimman vahvan rajojen vakauttamiseen tarkoitetun kartellin. Vaikka uusien valtioiden määrä maailmassa kasvoi 1990-luvulla, se tapahtui pääasiassa kahdessa klusterissa entisten monietnisten kommunistidiktatuurien romahtamisen, muun muassa entisessä Neuvostoliitossa ja Jugoslaviassa, myötä. On huomionarvoista, että myös muut johtavat kansallisvaltiot, mukaan lukien Yhdysvallat, toimivat säilyttääkseen Neuvostoliiton mahdollisimman pitkään. Harvat hallitukset vastaanottivat Jugoslavian hajoamisen lämpimästi – entisten Jugoslavian tasavaltojen itsenäisyys tunnustettiin vasta sen jälkeen, kun irtautujat olivat saaneet itselleen sellaisen sotilaallisesti toimeenpanettavan vallan, että se voitaisiin käytännössä toteuttaa. Johtavat valtiot tyytyivät siihen, että aseettomat tai huonosti aseistetut separatistit teurastettiin serbien aiheuttamien kidutusten seurauksena. Jopa kaukana sijaitseva Kiina, vahva kansallisvaltio, jolla ei ollut suoraa etua Jugoslaviajäännöksen säilyttämisessä, vastusti voimakkaasti pyrkimyksiä saavuttaa itsemääräämisoikeus sortuneille etnisille albaanisille Kosovossa. Ironista kyllä, tämä rajojen vakauttamiseen kohdistuva pakkomielteinen ajattelu ohjaa todennäköisemmin devoluution polkua kohti hajanaista suvereniteettia kuin estää itseään. Haastava vastarinta haavoittuvien kansallisvaltioiden keskuudessa avoimen itsenäistymisen ja poliittisen hajoamisen edessä tekee tunnustetusta suvereniteetista arvokkaan eräänlaisen transsendentaalisen pääoman muodon, jota kyseiset valtiot voivat vapaaehtoisesti hajauttaa ja vuokrata eteenpäin.

Esimerkki siitä, kuinka suvereniteetti voidaan halutusti pilkkoa luodakseen pohjimmiltaan yksityisen, verovapaan toimivallan alueen, on *Agulhas Bay Concession Free Zone*, joka kattaa viisikymmentä neliökilometriä Principe-saarella Länsi-Afrikan rannikon edustalla. Vaikka alue säilyy São Tomé ja Principen demokraattisen tasavallan rajoissa, vyöhykkeen hallinto on yksityistetty. Hallinnointi määräytyy sopimuksen mukaan, jota hallinnoi *WADCO* – West African Development Corporation Ltd. – eteläafrikkalaisena yksityisenä yhtiönä. Vyöhykkeen virallinen kieli ei ole virallinen Tomean kieli, portugali, vaan englanti. Virallinen valuutta ei ole Tomean paikallinen monopolirahaa, vaan dollari – maailman raha, Yhdysvaltain dollari. Turvallisuudesta huolehtiva taho ei ole São Tomé ja Principen demokraattisen tasavallan poliisirykmentti, vaan *WADCO*:n palkkaama yksityinen poliisi. São Tomean kauppalaki ei ole sovellettavissa vyöhykkeen kaupallisiin tapahtumiin, eikä São Tomean tuomioistuimilla ole toimivaltaa. Kaikki erimielisyydet on ratkaistava kansainvälisen välimiesmenettelyn kautta Pariisin *ICC*:n sääntöjen mukaisesti. Hyvin säännösteltyjen ja vähäpätöisten poikkeusten lisäksi São Tomean veroja ei sovelleta vyöhykkeelle, eikä myöskään virallisia monopoleja. Esimerkiksi televiestintä on vyöhykkeellä automaattisesti dereguloitu. Mikäli vuokrasta maksetaan ja noudatetaan konsessiosopimuksen muita ehtoja, *WADCO*:lla on oikeus automaattisesti ja toistuvasti uusia vuokrasopimuksensa yksityisestä, pilkotusta suvereniteetistaan viidenkymmenen vuoden jaksoissa ensimmäisestä uusiutumisajankohdasta lähtien, vuonna 2047.

Sen, mitä *WADCO* on saavuttanut São Tomé ja Principessa, voivat ja tulevat saavuttamaan myös muut eri lainkäyttöalueet. Yksi 2000-luvun todellisista uranuurtajista, Joaquin Aguirre, on luonut vastaavanlaisen yksityisen suvereniteetin vyöhykkeen nimeltä Central Aguirre Portuaria Itä-Boliviassa. Aguirre, multimiljonäärinä, romaanintekijänä ja keksijänä, *United Nations*:in perustajajäsen ja entinen Bolivian tasavallan senaattori, on moninkertainen uranuurtaja. Puolen vuosisadan kuluttua siitä, kun hän auttoi perustamaan *United Nations*:in, Aguirre toimii nyt 2000-luvun suvereenin yksilön prototyyppinä. Hänen *Zona Franca* -alueensa, joka on vapaa useimmista bolivialaisista veroista, tullimaksuista ja sääntelyvaatimuksista, osoittaa tien kohti uutta yksityistettyjen kaupunkivaltioiden muotoa, jonka menestyvät yksilöt tulevat yhä useammin saavuttamaan tietoajan aikana. Se todistaa myös lopullisesti, että massojen elämä – josta usein suurten hallitusten puolustajat ylistävät – voi parantua dramaattisesti vapaakauppa-alueiden käynnistämän talouskehityksen myötä, kuten Señor Aguirren aloittama alue. Ajan myötä de facto -kaupunkivaltioiden määrä maailmassa moninkertaistuu merkittävästi. Todellakin, jos saavutat riittävän taloudellisen itsenäisyyden yksilönä, pystyt saavuttamaan lopullisen itsemääräämisoikeuden, aivan kuten Joaquin Aguirre. Mikäli kukaan muu pilkottu, kaupallistettu suvereniteetin osa ei tarjoa sinulle mukavaa tukikohtaa, voit perustaa oman yksityisen pienvaltiosi – yhtä itsenäisen kuin keskiaikaiset herttuakunnat. Sen sijaan, että riitelisit demagogien ja poliittisten kikkaajien kanssa omaisuutesi saamiseksi massademokratian huutavien käsiin ja jaettavaksi, pystyt perustamaan oman yksityisen hallinta-alueesi.

Massademokratiasta lopulliseen itsehallinnon muotoon, eli yksilön suvereniteettiin, tapahtuva dramaattinen vaiheenvaihdos ei vaadi radikaalia mielipidemuutosta tai ihmeellistä äänestystä, jossa pettymään jääneiden äänestäjien päätös luopua massademokratiasta ratkaistaisi yhdessä. Tällainen vallankumous voi alkaa – itse asiassa se on jo alkanut – huomaamattomasti suvereniteterajoitettujen alueiden vuokraamisen kautta verovapaana vyöhykkeenä, kuten *Zona Francas* ja vapaat satamat osoittavat. Ajan myötä suvereniteetti hajoaa toistuvasti siihen pisteeseen, että sen edelleen jakaminen ei tuota arvoltaan riittävästi kattamaan devolution transaktiokustannuksia. Moore'n lain ja Gilderin korollaarin mukaan, sillä tiedonsiirtonopeus kolminkertaistuu joka vuosi, nykyisellään ei ole perusteita ennakoida devolution-trendin varhaista päättymistä. Päinvastoin, ennakoimme, että valtioiden, jotka nykyisin näyttävät olevan massademokratiassa juurtuneita, ilmeinen solidi voima hajoaa kymmeniä tuhansia pirstaleita muistuttavaksi järjestelmäksi, joka muistuttaa enemmän keskiaikaa kuin modernia teollisuusikää.

Ajan myötä jopa ne valtioiden jäännökset, jotka säilyttävät massademokratian instituutiot, kokevat merkittäviä politiikkamuutoksia uusiin metakonstituutionaalisiin realiteetteihin sopeutumiseksi. Kuten demokraatian vilpitön puolestapuhuja William Keech väittää teoksessaan *Economic Politics: The Costs of Democracy*:[^441] 'Ihmiset oppivat haluamaan sitä, mitä he näkevät olevansa saatavilla, mutta he voivat myös muuttaa mieltään, jos huomaavat etteivät pidä siitä, mitä he halusivat ja mitä he saivat.' Toisin sanoen se, että perinteinen edustuksellinen massademokratia ylistetään kaikkialla 1900-luvun päättymisen kynnyksellä, saattaa toimia myyntisignaalina. Tämä ei kuitenkaan takaa, että kyseiset päätösmenettelyt kestäisivät ajan hammasta edes oman logiikkansa puitteissa. Kun tarkastelet politiikan ulkopuolelle, et juuri löydä todisteita siitä, että johtajat, ylläpitäjät, valmentajat tai muut ammattilaisjohtajat valittaisiin demokraattisesti. Päinvastoin menestyneimmät johtajat palkataan tavallisesti omaisuuden haltijoiden toimesta valintaprosessien kautta, joissa eniten riskiä kantavat saavat epäsuhtaisen ja suhteettoman etuoikeutetun vaikutusvallan päätöksenteossa. Jos demokraattinen valinta todellakin olisi yleismaailmallinen menetelmä pätevien johtajien tunnistamiseksi, sen odotettaisiin rajoittuvan lähes yksinomaan poliittiseen maailmaan. Lyhyesti sanottuna, nykyisten todisteiden perusteella on järkevämpää olettaa, että suvereniteettipalveluiden tarjoaminen on demokratian päätöksenteon hallitsevuuden vuoksi rajoitettua, kuin olettaa toisin – eli että yritys- ja liiketoimintaorganisaatiot kärsivät siksi, että niitä johtavat omaisuuden haltijat eivät valitse johtajiaan äänestyksellä.

2000-luvun puoliväliin mennessä on todennäköistä, että omistusperusteisten, pilkotun suvereniteetin oikeusalueiden yleistyminen on lopullisesti osoittanut omistusperusteisen hallinnon edut. Äänestäjät huomaavat kärsivänsä siitä, että he on rasitettu massademokratian kanssa. Siksi, kuten professori Keech ehdottaa, he alkavat nähdä, että työntekijöiden hallinnon tuomat edut jäävät sen kustannuksille varjoon. He suuntaavat mielensä uudistuksiin. Jopa Euroopan ja Pohjois-Amerikan äänestäjäkunnat, jotka nyt näyttävät olevan niin vahvasti uudistuksia vastaan sitoutuneita, saattavat lopulta äänestää alueidensa muuttamisesta suotuisammiksi omaisuudenhallinnalle. Suurimmistot saattavat halukkaasti – jopa iloisesti – hylätä politiikan farssin ja ottaa tilalle omistuspohjaisen hallinnon, jonka päätarkoituksena on saavuttaa optimaaliset edellytykset sopimusten tekemiselle ja niiden täytäntöönpanolle.

Sen dramaattinen muutos massademokratiasta lopulliseen itsehallintoon eli yksilön suvereniteettiin ei välttämättä edellytä radikaalia yleistä mielipidemuutosta tai ihmeellistä äänestystä, jossa pettymään jääneiden äänestäjien päätös luopua massademokratiasta toteutuu. Tällainen vallankumous voi alkaa – itse asiassa se on jo alkanut – huomaamattomasti vuokraamalla suvereniteetillista aluetta verovapaiden vyöhykkeiden, kuten *Zona Francas* ja vapaiden satamien, käyttöön. Ajan myötä suvereniteetti hajoaa toistuvasti siihen pisteeseen, että sen edelleen jakaminen ei tuota arvoltaan riittävästi kompensoidakseen devoluutiosta aiheutuvia transaktiokustannuksia. Moore'n lain ja Gilderin korollaarin valossa, sillä tiedonsiirtonopeus kolminkertaistuu vuosittain, ei nykyisellään ole perusteita ennakoida devolution-trendin varhaista päättymistä. Päinvastoin ennakoimme, että nykyisin massademokratiassa juurtuneena vaikuttava näennäisen vankka valta hajoaa kymmeniä tuhansia pirstaleita muistuttavaksi järjestelmäksi, joka muistuttaa enemmän keskiaikaa kuin modernia teollisuusyhteiskuntaa.

Vuosisadalla edes valtioiden jäänteet, jotka säilyttävät massademokratian instituutiot, kokevat merkittäviä politiikkamuutoksia sopeutuakseen uusiin metakonstituutionaalisiin realiteetteihin. Kuten *Economic Politics: The Costs of Democracy* -teoksessaan demokraation puolestapuhuja William Keech toteaa, 'ihmiset oppivat haluamaan sitä, mitä he näkevät olevansa saatavilla, mutta he voivat myös muuttaa mieltään, jos huomaavat etteivät pidä siitä, mitä he halusivat ja mitä he saivat.'[^441] Toisin sanoen se, että perinteinen edustuksellinen massademokratia ylistetään kaikkialla 1900-luvun loppua kohti, saattaa olla myyntisignaali – se ei kuitenkaan millään tavalla takaa, että tällaiset päätösmenettelyt kestäisivät ajan hammasta edes omissa rajoissaan. Kun tarkastelet politiikan ulkopuolta, ei juuri löydy todisteita siitä, että johtajat, ylläpitäjät, valmentajat tai muut ammatilliset johtajat valittaisiin demokraattisesti. Päinvastoin menestyneimmät johtajat palkataan tavallisesti omaisuudenhaltijoiden toimesta valintaprosessien kautta, joissa niitä, joilla on suurimmat edut vaakalaudalla, on suhteettoman suuri vaikutusvalta päätöksenteossa. Jos demokraattinen valinta todella olisi yleismaailmallinen menetelmä pätevien johtajien tunnistamiseksi, sen odotettaisiin rajoittuvan lähes yksinomaan poliittiseen maailmaan. Lyhyesti sanottuna nykyisten todisteiden perusteella on järkevämpää olettaa, että suvereniteettipalveluiden tarjoaminen on demokratian hallitsevuuden vuoksi rajoitettua, kuin olettaa päinvastoin – eli että yritys- ja liiketoimintaorganisaatiot kärsivät siksi, että niitä johtavat johtajat ovat omaisuudenhaltijoiden asettamia sen sijaan, että ne olisi valittu äänestyksellä.

Vuosisadan puoliväliin mennessä on todennäköistä, että omistuspohjaisten, pilkottua suvereniteettia hyödyntävien oikeusalueiden leviäminen on lopullisesti osoittanut omistuspohjaisen hallinnon edut. Äänestäjät huomaavat kärsivänsä siitä, että he on rasitettu massademokratian kanssa, ja kuten professori Keech ehdottaa, he alkavat ymmärtää, että työntekijöiden hallinto tuo hyötyjä, jotka jäävät sen kustannusten varjoon. He suuntaavat mielensä uudistuksiin. Jopa Euroopan ja Pohjois-Amerikan äänestäjäkunnat, jotka nyt vaikuttavat olevan niin vahvasti uudistuksia vastaan sitoutuneita, saattavat lopulta äänestää alueidensa muuttamisesta omaisuudenhallintoa suotuisammiksi. Suurimmistot saattavat halukkaasti – jopa iloisesti – hylätä politiikan farssin ja ottaa käyttöön omaisuudenhaltijoiden johtaman hallinnon, jonka tavoitteena on saavuttaa optimaalinen tilanne sopimusten solmimiseksi ja niiden täytäntöönpanemiseksi.

Siinä määrin kuin hallitus omine tuttuine välineineen selviytyy lainkaan, sitä voitaisiin suunnata täysin uusilla tavoilla. Jossakin, jossakin lainkäyttöalueella, joskus ennen maailmanlopun hetkeä, joku ymmärtää tietokonetechnologian tarjoaman potentiaalin tehdä mahdolliseksi todella edustuksellinen hallitus. Oletettu ongelma liiallisista kampanjamenojen kustannuksista ja kiistattomasta poliittisen kampanjoinnin ärsytyksestä voitaisiin ratkaista hetkessä. Sen sijaan, että edustajat valittaisiin, heidät voitaisiin valita arvonnalla täysin satunnaisesti, suurella tilastollisella todennäköisyydellä, että heidän kykynsä ja näkemyksensä vastaavat laajan väestön mieltymyksiä.

Tämä olisi vain moderni versio antiikin kreikkalaisesta arpomisjärjestelmästä. Kuten E. S. Staveley käy ilmi auktoriteettisessa historiassaan *Greek and Roman Voting and Elections*, lukuisia paikkoja Ateenassa – virkamiehistä arkhoihin – valittiin arvonnalla vaalien sijaan. Tämä saatiin kekseliäästi aikaan, huolimatta satunnaisuuden mekaanisista rajoitteista, käyttämällä jakoa varten suunniteltua koneistoa, "tai, kuten atheniankin kutsuivat sitä, cleroterion."[^442]

Sarja mustia ja valkoisia papuja toimi satunnaisina lukureina määrittämään, kuka valitaan täyttämään erilaisia virkoja, sekä "määrittämään järjestyksen, jossa heimosektiot neuvostossa ottaisivat vuoronsa prytaneisina."[^443] Tämän idean klassinen alkuperä voi lisätä sen uskottavuutta, mutta sen päävetovoima on juuri se, että se välttäisi politiikassa tapahtuvan itsevalikoitumisen haittoja. Se takaisi tilastollisesti sen, että vähemmän lakimiehiä ja egoisteja pääsisi lannistamaan yleistä toimintaa.

Lainsäädäntäelimet voisivat koostua todellisista edustajista. Koska heitä ei kerättäisi yhteen vallanhimon vuoksi, eikä heille olisi missään tapauksessa merkittävää mahdollisuutta tulla jälleen valituiksi arvonnalla, he olisivat vapaita hoitamaan hallituksen asioita ja laatimaan politiikkaa rationaalisen ongelma-analyysin pohjalta.

Nykyään äänestyksiä optimoimaan pyrkivillä poliitikoilla on vain vähäinen kannustin analysoida ongelmia johdonmukaisesti. Siksi ei ole yllättävää, että heidän kykynsä ratkaista ongelmia on paljon heikompi verrattuna yrittäjiin, yritysjohtajiin ja urheilujoukkueiden valmentajiin, joita palkitaan suorituksen perusteella. Suoritukseen perustuva palkitseminen lainsäätäjille ei tekisi satunnaisesti valituista kaikista yhtä tehokkaita kuin Lee Kuan Yew, mutta on kaikki syyt uskoa, että heidän suoriutumisensa paranisi huomattavasti, jos lainsäätäjien palkka sidottaisiin johonkin objektiiviseen suoritusmittariin, kuten verojen jälkeisen per asukas -tulon kasvuun. Palkatkaa heitä suorituksen perusteella, ja mahdollisuus siihen, että he todella kohtaavat haasteet, kasvaisi tuhanteen kertaan.

Yhteiskunnalle realisen, verojen jälkeisen tulon paranemista edistävien politiikkojen mukanaan tuoma hyöty voisi olla valtava. Miksi ei maksaisi pääministereille ja presidenteille edes pientä osuutta niistä saavutuksista, joita heidän politiikkansa edistävät? Tällaisen maksun rahoituksen voisi kattaa pienellä, huomaamattomalla verolla. Tällainen järjestely vapauttaisi yhteiskunnan sen nykyiseltä uhalta kunnianhimoisia, poliittiseen lahjakkuuteen erikoistuneita miehiä kohtaan, kuten Richard Nixon ja Bill Clinton, vastaan.

> "He toivat hänelle kultaa, hopeaa ja vaatteita; mutta 'Kristus' jakoi kaikki nämä asiat köyhille. Kun lahjoja tarjottiin, hän ja hänen naispuolinen seuralaisensa polvistuivat ja esittivät rukouksia; mutta sitten noustuaan jaloilleen hän käski kokoontumista palvomaan häntä. Myöhemmin hän järjesti aseistetun ryhmän, jota hän johti maaseudulla, väijyen ja ryöstäen matkustajia, joita he kohtasivat matkalla. Mutta myös täällä hänen tavoitteensa ei ollut tulla rikkaaksi, vaan tulla palvotuksi. Hän jakoi kaiken saaliin niille, joilla ei ollut mitään – oletettavasti myös omille seuraajilleen." [^444]  
NORMAN COHN

### Messiaaniset persoonallisuudet

Vähän on kiinnitetty huomiota siihen, että vaalipolitiikka houkuttelee epäjärjestäytyneitä, messiaanisia persoonallisuuksia valtaan. Tällaiset henkilöt ovat olleet olemassa ja ovat usein muodostaneet vakavia uhkia yhteiskuntajärjestykselle jo maatalousyhteiskunnissa ennen demokraattisten poliittisten järjestelmien syntyä. Tarkasteltaessa Eudo de Stellin, bretonilaisen Kristuksen, kahdeksannesta vuosisadasta peräisin olevan Adelbertin, yhdentoista vuosisadan Eonin, Antwerpenin Tanchelmin, Melchior Hoffmannin, Bernt Rothmannin ja heidän lajitovereidensa uria, useat asiat erottuvat: Mitä ilmeisemmiltä heidän poliittiset lahjakkuutensa vaikuttavat, sitä suurempia vahinkoja heidän näyttäisi aiheuttaneen. Koska valtio ei vielä ollut ryhtynyt järjestämään laajamittaista systemaattista pakottamista, nämä varhaiset protopoliitikot ottivat usein itse käsiinsä ryöstäkseen ja ryöstääkseen saadakseen käteistä ja jaettavaksi seuraajilleen köyhien joukossa.

### Protopoliitikot toiminnassa

Tarinoiden heidän tempuistaan antaa vaikutelman ajattomista lahjakkuuksista, aivan kuin lukisi seitsemän jalan pitävistä miehistä, jotka juoksisivat ylös ja alas kentällä jo ennen koripallon keksimistä. Nykyään NBA:n ansiosta poikkeuksellisen pitkät miehet tienaavat miljoonia dribbleillä ja dunkkaamalla. Jos koripallo katoaisi, he vetäytyisivät jälleen yhteiskunnan kolkkoihin, todennäköisesti esiintyen enimmäkseen sirkuksenäyttelyinä ja oheisohjelmissa.

Ennen politiikan keksimistä demagogit suuntautuivat maatalousyhteisön tarjoamaan lähimpään politiikan muotoon: kiertävämpreikkaukseen. He räpsivät yleisöjä ja, kuten poliitikotkin, lupasivat sujuvasti parempaa elämää seuraajilleen. Juuri silloin, kuten nytkin, köyhät olivat demagogien pääkohde. Norman Cohnin merkittävä historiallinen teos millenaaristen liikkeiden parissa, *The Pursuit of the Millennium*, kertoo lukuisten messiaanisten johtajien urista ennen äänestyksiä. Hänen kuvauksistaan on helppo tunnistaa vahvat yhtäläisyydet modernin ajan karismaattisten poliitikkojen persoonallisuuksissa.

> [T]ehden johtajalla on – kuten faaraolla ja monilla muilla 'jumalallisena kuninkaana' – kaikki ihanteellisen isän ominaisuudet: hän on täydellisen viisas, täydellisen oikeudenmukainen, hän suojelee heikkoja. Toisaalta hän on myös poika, jonka tehtävänä on muuttaa maailma, messias, joka aikoo perustaa uuden taivaan ja uuden maan ja joka voi sanoa itsestään: 'Katsokaa, minä teen kaiken uudeksi!' Ja sekä isänä että poikana tämä hahmo on jättimäinen, yli-ihmisen kaltainen, kaikkivaltainen. Hänelle uskalletaan antaa niin runsaasti yliluonnollisia voimia, että niitä kuvataan valon tulvana. … Lisäksi, täynnä tätä jumalallista henkeä, eskatologinen johtaja omistaa ainutlaatuiset ihmeiden tekemisen voimat; hänen armeijansa tulevat aina ja voitokkaasti voittamaan, hänen läsnäolonsa saa maan antamaan satoa ja hänen hallintonsa tulee olemaan aikakausi, josta vanha, laastariintunut maailma ei ole koskaan kokenut.

> Tämä kuva oli tietenkin puhtaasti fantastinen siinä mielessä, että se ei viitannut minkään todellisen ihmisen luonteeseen tai kykyihin, jotka olisivat koskaan olleet mahdollisia. Se oli kuitenkin kuva, joka voitiin projisoida elävälle ihmiselle; ja aina oli olemassa miehiä, jotka olivat enemmän kuin valmiita hyväksymään tällaisen projisoinnin – jotka itse asiassa intohimoisesti halusivat tulla nähtäviksi erehtymättöminä, ihmeiden tekijöinä. … Ja se salaisuus, jolla he saavuttivat ylivallan, ei koskaan perustunut syntyperäänsä eikä suurelta osin koulutukseensa, vaan aina heidän persoonallisuuksiinsa. Aikalaisten kuvaukset näistä köyhien messiaaneista painottavat yleensä heidän sujuvuuttaan, auktoriteettista olemustaan ja henkilökohtaista magneettisuuttaan. Kaiken lisäksi herää vaikutelma siitä, että vaikka jotkut näistä miehistä saattoivat olla tiedostettuja huijareita, suurin osa heistä todella piti itseään ruumiillistuneina jumalina…[^445]

Vaikka tämä ote on uskomattoman ytimekäs kuvaillessaan millenaarisia pelastajia, jotka usein rauhoittivat keskiaikaista yhteiskuntaa, se ei pysty välittämään Cohnin majesteettisen laajan katsauksen koko aromaa. Koko teosta ei voi lukea tunnistamatta näiden profeettojen tempuissa tuttuja piirteitä modernin demagogin osalta: sujuvuutta, "persoonallista magneettisuutta", "messiaanisia vaatimuksia" sekä toistuvaa halua tulla palvotuksi köyhien edustajana.

Keskeinen ero keskiaikaisen yhteiskunnan suhtautumisessa näihin huijareihin verrattuna siihen, miten demokratia 1900-luvun lopulla suhtautuu heihin, on se, että keskiajalla tällaiset henkilöt todettiin yleensä teloitettaviksi, kun taas 1900-luvun lopulla moderni demokraattinen politiikka tarjoaa heille avoimen kanavan, jonka kautta he voivat laillisesti vallata valtaa kansallisvaltiossa.

Järjestelmä, joka rutiininomaisesti antaa maailman suurimpien ja tappavimpien yritysten hallinnan karismaattisten demagogien välisten suosikkikilpailujen voittajalle, kärsii siitä lopulta pitkällä aikavälillä.

### Palkkaa johtajat tekemään hyvää työtä

Kuten aiemmin ehdotettiin, olisi helppoa määritellä ylivoimainen keino hankkia lahjakasta johtajuutta organisaatiolle: palkkaamalla se. Tämä on menetelmä, jota kilpailukykyisissä talouksissa käytetään laajimmin ja menestyksekkäimmin. Rationaalinen valintaprosessi yhdistettynä rakentavaan kannustinjärjestelmään, joka palkitsee myönteisestä johtajuudesta, toisi kyvykkäät ihmiset hallituksen johtoon. Se myös aktivoi uusia kykytyyppejä, jotka muuten eivät normaalisti kiinnostuisi hallinnon haasteista.

Maailman lahjakkaimmat johtajat voitaisiin houkutella johdattamaan horjuvia hallituksia, jos heille voitaisiin maksaa sen pohjalta, mitä konkreettisia tuloksia he todella saavuttavat yhteiskunnalle. Johtaja, joka pystyisi merkittävästi kasvattamaan reaalituloja missä tahansa johtavassa länsimaisessa maassa, voisi oikeutetusti ansaita paljon enemmän kuin Michael Eisner. Paremmassa maailmassa jokainen menestynyt hallituksen päämies olisi monimiljonääri.

### Sähköiset kansanäänestykset

Toinen ilmeinen vaihtoehto edustuksellisen huonon hallinnon sijaan olisi sähköiset kansanäänestykset, joissa kansalaiset – ehkä häiriöttömän arvonnan avulla valittu edustava osuus – voisivat äänestää suoraan lakiehdotuksista. Tietotekniikka mahdollistaa päätösten demokraattisen tekemisen sähköisten kansanäänestysten avulla. Äänestyksiä voitaisiin yhdistää helposti osallisuuden jakamiseen siten, että tietyn ongelman äänten antajien määrä rajoittuisi. Periaatteessa tuleville äänestäjille on huomattavasti vähemmän haastavaa ymmärtää poliittisia kysymyksiä kuin yrittää selvittää poliitikkojen ajatuksia tai arvioida näiden poliitikkojen näkemyksiä samoista asioista, saati edes tietää, mitä kyseiset poliitikot todella tekisivät virkaan astuessaan. Tämä on erityisen hankalaa, sillä poliitikot ja heidän edustajansa ovat yhä taitavampia muotoilemaan ja manipuloimaan julkisuudelle esittämiään kuvia.

## Käypentynyt suvereniteetti

Odotamme uudenlaisen ilmiön syntyvän korvaamaan politiikan. Vaikka edellä käsiteltyjä mahdollisuuksia voitaisiin kokeilla joillakin eduilla, emme odota politiikan uudistuvan tai parantuva, vaan sen vanhentuvan ja useimmilta osin hylätyksi jäävän. Emme tarkoita tällä sitä, että odottaisimme diktaattoria, vaan pikemminkin yrittäjähenkistä hallintoa – suvereniteetin kaupallistamista.

Toisin kuin diktaattoriassa tai edes demokratiassa, kaupallistettu suvereniteetti ei sulje pois valinnanmahdollisuuksia. Se antaa jokaiselle yksilölle laajemmat mahdollisuudet ilmaista näkemyksiään. Ja niille, jotka kykenevät hyödyntämään sitä, kaupallistettu suvereniteetti mahdollistaa käytännöllisemmän päätöksenteon ja itsehallinnon laajuuden kuin mikään tähän asti ollut sosiaalisen järjestäytymisen muoto.

### Räätälöity hallinto

Ellei tämä kuulosta liian vuosisatojen odotuksilta, on syytä huomata, että mikroteknologia pienentää ja hajottaa kokonaisuuksia. Se mahdollistaa yksilöllisen räätälöinnin massatuotannon sijaan. Nykyään voit mennä kauppaan ja ostaa farkut, jotka leikataan juuri sinulle sovitetusta mallista ja ommellaan puolikkaan maailman päästä. Kun uudet instituutiot lopulta kehittyvät vastaamaan tietoyhteiskunnan uudenlaista megapoliittista todellisuutta, voit saada hallintoa, joka on vähintään yhtä hyvin räätälöity henkilökohtaisia tarpeitasi ja makujasi varten kuin farkut.

Alvin Toffler – kaikista ihmisistä – on kritisoinut ajatusta, että tietoteknologia voisi muuttaa kansalaiset asiakkaiksi. Toffler sanoo – virheellisesti mielestämme – 'Se on aivan liian kapea malli. Pidämmekö sitä sitten hyvänä vai pahana, on olemassa uskonnon ja tunteen maailma, jota ei voi yksinkertaisesti supistaa sopimussuhteiksi.'[^446] Kuten aiemmin on pohdittu, on totta, että on vaikeaa "supistaa nationalistisen tunteen maailma" "sopimussuhteiksi." Tämä ei kuitenkaan tarkoita, ettei se olisi mahdollista – eikä se välttämättä olisi huono järjestely. Vähän vähemmän järjetöntä innokkuutta nationalismiin voisi pelastaa miljoonia ihmishenkiä.

### "Sisäänkäynti, ulosmeno" ja "Ääni"

Tietenkin suvereniteetin kaupallistaminen on vieras käsite – ilmeisesti jopa Alvin Tofflerille. Sen keskeinen ajatus – taloudellinen ilmaisumuoto – on kuitenkin arkipäivää 1900-luvun loppupuolella elävien ihmisten elämässä. Jokaisessa vähintään marginaalisesti vapaassa taloudessa kuluttajat voivat toimia suoraan ilmaistakseen toiveensa ostamalla palveluita ja tuotteita tai vetäytymällä käytöstä. Kun menet tyytymättömäksi johonkin tuotteen versioon tai palveluntarjoajaan, voit suoraan ilmaista tyytymättömyytesi "ulosmenon" kautta. Toisin sanoen, voit siirtää liiketoimintasi muualle.

Edellisissä luvuissa analysoimme, kuinka tietotekniikan kehitys tekee sinulle pian mahdolliseksi luoda kyberavaruudessa omaisuuseriä, jotka ovat käytännössä immuuneja valtioiden petolliselta hyökkäykseltä. Tämä luo *de facto* metakonstituutionalaisen vaatimuksen, jonka mukaan hallitusten on tarjottava sinulle tyydyttävää palvelua ennen kuin maksat niiden laskut. Miksi? Koska tuloverotuksesta tulee käytännössä lähes yhtä vapaaehtoista kuin teoriassa oletetaan.

### Cumbrous poliittisten kanavien välttäminen

Jos tietotekniikka kehittyy odotetusti, varmistuu, että hallituksia hallitsevat todellisuudessa niiden asiakkaat. Asiakkaana sinulla on aluksi satoja ja myöhemmin tuhansia vaihtoehtoja pienentää suojakustannuksiasi suoraan tekemällä yksityinen verosopimus valtion kanssa tai erkaantumalla kokonaan valtioista siirtymällä kehittyviin minsuvereniteetteihin. Nämä sopimukselliset "sisäänkäynti-" ja erkaantumisvaihtoehdot ovat taloudellisia ilmaisumuotoja toiveistasi asiakkaana. Olennaista on, että jalkojen ja rahojen äänestäminen johtaa juuri niihin tuloksiin, joita haluat.

Miten asiakkaana sinulla olevat "sisäänkäynti"‑ ja "uloskäyntivaihtoehdot" vertautuvat demokratian poliittiseen ilmaisutapaan? Henkilöt, jotka kokevat jotakin tuotetta tai palvelua tyytymättömäksi – erityisesti sellaista, jota hallitus tarjoaa tai säätelee voimakkaasti – voivat antaa mielipiteensä kuulua esimerkiksi kirjoittamalla kirjeitä Yhdysvaltain presidentille tai hakemalla tapaamista kansanedustajansa tai muun asianmukaisen valitun virkamiehen kanssa. Joskus tällaiset "rakkauskirjeet" toimivat. Mutta eivät aina – yleensä eivät. Ensisijaisen onnistumisen puuttuessa ihmiset, jotka haluavat vaikuttaa äänellään, voivat järjestää mielenosoituksen, julkaista koko sivun mainoksen sanomalehdessä tai jopa hakeutua itse ehdokkaiksi.

Poliittinen ilmaisutapa antaa mahdollisuuden täsmällisiin lausuntoihin ja puhetaitoon, mutta sen haittapuolena on se, että omilla toimilla harvoin saa aikaan tyydyttävää vaikutusta tai parannusta omaan asemaansa. Kun kohtaat hallituksen tarjoaman heikkolaatuisen tuotteen tai palvelun, joudut yleensä maksamaan siitä eteenpäin, kunnes pystyt vakuuttamaan koko poliittisen prosessin myöntymään pyyntöösi muutoksesta.

Länsimaissa – ja nykyään käytännössä koko maailmassa – tämä on tarkoittanut demokraattisen poliittisen järjestelmän enemmistötuen varmistamisen välttämättömyyttä. Enemmistön mukaan ottaminen tuo mukanaan valtavia transaktiokustannuksia sinun ja sen välillä, että saavutetaan hyvin todennäköisesti suhteellisen yksinkertainen ja järkevä tavoite.

Milton Friedman käsitteli taloudellisen, toisin kuin poliittisen, ilmaisutavan etuja ehdottaessaan kouluseteleitä kirjassaan *Capitalism and Freedom*:

> Vanhemmat voisivat ilmaista näkemyksiään kouluista suoraan vetäytymällä yhdestä koulusta ja siirtämällä lapsensa toiseen paljon laajemmin kuin nykyisin on mahdollista. Yleisesti ottaen he voivat nyt tehdä tämän ainoastaan muuttamalla asuinpaikkaansa. Muutoin heidän näkemyksensä voi ilmaista vain kömpelöiden poliittisten kanavien kautta.[^447]

Albert O. Hirschman, joka puhui politiikan puolesta, vastusti Friedmanin mieltymystä 'poistua' suoran tavan sijaan ilmaista epäedullisia näkemyksiään organisaatiosta. Hirschman vastasi: 'Vähemmän taloustieteellisesti koulutettu henkilö saattaisi naiiviinsa ehdottaa, että suorin tapa ilmaista näkemyksensä on yksinkertaisesti ilmaista ne!'[^448]

On monimutkaista ja kiisteltyä, kumpi tapa – mielipiteiden ilmaiseminen markkinamekanismien kautta, kuten antamalla tai vetäytymällä asiakkaana tukensa osalta, tai kömpelöiden poliittisten kanavien kautta – on suorempi tai tehokkaampi. Eri ihmiset vastaavat siihen eri tavoin. Niille, joiden ensisijainen poliittinen toimintatapa on vaatia etuja toisten kustannuksella, taloudelliseen ilmaisutapaan siirtyminen saattaa todellakin vaikuttaa alistavalta vaihtoehdotukselta verrattuna siihen, että he kirjoittaisivat poliitikolle ja vaatisivat enemmän.

### Taloudellinen ilmaisumuoto ja 'vastavuoroinen sosiaalisuus'

Niille, jotka aikovat sitouttaa toverinsa "vastavuoroiseen" sen sijaan, että harjoitettaisiin "pakottavaa" tai loiseläimellistä sosiaalisuutta, taloudellinen ilmaisumoodi avaa mahdollisuuden saavuttaa huomattavasti suurempi tyytyväisyys alhaisemmilla ajankäytön ja vaivan kustannuksilla. Vaikka professori Hirschfieldin näkemyksiä tulisi huomioida, tämä on helposti osoitettavissa.

Mikä tahansa joukko taloudellisia ilmaisuja – jotka koostuvat sisäänkäynneistä, jatkuvista sopimuksista ja uloskirjautumisista – voitaisiin muuntaa poliittisen "äänen" ilmaisuksi yksinkertaisesti ottamalla päätöksentekoon mukaan massoja ihmisiä. Kokeile sitä kokeiluna. Kokeiluun tarvitsisit vain muutaman sadan ihmisen joukon, jotka kokevat, että heidän elämästään puuttuu politiikkaa. Sen sijaan, että he kuluttaisivat käytettävissään olevat tulonsa tuhansiin erillisiin ostoihin vuoden aikana, he muuntaisivat tämän määrän taloudellisia päätöksiä muutamaksi poliittiseksi päätökseksi.

Aluksi kaikki sopisivat yhteen siitä, että he yhdistävät käytettävissään olevat tulonsa ja luopuvat sen jälkeen yksilöllisestä kulutuksesta. Sen sijaan, että kukin käyttäisi tuhansia dollareita erikseen tuhansiin ostoihin, jokaiselle annettaisiin yksi ääni – tai ehkä muutama ääni sen mukaan, kuinka monta virkaa on täytettävänä. Sen sijaan, että kuluttaisit rahaa suoraan saadaksesi haluamasi milloin tahansa, käyttäisit äänesi niissä harvoissa vaaleissa, joissa valitaan edustajia, jotka sitten päättävät, mihin nyt valtavan yhteisen rahapussin varat käytetään.

Sinä, yhdessä muiden kanssa, jakaisitte sen jälkeen näiden tavaroiden kulutuksen – ja vain niiden tavaroiden, jotka hallitseva komitea olisi enemmistön nimissä hyväksynyt.

Vaikuttaako tuo vielä "raskaalta poliittiselta kanavalta" ilmaisulle? Odota vain. Tämä malli sisältää kaiken kansallisen tason politiikassa havaittavan retoriikan ja vaikuttamisen potentiaalin – ja suurimman osan myös turhautumisen mahdollisuudesta.

Esimerkiksi, jos pidät tuoreesta parsakaalista ja ryhmässä on tavallinen ruokamaku, olet pulassa. On todennäköistä, että jotkut tai useimmat muista ryhmässäsi haluaisivat käyttää suuremman osan yhteisestä ruokabudjetista punaisen lihan hankintaan kuin tuoreiden vihannesten. Jotta ruokalan komitea ei lähtisi varastokauppaan mupsamaan koko vuotuista vihannesbudjettia tölkittyihin herneisiin ja maissiin, saatat joutua astumaan esiin ja antamaan näkemyksillesi äänen. Voisit kiinnittää ryhmän huomion siihen, kuinka parsakaalista nautittava suurempi määrä vitamiineja ja fytonutrietteja – kuten sulforafana – on suhteessa punaisesta lihasta saamuun enemmän eduksi kuin tyydyttyneet rasvat ja kolesteroli.

Tietenkin, miten teet tämän tai minkä tahansa muun asian ymmärrettäväksi, on yhtä arvoitus tässä suunnitellussa poliittisessa mallissa kuin minkä tahansa poliittisen asian tai ehdokkuuden puolestapuhujille. Voisit pitää puheen – mikä edellyttää sitä, että suuri osa sitä ryhmästä, jonka sinun täytyy vakuuttaa, on jo kokoontunut ja valmis kuuntelemaan. Voisit painattaa esitteitä, mikäli tällainen "kampanjakulutus" sallisikin poliittisen pelisi talonsäännöissä. Voisit kirjoittaa kirjeitä. Mutta kummatkin vaihtoehdot edellyttävät, että muut osallistujat osaavat lukea.

> 'Se maalaa kuvan yhteiskunnasta, jossa suurin osa amerikkalaisista ei tiedä, etteivät he omista taitoja, joita tarvitaan elannon tienaamiseen yhä teknologisemmassa yhteiskunnassamme ja kansainvälisillä markkinoilla.' RICHARD RILEY; U.S. SECRETARY OF EDUCATION, IN *ADULT LITERACY IN AMERICA*

### Yhdeksänkymmentä miljoonaa Alzheimerin tautia sairastavaa potilasta?

Jos ryhmäsi tässä mallipoliittisessa harjoituksessa sattuisikin koostumaan amerikkalaisista, sinun olisi todella vaikea saada edes minkään vakuuttavaa viestiä todella iskeytymään, erityisesti jos ryhmän jäsenet olisivat samanlaisia kuin Yhdysvaltain äänestäjäkunta kokonaisuudessaan. Se, että maailman voimakkaimman kansallisvaltion suhteellisen suuri määrä kansalaisia jää alisuoriutujiksi, on karusti vahvistettu perusteellisimmalla koskaan toteutetulla tutkimuksella amerikkalaisten aikuisten osaamisesta. Tutkimus, *Adult Literacy in America*, osoittaa, että lukevan yleisön löytäminen minkä tahansa poliittisen argumentin tueksi ei ole lainkaan helppoa. Suuri osuus – ehkä enemmistö yli viisitoista vuotta vanhoista amerikkalaisista – puuttuu perusosaamisista, jotka ovat välttämättömiä ideoiden arvioimisessa ja tuomioiden muodostamisessa. Yhdysvaltain opetusministeriön mukaan 90 miljoonalla amerikkalaisella ei ole kykyä kirjoittaa kirjettä, ymmärtää linja-autojen aikatauluja eikä edes pystyä tekemään peruslaskutoimituksia laskimella. Tämä on suunnilleen sitä, mitä voisi odottaa, jos 90 miljoonaa amerikkalaista etenisi eri Alzheimerin taudin vaiheiden läpi; 30 miljoonaa heistä arvioitiin niin epäpäteviksi, etteivät he pystyneet edes vastaamaan kysymyksiin.

Jos siis terveysviestisi ei onnistunut kääntämään tilannetta – mikä muuten saavuttaisi oman tasapainonsa – voisit kutsua apuun eläinoikeusaktivisteja. Ehkä saisit heidät protestoimaan vastustajiisi ruokalan komiteassa tai tekemään meteliä vaikuttavien jäsenten kodeissa tapahtuvasta lehmien surmaamisesta.

Tätä esimerkkiä voisi jatkaa loputtomiin, mikä todennäköisesti ylittää rationaalisten ihmisten kärsivällisyyden. Se osoittaa selvästi, että (1) mikä tahansa taloudellinen sisään- tai uloskirjautuminen voidaan muuttaa poliittiseksi äänilausekkeeksi tekemällä siitä kollektiivinen päätös, ja (2) että kollektiiviset päätökset, huolimatta siitä, että ne kutsuvat esiin eloisaa retoriikkaa, ovat todellakin kömpelöitä ja usein sitkeitä.

Juuri näin kokemus on osoittanut. Demokratian kurssin muuttamiseen tarvittavan ponnistelun mobilisointi on kaikkea muuta kuin helppoa. Toistettakoon, tämä saattaa hyvin olla syy siihen, miksi demokraattiset hyvinvointivaltiot selvisivät vuosisatojen ajan vaihtoehtoisten hallintomenetelmien kilpailussa ja nousivat etualalle teollistumisen lopulla. Demokratia menestyi poliittisena järjestelmänä juuri siksi, että sen toiminta teki asiakkaiden vaikeaksi hallita hallitusta tai rajoittaa valtion vaatimuksia resursseista.

Koska rajattomalla osakkuudella valtiolla asioissasi ei enää saavuteta sotilaallista etua informaatiokaudella, kekseliäät ihmiset löytävät ylivoimaisia tapoja saada ne harvat arvokkaat palvelut, joita hallitukset oikeastaan tarjoavat. Todennäköistä on, että todellinen valta siirretään ulos niistä kollektiivisista mekanismeista, jotka eivät enää kata itseään. Odotamme tehokkuuden nousevan massajoukon vallan yläpuolelle. Kuten Neil Munro ilmaisi napakasti, '[S]itä, mikä yhä enemmän ajaa Yhdysvaltain taloutta ja mikä voittaa sodat maailmassa, jossa on yhteenkytketty 500 TV-kanavaa, on tietokoneistettu informaatio – ei työvoima eikä massatuotanto. Tietokoneistettua informaatiota on olemassa kyberavaruudessa – uusi ulottuvuus, jonka ovat luoneet loputtoman määrän tietoverkkoja, satelliitteja, modeemeja, tietokantoja ja julkista Internetiä.' [^449]

Massiiviset armeijat eivät merkitse paljoa tällaisessa maailmassa. Tehokkuus tulee olemaan merkityksellisempää kuin koskaan aiemmin. Koska mikroteknologia luo uuden ulottuvuuden suojeluun, kuten käsittelimme luvussa 6 ja muualla, yksilöt pystyvät ensimmäistä kertaa ihmiselämän historiassa luomaan ja suojelemaan varoja, jotka sijaitsevat täysin sen ulkopuolella, mitä yksittäisen hallituksen alueellinen väkivallan monopoli kattaa. Nämä varat ovat siksi erittäin alttiita yksilölliselle hallinnalle. On täysin kohtuullista, että sinä ja huomattava määrä muita tulevia itsenäisiä yksilöitä äänestätte jaloillanne poistumalla johtavista kansallisvaltioista ja solmimalla henkilökohtaisesta suojelusta sopimuksen tai uuden minioikeuden kanssa, joka veloittaa vain kaupallisesti siedettävän määrän – ei suurinta osaa nettovarallisuudestasi. Lyhyesti sanottuna, hyväksyisit todennäköisesti 50 miljoonaa dollaria muuttaaksesi Bermudalle.

### Ensiksi poistutaan, sitten sopimus

Itsemääräämisoikeuden kaupallistumisen alkuvaiheen kannustin tulee ihmisiltä, jotka ilmaisevat taloudellisesti itseään poistumalla. Tämä vaihtoehto on vaikein Yhdysvalloissa, jossa se on myös arvokkainta. Presidentti Bill Clintonin ja republikaanikongressin asettama "Berliinin muuri" kapitalisteille on ristiriidassa 1960-luvun amerikkalaisten nationalistien varman iskulauseen, 'Rakasta sitä tai poistu', kanssa. Asettamalla rangaistusveroja poistuville poistumisvero pyrkii pakottamaan lojaalisuutta. Tämä kostava lainsäädäntö, joka muistuttaa Rooman valtakunnan loppupäivinä pakenneiden omaisuuden omistajille asetettuja rangaistuksia, saattaa kuitenkin tahattomasti luoda kehyksen myöhemmin tietotekniikan aikakaudella sovellettavalle rationalisoidulle politiikalle.

Jossain vaiheessa, kun tarpeeksi kyvykkäitä henkilöitä on poistunut ja he ovat kertaantuneet riittävän suuriksi ulkomaisiksi varoiksi, Yhdysvaltain viranomaisille tulee houkuttelevaksi sallia kansalaisten tai green card -haltijoiden ostaa ulos tulevista verovelvoitteistaan maksamalla poistumisveroa, mutta ilman poistumista. Toisin sanoen, poistumisverosta voisi muodostua malli kertaluonteiselle lunastukselle. Hallitus, joka asettaa poistumisveron, hyötyisi huomattavasti, jos poistuvien sallitaan palata asuntoonsa yksityissopimuksen ehtojen mukaisesti, kuten nykyisin on käytössä Sveitsissä ja muualla.

Tällaiset toimet Yhdysvalloissa tai muissa hallituksissa olisivat rationaalisia tulon optimointitoimenpiteitä. Lopulta kilpailu suojapalveluissa pakottaa verokannat laskemaan ja verotuksen ehdot mukautumaan sivistyneempiin standardeihin. Sen sijaan, että luotettaisiin lainsäätäjiin hyväksyttävien verojärjestelmien säätämisessä, tulevaisuuden itsenäiset yksilöt pystyvät neuvottelemaan hyväksyttäviä, räätälöityjä politiikkapaketteja yksityissopimuksin.

## Loukkaamassa todellisia uskovia

Tietenkään emme väitä hetkeäkään, että suuri osa tästä olisi suosittua. Yksilön denationalisaatio ja siihen liittyvä suvereniteetin kaupallistuminen saattavat loukata niitä, jotka yhä uskovat 1900-luvun politiikan kliseisiin. Kuten edesmenneen Christopher Laschin mukaan, he pitävät politiikan rappeutumista uhkana enemmistön hyvinvoinnille. Heidän mukaansa teollisaikaan sitoutunut politiikan uusiherääminen, joka pyrkii uudelleenjärjestämään tuloja, voisi olla ratkaisu niihin ahdistuksiin, joita monet kokevat tietotekniikan tuomien kilpailupaineiden vuoksi.

E. J. Dionne, Jr. on poliittinen toimittaja *Washington Postille*. Kuten Lasch, hän kääntyy nostalgisesti politiikan puoleen. Hänä edustaa myös sosiaalidemokraattista tasausimpulssia, jonka ääni tulee vahvistumaan tulevina vuosikymmeninä, kun informaatiokauden uudet megapoliittiset realiteetit entistä päättäväisemmin heikentävät modernin maailman jäänteinä säilyneitä instituutioita. Dionne näkee 1900-luvulla rikkaissa oikeudenkäyttöalueissa laajasti jaettujen elintaso-parannusten johtuvan lähinnä demokraattisesta politiikasta eikä teknologisesta tai taloudellisesta kehityksestä. Hänen viestinsä on, että tulevaisuuden toivo edellyttää politiikan vallan laajentamista informaatiokauden teknologioiden yli:

> Yhdysvalloissa ja koko demokraattisen maailman keskeisin tarve on uusi sitoutuminen demokraattiseen uudistukseen, siihen poliittiseen moottoriin, joka teki teollisajasta menestyksekkään. Informaatiokauden teknologiat eivät yksin pysty rakentamaan menestyvää yhteiskuntaa, aivan kuten teollisuutta itsessään annettaisiin jäädä ilman vaikutusta parantaakseen maailmaa. ... Jopa teknologian uskomattomimmat läpimurrot ja Internetin nerokkaimmat sovellukset eivät pelasta meitä yhteiskunnalliselta eroosiolta, rikollisuudelta tai epäoikeudenmukaisuudelta. Vain politiikka, joka on tapa, jolla järjestämme itsemme, voi edes aloittaa tällaisten tehtävien hoitamisen.[^450]

Dionne ja hänelle kaltaiset eivät ymmärrä, että ne olosuhteet, jotka tekivät 1900-luvun elämästä erityisen alttiin systemaattiselle pakottamiselle, eivät olleet inhimillisten toimijoiden valitsemia. Ilmaus 'tapa, jolla järjestämme itsemme' ei olisi ollut ymmärrettävä modernia aikaa edeltäneenä. Yhteiskunnat ovat liian monimutkaisia ollakseen minkään tahallisen itseorganisoitumisen tulosta. Modernin ajan kansallisvaltiot nousivat spontaanisti teollisuusteknologian sattumanvaraisena sivutuotteena, joka lisäsi väkivallan tuottoja. Nyt tietotekniikka vähentää näitä tuottoja, mikä tekee politiikasta anakronistisen ja korjaamattoman riippumatta siitä, kuinka vilpittömästi ihmiset haluaisivat säilyttää sen seuraavalle vuosituhannelle.

[^450]: E. J. Dionne, Jr., *Washington Post* (viitattu).

> 'Ei ole tänään eikä eilisen tavoin,
> Kautta aikojen ne elävät; mistä ne ovat tulleet,
> ei kukaan tiedä.'  - SOPHOCLES, Antigone

## 'They don't make them like they used to'

Kiihkeä halu 'laskea lakeja', joka vaikuttaa olevan niin keskeinen osa 1900-luvun politiikan kansankäyttöä, ei kuitenkaan ole kaikkien kulttuurien yleismaailmallinen piirre. Sen katoamista tulevaisuudessa voitaisiin tulkita osana sykliä, joka on noussut ja laskenut vuosisatojen saatossa. Esimerkiksi varhaiset kreikkalaiset – muiden muassa – uskoivat, että lakeja ei voi laatia. Filosofi Ernst Cassirer'n mukaan kreikkalaiset uskoivat, että 'kirjoittamattomilla laeilla', oikeuden laeilla, ei ole alkuperää ajassa.[^451] Kuten muutkin esipoliittiset kansat, he tunsivat, että kukaan ei voisi parantaa sitä luonnollista, 'geometristä' oikeuden järjestystä, jota mikään inhimillinen valta ei ollut luonut.

He eivät uskonneet 'lakien antajaan'. Kuten Cassirer totesi, 'järkevän ajattelun avulla meidän tulee löytää moraalisen käytöksen normit, ja pelkästään järki voi antaa niille auktoriteetin.' Tässä mielessä kaikki yritykset panna lakeja yhteiskuntaan lainsäädännöllä olisivat kuin yrittäisi muuttaa geometriaa lainsäädännöllä.

### Legislation as sacrilege

Suurin osa keskiajan ajasta, hyvin erilaisista syistä huolimatta, vallitsi samanlainen vastustus lainsäädännön muovaamiselle. Kuten John B. Morrall kirjoittaa, “[F]or the Germans, laki oli jotakin, mikä on ollut olemassa ikiaikojen alusta lähtien.” Se oli “takuu yksittäisten heimojäsenien oikeuksista.”[^452] Kuninkaat ja neuvostot

> Ei ollut vielä aikomusta laatia uutta lakia. Tällainen aikomus olisi näiden varhaiskeskiaikojen näkökulmasta ollut paitsi tarpeetonta myös osittain jumalanpilkkaa, sillä laki – kuten kuninkaallisuuskin – kantoi mukanaan omaa pyhää auraansa. Sen sijaan kuningas ja neuvoston jäsenet pitivät itseään vain selventämässä jo olemassa olevan ja täydellisen lainsäädännön todellista merkitystä. Germaaninen tapausperinne siirsi keskiaikaiseen ajatteluun idean, jota se ei koskaan unohtanut, vaikka käytännössä toiminta poikkesi toisistaan. Tämä idea oli, että hyvät lait löydettiin uudelleen tai muotoiltiin uudelleen, mutta niitä ei koskaan tehty kokonaan alusta lähtien.[^453]

#### Regrets

Ei ole siis ihme, että politiikan viimeisten päivien aikana syntyy surullisia lauluja. Ne ovat täysin ennustettavia. Eikä vain siksi, että ne heijastavat useimpien ajattelijoiden sokeutta megapolitiikan vaatimuksiin. Harvat poliittiset toimittajat, kuten Dionne, ovat valmiita hyväksymään politiikan näennäisen surkastumisen ja katoamisen, vaikka se saattaisi asettaa heidät taas rikostutkinnan painajaisiin. Keskiajan lopulla kohosi ääniä, jotka kannattivat ritarillisuuden herättämistä uudelleen. Pohdi *Il Libro del Cortegiano* -teosta, tai vaihtoehtoisesti *The Book of the Courtier*, jonka kreivi Baldassare Castiglione kirjoitti vuonna 1514 ja jonka Aldus julkaisi Venetsiassa vuonna 1528.

Castiglion kaipuu palata ritarillisien hyveiden aikakauteen oli syvästi koettu, mutta kaipaus vanhentuneeseen elämäntapaan ei voinut palauttaa sitä 1500-luvulla. Eikä sitä tulekaan palauttamaan 2000-luvullakaan.

Kuten olemme pyrkineet selventämään megapoliittisen teoriamme yhteydessä, teknologiset imperatiivit – eivät kansan mielipiteet – ovat tärkeimmät muutosvoimat. Jos megapoliittinen teoriamme on pätevä, modernin ajan, jossa kansalaisuuden käsite ja valtion ympärille organisoitu politiikka syrjäyttivät feodaalisen järjestelmän ja henkilökohtaisten valojen sekä suhteiden pohjalta toimineen ritarillisuuden, syy ei ollut ideoissa vaan uusien teknologioiden tuomissa kustannus- ja hyötymuutoksissa. Ritarillisuus ei kuollut siksi, että Castiglione tai muut epäonnistuivat vakuuttamaan siitä välinpitämättömiä kansalaisia, joilla oli valtaa asian suhteen, ettei kunnian tai moraalin tarvitsisi vaikuttaa valtiollisiin asioihin. Päinvastoin, Castiglion *Courtier* kritisoi prinssiä ja sitä käyttäytymistä, jota hänen aikakaverinsa Niccolò Machiavelli kehuikin teoksessaan *Il Principe* eli *The Prince*. Mutta entä sitten? Machiavelli tavoitti lopulta laajemman yleisön kirjallaan, ei siksi, että hänen väitteensä *The Prince* -teoksessa olisi ollut sujuvampia, vaan siksi, että hänen neuvonsa sopivat paremmin modernin ajan megapoliittisiin olosuhteisiin.

Kuinka arvostettu 1900-luvun filosofi Ernst Cassirer totesi keskustellessaan 'Machiavellin moraalisesta ongelmasta',

> Kirja kuvaa täysin välinpitämättömästi keinoja ja menetelmiä, joilla poliittinen valta hankitaan ja säilytetään. Se ei sano yhtään sanaa vallan oikeasta käytöstä. ... Kukaan ei ollut koskaan epäillyt, että nykyinen poliittinen elämä on täynnä rikoksia, petoksia ja lainvastaisuuksia. Mutta mikään ajattelija ennen Machiavellia ei ollut ryhtynyt opettamaan näiden rikosten taitoa. Näitä tekoja tehtiin, mutta niistä ei opetettu. Se, että Machiavelli lupasi tulla opettajaksi viekkauden, petturuuden ja julmuuden taiteessa, oli kuultua ennen. [^454]

Lyhyesti sanottuna, *The Prince* oli radikaali teos, joka esitti modernin reseptin, jonka mukaan kunnianhimoinen hallitsija voi edistää uraansa hinnalla millä hyvänsä muille. Machiavelli kannatti toimintaa, joka soveltui erinomaisesti vallan aikakauden politiikan luonteeseen. Mutta kaksoispetoksen taito, joka osoittautui nokkelaksi strategiaksi nykyajan poliitikoille, oli järkyttävää ja hajottavaa sitä ritarillisuuskulttuuria ajatellen, joka oli kehittynyt aiemmilla vuosisadoilla.

Kuten aiemmin tarkastelimme, ritarillisuden hyveisiin kuului äärimmäinen uskollisuus vannouksia kohtaan. Tämä oli välttämättömyys yhteiskunnassa, jossa suojaa järjestettiin henkilökohtaisten palveluiden vastineeksi. Feodaalisen yhteiskunnan peruspilarit eivät olisi spontaanisti uudelleen ilmestyneet ihmisten keskuuteen, joilla oli mahdollisuus vapaasti määrittää omat etunsa painostustilanteissa. Siksi ritarillisuutta tukevat feodaaliset sitoumukset piti perustaa vahvaan kunnian tunteeseen. Tässä yhteydessä mikään ei voinut olla kapinallisempaa kuin Machiavellin ehdotus, jonka mukaan prinssin ei tulisi epäröidä valehdella, huijata ja varastaa, jos se palvelee hänen etujaan.

Kun 1900-luku lähestyi loppuaan, Machiavellin argumentteja tutkittiin edelleen niiden merkityksen vuoksi modernin politiikan sekä erilaisten 1900-luvun rikosten ja tyrannoiden ymmärtämisessä. Castiglion teos taas on käytännössä unohtunut. Vuoden kuluttua *Il Libro del Cortegiano* saattaa lukea läpi kannen yli vain muutama jatko-opiskelija kirjallisuustieteellisessä ohjauksessa ja muutama käytöstapojen historian asiantuntija.

Jossain seuraavien vuosikymmenten aikana Information Age -ajan uudet megatalousvoimat vanhentavat *The Prince* -teoksen. Itsemääräämistä arvostava yksilö tarvitsee uuden menestyksen reseptin, jossa korostuvat erityisesti kunnia ja rehellisyys, kun resursseja käytetään valtion valvonnan ulkopuolella. Voimme ennustaa, että sellaista neuvontaa eivät lue mielellään E. J. Dionne, Jr. ja muut nykyiset sosiaalidemokraatit.

### Asiakkaiden asettama politiikka

Tämä pätee erityisesti siirtymävaiheen alussa, jolloin useimmat lainkäyttöalueet ovat vielä velvoitettuja muotoilemaan politiikkoja, joiden puolustajat pystyvät houkuttelemaan enemmistön kansan hyväksynnän. Myöhemmin, kun demokratia hälvenee ja itsemääräämispalveluiden markkinat syvenevät, markkinaolosuhteet, jotka rajoittavat 'politiikkaa', tulevat laajemmin ymmärretyiksi.

What we now think of as 'poliittisena' johtajuutena, joka aina määritellään kansallisvaltioiden näkökulmasta, tulee yhä enemmän muuttumaan yrittäjämäiseksi ennemmin kuin poliittiseksi. Näissä olosuhteissa toimivan 'politiikka'-järjestelmän kokoaminen tietylle alueelle kapenee olennaisesti samalla tavalla kuin yrittäjille avoinna oleva vaihtoehtojen kirjo ensiluokkaista lomahotellia tai muuta vastaavaa tuotetta tai palvelua suunniteltaessa määräytyy sen mukaan, mistä ihmiset ovat valmiita maksamaan. Esimerkiksi lomahotelli harvoin pyrkisi toimimaan sellaisten ehtojen mukaisesti, joissa vierailijoiden edellyttäisi tehdä raskasta työtä sen tilojen korjaamiseksi ja laajentamiseksi. Jopa työntekijöidensä omistama tai hallitsema lomahotelli, kuten tyypillinen moderni demokratia, pyrkisi turhaan pakottamaan asiakkaitaan noudattamaan tällaisia vaatimuksia, erityisesti sen jälkeen kun parempia majoitusvaihtoehtoja tulisi saataville. Jos asiakkaat mieluummin pelaavat golfia kuin tekevät raskaata työtä kuumassa auringossa, markkina tarjoaa tuon asian osalta vain vähän mahdollisuuksia asettaa mielivaltaisia vaihtoehtoja. Näissä olosuhteissa nykyiset 'poliittiset' kysymykset väistyvät yrittäjämäisempien arvioiden taakse, kun alueet pyrkivät selvittämään, millaiset politiikkapakettien kokonaisuudet houkuttelevat asiakkaita.

### Politiikan rappeutuminen

Kun tämä ymmärretään, asenteissa tapahtuu radikaali muutos. Vallan siirtymisalueiden väestöt eivät enää odota voivansa valita samanlaisista toiveita tyydyttävistä politiikkavaihtoehdoista, jotka vaativat poliittista keskustelua 1900-luvulla. Koska tulonhankintakyky tulee yhä epätasaisemmaksi kuin teollisuusaikana, alueet pyrkivät palvelemaan niiden asiakkaiden tarpeita, joiden liiketoiminta on arvokkainta ja joilla on eniten valinnanvaraa, mihin se sijoitetaan. Tällaisissa olosuhteissa saattaa olla paljon vähemmän merkitystä kuin olemme tottuneet olemaan, vetoavatko kaupallisesti optimaaliset politiikat tietylle alueelle keskimääräiseen äänestäjään fokusryhmässä vai eivät. Lyhyesti sanottuna, suvereniteetin kaupallistuminen helpottaa hallitusten kontrollointia niiden asiakkaiden toimesta. Tämä johtaa siihen, että ei-asiakkaiden mielipiteet tulevat merkityksettömiksi tai vähemmän merkityksellisiksi, aivan kuten Big Mac -syöjien näkemykset foie grasista ovat merkityksettömiä kolmen tähden ranskalaisten ravintoloiden, kuten *L'Arpege* Parisissa, menestyksen kannalta.

## 'The betrayal of democracy'

Kuten edes kuollut Christopher Lasch, vastustajat eivät ainoastaan valita, että tieto- ja viestintätekniikka tuhota työpaikkoja; he valittavat myös, että se kumoaa demokratian, koska se mahdollistaa yksilöiden sijoittaa varansa poliittisen pakottamisen ulkopuolelle. Tästä syystä uuden vuosituhannen reaktionaarit kokevat tietotekniikan mahdollistaman taloudellisen yksityisyyden erityisen uhkaavana. He perääntyvät ajatuksesta, että tulon- ja pääomaverotuksen tulisi todella perustua 'voluntary compliance' -periaatteeseen. He kannattavat uusia ja jopa radikaaleja keinoja puristaa resursseja keneltä tahansa, joka vaikuttaa vauraalta, kuten 'presumptive taxation' -järjestelmää ja varakkaiden henkilöiden suoraa kiristämistä.

### Yhteisomaisuus

Kirjoittaessamme pintaa lähestyvät jo vihjeet tulevasta. Varhaiset todisteet siitä, että hallitusten kyky kontrolloida kansainvälisiä markkinoita liukuu käsistä, loukkaavat niitä, jotka uskovat, että yksilöt ovat oikeutettuina kansallisvaltioiden varoiksi. He haluavat panna täytäntöön kykynsä kohdella maan kansalaisia omaisuutena, eivät asiakkaina. Reaktionaarit uskovat, että kaikki tulot tulisi katsoa yhteisön tuloina, eli niiden tulisi olla valtion käytettävissä.[^455]

Olemme jo käsitelleet Laschin esittämiä argumentteja teoksissa *Revolt of the Elites* ja *Betrayal of Democracy*. Mutta hänen vuoropuheensa kansallisvaltiota tukien ei ole ainoa tällainen äänekäs kritiikki. Harvardin yliopiston poliittinen teoreetikko Michael Sandel väittää teoksessaan *Democracy in Discontent*, että 'Democracy today is not possible without a politics that can control global economic forces, because without such control it won't matter who people vote for, the corporations will rule.' Toisin sanoen valtion on säilytettävä loisema voimansa yksilöihin nähden varmistaakseen, että poliittiset lopputulokset voivat poiketa markkinaolosuhteista. Muuten kollektiiviset päätökset pakottaa epäekonomisia lopputuloksia olisivat merkityksettömiä.

Mielestämme Sandelin valitus, kuten myös Laschin, on enintään puolia totta. Myöntämämme seikka on, että demokratia menettää merkitystään, jos hallituksilla ei ole voimaa pakottaa yksilöitä käyttäytymään poliitikkojen vaatimalla tavalla – mikä on itsestään selvää. Todellisuudessa demokratia sellaisena kuin sitä 1800- ja 1900-luvuilla tunnettiin, on määrä kadota. Mutta Sandel ei huomioi todellista merkitystä siitä, miten markkinoiden voitto pakottamista vastaan muuttuu ratkaisevaksi. Hänen viittauksensa 'corporate rule' -periaatteeseen vaarana kansallisvaltion romahtamisen yhteydessä on häikäisevän anakronistinen.

Yritykset eivät todennäköisesti pääse hallitsemaan uuden globaalin talouden markkinoita. Itse asiassa, kuten olemme ehdottaneet, ei ole ollenkaan ilmeistä, että yritykset edes jatkaisivat olemassaoloaan tutulla modernilla muodollaan. Päinvastoin. Yritysten on lähes pakko muuttua sen megapoliittisen vallankumouksen myötä, joka seurauksena informaatiokauden käyttöönotosta. Kuten aiemmin olemme käsitelleet, mikrosuorituskyky muuttaa „informaatiokustannuksia”, jotka vaikuttavat yrityksiä määrittävien „sopimussuhteiden yhteyksiin”. Kuten ekonomistit Michael C. Jensen ja William H. Meckling ehdottavat, yritykset ovat vain yksi juridinen muoto, joka tarjoaa „yhteyden joukolle yksilöiden välisiä sopimussuhteita.” [^457]

Se, pystyykö yritys edes selviytymään – puhumattakaan siitä, että se voisi „hallitsemalla” toimia sellaisena birokraattisen ohjauksen alueena, joka on suojassa markkinavoimilta –, määräytyy todennäköisesti, kuten ekonomistien Louis Puttermanin ja Randall S. Krosznerin sanojen mukaan, markkinavoimien täydellisyyden ja niiden kyvyn tunkeutua yrityksen sisäisiin suhteisiin perusteella.[^458]

Kuten aiemmin argumentoitimme, on epäilyttävää, että yritykset pystyisivät selviytymään yhä lisääntyvästä markkinavoimien tunkeutumisesta siihen, mitä tähän asti on pidetty ”yritysten sisäisinä suhteina”. Tämän seurauksena yritykset hajoavat, kun informaatioteknologia tekee palkkamekanismin ja huutokauppamarkkinan hyödyntämisestä kannattavampaa tehtävien hoitamisessa kuin niiden sisäistä järjestäytymistä. Kun informaatioteknologia yhä enemmän automatisoi tuotantoprosesseja, se vie osan yrityksen *raison d’être* -syystä, eli tarvetta työllistää ja motivoida johtajia valvomaan yksittäisiä työntekijöitä.

### Miksi yrityksiä on olemassa?

Muista, että kysymys ’Miksi yrityksiä on olemassa?’ ei ole niin triviali kuin satunnainen tarkastelu saattaisi antaa ymmärtää. Mikroekonomia olettaa yleensä, että hintamekanismi on tehokkain keino koordinoida resursseja niiden arvokkaimpiin käyttötarkoituksiin. Kuten Putterman ja Kroszner toteamaan, tämä viittaa siihen, ettei organisaatioilla – kuten yrityksillä – ole mitään sisäistä „taloudellista raison d’êtreä”.[^459] Tässä märkässä mielessä yritykset ovat pääasiassa informaation ja transaktiokustannusten artefakteja, joita informaatioteknologiat pyrkivät radikaalisti vähentämään.

Siispä informaatiovaikakausi tulee luonnostaan olemaan itsenäisten urakoitsijoiden aikakausi ilman perinteisiä "työpaikkoja", mutta pitkäikäisillä "yrityksillä". Teknologian laskiessa transaktiokustannuksia juuri se prosessi, joka mahdollistaa yksilöiden vapautumisen poliitikkojen hallinnasta, estää myös "yritysten sääntövallan". Yritykset kilpailevat "virtuaaliyrityksinä" ympäri maailman sellaiseen astetta, joka häiritsee ja uhkaa lähes kaikkia, ja suurin osa yrityksistä instituutioina on onnekas selviytymään kiristyvästä kilpailusta markkinoiden täyttyessä.

Odotettavissa oleva seuraus ei ole se, että yksilöt joutuisivat yritysten armoille – päinvastoin, yrityksillä itsellään ei ole enempää valtaa vaikuttaa markkinoiden toimintaan kuin poliitikoilla. Pikemminkin yksilöt saavat vihdoin olla vapaita määrittämään oman kohtalonsa todellisesti vapaassa markkinassa, jota eivät ohjaa suuret hallitukset eivätkä yrityshierarkiat.

Transaktiokustannusten rapautuminen kumoaa myös viime aikoina suosittuja käsityksiä "sidosryhmäkapitalismista". Näitä ajatuksia, joita arvostavat muun muassa Britannian Labour-puolueen Tony Blair sekä osat Bill Clintonin seurueesta, tarkastellaan usein valtion kykyyn manipuloida yrityksiä. Sosialismin romahtua interventiohaluiset unelmoivat nyt saavuttavansa sosialismin päämäärät markkinoita tehokkaammilla keinoilla säätelemällä yrityksiä ankarasti. Tämä uusi uudelleenjako-teoria perustelee, että yritysten johto, osakkeenomistajat, työntekijät ja "yhteisö" ovat kaikki yritysten "sidosryhmiä" – he kaikki saavat etuja pitkäikäisistä yrityksistä ja ovat jopa riippuvaisia niistä. Siksi sääntelyn tulisi suojella niitä intressejä, joita johtajat, työntekijät ja paikalliset veroviranomaiset omaavat yritysten historiallisten suhteiden jatkuvuudessa.

"Sidosryhmäkapitalismi" on oppi, joka lopulta edellyttää paitsi valtion kykyä manipuloida yritysten päätöksentekoa, myös oletusta siitä, että yritykset ovat pitkäikäisiä organisaatioita, jotka kykenevät toimimaan itsenäisesti huutokauppamarkkinoiden hintasignaaleista huolimatta.

Arvelumme mukaan markkinoiden syventyminen ei ainoastaan rajoita valtioiden verotusvaltaa, vaan rapauttaa myös poliitikkojen kykyä määrätä mielivaltaisesti resurssien omistajien tahdosta sääntelyn keinoin. Maailmassa, jossa alueelliset etulyöntiasemat joutuvat markkinakokeiden alaisiksi ja monet paikalliset markkinat avautuvat kilpailulle mistä tahansa, on tuskin odotettavissa, että paikallisilla "yhteisöillä" olisi paljon tehokkaita keinoja eristää suosikkiyrityksensä globaalilta kilpailupaineelta. Näin ollen niillä on vain vähän mahdollisuuksia varmistaa, että yritykset, joilla on korkeammat kustannukset (esimerkiksi tarpeettomien työntekijöiden ja johtohenkilöstön pitämiseksi ja ylimääräisten tilojen ylläpitämiseksi paikallisten poliittisten paineiden vuoksi), pystyvät kattamaan nämä kustannukset ja pysymään elinkelpoisina. Teollisuusajalla poliitikot pystyivät sulkemaan markkinat ja rajoittamaan pääsyn vain muutamille suosikkiyrityksille täyttääkseen työllisyys- ja muut tavoitteet. Tulevaisuudessa, kun tieto on vapaasti vaihdettavissa kaikkialla, hallitusten mahdollisuudet suojata paikallisia yrityksiä globaalilta kilpailulta ovat minimaaliset.

Ei ole myöskään todennäköistä, että vaatimukset "uudesta yhteiskuntasopimuksesta", joka keskittyy niin sanottuun riippumattomaan tai vapaaehtoiseen sektoriin sitomaan muuten työttömien tai syrjäytyneiden työntekijöiden aikaa "yhteisössä", osoittautuisivat käyttökelpoisiksi.[^460] Jeremy Rifkin kuvittelee "uutta kumppanuutta hallituksen ja kolmannen sektorin välillä sosiaalitalouden uudelleenrakentamiseksi. ... Ruoan jakaminen köyhille, perustason terveydenhuoltopalvelujen tarjoaminen, kansakunnan nuorten kouluttaminen, kohtuuhintaisten asuntojen rakentaminen ja ympäristön suojeleminen. ..." [^461]

### Julkishyödykkeiden himmeneminen

Tietysti pakottamisen puolustajat väittävät, että valtionvallan hiipuminen johtaa julkishyödykkeiden hankinnan tai nauttimisen kyvyttömyyteen. Tämä on epätodennäköistä sekä kilpailullisista että muista syistä. Ensinnäkin, kun sijainnilliset edut ovat pääosin hälvenneet teknologian myötä, ne alueelliset toimivalta-alueet, jotka epäonnistuvat tarjoamaan välttämättömiä julkishyödykkeitä, kuten lain ja järjestyksen ylläpitoa, menettävät nopeasti asiakkaansa. Äärimmäisimmissä epäonnistumistapauksissa, kuten jo on nähty Somalian, Liberian, Ruandan ja entisen Jugoslaviaa koskevissa tapauksissa, katsomattomat rahattomat pakolaiset saattavat virrata yli rajojen etsiessään tyydyttävämpää lain ja järjestyksen toteutumista. Nämä äärimmäiset esimerkit pakenemisesta eli "äänestämisestä jaloilla" eroavat toisistaan vain kiireellisyydessään suorasta toimivallan kilpailusta. Joka tapauksessa yritykset pakottavat paikalliset toimivalta-alueet vastaamaan asiakkaidensa tarpeita.

### "Kilpailukykyiset alueelliset klubit"

Tämä ei ole pelkkä teoria, kuten taloustieteilijä Charles Tiebout esitti ensimmäisenä vuonna 1956.[^462] Taloustieteilijä Fred Foldvary on dokumentoinut teoksessaan *Public Goods and Private Communities: The Market Provision of Social Services*, ettei ole olemassa olennaista syytä, miksi sosiaalisia palveluja ja monia julkishyödykkeitä tulisi tarjota pelkästään poliittisin keinoin. Foldvaryn esimerkit muun muassa vahvistavat myös Nobel-palkitun taloustieteilijä Ronald Coasen kiistanalaisen teoreeman, jonka mukaan "hallituksen interventioita ei tarvita ulkoisvaikutusten, kuten saastumisen, ongelmien ratkaisemiseksi."[^463] Yrittäjät voivat tarjota kollektiivisia hyödykkeitä markkinakeinoin. Monet tekevät tätä jo nyt tosielämän yhteisöissä. Foldvaryn tapaustutkimukset osoittavat, kuinka yhteisöjen yksityistämisen seurauksena syntyy uusia mekanismeja julkishyödykkeiden ja palvelujen tarjoamiseksi ja rahoittamiseksi.[^464]

Mikroteknologia helpottaa uusia keinoja rahoittaa ja säädellä hyödykkeiden tuotantoa, joita aiemmin on pidetty julkisina hyödykkeinä. Jälkikäteen tarkasteltuna osa näistä hyödykkeistä osoittautuu olleen yksityisiä hyödykkeitä naamioituneina. Moottoritiet ovat keskeinen esimerkki. Niin kauan kuin ruuhkautuminen oli vähäinen ongelma, teitä ja moottoriteitä voitiin käsitellä ikään kuin ne olisivat julkisia hyödykkeitä, vaikkakin Adam Smith kritisoi niitä siitä, että ne hyödyttävät suhteettomasti lähialueen asukkaita kustannuksella syrjäisillä alueilla asuvista, jotka joutuvat maksamaan niistä ja saavat samalla vain vähän hyötyä.

Tietoyhteiskunnan aikakaudella on teknologisesti mahdollista asettaa tulleja – mukaan lukien ruuhkamaksuja – jotka hinnoittelevat tarkasti pääsyn moottoriteille, lentokentille ja muuhun infrastruktuuriin keskeyttämättä liikennevirtaa. Näin liikenneinfrastruktuurin tarjoaminen voitaisiin yksityistää hienovaraisesti ja rahoittaa suoraan niiltä, jotka käyttävät palvelua. Taloustieteilijä Paul Krugman arvioi, että Yhdysvaltain liikenneinfrastruktuurin markkinahinnoittelu lisäisi vuosittain 60–100 miljardilla dollarilla CIDP:tä Yhdysvalloissa, parantaen samalla resurssien tehokkuutta ja vähentäen saastumista.[^465]

Lisäksi ei tule unohtaa, että modernien valtioiden toiminnan – tulojen uudelleenjaon – kallein osa ei johdu julkisen hyödykkeen tarjoamisesta, vaan yksityisten hyödykkeiden tarjoamisesta julkisilla kustannuksilla. Tässä termillä "julkinen kustannus" tarkoitetaan ikään kuin sitä, että maksajat kantavat kustannuksen.

Mitä sitten on aito julkinen hyödyke, kuten sotilaallisen joukon tarjoaminen, joka kykenee pelottelemaan suurvallan hyökkäystä? Tällainen voima on perinteisesti ollut kallista. Ilmiselvää onkin, kuten olemme jo tarkastelleet, että hallitus, jolla ei ole rajoittamatonta valtaa takavarikoida kansalaistensa tuloja ja omaisuutta, ei pystyisi rahoittamaan osallistumistaan toisen suurvallan konfliktiin, kuten toiseen maailmansotaan.

Silti tämä finanssirajoite uhkaa vähemmän kuin reaktionäärien väitetään, yksinkertaisesta syystä, että toisen maailmansodan kaltaisia konflikteja ei enää tule. Juuri se teknologia, joka vapauttaa yksilöitä, varmistaa tämän.

### Politiikasta ylös

Sen sijaan, että tällaisen palvelun laatu ja luonne jätettäisiin politiikan armoille, 'hallituksia' voidaan pyörittää yrittäjähenkisesti ja muuttaa sellaisiksi kuin Foldvary kuvailee 'kilpailukykyisiksi alueellisiksi klubeiksi.' Uskomme, että lopulta päätöksentekoprosessi, jolla tällaiset "kilpailukykyiset alueelliset klubit"[^466] organisoidaan, merkitsee paljon vähemmän kuin niiden menestys markkinakokeissa. Nykyään harvat kuluttajat välittävät siitä, onko tuotetta tai palvelua myyvä yritys yksityisomistuksessa, osakeyhtiö tai ulkopuolisten hallituksen jäsenten nimittämä yhtiö, jonka salkkuja valvovat eläkejärjestelmät. Vastaavasti epäilemme, että tietoan aikakauden järkevä suvereniteettipalveluiden kuluttaja välittää siitä, onko Singapore massademokratia vai Lee Kwan Yewn omaisuus.

[^430]: John Dunn, *Western Political Theory in the Face of the Future*, Cambridge, Eng.: Cambridge University Press. 1979, s. 2.

[^431]: Carroll Quigley, *Weapons Systems and Political Stability* (Washington, D.C.: University Press of America, 1983).

[^432]: Sama lähde, s. 56.

[^433]: Lainattu Kellyn *op. cit.* -teoksesta, s. 46.

[^434]: Molander ym., Strategic Information Warfare, op. cit., s. xv.

[^435]: Sama lähde, s. xiv.

[^436]: Dennis C. Mueller, *Public Choice*, vol. 2 (Cambridge: Cambridge University Press, 1989), s. 43–226.

[^437]: Michael A. Bernstein, *The Great Depression: Delayed Recovery and Economic Change in America, 1929-1939* (Cambridge: Cambridge University Press, 1987).

[^438]: Mancur Olson, *The Rise and Decline of Nations: Economic Growth, Stagflation, and Social Rigidities* (New Haven: Yale University Press, 1982).

[^439]: Michael M. Phillips, 'Math Ph.D.s Add to Anti-Foreigner Wave: Scholars Facing High Jobless Rate Seek Immigration Curbs,' *Wall Street Journal*, 4. syyskuuta 1996, s. A2.

[^440]: Juan J. Linz ja Alfred Stepan (toim. ed.), *The Breakdown of Democratic Regimes* (Baltimore, Md.: The Johns Hopkins University Press, 1978), s. 18.

[^441]: William Keech, Economic Politics: The Costs of Democracy (Cambridge: Cambridge University Press, 1995), s. 221.

[^442]: E.S. Staveley, Greek and Roman Voting and Elections (Ithaca, N.Y.: Cornell University Press, 1972), s. 62.

[^443]: Ibid., s. 65.

[^444]: Norman Cohn, The Pursuit of the Millennium (Oxford: Oxford University Press, 1970), s. 41.

[^445]: Ibid., s. 84–85.

[^446]: Lainattuna Kelly'n teoksesta, *op. cit.*, s. 46.

[^447]: Milton Friedman, *Capitalism and Freedom* (Chicago: University of Chicago Press, 1962), s. 91. Käsitelty Hirschmanin toimesta, *op. cit.*, s. 16–17.

[^448]: Hirschman, *op. cit.*, s. 17.

[^449]: Neil Munro, 'The Pentagon's New Nightmare: An Electronic Pearl Harbor,' *Washington Post*, 16. heinäkuuta 1995, s. C3.

[^450]: E. J. Dionne, 'Why the Right Is Wrong,' *Utne Reader*, kesäkuussa 1996, s. 32.

[^451]: Ernst Cassirer, *The Myth of the State* (New Haven: Yale University Press, 1946), s. 81.

[^452]: John B. Morrall, *Political Thought in Medieval Times* (New York: Harper Torchbooks, 1962), s. 15.

[^453]: Ibid., s. 16.

[^454]: Cassirer, *op. cit.*, s. 142, 150.

[^455]: Robert I. Shapiro, 'Flat Wrong: New Tax Schemes Can't Top Old Progressive Truths', *Washington Post*, 24. maaliskuuta 1996, s. C3, ja Thomas L. Friedman, 'Politics in the Age of NAFTA', *New York Times*, 7. huhtikuuta, s. Eli.

[^456]: Lainattuna Friedmanin *op. cit.*

[^457]: Katso Louis Putterman ja Randall S. Kroszner, 'The Economic Nature of the Firm: A New Introduction,' kirjassa Louis Putterman ja Randall S. Kroszner (toim.), *The Economic Nature of the Firm: A Reader* (Cambridge: Cambridge University Press, 1996), s. 17.

[^458]: Sama.

[^459]: Sama, s. 9.

[^460]: Katso Jeremy Rifkin, *The End of Work: The Decline of the Global Labor Force and the Dawn of the Post-Market Era* (New York: G.P. Putnam's Sons, 1995).

[^461]: Sama, s. 250.

[^462]: Katso Charles M. Tiebout, 'A Pure Theory of Local Expenditure,' *Journal of Political Economy* 64 (1956), s. 416–24

[^463]: Mueller, *op. cit.*, s. 28–29.

[^464]: Fred Foldvary, *Public Goods and Private Communities: The Market Provision of Social Services* (Aldershot, Hants, England: Edward Elgar Publishing, Ltd., 1994).

[^465]: Paul R. Krugman, 'The Tax-Reform Obsession,' *New York Times Magazine*, 7. huhtikuuta 1996, s. 37.

[^466]: Foldvary, *op. cit.*, s. 66f.