# Muutos vuonna 2000

> "Tuntuu siltä, että jotain suurta on tapahtumassa: kaaviot näyttävät väestön, hiilidioksidin ilmakehäpitoisuuksien, verkkosivustojen ja megatavujen (Mbyte) vuotuisen kasvun per dollari. Ne kaikki kohoavat kohti asymptoottista rajaa juuri vuosisadan vaihteessa: Singulariteetti. Kaiken, mitä tunnemme, loppu. Jotakin, mitä emme ehkä koskaan ymmärrä." [^1] - Danny Hillis

## Ennakkoluulot

Vuoden 2000 saapuminen on kummitellut länsimaista mielikuvitusta jo viimeisen tuhannen vuoden ajan. Sen jälkeen, kun maailma ei päättynyt Kristuksen jälkeisen ensimmäisen vuosituhannen vaihteessa, teologit, evankelistat, runoilijat ja tietäjät ovat katsoneet tämän vuosikymmenen loppua odottaen jotain merkittävää. Itse Isaac Newton spekuloi, että maailma päättyisi vuonna 2000. Michel de Nostradamus, jonka ennustuksia on luettu jokainen sukupolvi sen ensimmäisestä julkaisusta vuonna 1568 lähtien, ennakoi kolmannen antikristuksen saapumista heinäkuussa 1999.[^2] Sveitsiläinen psykologi Carl Jung, joka tunnetaan "yhteisestä alitietoisuudesta", näki uuden aikakauden syntymän vuonna 1997. Tällaiset ennusteet saattavat helposti herättää naurun. Samoin kauhukuulut ekonomistien taholta, kuten Deutsche Bank Securitiesin tohtori Edward Yardenin, joka odottaa millenniaalisen keskiyön tietokonevikojen "häiritsevän koko globaalia taloutta."[^3] Olipa Y2K-tietokoneongelmaa sitten pidetty perustamattomana hysteeriana, jota tietokoneohjelmoijat ja IT-konsultit ovat herättäneet liiketoiminnan vauhdittamiseksi, tai mystisenä teknologian pettymisenä, joka kulkee käsi kädessä ennustuksellisen mielikuvituksen kanssa, ei voi kiistää, että vuosituhannen kynnyksellä vallitsevat olosuhteet herättävät paljon enemmän kuin tavallista synkkää epäilystä siitä, mihin maailma on menossa.

Tulevaisuudesta vallinnut huolestuneisuus on alkanut varjostaa sitä optimistista henkeä, jolle länsimaiset yhteiskunnat ovat tyypillisiä viimeiset 250 vuotta. Ihmiset kaikkialla ovat epävarmoja ja huolissaan. Näet sen heidän kasvoillaan, kuulet sen heidän keskusteluissaan, näet sen mielipidemittausten tuloksissa ja äänestyslaatikoissa. Niin kuin näkymätön fysikaalinen ionimuutos ilmakehässä ilmoittaa ukkosmyrskystä jo ennen kuin pilvet tummuvat ja salama iskee, niin nyt vuosituhannen hämärässä muutosennusteet leijuvat ilmassa. Yksi henkilö toisensa jälkeen, kukin omalla tavallaan, aistii ajan loppuvan kuolevan elämäntavan ylläpitämiseksi. Kun vuosikymmentä umpeutuu, sen mukana katoaa murhaava vuosisata ja loistava vuosituhannen mittainen aika, jolloin ihmiskunta on saavuttanut paljon. Kaikki päättyvät vuoteen 2000.
> Sillä ei ole mitään peitettyä, mikä ei paljastuisi, eikä mitään kätkettyä, mikä ei tultaisi tuntemaan." - Matteus 10:26

Uskomme, että länsimaisen sivilisaation moderni vaihe päättyy siihen. Tämä kirja kertoo miksi. Kuten monet aiemmat teokset, se on yritys nähdä tulevaisuuteen hämärän läpi, hahmottaen vielä määrittelemättömiä muotoja ja ulottuvuuksia. Tällaisessa merkityksessä tarkoitamme työnämme olevan apokalyptinen alkuperäisessä merkityksessään – apokalypsis tarkoittaa kreikaksi "paljastamista". Uskomme, että historian uusi vaihe – tietoyhteiskunta – on pian "paljastumassa."

> Olemme todistamassa uuden loogisen avaruuden alkuja, hetkellistä sähköistä kaikkiallaoloa, johon me kaikki voimme päästä käsiksi, astua siihen ja kokea sen. Meillä on lyhyesti sanottuna uudenlaisen yhteisön alku. Virtuaalinen yhteisö muodostuu maallisen Taivaan valtakunnan malliksi; kuten Jeesus totesi, Isän valtakunnassa on monia kartanoita, niin on olemassa lukuisia virtuaaliyhteisöjä, jotka heijastavat omia tarpeitaan ja toiveitaan. - Michael Grasso[^4]

## Ihmiskunnan neljä vaihetta

Tämän kirjan teema on uuden vallankumouksen synty, joka vapauttaa yksilöt 1900-luvun kansallisvaltion kustannuksella. Innovaatiot, jotka muuttavat väkivallan logiikkaa ennennäkemättömillä tavoilla, muokkaavat niitä rajoja, joiden sisällä tulevaisuuden on määriteltävä itsensä. Jos johtopäätöksemme ovat oikein, seisot kynnyksellä historian kattavimman vallankumouksen edessä. Mikroprosessointi mullistaa ja tuhoaa kansallisvaltion nopeammin kuin harvat nyt osaisivat kuvitella, samalla luoden uusia sosiaalisen organisoinnin muotoja. Tämä muutos ei tule olemaan lainkaan helppoa.
Haaste tulee olemaan entistä suurempi, koska se tapahtuu uskomattoman nopeasti verrattuna mihinkään aiemmin nähtyyn. Koko ihmiskunnan historian, sen alkuajoista nykypäivään, ajan on ollut vain kolme perustasoa talouselämässä: (1) metsästys-keräily-yhteiskunnat; (2) maatalousyhteiskunnat; ja (3) teollisuusyhteiskunnat. Nyt, horisontin takana, uhkaa jotain täysin uutta, sosiaalisen organisaation neljäs vaihe: tietoyhteiskunnat.

Jokainen aiemmista yhteiskuntavaiheista on vastannut selvästi erilaisia vaiheita väkivallan kehittymisessä ja hallinnassa. Kuten käymme yksityiskohtaisesti läpi, tietoyhteiskunnat lupaavat dramaattisesti vähentää väkivallan tuottoja, osittain siksi, että ne ylittävät paikallisuuden rajat. Kyberavaruuden virtuaalitodellisuus – mitä romaanikirjailija William Gibson kuvaili "yhteisymmärryshallusina" – on yhtä kaukana kiusaajien ulottumattomissa kuin mielikuvitus voi viipyä. Jos uusi vuosituhat tulee, laajamittaisen väkivallan hallinnan etulyöntiasema on huomattavasti pienempi kuin mihin se on koskaan kyennyt ennen Ranskan vallankumousta. Tämä tulee vaikuttamaan syvästi. Yksi seuraus on rikollisuuden kasvu. Kun laajamittaisen väkivallan järjestämisen tuotto romahtaa, pienemmän mittakaavan väkivallan tuotto todennäköisesti nousee. Väkivalta muuttuu satunnaisemmaksi ja paikallisemmaksi, ja järjestäytynyt rikollisuus laajenee.

Toinen looginen seuraus väkivallan tuottojen laskusta on politiikan horjuminen. On paljon näyttöä siitä, että 1900-luvun kansallisvaltiollisten kansallismyyttien noudattaminen rappeutuu nopeasti. Kommunismin kaatuminen on vain kaikkein silmiinpistävin esimerkki. Kuten tarkastelemme yksityiskohtaisesti, länsimaisten hallitusten johtajien moraalisuuden romahtaminen ja kasvava korruptio eivät ole satunnaisia ilmiöitä, vaan ne ovat todiste siitä, että kansallisvaltion potentiaali on ehtynyt. Monet sen johtajista eivät enää itse usko niitä yleisiä totuuksia, joita he julistavat, eivätkä muut enää usko heihin.

Historia toistaa itseään

Tämä tilanne muistuttaa merkittäviä yhtäläisyyksiä menneisyydestä. Aina kun teknologinen muutos erottaa vanhat muodot uusista, talouden liikkeitä ohjaavista voimista, moraaliset normit muuttuvat ja ihmiset alkavat suhtautua vanhojen instituutioiden johtajiin yhä halveksuvammin. Tämä laajalle levinnyt vastenmielisyys tulee esiin jo paljon ennen kuin ihmiset kehittävät uuden, yhtenäisen muutosideologian. Näin oli myöhäisellä viisitoista vuosisadalla, jolloin keskiaikainen kirkko oli feodalismi valtavin instituutio. Huolimatta yleisestä uskomuksesta "pappiviran pyhyydestä", sekä korkea- että matalampiarvoiset papiston jäsenet kohdeltiin äärimmäisellä halveksunnalla – aivan kuten nykyään poliitikkoja ja byrokraatteja kohdellaan.
Uskomme, että paljon voidaan oppia vertaamalla 1400-luvun lopun tilannetta, jolloin elämä oli täysin kyllästynyt organisoituun uskontoon, siihen, miten maailma tänä päivänä on kyllästynyt politiikkaan. 1400-luvun lopulla institutionalisoidun uskonnon tukemisen kustannukset olivat saavuttaneet historiallisesti ennennäkemättömän ääripään, aivan kuten nykyään hallituksen tukemisen kustannukset ovat nousseet äärimmäisen korkeiksi.

Tietämme, mitä tapahtui organisoidulle uskonnolle ruutiasevallankumouksen jälkeen. Teknologiset kehityssuunnat loivat vahvat kannustimet pienentää uskonnollisia instituutioita ja vähentää niiden kustannuksia. Samankaltainen teknologinen vallankumous on tuomassa radikaalia pienentämistä kansallisvaltion osalta uuden vuosituhannen alkuvaiheessa.

> Nykyään, yli vuosisadan sähköteknologian jälkeen, olemme laajentaneet keskushermostomme itsestään globaaliksi syleilyksi, poistaen sekä ajan että tilan merkityksen planeettamme suhteen.[^6]

### Tietovallankumous

Suurten järjestelmien murenemisen kiihtyessä järjestelmällinen pakottaminen vähenee tekijänä, joka muokkaa talouselämää ja tulojen jakautumista. Tehokkuudesta tulee nopeasti tärkeämpää kuin vallan määräykset sosiaalisten instituutioiden järjestämisessä. Tämä tarkoittaa, että maakunnat ja jopa kaupungit, jotka pystyvät tehokkaasti valvomaan omaisuusoikeuksia ja takaamaan oikeudenmukaisuuden toteutumisen samalla, kun ne kuluttavat vain vähän resursseja, tulevat olemaan elinkelpoisia itsemääräämisoikeuden alueita Tiedon aikakaudella – toisin kuin on yleensä ollut viimeisten viiden vuosisadan aikana. Kyberavaruudessa syntyy täysin uusi taloudellisen toiminnan alue, joka ei ole sidottu fyysiseen väkivaltaan. Ilmeisimmät hyödyt virtaavat "kognitiiviselle eliitille", jotka yhä enenevässä määrin toimivat poliittisten rajojen ulkopuolella. He ovat jo nyt yhtä kotonaan Frankfurtissa, Lontoossa, New Yorkissa, Buenos Airesissa, Los Angelesissa, Tokiossa ja Hongkongissa. Tulot tulevat muuttumaan epäyhtäläisemmiksi kunkin lainkäyttöalueen sisällä, mutta tasa-arvoisemmaksi niiden välillä.
Suvereenit yksilöt tutkii tämän vallankumouksellisen muutoksen sosiaalisia ja taloudellisia seurauksia. Haluamme auttaa sinua hyödyntämään uuden aikakauden tarjoamia mahdollisuuksia ja välttämään sen tuhoavan vaikutuksen. Jos vain puolet odotuksistamme toteutuu, edessäsi on muutos, jolla on harvat historialliset vertailukohdat.

Vuoden 2000 muutos ei ainoastaan mullista maailmantalouden luonnetta, vaan se tapahtuu nopeammin kuin mikään aiempi vaiheenvaihto. Toisin kuin maatalousvallankumous, informaatiovallankumous ei vie vuosituhansia, eikä teollinen vallankumous vaikuta vuosisatojen ajan. Informaatiovallankumous tapahtuu yhden eliniän aikana.

Mikä parasta, se tapahtuu lähes kaikkialla yhtä aikaa. Teknologiset ja taloudelliset innovaatiot eivät enää rajoitu pieneen osaan maailmaa. Muutos on käytännössä universaali, ja siihen sisältyy niin syvällinen katko menneeseen, että se melkein herättää henkiin jumalten maagisen valtakunnan, kuten varhaiset maatalousyhteisöt – esimerkiksi muinaiset kreikkalaiset – kuvittelivat. Suuremmassa määrin kuin useimmat nykyään myöntäisivät, monien nykyisten instituutioiden säilyttäminen uudessa vuosituhannessa osoittautuu vaikeaksi tai mahdottomaksi. Kun informaatioyhteiskunnat muotoutuvat, ne ovat yhtä erilaisia teollisyhteiskunnista kuin Aeschyluksen Kreikka oli luolaväen maailmasta.

## PROMETHEUS UNBOUND: THE RISE OF THE SOVEREIGN INDIVIDUAL

> En tiedä yhtään rohkaisevampaa tosiasiaa kuin vaaratonta kykyä, jonka avulla ihminen voi tietoisella ponnistelulla nostaa elämänsä uudelle tasolle. - Henry David Thoreau
Edessä oleva muutos on sekä hyviä että huonoja uutisia. Hyvinä uutisina on se, että tietovallankumous vapauttaa yksilöt tavalla, jota ei ole ennen nähty. Ensimmäistä kertaa ne, jotka kykenevät kouluttamaan itseään, ovat lähes täysin vapaita keksimään omaa työtään ja hyödyntämään täysimääräisesti oman tuottavuutensa edut. Nerokkuus vapautuu, sillä se irrotetaan sekä hallituksen sortosta että rodullisten ja etnisten ennakkoluulojen pidotteista. Tietoyhteiskunnassa ketään, joka on todellisuudessa kykenevä, ei pidätetä muiden huonosti muotoiltujen mielipiteiden vuoksi. Ei ole väliä, mitä suurin osa maan ihmisistä ajattelee rodustasi, ulkonäöstäsi, iästäsi, seksuaalisista taipumuksistasi tai siitä, miten pidät hiuksiasi. Kybertaloudessa he eivät koskaan näe sinua. Ruma, lihava, vanha ja vammainen kilpailevat nuorten ja kauniiden kanssa tasavertaisesti täysin värisokeassa anonymityydessä kyberavaruuden uusilla rajoilla.

### Ideat muuntuvat varallisuudeksi

Missä tahansa ansioita syntyy, niistä palkitaan ennennäkemättömällä tavalla. Ympäristössä, jossa suurin varallisuuden lähde on pään sisällä olevat ideat eikä pelkkä fyysinen pääoma, kuka tahansa, joka ajattelee selkeästi, voi potentiaalisesti rikastua. Tietokantaika tulee olemaan nousun ikä, sillä se tarjoaa huomattavasti tasavertaisemmat mahdollisuudet miljardien ihmisten osalta niillä alueilla, jotka eivät koskaan täysin hyötyneet teollisyhteiskunnan vaurastumisesta. Näistä kirkkaimmat, menestyneimmät ja kunnianhimoisimmat nousevat todellisina suvereenina yksilöinä.

Aluksi vain kourallinen saavuttaa täyden taloudellisen suvereniteetin, mutta tämä ei kumoa taloudellisen riippumattomuuden etuja. Se, että kaikilla ei ole yhtä valtavaa varallisuutta, ei tarkoita, että rikastuminen olisi turhaa tai merkityksetöntä. Jokaista miljardööriä kohti on 25 000 miljonääriä. Jos olet miljonääri etkä miljardööri, se ei tee sinusta köyhää. Vastaavasti tulevaisuudessa yksi niistä virstanpylväistä, joilla mittaat taloudellista menestystäsi, ei ole ainoastaan se, kuinka monta nollaa voit lisätä nettovarallisuuteesi, vaan myös se, pystytkö järjestämään asioitasi niin, että saat täyden henkilökohtaisen autonomian ja riippumattomuuden toteutumaan. Mitä älykkäämpi olet, sitä vähemmän voimaa tarvitset saavuttaaksesi taloudellisen pakenemisnopeuden. Jopa hyvin vaatimattomista varoista elävät henkilöt kohoavat, kun politiikan gravitaatiovaikutus globaaliin talouteen heikkenee. Ennennäkemätön taloudellinen riippumattomuus on saavutettavissa joko sinun elinaikana tai lastesi.

Tuottavuuden korkeimmalla tasanteella nämä suvereenit yksilöt kilpailevat ja ovat vuorovaikutuksessa sellaisissa suhteissa, jotka muistuttavat kreikkalaisten jumalten välisiä suhteita. Seuraavan vuosituhannen vaikeasti tavoiteltava Olimpos sijaitsee kyberavaruudessa – alueella, jolla ei ole fyysistä olemassaoloa, mutta joka silti kehittää sitä, mitä luvataan olevan maailman suurin talous uuden vuosituhannen toisella vuosikymmenellä. Vuoteen 2025 mennessä kybertalouteen osallistuu miljoonia ihmisiä. Jotkut heistä ovat yhtä rikkaita kuin Bill Gates, arvoltaan yli 10 miljardia dollaria kukin. Kyberköyhät saattavat olla niitä, joiden vuositulot ovat alle 200 000 dollaria. Kyberhyvinvointia ei tule olemaan – ei kyberveroja eikä kyberhallintoa. Kybertalous, eikä Kiina, voi hyvin olla seuraavien kolmenkymmenen vuoden suurin taloudellinen ilmiö.
Hyvä uutinen on se, että poliitikot eivät enää kykene hallitsemaan, tukahduttamaan ja säätelemään suurinta osaa kaupankäynnistä tässä uudessa valtakunnassa – samalla tavalla kuin antiikin kreikkalaisten kaupunkivaltioiden lainsäätäjät eivät olisi voineet trimmaamaan Zeuksen partaa. Tämä on hyvä uutinen varakkaille. Ja vielä parempaa uutista niille, jotka eivät ole niin varakkaita. Politiikan asettamat esteet ja taakot ovat enemmänkin esteitä rikastumiselle kuin itsessään varakkuudelle. Väkivallan vähenemiseen ja lainsäädäntöalueiden supistumiseen liittyvät hyödyt luovat mahdollisuuksia jokaiselle energiselle ja kunnianhimoiselle yksilölle hyötyä politiikan kuolemasta. Jopa hallintopalveluiden käyttäjät hyötyvät, kun yrittäjät laajentavat kilpailun etuja. Näin ollen suuri osa eri lainsäädäntöalueiden välisestä kilpailun kekseliäisyydestä kaavoitettiin sotilaallisiin ponnisteluihin. Kybertalouden etu puolestaan tuo kilpailuun uusia kriteerejä suvereniteettipalvelujen tarjoamisessa. Lainsäädäntöalueiden lisääntyminen merkitsee kokeilujen laajenemista uusilla tavoilla sopimusten täytäntöönpanon ja muutenkin ihmisten sekä omaisuuden turvallisuuden takaamiseksi. Suuren osan globaalin talouden vapautuminen poliittisesta ohjauksesta pakottaa kaikki jäljellä olevat hallinnolliset muodot toimimaan entistä lähemmäs markkinaehtoja. Lopulta niiden ei jää muuta vaihtoehtoa kuin kohdella alueidensa väestöä enemmän kuin asiakkaina ja vähemmän kuin järjestäytyneiden rikollisten hyväksikäyttämien uhrina.

### Politiikan ulkopuolella

Se, mitä mytologiassa kuvattiin jumalten provinssina, tulee muuttumaan elinkelpoiseksi vaihtoehdoksi yksilölle – elämäksi, joka on kuninkaiden ja neuvostojen ulottumattomissa. Ensin kymmenten, sitten satojen ja lopulta miljoonien mittakaavassa yksilöt pääsevät irti politiikan kahleista. Kun he tekevät niin, he muuttavat hallitusten luonnetta: pakottamisen alue supistuu ja yksityisten resurssojen hallinta laajenee.

Suvereenin yksilön nousu osoittaa jälleen myyttien outoa profeetallista voimaa. Vähän ajatellen luonnonlakeja, varhaiset maatalousyhteisöt kuvasivat, että "voimia, joita meidän pitäisi kutsua yliluonnollisiksi", oli laajalti läsnä. Näitä voimia käytettiin joskus ihmisten toimesta ja joskus "ruumiillistuneiden jumalien" – ihmismäisten jumalten – toimesta, jotka näyttivät ihmisiltä ja olivat vuorovaikutuksessa heidän kanssaan siinä, mitä Sir James George Frazer kuvaillikin teoksessaan *The Golden Bough* "suureksi demokratiaksi".

Kun muinaiset kuvittelivat Zeuksen lapsia elävän keskuudessaan, heitä innoitti syvä usko magiaan. He jakoivat muiden alkeellisten maatalousyhteisöjen kanssa luonnon mystiseen kunnioitukseen ja taikauskon vakaumukseen, jonka mukaan luonnon ilmiöt laukaistiin yksilöllisellä tahdolla – taikuuden keinoin. Tässä mielessä heidän käsityksensä luonnosta ja jumalista ei ollut lainkaan tietoisesti profeetallinen. He eivät osanneet edes kuvitella mikroteknologian vaikutuksia. He eivät olisi voineet kuvitella sen vaikuttavan yksilöiden rajalliseen tuottavuuteen tuhansia vuosia myöhemmin. Vielä enemmän he eivät olisi voineet ennustaa, miten se tasapainottaisi vallan ja tehokkuuden suhdetta ja mullistaisi siten omaisuuden muodostamisen ja suojelun tavat. Silti se, mitä he kuvasivat myytteissään, resonoi omituisesti maailmassa, jonka todennäköisesti kohtaat.
### Alt.Abracadabra

Taikailmoituksen "abracadabra" muistuttaa omituisella tavalla salasanaa, jota käytetään tietokoneeseen pääsyyn. Joillakin osin erittäin nopea laskenta on jo mahdollistanut geenien taian jäljittelyn. Ensimmäiset "digitaaliset palvelijat" tottelevat käskyjä niiltä, jotka hallitsevat tietokoneita, joissa ne on suljettu – aivan kuten henget suljettiin taikalamppuihin. Tietotekniikan virtuaalitodellisuus laajentaa ihmisen toiveiden maailmaa niin, että lähes mitä tahansa voidaan kuvitella todellisena. Teleläsnäolo antaa ihmisille saman kyvyn ylittää etäisyys yliluonnollisella nopeudella ja seurata etänä tapahtumia, kuten kreikkalaisten uskomusten mukaan Hermes ja Apollo pystyivät tekemään. Tietoyhteiskunnan suvereenit yksilöt, aivan kuten muinaisten primitiivisten myyttien jumalat, tulevat ajan myötä nauttimaan eräänlaisesta "diplomaattisesta koskemattomuudesta" useimmilta niistä poliittisista ongelmilta, jotka ovat kohdanneet kuolevaisia ihmisiä lähes kaikissa aikoina ja paikoissa.

Uusi suvereeni yksilö toimii myyttisten jumalten tavoin samassa fyysisessä ympäristössä kuin tavallinen kansalainen, mutta poliittisesti täysin omassa ulottuvuudessaan. Hän hallitsee huomattavasti suurempia resursseja ja on monien pakottamisen muotojen ulottumattomissa. Suvereeni yksilö uudelleenjärjestelee hallituksia ja muotoilee talouksia uudelleen uuden vuosituhannen aikana. Tämän muutoksen täysiä vaikutuksia on melkein mahdotonta edes kuvitella.

### Genius and Nemesis

Kaikkien niiden puolesta, jotka rakastavat inhimillistä pyrkimystä ja menestystä, Tietoyhteiskunta tarjoaa runsaasti rikkauksia – se on varmasti paras uutinen monille sukupolville. Mutta se tuo mukanaan myös huonoja uutisia. Yksilön autonomian voittoon ja todelliseen mahdollisuuksien tasa-arvoon perustuva uusi yhteiskuntajärjestys johtaa erittäin suuriin palkintoihin ansion perusteella ja merkittävään yksilölliseen itsenäisyyteen. Tämä asettaa yksilöt paljon vastuullisemmiksi omasta hyvinvoinnistaan kuin mitä teollisuusaikana on ollut tapana. Samalla se vähentää ansaitsemattomia etuja, joita kehittyneiden teollisuusmaiden asukkaat nauttivat koko 1900-luvun ajan. Kirjoittaessamme maailman ylä15 prosentilla asukkaista on keskimäärin 21 000 dollarin vuositulot per henkilö, kun taas loput 85 prosenttia tienaavat keskimäärin vain 1 000 dollaria. Tämä valtava, menneisyydessä kertyneenä pidetty etu on väistämättä hajaantuva Tietoyhteiskunnan uusien olosuhteiden vallitessa.
Samaan aikaan kansallisvaltioiden kyky uudelleenjakaa tuloja laajoissa mittakaavoissa romahtaa. Tietotekniikka mahdollistaa dramaattisesti lisääntyneen kilpailun eri toimivaltioiden välillä. Kun teknologia on liikuteltavaa ja kauppojen tapahtumat siirtyvät yhä enemmän kyberavaruuteen, hallitukset eivät enää pysty veloittamaan palveluistaan enemmän kuin mitä ne ovat maksajilleen todellisuudessa arvoltaan. Jokaisella, jolla on kannettava tietokone ja satelliittiyhteys, on mahdollisuus harjoittaa lähes mitä tahansa tietopalveluihin liittyvää liiketoimintaa missä tahansa – tämä kattaa lähes koko maailman monitiljardidolliset finanssitransaktiot.

Se tarkoittaa, ettei sinun enää tarvitse asua korkeaverotuksen alueella ansaitaksesi korkeita tuloja. Tulevaisuudessa, kun suurin osa vauraudesta on mahdollista ansaita ja jopa kuluttaa missä tahansa, hallitukset, jotka yrittävät periä liian suurta hintaa kotipaikasta, karkottavat vain parhaimmat asiakkaansa. Jos päättelyssämme on perää – ja uskomme sen olevan niin – kansallisvaltio sellaisena kuin sen tunnemme ei selviä milläänkaan nykyisessä muodossaan.

## Kansakuntien loppu

Muutos, joka heikentää vallitsevien instituutioiden voimaa, on yhtä häiritsevää kuin vaarallista. Aivan kuten kuninkaat, herrojen, paavien ja muun vallan omistajat ryhtyivät armottomasti taistelemaan säilyttääkseen vakiintuneet etuoikeutensa modernin aikakauden alkuvaiheissa, myös tämän päivän hallitukset turvautuvat väkivaltaan – usein salakavalalla ja mielivaltaisella tavalla – yrittäessään hidastaa ajan kulkua.

Teknologian asettaman haasteen heikentäminä valtio kohtaa yhä itsenäisempiä yksilöitä, entisiä kansalaisiaan, samalla armottomuuden ja diplomatian tasolla, jolla se tähän asti on kohdellut muita hallituksia. Tämän uuden historian vaiheen alkamista merkitsi August 20, 1998, kun Yhdysvallat ampui noin 200 miljoonan dollarin edestä Tomahawk BGM-109 -meriristeilyohjuksia kohteisiin, joiden väitettiin liittyvän maanpakoon joutuneeseen saudi-miljonääri Osama bin Ladeniin. Bin Ladenista tuli ensimmäinen henkilö historiassa, jonka satelliittipuhelin kohdistettiin risteilyohjusten hyökkäyksen kohteeksi. Samaan aikaan Yhdysvallat tuhosi Khartoumin, Sudanin, alueella toimineen farmaseuttisen tehtaan Bin Ladenin kunniaksi. Bin Ladenin nousu Yhdysvaltojen pääviholliseksi heijastaa valtavaa muutosta sodankäynnin luonteessa. Yksi yksittäinen henkilö, vaikkakin satoja miljoonia dollareita omaava, voidaan nyt esittää uskottavana uhkana teollisuusajan suurimmalle sotilasvallalle. Kylmän sodan propagandaa muistuttavissa lausunnoissa Yhdysvaltojen presidentti ja hänen kansallisen turvallisuuden avustajansa esittivät Bin Ladenin – yksityishenkilön – transnationaalisena terroristina ja johtavana vihollisena.

Sama sotilaallinen logiikka, jonka mukaisesti Osama bin Laden on noussut Yhdysvaltojen pääviholliseksi, tulee myös vaikuttamaan hallitusten sisäisiin suhteisiin kansalaisiinsa. Yhä ankarammat riistomenetelmät ovat looginen seuraus uudenlaisesta neuvottelutyylistä, joka kehittyy hallitusten ja yksilöiden välillä. Teknologia tekee yksilöistä lähes siirtokuntien suvereenimpia kuin koskaan aiemmin – ja heitä tullaan kohtelemaan juuri niin: joskus väkivalloin, vihollisina, toisinaan neuvottelukumppaneina tasa-arvoisina ja toisinaan liittolaisina. Mutta riippumatta siitä, kuinka armottomasti hallitukset käyttäytyvät, erityisesti siirtymäkaudella, jossa verohallinnon ja CIA:n yhdistäminen ei auta heitä paljoa, heidän on yhä useammin, välttämättömyyden voimasta, neuvoteltava itsenäisten yksilöiden kanssa, joiden resursseja ei enää pysty hallitsemaan yhtä helposti. 

Samuin sotilaallinen logiikka, joka on nostanut Osama bin Ladenin Yhdysvaltojen pääviholliseksi, tulee vaikuttamaan hallitusten sisäisiin suhteisiin kansalaisiinsa. Vähitellen hallitukset joutuvat neuvottelemaan autonomisten yksilöiden kanssa, joiden resursseja on vaikeampi kontrolloida, eikä mikään keskitetyistä viranomaisista – olipa kyseessä sitten verohallinto tai tiedusteluvirasto – pysty enää ratkaisemaan tätä ongelmaa yksinään.

Samalla kun hallitukset yritetään saada neuvotteluun entistä tiiviimmällä ohjauksella, teknologia tekee yksilöistä entistä itsenäisempiä. Tämä tarkoittaa sitä, että hallitukset tulevat kohtaamaan entistä enemmän kansalaisia, jotka vaativat suvereeniutta – joskus väkivaltaisesti vihollisina, joskus tasavertaisina neuvottelukumppaneina, joskus liittolaisina. 

Mutta aivan riippumatta siitä, kuinka armottomasti hallitukset käyttäytyvät siirtymäkaudella, jolloin verohallinnon ja tiedustelupalveluiden yhdistäminen ei tuo toivottua hyötyä, heidän on pakko neuvotella entistä enemmän itsenäisten yksilöiden kanssa, joiden omaisuutta ja resursseja ei enää pysty kontrolloimaan yhtä helposti.
Information Revolution -muutokset eivät ainoastaan aiheuta hallituksille finanssikriisiä, vaan ne myös hajottavat kaikki suuret rakenteet. Kaksitoista imperiumia on jo kadonnut 1900-luvulla. Imperiumien hajoaminen on osa prosessia, joka liu'uttaa kansallisvaltioiden olemuksen. Hallituksen on sopeuduttava yksilön kasvavaan autonomiaan. Verotuskapasiteetti romahtaa 50–70 prosentilla, mikä puolestaan suosii pienempiä oikeusalueita. Kyky asettaa kilpailukykyisiä ehtoja lahjakkaita yksilöitä ja heidän pääomaansa houkutellakseen toteutuu todennäköisemmin enklaveissa kuin mantereiden laajuisesti.

Uskomme, että modernin kansallisvaltion hajoamisen myötä nykyajan barbaarit tulevat yhä useammin käyttämään vallan taustalla. Ryhmät, kuten venäläinen mafiya, joka raottaa entisen Neuvostoliiton jäänteitä, muut etnilliset rikollisjengit, nimellisuuksia hyödyntävät tahot, huumekuningattaret ja kapinalliset salaiset virastot, muodostavat itsenäisiä lainalaisuuksia. He ovat jo sellaisia. Paljoa enemmän kuin yleisesti ymmärretään, modernit barbaarit ovat jo tunkeutuneet kansallisvaltion muotoihin muuttamatta sen ulkonäköä merkittävästi. He ovat mikropunkkeja, jotka ravitsevat kuolevaa järjestelmää. Samoin väkivaltaiset ja sääntöjenvastaiset kuin sodassa oleva valtio, nämä ryhmät soveltavat valtion tekniikoita pienemmässä mittakaavassa. Niiden kasvava vaikutus ja valta kuuluvat politiikan supistumiseen. Mikroprosessorointi pienentää sitä kokoa, johon ryhmien on tehokkaasti osattava väkivallan käyttö ja hallinta. Teknologisen vallankumouksen edetessä saalistava väkivalta organisoituu yhä enemmän keskitetyn kontrollin ulkopuolelle, ja väkivallan hillitsemisen pyrkimykset siirtyvät yhä useammin tehokkuuteen perustuviksi ennemminkin kuin vallan suuruuden mittaisiksi.

### Historia käänteisessä järjestyksessä

Se prosessi, jolla kansallisvaltio kasvoi viimeisen viiden vuosisadan aikana, käännetään uudeksi logiikaksi tietoaikana. Paikalliset vallan keskukset palauttavat asemansa, kun valtio hajoaa sirpaleisiksi, päällekkäisiksi itsemääräämisoikeuksiksi. Järjestäytyneen rikollisuuden kasvava voima on vain yksi tämän taipumuksen heijastus. Monikansalliset yhtiöt joutuvat jo nyt alihankkimaan kaiken paitsi välttämättömän työn. Jotkut konglomeraatit, kuten AT&T, Unisys ja ITT, ovat jakautuneet useiksi yrityksiksi toimiakseen kannattavammin. Kansallisvaltio hajoaa kuin kömpelö konglomeraatti, mutta todennäköisesti vasta sen jälkeen, kun rahoituskriisit pakottavat sen siihen.

Vallan lisäksi myös maailman työ muuttuu. Tämä tarkoittaa, että liiketoiminnan toimintatavat muuttuvat väistämättä. "Virtuaaliyritys" on todiste laajamittaisesta muutoksesta yrityksen luonteessa, jota helpottaa tiedon- ja transaktiokustannusten lasku. Tarkastelemme Information Revolution -muutoksen vaikutuksia yritysten hajottamiseen ja "hyvän työn" poistamiseen. Tietoaikana "työ" tarkoittaa tehtävää, ei asemaa, jonka sinulla "on". Mikroprosessorointi on luonut aivan uusia taloudellisia horisontteja, jotka ylittävät alueelliset rajat. Rajojen ja alueiden ylittäminen on ehkä kaikkein vallankumouksellisinta kehitystä siitä lähtien, kun Aatami ja Eeva eksyivät paratiisista Luojansa tuomion alla: "Hikihuoneesi hiki huoneessa saat syödä leipää." Kun teknologia mullistaa työkalumme, se vanhentaa myös lakimme, muokkaa moraaliamme ja muuttaa havaintojamme. Tämä kirja selittää kuinka.
Mikroprosessointi ja nopeassa vauhdissa kehittyvät viestintäkeinot mahdollistavat jo yksilölle sen, missä hän työskentelee. Internetissä ja World Wide Webissä toteutettavat kauppatoimet voidaan salata, ja pian niiden sieppaaminen veronkerääjiltä tulee lähes mahdottomaksi. Verovapaat varat kasautuvat nykyään huomattavasti nopeammin ulkomaisissa keskuksissa kuin mantereella toimivat varat, joita edelleen rasittaa kaksikymmentästen kansallisvaltioiden asettama korkea verorasitus.

Vuosituhannen vaihteen jälkeen suuri osa maailman kaupankäynnistä siirtyy uuden kyberavaruuden alueelle, jolla hallituksilla ei ole enempää valtaa kuin mitä ne ovat meren pohjasta tai ulkoplaneettojen yli. Kyberavaruudessa aikojen alusta lähtien politiikassa keskeisenä roolina olleet fyysisen väkivallan uhkat katoavat, ja siellä nöyrät sekä mahtavammat kohtaavat tasa-arvoisin ehdoin. Kyberavaruus on lopullinen offshore-oikeusalue – talous ilman veroja. Se on kuin Bermuda taivaalla, täynnä timantteja.

Kun tämä kaikkien joukossa suurin veroparatiisi on täysin auki liiketoiminnalle, kaikki varat muodostuvat pohjimmiltaan omistajansa harkinnan mukaan ulkomaisiksi sijoituksiksi. Tämä muutos aiheuttaa sarjaheitä seurauksia. Valtio on tottunut kohtelemaan veronmaksajiaan kuin maanviljelijä lehmänsä: se pitää ne laitumella lypsettäväksi. Pian lehmillä on siivet.

Kansojen kosto

Kuin vihaisen maanviljelijän tavoin valtio ryhtyy epäilemättä ensin epätoivoisiin toimiin sitoutuakseen ja rajoittaakseen karjaansa, joka yrittää paeta. Se käyttää salaisia ja jopa väkivaltaisia keinoja estääkseen pääsyn vapauttaviin teknologioihin. Tällaiset toimenpiteet toimivat vain väliaikaisesti, jos lainkaan. Kaksikymmentästen kansallisvaltio, kaikilla kunnianhimollaan, nälkiintyy kuollakseen, kun sen verotulot vähenevät.

Kun valtio huomaa, ettei se pysty kattamaan kiinteitä menojaan verotuloja nostamalla, se turvautuu muihin entistä epätoivoisempiin keinoihin, kuten rahan painamiseen. Hallitukset ovat tottuneet nauttimaan valuutan monopoliasemasta, jonka arvoa ne voivat halutessaan heikentää. Tätä mielivaltainen inflaatiota on käytetty kaikkien kaksikymmentästen valtioiden rahapolitiikassa. Jopa parhaan jälkityasodan kansallisen valuutan, Saksan markan, arvo laski 71 prosenttiin 1. tammikuuta 1949 alkaen aina kesäkuun 1995 loppuun, ja samassa ajassa Yhdysvaltain dollari menetti 84 prosenttia arvostaan.[^9] Tämä inflaatio vaikutti samalla tavalla kuin vero kaikille, jotka pitävät valuuttaa hallussaan.

Kuten myöhemmin tarkastelemme, inflaatio rahavirtavaihtoehtona estyy suurimmalta osin kyberrahan ilmaantumisen myötä. Uudet teknologiat antavat varallisuuden haltijoille mahdollisuuden ohittaa ne kansalliset monopoliasemat, jotka ovat nykyaikana liikkeeseen laskeneet ja säätäneet rahaa. Itse asiassa vuonna 1997–1998 Aasiaa, Venäjää ja muita kehittyviä talouksia ravistaneet luottokriisit todistavat, että kansalliset valuutat ja kansalliset luottoluokitukset ovat ajattomia ja haitallisia maailmanlaajuisen talouden sujuvalle toiminnalle. Juuri se tosiasia, että suvereniteetin vaatimukset edellyttävät kaikkien lainkäyttöalueen sisäisten tapahtumien olevan laskettuja kansallisella valuutalla, luo haavoittuvuuden keskuspankkiirien virheille ja spekulanttien hyökkäyksille, jotka laukaisivat deflaatiokriisejä toisensa jälkeen.

Tietoyhteiskunnassa yksilö pystyy käyttämään kybervaluuttoja ja näin julistamaan rahallisen itsenäisyytensä. Kun yksilöt voivat toteuttaa omia rahapoliittisia toimiaan World Wide Webin välityksellä, ei ole enää niin tärkeää, tai lainkaan, että valtio jatkaa teollisaikojen painokoneiden hallintaa. Teollisessa mielessä rahavallan rooli maailman varallisuuden hallinnassa ylittyy matemaattisilla algoritmeilla, joilla ei ole fyysistä olemassaoloa. Uudella vuosituhannella yksityisten markkinoiden hallitsema kyberraha syrjäyttää valtioiden liikkeeseen laskemat perinteiset rahamoodit. Vain köyhät joutuvat inflaation ja sen jälkeisten deflaatioiden uhreiksi, mikä on seurausta siitä keinotekoisesta vipuvaikutuksesta, jonka fiat-raha syöttää talouteen.

___

Kun tämä kaikkien joukossa suurin veroparatiisi on täysin auki liiketoiminnalle, kaikki varat muodostuvat pohjimmiltaan omistajansa harkinnan mukaan ulkomaisiksi sijoituksiksi. Tämä muutos aiheuttaa sarjaheitä seurauksia. Valtio on tottunut kohtelemaan veronmaksajiaan kuin maanviljelijä lehmänsä: se pitää ne laitumella lypsettäväksi. Pian lehmillä on siivet.

Kansojen kosto

Kuin vihaisen maanviljelijän tavoin valtio ryhtyy epäilemättä ensin epätoivoisiin keinoihin sitoutuakseen ja rajoittaakseen paeta yrittävän karjansa. Se käyttää salaisia ja jopa väkivaltaisia keinoja rajoittaakseen pääsyn vapauttaviin teknologioihin. Tällaiset toimenpiteet toimivat vain hetkellisesti, jos lainkaan. Kaksikymmentästen kansallisvaltio, kaikilla kunnianhimollaan, nälkiintyy kuollakseen, kun sen verotulot vähenevät.

Kun valtio huomaa, ettei se pysty kattamaan menojaan verotuloja nostamalla, se turvautuu muihin, entistä epätoivoisempiin keinoihin. Yksi näistä on rahan painaminen. Hallitukset ovat tottuneet nauttimaan valuutan monopoliasemasta, jonka arvoa ne voivat halutessaan heikentää. Tätä mielivaltainen inflaatiota on käytetty kaikkien kaksikymmentästen valtioiden rahapolitiikassa. Tämä inflaatio vaikutti samalla tavalla kuin vero kaikille, jotka pitävät valuuttaa hallussaan.

Uusiin teknologioihin perustuvat menetelmät tulevat antamaan varallisuuden haltijoille mahdollisuuden ohittaa ne kansalliset monopoliasemat, jotka ovat nykyaikana liikkeeseen laskeneet ja sääntäneet rahaa. Luottokriisit, jotka pyyhkäisivät läpi Aasian, Venäjän ja muiden kehittyvien talouksien vuonna 1997–1998, todistavat, että kansalliset valuutat ja luottoluokitukset ovat ajattomia ja estävät sujuvan globaalin talouden toiminnan. Juuri se tosiasia, että suvereniteetin vaatimukset edellyttävät kaikkien lainkäyttöalueen sisäisten tapahtumien olevan laskettuja kansallisella valuutalla, altistaa järjestelmät keskuspankkiirien virheille ja spekulanttien hyökkäyksille, mikä johti deflaatiokriiseihin toisensa jälkeen.

Tietoyhteiskunnassa yksilö pystyy käyttämään kybervaluuttoja ja näin julistamaan rahallisen itsenäisyytensä. Kun yksilöt voivat toteuttaa omia rahapoliittisia toimiaan verkossa, ei ole enää niin olennaista, että valtio jatkaa teollisaikojen painokoneiden hallintaa. Näiden painokoneiden merkitys maailman varallisuuden hallinnassa siirtyy matemaattisten algoritmien käsiin, joilla ei ole fyysistä olemassaoloa. Uuden vuosituhannen aikana yksityisten markkinoiden hallitsema kyberraha syrjäyttää valtioiden liikkeeseen laskemat rahamuodot. Ainoastaan köyhät jäävät inflaation ja sitä seuranneiden deflaatiokriisien uhreiksi, mikä on seurausta fiat-rahan keinotekoisesta vipuvaikutuksesta.

[^9]: Katso muun muassa C.R. Fay, "Newton and the Gold Standard", s. 117–118.


Ilman perinteistä mahdollisuutta verottaa ja kasvattaa inflaatiota, hallitukset – jopa perinteisesti sivistyneissä maissa – muuttuvat ilkeiksi. Tuloverojen perimisen vaikeutuessa vanhemmat ja mielivaltaisemmat perintämenetelmät nousevat takaisin käyttöön. Epätoivoisina estääkseen varallisuuden pakenemisen, hallitukset aikovat ottaa käyttöön ylimmän veronpidätyksen muodon – käytännössä jopa avoimena panttivankienottoa. Onnettomat yksilöt joutuvat eristetysti ja lähes keskiaikaisin menetelmin lunnaan, kun taas yritykset, jotka tarjoavat palveluita yksilöiden autonomian saavuttamisen helpottamiseksi, ovat tunkeutumisen, sabotaasin ja häiriöiden kohteena. Mielivaltaiset omaisuuden menetystapaukset, joita tapahtuu jo nyt Yhdysvalloissa viitoseitsemän tuhatta kertaa viikossa, yleistyvät entisestään. Hallitukset rikkovat ihmisoikeuksia, sensuroivat tiedon vapaata virtausta, sabotoivat hyödyllisiä teknologioita ja tekevät vielä pahempia tekoja. Sillä samojen syiden vuoksi, minkä takia edes menehtynyt Neuvostoliitto yritti turhaan rajoittaa pääsyä henkilökohtaisiin tietokoneisiin ja Xerox-koneisiin, länsimaiden hallitukset pyrkivät sortamaan kybertaloutta totalitaarisin keinoin.

# Ludditen paluu

Tällaiset menetelmät saattavat osoittautua suosituiksi tiettyjen väestöryhmien keskuudessa. Uutiset yksilöllisestä vapautumisesta ja autonomiasta vaikuttavat monille, jotka eivät kuulu kognitiiviseen eliittiin, pahalta uutisilta. Suurin katkeruus keskittyy todennäköisesti niitä keskitasoisen lahjakkuuden omaavien keskuudessa, jotka nykyisin asuvat rikkaissa maissa. He saattavat erityisesti kokea, että informaatioteknologia uhkaa heidän elämäntapaansa. Järjestetyn pakotteen uhreiksi joutuneet – mukaan lukien miljoonat, jotka saavat hallituksen uudelleenjaettua tuloja – saattavat vastustaa suvereenien yksilöiden saavuttamaa uutta vapautta. Heidän pahastuksensa havainnollistaa totuutta, että "mihin istut, sen perusteella asemointisi määräytyy."

> Joskus mietin, kuinka voisin kokea syvää surua niiden miesten kohtalosta, joita en tuntenut, kun he pelasivat peliä toista tuntematonta joukkoa vastaan sadat kilometrät erossa olevassa stadionissa. Vastaus on yksinkertainen: rakastin omia joukkuvojani. Vaikka se oli riskialtista, välittäminen oli sen arvoista. Urheilu sytytti vereni, innosti minua ja sai sydämeni jyskyttämään. Pidin siitä, että minulla oli jotain panoksena. Elämä oli kilpailun aikaan elävämpää. – Craig Lambert

Olisi kuitenkin harhaanjohtavaa pitää kaikkia tulevassa muutostilanteessa syntyviä negatiivisia tunteita pelkästään haluna elää toisen kustannuksella. Tilanteessa on kyse paljon muustakin. Ihmiskunnan perusluonne viittaa siihen, että tulossa olevan luddittien reaktion yhteydessä on väistämättä väärin suuntautunut moraalinen ulottuvuus – ikään kuin kärkevälle halulle olisi asetettu päälle moraalinen peruukki. Tutkimme siirtymäkriisin moraalisia ja moraalisoivia ulottuvuuksia. Itsekkään tietoisen ahneudella on paljon vähemmän voimaa motivoida toimia kuin itseoikeutettua raivoa.

Vaikka 1900-luvun kansalaismyyttien noudattaminen on nopeasti kuihtumassa, niillä on yhä todelliset uskovansa. Jokainen, joka täytti 1900-luvulla, on kasvanut 1900-luvun kansalaisen velvollisuuksien ja tehtävien parissa. Teollisyhteiskunnasta periytyvät moraaliset imperatiivit herättävät vähintäänkin jonkin verran uus-luddittien hyökkäyksiä informaatioteknologiaa vastaan.
Tässä kontekstissa tuleva väkivalta tulee ainakin osittain ilmentämään sitä, mitä kutsumme "moraaliseksi anakronismiksi" – moraalisten sääntöjen soveltamista yhdestä talouden vaiheesta toisen olosuhteisiin. Jokainen yhteiskunnan vaihe vaatii omat moraaliset sääntönsä, jotta yksilöt pystyvät välttämään juuri heidän kohtaamiinsa valintoihin liittyvät kannustinloukut. Niin kuin viljely-yhteisö ei voisi elää vaeltavan eskimon ryhmän moraalisin sääntöin, tietoyhteiskunta ei kykene täyttämään niitä moraalisia velvoitteita, jotka syntyivät takaamaan teollisuusvaltion menestyksen kaksikymmenesvuosisadalla. Selitämme miksi.

Seuraavien vuosien aikana moraalista anakronismia tullaan näkemään lännen ydinkansojen keskuudessa samalla tavoin kuin sitä on viimeisten viiden vuosisadan ajan havaittu reuna-alueilla. Länsimaiset siirtokunnat ja sotilaalliset retket laukaisevat tällaisia kriisejä kohdatessaan alkuperäiskansoja, jotka harjoittavat metsästystä ja keräilyä, sekä kansoja, joiden yhteiskunnat olivat yhä maatalouteen järjestettyjä. Uusien teknologioiden tuominen anakronistisille ympäristöille aiheutti hämmennystä ja moraalikriisejä. Kristillisten lähetyssaarnaajien menestys miljoonien alkuperäiskansojen kääntämisessä voidaan suurelta osin selittää paikallisilla kriiseillä, joita ulkopuolelta äkillisesti tuotujen uusien valtasuhteiden käyttöönotto aiheutti. Tällaisia kohtaamisia tapahtui yhä uudelleen 1500-luvulta 1900-luvun alkuun asti. Odotamme samanlaisia ristiriitoja uuden vuosituhannen alussa, kun tietoyhteiskunnat syrjäyttävät teollisuustuotoksiin perustuvat järjestelmät.

### Pakon aikainen nostalgia

Itsemääräävän yksilön nousua ei tule täysin vastaanotetuksi lupauksellisen uuden historiallisen vaiheen merkkinä, edes niiden keskuudessa, jotka siitä hyötyvät eniten. Kaikki tuntevat jonkinlaista epäilyä, ja monet halveksivat innovaatioita, jotka heikentävät alueellista kansallisvaltiota. Ihmisluonteessa on se piirre, että minkä tahansa radikaalin muutoksen koetaan lähes aina dramaattisena kääntymyksenä huonompaan suuntaan. Viisisataa vuotta sitten Burgundin herttuan ympärille kokoontuneet hovivirkamiehet olisivat sanoneet, että feodalismia heikentävät uudet innovaatiot olivat pahoja. He ajattelivat, että maailma oli nopeasti liukumassa alas – juuri sillä hetkellä, kun myöhemmät historioitsijat näkivät renessanssin aikaan räjähtelevän inhimillisen potentiaalin. Vastaavasti se, mitä jonain päivänä saatetaan nähdä uutena renessanssina seuraavan vuosituhannen näkökulmasta, vaikuttaa väsyneille kaksikymmenesvuosisadan silmille pelottavalta.

On erittäin todennäköistä, että ne, jotka uusista tavoista loukkaantuvat, sekä monet, jotka kokevat niiden aiheuttavan haittaa, reagoivat epämiellyttävästi. Heidän pakon aikaista nostalgiaansa pakon perään todennäköisesti kääntyy väkivalta. Kohtaamiset näiden uusien "luddittien" kanssa tekevät siirtymisestä radikaaleihin uusiin sosiaalisen järjestäytymisen muotoihin ainakin osittain huonoja uutisia kaikille. Valmistaudu väistämään, sillä muutoksen nopeus ohittaa monien elossa olevien sukupolvien moraalisen ja taloudellisen sopeutumiskyvyn; voit odottaa kiivaata ja raivoavaa vastarintaa tietoyhteiskuntarevoluutiota kohtaan, huolimatta sen suuresta lupauksesta vapauttaa tulevaisuus.
Sinun on ymmärrettävä ja varauduttava tällaiseen epämiellyttävyyteen. Edessä on siirtymäkriisi. Deflatoriset koettelemukset – kuten Aasian tarttuminen, joka pyyhkäisi Ääritien kautta Venäjälle ja muihin kehittyviin talouksiin vuosina 1997 ja 1998 – puhkeavat satunnaisesti, kun teollisesta aikakaudesta periytyneet vanhentuneet kansalliset ja kansainväliset instituutiot osoittautuvat riittämättömiksi uuden, hajautuneen ja ylivaltaisen kansainvälisen talouden haasteisiin. Uudet tieto- ja viestintäteknologiat alistavat modernin valtion enemmän kuin mikään poliittinen uhka sen hallitsevuudelle sen jälkeen, kun Kolumbus purjehti. Tämä on tärkeää, sillä vallassa olevat eivät ole harvoin reagoineet rauhanomaisesti kehitykseen, joka on horjuttanut heidän auktoriteettiaan – eivätkä he todennäköisesti reagoi nyt niin.

Uuden ja vanhan välinen ristiriita muovaa uuden tuhannen vuoden ensimmäisiä vuosia. Odotamme sen olevan aikaa suuria vaaroja ja suuria palkkioita, aikaa, jolloin joillakin aloilla sivistys vähenee huomattavasti ja toisilla sen laajuus on ennennäkemätön. Yhä itsenäisemmät yksilöt ja konkurssiin menneet, epätoivoiset hallitukset kohtaavat toisensa uuden jakolinjan yli. Odotamme näkevämme radikaalin uudelleenjärjestelyn suvereniteetin luonteessa sekä politiikan käytännön kuoleman ennen kuin siirtymä on ohi; sen sijaan että valtio dominoisi ja kontrolloisi resursseja, olet nähdäväsi lähes kaikkien nykyisten hallituspalvelujen yksityistämisen. Välttämättömistä syistä, joita käsittelemme laajasti tässä kirjassa, tieto- ja viestintäteknologia tulee tuhoamaan valtion kyvyn periä palveluistaan enempää kuin ne ovat maksavien ihmisten arvokkaita.

> Hallitusten täytyy selviytyä siitä, mitä suvereniteetti tarkoittaa.  
> – Robert Martin

### Suvereniteetti markkinoiden kautta

Sellaiseen määrin, jota harvat edes kymmenen vuotta sitten osanneet kuvitella, yksilöt saavuttavat yhä enemmän itsenäisyyttä alueellisten kansallisvaltioiden yli markkinamekanismien avulla. Kaikki kansallisvaltiot ovat konkurssin ja niiden auktoriteetin nopean rapautumisen uhkaamassa. Niin mahtavia kuin ne ovatkin, jäljellä oleva voimansa on kyky tuhota, ei komentaa. Niiden mantereen ylittävät ohjukset ja lentotukialukset ovat jo esineitä – yhtä vaikuttavia ja hyödyttömiä kuin feodalismia edustavan viimeisen sothevosen jäljet.
Tietotekniikka mahdollistaa markkinoiden dramaattisen laajenemisen muuttamalla tapaa, jolla omaisuuseriä luodaan ja suojataan. Tämä on todellakin vallankumouksellista – se lupaa olla teollisyhteiskunnalle vielä mullistavampaa kuin ampumatarhan käyttöönotto feodaalisessa maataloudessa. Vuoden 2000 muutos merkitsee [^11] suvereniteetin kaupallistamista ja politiikan kuolemaa, aivan kuten aseet ennustivat valahypätystä vandottuun feodalismiin. Kansalaisuus katoaa aivan kuten ritareiden elämäntapa.

Uskomme, että aikaa yksilölliselle taloudelliselle suvereniteetille on tulossa. Aivan kuten valtioiden ”kansallistamat” terästehtaat, puhelinyhtiöt, kaivokset ja rautatiet on nopeasti yksityistetty ympäri maailmaa, näette pian yksityistämisen huipentuman – yksilön täydellisen denationalisoinnin. Uuden vuosituhannen suvereeni yksilö ei enää ole valtion omaisuutta, de facto näppärä erä valtion taloushallinnon taseessa. Vuoden 2000 jälkeisinä aikoina denationalisoidut kansalaiset eivät ole enää kansalaisia ollenkaan, vaan he ovat asiakkaita.

### Kaistanleveys voittaa rajat

Suvereniteetin kaupallistaminen tekee kansalaisuuden kansallisvaltiossa yhtä vanhanaikaiseksi kuin ritareiden vannomat lupaukset tuntuivat feodaalisuuden romahduksen jälkeen. Sen sijaan, että ihmiset olisivat verotuksen kohteena kuuluvia kansalaisia, 2000-luvun suvereeni yksilö on hallitusten asiakas, joka toimii ”uudessa loogisessa tilassa”. Hän neuvottelee itselleen juuri sen minimaalisen hallinnon, jota hän tarvitsee, ja maksaa siitä sopimuksen mukaan. Tietoajan hallitukset järjestäytyvät eri periaatteiden mukaan kuin mitä maailma on viime vuosisatojen aikana tottunut, ja osia lainkäyttöalueista sekä suvereniteettipalveluista muodostuu ”assortatiivisen parinmuodostuksen” kautta, jossa yhteensopivuudet – kaupallisetkin – ovat perusta, jonka varassa virtuaaliset lainkäyttöalueet ansaitsevat lojaalisuutta. Harvoin uudet suvereniteetit saattavatkin olla keskiaikaisen järjestön, kuten 900 vuotta vanhan Jerusalem, Rhodian ja Maltan suvereenin sotilashyppereiden, jäänteitä. Maltan ritarit, paremmin tunnettuina Knights of Maltaina, muodostavat rikkaiden katolilaisten yhteenkuuluvuusryhmän, jonka nykyjäsenmäärä on noin 10 000 ja vuositulot useissa miljardeissa. Maltan ritarit myöntävät omat passinsa, leimaavat postimerkkinsä ja rahansa sekä ylläpitävät täysimittaisia diplomaattisia suhteita seitsemäänkymmeneen maahan. Kirjoittaessamme ne neuvottelevat Maltan tasavallan kanssa saadakseen takaisin Fort St. Angelon. Linnoituksen haltuunotto antaisi ritarille puuttuvan elementin alueellisuudesta, mikä mahdollistaisi sen tunnustamisen suvereniteetiksi. Maltan ritarit voisivat jälleen muodostua suvereeniksi mikrostaatiksi, heti pitkän historian myötä laillistettuna. Juuri Fort St. Angelosta Maltan ritarit torjuivat turkkilaiset vuoden 1565 suuressa piirityksessä, ja he hallitsivat Maltan saarta pitkään sen jälkeen, kunnes Napoleoni karkasi heidät vuonna 1798. Jos Maltan ritarit palaisivat lähivuosina, mikään ei osoittaisi selvemmin, että moderni kansallisvaltiojärjestelmä – jonka Ranskan vallankumous julisti – oli vain väliintulo historiassa, jossa erilaiset suvereniteetit ovat voineet elää rinnakkain.

Toinen hyvin erilainen malli postmodernille suvereniteetille, joka perustuu assortatiiviseen parinmuodostukseen, on Iridium-satelliittipuhelinverkosto. Ensisilmäyksellä saattaisi vaikuttaa omituiselta pitää matkapuhelinpalvelua jonkinlaisena suvereniteettina, mutta Iridium on jo saanut kansainvälisten viranomaisten tunnustuksen virtuaalisena suvereniteettina. Iridium on globaali matkapuhelinpalvelu, jonka tilaajat voivat vastaanottaa puheluita yhdellä numerolla missä tahansa planeetalla – Featherstonista Uuden-Seelannin alueella aina Bolivian Chacon asti. Jotta puhelut voitaisiin ohjata tilaajille maailmanlaajuisesti, ottaen huomioon globaalit telekommunikaatioverkostot, kansainvälisten televiranomaisten täytyi sopia Iridiumin tunnustamisesta virtuaalisena maana, jolla on oma maatunnus: 8816. Loogisesti ajatellen on vain lyhyt askel virtuaalikunnasta, joka koostuu satelliittipuhelintilaajista, siirryä suvereniteettiin, kun entistä yhtenäisemmät virtuaaliyhteisöt muodostuvat World Wide Webissä ylittäen kansalliset rajat. Kaistanleveys eli viestintäkanavan kantokyky on kasvanut paljon nopeammaksi transistoreiden keksimisen jälkeen kuin laskentateho, ja jos tämä trendi kohti suurempaa kaistanleveyttä jatkuu – kuten uskomme sen olevan todennäköistä – on vain muutaman vuoden kuluttua vuosituhannen vaihteen jälkeen, kun kaistanleveys on riittävä, niin kutsuttu ”metaverse”, vaihtoehtoinen kyberavaruusmaailma, jonka tieteiskirjailija Neal Stephenson kuvaili, on teknisesti mahdollista. Stephensonin ”metaverse” on tiheä virtuaaliyhteisö omine laeillaan. Uskomme väistämättä, että kun kybertalous rikastuu, sen osallistujat pyrkivät saamaan vapautuksen kansallisvaltioiden vanhanaikaisista laeista. Uudet kyberyhteisöt ovat vähintään yhtä varakkaita ja kykenevämpiä edistämään etujaan kuin Jerusalem, Rhodian ja Maltan suvereenien sotilashyppereiden järjestö, ja todellakin niitä on helpompi saada vaikuttamaan laajalla viestinnän ja tietovallan keinoin. Tarkastelemme vielä muita malleja, joissa pienet ryhmät voivat tehokkaasti vuokrata heikkojen valtioiden suvereniteetin ja toimia omina taloudellisina turvapaikkoinaan noin samalla tavalla kuin nykyiset vapaakauppaportit ja -alueet.

Tietotekniikan myötä markkinoille tulee myös uusia, erilaissuvuisia valuuttamalleja, jotta yksilöllisen suvereniteetin aikaa voidaan hyödyntää.
Uusi moraalinen sanasto tulee olemaan tarpeen kuvaamaan suvereenien yksilöiden välisiä suhteita sekä sitä, mitä hallinnosta jää. Epäilemme, että näiden uusien suhteiden ehdot tarkentuessa ne loukkaavat monia ihmisiä, jotka kasvoivat 1900-luvun kansallisvaltioiden "kansalaisina". Kansojen loppu ja "yksilön denationalisaatio" kaventavat joitakin lämpimästi arvostettuja käsityksiä, kuten "tasapuolista suojaa lain edessä", jotka edellyttävät valtasuhteita, joiden uskalletaan pian katketa. Virtuaaliyhteisöjen kasvaessa yhtenäisemmiksi ne vaativat, että niiden jäseniä pidetään vastuullisina omien lakien mukaisesti eikä entisten kansallisvaltioiden lakien mukaan, joissa he sattuvat asumaan. Moninaiset lakijärjestelmät tulevat jälleen elämään saman maantieteellisen alueen puitteissa, kuten ne elivät antiikin ja keskiaikojen aikana.

Samoin kuin yritykset säilyttää haarniskassa taistelevien ritareiden valta epäonnistuivat ruutiaseiden edessä, modernit kansallismielisyyden ja kansalaisuuden käsitykset ovat tuomittuja lyhytpiimäisiksi mikroteknologian vaikutuksesta. Itse asiassa ne muuttuvat lopulta koomisesti, aivan kuten 1400-luvun feodaalin pyhät periaatteet joutuivat pilkan kohteeksi 1500-luvulla. 1900-luvun rakkaat kansalaiskäsitykset muuttuvat koomiksi anakronismeiksi uusille sukupolville vuoden 2000 jälkeisen transformaation jälkeen. 2000-luvun Don Quixote ei ole rytari, joka kamppailee feodaalin loistojen herättämiseksi, vaan byrokraatti ruskeassa puvussaan, veronkerääjä, joka kaipaa kansalaista tarkastamaan tilinsä.

## Reunalakien elvyttäminen

Harvoin ajattelemme hallituksia kilpailukykyisinä toimijoina, paitsi hyvin laajassa merkityksessä, minkä vuoksi nykyaikainen intuitio suvereniteetin laajuudesta ja mahdollisuuksista on surkastunut. Aikoinaan, kun vallankäytön yhtälö teki ryhmien vaikeammaksi saavuttaa vakaa pakottamisen monopolia, valta usein hajautui, lainkäyttöalueet lipuivat päällekkäin ja erilaiset toimijat harjoittivat yhtä tai useampaa suvereniteetin ominaisuutta. Ei harvoin nominallinen ylivaltiasukkaan omisti todellisuudessa vain vähäisen määrän valtaa alueella. Nykyään kansallisvaltioita heikommat hallitukset kohtaavat jatkuvaa kilpailua kyvyssään asettaa paikalliselle alueelle pakottamisen monopoli. Tämä kilpailu on synnyttänyt väkivallan kontrolloimiseen ja uskollisuuden houkuttelemiseen sopeutumismekanismeja, jotka tulevat pian näyttämään uudelleen erilaisilta.

Kun lordien ja kuninkaiden vaikutusvallat olivat heikkoja ja yhden tai useamman ryhmän vaatimukset lipuivat päällekkäin rajalla, oli usein niin, ettei kumpikaan osapuoli pystynyt ratkaisevasti dominoimaan toisiaan. Keskiajalla oli lukuisia rajaseutuja tai "reuna-alueita", joissa suvereniteetit sulautuivat yhteen. Nämä väkivaltaiset rajat säilyivät vuosikymmenien tai jopa vuosisatojen ajan Euroopan raja-alueilla. Esimerkiksi Irlannissa vallitsi kelttiläisen ja englantilaisen hallinnon välinen raja; Walesin ja Englannin, Skotlannin ja Englannin, Italian ja Ranskan, Ranskan ja Espanjan, Saksan ja Keski-Euroopan slaavilaisalueiden sekä Espanjan kristillisten ja Granadan islamilaisen kuningaskunnan välillä. Tällaiset reuna-alueet kehittivät omaleimaisia institutionaalisia ja oikeudellisia malleja, joita todennäköisesti näemme taas seuraavan vuosituhannen aikana. Kahden toimivan viranomaisen kilpailuaseman vuoksi reuna-alueiden asukkaat maksavat harvoin veroja. Lisäksi heillä oli yleensä mahdollisuus päättää, kenen lakeja he noudattaisivat – mahdollisuus, joka toteutettiin oikeudellisten käsitteiden, kuten "tunnustuksen" ja "takavarikon", kautta, vaikka nämä käsitteet ovat nyt lähes kadonneet. Odotamme näiden käsitteiden nousevan merkittäviksi osiksi tietoyhteiskuntien oikeutta.

Kun jokien ja kuninkaiden ulottuvuus oli heikko ja useiden ryhmien vaatimukset lipuivat päällekkäin rajalla, kävi usein niin, ettei kumpikaan voinut ratkaisevasti hallita toisiaan. Keskiajalla oli lukuisia rajaseutuja eli "reunoja", joissa suvereniteetit sulautuivat yhteen. Nämä väkivaltaiset rajat säilyivät vuosikymmenien tai jopa vuosisatojen ajan Euroopan raja-alueilla. Esimerkiksi Irlannissa vallitsi kelttiläisen ja englantilaisen vaikutusvallan raja; Walesin ja Englannin, Skotlannin ja Englannin, Italian ja Ranskan, Ranskan ja Espanjan, Saksan ja Keski-Euroopan slaavilaisalueiden sekä Espanjan kristillisten ja Granadan islamilaisen kuningaskunnan välillä. Tällaiset reuna-alueet kehittivät omaleimaisia institutionaalisia ja oikeudellisia muotoja, joita todennäköisesti näemme jälleen seuraavalla vuosituhannella. Kahden kilpailijan aseman vuoksi reuna-alueiden asukkailla oli harvoin verovelvollisuutta. Lisäksi heillä oli usein mahdollisuus päättää, kenen lakeja noudatetaan – mahdollisuus, joka toteutettiin muun muassa oikeudellisten käsitteiden "tunnustuksen" ja "takavarikon" avulla, käsitteiden, jotka ovat nykyään lähes kadonneet. Odotamme näiden käsitteiden nousevan tärkeiksi osiksi tietoyhteiskuntien oikeudellista kenttää.
Maan kansallisuuden ylittäminen

Ennen kansallisvaltioita oli vaikea tarkalleen määritellä maailmassa vallitsevien suvereniteettien lukumäärää, sillä ne limittyivät monimutkaisin tavoin ja eri organisaatiomuodot käyttivät valtaa. Näin tulee tapahtumaan uudelleen. Alueiden jakolinjat muuttuivat kansallisvaltiojärjestelmässä selvästi rajatuiksi ja pysyviksi rajoiksi, mutta informaatiokaudella ne hämärtyvät jälleen. Uudella vuosituhannella suvereniteetti hajoaa jälleen. Uusia toimijoita nousee esiin, jotka käyttävät osaa, mutta eivät kaikkia niitä ominaisuuksia, joita nykyään liitämme hallituksiin.

Jotkut näistä uusista toimijoista, kuten keskiaikaiset Tempelihyvikset ja muut uskonnolliset sotilasjärjestöt, saattavat hallita huomattavaa varallisuutta ja sotilaallista valtaa ilman, että niillä olisi kiinteää aluetta. Ne organisoituvat periaatteiden mukaan, joilla ei ole mitään tekemistä kansallisuuden kanssa. Keskiajalla Euroopan tietyillä alueilla suvereenia valtaa käyttävien uskonnollisten yhtiöiden jäsenet ja johtajat eivät missään tapauksessa saaneet auktoriteettiaan kansallisesta identiteetistä. He olivat eri etnisistä taustoista ja julistivat kuuluvansa Jumalaan, eivätkä he omistautuneet mihinkään kansallisiin siteisiin.

Kyberavaruuden kaupparespublikat

Näet myös jälleen nousun kauppiaita ja varakkaita henkilöitä yhdistävistä liitoista, joilla on puolisuvereenia valtaa, kuten keskiajalla Hanse (kauppakaarnejärjestö). Ranskan ja Flämmin messuilla toiminut Hanse laajeni katamaan kuusikymmentä kaupungin kauppiaita.[^10] Englanniksi sitä kutsutaan redundanssilla "Hanseatie League" (kirjaimellinen käännös on "Liittovalta Liitto"), ja se oli saksalaisten kauppiaskilttojen järjestö, joka tarjosi jäsenilleen suojaa ja neuvotteli kauppasopimuksia. Se käytti puolisuvereenia valtaa useissa Pohjois-Euroopan ja Itämeren alueen kaupungeissa. Tällaiset toimijat nousevat uudelleen kuolevana olevan kansallisvaltion sijaan uudella vuosituhannella, tarjoten suojaa ja auttaen sopimusten täytäntöönpanossa epävakaassa maailmassa.
Lyhyesti sanottuna tulevaisuus todennäköisesti hämmentää niitä, jotka ovat omaksuneet 1900-luvun teollisyhteiskunnan kansalaismyyttejä. Näihin kuuluu sosiaalidemokratian harhaluulot, jotka aikoinaan innostivat ja motivoivat lahjakkaimpia mieliä. Ne olettavat, että yhteiskunnat kehittyvät juuri siinä mielessä kuin hallitukset haluavat – mieluiten mielipidekyselyiden ja huolellisesti lasketun äänimäärän vaikutuksesta. Tämä ei koskaan ollut yhtä totta kuin se vaikutti viisikymmentä vuotta sitten. Nyt se on anakronismi, teollisuuden jäänne, aivan kuten ruostuva savupiippu. Kansalaismyytit eivät ainoastaan heijasta ajattelutapaa, jossa yhteiskunnan ongelmia nähdään insinööritieteellisesti ratkaistavina, vaan myös väärää luottamusta siihen, että sekä resurssit että yksilöt pysyisivät tulevaisuudessakin yhtä alttiina poliittiselle pakottamiselle kuin 1900-luvulla. Me epäilemme sitä. Markkinavoimat, eivät poliittiset enemmistöt, pakottavat yhteiskunnat uudelleen järjestäytymään tavoilla, joita yleinen mielipide ei ymmärrä eikä hyväksy. Kun näin tapahtuu, naiivi näkemys siitä, että historia on sitä, mitä ihmiset toivovat sen olevan, osoittautuu valtavasti harhaanjohtavaksi.

On siksi ratkaisevan tärkeää, että näet maailman uudelleen. Tämä tarkoittaa sitä, että tarkastelet asioita ulkopuolelta tulevana ja analysoit uudelleen monia seikkoja, joita olet todennäköisesti pitänyt itsestäänselvyyksinä. Näin voit saavuttaa uuden ymmärryksen. Jos et onnistu ylittämään tavanomaista ajattelua aikana, jolloin se menettää yhteytensä todellisuuteen, joudut todennäköisemmin kohtaamaan hämmentymisen epidemian, joka uhkaa. Hämmentyminen synnyttää virheitä, jotka voivat uhata liiketoimintaasi, sijoituksiasi ja elämäntapaasi.

> Universumi palkitsee meitä siitä, että ymmärrämme sen, ja rankaisee meitä siitä, ettemme ymmärrä sitä. Kun ymmärrämme universumin, suunnitelmamme toimivat ja tunnemme olomme hyväksi. Toisaalta, jos yritämme lentää hyppäämällä rotkon reunalta ja räpyttämällä käsiämme, universumi tappaa meidät.[^11]  
> – JACK COHEN JA IAN STEWART

### Näkeminen uusin silmin

Valmistautuaksesi tulevaan maailmaan sinun on ymmärrettävä, miksi se tulee olemaan erilainen kuin useimpien asiantuntijoiden väitetyn mukainen. Tämä vaatii piilevien muutoksen syiden tarkkaa tarkastelua. Olemme pyrkineet tähän epätavanomaisella analyysillä, jota kutsumme megapolitiikan tutkimukseksi. Kaksi aiempaa teostamme, Blood in the Streets ja *The Great Reckoning*, esittivät, että tärkeimmät muutoksen aiheuttajat eivät ole poliittisissa manifestissa tai kuolleiden taloustieteilijöiden lausunnoissa, vaan piilevissä tekijöissä, jotka muuttavat niitä rajoja, joilla valta kohdistuu. Usein hienovaraiset muutokset ilmastossa, topografiassa, mikrobeissa ja teknologiassa muuttavat väkivallan logiikkaa. Ne muokkaavat tapaa, jolla ihmiset järjestävät elinkeinonsa ja puolustavat itseään.
Huomaa, että tapa, jolla pyrimme ymmärtämään, miten maailma muuttuu, eroaa merkittävästi useimpien ennustajien näkemyksistä. Emme ole asiantuntijoita mistään – emmekä väitä tietävämme paljon enemmän tietyistä "aihealueista" kuin ne, jotka ovat viettäneet koko uransa erikoistuneen tiedon kartuttamisessa. Päinvastoin, tarkastelemme asioita ulkopuolelta sisäänpäin. Olemme perehtyneet niihin aiheisiin, joista teemme ennusteita. Eniten tässä on kyse siitä, miten havaitaan, minne välttämättömyyden rajat asetetaan. Kun nämä rajat muuttuvat, myös yhteiskunta välttämättä muuttuu, riippumatta siitä, mitä ihmiset toivovat.

Mielestämme avain ymmärtää, miten yhteiskunnat kehittyvät, on ymmärtää tekijöitä, jotka määrittävät väkivallan käytön kustannukset ja palkkiot. Jokainen ihmiskunta – metsästysryhmästä keisarikuntaan – on muovautunut megapoliittisten tekijöiden vuorovaikutuksen kautta, jotka asettavat vallitsevan version "luonnonlaeista". Elämä on aina ja kaikkialla monimutkaista. Karitsa ja leijona ylläpitävät herkkää tasapainoa, vaikuttaen reuna-alueilla. Jos leijonat yhtäkkiä olisivat nopeampia, ne saavuttaisivat saaliin, joka nyt pääsee pakoon. Jos karitsat yhtäkkiä saisivat siivet, leijonat nälkäisivät. Kyky hyödyntää ja puolustautua väkivaltaa vastaan on ratkaiseva muuttuja, joka muuttaa elämää reuna-alueilla.

Asetamme väkivallan keskiöön megapoliittisessa teoriassamme hyvästä syystä. Väkivallan hallinta on kaikkien yhteiskuntien tärkein ongelma. Kuten kirjoitimme teoksessamme *The Great Reckoning*:

> Ihmiset turvautuvat väkivaltaan, koska se usein maksaa itsensä. Joissakin tapauksissa yksinkertaisin keino hankkia rahaa on yksinkertaisesti ottaa se. Tämä pätee yhtä hyvin armeijan, joka vallaa öljykentän, kuin yksittäisen rosvojen, joka nappaa lompakon. Kuten William Playfair kirjoitti, "valta on aina etsinyt helpointa tietä vaurauteen, hyökkäämällä niiden kimppuun, jotka ovat sen hallussa."

> Haaste vauraudelle on juuri se, että petollinen väkivalta maksaa hyvin tietyissä olosuhteissa. Sota muuttaa asioita. Se muuttaa säännöt. Se muuttaa varojen ja tulojen jakautumista. Se jopa määrää, kuka elää ja kuka kuolee. Juuri se, että väkivallan käyttö maksaa, tekee siitä vaikeasti hallittavaa.[^12]

Näitä ajatuksia hyödyntäen olemme kyenneet ennakoimaan useita kehityssuuntia, joiden toteutumista paremmin perillä olevat asiantuntijat vaativat, että ei koskaan tapahtuisi. Esimerkiksi varhain vuonna 1987 julkaistu teos Blood in the Streets oli yrityksemme kartoittaa sen suuren megapoliittisen vallankumouksen ensimmäisiä vaiheita, joka nyt on käynnissä. Siinä väitimme, että teknologinen muutos epävakauttaa maailmassa vallitsevaa valtasuhdetta. Yksi pääkriteereistämme oli seuraava.
- Me kerroimme, että amerikkalaisen ylivaltaisuuden taantuminen johtaisi taloudellisiin epätasapainoihin ja ahdinkoon, mukaan lukien toinen vuoden 1929 kaltaisen pörssiromahduksen kaltainen tilanne. Asiantuntijat olivat lähes yksimielisiä kiistämään, että tällaista voisi tapahtua. Silti kuuden kuukauden kuluessa, lokakuussa 1987, maailmanmarkkinat koettuivat vuosisadan väkivaltaisimman myyntihypyn seurauksena.

- Me kerroimme lukijoille, että kommunismin romahtaminen on odotettavissa. Taas asiantuntijat nauroivat. Silti vuosi 1989 toi mukanaan tapahtumat, joita "kukaan ei olisi voinut ennustaa." Berliinin muuri kaatui, kun vallankumoukset pyyhkäisivät kommunistiset hallinnot Itämereltä Bukarestiin.

- Selitimme, miksi monietninen imperiumi, jonka bolshevikkien nimeklaatura periytyi tsaareilta, "loukkuisi väistämättä auki." Joulukuun 1991 lopulla vasara- ja sirppilippu laskettiin viimeisen kerran Kremlinin ylle, kun Neuvostoliitto lakosi olemasta.

- Reaganin asevarustelun huippukohdassa väitimme, että maailma oli kynnyksellä merkittävienaseiden vähentämiselle. Myös tätä pidettiin epätodennäköisenä, ellei jopa naurettavana. Kuitenkin seuraavat seitsemän vuotta toi mukanaan sen ajanjakson, jolloin aseistuksen purkaminen oli ollut kattavinta ensimmäisen maailmansodan päättymisen jälkeen.

- Sinä aikana, kun Pohjois-Amerikan ja Euroopan asiantuntijat osoittivat Japanaa tukemaan sitä näkemystä, että hallitukset pystyvät onnistuneesti manipuloimaan markkinoita, me sanoimme toisin. Ennustimme, että japanilaisten rahoitusvarojen boomi päättäisi romahdukseen. Pian Berliinin muurin kaatumisen jälkeen japanilainen pörssiromahdus tuli, ja sen arvo laski melkein puoleen. Uskomme yhä, että sen lopullinen pohja voi vastata tai jopa ylittää sen 89 prosentin arvonmenetyksen, jonka Wall Street koki vuoden 1929 jälkeen.
Siinä vaiheessa, kun melkein kaikki – keskiluokkaisista perheistä maailman suurimpiin kiinteistösijoittajiin – näyttivät uskovan, että kiinteistömarkkinat voivat vain nousta eikä laskea, varoitimme, että kiinteistökuplan puhkeaminen on väistämätöntä. Neljän vuoden kuluessa kiinteistösijoittajat ympäri maailmaa menettivät yli biljoona dollaria, kun kiinteistöjen arvot laskivat.

Jo kauan ennen asiantuntijoiden selväksi havaitsemista selitimme teoksessamme *Blood in the Streets*, että siniviheriöiden tulot olivat laskeneet ja olivat määräytymässä laskeviksi pitkällä aikavälillä. Kuten kirjoitamme tänään, lähes vuosikymmenen myöhemmin, uneliaalle maailmalle on vihdoin alkanut kummahtaa, että näin on. Yhdysvalloissa keskimääräiset tuntipalkat ovat laskeneet alle toisen Eisenhowerin hallituksen saavuttamien tasojen. Vuonna 1993 keskimääräiset vuosittaiset tuntipalkat vakioiduissa dollareissa olivat 18 808 dollaria, kun taas vuonna 1957, kun Eisenhower vannoi toiselle kaudelleen, ne olivat 18 903 dollaria.

Vaikka *Blood in the Streets* -teoksen pääteemat ovatkin osoittautuneet jälkiviisauden valossa äärimmäisen tarkkoina, vain muutama vuosi sitten niitä pidettiin perin pahana hölynpölynä tavanomaisen ajattelun vartijoiden toimesta. Eräs *Newsweek*-lehden arvostelija vuonna 1987 heitti analyysimme "ajatuksettomana hyökkäyksenä järkeä vastaan", mikä kuvasti myöhäisen teollisuusyhteiskunnan suljettua ajatteluilmapiiriä.

Voisit kuvitella, että *Newsweek* ja vastaavat julkaisut olisivat ajan kuluessa tulleet ymmärtämään, että analyysimme linjaus oli paljastanut jotain hyödyllistä siitä, miten maailma oli muuttumassa. Ei lainkaan – *The Great Reckoning* -teoksen ensimmäistä painosta tervehti sama nauraen huvittava vastenmielisyys kuin *Blood in the Streets* -teos. Ei vähempää auktoriteettia kuin *Wall Street Journal* hylännyt kategorisesti analyysimme "sinun typerän tädillesi kuuluvana höpinänä."

Tämän hymyilyn ohi, *The Great Reckoning* -teoksen teemat osoittautuivat vähemmän naurettavina kuin ortodoksian vartijat olivat väittäneet.
Laajensimme ennustustamme Neuvostoliiton romahtamisesta tutkimalla, miksi Venäjä ja muut entiset Neuvostoliiton tasavallat kohtasivat tulevaisuudessa kasvavaa sisäistä kaaosta, hyperinflaatiota ja elintason laskua.

- Selitimme, miksi 1990-luku olisi supistamisen vuosikymmen, jolloin ensimmäistä kertaa nähtiin maailmanlaajuinen hallitusten ja liiketoimintayksiköiden vähentäminen.

- Ennustimme myös, että tulisi tapahtumaan merkittävä tulonjaon uudelleenmäärittely, jyrkkiä leikkauksia etuustasoissa. Viitteitä julkisesta kriisistä ilmestyi Kanadasta Ruotsiin, ja amerikkalaiset poliitikot alkoivat puhua "hyvinvointivaltion loppumisesta sellaisena kuin me sitä tunnemme."

- Ennakoimme ja selitimme, miksi "uusi maailmanjärjestys" osoittautuisi "uudeksi maailman kaaokseksi." Jo ennen Bosnian julmuuksien valtaamista otsikoihin varoitimme, että Jugoslavia romahtaisi sisällissotaan.

- Ennen kuin Somalia liukui anarkiaan, selitimme, miksi Afrikan hallitusten uhkaava romahtaminen johtaisi siihen, että jotkut maat asetettaisiin käytännössä ulkopuolisen hallinnon suojeluun.
- Ennustimme ja selitimme, miksi militantti islamismi syrjäyttäisi marxismin pääideologiana, kun lännen kanssa käydään vastakkainasettelua. Vuosia ennen Oklahoma-pommi-iskua ja World Trade Centerin räjäyttämisyritystä selitimme, miksi Yhdysvallat kohtasi terrorismin nousua.

- Ennen kuin uutisotsikoissa kerrottiin Los Angelesin, Toronton ja muiden kaupunkien laajoista mellakoista, selitimme, miksi urbaanien vähemmistöjen keskuudessa syntyivät rikolliset alakulttuurit loivat edellytykset laajalle rikolliselle väkivallalle.

- Ennakoimme myös „kahdenkymmenennen vuosisadan viimeistä lamaa”, joka alkoi Aasiassa vuonna 1989 ja on levinnyt reunalta kohti globaalin järjestelmän keskustaa. Sanottiin, että japanin osakemarkkinat seuraisivat Wall Streetin polkua vuoden 1929 jälkeen, mikä johtaisi luottokriisiin ja lamaan. Vaikka massiivinen hallituksen puuttuminen Japanissa ja muualla esti tilapäisesti markkinoita heijastamasta täysin luotto-olosuhteiden heikkenemistä, tämä siirsi ja pahensi taloudellista ahdinkoa, lisäten painetta kilpailullisiin devalvoihin ja järjestelmälliseen luottokriisiin, kaltaiseen, joka romahti maailmanlaajuisesti 1930-luvulla.

*The Great Reckoning* esitti myös useita kiistanalaisia teesejä, joita ei ole vielä vahvistettu tai jotka eivät ole kehittyneet ennustamallamme tasolla:

- Sanottiin, että japanin osakemarkkinat seuraisivat Wall Streetin polkua vuoden 1929 jälkeen, mikä johtaisi luottokriisiin ja lamaan. Vaikka Espanjan, Suomen ja muutaman muun maan työttömyysasteet ylittivät 1930-luvun tasot ja useat maat, mukaan lukien Japani, kokivat paikallisia lamoja, järjestelmällistä luottokriisiä, joka romahtaisi maailman taloudet kuten 1930-luvulla, ei ole vielä tapahtunut.
- Todimme, että entisen Neuvostoliiton komentaja-valvontajärjestelmän romahtaminen johtaisi ydinaseiden leviämiseen pienvaltioiden, terroristien ja rikollisjengien käsiin. Maailman onneksi näin ei ole käynyt – ainakaan ei siinä määrin kuin pelkäsimme. Lehdistötiedotteiden mukaan Iran osti useita taktisia ydinaseita mustilta markkinoilta, ja saksalaiset viranomaiset torjuivat useita yrityksiä myydä ydinmateriaaleja. Entisen Neuvostoliiton asekokoelmista ei kuitenkaan ole ilmoitettu ydinaseiden sijoittamisesta tai käytöstä.

- Selitimme, miksi "huumeiden vastainen sota" oli resepti, joka kumosi niiden maiden poliisi- ja oikeusjärjestelmiä, joissa huumeiden käyttö on laajalle levinnyttä, erityisesti Yhdysvalloissa. Joka vuosi kymmenien miljardien dollarien piilotettujen monopolivoittojen kasvaessa, huumekauppiailla on sekä keinoja että kannustimia lahota jopa näennäisesti vakaat maat. Vaikka maailman media on toisinaan tuonut esiin tarinoita, jotka vihjaavat huumerahan korkeatasoista tunkeutumista Yhdysvaltain poliittiseen järjestelmään, koko totuus ei ole vielä tullut julkisuuteen.

### Katsoa siellä, missä toiset eivät katso

Huolimatta niistä kohdista, joissa ennusteemme olivat virheellisiä tai vaikuttavat virheellisiltä nykyisen tiedon valossa, aineisto kestää tarkastelun. Paljon siitä, mitä todennäköisesti käsitellään tulevissa 1990-luvun taloushistoriankirjoissa, ennustettiin, odotettiin ja selitettiin teoksessa *The Great Reckoning*. Monet ennusteistamme eivät olleet yksinkertaisia trendien jatkumoja, vaan ennusteita merkittävistä poikkeamista siitä, mitä on pidetty normaalina toisen maailmansodan jälkeen. Varoimme, että 1990-luku olisi dramaattisesti erilainen kuin edelliset viisi vuosikymmentä. Lukien vuoden 1991–1995 uutisia, näemme, että *The Great Reckoning* -teoksen teemat toteutuivat melkein päivittäin.

Näemme nämä kehityssuunnat eivät erillisinä yksittäisinä ongelmina, vaan sokkeina ja tärinöinä, jotka kulkevat saman murtumalinjan mukaisesti. Vanha järjestys kaatuu meemittaisen poliittisen maanjäristyksen seurauksena, joka mullistaa instituutiot ja muuttaa tapaamme, joilla ajattelevat ihmiset näkevät maailman.
Huolimatta väkivallan keskeisestä roolista maailman toiminnan määrittäjänä, se herättää yllättävän vähän vakavaa huomiota. Suurin osa poliittisista analyytikoista ja taloustieteilijöistä kirjoittaa ikään kuin väkivalta olisi vain pieni harmittaja, samanlainen kuin kakkupalan ympärillä suriseva kärpänen, eikä kokki, joka sen on valmistanut.

### Toinen megapoliittinen uranuurtaja

Itse asiassa väkivallan roolista historiassa on ajateltu näin vähän selkeästi, että megapoliittisen analyysin lähdeluettelon voisi kirjoittaa yhdelle paperilevylle. Teoksessamme *The Great Reckoning* hyödynsimme ja syvensimme lähes kokonaan unohdetun megapoliittisen analyysin klassikon, William Playfairin teoksen *An Enquiry into the Permanent Causes of the Decline and Fall of Powerful and Wealthy Nations* (1805), väitteitä. Yksi lähtökohdistamme on Frederic C. Lanen työ. Lane oli keskiaikainen historioitsija, joka 1940– ja 1950-luvuilla kirjoitti useita läpikotaisin meneviä esseitä väkivallan roolista historiassa. Ehkä kattavin näistä oli artikkeli *Economic Consequences of Organized Violence*, joka julkaistiin Journal of Economic History -lehdessä vuonna 1958. Vain harvat, ammattimaiset taloustieteilijät ja historioitsijat ovat sitä lukeneet, eivätkä useimmat tunnistaneet sen merkitystä. Kuten Playfairkin, Lane kirjoitti yleisölle, jota silloin ei vielä ollut.

### Näkemyksiä informaatiokaudelle

Lane julkaisi työnsä väkivallasta ja sodan taloudellisesta merkityksestä hyvissä ajoin ennen informaatiokauden aikaa. Hän ei todellakaan kirjoittanut ennakoiden mikroprosessointia tai muita nyt kehittyviä teknologisia vallankumouksia. Silti hänen näkemyksensä väkivallasta loivat viitekehyksen ymmärtää, miten yhteiskunta uudelleen konfiguroidaan informaatiovaelluksen aikana.
Se ikkuna, jonka Lane avasi tulevaisuuteen, oli sellainen, jonka kautta hän vilkaisi menneisyyteen. Hän oli keskiajan historioitsija, erityisesti kauppakaupungin, Venetsian historioitsija, jonka kohtalo nousi ja laski väkivaltaisen maailman keskellä. Pohdiskellessaan, miten Venetsia nousi ja kaatui, hänen huomionsa kiinnittyi kysymyksiin, jotka voivat auttaa ymmärtämään tulevaisuutta. Hän havaitsi, että väkivallan organisoimisella ja kontrolloinnilla on merkittävä rooli määritettäessä, "mihin niukkoja resursseja käytetään." [^13]

Uskomme, että Lanen analyysit väkivallan kilpailevista käyttötavoista kertovat paljon siitä, miten elämänlaatu tulee muuttumaan tietoyhteiskunnassa. Älkää kuitenkaan odottako, että suurin osa ihmisistä huomaisi tai seuraisi näin epämuodollisesti abstraktia argumenttia. Sillä kun maailman huomio on tarkalleen kohdistettu epärehellisiin kiistoihin ja omalaatuisiin persoonallisuuksiin, megapolitiikan mutkaukset jatkuvat lähes huomaamatta. Keskimääräinen pohjoisamerikkalainen on todennäköisesti kiinnittänyt sata kertaa enemmän huomiota O. J. Simpsoniin kuin uusiin mikroteknologioihin, jotka ovat valmiita vanhentamaan hänen työpaikkansa ja syrjäyttämään sen poliittisen järjestelmän, johon hän tukeutuu työttömyyskorvauksen saamiseksi.

TOIVEIDEN TURHUUS

Se, että perimmäisen tärkeää sivuutetaan, ei rajoitu pelkästään sohvaa vasten televisiota katsoviin. Kaikki perinteiset ajattelijat eri muodoissaan tunnistavat kansallisvaltion esittämisen oletuksen – sen, että ihmisten mielipiteet määräävät, miten maailma muuttuu. Näennäisesti sofistikoituneet analyytikot lankeavat selityksiin ja ennusteisiin, joissa merkittävät historialliset kehityskulut tulkitaan ikään kuin ne määräytyisivät toivomuksellisesti. Huomiota herättävä esimerkki tällaista ajattelua osoittavasta logiikasta ilmestyi New York Timesin toimittajien lehtiolla juuri silloin, kun kirjoitimme "Goodbye, NationState, Hello...What?," Nicholas Colchesterilta [^14]. Aiheena oli kansallisvaltion kuolema – aivan se aihe, jota käsittelemme – ja kirjoittaja esittää itsensä erinomaisena mittapuuna havainnollistamaan, kuinka poikkeaiseksi ajattelutapamme ovat muodostuneet normista. Colchester ei ole typerys; hän toimi Economist Intelligence Unitin toimittajapäällikkönä, ja jos kenenkään tulisi muodostaa realistinen kuva maailmasta, sen tulisi olla hän. Kuitenkin hänen artikkelinsa osoittaa useissa kohdissa selvästi, että "kansainvälisen hallituksen" tuleminen on nyt loogisesti pysäyttämätöntä.

Miksi? Koska kansallisvaltio horjuu eikä enää kykene hallitsemaan taloudellisia voimia.
Meidän näkemyksemme mukaan tämä oletus on lähes absurdia. Olettaa, että jokin tietty uusi hallintomalli syntyisi pelkästään siksi, että toinen on epäonnistunut, on virheellinen päättely. Tällaisella ajattelulla Haitilla ja Zairella olisi jo kauan sitten ollut parempi hallinto, pelkästään siksi, että heidän nykyinen hallintonsa on räikeän riittämätön.

Colchesterin näkökulmaa – jota jakaa laajalti harvat, jotka pohtivat tällaisia asioita Pohjois-Amerikassa ja Euroopassa – ei oteta lainkaan huomioon niitä laajempia megapoliittisia voimia, jotka määrittävät, millaiset poliittiset järjestelmät ovat todellisuudessa kestäviä. Tämä onkin tämän kirjan keskiössä. Kun tarkastelemme niitä teknologioita, jotka muovaavat uutta vuosituhatta, on paljon todennäköisempää, että emme näe yhtä maailmanhallintoa, vaan pikemminkin mikrohallintoja tai jopa olosuhteita, jotka lähestyvät anarkiaa.

Jokaista vakavaa analyysiä väkivallan roolista siinä, miten kaikki toimivat määritellyin säännöin, vastaan on kirjoitettu kymmeniä kirjoja vehnätukien monimutkaisuudesta ja satoja lisää salamyhkäisistä rahapolitiikan yksityiskohdista. Paljon tätä kriittisten kysymysten pohdinnan puutetta heijastaa viimeisten useiden vuosisatojen verrattain vakaata valtarakennetta. Lintu, joka nukahtaa virtahevon selässä, ei ajattele menettävänsä pesäpaikkaansa ennen kuin virtahepo lähtee liikkeelle. Unet, myytit ja fantasiat näyttelevät huomattavasti suurempaa roolia oletettujen yhteiskuntatieteiden muodostamisessa kuin yleisesti ajattelemme.

Tämä on erityisen ilmeistä runsaassa taloudellisen oikeudenmukaisuuden kirjallisuudessa. Jokaista sivua, joka on omistettu huolelliselle analyysille siitä, kuinka väkivalta muokkaa yhteiskuntaa ja määrittää talouksien toimintarajat, vastaan on lausuttu ja kirjoitettu miljoonia sanoja taloudellisesta oikeudenmukaisuudesta ja epäoikeudenmukaisuudesta. Siitä huolimatta modernin taloudellisen oikeudenmukaisuuden muotoilut edellyttävät, että yhteiskuntaa hallitsee niin voimakas pakkokeino, joka pystyy riistämään ja jakamaan uudelleen elämän hyviä asioita. Tälläista valtaa on ollut olemassa vain muutama sukupolvi modernilla ajalla. Nyt se hiipuu pois.

### Isoveli sosiaaliturvassa
Teollisuusteknologia antoi hallituksille 1900-luvulla enemmän kontrollivälineitä kuin koskaan aiemmin. Hetken aikaa näytti väistämättömältä, että hallitukset tehostaisivat väkivallan monopolisoimista niin, ettei yksilön autonomialle jäisi mitään tilaa. Kukaan 1900-luvun puolivälissä ei odottanut Itsenäisen yksilön voittoa.

Jotkut 1900-luvun puolivälin oivaltavimmista tarkkailijoista tulivat päivän todisteiden perusteella vakuuttuneiksi siitä, että valtakunnan valtion taipumus keskittää valtaa johtaisi totalitaariseen dominointiin kaikkialla elämässä. George Orwellin teoksessa *1984* (1949) Isoveli seurasi yksilöä turhaan, kun tämä kamppaili säilyttääkseen jonkinlaisen autonomian ja itsekunnioituksen rajan. Tilanne vaikutti siltä, ettei taistelu olisi voitettavissa. Friedrich von Hayekin *The Road to Serfdom* (1944) esitti tieteellisemmän näkemyksen, jonka mukaan vapaus menetettiin uudenlaisen taloudellisen kontrollin vuoksi, jättäen valtion kaikenvallaksi. Nämä teokset on kirjoitettu ennen mikroprosessoinnin aikakautta, joka on synnyttänyt joukon teknologioita parantaen pienten ryhmien ja jopa yksilöiden kykyä toimia itsenäisesti keskusvallasta.

Vaikka tarkkailijat kuten Hayek ja Orwell olivat oivaltavia, he olivat liiankin pessimistisiä. Historia on tuonut mukanaan yllätyksiä. Totalitaarinen kommunismi kesti tuskin vuoteen 1984 asti. Uusi servitution muoto saattaa syntyä seuraavan vuosituhannen aikana, jos hallitukset onnistuvat tukahduttamaan mikroteknologian vapauttavat puolet. Todennäköisempää on kuitenkin, että näemme ennennäkemättömiä mahdollisuuksia ja yksilön autonomian laajenemista. Se, mistä vanhempamme huolestuivat, saattaa osoittautua täysin ongelmattomaksi. Ne piirteet, joita pidimme pysyvinä osina sosiaalista elämää, näyttävät nyt olevan kohtaloon häviämässä. Missä tahansa tarve asettaa rajat ihmisen valinnoille, me sopeudumme ja järjestämme elämämme uudelleen sen mukaisesti.

### Ennustamisen vaarat

Eikää epäröikö, sillä panemme pienen arvonmittamme vaaraan yrittäessämme ennustaa ja selittää syvällisiä muutoksia elämän järjestyksessä ja sen sitovassa kulttuurissa. Suurin osa ennusteista muuttuu ajan myötä hupsuiksi luettaviksi, ja mitä dramaattisemmaksi muutokset kuvittelevat, sitä noloimmiksi ne usein näyttävät. Maailma ei lopu. Otsonikerrosta ei katoa. Tuleva jääkausi liukenee globaaliin lämpenemiseen. Kaikista vastakkaisia varoituksia vastaan tankissa on yhä öljyä. Herra Antrobus, *The Skin of Our Teeth* -teoksen jokamies, välttää jäätymisen, selviytyy sodista ja uhkaavista taloudellisista katastrofeista ja vanhenee huolettomasti asiantuntijoiden tutkituista varoituksista välittämättä.
Useimmat yritykset "paljastaa" tulevaisuuden osoittautuvat pian koomikkalaisiksi. Jopa silloin, kun oma etu tarjoaa vahvan kannustimen selkeään ajatteluun, tulevaisuuden näkemys on usein lyhykököistä. Vuonna 1903 Mercedes-yhtiö totesi, että "maailmanlaajuisesti ei koskaan olisi yhtä paljon kuin 1 miljoona autoa. Syynä oli se, että oli epätodennäköistä, että 1 miljoonaa käsityöläistä ympäri maailmaa voitaisiin kouluttaa kuskeiksi."[^15]

Tästä huolimatta meidän pitäisi olla vaittuneita. Mutta emme ole. Emme pelkää seistä jonossa saadaksemme ansaitun osan pilkanherkkyydestä. Jos teemme vakavia virheitä, tulevat sukupolvet saattavat nauraa yhtä sydämellisesti kuin haluavat, olettaen että kukaan muistaa, mitä sanoimme. Ajatuksen uskaltaminen tarkoittaa riskin ottamista siitä, että olemme väärässä. Emme ole niin jäykkiä ja hyödyttömiä, että pelkäisimme erehtyä. Päinvastoin, mieluummin esittäisimme ajatuksia, jotka saattaisivat osoittautua hyödyllisiksi sinulle, kuin tukahduttaisimme ne pelosta, että ne jälkikäteen näyttäisivät liioitelluilta tai noloilta.

Kuten Arthur C. Clarke terävästi totesi, kaksi ylivoimaista syytä siihen, miksi yritykset ennakoida tulevaisuutta yleensä epäonnistuvat, ovat "rohkeuden puute ja mielikuvituksen puute."[^16] Näistä hän kirjoitti: "Rohkeuden puute vaikuttaa olevan yleisempää; se ilmenee silloin, kun edes kaikkien merkityksellisten faktojen valossa yrittäjäinen profeetta ei pysty näkemään, että ne johtavat väistämättömään johtopäätökseen. Jotkut näistä epäonnistumisista ovat niin naurettavia, että ne lähes vaikuttavat uskomattomilta."[^17]

Missä tietovallankumouksen tutkimuksemme jää vajaaksi – kuten se väistämättä tulee olemaan – syy on lähinnä mielikuvituksen puutteessa kuin rohkeuden puutteessa. Tulevaisuuden ennustaminen on aina ollut rohkea hanke, joka herättää oikein perusteltua epäilevyyttä. Ehkä aika näyttää, että johtopäätöksemme ovat täysin virheellisiä. Toisin kuin Nostradamus, emme teeskele olevamme profeettisia persoonia. Emme ennusta tulevaisuutta sekoittamalla taikasauvaa vesikulhossa tai laatimalla horoskooppeja. Emme myöskään kirjoita salaperäisiä runoja. Tarkoituksemme on tarjota sinulle asiallinen, etäinen analyysi asioista, jotka saattavat osoittautua sinulle erittäin merkityksellisiksi.

Koemme velvollisuudeksemme esittää näkemyksemme, vaikka ne saattavat vaikuttaa harhaoppisilta, juuri siksi, että niitä muuten ei ehkä kuulla. Myöhäisen teollistuneen yhteiskunnan suljetussa henkisessä ilmapiirissä ajatukset eivät liiku yhtä vapaasti kuin niiden kuuluisi kulkea vakiintuneiden tiedotusvälineiden kautta.
Tämä kirja on kirjoitettu rakentavassa hengessä. Se on kolmas teos, jonka olemme yhdessä kirjoittaneet analysoiden eri vaiheita suuren nykyisessä muutoksessa. Aivan kuten teokset Blood in the Streets ja *The Great Reckoning*, tämäkin on ajatteluharjoitus. Se tutkii teollisyhteiskunnan kuolemaa ja sen uudelleenjärjestäytymistä uusina muotoina. Odotamme näkevämme hämmästyttäviä paradokseja tulevina vuosina. Toisaalta tulet todistamaan uudenlaisen vapauden toteutumista, kun nousee Suvereeni Yksilö. Voit odottaa näkeväsi lähes täydellisen tuottavuuden vapautumisen. Samalla odotamme modernin kansallisvaltion kuolemaa. Monien länsimaisten tasa-arvon perustusolettamusten, joita 1900-luvulla pidettiin itsestäänselvyyksinä, on määrä kuolla sen mukana. Uskomme, että nykyisen edustuksellisen demokratian nykyinen muoto häipyy ja sen tilalle astuu kybermarkkinapaikan uudenvalintaisen demokratian aika.

Olemme varmoja, että argumenttimme ovat helposti seurattavissa, vaikka ne kuljettavatkin sinut alueille, jotka ovat älyllisesti vastaavia maaseudun syrjäalueiden ja huonojen naapurustojen kanssa. Jos merkityksemme ei ole täysin ymmärrettävä tietyissä kohdissa, se ei johdu siitä, että yrittäisimme olla nokkelia tai käyttäisimme perinteistä moniselitteisyyttä, jolla teeskentelemme ennustavamme tulevaisuutta kätkettyjen lausuntojen avulla. Emme ole moniselitteisiä. Jos argumenttimme ovat epäselviä, se johtuu siitä, että emme ole onnistuneet kirjoittamaan tavalla, joka tekisi vakuuttavista ideoistamme helposti saavutettavia. Toisin kuin monet ennustajat, haluamme sinun ymmärtävän ja jopa kopioivan ajattelutapaamme. Se perustuu ei psyykkisiin unelmiin eikä planeettojen liikkeisiin, vaan vanhanaikaiseen, rumaan logiikkaan. Melko loogisista syistä uskomme, että mikroprosessointi väistämättä alistaa ja tuhoaa kansallisvaltion, luoden samalla prosessissa uusia sosiaalisen järjestäytymisen muotoja. On sekä tarpeellista että mahdollista, että pystyt ennakoimaan ainakin joitakin uuden elämäntavan yksityiskohtia, jotka saattavat olla täällä nopeammin kuin uskallat ajatella.

### Ironioita ennustetusta tulevaisuudesta

Vuosisatojen ajan tämän vuosituhannen loppua on pidetty historian merkittävänä hetkenä. Yli 850 vuotta sitten Pyhä Malachy määräsi viimeisen tuomion päivämääräksi vuosi 2000. Amerikkalainen psyykkinen Edgar Cayce totesi vuonna 1934, että maa kääntyy akselinsa ympäri vuonna 2000, mikä aiheuttaisi Kalifornian jakautumisen kahteen osaan sekä tulvien New Yorkin kaupungissa ja Japanissa. Japanilainen rakettitiedemies Hideo Itokawa ilmoitti vuonna 1980, että planeettojen asettuminen "Suureen ristiin" 18. elokuuta 1999 aiheuttaisi laajamittaista ympäristötuhoa, jättäen ihmiskunnan maan päältä.

Tällaiset maailmanlopun näkymät tarjoavat mehukkaan maalin pilkalle. Loppujen lopuksi vuosi 2000, vaikkakin vaikuttava pyöristysluku, on vain mielivaltainen artefakti länsimaisen kristillisen kalenterin mukaisesti. Muut kalenterit ja ajastuksen järjestelmät laskevat vuosisatoja ja vuosituhansia eri lähtöpisteistä. Esimerkiksi islamilaisen kalenterin mukaan jKr. 2000 on vuosi 1378 – tavallinen kuin vuosi voi olla. Kiinalaisen kalenterin mukaan, joka toistuu joka kuusikymmentä vuotta, jKr. 2000 on vain yksi lohikäärmeen vuosi. Se on osa jatkuvaa sykliä, joka ulottuu vuosituhansia menneisyyteen. Kuitenkin vuoden 2000 merkitys ei perustu pelkästään teologiseen sijoitukseen, vaan myös 1900-luvun puolivälin tietotekniikan rajoitteisiin. Kutsuttu Y2K- tai vuosi 2000 -tietokoneongelma, potentiaalisesti tuhoisa looginen virhe miljardissa tietokonerivissä, saattaa tuoda lähes maailmanlopun olosuhteita sulkemalla teollisyhteiskunnan tärkeät osat milleniumin keskiyössä. Monet tietokoneet ja mikroprosessorit käyttävät ohjelmistoja, jotka on säilytetty ja kierrätetty tietokoneiden alkuajoilta, jolloin muistitilan hinta, noin 600 000 dollaria per megatavu, oli arvokkaampaa kuin kulta. Säästääkseen arvokasta tilaa varhaiset ohjelmoijat seurasivat päivämääriä vain kahdella vuoden viimeisellä numerolla – käytäntö, joka siirtyi useimpiin pääjärjestelmien ohjelmistoihin ja levisi laajasti myös henkilökohtaisten tietokoneiden ja upotettujen mikroprosessoreiden käyttöön, joita käytetään lähes kaikkeen hallintaan, niin VCR:istä auton sytytysjärjestelmiin, turvajärjestelmiin, puhelimiin, puhelinverkkojen kytkentäjärjestelmiin, tehdas- ja voimalaitosprosesseihin, öljynjalostamoihin, kemianteollisuuteen, putkistoihin ja paljon muuhun. Näin lyhennettyinä kahden numeron kentiksi vuosi 1999 olisi "99". Ongelma on, mitä tapahtuu, kun vuosi 2000 tulee "00":na. Monet tietokoneet tulkitsevat tämän vuoden 1900:na, mikä saattaa tehdä mahdottomaksi monien korjaamattomien tietokoneiden ja muiden digitaalisten laitteiden tunnistamisen päivämääräkentissä.


Tulosena syntyy valtava tietojen korruptiosta johtuva ongelma, joka tahattomasti havainnollistaa uutta potentiaalia informaatiovaikuttamiseen. Informaatiokaudella potentiaaliset vastustajat pystyvät aiheuttamaan kaaosta räjäyttämällä "logiikkapommeja", jotka sabotoivat olennaisten järjestelmien toimintoja vioittamalla niiden toimintaa tukevia tietoja. Esimerkiksi sotaharjoituksena sinun ei tarvitsisi kaataa lentokonetta, jos voisit vioittaa sen turvallisen toiminnan kannalta keskeiset tiedot. Tietojen korruptio voi tehdä lähes yhtä paljon kuin fyysiset aseet modernin yhteiskunnan toimintojen sabotoimiseksi. On itsestään selvää, että tällä on potentiaalisesti laaja-alaiset seuraukset.

Esimerkiksi Lontoon *Mail* -lehti raportoi 14. joulukuuta 1997, että lentoyhtiöt ympäri maailmaa suunnittelivat perumassa satoja lentoja 1. tammikuuta 2000, peläten, että lennonvalvontajärjestelmät pettäisivät. Mahdollisia ongelmia aiheuttavat paitsi lennonvalvontajärjestelmät, myös lentokoneisiin sisäänrakennetut päivämääräherkät toiminnot. Boeingin mukaan monien lentokoneiden on saatava Y2K-korjaustoimenpiteitä. Monilla laitteilla saattaa olla ongelmia, jos ne yrittävät kirjata tapahtuman virheelliselle päivämäärälle. Lentokoneita ohjaavat tietokoneohjatut "fly-by-wire" -järjestelmät saattavat toimia virheellisesti, jos niiden ohjelmointi johtaa siihen, että ne päättävät tärkeän huollon suoritetun viimeksi vuonna 1900, ja ne saattavat jopa jäädä virhekierrokseen ja sammua.

Mahdollisesti tappavat logiikkapommin palauttavat vaikutukset, jotka sulkevat sääntöjään noudattamattomat ohjausjärjestelmät, saattavat tehdä vuosituhannen vaihdoksesta ikimuistoisen epämiellyttävistä syistä. Muista, että monet laitteet, jotka jäävät virhekierrokseen ja sammuvat, voivat vaikuttaa sinuun, vaikka et löytäisikään itseäsi uudenvuosituksessa ilmassa. Olisit hyvin neuvottu välttämään onnettomuutta, joka johtuu Y2K-yhteensopimattomista sydämentahdistimista tai yksinkertaisesti humalaisista millenniaalijuhlia viettävistä, sillä jos tahdistimet sammuvat, puhelinjärjestelmäkin saattaa pettää eikä ambulanssi välttämättä edes saavu. Ellet asu Brasiliassa tai Ukrainassa, olet tottunut vastaamaan puhelimeen tai käynnistämään auton puhelimen ja kuulemaan automaattisesti soittotoni. Onneksi sinun tarvitsee harvoin miettiä teknisiä yksityiskohtia siitä, miten puhelinjärjestelmä toimii. Kuitenkin kävi ilmi, että puhelinverkkojen kytkimet ja reitittimet ovat erittäin päivämääräriippuvaisia. Kaikki yhteydet kirjataan päivämäärä- ja kellonaikaan, mikä on ratkaisevan tärkeää puheluiden keston laskemiseksi laskutusta varten. Jos teet yhden minuutin puhelun 31. joulukuuta 1999 klo 11:59:30 ja klo 12:00:00 järjestelmä lukee puhelusi kestoksi negatiivisen ajan, joka olisi yli 99 vuotta, virhekierrokset ja sammumiset ovat mahdollisia. Vaikka pitkän matkan operaattorit käyttävät suuria summia päivittääkseen kytkimensä vuoteen 2000 yhteensopiviksi – ja paikalliset palveluntarjoajat oletettavasti tekevät samoin – jos jopa muutama pienempi yritys epäonnistuu ja kaatuu, koko verkko voi häiriintyä. Olet onnekas, jos saat soittotonin 1. tammikuuta 2000.

Y2K-asiantuntija Peter de Jager kiteyttää: “Jos menetämme kyvyn soittaa, menetämme kaiken. Menetämme sähköiset rahansiirrot, kaupankäynnin ja konttoripankkipalvelut.” Y2K-ongelmien seuraukset voivat ulottua näitäkin laajemmille alueille.

Tänä päivänä kukaan ei tiedä, kuinka laajalle levinneesti elintärkeät järjestelmät kaatuvat vuoden 2000 ongelman takia. Päivämääräherkät sulautetut järjestelmät, joita ei voida uudelleen ohjelmoida vaan jotka on vaihdettava, jos ne eivät toimi, löytyvät esimerkiksi 1976 jälkeen valmistetuista korteista, kuorma-autoista ja busseista. (Ehkä et joudu onnettomuuteen, sillä näiden ajoneuvojen käynnistysongelmat estävät siirtymisen eteenpäin.) Sulautettuja järjestelmiä on laajalti myös kaikentyyppisissä voimalaitoksissa, vesihuolto- ja jätevesijärjestelmissä, lääketeknisissä laitteissa, sotilasvarusteissa, lentokoneissa, merellä sijaitsevissa öljyalustoissa, öljytankkereissa, hälytysjärjestelmissä ja hisseissä. Vaikka monet mikroprosessoreita sisältävät kokoonpanot eivät suorita päivämääräherkkiä toimintoja, ne saattavat silti olla riippuvaisia kellosta, joka voi olla Y2K-herkkä, sisäisten toimintojensa ylläpitämiseksi.
## Mainframe-tietokoneet ja vuosituhannen aikabommi

Hallituksen ja suuryritysten laajamittaiset komentojärjestelmät, jotka käsittelevät valtavia transaktiomääriä mainframe-tietokoneilla, olivat alkuperäinen huolenaihe Y2K-ongelman suhteen. Koska nämä järjestelmät toimivat suurilla koneilla, joiden suurin osa ohjelmistoista on vuosikymmenten vanhoja ja usein epäyhteensopivia nykyisten vaatimusten kanssa, alkuperäiset hälytykset vuosituhannen perään – joita Peter de Jager antoi ensimmäisenä 1990-luvun alussa – ovat keskittyneet pääasiassa operatiivijärjestelmien päivittämisen tarpeeseen suurille, moniprosessorisille mainframeille. Herra de Jager ilmaisi huolensa siitä, ettei COBOLia hallitsevia ohjelmoijia – vanhaa mainframe-kieltä – ehkä ole riittävästi kattamaan vaadittavat korjaukset ja päivitykset päivämääräherkälle koodille, vaikka kaikki järjestelmistään haavoittuvat yritykset ja virastot olisivat aloittaneet kriisiaikaisen korjausohjelman useita vuosia sitten. Koska näin ei ole tapahtunut ja monet päivämääräherkkien tietojärjestelmien ylläpitäjät ovat vasta alkaneet arvioida haavoittuvuuttaan, voidaan varmuudella ennustaa, että monet mainframe-järjestelmät eivät ole valmiita toimimaan sujuvasti vuoteen 2000 asti.

Tämä on ehdottomasti merkittävä huolenaihe, sillä nykyisen talouden rakenteessa tietokoneprosessoroinnille ei ole oikeastaan vaihtoehtoa. Useimmat yritykset, jotka ovat tarpeeksi suuria edellyttämään mainframea transaktioidensa hoitamiseen, ovat riippuvaisia sellaisista transaktiomääristä, joita ei voisi hallita vanhanajan 1800-luvun paperiprosessien avulla. Jos tällaiset yritykset pakotettaisiin palaamaan paperityöhön, ne pystyisivät todennäköisesti käsittelemään vain murto-osan normaalista transaktiomäärästään. Tällainen liiketoiminnan romahtaminen aiheuttaisi tuloshokin, joka vaarantaisi paitsi erittäin pääomavaraisten myös muiden yritysten selviytymisen.

Melkein kaikki rahaan liittyvä – laskutus-, hankinta- ja palkkajärjestelmät sekä varastonhallinta ja sääntelyvaatimusten noudattaminen – menisi sekaisin. Suuret määrät päivämääriä katoaisivat, kun tietokoneet kaatuisivat tai purskahtaisivat virheellistä dataa Y2K-ongelman seurauksena. Joissakin tapauksissa järjestelmien välitön kaatuminen voisi osoittautua jopa siunaukseksi sen sijaan, että ne korruptoisivat tietonsa kumuloivasti, kunnes massiivinen toimintahäiriö herättäisi huomion ongelmaan. Mitä tiedostoille tapahtuisi, kun varmuuskopiointiohjelma kopioisi 04.07.99-alkuperäiset tiedostot päivitykseen 04.01.00? Kuka tietää? Tulkitseeko tietokone tammikuun 4. päivänä, "1900", tehdyn maksun vakuutussopimuksesta merkkinä siitä, että sopimus on ollut vuosisadan ajan maksukyvyttömänä, jolloin se peruutetaan ja poistetaan arkistosta? Pyytävätkö pankkien ja rahoitusyhtiöiden järjestelmät arvioimaan sadan vuoden koron lainoista, jotka ulottuvat uuden vuosituhannen vaihtuessa? Säilyttävätkö pankkisi ja välittäjätoimistosi tarkan kirjanpidon tilisi saldoista ja antavatko ne sinulle ajantasaisen pääsyn varoihisi? Nämä ovat vain joitakin mielenkiintoisia kysymyksiä, joita tulet kohtaamaan Y2K-ongelman vuoksi.

> "Tämä on potentiaalisesti vuoden 2000 ongelman tuhoisin osa. Tämä ei ole se häiriö, jossa palkkasi saapuu muutaman päivän myöhästyksellä. Tämä on kadunveressä 'verinen' tilanne." - Tohtori Leon Kappelman, Society For Information Managementin vuosituhannen työryhmän puheenjohtaja
Myös hyvin huolestuttavaa on, mitä tapahtuu, jos sähkö katkeaa Y2K-ongelmien takia. Ilman sähköä edes useimmat järjestelmät, jotka eivät ole Y2K-vaurioituneita, eivät toimi: jääkaappisi, pakastimesi – kenties jopa lämmönlähteesi. Y2K-yhteensopivuusongelmat saattavat vaikuttaa ydinvoimaloiden turvallisuuteen liittyviin pääsy- ja ohjaustoimintoihin. Esimerkiksi ydinkäyttöisissä laitoksissa henkilökunta kantaa dozimetrilaitteita, jotka mittaavat heidän altistustaan säteilylle laitoksessa oleskelun aikana. Näitä laitteita analysoidaan säännöllisesti, ja altistusmääristä kerätty data tallennetaan tietokonejärjestelmään, joka hallitsee henkilökunnan pääsyä laitokseen. Ilmeistä on, että jos ohjaavat tietokoneet pettävät, ne tekevät kaaoksen kaikissa monimutkaisissa ohjausjärjestelmissä, joiden tarkoituksena on taata turvallinen toiminta ja asianmukainen ylläpito. Vielä tärkeämpää on se, että Ydinsuostutuskomission muistiinpano huomauttaa, että monet "ei-turvallisuuteen liittyvät, mutta tärkeät tietokonepohjaiset järjestelmät – pääasiassa tietokannat ja tietojen keräys, jotka ovat välttämättömiä laitoksen toiminnalle" ovat päivämääräherkkiä.

Perinteiset voimalaitokset eivät myöskään ole vähemmän alttiita Y2K-häiriöille. Yksi syy on se, että hiilivoimalat ovat alttiita pintakuljetusjärjestelmän häiriöille, jotka toimittavat hiiltä kattiloihin. Vuoden 1997–1998 talven lämmityskauden aikana hiilivoimaloiden toimijat joutuivat joissakin tapauksissa vähentämään tuotantoaan, koska Länsimaisen hiilen raidekuljetuksissa hidastui toimituksia, mikä johtui Southern Pacificin ja Union Pacificin rautatiejärjestelmien yhdistymisestä. Ongelma ilmeni, kun kahden rautatien tietokoneohjaus- ja lähetysjärjestelmien välillä oli yhteensopimattomuuksia. Union Pacificin tiedottajan mukaan näiden järjestelmien integroiminen muuttui "painajaiseksi", huolimatta siitä, että Union Pacific Technologiesia pidettiin tietokoneistetun kuljetusohjauksen kehityksen edelläkävijänä. Ohjelmointiongelmien seurauksena yhtiö ei pystynyt tarkasti seuraamaan rahtvaunujen liikkeitä. Union Pacificin epäonnistuminen Southern Pacificin sulauttamisessa on huono ennusmerkki siitä, mitä saattaa tapahtua, kun Y2K-logiikalla varustetut "aikalamput" häiritsevät kuljetus-, sähköntuotanto- ja muita talouden toimintoja.

Suurin huoli sähköverkostosta kuitenkin johtuu siitä, että koko järjestelmä on herkkä tarkkailulle ja tietokoneohjaukselle, joka siirtää sähköä ylijäämätuotantoalueilta puutteen alueille. Tätä prosessia on seurattava huolellisesti tietokoneella, jotta estetään jännitepiikkejä ja järjestelmäongelmia. Kaikki sähkön siirrot kirjataan ajankohdasta riippuen, aivan kuten puhelinyhteys. Vaikka liitosten muodostamiseen käytetään rasittavia mekaanisia releitä, niitä ohjaavat tietokonejärjestelmät. Nämä tietokoneohjaukset, jotka ovat olennaisia kuormantasapainon ylläpitämiseksi, saattavat pettää samoista syistä kuin puhelinverkostot. Itse asiassa Pohjois-Amerikan sähkön kuormanjakeluohjausjärjestelmät on yhdistetty toisiinsa T-1-linjojen ja puhelinmikrolinkkien kautta. Jos siis puhelinverkko pettää, voit odottaa myös sähkön katkeavan. Ja muista, kuten Kanadassa tammikuussa 1998 koettu osoittaa, kun laajalla alueella sähkö sammuu, järjestelmän käynnistäminen uudelleen on haastavaa. Sähkökatko saattaa kestää epämukavan pitkään.

## Y2K ja ydinvarustus

Modernien talouksien osalta talven keskellä tapahtuva laaja sähkökatko aiheuttaisi suuria häiriöitä ja potentiaalisesti terveysriskejä, erityisesti niille, jotka ovat riippuvaisia sähköisestä lämmöstä ja lääkinnällisistä laitteista. Mutta pahin skenaario on vielä pahempi. John Koskinenin mukaan, joka johtaa presidentti Clintonin Y2K-muutosneuvostoa, Yhdysvaltain sotilasvarustot saattavat lakata toimimasta täsmälleen keskiyön aikaan 31. joulukuuta 1999. Vaikka hän ei halua aiheuttaa tarpeetonta paniikkia, Koskinen lisää: "Siitä täytyy olla huolissaan." Yksi ydinmiinoihin liittyvä huolenaihe on se, että jos data ei toimi, ne voivat oikeastaan laukaista itsestään.


Tietenkin tämä huoli koskisi yhtä hyvin tai vielä voimakkaammin Venäjän ydinaseita. Venäjän konkurssi on tehnyt Y2K-yhteensopivuuden parannuksista ongelmallisempia kuin Yhdysvalloissa, ja on todisteita siitä, että Venäjä ei vielä ota Y2K-muunnosta vakavasti. Vaikka toivoisi, ettei olisi satunnaisia laukaisuja, ei pitäisi epäillä, että vuosituhannen vaihteen myötä maailmanlaajuinen turvallisuustilanne voisi kärjistyä – edes siksi, että monien maiden sotilasviestintäjärjestelmät eivät ehkä toimi normaalisti. Kuten Koskinen toteaa: "Jos istut jossain maassa ja yhtäkkiä et oikein ymmärrä, mitä menee vikaan, ja viestintäsi ei toimi yhtä hyvin, hermostut entisestään." Lisää siis tämä Y2K-huoliesi listalle. Logiikkarummun kaltaiset ajasta riippuvat "aikapommien" laukaisut voivat ennakoida aidosti räjähtävien panssaripommien laukaisua – mikä korostaa tietosodankäynnin vaaroja keskitetyille komentojärjestelmille.

Jos terroristit haluavat iskeä mihin tahansa keskitettyyn järjestelmään, he voivat valita toimintapäiväksi 31. joulukuuta 1999, koska se on monien järjestelmien suurimman haavoittuvuuden hetki. Viestintä on heikossa tilassa parhaimmillaan, sähkö saattaa pettää, kulkuneuvoissa voi olla käynnistysongelmia, hätäkeskuspalvelut kuten 911 – politiisi, palokunta ja ambulanssi – eivät välttämättä toimi, ja lisäksi monet muut itsestäänselvyyksinä pidetyt toiminnot, kuten ilmatieliikenteen valvonta, voivat lakata toimimasta. Ilman sähköä hana ei johda vettä, jätevedenpuhdistusjärjestelmät pettävät ja liikennevalot saattavat sammua. Muutaman tunnin kuluttua todellisesta kuljetusjärjestelmän romahtamisesta ruokakaupoissa oleva ruoka loppuisi (tai ryöstettäisiin). Viimeaikaisten kokemusten perusteella amerikkalaisissa kaupungeissa voi olettaa, että ilman sähköä, vettä ja lämmitystä monille, ilman valoa ja katkonaisia yhteyksiä hätäkeskuksiin – mukaan lukien poliisi ja palokunta – ei synny sivilisaatiota. Vaikka kenenkään ei voi olla varma Y2K-ongelman vaikutuksista, se voisi laajentua kadotuksiin ja kadotuksiin kaduilla, erityisesti jos kävisi ilmi, että palkkojen, sosiaaliturvan ja eläke-ajanmaksujen maksaminen epäonnistuisi laajamittaisesti.

> "Me emme tule olemaan sitä, mitä olemme olleet, vaan alamme olla something muuta."[^20] - Joachim de Fiore

Uhkauksia uudesta vuosituhannesta ei välttämättä perusteta kristinuskoon sidottuun teologiaan, mutta ne sopivat hyvin Joachim de Fioren milleniaaliperinteeseen, jonka meditaatiot saivat hänet uskomaan, että Kristus oli vain "historian toinen sarana" ja että vielä toinen oli määrä toteutua.[^21] Näin argumentoikin filosofi Michael Grosso, joka ehdottaa, että tietorevoluutio ohjaa ihmiskunnan historiaa kohti läntisen maailman profeetallisen vision toteutumista. Hän kutsuu tätä "teknoklaukseksi". Riippumatta siitä, vaikuttaako teknologian kehitystä milleniaaliset visiot, Y2K-ilmiö on artefakti vallitsevasta länsimaisesta ajankuvasta. Outoudessaan se voisi täydentää unelmia, haaveita ja visioita tai visioiden numeerisia tulkintoja, kuten Newtonin selityksiä Danielin profetioista. Nämä intuitiiviset harppaukset lähtevät siitä näkökulmasta, jonka mukaan Kristuksen syntymä on historian keskeinen tapaus. Niihin liittyy myös suurten pyöreiden lukujen psykologinen voima, jonka jokainen kauppias tunnistaa lumoavaksi. Keskiaikaisen aikakauden kaksi tuhannesvuotta eivät voi olla muuta kuin intuitiivisten ihmisten mielikuvituksen tarkennuskohde.

Kriitikko voisi helposti saada nämä ennustukset näyttämään naurettavilta käsittelemättä edes epäselviä ja kiistanalaisia teologisia käsityksiä Tuomiopäivästä ja Viimeisestä tuomiosta, jotka antavat näille visioille suuren osan niiden voimasta. Mielenkiintoista on kuitenkin se, että Y2K-tietokonevirhe ohittaa aritmeettiset virheet, jotka muuten saattaisivat vaikuttaa vähentävän vuoden 2000 tärkeyttä jopa kristillisessä kehyksessä. Vuosi 2000:lla on potentiaalia muodostua nousupisteeksi historian seuraavalle vaiheelle yksinkertaisesti siksi, että se tuo lähemmäs uuden vuosituhannen saapumisen. Tiukan logiikan mukaan seuraava vuosituhat ei ala ennen vuotta 2001. Vuosi 2000 on vain kaksituhatta vuotta Kristuksen syntymästä. Tai se olisi ollut, jos Kristus olisi syntynyt kristillisen ajan ensimmäisenä vuonna – hän ei syntynyt niin. Vuonna 533, kun Kristuksen syntymä korvasi Rooman perustamisajankohdan länsimaisen kalenterin perusteena, munkeja, jotka ottivat uuden käytännön käyttöön, laskivat Kristuksen syntymän väärin. Nykyään hyväksytään, että hän syntyi vuona 4 eKr. Tämän perusteella täysi kaksituhatta vuotta hänen syntymästään täyttyy jossain vaiheessa vuonna 1997. Siksi Carl Jungin ilmeisen omituisena näyttämä käynnistymispäivä uuden ajan alulle.


Naura vaikka, mutta emme halveksi eikä hylkää intuitiivisia ymmärryksiä historiasta. Vaikka perustelumme pohjautuvat logiikkaan, eivät tuloihin, olemme hämmästyneitä inhimillisen tietoisuuden profeetallisesta voimasta. Kerta toisensa jälkeen se lunastaa hulluuden, parapsykologien ja pyhimysten näkemykset. Sama saattaa tapahtua vuoden 2000 muutoksen yhteydessä. Lännen mielikuvassa jo pitkään kiinnittynyt päivämäärä näyttäytyy käännekohtana, joka ainakin osittain vahvistaa sen, että historiassa on kohtalo. Emme pysty selittämään miksi näin on, mutta olemme vakuuttuneita, että niin on.

Intuitionamme on, että historiassa on kohtalo, ja että vapaa tahto sekä determinismi ovat saman ilmiön kahta puolta. Ihmissuhteet, jotka muovaavat historiaa, käyttäytyvät kuin ne ohjautuisivat jonkinlaisella kohtalolla. Niin kuin elektroniplasma – tiheä elektronikaasu – käyttäytyy monimutkaisena järjestelmänä, niin tekevät ihmisetkin. Elektronien yksilöllisen liikkeen vapaus osoittautuu yhteensopivaksi erittäin organisoidun kollektiivisen käyttäytymisen kanssa. Kuten David Ohm totesi elektroniplasman osalta, ihmishistoria on "erittäin organisoitunut järjestelmä, joka toimii kokonaisuutena."

Maailman toiminnan ymmärtäminen edellyttää realistisen intuitiivisen käsityksen kehittämistä siitä, miten ihmiskunta tottelee luonnon prosessien matematiikkaa. Todellisuus on epälineaarista, mutta useimpien ihmisten odotukset eivät sitä ole. Muutoksen dynamiikan ymmärtämiseksi on tunnistettava, että ihmiskunta – kuten muutkin luonnon monimutkaiset järjestelmät – on luonteeltaan syklinen ja katkonainen. Tämä tarkoittaa, että tiettyjen historian piirteiden on taipumus toistua, ja tärkeimmät muutokset, kun ne tapahtuvat, voivat olla äkillisiä sen sijaan, että ne etenisivät vähitellen.

Ihmiselämän sykleistä salaperäinen viisisadan vuoden sykli näyttäytyy merkittävänä käännekohdana Lännen sivilisaation historiassa. Vuoden 2000 lähestyessä meitä kummittelee outo seikka, että jokaisen viidellä jaollisen vuosisadan viimeinen vuosikymmeni on merkinnyt syvää murrosta Lännen sivilisaatiossa – kuoleman ja uudelleensyntymän mallia, joka rajaa uuden sosiaalisen järjestäytymisen vaiheet aivan kuten kuolema ja syntymä määrittelevät ihmislukujen syklin. Tämä on ollut totta ainakin vuodesta 500 eaa., jolloin kreikkalainen demokratia nousi Cleisthenesin perustuslaillisten uudistusten myötä vuonna 508 eaa. Seuraavat viisi vuosisataa olivat kasvun ja muinaisen talouden tehostumisen aikaa, huipentuen Kristuksen syntymään vuonna 4 eaa. Tämä oli myös muinaisen talouden suurimman vaurauden aika, jolloin korot olivat alhaisimmillaan ennen moderneja aikoja.

Seuraavien viiden vuosisadan aikana vauraus vähitellen laski, mikä johti Rooman valtakunnan romahtamiseen myöhään viidennellä vuosisadalla jaa. William Playfairin tiivistelmä on syytä toistaa: "Kun Rooma oli suuruutensa huipulla... se nähdään Kristuksen syntymän aikaan eli Augustuksen hallituskaudella, ja sen jälkeen se havaitaan vähitellen kipuavan vuoteen 490 saakka."[^22] Silloin viimeiset legioonat hajoivat, ja Länsi-maa vajosi pimeisiin aikoihin.
Seuraavien viiden vuosisadan aikana talous kuihtui, kaukana käytetty kauppa pysähtyi, kaupungit tyhjentyivät, raha hävisi liikkeestä ja taide sekä lukutaito lähes katoavat. Tehokkaan lain katoaminen Lännen Rooman valtakunnan romahtaessa johti primitiivisempien riitojen ratkaisujärjestelmien syntyyn. Verisyytalo alkoi saada merkitystä jo viidennen vuosisadan lopulla, ja ensimmäinen virallisesti kirjatuksi merkityt koettelemuksellinen oikeudenkäynti tapahtui juuri vuonna 500.

Vielä kerran, tuhannen vuoden takaa, kymmenes vuosisadan viimeinen vuosikymppi todisti toisenlaisen "valtavan murroksen sosiaalisissa ja taloudellisissa järjestelmissä." Ehkä näistä muutoksista vähiten tunnettu, feodaalinen vallankumous, alkoi aikana, jolloin taloudellinen sekä poliittinen kaaos oli täydellistä. Teoksessaan *Tuhannen vuoden muutos* Pariisin yliopiston keskiaikaisten historian professori Guy Bois väittää, että tämän kymmenes vuosisadan lopun murroksen seurauksena antiikin instituutioiden jäänteet romahtuivat kokonaan ja kaaoksen keskeltä feodaalinen järjestelmä sai uuden muodon.[^23] Raoul Glaberin sanojen mukaan “Sanottiin, että koko maailma, yhtenäisesti, ravisteli pois antiikin harsoja.”[^24] Äkillisesti syntynyt uusi järjestelmä mahdollisti talouskasvun hitaan elpymisen. Nyt Keskiaikaksi kutsutun viiden vuosisadan aikana raha sekä kansainvälinen kauppa kokivat jälleensyntymän, samoin kuin aritmetiikan, lukutaidon ja ajan tajunnan uudelleenlöytämisen.

Sitten, 1400-luvun viimeisellä vuosikymmenellä, koettiin toinen merkittävä käännekohta. Juuri silloin Eurooppa nousi pois Mustan surman aiheuttamasta väestökadosta ja melkein välittömästi alkoi lujittaa valtaansa muualla maailmassa. Termit “tulipulverirevoluutio”, “renessanssi” ja “reformaatio” kuvaavat tämän siirtymävaiheen eri puolia, jotka toivat modernin aikakauden mukanaan. Uutinen ilmoitettiin räjähdyksellä, kun Kaarle VIII hyökkäsi Italiaan uusilla pronssikanuunoilla. Tämä merkitsi maailman avoimeksi tulemista, jota ilmentää Kristoffer Kolumbuksen matka Amerikkaan vuonna 1492. Uuden maailman avaaminen käynnisti voimakkaan työntövoiman kohti ihmiskunnan historian dramaattisinta talouskasvua. Se synnytti fysiikan ja astronomian mullistumisen, joka johti modernin tieteen syntyyn, ja sen ideoita levitettiin laajasti uuden painokoneen avulla.

Nyt seisomme uuden vuosituhannen muutoksen kynnyksellä. Teollisesta aikakaudesta perittyjen suurten komentokeskusten ja ohjausjärjestelmien voi murentua kuin yhden hevosen vaunu vuosituhannen keskiyöllä. Olivatpa Y2K-logiikkatroppu aiheuttamassa teollisuusyhteiskunnan välitöntä romahtamista vai eivät, niiden päiviä on laskettu. Odotamme informaatioyhteiskunnan saapuvan ja muuttavan maailmaa radikaalisti tavoilla, joita tämä kirja pyrkii selittämään. Olisit täysin oikeutettu epäilemään tätä, sillä mikään vuosituhannen aikana kahdesti toistuva sykli ei ole osoittanut tarpeeksi toisteja ollakseen tilastollisesti merkittävä. Itse asiassa jopa paljon lyhyemmät syklit ovat herättäneet taloustieteilijöiden epäilyksiä, jotka vaativat tilastollisesti vakuuttavampaa näyttöä. "Professori Dennis Robertson kirjoitti kerran, että meidän olisi paremmin odotettava pari vuosisataa ennen kuin voimme olla varmoja" nelivuotisista ja kahdeksasta–kymmeneen vuoteen kestävästä kauppasyklistä.[^25] Tällä perusteella professori Robertson joutuisi lykkäämään päätöstään noin kolmekymmentätuhannen vuoden ajaksi varmistaakseen, ettei viisisataa vuoden sykli ole vain tilastollinen sattuma. Me emme ole yhtä dogmaattisia, vaan tunnustamme, että todellisuuden mallit ovat monimutkaisempia kuin useimpien taloustieteilijöiden staattiset ja lineaariset tasapainomallit.

Uskomme, että vuoden 2000 saapuminen merkitsee jotain enemmän kuin vain toista kätevää jakoviivaa loputtomassa ajan jatkumossa. Uskomme, että se tulee olemaan käännekohta Vanhan maailman ja tulevan Uuden maailman välillä. Teollisaika on nopeasti menossa, ja sen loppua voi ironisesti kiihtyä jo varhaisen tietokonemuistin korkean hintatason takia, mikä kannusti laajamittaiseen kahden numeron päivämääräkenttien käyttöönottoon. Kun Hallerithin reikäkortit pystyivät sisältämään vain kahdeksankymmentä merkkiä, päivämäärien lyhentäminen vaikutti järkevältä toimenpiteeltä. Aikaisempien ohjelmoijien odotuksiin nähden heidän päivämääräkenttänsä lyhentäminen kesti kuitenkin neljä vuosikymmentä vuosituhannen loppuun asti, kuin tahaton logiikkatroppu, joka uhkaa tuhota suuren osan teollisuusyhteiskunnan. Yhdysvaltain hallituksen Office of Management and Budget kuvaili ongelmaa raportissaan "Getting Federal Computers Ready for 2000" (7. helmikuuta 1997) seuraavasti: "Ellei niitä korjata tai vaihtaa, tietokoneet epäonnistuvat vuosituhannen vaihteessa yhdellä kolmesta tavalla: ne hylkäävät lailliset merkinnät, laskentatulokset ovat virheellisiä tai ne yksinkertaisesti eivät käynnisty." Näiden kolmen lopputuloksen yhdistelmä voisi lamaannuttaa teollisuusyhteiskunnan. Massatuotantoteknologia on määrä joutua uuden miniaturisaatioteknologian varjoon joka tapauksessa, ja lähitulevaisuuden kriisi kiihdyttäisi tätä prosessia entisestään. Uuden informaatioteknologian myötä on synnyttänyt epälineaarisen dynamiikan uuden tieteen, jonka hämmästyttävät johtopäätökset ovat vielä varsin sirpaleisia, eikä niitä ole vielä kudottu yhtenäiseksi maailmankuvaksi. Elämme tietokoneiden aikaa, mutta unelmamme edelleen tihkuvat lankakudoksilla. Elämme yhä teollisuudentutkijoiden metaforien ja ajatusten mukaisesti. Politiikkamme jakautuu yhä teollisuuden oikealle ja vasemmalle, kuten Adam Smithin ja Karl Marxin kaltaiset ajattelijat, jotka kuolivat ennen kuin lähes kaikki nykyisin elävät syntyivät.[^28] Teollinen maailmankuva – joka sisältää teollistieteen toimintaperiaatteet – on yhä koulutetun mielipiteen "järkevänä intuitiotasona." Teesimme on, että teollisuusajan "järkevyys" ei enää päde monilla elämänalueilla, kun maailma on muuttumassa.

Uskomme, että vuoden 2000 saapuminen merkitsee enemmän kuin vain toista kätevää jakoviivaa loputtomassa ajan jatkumossa. Uskomme sen olevan käännekohta Vanhan maailman ja tulevan Uuden maailman välillä. Teollisaika on nopeasti menossa, ja sen loppua voi ironisesti kiihtyä jo varhaisen tietokonemuistin kalliuden vuoksi, mikä johti laajamittaiseen kahden numeron päivämääräkenttien käyttöönottoon. Kun Hallerithin reikäkortit pystyivät sisältämään vain kahdeksankymmentä merkkiä, päivämäärien lyhentäminen vaikutti harkitulta ratkaisulta. Aikaisempien ohjelmoijien odotuksiin nähden päivämääräkentän lyhentäminen kesti kuitenkin neljä vuosikymmentä vuosituhannen loppuun asti – kuin tahaton logiikkatroppu, joka uhkaa tuhota suuren osan teollisyhteiskuntaa. Yhdysvaltain hallituksen Office of Management and Budget kuvasikin ongelman seuraavasti raportissaan "Getting Federal Computers Ready for 2000" (7. helmikuuta 1997): "Ellei niitä korjata tai vaihtaa, tietokoneet epäonnistuvat vuosituhannen vaihteessa yhdellä kolmesta tavalla: ne hylkäävät lailliset merkinnät, antavat virheellisiä laskentatuloksia tai eivät yksinkertaisesti käynnisty." Näiden kolmen lopputuloksen yhteisvaikutus voisi lamaannuttaa teollisyhteiskunnan. Massatuotantoon perustuva teknologia on määrä jättämään taakseen uuden miniaturisaatioteknologian myötä – mikä vain nopeuttaa prosessia entisestään. Uuden informaatioteknologian myötä on syntynyt myös uusi epälineaarisen dynamiikan tiede, jonka hämmästyttävät johtopäätökset ovat vielä varsin irrallisia, eikä niitä ole vielä kudottu yhteen kattavaksi maailmankuvaksi. Elämme tietokoneiden aikaa, mutta unelmamme vielä kudotaan lankakudoksilla. Jatkamme elämistä teollisuuden metaforien mukaan. Politiikkamme jakautuu yhä teollisuuden oikealle ja vasemmalle, kuten ajattelijat kuten Adam Smith ja Karl Marx (jotka kuolivat ennen lähes kaikkia nykyisiä ihmisiä) ovat kartoittaneet. Teollinen maailmankuva, joka sisältää teollisen tieteen periaatteet, on yhä koulutettujen mielipiteiden "jarkevanä intuitiona." Teesimme on, että teollisuusajan "järkevyys" ei enää päde monilla aloilla, kun maailma muuttuu.


Yli kahdeksankymmentäviisi vuotta sen 1911 päivän jälkeen, jolloin Oswald Spengleria valaisi aavistus tulevasta maailmansodasta ja "Lännen rappeutumisesta", mekin näemme, että "*historiallinen vaiheenvaihdos* tapahtuu... siinä kohdassa, joka sille oli määrätty jo satoja vuosia sitten."[^26] Kuten Spengler, näemme Länsimaisen sivilisaation lähestyvän tuhoa, ja sen myötä romahtavan sen maailmanjärjestyksen, joka on hallinnut viimeiset viisi vuosisataa aina siitä lähtien, kun Kolumbus purjehti länteen ottaakseen yhteyttä Uuteen maailmaan. Toisaalta, toisin kuin Spengler, me näemme uuden vaiheen syntyvän Länsimaisen sivilisaation historiassa tulevalla vuosituhannella.

[^1]: Danny Hillis, "The Millennium Clock," Wired, Special Edition, Fall 1995, s.48.

[^2]: Ericka Cheetham, The Final Prophecies of Nostradamus (New York: Putnam, 1989), s.424.

[^3]: Dr. Edward Yardeni, Year 2000 Recession: "Prepare for the worst. Hope for the best," Version 5.0, 13. toukokuuta 1998, B1.2.

[^4]: Michael Grasso, The Millenium Myth: Love and Death at the End of Time, Wheaton, Illinois: Quest Books, 1995.
[^5]: Johan Huizinga, *The Waning of the Middle Ages*, käännös E Hopman (Lontoo: Penguin Books, 1990), s. 172.

[^6]: Marshall McLuhan, *Understanding Media*, New York: Signet, 196, s. 19.

[^7]: James George Frazer, *The Golden Bough: A Study in Magic and Religion* (New York: Macmillan, 1951), s. 105.

[^8]: Lisätietoja fragmentoituneista suvereniteeteista kansvaltiota edeltävinä ja vaihtoehtoisina muotoina, katso Charles Tilly, *Coercion, Capital and European States AD 990-1992* (Oxford: Blackwell, 1993).

[^9]: Saksan GPI-indeksi oli 33,20 31. joulukuuta 1948 ja 112,90 30. kesäkuuta 1995, mikä edustaa vuosittaista yhdistettyä arvonalenemista 2,7 prosenttia. Yhdysvaltojen CPI oli 24 31. joulukuuta 1948 ja 152,50 30. kesäkuuta 1995. Jakson kumulatiivinen inflaatio Yhdysvalloissa oli 635 prosenttia.
[^10]: Janet L. Abu-Lughod, Before European Hegemony: The World System A.D.1250-1350 (Oxford: Oxford University Press, 1991), s. 62.

[^11]: Jack Cohen ja Ian Stewart, The Collapse of Chaos (New York: Viking, 1994).

[^12]: Katso James Dale Davidson ja Lord William Rees-Mogg, *The Great Reckoning*, 2. painos (New York: Simon & Schuster, 1993), s. 53.

[^13]: Frederic C. Lane, "Economic Consequences of Organized Violence," The Journal of Economic History, vol. 18, nro 4 (joulukuu 1958), s. 402.

[^14]: Nicholas Colehester, "Goodbye NationState, Hello . . . What?," New York Times, 17. heinäkuuta 1994, s. E17.
[^15]: Norman Macrae, "Governments in Decline," Cato Policy Report, heinä-/elokuu 1992, s. 10.

[^16]: Arthur C. Clarke, *Profiles of the Future: An Enquiry into the Limits of the Possible* (Lontoo: Victor Gollancz Ltd., 1962), s. 13.

[^17]: Ibid.

[^18]: A. T. Mann, *Millennium Prophecies: Predictions for the Year 2000* (Shafiesbury, Englanti: Element Books, 1992), s. 88, 112, 117.

[^19]: Yardeni, op. cit., s. 45.
[^20]: Viitattu Froosossa, op. cit., s. 40.

[^21]: Sama.

[^22]: William Playfair, Tutkimus mahtavien ja varakkaiden kansojen rappion pysyvien syiden takana: suunniteltu osoittamaan, kuinka Britannian imperiumin vauraus voidaan pidentää (Lontoo: Greenland ja Norris, 1805), s. 79.

[^23]: Guy Bois, Vuosituhannen muodonmuutos: Lournardin kylä antiikista feodalismiin (Manchester, Englanti: Manchester University Press, 1992).

[^24]: Sama, s. 150.
[^25]: Lainattu teoksesta S. B. Saul, The Myth 0f the Great Depression (London: Macmillan, 1985), s. 10.

[^26]: Oswald Spengler, The Decline of the West, kääntänyt Charles Francis Atkinson, lainattuna teoksesta I. F. Clark, The Pattern of Expectation, 1644–2001 (London: Jonathan Cape, 1979), s. 220.

[^27]: Nomenklatunas ovat juurtuneita eliittejä, jotka hallitsivat entistä Neuvostoliittoa ja muita valtion ohjaamia talouksia.

[^28]: Adam Smith kuoli vuonna 1790, Karl Marx vuonna 1883.