# East of Eden

::: {.content-hidden when-format=latex}
*The Agricultural Revolution and the Sophistication of Violence*
:::

> “And the Lord said unto Cain, Where is Abel, thy brother? And he said, I know not: Am I my brothers' keeper? And he said, What hast thou done? the voice of thy brothers' blood crieth unto me from the ground.” - GENESIS 4:9-10

Viisisataa sukupolvea sitten alkoi ihmiskunnan yhteiskunnan organisaatiossa ensimmäinen vaiheenvaihdos.[^51] Esivanhempamme eri alueilla tarttuivat vastahakoisesti kömpelöihin työvälineisiin, terävöittivät keppejä ja improvisoivat tilapäisiä haravia ja ryhtyivät työhön. Kylvessään ensimmäisiä satojaan he samalla loivat uuden perustan vallalle maailmassa. Maanviljelysrevoluutio oli ensimmäinen suuri taloudellinen ja sosiaalinen vallankumous. Se alkoi Eedenistä karkottamisesta ja eteni niin hitaasti, että maanviljely ei ollut vielä täysin syrjäyttänyt metsästystä ja keräilyä kaikilla sopivilla alueilla maailmanlaajuisesti, kun 1900-luku avautui. Asiantuntijoiden mukaan jopa Lähi-idässä, jossa maanviljely ensisijaisesti ilmestyi, sen käyttöönotto tapahtui “a long incremental process” – eli pitkässä asteittaisessa prosessissa, joka “may have taken five thousand years or more.”[^52]

Maanviljelyn vallankumouksen ymmärtäminen on ensimmäinen askel informaatiovallankumouksen ymmärtämisessä. Maaperän muokkaamisen ja sadonkorjuun käyttöönotto tarjoaa paradigmaesimerkin siitä, kuinka näennäisesti yksinkertainen muutos työn luonteessa voi radikaalisti muuttaa yhteiskunnan järjestystä. Asettamalla tämän menneisyyden vallankumouksen oikeaan kontekstiin, olet paljon paremmin varustettu ennustamaan, kuinka historia saattaa kehittyä reagoidessaan mikroprosessorien myötä esitettyyn uuteen väkivallan logiikkaan.

Jotta voit arvostaa maanviljelyn vallankumouksellisen luonteen merkitystä, tarvitset ensin kuvan siitä, miten alkukantainen yhteiskunta toimi ennen maanviljelyä. Olemme käsitelleet tätä teoksessa *The Great Reckoning* ja alla esittelemme lisäkuvauksen. Metsästys- ja keräilyyhteisöt olivat ainoita sosiaalisen järjestäytymisen muotoja pitkän esihistoriallisen ajan, jolloin ihmisen elämä muuttui vain vähän tai ei ollenkaan sukupolvesta toiseen. Antropologien mukaan ihmiset ovat olleet metsästäjiä ja keräilijöitä 99 prosenttia siitä ajasta, kun ilmestyimme maapallolle. Keskeistä metsästö- ja keräilyryhmien pitkälle jatkuneelle menestykselle – ja lopulta myös epäonnistumiselle – on se, että niiden täytyi toimia hyvin pienessä mittakaavassa hyvin laajalla alueella.

Keräilijät pystyivät selviytymään vain alueilla, joissa väestötiheys oli alhainen. Jos haluat ymmärtää miksi, ajattele mitä ongelmia suuremmat ryhmät olisivat aiheuttaneet. Esimerkiksi tuhansien metsästäjien marssi yhdessä maiseman halki olisi aiheuttanut niin suurta melua, että se olisi pelottanut sen riistan, jota he pyrkivät pyydystämään. Ja vielä pahempaa, jos pieni metsästäjäarmeija olisi joskus onnistunut kuljettamaan suuren lauman pihalle, silloin ruokaa – mukaan lukien villinä esiintyvät hedelmät ja syötävät kasvit – ei olisi voinut säilyä runsaina kauan. Suuri keräilyryhmä olisi pyyhkinyt maaseudun romuksi ylikorjuamisen seurauksena, aivan kuten nälissään oleva armeija Kolmekymmentä vuotta kestäneessä sodassa. Siksi metsästysryhmien täytyi olla pieniä, jotta ylikorjuus minimoituisi. Kuten Stephen Boyden kirjoittaa teoksessa *Western Civilization in Biological Perspective*:  
"Most commonly, hunter-gatherer groups number between twenty-five and fifty individuals."[^53]

Eläminen kymmenen tuhannen acren alueella lauhkeassa ilmastossa on nykyään ylellisyys, johon oikeuttaa vain erittäin varakkaat. Metsästäjä-keräilyperhe ei olisi todellakaan selvinnyt pienemmällä alueella. Yleisesti ottaen he tarvitsivat tuhansia acreja henkeä kohden, jopa alueilla, jotka olivat kaikkein hedelmällisimpiä keräilyyn. Tämä viittaa siihen, miksi ihmisväestön kasvu ajanjaksoina, jotka olivat erityisen suotuisia maanviljelylle, saattoi luoda perustan väestökriiseille. Koska yhden ihmisen tukemiseen tarvittiin niin paljon maata, metsästys- ja keräilyyhteisöjen väestötiheys oli uskomattoman alhainen. Ennen maanviljelyä ihmiset asettuivat tiheydeltään melkein samalla tavalla kuin karhut.

Pienin eroavuuksin ihmisten ruokavalio muistutti karhujen ruokavaliota. Keräilyyhteisöt nojautuivat ruoan saantiin avoimesta maaseudusta tai läheisiltä vesistöiltä. Vaikka osa keräilijöistä oli kalastajia, suurin osa oli metsästäjiä, jotka saivat noin kolmasosan–viidesosan ruokavaliostaan proteiinia suurista nisäkkäistä. Muutamien yksinkertaisten työkalujen ja esineiden lisäksi, joita he kuljettivat mukanaan, metsästäjä-keräilijöillä ei ollut käytössään juurikaan teknologiaa. Heillä ei yleensä ollut keinoja säilyttää tehokkaasti suuria määriä lihaa tai muuta ruokaa myöhempää käyttöä varten; suurin osa ruoasta piti kuluttaa pian sen keräämisen jälkeen tai se pilaantui. Tämä ei tietenkään tarkoita, että jotkut metsästäjä-keräilijät eivät olisi syöneet pilaantunutta ruokaa. Kuten Boyden raportoi, Eskimot "sanotaan pitävän erityisesti hajoavasta ruoasta."[^54] Hän toistaa asiantuntijoiden havainnot, joiden mukaan Eskimot "haudattavat kalojen päät ja antavat niiden mädäntyä, kunnes luiden koostumus muuttuu samanlaiseksi kuin lihan. Sitten he vaivaavat hajuavan massan tahnaksi ja syövät sitä"; he myös nauttivat "poron muutin perhosten rasvaisista toukista, joita tarjoillaan raakana… peurojen ulosteita, joita pureskellaan kuin marjoja … ja luuydintä, joka on yli vuoden ikäinen ja täynnä toukkia."[^55]

Muita herkkuja lukuun ottamatta keräilijät eivät kehittäneet juurikaan ylimääräistä ravintoa. Kuten antropologi Gregg huomauttaa, "liikkuvat väestöt eivät yleensä varastoi ruokaa sesonkien tai odottamattomien resurssipuutteiden varalle." Tämän seurauksena keräilijöillä ei ollut paljoa varastettavaa. Työjaon, johon kuului erikoistuminen väkivallan käyttöön, toteuttaminen oli kestämätöntä ympäristöissä, joissa ylijäämäruokaa ei voitu varastoida. Myös metsästyksen logiikka määrasi, että väkivalta metsästys- ja keräilyryhmien kesken ei voinut koskaan nousta suuremmaksi kuin pieni mittakaava, koska ryhmien itse tuli pysyä pienenä.

Keräilijäryhmien pieni mittakaava oli eduksi myös muulla tavalla. Pienen ryhmän jäsenet tunsivat toisensa hyvin, mikä teki yhteistyöstä heille tehokkaampaa. Päätöksenteko vaikeutuu jäsenten määrän kasvaessa, koska kannustekoukkuja esiintyy entistä enemmän. Riittää, että ajattelet, kuinka vaikeaa on saada järjestykseen vain noin kaksitoista ihmistä lähtemään ulos syömään. Kuvittele, kuinka toivottomaksi muodostuisi satojen tai tuhansien ihmisten järjestäminen liikkumaan yhdessä juhlan merkeissä. Ilman pysyvää ja erillistä poliittista järjestäytymistä tai sodan erikoistumisen vaatimaa byrokratiaa metsästys- ja keräilyryhmien oli tukeuduttava vaikuttamiseen ja yhteisymmärrykseen perustuviin periaatteisiin, jotka toimivat parhaiten pienissä ryhmissä, joissa asenteet olivat suhteellisen joustavia.

Se, olivatko metsästys- ja keräilyryhmät rentoja, on kysymys, josta voi kiistellä. Sir Henry Maine viittaa "alkukantaisen ihmisen yleiseen sotahenkisyyteen." Hänen sanojensa mukaan: "Luonnollista ja alkukantaista ei ole rauha, vaan sota."[^56] Hänen näkemyksensä on vahvistanut evoluutiobiologien tutkimus. R. Paul Shaw ja Yuwa Wong huomauttavat: "[T] vahvoja viitteitä on siitä, että monet Euroopan neljännen ja esineljänneksen jäätiköitymien aikaiset Australopithecus-, Homo erectus- ja Homo sapiens-jäännöksissä esiintyvät vammat ovat johtuneet taisteluista."[^57] Mutta toiset kyseenalaistavat tämän. Stephen Boydenin kaltaiset asiantuntijat väittävät, että primitiiviset ryhmät eivät yleensä olleet sodanhaluisia tai väkivaltaisia. Sosiaaliset tavat kehittyivät vähentämään sisäisiä jännitteitä ja helpottamaan metsästyksen tulosten jakamista. Erityisesti alueilla, joilla ihmiset saalistasivat suurempaa riistaa, jonka kaataminen yksittäisellä metsästäjällä oli vaikeaa, kehittyivät uskonnolliset ja sosiaaliset opetukset edistämään minkä tahansa saaliin uudelleenjaottelua koko ryhmän toimesta. Kaloriresurssien jaon ensisijainen prioriteetti oli metsästäjien kesken. Tarve, ei tunteet, toimi liikkeellepanevana voimana. Ensimmäisenä resurssien saatavan vaatimuksen käyttivät taloudellisesti taitavimmat ja sotilaallisesti vahvimmat, eivät sairaat ja heikot. Epäilemättä merkittävä tekijä tämän prioriteetin taustalla oli se, että parhaassa kunnossa olevat metsästäjät olivat myös sotilaallisesti pienryhmän tehokkaimpia jäseniä. Varmistamalla heille ensisijaisen oikeuden saaliiseen ryhmä vähensi mahdollisesti kuolemaan johtavia sisäisiä riitoja.

Niin kauan kuin väestötiheydet pysyivät alhaisina, keräilijöiden jumalat eivät olleet sotilaallisia jumalia, vaan luonnonvoimien tai saalistamiensa eläinten ilmentymiä. Pääoman niukkuus ja avoimet rajat tekivät sodasta useimmissa tapauksissa tarpeetonta. Oman pienen perheen tai klaanin ulkopuolella oli harvoin naapureita, jotka uhkaisivat. Koska keräilijät liikkuilivat ruoan etsimiseksi, henkilökohtaiset omaisuudet minimaalin lisäksi muodostivat rasitteen. Niillä, joilla oli vähän omaisuutta, oli luonteeltaan vähän omaisuusrikollisuutta. Kun ristiriitoja syntyi, osapuolet usein tyytyivät menemään pois, koska heillä ei ollut paljon panostettuna mihinkään tiettyyn paikkaan. Pako oli helppo ratkaisu henkilökohtaisiin riitoihin tai muihin kohtuuttomiin vaatimuksiin. Tämä ei tarkoita, että varhaiset ihmiset olisivat olleet rauhanomaisia. Ne saattoivat olla väkivaltaisia ja epämiellyttäviä siinä määrin, että harva voi edes kuvitella. Mutta jos he käyttivät väkivaltaa, se johtui pääosin henkilökohtaisista syistä tai, mikä voi olla vielä pahempaa, huvin vuoksi.

Metsästäjä-keräilijöiden elinkeinot perustuivat pienten ryhmien toimintaan, joissa työjakoa lähes ei ollut mahdollista muuta kuin sukupuolten mukaan. Heiltä puuttui järjestäytynyt hallinto, yleensä pysyvät asutukset, eikä mahdollisuuksia varallisuuden kerryttämiseen. Jopa näin perustavanlaatuisia sivilisaation rakennuspalikoita kuin kirjallinen kieli eivät olleet tunnettuja alku-era taloudessa. Ilman kirjallista kieltä ei voinut olla virallisia asiakirjoja eikä historiaa.

### Overkill

Keräily- ja metsästyselämän dynamiikka loi hyvin erilaiset työmotivaatioiden kannustimet kuin ne, joihin olemme tottuneet maanviljelyn alkamisesta lähtien. Keräilijän elämä edellytti minimaalisia pääomavaatimuksia. Muutama primitiivinen työkalu ja ase riittivät. Investointikanavaa ei ollut lainkaan, ei edes maan yksityisomaisuutta, paitsi satunnaisesti kivilouhoksissa, joissa kaivettiin pilkkoa tai saippualuotia.[^58] Kuten antropologi Susan Alling Gregg kirjoitti teoksessaan Foragers and Farmers: "Resurssien omistusoikeus ja niihin pääsy olivat ryhmän yhteisiä."[^59]

Harvoin, esimerkiksi järvenrannoilla asuvien kalastajien tapaan, keräilijöillä oli pysyvää asuinpaikkaa. Koska heidän kotejaan ei ollut pysyvästi, heidän ei tarvinnut tehdä kovasti töitä omaisuuden hankkimiseksi tai sen ylläpitämiseksi. Heillä ei ollut asuntolainaa tai maksettavia veroja, eikä heidän tarvinnut ostaa huonekaluja. Heidän muutamat kulutushyödykkeensä olivat eläinskinat ja ryhmän jäsenten itse valmistamat henkilökohtaiset koriste-esineet. Ei ollut juuri mitään kannustinta hankkia tai kerätä mitään, mikä olisi voinut toimia rahana, koska ostettavaa oli hyvin vähän. Tällaisissa olosuhteissa keräilijöiden säästöajatus saattoi olla vain karkeasti hahmoteltu käsite.

Koska ei ollut syytä ansaita ja lähes mitään työjakoa, kovan työn hyveenä pidetty käsite oli varmasti vieras metsästäjä-keräilyryhmille. Lukuun ottamatta poikkeuksellisia vaikeuksia, jolloin jatkuvaa ponnistelua tarvittiin ruoan löytämiseksi, työtä tehtiin hyvin vähän, koska sitä ei tarvinnut. Kirjaimellisesti mitään ei saavutettu tekemällä enemmän työtä kuin selviytymiseen välttämätöntä vähimmäismäärää. Tyypillisessä metsästäjä-keräilyryhmässä se tarkoitti noin kahdeksasta viisitoista tuntia viikossa.[^60] Koska metsästäjän työ ei lisännyt ruontarantoja vaan vain kulutti niitä, se, joka sankarillisesti tehosti työpanostaan surmata enemmän eläimiä tai kerätä enemmän hedelmiä kuin mitä ehtisi syödä ennen niiden pilaantumista, ei edistänyt vaurautta. Päinvastoin, liiallinen tappaminen (overkill) heikensi tulevien ruoan löytämisen mahdollisuuksia ja vaikutti siten negatiivisesti ryhmän hyvinvointiin. Siksi jotkut keräilijät, kuten eskimot, rankaisivat tai ulkona jättivät ryhmän jäseniä, jotka harjoittivat liiallista tappamista.

Eskimojen tapa rankaisua liiallisesta tappamisesta on erityisen puhelias, sillä he, paljon enemmän kuin muut, olisivat voineet säilöä lihaa pakastamalla. Lisäksi olisi ollut mahdollista järjestää ainakin jonkinlaista varastointia suurten merieläinten öljyjen erottamiseksi. Se, että keräilijät yleensä eivät tehneet näin, kuvastaa heidän paljon passiivisempia vuorovaikutuksiaan luonnon kanssa. Se saattaa myös kertoa siitä, kuinka kulttuuri vaikuttaa kognitioon ja mentaalisiin prosesseihin. Monimutkaisten ympäristöjen oppimista ja käyttäytymistä rajoittavat tekijät tekevät joidenkin strategioiden omaksumisesta huomattavasti vaikeampaa kuin miltä muuten vaikuttaisi. Kuten R. Paul Shaw ja Yuwa Wong ovat kirjoittaneet, "Koska ekologiset niitit eroavat monin tavoin, niin myös oppimisen harhat eroavat."[^61]

Tässä näkökulmassa maanviljelyn alku merkitsi muutakin kuin pelkkää ruokavalion muutosta; se käynnisti myös suuren vallankumouksen taloudellisen elämän ja kulttuurin organisoinnissa sekä väkivallan logiikan transformaation. Maanviljely loi suuria pääomatavoitteita maa-alueilla ja joskus myös kastelujärjestelmissä. Viljat ja kesytetyt eläimet, joita viljelijät kasvattivat, olivat arvokkaita omaisuuksia. Niitä voitiin säilyttää, varastoida ja varastaa. Koska viljaa piti hoitaa koko kasvukauden ajan, istutuksesta sadonkorjuuseen, muuttaminen pois uhkista kävi vähemmän houkuttelevaksi – erityisesti kuivilla alueilla, joissa viljelymahdollisuudet rajoittuivat pieneen maa-alueeseen, jolla oli luotettavat vesivarannot. Kun pakeneminen kävi vaikeammaksi, järjestettyjen ryöstöjen ja ryöstelyjen mahdollisuudet kasvoivat. Viljelijöihin kohdistuivat hyökkäykset sadonkorjuuaikana, mikä vähitellen nosti sodankäynnin mittakaavaa.

Tämä vaikutti siihen, että yhteisöjen koko kasvoi, sillä väkivaltaiset yhteenotot voitettiin useammin suuremman ryhmän toimesta. Kun maa-alueiden ja niiden tuoton hallinnasta käyty kilpailu kiristyi, yhteisöistä tuli pysyvämpiä. Työnjako tuli näkyvämmäksi. Työllisyys ja orjuus syntyivät ensimmäistä kertaa. Maanviljelijät ja karjankasvattajat erikoistuivat ruoan tuottamiseen. Keramiikkataiteilijat valmistivat astioita, joihin ruokaa säilytettiin. Papit rukoilivat sateita ja runsaita satoja. Väkivallan asiantuntijat, hallituksen esi-isät, omistautuivat yhä enemmän ryöstöön ja suojeluun ryöstöä vastaan. Papien kera heistä tuli historian ensimmäisiä varakkaita henkilöitä.

Maaseudun yhteisöjen varhaisvaiheissa nämä soturit alkoivat hallita osaa vuotuisen satojen määrästä suojelumaksuna. Paikoissa, joissa uhkia oli vain vähän, yrittäjämaanviljelijät pystyivät toisinaan säilyttämään suhteellisen suuren itsenäisyyden. Mutta kun väestötiheys kasvoi ja ruoan saatavuudesta käyty kilpailu kiristyi – erityisesti aavikoiden ympärillä, missä tuottava maa oli niukkaa – soturiryhmä pystyi ottamaan suuren osan kokonaisproduktiosta. Nämä soturit perustivat ensimmäiset valtiot näillä rahankorjuun tuotoilla, jotka saattoivat olla jopa 25 prosenttia viljasadosta ja puolet kotieläinkannan kasvusta. Maanviljely siis lisäsi dramaattisesti pakottamisen merkitystä. Ryöstettävissä olevien resurssien lisääntyminen johti huomattavaan ryöstön kasvuun.

Koko maatalousvallankumouksen logiikan toteutuminen vei vuosituhansia. Pitkään aikavälillä harvaan asutut viljelijäyhteisöt leutojen ilmastojen alueilla saattoivat elää niin kuin heidän metsästys-keräily-esivanhempansa olivat eläneet. Siellä, missä maa ja sade olivat runsaasti, maanviljelijät viljelivät satoa pienimuotoisesti ilman suurta väkivaltaista häiriötä. Mutta kun väestömäärät kasvoivat useiden tuhansien vuosien aikana, myös harvaan asutuilla alueilla viljelijät joutuivat satunnaisen ryöstön kohteiksi, mikä saattoi joskus jättää heille riittämättömän määrän siemeniä seuraavan sadon uudelleenviljelyyn. Kilpaileva ryöstö eli anarkia oli toinen ääripää, samoin kuin suojaamattomat yhteisöt, jotka elivät ilman erityistä järjestäytymistä, jolla monopolisoitaisiin väkivaltaa.

Ajan myötä maanviljelyn sisäinen väkivallan logiikka valtti itsensä yhä laajemmalle alueelle. Alueet, joilla viljelyä ja karjankasvatusta pystyttiin harjoittamaan ilman valtioiden ryöstöä, vetäytyivät muutamaksi aidosti syrjäiseksi alueeksi. Esimerkiksi Afganistanin Kafir-alueet kieltäytyivät hallinnon määräämisestä aina 1800-luvun viimeiseen vuosikymppiin saakka, mutta tätä tehdessään ne muuttuivat jo vuosisatoja aikaisemmin varsin sotilaalliseksi yhteiskunnaksi, joka oli järjestäytynyt sukulaisuussuhteiden pohjalta. Tällaiset järjestelyt eivät kyenneet kokoamaan laajamittaista voimaa. Siihen asti, kunnes britit toivat modernit aseet alueelle, Kafirit pysyivät itsenäisinä syrjäisissä Bashgalin ja Waigalin laaksoissa, sillä heidän linnoituksensa suojasi maaston piirteet, korkeat vuoret ja aavikot, jotka erottivat heidät ulkopuolisten valloittajien tieltä.[^62]

Ajan myötä maatalousvallankumouksen peruslogiikka vaikutti niihin yhteiskuntiin, joissa viljely vakiintui. Maanviljely kasvatti huomattavasti ihmisyhteisöjen muodostumisen laajuutta. Noin kymmenen tuhatta vuotta sitten alkoivat syntyä kaupunkeja. Vaikka ne olivat nykyisin hyvin pieniä, ne muodostivat ensimmäisten "sivilisaatioiden" keskuksia – sana on peräisin latinankielisestä civit, joka tarkoittaa "kansalaisuutta" tai "kaupungin asukkaita". Koska maanviljely loi varoja ryöstöä ja suojelua varten, se loi myös tarpeen varastonhallinnalle. Et voi verottaa, ellet pysty kokoamaan tietueita ja antamaan kuitteja. Kirjanpitäjän kirjanpidossa käytetyt symbolit muodostivat kirjoitetun kielen peruselementit, mikä oli innovaatio, jota metsästäjiltä ja keräilijöiltä ei ollut koskaan nähty.

Maatalous laajensi myös ajanjaksoa, jonka puitteissa ihmisten piti ratkaista ongelmia. Metsästäjäryhmät toimivat hyvin lyhyen aikahorisontin puitteissa – he harvoin ryhtyivät hankkeisiin, jotka kestäisivät yli muutaman päivän. Sen sijaan kasvin istuttaminen ja sadonkorjuu veivät kuukausia. Pitkän aikavälin hankkeiden toteuttaminen pakotti maanviljelijöitä suuntaamaan huomionsa tähtiin. Tarkat tähtitieteelliset havainnot olivat ennakkovaatimus almanakkojen ja kalentereiden laatimiselle, jotka toimivat oppaina parhaan ajoituksen määrittämiseksi istutukselle ja sadonkorjuulle. Maatalouden myötä metsästäjien toiminta-alueet laajenivat.

## Property

Siirtyminen pysyvään maatalousyhteiskuntaan johti yksityisomistuksen syntyyn. Ilmiselvää on, ettei kukaan olisi tyytyväinen siihen, että hän suorittaisi koko kasvukauden aherrusta saadakseen satoonsa, vain nähdäkseen jonkun muun ilmestyvän ja korjaavan sen, mitä hän itse oli tuottanut. Omistuksen käsite syntyi väistämättömänä seurauksena maataloudesta. Mutta yksityisomistuksen käsitteen selkeyttä heikensi myös maanviljelyn käyttöönoton mukanaan tuoma väkivallan logiikka. Omistuksen syntyä sekasi se, että yksilöiden megapoliittinen valta ei enää ollut yhtä tasa-arvoista kuin keräilyyhteisöissä, joissa jokainen terve aikuismies oli metsästäjä, yhtä hyvin aseistettuna kuin muutkin. Maatalous johti väkivallan erikoistumiseen. Juuri koska se loi jotain varastettavaa, maatalous teki paremmin aseistukseen investoimisesta kannattavaa. Tuloksena oli varkautta, suuri osa erittäin järjestäytynyttä.

Nyt vahvoilla oli mahdollisuus organisoida uusi saalistuksen muoto: väkivallan monopoli eli hallitus. Tämä erotti yhteiskunnat jyrkästi, luoden hyvin erilaiset olosuhteet niille, jotka hyötyivät ryöstöstä, sekä köyhälle väelle, joka aherrutti pelloilla. Harvat, jotka hallitsivat sotilaallista valtaa, pystyivät nyt rikastumaan, samoin kuin muut, jotka saivat heidän suosionsa. Jumalkuninkaat ja heidän liittolaisensa, eri pienemmät paikalliset mahtavat, jotka hallitsivat ensimmäisiä Lähi-idän valtioita, nauttivat huomattavasti modernimmista omaisuuden muodoista kuin suuri väki, joka aherrutti heidän alapuolellaan.

Tietenkin on anakronistista ajatella yksityisen ja julkisen omaisuuden eroa varhaisissa maatalousyhteiskunnissa. Hallitsevalla jumalkuninkaalla oli kaikki valtion resurssit käytössään tavalla, jota tuskin olisi mahdollista erottaa laajan tilan omistajuudesta. Juuri kuten Euroopan feodaalikaudella, kaiken omaisuuden hallinnassa oli ylempien voimavaltaisten toimijoiden ylivallan alaisena, ja hierarkian alempiin tasoihin kuuluvat omaisuudet olivat alttiina heikkenemiselle hallitsijan mielivallan mukaan.

Vain väittäminen, ettei voimansa haltija ollut lain rajoittama, ei tarkoita, että hän olisi voinut ottaa haltuunsa mitä tahansa. Kustannukset ja palkkiot vaikuttivat faaraon vapauteen yhtä paljon kuin ne vaikuttavat nykyään Kanadan pääministerin vapauteen. Lisäksi faaraota rajoittivat nykyjohtajiin nähden paljon kuljetus- ja viestintäongelmat. Pelkkä ryöstön siirtäminen paikasta toiseen – erityisesti kun ryöstön arvo mitattiin pääasiassa maataloustuotteina – johti runsaisiin menetyksiin pilaantumisen ja varkauksien vuoksi. Toistensa valvomiseen tarkoitettujen virkamiesten lisääntyminen vähensi varastamisesta johtuvia tappioita, mutta lisäsi samalla niitä kokonaiskustannuksia, jotka faaraon piti kantaa. Hajautettu valta, joka tietyissä tilanteissa optimoi tuotannon, synnytti myös vahvempia paikallisia valtakeskuksia, jotka toisinaan kasvoivat täysimittaisiksi dynastisen hallinnan haastajiksi. Jopa itämaiset despotit eivät olleet millään tavalla vapaita tekemään mitä he tahtoisivat, vaan heidän oli hyväksyttävä se, millainen raavan vallan tasapaino oli.

Vaikka kaikkia, myös rikkaita, kohdistettiin mielivaltaisesti riistaamalla, jotkut pystyivät kerryttämään omaa omaisuuttaan. Sitten kuten nytkin, valtio käytti suuren osan tuloistaan julkisiin hankkeisiin. Hankkeet, kuten kastelujärjestelmät, uskonnolliset monumentit ja kuninkaiden hautakammio, tarjosivat arkkitehdeille ja käsityöläisille mahdollisuuden ansaita elinkustannuksia. Jotkut hyvät asemaltaan olevat yksilöt pystyivät kerryttämään huomattavaa yksityisomaisuutta. Itse asiassa suuri osa Sumerista – varhaisesta Mesopotamian sivilisaatiosta – periytyvistä kiilakirjoista sisältää merkintöjä erilaisista kauppatoimista, joista suurin osa koskee omaisuusoikeuksien siirtoa.

Varhaisissa maatalousyhteiskunnissa oli yksityisomaisuutta, mutta sitä esiintyi harvoin sosiaalipyramidin alimmalla tasolla. Suurin osa väestöstä koostui talonpojista, jotka olivat liian köyhiä kerryttämään paljon varallisuutta. Itse asiassa, harvoja poikkeuksia lukuun ottamatta, suurin osa talonpojista aina nykyaikaan asti oli niin köyhiä, että he joutuivat jatkuvaan vaaraan nälkään joutua, aina kun kuivuus, tulva tai tuholaisten aiheuttama vahinko heikensi satoja. Tästä syystä talonpoikien oli järjestettävä asiansa siten, että huonojen vuosien riskejä minimoitiin. Laajassa ja köyhässä yhteiskunnan kerroksessa vallitsi primitiivisempi omaisuuden organisointi, joka lisäsi selviytymismahdollisuuksia hinnoitellen samalla suurinta osaa mahdollisuuksista kerryttää pääomaa ja nousta taloudellisessa järjestelmässä.

### Talonpoikavakuutus

Tämän järjestelyn muoto oli sellaisen, mitä antropologit ja yhteiskuntahistorioitsijat kuvaavat "suljetuksi kyläksi." Lähes jokaisessa esikehityksellisessä talonpoikayhteiskunnassa oli taloudellisen organisoinnin päämuotona "suljettu kylä." Toisin kuin nykyaikaisemmissa talousjärjestelmissä, joissa yksilöt yleensä käyvät kauppaa monien ostajien ja myyjien kanssa avoimilla markkinoilla, suljetun kylän kotitaloudet yhdistyivät toimimaan kuin epävirallinen osakeyhtiö tai suuri perhe – eivät avoimilla markkinapaikoilla, vaan suljetussa järjestelmässä, jossa kaikkien kylän taloudellisten tapahtumien keskimääräinen vastapuoli oli yksi monopolisti, paikallinen maanomistaja tai hänen kyläpäälliköidensä edustajat. Koko kylä solmi sopimuksen maanomistajan kanssa, yleensä maksuna luonnontuotteina, jolloin maksu perustui satoon, ei kiinteään vuokraan. Prosentuaalinen vuokra tarkoitti, että maanomistaja kantoi osan huonon sadon riskeistä. Tietenkin maanomistaja sai myös suurimman osan mahdollisesta voitosta. Lisäksi maanomistajat toimivat usein myös siemenlähteenä.

Tämä järjestely minimoikin nälänhätien vaaran. Se vaati, että maanomistajan – eikä talonpojan – tulisi säästää suhteettoman suuri osuus omasta osuudestaan sadosta. Koska maataloustuotokset olivat monilla alueilla aikaisemmin järkyttävän alhaiset, jokaista kolmea korjettua sadonosaa kohden piti kylvää jopa kaksi siementä. Tällaisissa olosuhteissa huono sato merkitsi massiivista nälänhätää. Talonpojat suosivat järkevästi järjestelyä, jossa maanomistajan velvoitettiin investoimaan heidän selviytymiseensä. Ostamalla monopolihinnoin, myymällä halvalla ja tarjoamalla maanomistajalle työtä vastikkeena talonpojat lisäsivät selviytymismahdollisuuksiaan.

Vastaava impulssi sai tyypillisen talonpojan suljetun kyläekonomian puitteissa luopumaan vapaan omistusoikeuden tarjoamasta turvasta. Asettamalla itsensä kylän vanhimmalle alttiiksi, talonpoikaperhe paransi mahdollisuuksiaan hyötyä säännöllisestä peltojen uudelleenjaosta. Ei harvoin vanhimi valitsi itselleen ja suosikeilleen parhaat pellot. Tämä oli kuitenkin riski, jonka talonpoikien täytyi sietää voidakseen nauttia siitä selviytymisen vakuutuksesta, mitä hämmentävä yhteinen peltojen omistajuus tarjosi. Aikoina, jolloin sato oli surkean heikko, sadan jaardin etäisyyden pellon kasvuolosuhteiden ero saattoi ratkaista, johtiikö nälänhätään vai selviytymiseen. Talonpojat valitsivat usein sellaisen järjestelyn, joka vähensi riskiä – vaikka se tarkoitti mahdollisuudesta lisävaurauden kasvun luopumista.

Yleisesti ottaen riskin välttämiseen suuntautunut käyttäytyminen on ollut tyypillistä kaikissa selviytymisen laidoilla toimivissa ryhmissä. Selviytymisen haasteet esiteollisissa yhteiskunnissa rajoittivat köyhien käyttäytymistä aina voimakkaasti. Mielenkiintoinen piirre tästä riskin välttämisestä, jota käsitellään teoksessa *The Great Reckoning*, on se, että se kavensi niiden rauhanomaisten taloudellisten toimintamallien kirjoa, joita yksilöille sosiaalisesti sallittiin. Tabut ja sosiaaliset rajoitteet rajoittivat kokeilunhalua ja innovatiivisuutta, vaikka tämä ilmeisesti maksoikin sen, että mahdollisesti edullisia parannuksia vakiintuneisiin toimintatapoihin jouduttiin uhraamaan.[^63] Tämä oli rationaalinen heijastus siitä tosiasiallisesta, että kokeilu lisää tulosten vaihtelua. Suurempi vaihtelu tarkoittaa paitsi potentiaalisesti suurempia voittoja myös, entistä uhkaavammalla tavalla selviytymisen laidoilla eläville, mahdollisesti tuhoisia tappioita. Suuri osa köyhien maatalousyhteisöjen kulttuurienergiasta on aina ollut omistettu kokeilujen tukahduttamiseen. Tämä tukahdutus toimi käytännössä heidän vakuutuksensa sijasta. Jos heillä olisi ollut vakuutuksia tai riittävästi säästöjä kokeilujensa itsensä vakuuttamiseen, tällaisia voimakkaita sosiaalisia tabuja ei olisi tarvittu selviytymisen varmistamiseksi.

Kulttuurit eivät ole makuasioita, vaan ne ovat sopeutumisjärjestelmiä tiettyihin olosuhteisiin, jotka saattavat osoittautua merkityksettömiksi tai jopa vastavaikutteisiksi muissa ympäristöissä. Ihmiset elävät monenlaisissa elinympäristöissä. Asuinpaikkamme potentiaalisten niukkien mahdollisuuksien lukumäärä edellyttää käyttäytymismallien vaihtelua, jotka ovat liian monimutkaisia instinktien ohjaamiksi. Siksi käyttäytyminen ohjelmoituu kulttuurisesti. Monien maatalousyhteisöjen valtavalle enemmistölle kulttuuri ohjelmoi heidät selviytymään – mutta vain selviytymään – sellaisessa ympäristössä, jossa ylellisyytenä avoimilla markkinoilla toimimiseen osallistuminen oli varattu muille.

Yksilöllinen kyky ja henkilökohtainen valinta – modernin ajatuksen mukainen "onnellisuuden tavoittelu" – alistettiin tabujen ja sosiaalisten rajoitusten vuoksi, jotka ovat aina olleet kaikkein korostavimpia köyhien keskuudessa. Tällaiset rajoitukset syrjäytettiin vain suurin vaikeuksin yhteiskunnissa, joissa tuottavuus oli rajallinen. Kun ja missä maataloustuottavuus oli korkeampaa, kuten muinaisessa Kreikassa, tapahtui pieniä mega- poliittisia vallankumouksia. Omaisuus otti nykyaikaisempia muotoja. "Allod", eli vapaa omistusoikeus, syntyi. Maa vuokrattiin yleensä kiinteällä palkkiolla, ja vuokralainen kantoi taloudellisen riskin sekä suuremman osuuden voitosta, jos sato oli hyvä. Korkeammat säästöt mahdollistivat riskialttiimpaa käyttäytymistä itsensä vakuuttamiseksi. Tällaisissa olosuhteissa itsenäiset viljelijät pystyivät nousemaan talonpoikaisuuden yläpuolelle ja joskus jopa kartuttamaan itsenäistä varallisuutta.

Markkinamaisempien omaisuusoikeuksien ja suhteiden kehittymisen taipumus talouksien hierarkian ylimpien puolien läheisyydessä tai harvinaisissa tapauksissa koko talouden laajuisesti, kun yhteiskunnat nousivat köyhyydestä, on tärkeä piirre yhteiskuntajärjestyksessä. On yhtä tärkeää huomata, että maatalousyhteiskuntien yleisin järjestys historiallisesti oli pohjimmiltaan feodaalinen, jossa markkinasuhteet olivat ylimpänä ja suljettu kyläjärjestelmä alimpana. Suuri osa talonpojista oli sidottu maahan lähes kaikissa esiteollisissa maatalousyhteiskunnissa. Niin kauan kun maataloustuottavuus pysyi alhaisena tai korkeampi tuottavuus oli riippuvainen pääsystä keskitettyihin vesivoimajärjestelmiin, yksittäisten viljelijöiden vapaus ja omaisuusoikeudet alimmalla tasolla pysyivät minimaalisina. Tällaisissa olosuhteissa feodaaliset omaisuusmuodot vallitsivat. Maa oli hallussa käyttösopimuksella pikemminkin kuin vapaalla omistusoikeudella. Tavallisesti myynti-, lahjoitus- ja perimisoikeuksia rajoitettiin.

Feodalismi eri muodoissaan ei ollut ainoastaan vastaus jatkuvasti läsnä oleviin saalistavaa väkivaltaa vastaan kohdistuviin riskeihin. Se oli myös reaktio järkyttävän alhaisiin tuottavuuslukuihin. Näitä kahta ilmiötä on usein havaittu kulkevan käsi kädessä maatalousyhteisöissä, jolloin ne usein vaikuttivat toisiinsa. Kun julkinen auktoriteetti romahti, myös omaisuusoikeudet ja vauraus vähenivät vastaavasti. Tuottavuuden lasku taas heikensi myös auktoriteettia. Vaikka kaikki kuivuudet tai epäedulliset ilmasto-olosuhteet eivät johtaneet julkisen vallan hajoamiseen, monet niistä tekivät niin.

## Feodaalisen vallankumouksen vuosi 1000

Niin kävi vuoden 1000 muutoksessa, joka laukaisi feodaalisen vallankumouksen.[^64] Tuolloin megapoliittiset ja taloudelliset olosuhteet erosivat merkittävästi niistä, joita nykyään pidämme keskiaikojen tunnusmerkkeinä. Rooman romahdusta seuraavien ensimmäisten vuosisatojen aikana Länsi-Euroopan talous kuihtui. Ne saksalaiset kuningaskunnat, jotka juurtuivat entisen Rooman valtakunnan alueille, olivat ottaneet vastaan monia Rooman valtion toimintoja, mutta paljon vähemmällä kunnianhimolla. Infrastruktuuria ei juuri ylläpidetty, ja vuosisatojen myötä sillat ja vesiautomaatiot rappeutuivat ja tulivat käyttökelvottomiksi. Roomalaisia kolikoita käytettiin vielä jonkin verran, mutta ne lähes katoivat liikkeestä. Maanmarkkinat, jotka Rooman aikana kukoistivat, kuivuttuivat käytännössä, ja kaupungit, jotka olivat olleet Rooman hallinnon keskuksia, hävisivät lähes yhtä lailla kuin valtion verotusvalta. Samoin lähes kaikki muut sivilisaatiota kuvaavat välineet katoivat.

"Pimeät ajat" saivat nimensä hyvistä syistä. Lukutaito tuli niin harvaksi, että kuka tahansa, jolla oli kyky lukea ja kirjoittaa, saattoi odottaa saavansa rikoksista – jopa murhasta – vapautuksen syytteistä. Taide-, tiede- ja tekniikkataidot, jotka olivat kehittyneet kovalla tasolla Rooman aikana, katosivat. Tienrakennuksesta viinirypäleiden ja hedelmäpuiden variaatioiden parantamiseen Länsi-Eurooppa lakkasi käyttämästä monia aikoinaan hyvin tunnettuja ja korkeatasoisesti harjoitettuja menetelmiä. Jopa niin muinainen laite kuin savenpyörä hävisi monilla alueilla. Kaivostoiminta supistui, metallurgia väheni ja Välimeren kastelujärjestelmiä rappeutuivat laiminlyönnin seurauksena.[^65] Kuten historioitsija Georges Duby totesi, "kuudennen vuosisadan lopussa Eurooppa oli syvästi sivistymätön paikka."[^66] Vaikka noin vuonna 800 Charlemagne’n hallinnon aikana tapahtui lyhyt keskitetyn auktoriteetin renessanssi, kaikki alkoi pian jälleen hajaantua hänen kuolemansa jälkeen.

Yllättävänä seurauksena tälle karulle maisemalle oli se, että Rooman valtion romahtaminen todennäköisesti nosti pienten maanviljelijöiden elintasoa useiden vuosisatojen ajan. Ne saksalaiset kuningaskunnat, jotka hallitsivat Länsi-Eurooppaa pimeiden aikojen aikana, sisällyttivät joitakin suhteellisen huoletonta sosiaalisia piirteitä, jotka olivat tyypillisiä heidän esi-heimoilleen – esimerkiksi vapaan maanomistajan juridinen tasa-arvo. Tämän seurauksena pimeiden aikojen pienet maanviljelijät olivat huomattavasti vapaampia kuin feodaalisten vuosisatojen aikana, mikä viittaa myös siihen, että he olivat vauraampia. Kuten aiemmin analysoimme omaisuusmuotojen logiikkaa eri tuottavuustasojen oloissa, vapaaomaisuus on historiallisesti kulkenut käsi kädessä pienten maanviljelijöiden suhteellisen vaurauden kanssa. Suljetun kylän ja feodaaliset omaisuusmuodot puolestaan syntyivät siellä, missä pienten maanviljelijöiden mahdollisuudet elää olivat epävarmempia.

Totisesti, pimeiden aikojen lähes täydellinen kaupankäynnin romahtaminen maksutti pientalouksia kaupan eduista ja laajempien markkinoiden tarjoamista hyödyistä. Kaupunkien katoaminen horjensi käteis-taloutta, mutta merkitsi myös sitä, että maaseudun väestöä ei enää tarvittu tukemaan byrokratian murskaavaa taakkaa. Kuten Guy Bois on kirjoittanut, roomalainen kaupunki oli loiseläimellinen yhteisö, ei tuotannon keskus: "Rooman aikana kaupungin hallitseva funktio oli poliittinen. Se sai elämänsä ensisijaisesti ympäröiviltä alueilta tulevista tuloista, joita maanveron kautta kerättiin … Kaupunki käytännössä tuotti vähän tai ei lainkaan ympäröivän maaseudun hyödyksi." [^67] Roomalaisen vallan romahtaminen vapautti suurelta osin maaseudun maanviljelijät veroista, jotka olivat imeneet pois "yksi neljäsosa–yksi kolmasosa maan bruttotuotannosta, lukuun ottamatta pienten ja keskisuurten maaomistajien kärsimiä erilaisia veronkorotuksia." [^68] Verot olivat niin kohtuuttomia, että niitä saatettiin joskus panna täytäntöön teloituksin, minkä seurauksena omistajien omaisuudesta luopuminen oli yleistä. Barbarit antoivat näiden verojen erääntyä armollisesti.

### Agri Deserti

Hallinnon taakat vähenivät niin merkittävästi barbarien valtaukset myötä, että köyhille avautui mahdollisuus hankkia ja säilyttää omistusoikeuteen perustuvaa omaisuutta. Osa agri deserti—tai hylättyjä maatiloja, joita omistajat olivat jättäneet pakoon saalistavaa verotusta Rooman valtakunnan loppuvuosina—tuotiin takaisin tuotantoon. Huolimatta tuon ajan karuista olosuhteista ja siitä tosiasiallisesta, että satojen tuottavuus oli nykytasoon verrattuna naurettavan alhainen, pimeät ajat olivat Euroopan pienviljelijöille suhteellisen vaurauden aikaa. Itse asiassa he olivat vahvemmassa asemassa kuin he koskaan uudelleen olisivat modernin ajan asti. Yhtäältä hedelmällistä maata viljeltävien käsien määrä oli vähentynyt, sillä suuret alueet olivat joutuneet lopettamaan viljelynsä. Mölyt, sodat ja omistajien pakeneminen romahtaneen Rooman valtakunnan vuoksi olivat merkittävästi vähentäneet aiemmin viljellyillä alueilla asuvaa väestöä. Toinen etu, josta pienviljelijät pimeinä aikoina hyötyivät, syntyi kuudennella vuosisadalla otetusta uudesta maatalousteknologiasta: raskaasta kyntöraudasta, joka usein oli varustettu pyörillä. Yhdessä parannetun talituksen kanssa, joka mahdollisti useiden härkien samanaikaisen käytön, uusi teknologia helpotti huomattavasti pohjois-Euroopan metsien raivaamista.

Tällaisissa olosuhteissa maamarkkinat supistuivat melkein häviämisen äärelle. Uutta viljelysmaata sai pelkästään raivaamalla sitä ja jakamalla osa kustakin uudesta tontista asianmukaisten paikallisten viranomaisten kanssa. Tätä prosessia, jota kutsutaan assartingiksi, käytettiin mukavana kanavana väestönkasvun tyydyttämiseksi vuosisatojen ajan Rooman romahduksen jälkeen. Assarting tuli erityisen houkuttelevaksi harvaanasutetuilla pohjoisilla alueilla, kun kahdeksannella vuosisadalla lämpimämmät lämpötilat tekivät maataloudesta tuottavampaa.

Germanikansojen heimojen johtajat, jotka valloittivat entiset roomalaiset alueet, olivat vakiinnuttaneet asemansa suurina maaomistajina. Suurin osa muusta väestöstä viljeli pieniä tontteja – mutta hyvin erilaisissa olosuhteissa kuin myöhemmin feodaalijärjestelmässä. Varakkaammat maaomistajat, eli herrat, edustivat noin 7–10 prosenttia väestöstä. Näyttää siltä, että ennen vuotta 1000 noin kaksi kolmasosaa ranskan tyypillisestä kylästä oli vapaanomistajia.[^70] He omistivat noin puolet kaikesta viljellystä maasta.[^71] Orjia oli vähän. Coloni, eli vuokratilayrittäjät, muodostivat enintään 5 prosenttia väestöstä. Orjuus jatkui, mutta paljon pienemmässä mittakaavassa kuin roomalaisina aikoina.

Rooman jatkajamaat, germaaniset valtakunnat, puolustettiin sotilaallisesti kaikkien vapaan kansan miesten toimesta, jotka kokoontuivat kantamaan aseita kuninkaan paikallisen edustajan, kreivin, kutsusta. Jopa “pieniltä ja keskikokoisilta omistajilta” odotettiin, että he yhdistäisivät voimansa ja lähettäisivät yhden jäsenestään taistelemaan jalkaväen riveissä.[^72]

Pitresin asetuksessa Charles the Bald määräsi kaikkia, joilla oli varaa siihen, kokoontumaan ratsain taisteluun. Paavi Gregory II oli yrittänyt edistää tätä sotilaallista velvoitetta vuosisataa aiemmin kieltämällä hevosenlihan syömisen vuonna 732.[^73] Mutta vapaan maanomistajien jalkaväen ja ratsuväen välillä ei vielä ollut juurikaan eroa niin statuksen kuin lainkaan. Kaikki vapaat miehet osallistuivat paikallisiin oikeudellisiin kokouksiin ja saattoivat tehdä anomuksia riitatilanteiden ratkaisemiseksi kreiville, viralle, joka oli ollut olemassa myöhäisroomalaisilta ajoilta lähtien. Aatelistoa sellaisenaan ei ollut.

> “Yhteiskunnallinen ilmiö, uusi massailmiö, ilmestyi yhtäkkiä horisonttiin 980-luvulla: laskeva sosiaalinen liikkuvuus. Sen ensimmäisiksi uhreiksi joutuivat pienet allod-haltijat.” [^74]  
> – Guy Bois

Kuitenkin keskiaikojen pimeyden edetessä tapahtui useita asioita, jotka horjuttivat niitä suhteita, jotka olivat säilyttäneet tiloistaan omistautuneiden maanviljelijöiden ja vapaan maanomistajien itsenäisyyden germaanisissa valtakunnissa, jotka perivät vallan Rooman romahduksen jälkeen:

1. Väestö vähitellen palautui, mikä lisäsi paineita maan käytölle. Useiden vuosisatojen aikana suuri osa niistä kaikkein hedelmällisimmistä, vailla omistajaa olevista maista otettiin tuotantoon, erityisesti Pohjois-Euroopassa tapahtuneen kasvun myötä. Maanviljelijöiden kasvava määrä suhteessa maan tarjontaan vaikutti siihen, että jokaisen maanviljelijän työvoiman arvo laski. Suurin osa vapaan omistusoikeudesta murentuivat yhä pienemmiksi osiksi perinnön seurauksena. Keskiaikojen pimeyden aikana lapset jakoivat yleensä tasapuolisesti vanhempiensa perintöjä. Omistusten sirpaloituminen väestönkasvun aikana nosti maan jälleen arvon korkealle ja johti aktiivisten maa-alueiden markkinoiden uusiutumiseen kymmenesvuosisadan puolivälissä.

2. Kymmenvuosisadan viimeisinä vuosikymmeninä lämpötilat laskivat äkillisesti, mikä vaikutti tuhoisasti maatilojen sadonkorjuuseen. Kolme peräkkäistä kasvin epäonnistumista johtivat vakavaan nälänhätätilanteeseen vuosina 982–984. Nälänhätä iski uudelleen toisen kasvin epäonnistumisen jälkeen vuonna 994.[^75] Sitten vuonna 997 ongelmaa heikentyneistä satoista pahensi epidemia, joka iski erityisen voimakkaasti pieniin perhetiloihin, sillä pienviljelijöiltä puuttui resursseja korvata menettämiensä perheenjäsenten tuottama työvoima. Nämä rynnäkkäät sadon epäonnistumiset ja katastrofit saivat aluksi yeoman-tyyppiset maanviljelijät ajautumaan velkaongelmiin. Kun sadot eivät palautuneet, he eivät pystyneet maksamaan asuntolainojaan.

3. Valtasuhteet rappeutuivat vähitellen raskaiden ratsuväen kasvavan merkityksen myötä. Keskiaikaissotahistorioitsija Frances Gies kuvaa panssaroidun ratsuväen muuttumista keskiaikaiseksi ritariksi:

> Alun perin keskivertasemastaan ylhäällä maalaisten joukosta, kalliilla hevosellaan ja panssarillaan kohotettu ritari paransi asemaansa yhteiskunnassa vähitellen, kunnes hänestä tuli osa aatelistoa. Vaikka ritareita pidettiin ylhäältä luokan vähimpänä, ritaruus sai ainutlaatuisen arvostuksen, joka teki ritariksi vihkimisestä kunnian, jota suuret aateliset ja jopa kuninkaalliset arvostivat. Tämä arvokkuus oli ensisijaisesti kirkon poliittinen tulos, jolla pyhitettiin ritaruuden vihkimisseremonia ja tuettiin käytöskoodia, jota kutsutaan ritarilliseksi käytökseksi – koodia, jota ehkä rikottiin useammin kuin kunnioitettiin, mutta joka vaikutti kiistattomasti jälkivaikutteena jälkimaailman ajatteluun ja toimintaan.[^76]

Kuten kerroimme teoksessa *The Great Reckoning*, satulanruskojen keksiminen antoi aseistetulle ratsastajaritarille valtavan hyökkäyskyvyn. Hän pystyi nyt hyökkäämään täydessä vauhdissa ilman, että keihäänsä iskun vaikutuksesta satulastaan heitettäisiin.

Raskaiden ratsuväen sotilaallinen arvoa vahvisti entisestään aasialainen keksintö, joka levisi Länsi-Eurooppaan 900-luvulla; nauloitettu rautainen hevosenkenkä. Tämä paransi entisestään hevosen kestävyyttä tiellä.[^77]

Aseistetun ritarin tehoa paransi myös muotoiltu satula, joka helpotti raskaiden aseiden käsittelyä, virveli sekä kurbibiitti, jonka avulla ratsastaja pystyi hallitsemaan hevosta yhdellä kädellä taistelun aikana.[^78]

Yhdessä nämä näennäisesti vähäpätöiset teknologiset innovaatiot heikensivät dramaattisesti pienviljelijöiden sotilaallista merkitystä, sillä heillä ei ollut varaa ylläpitää sotakoreja eikä aseistautua.

Sotaa varten erityisesti jalostetuista hevosista edullisin, suuret ratsut, joita kutsutaan destriereiksi, olivat arvoltaan neljän härän tai neljäkymmentä lampaan verran. Kalliimmat sotahesot maksivat kymmenen härää tai sata lammasta.

Panssari maksoi myös summan, johon mikään pienviljelijä ei voinut varaa, mikä vastasi kuudenkymmentä lampaan hintaa.[^79]

4. Se, että kylmempi sää, satojen epäonnistumiset, nälänhädät ja rutot osuivat luvun 1000 lähestyessä, vaikutti myös ihmisten käyttäytymiseen. Monet olivat vakuuttuneita siitä, että maailmanloppu tai Toiseksi tulemisen hetki oli käsillä. Hartaat tai pelästyneet maanomistajat, isot ja pienet, lahjoittivat maansa kirkolle valmistautuakseen apokalyptisiin tapahtumiin.

### "Vain köyhä mies myy maata"

Epävakaat olosuhteet 900-luvun lopulla raivasivat tien feodaaliseen vallankumoukseen. Peräkkäiset epäonnistuneet sadot ja katastrofit saivat itsenäiset talonpojat uppoamaan velkaan. Kun satoa ei enää palautunut, maanomistajat joutuivat epätoivoiseen tilanteeseen. Markkinat kohdistavat aina suurimmat paineet heikoimmille haltijoille – itse asiassa se on osa niiden hyveellisyyttä. Ne parantavat tehokkuutta siirtämällä varat pois heikosta hallinnasta. Mutta 900-luvun lopun Euroopassa omavarainen maatalous oli käytännössä ainoa elinkeino. Perheet, jotka menettivät maansa, menettivät ainoan keinojaan selviytyä. Kohtaessaan tämän epämiellyttävän näkymän monet tai useimmat vapaiden maanomistajien päättivät luovuttaa pelloistaan feodaalisen vallankumouksen aikana. Guy Bois sanoi: "The only sure way for a peasant to hold on to the land he tilled was to concede ownership of it to the Church, so he could retain its usufruct."[^80] Toiset sen sijaan siirsivät osan tai kaiken maastaan varakkaammille maanomistajille, joihin he luottivat – joko ystävällisiin naapureihin tai sukulaisiin.

Nämä omaisuuden siirrot tehtiin ehdolla, että viljelijä, hänen perheensä ja jälkeläisensä pysyisivät työskentelemään pelloilla. Köyhät viljelijät saivat myös nauttia vahvempien haltijoiden, nyt "aatelisten", vastavuoroisesta tuesta, jotka pystyivät varustautumaan hevosilla ja panssareilla tarjotakseen suojaa laajentuneille tiloille. Tällaista diiliä voidaan nähdä uuden orjan näkökulmasta välivaiheena jatkuvan taloudellisen omistuksen ja ulosoton välillä. Useimmiten se oli diili, josta ei voinut kieltäytyä.

Lajitun tuotannon lasku ei ainoastaan asettanut köyhiä viljelijöitä epätoivoiseen taloudelliseen pulaan, vaan se myös käynnisti saalistavaa väkivaltaa, joka heikensi omaisuuden turvaa. Ne, joilla ei ollut resursseja riistää osaa saatavilla olevasta ja riittämättömästä hevos- ja rehuvarannosta, huomasivat äkki, että he ja heidän omaisuutensa eivät enää olleet turvassa. Nykykielellä sanottuna se olisi kuin joutuisit aseistamaan itsesi uudella aseella, mutta sen hinnaksi tulisi 100 000 dollaria. Jos et pystyisi maksamaan tuota hintaa, olisit niiden armoilla, jotka sen pystyvät maksamaan.

Muutamassa vuodessa kuninkaan ja tuomioistuinten kyky ylläpitää järjestystä romahti.[^81] Kuka tahansa, jolla oli panssarit ja hevonen, pystyi nyt toimimaan oman lakinsa auktoriteettina. Tuloksena oli 900-luvun lopun Blade Runner -version kaltainen tilanne, jossa väkivaltaiset taistelut ja ryöstely levittäytyivät, eikä viranomaisilla ollut voimia pysäyttää sitä. Aseistettujen ritarien ryöstelyt ja hyökkäykset häiritsivät maaseutua. Ei kuitenkaan ole mitenkään itsestään selvää, että kaikki tämän ryöstelyn uhrit olivat köyhiä. Päinvastoin, vanhimmat, fyysisesti heikommat tai huonosti varautuneet suurempien maanomistajien joukossa muodostivat houkuttelevampia kohteita, sillä heillä oli enemmän varastettavaa.

Ei ollut sattumaa, että tämä tapahtui juuri silloin, kun kylmempi sää, nälänhätä ja rutto kiristivät resurssien saatavuutta. Valtavallalliset olosuhteet, jotka suotasivat auktoriteetin murenemista, olivat vallinneet jo jonkin aikaa. Niiden kyky muuttaa yhteiskunnan valtasuhteita ei kuitenkaan toteutunut ennen kuin kriisi laukeili. Sadon epäonnistumiset ja nälänhädät näyttävät olevan juuri ne kriisit, jotka laukaisivat muutoksen. Vaikka tapahtumien tarkkaa järjestystä on vaikea rekonstruoida, vaikuttaa siltä, että ryöstelylle oli ainakin osittain innoittajakseen epätoivoiset olosuhteet. Kun väkivalta kerran irti päästiin, kävi ilmi, ettei kukaan pystynyt mobilisoimaan voimia estääkseen sitä. Erittäin vähäisesti aseistettujen viljelijöiden suurin osa pystyi todellisuudessa tekemään vain vähän. Jopa kymmenet jaloilla kulkevat viljelijät olisivat jääneet helposti yksittäisen hevonvarustetun ritarin varjoon. Vapaiden maanomistajien, kuten myös viranomaisten – kuninkaiden ja heidän kreivinsä – voimattomuus estää paikallisen maan joutumasta aseistettujen sotilaiden haltuun oli ilmeistä.

### "Jumalan rauha"

Näissä epätoivoisissa oloissa kirkko auttoi käynnistämään feodalismia pyrkimyksillään neuvotella tulitauosta väkivaltaisella maaseudulla. Historiantutkija Guy Bois kuvailee tilannetta näin: "Poliittisten viranomaisten voimattomuus oli sellaista, että kirkko otti heidän sijalleen yrittäessään palauttaa järjestystä liikkeessä, joka tunnetaan nimellä 'Jumalan rauha'. 'Rauhanneuvostot' julistivat sarjan kieltoja, joita tuomitsivat anatemailla; laajat 'rauhan kokoukset' vastaanottivat sotureiden valat. Liike sai alkunsa Ranskan Midistä (Charrouxin neuvosto vuonna 989, Narbonnen neuvosto vuonna 990) ja levisi vähitellen..." [^82]

Kirkon tekemä sopimus sisälsi aseistettujen ritareiden herruusaseman tunnustamisen paikallisissa yhteisöissä vastineeksi väkivallan ja ryöstelyn loppumisesta tai lieventämisestä. Myöhään 10. vuosisadalla tapahtuneen väkivallan purskahduksen jälkeen maaoikeuksiin kaiverrettiin äkillisesti titteli "nobilis" tai "miles" osoituksena herruudesta. Feodaalisen vallankumouksen myötä erillisen aateliston synty tapahtui; vain muutamaa vuotta aiempaan kiinteistökauppaan samojen henkilöiden kanssa ei ollut mainittu minkäänlaista erottelua.[^83]

Matalan tuottavuuden ja pienviljelijöiden taloudellisen epävarmuuden valossa aseistettujen ritareiden megapoliittinen voima johti väistämättä omaisuuden hallintaan feodaalisen kiinteistönomistuksen kautta. Yhdentoista vuosisadan ensimmäisen neljänneksen loppuun mennessä itsenäiset viljelijät olivat suurelta osin kadonneet. Heidän vapaat omistuksensa olivat kutistuneet vain murto-osaan aiemmasta laajuudestaan ja niitä viljeltiin nyt vain osa-aikaisesti. Pienviljelijät tai heidän jälkeläisensä olivat orjia, jotka viettivät suurimman osan ajastaan työskentelemällä feodaalisten herrojen, sekä siviili- että kirkollisten, tiloilla.

Feodaalisen vallankumouksen mukana irronnut järjestys johti käytösmallien muutoksiin, jotka vahvistivat feodalismia. Näihin kuului muun muassa linnoitusten rakentamisen kiihtyminen. Linnoitukset ilmestyivät alun perin Luoteis-Eurooppaan alkeellisina puurisrakenteina viikinkirintamien seurauksena 9. vuosisadalla. Alun perin karolingilaisten viranomaisten komentokeskuksina toimineet linnoitukset muuttuivat feodaalisen vallankumouksen myötä perinnöllisiksi omaisuuksiksi. Nämä varhaiset tukikohdat olivat paljon alkeellisempia kuin myöhemmät versiot, mutta ne olivat silti haastavia hyökätä. Rakennetuiksi saatuja linnoituksia tuhottiin vain valtavalla vaivalla, ja niiden alkaminen ilmestyä maaseudulle teki yhä epätodennäköisemmäksi sen, että kuningas tai hänen kreivinsä pystyisivät tehokkaasti haastamaan herrojen paikallisen ylivallan.

### Kirkkon panos tuottavuuteen

Feodalismi oli maatalousyhteiskunnan vastaus järjestyksen romahtamiseen alhaisella tuottavuudella. Feodaalijärjestelmän varhaisvaiheissa Kirkko näytti tärkeän ja taloudellisesti tuottavan roolin. Kirkon panoksiin kuuluivat muun muassa seuraavat seikat:

1. Sellaisessa ympäristössä, jossa sotilaallinen valta oli hajautettua, Kirkko oli ainutlaatuisessa asemassa ylläpitää rauhaa ja kehittää järjestyssääntöjä, jotka ylittivät hajanaiset, paikalliset suvereniteetit. Tämä on tehtävä, jonka kannalta mikään maallinen valta ei ollut kyvykäs toimimaan. Suuren uskonnollisen auktoriteetin A. R. Radcliffe-Brown havaintoja on tässä yhteydessä hyvä muistaa. Hän huomautti, että "uskonnon sosiaalinen tehtävä on riippumaton sen totuudesta tai epätotuudesta." Jopa ne uskonnot, jotka ovat "absurdeja ja vastenmielisiä, kuten joidenkin villien heimojen uskomukset, saattavat olla tärkeitä ja vaikuttavia osia sosiaalisessa koneistossa."[^84] Tämä pätevöi ehdottomasti Kirkon osalta feodaalijärjestelmän varhaisessa vaiheessa. Kirkko auttoi luomaan sääntöjä – kuten vain uskonto kykenisi – jotka mahdollistivat ihmisten ylittää kannustimien loukkuja ja käyttäytymisongelmia. Jotkut näistä ongelmista olivat yleisiä moraalisia dilemoja, jotka koskivat kaikkea ihmiselämää, mutta toiset olivat paikallisia dilemmoja, ainutlaatuisia vallitsevien megapoliittisten olosuhteiden kannalta. Keskiaikaisella Kirkolla oli erityinen rooli palautettaessa järjestystä maaseudulle 900-luvun loppupuolella. Tarjoamalla uskonnollista ja seremoniallista tukea paikallisille viranomaisille kirkko vähensi väkivallan aiheuttamien, edes heikkojen paikallisten monopolien perustamiskustannuksia. Näin Kirkko vaikutti olosuhteisiin, jotka lopulta johtivat vakaampiin valtarakenteisiin.

Kirkko jatkoi pitkään rooliaan hillitsemässä yksityisten sotien ja väkivallan liiallisuuksia, joita siviilivallan ei muuten pystynyt rajoittamaan. Kirkon suhteellinen merkitys verrattuna maallisiin viranomaisiin näkyi siinä, että yhdestoista vuosisadalla useimmassa Länsi-Euroopassa vallan pääasiallisena hallinnollisena yksikkönä muodostui seurakunta – toisin kuin vanhat siviilivallan jakoalueet, ager ja pagus (kaupunki), jotka olivat säilyneet Rooman ajoista pimeille ajoille.[^85]

2. Kirkko oli tärkein lähde teknisen tiedon ja informaation säilyttämiselle ja välittämiselle. Se rahoitti yliopistoja ja tarjosi keskiaikaiselle yhteiskunnalle vähimmäiskoulutuksen. Kirkko tarjosi myös mekanismin kirjojen ja käsikirjoitusten kopioimiseen, mukaan lukien lähes kaikki nykyajan tiedot maataloudesta ja karjankasvatuksesta. Benediktimaalaisluostareiden scriptoriat voidaan ymmärtää vaihtoehtoisena teknologiana painokoneille, joita ei vielä ollut olemassa. Vaikka scriptoriat olivat kalliita ja tehottomia, ne olivat käytännössä ainoa mekanismi kirjallisen tiedon kopioimiseen ja säilyttämiseen feodaalisen jakson aikana.

3. Osittain siksi, että tilanhoitajansa osasivat lukea ja kirjoittaa, kirkko teki valtavasti parantaakseen eurooppalaisen maanviljelyn tuottavuutta, erityisesti feodalismikauden alkuvaiheissa. Ennen kolmatta vuosisataa maallisten herrojen tilanhoitajat olivat lähes kaikki analfabetteja, jotka pitivät kirjaa käyttämällä monimutkaista merkkijärjestelmää. Vaikka he saattoivat olla nokkelia viljelijöitä, he eivät olleet missään asemassa hyötymään tuotantomenetelmien parannuksista, joita he eivät itse keksineet tai nähneet omin silmin. Kirkko oli siten olennaisen tärkeä parannettaessa viljan, hedelmien ja jalostuseläinten laatua. Laajojen omistustensa vuoksi, jotka ulottuivat koko Euroopan mantereelle, kirkko pystyi lähettämään kaikkein tuottavimmat siemenet ja jalostuseläimet niille alueille, joilla tuotanto jäi jälkeen. Pohjois-Euroopassa sakramenttimaisen viinin kysynnän vuoksi munkit alkoivat kokeilla kestävämpiä rypälelajikkeita, jotka selviytyisivät kylmemmissä ilmastoissa. Kirkko auttoi myös nostamaan keskiaikaisen maanviljelyn tuottavuutta muilla tavoin. Monet taloudellisesti liian pieniksi todetut tilat, jotka lahjoitettiin kirkolle feodaalisen vallankumouksen aikana, uudelleenjärjesteltiin niin, että niistä tuli entistä viljelykelpoisempia. Kirkko tarjosi lisäksi pienille maanviljelysyhteisöille tarvittavia lisäpalveluja; monilla alueilla kirkon omistamat myllyt jauhosivat viljaa jauhoseksi.

4. Kirkko hoiti monia tehtäviä, jotka nykyään kuuluuvat valtion vastuulle, mukaan lukien julkisen infrastruktuurin tarjoaminen. Tämä on osa sitä, miten kirkko auttoi ratkaisemaan taloustieteilijöiden kutsumia "julkisten hyödykkeiden dilemmoja" aikana, jolloin valta oli hajanaista. Varhaiskeskiajan kirkon tietyt uskonnolliset järjestöt omistautuivat käytännön insinööritehtäville, kuten teiden avaamiselle, romahtaneiden siltojen uudelleenrakentamiselle ja rappeutuneiden roomalaisten vesijohtojen korjaamiselle. He raivasivat myös maata, rakensivat patoja ja kuivaisivat soita. Uusi luostarijärjestö, kartusiaanit, kaivoi ensimmäisen "artesaanisen" kaivon Artoiksen alueella Ranskassa. Iskusonittelutekniikalla he kaivoivat pienen reiän, joka oli tarpeeksi syvä ilman, että se tarvitsi pumppua.[^86] Siterikaanien järjestö sitoutui rakentamaan ja ylläpitämään epävarmoja merilinnoitteita ja patoja Euroopan Alamaissa. Maanviljelijät luovuttivat maata siterikaanien luostareille ja vuokrasivat sen sen jälkeen takaisin, samalla kun munkit ottivat täyden vastuun hoidosta ja korjauksista. Siterikaanit johtivat myös vesivoimakoneiden kehittämistä, joita alettiin hyödyntää laajasti esimerkiksi "lyömiseen, nostamiseen, jauhamiseen ja puristamiseen".[^87] Clairvaux-luostari kaivoi kahden mailin mittaisen kanavan Auben joesta.[^88] Kirkko puuttui myös rakentamalla uusia teitä ja siltoja silloin, kun asutuskeskukset olivat siirtyneet vanhojen roomalaisten vartioasemateiden ulkopuolelle. Piispat myönsivät antemuksia paikallisille herroille, jotka rakentaisivat tai korjaisivat joen ylityspaikkoja ja ylläpitäisivät matkaajille tarkoitettuja turvapaikkoja. Pyhän Benezetin perustama järjestö, Freres Pontifes eli "Sillan veljet", rakensi useita aikansa pisimpiä siltoja, mukaan lukien Pont d'Avignonin, massiivisen kaksikymmentäkaaren rakenteen Rhonetta vasten, jossa toisessa päässä yhdistyi kappeli ja tienpalkki. Jopa London Bridge, joka seisoi 1800-luvulle asti, rakennettiin kaplain toimesta ja sen rahoitti osittain papin legaatan 1 000 markin panoksella.[^89]

5. Kirkko auttoi myös kehittämään monimutkaisempaa markkinaa. Esimerkiksi tuomiokirkkojen rakentaminen eroaa luonteeltaan julkisesta infrastruktuurista, kuten siltojen ja vesijohtojen rakentamisesta. Periaatteessa kirkon rakennuksia käytettiin vain uskonnollisiin seremonioihin, ei liikenteen reitteinä kaupankäynnille. Kuitenkin ei pidä unohtaa, että kirkkojen ja tuomiokirkkojen rakentaminen auttoi luomaan ja syventämään markkinoita monille käsityöläis- ja insinööritaidolle. Samalla tavalla kuin kansallisvaltion sotilasmenot kylmän sodan aikana tahattomasti auttoivat inkuboimaan internetiä, niin keskiaikaisten tuomiokirkkojen rakentaminen johti muihin spin-off-yrityksiin eli kaupankäynnin inkubaatioon. Kirkko oli merkittävä rakennusalan ja käsityöläisten asiakas. Kirkon ostamat hopeaesineet sakramenttipalveluihin, kynttilänjalat sekä kirkkojen koristeluun tarkoitetut taideteokset auttoivat luomaan markkinan ylellisyystavaroille, joita muuten ei olisi syntynyt.

Monin tavoin kirkko auttoi hillitsemään aseellisten ritarien aiheuttaman väkivallan raivokkuutta feodaalisen vallankumouksen aikana ja sen jälkeen. Erityisesti feodalismikauden varhaisina vuosisatoina kirkko vaikutti merkittävästi maanviljelysekonomian tuottavuuden parantamiseen. Se oli olennainen instituutio, joka vastasi maatalousyhteiskunnan tarpeisiin pimeän ajan loppuvaiheessa.

### Haavoittuvuus väkivallalle

"In 'kolmekymmentä tai neljäkymmentä vuotta väkivaltaisia häiriöitä – vuoden 1000 feodaalinen vallankumous,' [^90] aivan kuten Romin romahtaminen viisi vuosisataa aiemmin, oli ainutlaatuinen tapahtuma, jonka taustalla vaikutti monimutkainen tekijöiden vuorovaikutus. Toisaalta mali ham ines (wicked men) -voiton ja heidän aiheuttamansa sortotoimien kautta nähdään täydellisesti maatalousyhteiskunnan kultainen heikkous väkivallalle. Verrattuna ihmisen elämän keräilyvaiheeseen maanviljely toi mukanaan kvanttihypyn järjestäytyneessä väkivallassa ja sortamisessa.

Varhaisimmista ajoista alkaen tämä ilmeni maatalousyhteisöjen sotilaallisesti suuntautuneissa kulttuureissa. Varhaisten maatalousyhteiskuntien jumalat olivat sateen ja tulvien jumalia, joiden tehtävät heijastivat näiden yhteisöjen huolia satojen määrää määräävistä tekijöistä. Sateen tai veden lähettäjä oli usein myös sodan jumala, johon ensimmäiset kuninkaat – ennen kaikkea sotapäälliköt – turvautuivat.[^91]

Maanviljelyn ja sodankäynnin tiivis yhteys näkyi niiden ihmisten uskonnollisessa mielikuvituksessa, joiden elämä muuttui maatalousvallankumouksen innovaatioiden myötä. Eedenin puutarhasta karkottaminen voidaan nähdä kuvaannollisena kertomuksena yhteiskunnan muutoksesta keräilyelämästä maanviljelyyn – vapaasta elämästä, jossa ruokaa kerättiin luonnon antimia vain vähällä työllä, kohti kovaa työelämää.

## Paradise lost

Maanviljely asetti ihmiskunnan aivan uudelle kurssille. Ensimmäiset maanviljelijät kylvivät todellisuudessa sivilisaation siemenet. Heidän ahkeruudestaan syntyi kaupunkeja, armeijoita, aritmetiikkaa, tähtitiedettä, vankiloita, viiniä ja viskiä, kirjallinen sana, kuninkaita, orjuutta ja sotaa. Siitä huolimatta, kaikesta siitä draamasta, mitä maanviljely lisäsi elämään, muutos alkuperäisestä talousjärjestelmästä näyttää olleen hyvin epäsuosittu jo sen varhaisimmista päivistä lähtien. Todisteena tästä on Genesis-kirjassa säilynyt kertomus, joka kertoo paratiisista karkottamisesta.

Raamatullinen vertaus Eedenin puutarhasta on lämpimän muiston herättämä kuva siitä, millaista helppoutta keräilijä nautti erämaassa. Tutkijat viittaavat siihen, että sana "Eden" vaikuttaa olevan peräisin sumerilaisesta sanasta, joka tarkoittaa "erämaata."[^92]

Vapaan ja harvoin asutun luonnossa elämän muuttuminen maanviljelykylän paikallaan pysyväksi elämäksi oli syvästä katumuksesta – asia, josta ilmeni paitsi Raamatussa, myös ihmiskunnan jatkuvassa vastenmielisyydessä nousta aamulla ja mennä töihin. Kuten Stephen Boyden kirjoitti teoksessaan Western Civilization in Biological Perspective, maatalouden mukanaan tuoma uusi elämäntapa oli "evodeviant."[^93] Ennen maanviljelyn aikaa tuhannet ihmispolvet elivät kuten Aatami Eedenissä, Luojansa kutsumana: "Puutarhan jokaisesta puusta voit syödä vapaasti." Metsästäjillä ja keräilijöillä ei ollut hoidettavia viljelyskasveja, ei karjaa valvottavana, eikä veroja maksettavana. Niin kuin kulkureissa, keräilijät ajelehtivat minne halusivat, tekivät vähän töitä eivätkä vastanneet kenellekään.

Maanviljelyn myötä alkoi uusi elämäntapa, ja se tuli aivan paljon painavampina realiteetteina. "Myös piikit ja tikkurit tuottavat sinulle; ja sinä tulet syömään kentän yrttejä; kasvojesi hikipisaroissa sinun on syötävä leipää." Maanviljely oli raskasta työtä. Maanviljelyn aikaisesta elämästä jäi muisto kadotetusta paratiisista.

Enemmän kuin he olisivat voineet kuvitella, maanviljelijät loivat uusia olosuhteita, jotka muuttuivat väkivallan logiikan radikaalisti. Ei ole sattumaa, että Ensimmäinen Mooseksen kirja kuvaa Kainia, ensimmäistä murhaajaa, "maanviljelijänä." Todellakin, on osa Raamatun kummallista profeetallista voimaa, että sen tarina annettiin paimenille, jotka ymmärsivät vaivatta, miten maanviljely antoi väkivallalle vipuvoimaa. Muutamalla jakeella Raamatun kertomus tiivistää logiikan, jonka toteutuminen kesti tuhansia vuosia. Maanviljely toimi erimielisyyksien kehtona. Se loi paikallaan pysyvää pääomaa laajassa mittakaavassa, nosti väkivallan tuottoa ja kasvatti dramaattisesti omaisuuden suojaamisen haastetta. Maanviljely teki ensimmäistä kertaa sekä rikollisuudesta että hallituksen maksukykyisistä ehdotuksista mahdollisia.

[^93]: Boyden, op. cit., p.4.
[^52]: Gregg, op. ciL, xv.

[^53]: Boyden, op. cit., s. 62.

[^54]: Ibid., s. 67.

[^55]: Ibid.

[^56]: Siteerattu teoksesta E. J. P Veale, *Advance to Barbarism: The Development of Total Warfore* (New York: Devin-Adair, 1968), s. 37.

[^57]: R. Paul Shaw ja Yuwa Wong, *Genetic Seeds of Warfare: Evolution, Nationalism and Patriotism* (Boston: Unwin Hyman, 1989), s. 4.

[^58]: Katso Carleton S. Coon, The Hunting Peoples (New York: Nick Lyons Books, 1971), s.275.

[^59]: Gregg, op. cit., s.23.

[^60]: Boyden, op. cit., s. 69.

[^61]: Shaw ja Wong, op. cit., s. 69

[^62]: Lisätietoja kafireista on: Schuyler Jones, Men of Influence in Nuristan (London: Seminar Press, 1974).

[^63]: Katso Samuel L. Popkin, *The Rational Peasant* (Berkeley: University of California Press 1979), s. 13.

[^64]: Katso Bois, op. cit

[^65]: Katso Frances and Joseph Gies, Cathedral, Forge, and Waterwheel: Technology and Invention in the Middle Ages (New York: HarperCollins, 1994), s. 40.

[^66]: Lainattuna ibid., s. 42.

[^67]: Katso Bois, op. cit., s. 78.

[^68]: Ibid., s. 118.

[^69]: Gies, op. cit., s. 45.

[^70]: Bois, op. cit., s. 116.

[^71]: Ibid., s. 26.

[^72]: Ibid, s. 64.

[^73]: Gies, op. cit., s. 47.

[^74]: Bois, op. cit., s. 52.

[^75]: Ibid., s. 150

[^76]: Gies, op. cit., s. 2.

[^77]: Ibid., s. 46.

[^78]: Ibid., s.56–57.

[^79]: Ibid., s.58.

[^80]: Bois, op. cit., s.87.

[^81]: Ibid. Vaikka feodaalisen vallankumouksen tarkkaa tapahtumajärjestystä on vaikea rekonstruoida lähteiden vähäisyyden vuoksi, Guy Boisin esittämän teesin laaja luonnos vaikuttaa meille todennäköisesti oikealta. Se ei ole vain itsessään uskottava, vaan se selittää muuten poikkeavia tosiasioita ja sopii hyvin teorioihimme.

[^82]: Ibid., s.136.

[^83]: Ibid., s. 57 ja passim.

[^84]: A. R. Radcliffe-Brown, Religion and Society, teoksessa Structure and Function in Primitive Society (London: Cohen & West, 1952), s. 153–77.

[^85]: Bois, op. cit., s. 36.

[^86]: Gies, op. cit., s. 112.

[^87]: Ibid., s. 114.

[^88]: Sama teos, s. 117.

[^89]: Yksityiskohdat siltojen ja infrastruktuurin osalta ovat pääasiassa samasta teoksesta, s. 148–154.

[^90]: Bois, op. cit., s. 136.

[^91]: Katso Norman Cohn, Cosmos, Chaos, and the World to Come: The Ancient Roots of the Apocalyptic Faith (New Haven: Yale University Press, 1993), luvut I–3, erityisesti s. 60.

[^92]: Bruce Ni. Metzger ja Michael D. Coogan, toim., The Oxford Companion to the Bible (Oxford: Oxford University Press, 1993), s. 178.

[^93]: Boyden, op. ciL, s. 118.