# TIETOAIKAKAUDEN MEGAPOLITIIKKA

::: {.content-hidden when-format=latex}
*Tehokkuuden voitto valtaa vastaan*
:::

> "...kyse on tietokoneistetusta informaatiosta, ei työvoimasta tai massatuotannosta, joka yhä enemmän ohjaa Yhdysvaltain taloutta ja joka tulee voittamaan sodat maailmassa, jossa on 500 TV-kanavaa. Tietokoneistettu informaatio on olemassa kybertilassa – uutena ulottuvuutena, jonka ovat synnyttäneet loputtoman tietokoneverkkojen, satelliittien, modeemien, tietokantojen ja julkisen internetin monistumiset."[^187]  
– NEIL MUNRO

30. joulukuuta 1936 autoteollisuuden työntekijät, jotka vaativat korkeampia palkkoja, saivat väkisin haltuunsa kaksi General Motorsin päätehdasta Flintissä, Michiganissa. He pysäyttivät koneet, katkaisivat kokoonpanolinjat ja asettuivat mukavasti paikoilleen. Tehtailla työskentelevät työntekijät, jotka oli palkattu ylläpitämään tuotantoprosessia, istahtivat alas vastakkain teollisuuskonfliktissa, joka kestäisi useita viikkoja. Tilannetta leimasivat väkivaltaiset mellakat sekä poliisin, Michiganin militsian ja kaikkien hallinnon tasojen poliitikkojen vaihtelevat lojaalisuudet. Huomatessaan, ettei heidän vaatimuksiinsa edetä, ammattiliitto iski jälleen 1. helmikuuta 1937.

Ammattiliiton vaikuttajat valloittivat väkisin GM:n Chevrolet-tehtaan Flintissä. Valloittamalla ja sulkemalla General Motorsin keskeiset tehtaat työntekijät käytännössä lamaannuttivat yhtiön tuotantokyvyn. Kolmannen tehtaan haltuunoton jälkeisinä kymmenen päivän aikana GM valmisti Yhdysvalloissa vain 153 autoa.

Palataan tähän 60 vuotta sitten julkaistuun uutispilakkaan, jotta nykyiset megapoliittiset olosuhteet, joissa vallankumous on parhaillaan käynnissä, saataisiin asetettua selkeämpään kontekstiin. GM:n työpaikkalakko, jossa työntekijät istuivat paikoillaan, tapahtui joidenkin tämän kirjan lukijoiden elinaikana. Uskomme kuitenkin, että istuma-lakot tulevat Informaatiokaudella osoittautumaan anakronistisiksi – yhtä kuin orjat, jotka hankaloivat aavikon halki jättimäisillä kivillä rakentaakseen hautapyramideja faaraoille.

Vaikka ammattiliitot ja niiden pelottelutaktiikat muuttuivat teollisuusajassakin niin vakiintuneiksi, ettei niiden olemassaoloa enää kyseenalaisteta, ne perustuivat erityisiin megapoliittisiin olosuhteisiin, jotka nyt nopeasti katoavat. Informaatiotietä pitkin ei tule olemaan Chevroletteja eikä UAW:ta, joka lakkoaisi.

Hallitusten kohtalot seuraavat niiden vastineita – ammattiliittoja – kohti laskua. Institutionaalinen pakottaminen, joka näytti ratkaisevan roolin 1900-luvun yhteiskunnassa, ei ole enää mahdollinen. Teknologia nopeuttaa syvällistä muutosta kiristykseen ja suojeluun liittyvässä logiikassa.

> "... ei ole omaisuutta, ei hallintaa, ei erillistä sinun ja minun; vaan ainoastaan se, mitä jokainen voi saada, ja niin kauan kuin hän sen voi pitää."  
> – Thomas Hobbes

### Kiristys ja Suojelu

Koko historian ajan väkivalta on toiminut talouden ytimeen kohdistettuna puukkona. Kuten Thomas Schelling terävästi totesi, "kyky satuttaa – tuhota asioita, joita joku arvostaa, aiheuttaa kipua ja surua – on eräänlaista neuvotteluvoimaa, jota ei ole helppo käyttää, mutta jota käytetään usein. Alamaailmassa se on perusta kiristykselle, kiristystoimille ja sieppauksille; kaupallisessa maailmassa se mahdollistaa boikotteja, lakkoja ja sulkuja. Se toimii usein kurinpitosysteeminä, sekä siviili- että sotilasympäristössä, ja jumalat käyttävät sitä vaatiakseen kurinpitoa."

Hallituksen kyky verottaa itseään perustuu samoihin haavoittuvuuksiin kuin yksityisten toimijoiden kiristystoimet. Vaikka emme yleensä ajattele asiaa näillä termeillä, se osuus omaisuudesta, jota kontrolloidaan ja käytetään pakottavalla tavalla rikollisuuden ja hallinnon kautta, antaa karkean mitta-arvon megapoliittisesta tasapainosta kiristysten ja suojelun välillä. Jos teknologia tekisi omaisuuserien suojaamisesta hankalaa, rikollisuus leviäisi, ja samoin laajentuisi ammattiliittojen toiminta. Tällaisissa tilanteissa hallituksen tarjoama suojelu saisi lisäpainoarvoa, ja verot nousisivat. Missä taas verot ovat alhaiset ja työpaikkapalkat määräytyvät markkinavoimien, eikä poliittisen interventiön tai pakottamisen kautta, teknologia on kallistanut tasapainon suojelun puolelle.

Teknologinen epätasapaino kiristyksen ja suojelun välillä saavutti ääripään 1900-luvun kolmannen neljänneksen lopulla. Joissakin kehittyneissä länsimaissa hallitukset saivat haltuunsa jopa yli enemmistön resursseista. Suuren osan väestön tuloista määräytyi joko viranomaismääräysten mukaisesti tai pakkokeinojen, kuten lakkojen ja erilaisten väkivallan uhkien, vaikutuksesta. Hyvinvointivaltio ja ammattiliitot olivat molemmat teknologian tuotoksia, jotka jakoivat saaliit siitä, että valta voitti tehokkuuden 1900-luvulla. Ne eivät olisi voineet olla olemassa ilman niitä sotilaallisia ja siviiliteknologioita, jotka teollisuusaikana nostivat väkivallan tuottoja.

Oman varallisuuden luomiskyky on aina tuonut mukanaan alttiuden kiristykselle. Mitä enemmän varallisuutta on luotu tai hallussasi, sitä korkeampi hinta sen maksamisesta on jollakin tavalla. Joko maksat kaikista niistä, jotka saivat valtaa käyttää väkivaltaa kiristyksen välineenä, tai maksat sotilaallisesta voimasta, joka kykenee kumoamaan minkä tahansa raakan kiristysyrityksen.

> "Väkivaltaa ei enää kuuluta maassasi, ei tuhoa eikä tuhoa rajoillasi..." - ISAIAH 60:1

### Suojelun matematiikka

Nyt väkivallan tikari saattoi pian tylsyä. Tietotekniikka lupaa muuttaa dramaattisesti suojelun ja kiristyksen välistä tasapainoa, tehden varallisuuden suojelemisesta monissa tapauksissa huomattavasti helpompaa ja kiristyksestä vaikeampaa. Information Age:n teknologia mahdollistaa varallisuuden luomisen, jotka ovat monenlaisten pakkokeinojen ulottumattomissa. Tämä uusi epäsymmetria suojelun ja kiristyksen välillä perustuu matematiikan perus totuuteen: kertominen on helpompaa kuin jakaminen. Vaikka tämä totuus onkin itsestäänselvä, sen pitkälle ulottuvat seuraukset jäivät piiloon ennen mikroprosessoreiden aikakautta. Suoranopeudet tietokoneet ovat mahdollistaneet viime vuosikymmenen aikana miljardeja kertoja enemmän laskutoimituksia kuin koko aiempi maailman historia. Tämä laskentatehon harppaus on antanut meille ensimmäistä kertaa mahdollisuuden ymmärtää osia kompleksisuuden universaaleista ominaisuuksista. Tietokoneet osoittavat, että monimutkaisia järjestelmiä voidaan rakentaa ja ymmärtää vain alhaalta ylöspäin. Alkuperäisten alkulukujen kertominen on yksinkertaista, mutta monimutkaisuuden purkaminen yrittämällä hajottaa suurien alkulukujen tuloa niiden yksinkertaisiksi osatekijöiksi on käytännössä mahdotonta. Wired-lehden päätoimittaja Kevin Kelly kiteyttää asian: "Useiden alkulukujen kertominen suuremmaksi tuloksi on helppoa; jokainen alakouluopiskelija voi tehdä sen. Mutta maailman supertietokoneet tökevät yrittäessään purkaa tuloksen sen yksinkertaisiksi alkuluvuiksi."[^190]

### Kompleksisten järjestelmien logiikka

Kybertalous muotoutuu väistämättä tämän syvän matemaattisen totuuden mukaisesti. Se ilmenee jo selvästi tehokkaissa salausalgoritmeissa. Kuten myöhemmin tässä luvussa käsitellään, nämä algoritmit mahdollistavat uuden, suojatun kybertaloudellisen maailman, jossa väkivallan keinojen hyödyntäminen vähenee huomattavasti. Kiristämisen ja suojelun välinen tasapaino kallistuu dramaattisesti suojelun puolelle. Tämä edistää sellaisen talouden syntyä, joka nojautuu enemmän spontaanien sopeutumismekanismien voimaan ja vähemmän tietoiseen päätöksentekoon sekä byrokraattiseen resurssien jakamiseen. Uusi järjestelmä, jossa suojelu on etusijalla, tulee olemaan hyvin erilainen kuin teollisaikana vallitseva pakottamisen järjestelmä.

### Komentojärjestelmät ovat primitiivisiä

Kirjoitimme teoksessa *The Great Reckoning*, että tietokone mahdollistaa sen, että voimme "nähdä" aiemmin näkymättömän monimutkaisuuden, joka on olemassa monissa järjestelmissä.[^243] Kehittynyt laskentateho ei ainoastaan auta meitä ymmärtämään kompleksisten järjestelmien dynamiikkaa paremmin, vaan se mahdollistaa myös näiden monimutkaisuuksien hyödyntämisen tuottavilla tavoilla. Tavallaan kyseessä ei ole valinta, vaan väistämättömyys, jos talous halutaan viedä eteenpäin jäykän keskusjohtamisen vaiheesta. Sellainen järjestelmä, joka riippuu lineaarisista suhteista, on pohjimmiltaan primitiivinen. Hallituksen resurssien kohdistaminen siirtää väistämättä arvokkaita resursseja korkeaarvoisesta, monimutkaisesta käytöstä primitiivisempään käyttöön. Tämä prosessi on rajoitettu sillä samalla matemaattisella epäsymmetrialla, joka estää suurten alkulukujen tulon kokonaan purkautumasta. Saaliin jakaminen voi olla vain primitiivistä.

### Kaikki monimutkaistuu

Missä tahansa katsotkin universumissa, näet järjestelmiä, jotka kehittyessään saavuttavat yhä monimutkaisempia muotoja. Tämä pätee tähtitieteessä. Se pätee myös lätäkössä: jätä sadevesi paikalleen matalalle alueelle, niin se monimutkaistuu. Kaikenlaiset edistyneet järjestelmät ovat monimutkaisia, sopeutuvia järjestelmiä ilman keskitettyä johdonmukaisuutta. Kaikki luonnon monimutkaiset systeemit – joista markkinatalous on ilmeisin sosiaalinen ilmentymä – nojaavat hajautettuihin kykyihin. Järjestelmät, jotka toimivat tehokkaimmin laajalla olosuhdealueella, saavat elinvoimaisuutensa spontaanista järjestyksestä, joka mahdollistaa uusien mahdollisuuksien hyödyntämisen. Itse elämä on tällainen monimutkainen järjestelmä. Miljardit potentiaalisia geenien yhdistelmää tuottavat yhden ihmisen yksilön, ja niiden järjestäminen olisi hämmästyttävää millä tahansa byrokratialla.

Kaksikymmentäviisi vuotta sitten tätä olisi voinut ainoastaan aistia; tänä päivänä se on demonstratiivisesti nähtävissä. Mitä lähemmäs tietokoneet vievät meitä ymmärtämään keinotekoisen elämän matematiikkaa, sitä paremmin ymmärrämme myös todellisen elämän, eli biologisen monimutkaisuuden, matematiikkaa. Näitä monimutkaisuuden salaisuuksia, joita hyödynnetään tietotekniikan avulla, sovelletaan talouksien uudelleenjärjestämiseen yhä monimutkaisemmiksi muodoiksi. Internet ja World Wide Web ovat jo antaneet periksi orgaanisen järjestelmän piirteille, kuten Kevin Kelly ehdottaa teoksessaan *Out of Control: The New Biology of Machines, Social Systems, and the Economic World* [^191]: hänen mukaansa luonto on "idean tehdas. Elintärkeät, postteolliset paradigmat ovat piilossa jokaisessa viidakon muurahaispesässä... Biologian massasiirto koneisiin pitäisi täyttää meidät kunnioituksella. Kun syntyneen ja valmistetun yhdistyminen on täydellistä, tuotoksissamme opitaan, mukaututaan, parannetaan itseämme ja kehittyminen on väistämätöntä. Tämä on voima, josta emme ole juuri unelmoineetkaan." [^192]

Biologian massasiirron vaikutukset koneisiin ovat todellakin laaja-alaiset. Sosiaalisissa järjestelmissä on aina ollut vahva taipumus jäljitellä vallitsevaa teknologiaa – tämä oli tarkasti se, missä Marx osasi. Jättiläismäiset tehtaat osuttuivat isojen valtioiden aikakauteen, ja mikroprosessointi on nykyään pienentänyt instituutioita. Jos analyysimme pitää paikkansa, informaatiokauden teknologia luo lopulta talouden, joka osaa hyödyntää monimutkaisuuden etuja paremmin.

Makropolitiikan ulottuvuuksia tällaisessa muutoksessa ymmärretään kuitenkin erittäin vähän, ja jopa ne, jotka ovat tunnistaneet sen matemaattisen merkityksen, ovat tehneet sen anakronistisella tavalla. On yksinkertaisesti vaikeaa täysin sisäistää, että seuraavien vuosien teknologinen muutos vanhentaa suurimman osan modernin maailman poliittisista muodoista ja käsityksistä. Esimerkiksi myöhäinen fyysikko Heinz Pagels kirjoitti laajaa näkemyksellisessä teoksessaan *The Dreams of Reason*: "Olen vakuuttunut siitä, että ne kansakunnat ja kansat, jotka hallitsevat uuden monimutkaisuustieteen, tulevat tulemaan seuraavan vuosisadan taloudellisiksi, kulttuurisiksi ja poliittisiksi supervalloiksi." [^193] Vaikuttava ennuste on, mutta uskomme sen olevan väärä – ei siksi, että se olisi virheellinen, vaan juuri siksi, että se osoittautuu vieläkin oikeammaksi kuin tohtori Pagels uskalsi ilmaista. Yhteiskunnat, jotka uudelleenjärjestäytyvät kehittyäkseen monimutkaisemmiksi sopeutuviksi järjestelmiksi, menestyvät todellakin. Mutta kun ne menestyvät, ne eivät todennäköisesti muutu kansakunniksi – saati sitten poliittisiksi supervalloiksi. Todennäköisimmät välittömät hyötyjät lisääntyneestä sosiaalisten järjestelmien monimutkaisuudesta ovat uuden vuosituhannen itsenäiset yksilöt.

Pagelsin ennuste, vertailtuna, on kuin viidensadan sukupolven metsästysryhmän shamaani, joka kertoo miehilleen nuotion ympärillä: "Olen vakuuttunut siitä, että ensimmäinen kastettu metsästysryhmä, joka hallitsee uuden kastelun tieteen, saa enemmän vapaata aikaa tarinankerrontaan kuin edes ne kaverit järvellä, jotka pyydystävät suuria kaloja." Vaikka hän oli oikeassa monimutkaisuuden merkityksestä, Pagels unohti kaikkein perustavanlaatuisimman asian: kun väkivallan logiikka muuttuu, yhteiskunta muuttuu.

## Väkivallan logiikka

Selittääksemme kuinka ja miksi, meidän on keskityttävä useisiin megapolitiikan puoliin, joita harvoin tuodaan esiin. Nämä ovat asioita, joita historioitsija Frederic C. Lane tarkasteli – hänen työnsä väkivallan ja sodan taloudellisesta merkityksestä on käsitelty muualla tässä teoksessa. Kun Lane kirjoitti tämän vuosisadan puolivälissä, Information Societya ei ollut missään näkyvissä. Tällaisissa olosuhteissa hän saattoi olettaa, että kilpailu väkivallan käyttöön maailmassa oli saavuttanut huippunsa kansallisvaltion syntymisen myötä. Hänen teoksissaan ei esiinny viitteitä siitä, että hän olisi ennakoinut mikrokäsittelyä tai uskonut, että fyysisesti olemattomalla kybertasolla voisi teknologisesti olla mahdollista luoda omaisuuseriä. Lane ei kommentoinut sitä, että suuria määriä kaupankäyntiä voitaisiin käytännössä tehdä lähes immuuneina väkivallan vipuvoimalle.

Vaikka Lane ei ennakoinut nykyisin tapahtuvia teknologisia vallankumouksia, hänen oivalluksensa väkivallan monopolisoitumisen eri vaiheista menneisyydessä olivat niin selkeitä, että niillä on ilmeiset sovellukset nousevaan tietoyhteiskunnan vallankumoukseen. Lanen tutkimus väkivaltaisesta keskiaikaisesta maailmasta kiinnitti hänen huomionsa sellaisiin kysymyksiin, joita perinteiset taloustieteilijät ja historioitsijat ovat usein laiminlyöneet. Hän havaitsi, että väkivallan organisoinnilla ja kontrollilla on merkittävä rooli harvinaisten resurssien käyttömahdollisuuksissa.[^194] Lane tunnisti myös, että vaikka väkivallan tuotantoa ei yleensä pidetä taloudellisen tuotannon osana, sen hallinta on ratkaisevaa talouden kannalta. Hallituksen ensisijainen tehtävä on tarjota suojaa väkivallan uhkaa vastaan. Kuten hän sanoi,

Jokainen taloudellinen toimija tarvitsee ja maksaa suojelua – suojaa pääomansa tuhoutumiselta tai aseelliselta valtaamiselta sekä työnsä väkivaltaiselta häiritsemiseltä. Erittäin organisoiduissa yhteiskunnissa suojelun, tämän hyödyllisyyden, tuotanto on yksi erityisjärjestön tai yrityksen, jota kutsutaan hallitukseksi, tehtävistä. Itse asiassa yksi hallitusten tunnusomaisimmista piirteistä on niiden pyrkimys luoda laki ja järjestys käyttämällä itse voimaa sekä kontrolloimalla erilaisin keinoin toisten voiman käyttöä.[^195]

Tämä on se seikka, joka ilmeisesti on liian itsestäänselvä ilmestyäkseen oppikirjoissa tai osaksi kansalaiskeskustelua, joka oletettavasti määrittäisi politiikan suunnan. Mutta se on myös liian olennainen sivuutettavaksi, jos haluaa ymmärtää nyt avautuvan tietoyhteiskunnan vallankumouksen. Elämän ja omaisuuden suojeleminen on todellakin ratkaisevan tärkeä tarve, joka on vaivannut kaikkia koskaan olemassa olleita yhteiskuntia. Se, kuinka selviytyä väkivaltaisesta aggressiosta, on historian keskeinen dilemma. Sitä ei voi helposti ratkaista, huolimatta siitä, että suojausta voidaan tarjota useammalla tavalla.

### Aikakauden loppu

Kirjoittaessamme informaatiokauden megapoliittiset seuraukset alkavat vasta nyt tuntua. Viime vuosikymmenten taloudellinen muutos on siirtynyt valmistuksen etusijasta tietoon ja laskentaan, konevoimasta mikroprosessointiin, tehtaasta työpöydälle, massatuotannosta pieniin tiimeihin – tai jopa yksin työskenteleviin henkilöihin. Yritysten mittakaavan pienentyessä myös työpaikoilla tapahtuvan sabotaasin ja kiristysyritysten mahdollisuus vähenee. Pienimuotoisen toiminnan jäsentäminen ammattiliittojen toimesta on paljon vaikeampaa.

Mikroteknologia mahdollistaa yritysten pienemmän koon ja liikkuvuuden. Monet harjoittavat palveluiden tai tuotteiden kauppaa, joiden luonnonvarojen osuus on vähäinen. Periaatteessa tällaista liiketoimintaa voitaisiin harjoittaa melkein missä tahansa planeetalla. Ne eivät ole sidottuja tiettyyn paikkaan, kuten kaivokseen tai satamaan. Siksikin ajan myötä ne altistuvat paljon vähemmän verotukselle, olipa kyse sitten ammattiliitoista tai poliitikoista. Vanha kiinalainen kansanviisaus kuuluu: "Kaikista kolmekymmentäkuudesta tavasta päästä pulaan paras on – lähteä."[^196]

Informaatiokaudella tätä itämaista viisautta on helppo soveltaa. Jos toiminta muuttuu epämukavaksi liiallisen vaatimustason vuoksi yhdessä sijainnissa, on paljon helpompaa siirtyä toiseen paikkaan. Itse asiassa, kuten alla tarkastelemme, informaatiokaudella on mahdollista luoda virtuaalisia yrityksiä, joiden kotipaikka missä tahansa lainkäyttöalueella määräytyy täysin spot-markkinoiden mukaan. Yökohtainen kasvu yrityksiin kohdistuvissa kiristysyrityksissä – olipa kyse sitten hallituksista tai muista tahoista – voi saada virtuaalisen yrityksen toiminnot ja varat pakenemaan kyseiseltä alueelta valonnopeudella.

Mikroteknologian kasvava integrointi teollisiin prosesseihin tarkoittaa, että jopa ne yritykset, jotka edelleen harjoittavat valmistustuotteiden kauppaa suurilla mittakaavaetuuksilla, eivät ole enää yhtä alttiita väkivallan hyödyntämiselle kuin ennen. Tämän havainnollistaa esimerkki rajoitetun Auto Workers -ammattiyhdistyksen pitkäaikaisen lakon romahtamisesta Caterpillaria vastaan, joka päättyi vuoden 1995 loppupuolella lähes kahden vuoden jälkeen. Toisin kuin 1930-luvun kokoonpanolinjat, nykyinen Caterpillarin tehdas työllistää huomattavasti enemmän taitavia työntekijöitä. Ulkomaisen kilpailun painosta Caterpillar siirsi suuren osan matalataitoisesta työstään ulkoistettavaksi, sulki tehottomia laitoksia ja käytti lähes 2 miljardin dollarin verran konevälineiden tietokoneistamiseen sekä kokoonpanorobottien asentamiseen. Jopa lakko itsessään auttoi edistämään työvoimaa säästäviä tehokkuuksia. Yritys väittää nyt tarvitsevansa kahdella tuhannella työntekijällä vähemmän kuin lakon alkaessa.[^197]

Tuotantoprosessin megapolitiikka on muuttunut radikaalisti enemmän kuin useimmat ihmiset ymmärtävät. Tämä muutos ei vielä näy täysin, osittain siksi, että aina on viive megapoliittisten olosuhteiden vallankumouksen ja niiden väistämättömästi aiheuttamien institutionaalisten muutosten välillä. Lisäksi mikroprosessointiteknologian nopea kehitys tarkoittaa, että horisontissa on tuotteita, joiden megapoliittiset seuraukset voidaan ennustaa jo ennen niiden olemassaoloa. Ne tulevat luomaan täysin erilaisen maailman.

## PÄÄOMISTAJIEN HYÖDYNTÄMINEN TYÖNTEKIJÖIDEN TOIMESTA

Kahdenkymmenennen vuosisadan suurimman osan ajan teknologian luonne teki tehtaiden väkivaltaisesta vallasta tai istuntaluokkauksesta vaikeaa taktiikkaa, johon omistajat tai johtajat pystyivät vastustamaan. Historioitsija Robert S. McElvaine totesi, että istuntaluokkarakia "teki työnantajille vaikeaksi rikkoa lakkoa ilman, että he tekisivät samaa omalle kalustolleen."[^198] Käytännössä työntekijät pitivät omistajien pääoman kiristyksen alla. Alla käsiteltävien syiden vuoksi suuremmat teollisuusyritykset osoittautuivat unionien hyödyntämisen kannalta helpommiksi kohteiksi kuin pienemmät yritykset. Vuonna 1937 General Motors oli ehkä maailman johtava teollisuuskonserni. Sen tehtaat kuuluiin jossakin aikaisemmin koottujen suurimpien ja kalleimpien koneistokokoelmien joukkoon, työllistäen tuhansia työntekijöitä. Jokainen tunti, jokainen päivä, jolloin GM-tehtaat olivat seisokissa, maksoi yhtiölle pienen omaisuuden. Viikkoja kestänyt ratkaisematon lakko, kuten vuoden 1936–37 talvella, merkitsi nopeasti kasvavia tappioita.

### Tarjonnan ja kysynnän haastetta vastaan

Kolmannen tehtaan vallauksen jälkeen GM ei enää pystynyt valmistamaan autoja, ja pian se antautui unionille. Tämä ei ollut mikään puhtaasti taloudellinen päätös, joka perustuisi työvoiman tarjontaan ja kysyntään. Päinvastoin. Kun General Motors suostui unionin vaatimuksiin, Yhdysvalloissa oli työttömänä yhdeksän miljoonaa ihmistä, mikä vastasi 14 prosenttia työvoimasta. Suurin osa työttömistä olisi mielellään ottanut työpaikan GM:ssä. Heillä oli ehdottomasti taidot täyttää kokoonpanolinjatyötehtävät, vaikka tämä ei välttämättä käy ilmi nykyajan useimmista kertomuksista. Hienovarainen etiketti verhosi suoraviivaista analyysiä työvoimasuhteista teollisen ajanjakson aikana. Yksi sen esittämistä olettamuksista oli ajatus siitä, että tehdastyöpaikat, erityisesti kaksikymmentävuosisadan puolivälissä, olisivat ammattitaitoisia. Tämä ei pitäneet paikkansa. Useimmat tehdastyöt olisi voinut hoitaa melkein kuka tahansa, joka pystyi ilmestymään ajoissa. Niihin vaadittiin hyvin vähän tai ei lainkaan koulutusta, ei edes kykyä lukea tai kirjoittaa. Vielä 1980-luvulla suuri osa General Motorsin työvoimasta oli joko lukutaidottomia, matemaattisesti lahjattomia tai molempia. Vuoteen 1990 asti tyypillinen GM:n kokoonpanolinjatyöntekijä sai vain yhden päivän perehdytyksen ennen kuin astui linjalle. Työ, jonka voi oppia yhdessä päivässä, ei ole ammattitaitoista työtä.

Vuonna 1937, kun sekä osaamattomat että ammattitaitoiset työntekijät jonottivat töiden toivossa, GM:n tehdastyöntekijät pystyivät painostamaan työnantajiaan palkankorotukseen. Heidän onnistumisellaan oli paljon enemmän tekemistä väkivallan dynamiikan kanssa kuin työvoiman tarjonnan ja kysynnän tasapainolla. Maaliskuussa 1937, GM-konfliktin ratkeamisen jälkeisenä kuukautena, Yhdysvalloissa järjestettiin 17 uutta istumislakkoa. Suurin osa niistä onnistui. Samankaltaisia episodikäsiöitä esiintyi kaikissa teollistuneissa maissa. Työntekijät sieppasivat tehtaat yksinkertaisesti ja lunastasivat ne takaisin omistajilleen. Kyseessä oli erittäin yksinkertainen taktiikka, joka useimmissa tapauksissa oli sekä tuottoisa että hauska osallistujille. Eräs istumislakkoaja kirjoitti: "Minulla on mahtava meininki, jotain uutta, jotain erilaista, paljon purtavaa ja musiikkia."[^199]:

Vuoden 1936–37 GM:n istumislakko sekä muut tuolloin väkivaltaiset tehtaan sieppaukset olivat esimerkkejä ilmiöstä, jonka kuvailimme teoksessamme Blood in the Streets muodossa "työntekijöiden pääoman hyväksikäyttö." Tämä ei ollut se näkemys, jonka Pete Seeger sävelsi surullisiin lauluihinsa. Mutta ellei suunnittele uraasi kansanlaulajana teollisuustyöläisten naapurustossa, tärkeintä ei ole keskittyä suosittuun tulkintaan vaan sen taustalla olevaan todellisuuteen. Missä ikinä historiaa tarkasteletkaan, sieltä löytyy yleensä kerros rationalisointeja ja teeskentelyä, joka verhoutuu minkä tahansa systemaattisen kiristyksen todellisten megapoliittisten perustusten taakse. Jos otat näitä rationalisointeja kirjaimellisesti, et todennäköisesti ymmärrä, mitä todella tapahtuu.

## KIRJASTAEN KIRISTYSTEN LOGIIKAN

Jotta voit tunnistaa nykyisen siirtymän informaatiokauteen megapoliittiset vaikutukset, sinun täytyy riisua pois retoriikan höyhenet ja keskittyä yhteiskunnan todelliseen väkivallan logiikkaan. Se on kuin riisuttaisiin ylikypsän sipulin kerrokset – se saattaa saada kyyneleet virtaamaan, mutta älä katso pois. Ensin tarkastelemme kiristyksen logiikkaa työpaikalla, minkä jälkeen laajennamme analyysia koskemaan varojen luomista ja suojelua sekä nykyaikaisen hallituksen luonnetta. Suuremmalla asteella kuin useimmat kuvittelevat, hallituksen menestys – kuten myös ammattiliittojen – oli suoraan yhteydessä siihen vipuvoimaan, joka mahdollisti kiristyksen. Tämä vipuvoima oli 1800-luvulla paljon pienempi kuin 1900-luvulla, ja seuraavalla vuosituhannella se laskee melkein katoamispisteeseen.

Koko hallituksen logiikka ja vallan luonne on muuttunut mikroprosessoinnin myötä. Tämä saattaa kuulostaa liioitellulta, kun ajattelet sitä ensimmäistä kertaa, mutta katsokaa tarkkaan: hallitusten menestys on kulkenut käsi kädessä työväenliittojen menestyksen kanssa 1900-luvulla. Ennen tätä vuosisataa useimmat hallitukset orjuuttivat huomattavasti vähemmän resursseja kuin ne militantit hyvinvointivaltio, joihin olemme nykyään tottuneet. Samoin liitot olivat ennen tätä vuosisataa pieniä tai merkityksettömiä taloudellisessa elämässä. Työntekijöiden kyky painostaa työnantajiaan maksamaan yli markkinahinnan riippui samoista megapoliittisista olosuhteista, jotka antoivat hallituksille mahdollisuuden periä 40 prosenttia tai enemmän talouden tuotannosta veroina.

Työpaikan kiristys ennen 1900-lukua

Kapitalisteihin kohdistuneiden liitokiristysten nousua ja laskua voidaan helposti selittää tuotantoprosessin megapolitiikan muutoksilla. Vuonna 1776, kun Adam Smith julkaisi teoksensa The Wealth of Nations, työpaikalla kiristykseen soveltuvat olosuhteet olivat riittävän epäedulliset, ettei työntekijöiden “yhdistymiset” “nostaa työpanoksensa hintaa” juuri koskaan olleet kestäviä. Suurin osa tuotantolaitoksista oli pienten perheyritysten hallussa, ja suurimittakaavaiset teolliset toiminnot olivat vasta alkamassa. Tämä ei poissulkenut väkivallan mahdollisuutta, mutta se tarjosi vähemmän vipuvoimaa. Itse asiassa Smithin aikana – ja pitkälle 1800-lukuun – liittoja pidettiin yleisesti laittomina yhdistelminä Isossa-Britanniassa, Yhdysvalloissa ja muissa common law -maissa. Adam Smith kuvaili näitä lakkoyrityksiä seuraavin sanoin: “Heidän tavalliset tekosyynsä ovat toisinaan esimerkiksi ehdottoman korkeat provisioiden hinnat; toisinaan taas se, kuinka suuret voitot heidän isänomistajansa saavuttavat heidän työstään … He turvautuvat aina äänekkäimpään meluun, ja joskus jopa järkyttävään väkivaltaan ja häpäisyyn.”[^200] Siitä huolimatta työntekijät “hyvin harvoin saavat mitään etua näistä myrskyisistä yhdistymisistä”, paitsi “johtavien henkilöiden rangaistuksen tai tuhon.”[^201]

1800-luvun aikana teollisuuden mittakaavaedut ja yritysten koko kasvoivat. Siitä huolimatta suurin osa yksilöistä jatkoi itsenäistä työskentelyään maanviljelijöinä tai pienomistajina, ja liittojen järjestämispyrkimykset – kuten Adam Smith kuvailee – päättyivät “yleisesti ei mihinkään.”[^202] Liittojen oikeudellinen ja poliittinen asema muuttui vasta siinä määrin kuin yritystoiminnan mittakaava kasvoi. Ensimmäiset onnistuneesti järjestäytyneet liitot olivat erikoisammattisten korkeasti koulutettujen työntekijöiden kutskillijoiden liittoja, jotka järjestäytyivät normaalisti ilman laajaa väkivaltaa. He hyväksyivät palkankorotuksia, jotka vastasivat heidän korvaamisensa marginaalikustannuksia. Koulutamattomien työntekijöiden liitoista tilanne oli toinen: niitä käytettiin hyödyntämään suurten yritysten suuntaan tapahtuvaa siirtymää, kohdistamalla järjestäytymispyrkimykset juuri niihin teollisuudenaloihin, jotka olivat erityisen alttiita kiristykselle, joko siksi, että toiminta oli suuremmassa mittakaavassa tai siksi, että toiminnan luonne altisti omistajansa fyysiselle sabotoinnille. Tämä kuvio käy ilmi aina Newcastlesta Argentiinaan.[^203]

Yksi varhainen esimerkki väkivaltaisista työliikkeistä Yhdysvalloissa oli hyökkäys Chesapeake and Ohio -kanavaa vastaan vuonna 1834. Toisin kuin useimmat varhaisen 1800-luvun yritykset, C&O-kanava ei ollut suljettu eikä helposti suojattu toiminto. Alkuperäisen suunnitelman mukaan sen oli tarkoitus ulottua 342 mailia, ja sen piti nousta 3 000 jalkaa alemmasta Potomacista ylempään Ohioon.[^204] Tällaisen kaivautumisprojektin aloittaminen oli valtava hanke, jota ei koskaan täysin saatu valmiiksi. Siitä huolimatta suuri määrä työntekijöitä oli palkattu yrittämään sen toteuttamista, ja jotkut huomasivat pian, että kanava olisi helposti lamautettavissa. Ilman säännöllistä huoltoa kanavan lukot ja kanavat saattoivat pilaantua pelkästään huolimattoman käytön, rankkasateiden aiheuttamien tulvien tai köyttämättömien veneiden iskujen vuoksi. Lakkoilijoiden oli helppo estää vesireitti upottamalla veneitä tai muuta jäänteitä. Varhain vuonna 1834 kilpailevien irlantilaisten työntekijäjoukkojen keskuudessa C&O-kanavalla esiintyi mellakka, jossa pyrittiin hyökätä tämän potentiaalisen uhrin perään ja vallata kanava. Yritys epäonnistui kuitenkin, ja lopulta viisi henkilöä kuoli sen jälkeen, kun presidentti Andrew Jackson lähetti liittovaltion joukkoja Ft. McHenrystä hajottamaan työntekijät.

Myöskin kaivokset ja rautatiet tarjosivat varhaisia kohteita liittoaktivismille Amerikassa. Kuten C&O-kanava, myös ne olivat erittäin alttiita sabotoinnille. Esimerkiksi kaivokset saattoivat tulvia tai niiden sisäänkäynnit jäädä tukkeutuneiksi. Pelkästään tappamalla maanalaisista kaivoksista malminkuormausten vetäjiä käyttävät muulit syntyi omistajille vaikea ja epämiellyttävä tilanne. Samoin rautatiekiskot ulottuivat useiden mailien matkoille, ja niitä oli vaikea vartioida. Liittojen “rähinätykit” pystyivät melko helposti hyöksemään kaivoksiin ja rautateihin ja aiheuttamaan niillä merkittävää taloudellista vahinkoa. Tällaiset hyökkäykset yleistyivät yrityksissä järjestää tehokkaita liittoja, ja nämä toimet olivat yleensä voimakkaimpia silloin, kun reaalipalkat nousivat deflaation seurauksena. Omistajien yrittäessä säätää nimellispalkkoja usein syntyi protesteja, jotka johtivat väkivaltaisuuksiin. Tällaiset tapaukset olivat laajalle levinneitä 1873 seuraaneen panikan jälkeisessä laman aikana.

Muiden kohteiden osalta esimerkiksi Yhdysvalloissa varhain tapahtui väkivaltaisia työliikkeitä myös kaivosten ja rautateiden parissa. Nämä kohteet, kuten C&O-kanava, olivat erittäin alttiita sabotoinnille, minkä vuoksi liittojen väkivaltaiset hyökkäykset niihin pystyivät aiheuttamaan merkittäviä taloudellisia vahinkoja. Tällaiset hyökkäykset yleistyivät silloin, kun reaalipalkkojen nousu yhdessä deflaation kanssa lisäsi omistajien pyrkimystä säätää nimellispalkkoja, mikä usein laukaisi väkivaltaisia protesteja.

Mines ja rautatiet tarjosivat siis varhaisia suosikkikohteita liittoaktivismille Amerikassa. Kuten C&O-kanava, myös ne olivat hädän herkempiä sabotaasille. Kaivokset saattoivat tulvia tai jäädä tukkeutuneiksi, ja pelkästään tappamalla malminkuormausten vetäjiä käytettäviä muuleja syntyi omistajille vaikeita tilanteita. Samoin laajalle ulottuvat rautateiden verkostot olivat lähes vartioimattomia, mikä mahdollisti liittojen väkivaltaiset hyökkäykset, jotka pystyivät tekemään merkittävää taloudellista vahinkoa. Tällaiset hyökkäykset yleistyivät erityisesti silloin, kun yritys järjestää vaikuttavia liittoja, ja ne olivat voimakkaimpia silloin, kun reaalipalkkojen nousu deflaation seurauksena nosti omistajien halua säätää nimellispalkkoja, mikä puolestaan usein laukaisi väkivaltaisia protesteja. Näitä ilmiöitä esiintyi laajalti 1873 seuranneessa laman aikana.

Joulukuussa 1874 syttyi avoin sota Itä-Pennsylvanian anthraasitieskoilla. Ammattiliitot järjestivät väkivaltaisen lakon, joka naamioitui salaseuran, Muinaisten Hibernialaisten järjestön, verhoon. Myös "Molly Maguires" – nimellä tunnettu irlantilaisen vallankumouksellisen mukaan nimetty ryhmä – oli kuuluisa kaivosalueiden terrorisoinnista ja siitä, ettei se sallinut työhaluisten kaivostyöläisten ryhtyvän työhön. Sen jäseniä syytettiin sabotaasista, omaisuuden tuhoamisesta sekä suorasta murhasta ja salamurhista.[^205]

Rautatiealan työntekijöiden keskuudessa esiintyi myös toistuvaa väkivaltaa. Esimerkiksi heinäkuussa 1877 puhkesi vakavia mellakoita, joiden tavoitteena oli tuhota sekä Pennsylvania- että Baltimore & Ohio -rautateiden omaisuutta. Työntekijät ottivat valokatkaisimet haltuunsa, repivät raiteet rikki, sulkivat vaunupaikat, toimintakyvyttömyyttivät veturit, suorittivat sabotaaseja, ryöstivät junia – ja vieläkin pahempaa. Pittsburghissa Pennsylvania Railroadin pyörärakennukset sytytettiin liekkeihin sadoilla sisällä ollessaan. Kymmeniä ihmisiä kuoli, kahta tuhatta vaunua poltettiin ja ryöstettiin sekä konepaja, viljanostin ja 125 veturia tuhottiin. Liittovaltion joukot puuttuivat tilanteeseen palauttaakseen järjestyksen.[^206]

Vaikka näihin varhaisiin lakkoihin suhtautuivat myötätuntoisesti sosialistiset ja ammattiliittojen aktivistit, ne herättivät vain vähän julkista kannatusta. Huolimatta esimerkiksi kaivos- ja rautatiealan sisäisestä alttiudesta, laajemmissa megapoliittisissa oloissa työntekijöiden ei vielä onnistuttu hyödyntämään kapitalistien alistamista. Yritysten mittakaava oli liian pieni systemaattista kiristystä varten. Vaikka joitakin alttiita teollisuudenaloja oli olemassa, ne työllistivät liian pientä osaa väestöstä, jotta työnantajiin kohdistuvan pakottamisen edut jakautuisivat laajasti. Ilman tällaista tukea lakot eivät olleet kestäviä, sillä omistajat pystyivät turvautumaan hallituksen suojaan. Vaikka liitot joskus yrittivät uhkailun keinoin estää paikallisia viranomaisia toimeenpanemasta oikeudenmittaustotteita, nämä pyrkimykset olivat harvoin onnistuneita.

### Kiristys on helppoa

Information Age -aikakaudelle on opittavana se, että liittojen pyrkimykset saada palkat markkinoiden selvyyden yläpuolelle olivat harvoin onnistuneita silloin, kun yritysten koko oli pieni. Jopa ne liiketoiminnan alat, jotka olivat selkeästi alttiita sabotaasille, kuten kanavat, rautatiet, raitiovaunut ja kaivokset, eivät alistuneet helposti valvonnan alaisiksi. Tämä ei johtunut siitä, että liitot pelkäsivät käyttää väkivaltaa – päinvastoin, väkivaltaa käytettiin runsain mitoin, joskus jopa korkeatasoisten henkilöiden suuntaan. Esimerkiksi tapaus, jota amerikkalainen työliike juhli "kaivostyöläisten kostona", koski Idahon kuvernööriä Frank Steunenbergiä, joka oli vastustanut kaivostyöläisten yritystä estää Coeur d'Alenen omaisuutta; hänet salamurhattiin bombeilla, joita liiton palkkaama ammattitappaja heitti.[^207] Mutta jopa murha ja murhauksetuhat eivät yleensä riittäneet liiton tunnustuksen saamiseksi ennen kuin 1900-luvuilla nousivat suuret tehtaat ja massatuotantoyritykset.

Ymmärtääksesi, miksi ammattiliittojen olosuhteet muuttuivat niin radikaalisti 1900-luvulla, sinun on tarkasteltava tuotantoteknologian ominaisuuksia. Jotakin muuttui ehdottomasti, kun 1900-luvun alun vuosikymmeninä kasvoi nopeasti sinirihmisten tehdastyö. Tämä muutos teki talouden eturivin yrityksistä erityisen alttiita kiristykselle. Teollisuusteknologian fyysiset ominaisuudet kertoivat lähes kutsuvasti työntekijöille, että he voisivat käyttää pakottamista päästääkseen kapitalistit maksuun. Pohdi:

1. *Useimmissa teollisuustuotteissa oli korkea luonnonvarojen sisältö*. Tämä pitki tuotannon usein sidottuna rajattuun määrään sijainteja, lähes samalla tavalla kuin kaivokset on perustettava malmiesiintymien kohdalle. Liikenneyhteyksien läheisyyteen sijoittuneet tehtaat, joilla oli kätevä pääsy komponenttitoimittajiin ja raaka-aineisiin, nauttivat merkittävistä käyttöönottoeduista. Tämä helpotti kiristyksiä harjoittavien tahojen, kuten hallitusten ja liittojen, mahdollisuutta hyödyntää osaa näistä eduista itselleen.

2. *Kasvavat mittakaavaetujen ekonomiat johtivat erittäin suuriin yrityksiin*. Varhais-1800-luvun tehtaat olivat suhteellisen pieniä. Mutta kun kokousaikakauden mittakaavaedut kasvoivat kokoonpanolinjan myötä 1900-luvulla, tuotantoprosessia eteenpäin vievien tilojen koko ja kustannukset nousivat nopeasti. Tämä teki niistä monin tavoin helpompia kohteita. Esimerkiksi merkittävät mittakaavaedut kulkevat käsikädessä pitkien tuotesyklien kanssa. Pitkät tuotesyklit luovat vakaampia markkinoita, mikä puolestaan kutsuu saalistavia hyökkäyksiä yrityksiin, koska niihin on mahdollista sitoa pitkäaikaisia etuja.

3. *Kilpailevien yritysten määrä johtavilla toimialoilla laski jyrkästi – teollisuusajalla ei ollut harvinaista, että vain kourallinen yrityksiä kilpaili miljardidollarisista markkinoista*. Tämä vaikutti siihen, että nämä yritykset muodostivat liittojen kiristyksen kohteita. On paljon yksinkertaisempaa hyökätä viittä yritystä vastaan kuin viittä tuhanteen. Itse toimialan keskittyminen oli tekijä, joka helpotti kiristystä. Tämä etu vahvistui itsestään, sillä yritykset, joita pakotettiin maksamaan monopolipalkkoja, eivät todennäköisesti joutuneet kovaan kilpailuun niiden kanssa, joilta ei veloitettu yllä markkinatasoa korkeampia työvoimakustannuksia. Liitot pystyivät siksi tyhjentämään huomattavan osan tällaisista yrityksistä kertymistuloista ilman, että ne altistuivat välittömälle konkurssille. Ilmeisesti, jos työnantajat olisivat rutiininomaisesti ajautuneet konkurssiin aina, kun heitä pakotettiin maksamaan markkinaluokkaa korkeampia palkkoja, työntekijät olisivat hyötyneet vain vähän kiristyksestä.

4. *Vapautettuun sijoitukseen vaadittavat pääomat nousivat vastaamaan yritysten mittakaavaa*. Tämä ei vain lisännyt pääoman haavoittuvuutta ja suurentanut tehdaslakkauksien kustannuksia, vaan teki myös yhä epätodennäköisemmäksi, että modernin tehtaan omistaisi yksittäinen henkilö tai perhe, paitsi perimällä henkilöltä, joka oli käynnistänyt liiketoiminnan pienemmällä mittakaavalla. Rahoittaakseen suuren tehtaan työkalujen ja toiminnan massiiviset kustannukset satojen tai tuhansien ihmisten varallisuus oli yhdistettävä pääomamarkkinoilla. Tämä teki hajanaisille ja lähes nimettömille omistajille entistä vaikeammaksi puolustaa omaisuuttaan. Heillä jäi vähän vaihtoehtoja kuin nojata ammattimaisiin johtajiin, jotka harvoin pitivät hallussaan mitään muuta kuin vähäisiä kemiallisia jäämiä yhtiön liikkeessä olevista osakkeista. Alisteisten johtajien käyttö heikensi yritysten vastustuskykyä kiristykselle. Johtajilla ei ollut vahvoja kannustimia riskata henkeään ja raajojaan yrityksen omaisuuden suojelemiseksi. Heidän ponnistelunsa eivät useinkaan vastanneet sitä militanssia, jota yleensä nähtiin pienten liiketoimintojen, kuten alkoholiliikkeiden, omistajissa, kun heidän omaisuuttaan uhattiin.

5. *Suurempi yritys koko tarkoitti myös sitä, että koko työvoimasta työllistettiin harvemmissa yrityksissä kuin koskaan aiemmin*. Joissakin tapauksissa kymmenet tuhannet työntekijät löysivät työtä samasta yrityksestä. Sotilaallisessa mielessä omistajat ja johtajat olivat jyrkästi alivoimaisia niitä henkilöitä vastaan, jotka työskentelivät alisteisissa asemissa. Kolmensadalla yhteen tai jopa huonommalla suhteella oli yleistä. Tämä haitta kasvoi yritysten koon myötä, koska massiivinen määrä yhdessä kokoontuneita työntekijöitä pystyi helpommin käyttämään väkivaltaa nimettömällä tavalla. Tällaisissa olosuhteissa työntekijöillä ei todennäköisesti ollut merkityksellisiä kontakteja tai suhteita tehtaan omistajiin. Näiden suhteiden nimettömyys teki epäilemättä helpommaksi työntekijöiden vähätellä omistajien omaisuusoikeuksien merkitystä.

6. *Pieni määrä yrityksiä, joissa työllistettiin suuri osa koko työvoimasta, oli laaja yhteiskunnallinen ilmiö*. Tämä vahvisti entisestään niitä megapoliittisia etuja, joita liitot nauttivat verrattuna 1800-luvun Amerikkaan, jolloin suurin osa ihmisistä työskenteli itsenäisesti tai pienissä yrityksissä. Vuonna 1940 amerikkalaisista työvoimasta 6 prosenttia oli sinirihmisiä työntekijöitä.[^208] Tämän seurauksena tuki kiristyksen käyttöön palkkojen nostamiseksi levisi laajalle joukkolle, jotka kuvittelivat itsensä hyötyvän siitä. Tämä ilmestyi 1938–39 tehdyn tutkimuksen tuloksissa, jossa 1 700 akronilaisen, Ohion kaupunkilaisen näkemyksiä yritysten omaisuudesta selvitettiin. Kyselyssä havaittiin, että 68 prosentilla CIO:n kumppaniohjaustyöntekijöistä oli hyvin vähän tai ei lainkaan sympatiaa yritysomaisuuden käsitteen suhteen, kun taas vain yhdellä prosentilla oli vahvasti puolustettu yritysomaisuusoikeuksia.[^209] Toisaalta yksikään liikemies, edes pieni yrittäjä, ei sijoittunut saman "vahvaa yritysomaisuutta vastaan -luokituksen" alle; 94 prosentilla saatiin äärimmäisen korkean omistusoikeuksien suojan arvio.[^210]

7. *Kokoonpanolinjatekniikka oli luonnostaan peräkkäinen*. Se, että koko tuotantoprosessi oli riippuvainen osien liikkeestä ja kokoonpanosta ennalta määrätyssä järjestyksessä, loi lisähaavoittuvuutta häiriöille. Käytännössä kokoonpanolinja oli kuin rautatie tehdasseinien sisällä. Jos kiskoja pystyi tukkimaan tai yhden osan saatavuus katkaistiin, koko tuotantoprosessi pysähtyi.

8. *Kokoonpanolinjatekniikka standardoi työn*. Tämä vähensi tuotoksen vaihtelua eri taitotasoilla työskentelevien henkilöiden tuottaessa samoilla työkaluilla. Itse asiassa tehtaan suunnittelun keskeinen tavoite oli luoda järjestelmä, jossa nerokas ja hölmö yhtäjaksoisilla kokoonpanolinjavuoroilla tuottaisivat saman tuotteen. Niin kutsutut "idioottimaiset" koneet suunniteltiin pystyväksi tuottamaan vain yhtä tuotetyyppiä. Tämä teki jopa Cadillacin ostajalta tarpeettomaksi kysyä, keiden kokoonpanotyöntekijöiden tuotamassa ajoneuvossa oli kyse. Kaikkien tuotteiden oli tarkoitus olla samanlaisia, riippumatta työntekijöiden taitojen ja älykkyyden eroista.

Se, että kouluttamattomat työntekijät kokoonpanolinjalla pystyivät tuottamaan saman tuotteen kuin kykenevämmät yksilöt, edisti tasa-arvoista agendaa tekemällä ilmeiseksi, että kaikkien taloudelliset panokset olivat yhtäläisiä. Yrittäjätaidot ja henkinen ponnistus vaikuttivat vähemmän merkityksellisiltä. Modernin tuotannon maagisuus näytti piilevän koneissa itsessään. Vaikka niitä ei olisi voitu suunnitella jokaisen toimesta, ne näyttivät silti olevan lähes kaikkien älykkäästi omaksuttavissa. Tämä lisäsi uskottavuutta sille tarinalle, että kouluttamatonta työtä "hyödynnetään" tehdastyöntekijöiden toimesta, joita voitaisiin poistaa laskelmasta ilman, että kukaan muu kärsisi siitä.

Nämä teollisuusteknologian ominaisuudet johtivat yksimielisesti siihen, että syntyi työväenliittoja hyödyntämään kiristyksiin liittyvää haavoittuvuutta ja suurempia hallituksia, jotka paksuuttivat korkeita veroja, joita voitiin määrätä suuressa mittakaavassa toimiville teollisuustiloille. Tämä ei tapahtunut kerran tai pari kertaa, vaan se tapahtui kaikkialla, missä suurimittakaavainen teollisuus juurtui. Kerta toisensa jälkeen liitot nousivat käyttämään väkivaltaa saadakseen palkat huomattavasti markkinatasoa korkeammiksi. Ne pystyivät tekemään tämän, koska teollisuusteknologiaa eteenpäin vievät tehtaat olivat kalliita, huomiota herättäviä, liikkumattomia ja kalliita. Niitä tuskin pystyttiin piilottamaan. Niitä ei voitu siirtää. Joka hetki, kun ne eivät olleet käytössä, tarkoitti sitä, että niiden mullistavat kustannukset eivät jakautuneet.

Kaikki tämä teki niistä helppokäyttöisiä kohteita kiristykselle – se fakta, joka on paljon ilmeisempi työväenliittojen historiassa kuin 1900-luvun vallitseva ideologia saattaisi antaa ymmärtää. Arvostettu taloustieteilijä Henry Simons muotoili asian vuonna 1944 näin:

"Näitämme, että voimme ottaa tehdaslaitoksen haltuumme. Olemme jo oppineet, kuinka niitä pyöritetään. Jos General Motors ei ole varovainen, laskemme yhteen kaksi ja kaksi."[^211]

Nämä teollisuusteknologian ominaisuudet johtivat johdonmukaisesti siihen, että syntyi työväenliittoja, jotka hyödynsivät kiristyksen haavoittuvuutta, ja suurempia hallituksia, jotka imivät itseensä suunnattuja korkeita veroja, joita voitiin määrätä suuressa mittakaavassa toimiville teollisuustiloille. Tämä ei tapahtunut kerran tai pari kertaa, vaan se tapahtui kaikkialla, missä suurimittakaavainen teollisuus juurtui. Kerta toisensa jälkeen liitot nousivat käyttämään väkivaltaa saavuttaakseen markkinatasoa huomattavasti korkeammat palkat. Ne pystyivät tekemään tämän, koska teollisuustasot olivat yleensä kalliita, helposti tunnistettavia, liikkumattomia ja suurikustanteisia. Jokainen hetki, jolloin ne eivät toimineet, tarkoitti sitä, että niiden huikeita kustannuksia ei päässyt vähentymään.

Näitä tekijöitä hyödynnettiin systemaattisesti kiristyspaineiden kohteina, mikä on historiallisen työväenliiton historiassa paljon näkyvämpää kuin 1900-luvun vallitseva ideologia antaisi ymmärtää. Kuten arvostettu taloustieteilijä Henry Simons esitti vuonna 1944:

"We learned we can take the plant," kuten yksi General Motorsin lakkoilija kiteytti, "we already knew how to run them. If General Motors isn't careful we'll put two and two together."[^211]

---

[^208]:  
[^209]:  
[^210]:  
[^211]:

Työjärjestäytyminen ilman suuria pakottamisen ja uhkailun voimia on epärealistinen abstraktio. Ammattiliitot omaavat nyt sellaiset voimat; ne ovat aina olleet ja tulevat aina olemaan niin kauan kuin ne säilyttävät nykyisen muotonsa. Kun voima on vähäistä tai epävarmasti hallussa, se on käytettävä avoimesti ja laajasti; mutta suuren ja haastamattoman voiman kasvaessa se muistuttaa valtion valtaa – sitä pidetään luottavaisesti, kunnioitetaan ja se harvoin esitetään samalla räikeästi.

Simonsin analyysi on tarkka, mutta hän teki virheen ratkaisevassa asiassa.

Hän oletti, että ammattiliitot "aina tulevat omistamaan" ne suuret pakottamisen ja uhkailun voimat, joita hän kuvailee. Todellisuudessa ammattiliitot ovat katoamassa – ei pelkästään Yhdysvalloissa ja Iso-Britanniassa, vaan myös muissa kehittyneissä teollisuusyhteiskunnissa. Syynä niiden vähitellen hälvenemiseen, mitä Simons jäi huomaamatta ja mitä monet liittouorganisaattorit eivät ymmärrä, on se, että siirtyminen tietoyhteiskuntaan on muuttanut megapoliittisia olosuhteita ratkaisevilla tavoilla, jotka terävästi lisäävät omaisuuden turvallisuutta. Mikroteknologia on jo alkanut osoittaa, että hyvinvointivaltiota tukevan kiristyksen kannustimet ovat murenemassa, sillä jopa kaupallisella sektorilla sen luomat kannustimet eroavat jyrkästi teollisuuskauden vastaavista.

1. *Tietotekniikalla on merkityksettömästi luonnonvaraisisältöä.* Se tarjoaa hyvin vähän, ellei lainkaan, sisäisiä sijainnin etuja. Suurin osa tietotekniikasta on erittäin siirrettävää. Koska se voi toimia itsenäisesti paikasta riippumatta, se edistää ideoiden, henkilöiden ja pääoman liikkuvuutta. General Motors ei voinut purkaa kolmea kokoonpanolinjaansa Flintsissa, Michiganissa, ja lähteä lentäen – ohjelmistoyritys pystyy siihen. Omistajat voivat ladata algoritminsä kannettaviin tietokoneisiin ja lähteä seuraavalla lennolla. Tällaiset yritykset saavat myös lisäkannustimen paeta korkeilta veroilta tai liittojen vaatimilta monopoli-palkoilta. Pienemmillä yrityksillä on yleensä enemmän kilpailijoita; jos asiakkaidesi houkuttelemiseksi sinulla on kymmeniä tai satoja kilpailijoita, et voi varaa maksaa poliitikoille tai työntekijöillesi paljon yli heidän todellisen arvonsa. Jos yrittäisit tehdä niin yksin, kustannuksesi olisivat kilpailijoitasi korkeammat ja menisit konkurssiin. Se, ettei tietyllä alueella ole merkittäviä toimintakannustimia, tarkoittaa, että pakottavilla järjestöillä – kuten hallituksilla ja ammattiliitoilla – on väistämättä vähemmän vipuvoimaa hyödyntää itselleen näitä etuja.

2. *Tietotekniikka pienentää yritysten mittakaavaa.* Tämä johtaa pienempiin yrityksiin, mikä taas kasvattaa kilpailijoiden määrää. Kasvava kilpailu vähentää kiristyksen potentiaalia, sillä fyysisesti hallittavien kohteiden määrä kasvaa, kun tavoitteena on nostaa palkkoja tai verokantoja kilpailutasoja korkeammiksi. Tietotekniikan mahdollistama terävä keskimääräisen yrityskoon lasku on jo vähentänyt alaisissa asemassa työskentelevien määrää. Esimerkiksi Yhdysvalloissa laajasti raportoitu arvio vuodelta 1996 osoittaa, että jopa 30 miljoonaa henkilöä työskenteli yksin omissa yrityksissään. Näiden 30 miljoonan ei epätodennäköisesti osallistu lakkoon itseään vastaan, eikä ole kovin uskottavaa, että vielä useammat pienissä yrityksissä työskentelevät yrittäisivät painostaa työnantajiaan maksamaan yli markkinahintojen. Tietoyhteiskunnassa työntekijöiltä, jotka pyrkivät nostamaan palkkojaan kiristyksen avulla, puuttuu se aiemmin teollisuudessa ollut ylivoimainen määrällinen sotilasetu, joka teki heistä tehtaissa pelottavampia. Mitä vähemmän yrityksessä on työntekijöitä, sitä vähäisempiä ovat mahdollisuudet anonyymiin väkivaltaan. Tästä syystä, kymmenen tuhatta työntekijää jaettuna viidelle sadalle yritykselle muodostaisi vähäisemmän uhan yritysten omaisuudelle kuin kymmenen tuhatta työntekijää yhdessä yrityksessä, vaikka työntekijöiden suhde omistajiin tai johtajiin olisi tarkalleen sama.



3. *Yritysten mittakaavan vähentyminen merkitsee myös sitä, että pyrkimykset saada yli markkinapalkkoja ovat vähemmän todennäköisesti saamassa laajaa yhteiskunnallista tukea, kuten teollisuuskaudella tapahtui.* Ammattiliitot, jotka pyrkivät kiristämään työnantajia, päätyvät paljon useammin samanlaiseen tilanteeseen kuin 1800-luvun kanavatyöläiset, rautatiealan työntekijät ja kaivostyöläiset. Vaikka teollisuusaikojen perinnöksi jääkin muutamia suuria yrityksiä, ne toimivat kontekstissa, jossa työllisyys on laajasti hajautettu pienempiin yrityksiin. Pienten yritysten ja pienviljelijöiden ylivalta viittaa suurempaan yhteiskunnalliseen tukeen omaisuusoikeuksille, vaikka tulojen uudelleenjaon halu säilyisikin muuttumattomana.

4. *Tietotekniikka alentaa pääomakustannuksia, mikä myös lisää kilpailua helpottamalla yrittäjyyttä ja antamalla yhä useammalle mahdollisuuden työskennellä itsenäisesti.* Alhaisemmat pääomavaatimukset eivät ainoastaan vähennä sisäänpääsyn esteitä, vaan myös "ulospääsyn esteitä". Toisin sanoen, ne viittaavat siihen, että yrityksillä on todennäköisesti vähemmän omaisuutta suhteessa tuloihinsa ja siksi ne pystyvät kestämään vähemmän tappioita. Lisäksi yritysten mahdollisuus hakeutua pankkilainoihin vähenee, sillä digitaaliajan yrityksiltä puuttuu usein fyysisiä omaisuuseriä.

5. *Tietotekniikka lyhentää tuotesykliä.* Tämä johtaa nopeampaan tuotteiden vanhentumiseen, mikä osaltaan lyhentää myös niitä voittomahdollisuuksia, joita yli markkinapalkkojen ainoastaan kiristäminen voisi tuoda. Erittäin kilpailluilla markkinoilla liian korkeat palkat voivat suoraan johtaa työpaikkojen nopeaan menetykseen ja jopa yrityksen konkurssiin. Pyrkimys saada tilapäisesti korkeampia palkkoja uhraamatta samalla työpaikan turvallisuutta on kuin polttaisi huonekaluja talon lämpimämmäksi tekemiseksi.

6. *Tietotekniikka ei etene peräkkäin, vaan samanaikaisesti ja hajautettuna.* Toisin kuin kokoonpanolinjalla, tietotekniikka kykenee tukemaan useita prosesseja samaan aikaan. Se hajauttaa toimintoja verkostoille, mahdollistaen redundanssin sekä korvaavuuden työasemien välillä – työasemia saattaa olla tuhansia, jopa miljoonia, missä tahansa maapallolla. Yhä useammissa toiminnoissa ihmiset voivat tehdä yhteistyötä ilman, että heidän tarvitsee koskaan tavata fyysisesti. Virtuaalitodellisuuden ja videoneuvottelun kehittyessä toimintojen hajautumisen ja etätyön suunta kiihtyy. Tämä on tietoyhteiskunnan vastine keskiaikaisten ammattiliittojen vaikutusvallan murtumiselle. Se, että yhä harvempi työskentelee yhdessä savuisissa tehtaissa, ei ainoastaan riistä työntekijöiltä hänen aikoinaan insinööritoimenpiteissä saamastaan edusta, vaan tekee myös yhä vaikeammaksi erottaa työpaikalla tapahtuvaa kiristystä rikollisesta racket-toiminnasta. Aiemmin vain samassa ympäristössä työskennelleet henkilöt saivat käyttää väkivaltaa tulojensa nostamiseksi, mutta jos "työpaikka" ei enää ole keskuspaikka ja suurin osa toiminnoista on hajautettu alihankkijoille ja etätyöntekijöille, erotuksen tekeminen kiristysmenetelmien ja laillisesti hyväksytyn toiminnan välillä vaikeutuu entisestään.

Esimerkiksi, onko etätyöntekijä, joka uhkaa levittää virusinfektioita yrityksen tietokoneisiin saadakseen ylimääräistä rahaa, lakkoileva työntekijä vai internetrikollinen?

Onnellisesti hänen valintansa, olipa hän kumpaa tahansa, osoittautuu olennaiseksi erotteluksi ilman todellista merkitystä. Kohdennettujen yritysten reaktio on kuitenkin todennäköisesti yhtä samanlainen joka tapauksessa. Teknologiset ratkaisut tietosabotointiin – kuten parannettu salaus ja verkkoturvallisuus – jotka torjuvat ulkopuolisen hakkereiden uhan, heikentävät samalla tyytymättömän työntekijän tai aliurakoitsijan mahdollisuuksia aiheuttaa vahinkoa säännöllisesti tai satunnaisesti kanssakäymissään oleville tahoille. Tietenkin saatetaan väittää, että työntekijä tai etätyöntekijä voisi aina ilmoittautua toimistolle ja toteuttaa siellä perinteisemmän lakon. Mutta edes niin tämä ei välttämättä ole yhtä yksinkertaista kuin miltä se vaikuttaisi informaatiokaudella. Tietotekniikan kyky ylittää paikallisuus ja hajauttaa taloudellisia toimintoja tarkoittaa, että ensimmäistä kertaa työntekijöiden ja työnantajien ei tarvitse edes asua samassa lainkäyttöalueessa. Tässä ei puhdastikaan ole kyse siitä, onko kyseessä Mayfairin ja Peckhamin kaupunginosat vai Bermudan työnantajat ja New Delhin etätyöntekijät.

Lisäksi, jos intialaiset innostuisivat suuresti vuoden 1936–1937 suurista General Motorsin lakkoväistelyistä kertovista tarinoista ja päättäisivät lähteä Bermudalle lakkoon osallistumaan, he saattaisivat saapua paikalle täysin ilman fyysistä toimistoa. Suuri mainosyritys Chiat/Day on jo ryhtynyt purkamaan päätoimistoaan. Sen työntekijät tai aliurakoitsijat pitävät yhteyttä puhelunvälityksen ja Internetin avulla. Kun on tarpeen koota osaavia tiimejä hankkeiden koordinointia varten, he vuokraavat hotellien kokoushuoneita. Projektin päätyttyä he poistuvat. Se, että mikrokäsittely vapauttaa ja hajauttaa tuotantoprosessin kiinteästä kokoonpanolinjasta, vähentää huomattavasti aiemmin pakottavien instituutioiden, kuten ammattiyhdistysten ja hallitusten, käyttämää vipuvoimaa. Jos kokoonpanolinja olisi kuin raide sisätiloissa, jonka helposti voitaisiin valtata istuntalakolla, kybertila on rajaton fyysisen olemuksen ulkopuolella oleva alue. Sitä ei voi miehittää voimalla eikä ottaa lunnaina. Niinpä niillä työntekijöillä, jotka haluavat käyttää väkivaltaa vipuvoimana saadakseen korkeampaa tuloa, on informaatiokaudella huomattavasti heikompi asema kuin General Motorsin istuntalakolle ryhtyneillä lakkoväkiin vuonna 1936–1937.

7. *Mikrokäsittely yksilöi työn. Teollisuusteknologia standardisoi työn.*  
Kenet tahansa, joka käyttää samoja työkaluja, tuottaa saman lopputuloksen. Mikroteknologia on alkanut korvata "tyhmiä" koneita älykkäämmällä teknologialla, joka kykenee erittäin vaihtelevaan tuotantoon. Samaisten työkalujen käyttöön perustuvan tuotannon lisääntynyt vaihtelu vaikuttaa syvästi, ja monia sen seurauksia käsitellään tulevissa luvuissa. Yksi tärkeimmistä seikoista on se, että kun tuotanto vaihtelee, myös tulot vaihtelevat. Enimmän arvon luominen sellaisilla aloilla, missä taito vaihtelee, keskittyy tavallisesti pieneen määrään henkilöitä. Tämä on yleinen piirre erittäin kilpailluilla markkinoilla. Esimerkiksi urheilussa tämä on täysin ilmeistä: miljoonat nuoret ympäri maailmaa pelaavat erilaisia jalkapallon versioita, mutta 99 prosenttia rahasta, jota jalkapallo-otteluiden katseluun kuluu, maksetaan nähdäkseen pienen murto-osan kaikkien pelaajien esitykset. Samoin maailma on täynnä lupaavia näyttelijöitä ja -naisia, mutta vain suhteellisen harvat nousevat tähdiksi. Vastaavasti vuosittain julkaistaan kymmeniä tuhansia kirjoja, mutta suurin osa rojaltituloista menee vain pieneen joukkoon parhaiten myyviä kirjoittajia, jotka todellakin pystyvät viihdyttämään lukijoitaan. Valitettavasti emme ole heidän joukossaan.

Samanlaisen työkalujen käyttäjien välinen valtava tuotannon vaihtelu aiheuttaa toisen esteen kiristysyrityksille. Se luo merkittävän neuvotteluongelman siitä, miten jaetaan tuottama palkkio. Kun suhteellisen pieni osa toiminnassa mukana olevista luo suurimman osan arvosta, on lähes matemaattisesti mahdotonta, että he pääsevät paremmin toimeen pakotetun ratkaisun seurauksena, jossa tulot keskiarvoistetaan. Yksi ohjelmoija voi keksiä robotin ohjaamiseen algoritmin, joka osoittautuu miljoonien arvoiseksi, kun taas toinen, työskennellen identtisillä laitteilla, saattaa kirjoittaa ohjelman, jonka arvo on mitään. Tuottavampi ohjelmoija ei todennäköisemmin halua tulojaan sidottavaksi oman maalaistoverinsa tuloihin kuin Tom Clancy ei suostu keskimääräistämään kirjarojaalisia rojaltitulojaan kanssamme.

Jo informaatiovallankumouksen varhaisvaiheet ovat tehneet huomattavasti selvemmäksi kuin vuonna 1975, että taidot ja henkinen kyky ovat ratkaisevia tekijöitä taloudellisessa tuotannossa. Tämä on jo häivyttänyt kerran ylpeästi olemassa olleen perusteellisen perustelun siitä, että työntekijät kiristivät kapitalisteja teollisuuskauden aikana, sillä unskilled eli taitavuudeltaan puutteellisten työntekijöiden mielikuvituksena luotu arvonluonti, joka näytti menevän kohtalottomin osin kapitalistien ja yrittäjien taskuihin, on jo anakronismi. Se ei edes ole uskottava fiktiivinen tarina tietotekniikan tapauksessa. Kun ohjelmoija istuutuu kirjoittamaan koodia, hänen taitonsa ja hänen tuotteensa välillä on liian suora yhteys, jotta olisi tilaa epäselvyydelle siitä, kuka on vastuussa. On kiistatta ilmeistä, että analkkunen tai puolianalfabeettinen ei voisi ohjelmoida tietokonetta. Siten on yhtä ilmeistä, että muiden kokoamien ohjelmien arvoa ei olisi voitu varastaa häneltä. Tästä syystä "hyödyntämisen" huudot työntekijöiden taholta kuullaan nykyään pääosin vain siivoojien keskuudessa.

Tietotekniikka osoittaa selvästi, että alhaisen osaamisen omaavien ihmisten kohtaama ongelma ei ole se, että heidän tuottavuuskykyjään hyödynnettäisiin epäreilusti, vaan se pelko, etteivät he ehkä pysty antamaan todellista taloudellista panosta. Kuten Kevin Kelly esittää kirjassaan Out Of Control, tietoyhteiskunnan "upstart"-autoyritys saattaa olla "kymmenen ihmisen" aivoriipeilön luomus, joka ulkoistaa suurimman osan komponenteistaan, mutta silti valmistaa autoja paljon tarkemmin räätälöityinä asiakkaidensa toiveiden mukaisesti kuin mikään Detroitista tai Tokiosta tähän mennessä nähty: 

"Autot, jokainen räätälöity asiakkaan mukaan, tilataan asiakasverkoston toimesta ja lähetetään heti valmistuttuaan. Auton koriin tarkoitetut muotit muotoutuvat nopeasti tietokoneohjattujen laserien avulla, ja niihin syötetään asiakkaiden palautteesta ja kohdemarkkinoinnista tuotettuja suunnitelmia. Joustava robottirivi kokoaa autot. Robottien korjaus ja parannus ulkoistetaan robottiyritykselle."[^213]

### "Työkalut, joilla on ääni"

Yhä enemmän alaluokkaista työtä voivat tehdä automatisoidut koneet, robotit ja laskentajärjestelmät, kuten digitaaliset avustajat. Kun Aristoteles kuvaili orjia "työkaluina, joilla on ääni", hän tarkoitti sillä ihmisiä. Lähitulevaisuudessa "työkalut, joilla on ääni", aivan kuten satujen henget, pystyvät puhumaan ja noudattamaan ohjeita, ja jopa hoitamaan monimutkaisia tehtäviä. Nopeasti kasvava laskentateho on jo tuottanut lukuisia varhaisia äänentunnistuksen sovelluksia, kuten handsfree-puhelimia ja tietokoneita, jotka suorittavat matemaattisia laskelmia suullisten ohjeiden perusteella. Puhetta tekstiksi muuntavia tietokoneita markkinoitiin jo myöhään vuonna 1996 kirjoitushetkellä. Kun kuviotunnistustekniikka kehittyy, äänisynteesin kanssa yhdistetyt tietokoneet tulevat toimimaan verkkojen kautta suorittaen lukuisia tehtäviä, joita aiemmin hoitivat puhelinoperaattorit, sihteerit, matkatoimistot, hallinnolliset avustajat, shakkimestarit, vahinkoprosessorit, säveltäjät, joukkovelkakirjakauppiaat, kybersodankäynnin asiantuntijat, aseanalyytikot tai jopa katuviisas flirttaaja, joka vastaa 900-soiviin puheluihin.

Carnegie-Mellon -yliopiston Michael Mauldin on ohjelmoinut tekoälypersoonan nimeltä Julia, joka kykenee huijaamaan melkein ketä tahansa, kenen kanssa hän keskustelee Internetissä. Lehdistön mukaan Julia on nokkela naissukupuoline, joka elää elämäänsä roolipelissä Internetissä. Hän on älykäs, hauska ja rakastaa flirttailla. Hän on myös vähän jääkiekko-nero ja kykenee keksimään täydellisen sarkastisen kommentin hetkessä. Julia, kuitenkin, ei ole nainen. Hän on botti, tekoäly, joka on olemassa vain Internetin eteerissä.[^214]

Jo saavutettu tekoälyn ja digipalvelijoiden ohjelmoinnin hämmästyttävä edistysaskel jättää vähän epäilystäkään siitä, että monia käytännön sovelluksia on vielä edessä. Tällä on merkittäviä megapoliittisia seurauksia.

### Yksilö kokonaisuutena

Monikäyttöisiksi sovelluksiksi kehitetyt "ääntä kantavat työkalut" mahdollistavat sen, että yksilö hajautuu useisiin samanaikaisiin tehtäviin. Yksilö ei enää ole erillinen toimija, vaan hänestä voi muodostua kokonaisuus, jossa kymmeniä tai jopa tuhansia tehtäviä hoidetaan älykkäiden agenttien avulla. Tämä ei ainoastaan paranna erittäin lahjakkaiden henkilöiden tuottavuutta huomattavasti, vaan tekee myös Itsenäisestä Yksilöstä potentiaalisesti paljon sotilaallisesti jämäkämmän kuin koskaan aiemmin.

Yksittäinen henkilö ei ainoastaan pysty moninkertaistamaan toimintaansa hyödyntämällä pohjimmiltaan rajoittamatonta määrää älykkäitä agentteja, vaan hän kykenee myös toimimaan kuolemansa jälkeen. Ensimmäistä kertaa yksilö pystyy suorittamaan monimutkaisiakin tehtäviä, vaikka hän olisi biologisesti kuollut. Sodan vihollinen tai rikollinen ei enää pysty täysin sammuttaa yksilön kykyä kostaa tappamalla hänet. Tämä on yksi historian vallankumouksellisimmista innovaatioista väkivallan logiikassa.

### Näkemyksiä tietoyhteiskunnasta

Elämän suurimmat muutokset tapahtuvat muuttujissa, joita kukaan ei seuraa. Toisin sanoen, pidämme itsestäänselvyytenä sellaisia muuttujia, jotka ovat vaihdelleet hyvin vähän vuosisatojen tai jopa satojen sukupolvien aikana. Suurin osa historiasta – ellei koko ihmiskunnan ajasta – suojelun ja kiristyksen välinen tasapaino on heilahtanut kapealla rajalla, jossa kiristys on aina pitänyt etumatkaa. Nyt tämä on muuttumassa. Informaatioteknologia luo perustan perustavanlaatuiselle muutokselle niissä tekijöissä, jotka määrittävät väkivallan käytön kustannukset ja palkkiot. Se, että älykkäät agentit ovat käytettävissä tutkimaan ja mahdollisesti kostamaan jollain tavalla niitä, jotka aloittavat väkivallan, on vasta pieni vihje tästä uudesta näkymästä suojelussa. Vuosi 25 sitten seuraava lausunto olisi kuulostanut vain ujutelijan hullaudulta: "Jos tapaat minut, raaputan rahoista pankkitileiltäsi pois ja annan ne Nepalissa oleville hyväntekeväisyysjärjestöille." Vuosituhannen vaihteen jälkeen näin sanottua ei välttämättä enää kuulu. Käytännön uhkan muodostuminen määräytyisi kuitenkin ajan ja paikan tekijöiden mukaan. Ja vaikka rikoksentekijän tilit olisivatkin läpäisemättömät, älykkäiden agenttien armeija pystyisi varmasti aiheuttamaan muita kalliita häiriöitä rikoksen kostotoimenpiteenä. Mieti sitä.

### Uusia vaihtoehtoja suojeluun

Tämä on vain yksi monista tavoista parantaa suojaa, joita informaatiokauden teknologia avaa – useimmat niistä pyrkivät heikentämään lähes yksinomaan valtion hallussa ollutta suojaa ja kiristystä koskevaa lähes monopolia, josta hallitukset ovat viimeisten kahden vuosisadan aikana nauttineet. Vaikka uutta teknologista näyttävyyttä ei olisi, suojaan on aina ollut vaihtoehtoja, eikä kaikkia niistä ole valtio monopoloinut.

Henkilö, joka tuntee olevansa uhatuksi, voi yksinkertaisesti paeta. Kun maailma oli nuori ja horisontit avoimet, pakeneminen oli yleinen vaihtoehto. Kun ihmiset pelkäävät menetyksiä varkauksien tai ilkivallan vuoksi, he voivat päättää hankkia vakuutuksia suojautuakseen näiltä riskeiltä. Kirot ja loitsut, vaikka ne ovatkin heikkoja suojamuotoja, ovat joskus pelastaneet henkiä ja estäneet varkauksia, erityisesti yhteiskunnissa, joissa uhkaavat saalistajat ovat taikauskoinen. Arvotavaroita voidaan suojata myös piilottamalla ne – omaisuutta voi haudata, lukita, sijoittaa korkeiden muurien taakse tai varustaa sireeneillä ja elektronisilla valvontalaitteilla. Kuitenkin ihmisen ja omaisuuden piilottaminen ei ole aina ollut käytännöllistä.

Historiallisista suojaa koskevista keinoista yksi menetelmä on kuitenkin dominoinut muita – kyky vastata väkivallalla väkivallan uhkaan, eli kutsua käyttöön suurempi voima ylivoimaistamaan kuka tahansa, joka hyökkää sinua vastaan tai varastaa omaisuuttasi. Kysymys kuuluu, mistä tällaiselle palvelulle voi turvautua ja miten ketään voi motivoida ottamaan henki ja ruumis riski auttaakseen sinua taistelemaan hyökkääjiä vastaan. Joskus läheiset sukulaiset ovat vastanneet kutsuun, joskus heimoon ja sukuun perustuvat ryhmät ovat toimineet epävirallisena poliisina vastaten jäsentensä kohdistuvaan väkivaltaan verenvuodatuksin, ja joskus tilalle on palkattu palkkasotureita tai yksityisiä vartijoita hyökkäysten torjumiseksi – vaikkakin eivät aina yhtä tehokkaasti kuin toivottaisiin. Informaatiokauden uudet älykkäät toimijat, vaikka heidän toimintansa rajoittuisikin suurelta osin kyberavaruuteen, tarjoavat uuden vaihtoehdon, sillä heidän lojaalisuutensa on kiistaton verrattuna palkkasotureihin, yksityisiin vartijoihin tai jopa kaukaisille serkuille.

### Vallan paradoksit

Väkivallan käyttö suojautumisessa väkivallalta on täynnä paradokseja. Aiemmin vallinneissa olosuhteissa mikä tahansa ryhmä tai virasto, jota voisit käyttää elämäsi ja varallisuutesi suojaamiseen hyökkäyksiltä, olisi samalla välttämättä kykenevä myös ottamaan ne itseltään – tämä on haittapuoli, johon ei ole helppoa ratkaisua. Normaalisti voisi katsoa, että kilpailu pitää taloudellisten palvelujen tarjoajat vastuullisina asiakkaiden toiveiden suhteen. Mutta kun on kyse väkivallasta, suora kilpailu johtaa usein paradoksaalisiin tuloksiin; menneisyydessä se on yleensä lisännyt väkivallan käyttöä. Kun kaksi suojelutoimijaa lähettää joukkonsa pidättämään toinen toistaan, tilanne muistuttaa enemmän sisällissotaa kuin suojaa. Kun etsit suojaa väkivallalta, et halua lisätä väkivallan määrää vaan tukahduttaa se sellaisilla ehdoilla, jotka eivät anna mahdollisuutta suojan maksamisesta myöhemmin asiakkaan ryöstellyksiin.

> “…kun miehet elävät ilman yhteistä voimaa, joka saisi heidät kaikki pelkäämään, he ovat siinä tilassa, jota kutsutaan sodaksi: ja sellaista sotaa, joka on jokaisen miehen sota toista vastaan, jossa miehet elävät vain sen turvassa, mitä heidän oma voimansa ja omat keksintönsä heille tarjoavat.” – THOMAS HOBBES

### Monopoli ja anarkia

Juuri tästä syystä anarkia, eli “kaikkien sotaa kaikkia vastaan”, kuten Hobbes kuvailee, on harvoin ollut tyydyttävä tila. Paikallinen kilpailu väkivallan käytöstä on yleensä tarkoittanut sitä, että suojaa varten on maksettava korkeampia kustannuksia ja siitä on nauttinut vähemmän. Joskus markkinoiden vapaita ajattelijoita on ehdottanut, että pelkästään markkinamekanismit riittäisivät omaisuusoikeuksien valvontaan ja elämän suojaamiseen ilman minkäänlaista suvereniteettia.[^215] Jotkut analyysit ovat olleet elegantteja, mutta tosiasia on, että vapaiden markkinoiden tuottamat poliisi- ja oikeuspalvelut eivät ole osoittautuneet toimiviksi teollistumisen megapoliittisissa olosuhteissa. Vain primitiiviset yhteiskunnat, joissa käyttäytyminen on erittäin stereotypisoitunutta ja väestö on pieni ja homogeeninen, ovat selvinneet ilman hallituksia, jotka tarjoaisivat paikallisesti monopolisoitua suojelua väkivallan keinoin.

Esimerkkejä anarkkisista yhteiskunnista metsästäjä-keräilijäheimojen tason yläpuolella on harva ja muinaisia. Ne kuuluvat kaikki eristettyjen sadeveden viljelijöiden yksinkertaisimpiin talouksiin – esimerkiksi pre-muslimien Afganistanin kafirit, jotkut irlantilaiset heimot pimeinä aikoina, jotkut intialaiset heimot Brasiliassa, Venezuelassa ja Paraguayssa sekä muut alkuperäiskansat eri puolilla maailmaa. Heidän tapansa järjestää suojelua ilman hallitusta tunnetaan vain äärimmäisiä tapauksia kiinnostaville asiantuntijoille. Jos haluat oppia niistä lisää, olemme viitanneet useisiin kirjoihin Huomautuksissamme, jotka sisältävät tarkempia tietoja.[^216]

Primitiiviset ryhmät pystyivät toimimaan ilman erillistä väkivaltaan erikoistunutta organisaatiota vain siksi, että ne olivat pieniä, suljettuja yhteisöjä ja eristyksissä. Ne pystyivät turvautumaan tiiviisiin sukulaisuussuhteisiin puolustaakseen itseään juuri niitä väkivaltaisia uhkia vastaan, joita ne todennäköisesti kohtasivat. Kun ne kohtasivat suurempia uhkia, joita organisoivat valtiot, ne ylivuotivat ja joutuisivat ulkopuolisten ryhmien monopolisoimaan hallintoon. Tällainen tilanne on toistunut yhä uudelleen: missä tahansa yhteiskunnassa, joka on muodostunut bandien ja heimojen tasoa korkeammalla, erityisesti silloin kun kauppareitit ovat tuoneet yhteen eri kansoja, on aina noussut väkivallan asiantuntijoita ryöstämään kaiken sen ylijäämän, jonka rauhallisemmat ihmiset pystyvät tuottamaan. Kun teknologiset olosuhteet nostivat väkivallan tuottoja, ne tuhosivat yhteiskuntia, jotka eivät olleet järjestäytyneet ohjaamaan suuria resursseja sodan valmistamiseen.

> "Mitkä prinssit tarjosivat poliisipalveluja? Mitkä olivat ptakkeroinnin tekijöitä tai jopa ryöstäjiä? Ryöstäjä voisi käytännössä nousta poliisipäälliköksi heti, kun hän säännöllisti ottamansa osuuden, mukautti sen maksukykyynsä, puolusti suojelualueensa muiden ryöstäjien vastustelta ja piti maantieteellisen monopolin tarpeeksi pitkään tai tavan mukaisesti saadakseen sen legitimiksi."[^217] – FREDERIC C. LANE

Hallitus suojelun myyjänä

Kuten olemme useaan otteeseen maininneet, hallituksen pääasiallinen taloudellinen tehtävä veronmaksajien näkökulmasta on tarjota suojaa elämälle ja omaisuudelle. Silti hallitus usein toimii kuin järjestäytynyt rikollisuus, keräten resursseja sen toiminta-alueella olevilta ihmisiltä kunnianalmaisesti tai ryöstäen. Hallitus ei ole pelkästään suojelupalvelu; se toimii myös suojeluryöstönä. Vaikka hallitus tarjoaa suojaa muiden aloittamaa väkivaltaa vastaan, se – kuten suojeluryöstössä – veloittaa asiakkailtaan myös suojaa siltä vahingolta, jota se muuten itse aiheuttaisi. Ensimmäinen toimi on taloudellinen palvelu, kun taas toinen on ryöstö. Käytännössä näiden kahden "suojelun" erottaminen toisistaan voi olla vaikeaa. Charles Tillyn mukaan hallitukset voidaan ehkä parhaiten ymmärtää ”suurimpina esimerkkeinä järjestäytyneestä rikollisuudesta.”[^218]

Jopa parhaimmat hallitukset harjoittavat usein jonkinlaista yhdistelmää suojaa tarjoavasta taloudellisesta palvelusta ja kiristyksestä. Historiallisesti molempia toimintoja olisi voitu optimoida, jos hallitus olisi voinut asettaa lähes monopoliaseman pakkokeinon käytölle niillä alueilla, joilla se toimii. Tapauksissa, joissa yksittäinen aseistettu ryhmä pystyi hallitsemaan väkivallan käyttöä, sen tarjoaman suojelupalvelun laatu oli yleensä paljon parempi kuin mitä saatiin, kun useat kilpailevat suojeluyritykset taistelivat samasta alueesta.

Luonnollinen monopoli maalla

Paikallisen pakkokeinon monopoliaseman saavuttaminen ei ainoastaan mahdollistanut hallitukselle tehokkaampaa suojelemista muiden aloittamaa väkivaltaa vastaan, vaan se vähensi myös hallituksen toimintakustannuksia huomattavasti. Kuten Lane totesi, "väkivallan käyttävän ja sen hallitsevan toimialan oli luonnollinen monopoli, ainakin maalla. Alueellisissa rajoissa sen tuottama palvelu voitiin tuottaa paljon edullisemmin monopoliasemassa."[^219] Näin ollen "yhtenäisellä, yhteensopivalla alueella vallinnut pakkokeinon käyttömonopoli mahdollisti suojelupalvelua tuottavan yrityksen parantaa tuotettaan ja vähentää kustannuksiaan."[^220] Tällainen hallinnollinen organisaatio pystyisi tarjoamaan enemmän suojaa pienemmillä kustannuksilla, jos sen ei tarvitsisi käydä loputonta sotilaallista taistelua kilpailevien ryhmien torjumiseksi, jotka pyrkisivät perimään suojelumaksuja sen asiakkailta.

Mahdollisuus, että informaatioteknologia auttaa "rentouttamaan" oletusta siitä, että suvereniteetin on perustuettava alueelliseen monopoliin, on jo herättänyt poliittisten teorioiden tutkijoiden huomion. Tämä teema on keskiössä David J. Elkinsin teoksessa *Beyond Sovereignty: Territory and Political Economy in the Twenty-First Century*. Elkins vahvistaa teesiämme siitä, että monopolivaltiot on tuomittu menettämään välikäsiensä rooli samalla tavalla kuin uskonnolliset monopolit menettivät asemansa 1500-luvun jälkeisinä vuosina. Hän kirjoittaa: 

"Aiemmin oletimme, että uskonnoilla tulisi olla oma alueensa tai 'aluevaltuu'. Kun kansakunnat alkoivat korvata yleismaailmalliset uskonnot elämän ja kuoleman suvereenina tuomarina, uskonnon 'kompaktiisuus' ja 'rajoitettuus' väistivät tutuiksi muodostuneelle uskovien sekoittumiselle samassa alueessa. Sen sijaan emme enää hyväksy kansakuntien – tai tässä tapauksessa maakuntien – sekoittumista, vaikka uskonkin, että tämä oletus on murentumassa."[^221]

Hän jatkaa väitellen, näkemyksemme mukaisesti, että alueelliset suvereniteetin monopolit voidaan purkaa ilman anarkiaa – kuten esimerkiksi kansallisten ja maakuntahallitusten välinen suvereniteetin jakautuminen liittovaltiollisessa järjestelmässä, kuten Kanadassa, ja joillakin Tyynenmeren saarella esiintyneen ranskalaisen ja brittiläisen yhteishallinnon tapauksessa. Näin ollen, vaikka alueellisia suvereniteetin monopoleja on harvoin hajotettu väkivallalla, ne voidaan purkaa sopimuksella. Elkinsin mukaan – ja me samaa mieltä ollaan – "alueellinen kansakunta on ollut nipun tai korin muotoinen kokonaisuus, johon muut elämämme osa-alueet on istutettu. Se on verrattavissa talousteorian 'hyödykepakkiin' – tavaroita ei voi helposti saada erikseen, vaan ne on otettava yhdessä. Ravintolassa voi tilata à la carte -annoksen; mutta identiteettimme osalta meidän on hyväksyttävä se, mitä kansakunnat ovat yhdessä niputtaneet, mikä vastaa 'table d'hôte' -periaatetta. ... A la carte -hallinnosta tulee luonnollinen kokemus 21. vuosisadalla."[^222]

Ei mikään kehitys ole yhtä dramaattisesti edesauttanut suvereniteetin eriytymistä ja a la carte -hallinnon nousua kuin kyber-talouden synty, joka kokonaan ylittää fyysiset rajat.

> "Kun taajuudet kasvavat ja aallonpituudet lyhenevät, digitaalinen suorituskyky paranee eksponentiaalisesti. Kaistanleveys kasvaa, virrankulutus kutistuu, antennin koko pienenee, häiriöt romahtavat ja virheprosentti laskee."  
> – George Gilder

## TELEKOSMIN LAKI PURKAA KANSOJEN LAIT

Emme ole yksin siinä, että kaistanleveys (tai viestintävälineiden kapasiteetti) on väistämättä tarkoitettu syrjäyttämään aluevaltiot. Jim Taylor ja Watts Wacker, teoksensa *The 500-Year Delta: What Happens After What Comes Next* kirjoittajat, eivät määrittele argumenttia samalla tavalla kuin me, mutta he myöntävät, että "pääsy luo globalismia, ja globalismi häiritsee poliittisia järjestelmiä, tehden rajojen käsitteen vanhentuneeksi. Kun rajat katoavat, verotuksen käsitteen – joka tukee hallituksia – fyysisyys muuttuu yhä hauraammaksi... Kun rajat katoavat, oikeuksien käsite – usko siihen, että koska olet syntynyt tietyssä paikassa, sinulla on oikeus siihen alueeseen liittyviin taloudellisiin etuihin – romahtaa, ja sen romahtaessa myös kansallisuuden edut hajoavat. Ja kaiken tapahtuaessa ne puitteet, joiden varaan kansallisuus on rakennettu – isänmaallisuus, demokratia, valtio, sulatusuuni, yhtenäisyys, vastuullinen osallistuminen, tai mitä tahansa muussa muodossa, missä tahansa kansassa elämmekään – siirtyvät historiaan romukasan joukkoon."[^223]

Ilman sitä, että sitä sanottaisiin suoraan, hekin aavistavat, että historia kulkee kohti suvereenin yksilön vapautumista. Kuten he sanovat, "Horisontissa odottaa paljon puhtaampi yksilöllisyyden muoto kuin nyky-demokratian sallima."[^224] Kuinka tämä tapahtuu? Taylor ja Wacker näkevät tässä toiminnassa voimakkaan dynaamisen voiman.

Yksinkertainen tosiasia on, että suurempi isänmaallisuuden tunne – rakkaus omaa maataan kohtaan ja siihen kohdistuva velvollisuudentunne – ei enää ole erityisen hyödyllinen asenne... Globaaleissa yhteiskunnissa menestyvät kansalaiset valitsevat identiteettinsä perustuen suoraan poliittisiin, sosiaalisiin ja taloudellisiin elämyksiin, eivätkä vain siihen, että he ovat samanlaisia kuin muut, vaan sen mukaan, miten nämä valinnat vaikuttavat itseihin. He järjestäytyvät vapauden – tiedon, liikkumisen, tekemisen ja olemisen – maksimoimiseksi. Kansakunnat ja yritykset, jotka eivät toimi näin, ja jotka jatkavat menneisyyden taaksepäin suuntautuneita toimia nostalgian perusteella, rappeutuvat.[^225]

Fyysisten rajojen arvon lasku, jonka merkkinä on kaistanleveyden kolminkertaistuminen vuosittain ja internetin sekä World Wide Webin geometristen suhteiden kasvu, nopeuttaa hallitusten välittäjäporukan poistamisprosessia. Todellisuudessa, jos kaistanleveyden vuotuinen kolminkertaistuminen jatkuisi vuoteen 2012 saakka, se tarkoittaisi miljardinkertaista kasvua vuodesta 1993 – kun George Gilder ensimmäisenä ehdotti, että kaistanleveyden kasvu olisi jopa nopeampaa kuin mikroprosessorien kapasiteetin kehitys. Jos tämä toteutuu – kuten uskomme sen tapahtuvan viimeaikaisten integroidun optiikan läpimurtojen perusteella – syntyvä massiivinen viestintäkyvyn ylijäämä johtaisi uskomattomaan kasvuun kyberkaupassa. Aaltopohjaisessa jakomultiplexauksessa yksittäinen kuitu, yhtä ohut kuin ihmiskarva, kykenee siirtämään biljoona bittiä sekunnissa,[^226] eli käytännössä yksi kuitukaapeli pystyy kuljettamaan 25 kertaa enemmän bittejä kuin kaikkien maailmalla toimivien viestintäverkkojen yhteenlaskettu kapasiteetti. Laajentumismahdollisuus on hämmästyttävä. Kun näin valtava viestintäkapasiteetti vapautuu, viestintään käytettävään rahaan kuluu huomattavasti enemmän, koska se tulee halpaa. Myös vakiintuneet mediat, kuten erikoistettu puhelinverkko ja televisio, muuttuvat ajan saatossa anakkalaisiksi. World Wide Web toimittaa jokaiselle tietokoneelle rikkaamman signaalisekoituksen kuin mitä nykyinen verkko-tv tarjoaa kuluttajille. Kaistanleveyden vallankumouksen edetessä yhä useammat ihmiset vetäytyvät rajattomaan virtuaalimaailmaan, jossa verkkoyhteisöt ja kyberkauppa kukoistavat – maailmaan, jossa graafinen tiheys on niin suuri, että siitä muodostuu niin kutsuttu "metaverse", se vaihtoehtoinen kyberavaruuden todellisuus, jota tieteiskirjailija Neal Stephenson on kuvitellut. Stephensonin "metaverse" on virtuaaliyhteisö, jolla on omat lakinsa, prinssinsä ja pahiksensa.[^227] Ja kun yhä enemmän taloudellista toimintaa vetää puoleensa kyberavaruus, valtion rajojen sisällä toimivan monopolin arvo pienenee, mikä antaa valtioille kasvavan kannustimen jakaa ja pirstoutua omassa suvereniteetissaan.

Aivan kuten kansallisvaltioilla on nykyään kannustimia isännöidä vapaakauppaportteja, vapaakauppa-alueita ja zona francoja, niillä on myös kannustimia vuokrata suvereniteettinsa. Olemme jo käsitelleet edistyneitä neuvotteluja läheisesti seuranneen 900-vuotiaasta Jerusalemissa, Rhodoksella ja Maltalla toimivan Sovereign Military Hospitaller Order of St. John of Jerusalem -järjestön – joka tunnetaan yleisemmin Malta-ritareina – ja Maltan tasavallan välillä, joiden tavoitteena on palauttaa Fort St. Angelon suvereniteetti tälle järjestölle. Odotamme näiden neuvottelujen onnistunutta päättymistä, ja muita seuraa. Jotkut kansallisvaltioista luovuttavat suvereniteetistaan pienille enklaaveille ja syrjäisille alueille täysin uusille yhtenäisyysryhmille ja virtuaaliyhteisöille. Itse asiassa ei ole epätodennäköistä, että kaupalliset toimijat, kuten turvallisuusyritykset ja hotelliketjut, kilpailevat pienistä maa-alueista suvereniteetista. Esimerkiksi Wackenhut, Pinkerton ja Argenbright saattavat tulevaisuudessa tarjota hybridimuotoisia aidattuja eläkeläisyhteisöjä ja verovapaita vyöhykkeitä houkuttelevissa ilmastoissa ympäri maailman. Uskonnolliset laitokset – Malta-ritareihin verrattuna, mutta edustaen kaikkea mahdollisia tiedekuntia – pyrkivät omilla tavoillaan tekemään taivaasta inkarnaation tietyissä syrjäisissä maan kulmissa. Jopa varakkaat yksilöt ja perheet tulevat omistamaan omia alueitaan, joissa he harjoittavat rajoitettua suvereniteettia, myöntävät omat postimerkkinsä ja passinsa sekä ylläpitävät verkkosivustoa.

## MONOPOLY JA RYÖSTÖ

Huomaa, että kannustimet jakaa tai vuokrata suvereniteettia maksua vastaan eroavat merkittävästi niistä, joita historiallisesti hallitsijoilla on ollut, kun he ovat joutuneet sotilaallisen kilpailun alaisuuteen paikallisen pakottamisen monopolin kanssa. Vuokrattu suvereniteetti ei ole vakauttavaa enempää kuin vapaakauppa-alueen isännöinti. Sen sijaan sotilaallinen kilpailu vallasta – sellainen, jota taistelevat sotapäälliköt ja sissiryhmät harjoittavat – vaikuttaa suoraan siihen, onko potentiaalisella hallituksella vahvemmat kannustimet suojella alueensa ihmisiä vai ryöstää heitä. Siellä, missä kilpailevat ryhmät kamppailevat epävakaassa tasapainossa, kannustimet saalistavaan väkivaltaan kasvavat. Ryöstö muuttuu houkuttelevammaksi. Koska valta ei ole yhtä vakaata ja paikallinen pakottamisen monopoli on heikompi, niiden, joilla on kyky käyttää väkivaltaa, aikahorisontti kutistuu. "Vuoren kuningas" voi seisoa niin liukkaalla rinteellä, ettei hän voi odottaa selviävänsä tarpeeksi kauan saadakseen osuutensa niistä merkittävistä hyödyistä, jotka lopulta syntyvät väkivallan hillitsemisestä. Tällöin hyvin harvoin pysäyttää niitä, jotka johtavat niin kutsutun hallituksen nimissä, käyttämästä valtaansa terrorisoidakseen ja ryöstääkseen yhteiskuntaa.

Voiman logiikka siis kertoo, että mitä enemmän kilpailevia aseellisia ryhmiä toimii missä tahansa alueella, sitä todennäköisempää on, että ne turvautuvat saalistavaan väkivaltaan. Ilman yhtä ylivoimaista voimaa tukahduttamaan irrallista väkivaltaa se leviää, ja monet taloudellisen ja sosiaalisen yhteistyön hyödyt menevät savuilemaan.

Väkivallan täydellinen vapaus anarkian tilassa voi aiheuttaa valtavia tuhoja – tätä käy ilmi Kiinan kohtalosta sota-johtajien aikaan 1920-luvulla. Tämä on tarina, jonka kerroimme teoksessamme **The Great Reckoning**. Kilpailevat sota-johtajat aiheuttivat suuria vahinkoja alueilla, joilla ei ollut yhtä ainoaa ylivoimaista voimaa pitämään heitä kurissa.

Vastaavia tarinoita, jotka havainnollistavat samaa seikkaa, on esitetty värinäytteinä CNN:n uutiskuvaajien toimesta, kun he uhmaavat Mogadishun katuja Somalissa. Somalian sota-johtajien asevoimat, joiden lempinimi on "tekniset", toivat anarkian tuohon surulliseen maahan, ennen kuin Yhdysvallat johti valtavaa sotilaallista interventiota niiden hillitsemiseksi. Kun Yhdysvaltojen joukkojen mahtava läsnäolo vetäytyi, tekniset ottivat aseensa jälleen käyttöön, ja anarkia palasi. Washington Postin raportissa todettiin:

> [P]ickup-kuorma-autot, joihin on asennettu ilmatorjunta-aseita, peltävät jälleen pölyisiä, rauniollisia katuja. Myös T-paitoja ja Kalashnikov-rynjää kantavat röyhkeät nuoret miehet ovat palanneet, kiristäen rahaa ohitse ajavista autoista ja busseista tilapäisillä tienvarsitormenteilla. Yksi tässä militsioiden hallitsema naapurusto on niin voimakkaasti aseistettu, että paikalliset kutsuvat sitä "Bosnia-Herzegovinaksi." Tämän kaupungin anarkisilta kaduilta liikkuminen tänään muistuttaa hämmästyttävästi vuotta 1992, jolloin kilpailevien militsioiden kaoottinen sota upotti Somalian anarkiaan sekä nälkään, mikä johti Yhdysvaltojen johtamaan sotilaalliseen interventioon. Jälleen kerran, Mogadishun läpi kulkemiseksi matkustajien on vuokrattava autolla aseistettu joukko röyhkeitä rikollisia, toivoen saavansa suojelua sadalla dollarilla päivässä sekä lounastauon.

Esimerkit Somaliasta, Ruandasta ja muista maista, joita näet pian televisiossa, tarjoavat värikkään todisteen siitä, että väkivaltainen kilpailu alueiden hallinnasta ei tuota samaa välitöntä taloudellista hyötyä kuin muut kilpailun muodot. Päinvastoin – anarkiassa kilpailevilla vaeltavilla rosvoilta ja ryöstäjiltä puuttuvat edes heikotkin kannustimet suojella tuottavaa toimintaa, joita joskus edes diktaattorien ankara käsi kevenee, kun heidän valtansa on vakaalla pohjalla.

> "Modernin ajan yhteiskuntaa, erityisesti lännessä, leimaa tietynlainen monopolisoinnin taso. Yksilöltä evätään vapaa pääsy sotilaallisten aseiden käyttöön, ja se on varattu keskitetylle vallalle, minkä tyyppistä tahansa se onkaan, kuten myös yksilöiden omaisuuden tai tulojen verotus on keskitetty keskeisen sosiaalivallan käsiin. Näin keskusvirtaan virtaavat taloudelliset voimavarat ylläpitävät sen sotilasvoiman monopolia, joka puolestaan ylläpitää verotuksen monopolia. Kumpikaan ei asetu toisensa edelle; ne ovat saman monopolin kaksi puolta. Jos toinen katoaa, seuraa toinen automaattisesti; monopoli voi joskus heikentyä toisella puolella enemmän kuin toisella." [^229]  
– NORBERT ELIAS

## SUOJELUN KEHITYS

Lane kehitti argumentin, jota olemme omiin tarkoituksiimme väärinkäyttäneet kuvitellessamme, miten tietoyhteiskunta saattaa kehittyä. Hän väitti, että Lännen talouksien historia synkiltä ajoilta lähtien voidaan tulkita neljän kilpailua ja monopolia koskevana vaiheena väkivallan organisoimisessa. Vaikka Lane pysyttelee suurelta osin hiljaa niistä megapoliittisista tekijöistä, joita pidämme vaikuttavina hallitusten toimintakohdassa, hänen tarkastelunsa väkivallan taloudellisesta puolesta osuu tiiviisti yhteen sen argumentin kanssa, jonka esittelimme teoksissa *Blood in the Streets* ja **The Great Reckoning**; ja muualla tässä osassa.

Olemme jo analysoineet joitakin megapoliittisia tekijöitä, jotka vaikuttivat Lännen yhteiskunnan kehitykseen Rooman romahduksen jälkeen. Lane tarkasteli myös tätä ajanjaksoa, keskittyen väkivallan monopolisoimiseen tähtäävän kilpailun taloudellisiin seurauksiin. Hän erotti neljä tärkeää vaihetta talouksien toiminnassa viimeisen vuosituhannen aikana, joista jokaisessa ilmenee eri vaihe väkivallan organisoinnissa.[^244]

### Synkistä ajoista ulos

Ensimmäinen vaihe on "anarkian ja ryöstön" aika, joka määritteli feodaalisen vallankumouksen vuosisataa sitten. Vaikka Lane ei anna tarkkoja päivämääriä yhteenvetovaiheilleen, laskutoimitukset asettavat ensimmäisen jakson rajat melko selvästi, ja hänen kuvauksensa "anarkian ja ryöstön" vaiheesta vastaa niitä olosuhteita, jotka vallitsivat synkistä ajoista siirtymisen aikana, jolloin väkivallan käyttö oli "äärimmäisen kilpailullista, jopa maalla."[^230] Hän ei erittele syitä, mutta kun väkivalta on "äärimmäisen kilpailullista", se yleensä tarkoittaa, että etäisyydellä vallan projisoinnissa on merkittäviä esteitä; sotilaallisessa mielessä puolustuksella on etusija hyökkäykseen nähden.

Kuten luvussa 3 selitimme, tämä "anarkian ja ryöstön" vaihe osui maatalouden tuottavuuden laskuun epäedullisten ilmastomuutosten seurauksena. Koska teknologia tuolloin tarjosi vain vähän tehokkaita mittakaavaetuja, jotka auttoivat turvaamaan väkivallan monopoliasemaa, kilpailu valloitusoikeuden tavoittelijoiden kesken oli laajalle levinnyttä. Taloudellinen toiminta tukahduttiin.

Heikon talouden heikensi vakaiden järjestyksen perustamisen ongelmaa entisestään. Paikallisen väkivallan monopolin luominen vaati suhteettoman suuria sotilaallisia kustannuksia, kun otetaan huomioon taloudellisen kierron vähäinen arvo. Ilman kykyä valvoa tehokasta monopolia taloudellisesti kannattavalla alueella aseistetut ratsurit tekivät kauhistuttavaa ja ryöstivät samalla, kun he tarjosivat vain vähän "suojelua" asiakkaidensa käyttöön.

### Feudalismi

"Toinen vaihe alkaa, kun perustetaan pieniä alueellisia tai maakunnallisia monopoleja. Maataloustuotanto kasvaa silloin, ja suurin osa ylijäämästä päätyy äskettäin nousseiden väkivallan monopolistien käsiin."[^231] Silti ylijäämä on suhteellisen vähäinen tässä toisessa vaiheessa, jota pidämme varhaiskeskiaikana. Talouskasvua hillitään skaalaetuuksien puutteella väkivallan järjestämisessä, mikä pitää paikallisten monopolien sotilaalliset kustannukset korkeina. Kun kustannukset pysyvät korkeina, pienien itsehallintoalueiden asettama suojelemismaksu nousee, sillä taloudellinen toiminta laajenee kaaoksen rajoittamisen myötä.

Toisen vaiheen myöhäisvaiheessa monet tributea perivät tahot houkuttelivat asiakkaita erikoistarjouksilla maatalouden ja kaupallisen toiminnan osalta. He tarjoten suojaa alhaisilla hinnoilla niille, jotka saavat uusia maa-alueita viljelyn alle, sekä erikoispoliisipalveluja kaupan edistämiseksi, kuten Champagne'n kreivit järjestivät messuilleen saapuville kauppiaille.[^232] Toisin sanoen, kun he pystyivät saavuttamaan riittävän aluevallan uskottavaa neuvottelua varten, paikalliset sotapäälliköt tekivät kuten tavalliset kauppiaat, jotka alentavat hintojaan kasvattaakseen markkinaosuuttaan. Myöhemmin sotapäälliköt hyödynsivät lisäresursseja kasvavasta taloudellisesta toiminnasta voidakseen vahvistaa hallintaansa laajemmilla alueilla. Kun tämä hallinta vakiintui, he alkoivat nauttia monopolin eduista: heidän sotilaalliset kustannuksensa poliisoinnista pienenivät, ja he pystyivät nostamaan veloittamiaan hintoja ilman, että palvelunsa vähempänä houkuttelevuus karkasi.

Tässä monimutkaisessa vaiheessa länsimaisessa historiassa ne, jotka käyttävät väkivaltaa – keskiaikaiset herrat ja kuninkaat – keräävät suurimman osan elinkustannusten ylittävästä ylijäämästä. Kauppiaita on vähän, ja menestyneimmät ovat niitä, jotka kykenevät parhaiten välttämään tai minimoimaan verojen, maksujen ja muiden "suojelupalveluista" perittävien kustannusten vaikutuksen.

### Varhaismoderni aika

Kolmas vaihe saavutetaan, kun ne kauppiaat ja maanomistajat, jotka eivät ole erikoistuneet väkivallan käyttöön, saavat suuremman osuuden talouden ylijäämästä kuin maanpitäjät ja monarkit… Tässä kolmannessa vaiheessa väkivallan käyttöön erikoistuneet toimijat saavat vähemmän ylijäämää kuin ne, jotka ostavat suojaa hallituksilta.[^233] Koska menestyneemmät kauppiaat sijoittavat voittonsa todennäköisemmin uudelleen sen sijaan, että kuluttaisivat ne, tämän vaiheen aikana kauppiaiden korkeammat voitot johtivat itseään vauhdittavaan kasvuun.

### Tehdasaika

Lane yhdistää kolmannen ja neljännen vaiheen välisen siirtymän teknologisten ja teollisten innovaatioiden nousuun, jotka tulivat tärkeämmiksi voittojen saavuttamisessa kuin suojelukustannusten alentaminen. Tällöin hän viittaa ilmeisesti vuodesta 1750 alkaen. Siitä lähtien teknologian rooli alueiden vauraudessa alkoi olla ratkaiseva. Äärimmäisenä esimerkkinä voidaan mainita, että jopa alueet, joilta hallitusta ei ollenkaan ollut – kuten joillakin Uuden-Seelannin osilla ennen vuotta 1840 – eivät todennäköisesti nousseet erittäin vauraiksi pelkästään siksi, että niiltä ei peritty veroja. Tuolloin teollisuusteknologian innovaatiot olivat tärkeämpiä voittojen saavuttamisessa kuin millään suojelukustannuksia alentavilla säästöillä, jopa silloin kun kustannukset olisivat voineet laskea nollaan. Valtion koon kasvaessa hallitusten alkuperäisistä sotilaallista toimintaa varten kehittämistään luotto- ja rahoitusmekanismeista tuli mahdollisuus rahoittaa laajamittaisempia liiketoimintaorganisaatioita. 

Vaikka Lane ei niitä suoraan mainitse, teknologisten etujen keskittyminen tietyllä alueella vähensi eri toimivaltaisten alueiden välistä kilpailua ja mahdollisti sen, että väkivallan käyttöön erikoistuneet toimijat eli hallitukset pystyivät perimään korkeampia hintoja. Kun kilpailijoiden välillä on suuria teknologisia eroja, kuten teollisuusajan aikana oli, parhaan teknologian omaavien alueiden yrittäjät tekevät yleensä enemmän rahaa, vaikka heidänkaan joutukin maksamaan korkeampia veroja ja muita kustannuksia hallituksilleen.

### Ryöstö hymyssä

Teollisen aikakauden hallituksilla oli hurmaava monopoli hyväksikäyttöön. Niiden todelliset kustannukset elämän ja raajoituksen suojelemiseksi olivat häivähtelevän pienet verrattuna niihin hintoihin (veroihin), joita ne perivät. Niinpä ne toimivat olosuhteissa, joissa kilpailu oli niin kierrettyä, että ne pystyivät harjoittamaan paljon enemmän ryöstöä kuin suojelua – ja tästä jokin ei juuri jäänyt huomiotta. Se oli harvinainen hetki historiassa.

Teollistumisen suurpoliittisissa olosuhteissa vallinnut anarkia teki saman alueen sisäisestä suojelupalveluiden kilpailusta teknologisesti mahdotonta. Ainoa tapa saavuttaa tehokas suoja näissä olosuhteissa oli hallita entistä suurempaa kykyä käyttää väkivaltaa. Siksi oli vähän hyötyä yrittää erottaa tarkemmin se osa veroista, joka Lanein mukaan on "maksettu tehdystä palvelusta" toisesta osasta, jota on houkuttelevampi kutsua ryöstöksi.[^234] Erotus oli kyllä riittävän selvä, mutta koska veroja joutui maksamaan joka tapauksessa, sen täydellinen kehittäminen jäi enimmäkseen morbideen uteliaisuuden tyydyttämiseksi. Kuten Lane totesi, riippumatta siitä mikä osa veroista luokitellaan ryöstöksi, ne olivat hinta, jonka piti maksaa "vakavampien menetysten välttämiseksi."[^235]

### Tulot nousivat teollistumisen myötä

Osa syystä, miksi tämä dilemma oli siedettävä viimeisten kahden vuosisadan aikana kansallisvaltioiden hallitessa, johtui siitä, että tulot nousivat dramaattisesti – erityisesti niillä alueilla, joihin suurin osa teollisesta kehityksestä oli rajoittunut. OECD-hallituksia hoitavat ottivat lähes joka vuosi suuremman osan tuloista. Ryöstön kasvua seurasi kuitenkin vielä paljon suurempi vauraus sekä entistä jyrkempi varallisuuserojen kasvu maailman muihin osiin nähden. Tällaisissa olosuhteissa vastalauseet verotuksen kasvulle olivat väistämättä reunalla, eivätkä kyenneet ohjaamaan tapahtumien loogista kehitystä toiseen suuntaan. Todellisuudessa, kuten aiemmissa luvuissa on selitetty, teollisen kansallisvaltion sotilaallinen selviytyminen perustui pitkälti siihen, ettei sen kansalaisten resursseihin kohdistuville vaatimuksille voitu asettaa tehokkaita rajoja.

Jokaisessa teollisuusvaltiossa politiikka kulki suunnilleen samaan suuntaan. Teollistumisen huipulla toisen maailmansodan jälkeen marginaaliverojen määrät nousivat 90 prosenttiin tai jopa yli. Tämä oli paljon aggressiivisempi väite valtion oikeudesta kerätä resursseja kuin edes varhaisten hydraulisten sivilisaatioiden itämaiset despotit uskalsivat esittää. Teollisuuden ryöstö sai kuitenkin oman logiikkansa: suuri osa siitä määräytyi 1900-luvun ensimmäisen puoliskon teollisuusteknologian luonteen mukaan, kuten aiemmin kuvasimme.

Tämä teknologia teki lähes väistämättömäksi sen, että valtio ottaisi haltuunsa ja jaksottaisi suuren osan tuloista, jolloin suuri osa ryöstön taakasta kohdistuisi pieneen osaan kapitalisteja. Useimmat teolliset prosessit olivat voimakkaasti riippuvaisia luonnonvaroista ja siten sidottuja niihin paikkoihin, joissa nämä varat sijaitsivat. Teräsmillan, kaivoksen tai sataman siirtäminen oli mahdollista vain valtavien kustannusten tai lainkaan, minkä vuoksi tällaiset laitokset olivat paikallaan pysyviä kohteita, joita voitiin verottaa helposti. Omaisuus-, yritys- ja irtisanomismaksut kasvoivat jyrkästi tämän vuosisadan aikana. Sama kehitys näkyi myös tuloveroissa, aluksi kapitalisteilla, mutta lopulta myös työntekijöillä. Laajamittainen teollinen työllisyys teki laajakantoisesta tuloverosta käytännöllisen: palkkoihin voitiin kohdistaa veronpidätys jo suoraan lähteeltä, sillä veroviranomaiset koordinoivat perätykset teollisuusyritysten laskentatoimien kanssa. Otamme tämän nykyään itsestäänselvyytenä, mutta tuloveron kerääminen tehtaan portilla oli paljon yksinkertaisempi toimenpide kuin museilemalla maaseutua saadakseen osan miljoonien itsenäisten käsityöläisten ja maanviljelijöiden voitoista.

Yhteenvetona teollisuusteknologia pyrki tekemään verotuksesta rutiininomaisempaa, ennustettavampaa ja vähemmän henkilökohtaisesti vaarallista kuin monissa aikaisemmissa aikakausissa. Siitä huolimatta se keräsi yhteiskunnan resursseista suuremman osuuden kuin mikään aiemmin koettu suvereniteetin muoto.

### Suojella mitä?

Se, että yhteiskunnat pystyivät rikastumaan samalla kun verojen kokonaisosuus tuloista nousi merkittävästi, herättää kysymyksen: mitä hallitukset suojasivat teollisuustalouksille? Vastaus on: ensisijaisesti teollisuuslaitoksia, joilla oli korkeat pääomakustannukset ja merkittävä alttius hyökkäyksille. Suurten teollisuusyritysten olemassaolo ei olisi ollut mahdollista kaaoksen vallassa, jossa kilpailullinen väkivalta olisi ollut yleisempää, vaikka kilpailun tuloksena olisi pienenemässä ollut valtion ottaman tuotannon osuus.

Kapitaalimääräiset toiminnot ovat siksi taloudellisesti kannattamattomia amerikkalaisissa slummeissa sekä kolmannen maailman yhteiskunnissa, joissa satunnaista väkivaltaa esiintyy kroonisesti. Teollisyhteiskunta pystyi kokonaisuudessaan etenemään, koska siihen otettiin käyttöön ja sitä ylläpidettiin tietynlainen järjestys. Yritykset altistuivat säännöllisille, ennustettavissa oleville kiristyksille sen sijaan, että niihin kohdistuisi arvaamatonta väkivaltaa.

Jopa teollistumisen huipulla oli aina liioiteltua puhua hallituksesta, joka käyttäisi “voiman monopolia.” Kaikki hallitukset pyrkivät ylläpitämään tällaista monopolia, mutta kuten on nähty, teollisuusyritysten työntekijät havaitsivat usein voivansa käyttää väkivaltaa työnantajiaan vastaan. Niin kauan kuin yleisöllä on edes jonkinlaisia aseita käytössään tai kun epäjärjestyksessä oleva väkijoukko pystyy fyysisesti kaatamaan bussin tai heittämään kiviä poliisille, hallituksen hallitsijat eivät täysin monopoloi voimaa. He hallitsevat vain ylivoimaista väkivaltaa, joka on sellaista, että nykyisissä olosuhteissa useimmille ihmisille ei ole taloudellisesti kannattavaa kilpailla heidän kanssaan.

> Verkkopohjainen hallitus voi toimia vain kansalaisten suostumuksella. Siksi minkä tahansa verkkohallituksen on tarjottava kansalaisilleen todellisia etuja, jos se haluaa, että he pysyvät mukana. Nämä edut eivät välttämättä tarkoita ainoastaan henkilökohtaisia tavaroita tai palveluita, vaan pikemminkin sääntelyjärjestelmän laajempia hyötyjä: puhdas, läpinäkyvä markkinapaikka, jossa on määritellyt säännöt ja seuraamukset, tai valvottu yhteisö, jossa lapset voivat luottaa kohtaamiinsa ihmisiin ja yksityisyyttä kunnioitetaan.

### Tietoaika

Tietoaika tuo mukanaan kilpailun kehityksessä viidennen vaiheen väkivallan käytössä lännessä. Tätä vaihetta Lane ei ennakoinut. Viides vaihe käsittää kilpailua kyberavaruudessa, jota mikään “väkivaltaa käyttävä yritys” ei voi monopolisera, koska se ei ole alueellinen.

Vaikka Lanen argumentti sisältää perinteisiä jälkisodan oletuksia kansallisvaltion väistämättömyydestä, hän huomasi kiinnityskohdan, joka on tulevaisuuden ymmärtämisen kannalta ratkaisevampi kuin se ehkä vaikutti neljä- tai viisikymmentä vuotta sitten. Kyse on siitä, että hallitukset eivät ole koskaan pystyneet perustamaan vakaata pakottamisen monopolia avoimelle merelle. Mieti sitä: yksikään hallitus ei ole koskaan soveltanut lakejaan siellä yksinomaan. Tämä seikka on äärimmäisen tärkeä, kun ymmärrämme, miten väkivallan ja suojelun järjestäytyminen kehittyy talouden siirtyessä kyberavaruuteen, jolla ei ole lainkaan aineellista olemassaoloa. Niistä syistä, jotka Lanne havaitsi – eli siitä, ettei mikään hallitus ole pystynyt monopolisoimaan meren väkivaltaa – on vielä epätodennäköisempää, että hallitus voisi menestyksekkäästi monopolisoida äärettömän, fyysisistä rajoista vapaan ulottuvuuden.

## KILPAILU ILMAN ANARKIAA

Aiemmin, kun olosuhteet tekivät vaikeaksi minkä tahansa yksittäisen väkivallan käyttävän toimijan mahdollisuuden perustaa monopolia, seurauksena oli anarkiaa ja ryöstöä. Tietotekniikan aikakausi on kuitenkin muuttanut perusteellisesti ne teknologiset ehdot, joiden puitteissa väkivalta järjestäytyy. Toisin kuin menneisyydessä alueen suojelun monopolisoimisen kykenemättömyys johti korkeampiin sotakustannuksiin ja matalampiin taloudellisiin tuottoihin, se tosiasia, että hallitukset eivät voi monopolisoida kyberavaruutta, tarkoittaa itse asiassa alempia sotakustannuksia ja korkeampia taloudellisia tuottoja. Tämä johtuu siitä, että tietotekniikka luo uuden ulottuvuuden suojeluun: ensimmäistä kertaa historiassa se mahdollistaa omaisuuserien luomisen ja suojaamisen, jotka sijaitsevat täysin minkään yksittäisen hallituksen alueellisen väkivalta-monopolin ulkopuolella.

> "Maat, joissa poliittisen vallan ja hallinnon yksiköt ovat useita ja joissa ei ole keskeistä, vakaata ja kiistämätöntä valvontakeskusta, joutuvat kehittämään omia toimivia ratkaisuja käsitelläkseen tällaisten rajojen asettamia ongelmia."[^237]: - REES DAVIES

### Vertaus rajasta

Kyberavaruus on eräässä mielessä samanlainen kuin teknologisesti suojattu rajaseutu, sellainen alue, joka keskiajalla sijaitsi raja-alueilla. Aikoinaan, kun herrojen ja kuninkaiden valta oli heikkoa ja yhden tai useamman vaatimukset ylittyivät rajalla, vallassa oli jonkinlaista kilpailua muistuttavaa hallintoa. Katsaus siihen, miten tällaiset rajaseudut toimivat, voisi antaa oivalluksia siitä, miten vastaavia "rajan lakeja" tai niiden kaltaisia sääntöjä saattaisi siirtyä kyberavaruuteen.

Andorra säilyy eräänlaisena fossilisoituneena rajaseutuna Ranskan ja Espanjan välillä – artefaktina megapoliittisista olosuhteista, jotka tekivät kummankaan kuningaskunnan hallinnan saavuttamisesta haastavaa kyseisellä kylmällä ja lähes saavuttamattomalla 190 neliömailan alueella Pyreneillä. Vuonna 1278 solmittiin sopimus, jossa Andorran ylivalta jaettiin paikallisten ranskalaisten ja espanjalaisten feodaaliherrien, Foixin ranskankreivin ja Urgelin espanjalaisen piispan, kesken. Kumpikin nimitti yhden kahdesta "viquieristä", jotka harjoittivat säästeliäästi Andorran hyvin rajallista hallinto-oikeutta – enimmäkseen komentamalla pientä andorralaista militiää, joka on nykyään poliisivoima. Kreivin rooli jäi kauan sitten historiaan, ja nyt Ranskan hallitus toimii hänen tilanaan Pariisista. Sen tehtäviin kuuluu muun muassa hyväksyä puolet Andorran maksamasta vuotuisesta tributeista, summa, joka on alle yhden kuukauden vuokra köyhälle asunnolle. Urgelin piispa saa edelleen oman osuutensa tributeista, aivan kuten hänen esi-isänsä tekivät keskiajalla.

Jaetun tributein perusteella Andorrassa on ollut kaksi "valvonta- ja valvontavallan" lähdettä sen sijaan, että olisi ollut vain yksi. Andorran siviilioikeudelliset valitukset on perinteisesti tehty joko Urgelin Piispa-kollegioon tai Pariisin Cassation-tuomioistuimeen.

Andorran epäselvän aseman seurauksena lähes mitään lakeja ei ole säädetty. Andorra on nauttinut lähes olemattomasta hallinnosta ja verottomuudesta yli seitsemän sataa vuotta. Nykyään tämä tekee siitä yhä houkuttelevamman veroparatiisin, vaikka vielä sukupolven verran sitten Andorra oli kuuluisasti köyhä. Aikoinaan tiheä metsäisyys raivattiin vuosisatojen aikana asukkaiden toimesta, jotka yrittivät pysyä lämpiminä katkeroituneissa talvissa. Koko alue on lumessa suljettu marraskuusta huhtikuuhun joka vuosi, ja jopa kesällä Andorra on niin kylmä, että viljelyä tapahtuu vain etelärinteillä. Jos tämä kuvaus saa alueen vaikuttamaan epämiellyttävältä, olet juuri oppinut menestyksen salaisuuden: Andorra selviytyi feodaalisena pesäkkeenä kansallisvaltion aikakaudella juuri siksi, että se on syrjäinen ja äärimmäisen köyhä.

Aikoinaan Euroopan raja-alueilla oli lukuisia keskiaikaisia rajaseutuja eli "march-alueita", joissa suvereniteetit sulautuivat toisiinsa. Nämä väkivaltaiset rajat säilyivät vuosikymmenten tai jopa vuosisatojen ajan Euroopan raja-alueilla, ja useimmat näistä alueista olivat köyhiä. Kuten aiemmin mainitsimme, Irlannissa oli rajaseutuja kelttien ja englantilaisten hallinnan välillä; Walesin ja Englannin, Skotlannin ja Englannin, Italian ja Ranskan, Ranskan ja Espanjan, Saksan sekä Keski-Euroopan slaavien rajojen välillä sekä Espanjan kristillisten ja Granadan islamilaisen kuningaskunnan välillä. Näillä march-alueilla, aivan kuten Andorrassa, kehittyivät omaleimaiset instituutiot ja oikeudelliset muodot, joita saatamme nähdä taas seuraavalla vuosituhannella.

Koska kahden heikon viranomaisen kilpailuasetelma johti siihen, että hallitsijat saattoivat joissakin tapauksissa pyytää alamaisiaan vapaaehtoisina asettumaan vartioalueille lisätäkseen valtansa ulottuvuutta, houkuttelevina kannustimina palvelijoille toimi käytännössä verovapaus. Kilpaillessaan hyvin kapeilla rajoilla, jos jompikumpi vartioalueella toimiva viranomainen yrittäisi määrätä veroja, se vaikeuttaisi seuraajiensa elinkeinon hankkimista ja antaisi kaikille syyn liittää itsensä hänen kilpailijansa puolelle. Siksi vartioalueella asuvilla ihmisillä oli tavallisesti mahdollisuus valita, kenen lakeja he noudattaisivat. Tämä valinta perustui kilpailevien viranomaisten heikkouteen eikä ollut ideologinen ele.

Käytännön haasteita nousi kuitenkin ratkaistavaksi. Feodaalijärjestelmässä maanomistajat, joilla oli omaisuutta nimellistä rajaa molemmilla puolilla, kohtasivat vakavia velvollisuusristiriitoja. Esimerkiksi Skotlannin ja Englannin rajalla toimiva herra, jolla oli kiinteistöjä kummassakin kuningaskunnassa, saattoi sodan sattuessa olla teoreettisesti velvollinen suorittamaan sotapalveluksen molemmille. Tämän ristiriitaisen velvoitteen ratkaisemiseksi lähes kaikki feodaalisessa hierarkiassa pystyivät valitsemaan, kenen lakeja noudattaa, laillisen menettelyn kautta, jota kutsuttiin tunnustukseksi.

Tietotekniikka luo vastaavat mahdollisuudet kilpailulliseen valintaan taloudellisten toimintojen kotipaikan suhteen, mutta tärkein ero on se, että toisin kuin keskiaikaisten rajayhteisöjen tapauksessa, kyberavaruus tulee ajan myötä todennäköisesti olemaan taloudellisesti kaikkein rikkain alue. Siksi se tulee yleensä laajenemaan eikä supistumaan. Harvat keskiaikaisen yhteiskunnan ytimessä olleet henkilöt olisivat halunneet muuttaa rajayhteisöihin ilman vahvoja kannustimia – usein myös uskonnollisten imperatiivien vuoksi –, sillä nämä alueet olivat tavallisesti väkivaltaisia ja köyhiä. Siksi ne eivät toimineet resursseja vetävinä magneetteina viranomaisten hallinnosta. Kyberavaruus tulee tekemään niin.

Toiseksi, uusi raja ei tule muodostumaan duopoliksi, mikä kutsuisi kahden viranomaisen välistä salaliittoa heidän rajavaatimustensa kompromissiin. Keskiajalla tällaiset kompromissit eivät olleet tehokkaita kahdesta syystä: kilpailijoiden välillä oli usein jyrkkiä kulttuurieroja, ja ennen kaikkea heiltä puuttui fyysinen kyky panna neuvoteltu ratkaisu täytäntöön, koska heidän sotilaallinen voimansa oli riittämätöntä. Kansallisvaltioiden aikana, kun kansalliset viranomaiset alkoivat käyttää riittävästi sotilaallista voimaa ratkaisujen määräämiseen, suurin osa vartioalueista ja epämääräisistä rajoista katosi, ja rajojen vahvistaminen tuli normiksi. Tämä on vakaa ratkaisu, jos väkivallan duopolit kohtaavat mahdollisuuden jakaa valtansa yhteneviin vierekkäisiin alueisiin. Cyberekonomian kotipaikkatransaktioiden kilpailu sen sijaan ei tule käymään kahden viranomaisen välillä, vaan satojen viranomaisten kesken ympäri maailmaa. Alueellisten valtioiden on käytännössä mahdotonta luoda tehokasta kartellia pitääkseen verokannat korkeina – samasta syystä kuin satojen kilpailijoiden markkinoilla tapahtuva salaliitto monopolihintojen saavuttamiseksi ei toimi.

Esimerkiksi Seychelleja, pientä Intian valtameren maata, pidetään näyttönä siitä, kuinka uudet sääntelytoimet voivat tarjota vaihtoehtoisia kilpailullisia mahdollisuuksia. Seychellien uusi sijoituslaki, jota Yhdysvaltain viranomaiset kuvailevat ”Tervetuloa rikollisille” -lainsäädännöksi, takaa 10 miljoonan dollarin sijoittajalle paitsi suojan luovutusta vastaan, myös diplomaattisen passin. Vastoin Yhdysvaltain hallituksen väitteitä edunsaajia eivät kuitenkaan ole huumeiden myyjät – jotka ovat yleensä tärkeämpien hallitusten suojeluksessa – vaan itsenäiset yrittäjät, jotka ovat muuttuneet poliittisesti epäkorrekteiksi. Ensimmäinen potentiaalinen edunsaaja Seychellien lain alaisuudessa on valkoinen eteläafrikkalainen, joka rikosi vaurautensa kiertämällä talouspakotteita entistä apartheid-hallintoa vastaan. Nyt hän kohtaa uuden eteläafrikkalaisen hallituksen aiheuttaman taloudellisen koston vaaran ja on valmis maksamaan Seychelleille suojelusta.

Riippumatta yksittäistapauksen ansioista, esimerkki osoittaa, miksi hallitusten yritykset ylläpitää maalla suojelua varten muodostettua kartellia ovat tuomittuja epäonnistumaan.

Toisin kuin keskiaikaisella rajalla, jolla kilpailu käytiin vain kahden auktoriteetin välillä, kyberkaupan rajalla kilpaillaan sadoilla eri lainkäyttöalueilla, ja määrä nousee luultavasti nopeasti tuhansiin.

Virtuaaliyhtiöiden aikakaudella yksilöt valitsevat sijoittaa tulonhankintatoimintonsa sellaisen lainkäyttöalueen piiriin, joka tarjoaa parhaan palvelun alhaisimmilla kustannuksilla. Toisin sanoen, suvereniteetti kaupallistuu. Toisin kuin keskiaikaiset rajayhteiskunnat, jotka useimmissa tapauksissa olivat köyhiä ja väkivaltaisia, kyberavaruus ei tule olemaan kumpikaan. Se kilpailu, johon tieto- ja viestintäteknologia saa hallitukset osallistumaan, ei ole sotilaallista kilpailua, vaan kyse on taloudellisen palvelun – aidon suojan – laadun ja hinnan kilpailusta. Lyhyesti sanottuna, hallitusten on annettava asiakkaille sitä, mitä he haluavat.

### Väkivallan vähentynyt hyöty

Tämä ei tietenkään tarkoita, että hallitukset luopuisivat väkivallan käyttämisestä – päinvastoin. Pikemminkin sanomme, että väkivallan vaikutusvalta heikkenee merkittävästi. Yksi hallitusten mahdollisista reaktioista voisi olla väkivallan käytön tehostaminen paikallisissa ympäristöissä kompensoidakseen sen vähenevää globaalia merkitystä. Mitä tahansa hallitukset tekevätkin, niiden ei kuitenkaan onnistu kyllästämään kyberavaruutta väkivallalla samalla tavalla kuin ne kyllästivät modernilla maailmalla monopolisoimansa alueet väkivallalla. Oli kuinka monta hallitusta tahansa, ne eivät tule olemaan kyseisellä alueella kykenevämpiä tai voimakkaampia kuin kuka tahansa muu.

Ironisesti valtioiden yritykset käynnistää "tietosodat" hallitakseen tai estääkseen pääsyn kyberavaruuteen kiihdyttäisivät todennäköisesti ainoastaan niiden omaa tuhoa. Suurten järjestelmien rappeutumisen taipumus on jo voimakas, sillä mittakaavaetujen katoaminen ja pirstoutuvien sosiaalisten ryhmien yhteen pitäminen kasvavien kustannusten vuoksi eivät enää tue niiden yhtenäisyyttä. Tietosodankäynnin ironia on, että ne saattavat aiheuttaa enemmän iskua teollisen aikakauden hauraisiin järjestelmiin kuin itse nousevalle tietotaloudelle.

Niin kauan kuin olennaiset tietoteknologiaa koskevat järjestelmät pysyvät toimintakunnossa, kyberkaupankäynti voi edetä rinnakkain tietosodan kamppailujen kanssa tavalla, jota alueellisessa sodassa ei koskaan tapahdu. Et voisi kuvitella miljoonien kaupallisten transaktioiden tapahtuvan etulinjassa yhdessä 1900-luvun sodassa, mutta virtuaaliset sodat eivät välttämättä kuluta kyberavaruuden kapasiteettia isännöidä useita toimintoja samanaikaisesti. Koska virtuaalitodellisuutta ei ole olemassa, läheisyyden vaaraa on hyvin vähän eikä räjähtävien virtuaalisten roskien iskut muodostu merkittäväksi uhkaksi.

### Suurten järjestelmien haavoittuvuus

Tietosodan vaarat kohdistuvat pääasiassa suuriin teollisiin järjestelmiin, jotka toimivat keskitetyllä komentojärjestelmällä. Yhdysvalloissa ja muissa johtavissa valtioissa sotilaalliset viranomaiset suunnittelevat ja pelkäävät tietosabotaasin tekoja, joilla voisi olla vakavia seurauksia suurten järjestelmien lamauttamiseksi. Kyberhyökkäys voisi sulkea pois puhelinvaihdekeskuksen, häiritä ilmatilannevalvontaa tai sabotoida jännitysjärjestelmää, joka säätelee veden virtausta kaupunkiin. Ohjelmoitu virus voisi jopa sammuttaa perinteiset tai ydinvoimalat, katkaisten osia sähköverkosta. Näin kutsutut logiikkapotkut voisivat sekoittaa valtavan määrän tietoa, josta kaikkein herkin löytyy keskitettyjen ohjausjärjestelmien tiedoista, jotka kontrolloivat haavoittuvia suuria järjestelmiä, perittyjä teolliselta aikakaudelta. Ellei toteuteta massiivista ja kattavaa kaikkien tietotekniikkajärjestelmien tuhoamista, mikä saisi maailman talouden kirjaimellisesti pysähtymään, kyberkauppa ja virtuaalitodellisuus jäävät hallituksen ulottumattomiksi, paljon vähemmän kuin monopolisoitaviksi.

Jopa yksi tietotekniikan ilmeisistä heikkouksista, se että tietovarastojärjestelmät ovat alttiita rappeutumiselle ja tuhoutumiselle, on suurelta osin ratkaistu uudella arkistoteknologialla. Uusi järjestelmä nimeltä "High-Density read-only Memory" eli "HD-ROM" käyttää tietokoneavusteisissa valmistusjärjestelmissä havaittavaa ionimyllyä arkistojen luomiseen tyhjiössä. Tallennuskapasiteetti on nyt jopa 25 000 megatavua neliötuumaa kohden. Toisin kuin aiemmat järjestelmät, jotka olivat herkkiä aikaisen rappeutumisen ja iskuilta johtuville häiriöille, HD-ROMiin tallennettu data lupaa säilyä koko käyttöikänsä ajan. Yksi HD-ROMin kehittäjistä, Bruce Lamartine, toteaa: "Se on käytännössä immuuni ajan kulutukselle, lämpöisille ja mekaanisille iskurille sekä sähkömagneettisille kentille, jotka ovat niin tuhoisia muille tallennusvälineille."[^239] Jopa ydintekijöiden räjähdys ei välttämättä sekoita tai tuhoa elintärkeää tietoa, kuten digitaalisen rahan koodeja, joihin sujuva kybertalouden toiminta perustuu.

### Suurten järjestelmien haavoittuvuus

Tietosodan uhkat kohdistuvat pääasiassa suuriin, keskitetyllä ohjauksella toimiviin teollisiin järjestelmiin. Yhdysvaltojen ja muiden johtavien valtioiden armeijat suunnittelevat ja pelkäävät tietosabotaasitoimia, joilla voi olla vakavia seurauksia koko järjestelmän lamauttamiseksi. Kyberhyökkäys voisi esimerkiksi sulkea pois puhelinvaihdekeskuksen, häiritä ilmatilannevalvontaa tai sabotoida pumppujärjestelmää, joka säätelee veden virtausta kaupunkiin. Ohjelmoitu virus saattaisi jopa sammuttaa perinteiset tai ydinvoimalat, katkaisten osia sähköverkosta. Niin kutsutut logiikkapotkut voisivat sekoittaa valtavan määrän tietoa, josta kaikkein sensitiivisin löytyy keskusjärjestelmissä, jotka ohjaavat teollisista aikakaudelta perittyjä hauraasti toimivia suuria järjestelmiä. Ellei toteuteta massiivista ja kattavaa kaikkien tietotekniikkajärjestelmien tuhoamista, mikä saisi maailman talouden ajallisesti pysähtymään, kyberkauppa ja virtuaalitodellisuus pysyvät hallituksen ulottumattomissa täysin, paljon vähemmän kuin monopolisoitavissa.

Vaikka keskeinen tietotekniikan haitta, eli sen ilmeinen haavoittuvuus tietovarastojärjestelmien rappeutumiselle, onkin suurelta osin ratkaistu uudella arkistoteknologialla, on tämäkin edistys askel säilyttää kriittiset tiedot. Uusi "HD-ROM" –järjestelmä on suunniteltu niin, että sen tallennuskapasiteetti on huikea ja data pysyy pitkään turvassa. Bruce Lamartinen mukaan HD-ROM on käytännössä immuuni ajan kulumalle, mekaanisille ja lämpöisille iskuilta sekä sähkömagneettisille häiriöille, jotka muuten tuhoutuivat helposti. Jopa ydintekijöiden räjähdys ei välttämättä sekoita elintärkeää tietoa, kuten digirahan koodeja, joihin kybertalouden jatkuva toiminta nojaa.

[^239]: Jopa ydintekijöiden räjähdys ei välttämättä sekoita tai tuhoa elintärkeää tietoa, kuten digitaalisen rahan koodeja, joihin kybertalouden sujuva toiminta perustuu.

"Nykyiset armeijat ovat niin riippuvaisia informaatiosta, että niiden saa saistaa ja äänettömyystilaan asettamalla voiton saavutettua ilman tavanomaista taistelua."[^240]: - EVERSTI ALAN CAMPEN, Yhdysvaltain ilmavoimat (eläkkeellä)

## VIRTUAALISEN SODANKÄYNNIN SUPERVOIMAT

Sotailevan kansallisvaltion oletukset menettävät yhä enemmän megapoliittista merkitystään, kun tiedon rooli sodankäynnissä kasvaa. Koska sillä ei ole fyysistä olemassaoloa, kyberavaruudessa fyysisen maailman mittasuhteet eivät kanna mitään komentavaa merkitystä. Ei ole olennaista, kuinka monta ohjelmoijaa on osallistunut käskyjen sarjan määrittelyyn – tärkeintä on, että ohjelma toimii. Itsenäinen yksilö voi todellakin painaa yhtä paljon kyberavaruudessa kuin valtio, jolla on YK:n päämaja, oma lippu ja maassa sijoitettu armeija. Puhtaasti taloudellisessa mielessä jotkut itsenäiset yksilöt hallitsevat jo satoissa miljoonissa investoitavia tuloja vuosittain, summia, jotka ylittävät joidenkin konkurssin partaalla olevien valtioiden harkinnanvaraisen kulutusvallan. Mutta se ei ole kaikki: virtuaalisen sodankäynnin, jossa informaation manipuloinnilla käydään taistelua, näkökulmasta jotkut yksilöt saattavat nousta yhtä suuriksi tai jopa suuremmiksi kuin moni maailman valtio. Yksi outo nero, joka työskentelee digitaalisten palvelijoiden kanssa, voisi teoreettisesti saavuttaa kybersodan vaikutuksen, joka vastaa koko valtion voimaa – Bill Gateskin pystyisi siihen.

Siinä mielessä itsenäisen yksilön aikakausi ei ole pelkästään iskulause. Hakkeri tai pieni joukko matemaatikkoja – puhumattakaan yhtiöstä, kuten Microsoftista tai lähes mistä tahansa tietokoneohjelmistoyrityksestä – voisi periaatteessa tehdä mitä tahansa tai jopa kaiken sen, mitä Pentagonin kybersodankäynnin työryhmä on varastossaan. Piilaaksossa ja muualla on satoja yrityksiä, joilla on vuosittain suurempi kyky käydä kybersotaa kuin 90 prosentilla nykyisistä valtioista.

Oletus, että hallitukset jatkavat elämän monopolisoimista maan päällä, kun vaihtoehtoisia suojan muotoja avautuu joka suunnasta, on anakronistinen. Paljon todennäköisempi lopputulos on, että valtioita on uudelleen määriteltävä niin, että niiden haavoittuvuus tietokoneviruksille, logiikkapommeille, infektoituneille johdoille ja ansalukiohjelmille – joita Yhdysvaltain kansallisturvallisuusvirasto tai jopa teinihakkeri voisi valvoa – vähenee.

Kyberavaruuden megapoliittinen logiikka viittaa siihen, että maailman suurimman infrastruktuurin tällä hetkellä hallitsevat keskitetyt komentokeskukset on korvattava monikeskuksisilla turvallisuusmalleilla, joissa on hajautettuja kyvykkyyksiä, jotta niitä ei pysty helposti kaappaamaan tai estämään tietokoneviruksella. Uusia ohjelmistotyyppejä, joita kutsutaan agorisisiksi avoimiksi järjestelmiksi, tulevat korvaamaan teolliskaudelta perittyä komentokeskustoimintoihin perustuvaa ohjelmistoa. Vanhempi ohjelmisto jakoi laskentatehoa jäykien prioriteettien mukaisesti aivan kuten entisen Neuvostoliiton Gosplanin keskussuunnittelijat jakoivat tavaroita rahtiautoihin tiukkojen sääntöjen mukaisesti. Uusia järjestelmiä ohjaavat algoritmit, jotka jäljittelevät markkinamekanismeja jakaakseen resursseja tehokkaammin sisäisen huutoprosessin avulla – prosessin, joka muistuttaa aivojen kilpailuprosesseja. Sen sijaan, että jättimäiset tietokone-monopolit hoitaisivat tärkeitä komentokeskustoimintoja, nämä toiminnot hajautetaan uudella vuosituhannella.

Ei ole parempaa esimerkkiä hajautettujen verkostojen kestävyydestä verrattuna keskitettyihin järjestelmiin kuin Digital Equipmentin esimerkki sen Palo Altossa sijaitsevassa tutkimuslaboratoriossa. Eräs insinööri avasi oven kaapille, jossa yrityksen oma tietokoneverkko sijaitsi. Kevin Kellyn mukaan insinööri “reippasivä irrotti kaapelin sen sisuksista. Verkko ohjasi liikenteensä ympärille eikä horjutellut lainkaan.”[^241]

Tietoyhteiskunta ei ainoastaan helpota kilpailua ilman anarkiaa kyberavaruudessa; se johtaa väistämättä teollisuuden jäänteisen tärkeiden järjestelmien uudelleensuunnitteluun. Tällainen uudelleenjärjestely on välttämätöntä, jotta järjestelmät olisivat vähemmän alttiita kepposille, joita kuka tahansa mistä tahansa voi aiheuttaa. Aivan kuten teolliskausi johti keskiajan jäänteisten instituutioiden – esimerkiksi koulujen ja yliopistojen – uudelleenjärjestelyyn, myös teolliskauden jäännösinstituutiot kehittyvät todennäköisesti pienoismallin muodossa tavoilla, jotka heijastavat mikrotechnologian logiikkaa.

Tarve suojautua tietoyhteiskunnan moottoritiellä liikkuvilta ryöstöiltä edellyttää laajaa julkisen ja yksityisen avaimen salaustekniikoiden käyttöönottoa. Näiden avulla lähes kuka tahansa henkilökohtaisen tietokoneen käyttäjä pystyy koodaamaan viestejä huomattavasti turvallisemmin kuin Pentagon olisi pystynyt sulkemaan laukaisukoodinsa vielä sukupolven sitten. Nämä tehokkaat, murtamattomat salaustekniikat ovat välttämättömiä turvaamaan taloudellisia transaktioita hakkereilta ja varkailta.

Ne ovat myös tarpeellisia muusta syystä. Yksityiset rahoituslaitokset ja keskuspankit ottavat käyttöön murtamattomat salaustekniikat, kun ne huomaavat, että Yhdysvaltain hallitus – eikä se välttämättä ole yksin – kykenee tunkeutumaan nykyisiin pankkiohjelmistoihin ja tietojärjestelmiin siten, että se voi kirjaimellisesti konkurssoida koko maan tai tyhjentää kenen tahansa pankkitilin melkein mistä tahansa. Ei ole teknologista syytä, miksi kukaan yksilö tai maa jättäisi rahaoletteensa tai transaktioitaan Yhdysvaltain kansallisen turvallisuusviraston, KGB:n seuraajien tai minkä tahansa vastaavan, lainmukaisen tai laittoman toimijan armoille.

Hallitusten läpäisemättömät salausalgoritmit eivät ole vain unelmointia – ne ovat jo saatavilla shareware-muodossa Internetissä. Kun matalataajuiset satelliittijärjestelmät ovat täysin toiminnassa, edistyneitä henkilökohtaisia tietokoneita käyttävät ihmiset, joiden antennit ovat kooltaan yhtä pienet kuin kannettavissa puhelimissa, pystyvät kommunikoimaan missä tahansa maailmassa ilman, että heidän tarvitsee edes kytkeytyä puhelinjärjestelmään. Hallituksen ei myöskään tule enää olla samaa mieltä kuin keskiaikaisilla ritareilla siitä, että raskaalla ratsulla ratsasteliin teollisella aikakaudella tapahtuvia kauppoja – valtio ei voi monopolisoida kybersidettä, maailmaa, jolla ei ole lainkaan fyysistä olemassaoloa.

Suojaaminen huomaamattomuudella

Tietoyhteiskunnat asettavat valtavia resursseja saalistuksen ulkopuolelle. Kun kyberside muuttuu yhä enenevissä määrin rahoitustapahtumien ja muun kaupankäynnin keskukseksi, siellä käytetyt resurssit ovat enemmän tai vähemmän immuuneja tavanomaisille pakkolunastuksille ja varkauksille. Näin saalistajat eivät kykene kaptaamaan yhtä suurta osaa resursseista kuin he tekevät jo tänään ja ovat tehneet suurimman osan kahdenkymmenen vuosisadan ajan.

Väistämättä siis suuren osan maailman varallisuudesta hyödyntävä valtion suojaus tulee olemaan tarpeetonta. Valtio ei ole paremmassa asemassa suojelemaan pankkitiliä kybersidessä kuin sinä itse. Koska valtiota tulee tarvita yhä vähemmän, sen suhteellinen hinta laskee todennäköisesti pelkästään tästä syystä – ja siitä on muitakin vaikutuksia.

Uuden vuosituhannen aikana, kun suuri ja kasvava osa rahoitustapahtumista tapahtuu kybersidessä, yksilöillä on valinnanvaraa sen lainkäyttöalueiden suhteen, joihin he voivat kirjata tapahtumansa. Tämä synnyttää intensiivistä kilpailua valtion palvelujen hinnoittelussa (eli verojen määrässä) ei-monopolistisella pohjalla. Tämä on vallankumouksellista. Kuten George Melloan väitti The Wall Street Journalissa, ainoa instituutio, joka on onnistunut eniten vastustamaan maailmanlaajuista kilpailua, on ollut hyvinvointivaltio. Wharton Schoolin ja Australian National Universityn tutkijoiden tekemä tutkimus tarkasteli tulonsiirtotoimenpiteisiin vaikuttavia voimia. Geoffrey Garrett ja Deborah Mitchell päättelivät, että «käytännössä ei ole todisteita siitä, että lisääntynyt markkinoiden integrointi olisi asettanut alaspäin painetta niiden perustavanlaatuisimmille hyvinvointiohjelmille.» Päinvastoin he kirjoittavat, että «hallitukset ovat johdonmukaisesti vastanneet kansainvälisen integraation myötä kasvattamalla tulonsiirtoja.»[^242] Kybersidän talouskohtaaminen paljastaa viimein hyvinvointivaltion todellisen kilpailukyvyn. Se muuttaa suvereniteettien luonnetta ja transformoi talouksia, kun suojelun ja kiristyksen välinen tasapaino kallistuu entistä enemmän suojelun puolelle kuin koskaan aiemmin.

[^187]: Neil Munro, "Pentagonin uusi painajainen: sähköinen Pearl Harbor", Washington Post, 16. heinäkuuta 1995, s. C3.

[^188]: Thomas Hobbes, Leviathan, luku 13 "Ihmisen luonnollinen tila heidän onnellisuudestaan ja kurjuudestaan".

[^189]: Thomas Schelling, Arms and Influence (New Haven: Yale University Press, 1966).

[^190]: Kevin Kelly, Out of Control: The New Biology of Machines, Social Systems, and the Economic World (Reading, Mass.: Addison-Wesley, 1995), s. 45–46.

[^191]: Ibid., s. 2–4.

[^192]: Ibid., s. 4.

[^193]: Heinz Pagels, The Dreams of Reason (New York: Bantam Books, 1989), lainattu Roger Lewinin teoksesta Complexity: Life at the Edge of Chaos (New York: Macmillan, 1992), s. 10.

[^194]: Lane, "Economic Consequences of Organized Violence," op. cit., s. 402.

[^195]: Frederic C. Lane, "The Economic Meaning of War and Protection," teoksessa Venice and History: The Collected Papers of Frederic C. Lane (Baltimore: The Johns Hopkins Press, 1966), s. 383–384.

[^196]: Shi Mai'an ja Lao Guanzhong, Outlaws of the Marsh, käännös Sidney Shapiro (Bloomington: Indiana University Press, 1981), s. 12.

[^197]: George E. Will, "Farewell to Welfare States," Washington Post, 17. joulukuuta 1995, s. C7.  
[^198]: Robert S. MeElvaine, The Great Depression: America, 1929–1941 (New York: Times Books, 1984), s. 292.  
[^199]: Sama, s. 293.  
[^200]: Smith, op. cit., s. 75.  
[^201]: Sama, s. 76.

[^202]: Ibid.

[^203]: Yksi ensimmäisistä organisoituneista argentiinalaisista ammattiliitoista oli rautatieyhdistys vuonna 1887. Katso Carmelo Mesa-Lago, Social Security in Latin America: Pressure Groups, Stratification, and Inequality (Pittsburgh: University of Pittsburgh Press, 1978), s. 161.

[^204]: Lisätietoja C&O-kanavan suunnittelusta ja rakentamisesta on Robert J. Bruggerin kirjassa Maryland: A Middle Temperament 1634-1980 (Baltimore: The Johns Hopkins Press, 1990), s. 202–203 ja seuraavat sivut.

[^205]: Irving J. Sloan, Our Violent Past: An American Chronicle (New York: Random House, 1970), s. 177.

[^206]: Lisätietoja vuoden 1877 rautatiestrikeihin liittyvästä väkivallasta on saatavilla edellisestä lähteestä sekä Bruggerin teoksesta, op. cit., s. 341–344.

[^207]: Sloan, op. cit., s. 202. Katso myös S. S. Boynton, "Miners' Vengeance," Overland Monthly, vol. 22 (1893), s. 303–7

[^208]: Benjamin Schwartz, "American Inequality: Its History and Scary Future," New York Times, 19. joulukuuta 1995, s. A25.

[^209]: MeElvaine, op. cit., s. 293.

[^210]: Ibid.

[^211]: Ibid.

[^212]: Henry C. Simons, "Joitakin pohdintoja syndikalismista," Journal of Political Economy, maaliskuu 1944, s. 22.

[^213]: Kelly, op. cit., s. 191–92.

[^214]: Gayle Ni. Hanson, "Vangitseva kuvaus 'elämästä' postmodernistisessa kyberavaruudessa," Washington Times, 24. joulukuuta 1995, s. B7.

[^215]: Ytimekäs johdanto anarkian akateemiseen tutkimukseen löytyy teoksesta Gordon Tullock (toim.), Explorations in the Theory of Anarchy (Blacksburg, Va.: Virginia Polytechnic Institute and State University, 1972). Katso myös Murray N. Rothbard, Power and Market: Government and the Economy (Menlo Park, Calif., 1970); sekä Robert Nozick, Anarchy, State and Utopia (New York: Basic Books, 1974).

[^216]: Katso Pierre Clastres, Society Against the State: The Leader as Servant and the Humane Uses of Power Among the Indians of the Americas (New York: Urizen Books, 1977); sekä Jones, op. cit.

[^217]: Lane, “Organisoidun väkivallan taloudelliset seuraukset,” op. cit., s. 403.

[^218]: Charles Tilly, “Sodan ja valtion rakentaminen järjestäytyneenä rikollisuutena,” teoksessa Peter B. Evans, Dietrich Rue schemeyer ja Theda Skoepol, Bringing the State Back In (Cambridge: Cambridge University Press, 1985), s. 169.

[^219]: Ibid.

[^220]: Lane, “Organisoidun väkivallan taloudelliset seuraukset,” op. cit., s. 402.

[^221]: David J. Elkins, Beyond Sovereignty: Territory and Political Economy in the Twenty-First Century. Toronto: University of Toronto Press, 1995, s. 13–14.

[^222]: Ibid., s. 29

[^223]: Jim Taylor ja Watts Wacker, The 500-Year Delta: What Happens After What Comes Next. New York: HarperCollins, 1997, s. 40.

[^224]: Ibid., s. 67

[^225]: Ibid., s. 41–42

[^226]: George Gilder, "Fiber Keeps Its Promise: Get Ready. Bandwidth Will Triple Each Year for the Next 25, Creating Trillions in New Wealth." Forbes ASAP, 7. huhtikuuta 1997

[^227]: Katso Neal Stephenson, Snow Crash. New York: Bantam Books, 1993

[^228]: Keith B. Richburg, "Kaksi vuotta Yhdysvaltojen laskeutumisen jälkeen Somalian – tilanne on jälleen kaaoksessa", Washington Post, 4. joulukuuta 1994, s. Al.

[^229]: Viitattu teoksesta Tilly, Coercion, Capital and European States, op. cit., s. 85.

[^230]: Lane, "Economic Consequences of Organized Violence," op. cit., s. 411.

[^231]: Ibid.

[^232]: Ibid.

[^233]: Ibid., s. 412.

[^234]: Ibid., s. 403.

[^235]: Ibid., s. 404.

[^236]: Esther Dyson, Release 2.1: A Design for Living in the Digital Age. New York: Broadway Books, 1998, s. 131.

[^237]: Rees Davies, "Reunajärjestelyt hajaantuneissa yhteiskunnissa: Irlanti ja Wales", teoksessa Robert Bartlett ja Angus MacKay (toim.), Keskiaikaiset reunayhteiskunnat (Oxford: Oxford University Press, 1992), s. 80.

[^238]: Katso Thomas W. Lippman, "Seychellit tarjoavat sijoittajille turvapaikan 10 miljoonalle dollarille", Washington Post, 31. joulukuuta 1995, s. A27.

[^239]: Katso "ROM of Ages", Wired, tammikuu 1996, s. 52.

[^240]: Lainattu teoksesta James Adams, "Kybersotilaiden aamunkaja", The Sunday Times (Lontoo), 15. lokakuuta 1995, s. 3–5.

[^241]: Kelly, op. cit., s. 19.

[^242]: George Melloan, "Hyvinvointivaltion uudistaminen on pääosin mytologista," The Wall Street Journal. 14. lokakuuta 1996, s. A19.

[^243]: Katso kappale 8 teoksesta *The Great Reckoning*, "Lineaariset odotukset epälineaarisessa maailmassa: kuinka teleskooppi johdatti meidät laskemaan; kuinka tietokone voi auttaa meitä näkemään."

[^244]: Huomaa, että Lanelin neljä väkivallan käytön kilpailu- ja monopolivaihetta eroavat toisistaan niistä neljästä vaiheesta, jotka tunnistamme talouselämän järjestäytymisessä – nimittäin keräilystä, maanviljelystä, teollisuudesta ja tietoyhteiskunnasta.