# De overgang in het jaar 2000



> "Het voelt alsof er iets groots gaat gebeuren: grafieken tonen ons de jaarlijkse groei van de bevolking, de atmosferische concentraties van koolstofdioxide, webadressen en Mbytes per dollar. Ze stijgen allemaal naar een asymptoot net voorbij de eeuwwisseling: De Singulariteit. Het einde van alles wat we kennen. Het begin van iets wat we misschien nooit zullen begrijpen" [^1] - Danny Hillis

## Voorgevoelens



De komst van het jaar 2000 heeft de westerse verbeelding de afgelopen duizend jaar achtervolgd. Sinds de wereld niet verging bij de eeuwwisseling van het eerste millennium na Christus, hebben theologen, evangelisten, dichters en ziener het einde van dit decennium met de verwachting bekeken dat het iets belangrijks zou brengen. Isaac Newton, niet de minste autoriteit, speculeerde dat de wereld zou vergaan in het jaar 2000. Michel de Nostradamus, wiens profetieën sinds hun eerste publicatie in 1568 door elke generatie zijn gelezen, voorspelde de komst van de Derde Antichrist in juli 1999. [^2] De Zwitserse psycholoog Carl Jung, kenner van het "collectieve onbewuste", voorzag de geboorte van een nieuw tijdperk in 1997. Dergelijke voorspellingen kunnen gemakkelijk belachelijk worden gemaakt. En zo ook de nuchtere voorspellingen van economen, zoals Dr. Edward Yardeni van Deutsche Bank Securities, die verwacht dat computerstoringen op de millenniumnacht "de hele wereldeconomie zullen verstoren".[^3] Maar of je het Y2K-computerprobleem nu ziet als een ongegronde hysterie aangewakkerd door computerprogrammeurs en IT-consultants om zaken te stimuleren, of als een mysterieus voorbeeld van technologie die samengaat met de profetische verbeelding, het valt niet te ontkennen dat de omstandigheden aan de vooravond van het millennium meer dan de gebruikelijke morbide twijfel oproepen over de richting waarin de wereld zich beweegt.

Een gevoel van onrust over de toekomst heeft de optimisme begonnen te kleuren dat zo kenmerkend is voor de westerse samenlevingen van de afgelopen 250 jaar. Mensen overal zijn aarzelend en bezorgd. Je ziet het in hun gezichten. Je hoort het in hun gesprekken. Je ziet het weerspiegeld in opiniepeilingen en geregistreerd in de stembus. Net zoals een onzichtbare, fysieke verandering van ionen in de atmosfeer aangeeft dat een onweersbui op komst is, nog voordat de wolken donker worden en de bliksem inslaat, zo hangen er nu, in de schemering van het millennium, voorgevoelens van verandering in de lucht. De ene persoon na de andere, elk op zijn eigen manier, voelt dat de tijd opraakt voor een stervende manier van leven. Naarmate het decennium afloopt, loopt er een moorddadige eeuw met het af, en ook een glorieus millennium van menselijke prestaties. Alles loopt ten einde met het jaar 2000.

"Want er is niets bedekt dat niet geopenbaard zal worden, en niets verborgen dat niet bekend zal worden." - Matteüs 10:26

Wij geloven dat de moderne fase van de westerse beschaving hiermee zal eindigen. Dit boek legt uit waarom. Net als vele eerdere werken, is het een poging om door een glazen wand te kijken, om de vage vormen en dimensies van een toekomst te schetsen die nog moet komen. In die zin bedoelen we dat ons werk apocalyptisch is in de oorspronkelijke betekenis van het woord. Apokalypsis betekent "onthulling" in het Grieks. Wij geloven dat een nieuw tijdperk in de geschiedenis - het informatietijdperk - op het punt staat "geopenbaard" te worden.

> Wij zien de beginselen van een nieuwe logische ruimte, een ogenblikkelijke elektronische alomtegenwoordigheid, die wij allen kunnen benaderen, betreden en ervaren. Kortom, wij hebben de beginselen van een nieuw soort gemeenschap. De virtuele gemeenschap wordt het model voor een seculier Koninkrijk der Hemelen; zoals Jezus zei dat er vele woningen waren in het Koninkrijk van zijn Vader, zo zijn er vele virtuele gemeenschappen, elk reflecterend op hun eigen behoeften en verlangens. - Michael Grasso[^4]

## DE VIERDE FASE VAN DE MENSELIJKE SAMENLEVING



Het thema van dit boek is de nieuwe machtsrevolutie die individuen bevrijdt ten koste van de natiestaat van de twintigste eeuw. Innovaties die de logica van geweld op ongekende manieren veranderen, transformeren de grenzen waarbinnen de toekomst moet liggen. Als onze deducties correct zijn, staat u op de drempel van de meest ingrijpende revolutie in de geschiedenis. Sneller dan de meesten zich nu kunnen voorstellen, zal microverwerking de natiestaat ondermijnen en vernietigen, waarbij nieuwe vormen van sociale organisatie ontstaan. Dit zal verre van een gemakkelijke transformatie zijn.

De uitdaging zal des te groter zijn omdat het met ongelooflijke snelheid zal gebeuren in vergelijking met alles wat we in het verleden hebben gezien. Door de hele menselijke geschiedenis, van het prille begin tot nu toe, zijn er slechts drie basisstadia van het economische leven geweest: (1) jager-verzamelaarsmaatschappijen; (2) agrarische maatschappijen; en (3) industriële maatschappijen. Nu, aan de horizon, doemt iets geheel nieuws op: de vierde fase van sociale organisatie: informatiemaatschappijen.

Elk van de vorige stadia van de samenleving correspondeerde met duidelijk verschillende fasen in de evolutie en beheersing van geweld. Zoals we in detail uitleggen, beloven informatiemaatschappijen het rendement van geweld drastisch te verminderen, gedeeltelijk omdat ze de lokale context overstijgen. De virtuele realiteit van de cyberspace, wat romanschrijver William Gibson kenmerkte als een 'consensuele hallucinatie', zal net zo buiten het bereik van bullebakken liggen als de verbeelding het toelaat. Als het nieuwe millennium aanbreekt, zal het voordeel van het beheersen van geweld op grote schaal veel lager zijn dan ooit tevoren, sinds voor de Franse Revolutie. Dit zal ingrijpende gevolgen hebben. Een daarvan zal een toename van criminaliteit zijn. Wanneer de opbrengst van het organiseren van geweld op grote schaal daalt, zal de opbrengst van geweld op kleinere schaal waarschijnlijk toenemen. Geweld zal willekeuriger en meer gelokaliseerd worden. De georganiseerde misdaad zal toenemen in omvang. We leggen uit waarom.

Een andere logische implicatie van een dalend rendement van geweld is de ondergang van de politiek. Er is veel bewijs dat de aanhankelijkheid aan de burgerlijke mythes van de natiestaat van de twintigste eeuw snel afbrokkelt. De val van het communisme is slechts het meest opvallende voorbeeld. Zoals we in detail zullen onderzoeken, is de morele verenging en de toenemende corruptie onder leiders van westerse regeringen geen toevallige ontwikkeling. Het is een bewijs dat het potentieel van de natiestaat uitgeput is. Zelfs veel van haar leiders geloven de platitudes die ze uitspreken niet langer. En ze worden ook niet meer geloofd door anderen.

### Geschiedenis herhaalt zich

Dit is een situatie met opvallende parallellen in het verleden. Telkens wanneer technologische veranderingen de oude vormen losmaakten van de nieuwe drijfveren van de economie, verschoven de morele normen en begonnen mensen degenen die de oude instellingen beheersen met groeiende minachting te behandelen. Deze wijdverspreide afkeer wordt vaak duidelijk lang voordat mensen een nieuwe samenhangende ideologie van verandering ontwikkelen. Zo was het in de late vijftiende eeuw, toen de middeleeuwse kerk de belangrijkste instelling van het feodalisme was. Ondanks het volksgeloof in 'de heiligheid van het priesterambt', werden zowel de hogere als de lagere geestelijkheid met de grootste minachting behandeld – niet ongelijk aan de houding ten opzichte van politici en ambtenaren vandaag de dag.[^5]

Wij geloven dat veel te leren valt door een analogie te trekken tussen de situatie aan het einde van de vijftiende eeuw, toen het leven volledig doordrongen was van georganiseerde religie, en de situatie vandaag de dag, toen de wereld verzadigd is geraakt met politiek. De kosten van het ondersteunen van geinstitutionaliseerde religie aan het einde van de vijftiende eeuw bereikten een historisch hoogtepunt, net zoals de kosten van het ondersteunen van de overheid vandaag de dag een seniele hoogte hebben bereikt.

We weten wat er met de georganiseerde religie gebeurde in de nasleep van de Kruithuistrevoltie. Technologische ontwikkelingen creëerden sterke prikkels om religieuze instellingen te verkleinen en hun kosten te verlagen. Een soortgelijke technologische revolutie is voorbestemd om de natiestaat vroeg in het nieuwe millennium radicaal te verkleinen.

> Vandaag de dag, na meer dan een eeuw van elektronische technologie, hebben we ons centrale zenuwstelsel zelf uitgebreid in een globale omhelzing, waardoor zowel ruimte als tijd, wat onze planeet betreft, afgeschaft zijn.[^6]

### De Informatie Revolutie



Naarmate het uiteenvallen van grote systemen versnelt, zal systematische dwang afnemen als een factor die het economische leven en de inkomensverdeling vormgeeft. Efficiëntie zal snel belangrijker worden dan de dictaten van de macht in de organisatie van sociale instellingen. Dit betekent dat provincies en zelfs steden die effectief eigendomsrechten kunnen handhaven en voor de rechtspraak kunnen zorgen, terwijl ze weinig middelen verbruiken, levensvatbare soevereiniteiten zullen zijn in het informatietijdperk, zoals ze dat over het algemeen niet zijn geweest in de afgelopen vijf eeuwen. Een geheel nieuw rijk van economische activiteit dat niet afhankelijk is van fysiek geweld zal ontstaan in de cyberspace. De meest voor de hand liggende voordelen zullen ten goede komen aan de "cognitieve elite", die steeds meer buiten politieke grenzen zullen opereren. Ze voelen zich al even thuis in Frankfurt, Londen, New York, Buenos Aires, Los Angeles, Tokio en Hong Kong. De inkomens zullen ongelijkmatiger worden binnen rechtsgebieden en gelijkmatiger tussen rechtsgebieden.

Het boek *The Sovereign Individual* verkent de sociale en financiële gevolgen van deze revolutionaire verandering. Ons doel is u te helpen profiteren van de kansen van het nieuwe tijdperk en te voorkomen dat u wordt verwoest door de impact ervan. Als maar de helft van wat we verwachten werkelijkheid wordt, zult u geconfronteerd worden met een verandering van een omvang die weinig precedent kent in de geschiedenis.

De transformatie van het jaar 2000 zal niet alleen het karakter van de wereldeconomie revolutioneren, maar dit ook sneller doen dan enige voorgaande faseovergang. In tegenstelling tot de landbouwrevolutie, zal de informatierevolutie niet duizenden jaren duren. In tegenstelling tot de industriële revolutie zal de impact ervan niet over eeuwen worden uitgesmeerd. De informatierevolutie zal zich binnen een mensenleven voltrekken.

Bovendien zal het zich bijna overal tegelijk voltrekken. Technische en economische innovaties zullen niet langer beperkt blijven tot kleine delen van de wereld. De transformatie zal vrijwel universeel zijn. En het zal een breuk betekenen met het verleden, zo diepgaand dat het bijna het magische rijk van de goden tot leven zal brengen, zoals dat werd voorgesteld door de vroege agrarische volkeren, zoals de oude Grieken. In sterkere mate dan de meesten nu zouden willen toegeven, zal het moeilijk of onmogelijk blijken om veel hedendaagse instituties in het nieuwe millennium te behouden. Wanneer informatiemaatschappijen vorm krijgen, zullen ze net zo anders zijn dan industriële maatschappijen als het Griekenland van Aeschylus verschilde van de wereld van de grotwonenden.

## PROMETHEUS UNBOUND: DE OPKOMST VAN DE SOUVEREINE INDIVIDU

>Ik ken geen aanmoedigender feit dan het onbetwijfelbare vermogen van de mens om zijn leven te verheffen door bewuste inspanning. - Henry David Thoreau

De komende transformatie is zowel goed als slecht nieuws. Het goede nieuws is dat de informatierevolutie individuen zal bevrijden als nooit tevoren. Voor het eerst zullen zij die zichzelf kunnen opleiden, vrijwel volledig vrij zijn om hun eigen werk te creëren en de volle vruchten te plukken van hun eigen productiviteit. Genie zal ontketend worden, bevrijd van zowel de onderdrukking van de overheid als de belemmeringen van raciale en etnische vooroordelen. In de informatiemaatschappij zal niemand die werkelijk bekwaam is, worden tegengehouden door de misvormde meningen van anderen. Het zal niet uitmaken wat de meeste mensen op aarde van je ras, je uiterlijk, je leeftijd, je seksuele geaardheid of de manier waarop je je haar draagt, vinden. In de cybereconomie zullen ze je nooit zien. De lelijke, de dikke, de oude, de gehandicapten zullen op gelijke voet concurreren met de jonge en mooie in volkomen kleurenblind anonimiteit op de nieuwe grenzen van de cyberspace.

Ideeën worden rijkdom


Verdiensten, waar ze ook vandaan komen, zullen als nooit tevoren worden beloond. In een omgeving waar de grootste bron van rijkdom de ideeën in je hoofd zullen zijn in plaats van alleen fysiek kapitaal, kan iedereen die helder denkt potentieel rijk worden. Het informatietijdperk zal het tijdperk van sociale mobiliteit zijn. Het zal veel meer gelijke kansen bieden aan miljarden mensen in delen van de wereld die nooit volledig hebben deelgenomen aan de welvaart van de industriële samenleving. De slimste, meest succesvolle en ambitieuze van hen zullen opkomen als ware soevereine individuen.

Aanvankelijk zullen slechts een handvol mensen volledige financiële soevereiniteit bereiken. Maar dit ontkent de voordelen van financiële onafhankelijkheid niet. Het feit dat niet iedereen een even enorm fortuin verwerft, betekent niet dat het zinloos is om rijk te worden. Er zijn 25.000 miljonairs per miljardair. Als je een miljonair bent en geen miljardair, ben je niet arm. Evenzo zal in de toekomst een van de mijlpalen waarmee je je financiële succes meet, niet alleen zijn hoeveel nullen je aan je nettowaarde kunt toevoegen, maar of je je zaken zo kunt structureren dat je volledige individuele autonomie en onafhankelijkheid kunt realiseren. Hoe slimmer je bent, hoe minder voortstuwing je nodig zult hebben om financiële ontsnappingssnelheid te bereiken. Mensen met zelfs vrij bescheiden middelen zullen stijgen, naarmate de zwaartekracht van de politiek op de wereldeconomie afneemt. Ongeëvenaarde financiële onafhankelijkheid zal een haalbaar doel zijn in jouw leven of dat van je kinderen.

Op het hoogste niveau van productiviteit zullen deze soevereine individuen concurreren en interageren op een manier die de relaties tussen de goden in de Griekse mythologie weerspiegelt. De ongrijpbare berg Olympus van het volgende millennium zal zich in de cyberspace bevinden – een rijk zonder fysiek bestaan dat niettemin de grootste economie ter wereld zal ontwikkelen tegen het tweede decennium van het nieuwe millennium. Tegen 2025 zal de cybereconomie miljoenen deelnemers hebben. Sommigen van hen zullen net zo rijk zijn als Bill Gates, elk meer dan 10 miljard dollar waard. De cyberarmen zullen misschien zij zijn met een inkomen van minder dan 200.000 dollar per jaar. Er zal geen cyberwelzijn zijn. Geen cyberbelastingen en geen cyberregering. De cybereconomie, in plaats van China, zou wel eens het grootste economische fenomeen van de komende dertig jaar kunnen zijn.

Het goede nieuws is dat politici in dit nieuwe rijk niet meer in staat zullen zijn om het grootste deel van de handel te domineren, te onderdrukken en te reguleren, net zoals de wetgevers van de oude Griekse stadstaten de baard van Zeus niet konden trimmen. Dat is goed nieuws voor de rijken. En nog beter nieuws voor de minder rijken. De obstakels en lasten die de politiek oplegt, zijn meer obstakels om rijk te worden dan om rijk te zijn. De voordelen van afnemende meeropbrengsten van geweld en afnemende jurisdicties zullen ruimte creëren voor elke energieke en ambitieuze persoon om te profiteren van het einde van de politiek. Zelfs de consumenten van overheidsservices zullen profiteren naarmate ondernemers de voordelen van concurrentie uitbreiden.  Dientengevolge werd veel van de vindingrijkheid van interjurisdictionele concurrentie gekanaliseerd in militaire inspanningen. Maar de komst van de cybereconomie zal concurrentie op nieuwe voorwaarden brengen voor het leveren van soevereiniteitsservices. Een proliferatie van jurisdicties zal leiden tot een toename van experimenten met nieuwe manieren om contracten af te dwingen en de veiligheid van personen en eigendommen te waarborgen. De bevrijding van een groot deel van de wereldeconomie van politieke controle zal alle overgebleven vormen van overheid verplichten om meer op markttermen te opereren. Ze zullen uiteindelijk weinig keuze hebben dan de bevolking in de gebieden die ze bedienen meer als klanten te behandelen en minder zoals georganiseerde criminelen de slachtoffers van een afpersingsracket behandelen.

## Buiten de politiek

Wat de mythologie beschreef als het domein van de goden, zal een haalbare optie worden voor het individu – een leven buiten het bereik van koningen en raden. Eerst tientallen, dan honderden en uiteindelijk miljoenen individuen zullen ontsnappen aan de boeien van de politiek.  En terwijl ze dat doen, zullen ze het karakter van regeringen veranderen, het rijk van dwang verkleinen en de reikwijdte van de private controle over middelen verbreden.

De opkomst van het soevereine individu zal opnieuw het vreemde profetische vermogen van mythen aantonen.  De vroege agrarische volkeren, die weinig van de natuurwetten begrepen, stelden zich voor dat "krachten die wij bovennatuurlijk zouden noemen" wijdverspreid waren. Deze krachten werden soms gebruikt door mensen, soms door "geïncarneerde menselijke goden" die op mensen leken en met hen omgingen in wat Sir James George Frazer in *The Golden Bough* beschreef als "een grote democratie".[^7]

Toen de ouden zich de kinderen van Zeus voorstelden die onder hen leefden, werden ze geïnspireerd door een diep geloof in magie. Ze deelden met andere primitieve agrarische volkeren een ontzag voor de natuur en een bijgelovige overtuiging dat de werken van de natuur in beweging werden gezet door individuele wil, door magie. In die zin was er niets zelfbewust profetisch aan hun visie op de natuur en hun goden. Ze waren verre van het anticiperen op microtechnologie. Ze hadden zich de impact ervan niet kunnen voorstellen bij het veranderen van de marginale productiviteit van individuen duizenden jaren later. Ze hadden zeker niet kunnen voorzien hoe het de balans tussen macht en efficiëntie zou verschuiven en zo de manier waarop activa worden gecreëerd en beschermd zou revolutioneren. Toch heeft wat ze zich voorstelden toen ze hun mythen verzonnen een vreemde resonantie met de wereld die u waarschijnlijk zult zien.

Alt.Abracadabra


Het ‘abracadabra’ van de magische aanroeping vertoont bijvoorbeeld een merkwaardige gelijkenis met het wachtwoord dat wordt gebruikt om toegang te krijgen tot een computer. In sommige opzichten maakt hogesnelheidsberekening het al mogelijk om de magie van de geest na te bootsen. Vroege generaties van ‘digitale dienaren’ gehoorzamen de bevelen van degenen die de computers beheersen waarin ze zijn opgesloten, net zoals genies werden opgesloten in magische lampen. De virtuele realiteit van de informatietechnologie zal het rijk van menselijke wensen verbreden, waardoor bijna alles wat men zich kan voorstellen, echt lijkt. Telepresence zal levende individuen hetzelfde vermogen geven om afstanden met bovennatuurlijke snelheid te overbruggen en gebeurtenissen van verre te volgen, zoals de Grieken zich dat voordeden bij Hermes en Apollo. De Soevereine Individuen van het Informatietijdperk zullen, net als de goden van oude en primitieve mythen, mettertijd een soort ‘diplomatieke immuniteit’ genieten tegen de meeste politieke problemen die sterfelijke mensen in de meeste tijden en plaatsen hebben geteisterd.


De nieuwe Soevereine Individuen zullen, net als de goden uit de mythologie, in dezelfde fysieke omgeving opereren als de gewone, onderworpen burger, maar in een apart politiek rijk. De Soevereine Individuen, die over enorm veel grotere middelen beschikken en buiten het bereik van veel vormen van dwang vallen, zullen in het nieuwe millennium regeringen herontwerpen en economieën herstructureren. De volledige implicaties van deze verandering zijn bijna onvoorstelbaar.


Genie en Nemesis


Voor iedereen die menselijke aspiratie en succes liefheeft, zal het Informatietijdperk een overvloed aan mogelijkheden bieden. Dat is zeker het beste nieuws in vele generaties. Maar het is ook slecht nieuws. De nieuwe organisatie van de samenleving, zoals geïmpliceerd door het succes van individuele autonomie en de ware gelijke kansen op basis van verdienste, zal leiden tot zeer grote beloningen voor verdienste en grote individuele autonomie. Dit zal individuen veel meer verantwoordelijk maken voor zichzelf dan ze gewend waren te zijn tijdens de industriële periode. Het zal ook het onverdiende voordeel in levensstandaard verminderen dat bewoners van geavanceerde industriële samenlevingen gedurende de twintigste eeuw hebben genoten. Op het moment van schrijven heeft de bovenste 15 procent van de wereldbevolking een gemiddeld jaarlijks inkomen per hoofd van de bevolking van $ 21.000. De resterende 85 procent van de wereld heeft een gemiddeld inkomen van slechts $ 1.000. Dat enorme, opgepotte voordeel uit het verleden zal onder de nieuwe omstandigheden van het Informatietijdperk zeker verdwijnen.

Zo ja, dan zal het vermogen van natiestaten om inkomen op grote schaal te herverdelen, instorten. Informatietechnologie vergemakkelijkt een dramatisch toegenomen concurrentie tussen rechtsgebieden. Wanneer technologie mobiel is en transacties plaatsvinden in de cyberspace, zoals dat steeds meer zal gebeuren, zullen regeringen niet langer meer voor hun diensten kunnen rekenen dan ze waard zijn voor de mensen die ervoor betalen. Iedereen met een draagbare computer en een satellietverbinding kan vrijwel elke informatiebusiness overal ter wereld uitvoeren, en dat omvat vrijwel alle financiële transacties ter wereld ter waarde van vele biljoenen dollars.

Dit betekent dat u niet langer verplicht bent om in een rechtsgebied met hoge belastingen te wonen om een hoog inkomen te verdienen. In de toekomst, wanneer het meeste vermogen overal kan worden verdiend en zelfs overal kan worden uitgegeven, zullen regeringen die proberen te veel te rekenen als prijs voor domicilie, gewoon hun beste klanten wegjagen. Als onze redenering klopt, en dat geloven we, zal de natiestaat zoals we die kennen, niet overleven in iets dat lijkt op zijn huidige vorm.

## HET EINDE VAN DE NATIES



Veranderingen die de macht van dominante instellingen verminderen, zijn zowel verontrustend als gevaarlijk. Net zoals monarchen, edelen, pausen en potentaten in de beginfase van de moderne tijd genadeloos vochten om hun gebruikelijke privileges te behouden, zo zullen de regeringen van vandaag geweld gebruiken, vaak van een verborgen en willekeurige aard, in een poging om de klok terug te draaien. Verzwakt door de uitdaging van technologie, zal de staat steeds autonomere individuen, zijn voormalige burgers, behandelen met dezelfde wreedheid en diplomatie die hij tot nu toe heeft getoond in zijn omgang met andere regeringen. De komst van deze nieuwe fase in de geschiedenis werd op 20 augustus 1998 met een knal gemarkeerd, toen de Verenigde Staten ongeveer 200 miljoen dollar aan Tomahawk BGM-109 zeelanced cruise-raketten afvuurden op doelen die naar verluidt verband hielden met een in ballingschap levende Saoedische miljonair, Osama bin Laden. Bin Laden werd de eerste persoon in de geschiedenis die zijn satelliettelefoon als doelwit had van een aanval met cruise-raketten. Tegelijkertijd vernietigden de Verenigde Staten een farmaceutische fabriek in Khartoem, Soedan, ter ere van Bin Laden. De opkomst van Bin Laden als de belangrijkste vijand van de Verenigde Staten weerspiegelt een ingrijpende verandering in de aard van de oorlogvoering. Een enkel individu, zij het een met honderden miljoenen dollars, kan nu worden afgeschilderd als een plausibele bedreiging voor de grootste militaire macht van het industriële tijdperk. In verklaringen die doen denken aan propaganda die tijdens de Koude Oorlog over de Sovjet-Unie werd gebruikt, schilderden de Amerikaanse president en zijn adviseurs nationale veiligheid Bin Laden, een particulier, af als een transnationale terrorist en belangrijkste vijand van de Verenigde Staten.

Dezelfde militaire logica die Osama bin Laden tot belangrijkste vijand van de Verenigde Staten heeft verheven, zal zich manifesteren in de interne betrekkingen van regeringen met hun onderdanen. Steeds hardere methoden van afpersing zullen een logisch gevolg zijn van de opkomst van een nieuw type onderhandeling tussen regeringen en individuen. Technologie zal individuen bijna soevereiner maken dan ooit tevoren. En ze zullen zo worden behandeld. Soms gewelddadig, als vijanden, soms als gelijke partijen in onderhandeling, soms als bondgenoten. Maar hoe meedogenloos regeringen zich ook gedragen, vooral in de overgangsfase, het koppelen van de belastingdienst aan de CIA zal hen weinig baten. Ze zullen steeds meer door de noodzaak gedwongen worden om te onderhandelen met autonome individuen wier middelen niet langer zo gemakkelijk te beheersen zijn.

De veranderingen die de informatierevolutie met zich meebrengt, zullen niet alleen een financiële crisis voor regeringen veroorzaken, maar ook de desintegratie van alle grote structuren in de hand werken. Veertien imperiums zijn al verdwenen in de twintigste eeuw. Het uiteenvallen van imperiums maakt deel uit van een proces dat de natiestaat zelf zal ontbinden. De overheid zal zich moeten aanpassen aan de groeiende autonomie van het individu. Het belastend vermogen zal met 50 tot 70 procent dalen. Dit zal kleinere rechtsgebieden succesvoller maken. De uitdaging om concurrerende voorwaarden te scheppen om bekwame individuen en hun kapitaal aan te trekken, zal gemakkelijker te realiseren zijn in enclaves dan over continenten.

Wij geloven dat, naarmate de moderne natiestaat uiteenvalt, latere barbaren steeds meer macht achter de schermen zullen uitoefenen. Groepen zoals de Russische maffia, die de resten van de voormalige Sovjet-Unie leegt, andere etnische criminele bendes, nomenklatura's[^27], drugsbaronnen en afvallige geheime diensten zullen hun eigen wetten stellen. Dat doen ze al. Veel meer dan algemeen wordt begrepen, hebben de moderne barbaren de vormen van de natiestaat al geïnfiltreerd zonder het uiterlijk ervan sterk te veranderen. Het zijn microparasieten die zich voeden met een stervend systeem. Even gewelddadig en gewetenloos als een staat in oorlog, gebruiken deze groepen de technieken van de staat op kleinere schaal. Hun toenemende invloed en macht maken deel uit van de verkleining van de politiek. Microverwerking verkleint de omvang die groepen moeten bereiken om effectief geweld te gebruiken en te beheersen. Naarmate deze technologische revolutie zich ontvouwt, zal roofzuchtig geweld steeds meer buiten de centrale controle worden georganiseerd. Pogingen om geweld te beteugelen, zullen zich ook ontwikkelen op manieren die meer afhankelijk zijn van efficiëntie dan van de omvang van de macht.

### Geschiedenis omgekeerd

Het proces waarmee de natiestaat in de afgelopen vijf eeuwen is gegroeid, zal door de nieuwe logica van het informatietijdperk worden omgekeerd. Lokale machtscentra zullen zich opnieuw doen gelden naarmate de staat evolueert naar gefragmenteerde, overlappende soevereiniteiten.[^8] De groeiende macht van de georganiseerde misdaad is slechts een weerspiegeling van deze tendens. Multinationale bedrijven moeten al het niet-essentiële werk uitbesteden. Sommige conglomeraten, zoals AT&T, Unisys en ITT, hebben zichzelf in verschillende bedrijven gesplitst om winstgevender te functioneren. De natiestaat zal uiteenvallen als een onhandig conglomeraat, maar waarschijnlijk niet voordat hij daartoe wordt gedwongen door financiële crises.

Niet alleen verandert de macht in de wereld, maar ook het werk in de wereld verandert. Dit betekent dat de manier waarop bedrijven opereren onvermijdelijk zal veranderen. Het "virtuele bedrijf" is een bewijs van een ingrijpende transformatie in de aard van het bedrijf, die wordt vergemakkelijkt door de daling van de informatie- en transactiekosten. Wij onderzoeken de implicaties van de informatierevolutie voor het ontbinden van bedrijven en het afschaffen van de "goede baan". In het informatietijdperk zal een "baan" een taak zijn om te doen, geen positie die je "hebt". Microverwerking heeft geheel nieuwe horizonten van economische activiteit gecreëerd die territoriale grenzen overstijgen. Deze overstijging van grenzen en territoria is misschien wel de meest revolutionaire ontwikkeling sinds Adam en Eva uit het paradijs werden verdreven onder de straf van hun Schepper: "In het zweet uws aanschijns zult gij u brood eten." Naarmate de technologie de instrumenten die wij gebruiken revolutioneert, maakt zij ook onze wetten achterhaald, hervormt zij onze moraal en verandert zij onze percepties. Dit boek legt uit hoe.

Microprocessors en snel verbeterende communicatie maken het voor individuen al mogelijk om te kiezen waar ze werken. Transacties op internet of het World Wide Web kunnen versleuteld worden en zullen binnenkort bijna onmogelijk te traceren zijn voor belastinginners. Belastingvrij geld groeit al veel sneller offshore dan onshore fondsen die nog steeds onderworpen zijn aan de hoge belastingdruk die de natiestaat van de twintigste eeuw oplegde. Na de eeuwwisseling zal een groot deel van de wereldhandel migreren naar het nieuwe rijk van de cyberspace, een gebied waar regeringen niet meer macht zullen hebben dan over de bodem van de zee of de buitenste planeten. In cyberspace verdwijnen de bedreigingen van fysiek geweld die sinds mensenheugenis de alfa en omega van de politiek zijn geweest. In cyberspace zullen de zachtmoedigen en de machtigen elkaar op gelijke voet ontmoeten. Cyberspace is de ultieme offshore jurisdictie. Een economie zonder belastingen. Bermuda in the sky with diamonds.

Wanneer dit grootste belastingparadijs van allemaal volledig operationeel is, zullen alle fondsen in wezen offshore fondsen zijn naar goeddunken van hun eigenaar. Dit zal kettingreacties veroorzaken. De staat is gewend geraakt om zijn belastingbetalers te behandelen zoals een boer zijn koeien behandelt: ze in een weide houden om ze te melken. Binnenkort zullen de koeien vleugels hebben.

### De wraak van de naties


Net als een boze boer zal de staat ongetwijfeld in eerste instantie wanhopige maatregelen nemen om zijn ontsnappende kudde vast te binden en te belemmeren. Hij zal geheime en zelfs gewelddadige middelen gebruiken om de toegang tot bevrijdende technologieën te beperken. Zulke noodoplossingen zullen slechts tijdelijk werken, of helemaal niet. De natiestaat van de twintigste eeuw, met al zijn pretenties, zal verhongeren naarmate zijn belastinginkomsten dalen.

Wanneer de staat zich niet in staat acht om zijn toegezegde uitgaven te dekken door belastinginkomsten te verhogen, zal hij zijn toevlucht nemen tot andere, meer wanhopige maatregelen. Daartoe behoort het drukken van geld. Regeringen zijn gewend geraakt aan het genieten van een monopolie op valuta dat ze naar believen konden devalueren. Deze willekeurige inflatie is een opvallend kenmerk geweest van het monetaire beleid van alle staten van de twintigste eeuw. Zelfs de beste nationale valuta van de naoorlogse periode, de Duitse mark, verloor 71 procent van zijn waarde van 1 januari 1949 tot eind juni 1995. In dezelfde periode verloor de Amerikaanse dollar 84 procent van zijn waarde.[^9] Deze inflatie had hetzelfde effect als een belasting op iedereen die de valuta bezit. Zoals we later zullen zien, zal inflatie als inkomstenoptie grotendeels worden uitgesloten door de opkomst van cybergeld. Nieuwe technologieën zullen de bezitters van vermogen in staat stellen om de nationale monopolies die in de moderne tijd geld hebben uitgegeven en gereguleerd, te omzeilen.  De kredietcrises die in 1997 en 1998 door Azië, Rusland en andere opkomende economieën raasden, bewijzen dat nationale valuta's en nationale kredietratings anachronismen zijn die de soepele werking van de wereldeconomie schaden. Juist het feit dat de eisen van soevereiniteit vereisen dat alle transacties binnen een jurisdictie worden uitgedrukt in een nationale valuta, creëert de kwetsbaarheid voor fouten van centrale bankiers en aanvallen van speculanten die deflatoire crises in de ene jurisdictie na de andere veroorzaakten. In het informatietijdperk zullen individuen cybervaluta's kunnen gebruiken en zo hun monetaire onafhankelijkheid verklaren. Wanneer individuen hun eigen monetaire beleidslijnen kunnen voeren via het World Wide Web, zal het minder of helemaal niet uitmaken dat de staat de drukpersen uit het industriële tijdperk blijft beheersen. Hun belang voor het beheersen van de rijkdom van de wereld zal worden overtroffen door wiskundige algoritmen die geen fysiek bestaan hebben. In het nieuwe millennium zal cybergeld dat door particuliere markten wordt beheerd, fiatgeld dat door regeringen wordt uitgegeven, overtreffen. Alleen de armen zullen slachtoffer zijn van inflatie en de daaropvolgende ineenstorting in deflatie die het gevolg zijn van de kunstmatige hefboomwerking die fiatgeld in de economie injecteert.

Zelfs in traditioneel beschaafde landen zullen regeringen, verstoken van hun gebruikelijke mogelijkheden om te belasten en te inflatie, gemeen worden. Naarmate de inkomstenbelasting oninbaar wordt, zullen oudere en willekeurigere methoden van afpersing weer opduiken. De ultieme vorm van bronbelasting – de facto of zelfs openlijke gijzelneming – zal worden ingevoerd door regeringen die wanhopig proberen te voorkomen dat rijkdom buiten hun bereik ontsnapt. Ongelukkige individuen zullen merken dat ze op een bijna middeleeuwse manier worden uitgekozen en vastgehouden voor losgeld. Bedrijven die diensten aanbieden die de verwerkelijking van autonomie door individuen vergemakkelijken, zullen worden blootgesteld aan infiltratie, sabotage en verstoring. Willekeurige verbeurdverklaring van eigendommen, die al een veelvoorkomend verschijnsel is in de Verenigde Staten, waar het vijfduizend keer per week voorkomt, zal nog alomtegenwoordiger worden. Regeringen zullen de mensenrechten schenden, de vrije stroom van informatie censureren, nuttige technologieën saboteren en erger. Om dezelfde redenen waarom de inmiddels ter ziele gegane Sovjet-Unie tevergeefs probeerde de toegang tot personal computers en Xerox-machines te onderdrukken, zullen westerse regeringen proberen de cybereconomie met totalitaire middelen te onderdrukken.

## DE TIJD VAN DE NIEUWE LUDDIETEN


Dergelijke methoden kunnen populair blijken te zijn onder sommige bevolkingsgroepen. Het goede nieuws over individuele bevrijding en autonomie zal voor velen die niet tot de cognitieve elite behoren, slecht nieuws lijken. De grootste wrok zal waarschijnlijk geconcentreerd zijn onder degenen met een gemiddeld talent in de huidige rijke landen. Zij in het bijzonder kunnen het gevoel krijgen dat informatietechnologie een bedreiging vormt voor hun manier van leven. De begunstigden van georganiseerde dwang, waaronder miljoenen mensen die inkomsten ontvangen die door regeringen worden herverdeeld, kunnen[^9] de nieuwe vrijheid die Soevereine Individuen realiseren, kwalijk nemen. Hun verdriet zal de waarheid illustreren dat "waar je staat, wordt bepaald door waar je zit."

> Soms vroeg ik me af hoe ik zo'n diep lijden kon ervaren over het lot van een handvol mensen die ik niet kende, die een spel speelden tegen een andere groep vreemdelingen in een honderden kilometers verderop gelegen honkbalveld. Het antwoord is eenvoudig. Ik hield van mijn teams. Hoewel riskant, was het de moeite waard om te geven. Sport deed mijn bloed koken, maakte me enthousiast, deed mijn hart bonken. Ik vond het fijn om iets op het spel te hebben. Het leven was levendiger tijdens een wedstrijd. -- Craig Lambert


Het zou echter misleidend zijn om alle negatieve gevoelens die tijdens de komende transitiecrisis zullen ontstaan, toe te schrijven aan de blanke wens om ten koste van iemand anders te leven. Er komt meer bij kijken. Het karakter van de menselijke samenleving suggereert dat de komende Ludditische reactie ongetwijfeld een misleidende morele dimensie zal hebben. Denk eraan als een blanke wens met een morele pruik. We onderzoeken de morele en moraliserende dimensies van de transitiecrisis. Zelfzuchtige hebzucht van een bewuste soort heeft veel minder kracht om acties te motiveren dan zelfrechtvaardige woede. Hoewel de burgermythes van de twintigste eeuw snel aan belang verliezen, zijn ze niet zonder hun trouwe gelovigen. Iedereen die in de twintigste eeuw volwassen werd, is geïndoctrineerd in de plichten en verplichtingen van de burger van de twintigste eeuw. De resterende morele imperatieven uit de industriële samenleving zullen ten minste sommige neoluditische aanvallen op informatietechnologie stimuleren.

In die zin zal dit komende geweld minstens gedeeltelijk een uiting zijn van wat we "moreel anachronisme" noemen, de toepassing van morele regels die zijn ontleend aan een fase van het economische leven op de omstandigheden van een andere. Elke fase van de samenleving vereist haar eigen morele regels om individuen te helpen incentive traps te overwinnen die eigen zijn aan de keuzes die ze in die specifieke manier van leven maken. Net zoals een agrarische samenleving niet kon leven volgens de morele regels van een migrerende Eskimo-stam, zo kan de informatiesamenleving geen morele imperatieven bevredigen die zijn ontstaan om het succes van een militante industriële staat uit de twintigste eeuw te vergemakkelijken. We leggen uit waarom.

In de komende jaren zal moreel anachronisme in de kernlanden van het Westen zichtbaar zijn, net zoals het de afgelopen vijf eeuwen aan de periferie is waargenomen. Westerse kolonisten en militaire expedities stimuleerden dergelijke crises toen ze in contact kwamen met inheemse jagers-verzamelaars, maar ook met volkeren wier samenlevingen nog steeds waren georganiseerd voor landbouw. De introductie van nieuwe technologieën in anachronistische omgevingen veroorzaakte verwarring en morele crises. Het succes van christelijke missionarissen bij het bekeren van miljoenen inheemse volkeren kan grotendeels worden toegeschreven aan de lokale crises die werden veroorzaakt door de plotselinge introductie van nieuwe machtsverhoudingen van buitenaf. Dergelijke ontmoetingen deden zich steeds opnieuw voor, van de zestiende eeuw tot het begin van de twintigste eeuw. We verwachten soortgelijke botsingen aan het begin van het nieuwe millennium, naarmate informatiesamenlevingen die samenlevingen vervangen die langs industriële lijnen zijn georganiseerd.

### De nostalgie naar dwang


De opkomst van de Soevereine Individe zal niet volledig worden verwelkomd als een veelbelovende nieuwe fase van de geschiedenis, zelfs niet onder degenen die er het meest van profiteren. Iedereen zal wat bedenkingen hebben. En velen zullen innovaties verachten die de territoriale natiestaat ondermijnen. Het is een feit van de menselijke natuur dat radicale veranderingen van welke aard dan ook bijna altijd worden gezien als een dramatische verslechtering. Vijfhonderd jaar geleden zouden de hovelingen rond de hertog van Bourgondië hebben gezegd dat de zich ontvouwende innovaties die het feodalisme ondermijnden kwaadaardig waren. Zij dachten dat de wereld snel bergafwaarts ging, juist op het moment dat latere historici een explosie van menselijk potentieel zagen in de Renaissance. Evenzo zal wat vanuit het perspectief van het volgende millennium ooit als een nieuwe Renaissance kan worden gezien, angstaanjagend ogen voor vermoeide ogen uit de twintigste eeuw.

Er is een grote kans dat sommigen die zich beledigd voelen door de nieuwe manieren, evenals velen die erdoor worden benadeeld, onaangenaam zullen reageren. Hun nostalgie naar dwang zal waarschijnlijk gewelddadig worden. Ontmoetingen met deze nieuwe "Luddieten" zullen de overgang naar radicale nieuwe vormen van sociale organisatie minstens een beetje slecht nieuws maken voor iedereen. Wees voorbereid om te bukken. Met de snelheid van verandering die de morele en economische capaciteit van veel mensen in de levende generaties om zich aan te passen overtreft, kunt u een felle en verontwaardigde weerstand tegen de informatierevolutie verwachten, ondanks de grote belofte om de toekomst te bevrijden.

U moet zich voorbereiden op dergelijke onaangename gebeurtenissen. Een transitiecrisis staat ons te wachten. Deflationaire problemen, zoals de Aziatische crisis die zich in 1997 en 1998 door het Verre Oosten naar Rusland en andere opkomende economieën verspreidde, zullen sporadisch opduiken, omdat de verouderde nationale en internationale instellingen die overgebleven zijn uit het industriële tijdperk ontoereikend blijken voor de uitdagingen van de nieuwe, gedecentraliseerde, transnationale economie. De nieuwe informatie- en communicatietechnologieën ondermijnen de moderne staat meer dan welke politieke bedreiging voor zijn overwicht dan ook sinds Columbus’ zeereis. Dit is belangrijk, omdat machthebbers zelden vreedzaam gereageerd hebben op ontwikkelingen die hun gezag ondermijnden. Dat zullen ze nu waarschijnlijk ook niet doen.

De botsing tussen oud en nieuw zal de eerste jaren van het nieuwe millennium bepalen. We verwachten een tijd van groot gevaar en grote beloningen, een tijd van veel minder beschaving op sommige gebieden en ongekende mogelijkheden op andere. Steeds autonomere individuen en failliete, wanhopige regeringen zullen elkaar confronteren over een nieuwe kloof. We verwachten een radicale herstructurering van de aard van de soevereiniteit en de virtuele dood van de politiek voordat de transitie voorbij is. In plaats van staatsdominatie en controle over de middelen, zult u de privatisering van bijna alle diensten zien die regeringen nu leveren. Om onvermijdelijke redenen, die we in dit boek uitvoerig behandelen, zal de informatietechnologie het vermogen van de staat vernietigen om meer te rekenen voor haar diensten dan ze waard zijn voor de mensen die ervoor betalen.

> Regeringen zullen zich moeten bezighouden met de betekenis van soevereiniteit. -- Robert Martin

### Soevereiniteit via markten

In een mate die slechts tien jaar geleden weinigen zich zouden hebben kunnen voorstellen, zullen individuen steeds meer autonomie verwerven ten opzichte van territoriale natiestaten via marktmechanismen. Alle natiestaten staan voor het faillissement en een snelle erosie van hun gezag. Hoe machtig ze ook zijn, de macht die ze behouden is de macht om te vernietigen, niet om te bevelen. Hun intercontinentale raketten en vliegdekschepen zijn al relikwieën, net zo imposant en nutteloos als het laatste oorlogspaard van het feodalisme.

Informatietechnologie maakt een dramatische uitbreiding van markten mogelijk door de manier waarop activa worden gecreëerd en beschermd te veranderen. Dit is inderdaad revolutionair; het belooft revolutionairder te zijn voor de industriële samenleving dan het ontstaan van buskruit voor de feodale landbouw bleek te zijn. De transformatie van het jaar 2000 impliceert de[^11] commercialisering van soevereiniteit en het einde van de politiek, niet minder dan kanonnen het einde van de op eden gebaseerde feodale samenleving impliceerden. Burgerschap zal hetzelfde lot ondergaan als ridderlijkheid.

Wij geloven dat het tijdperk van individuele economische soevereiniteit aanbreekt. Net zoals staalfabrieken, telefoonbedrijven, mijnen en spoorwegen die ooit werden "genationaliseerd" snel zijn geprivatiseerd over de hele wereld, zult u binnenkort de ultieme vorm van privatisering zien: de ingrijpende denationalisering van het individu. Het soevereine individu van het nieuwe millennium zal niet langer een bezit van de staat zijn, een de facto post op de balans van de schatkist. Na de overgang van het jaar 2000 zullen denationaliseerde burgers helemaal geen burgers meer zijn, maar klanten.

### BANDWIDTH IS BELANGRIJKER DAN GRENZEN


De commercialisering van soevereiniteit zal de voorwaarden van het burgerschap in de natiestaat even achterhaald maken als ridderlijke eden leken na de val van het feodalisme. In plaats van zich te verhouden tot een machtige staat als burgers die belast moeten worden, zullen de soevereine individuen van de eenentwintigste eeuw klanten zijn van regeringen die vanuit een "nieuwe logische ruimte" opereren. Ze zullen onderhandelen over de minimale overheid die ze nodig hebben en ervoor betalen volgens contract. De regeringen van het informatietijdperk zullen volgens andere principes worden georganiseerd dan die welke de wereld de afgelopen eeuwen heeft leren verwachten. Sommige rechtsgebieden en soevereiniteitsdiensten zullen worden gevormd door middel van "assortive matching", een systeem waarbij affiniteiten, waaronder commerciële affiniteiten, de basis vormen waarop virtuele rechtsgebieden trouw verdienen. In zeldzame gevallen kunnen de nieuwe soevereiniteiten overblijfselen zijn van middeleeuwse organisaties, zoals de 900 jaar oude Soevereine Militaire Hospitaalorde van Sint-Jan van Jeruzalem, van Rhodos en van Malta. Beter bekend als de Orde van Malta, is de orde een affiniteitsgroep voor rijke katholieken, met 10.000 huidige leden en een jaarinkomen van enkele miljarden. De Orde van Malta geeft zijn eigen paspoorten, postzegels en geld uit en onderhoudt volledige diplomatieke betrekkingen met zeventig landen. Terwijl wij dit schrijven, onderhandelt zij met de Republiek Malta om het bezit van Fort Sint-Angelo te hernemen. Het in bezit nemen van het kasteel zou de Orde het ontbrekende ingrediënt van territorialiteit geven dat het in staat zal stellen om als een soevereiniteit erkend te worden. De Orde van Malta zou opnieuw een soevereine microstaat kunnen worden, onmiddellijk gelegitimeerd door een lange geschiedenis. Het was vanuit Fort Sint-Angelo dat de Orde van Malta de Turken terugsloeg tijdens het Grote Beleg van 1565. Inderdaad, zij regeerden Malta vele jaren daarna, totdat ze in 1798 door Napoleon werden verdreven. Als de Orde van Malta de komende jaren zou terugkeren, zou er geen duidelijker bewijs kunnen zijn dat het moderne systeem van natiestaten, ingesteld na de Franse Revolutie, slechts een intermezzo was in de langere loop van de geschiedenis, waarin het de norm was voor vele soorten soevereiniteiten om tegelijkertijd te bestaan.

Nog een heel ander model voor een postmoderne soevereiniteit, gebaseerd op assortive matching, is het Iridium-satelliettelefoonnetwerk. Op het eerste gezicht vindt u het misschien vreemd om een mobiele telefoondienst als een soort soevereiniteit te beschouwen. Toch heeft Iridium al erkenning gekregen als een virtuele soevereiniteit door internationale autoriteiten. Zoals u wellicht weet, is Iridium een wereldwijde mobiele telefoondienst waarmee abonnees oproepen kunnen ontvangen op één nummer, waar ze zich ook bevinden op de planeet, van Featherston, Nieuw-Zeeland, tot de Boliviaanse Chaco. Om oproepen te laten routeren naar Iridium-abonnees overal ter wereld, gezien de architectuur van de wereldwijde telecommunicatie, moesten de internationale telecomautoriteiten ermee instemmen Iridium te erkennen als een virtueel land, met zijn eigen landcode: 8816. Het is logisch gezien een kleine stap van een virtueel land dat bestaat uit satelliettelefoonabonnees naar soevereiniteit voor meer samenhangende virtuele gemeenschappen op het World Wide Web die grenzen overschrijden. Bandbreedte, of de draagcapaciteit van een communicatiemedium, is sneller gegroeid dan de rekencapaciteit na de uitvinding van transistoren. Als deze trend naar grotere bandbreedte zich voortzet, wat wij waarschijnlijk achten, is het slechts een kwestie van een paar jaar, kort na de eeuwwisseling, totdat de bandbreedte voldoende ruim wordt om het "metaversum" technisch mogelijk te maken, de alternatieve, cyberwereld die door de sciencefictionauteur Neal Stephenson werd bedacht. Stephenson's "metaversum" is een dichte virtuele gemeenschap met haar eigen wetten. Wij geloven dat het onvermijdelijk is dat, naarmate de cybereconomie rijker wordt, de deelnemers vrijstelling zullen zoeken en verkrijgen van de anachronistische wetten van natiestaten. De nieuwe cybergemeenschappen zullen minstens even rijk zijn en even bekwaam in het behartigen van hun belangen als de Soevereine Militaire Hospitaalorde van Sint-Jan van Jeruzalem, van Rhodos en van Malta. Sterker nog, ze zullen beter in staat zijn zich te doen gelden vanwege hun verreikende communicatie- en informatiecapabiliteiten. Wij onderzoeken nog andere modellen van gefragmenteerde soevereiniteit waarin kleine groepen effectief de soevereiniteit van zwakke natiestaten kunnen leasen en hun eigen economische havens kunnen exploiteren, zoals vrijhavens en vrijhandelszones dat vandaag de dag mogen doen.

Een nieuwe morele woordenschat zal nodig zijn om de relaties tussen soevereine individuen onderling en wat er overblijft van de overheid te beschrijven. We vermoeden dat, zodra de voorwaarden van deze nieuwe relaties scherper in beeld komen, ze veel mensen zullen choqueren die volwassen werden als 'burgers' van de natiestaten van de twintigste eeuw. Het einde van naties en de 'denationalisering van het individu' zullen sommige warm gekoesterde ideeën, zoals 'gelijke bescherming onder de wet', die machtsrelaties veronderstellen die binnenkort verouderd zullen zijn, doen leeglopen. Naarmate virtuele gemeenschappen meer samenhang krijgen, zullen ze erop staan dat hun leden ter verantwoording worden geroepen volgens hun eigen wetten, in plaats van volgens die van de voormalige natiestaten waarin ze toevallig wonen. Meerdere rechtssystemen zullen opnieuw naast elkaar bestaan in hetzelfde geografische gebied, zoals dat in de oudheid en in de middeleeuwen het geval was.

Net zoals pogingen om de macht van ridders in harnas te behouden gedoemd waren te mislukken in het licht van buskruitwapens, zo zijn de moderne ideeën van nationalisme en burgerschap gedoemd om te worden ondermijnd door microtechnologie. Sterker nog, ze zullen uiteindelijk komisch worden, net zoals de heilige principes van het vijftiende-eeuwse feodalisme in de zestiende eeuw belachelijk werden gemaakt. De gekoesterde burgerlijke ideeën van de twintigste eeuw zullen komische anachronismen zijn voor nieuwe generaties na de transformatie van het jaar 2000. De Don Quichot van de eenentwintigste eeuw zal niet een rondtrekkende ridder zijn die vecht om het feodalisme te doen herleven, maar een ambtenaar in een bruine pak, een belastinginner die verlangt naar een burger om te controleren.

## HET HERLEVEN VAN DE WETTEN VAN DE MARK

We beschouwen overheden zelden als concurrerende entiteiten, behalve in de breedste zin van het woord, dus het moderne inzicht in de reikwijdte en de mogelijkheden van soevereiniteit is verschrompeld. In het verleden, toen de machtsvergelijking het voor groepen moeilijker maakte om een stabiel monopolie op dwang te vestigen, was de macht vaak gefragmenteerd, liepen jurisdicties door elkaar heen en oefenden entiteiten van vele verschillende soorten een of meer van de attributen van soevereiniteit uit. Niet zelden genoot de nominale opperheer in de praktijk weinig macht. Overheden die zwakker zijn dan de natiestaten krijgen nu te maken met aanhoudende concurrentie in hun vermogen om een monopolie op dwang over een lokaal gebied af te dwingen. Deze concurrentie leidde tot aanpassingen in de beheersing van geweld en het aantrekken van loyaliteit die binnenkort weer nieuw zullen zijn.

Wanneer de reikwijdte van heren en koningen gering en de aanspraken van een of meer groepen op een grensgebied overlappend waren, gebeurde het vaak dat geen van beiden de ander beslissend kon overheersen. In de middeleeuwen waren er talloze grens- of 'mark'gebieden waar soevereiniteiten in elkaar overvloeiden. Deze gewelddadige grenzen bleven tientallen jaren of zelfs eeuwenlang bestaan in de grensgebieden van Europa. Er waren marken tussen gebieden met Keltische en Engelse controle in Ierland; tussen Wales en Engeland, Schotland en Engeland, Italië en Frankrijk, Frankrijk en Spanje, Duitsland en de Slavische grenzen van Midden-Europa en tussen de christelijke koninkrijken van Spanje en het Islamitische koninkrijk Granada. Dergelijke markgebieden ontwikkelden aparte institutionele en juridische vormen van een soort die we waarschijnlijk in het volgende millennium opnieuw zullen zien. Vanwege de concurrerende positie van de twee autoriteiten betaalden inwoners van markgebieden zelden belasting. Bovendien hadden ze meestal de keuze om te beslissen wiens wetten ze moesten gehoorzamen, een keuze die werd uitgeoefend via juridische concepten als 'bekentenis' en 'beslag' die nu vrijwel verdwenen zijn. We verwachten dat dergelijke concepten een prominente plaats zullen innemen in het recht van de informatiemaatschappijen.

### Nationale grenzen overstijgen

Vóór de natiestaat was het moeilijk om precies het aantal bestaande soevereiniteiten ter wereld te tellen, omdat ze op complexe wijze overlaptten en vele uiteenlopende vormen van organisatie macht uitoefenden. Dat zal opnieuw gebeuren. De scheidslijnen tussen territoria werden in het natiestaatsysteem duidelijk afgebakend en vastgelegd als grenzen. In het informatietijdperk zullen ze weer vaag worden. In het nieuwe millennium zal de soevereiniteit opnieuw gefragmenteerd worden. Nieuwe entiteiten zullen ontstaan die sommige, maar niet alle kenmerken vertonen die we zijn gaan associëren met regeringen.

Sommige van deze nieuwe entiteiten, zoals de Tempeliers en andere religieuze militaire orden uit de middeleeuwen, kunnen aanzienlijke rijkdom en militaire macht beheersen zonder enig vast territorium te controleren. Ze zullen georganiseerd zijn volgens principes die geen enkel verband houden met nationaliteit. Leden en leiders van religieuze corporaties die in delen van Europa in de middeleeuwen soevereine macht uitoefenden, ontleenden hun gezag in geen enkel opzicht aan een nationale identiteit. Ze kwamen uit alle etnische achtergronden en beweerden God, en niet enige verwantschap die leden van een nationaliteit gemeenschappelijk zouden moeten hebben, als hun trouw te verschuldigd te zijn.

### Koopliedenrepublieken van de cyberspace

U zult ook de wederopstanding zien van verenigingen van kooplieden en rijke individuen met semi-soevereine machten, zoals de Hanze (een confederatie van kooplieden) in de middeleeuwen. De Hanze die actief was op de Franse en Vlaamse beurzen, groeide uit tot een samenwerkingsverband van kooplieden uit zestig steden.[^10] De "Hanseatische Liga", zoals ze in het Engels pleonastisch wordt genoemd (de letterlijke vertaling is "Liga Liga"), was een organisatie van Germaanse koopliedengilden die bescherming bood aan leden en handelsovereenkomsten onderhandelde. Ze kwam semi-soevereine machten in een aantal Noord-Europese en Baltische steden te oefenen. Dergelijke entiteiten zullen in het nieuwe millennium in de plaats van de stervende natiestaat opduiken, bescherming bieden en helpen bij het afdwingen van contracten in een onveilige wereld.

Kortom, de toekomst zal de verwachtingen van hen die de burgerlijke mythes van de industriële samenleving van de twintigste eeuw hebben overgenomen, waarschijnlijk volledig in de war sturen. Daaronder vallen de illusies van de sociale democratie die ooit de meest begaafde geesten enthousiasmeerden en motiveerden. Ze gaan ervan uit dat samenlevingen evolueren zoals regeringen dat willen; bij voorkeur in reactie op opiniepeilingen en nauwkeurig getelde stemmen. Dit was nooit zo waar als het vijftig jaar geleden leek. Nu is het een anachronisme, net zozeer een artefact van het industrialisme als een roestige schoorsteen. De burgerlijke mythes weerspiegelen niet alleen een mentaliteit die de problemen van de samenleving ziet als vatbaar voor technische oplossingen; ze weerspiegelen ook een vals vertrouwen dat middelen en individuen in de toekomst net zo kwetsbaar zullen blijven voor politieke dwang als in de twintigste eeuw. Dat betwijfelen we. Marktkrachten, niet politieke meerderheden, zullen samenlevingen dwingen zichzelf op manieren te herconfigureren die de publieke opinie noch zal begrijpen noch zal verwelkomen. En terwijl dat gebeurt, zal de naïeve opvatting dat geschiedenis is wat mensen ervan willen maken, volkomen misleidend blijken.

Het zal daarom cruciaal zijn dat u de wereld opnieuw bekijkt. Dat betekent van buitenaf kijken om veel van wat u waarschijnlijk voor lief heeft genomen opnieuw te analyseren. Dit zal u in staat stellen tot een nieuw begrip te komen. Indien u er niet in slaagt om het conventionele denken te overstijgen in een tijd waarin het conventionele denken de realiteit uit het oog begint te verliezen, dan zult u eerder ten prooi vallen aan een epidemie van desoriëntatie die voor de deur staat. Desoriëntatie leidt tot fouten die uw bedrijf, uw investeringen en uw manier van leven zouden kunnen bedreigen.

> Het universum beloont ons voor het begrijpen ervan en straft ons voor het niet begrijpen ervan. Wanneer we het universum begrijpen, werken onze plannen en voelen we ons goed. Omgekeerd, als we proberen te vliegen door van een klif te springen en met onze armen te fladderen, zal het universum ons doden.[^11] -- JACK COHEN EN IAN STEWART

### Een nieuwe blik


Om uzelf voor te bereiden op de wereld die komt, moet u begrijpen waarom die anders zal zijn dan wat de meeste experts u vertellen. Dat houdt in dat u de verborgen oorzaken van verandering van dichtbij bekijkt. We hebben geprobeerd dit te doen met een onconventionele analyse die we de studie van megapolitiek noemen. In twee eerdere delen, *Blood in the Streets* en *The Great Reckoning*, betoogden we dat de belangrijkste oorzaken van verandering niet te vinden zijn in politieke manifesten of in de uitspraken van overleden economen, maar in de verborgen factoren die de grenzen veranderen waar macht wordt uitgeoefend. Vaak veranderen subtiele veranderingen in klimaat, topografie, microben en technologie de logica van geweld. Ze transformeren de manier waarop mensen hun levensonderhoud organiseren en zichzelf verdedigen.

onze aanpak om te begrijpen hoe de wereld verandert verschilt sterk van die van de meeste voorspellers. We zijn geen experts in enige zin, in die zin dat we doen alsof we veel meer weten over bepaalde ‘onderwerpen’ dan degenen die hun hele carrière hebben besteed aan het ontwikkelen van zeer gespecialiseerde kennis. Integendeel, we kijken van buitenaf naar binnen. We zijn welbekend met de onderwerpen waarover we voorspellingen doen. Meer nog, dit houdt in dat we zien waar de grenzen van de noodzaak worden getrokken. Wanneer die veranderen, verandert de samenleving noodzakelijkerwijs, ongeacht wat mensen misschien wensen.

Volgens ons is de sleutel tot het begrijpen van de evolutie van samenlevingen het begrijpen van factoren die de kosten en baten van het gebruik van geweld bepalen. Elke menselijke samenleving, van de jachtband tot het rijk, is beïnvloed door de interacties van megapolitieke factoren die de heersende versie van de ‘natuurwetten’ vaststellen. Het leven is altijd en overal complex. Het lam en de leeuw houden een delicaat evenwicht, dat aan de rand interageert. Als leeuwen plotseling sneller waren, zouden ze prooien vangen die nu ontsnappen. Als lammeren plotseling vleugels kregen, zouden leeuwen verhongeren. Het vermogen om geweld te gebruiken en zich ertegen te verdedigen is de cruciale variabele die het leven aan de rand verandert.

We plaatsen geweld centraal in onze theorie van megapolitiek om een goede reden. De beheersing van geweld is het belangrijkste dilemma waarmee elke samenleving wordt geconfronteerd. Zoals we schreven in *The Great Reckoning*:

>De reden dat mensen hun toevlucht nemen tot geweld is dat het vaak loont. Op sommige manieren is het eenvoudigste wat een man kan doen als hij geld wil, het nemen ervan. Dat is niet minder waar voor een leger mannen dat een oliebron in beslag neemt dan voor een enkele brutale dief die een portemonnee steelt. Macht, zoals William Playfair schreef, “heeft altijd de gemakkelijkste weg naar rijkdom gezocht, door degenen die het in bezit hadden aan te vallen.”

>De uitdaging voor welvaart is precies dat roofzuchtig geweld onder bepaalde omstandigheden goed betaalt. Oorlog verandert dingen. Het verandert de regels. Het verandert de verdeling van activa en inkomen. Het bepaalt zelfs wie leeft en wie sterft. Het is juist het feit dat geweld loont dat het moeilijk maakt om het te beheersen.

Door op deze manier te denken hebben we een aantal ontwikkelingen kunnen voorzien die beter geïnformeerde experts onmogelijk achtten. Zo was *Blood in the Streets*, gepubliceerd begin 1987, onze poging om de eerste stadia van de grote megapolitieke revolutie die nu gaande is in kaart te brengen. We beargumenteerden toen dat technologische veranderingen de machtsverhoudingen in de wereld destabliseerden. Tot onze belangrijkste punten behoorden:

We stelden dat de Amerikaanse overheersing aan het afnemen was, wat zou leiden tot economische onevenwichtigheden en problemen, waaronder een nieuwe beurscrash in de stijl van 1929. Experts waren vrijwel unaniem in hun ontkenning dat zoiets kon gebeuren. Toch werden de markten binnen zes maanden, in oktober 1987, getroffen door de meest heftige koersdaling van de eeuw.

We vertelden de lezers dat ze de ineenstorting van het communisme mochten verwachten. Ook hier lachten experts. Toch bracht 1989 de gebeurtenissen die 'niemand had kunnen voorspellen'. De Berlijnse Muur viel, terwijl revoluties communistische regimes van de Baltische staten tot Boekarest wegvaagden.

We legden uit waarom het multi-etnische rijk dat de bolsjewistische nomenklatura van de tsaren erfde, 'onvermijdelijk uiteen zou vallen'. Eind december 1991 werd de hamer-en-zeisvlag voor het laatst over het Kremlin gestreken toen de Sovjet-Unie ophield te bestaan.

Tijdens het hoogtepunt van de wapenopbouw onder Reagan beweerden we dat de wereld op de drempel stond van een ingrijpende ontwapening. Ook dit werd als onwaarschijnlijk, zo niet absurd, beschouwd. Toch brachten de volgende zeven jaar de meest ingrijpende ontwapening sinds het einde van de Eerste Wereldoorlog.

Op een moment dat experts in Noord-Amerika en Europa naar Japan wezen ter ondersteuning van de opvatting dat regeringen markten met succes kunnen manipuleren, zeiden wij het tegendeel. We voorspelden dat de hausse op de Japanse financiële activa zou eindigen in een crisis. Kort na de val van de Berlijnse Muur stortte de Japanse aandelenmarkt in en verloor bijna de helft van zijn waarde. We blijven geloven dat het ultieme dieptepunt het verlies van 89 procent, dat Wall Street na 1929 leed, kan evenaren of overtreffen.

Op een moment dat bijna iedereen, van het gezin uit de middenklasse tot de grootste vastgoedbeleggers ter wereld, leek te geloven dat de vastgoedmarkt alleen maar kon stijgen en niet dalen, waarschuwden wij voor een aanstaande vastgoedcrash. Binnen vier jaar verloren vastgoedbeleggers wereldwijd meer dan 1 biljoen dollar toen de waarde van onroerend goed daalde.

Lang voordat het voor de experts duidelijk was, legden wij in *Bloed op de straten* uit dat het inkomen van arbeiders was gedaald en op lange termijn zou blijven dalen. Nu we dit schrijven, bijna een decennium later, begint een slaperige wereld eindelijk door te krijgen dat dit waar is. De gemiddelde uurlonen in de Verenigde Staten zijn gedaald tot onder het niveau van de tweede Eisenhower-regering. In 1993 waren de gemiddelde jaarlijkse uurlonen in constante dollars $18.808. In 1957, toen Eisenhower zijn tweede ambtstermijn begon, waren de gemiddelde jaarlijkse uurlonen in de VS $18.903.

Hoewel de belangrijkste thema's van *Bloed op de straten* achteraf gezien opmerkelijk accuraat bleken te zijn, werden ze een paar jaar geleden nog beschouwd als volslagen onzin door de hoeders van het conventionele denken. Een recensent in *Newsweek* in 1987 weerspiegelde het bekrompen klimaat van de late industriële samenleving toen hij onze analyse afdeed als "een onnadenkende aanval op de rede".

U zou zich kunnen voorstellen dat *Newsweek* en soortgelijke publicaties in de loop der tijd zouden hebben ingezien dat onze analyse iets nuttigs had onthuld over de manier waarop de wereld aan het veranderen was. Niets van dat alles. De eerste editie van *De grote afrekening* werd begroet met dezelfde spottende vijandigheid die *Bloed op de straten* te beurt viel. Niemand minder dan de *Wall Street Journal* verwierp onze analyse categorisch als het gezwets van "je suf tante".

Afgezien van dit gegiechel, bleken de thema's van *De grote afrekening* minder belachelijk dan de hoeders van de orthodoxie beweerden.

We breidden onze voorspelling over het uiteenvallen van de Sovjet-Unie uit en onderzochten waarom Rusland en de andere voormalige Sovjetrepublieken een toekomst tegemoet gingen van toenemende burgerlijke onrust, hyperinflatie en dalende levensstandaarden.

We legden uit waarom de jaren negentig een decennium van downsizing zouden worden, inclusief voor het eerst een wereldwijde verkleining van overheden en bedrijven.

We voorspelden ook dat er een grote herdefinitie zou plaatsvinden van de voorwaarden voor herverdeling van inkomens, met scherpe bezuinigingen op de hoogte van de uitkeringen.  Tegen die tijd doemden tekenen van een fiscale crisis op van Canada tot Zweden, en Amerikaanse politici begonnen te spreken van 'een einde aan de verzorgingsstaat zoals we die kennen'.

We voorzagen en legden uit waarom de 'nieuwe wereldorde' een 'nieuwe wereldwanorde' zou blijken te zijn.  Lang voordat de wreedheden in Bosnië de krantenkoppen haalden, waarschuwden we dat Joegoslavië in een burgeroorlog zou vervallen.

Voordat Somalië in de anarchie wegzonk, legden we uit waarom het dreigende instorten van regeringen in Afrika ertoe zou leiden dat sommige landen daar feitelijk onder curatele zouden worden geplaatst.

We voorspelden en legden uit waarom militair islam het marxisme zou verdringen als belangrijkste ideologie van confrontatie met het Westen. Jaren voor de bomaanslag in Oklahoma en de aanslag op het World Trade Center, legden we uit waarom de Verenigde Staten geconfronteerd werden met een toename van terrorisme.

Voordat de krantenkoppen verschenen over de rellen die Los Angeles, Toronto en andere steden teisterden, legden we uit waarom de opkomst van criminele subculturen onder stedelijke minderheden de aanzet gaf tot wijdverspreid crimineel geweld.

We voorzagen ook 'de laatste depressie van de twintigste eeuw', die in 1989 in Azië begon en zich van de periferie naar het centrum van het mondiale systeem verspreidde. We zeiden dat de Japanse aandelenmarkt het pad van Wall Street na 1929 zou volgen, en dat dit zou leiden tot een kredietcrisis en een depressie. Hoewel massale overheidsinterventie in Japan en elders tijdelijk verhinderde dat markten de verslechtering van de kredietcondities volledig weerspiegelden, verdrong en verergerde dit alleen maar de economische problemen, waardoor de druk op concurrerende devaluaties en een systemische kredietcrisis toenam, zoals die in de jaren dertig de wereldeconomieën deed imploderen.

*The Great Reckoning* formuleerde ook een aantal controversiële stellingen die nog niet bevestigd zijn, of die het ontwikkelingsniveau dat we voorspelden nog niet bereikt hebben:

We zeiden dat de Japanse aandelenmarkt het pad van Wall Street na 1929 zou volgen, en dat dit zou leiden tot een kredietcrisis en een depressie. Hoewel de werkloosheidscijfers in Spanje, Finland en een paar andere landen die van de jaren dertig overtroffen, en een aantal landen, waaronder Japan, wel lokale depressies meemaakten, heeft er nog geen systemische kredietcrisis plaatsgevonden zoals die in de jaren dertig de wereldeconomieën deed imploderen.

Wij stelden dat het uiteenvallen van het commando- en controlesysteem in de voormalige Sovjet-Unie zou leiden tot de verspreiding van kernwapens in handen van mini-staten, terroristen en criminele bendes. Tot geluk van de wereld is dit niet gebeurd, althans niet in de mate die wij vreesden. Persberichten geven aan dat Iran verschillende tactische kernwapens op de zwarte markt heeft gekocht en Duitse autoriteiten hebben verschillende pogingen om kernmateriaal te verkopen verijdeld. Maar er is geen melding geweest van de inzet of het gebruik van kernwapens uit de arsenalen van de voormalige Sovjet-Unie.

Wij legden uit waarom de "oorlog tegen drugs" een recept was voor het ondermijnen van de politie- en justitiële systemen van landen waar drugsgebruik wijdverbreid is, met name de Verenigde Staten. Met tientallen miljarden dollars aan verborgen monopolie-winsten die zich elk jaar opstapelen, hebben drugshandelaren zowel de middelen als de aanmoediging om zelfs ogenschijnlijk stabiele landen te corrumperen. Hoewel de wereldmedia af en toe berichten hebben gepubliceerd die hintten naar infiltratie op hoog niveau van het Amerikaanse politieke systeem door drugsgeld, is het volledige verhaal nog niet verteld.

### Kijken waar anderen niet kijken


Ondanks de punten waarop onze voorspellingen verkeerd waren of verkeerd lijken in het licht van wat nu bekend is, kan de geschiedenis de toets der kritiek doorstaan. Veel van wat waarschijnlijk zal voorkomen in toekomstige economische geschiedenissen van de jaren negentig werd voorspeld of verwacht en uitgelegd in *The Great Reckoning*. Veel van onze voorspellingen waren geen eenvoudige extrapolaties of uitbreidingen van trends, maar voorspellingen van grote afwijkingen van wat als normaal werd beschouwd sinds de Tweede Wereldoorlog. Wij waarschuwden dat de jaren negentig dramatisch anders zouden zijn dan de voorgaande vijf decennia. Als we het nieuws van 1991 tot en met 1995 lezen, zien we dat de thema's van *The Great Reckoning* bijna dagelijks werden bevestigd.

Wij zien deze ontwikkelingen niet als voorbeelden van geïsoleerde moeilijkheden, problemen hier, problemen daar, maar als schokken en trillingen die langs dezelfde breuklijn lopen. De oude orde wordt omvergeworpen door een megapolitieke aardbeving die instellingen zal revolutioneren en de manier waarop denkende mensen de wereld zien zal veranderen.

Ondanks de centrale rol van geweld bij het bepalen van de werking van de wereld, krijgt het verrassend weinig serieuze aandacht. De meeste politieke analisten en economen schrijven alsof geweld een kleine ergernis is, zoals een vlieg die om een taart zoemt, en niet de kok die hem heeft gebakken.

### Een andere megapolitieke pionier


Er is eigenlijk zo weinig helder nagedacht over de rol van geweld in de geschiedenis, dat een bibliografie van megapolitieke analyses op een enkel vel papier zou kunnen worden geschreven. In *The Great Reckoning* baseerden we ons op en werkten we argumenten uit van een bijna volledig vergeten klassieker van de megapolitieke analyse, William Playfair's *An Enquiry into the Permanent Causes of the Decline and Fall of Powerful and Wealthy Nations*, gepubliceerd in 1805. Een van onze uitgangspunten is het werk van Frederic C. Lane. Lane was een middeleeuwse historicus die in de jaren veertig en vijftig verschillende doordringende essays schreef over de rol van geweld in de geschiedenis. Misschien wel het meest uitgebreide daarvan was "Economic Consequences of Organized Violence," dat in 1958 verscheen in het *Journal of Economic History*. Weinig mensen buiten professionele economen en historici hebben het gelezen, en de meesten lijken het belang ervan niet te hebben onderkend. Net als Playfair schreef Lane voor een publiek dat nog niet bestond.

### Inzichten voor het informatietijdperk


Lane publiceerde zijn werk over geweld en de economische betekenis van oorlog lang voordat het informatietijdperk aanbrak. Hij schreef zeker niet anticiperend op microverwerking of de andere technologische revoluties die zich nu ontvouwen. Toch vormen zijn inzichten in geweld een kader voor het begrijpen van hoe de samenleving zal worden herconfigureerd in de informatie-revolutie.

Het venster waar Lane doorheen naar de toekomst keek, was er een waardoor hij in het verleden tuurde. Hij was een middeleeuwse historicus, en in het bijzonder een historicus van een handelsstad, Venetië, wiens welvaart steeg en daalde in een gewelddadige wereld. Door na te denken over de opkomst en ondergang van Venetië, werd zijn aandacht getrokken door kwesties die kunnen helpen de toekomst te begrijpen. Hij zag het feit dat de manier waarop geweld wordt georganiseerd en gecontroleerd een grote rol speelt bij het bepalen van 'het gebruik van schaarse middelen'.[^13]

Wij geloven dat Lane's analyses van het concurrerende gebruik van geweld ons veel kunnen vertellen over hoe het leven zich waarschijnlijk zal ontwikkelen in het informatietijdperk. Maar verwacht niet dat de meeste mensen zo'n onmodieus abstract argument zullen opmerken, laat staan volgen. Terwijl de aandacht van de wereld gekluisterd is aan oneerlijke debatten en eigenzinnige persoonlijkheden, blijven de kronkelwegen van de megapolitiek bijna onopgemerkt. De gemiddelde Noord-Amerikaan heeft waarschijnlijk honderd keer meer aandacht besteed aan O.J. Simpson dan aan de nieuwe microtechnologieën die op het punt staan zijn baan te vervangen en het politieke systeem waarvan hij afhankelijk is voor werkloosheidsuitkeringen, te ondermijnen.

## De ijdelheid van wensen

De neiging om het fundamenteel belangrijke te overzien, is niet beperkt tot de couch potato die naar de televisie kijkt. Conventionele denkers van alle soorten en maten nemen een van de voorwendsels van de natiestaat waar: dat de opvattingen van mensen bepalen hoe de wereld verandert. Blijkbaar verfijnde analisten vervallen in verklaringen en voorspellingen die belangrijke historische ontwikkelingen interpreteren alsof ze op een wensdrijvende manier werden bepaald. Een treffend voorbeeld van dit soort redenering verscheen op de opinierubriek van de *New York Times*, net toen wij 'Goodbye, NationState, Hello...What?' schreven, door Nicholas Colchester.[^14] Niet alleen was het onderwerp, het einde van de natiestaat, precies het onderwerp dat wij behandelen, maar de auteur presenteert zichzelf als een uitstekende markering om te illustreren hoe ver onze manier van denken van de norm verwijderd is. Colchester is geen simpele ziel. Hij schreef als editorial director van de Economist Intelligence Unit. Als iemand een realistisch beeld van de wereld moet vormen, dan is hij het wel. Toch geeft zijn artikel op verschillende plaatsen duidelijk aan dat 'de komst van een internationale regering nu logisch onstuitbaar is'.

Waarom? Omdat de natiestaat wankelt en de economische krachten niet langer kan beheersen.

In onze ogen grenst deze veronderstelling aan het absurde.  Te veronderstellen dat er een specifieke nieuwe vorm van bestuur zal ontstaan, enkel omdat een andere is mislukt, is een drogreden.  Volgens die redenering zouden Haïti en Zaïre al lang een beter bestuur hebben gehad, simpelweg omdat wat ze hadden zo onvoldoende was.

Colchesters standpunt, wijdverbreid onder de weinigen die in Noord-Amerika en Europa over zulke zaken nadenken, houdt volkomen geen rekening met de grotere megapolitieke krachten die bepalen welke soorten politieke systemen daadwerkelijk levensvatbaar zijn. Dat is het onderwerp van dit boek.  Wanneer de technologieën die de vorm geven aan het nieuwe millennium worden overwogen, is het veel waarschijnlijker dat we niet één wereldregering zullen zien, maar microroveringen, of zelfs omstandigheden die grenzen aan anarchie.

Voor elke serieuze analyse van de rol van geweld bij het bepalen van de regels waaronder iedereen opereert, zijn tientallen boeken geschreven over de complexiteit van tarwesubsidies, en honderden meer over obscure aspecten van het monetaire beleid.  Dit tekort aan denken over de cruciale kwesties die de loop van de geschiedenis daadwerkelijk bepalen, weerspiegelt waarschijnlijk de relatieve stabiliteit van de machtsverhoudingen gedurende de afgelopen eeuwen. De vogel die inslaapt op de rug van een nijlpaard, denkt niet na over het verlies van zijn zitstok totdat het nijlpaard zich daadwerkelijk beweegt. Dromen, mythen en fantasieën spelen een veel grotere rol bij het informeren van de zogenaamde sociale wetenschappen dan we gewoonlijk denken.

Dit is vooral duidelijk in de overvloedige literatuur over economische rechtvaardigheid. Miljoenen woorden zijn uitgesproken en geschreven over economische rechtvaardigheid en onrechtvaardigheid voor elke pagina die gewijd is aan een zorgvuldige analyse van hoe geweld de samenleving vormgeeft en zo de grenzen bepaalt waaronder economieën moeten functioneren.  Formuleringen van economische rechtvaardigheid in de moderne context veronderstellen echter dat de samenleving wordt gedomineerd door een instrument van dwang zo krachtig dat het de goede dingen van het leven kan afnemen en herverdelen.  Zulke macht heeft slechts gedurende enkele generaties van de moderne periode bestaan. Nu vervaagt ze.

Grote broer op sociale zekerheid

Industriële technologie gaf regeringen in de twintigste eeuw meer controlemiddelen dan ooit tevoren.  Een tijdlang leek het onvermijdelijk dat regeringen zo effectief zouden worden in het monopoliseren van geweld dat er weinig ruimte overbleef voor individuele autonomie. Niemand halverwege de eeuw keek uit naar het succes van de soevereine individu.

Sommige van de meest scherpzinnige waarnemers van het midden van de twintigste eeuw raakten ervan overtuigd, op basis van het toenmalige bewijsmateriaal, dat de neiging van de natiestaat om macht te centraliseren zou leiden tot totalitaire dominantie over alle aspecten van het leven. In George Orwells *1984* (1949) zag Grote Broer toe hoe het individu tevergeefs worstelde om een marge van autonomie en zelfrespect te behouden. Het leek een verloren zaak. Friedrich von Hayeks *De weg naar de slavernij* (1944) bekeek het op een meer wetenschappelijke manier door te stellen dat de vrijheid verloren ging aan een nieuwe vorm van economische controle die de staat tot meester van alles maakte. Deze werken werden geschreven vóór de opkomst van de microverwerking, die een hele reeks technologieën heeft voortgebracht die het vermogen van kleine groepen en zelfs individuen vergroten om onafhankelijk van centraal gezag te functioneren.

Hoe scherpzinnig waarnemers als Hayek en Orwell ook waren, ze waren te pessimistisch. De geschiedenis heeft haar verrassingen gebracht. Het totalitaire communisme heeft het jaar 1984 nauwelijks overleefd. Een nieuwe vorm van slavernij kan in het volgende millennium nog opduiken als regeringen erin slagen de bevrijdende aspecten van microtechnologie te onderdrukken. Maar het is veel waarschijnlijker dat we ongekende mogelijkheden en autonomie voor het individu zullen zien. Waar onze ouders zich zorgen over maakten, blijkt misschien helemaal geen probleem te zijn. Wat zij als vaste en permanente kenmerken van het sociale leven beschouwden, lijkt nu gedoemd te verdwijnen. Waar de noodzaak grenzen stelt aan de menselijke keuze, passen we ons aan en reorganiseren we ons leven dienovereenkomstig.

### De gevaren van voorspellingen



Ongetwijfeld brengen we onze kleine mate van waardigheid in gevaar door te proberen diepe veranderingen in de organisatie van het leven en de cultuur die het bindt te voorzien en uit te leggen. De meeste voorspellingen zijn gedoemd om over een tijdje dwaas te lijken. En hoe dramatischer de verandering die ze voor ogen hebben, hoe gênanter fout ze meestal blijken te zijn. De wereld gaat niet ten onder. De ozonlaag verdwijnt niet. De komende ijstijd lost op in globale opwarming. Ondanks alle alarmerende berichten daartegenover zit er nog steeds olie in de tank. Meneer Antrobus, de gewone man uit *The Skin of Our Teeth*, vermijdt bevriezing, overleeft oorlogen en bedreigde economische rampen en wordt oud zonder de weloverwogen alarmen van experts in acht te nemen.

De meeste pogingen om de toekomst te ‘onthullen’ blijken al snel komisch. Zelfs waar eigenbelang een sterke aanleiding tot helder denken biedt, is vooruitziende blik vaak bijziend. In 1903 beweerde het bedrijf Mercedes dat er nooit meer dan een miljoen auto’s wereldwijd zouden zijn. De reden was dat het onwaarschijnlijk was dat wereldwijd een miljoen ambachtslieden zouden kunnen worden opgeleid tot chauffeur.[^15]

Dit besef zou ons de mond moeten snoeren. Dat doet het niet. We zijn niet bang om in de rij te gaan staan voor een welverdiend deel van de spot. Als we de zaken ernstig misgrijpen, mogen toekomstige generaties er lustig op los lachen, ervan uitgaande dat iemand zich nog herinnert wat we zeiden. Een gedachte wagen is het risico lopen om het mis te hebben. We zijn toch niet zo stijf en nutteloos dat we bang zijn om fouten te maken. Integendeel. We wagen liever gedachten die nuttig voor u zouden kunnen blijken te zijn dan ze te onderdrukken uit vrees dat ze achteraf overdreven of gênant zouden blijken te zijn.

Zoals Arthur C. Clarke scherpzinnig opmerkte, zijn de twee belangrijkste redenen waarom pogingen om de toekomst te voorspellen meestal mislukken ‘gebrek aan lef en gebrek aan verbeelding.’[^16] Van de twee, schreef hij, ‘lijkt gebrek aan lef het meest voorkomend; het treedt op wanneer zelfs met alle relevante feiten, de aspirant-profeet niet kan inzien dat ze wijzen op een onontkoombare conclusie. Sommige van deze mislukkingen zijn zo belachelijk dat ze bijna onvoorstelbaar zijn.’[^17]

Waar onze verkenning van de informatierevolutie tekortschiet, zoals onvermijdelijk zal gebeuren, zal de oorzaak meer te wijten zijn aan een gebrek aan verbeelding dan aan een gebrek aan lef. Het voorspellen van de toekomst is altijd een gewaagde onderneming geweest, een onderneming die terecht scepsis oproept. Misschien zal de tijd uitwijzen dat onze deducties volledig naast de kwestie zijn. In tegenstelling tot Nostradamus doen we niet alsof we profetische persoonlijkheden zijn. We voorspellen de toekomst niet door een toverstaf in een kom water te roeren of door horoscopen te werpen. We schrijven ook niet in cryptische verzen. Ons doel is u te voorzien van een nuchtere, onafhankelijke analyse van kwesties die van groot belang voor u zouden kunnen blijken te zijn.

We voelen ons verplicht om onze standpunten uiteen te zetten, zelfs waar ze ketters lijken, juist omdat ze anders misschien niet gehoord zouden worden. In de gesloten mentale atmosfeer van de late industriële samenleving circuleren ideeën niet zo vrij als ze zouden moeten doen via de gevestigde media.

Dit boek is geschreven in een constructieve geest. Het is het derde dat we samen hebben geschreven, waarin we verschillende fasen van de grote verandering die nu gaande is analyseren. Net als *Bloed in de straten* en *De grote afrekening*, is het een denk-oefening. Het verkent het einde van de industriële samenleving en de herconfiguratie ervan in nieuwe vormen. We verwachten in de komende jaren verbazingwekkende paradoxen te zien. Aan de ene kant zul je de realisatie van een nieuwe vorm van vrijheid zien, met de opkomst van de Soevereine Individe. Je kunt een bijna volledige bevrijding van de productiviteit verwachten. Tegelijkertijd verwachten we de ondergang van de moderne natiestaat. Veel van de zekerheden van gelijkheid die westerlingen in de twintigste eeuw als vanzelfsprekend zijn gaan beschouwen, zijn gedoemd om daarmee te verdwijnen. We verwachten dat de representatieve democratie zoals die nu bekend is, zal vervagen en vervangen zal worden door de nieuwe democratie van keuze in de cybermarktplaats. Als onze gevolgtrekkingen juist zijn, zullen de politiek van de volgende eeuw veel gevarieerder en minder belangrijk zijn dan die waaraan we gewend zijn geraakt.

We zijn ervan overtuigd dat ons betoog gemakkelijk te volgen zal zijn, ondanks het feit dat het leidt door een gebied dat intellectueel gezien gelijk staat aan de afgelegen gebieden en achterbuurten. Als onze betekenis op sommige plaatsen niet helemaal duidelijk is, komt dat niet doordat we flauw willen doen, of de bekende dubbelzinnigheid gebruiken van degenen die doen alsof ze de toekomst kunnen voorspellen door cryptische uitspraken te doen. We zijn geen dubbelzinnige sprekers. Als onze argumenten onduidelijk zijn, komt dat doordat we de taak niet hebben volbracht om op een manier te schrijven die overtuigende ideeën toegankelijk maakt. In tegenstelling tot veel voorspellers, willen we dat je onze gedachtegang begrijpt en zelfs herhaalt. Deze is niet gebaseerd op psychische dromen of de bewegingen van planeten, maar op ouderwetse, nuchtere logica. Om heel logische redenen geloven we dat microprocessing onvermijdelijk de natiestaat zal ondermijnen en vernietigen, waarbij in het proces nieuwe vormen van sociale organisatie ontstaan. Het is zowel nodig als mogelijk voor jou om ten minste een aantal details van de nieuwe manier van leven te voorzien, die er eerder kan zijn dan je denkt.


### Ironieën van een voorspelde toekomst


Eeuwenlang werd het einde van dit millennium gezien als een zwanger moment in de geschiedenis. Meer dan 850 jaar geleden bepaalde Sint-Malachias 2000 als de datum van het Laatste Oordeel. De Amerikaanse helderziende Edgar Cayce zei in 1934 dat de aarde in het jaar 2000 van as zou verschuiven, waardoor Californië in tweeën zou splitsen en New York City en Japan zouden overstromen. Een Japanse raketwetenschapper, Hideo Itokawa, kondigde in 1980 aan dat de uitlijning van de planeten in een "Groot Kruis" op 18 augustus 1999 wijdverspreide milieuschade zou veroorzaken, wat zou leiden tot het einde van het menselijk leven op aarde.

Zulke visioenen van een apocalyps zijn een gemakkelijke prooi voor spot. Immers, het jaar 2000, hoewel een indrukwekkend rond getal, is slechts een willekeurig artefact van de christelijke kalender zoals die in het Westen is aangenomen. Andere kalenders en dateringssystemen berekenen eeuwen en millennia vanaf verschillende startpunten. Volgens de berekening van de islamitische kalender bijvoorbeeld, zal 2000 na Christus het jaar 1378 zijn. Een jaar dat zo gewoon klinkt als maar kan. Volgens de Chinese kalender, die zich elke zestig jaar herhaalt, is 2000 na Christus gewoon weer een jaar van de draak. Het maakt deel uit van een continue cyclus die millennia in het verleden teruggaat. Toch is er meer dan alleen theologische investering in het jaar 2000. Het belang ervan wordt niet alleen ondersteund door de christelijke traditie, maar ook door de beperkingen van de mid-century-informatietechnologie. Het zogenaamde Y2K- of jaar 2000-computerprobleem, een potentieel verwoestende logische fout in miljarden regels computercode, zou apocalyptische omstandigheden kunnen benaderen door essentiële elementen van de industriële samenleving op middernacht van het millennium af te sluiten. Veel computers en microprocessoren gebruiken software die bewaard en gerecycled is vanaf de eerste dagen van computers, toen geheugenruimte, tegen $600.000 per megabyte, waardevoller was dan goud. Om dure ruimte te besparen, volgden de eerste programmeurs data met slechts de laatste twee cijfers van het jaar. Deze conventie van het gebruik van datumvelden met twee cijfers werd overgenomen in de meeste software die in mainframecomputers werd gebruikt, en vond zelfs wijdverbreid gebruik in personal computers en zogenaamde embedded chips, microprocessoren die worden gebruikt om bijna alles te besturen, van VCR's tot auto-ontstekingssystemen, beveiligingssystemen, telefoons, de schakelingssystemen die het telefoonnetwerk besturen, proces- en controlesystemen in fabrieken, energiecentrales, olieraffinaderijen, chemische fabrieken, pijpleidingen en nog veel meer. Aldus afgekort tot een veld met twee cijfers, zou het jaar 1999 "99" zijn. Het probleem is wat er gebeurt als 00 voor het jaar 2000 verschijnt. Veel computers zullen dit lezen als 1900. Dit kan het voor veel onbehandelde computers en andere digitale apparaten onmogelijk maken om het jaar 2000 in datumvelden te herkennen.

Het gevolg zal een enorm probleem zijn van gegevenscorruptie, wat een onbedoelde illustratie zal vormen van een nieuw potentieel voor informatieoorlogvoering. In het informatietijdperk zullen potentiële tegenstanders in staat zijn om grote schade aan te richten door het tot ontploffing brengen van 'logische bommen' die de functies van essentiële systemen saboteren door de gegevens te corrumperen waarop hun functioneren berust. Als militaire oefening hoef je bijvoorbeeld geen vliegtuig neer te schieten als je gegevens kunt corrumperen die cruciaal zijn voor de veilige werking ervan. Gegevenscorruptie kan bijna net zoveel doen als fysieke wapens om de functie van een moderne samenleving te dwarsbomen. Dat dit potentieel verstrekkende gevolgen heeft, moet na enige reflectie duidelijk zijn. Zo meldde de *Mail* van Londen op 14 december 1997 dat luchtvaartmaatschappijen over de hele wereld van plan waren om honderden vluchten op 1 januari 2000 te annuleren uit angst dat luchtverkeersleidingsystemen zouden uitvallen.[^19] Potentiële problemen betreffen niet alleen de luchtverkeersystemen, maar ook datumgevoelige functies die in de vliegtuigen zelf zijn ingebouwd. Volgens Boeing vereisen veel vliegtuigen Y2K-reparatie. Veel apparaten kunnen een probleem hebben als ze proberen een gebeurtenis te loggen op een ongeldige datum. De fly-by-wire computergestuurde systemen die vliegtuigen bedienen, kunnen defect raken als ze zijn geprogrammeerd om te concluderen dat cruciaal onderhoud voor het laatst in het jaar 1900 is uitgevoerd. Ze kunnen zelfs in een foutlus terechtkomen en afsluiten.

De potentieel dodelijke feedback-effecten van een logische tijdbom die niet-compatibele controlesystemen uitschakelt, zouden de eeuwwisseling tot een gedenkwaardige datum kunnen maken om onaangename redenen. Vergeet niet dat je door veel apparaten die in een foutlus terechtkomen en afsluiten beïnvloed kunt worden, zelfs als je het geluk hebt je niet in de lucht te bevinden wanneer het nieuwe millennium begint.

Je doet er goed aan een ongeluk te voorkomen dat voortkomt uit niet-Y2K-compatibele pacemakers, of gewoon dronken millenniumvierders, want als de pacemakers uitvallen, kan het telefoonsysteem ook uitvallen, waardoor de ambulance mogelijk nooit zal komen. Tenzij je in Brazilië of Oekraïne woont, ben je gewend om de telefoon op te nemen of de autotelefoon aan te zetten en automatisch een kiestoon te krijgen. Gelukkig hoef je je zelden zorgen te maken over de technische details van hoe het telefoonsysteem werkt. Maar het blijkt dat telefoonnetwerkswitches en routers sterk afhankelijk zijn van de datum. Alle verbindingen worden geregistreerd met een datum en tijd, wat cruciaal is voor het berekenen van de gespreksduur voor facturering. Als je toevallig om 11:59:30 uur op 31 december 1999 een gesprek van één minuut voert en om 12:00:00 uur de systemen je gesprek lezen als een negatieve duur van meer dan 99 jaar, zijn foutlussen en storingen mogelijk. Hoewel lange-afstandsbedrijven grote bedragen uitgeven om hun switches te upgraden om ze compatibel te maken met het jaar 2000, en lokale serviceproviders vermoedelijk ook, als zelfs een paar kleinere bedrijven niet voldoen en uitvallen, kan het hele netwerk worden getroffen. Je zult geluk hebben als je op 1 januari 2000 een kiestoon krijgt.

In de woorden van de Y2K-expert Peter de Jager: 'Als we het vermogen verliezen om een telefoontje te plegen, dan verliezen we alles. We verliezen elektronische fondsoverdrachten, we verliezen handel, we verliezen bancaire activiteiten in de filialen.' En de daaropvolgende gevolgen van Y2K-storingen zouden verder kunnen gaan dan dat.

Tegenwoordig weet niemand hoe wijdverspreid cruciale systemen zullen crashen vanwege het jaar 2000-probleem. Ingebedde systemen die niet kunnen worden geherprogrammeerd maar moeten worden vervangen als ze niet functioneren op een datumgevoelige basis, worden aangetroffen in kaarten, vrachtwagens en bussen die na 1976 zijn gebouwd. (Misschien raak je niet betrokken bij een ongeluk met voertuigen die worden bestuurd door personen met niet-compatibele pacemakers, omdat hun voertuigen mogelijk niet starten.) Ingebedde systemen zijn ook wijdverspreid in alle soorten energiecentrales, water- en rioleringssystemen, medische apparaten, militaire uitrusting, vliegtuigen, offshore olieplatforms, olietankers, alarmsystemen en liften. Hoewel veel assemblages van microprocessoren geen datumgevoelige functies uitvoeren, kunnen ze niettemin afhankelijk zijn van een klok, die mogelijk Y2K-gevoelig is, voor hun interne werking.

## Mainframes en de Y2K-tijdbom


De grootschalige command and control-systemen van overheden en grote bedrijven, die grote transactievolumes verwerken op mainframecomputers, stonden aanvankelijk centraal in de zorgen rond Y2K. Omdat ze draaien op grote machines met software die vaak tientallen jaren oud is en meestal niet compatibel, richtten de eerste alarmeringen over Y2K, begin jaren negentig door Peter de Jager aangekaart, zich voornamelijk op de noodzaak om de besturingssystemen van grote, multiprocessing mainframes te upgraden. De heer De Jager uitte zijn zorgen dat er onvoldoende programmeurs zouden zijn die bedreven waren in COBOL, de oude mainframetaal, om de nodige patches en reparaties aan datumgevoelige code te voltooien, zelfs als elk bedrijf en elke overheidsinstantie met een kwetsbaar systeem enkele jaren geleden een spoedprogramma was gestart. Aangezien dit niet gebeurd is en veel beheerders van datumgevoelige informatiesystemen pas net begonnen zijn hun kwetsbaarheid in te schatten, kunt u met grote zekerheid voorspellen dat veel mainframesystemen niet klaar zullen zijn om probleemloos door te werken in het jaar 2000.


Dit is zeker een grote zorg, omdat er eigenlijk geen alternatief is voor computerverwerking zoals de economie nu gestructureerd is. De meeste bedrijven die groot genoeg zijn om een mainframe te gebruiken voor hun transacties, zijn afhankelijk van transactievolumes die niet te beheren zouden zijn met ouderwetse papierwerksystemen uit de negentiende eeuw. Als dergelijke bedrijven gedwongen zouden worden terug te keren naar het schuiven met papieren, zouden ze slechts een fractie van hun normale transactievolume kunnen verwerken. De omzetdaling door een dergelijke terugval in de bedrijfsactiviteit zou het voortbestaan van alle, behalve de meest kapitaalkrachtige bedrijven, in gevaar brengen.


Bijna alles wat met geld te maken heeft - facturering, inkoop- en salarissystemen, plus voorraadbeheer en naleving van regelgeving - zou in de war raken. Enorme hoeveelheden gegevens zouden verloren gaan als computers crashen of onjuiste gegevens uitspuwen als reactie op het Y2K-probleem. In sommige gevallen zou het zelfs een zegen zijn als systemen onmiddellijk crashen in plaats van hun gegevens op cumulatieve wijze te beschadigen tot een massale storing de aandacht vestigt op het probleem. Wat gebeurt er met bestanden wanneer een back-up utility bestanden kopieert die op 07/04/99 zijn aangemaakt naar een update op 01/04/00? Niemand weet het. Zal de computer een betaling op 4 januari "1900" voor een verzekeringspolis interpreteren als een signaal dat de polis al een eeuw in gebreke is, wat resulteert in een geannuleerde polis die uit het bestand wordt geschrapt? Zullen computers van banken en financiële instellingen proberen honderd jaar rente te berekenen op leningen die de overgang naar het nieuwe millennium overbruggen? Zullen uw banken en beleggingsfirma's nauwkeurige gegevens van uw rekeningstanden bewaren en u tijdige toegang tot uw geld geven? Dit zijn slechts enkele van de interessante vraagstukken waarmee u door het Y2K-probleem te maken zult krijgen.

> "Dit is potentieel het meest destructieve deel van het jaar 2000-probleem. Dit is niet het ongemakkelijke deel waarbij uw loonstrookje een paar dagen te laat komt. Dit is het bloed-in-de-straten-deel." - Dr. Leon Kappelman, Co-voorzitter van de Year 2000 Working Group van de Society for Information Management

ook hoog op uw lijst van zorgen moet staan wat er gebeurt als de elektriciteit uitvalt door storingen in verband met het jaar 2000-probleem. Zelfs de meeste systemen die niet door het jaar 2000-probleem worden getroffen, zullen zonder elektriciteit niet functioneren: uw koelkast, uw vriezer, misschien zelfs uw verwarming. Problemen met de Y2K-compatibiliteit zouden gevolgen kunnen hebben voor de veiligheid gerelateerde toegangs- en controlefuncties in kerncentrales. Zo dragen personeelsleden in kerncentrales dosimeterapparaten die de hoeveelheid stralingsblootstelling meten die zij in de centrale ontvangen. Deze apparaten worden regelmatig geanalyseerd, waarbij de gegevens over de blootstellingshoeveelheden worden bewaard in een computersysteem dat de toegang van personeel tot de faciliteit regelt. Het is duidelijk dat een storing in de besturingcomputers alle complexe controles, die zijn ontworpen om een veilige werking te garanderen en een correct onderhoud te waarborgen, ernstig zullen verstoren. Maar belangrijker nog, een memo van de Nuclear Regulatory Commission merkt op dat veel "niet-veiligheidsrelevante, maar belangrijke computergestuurde systemen, voornamelijk databases en gegevensverzameling die nodig zijn voor de werking van de centrale," datumgevoelig zijn.

De conventionele energiecentrales zijn niet minder kwetsbaar voor storingen door het jaar 2000-probleem. Ten eerste zijn kolencentrales gevoelig voor verstoringen in het transportsysteem aan de oppervlakte dat de kolen naar de ketels brengt. In het winterverwarmingsseizoen 1997-1998 zagen exploitanten van kolengestookte elektriciteitsopwekking zich in sommige gevallen gedwongen om de productie te verminderen vanwege een vertraging in de spoorwegtransporten van westelijke kolen, als gevolg van de fusie van de spoorwegmaatschappijen Southern Pacific en Union Pacific. Het probleem ontstond door incompatibiliteiten tussen de computergestuurde besturings- en verzendsystemen die door de twee spoorwegen werden gebruikt. Volgens een woordvoerder van Union Pacific werd de integratie van de twee systemen een "nachtmerrie", ondanks het feit dat Union Pacific Technologies als een industriële leider werd beschouwd bij de ontwikkeling van computergestuurde transportsystemen. Als gevolg van de programmeerproblemen kon de spoorweg de bewegingen van zijn goederenwagons niet nauwkeurig volgen. Het onvermogen van Union Pacific om de overname van Southern Pacific te beheersen is een slecht voorteken voor wat er zou kunnen gebeuren wanneer Y2K-logische tijdbommen het transport, de energieopwekking en andere aspecten van de economie verstoren.

De grootste zorg over het elektriciteitsnet is echter dat het hele systeem onderworpen is aan gevoelige monitoring en computergestuurde besturing om elektriciteit over te brengen van gebieden met een overschot aan opwekking naar gebieden met een tekort. Dit proces moet zorgvuldig door de computer worden gemonitord om overspanningen en systeemstoringen te voorkomen. Alle overdrachten van elektriciteit worden geregistreerd op tijd en datum voor de duur, net als een telefoonverbinding. Hoewel zwaar uitgevoerde mechanische relais worden gebruikt om de verbindingen tot stand te brengen, worden ze bestuurd door computersystemen. Deze computerbesturingen, essentieel voor het balanceren van de belasting, kunnen om dezelfde redenen als de telefoonnetwerken uitvallen. De systemen voor de verdeling en besturing van de stroombelasting in Noord-Amerika zijn eigenlijk met elkaar verbonden via T-1-lijnen en telefoonmicrogolfverbindingen. Dus als het telefoonnetwerk uitvalt, kunt u verwachten dat de elektriciteit ook zal uitvallen. En onthoud, zoals de ervaring in Canada in januari 1998 bevestigt, dat zodra de elektriciteit over een groot gebied uitvalt, het systeem weer aan de praat krijgen een uitdaging is. Een stroompanne kan ongemakkelijk lang duren.

## Het jaar 2000-probleem en het nucleaire arsenaal



Voor moderne economieën zou het uitvallen van de elektriciteit in de winter een verstoring zijn en potentieel bedreigend voor de gezondheid, vooral voor mensen die afhankelijk zijn van elektrische verwarming en medische apparatuur. Toch is het slechtste scenario nog erger. Volgens John Koskinen, die het Y2K Conversion Council van president Clinton leidt, kunnen de Amerikaanse militaire arsenalen op slag van middernacht, 31 december 1999, ophouden te functioneren. Hoewel hij aangeeft dat hij geen onnodige alarm wil slaan, voegt Koskinen eraan toe: "Het moet wel zorgwekkend zijn". Een zorg over kernraketten "is of de gegevens niet functioneren en ze daadwerkelijk afgaan".

Natuurlijk zou deze zorg met even grote of grotere kracht gelden voor Russische kernraketten. Het faillissement van Rusland heeft upgrades voor Y2K-compliance nog problematischer gemaakt dan in de Verenigde Staten. En er is bewijs dat Rusland de Y2K-conversie nog niet serieus neemt. Hoewel men zou bidden dat er geen accidentele lanceringen zouden plaatsvinden, valt nauwelijks te betwijfelen dat de jaarwisseling van 2000 het potentieel heeft om de wereldwijde onveiligheid te verergeren, al was het maar omdat militaire communicatiesystemen in veel landen mogelijk niet normaal zullen functioneren. Zoals Koskinen het zegt: "Als je in een land zit en je kunt plotseling niet precies achterhalen wat er gebeurt, en je communicatie werkt niet goed, word je nog nerveuzer." Dus zet dat op je lijstje van Y2K-zorgen. De logische tijdbom zou de lancering van echt explosieve bommen kunnen veroorzaken - een feit dat het gevaar van informatieoorlogvoering voor gecentraliseerde commando- en controlesystemen benadrukt.

Als terroristen een gecentraliseerd systeem willen aanvallen, kunnen ze 31 december 1999 kiezen als datum voor actie, omdat het dan een tijd van maximale kwetsbaarheid van veel systemen zal zijn. Niet alleen zal de communicatie op zijn best beperkt zijn, met de mogelijkheid dat de elektriciteit uitvalt, voertuigen niet starten, politie, brandweer en ambulance 911-diensten niet werken, enzovoort, maar veel andere functies die je waarschijnlijk als vanzelfsprekend beschouwt, zoals luchtverkeersleiding, zullen mogelijk niet meer functioneren. Geen stroom betekent geen water uit de kraan. Rioolsystemen zullen uitvallen. Verkeerslichten kunnen uitgaan. Binnen een paar uur na een echte storing in het transportsysteem zou het voedsel in de supermarkten weggekocht zijn. (Of geplunderd.) Op basis van recente ervaringen in Amerikaanse steden, zou je kunnen veronderstellen dat geen stroom, geen water, geen verwarming voor velen, geen licht en gefragmenteerde communicatie met hulpdiensten, inclusief politie en brandweer, allemaal samen geen beschaving betekenen. Hoewel niemand zeker kan weten wat de impact van het Y2K-probleem zal zijn, zou het kunnen leiden tot plunderingen en rellen op straat, vooral als bekend wordt dat er wijdverspreide problemen zouden kunnen zijn bij het uitbetalen van salarissen, uitkeringen en pensioenen.

> "Wij zullen niet zijn wat wij geweest zijn, maar wij zullen beginnen te zijn wat anders is."[^20] - Joachim van Fiore

Voorgevoelens van ondergang over het nieuwe millennium zijn niet noodzakelijkerwijs gebaseerd op theologie verbonden aan het christelijk geloof, maar ze passen wel binnen de millenniale traditie van Joachim van Fiore wiens overdenkingen hem overtuigden dat Christus slechts "het tweede scharnier van de geschiedenis" was en dat een ander bestemd was om zich te ontvouwen."[^21] Zo betoogt de filosoof Michael Grosso, die suggereert dat de informatie-revolutie de menselijke geschiedenis stuurt naar de realisatie van de profetische visie van de westerse wereld. Hij noemt dit "technocalypse". Of de ontwikkeling van technologie nu wel of niet op de een of andere manier wordt geïnformeerd door millenniale visioenen, het Y2K-fenomeen is een artefact van de dominante westerse voorstelling van tijd. Op een vreemde manier zou het dromen, dagdromen en visioenen, of numerieke interpretaties van visioenen, zoals Newton's commentaar op de profetieën van Daniël, kunnen aanvullen. Deze intuïtieve sprongen beginnen met een perspectief dat de geboorte van Christus als het centrale feit van de geschiedenis beschouwt. Ze worden versterkt door de psychologische kracht van grote ronde getallen, die elke handelaar zal herkennen als iets dat een pakkende kwaliteit heeft. Het tweeduizendste jaar van ons tijdperk kan niet anders dan een focus worden voor de verbeelding van intuïtieve mensen.

Een criticus zou deze voorgevoelens gemakkelijk belachelijk kunnen maken, zonder zelfs maar de ambigue en bespreekbare theologische noties van de Apocalyps en het Laatste Oordeel aan te pakken die deze visioenen zoveel van hun kracht geven. Interessant genoeg echter, overtreft de Y2K-computerstoring de rekenfouten die anders de belangrijkheid van het jaar 2000 zouden lijken te devalueren, zelfs binnen het christelijke kader. Het jaar 2000 heeft het potentieel om een keerpunt te worden voor de volgende fase van de geschiedenis, simpelweg omdat het de komst van het nieuwe millennium aankondigt. Strikt logisch gezien begint het volgende millennium pas in 2001. Het jaar 2000 is slechts het tweeduizendste jaar sinds de geboorte van Christus. Of dat zou het zijn geweest als Christus in het eerste jaar van de christelijke jaartelling was geboren. Dat was hij niet. In 533, toen de geboortedatum van Christus de stichtingsdatum van Rome verving als basis voor het berekenen van jaren volgens de westerse kalender, hebben de monniken die de nieuwe conventie introduceerden de geboorte van Christus verkeerd berekend. Het wordt nu aanvaard dat hij in 4 v. Chr. werd geboren. Op die basis zal een volle tweeduizend jaar sinds zijn geboorte ergens in 1997 voltooid zijn. Vandaar Carl Jung's schijnbaar vreemde lanceringsdatum voor het begin van een New Age.

Lach gerust, maar wij verwerpen intuïtieve inzichten in de geschiedenis niet. Hoewel ons betoog gebaseerd is op logica, niet op inkomsten, staan we versteld van de profetische kracht van het menselijk bewustzijn. Steeds weer verlost het de visioenen van gekken, helderzienden en heiligen. Zo zou het ook kunnen zijn met de transformatie van het jaar 2000. De datum die lang vast heeft gezeten in de verbeelding van het Westen lijkt het keerpunt te zijn dat minstens ten dele bevestigt dat de geschiedenis een bestemming heeft. We kunnen niet uitleggen waarom dit zo zou moeten zijn, maar niettemin zijn we ervan overtuigd dat het zo is.

Ons intuïtie is dat de geschiedenis een bestemming heeft en dat vrije wil en determinisme twee versies van hetzelfde fenomeen zijn. De menselijke interacties die de geschiedenis vormen, gedragen zich alsof ze geïnformeerd worden door een soort bestemming. Net zoals een elektronenplasma, een dicht gas van elektronen, zich gedraagt als een complex systeem, zo doen mensen dat ook. De vrijheid van individuele beweging van de elektronen blijkt verenigbaar te zijn met een sterk georganiseerd collectief gedrag. Zoals David Bohm zei over een elektronenplasma, is de menselijke geschiedenis "een sterk georganiseerd systeem dat zich als geheel gedraagt".

Het begrijpen van de manier waarop de wereld werkt, betekent het ontwikkelen van een realistische intuïtie van de manier waarop de menselijke samenleving gehoorzaamt aan de wiskunde van natuurlijke processen. De werkelijkheid is niet-lineair, maar de verwachtingen van de meeste mensen zijn dat niet. Om de dynamiek van verandering te begrijpen, moet je erkennen dat de menselijke samenleving, net als andere complexe systemen in de natuur, wordt gekenmerkt door cycli en discontinuïteiten. Dat betekent dat bepaalde kenmerken van de geschiedenis de neiging hebben zich te herhalen en dat de belangrijkste veranderingen, wanneer ze optreden, abrupt kunnen zijn in plaats van geleidelijk.

Onder de cycli die het menselijke leven doordringen, lijkt een mysterieuze vijfhonderdjarige cyclus belangrijke keerpunten in de geschiedenis van de westerse beschaving te markeren. Naarmate het jaar 2000 nadert, worden we achtervolgd door het vreemde feit dat het laatste decennium van elke eeuw deelbaar door vijf een diepe transitie in de westerse beschaving heeft gemarkeerd, een patroon van dood en wedergeboorte dat nieuwe fasen van sociale organisatie markeert, net zoals dood en geboorte de cyclus van menselijke generaties afbakenen. Dit is waar sinds minstens 500 v.Chr., toen de Griekse democratie ontstond met de constitutionele hervormingen van Kleisthenes in 508 v.Chr. De volgende vijf eeuwen waren een periode van groei en intensivering van de oude economie, culminatie in de geboorte van Christus in 4 v.Chr. Dit was ook de tijd van de grootste welvaart van de oude economie, toen de rentevoeten hun laagste niveau bereikten vóór de moderne periode.

De volgende vijf eeuwen zagen een geleidelijke afname van de welvaart, leidend tot de ineenstorting van het Romeinse Rijk aan het eind van de vijfde eeuw na Chr. William Playfair's samenvatting is het herhalen waard: "Toen Rome op het hoogtepunt van zijn grootheid stond... zal blijken dat dit tijdens de geboorte van Christus was, dat wil zeggen, tijdens het bewind van Augustus, en op dezelfde manier zal blijken dat het geleidelijk achteruitging tot het jaar 490." Het was toen dat de laatste legioenen werden ontbonden en de westerse wereld in de donkere middeleeuwen verzonk.

De volgende vijf eeuwen werden gekenmerkt door economische achteruitgang: de handel over lange afstanden kwam tot stilstand, steden raakten ontvolkt, geld verdween uit de circulatie en kunst en geletterdheid verdwenen bijna volledig. Het verdwijnen van effectief recht na de val van het westerse Romeinse Rijk leidde tot primitievere manieren om geschillen te beslechten. De bloedwraak werd aan het eind van de vijfde eeuw een belangrijk fenomeen. Het eerste geregistreerde geval van een godsoordeel vond precies in het jaar 500 plaats.

Ook duizend jaar geleden, in het laatste decennium van de tiende eeuw, vond een "enorme omwenteling in sociale en economische systemen" plaats. Misschien wel de minst bekende van deze overgangen, de feodale revolutie, begon in een tijd van grote economische en politieke onrust. In *The Transformation of the Year One Thousand*, Guy Bois, hoogleraar middeleeuwse geschiedenis aan de Universiteit van Parijs, beweert dat deze breuk aan het einde van de tiende eeuw de volledige ineenstorting van de overblijfselen van oude instellingen betekende en de opkomst van iets nieuws uit de anarchie van het feodalisme.[^23] In de woorden van Raoul Glaber: "Er werd gezegd dat de hele wereld, eensgezind, de vodden van de oudheid afschudde."[^24] Het nieuwe systeem dat plotseling opkwam, maakte de langzame opleving van de economische groei mogelijk. De vijf eeuwen die we nu kennen als de middeleeuwen zagen een wedergeboorte van geld en internationale handel, samen met de herontdekking van rekenen, geletterdheid en tijdsbesef.

Vervolgens, in het laatste decennium van de vijftiende eeuw, vond er weer een keerpunt plaats. Europa herstelde toen van het demografische tekort veroorzaakt door de Zwarte Dood en begon bijna onmiddellijk zijn heerschappij over de rest van de wereld te vestigen. De "kruitrevolutie", de "renaissance" en de "reformatie" zijn namen die aan verschillende aspecten van deze overgang zijn gegeven, die het moderne tijdperk inluidde. Het werd aangekondigd met een knal toen Karel VIII Italië binnenviel met nieuwe bronzen kanonnen. Het betekende een opening naar de wereld, zoals gesymboliseerd door Columbus' reis naar Amerika in 1492. Deze opening naar de Nieuwe Wereld luidde een periode in van de meest dramatische economische groei in de geschiedenis van de mensheid in. Het betekende een transformatie van de natuurkunde en astronomie, die leidde tot de totstandkoming van de moderne wetenschap. En de nieuwe ideeën werden breed verspreid dankzij de nieuwe technologie van de boekdrukkunst.

Nu staan we aan de drempel van een nieuwe millenniumbetrokken transformatie. De grote command-and-control-systemen die we hebben geërfd van het industriële tijdperk, kunnen instorten als een oud karretje op slag van middernacht. Maar of de Y2K-bug nu al dan niet een onmiddellijke ineenstorting van de industriële samenleving teweegbrengt, de dagen ervan zijn geteld. We verwachten dat de komst van de informatiesamenleving de wereld volledig zal veranderen, op manieren die dit boek moet uitleggen. U zou perfect in uw recht staan om hieraan te twijfelen, aangezien een cyclus die zich slechts twee keer per millennium herhaalt, niet genoeg iteraties heeft laten zien om statistisch significant te zijn. Sterker nog, zelfs veel kortere cycli zijn sceptisch bekeken door economen die om een statistisch bevredigender bewijs vragen. "Professor Dennis Robertson schreef ooit dat we beter een paar eeuwen kunnen wachten voordat we zeker zijn" van het bestaan van vierjarige en acht- tot tienjarige handelscycli.[^25] Volgens die maatstaf zou professor Robertson zijn oordeel ongeveer dertigduizend jaar moeten opschorten om er zeker van te zijn dat de vijfhonderdjarige cyclus geen statistische toevalstreffer is. Wij zijn minder dogmatisch, of bereid te erkennen dat de patronen van de werkelijkheid complexer zijn dan de statische en lineaire evenwichtsmodellen van de meeste economen.

Wij geloven dat de komst van het jaar 2000 meer is dan een handige indeling langs een eindeloze continuüm van tijd. Wij geloven dat het een keerpunt zal zijn tussen de oude wereld en een nieuwe wereld die komen gaat. Het industriële tijdperk is snel aan het verdwijnen, en zijn ondergang wordt ironisch genoeg mogelijk versneld door het feit dat vroegere computergeheugens zo duur waren dat het de wijdverbreide invoering van tweecijferige datumvelden stimuleerde. Toen Hallerith ponskaarten slechts tachtig tekens per kaart konden bevatten, leek het afkorting van datums een verstandige zaak. In tegenstelling tot de verwachtingen van de eerste programmeurs heeft hun afkorting van het datumveld echter vier decennia standgehouden tot het einde van het millennium als een onbedoelde logische bom die een groot deel van de industriële samenleving zou kunnen vernietigen. Het Amerikaanse Bureau voor Begroting beschreef het probleem in "Getting Federal Computers Ready for 2000", een rapport van 7 februari 1997. De OMB concludeert over computers: "Tenzij ze gerepareerd of vervangen worden, zullen ze aan het einde van de eeuw op een van de drie manieren falen: ze zullen legitieme invoer afwijzen, of ze zullen foutieve resultaten berekenen, of ze zullen gewoon niet werken". Deze drie uitkomsten in combinatie zouden de industriële samenleving kunnen lamleggen. De technologie van massaproductie is hoe dan ook gedoemd te worden overschaduwd door een nieuwe technologie van miniaturisering. Een crisis op korte termijn zal het proces alleen maar versnellen. Met de nieuwe informatietechnologie is een nieuwe wetenschap van niet-lineaire dynamica gekomen, waarvan de verrassende conclusies slechts draden zijn die nog moeten worden samengeweven tot een uitgebreid wereldbeeld. We leven in de tijd van de computer, maar onze dromen worden nog steeds gesponnen op de weefgetouwen. We blijven leven volgens de metaforen en gedachten van het industrialisme. Onze politiek bevindt zich nog steeds op de industriële kloof tussen links en rechts, zoals in kaart gebracht door denkers als Adam Smith en Karl Marx, die stierven voordat bijna iedereen die nu leeft, geboren was.[^28] Het industriële wereldbeeld, met inbegrip van de werkingsprincipes van de industriële wetenschap, is nog steeds de "gezond verstand"-intuïtie van de ontwikkelde opinie. Het is onze stelling dat het "gezond verstand" van het industriële tijdperk niet langer van toepassing zal zijn op vele gebieden terwijl de wereld wordt getransformeerd.

Meer dan vijfentachtig jaar na de dag in 1911 waarop Oswald Spengler een voorgevoel kreeg van een naderende wereldoorlog en "de ondergang van het Westen," zien wij ook "*een historische faseovergang* die zich voltrekt ... op het punt dat er honderden jaren geleden al voor was vastgelegd."[^26] Net als Spengler zien wij de naderende dood van de westerse beschaving en daarmee de ineenstorting van de wereldorde die de afgelopen vijf eeuwen, sinds Columbus naar het westen voer om contact te leggen met de Nieuwe Wereld, heeft overheerst. Maar in tegenstelling tot Spengler zien wij de geboorte van een nieuw stadium in de westerse beschaving in het komende millennium.

[^1]: Danny Hillis, "The Millennium Clock," *Wired*, Special Edition, Fall 1995, p.48.

[^2]: Ericka Cheetham, *The Final Prophecies of Nostradamus* (New York: Putnam,1989), p.424.

[^3]: Dr. Edward Yardeni, *Year 2000 Recession: "Prepare for the worst. Hope for the best,"* Version 5.0, May 13, 1998, B1.2.

[^4]: Michael Grasso, *The Millenium Myth: Love and Death at the End of Time*, Wheaton, Illinois: Quest Books, 1995.

[^5]: Johan Huizinga, *Het verval van de middeleeuwen*, vert. E. Hopman (Londen: Penguin Books, 1990), p. 172.

[^6]: Marshall McLuhan, *Understanding Media*, New York: Signet, 196, p. 19.

[^7]: James George Frazer, *The Golden Bough: A Study in Magic and Religion* (New York: Macmillan, 1951), p. 105.

[^8]: Voor meer details over gefragmenteerde soevereiniteiten als voorloper en alternatief voor de natiestaat, zie Charles Tilly, *Coercion, Capital and European States AD 990-1992* (Oxford: Blackwell, 1993).

[^9]: De Duitse GPI-index stond op 33,20 op 31 december 1948 en op 112,90 op 30 juni 1995, wat een gemiddelde jaarlijkse depreciatie van 2,7 procent vertegenwoordigt. De Amerikaanse CPI stond op 24 op 31 december 1948 en op 152,50 op 30 juni 1995. De cumulatieve Amerikaanse inflatie bedroeg 635 procent voor deze periode.

[^10]: Janet L. Abu-Lughod, *Before European Hegemony: The World System A.D. 1250-1350* (Oxford: Oxford University Press, 1991), p. 62.

[^11]: Jack Cohen en Ian Stewart, *The Collapse of Chaos* (New York: Viking, 1994).

[^12]: Zie James Dale Davidson en Lord William Rees-Mogg, *The Great Reckoning*, 2e ed. (New York: Simon & Schuster, 1993), p. 53.

[^13]: Frederic C. Lane, "Economic Consequences of Organized Violence," *The Journal of Economic History* vol. 18, nr. 4 (december 1958), p. 402.

[^14]: Nicholas Colchester, "Goodbye Nation-State, Hello . . . What?", *New York Times*, 17 juli 1994, p. E17.

[^15]: Norman Macrae, *"Overheden in verval,"* Cato Policy Report, juli/augustus 1992, p. 10.

[^16]: Arthur C. Clarke, *Profielen van de toekomst: Een onderzoek naar de grenzen van het mogelijke* (Londen: Victor Gollancz Ltd., 1962), p. 13.

[^17]: Ibidem.

[^18]: A. T. Mann, *Millenniumprofetieën: Voorspellingen voor het jaar 2000* (Shaftesbury, Engeland: Element Books, 1992), pp. 88, 112, 117.

[^19]: Yardeni, op. cit., p. 45.

[^20]: Geciteerd in Frooso, op. cit., p. 40.

[^21]: Ibidem.

[^22]: William Playfair, *An Inquiry into the Permanent Causes 0f the Decline and Fall of Powerful and Wealthy Nations: Designed to Show How the Prosperity of the British Empire May he Prolonged* (Londen: Greenland and Norris, 1805), p. 79.

[^23]: Guy Bois, *The Transformation 0f the Year One Thousand: The Village of Lournard from Antiquity to Feudalism* (Manchester, Engeland: Manchester University Press, 1992).

[^24]: Ibidem, p. 150.

[^25]: Geciteerd in *S. B. Saul, The Myth of the Great Depression* (Londen: Macmillan, 1985), p. 10.

[^26]: Oswald Spengler, *The Decline of the West*, vertaling Charles Francis Atkinson, geciteerd in *I. F. Clark, The Pattern of Expectation, 1644-2001* (Londen: Jonathan Cape, 1979), p. 220.

[^27] De nomenklatura waren de gevestigde elites die de voormalige Sovjet-Unie en andere door de staat geleide economieën bestuurden.

[^28]: Adam Smith stierf in 1790, Karl Marx in 1883.