# East of Eden

:::{.content-hidden when-format=latex}

*De agrarische revolutie en de verfijning van geweld*

:::

> 'En de Heer zei tot Kaïn: Waar is Abel, jouw broeder? En hij antwoordde: Ik weet het niet: ben ik de hoeder van mijn broeders? En hij zei: Wat heb je gedaan? De stem van het bloed van jouw broeders roept tot mij vanaf de aarde.' - GENESIS 4:9-10

Vijfhonderd generaties geleden begon de eerste faseverandering in de organisatie van de menselijke samenleving.[^51] Onze voorouders in verschillende regio’s pakten met tegenzin ruwe werktuigen, aangeslepen palen en geïmproviseerde hakken op en gingen aan het werk. Terwijl zij de eerste gewassen zaaiden, legden zij tevens een nieuwe basis voor macht in de wereld. De agrarische revolutie was de eerste grote economische en sociale revolutie. Ze begon met de verdrijving uit Eden en vorderde zo langzaam dat de landbouw de jacht en het verzamelen in alle geschikte gebieden op aarde nog niet volledig had vervangen toen de twintigste eeuw aanbrak. Deskundigen menen dat zelfs in het Nabije Oosten, waar de landbouw voor het eerst opkwam, deze invoering het gevolg was van 'een langdurig, stapsgewijs proces' dat 'vijfduizend jaar of langer zou kunnen hebben geduurd.'[^52]

Het lijkt misschien overdreven om een proces dat zich over millennia uitstrekte een 'revolutie' te noemen. Maar dat was precies wat de opkomst van de landbouw inhield: een revolutie die zich in langzaam tempo voltrekte en het menselijk leven transformeerde door de logica van geweld te veranderen. Waar de landbouw voet aanschoof, kreeg geweld een belangrijkere plaats in het sociale leven. Hiërarchieën die bedreven waren in het manipuleren of beheersen van geweld, kwamen de samenleving te domineren.

Het begrijpen van de agrarische revolutie is een eerste stap naar het doorgronden van de informatierrevolutie. De introductie van ploegen en oogsten vormt een paradigmaatvoorbeeld van hoe een schijnbaar eenvoudige verandering in de aard van arbeid de organisatie van de samenleving radicaal kan veranderen. Wanneer je deze vroegere revolutie in perspectief plaatst, sta je veel sterker om te voorspellen hoe de geschiedenis zich mogelijk ontvouwt als reactie op de nieuwe logica van geweld die met microprocessors is geïntroduceerd.

Om het revolutionaire karakter van de landbouw te waarderen, heb je eerst een beeld nodig van hoe de oeroude samenleving functioneerde vóór de landbouw. We hebben dit behandeld in *The Great Reckoning* en hieronder wordt een nadere schets gegeven. Jagers-verzamelaars samenlevingen waren de enige vormen van sociale organisatie tijdens een lange, prehistorische periode waarin het menselijk leven nauwelijks of helemaal niet veranderde van generatie op generatie. Antropologen beweren dat mensen gedurende 99 procent van de tijd, sinds onze verschijning op aarde, jagers en verzamelaars zijn geweest. Cruciaal voor het lange succes én het uiteindelijke falen van jagers-verzamelaarsgroepen is het feit dat zij op zeer kleine schaal in een uitgestrekt gebied moesten opereren.

Verzamelaars konden alleen overleven waar de bevolkingsdichtheid laag was. Om te begrijpen waarom, denk aan de problemen die grotere groepen zouden veroorzaken. Ten eerste zou een duizend jagers die samen door het landschap marcheerden zo'n rumoer veroorzaken dat het wild, dat zij wilden vangen, direct zou verdwijnen. En nog erger: als een klein leger jagers er af en toe in slaagde een enorme kudde wild te omsingelen, dan zou het voedsel dat zij oogstten – waaronder vruchten en eetbare wilde planten – niet lang overvloedig blijven. Een grote groep jagers-verzamelaars zou het platteland hebben verwoest door buitensporige jacht, vergelijkbaar met een hongerig leger in de Dertigjarige Oorlog. Daarom moesten de jachtpartijen klein zijn. Zoals Stephen Boyden schrijft in Western Civilization in Biological Perspective, 'bestaan jagers-verzamelaarsgroepen doorgaans uit tussen de vijfentwintig en vijftig personen.'[^53]

Tegenwoordig is het leven op tienduizend acres in een gematigd klimaat een luxe die alleen de allerrijksten zich kunnen veroorloven. Een familie van jagers-verzamelaars had op minder nauwelijks kunnen overleven. Zij hadden gemiddeld duizenden acres per persoon nodig, zelfs in de gebieden die het meest vruchtbaar waren voor het verzamelen. Dit verklaart waarom de groei van de menselijke bevolking tijdens periodes die bijzonder gunstig waren voor de landbouw de basis voor bevolkingscrises kon hebben gelegd. Doordat er zoveel land nodig was om één persoon te ondersteunen, moest de bevolkingsdichtheid in jagers-verzamelaars samenlevingen ongelooflijk laag zijn. Vóór de landbouw waren mensen ongeveer zo dunbevolkt als beren.

Met geringe verschillen leek het menselijke dieet sterk op dat van beren. Jagers-verzamelaars waren afhankelijk van voedsel dat verzameld werd op het open platteland of nabij waterlichamen. Hoewel sommigen ook vissers waren, waren de meesten jagers die voor een derde tot een vijfde van hun voeding op eiwitten uit grote zoogdieren rekenden. Afgezien van een paar eenvoudige werktuigen en voorwerpen die zij bij zich droegen, beschikten jagers-verzamelaars vrijwel over geen technologie. Zij hadden doorgaans geen effectieve manier om grote hoeveelheden vlees of ander voedsel voor later gebruik op te slaan; het grootste deel van het voedsel moest bijna direct na het verzamelen geconsumeerd worden om bederf te voorkomen. Dat betekent natuurlijk niet dat sommige jagers-verzamelaars geen bedorven voedsel aten. Zoals Boyden rapporteert, 'hebben Eskimo’s naar verluidt een bijzondere voorliefde voor ontbonden voedsel.'[^54] Hij herhaalt de bevindingen van deskundigen die opmerken dat Eskimo’s 'viskoppen begraven en laten vergaan totdat de botten dezelfde consistentie krijgen als het vlees. Vervolgens kneden zij de stinkende massa tot een pasta en eten die'; zij genieten ook van 'de vette, wormige larven van de rendiervlieg, rauw geserveerd; hertenuitwerpselen, gekauwd als bessen … en merg dat meer dan een jaar oud is, bezaaid met wormen.'[^55]

Afgezien van zulke lekkernijen ontwikkelden jagers‐verzamelaars nauwelijks overtollig voedsel. Zoals de antropoloog Gregg opmerkt: “mobiele populaties slaan doorgaans geen voedselvoorraden op tegen seizoensgebonden of onverwachte dalingen in de beschikbaarheid van hulpbronnen.” Bijgevolg hadden jagers‐verzamelaars weinig over te nemen. Een arbeidsverdeling die specialisatie tot het inzetten van geweld omvatte, was onhoudbaar in situaties waarin overtollig voedsel niet kon worden opgeslagen. De logica van de jacht dicteerde bovendien dat geweld binnen jager‐en verzamelgroepen nooit boven een klein niveau kon uitstijgen, omdat de groepen zelf klein moesten blijven.

De kleinschaligheid van de jagers‐verzamelgroepen bood nog een ander voordeel. Leden van zulke kleine groepen kenden elkaar grondig, wat hen effectiever maakte in samenwerking. Besluitvorming wordt moeilijker naarmate het aantal betrokkenen toeneemt, omdat de prikkelvalkuilen zich vermeerderen. Je hoeft maar te bedenken hoe lastig het is om een dozijn mensen te organiseren om samen uit eten te gaan. Stel je eens voor hoe hopeloos de taak zou zijn geweest om honderden of zelfs duizenden mensen bijeen te krijgen voor een rondtrekkend feest. Zonder een blijvende, aparte politieke organisatie of bureaucratie – zoals die door specialisatie voor oorlogvoering vereist wordt – moesten jagers‐en verzamelgroepen vertrouwen op overreding en consensus, methoden die het beste werken binnen kleine, relatief ontspannen groepen.

Of jagers‐en verzamelgroepen daadwerkelijk ontspannen waren, is ter discussie. Sir Henry Maine verwijst naar “de universele strijdlust van de primitieve mens.” Zoals hij het verwoordt: “Het is niet de vrede die natuurlijk en primitief is, maar de oorlog.”[^56] Zijn visie is onderbouwd door het werk van evolutionaire biologen. R. Paul Shaw en Yuwa Wong merken op: “[E]rm zijn sterke aanwijzingen dat veel van de verwondingen die zichtbaar zijn in resten van Australopithecus, Homo erectus en Homo sapiens uit de Europese vierde en pre-vierde ijstijden het gevolg waren van gevechten.”[^57] Maar anderen betwijfelen dit. Experts zoals Stephen Boyden beweren dat primitieve groepen doorgaans niet oorlogszuchtig of geneigd tot geweld waren. Er ontwikkelden zich sociale conventies om interne spanningen te verminderen en de verdeling van de buit van de jacht te vergemakkelijken. Vooral in gebieden waar mensen op groot wild jaagden – wat voor een enkele jager moeilijk neer te halen was – ontstonden religieuze en sociale doctrines die de herschikking van de buit over de hele groep moesten regelen. De eerste aanspraak op de caloriebronnen werd gedaan door medejagers; noodzaak, eerder dan sentiment, was de drijfveer. De eerste claim op de hulpbronnen legden degenen met de meeste economische vaardigheden en militaire kracht, niet de zieken en de zwakken. Ongetwijfeld speelde ook mee dat jagers in de bloei van hun leven militair de krachtigste leden van de kleine groep waren. Door hen een eerste recht op de jacht toe te kennen, minimaliseerde de groep potentieel dodelijke interne conflicten.

Zolang de bevolkingsdichtheid laag bleef, waren de goden van de jagers‐verzamelaars geen krijgshaftige godheden, maar belichamingen van natuurkrachten of van de dieren die zij jaagden. De schaarste aan kapitaal en de open grenzen maakten oorlog in de meeste gevallen overbodig. Er waren maar weinig buren buiten de eigen kleine familie of stam die als bedreiging konden gelden. Omdat jagers‐verzamelaars de neiging hadden rond te zwerven op zoek naar voedsel, werden persoonlijke bezittingen boven een absoluut minimum juist een last. Zij die weinig bezaten, hadden dan ook onvermijdelijk weinig te maken met vermogensdelicten. Wanneer conflicten ontstonden, waren de strijdende partijen vaak bereid gewoon weg te lopen, omdat zij weinig hadden geïnvesteerd in een bepaalde plek. Ontsnappen bleek een gemakkelijke oplossing voor persoonlijke vetes of buitensporige eisen van andere aard. Dit betekent echter niet dat de vroege mens per definitie vredelievend was. Ze konden gewelddadig en onaangenaam zijn in een mate die we nauwelijks kunnen voorstellen. Maar als zij geweld toepasten, was dat meestal om persoonlijke redenen of, wat wellicht nog erger is, voor de lol.

Het levensonderhoud van jagers‐verzamelaars hing af van hun functioneren in kleine groepen die nauwelijks ruimte boden voor een arbeidsverdeling anders dan langs geslachtslijnen. Zij hadden geen georganiseerde regering, meestal geen permanente nederzettingen en geen mogelijkheid om rijkdom te vergaren. Zelfs zulke fundamentele bouwstenen van beschaving als een geschreven taal waren onbekend in de oeroude economie. Zonder een geschreven taal konden er geen formele documenten en dus ook geen geschiedenis ontstaan.

### Overkill

De dynamiek van het foerageren creëerde heel andere prikkels om te werken dan die waaraan we sinds de opkomst van de landbouw gewend zijn geraakt. De kapitaalvereisten voor een levensstijl als foerager waren minimaal. Een paar primitieve gereedschappen en wapens volstonden. Er was geen mogelijkheid tot investering, niet eens in de vorm van privébezit van land, behalve af en toe in steengroeven waar vuursteen of zeepsteen gewonnen werd.[^58] Zoals antropoloog Susan Alling Gregg schreef in Foragers and Farmers, 'het eigendom van en de toegang tot hulpbronnen werd gezamenlijk door de groep beheerd.'[^59] Met zeldzame uitzonderingen, zoals vissers die aan de oevers van meren woonden, hadden foeragers doorgaans geen vaste woonplaats. Omdat ze geen permanente woningen bezaten, hadden ze weinig noodzaak om hard te werken om eigendom te verwerven of te onderhouden. Ze hadden geen hypotheken of belastingen om te betalen, geen meubels om aan te schaffen. Hun weinige consumentengoederen bestonden uit dierenhuiden en persoonlijke versieringen, vervaardigd door de leden van de groep zelf. Er was weinig prikkel om iets te bezitten of op te hopen dat als geld had kunnen gelden, omdat er vrijwel niets te kopen viel. Onder dergelijke omstandigheden kon sparen voor foeragers hooguit een rudimentair concept zijn geweest.

Zonder reden om te verdienen en met bijna geen arbeidsverdeling, moet het concept van hard werken als deugd vreemd zijn geweest voor jagers-verzamelaars. Behalve tijdens perioden van bijzondere ontbering, waarin langdurige inspanning nodig was om iets te eten te vinden, werd er weinig gewerkt omdat er weinig nodig was. Er was letterlijk niets te winnen door harder te werken dan het absolute minimum dat nodig was om te overleven. Voor de leden van een typische jagers-verzamelaarsgroep betekende dit dat ze slechts zo'n acht tot vijftien uur per week werkten.[^60] Omdat de arbeid van een jager de voedselvoorraad niet vergrootte maar slechts verminderde, droeg iemand die heldhaftig overuren maakte om meer dieren te doden of meer fruit te plukken dan voor bederf gegeten kon worden niets bij aan de voorspoed. Integendeel, overkill verminderde de vooruitzichten op toekomstige voedselvoorziening en had daardoor een nadelig effect op het welzijn van de groep. Daarom bestraften of schenen sommige foeragers, zoals de Eskimo’s, leden van de groep die zich schuldig maakten aan overkill.

Het voorbeeld van de Eskimo’s die overkill bestraffen is bijzonder treffend, omdat zij, veel meer dan anderen, in staat zouden zijn geweest om vlees te bewaren door het te bevriezen. Bovendien zou het haalbaar zijn geweest om op zijn minst enige opslag te voorzien voor oliën vervaardigd uit grote zeezoogdieren. Het feit dat foeragers er over het algemeen voor kozen dit niet te doen, weerspiegelt hun veel meer passieve interactie met de natuur. Dit kan tevens duiden op de mate waarin cognitie en mentale processen door cultuur worden gekleurd. Beperkingen in leren en gedrag in complexe omgevingen maken het aannemen van bepaalde strategieën veel moeilijker dan op het eerste gezicht lijkt. Zoals R. Paul Shaw en Yuwa Wong schreven, 'omdat niches op vele vlakken verschillen, doen ook de vooroordelen in het leren dat.'[^61]

In dit perspectief betekende de opkomst van de landbouw meer dan een verandering in het dieet; het luidde tevens een grote revolutie in de organisatie van het economische leven en de cultuur in, en zorgde voor een transformatie van de logica van geweld. Landbouw creëerde grootschalige kapitaalgoederen in de vorm van land en, soms, irrigatiesystemen. De gewassen en gedomesticeerde dieren die boeren verbouwden waren waardevolle bezittingen. Ze konden opgeslagen, opgepot en gestolen worden. Omdat gewassen gedurende het hele groeiseizoen verzorgd moesten worden, van planten tot oogsten, werd migratie als reactie op bedreigingen minder aantrekkelijk, zeker in droge gebieden waar de kans om gewassen te verbouwen beperkt was tot de kleine stukken land met betrouwbare watervoorzieningen. Naarmate ontsnappen moeilijker werd, namen de mogelijkheden voor georganiseerde afpersing en plundering toe. Boeren werden tijdens de oogsttijd aan raids onderworpen, wat geleidelijk de schaal van oorlogsvoering deed toenemen.

Dit had de neiging de omvang van samenlevingen te vergroten, omdat gewelddadige conflicten vrijwel altijd door de grotere groep werden gewonnen. Naarmate de concurrentie om land en de controle over de opbrengst intenser werd, gingen samenlevingen steeds meer op één plek vestigen. Een duidelijke arbeidsverdeling werd zichtbaar. Voor het eerst kwamen werkgelegenheid en slavernij op. Boeren en herders specialiseerden zich in voedselproductie. Pottenbakkers vervaardigden potten en andere containers om voedsel in op te slaan. Priesters baden voor regen en overvloedige oogsten. Specialisten in geweld – de voorlopers van de overheid – wijdden zich in toenemende mate aan plundering en de bescherming tegen plundering. Samen met de priesters werden zij de eerste rijke personen in de geschiedenis.

In de vroege fasen van agrarische samenlevingen verwierven deze krijgers een deel van de jaarlijkse oogst als vergoeding voor bescherming. Op plaatsen waar de dreiging minimaal was, waren zelfstandige boeren soms in staat een relatief grote mate van autonomie te behouden. Maar naarmate de bevolkingsdichtheid toenam en de concurrentie om voedsel intenser werd – vooral in gebieden rond woestijnen waar vruchtbaar land schaars was – kon de krijgersgroep een groot deel van de totale opbrengst opeisen. Met de opbrengsten van deze afpersing, die opliepen tot wel 25 procent van de graanoogst en tot de helft van de toename van de kuddes gedomesticeerde dieren, stichtten deze krijgers de eerste staten. De landbouw vergrootte daardoor in sterke mate het belang van dwang; de toename van middelen die geplunderd konden worden, leidde tot een flinke toename van plunderingen.

Het duurde millennia voordat de volledige logica van de agrarische revolutie zich ontvouwde. Lange tijd leefden verspreide populaties boeren in gematigde streken wellicht nog zoals hun jagers-verzamelaarsvoorouders. Waar land en neerslag overvloedig waren, oogstten boeren op kleine schaal zonder al te veel gewelddadige inmenging. Maar naarmate de bevolking over enkele duizenden jaren toenam, werden zelfs boeren in dunbevolkte gebieden onderworpen aan grillige plunderingen die hen soms met onvoldoende zaad achterlieten om de oogst van het volgende jaar opnieuw te planten. Aan de ene kant bestond de mogelijkheid van concurrerende plundering – ofwel anarchie –, aan de andere kant leefden onbeschermde gemeenschappen zonder enige gespecialiseerde organisatie om geweld te monopoliseren.

Naarmate de tijd verstreek, werkte de geweldslogica, die inherent was aan de landbouw, zich uit over een steeds groter gebied. De gebieden waar landbouw en veeteelt konden voortbestaan zonder de roof van de overheid, werden beperkt tot enkele werkelijk afgelegen streken. De Kafir-regio’s van Afghanistan, om een extreem voorbeeld te noemen, boden weerstand tegen de vestiging van een overheid tot de laatste tien jaar van de negentiende eeuw. Hierbij waren zij al eeuwen eerder getransformeerd tot een behoorlijk militante samenleving, georganiseerd langs verwantschapslijnen. Dergelijke samenlevingsvormen waren niet in staat op grote schaal kracht te mobiliseren. Totdat de Britten moderne wapens naar de regio brachten, bleven de Kafirs onafhankelijk in hun afgelegen Bashgal- en Waigal-valleien, omdat hun versterkte posten beschermd werden door natuurlijke kenmerken zoals hoge bergen en woestijnen die tussen hen en buitenlandse veroveraars lagen.

In de loop der tijd drukte de basislogica van de agrarische revolutie zich op in de samenlevingen waar de landbouw voet aan de grond kreeg. De landbouw verruimde de mogelijkheden voor het vormen van menselijke gemeenschappen aanzienlijk. Vanaf ongeveer tienduizend jaar geleden begonnen steden te ontstaan. Hoewel ze volgens de hedendaagse maatstaven nog klein waren, waren het de centra van de eerste ‘beschavingen’ – een term afgeleid van civitas, wat in het Latijn ’burgerschap’ of ’inwoners van een stad’ betekent. Omdat de landbouw bezittingen creëerde die geplunderd en beschermd moesten worden, ontstond ook de noodzaak voor een vorm van inventarisatie en boekhouding. Je kunt immers geen belastingen heffen als je geen administratie kunt bijhouden en kwitanties kunt uitreiken. De symbolen die in het grootboek van de boekhouder werden gebruikt, vormden de basisprincipes van de geschreven taal, een innovatie die onder jagers en verzamelaars nog onbekend was.

De landbouw verbreedde ook de horizon waarbinnen mensen problemen moesten oplossen. Jagersstammen leefden binnen een onmiddellijke tijdshorizon. Zij gingen zelden projecten aan die langer dan een paar dagen duurden. Maar het planten en oogsten van een gewas duurde maanden. Het nastreven van projecten op langere termijn dwong boeren hun blik op de sterren te richten. Nauwkeurige astronomische observaties waren een noodzakelijke voorwaarde voor het opstellen van almanakken en kalenders, die als gids dienden om het juiste moment te bepalen voor het planten en oogsten. Met de komst van de landbouw breidden ook de horizon van de jagers zich uit.

## Eigendom

De overgang naar een gevestigde landbouwsamenleving leidde tot het ontstaan van privébezit. Natuurlijk zou niemand genoegen nemen met ploeteren door een heel groeiseizoen om een gewas te produceren, alleen maar om te zien dat iemand anders opdook en oogstte wat hij had geproduceerd. Het idee van eigendom was een onvermijdelijk gevolg van de landbouw. Maar de helderheid van het concept privébezit werd verzwakt door de logica van geweld die met de introductie van de landbouw gepaard ging. De opkomst van eigendom werd bemoeilijkt door het feit dat de megapolitieke macht van individuen niet langer zo gelijk verdeeld was als in de verzamelende samenlevingen, waar iedere gezonde volwassen man even goed bewapend was als ieder ander. De landbouw leidde tot een specialisatie in geweld. Juist omdat zij iets creëerde dat gestolen kon worden, maakte de landbouw investeringen in betere wapens winstgevend. Het resultaat was diefstal, vaak in zeer georganiseerde vorm.

De machtigen waren nu in staat een nieuwe vorm van roofzucht te organiseren: een monopolie op geweld, oftewel de overheid. Dit creëerde een scherpe scheiding in de samenlevingen, met geheel andere omstandigheden voor degenen die van plunderingen profiteerden en voor de grote massa armen die de akkers bewerkten. De enkelen die over de militaire macht beschikten, konden nu rijk worden, samen met anderen die in hun gunst vielen. De godkoningen en hun bondgenoten, de verschillende lagere, lokale potentaten die de eerste staten in het Nabije Oosten regeerden, beschikten over veel meer hedendaagse vormen van eigendom dan de grote meerderheid die onder hen ploeterde.

Natuurlijk is het anachronistisch om in de vroege landbouwsamenlevingen een onderscheid te maken tussen privé- en publiek bezit. De regerende godkoning had de volledige middelen van de staat tot zijn beschikking op een manier die nauwelijks te onderscheiden was van het bezit van een uitgestrekt landgoed. Net zoals in de feodale periode van de Europese geschiedenis viel al het eigendom onder het gezag van hogere potentaten. Degenen die lager in de hiërarchie stonden, zagen dat hun eigendom werd aangetast naar de grill van de heerser.

Alleen stellen dat de potentaat niet door de wet werd beperkt, houdt niet in dat hij zich alles kon toe-eigenen wat hij maar wilde. Kosten en beloningen beperkten de vrijheid van de farao net zoveel als die van de hedendaagse premier van Canada. En de farao werd veel sterker beperkt door de problemen met transport en communicatie dan moderne leiders tegenwoordig. Het verplaatsen van buit van de ene plaats naar de andere, zeker wanneer deze buit hoofdzakelijk bestond uit landbouwproducten, ging gepaard met aanzienlijke verliezen door bederf en diefstal. De toename van functionarissen om elkaar in de gaten te houden, verminderde weliswaar de verliezen door kleine diefstallen, maar verhoogde tegelijkertijd de totale vaste kosten die de farao moest dragen. Gedecentraliseerde bevoegdheid, die onder bepaalde omstandigheden de productie optimaliseerde, leidde ook tot sterkere lokale machten die soms uitgroeiden tot volwaardige rivalen voor dynastieke controle. Zelfs oosterse despoten waren geenszins vrij om naar eigen goeddunken te handelen; zij hadden geen andere keus dan de balans van pure macht te erkennen zoals die bestond.

Hoewel iedereen, inclusief de rijken, onderhevig was aan willekeurige onteigening, konden sommigen toch eigen bezit vergaren. Toen, net als nu, wijdde de staat een groot deel van haar inkomsten aan openbare werken. Projecten zoals irrigatiesystemen, religieuze monumenten en grafkelders voor de koningen boden architecten en ambachtslieden de kans om een inkomen te verdienen. Enkele gunstig gepositioneerde individuen slaagden erin aanzienlijke particuliere eigendommen te vergaren. In feite legt een groot deel van de bewaarde spijkerschrifttabletten uit Soemer, een vroege Mesopotamische beschaving, diverse handelsacties vast, waarvan de meeste de overdracht van eigendomsrechten betreffen.

Er bestond privébezit in de vroege landbouwsamenlevingen, maar zelden op de onderkant van de sociale piramide. De overgrote meerderheid van de bevolking bestond uit boeren die te arm waren om veel vermogen te vergaren. In feite waren, met enkele uitzonderingen, de meeste boeren tot in de moderne tijd zo arm dat zij voortdurend het risico liepen te sterven aan de honger wanneer een droogte, overstroming of plaag de oogstopbrengst vernielden. Daarom moesten de boeren hun zaken zo organiseren dat zij de neerwaartse risico’s in slechte jaren tot een minimum beperkten. Binnen de brede en armoedige laag van de samenleving heerste een meer primitieve vorm van eigendomsorganisatie. Dit vergrootte de kans op overleving, maar ten koste van de meeste mogelijkheden om kapitaal te vergaren en economisch op te klimmen.

### Boerenverzekering

De vorm die deze regeling aannam, was de invoering van wat antropologen en sociale historici omschrijven als het ‘gesloten dorp’. Bijna elke boerenmaatschappij in de premoderne tijd kende als voornaamste vorm van economische organisatie het ‘gesloten dorp’. In tegenstelling tot de modernere economische organisatie, waarin individuen vaak te maken hebben met talrijke kopers en verkopers op een open markt, bundelden de huishoudens in het gesloten dorp hun krachten en functioneerden zij als een informele corporatie, of als een grote familie, niet op een open marktplaats maar in een gesloten systeem waarin alle economische transacties van het dorp doorgaans werden verricht met één monopolist – de plaatselijke landeigenaar of diens agenten onder de dorpshoofden. Het dorp als geheel sloot een contract met de landeigenaar, doorgaans op basis van betaling in natura, voor een groot deel van de oogst in plaats van een vaste huurprijs. Deze verhouding in de huur hield in dat de landeigenaar een deel van het risico van een slechte oogst op zich nam. Natuurlijk nam de landeigenaar ook het merendeel van de mogelijke winst. Landeigenaren zorgden daarnaast typisch voor het zaad.

Deze conventie beperkte tevens het risico op hongersnood. Het vereiste dat de landeigenaar, in plaats van de boer, een onevenredig deel van zijn aandeel in de oogst opzij zou sparen. Omdat de landbouwopbrengsten in het verleden in veel gebieden afschuwelijk laag waren, moest er soms twee zaden gezaaid worden voor iedere drie geoogste. Onder zulke omstandigheden zou een slechte oogst massale hongersnood betekenen. De boeren verkozen rationeel een regeling waarbij de landeigenaar moest investeren in hun overleving. Tegen de prijs van kopen tegen monopolistische prijzen, goedkoop verkopen en het leveren van arbeid in natura voor de landeigenaar, vergrootten de boeren hun overlevingskansen. Een vergelijkbare impuls leidde ertoe dat de typische boer in een gesloten dorpsmaatschappij afstand deed van de zekerheid van vrij eigendom. Door zich over te geven aan de grillen van de dorpshoofd, vergrootte een boerengezin zijn kansen om te profiteren van de regelmatige herverdeling van akkers. Niet zelden nam de dorpshoofd de beste velden voor zichzelf en zijn favorieten, maar dat was een risico dat de boeren moesten accepteren om te profiteren van de overlevingsverzekering die het complexe dorpsbezit van akkers bood. In tijden dat de oogstopbrengsten erbarmelijk laag waren, kon een verschil in teeltomstandigheden tussen velden die een honderd meter van elkaar verwijderd lagen, het verschil betekenen tussen hongersnood en overleving. Boeren kozen dan vaak voor de regeling die het neerwaartse risico verminderde, zelfs als dat betekende dat zij elke hoop op toenemende welvaart moesten opgeven.

Over het algemeen is risicomijdend gedrag kenmerkend geweest voor alle groepen die aan de rand van overleving opereerden. De pure uitdaging om te overleven in premoderne samenlevingen beperkte immers altijd het gedrag van de armen. Een interessant aspect van deze risicomijding, behandeld in *The Great Reckoning*, is dat zij het scala aan vreedzaam economisch gedrag dat individuen sociaal gezien mochten vertonen, verkleinde. Taboed en sociale beperkingen beperkten experimentatie en innovatief gedrag, zelfs tegen de voor de hand liggende prijs van het opgeven van potentieel voordelige verbeteringen in gevestigde werkwijzen.[^63] Dit was een rationele afspiegeling van het feit dat experimenteren de variabiliteit van de resultaten vergroot. Een grotere variabiliteit betekent niet alleen potentieel hogere winsten, maar – des te dreigender voor degenen die op de rand van de overleving leven – potentieel ruinieuze verliezen. Een groot deel van de culturele energie in arme landbouwsamenlevingen was dan ook altijd gericht op het onderdrukken van experimentatie. Deze repressie fungeerde feitelijk als hun vervanging voor verzekeringspolissen. Hadden zij verzekering of voldoende spaargeld om hun experimenten zelf te verzekeren, dan zouden zulke sterke sociale taboes niet nodig zijn om hun overleving te garanderen.

Culturen zijn geen kwesties van smaak, maar systemen van aanpassing aan specifieke omstandigheden die in andere contexten irrelevant of zelfs contraproductief kunnen blijken te zijn. Mensen leven immers in een grote verscheidenheid aan habitats. Het overweldigende aantal potentiële niches waarin wij leven vergt gedragsvariaties die te complex zijn om uitsluitend door instinct gestuurd te worden. Daarom is gedrag cultureel geprogrammeerd. Voor de overgrote meerderheid in veel landbouwsamenlevingen programmeerde cultuur hen zodanig dat zij vooral gericht waren op overleving, zonder veel ruimte voor meer dan alleen het overleven in een omgeving waarin de luxe om deel te nemen aan open markten aan anderen was voorbehouden.

Persoonlijke bekwaamheid en individuele keuze – het moderne idee van ‘het nastreven van geluk’ – werden onderdrukt door taboes en sociale beperkingen die altijd het sterkst tot uiting kwamen onder de armen. Zulke beperkingen werden in samenlevingen met beperkte productiviteit slechts met grote moeite opgeheven. Wanneer en waar de landbouwproductiviteit hoger was, zoals in het oude Griekenland, vonden er kleinere megapolitieke revoluties plaats. Eigendom kreeg modernere vormen. ‘Allod’, oftewel vrij eigendom, ontstond. Landen werden doorgaans verhuurd tegen een vaste vergoeding, waarbij de huurder zowel het economische risico als een groter deel van de winst op zich nam als de oogst goed was. Hogere besparingen stelden hen in staat om risicovoller gedrag zelf te verzekeren. Onder zulke omstandigheden konden vrije boeren boven de boerenstand uitstijgen en soms zelfs een onafhankelijk vermogen opbouwen.

De neiging dat meer marktgerichte eigendomsrechten en -verhoudingen zich ontwikkelden aan de top van een economische hiërarchie – of, in zeldzamere gevallen, in de gehele economie – naarmate samenlevingen uit de armoede opstegen, is een belangrijk kenmerk van de sociale organisatie. Even belangrijk is het op te merken dat de meest voorkomende organisatievorm van landbouwsamenlevingen historisch gezien in wezen feodaal was, met marktrelaties aan de top en het gesloten dorpssysteem aan de onderkant. De grote massa boeren was in bijna alle premoderne landbouwsamenlevingen aan het land gebonden. Zolang de landbouwproductiviteit laag bleef, of een hogere productiviteit afhankelijk was van toegang tot gecentraliseerde hydraulische systemen, waren de vrijheid en eigendomsrechten van individuele boeren aan de onderkant minimaal. In zulke omstandigheden heersten feodale vormen van eigendom. Land werd verkregen door erfpacht en niet door vrij eigendom. Typisch waren de rechten van verkoop, schenking en erfopvolging sterk beperkt.

Feodalisme in zijn verschillende vormen was niet alleen een reactie op de voortdurend aanwezige dreiging van roofzuchtig geweld. Het was tevens een reactie op schrikbarend lage productiviteitsniveaus. In landbouwsamenlevingen gingen beide vaak hand in hand en droegen zij regelmatig elkaars bestaan bij. Wanneer de publieke autoriteit instortte, gingen eigendomsrechten en welvaart overeenkomstig achteruit. Het verval van de productiviteit ondermijnde bovendien de autoriteit. Hoewel niet elke droogte of ongunstige klimaatverandering leidde tot de ineenstorting van de publieke orde, gebeurde dat in veel gevallen wel.

## De feodale revolutie van het jaar 1000

Zo was het ook het geval tijdens de transformatie rond het jaar 1000, die de feodale revolutie in gang zette.[^64] In die tijd verschilden de megapolitieke en economische omstandigheden op belangrijke wijzen van hetgeen wij tegenwoordig met de Middeleeuwen associëren. In de eerste paar eeuwen na de val van Rome verzwakte de economie van West-Europa aanzienlijk. De Germaanse koninkrijken die zich in de gebieden van het voormalige Romeinse Rijk vestigden, hadden vele functies van de Romeinse staat overgenomen, maar op een veel minder ambitieus niveau. De infrastructuur raakte min of meer verwaarloosd; in de loop der eeuwen raakten bruggen en aquaducten in verval en werden ze onbruikbaar. Hoewel de Romeinse munten nog enige tijd in gebruik waren, verdween hun circulatie vrijwel geheel. De grondmarkten, die in Romeinse tijden floreerden, droogden min of meer op, en steden – ooit centra van Romeinse administratie – verdwenen vrijwel samen met de belastingkracht van de staat. Het meeste andere attribuut van de beschaving verdween eveneens.

De 'donkere middeleeuwen' hebben hun naam niet voor niets. Geletterdheid werd zo zeldzaam dat iedereen die kon lezen en schrijven vrijwel voor elk misdrijf – zelfs voor moord – gevrijwaard bleef van vervolging. Artistieke, wetenschappelijke en technische vaardigheden, die in de Romeinse tijd sterk ontwikkeld waren, verdwenen. Van de aanleg van wegen tot het enten van wijnstokken en vruchtbomen: West-Europa maakte geen gebruik meer van vele technieken die ooit algemeen bekend waren en op hoog niveau werden beoefend. Zelfs zo’n oud instrument als de pottenbakkersschijf verdween op talrijke plaatsen. Mijnbouwwerkzaamheden krompen in, de metallurgie deed terug en de irrigatiewerken in de mediterrane regio vielen door verwaarlozing uiteen.[^65] Zoals historicus Georges Duby opmerkte: 'Aan het eind van de zesde eeuw was Europa een diep ongeciviliseerde plaats.'[^66] Hoewel er rond het jaar 800, onder de heerschappij van Karel de Grote, een korte renaissance van centrale autoriteit optrad, verviel alles na zijn dood al snel weer in desorganisatie.

Een verrassend gevolg van dit sombere landschap was dat de ineenstorting van de Romeinse staat waarschijnlijk de levensstandaard van kleine boeren enkele eeuwen lang heeft verhoogd. De Germaanse koninkrijken die tijdens de donkere middeleeuwen West-Europa domineerden, namen enkele relatief soepele sociale kenmerken over die kenmerkend waren voor hun voorouderlijke stammen, zoals de wettelijke gelijkheid van vrije landeigenaren. Daardoor waren kleine boeren in de donkere middeleeuwen veel vrijer dan zij dat in de feodale eeuwen konden zijn – en hieruit kunnen we afleiden dat zij ook welvarender waren. Zoals hierboven werd geanalyseerd bij het onderzoeken van de logica van eigendomsvormen onder verschillende condities van productiviteit, ging vrije eigendom historisch gezien steeds gepaard met de relatieve welvaart van kleine boeren. De gesloten dorps- en feodale vormen van eigendom neigden zich juist te ontwikkelen op plaatsen waar de mogelijkheden voor kleine boeren om in hun levensonderhoud te voorzien minder zeker waren.

Zeker, de vrijwel volledige ineenstorting van de handel tijdens de donkere middeleeuwen heeft kleine boeren beroofd van de vruchten van de handel en de voordelen van bredere markten. Het verval van de steden ondermijnde de contante economie, maar betekende ook dat de landelijke bevolking niet langer gedwongen werd de verpletterende last van de bureaucratie te dragen. Zoals Guy Bois schreef, was de Romeinse stad een parasitaire gemeenschap, geen centrum van productie: 'In de Romeinse periode was de dominante functie van een stad van politieke aard. Zij leefde hoofdzakelijk van de opbrengsten die via de grondbelasting uit haar omgeving naar binnen stroomden…. In wezen produceerde de stad weinig of niets ten behoeve van het omliggende platteland.' [^67] De ineenstorting van de Romeinse heerschappij bevrijdde de boeren op het platteland grotendeels van belastingen, die tussen een kwart en een derde van het bruto product van het land opslokten, zonder de diverse afpersingen mee te rekenen waaraan kleine en middelgrote landeigenaren werden onderworpen. [^68] De belastingen waren zo ondragelijk – soms zelfs afgedwongen met de dood als straf – dat het verlaten van eigendommen door de eigenaren wijdverspreid was. De barbaren lieten deze belastingen genadig vervallen.

### Agri Deserti

De lasten van de overheid werden door de barbaarse veroveringen zodanig verminderd dat er een opening ontstond voor de armen om grond in eigendom te verkrijgen en te behouden. Sommige van de agri deserti, oftewel verlaten boerderijen die waren achtergelaten door eigenaren die de roofzuchtige belastingen in de laatste jaren van het Romeinse Rijk ontvluchtten, werden weer in productie genomen. Ondanks de ruwe omstandigheden van die tijd en het feit dat de oogstopbrengsten naar moderne maatstaven belachelijk laag waren, waren de donkere middeleeuwen een periode van relatieve welvaart voor de kleine boeren in Europa. In feite stond hun positie sterker dan ze dat weer zouden zijn tot aan de moderne tijd. Ten eerste waren er minder handen beschikbaar om het vruchtbare land te bewerken, waarvan grote delen onbewerkt waren geraakt. Plagen, oorlogen en het verlaten van land door eigenaren die het instortende Romeinse Rijk ontvluchtten, hadden gebieden die voorheen bebouwd waren aanzienlijk ontvolkt. Een ander voordeel voor de kleine boeren in de donkere middeleeuwen kwam voort uit de invoering in de zesde eeuw van een nieuwe landbouwtechnologie: de zware ploeg, vaak gemonteerd op wielen. In combinatie met een verbeterd tuig dat boeren in staat stelde meerdere ossen te gebruiken, maakte deze nieuwe technologie het een stuk eenvoudiger om bosrijk land in Noord-Europa te ontginnen. [^69]

Onder dergelijke omstandigheden kromp de markt voor land bijna tot het nulpunt. Nieuwe landbouwgrond kon worden verkregen door die simpelweg te ontginnen en een deel van elk nieuw perceel af te staan aan de desbetreffende lokale autoriteiten. Dit proces, dat 'assarting' wordt genoemd, bood gedurende eeuwen na de val van Rome een comfortabele manier om de bevolkingsgroei op te vangen. Assarting werd bijzonder aantrekkelijk in dunbevolkte noordelijke regio's, nadat de warmere temperaturen in de achtste eeuw de landbouw productiever maakten.

De leiders van de Germaanse stammen die voormalige Romeinse gebieden veroverden, hadden zich gevestigd als grote landeigenaren. Het merendeel van de overige bevolking bewerkte kleine percelen, maar onder omstandigheden die radicaal anders waren dan die later in het feodale tijdperk. Rijkere landeigenaren, oftewel heren, vertegenwoordigden ongeveer 7–10 procent van de bevolking. Het blijkt dat vóór het jaar 1000 tweederde van de dorpelingen in een typisch gebied in Frankrijk vrije landeigenaren waren. [^70] Zij bezaten ongeveer de helft van al het land dat in landbouw in gebruik was. [^71] Er waren weinig lijfeigenen. Coloni, ofwel pachtkwekers, maakten niet meer dan 5 procent van de bevolking uit. De slavernij bleef bestaan, maar op een veel kleinere schaal dan in de Romeinse tijd.

De Germaanse opvolgerkoninkrijken van Rome werden militair verdedigd door alle vrije mannen die zich verzamelden om het wapen te voeren op de roep van de lokale vertegenwoordiger van de koning, de graaf. Zelfs van 'kleine en middelmatige eigenaren' werd verwacht dat zij zich zouden verenigen en één van hen zouden sturen om mee te vechten in de infanterie. [^72] In het Edict van Pitres beval Karel de Kale dat iedereen die hiertoe in staat was, zich te verzamelen voor een strijd te paard. Paus Gregorius II had een eeuw eerder geprobeerd dit militair imperatief te bevorderen door in 732 de menselijke consumptie van paardenvlees te verbieden. [^73] Maar er was nog nauwelijks onderscheid in status of wet tussen de infanterie van de vrije landeigenaren en de cavalerie. Alle vrije mannen namen deel aan lokale juridische vergaderingen en konden een verzoek indienen voor geschillenbeslechting bij de graaf, een ambt dat sinds de late Romeinse tijd bestond. Er was geen adel als zodanig.

> 'Een sociaal fenomeen, nieuw als massaal fenomeen, verscheen plotseling in de jaren 980 aan de horizon: neerwaartse sociale mobiliteit. De eerste slachtoffers waren de kleine allodhouders.' [^74] - Guy Bois

Naarmate de donkere eeuwen voortduurden, gebeurden er echter verschillende zaken die de relaties destabiliseerden die de onafhankelijkheid van de boeren en vrije landeigenaren in de Germaanse koninkrijken, die de macht overnamen na de val van Rome, hadden gewaarborgd:

1. De bevolkingen herstelden zich geleidelijk, wat leidde tot een grotere druk op het gebruik van land. In de loop van enkele eeuwen werd een groot deel van het meest vruchtbare onclaimde land in gebruik genomen, met name in Noord-Europa. De toename van het aantal boeren ten opzichte van het aanbod van land deed de arbeid van iedere boer minder waard worden. De meeste eigendomsrechten werden door overerving opgesplitst in steeds kleinere percelen. In de donkere eeuwen hadden kinderen de neiging om de nalatenschap van hun ouders gelijkmatig te delen. Deze versnippering van bezittingen in een periode van bevolkingsgroei deed het land weer in trek raken en leidde tegen het midden van de tiende eeuw tot het heropleven van actieve landmarkten.

2. In de laatste decennia van de tiende eeuw werden de temperaturen plotseling kouder, met een verwoestende impact op de landbouwopbrengsten. Drie opeenvolgende mislukte oogsten leidden tot een zware hongersnood van 982 tot 984. Na een nieuwe mislukte oogst sloeg de hongersnood in 994 opnieuw toe.[^75] Vervolgens, in 997, werd het probleem van dalende oogstopbrengsten verergerd door een pest, die kleinere familiebedrijven met bijzondere kracht trof omdat de kleinschalige eigenaren niet over de middelen beschikten om de door verloren familieleden geleverde arbeid te vervangen. Deze opeenstapeling van mislukte oogsten en rampen bracht de boeren aanvankelijk in de schulden. Toen de opbrengsten niet herstelden, konden zij hun hypotheken niet betalen.

3. Machtsverhoudingen raakten geleidelijk ontwricht door de groeiende belangrijkheid van de zware cavalerie. Middeleeuwse historicus Frances Gies beschrijft de transformatie van de bepantserde cavalerist tot de middeleeuwse ridder:

> Aanvankelijk was de ridder een persoon van middelmatige status, die door zijn kostbare paard en harnas boven de boer werd verheven, en verbeterde hij langzaam zijn positie in de samenleving totdat hij tot de adel behoorde. Hoewel ridders de laagste rang binnen de hogere klasse bleven, kreeg het ridderschap een unieke allure waardoor het ridderslaan een eer werd die door de grote adel en zelfs het koningshuis hoog in aanzien werd gehouden. Die allure was voornamelijk het gevolg van het beleid van de Kerk om het ridderambt te christianiseren door de ceremonie van het ridderslaan te heiligen en door een gedragscode, bekend als ridderlijkheid, te sponsoren – een code die wellicht vaker werd geschonden dan nageleefd, maar die onbetwistbare invloed uitoefende op het denken en handelen van latere generaties.[^76]

Zoals we in *The Great Reckoning* hebben beschreven, gaf de uitvinding van de stijgbeugel de bewapende ridder op paard een formidabele aanvalscapaciteit. Hij kon nu op volle snelheid aanvallen zonder door de klap van zijn lans op een doelwit van zijn zadel gesmeten te worden. De militaire waarde van de zware cavalerie werd verder versterkt door een Aziatische uitvinding die in de tiende eeuw West-Europa bereikte: het metijzeren hoefijzer. Dit verbeterde de duurzaamheid van het paard op de weg verder.[^77] Ook droegen het gevormde zadel – dat het hanteren van zware wapens vergemakkelijkte –, de schop en het kurkenbit – waarmee de ruiter het paard met één hand kon beheersen tijdens het gevecht – bij aan de effectiviteit van de bewapende ridder.[^78] Gezamenlijk hebben deze schijnbaar kleine technologische innovaties de militaire waarde van de kleine landeigenaren drastisch doen afnemen, daar zij zich geen oorlogspaarden en bewapening konden veroorloven. De goedkopere van de voor oorlogsvoering speciaal gefokte paarden, de grote strijdpaarden die als destriers bekendstonden, waren vier ossen of veertig schapen waard. De duurdere oorlogspaarden kostten tien ossen of honderd schapen. Harnassen kostten bovendien een bedrag dat geen kleine landeigenaar zich kon veroorloven, gelijk aan de prijs van zestig schapen.[^79]

4. Het feit dat het koudere weer, mislukte oogsten, hongersnoden en plagen zich in de aanloop naar het jaar 1000 voordeden, speelde ook een rol in het bepalen van het gedrag. Veel mensen waren ervan overtuigd dat het einde der tijden of de Tweede Komst nabij was. Vrome of angstige landeigenaren, groot en klein, gaven hun land aan de Kerk in voorbereiding op de apocalyps.

### 'Alleen een arme man verkoopt land'

De onstabiele omstandigheden van de late tiende eeuw effenden de weg voor de feodale revolutie. Aaneengesloten mislukte oogsten en rampen zorgden ervoor dat de kleinschalige boeren in de schulden raakten. Toen de oogstopbrengsten niet herstelden, kwamen de vrije landeigenaren in een hopeloze situatie. Markten leggen immers altijd de grootste druk op de zwakste bezitters. Dat is immers een deel van hun deugd: zij bevorderen efficiëntie door activa uit de handen van de zwakken te verwijderen. Maar in het Europa van de late tiende eeuw was zelfvoorzienende landbouw vrijwel de enige bezigheid. Families die hun land verloren, verloren daarmee ook hun enige middel van bestaan. Geconfronteerd met dit onaanvaardbare vooruitzicht besloten veel, zo niet de meeste, vrije landeigenaren tijdens de feodale revolutie hun velden op te geven. In de woorden van Guy Bois: 'De enige zekere manier voor een boer om het land dat hij bebouwde te behouden, was door het eigendom ervan over te dragen aan de Kerk, zodat hij het vruchtgebruik ervan kon behouden.'[^80] Anderen droegen een gedeelte of al hun land over aan welvarendere boeren in wie zij vertrouwen hadden, hetzij bevriende buren, hetzij familieleden.

Deze eigendomsoverdrachten geschiedden onder de voorwaarde dat de boer, zijn familie en zijn nakomelingen bleven om de velden te bewerken. De arme boeren mochten tevens rekenen op de wederzijdse steun van de meer substantiële bezitters, nu de 'nobelen' die zich paard en harnas konden veroorloven en daarmee de vergrote landgoederen konden beschermen. Zo'n regeling kon vanuit het oogpunt van de nieuwe horige worden gezien als een tussentijdse stap tussen blijvend economisch eigendom en onteigening. Vaker wel dan niet was dit een overeenkomst die hij niet kon weigeren.

De dalende productiviteit bracht de arme boeren niet alleen in een hopeloos economisch dilemma; het veroorzaakte tevens een golf van roofzuchtig geweld dat de zekerheden omtrent eigendom ondermijnde. Degenen die niet de middelen hadden om een deel van de beperkte – en ontoereikende – voorraad paarden en voer te bemachtigen, ontdekten plots dat noch zij, noch hun bezittingen nog veilig waren. Om hun dilemma in hedendaagse termen uit te drukken: het was alsof je je vandaag de dag zou moeten bewapenen met een nieuw type wapen, maar dat de kosten daarvan $100.000 bedroegen. Als je die prijs niet kon betalen, zou je overgeleverd zijn aan degenen die dat wel konden.

Binnen enkele jaren stortte het vermogen van de koning en de rechtbanken in om de orde te handhaven.[^81] Iedereen met een harnas en een paard kon nu in wezen voor zichzelf de wet zijn. Het resultaat was een late tiende-eeuwse versie van Blade Runner, een chaotische uitbarsting van gevechten en plunderingen waartegen de gevestigde autoriteiten machteloos waren. Plunderingen en aanvallen door gewapende ridders verstoorden het platteland. Het is echter geenszins vanzelfsprekend dat alle slachtoffers van deze roofacties de armen waren. Integendeel, de ouderen, de fysiek zwakkeren of slecht voorbereide onder de grotere landeigenaren vormden aantrekkelijkere doelwitten, omdat zij immers meer bezaten.

Het was geen toeval dat dit gebeurde op het moment dat kouder weer, hongersnood en de pest de middelen onder druk zetten. De grootschalige politieke omstandigheden die bijdroegen aan de ineenstorting van het gezag waren al enige tijd aanwezig, maar hun potentieel om de machtsverhoudingen in de samenleving te veranderen, kwam pas tot uiting toen een crisis werd uitgelokt. Het lijkt erop dat mislukte oogsten en hongersnoden precies dat teweegbrachten. Hoewel het exacte verloop van de gebeurtenissen moeilijk te reconstrueren is, lijkt de plundering – althans deels – te zijn veroorzaakt door de wanhopige omstandigheden. Zodra het geweld losbarstte, werd duidelijk dat niemand in staat was de kracht te mobiliseren om het te stoppen. De overgrote meerderheid van de slecht bewapende boeren kon zeker weinig doen. Zelfs tientallen boeren te voet zouden geen partij kunnen opmaken tegen één gewapende ridder te paard. De vrije landeigenaren, net als de gevestigde autoriteiten – de koningen met hun graven – waren machteloos om te voorkomen dat lokaal land door gewapende strijders werd veroverd.

"The Peace of God"

In deze wanhopige omstandigheden droeg de kerk bij aan de opkomst van het feodalisme door te trachten een wapenstilstand te onderhandelen in het gewelddadige platteland. De historicus Guy Bois beschreef de situatie als volgt: 'De machteloosheid van de politieke autoriteiten was zodanig dat de kerk voor hen opdook in de poging de orde te herstellen, binnen de beweging die bekendstaat als "The Peace of God." "Councils of Peace" vaardigden een reeks verboden uit die door anathemata werden bekrachtigd; omvangrijke "assemblies of peace" verzamelden de eden van de krijgers. De beweging ontstond in de Franse Midi (Council of Charroux in 989, Council of Narbonne in 990) en verspreidde zich geleidelijk...' [^82]

De overeenkomst die de kerk sloot hield in dat er erkenning werd verleend aan het gezag van gewapende ridders in lokale gemeenschappen, in ruil voor een stilstand of verzachting van het geweld en de plunderingen. Grondbewijzen die na de uitbraak van geweld aan het einde van de tiende eeuw werden vastgelegd, droegen plotseling de aanduidingen "nobilis" of "miles" als teken van herenbezit. De adel als een afzonderlijke stand werd gecreëerd door de feodale revolutie. Eigendomsoverdrachten die enkele jaren eerder aan dezelfde personen waren geregistreerd, maakten nog geen dergelijk onderscheid uit. [^83]

Gezien de dalende productiviteit en de economische onzekerheid van de kleine landeigenaren leidde de megapolitieke macht van de gewapende ridders onvermijdelijk tot grondbezit op basis van feodaal leenstelsel. Tegen het einde van het eerste kwart van de elfde eeuw waren de vrije boeren grotendeels verdwenen. Hun vrije grondbezit was gekrompen tot een fractie van hun vroegere omvang en werd nu slechts deeltijds bewerkt. De kleine boeren of hun nakomelingen waren horigen die het grootste deel van hun tijd arbeid verrichtten op de landgoederen van feodale heren, zowel seculier als kerkelijk.

De wanorde die de feodale revolutie vergezeldde, leidde tot gedragsaanpassingen die het feodalisme verder versterkten. Een daarvan was de sterke toename in de bouw van kastelen. Kastelen verschenen voor het eerst in Noordwest-Europa als primitieve houten constructies in de nasleep van de Vikingaanvallen in de negende eeuw. Oorspronkelijk dienden zij als commandocentra voor Karolingische functionarissen, maar na de feodale revolutie werden ze erfelijke eigendommen. Deze vroege bolwerken waren veel primitiever dan zij later zouden worden, maar ze bleven desalniettemin moeilijk aan te vallen. Eenmaal opgericht, werden kastelen slechts met de grootste moeite verwoest. Naarmate zij het platteland begonnen te sieren, werd het steeds onwaarschijnlijker dat de koning of zijn graven de lokale suprematie van de heren effectief konden uitdagen.

### Bijdragen van de kerk aan de productiviteit

Het feodalisme was de reactie van de agrarische samenleving op het instorten van de orde in een tijdperk van lage productiviteit. In de vroege fasen van het feodalisme speelde de kerk een belangrijke en economisch productieve rol. Tot de bijdragen van de kerk behoorden:

1. In een omgeving waarin de militaire macht gedecentraliseerd was, bevond de kerk zich in een unieke positie om de vrede te handhaven en regels van orde te ontwikkelen die verder gingen dan de gefragmenteerde, lokale soevereiniteiten. Dit was een taak die door geen enkele wereldlijke macht kon worden vervuld. De observaties van de grote religieuze autoriteit A. R. Radcliffe-Brown zijn hierbij direct relevant. Hij wees erop dat ‘de sociale functie van een religie onafhankelijk is van haar waarheid of onwaarheid.’ Zelfs religies die absurd en afstotelijk zijn – zoals die van sommige wilde stammen – kunnen belangrijke en effectieve onderdelen vormen van de maatschappelijke machine.[^84] Dit was zeker het geval met de kerk in de vroege fasen van het feodalisme. Zij hielp regels op te stellen – zoals alleen een religie dat kon – die mensen in staat stelden prikkelvalstrikken en gedragsdilemma’s te overwinnen. Sommige van deze dilemma’s waren morele vraagstukken die inherent waren aan het menselijke bestaan, terwijl andere lokale dilemma’s waren, uniek voor de heersende megapolitieke omstandigheden. De middeleeuwse kerk speelde een bijzondere rol bij het herstellen van de orde op het platteland in de laatste jaren van de tiende eeuw. Door lokale autoriteiten religieuze en ceremoniële steun te verlenen, verlaagde zij de kosten voor het vestigen van ten minste zwakke lokale monopolen op geweld. Hierdoor droeg de kerk bij aan de voorwaarden die uiteindelijk leidden tot stabielere machtsverhoudingen.

De kerk bleef lange tijd daarna een rol spelen in het temmen van particuliere oorlogen en geweldsexcessen die anders door de burgerlijke autoriteiten niet in toom gehouden konden worden. Het relatief belang van de kerk ten opzichte van wereldlijke autoriteiten blijkt uit het feit dat in de elfde eeuw de belangrijkste administratieve indeling van het gezag in het grootste deel van West-Europa de parochie werd, in plaats van de oude civiele indelingen – de ager en pagus (stad) – die vanaf de Romeinse tijd tot in de duistere middeleeuwen waren standgehouden.

2. De kerk was de voornaamste bron voor het behouden en overdragen van technische kennis en informatie. Zij sponsorde universiteiten en verzorgde het minimale onderwijs waarvan de middeleeuwse samenleving genoot. Daarnaast bood de kerk een mechanisme voor het reproduceren van boeken en manuscripten, waaronder bijna alle hedendaagse informatie over landbouw en veeteelt. De scriptoria van de benedictijner kloosters kunnen worden beschouwd als een alternatieve technologie voor drukpersen, die toen nog niet bestonden. Hoe kostbaar en inefficiënt de scriptoria ook waren, zij waren in de feodale periode praktisch het enige middel om geschreven kennis te reproduceren en te bewaren.

3. De kerk heeft in hoge mate bijgedragen aan de verbetering van de productiviteit in de Europese landbouw, mede doordat haar landgoedbeheerders geletterd waren, vooral in de vroege fase van het feodalisme. Voordat de dertiende eeuw aanbrak, waren de beheerders van de landgoederen van de wereldlijke heren vrijwel allemaal analfabeten die hun administratie bijhielden met een ingewikkeld systeem van tekens. Hoe kundig deze boeren ook mochten zijn, zij waren niet in staat te profiteren van verbeteringen in productiemethoden die zij niet zelf konden bedenken of met eigen ogen konden aanschouwen. Daarom was de kerk essentieel voor de verbetering van de kwaliteit van granen, fruit en fokdieren. Dankzij haar uitgebreide bezittingen, die zich over het gehele Europese continent uitstrekten, kon de kerk het meest productieve zaad en de beste fokdieren naar gebieden sturen waar de opbrengst achterbleef. De vraag naar sacramentele wijn in Noord-Europa zette monniken ertoe aan te experimenteren met robuustere druivensoorten die in koudere klimaten konden overleven. Bovendien heeft de kerk op andere wijzen bijgedragen aan een hogere productiviteit in de middeleeuwse landbouw. Veel van de economisch inefficiënte, kleine percelen die tijdens de feodale revolutie aan de kerk waren geschonken, werden heringericht om ze gemakkelijker te bewerken. Tevens bood de kerk aanvullende diensten aan die kleine landbouwgemeenschappen vereisten. In veel regio’s maalden door de kerk beheerde molens graan tot meel.

4. De kerk vervulde vele functies die tegenwoordig door de overheid worden overgenomen, waaronder de aanleg van openbare infrastructuur. Dit is een van de manieren waarop de kerk heeft geholpen de door economen ‘dilemma’s rond publieke goederen’ te overwinnen in een tijdperk van gefragmenteerd gezag. Specifieke religieuze orden van de vroegmiddeleeuwse kerk wijdde zich aan toegepaste technische werkzaamheden, zoals het aanleggen van wegen, het herbouwen van ingestorte bruggen en het herstellen van vervallen Romeinse aquaducten. Daarnaast ruimden zij land op, bouwden dammen en droogden moerassen. Een nieuwe monastieke orde, de Kartusiaanse orde, groef in Artois, Frankrijk, de eerste ‘artesische’ put. Met percussieboringen groefden zij een klein gat, diep genoeg om een put te vormen die geen pomp vereiste.[^86] De cisterciënzerorde nam de taak op zich om in de Lage Landen onstabiele zeewallen en dijken te bouwen en te onderhouden. Boeren droegen land over aan cisterciënzer kloosters en huurden het vervolgens weer terug, terwijl de monniken de volledige verantwoordelijkheid namen voor het onderhoud en de reparaties. De cisterciënzers gingen ook voorop bij de ontwikkeling van waterkrachtmachines, die werden toegepast voor uiteenlopende werkzaamheden, zoals stampen, hijsen, malen en persen.[^87] Het klooster van Clairvaux groef een kanaal van twee mijl lang uit de rivier de Aube.[^88] De kerk trad eveneens op om nieuwe wegen en bruggen aan te leggen op plaatsen waar bevolkingscentra waren verschoven buiten het bereik van de oude Romeinse garnizoenswegen. Bisschoppen verleenden aflaten aan lokale heren die rivierovergangen bouwden of herstelden en hospices voor reizigers in stand hielden. Een monastieke orde, opgericht door Sint Benezet, de Frères Pontifes of 'Broeders van de Brug', bouwde enkele van de langste bruggen die destijds bestonden, waaronder de Pont d’Avignon, een enorme brug met twintig bogen over de Rhône, waaraan aan één uiteinde een kapel met tolpost was verbonden. Zelfs London Bridge, die tot in de negentiende eeuw overeind bleef, werd gebouwd door een kapelaan en deels gefinancierd met een bijdrage van 1.000 mark van de pauselijke legaat.[^89]

5. De kerk droeg tevens bij aan het ontstaan van een complexere markt. De bouw van kathedralen verschilt bijvoorbeeld in aard van de aanleg van openbare infrastructuur, zoals bruggen en aquaducten. In principe werden kerkelijke gebouwen uitsluitend gebruikt voor religieuze diensten en niet als doorgangswegen voor de handel. Niettemin mag niet worden vergeten dat de bouw van kerken en kathedralen heeft bijgedragen aan de totstandkoming en verdieping van markten voor tal van ambachtelijke en technische vaardigheden. Op dezelfde wijze als de militaire uitgaven van de natiestaat tijdens de Koude Oorlog onbedoeld hebben bijgedragen aan de ontwikkeling van het internet, leidde ook de bouw van middeleeuwse kathedralen tot neveneffecten, namelijk de stimulering van de handel. De kerk was een van de voornaamste afnemers bij de bouwsector en van ambachtslieden. Aankopen van zilver door de kerk voor communiediensten, kandelaars en kunstwerken ter decoratie van kerken hebben geholpen een markt voor luxe goederen te creëren die anders niet zou hebben bestaan.

In veel opzichten hielp de kerk de meedogenloosheid van het geweld te temperen dat werd ontketend door bewapende ridders tijdens en na de 'feodale revolutie'. Vooral in de eerste eeuwen van het feodalisme leverde de kerk een aanzienlijke bijdrage aan de verhoging van de productiviteit in de landbouw. Het was een essentiële instelling, die perfect aansloot op de behoeften van de agrarische samenleving aan het einde van de duistere middeleeuwen.

### Kwetsbaarheid voor geweld

In "dertig of veertig jaar gewelddadige onrust, de feodale revolutie van het jaar 1000," [^90] net als de val van Rome vijf eeuwen eerder, was een uniek evenement, veroorzaakt door een complexe wisselwerking van invloeden. Toch weerspiegelen in één opzicht de triomf van mali ham ines (slechte mannen) en de onderdrukkingen die zij teweegbrachten perfect de fundamentele kwetsbaarheid van de agrarische samenleving voor geweld. In tegenstelling tot de jacht- en verzamelperiode van het menselijk bestaan, bracht de landbouw een kwantumsprong in georganiseerd geweld en onderdrukking.

Al vanaf het allereerste begin werd dit weerspiegeld in de meer militante culturen van landbouwvolkeren. De goden van de vroege agrarische samenlevingen waren goden van regenval en overstromingen, waarvan de functies de bezorgdheden van die samenlevingen omtrent de factoren die de oogstopbrengst bepaalden weerspiegelden. De zender van regen of water was ook vaak de god van de oorlog, aangeroepen door de vroegste koningen, die bovenal krijgsheren waren.[^91]

De nauwe band tussen landbouw en oorlogsvoering werd weerspiegeld in de religieuze verbeelding van mensen wier levens werden getransformeerd door de innovaties van de agrarische revolutie. De verdrijving uit de Hof van Eden kan worden gezien als een symbolische weergave van de transformatie van de samenleving: van een bestaan waarin men met weinig inspanning voedsel plukte uit de overvloed van de natuur, naar een bestaan dat werd gekenmerkt door zware arbeid.

## Paradijs verloren

De landbouw zette de mensheid op een geheel nieuw spoor. De eerste boeren plantten werkelijk de zaden van de beschaving. Uit hun arbeid ontstonden steden, legers, rekenkunde, astronomie, kerkers, wijn en whiskey, het geschreven woord, koningen, slavernij en oorlog. Niettemin, ondanks al het drama dat de landbouw aan het leven toevoegde, lijkt de overgang van de oer-economie vanaf het allereerste begin breed impopulair te zijn geweest. Zie het verslag dat bewaard is gebleven in het boek Genesis, waarin het verhaal van de verdrijving uit het paradijs wordt verteld. De bijbelse gelijkenis van de Hof van Eden roept een dierbare herinnering op aan het zorgeloze bestaan dat de verzamelaar in de wildernis genoot. Wetenschappers stellen dat het woord 'Eden' schijnbaar is afgeleid van een Sumerisch woord voor 'wildernis.'[^92]

De overgang van een vrij en schaars bevolkt leven in de natuur naar een sedentaire levensstijl in een landbouwdorp werd met diepe spijt ervaren, zoals blijkt niet alleen in de Bijbel, maar ook uit de voortdurende wrok van de mensheid tegen het 's ochtends opstaan en naar het werk gaan. Zoals Stephen Boyden schreef in Western civilization in biological perspective, was de nieuwe manier van leven die de landbouw met zich meebracht "evodeviant."[^93] Vóór de opkomst van de landbouw leefden duizenden generaties mensen zoals Adam in Eden, op uitnodiging van zijn Schepper: "Van alle bomen in de tuin magt gij vrij eten." Jagers en verzamelaars hadden geen gewassen om te verzorgen, geen kudde om te bewaken en geen belastingen te betalen. Net als hobo's zwierven zij waarheen zij wilden, werkten weinig en waren aan niemand verantwoording verschuldigd.

Met de landbouw begon een nieuwe levenswijze, en wel onder veel ingrijpendere voorwaarden. "Thorns also and thistles shall it bring forth to thee; and thou shalt eat the herb of the field; In the sweat of thy face shalt thou eat bread." Landbouw was zwaar werk. De herinnering aan het leven vóór de landbouw was die van een verloren paradijs.

Meer dan zij zich hadden kunnen voorstellen, schiepen boeren nieuwe omstandigheden die de logica van geweld radicaal veranderden. Het is geen toeval dat het boek Genesis Kaïn, de eerste moordenaar, als "a tiller of the ground" afbeeldt. Inderdaad, het behoort tot de onheilspellende profetische kracht van de Bijbel dat haar verhaal werd toevertrouwd aan herders die als geen ander begrepen hoe de landbouw geweld een hefboomwerking verleende. In enkele verzen vat het bijbelse verslag een logica samen die zich over duizenden jaren heeft ontwikkeld. Landbouw was een broedplaats voor conflicten. De landbouw schiep op grote schaal stationair kapitaal, waardoor de opbrengst van geweld toenam en het beschermen van eigendommen een dramatisch grotere uitdaging werd. Voor het eerst werden zowel misdaad als overheidsingrijpen lucratieve ondernemingen.

[^51]: Boyden, op. cit., p.4.
[^52]: Gregg, op. ciL, xv.

[^53]: Boyden, op. cit., p. 62.

[^54]: Ibid., p. 67.

[^55]: Ibid.

[^56]: Geciteerd in E. J. P. Veale, Advance to Barbarism: The Development of Total Warfore (New York: Devin-Adair, 1968), p. 37.

[^57]: R. Paul Shaw en Yuwa Wong, Genetic Seeds of Warfare: Evolution, Nationalism and Patriotism (Boston: Unwin Hyman, 1989), p. 4.

[^58]: Zie Carleton S. Coon, *The Hunting Peoples* (New York: Nick Lyons Books, 1971), p.275.

[^59]: Gregg, op. cit., p.23.

[^60]: Boyden, op. cit., p. 69.

[^61]: Shaw and Wong, op. cit., p. 69

[^62]: Voor meer details over de kafirs, zie Schuyler Jones, *Men of Influence in Nuristan* (London: Seminar Press, 1974).

[^63]: Zie Samuel L. Popkin, *The Rational Peasant* (Berkeley: University of California Press 1979), p. 13.

[^64]: Zie Bois, op. cit.

[^65]: Zie Frances en Joseph Gies, Cathedral, Forge, and Waterwheel: Technology and Invention in the Middle Ages (New York: HarperCollins, 1994), p. 40.

[^66]: Geciteerd in ibid., p. 42.

[^67]: Bois, op. cit., p. 78.

[^68]: Ibid., p.118.

[^69]: Gies, op. cit., p.45.

[^70]: Bois, op. cit., p. 116.

[^71]: Ibid., p.26.

[^72]: Ibid, p.64.

[^73]: Gies, op. cit., p.47.

[^74]: Bois, op. cit., p.52.

[^75]: Ibid., p.150

[^76]: Gies, op. cit., p.2.

[^77]: Ibid., p.46.

[^78]: Ibid., pp.56-57.

[^79]: Ibid., p.58.

[^80]: Bois, op. cit., p.87.

[^81]: Ibid. Hoewel de precieze volgorde van gebeurtenissen tijdens de feodale revolutie moeilijk te reconstrueren is door het gebrek aan bronnen, lijkt de brede schets van de these, zoals voorgesteld door Guy Bois, hoogstwaarschijnlijk juist te zijn. Het is niet alleen op zichzelf aannemelijk, maar verklaart ook op logische wijze anders afwijkende feiten en past bovendien binnen onze theorieën.

[^82]: Ibid., p.136.

[^83]: Ibid., blz. 57 en passim.

[^84]: A. R. Radcliffe-Brown, religie en samenleving, in structuur en functie in de primitieve samenleving (London: Cohen & West, 1952), blz. 153-77.

[^85]: Bois, op. cit., blz. 36.

[^86]: Gies, op. cit., blz. 112.

[^87]: Ibid., blz. 114.

[^88]: Ibid., p.117.

[^89]: De details over bruggen en infrastructuur komen voornamelijk uit ibid., pp.148-54.

[^90]: Bois, op. cit., p.136.

[^91]: Zie Norman Cohn, *Cosmos, Chaos, and the World to Come: The Ancient Roots of the Apocalyptic Faith* (New Haven: Yale University Press, 1993), hoofdstukken I-3, met name p.60.

[^92]: Bruce Ni. Metzger en Michael D. Coogan, red., *The Oxford Companion to the Bible* (Oxford: Oxford University Press, 1993), p.178.

[^93]: Boyden, op. ciL, p. 118.