# de laatste dagen van de politiek

:::{.content-hidden when-format=latex}

*Parallellen tussen de seniele achteruitgang van de heilige moederkerk en de bemoeizuchtige staat*

:::

> 'Ik geloof er ook in - en hoop - dat politiek en economie in de toekomst niet zo belangrijk zullen zijn als in het verleden; er zal een tijd komen waarop de meeste van onze huidige controverses over deze onderwerpen zo banaal of betekenisloos zullen lijken als de theologische debatten waarin de scherpste geesten van de middeleeuwen hun energie verkwistten.'[^94] - ARTHUR C. CLARKE

Om te spreken over de op handen zijnde dood van de politiek lijkt, afhankelijk van je instelling, belachelijk of optimistisch. Toch is dat wat de informatierevolutie waarschijnlijk zal brengen. Voor lezers die zijn opgegroeid in een eeuw die doordrenkt is van politiek, lijkt het idee dat het leven zonder politiek zou kunnen doorgaan misschien fantasierijk, vergelijkbaar met beweren dat men zich uitsluitend zou kunnen voeden door voedingsstoffen uit de lucht op te nemen. Toch is politiek in de moderne zin – de preoccupatie met het beheersen en rationaliseren van de macht van de staat – grotendeels een moderne uitvinding. Wij geloven dat deze zal eindigen met de moderne wereld, net zoals het wirwar van feodale plichten en verplichtingen, dat de aandacht van de mensen in de middeleeuwen opslokte, tot een einde kwam met de middeleeuwen. Tijdens de feodale periode, zoals historicus Martin van Creveld opmerkt, "bestond politiek niet (het concept moest nog uitgevonden worden en dateert slechts uit de zestiende eeuw)." [^95]

De gedachte dat politiek, zoals wij die nu kennen, niet bestond vóór de moderne periode, kan verrassend lijken, zeker gezien het feit dat Aristoteles in de tijd van Alexander de Grote een essay met die titel schreef. Maar kijk goed: woorden die in oude teksten werden gebruikt, zijn niet per se hedendaagse concepten. Aristoteles schreef ook een essay getiteld Sophistical Refutations, een term die tegenwoordig ongeveer net zo betekenisloos is als "politics" dat in de middeleeuwen was. Het woord was simpelweg niet in gebruik. De eerste bekende vermelding in het Engels dateert uit 1529.[^96] Zelfs toen leek "politics" een pejoratief te zijn, afgeleid van het Oudfranse woord politique, dat werd gebruikt om "opportunisten en tempelaars" te beschrijven.[^97]

Het heeft bijna tweeduizend jaar geduurd voordat Aristoteles’ latente concept opkwam met de betekenis die wij nu kennen. Waarom? Voordat de moderne wereld aan Aristoteles’ woord een betekenisvolle invulling kon geven, waren grootschalige politieke omstandigheden vereist die de opbrengsten van geweld drastisch deden stijgen. De buskruitrevolutie, die we in *The Great Reckoning* hebben geanalyseerd, deed precies dat. Het verhoogde de opbrengsten van geweld ver boven elk eerder niveau. Hierdoor werd de vraag wie de staat beheerste belangrijker dan ooit tevoren. Logisch en onvermijdelijk ontstond de politiek uit de strijd om de sterk toegenomen buit van de macht te beheersen.

De politiek begon vijf eeuwen geleden met de vroege stadia van het industrialisme. Nu is het aan het sterven. Een wijdverspreide afschuw jegens politiek en politici raast over de wereld. Je ziet het terug in berichten en speculaties over de verborgen details van Whitewater en de slecht vermomde moord op Vincent Foster. Je ziet het in tal van andere schandalen waarbij president Bill Clinton betrokken is. Je leest er ook over verduistering door vooraanstaande congresleden van het postkantoor van het Huis van Afgevaardigden in. Je ziet het in schandalen die tot aftreden leidden in de kring van John Major en in vergelijkbare schandalen in Frankrijk, waarbij twee recente premiers, Eduard Balladur en Alain Juppe, betrokken waren. Nog grotere schandalen kwamen aan het licht in Italië, waar de zevenvoudige premier Giuho Andreotti voor de rechtbank werd gebracht om berecht te worden op aanklachten waaronder banden met de maffia en het bevel tot moord op Mino Pecorelli, een onderzoeksjournalist. Nog andere schandalen hebben de reputatie van de Spaanse premier Filipe Gonzales bezoedeld. Corruptieaanklachten kostten vier Japanse premiers hun positie in de eerste vijf jaar van de jaren negentig. Het Canadese ministerie van Justitie beweerde in een brief aan de Zwitserse autoriteiten dat de voormalige premier Brian Mulroney steekpenningen had ontvangen bij een verkoop van Airbus-vliegtuigen aan Air Canada ter waarde van C$l.8 miljard.[^98] Willy Claes, de secretaris-generaal van de NAVO, werd gedwongen af te treden onder een wolk van corruptieaanklachten. Zelfs in Zweden werd Mona Sahlm, een vicepremier en veronderstelde premier, gedwongen af te treden naar aanleiding van beschuldigingen dat ze overheidscreditcards had gebruikt om luiers en andere huishoudelijke artikelen te kopen. Bijna overal, in landen met volwassen welvaartsstaten die ooit als goed bestuurd werden beschouwd, haten mensen hun politieke leiders.

### Minachting als leidende indicator

Morele verontwaardiging over corrupte leiders is geen geïsoleerd historisch verschijnsel, maar een veelvoorkomende voorloper van verandering. Het gebeurt keer op keer wanneer het ene tijdperk plaatsmaakt voor het andere. Wanneer technologische veranderingen de oude vormen scheiden van de nieuwe drijvende krachten van de economie, verschuiven de morele normen en beginnen mensen degenen die de oude instellingen aansturen met toenemende minachting te behandelen. Deze wijdverspreide afkeer komt duidelijk naar voren ruim voordat mensen een nieuwe, coherente ideologie van verandering ontwikkelen. Op het moment van schrijven is er nog weinig bewijs van een welgearticuleerde afwijzing van de politiek. Dat zal later komen. Het is bij de meeste van je tijdgenoten nog niet opgekomen dat een leven zonder politiek mogelijk is. Wat we hebben in de laatste jaren van de twintigste eeuw is onuitgesproken minachting.

Iets vergelijkbaars gebeurde aan het einde van de vijftiende eeuw, maar in die tijd was het de religie in plaats van de politiek die werd afgeslankt. Ondanks de populaire opvatting in 'de heiligheid van het sacerdotale ambt' werden zowel de hogere als de lagere geestelijkheid met de grootste minachting behandeld, vergelijkbaar met de hedendaagse publieke houding tegenover politici en bureaucraten. Men geloofde algemeen dat de hogere geestelijkheid corrupt, werelds en venaal was. En dat niet zonder reden. Verschillende pausen uit de vijftiende eeuw hadden openlijk buitenechtelijke kinderen. De lagere geestelijkheid werd nog lager geëerd, omdat zij in het platteland en in de steden in overvloed aanwezig waren, aalmoezen bedelend en frequent Gods genade en de vergeving van zonden te koop aanbiedend aan iedereen die bereid was er contant geld voor te geven.

Onder de 'korst van oppervlakkige vroomheid'[^100] schuilde een corrupt en steeds disfunctioneler wordend systeem. Velen verloren al lang het respect voor degenen die het bestuurden, lang voordat iemand de moed had op te merken dat het niet werkte. Een leven doordrenkt van religie, waarbij geen onderscheid werd gemaakt tussen het geestelijke en het wereldlijke, had al zijn mogelijkheden uitgeput. Het einde ervan was onvermijdelijk lang voordat Luther zijn 95 stellingen op de kerkdeur van Wittenberg spijkerde.

## Een seculiere reformatie

Wij zijn van mening dat de reactie tegen de verzadigingspolitiek een soortgelijk pad volgt.

De val van de Sovjet-Unie en de afwijzing van het socialisme maken deel uit van een breed patroon van depolitisering dat de wereld overspoelt. Dit uit zich met name in de groeiende minachting voor degenen die de regeringen van de wereld besturen. Deze ontwikkeling wordt slechts deels gevoed door het besef dat zij corrupt zijn en dat zij de neiging hebben om 'aflaat' te verkopen om politieke moeilijkheden te sussen, in ruil voor campagnebijdragen of bijzondere hulp bij de handel in grondstoffen om hun persoonlijke financiën te ondersteunen.

De reactie tegen politici wordt bovendien ingegeven door het groeiende besef dat veel van hun inspanningen, ondanks enorme kosten, zinloos is – op dezelfde wijze als dat het organiseren van nog een pelgrimstocht van boetelingen om blootsvoets door de sneeuw te marcheren, of het stichten van opnieuw een orde van bedelaarsmonniken in de late vijftiende eeuw, weinig zou bijdragen aan het verbeteren van de productiviteit of het verlichten van de druk op de levensstandaard.

### De laatste dagen van de heilige moederkerk

Aan het einde van de middeleeuwen was de monolithische kerk als instelling seniel en contraproductief geworden – een duidelijke ommekeer ten opzichte van haar positieve economische bijdrage vijf eeuwen eerder. Zoals we in het vorige hoofdstuk hebben vastgesteld, speelde de kerk aan het einde van de tiende eeuw een leidende rol bij het vestigen van orde en het bevorderen van economisch herstel na de anarchie die het einde van de donkere eeuwen kenmerkte. In die tijd was de kerk onmisbaar voor het voortbestaan van talloze kleine vrije landeigenaren en lijfeigenen, die samen de meerderheid van de West-Europese bevolking vormden. Tegen het einde van de vijftiende eeuw was de kerk een zware belemmering geworden voor de productiviteit, en de lasten die zij de bevolking oplegde, zorgden voor een daling van de levensstandaard.

Hetzelfde geldt voor de natiestaat van vandaag. Zij vormde een noodzakelijke aanpassing aan de nieuwe megapolitieke omstandigheden die vijf eeuwen geleden door de buskruitrevolutie waren gecreëerd. De natiestaat vergrootte de omvang van de markten en verdrong de gefragmenteerde lokale autoriteiten op een moment dat steeds grotere handelsgebieden aanzienlijke opbrengsten opleverden. Dat handelslieden bijna overal in Europa zich spontaan met de centrale vorst verbonden terwijl hij zijn gezag wist te consolideren, is op zich al duidelijk bewijs dat de natiestaat in haar vroege vorm gunstig was voor het bedrijfsleven. Zij hielp de lasten op de handel, opgelegd door feodale landeigenaren en lokale magnaten, te verlichten.

In een wereld waarin de opbrengsten van geweld hoog waren en toenamen, was de natiestaat een nuttige instelling. Maar vijf eeuwen later, nu dit millennium ten einde loopt, zijn de megapolitieke omstandigheden ingrijpend veranderd. De opbrengsten van geweld dalen, en de natiestaat is, net als de kerk in de schemering van de middeleeuwen, een anachronisme dat de groei en productiviteit belemmert.

Net als de kerk destijds heeft de natiestaat van vandaag haar mogelijkheden uitgeput. Zij is failliet, een instelling die tot op een seniele extreme is gegroeid. Vijf eeuwen lang diende zij als de overheersende vorm van sociale organisatie, maar omdat zij de omstandigheden die haar tot stand brachten heeft overleefd, is zij rijp voor ondergang. En vallen zal zij dan ook. Technologie zorgt voor een revolutie in de uitoefening van macht die de natiestaat net zo zeker zal vernietigen als buskruitwapens en de drukpers ooit het monopolie van de middeleeuwse kerk hebben doen instorten.

Als onze redenering klopt, zal de natiestaat worden vervangen door een nieuwe vorm van soevereiniteit, waarvan sommigen uniek in de geschiedenis zullen zijn en anderen doen denken aan de stadstaten en middeleeuwse koopmansrepublieken uit de premoderne wereld. Wat oud was, zal na het jaar 2000 nieuw blijken te zijn. En wat onvoorstelbaar was, zal alledaags worden. Naarmate de schaal van de technologische ontwikkelingen in een stroomversnelling raakt, zullen regeringen ontdekken dat zij als bedrijven moeten concurreren om inkomsten, door niet meer te vragen voor hun diensten dan deze daadwerkelijk waard zijn voor de mensen die ervoor betalen. De volledige implicaties van deze verandering zijn vrijwel onvoorstelbaar.

## Toen en nu

Zoiets zou vijfhonderd jaar geleden gezegd kunnen zijn, aan het begin van de vijftiende eeuw. Toen, net als nu, stond de westerse beschaving op de drempel van een ingrijpende transformatie. Hoewel bijna niemand het doorhad, verging de middeleeuwse samenleving. Haar ondergang werd noch breed verwacht, noch begrepen. Desalniettemin heerste er een sfeer van diepe somberheid. Dit is gebruikelijk aan het einde van een tijdperk, wanneer conventionele denkers het gevoel krijgen dat de dingen uit elkaar vallen, dat ‘de valk het geluid van de valker niet meer hoort.’ Toch is hun mentale traagheid vaak te groot om de implicaties van de opkomende machtsconfiguraties te doorgronden. De middeleeuwse historicus Johan Huizinga schreef over de laatste dagen van de middeleeuwen: ‘De kroniekschrijvers van de vijftiende eeuw zijn, bijna allen, ten prooi gevallen aan een volstrekt misvatting van hun tijden, waarin de werkelijke drijvende krachten aan hun aandacht ontsnapten.’[^101]

### Mythen verraden

Grote veranderingen in de onderliggende machtsdynamiek brengen conventionele denkers vaak in verwarring, omdat zij mythen blootleggen die de oude orde rechtvaardigen maar geen echte verklaringskracht bezitten. Aan het einde van de middeleeuwen, net als nu, was er een bijzonder grote kloof tussen de overgeleverde mythen en de werkelijkheid. Zoals Huizinga over de Europeanen in de late vijftiende eeuw zei: ‘Hun gehele ideeënstelsel was doordrenkt met de fictie dat de ridderlijkheid de wereld regeerde.’[^102] Dit heeft een nauw verwante tegenhanger in de hedendaagse opvatting dat alles wordt geregeerd door stemmen en populariteitswedstrijden. Geen van beide stellingen houdt stand bij nadere beschouwing. Inderdaad, het idee dat de loop der geschiedenis wordt bepaald door democratische optellingen van wensen is even belachelijk als de middeleeuwse opvatting dat zij wordt bepaald door een uitgebreide gedragscode, genaamd ridderlijkheid.

Het feit dat zo'n uitspraak bijna als ketterij wordt beschouwd, suggereert hoe ver conventioneel denken verwijderd is van een realistisch begrip van de machtdynamiek in de laat-industriële samenleving. Dit is een kwestie die we in dit boek grondig onderzoeken. Volgens ons was stemmen eerder een gevolg dan een oorzaak van de megapolitieke omstandigheden die de moderne natiestaat tot stand brachten. Massademocratie en het concept van burgerschap bloeiden op naarmate de natiestaat groeide. Zij zullen wankelen naarmate de natiestaat faalt, waardoor in Washington net zoveel onvrede ontstaat als de achteruitgang van de ridderlijkheid ooit in het hof van de hertog van Bourgondië vijfhonderd jaar geleden.

## Parallellen tussen ridderlijkheid en burgerschap

Als u begrijpt hoe en waarom het belang van ridderlijke eden vervaagde met de overgang naar een industriële organisatie van de samenleving, bent u beter in staat te zien hoe het burgerschap, zoals wij dat nu kennen, in het informatietijdperk zou kunnen verdwijnen. Beide vervulden een soortgelijke functie; zij maakten de uitoefening van macht mogelijk onder twee geheel verschillende megapolitieke omstandigheden.

Feodale eden waren van kracht in een tijd waarin defensieve technologie doorslaggevend was, soevereiniteiten versnipperd waren en particuliere individuen en bedrijven uit eigen kracht militaire macht uitoefenden. Vóór de buskruitrevolutie werden oorlogen normaal gesproken uitgevochten door kleine contingenten gewapende mannen. Zelfs de machtigste monarchen beschikten niet over een militum perpetuum, oftewel staande legers. Zij ontleenden hun militaire steun aan hun vazallen – de grote heren – die op hun beurt hun steun ontleenden aan hun vazallen – de mindere heren – die vervolgens weer hun steun ontleenden aan hun vazallen, de ridders. De gehele loyaliteitsketen liep door de hiërarchie tot aan de persoon met de laagste sociale status die als waardig werd geacht om wapens te dragen.

### Uniformen of afwijkingen?

In tegenstelling tot een modern leger trok een middeleeuws leger, in de periode vóór de opkomst van het burgerschap, het slagveld op niet in uniformen. Integendeel, elke dienaar of vazal, elke ridder, baronet of heer van verschillende standen droeg zijn eigen kenmerkende dienstkledij die zijn positie in de hiërarchie weerspiegelde. In plaats van uniformen waren er juist verschillen die de verticale structuur van de samenleving benadrukten, waarin iedere positie uniek was. Zoals Huizinga zei, werden middeleeuwse krijgers onderscheiden door "uitwendige tekenen van ... verschillen: dienstkledij, kleuren, emblemen, strijdkreten."[^103]

Ook werden oorlogen niet uitsluitend gevoerd door overheden of naties. Zoals Martin van Creveld heeft opgemerkt, geven moderne opvattingen over oorlog, zoals gestileerd door strategen als Carl von Clausewitz, een vertekend beeld van de premoderne conflicten. Van Creveld schrijft:

> Duizend jaar na de val van Rome werd gewapend conflict gevoerd door verschillende soorten sociale entiteiten. Onder hen bevonden zich barbaarse stammen, de Kerk, feodale baronnen van alle rangen, vrije steden en zelfs particuliere individuen. En de "legers" van die periode waren totaal niet te vergelijken met de legers die we tegenwoordig kennen; het is immers moeilijk een woord te vinden dat recht doet aan hun aard. Oorlog werd gevoerd door zwermen dienaren die in militaire kledij verschenen en hun heer volgden.[^104]

Onder dergelijke omstandigheden was het voor de heer van cruciaal belang dat zijn dienaren daadwerkelijk "hun militaire kledij aantrokken en hun heer volgden." Vandaar de grote nadruk op de ridderlijke eed.

De eer van de middeleeuwse ridder en de plicht van de dienstplichtige soldaat vervulden een parallelle functie. De middeleeuwse mens was, net zoals de moderne burger door zijn burgerschap aan de natiestaat gebonden is, met eden verplicht aan zowel individuen als aan de Kerk. Het schenden van een eed was in de middeleeuwen gelijkwaardig aan hoogverraad. Mensen in de laatmiddeleeuwen gingen tot het uiterste om het breken van eden te vermijden, net zoals miljoenen moderne burgers tijdens de Wereldoorlogen tot het uiterste gingen door machinegeweerbatterijen te bestormen om hun plichten als burgers na te komen.

Zowel ridderlijkheid als burgerschap gaven een extra dimensie aan de simpele berekening die anders niet-geïndoctrineerde mensen ervan zou weerhouden om het slagveld op te gaan en daar te blijven wanneer het zwaar wordt. Ridderlijkheid en burgerschap leidden er immers toe dat mensen gingen doden en hun leven riskeerden. Alleen veeleisende en overdreven waarden, die krachtig worden versterkt door vooraanstaande instellingen, kunnen die functie vervullen.

### Het omzeilen van de kosten-batenanalyse

Het succes en overleven van ieder systeem is afhankelijk van het vermogen om in tijden van conflict en crisis militaire inspanningen te bundelen. Uiteraard was de beslissing van een middeleeuwse ridder of van een soldaat in de loopgraven tijdens de Eerste Wereldoorlog om zijn leven in de strijd te riskeren, niet te baseren op een nuchtere kosten-batenberekening. Zelden worden oorlogen zo eenvoudig gevoerd, of zijn de opbrengsten voor zij die de hoofdlast van de strijd dragen zo groot dat een leger vol economische optimaliseerders spontaan naar het slagveld zou kunnen worden gerekruteerd. Bijna elke oorlog, en inderdaad de meeste veldslagen, kennen momenten waarop de tolslag in een oogwenk kan keren. Zoals studenten van militaire geschiedenis weten, wordt het verschil tussen nederlaag en overwinning vaak bepaald door de moed, dapperheid en woede waarmee individuele soldaten hun taak op zich nemen. Als de mannen die vechten niet bereid zijn te sterven voor een strook land die, zodra de strijd stopt, nauwelijks enige waarde zou hebben, is de kans groot dat zij niet zullen zegevieren tegen een anders even sterk tegenstander.

Dit heeft belangrijke gevolgen. Hoe effectiever soevereiniteiten zijn in het beperken van desertie en het stimuleren van militaire inzet, des te groter is de kans op militaire overwinning. In oorlogszaken zorgen de meest bruikbare waardesystemen ervoor dat mensen zich op manieren gedragen die een kortetermijn, rationele berekening normaal gesproken zou uitsluiten. Geen enkele organisatie zou in staat zijn om militaire macht effectief te mobiliseren als de individuen die zij naar het slagveld stuurt, de vrijheid hadden om zelf te berekenen waar hun eigen belang het beste diende, en vervolgens wel of niet mee zouden strijden. In dat geval zouden zij vrijwel nooit vechten. Alleen onder de meest gunstige of juist de meest wanhopige omstandigheden zou de rationeel handelende persoon zich wagen aan een potentieel dodelijke strijd, gebaseerd op een kortetermijnkosten-batenanalyse. Misschien zou de Homo economicus vechten op een zonovergoten dag, wanneer de troepen aan zijn zijde overweldigend waren, de vijand zwak en de mogelijke beloningen van de strijd verleidelijk. Misschien. Hij zou ook kunnen vechten als hij door rondtrekkende kannibalen in het nauw wordt gedreven.

Maar dat zijn extreme omstandigheden. Hoe zit het met de meer alledaagse condities van oorlogvoering, die noch zo aantrekkelijk zijn dat ze een kosten-batenanalyse zouden doorstaan, noch zo wanhopig dat er geen uitweg mogelijk is? Het is juist in die situaties dat begrippen als ridderlijkheid en burgerschap een belangrijke bijdrage leveren aan het succesvolle gebruik van militaire kracht. Lang voordat een veldslag begint, moeten dominante organisaties individuen ervan overtuigen dat het nakomen van bepaalde plichten jegens de heer of de natiestaat belangrijker is dan het eigen leven. De mythen en rationalisaties die samenlevingen hanteren om risico’s op het slagveld aan te moedigen, vormen een essentieel onderdeel van hun militaire slagkracht.

Om effectief te zijn, moeten deze mythen worden afgestemd op de heersende megapolitieke omstandigheden. De fictie dat de ridderlijkheid de wereld regeert, betekent tegenwoordig niets, zeker niet in een stad als New York. Maar het was de gekoesterde mythe van het feodalisme. Het rechtvaardigde en rationaliseerde de verplichtingsbanden die iedereen bonden onder de overheersing van de Kerk en een oorlogszuchtige adel. In een tijd waarin particuliere oorlogen, voortgekomen uit hebzucht, gebruikelijk waren, hingen de uitoefening van macht en het voortbestaan van individuen af van de bereidheid van anderen om hun beloftes tot militaire dienst onder omstandigheden van dwang na te komen. Het was uiteraard cruciaal dat die beloftes betrouwbaar waren.

### Voor nationaliteit

In tegenstelling tot tegenwoordig speelde het concept van nationaliteit nauwelijks of helemaal geen rol bij het vestigen van soevereiniteit in de Middeleeuwen. Monarchen, evenals enkele prinsen van de Kerk en machtige heren, bezaten gebieden op grond van privaat recht. Op een wijze die geen moderne vergelijking kent, konden deze heren gebieden verkopen of weggeven, of nieuwe gebieden verwerven door overdracht, huwelijk én verovering. Tegenwoordig kun je je nauwelijks voorstellen dat de Verenigde Staten onder de soevereiniteit zouden vallen van een niet-Engelssprekende Portugese president omdat hij toevallig met de dochter van de voormalige Amerikaanse president trouwde. Toch was iets dergelijks in middeleeuws Europa heel gewoon. Macht werd overgedragen via erfopvolging. Steden en landen wisselden van heersers zoals antiek van eigenaar wisselt. In veel gevallen waren de heersers niet inheems in de gebieden waarin hun bezittingen lagen. Soms spraken zij de lokale taal niet, of deden dat op een gebrekkige wijze met een zwaar accent. Maar het maakte weinig uit voor de banden van persoonlijke verplichting of een Spanjaard koning van Athene was of een Oostenrijker koning van Spanje.

### Corporatieve soevereiniteit

Soevereiniteit werd ook uitgeoefend door religieuze corporaties zoals de Tempeliers, de ridders van Sint-Jan en de Teutoonse ridders.[^106] Deze hybride instellingen hebben geen moderne tegenhangers. Zij combineerden religieuze, sociale, juridische en financiële activiteiten met soevereiniteit over lokale gebieden. Hoewel zij territoriale jurisdictie uitoefenden, waren zij vrijwel het tegenovergestelde van de overheden van vandaag, aangezien nationaliteit geen enkele rol speelde in het mobiliseren van hun aanhang of in hun bestuursstructuur. De leden en functionarissen van deze religieuze ordes kwamen uit alle delen van het christelijke Europa, of ‘Christendom’, zoals dat destijds werd genoemd.

Niemand vond het gepast of noodzakelijk dat de heersers uit de lokale bevolking moesten komen. Het mobiliseren van steun in het gefragmenteerde middeleeuwse bestuursmodel was niet afhankelijk van een nationale identiteit of plicht aan de staat, zoals tegenwoordig wel het geval is, maar van persoonlijke loyaliteit en traditionele banden die als kwestie van persoonlijke eer in ere moesten worden gehouden. Deze eden konden door iedereen, van overal, worden afgelegd, op voorwaarde dat men hem op basis van zijn sociale positie als waardig beschouwde.

### De eed

Ridderlijke eden bonden individuen met elkaar en werden afgelegd op de eer van de betrokkenen. Zoals Huizinga schreef: "Door een eed af te leggen, legden mensen zichzelf een zekere ontzegging op als aansporing tot het verrichten van de handelingen waartoe zij zich hadden verplicht."[^107] Er werd zoveel belang gehecht aan het nakomen van eden dat mensen vaak de dood riskeerden of ernstige consequenties ondervonden om te voorkomen dat zij hun eden braken. Vaak verplichtten de eden zelf de personen bepaalde handelingen te verrichten als kwestie van eer, handelingen die u en de meeste lezers van dit boek waarschijnlijk belachelijk zullen lijken.

Zo zwoeren bijvoorbeeld de Ridders van de Ster een eed dat zij zich nooit meer dan vier acres van het slagveld zouden verwijderen, waardoor spoedig daarna meer dan negentig van hen hun leven verloren.[^108] Het verbod op zelfs een tactische terugtrekking is als militaire strategie irrationeel, maar het was een gangbare verplichting in de ridderlijke eden. Vlak voor de Slag bij Agincourt gaf de Engelse koning de opdracht dat ridders tijdens patrouilles hun harnas moesten afleggen, omdat het in strijd zou zijn met hun eer om zich terug te trekken uit de vijandelijke linies als zij hun harnas zouden dragen. Het gebeurde dat de koning zelf de weg kwijtraakte en langs het dorp kwam dat als nachtverblijf had gediend voor de voorhoede van zijn leger. Doordat hij harnas droeg, verbood zijn ridderlijke eer hem om, nadat hij zijn vergissing ontdekte, van koers te veranderen en terug te keren naar het dorp. Hij bracht de nacht door in een blootgestelde positie.

Hoe belachelijk dit voorbeeld ook lijkt, koning Hendrik heeft waarschijnlijk niet verkeerd ingeschat dat hij meer risico zou lopen door zijn eer te schenden door zich terug te trekken – en daarmee een demoraliserend voorbeeld voor zijn hele leger te zetten – dan door achter vijandelijke linies te slapen.

De geschiedenis van de middeleeuwen staat vol met voorbeelden van vooraanstaande personen die beloftes nakwamen die ons belachelijk zouden lijken. In veel gevallen hielden de voorgestelde handelingen geen objectieve band in met enig voordeel, maar dienden zij als een levendige demonstratie van het belang dat de betrokkenen aan hun geloftes hechtten. Tot de veelvoorkomende geloftes behoorden onder meer het sluiten van één oog, het uitsluitend eten en drinken in staande positie en het doelbewust tot een zelfopgelegde kreupel worden door deel te nemen aan een eenpersoonskettingploeg. Er was een wijdverspreide gewoonte om pijnlijke voetijzers te dragen. Als je vandaag iemand op straat zou zien worstelen met een zwaar beenijzer, zou je hoogstwaarschijnlijk denken dat hij krankzinnig is, en niet dat hij een man van grote deugd is. Toch was het, in de context van de ridderlijkheid, een ereteken om zo'n hulpmiddel vrijwillig te dragen. En er waren vele vergelijkbare gebruiken die ons tegenwoordig even belachelijk zouden voorkomen. Zoals Huizinga het beschrijft, namen velen de belofte 'niet op zaterdag in een bed te slapen, niet op vrijdag dierlijk voedsel te nuttigen, enzovoort. De één daad van ascese stapelt zich op de andere: een edelman belooft geen harnas te dragen, één dag per week geen wijn te drinken, niet in een bed te slapen, niet aan tafel te zitten tijdens de maaltijden en een penitentiehemd te dragen.'[^109]

De vastentijd is bewaard gebleven als een veel gematigder vorm van dit zelfopgelegde ongemak.

Veel enthousiastelingen voor geloftes richtten ordes op die hun leden bijzondere ontberingen oplegden als een test van hun eer. De Orde van Clalois en Galoises kleedde zich bijvoorbeeld in de zomer in bont en bontgevoerde capuchons en stak een vuur in de haard, terwijl men in de winter slechts een eenvoudig jasje zonder bont mocht dragen – noch mantels, noch hoeden, noch handschoenen – en men had bovendien slechts zeer lichte bedkleding. Zoals Huizinga meldt: 'Het is niet verwonderlijk dat heel wat leden aan de kou zijn gestorven.'[^110]

> 'Middelvingse zelfkastijding was een grimmige marteling die mensen zichzelf toebrachten in de hoop een oordelende en bestraffende God ertoe te bewegen zijn staf opzij te zetten, hun zonden te vergeven en hen te behoeden voor de zwaardere straffen die anders hun deel zouden zijn in deze wereld en de volgende.'[^111] - NORMAN COHN

### Zelfkastijding, toen en nu

Het was een korte stap van de gelofte die gevaar en ontbering met zich meebracht naar beproevingen, pelgrimstochten, boetedoening, ongemak en zelfs doelbewust toegebrachte zelfverwonding. In de middeleeuwen werden deze handelingen als zeer nuttig en prijzenswaardig beschouwd. Zij waren uitingen van de ernst waarmee geloften werden nageleefd, een gedachtegang die zelfs tegenwoordig nog terug te vinden is bij inwijdingen in broederschappen of zusterschappen.

Het verstikkend in de zomer, het bevriezend in de winter of het op blote voeten deelnemen aan pelgrimstochten door de sneeuw bleek relatief mild vergeleken met de 'grimmige marteling' van zelfkastijding. Dit was een bijzonder middeleeuwse vorm van boetedoening die vrijwel gelijktijdig met het ontstaan van het feodalisme tot stand kwam. Het werd voor het eerst 'overgenomen door kluizenaars in de kloostergemeenschappen van Camaldoli en Fonte Avellana aan het begin van de elfde eeuw.'[^112]

In plaats van slechts op blote voeten in de kou te lopen, organiseerden de zelfkastijders processies waarbij zij dag en nacht van de ene stad naar de andere marcheerden. 'En elke keer wanneer zij een stad bereikten, schikten zij zich in groepen voor de kerk en sloegen zichzelf urenlang.'[^113]

Wij zijn ervan overtuigd dat mensen in de toekomst, wanneer zij terugkijken op het tijdperk van de natiestaat, sommige ondernemingen die in de twintigste eeuw in naam van het burgerschap werden uitgevoerd, net zo belachelijk zullen vinden als wij de zelfkastijding. Vanuit het perspectief van de informatiesamenleving zal het schouwspel van soldaten in de moderne tijd, die halverwege de wereld reizen om de dood uit te dagen uit loyaliteit aan de natiestaat, als grotesk en belachelijk worden gezien. Het zal niet ver verschillen van enkele van de bijzondere en overdreven rituelen van ridderlijkheid, zoals het rondlopen in beenijzers, waaraan anders verstandige mensen tijdens het feodale tijdperk met trots deelnamen.

### Ridderlijkheid maakt plaats voor burgerschap

De ridderlijkheid verdween en maakte plaats voor burgerschap, toen de megapolitieke omstandigheden veranderden en het militaire doel van de eed aan zijn heer verouderd raakte. De wereld van buskruitwapens en industriële legers bracht geheel andere verhoudingen met zich mee tussen de individuen die vochten en hun commandanten. Burgerschap ontstond op een moment dat de opbrengsten van geweld hoog waren en toenamen, terwijl de staat over veruit grotere middelen beschikte dan de maatschappelijke entiteiten die in de middeleeuwen oorlog voerden. Door haar enorme macht en rijkdom kon de natiestaat rechtstreeks een overeenkomst sluiten met de massa gewone soldaten die in haar uniform vochten.

Dergelijke overeenkomsten bleken voor de staat veel goedkoper en veel minder problematisch dan pogingen om militaire troepen bijeen te brengen door te onderhandelen met machtige heren en lokale grootheden, die allen in staat waren om eisen af te wijzen die in strijd waren met hun eigen belangen, iets wat geen enkele individuele burger in de natiestaat kon.

Om redenen die we later uitvoeriger behandelen, hing het burgerschap in belangrijke mate af van het feit dat geen enkel individu, noch een kleine groep individuen, megapolitiek in staat was om onafhankelijk militaire macht uit te oefenen. Naarmate informatietechnologie de logica van het gevecht verandert, zullen de mythen over het burgerschap onvermijdelijk verouderen, net zoals buskruit de middeleeuwse ridderlijkheid verouderd maakte.

### Hell's Angels te paard

De aristocratie van bereden krijgers die eeuwenlang West-Europa domineerden, waren allesbehalve de heren die hun nakomelingen later werden. Zij waren ruw en gewelddadig. In hedendaagse termen zouden zij beter te begrijpen zijn als het middeleeuwse equivalent van motorbendes. De omgangsetiquette en pretenties van ridderlijkheid dienden meer om hun excessen te beteugelen dan als een beschrijving van hun ware gedrag. Zelfs een encyclopedisch verslag van de regels en verplichtingen van de ridderlijkheid zou weinig tot niets onthullen over de grondslagen van de macht van de adel.

### Perfectie als synoniem voor uitputting

De opkomst van effectieve buskruitwapens aan het einde van de vijftiende eeuw veroorzaakte een krachtige schok onder hen – net toen gewapende ridders hun kunst als nooit tevoren hadden geperfectioneerd. Tegen die tijd had zorgvuldig fokken eindelijk geleid tot een oorlogspaard van zestien handen hoog, een ros met de gestalte om een gemonteerde ridder in volledige wapenuitrusting comfortabel te dragen. Toch, zoals C. Northcote Parkinson scherp opmerkte, wordt 'perfectie' bereikt door instellingen die op instorten staan.[^114] Net zozeer als het nieuwe oorlogspaard werd veredeld, werden nieuwe wapens ingezet om paard en ridder van het slagveld te blazen. Deze nieuwe buskruitwapens konden door gewone mensen worden afgevuurd. Ze vereisten weinig vaardigheid in gebruik, maar waren duur om in grote hoeveelheden aan te schaffen. Hun verspreiding vergrootte gestaag het belang van handel ten opzichte van landbouw, hetgeen tot dan toe de basis van de feodale economie was.

### Oorlog op grotere schaal

Hoe hebben buskruitwapens zo'n transformatie teweeggebracht? Ten eerste vergrootten ze de schaal van de gevechten, waardoor het voeren van oorlog al snel veel kostbaarder werd dan in de middeleeuwse periode. Vóór de buskruitrevolutie werden oorlogen doorgaans uitgevochten door zodanig kleine groepen dat ze konden worden opgeroepen uit een klein en arm grondgebied. Buskruit bood een nieuw voordeel bij gevechten op grotere schaal. Alleen leiders met aanspraken op welvarende onderdanen konden zich veroorloven om effectieve strijdkrachten op te voeren onder de nieuwe omstandigheden. Leiders die de groei van de handel het beste omarmden – meestal monarchen die zich allieerden met de stedelijke kooplieden – ontdekten dat zij op het slagveld een concurrentievoordeel genoten. In de woorden van van Creveld: 'Dankzij, deels, de superieure financiële middelen die tot hun beschikking stonden, konden zij meer kanonnen aanschaffen dan wie dan ook en de tegenstand in stukken blazen.'[^115]

Hoewel het nog eeuwen zou duren voordat de volledige potentie van buskruitwapens losgelaten zou worden in de burgerlegeren van de Franse Revolutie, wees een vroeg teken van de transformatie van de oorlogsvoering door buskruit zich af in de invoering van militaire uniformen tijdens de renaissance. Deze uniformen symboliseren treffend de nieuwe verhoudingen tussen de krijger en de natiestaat, die hand in hand gingen met de overgang van ridderlijkheid naar burgerschap. In wezen sloot de nieuwe natiestaat een uniforme overeenkomst met haar burgers, in tegenstelling tot de bijzondere, uiteenlopende overeenkomsten die de monarch of de paus met een lange keten van vazallen onder het feodale systeem sloot. In het oude systeem had iedereen een andere plaats in een architectonische hiërarchie. Iedereen bezat een overeenkomst die net zo uniek was als zijn familiewapen en de kleurrijke vaandels die hij voerde.

### Het verlagen van de alternatieve kosten van rijkdom

Buskruitwapens hebben op nog een andere manier de aard van de samenleving radicaal veranderd. Ze scheidden het uitoefenen van macht van fysieke kracht, waardoor de alternatieve kosten van commerciële activiteiten werden verlaagd. Rijke kooplieden hoefden niet langer te vertrouwen op hun eigen behendigheid en kracht in hand-tot-handgevechten, noch op huurlingen met twijfelachtige loyaliteit om zich te verdedigen. Ze konden hopen verdedigd te worden door de nieuwe, grotere legers van de grote vorsten. Zoals William Playfair over de middeleeuwen zei, "Zolang fysieke kracht de macht was waarmee men bij vijandigheid werd geconfronteerd, ... [t]erwijl het toen onmogelijk was om langdurig zowel rijk als machtig te zijn."[^116] Toen het buskruit opkwam, was het onmogelijk machtig te zijn zonder rijk te zijn.

### Status en statisch begrip

Om dezelfde redenen waarvoor de meeste mensen tegenwoordig niet goed voorbereid zijn op de nieuwe dynamiek van de informatiemaatschappij, waren de vooraanstaande denkers van de middeleeuwse samenleving niet in staat de opkomst van de handel, die zo'n belangrijke rol speelde in het vormgeven van de moderne periode, te voorzien of te begrijpen. De meeste mensen vijf eeuwen geleden bekeken hun veranderende samenleving in statische termen. Zoals Huizinga zei, "Zeer weinig eigendom is in de moderne zin liquide, terwijl macht nog niet hoofdzakelijk met geld wordt geassocieerd; het is nog eerder inherent aan de persoon en berust op een soort religieus ontzag dat hij inboezemt; het komt tot uiting in praal en grootsheid, of in een talrijke stoet van trouwe volgelingen. Feodaal of hiërarchisch denken drukt het idee van grootsheid uit door zichtbare tekenen...."[^117]

Omdat mensen in de late middeleeuwen in de eerste plaats aan status dachten, waren zij niet in staat te begrijpen dat kooplieden mogelijk iets belangrijks konden bijdragen aan het leven van het rijk. Bijna altijd behoorden kooplieden tot de onderste laag van de drie standen, onder de adel en de geestelijkheid.

Zelfs de scherpzinnigste denkers van de late middeleeuwse samenleving slaagden er niet in het belang van de handel en andere vormen van ondernemerschap buiten de landbouw voor het vergaren van rijkdom te waarderen. Voor hen was armoede een apostolische deugd. Ze maakten letterlijk geen onderscheid tussen een rijke bankier en een bedelaar. In de woorden van Huizinga, "Er werd in de derde stand in principe geen onderscheid gemaakt tussen rijke en arme burgers, noch tussen stadsbewoners en plattelandsmensen."[^118] Noch beroep noch rijkdom deden er in hun opvatting toe, enkel de ridderlijke status.

Deze blindheid voor de economische dimensie van het leven werd versterkt door geestelijken, de ideologische hoeders van het middeleeuwse leven. Zij begrepen het belang van handel zo nauwelijks dat een breed geprezen hervormingsprogramma uit de vijftiende eeuw voorstelde dat alle personen van niet-adellijke status zich uitsluitend moesten wijden aan ambachtswerk of landbouwarbeid. Voor de handel werd echter helemaal geen rol voorzien.[^119]

> 'De datum 1492, die conventioneel wordt gebruikt om de middeleeuwen van de moderne geschiedenis te scheiden, is net zozeer een geschikt breukpunt als elk ander, want in het perspectief van de wereldgeschiedenis symboliseert Columbus’ reis het begin van een nieuwe relatie tussen West-Europa en de rest van de wereld.'[^120] - FREDERIC C. LANE

## DE GEBOORTE VAN HET INDUSTRIËLE TIJDPERK

Veel van de scherpzinnigste geesten van de vijftiende eeuw misten volledig een van de belangrijkste ontwikkelingen in de geschiedenis, een ontwikkeling die midden onder hun ogen begon. De ondergang van het feodalisme markeerde het begin van de grote moderne fase van Westerse overheersing. Het was een periode van toenemende beloningen voor geweld en een groeiende schaal in ondernemerschap. In de afgelopen tweeënhalf eeuwen heeft de moderne economie een ongeëvenaarde stijging van de levensstandaarden gerealiseerd voor dat deel van de wereld dat er het meest van profiteerde. De drijvende krachten achter deze veranderingen waren nieuwe technologieën, van buskruitwapens tot de drukpers, die de grenzen van het leven op manieren veranderden die maar weinigen konden bevatten.

Tegen het einde van de vijftiende eeuw begonnen ontdekkingsreizigers zoals Columbus net de toegangswegen naar immense, onbekende continenten te openen. Voor het eerst in de onherinnerde tijden van de mensheid werden alle uithoeken van de wereld bereikt. Galeons, nieuwe hooggemaste improvisaties op mediterrane galeien, zeilden de wereld rond en kaartten de doorgangen uit die uitgroeiden tot handelsroutes en hoofdwegen voor ziekte en verovering. Conquistadores, die hun nieuwe bronzen kanonnen zowel op zee als aan wal hanteerden, openden nieuwe horizonten. Zij vonden fortuinen in goud en specerijen, legden de basis voor nieuwe winstgewassen – van tabak tot aardappelen – en reserveerden nieuwe weidegronden voor hun vee.

### De eerste industriële technologie

Net zoals het kanon nieuwe economische horizonten opende, opende de boekdrukkunst nieuwe intellectuele horizonten. Het was de eerste massaproductiemachine, een kenmerkende technologie die het begin van het industrialisme markeerde. Hiermee delen we de opvatting die Adam Smith in The Wealth of Nations uiteenzette, namelijk dat de industriële revolutie al had plaatsgevonden lang voordat hij schreef. Het had weliswaar nog niet zijn volwassenheid bereikt, maar de principes van massaproductie en het fabrieksysteem waren al goed verankerd. Zijn beroemde voorbeeld van de speldfabrikanten maakt dit duidelijk. Smith legt uit hoe achttien afzonderlijke handelingen worden toegepast om speldjes te produceren. Door de gespecialiseerde technologie en arbeidsdeling kon iedere werknemer 4.800 keer zoveel speldjes in één dag maken als een individu op eigen kracht zou kunnen vervaardigen.[^121]

Smiths voorbeeld benadrukt dat de industriële revolutie eeuwen eerder begon dan historici conventioneel aannemen. De meeste leerboeken dateren de oorsprong ervan op het midden van de achttiende eeuw. Dat is niet onredelijk als datum voor de opstapfase in de verbetering van levensstandaarden. Maar de daadwerkelijke megapolitieke overgang van het feodalisme naar het industrialisme begon veel eerder, aan het einde van de vijftiende eeuw. De impact daarvan was vrijwel onmiddellijk merkbaar in de transformatie van de dominante instituties, met name in het vervagen van de middeleeuwse kerk.

De historici die de industriële revolutie later plaatsen, meten eigenlijk iets anders, namelijk de opstap in de levensstandaarden die te danken is aan massaproductie die door motoren werd aangedreven. Dit verhoogde de waarde van ongeschoolde arbeid en leidde tot dalende prijzen voor een breed scala aan consumptiegoederen. Inderdaad, het feit dat de levensstandaarden in verschillende landen op uiteenlopende tijdstippen scherp begonnen te stijgen, wijst erop dat er meer wordt gemeten dan de megapolitieke overgang. De Cambridge Economic History of Europe spreekt over 'industriële revoluties' in het meervoud, waarbij deze expliciet worden gekoppeld aan de gestage groei van nationale inkomens.[^122] In Japan en Rusland werd die inkomensstijging pas aan het einde van de negentiende eeuw gevoeld. De stijging van de levensstandaarden en de gestage groei van het nationale inkomen in andere delen van Azië en in sommige delen van Afrika bleek een fenomeen van de twintigste eeuw te zijn. In sommige delen van Afrika blijft gestage groei tot op de dag van vandaag een droom. Maar dat betekent niet dat deze regio’s niet in het moderne tijdperk leven.

### Daling van het inkomen in de transitie

De groei van het inkomen is niet synoniem met de komst van het industrialisme. De omschakeling naar een industriële samenleving was een megapolitiek evenement dat niet direct in inkomensstatistieken meetbaar is. Inderdaad, het reële inkomen van de meeste Europeanen daalde gedurende de eerste twee eeuwen van het industriële tijdperk. Pas na het begin van de achttiende eeuw begon het te stijgen en bereikte het rond 1750 weer de niveaus van 1250. Wij plaatsen de start van het industriële tijdperk aan het einde van de vijftiende eeuw. Het waren de industriële kenmerken van de vroegmoderne technologie, waaronder chemisch aangedreven wapens en drukpersen, die de ineenstorting van het feodalisme bespoedigden.

### Verlaging van de kosten van kennis

De mogelijkheid om boeken massaal te produceren was enorm ondermijnend voor middeleeuwse instellingen, net zoals microtechnologie subversief zal blijken voor de moderne natiestaat. De opkomst van de drukpers verzwakte rap het monopolie van de Kerk op het Woord van God, terwijl er tegelijkertijd een nieuwe markt voor ketterij ontstond. Ideeën die vijandig stonden tegenover de gesloten feodale samenleving verspreidden zich in hoog tempo, want in de laatste tien jaar van de vijftiende eeuw werden er 10 miljoen boeken gepubliceerd. Omdat de Kerk trachtte de drukpers te onderdrukken, werden de meeste nieuwe werken uitgegeven in die delen van Europa waar de macht van de gevestigde autoriteiten het zwakst was. Dit kan gezien worden als een nauwkeurige analogie met de hedendaagse pogingen van de Amerikaanse overheid om encryptietechnologie te onderdrukken. De Kerk ontdekte dat censuur de verspreiding van subversieve technologie niet kon voorkomen; het zorgde er slechts voor dat deze op de meest subversieve wijze werd aangewend.

### Waardevermindering van de kloosters

Veel schijnbaar onschuldige toepassingen van de drukpers bleken subversief vanwege hun inhoud. Het louter verspreiden van kennis over de fortuinen die onverschrokken avonturiers en kooplieden konden vergaren, was op zichzelf al een krachtig oplosmiddel dat de banden van feodale verplichtingen verbrak. De verleiding van nieuwe markten, samen met de behoefte en mogelijkheid om op grote schaal legers en vloten te financieren, gaf geld een waarde die het in de feodale eeuwen ontbrak. Deze nieuwe investeringsmogelijkheden, versterkt door krachtige wapens die de opbrengsten van geweld verhoogden, maakten het voor de heer in het achterland of de koopman in de stad steeds kostbaarder om zijn kapitaal aan de Kerk te schenken. Daarmee destabiliseerde het ontstaan van investeringskansen buiten landeigendommen de instellingen van het feodalisme en ondermijnde het diens ideologie.

Een andere subversieve consequentie van de boekdrukkunst was dat de kosten voor het reproduceren van informatie drastisch werden verlaagd. Een cruciale reden dat geletterdheid en economische vooruitgang in de middeleeuwen zo minimaal waren, was de hoge kostprijs van het met de hand dupliceren van manuscripten. Zoals we hebben gezien, was een van de belangrijkste productieve functies die de Kerk op zich nam na de val van Rome het reproduceren van boeken en manuscripten in benedictijnse kloosters. Dit was een uiterst kostbare onderneming. Een van de dramatischere gevolgen van de boekdrukkunst was dat de scriptoria, waar monniken dag na dag en maand na maand manuscripten vervaardigden die vervolgens binnen enkele uren door drukpersen gedupliceerd konden worden, in waarde daalden. De nieuwe technologie maakte het benedictijnse scriptorium tot een achterhaalde en kostbare methode om kennis te reproduceren, waardoor de religieuze orden en de Kerk die de kopisten steunden minder economisch belangrijk werden.

De massaproductie van boeken beëindigde het monopolie van de Kerk op de Schrift én op andere vormen van informatie. Door de bredere beschikbaarheid van boeken daalden de kosten van geletterdheid, wat het aantal denkers vermenigvuldigde dat in staat was om eigen meningen te geven over belangrijke onderwerpen, in het bijzonder theologische vraagstukken. Zoals de theologische historicus Euan Cameron opmerkte, legde ‘een reeks publicatiemijlpalen’ in de eerste twee decennia van de zestiende eeuw de basis voor de toepassing van ‘moderne tekstkritiek op de Schriften.’[^123] Dit ‘dreigde het monopolie’ van de Kerk te ondermijnen ‘door corrupte interpretaties van teksten in twijfel te trekken die gebruikt waren om traditionele dogma’s te ondersteunen.’[^124] Deze nieuwe kennis stimuleerde de opkomst van concurrerende protestantse sekten die hun eigen interpretaties van de Bijbel wilden formuleren. De massaproductie van boeken verlaagde de kosten van ketterij en bood de ketters een groot lezerspubliek.

Publicatie droeg ook bij aan de ondergang van de middeleeuwse wereldbeschouwing. De grotere beschikbaarheid en lagere kosten voor informatie leidden tot een verschuiving weg van een wereldbeeld dat verbonden was door symboliek in plaats van door causale verbanden. ‘Het wereldbeeld van de symboliek kenmerkt zich door een onberispelijke orde, een architectonische structuur en een hiërarchische ondergeschiktheid. Elke symbolische verbinding impliceert een verschil in rang of heiligheid… De walnoot symboliseert Christus; de zoete pit is Zijn goddelijke natuur, de groene en zachte buitenhuid staat voor Zijn menselijkheid en de houten schaal ertussen vertegenwoordigt het kruis. Zo tillen alle dingen de gedachten op naar het eeuwige…’[^125]

Een symbolische denkwijze vulde niet alleen een hiërarchisch gestructureerde samenleving aan, maar paste ook bij analfabetisme. Ideeën die via symbolen in houtsneden werden overgebracht, waren toegankelijk voor een analfabetische bevolking. Daarentegen leidde de opkomst van de boekdrukkunst in de moderne tijd tot de ontwikkeling van causale verbanden en het gebruik van de wetenschappelijke methode voor een geletterde bevolking.

## Een parallel voor vandaag

Middeleeuwse samenleving, schijnbaar zo stabiel en zeker in haar overtuigingen midden in de vijftiende eeuw, werd razendsnel getransformeerd. Haar voornaamste instelling, de Kerk, zag haar monopolie uitgedaagd en verbrijzeld worden. Autoriteit, die eeuwenlang onbetwist was geweest, werd plots ter discussie gesteld. Overtuigingen en loyaliteiten, die heiliger waren dan die welke een burger vandaag met een natiestaat verbinden, werden binnen enkele jaren heroverwogen en opgegeven – allemaal door een technologische revolutie die in het laatste decennium van de vijftiende eeuw tot volle bloei kwam.

Wij geloven dat een verandering zo dramatisch als die van vijfhonderd jaar geleden opnieuw zal plaatsvinden. De informatierrevolutie zal het machtsmonopolie van de natiestaat vernietigen, net zo zeker als de buskruitrevolutie het monopolie van de Kerk afschafte. Er is een opvallende analogie tussen de situatie aan het eind van de vijftiende eeuw, toen het leven volledig doordrenkt was met georganiseerde religie, en die van vandaag, waarin de wereld verzadigd is met politiek. De Kerk van toen en de natiestaat van nu zijn beide voorbeelden van instellingen die tot een seniele extremiteit zijn gegroeid. Net als de laatmiddeleeuwse Kerk is de natiestaat aan het eind van de twintigste eeuw een zwaar schuldbelaste instelling die zichzelf niet langer kan bekostigen. Haar functioneren is steeds minder relevant en zelfs contraproductief voor de welvaart van degenen die tot voor kort nog haar meest fervente aanhangers waren.

### Verarmd, gretig en extravagant

Net zoals de overheid vandaag weinig waar voor haar geld biedt, deed de Kerk aan het eind van de vijftiende eeuw dat eveneens. Zoals de kerkelijke historicus Euan Cameron opmerkte, “[E]en verarmd lokaal priesterschap leek weinig dienst te bewijzen voor het geld dat erom gevraagd werd; veel van hetgeen werd geheven ‘verdween’ effectief in afgesloten kloosters of in de obscure gebieden van hoger onderwijs en administratie. Ondanks de gul gegeven giften aan bepaalde sectoren van de Kerk slaagde de instelling als geheel erin er tegelijkertijd verarmd, gretig en extravagant uit te zien.”[^126] Het valt moeilijk de parallel met de overheid van de late twintigste eeuw te ontkennen.

Religieuze vieringen in de late vijftiende eeuw groeiden als programma’s die zich tegenwoordig in welvaartsstaten vermenigvuldigen. Niet alleen namen speciale zegeningen eindeloos toe, samen met de voorziening van heiligen en de botten van heiligen, maar elk jaar waren er meer kerken, meer nonnenkloosters, meer abdijen, meer kloosters van broeders, meer biechtvaders (inwonende huispriesters), meer predikantschappen, meer kathedraalkapitels, meer gestifte gebedshuizen, meer reliekvereringen, meer religieuze confraterniteiten, meer religieuze feesten en nieuwe heilige dagen. De diensten werden langer. Gebeden en hymnen werden ingewikkelder. De één na de ander verschenen er nieuwe bedelorders om aalmoezen te vragen. Het resultaat was een institutionele overbelasting, vergelijkbaar met die welke kenmerkend is voor sterk gepolitiseerde samenlevingen van tegenwoordig.

Religieuze festivals en feestdagen vermeerderden zich aan alle kanten. De religieuze diensten namen toe, met speciale festiviteiten ter ere van de zeven smarten van Maria, van haar zusters en van alle heiligen in de afstamming van Jezus.[^127] Het nakomen van de religieuze verplichtingen werd voor de gelovigen steeds kostbaarder en zwaarder, net zoals tegenwoordig de kosten om binnen de wet te blijven zijn toegenomen.

### De onschuldigen betalen

Toen, net als nu, droeg de productieve klasse een groeiende last van inkomensherverdeling. Deze kosten stegen veel sneller dan de machthebbers erkenden, als gevolg van een verschuiving in het gebruik van kapitaal. Het relatieve voordeel van het bezitten van land ten opzichte van geldkapitaal nam af. Toch bleef de middeleeuwse geest denken in termen van een statusgebonden samenleving, waarin de sociale positie werd bepaald door wie je was in plaats van door je vaardigheid in het effectief inzetten van kapitaal. Er werd weinig tot geen rekening gehouden met de stijgende opportuniteitskosten van het organiseren van overdreven religieuze plechtigheden. Deze kosten troffen in het bijzonder de meer ambitieuze en hardwerkende boeren, burghers en vrije boeren, die meer dan de aristocratie afhankelijk waren van een efficiënt gebruik van hun kapitaal. Zij waren verplicht om een onevenredig deel van de kosten te dragen voor het dekken van de tafels tijdens de eindeloze feesten en heilige dagen (feestdagen), alsmede voor het ondersteunen van een buitensporige kerkelijke bureaucratie.

### Contraproductieve regelgeving

Aan het einde van de vijftiende eeuw had de Kerk grotendeels de regulerende bevoegdheden in handen die later door de overheden werden overgenomen. De Kerk domineerde belangrijke rechtsgebieden: het vastleggen van akten, het registreren van huwelijken, het afhandelen van testamenten, het verlenen van handelslicenties, het toekennen van landtitels en het vaststellen van de voorwaarden voor het handelsverkeer. De details van het leven waren vrijwel net zo grondig geregeld door het canonieke recht als tegenwoordig door de bureaucratie, en met min of meer hetzelfde doel. Net zoals politieke regelgeving tegenwoordig doorspekt is met verwarringen en tegenstrijdigheden, zo was het canonieke recht vijfhonderd jaar geleden. Deze regelgeving onderdrukte en bemoeilijkte vaak het handelsverkeer op zodanige wijze dat duidelijk werd dat het bevorderen van de productiviteit ver af stond van de belangen van de regelgevers.

Bijvoorbeeld, het was verboden om een heel jaar lang zaken te doen op de dag van de week waarop de meest recente 28 december viel. Dus als deze dag op een dinsdag viel, mocht er op dinsdag geen legale handel worden bedreven als een verplichte uiting van vroomheid ter ere van de Slachting der Onschuldigen. In jaren waarin 28 december op een andere dag dan zondag viel, belemmerde dit verbod het potentieel voor veel vormen van handel, waardoor de kosten stegen door transacties uit te stellen of zelfs geheel te voorkomen.

### Monopoly Pricing

Ook werd het kanonieke recht opgelegd om de monopolistische prijsstelling te ondersteunen. De Kerk verkreeg aanzienlijke inkomsten uit de verkoop van aluin, gewonnen uit haar eigendommen in Tolfa, Italië. Toen sommige klanten in de textielindustrie de voorkeur gaven aan goedkoper aluin, geïmporteerd uit Turkije, trachtte het Vaticaan zijn monopolistische prijzen te handhaven via het kanonieke recht door het gebruik van het goedkopere aluin als zondig te verklaren. Handelaars die volhielden in de aankoop van het goedkopere Turkse product, werden excommuniceerd. Het beroemde verbod op het eten van vlees op vrijdag is in dezelfde geest ontstaan. De Kerk was niet alleen de grootste feodale landeigenaar; zij bezat ook belangrijke visgronden. Kerkvaders ontdekten een theologische noodzaak voor de vrome om vis te eten, hetgeen, niet bij toeval, de vraag naar hun product garandeerde in een periode waarin transport- en sanitaire omstandigheden de consumptie van vis ontmoedigden.

Net als de hedendaagse natiestaat reguleerde de laatmiddeleeuwse Kerk niet alleen specifieke industrieën om direct haar eigen belangen te dienen; zij maakte ook optimaal gebruik van haar regulerende bevoegdheden om op andere manieren inkomsten te genereren. Geestelijken deden er alles aan om voorschriften en edicten uit te vaardigen die moeilijk na te leven waren. Zo werd incest in zeer ruime zin gedefinieerd, waardoor zelfs verre neven en nichten en personen die enkel door huwelijk verwant waren, een bijzondere dispensatie van de Kerk nodig hadden om te kunnen trouwen. Aangezien dit bijna iedereen in vele kleine Europese dorpen vóór de moderne reisperiode omvatte, groeide de verkoop van vrijstellingen voor incestueuze huwelijken uit tot een bloeiende bron van inkomsten voor de Kerk. Zelfs de seks binnen het huwelijk werd streng gereguleerd door kerkelijke voorschriften. Seksuele betrekkingen tussen echtgenoten waren verboden op zondagen, woensdagen en vrijdagen, alsmede gedurende veertig dagen voorafgaand aan Pasen en Kerstmis. Bovendien dienden stellen drie dagen vóór het ontvangen van de communie van seks af te zien. Met andere woorden, gehuwde stellen mochten geen seks hebben zonder dat zij een indulgentie hadden verkregen, waarbij die indulgentie gold voor ten minste 55 procent van de dagen in het jaar. In *The Bishop’s Brothels* suggereert historicus E. J. Burford dat deze 'idioot' lijkende huwelijksvoorschriften hebben bijgedragen aan de groei van de middeleeuwse prostitutie, waaruit de Kerk aanzienlijk profiteerde.[^128] Burford meldt dat de bisschop van Winchester gedurende vele eeuwen de belangrijkste eigenaar was van de bordelen aan Bankside in Londen, Southwark. Bovendien was het kerkelijke winstbejag uit prostitutie geenszins louter een lokaal Engels fenomeen:

> Paus Sixtus IV (ca. 1471), die naar verluidt syfilis opliep van een van zijn vele minnaressen, werd de eerste paus die licenties aan prostituees uitgaf en een belasting op hun inkomsten instelde, waarmee de pauselijke inkomsten aanzienlijk werden vergroot. Inderdaad, de Romeinse Curia financierde gedeeltelijk de bouw van Sint-Pieters met deze belasting en de verkoop van licenties. Zijn opvolger, paus Leo X, zou naar verluidt ongeveer tweeëntwintigduizend gouden ducats hebben verdiend met de verkoop van licenties, vier keer zoveel als hij verdiende met de verkoop van aflaten in Duitsland.[^129]

Zelfs de beroemde regel van celibaat die aan priesters werd opgelegd, was een lucratieve bron van inkomsten voor de middeleeuwse kerk. Zoals Burford rapporteert, voerde de kerk een 'racket bekend als cullagium' in, een heffing die werd opgelegd aan 'concubinaire priesters.'[^130] Dit bleek zo winstgevend dat het uniform werd opgelegd aan alle priesters door bisschoppen in Frankrijk en Duitsland, ondanks het feit dat het lateraankonsil in 1215 dit 'schandelijke verkeer, waarbij dergelijke prelaten regelmatig toestemming tot zonde verkochten' had veroordeeld.[^131] Het was slechts een van de vele lucratieve markten voor de verkoop van licenties om het kanonieke recht en de regels te overtreden, een handel die werd gedreven door dezelfde logica die hebzuchtige politici ertoe aanzet om willekeurige reguleringsbevoegdheden over de handel na te streven.

### aflaatbrieven

De bevoegdheid om willekeurig te reguleren is tevens de bevoegdheid om een vrijstelling te verkopen voor de schade die dergelijke regelgeving kan veroorzaken. De kerk verkocht vergunningen, of 'aflaatbrieven', die alles autoriseerden, van verlichting van kleine lasten op de handel tot toestemming om tijdens de vastentijd zuivelproducten te consumeren. Deze 'aflaatbrieven' werden niet alleen tegen hoge prijzen verkocht aan de aristocratie en de rijke burgerij; ze werden ook als loterijprijzen verpakt, vergelijkbaar met de door de overheid georganiseerde loterijen van tegenwoordig, om de centen van de armen aan te trekken.[^132] De handel in aflaatbrieven nam toe naarmate de uitgaven van de kerk de inkomsten overtroffen. Dit bracht velen ertoe om tot de voor de hand liggende conclusie te komen dat de institutionele kerk haar macht hoofdzakelijk gebruikte om inkomsten te genereren. Zoals een hedendaagse criticus het verwoordde: '[C]anoniek recht werd uitsluitend ingesteld met het doel om een hoop geld te verdienen; wie christen wil zijn, moet zich uitkopen.'[^133]

### bureaucratische overbelasting

De kosten voor het in stand houden van een geïnstitutionaliseerde religie aan het einde van de vijftiende eeuw hadden een historisch hoogtepunt bereikt, net zoals de kosten voor het in stand houden van de overheid tegenwoordig een seniele extreme hebben bereikt. Hoe meer het leven doordrenkt was met religie, des te duurder en bureaucratischer werd de kerk. In de woorden van Cameron: 'Het was veel gemakkelijker om mensen te vinden om de enorm toegenomen posities binnen de kerk aan het einde van de middeleeuwen in te vullen, dan om geld te vinden om hen te betalen.'[^134] Net zoals failliete overheden vandaag op contraproductieve wijze naar inkomsten scharen, deed de kerk dat vijfhonderd jaar geleden ook. Inderdaad, de geestelijken maakten gebruik van enkele van dezelfde roofzuchtige trucs die hedendaagse politici hebben geperfectioneerd.

De middeleeuwse kerk vijfhonderd jaar geleden verbruikte, net als de natiestaat van vandaag, meer van de middelen van de samenleving dan ooit tevoren – en meer dan ooit nog zou doen. Destijds leek de kerk, net als de staat van tegenwoordig, niet in staat te zijn te functioneren en zichzelf in stand te houden, zelfs niet met recordinkomsten. Net zoals de staat de laat-industriële economieën heeft gedomineerd, waarbij in sommige West-Europese landen meer dan de helft van alle inkomsten werd besteed, domineerde de kerk de laat-feodale economie, waarbij zij middelen wegzapte en de groei belemmerde.

### Deficituitgaven in de vijftiende eeuw

De kerk deed er alles aan om met alle denkbare middelen meer geld uit haar volgelingen te persen, zodat haar opgeblazen bureaucratie gevoed kon worden. Regio’s die rechtstreeks onder het gezag van de kerk vielen, moesten steeds hogere belastingen betalen. In provincies en koninkrijken waar de kerk niet over een directe belastingbevoegdheid beschikte, legde het Vaticaan de zogeheten “annaten” op – een betaling die door de lokale vorst in plaats van directe kerkelijke belastingen diende te worden voldaan.

Net als de staat van tegenwoordig plunderde de kerk bovendien haar eigen schatkisten, door fondsen die waren bestemd voor specifieke doeleinden af te leiden om de algemene vaste lasten te dekken. Kerkelijke benefices en koopzuchtige religieuze ambten werden openlijk verkocht, evenals de inkomststromen uit de tienden. In feite werden de vorderingen op de tienden het kerkelijke equivalent van obligaties die door moderne regeringen worden uitgegeven om hun chronische tekorten te financieren.

Terwijl de kerk de ideologische verdediger was van het feodalisme en een felle criticus van handel en kapitalisme, maakte zij – net als de natiestaat van tegenwoordig – gebruik van elke beschikbare marketingtechniek om haar eigen inkomsten te optimaliseren. De kerk runde een bloeiende handel in de verkoop van sacramentelen, waaronder gewijde kaarsen, palmtakken gezegend op Palmzondag, kruiden die gezegend werden op het feest van de tenhemelopneming en vooral de diverse soorten heilig water.[^135]

Net zoals de politici van tegenwoordig hun kiezers bedreigen met ingeperkte afvalophaling en andere onwaardigheden als zij weigeren hogere belastingen te betalen, waren religieuze autoriteiten in de vijftiende eeuw evenzeer geneigd om de erediensten stil te leggen en zo gemeenten te chanteren om willekeurige boetes te voldoen. Vaak werden deze boetes opgelegd voor een kleine overtreding begaan door enkelen, die zelfs geen lid hoefden te zijn van de betreffende gemeenschap. Zo sloot bijvoorbeeld in 1436 bisschop Jacques Du Chatelier, 'een zeer opzichtig, hebzuchtige man', de Kerk der Onschuldigen in Parijs gedurende tweeëntwintig dagen, waarmee hij alle religieuze diensten stopzette terwijl hij wachtte op een onvoorstelbaar hoge boete die door twee bedelaars betaald diende te worden. De mannen hadden in de kerk ruzie gemaakt en een paar druppels bloed vergoten, waarvan de bisschop beweerde dat deze de kerk gedeconsecreerd hadden. Hij verbood dan ook dat iemand de kerk gebruikte voor huwelijken, begrafenissen of de gewone sacramenten, totdat zijn boete was voldaan.[^136]

> De Italiaanse beheerders (om de paus in een goed humeur te brengen)\
> betaalden twintigduizend ducatten in één jaar.\
> Bovendien geven zij een priester (om zijn honorarium te verhogen)\
> de winst van een hoer, of twee of drie...\
> Ik denk dat hij wel goddelijk moet zijn\
> dat hij met de beheerders zo'n affiniteit heeft.[^137]

 
– vijftiende-eeuwse Engelse ballade

### Haat jegens kerkelijke leiders

Het is dan ook niet verwonderlijk dat de algemene mening in de late vijftiende eeuw zowel de hogere als de lagere geestelijkheid verachtte, net zoals in sterk gepolitiseerde samenlevingen tegenwoordig de bureaucratie en politici het mikpunt van verachting zijn. Zoals Johan Huizinga het verwoordde: 'Haat is het juiste woord in deze context, want haat was er – latent, maar algemeen en hardnekkig. Het volk raakte nooit moe van het horen aan de kaak stellen van de ondeugden van de geestelijkheid.'[^138] Een van de redenen waarom men er algemeen van overtuigd was dat de kerk 'hebzuchtig en extravagant' was, is dat dit ook waar bleek te zijn. 'De wereldlijkheid van de hogere geestelijkheid en de verslechtering van de lagere geestelijkheid' waren immers niet te negeren.[^139] Van de parochiepriester tot de paus zelf leek de geestelijkheid corrupt, zoals alleen het personeel van een dominante instelling dat kan zijn.

Vijfhonderd jaar geleden liet paus Alexander VI zelfs Giuho Andreotti en Bill Clinton als toonbeelden van integriteit lijken. Alexander VI stond bekend om zijn uitbundige feestjes. Als kardinaal in Siena organiseerde hij een beroemde orgie waartoe alleen 'de mooiste jonge vrouwen van Siena' waren uitgenodigd, terwijl hun 'echtgenoten, vaders en broers' waren uitgesloten.[^140] De orgie in Siena was beroemd, maar bleek later tam in vergelijking met de feestjes die Alexander organiseerde nadat hij paus was geworden. Misschien was de meest opzienbarende daarvan het zogenaamde Kastanjeballet, waarbij de 'vijftig mooiste hoeren' van Rome deelnamen aan een copulatie-wedstrijd met de kerkvaders en andere invloedrijke Romeinen. Zoals William Manchester het beschrijft: 'Dienstmannen hielden de telling bij van de orgasmes van elke man, want de paus had een groot respect voor viriliteit... Nadat iedereen uitgeput was, deelde Zijn Heiligheid prijzen uit – mantels, laarzen, petten en fijne zijden tunieken. De winnaars, schreef de diarist, waren degenen die het grootste aantal malen liefde bedreven met die courtisanen.'[^141]

Alexander verwekte minstens zeven en mogelijk acht buitenechtelijke kinderen. Een van zijn schijnbare zonen, Giovanni, was de zogenoemde Infans Romanus, geboren uit de buitenechtelijke dochter van Alexander, Lucrezia Borgia, toen zij achttien was. In een geheime pauselijke bul erkende Alexander dat hij de vader van Giovanni was. Als hij niet de vader was, dan was hij zeker de grootvader aan beide zijden. De paus was verwikkeld in een drielinkige incestueuze affaire met Lucrezia, die tevens de minnares was van Juan, hertog van Gandia, de oudste buitenechtelijke zoon van Alexander, alsook de minnares van een andere buitenechtelijke zoon, kardinaal Cesare Borgia. Cesare was de ‘prins van de kerk’ die als inspiratie diende voor Niccolò Machiavelli’s The Prince. Cesare was een moordenaar, zoals ook de paus, die erom bekendstond meerdere moorden te hebben beraamd. Een van hen schijnt jaloers geworden te zijn op Juan, wiens levenloze lichaam op 15 juni 1497 uit de Tiber werd teruggevonden.[^142]

Het leiderschap van de laatmiddeleeuwse kerk was net zo corrupt als het leiderschap van de natiestaat van vandaag.

> 'Vandaag ben ik twee keer vader geworden, Gods zegen daarbij.'[^143] - Rodolph Acricola, toen hij hoorde dat zijn minnares op de dag van zijn verkiezing tot abt een zoon had gebaard.

## Hypocrisie

Onder een 'oppervlakkige korst van vroomheid' was de laatmiddeleeuwse samenleving opmerkelijk blasfemisch, oneerbiedig en losbandig. Kerken waren de favoriete ontmoetingsplaatsen voor jonge mannen en vrouwen en fungeerden tegelijkertijd als verzamelplekken voor prostituees en verkopers van obsceene afbeeldingen. Historici melden dat 'de oneerbiedigheid van de dagelijkse religieuze praktijk bijna grenzeloos was.' Koorzangers die waren ingehuurd om te zingen voor de zielen der doden vervingen tijdens de mis vaak heilige woorden door profane termen. Wachtpartijen en processies, die in de middeleeuwse religieuze praktijk een veel grotere rol speelden dan tegenwoordig, werden desalniettemin overschaduwd door grove humor, spot en drinken. Zo verklaarde de vooraanstaande theologische autoriteit van het laatmiddeleeuwse Europa, Denis de Kartusiaan.[^145]

Hoewel een dergelijk verslag als gezeur van een kille moralist zou kunnen worden bestreden, is het slechts een van de vele verslagen die hetzelfde beeld schetsen. Er is alle reden te geloven dat het schunnige en het heilige in het middeleeuwse leven vaak hand in hand gingen. Pelgrimstochten ontspoorden bijvoorbeeld zo vaak in rellen en losbandigheid dat hooggeplaatste hervormers er zonder succes voor opkwamen ze te verbieden. Lokale religieuze processies boden eveneens regelmatig gelegenheid voor menigten om te vandaliseren, te plunderen en zich in het algemeen tegoed te doen aan welke dronken capriolen hen ook maar in de zin lagen. Zelfs wanneer mensen stilzaten om de mis bij te wonen, was de ervaring zelden sober. In de kerk werden enorme hoeveelheden wijn genuttigd, vooral op feestnachten. Verslagen van de Raad van Straatsburg tonen aan dat degenen die “in gebed wachtten” op de nacht van Sint-Adolphus 1.100 liter wijn dronken, geleverd door de raad ter ere van de heilige.

Jean Gerson, een vooraanstaand theoloog uit de vijftiende eeuw, meldt dat “de heiligste feesten, zelfs de kerstnacht,” werden doorgebracht “in losbandigheid, spelend met kaarten, vloekend en godslasterend.” Wanneer de gewone mensen voor deze misstappen werden berispt, beroepen zij zich op het voorbeeld van de adel en de geestelijkheid, die zich op dezelfde wijze onbestraft gedroegen.[^146]

### vroomheid en mededogen

De vroomheid die in de late middeleeuwen de samenleving met georganiseerde religie doordrenkte, diende hetzelfde doel als het “mededogen” dat tegenwoordig bedoeld is om de politieke overheersing van het leven te rechtvaardigen. De verkoop van aflaten om een verlangen naar vroomheid zonder moraal te bevredigen, vertoont gelijkenis met buitensporige bestedingen aan sociale voorzieningen die de schijn van mededogen zonder liefdadigheid trachten te stillen. Het maakte grotendeels niet uit of het werkelijke effect van de aangenomen praktijken bestond uit het verbeteren van het morele karakter of het redden van zielen, net zoals het nauwelijks uitmaakt of een welzijnsprogramma daadwerkelijk de levens van de mensen verbetert voor wie het bedoeld is. “Vroomheid”, net als “mededogen”, was een bijna bijgelovige aanroep.

In een tijd waarin oorzakelijke verbanden nauwelijks werden begrepen, doordrongen de rituelen en sacramenten van de Kerk elke fase van het leven. “. . . Een reis, een taak, een bezoek werden evenzeer vergezeld door duizend formaliteiten: zegeningen, ceremonies, formules.”[^147] Gebeden, op stukken perkament geschreven, werden als kettingen geregen door degenen die aan koorts leden. Ondervoede meisjes hingen lokken van hun haar voor het beeld van Sint Urban om verdere haaruitval te voorkomen. Boeren in Navarra marcheerden in processies achter een beeld van Sint Petrus om tijdens droogtes om regen te smeken.[^148] Mensen namen deze en andere “ineffectieve technieken” gretig over om de angst te verzachten wanneer effectieve methoden niet beschikbaar waren.[^149]

### Twee fouten maken een ritueel

Mensen waren zo vast overtuigd van de wonderbaarlijke krachten die aan de relikwieën van heiligen worden toegekend, dat de dood van een opvallend vrome persoon vaak leidde tot een dolle wedloop om het lichaam op te delen. Nadat Thomas van Aquino in het klooster van Fossanuova was overleden, onthoofden de monniken daar zijn lichaam en kookten het, om zo de controle over zijn beenderen te verkrijgen. Toen Sint Elisabeth van Hongarije in algemene uitvaart lag, «kwam er een menigte aanbidders en sneden of rukten stroken van de linnen doek die haar gezicht omhulde; ze sneden het haar, de nagels, zelfs de tepels af.» [^150]

### Vroomheid zonder deugd

De middeleeuwse geest beschouwde de heiligen en hun relikwieën als een belangrijk onderdeel van het arsenaal van het geloof in een wereld die in de winter kouder, 's nachts donkerder en wanhopiger was ten opzichte van ziekte dan welke lezer van dit boek zich waarschijnlijk kan voorstellen. Duidelijker dan in de moderne periode geloofden mensen in de middeleeuwen dat demonen werkelijk bestonden, dat God actief ingreep in de wereld en dat gebed, boetedoening en pelgrimages goddelijke gunst inbrachten.

Alleen te stellen dat mensen in God geloofden, dekte noch de intensiteit van hun toewijding, noch de ogenschijnlijke eenvoud waarmee middeleeuwse vroomheid met zonde verstrengeld leek te zijn. Het geloof in de effectiviteit van rituelen, ceremonies en sacramenten was zo alomtegenwoordig dat het onvermijdelijk de urgentie van deugdzaam gedrag ondermijnde. Voor iedere zonde of geestelijke tekortkoming was er een remedie, een boetedoening die alles kon wissen – hetgeen men later een “wiskunde van de verlossing” noemde. [^151] De religie werd zo allomvattend dat haar oprechtheid geleidelijk begon te vervagen. Zoals Huizinga het verwoordde, «Betekent religie, die doordringt in alle relaties in het leven, een constante vermenging van de sferen van heilig en profaan denken. Heilige zaken zullen zo alledaags worden dat men ze niet langer diep kan voelen.» [^152] En zo was het.

## De verkleining van de kerk

Aan het eind van de vijftiende eeuw was de kerk niet alleen even corrupt als de hedendaagse natiestaat, maar vormde zij tevens een zware rem op de economische groei. De kerk absorbeerde grote hoeveelheden kapitaal op onproductieve wijze en legde lasten op die de productie van de samenleving beperkten en de handel onderdrukten. Deze lasten, zoals die door de hedendaagse natiestaat worden opgelegd, waren talrijk. We weten wat er met de georganiseerde religie gebeurde in de nasleep van de buskruitrevolutie: hierdoor ontstonden sterke prikkels om religieuze instellingen te verkleinen en hun kosten te verlagen. Toen de traditionele kerk dit weigerde, grepen protestantse sekten de kans om te concurreren. Daarbij maakten zij bijna elk denkbaar middel gebruik om de kosten van een vroom leven te verlagen:

- Zij bouwden sobere nieuwe kerken en haalden soms de altaren van oudere kerken weg om kapitaal voor andere doeleinden vrij te maken.

- Zij herzagen de christelijke leer op manieren die de kosten verlaagden, door het geloof boven goede werken te stellen als sleutel tot verlossing.

- Zij ontwikkelden een nieuwe, beknopte liturgie, schrapten of beperkten feestdagen en schaften talrijke sacramenten af.

- Zij sloten kloosters en nonnenkloosters en hielden op met het verstrekken van aalmoezen aan bedelaarsordes. Armoede transformeerde van een apostolische deugd tot een ongewenst en vaak verwijtbaar sociaal probleem.[^153]

Om te begrijpen hoe het verkleinen van de Kerk de productiviteit bevrijdde, moeten we de vele manieren herzien waarop de Kerk de groei belemmerde voordat haar monopolie werd doorbroken. Net zoals de natiestaat dat tegenwoordig doet, legde de Kerk aan het eind van de vijftiende eeuw een ongelooflijke last van buitensporige kosten op.

1. Directe kosten, zoals tienden, belastingen en heffingen, voedden de overgroeide kerkelijke bureaucratie. Tienden waren ook gebruikelijk bij de protestantse kerken die de middeleeuwse 'Heilige Moederkerk' vervingen, maar in stedelijke gebieden bleken zij doorgaans niet inningbaar te zijn. In feite leidde het einde van het kerkelijke monopolie tot dalende marginale belastingtarieven in regio’s met een sterk ontwikkelde handel.

2. Religieuze doctrines maakten sparen moeilijk. De aartsvijand van de middeleeuwse Kerk was de 'gierigaard', de persoon die zijn goud spaarde ten koste van zijn ziel. De verplichting voor de gelovigen om 'goede daden' te financieren hield kostbare bijdragen aan de Kerk in. De doctrine van 'satisfacties' verplichtte hen die bezorgd waren om hun zaligheid om missen of 'gildenkapellen' in te wijden, om zo het vagevuur te vermijden. Luther viel dit direct aan in de achtste en dertiende van zijn vijfennegentig stellingen. Hij schreef: 'de stervenden zullen al hun schulden afbetalen door hun dood.'[^154] Met andere woorden, het kapitaal van de protestantse gelovige bleek beschikbaar om aan zijn erfgenamen over te dragen. Volgens de protestantse doctrine was het niet nodig om gildenkapellen in te wijden voor het herhaaldelijk houden van missen, meestal voor dertig jaar en soms, voor de zeer rijken, in het eeuwige.

3. De ideologie van de middeleeuwse Kerk stimuleerde tevens de afleiding van kapitaal naar de verwerving van relikwieën. Talrijke relikwieculten werden begiftigd met grote sommen om fysieke objecten te verkrijgen die met Christus of diverse heiligen geassocieerd werden. De zeer rijken stelden zelfs persoonlijke relikwieënverzamelingen samen. Zo verzamelde kiesheren Frederick van Saksen een collectie van negentienduizend relikwieën, waarvan sommige werden verkregen tijdens een pelgrimstocht naar Jeruzalem in 1493. Zijn collectie omvatte hetgeen hij beschouwde als 'het lichaam van een heilige onschuldige, het melk van Maria en stro uit de stal van de Kribbe.'[^155] Vermoedelijk was het rendement op het in deze relikwieën geïnvesteerde kapitaal laag. De verschuiving naar een nadruk op geloof en het begrip van de uitverkorenen deed afbreuk aan het belang van de verwerving van de uiterlijke tekenen van het christelijk leven als talisman en stimuleerde geld om meer productieve kanalen te vinden die een rendement opleverden waarop de vorst kon rekenen.

4. De opkomst van protestantse denominaties brak het economische monopolie van de middeleeuwse Kerk en leidde tot een aanzienlijke verzwakking van de regulering. Zoals we hebben gezien, werd het kanonieke recht vaak gebogen om de monopolies en commerciële belangen van de Kerk te ondersteunen. Omdat de nieuwe denominaties minder economische belangen hadden om te beschermen en te bevorderen, leidde hun opvatting over de religieuze leer doorgaans tot een vrijer systeem, met minder belemmeringen voor de handel.

5. De protestantse revolutie schafte vele rituelen en gebruiken van de middeleeuwse Kerk af die de tijd van de gelovigen zwaar belastten. Rituelen, sacramenten en heilige dagen waren tegen het einde van de vijftiende eeuw zo uitgebreid dat zij bijna het hele jaar in beslag namen. Deze ceremoniële overbelasting was een logische uitkomst van de insisterende overtuiging van de Kerk dat 'men zovaak als men wilde gebeds- of aanbiddingshandelingen kon vermenigvuldigen en er voordelen uit kon halen.'[^156] Vermenigvuldigen, dat deden ze dan ook. De productiviteit werd belemmerd door langere en meer uitgebreide diensten, de verplichting om herhalende gebeden als boetedoening op te zeggen en de toenemende festiviteiten voor heiligen, waarop geen werk verricht mocht worden. Talrijke voorschriften en ceremonies bepaalden de indeling van de dagen en de seizoenen, waardoor de beschikbare tijd voor productieve taken aanzienlijk werd verkleind. Dit had wellicht weinig effect op het ritme van de middeleeuwse landbouw, waarin meer dan 90 procent van de bevolking werkzaam was. Er waren namelijk in de seizoenen vele periodes waarin dagelijkse veldarbeid niet noodzakelijk was. De opbrengst van gewassen onder middeleeuwse omstandigheden varieerde waarschijnlijk meer als gevolg van het weer en oncontroleerbare plaagrugten dan door enige marginale extra arbeid bovenop het minimum dat de kerkelijke kalender toeliet.

Het grotere probleem van verloren productiviteit deed zich minder voor in de landbouw dan in andere sectoren. De tijdsdruk opgelegd door de Kerk paste immers veel minder bij ambachtelijk werk, productie, transport, handel of enig ander bedrijf waarin productiviteit en winstgevendheid in belangrijke mate afhankelijk zijn van de aan een taak bestede tijd.

Het is wellicht geen toeval dat de grote transitie aan het einde van de vijftiende eeuw plaatsvond in een periode waarin de grondprijzen stegen en de reële lonen voor de boeren daalden. Toenemende bevolkingsdruk verminderde de opbrengst van de gemeenschappelijke gronden – vaak te vinden rondom rivieren en beken, waar de boeren hun vee lieten grazen en in sommige gevallen ook voor vis en brandhout op vertrouwden. De dalende levensstandaard zette de boeren steeds zwaarder onder druk om alternatieve inkomstenbronnen te vinden. Daardoor wendde steeds meer van de landelijke bevolking zich tot kleinschalige productie voor de markt, bovenal in textiel, in een proces dat bekendstaat als 'putting-out' of 'proto-industrialisatie.'[^157] De ceremoniële tijdsdruk die de Kerk oplegde, stond de pogingen van de ambitieuzere boeren in de weg om hun landbouwinkomen aan te vullen met ambachtelijk werk en verhinderde tevens elke verschuiving van arbeid naar nieuwe economische richtingen.

Een van de meest opvallende bijdragen van protestantse sekten aan de productiviteit was het schrappen van veertig feestdagen. Dit bespaarde niet alleen de aanzienlijke kosten voor het organiseren van de festiviteiten, waaronder het rijkelijk de dorpskantines voorzien van eten en drinken, maar maakte ook een hoop waardevolle tijd vrij. Impliciet kon iedereen die stopte met het vieren van de veertig afgeschaft feestdagen er driehonderd arbeidsuren of meer aan jaarlijkse productiviteit bijtellen. Kortom, het schrappen van de ceremoniële overbelasting in de middeleeuwse Kerk effende de weg voor een merkbare toename van de productie, simpelweg door tijd vrij te maken die anders aan de handel verloren zou gaan.

6. De doorbraak in het kerkelijke monopolie heeft enorme hoeveelheden activa vrijgemaakt die onder kerkelijk beheer lage rendementen opleverden – een situatie met duidelijke parallellen met staatsbezittingen aan het eind van de twintigste eeuw. De kerk was veruit de grootste feodale grondeigenaar. Haar greep op het land evenaarde die van de staat in sterk gepolitiseerde samenlevingen van tegenwoordig – in sommige Europese landen, zoals Bohemen, bedroeg dit meer dan vijftig procent van het geheel. Volgens het canonieke recht kon een eigendom, eenmaal in handen van de kerk, niet vervreemd worden. Dientengevolge nam het bezit van kerkelijk land gestaag toe, aangezien de kerk steeds meer testamentaire giften van de gelovigen ontving ter financiering van diverse sociale welzijnsdiensten, kapellen en andere activiteiten.

Hoewel het moeilijk is de relatieve productiviteit van kerkelijke bezittingen nauwkeurig te meten, moet deze aan het einde van de middeleeuwen veel lager zijn geweest dan in het vroege deel van die periode. In de veertiende eeuw had de toegenomen nadruk op productie voor de markt, in plaats van op zelfvoorzienende landbouw, ertoe geleid dat de meeste wereldlijke heren ongeleerde hoofdmannen inruilden voor professionele beheerders, zodat zij de opbrengst van hun bezittingen konden optimaliseren. Hun prikkels leidden hen er vermoedelijk toe de opbrengst van kerkelijke eigendommen al snel te overtreffen, die in theorie doorgaans niet ten goede kwamen aan iemands particuliere winst. Ongetwijfeld beheerden enkele wereldse prins-bisschoppen hun domeinen op manieren die niet te onderscheiden waren van die van de wereldlijke heren. Toch zou de productiviteit van andere kerkelijke bezittingen ongetwijfeld geleden hebben onder de tekortkomingen van een onverschillig beheer door een enorme, verspreide instantie, waarvan de nadelen vergelijkbaar waren met die van staats- en gemeenschappelijk eigendom van tegenwoordig. Bovendien is het overduidelijk dat de inbeslagname van de kloosters middelen herverdeelde die, na de komst van de boekdrukkunst, niet langer nodig waren voor de reproductie van boeken en manuscripten.

7. Zoals we uiteenzetten in *The Great Reckoning* reageerden enkele protestantse sekten onmiddellijk op de kruitrevolutie door hun doctrines zodanig aan te passen dat de handel werd gestimuleerd, bijvoorbeeld door het verbod op 'woekerrente' op te heffen, oftewel door uitleningen tegen rente mogelijk te maken. De ideologische oppositie van de middeleeuwse kerk tegen het kapitalisme vormde een rem op de groei. De voornaamste ideologische impuls van de kerkelijke leer was gericht op het bestendigen van het feodalisme – een systeem waarin de kerk, als grootste feodale grondeigenaar, een groot belang had. Al dan niet bewust maakte de kerk van haar eigen economische belangen religieuze deugden, terwijl zij zich verzette tegen de ontwikkeling van de industrie en de totstandkoming van een onafhankelijke commerciële rijkdom, die voorbestemd was het feodale systeem te destabiliseren. Zo waren de verboden tegen 'avance' bijvoorbeeld vooral bestemd voor commerciële transacties in plaats van voor feodale heffingen, en nooit van toepassing op de verkoop van aflaten. De beruchte pogingen van de kerk om een 'billijke prijs' voor handelswaren vast te stellen, onderdrukten de economische opbrengsten van die producten en diensten waarvoor de kerk zelf geen producent was.

Het verbod op 'woekerrente' was een treffend voorbeeld van de weerstand van de kerk tegen commerciële vernieuwing. Bankieren en kredietverlening waren immers van cruciaal belang voor de ontwikkeling van grootschalige commerciële ondernemingen. Door de beschikbaarheid van krediet te beperken, remde de kerk de groei.

8. Op een subtiele manier droeg de nadruk van de nieuwe denominaties op de Bijbel als tekst bij aan het afbreken van zowel de denkwijze als de ideologie van de middeleeuwse kerk. Beide legden obstakels op de weg naar groei. De culturele conditionering van de late middeleeuwen spoorde mensen aan om de wereld te bekijken in termen van symbolische gelijkenis in plaats van oorzaak en gevolg. Dit kortsluitte het redeneren en deed afzien van een koopmansmatige opvatting van het leven. Denken in termen van symbolische equivalentie vertaalt zich immers niet gemakkelijk naar denken in termen van marktwaarden. 'De drie standen vertegenwoordigen de eigenschappen van de Maagd. De zeven kiesmannen van het Rijk staan voor de deugden; de vijf steden van Artois en Henegouwen, die in 1477 trouw bleven aan het huis van Bourgondië, zijn de vijf wijze maagden. . . . Op dezelfde wijze betekenen schoenen zorg en ijver, kousen volharding en de kousband vastberadenheid, enzovoorts.'[^158] Zoals dit voorbeeld, geciteerd uit de vooraanstaande middeleeuwse historicus Johan Huizinga, suggereert, werd het denken gedomineerd door dogma’s, starre symbolen en allegorieën die elk aspect van het leven verenigden in een systeem van hiërarchische ondergeschiktheid. Elk beroep, elk onderdeel, elke kleur, elk getal, ja zelfs elk element van de grammatica maakte deel uit van een groot systeem van religieuze opvattingen.

Thus werden de alledaagse fragmenten van het leven niet gezien in termen van hun oorzakelijke verbanden, maar als statische symbolen en allegorieën. Soms, waarbij deugden en ondeugden werden gepersonifieerd, stond elk ding voor iets, dat op zijn beurt weer voor iets anders stond, op een wijze die de oorzaak-gevolgrelatie vaak verhinderde in plaats van verduidelijkte. Om de zaken nog verder te verwarren, werden relaties vaak willekeurig met elkaar verbonden in systemen van getallen. Het getal zeven speelde daarbij een bijzonder belangrijke rol. Er waren de zeven deugden, de zeven hoofdzonden, de zeven supplicaties van het Onzevader, de zeven gaven van de Heilige Geest, de zeven momenten van de passie, de zeven zaligsprekingen en de zeven sacramenten, “gerepresenteerd door de zeven dieren en gevolgd door de zeven ziekten.” [^159]

### Vijftiende-eeuwse journalistiek

Een nieuwsbericht uit de vijftiende eeuw, als er een geschreven zou zijn, zou geen van de klassieke vragen over het rapporteren van feiten beantwoorden, behalve indirect via allegorische personificatie. Beschouw eens dit verslag, in een privédagboek, van de Bourgondische moorden in het vijftiende-eeuwse Parijs:

> Daarop kwam de godin van tweedracht op, die woonde in de toren van de kwade raad, en wekte Woede, de gestoorde vrouw, en Hebzucht, en Razernij en Wraak, en zij grepen allerlei wapens en verdreven met grote schande Rede, Gerechtigheid, de Herinnering aan God en Matigheid. Toen raakte Waanzin hen tot razernij, en Moord en Slachting doodden, hakten neer, stelden ter dood en massaleerden alles wat zij in de gevangenissen aantroffen. … en Hebzucht stak haar rokken op in haar ceintuur met Roofzucht, haar dochter, en Diefstal, haar zoon. … Vervolgens gingen de voornoemde mensen, geleid door hun godinnen, te weten Woede, Hebzucht en Wraak, die hen door alle openbare gevangenissen van Parijs leidden, enzovoort.[^160]

De verschuiving weg van het middeleeuwse paradigma bereidde de mensen voor op het denken in ‘moderne’ termen over oorzaak en gevolg, in plaats van in termen van symbolische verbanden en allegorische personificatie.

Het is niet nodig te betogen dat de leer en de manier van denken van de laatmiddeleeuwse Kerk niet oprecht waren, om in te zien dat zij nauw aansloten bij de behoeften van het agrarische feodalisme, terwijl er nauwelijks ruimte was voor handel en om nog maar te zwijgen van industriële ontwikkeling. Het ging eerder om de Kerk als de dominante instelling die morele, culturele en juridische kaders vormgaf op een wijze die nauw was afgestemd op de imperatieven van het feodalisme. Om die reden waren deze kaders ongeschikt voor de behoeften van een industriële samenleving, net zoals de morele, culturele en juridische beperkingen van de moderne natiestaat niet bevorderlijk zijn voor de handel in het informatietijdperk. Wij zijn ervan overtuigd dat de staat – net als de Kerk – gerevolutioneerd zal worden om het nieuwe potentieel te benutten.

De protestantse leer, dat het paradijs uitsluitend door geloof en zonder de steun van toegekende gebeden voor de doden kon worden bereikt, werd voorgesteld als een theologisch vraagstuk. Toch was het een theologie die aansloot bij de economische realiteiten van een nieuw tijdperk. Het bood een duidelijke, kosteneffectievere weg naar verlossing op een moment dat de opportuniteitskosten voor het investeren van extra kapitaal in de opgeblazen kerkelijke bureaucratie plotseling waren gestegen. Mensen vonden het minder erg hun geld aan de Kerk te geven wanneer er geen ander alternatief voor beschikbaar was. Maar toen zij plotseling de mogelijkheid zagen om hun kapitaal honderdvoudig te vermeerderen door een specerijenreis naar het Oosten te financieren, of om een mindere, maar desalniettemin veelbelovende opbrengst van 40 procent per jaar te behalen door een bataljon voor de koning te financieren, zochten zij – volkomen terecht – de genade van God, omdat dat in lijn was met hun eigen belangen.

Veel kooplieden en andere gewone mensen werden al snel veel rijker dan hun voorouders dat onder het feodalisme waren. De sterke versnelling van de levensstandaard onder de kooplieden en kleine producenten in de vroegmoderne periode was wijdverbreid impopulair bij degenen wier inkomen en levenswijze instortten met het feodalisme. De verzwakking van het monopolie van de Kerk en de toegenomen megapolitieke macht van de rijken leidden tot een scherpe afname van inkomensherverdeling. De boeren en stedelijke armen, die niet direct profiteerden van het nieuwe systeem, waren bitter jaloers op degenen die dat wel deden. Huizinga beschreef de heersende houding, hetgeen wel eens een belangrijke parallel kan vormen met de informatierévolutie: 'Haat jegens rijke mensen, en in het bijzonder de nieuwe rijken – die toen zeer talrijk waren – is algemeen.'[^161]

Een even opvallende parallel deed zich voor door een enorme toename van de criminaliteit. De ineenstorting van de oude orde ontketent vrijwel altijd een golf van misdrijven, zo niet de regelrechte anarchie van de feodale revolutie die we in het voorgaande hoofdstuk bespraken. Aan het einde van de middeleeuwen schoot de criminaliteit eveneens de hoogte in, naarmate de oude systemen van sociale controle uiteenvielen. Zoals Huizinga het verwoordde: '[C]riminaliteit werd als een bedreiging voor orde en samenleving beschouwd.'[^162] Ook in de toekomst zou dit even bedreigend kunnen zijn.

De moderne wereld werd geboren in de verwarring van nieuwe technologieën, nieuwe ideeën en de stank van kruit. Buskruitwapens en verbeterde scheepvaart destabiliseerden de militaire basis van het feodalisme, terwijl nieuwe communicatietechnologieën zijn ideologie ondermijnden. Een van de elementen die door de nieuwe druktechniek aan het licht werd gebracht, was de corruptie binnen de Kerk, waarvan zowel de hiërarchie als het gewone volk al in een laag daglicht stonden bij een samenleving die op paradoxale wijze de religie centraal stelde. Het is een paradox met een duidelijke hedendaagse parallel in de desillusie jegens politici en bureaucraten, in een samenleving waarin de politiek centraal staat.

Het einde van de vijftiende eeuw was een periode van ontgoocheling, verwarring, pessimisme en wanhoop. Een tijd, net als nu.

[^94]: Clarke, op. cit., p.9.

[^95]: Martin van Creveld, *The Transformation of War* (New York: The Free Press, 1991), p.52.

[^96]: The Compact Edition of The Oxford English Dictionary, op. cit., p.1074.

[^97]: See T.C. Onions, ed., *The Oxford Dictionary of English Etymology* (Oxford: Oxford University Press, 1966), p.693.

[^98]: John Urquhart, 'Voormalig premier klaagt Canada aan wegens laster in onderzoek naar vermeende Airbus-stekpenningen,' *Wall Street Journal*, 21 november 1995, p.A11.

[^99]: Huizinga, op. cit., p.172.

[^100]: Ibid., p.150.

[^101]: Ibid., p.56.

[^102]: Ibid., p.65.

[^103]: Ibid., p.22.

[^104]: van Creveld, op. cit., p.52.

[^105]: Huizinga, op. cit., p.21.

[^106]: Ibid., p. 83.

[^107]: Ibid., p. 88-89.

[^108]: Ibid., p. 95.

[^109]: Ibid., p.90.

[^110]: Ibid., p.87.

[^111]: Norman Cohn, *de zoektocht naar het millennium: revolutionaire millennialisten en mystieke anarchisten van de middeleeuwen*, herziene en uitgebreide editie (Oxford: Oxford University Press, 1970), p.127.

[^112]: Ibid.

[^113]: Ibid., p.128.

[^114]: C. Northcote Parkinson, *Parkinson's law and other studies in administration* (Boston: Houghton Mifflin, 1957), p.60, geciteerd in Tilly, p.4.

[^115]: van Creveld, op. cit., p.50.

[^116]: Playfair, op. cit., p.72.

[^117]: Huizinga, op. cit., p.26.

[^118]: Ibid., p.57.

[^119]: Ibid.

[^120]: Frederic C. Lane, *Venetië: een maritieme republiek* (Baltimore: Johns Hopkins University Press, 1973), p.275.

[^121]: Adam Smith, *Een onderzoek naar de aard en oorzaken van de rijkdom van de naties* (Chicago: University of Chicago Press, 1976), pp.8-9.

[^122]: Zie H. J. Habakkuk en M. Postan, red., *De Cambridge economische geschiedenis van Europa*, vol.6, *De industriële revolutie en daarna: inkomens, bevolking en technologische verandering* (Cambridge: Cambridge University Press, 1966).

[^123]: Euan Cameron, de Europese reformatie (Oxford: The Clarendon Press, 1992), p. 68.
[^124]: Ibid.
[^125]: Huizinga, op. cit., p. 198.
[^126]: Cameron, op. cit., pp. 26–27.
[^127]: Huizinga, op. cit., p. 149.

[^128]: Cameron, op. cit., pp. 26–27.

[^129]: Ibid., p.102.

[^130]: Ibid.

[^131]: Ibid., p.103.

[^132]: Huizinga, op. cit., p.151.

De inhoud van het boek dat vertaald moet worden is:

[^133]: Cameron, op. cit., p.31.

[^134]: Ibid., p.24.

[^135]: Ibid., p.15.

[^136]: Huizinga, op. cit., p.27.

[^137]: Burford, op. cit., p.103.

[^138]: Huizinga, op. cit., p.173.

[^139]: Ibid.

[^140]: William Manchester, *A world lit only by fire: the medieval mind and the renaissance* (Boston: Little, Brown, 1992), pp.75-76.

[^141]: Ibid., p.79.

[^142]: Ibid., pp.82-84.

[^143]: Huizinga, op. cit., p.154.

[^144]: Ibid.

[^145]: Ibid., p. 155.

[^146]: Ibid.

[^147]: Ibid., p.9.

[^148]: Deze voorbeelden van religieuze rituelen zijn afkomstig uit Cameron, op. cit., pp.10-11.

[^149]: Keith Thomas, *Religion and the Decline of Magic* (London: Penguin, 1971), p.800, geciteerd in Cameron, op. cit., p.10.

[^150]: Huizinga, op. cit., p.161.

[^151]: Cameron, op. cit., p. 19.

[^152]: Huizinga, op. cit., p.148.

[^153]: Voor meer details over de scherpe verschillen tussen vijftiende-eeuwse en zestiende-eeuwse perspectieven op armoede, zie Robert Jutte, *Poverty and Deviance in Early Modern Europe* (Cambridge: Cambridge University Press, 1994), pp. 15-17.

[^154]: Cameron, op. cit., p. 127.

[^155]: Ibid., p. 148.

[^156]: Ibid., p. 11.

[^157]: Ibid., p. 5.

[^158]: Huizinga, op. cit.

[^159]: Ibid., p.199.

[^160]: Ibid., p.203.

[^161]: Ibid., p.27.

[^162]: Ibid., p.22.