# Het leven en de gezondheid van de natiestaat

:::{.content-hidden when-format=latex}

*Democratie en nationalisme als strategische middelen in het tijdperk van geweld*

:::

> 'Het allerbelangrijkste is dat succes in oorlog afhangt van het beschikken over voldoende geld om te voorzien in alles wat de onderneming nodig heeft.' [^163] - Robert de Balsac, 1502

## Het puin van de geschiedenis

Op 9 en 10 november 1989 zonden televisiezenders beelden uit naar de wereld waarop uitbundige Oost-Berliners de Berlijnse Muur met sloophamers afbraken. Onder de menigte pikten opkomende ondernemers stukken van de muur op, die later als souvenir-papiergewichten aan kapitalisten in alle windstreken werden verhandeld. Gedurende de daaropvolgende jaren werd er een bloeiende handel in deze relikwieën gedreven. Zelfs terwijl we dit schrijven, komt men nog incidenteel advertenties tegen in kleine tijdschriften die stukjes oud Oost-Duits beton te koop aanbieden voor prijzen die normaal gesproken gelden voor hoogwaardig zilvererts. Wij zijn van mening dat degenen die de souvenir-papiergewichten van de Berlijnse Muur hebben gekocht, geenszins haast hebben met verkopen. Zij dragen aandenken aan iets groters dan de val van het communisme. Wij geloven dat de Berlijnse Muur de belangrijkste hoop historisch puin is geworden sinds de muren van San Giovanni, bijna vijf eeuwen geleden in februari 1495, tot puin werden gesloopt.[^164]

De platmaking van San Giovanni door de Franse koning Karel VIII was de eerste uitbarsting van de buskruitrevolutie. Het betekende het einde van de feodale fase van de geschiedenis en de aanvang van het industrialisme, zoals we eerder hebben uiteengezet. De vernietiging van de Berlijnse Muur markeert een andere historische breuklijn, de overgang van het industriële tijdperk naar het nieuwe informatietijdperk. Nooit is er zo'n grote symbolische triomf van efficiëntie over macht geweest. Toen de muren van San Giovanni vielen, toonde dat duidelijk aan dat de economische opbrengsten van geweld in de wereld scherp waren gestegen. De val van de Berlijnse Muur zegt iets anders, namelijk dat die opbrengsten nu dalen. Dit is iets wat weinigen zelfs al begonnen zijn te herkennen, maar het zal dramatische gevolgen hebben.

Om redenen die we in dit hoofdstuk behandelen, zou de Berlijnse Muur wel eens veel symbolischer kunnen blijken te zijn voor het hele tijdperk van de industriële natiestaat dan door de menigte die die nacht in Berlijn aanwezig was of door de miljoenen die van een afstand toekeken werd begrepen. De Berlijnse Muur werd gebouwd met een heel ander doel dan de muren van San Giovanni – namelijk om te voorkomen dat mensen van binnenuit zouden vluchten, in plaats van om te voorkomen dat roofdieren van buitenaf binnendringen. Dat feit op zich is een duidelijke aanwijzing voor de toename van de macht van de staat van de vijftiende tot de twintigste eeuw. En in meer dan één opzicht.

Eeuwenlang maakte de natiestaat alle naar buiten gerichte muren overbodig. De mate van monopoliserende controle die de staat uitoefende over de toepassing van dwang in de gebieden waar zij voor het eerst voet aan de grond kreeg, maakte deze zowel intern vreedzamer als militair gezien imposanter dan alle soevereine staten die de wereld tot dan toe had gekend. De staat gebruikte de middelen die uit een grotendeels ontwapende bevolking werden onttrokken om kleinschalige roofdieren te verpletteren. De natiestaat werd het meest succesvolle instrument in de geschiedenis om hulpbronnen in beslag te nemen. Haar succes was te danken aan haar superieure vermogen om de rijkdom van haar burgers te onttrekken.

> "MTV is meer dan een leverancier van muziekvideo's – en een promotioneel instrument van de muziekindustrie. Het is het eerste werkelijk wereldwijde netwerk, het eerste netwerk dat in vrijwel elk land ter wereld een uniforme stroom programma’s levert. Daarbij creëert MTV een eenduidig gevoel van een gedeelde mondiale realiteit voor zijn kijkers, kinderen en jongvolwassenen. Recent onderzoek heeft aangetoond dat jonge mensen over de hele planeet steeds meer niet alleen gemeenschappelijke popiconen en gedeelde smaken delen, maar ook gemeenschappelijke verwachtingen voor hun carrières, een gezamenlijke set waarden over wat betekenisvol is in het leven en waarvoor men bang moet zijn, en een gedeeld besef dat politiek minder belangrijk is dan hun eigen vermogen om hun toekomst vorm te geven."[^165] - Jim Taylor and Watts Wacker, The 500-Year Delta: What Happens After What Comes Next

### 'Hou ervan of verlaat het' (tenzij je rijk bent)

Voordat de transitie van de natiestaat naar de nieuwe soevereiniteiten van het informatietijdperk voltooid is, zullen vele inwoners van de grootste en machtigste westerse natiestaten, net als hun tegenhangers in Oost-Berlijn in 1989, plannen smeden om eruit te komen. Voor de generaties die volwassen werden vóór de Tweede Wereldoorlog of in de vroege Koude Oorlog is verhuizen naar het buitenland een traumatische ervaring. Maar voor de nieuwe generaties, die hun referentiekader halen uit een meer mondiale blik, is het verlaten van het land van hun geboorte niet de ondenkbare keuze die dat zou zijn voor oudere mensen die diepgaand zijn doorgedrongen van de ideologie van de natiestaat. Jim Taylor en Watts Wacker presenteren de intrigerende resultaten van een grootschalige enquête onder 20.000 middelbare scholieren uit de middenklasse op vijf continenten. In een steekproef die tijdens het schooljaar 1995–96 werd uitgevoerd door Brainwaves Group, een consumentenonderzoeksbureau uit New York, was negen op de tien studenten het ermee eens dat 'het aan mij is om te krijgen wat ik van het leven wil.' Nog opvallender: 'bijna de helft van de tieners zei dat zij verwachtten het land van hun geboorte te zullen verlaten om hun doelen na te streven.'[^166] Misschien omdat hij is afgestemd op de opvattingen van de MTV-generatie, heeft Bill Clinton – als de eerste presidentskandidaat die campagne voerde op MTV – geprobeerd het voor Amerikanen moeilijker te maken om 'het land van hun geboorte te verlaten om hun doelen na te streven'. In 1995, ongeveer tegelijkertijd met wanneer de middelbare scholieren hun voornemen om onafhankelijk te worden bekendmaakten, stelde de president van de Verenigde Staten de invoering van een exitbelasting voor, een 'Berlijnse muur voor kapitaal', die rijke Amerikanen zou verplichten een aanzienlijk losgeld te betalen om zelfs een deel van hun geld mee te nemen.

Clintons losgeld doet niet alleen denken aan het beleid van de laat oost-Duitse staat, die haar burgers als bezittingen beschouwde; het roept ook de steeds draconischer wordende maatregelen op om de fiscale positie van het in verval geraakte Romeinse Rijk te versterken. Dit fragment uit *The Cambridge Ancient History* vertelt het verhaal.

> Zo begon de felle inspanning van de staat om de bevolking tot op de laatste druppel uit te persen. Omdat de economische middelen tekortschoten, vochten de sterken om het grootste deel voor zichzelf vast te leggen, met een geweld en meedogenloosheid die ruimschoots in overeenstemming waren met de oorsprong van de machthebbers en met een soldaat die gewend was aan plundering. De volle strengheid van de wet werd losgelaten op de bevolking. Soldaten traden op als deurwaarders of zwierven als geheime politie door het land. Degenen die het meest leden, waren uiteraard de vermogende klasse. Het was relatief gemakkelijk hun bezit in handen te krijgen en in noodgevallen waren zij de klasse waarvan het meest en snelst iets afgeperst kon worden.[^167]

Wanneer falende systemen daartoe in staat zijn, leggen ze vaak zware straflasten op aan degenen die willen ontsnappen. Nogmaals citeren we *The Cambridge Ancient History*: 'Als de vermogende klasse haar geld verstopte, of twee derde van haar bezit opofferde om een magistratuur te ontvluchten, of zelfs haar gehele eigendom opgaf om verlost te worden van de erfpacht, en de niet-vermogende klasse vluchtte, reageerde de staat door de druk te verhogen.'

Dit is de moeite waard om te onthouden bij het plannen van de toekomst. De ondergang van staatsystemen in het verleden is zelden op een beleefde en ordelijke manier verlopen. In hoofdstuk 2 noemden we de onprettige gewoonten van de Romeinse belastinginners. Het grote aantal agri deserti, oftewel verlaten boerderijen, in West-Europa na de val van het Romeinse Rijk weerspiegelde slechts een deel van een breder probleem. In Gallië en in de grensgebieden, waaronder het huidige Luxemburg en Duitsland, bleken de buitensporige heffingen relatief mild te zijn. In Egypte, de vruchtbaarste regio van Rome, waar de landbouw door irrigatie productiever was, vormde ontwrichting door grondbezitters een nog groter probleem. De vraag of men een poging tot ontsnapping moest wagen – het ultimum refugium, zoals het in het Latijn genoemd werd – werd de overkoepelende kwestie voor vrijwel iedereen met bezit. Uit de bronnen blijkt dat 'onder de algemene vragen die aan een orakel in Egypte gesteld werden, drie standaardtypen waren: 'Zal ik een bedelaar worden?', 'Zal ik vluchten?' en 'Zal mijn vlucht worden gestopt?''[^168]

Clintons voorstel zegt ja. Het betreft een vroege vorm van een ontsnappingsdrempel die waarschijnlijk zwaarder zal worden naarmate de fiscale middelen van de natiestaat wegebben. Natuurlijk is de eerste Amerikaanse versie van een vertrekbarrière minder ingrijpend dan Erich Honeckers beton en prikkeldraad. Bovendien speelt prijssensitiviteit een grotere rol, waarbij de last uitsluitend valt op ‘miljardairs’ met een belastbare erfenis van meer dan $600.000. Desondanks werd het gerechtvaardigd met argumenten die sterk leken op die van Honecker, die ooit ter verdediging werd ingezet van het beroemdste openbare werkproject van de inmiddels overleden Duitse Democratische Republiek. Honecker stelde dat de Oost-Duitse staat een aanzienlijke investering had gedaan in potentiële vluchtelingen. Hij wees erop dat het vrijlaten van deze mensen een economisch nadeel voor de staat zou betekenen, die immers op hun inzet in Oost-Duitsland rekende.

Als je de stelling aanvaardt dat mensen activa van de staat zijn of zouden moeten zijn, dan was Honeckers muur logisch. Een Berlijn zonder muur bood de communisten een weg, net zoals ontsnapping aan de Amerikaanse belastingjurisdictie voor Clintons IRS een terugweg was. Clintons argumenten over vluchttende miljardairs – afgezien van de gebruikelijke minachting van een politicus voor de integriteit van de cijfers – lijken sterk op die van Honecker, maar zijn enigszins minder logisch omdat de Amerikaanse overheid in feite geen grote economische investering heeft in rijke burgers die mogelijk zouden willen vluchten. Het gaat niet om het feit dat zij op kosten van de staat onderwijs hebben genoten en vervolgens onopgemerkt elders de advocatuur in wilden, want de overgrote meerderheid van degenen op wie de vertrekbelasting zou worden geheven, heeft hun rijkdom met eigen inzet vergaard – desondanks, niet dankzij de Amerikaanse overheid.

Nu het bovenste 1 procent van de belastingbetalers inmiddels 28,7 procent van de totale inkomstenbelasting in de Verenigde Staten betaalt, is het niet zo dat de rijken er niet in slagen een eventuele werkelijke investering van de staat in hun opleiding of economische voorspoed terug te betalen. Integendeel: zij die de meeste kosten betalen, voldoen ruimschoots meer dan de waarde van de enkele voordelen die zij ontvangen. Met een gemiddelde jaarlijkse belastingbetaling van meer dan $125.000 kosten belastingen het top 1-procent van de Amerikaanse belastingbetalers aanzienlijk meer dan zij momenteel beseffen. Als men ervan uitgaat dat zij zelfs een rendement van 10 procent op de extra betaalde belasting over een periode van veertig jaar zouden kunnen behalen, dan verkleint elke jaarlijkse overschrijding van $5.000 hun netto vermogen met $2,2 miljoen. Bij een rendement van 20 procent betekent elke $5.000 aan extra belasting een afname van het netto vermogen van $44 miljoen.

Naarmate het millennium nadert, zal onder de nieuwe megapolitieke voorwaarden van het Informatietijdperk steeds duidelijker worden dat de natiestaat, zoals die is geërfd uit het industriële tijdperk, een roofzuchtige instelling is. Elk voorbijgaand jaar zal ze minder als een zegen voor de welvaart worden ervaren en meer als een belemmering, waartegen individuen willen ontsnappen. Het is een ontsnapping die wanhopige regeringen maar al te ungern zullen toestaan. De stabiliteit en zelfs het voortbestaan van de westerse verzorgingsstaten hangt af van hun vermogen om een enorm deel van de wereldwijde productie te blijven onttrekken voor herverdeling aan een specifieke groep kiezers in de OESO-landen. Dit vereist dat de belastingen die worden opgelegd aan de meest productieve burgers van de huidige rijke landen tegen supermonopolistische tarieven worden geheven – honderden of zelfs duizenden keren hoger dan de werkelijke kosten van de diensten die de overheid in ruil daarvoor levert.

## THE LIFE AND DEATH OF THE NATIONSTATE

De val van de Berlijnse Muur was niet slechts een zichtbaar symbool van de ondergang van het communisme. Het betekende een nederlaag voor het gehele wereldsysteem van natiestaten en een triomf van efficiëntie en markten. Het draaipunt van de macht die aan de basis lag van de geschiedenis is verschoven. Wij zijn van mening dat de val van de Berlijnse Muur in 1989 het hoogtepunt vormt van het tijdperk van de natiestaat, een eigenaardige tweehonderdjarige fase in de geschiedenis die begon met de Franse Revolutie. Staten bestaan al zesduizend jaar, maar vóór de negentiende eeuw vertegenwoordigden zij slechts een klein deel van de wereldse soevereiniteiten. Hun opkomst begon en eindigde in revolutie. De grote gebeurtenissen van 1789 stelden Europa op een koers naar werkelijk nationale regeringen. De grote gebeurtenissen van 1989 markeerden de ondergang van het communisme en een bevestiging van de controle door marktmechanismen over geconcentreerde macht. Die twee revoluties, precies tweehonderd jaar uit elkaar, definiëren het tijdperk waarin de natiestaat predominante was in het systeem van de grote mogendheden. De grote mogendheden domineerden op hun beurt de wereld, door staatsstelsels te verspreiden of op te leggen aan zelfs de meest afgelegen tribale enclaves.

De triomf van de staat als het voornaamste instrument voor het organiseren van geweld in de wereld was geen kwestie van ideologie. Het werd bepaald door de kille logica van geweld. Het was, zoals wij graag zeggen, een megapolitieke gebeurtenis, die niet zozeer werd gevormd door de wensen van theoretici en staatslieden, of zelfs door het manoeuvreren van generaals, maar door de verborgen hefboomwerking van geweld, die de geschiedenis in beweging zette op de wijze waarop Archimedes droomde de wereld te verzetten.

Staten zijn de norm geweest gedurende de afgelopen tweehonderd jaar van de moderne periode, maar in de bredere loop van de geschiedenis waren staten zeldzaam. Zij waren altijd afhankelijk van buitengewone megapolitieke omstandigheden om te kunnen bestaan. Vóór de moderne periode waren de meeste staten 'oriëntaalse despotieën', agrarische samenlevingen in woestijnen die afhankelijk waren van de controle over irrigatiesystemen voor hun voortbestaan. Zelfs het Romeinse Rijk, door zijn controle over Egypte en Noord-Afrika, was indirect een hydraulische samenleving – maar niet in voldoende mate om te overleven. Rome, zoals de meeste premoderne staten, ontbeerde uiteindelijk het vermogen om naleving af te dwingen van het geweldmonopolie dat het verhongeren van mensen mogelijk maakt. De Romeinse staat buiten Afrika kon het water voor de gewassen niet afsluiten door ongehoorzame mensen de toegang tot het irrigatiesysteem te ontzeggen. Zulke hydraulische systemen boden een grotere hefboomwerking voor geweld dan welke andere megapolitieke configuratie in de oude economie dan ook. Wie in deze samenlevingen het water beheerste, kon buit innen op een niveau dat bijna te vergelijken is met het percentage van de totale output dat moderne natiestaten absorberen.[^169]

### Grootte boven efficiëntie

Buskruit stelde staten in staat zich gemakkelijker uit te breiden buiten de grenzen van rijstvelden en droge rivierdalen. De aard van buskruitwapens en de structuur van de industriële economie creëerden grote schaalvoordelen in oorlogsvoering. Dit leidde tot hoge en toenemende rendementen uit geweld. Zoals historicus Charles Tilly het verwoordde: '[S]taten die de grootste dwangmiddelen hadden, wonnen de oorlogen; efficiëntie (de verhouding tussen output en input) kwam op de tweede plaats na effectiviteit (totale output).'[ˆ170] Met regeringen die doorgaans op grote schaal georganiseerd waren, hadden zelfs de weinige kleine soevereiniteiten die overleefden – zoals Monaco of Andorra – de erkenning van de grotere staten nodig om hun onafhankelijkheid veilig te stellen. Alleen grote regeringen met een steeds groter wordende beheersing van middelen konden op het slagveld concurreren.

### De grote onbeantwoorde vraag

Dit leidt ons tot een van de grote onbeantwoorde raadsels uit de moderne geschiedenis: waarom stelde de Koude Oorlog, die volgde op het systeem van grootmachten, als uiteindelijke concurrenten communistische dictaturen tegenover democratieën van de verzorgingsstaat? Dit vraagstuk is zo weinig onderzocht dat het voor velen aannemelijk leek toen een analist van het ministerie van Buitenlandse Zaken, Francis Fukuyama, na de val van de Berlijnse Muur 'het einde van de geschiedenis' uitriep. Het enthousiaste publiek dat hierdoor werd overtuigd, nam te veel voor lief. Blijkbaar namen noch de auteur, noch velen anders de moeite om de fundamentele vraag te stellen: welke gemeenschappelijke kenmerken van staatssocialisme en democratieën van de verzorgingsstaat leidden ertoe dat zij de uiteindelijke concurrenten in de strijd om wereldheerschappij werden?

Dit is een belangrijk vraagstuk. Tenslotte zijn er in de afgelopen vijf eeuwen tientallen systemen van soevereiniteit gekomen en weer verdwenen, waaronder absolute monarchieën, tribale enclaves, prins-bisdommen, directe heerschappij door de paus, sultanaten, stadsstaten en anabaptistische kolonies. Tegenwoordig zou de meeste mens verbaasd zijn te horen dat een ziekenhuisbeheermaatschappij, met eigen strijdkrachten, eeuwenlang een land kon besturen. Toch is er iets dergelijks gebeurd. Driehonderd jaar na 1228 regeerden de teutoonse ridders van het St. Mary's Hospital in Jeruzalem, later verenigd met de ridders van het Zwaard van Livonië, over Oost-Pruisen en diverse gebieden in Oost-Europa, waaronder delen van Litouwen en Polen. Toen kwam de buskruitrevolutie. Binnen enkele decennia werden de teutoonse ridders als soevereine heersers uit al hun gebieden verdreven en was hun grootmeester niet meer van militair belang dan een schaakkampioen. Waarom? Waarom raakten zoveel andere systemen van soevereiniteit tot onbeduidendheid teruggedrongen, terwijl aan het einde van het industriële tijdperk de grote strijd om wereldmacht massademocratieën van de verzorgingsstaat tegenover staatssocialistische systemen plaatste?

### Onbelemmerde controle

Als onze theorie over megapolitiek klopt, is het antwoord eenvoudig. Het is vergelijkbaar met de vraag waarom sumoworstelaars vaak dik zijn. Het antwoord is dat een slanke sumoworstelaar, hoe indrukwekkend zijn kracht-tot-gewichtverhouding ook is, niet kan tippen tegen een worstelaar die gigantisch is. Zoals Tilly suggereert, was de cruciale kwestie 'effectiviteit (totale output)', niet 'efficiëntie (de verhouding van output tot input)'. In een wereld die steeds gewelddadiger wordt, waren de systemen die gedurende vijf eeuwen domineerden onvermijdelijk degenen die de grootste toegang boden tot de hulpbronnen die nodig waren om op grote schaal oorlog te voeren.

Hoe werkte dit?

In het geval van het communisme is het antwoord duidelijk. Onder het communisme controleerden degenen die de staat beheersten vrijwel alles. Als je tijdens de Koude Oorlog een burger van de Sovjet-Unie was geweest, had de KGB je tandenborstel kunnen afnemen als zij dat nuttig vonden voor hun eigen doeleinden. Ze hadden zelfs je tanden kunnen wegnemen. Volgens geloofwaardige schattingen – die nog meer geloofwaardigheid hebben gewonnen sinds de opening van de voormalige Sovjetarchieven in 1992 – hebben de geheime politie en andere agenten van de voormalige Sovjetstaat in vierenzeventig jaar bewind het leven genomen van 50 miljoen mensen. Het staatssocialistische systeem was in staat om alles wat binnen zijn grenzen bestond te mobiliseren voor zijn leger, met vrijwel niemand die daar bezwaar tegen zou maken.

In het geval van de westerse democratieën is het verhaal minder duidelijk, deels omdat we gewend zijn om democratie scherp te stellen tegenover het communisme. Als we kijken naar het tijdperk van de industriële revolutie, waren de twee systemen inderdaad grote tegenpolen. Maar gezien vanuit het perspectief van het informatietijdperk hadden de twee systemen meer gemeen dan je zou vermoeden. Beide stelden de overheid in staat om de hulpbronnen zonder belemmering te beheersen. Het verschil was dat de democratische verzorgingsstaat nog veel meer middelen in handen van de staat legde dan de staatssocialistische systemen.

Dit is een duidelijk voorbeeld van een zeldzaam fenomeen, waarbij minder meer is. Het staatssocialistische systeem ging uit van de doctrine dat de staat alles bezat. De democratische verzorgingsstaat daarentegen deed minder ambitieuze aanspraken en hanteerde daardoor betere stimulansen om een grotere productie te realiseren. In plaats van vanaf het begin aanspraak op alles te leggen, stelden de regeringen in het Westen individuen in staat eigendom te bezitten en rijkdom op te bouwen. Vervolgens namen de westerse natiestaten een groot deel van die rijkdom weg via belastingen. Hoge onroerendgoed-, inkomsten- en erfbelastingen voorzagen de democratische verzorgingsstaat van enorme hoeveelheden middelen in vergelijking met de middelen die beschikbaar waren via de staatssocialistische systemen.

### Inefficiëntie, waar het ertoe deed

Vergeleken met het communisme was de welvaartsstaat inderdaad een veel efficiënter systeem. Maar vergeleken met andere systemen voor het vergaren van rijkdom – zoals een echte laissez‑faire‐enclave als Hongkong – was de welvaartsstaat inefficiënt. Wederom bleek: minder was meer. Juist deze inefficiëntie maakte de welvaartsstaat tijdens de megapolitieke omstandigheden van het industriële tijdperk superieur.

Wanneer je eenmaal begrijpt waarom, kom je al veel dichter bij het doorgronden van wat de val van de Berlijnse Muur en de dood van het communisme werkelijk betekenen. In plaats van te bewijzen dat de democratische welvaartsstaat een triomfantelijk systeem zal zijn, zoals algemeen wordt aangenomen, is het eerder alsof je ziet dat je tweelingbroer aan ouderdom is gestorven. Dezelfde megapolitieke revolutie die het communisme heeft vernietigd, zal hoogstwaarschijnlijk ook de democratische welvaartsstaten, zoals we die in de twintigste eeuw kenden, ondermijnen en ten val brengen.

## Wie controleert de overheid?

De sleutel tot deze onorthodoxe conclusie ligt in het herkennen van waar de controle over de democratische overheid is gevestigd. Het is een kwestie die niet zo eenvoudig is als hij lijkt. In het moderne tijdperk wordt de vraag wie de overheid controleert bijna altijd als een politieke kwestie gesteld. Hierop zijn al vele antwoorden gegeven, maar vrijwel altijd ging het om het aanwijzen van de politieke partij, groep of factie die op een bepaald moment de controle over een specifieke staat domineerde. Je hebt gehoord van overheden die door kapitalisten worden beheerst. Overheden die door arbeiders worden beheerst. Overheden die door katholieken, en door islamitische fundamentalisten, worden beheerst. Ook overheden die door stam- en raciale groepen worden beheerst; overheden die door Hutu’s en door blanken worden beheerst. Je hebt ook gehoord van overheden die door beroepsgroepen – zoals advocaten of bankiers – worden beheerst. Je hebt gehoord van overheden die door landelijke belangen, door de politieke machines van grote steden en door bewoners van de voorsteden worden beheerst. En je hebt ongetwijfeld gehoord van overheden die door politieke partijen worden beheerst, door democraten, conservatieven, christendemocraten, liberalen, radicalen, republikeinen en socialisten.

Maar je hebt waarschijnlijk niet veel gehoord over een overheid die door haar klanten wordt gecontroleerd. De economische historicus Frederic Lane legde de basis voor een nieuwe benadering van waar de controle over de overheid ligt, zoals hij in enkele heldere essays over de economische gevolgen van geweld eerder besprak. Het benaderen van de overheid als een economische eenheid die bescherming verkoopt, leidde Lane ertoe de controle over de overheid in economische in plaats van in politieke termen te analyseren. Volgens deze visie zijn er drie fundamentele alternatieven voor de controle over de overheid, die ieder een wezenlijk ander stel prikkels met zich meebrengen: eigenaren, werknemers en klanten.

### Proprietors

In zeldzame gevallen, zelfs tegenwoordig, worden regeringen soms bestuurd door een eigenaar, meestal een erfelijke leider die feitelijk het land bezit. Zo behandelt de sultan van Brunei de regering van Brunei enigszins als een privébezit. Dit kwam in de middeleeuwen vaker voor, toen heren hun leenbezit beschouwden als privéondernemingen om hun inkomsten te optimaliseren.

Lane beschreef de prikkels voor 'de eigenaren van de productieproducerende onderneming' als volgt:

> Een streven naar winstmaximalisatie zou hem, terwijl hij de prijzen gelijk houdt, ertoe aanzetten zijn kosten te verlagen. Hij zou, net als Hendrik VII van Engeland of Lodewijk XI van Frankrijk, goedkope listen inzetten – of liever, zo goedkope middelen als mogelijk – om zijn legitimiteit te bevestigen, de binnenlandse orde handhaven en de aandacht van naburige vorsten af te leiden, zodat zijn eigen militaire uitgaven laag blijven. Door lagere kosten, of door de verhoogde heffingen die mogelijk werden gemaakt door de strengheid van zijn monopolie, of door een combinatie hiervan, vergaarde hij een overschot... [^171]

Regeringen die door eigenaren worden bestuurd, hebben sterke prikkels om de kosten voor het bieden van bescherming of het monopoliseren van geweld in een bepaald gebied te verlagen. Maar zolang hun heerschappij veilig is, hebben zij weinig prikkel om de prijs (belasting) die zij van hun klanten vragen, te verlagen tot onder het niveau dat de opbrengsten optimaliseert. Hoe hoger de prijs die een monopolist kan vragen en hoe lager zijn werkelijke kosten, des te groter de winst die hij zal maken. Het ideale fiscale beleid voor een door eigenaren gecontroleerde regering zou dan ook een enorm overschot zijn. Wanneer regeringen erin slagen hun inkomsten hoog te houden en tegelijkertijd hun kosten te drukken, heeft dit een grote impact op het gebruik van middelen. Arbeid en andere waardevolle productiefactoren die anders zouden worden verspild aan het leveren van onnodig dure bescherming, komen in plaats daarvan beschikbaar voor investeringen en andere doeleinden. Hoe meer winst de vorst kan realiseren door de kosten te verlagen, hoe meer middelen er vrijkomen. Worden deze middelen aangewend voor investeringen, dan vormen zij een stimulans voor groei. Maar zelfs als zij worden gebruikt voor pronkconsumptie, dragen zij bij aan het creëren en in stand houden van nieuwe markten die anders niet zouden ontstaan als de middelen waren verspild aan het leveren van inefficiënte 'bescherming'.

### Werknemers

Het is eenvoudig de prikkels te karakteriseren die heersen bij overheden die door hun werknemers worden bestuurd. Deze prikkels zouden vergelijkbaar zijn in andere door werknemers bestuurde organisaties. Allereerst hebben door werknemers bestuurde organisaties de neiging elk beleid te favoriseren dat de werkgelegenheid vergroot en maatregelen te verzetten die banen doen verdwijnen. Zoals Lane het verwoordde: 'Wanneer werknemers als geheel de macht hadden, hadden zij weinig interesse om de bedragen die voor bescherming werden afgedwongen te minimaliseren en geen enkele om dat grote deel van de kosten – dat door de loonkosten, oftewel hun eigen salarissen, werd vertegenwoordigd – te verlagen. Het vergroten van de omvang lag ook meer in hun aard.'[^172] Een door werknemers bestuurde overheid zou zelden de prikkel hebben om zowel de kosten van de overheid als de prijs die aan haar klanten in rekening wordt gebracht te verlagen. Echter, waar omstandigheden een sterke prijsweerstand opleggen in de vorm van oppositie tegen hogere belastingen, zullen overheden die door werknemers worden beheerd eerder toestaan dat hun inkomsten onder hun uitgaven zakken dan dat zij hun uitgaven beperken. Met andere woorden, hun prikkels impliceren dat zij mogelijk geneigd zijn tot chronische tekorten, zoals overheden die door eigenaars worden bestuurd dat niet zouden zijn.

### Klanten

Zijn er voorbeelden van overheden die door hun klanten worden beheerd? Ja. Lane liet zich ertoe inspireren om de aansturing van de overheid in economische termen te analyseren op basis van het voorbeeld van de middeleeuwse koopmansrepublieken, zoals Venetië. Daar controleerde een groep groothandelaren – die bescherming wensten – de overheid feitelijk eeuwenlang. Zij waren oprecht klanten van de beschermingsdienst die de overheid verleende, geen eigenaars. Zij betaalden voor de dienst en streefden er niet naar winst te behalen uit hun controle over het geweldmonopolie van de overheid. Als sommigen dat toch deden, weerhielden de andere klanten hen er lange tijd van. Andere voorbeelden van overheden die door hun klanten worden beheerd zijn democratieën en republieken met een beperkt kiesrecht, zoals de oude democratieën of de Amerikaanse republiek in haar oprichtingsperiode. In die tijd mochten alleen diegenen stemmen die voor de overheid betaalden – ongeveer 10 procent van de bevolking.

Overheden die door hun klanten worden beheerd, hebben, net als die van eigenaars, prikkels om hun bedrijfskosten zo ver mogelijk te verlagen.

Maar in tegenstelling tot regeringen die gecontroleerd worden door eigenaren of werknemers, hebben regeringen die daadwerkelijk door hun klanten worden gecontroleerd prikkels om de door hen gehanteerde prijzen laag te houden. Waar klanten het woord voeren, zijn regeringen mager opgebouwd en doorgaans onopvallend, met lage bedrijfskosten, minimale werkgelegenheid en lage belastingen. Een door haar klanten gecontroleerde overheid stelt belastingsniveaus niet vast om de opbrengst voor de overheid te maximaliseren, maar om juist het bedrag dat de klanten kunnen behouden te optimaliseren.

Net als typische ondernemingen in concurrerende markten zou zelfs een monopolistische instelling, die door haar klanten wordt gecontroleerd, gedwongen worden richting efficiëntie te bewegen. Zij zou niet in staat zijn een prijs – in de vorm van belastingen – te vragen die de kosten met meer dan een minimale marge overschrijdt.

## De rol van democratie: kiezers als werknemers en klanten

Lane benadert de democratie op de conventionele wijze door ervan uit te gaan dat zij ondernemingen die geweld gebruiken en produceren steeds meer onder de controle van hun klanten brengt.[^173] Dit is ongetwijfeld de politiek correcte conclusie. Maar is dat waar? Wij denken van niet. Kijk eens goed hoe moderne democratieën functioneren.

Allereerst vertonen zij maar weinig kenmerken van die concurrerende sectoren waarin de voorwaarden van de handel duidelijk door de klanten worden bepaald. Zo besteedt een democratische overheid doorgaans slechts een schamele fractie van haar totale uitgaven aan de bescherming, die haar kerntaak is. In de Verenigde Staten besteden staats- en lokale overheden bijvoorbeeld slechts 3,5 procent van hun totale uitgaven aan de voorziening van politie, rechtbanken en gevangenissen. Tel daar de militaire uitgaven bij op, en de fractie van de inkomsten die aan bescherming wordt besteed, blijft nog maar ongeveer 10 procent. Een andere onthullende aanwijzing dat massademocratie niet door haar klanten wordt gecontroleerd, is het feit dat de hedendaagse politieke cultuur, geërfd uit het industriële tijdperk, het onacceptabel zou vinden als beleid over cruciale kwesties daadwerkelijk werd beïnvloed door de belangen van de mensen die de rekeningen betalen. Stel je de ophef eens voor als een Amerikaanse president of een Britse premier zou voorstellen om de groep burgers die het merendeel van de belastingen betaalt, te laten bepalen welke overheidsprogramma’s gehandhaafd moeten blijven en welke groepen medewerkers ontslagen zouden moeten worden. Dat zou in grove strijd zijn met de verwachtingen over hoe de overheid zou moeten functioneren, op een manier die anderzijds niet zou opvallen wanneer overheidsmedewerkers zouden bepalen wiens belastingen verhoogd moeten worden.

Maar als je erover nadenkt, wanneer klanten werkelijk de macht hebben, zou het schandalig zijn als zij niet kregen wat ze wilden. Als je een winkel binnenging om meubels te kopen en de verkopers je geld aannamen, maar vervolgens jouw wensen negeerden en in plaats daarvan anderen raadplegen over hoe je je geld uit te geven, zou je terecht verontwaardigd zijn. Je zou het zeker niet normaal of gerechtvaardigd vinden als de medewerkers van de winkel zouden beweren dat je de meubels eigenlijk niet verdient en dat ze in plaats daarvan naar iemand gestuurd zouden moeten worden die zij meer waard achten. Het feit dat zoiets vrijwel dergelijks gebeurt in de omgang met de overheid, toont aan hoe weinig controle haar "klanten" daadwerkelijk hebben.

Op welke maatstaf ook, de kosten van democratische regeringen zijn buiten controle geraakt, in tegenstelling tot de typische situatie waarin de voorkeuren van klanten aanbieders dwingen efficiënt te opereren. De meeste democratieën kamperen met chronische begrotingstekorten. Dit is een kenmerk van een fiscale beleidvoering die voortvloeit uit de controle door werknemers. Overheden blijken opmerkelijk terughoudend in het verlagen van de kosten van hun operaties. Een bijna universele klacht over hedendaagse regeringen wereldwijd is dat politieke programma’s, eenmaal ingevoerd, met grote moeite kunnen worden ingeperkt. Het ontslaan van een ambtenaar is vrijwel onmogelijk. Sterker nog, een van de belangrijkste voordelen van de privatisering van voorheen staatsbezette functies is dat particuliere controle het doorgaans veel eenvoudiger maakt om overbodige banen te schrappen. Van Groot-Brittannië tot Argentinië is het niet ongewoon dat de nieuwe particuliere managers 50 tot 95 procent van de voorheen door de staat tewerkgestelde werknemers laten gaan.

Denk ook eens aan de grondslag waarop de fiscale voorwaarden voor de beschermingsdiensten van de overheid worden vastgesteld. Voor het grootste deel zou je tevergeefs zoeken naar sporen van concurrentie-invloeden op de belastingtarieven waarop de overheidsdiensten worden geprijsd. Zelfs de incidentele debatten over belastingverlagingen, die in de afgelopen jaren de normale politieke discussie hebben verstoord, onthullen hoe ver democratische regeringen doorgaans verwijderd zijn van de controle door hun klanten. Voorstanders van lagere belastingen hebben soms betoogd dat de overheidsinkomsten eigenlijk zouden toenemen, omdat de tarieven voorheen zo hoog waren vastgesteld dat ze economische activiteit ontmoedigden.

De afweging die zij normaal gesproken wilden benadrukken, betrof niet de concurrentie tussen rechtsgebieden, maar iets veel verbazingwekkenders. Zij betoogden niet dat, omdat de belastingtarieven in Hongkong slechts 15 procent bedroegen, de tarieven in de Verenigde Staten of Duitsland niet hoger konden zijn dan 15 procent. Integendeel. Belastingdebatten gingen er normaal gesproken vanuit dat de keuze voor de belastingbetaler niet bestond uit het selecteren van een rechtsgebied boven een ander, maar uit de afweging tussen zakendoen tegen straftarieven of eens pauze nemen. Men stelde dat productieve mensen, geconfronteerd met roofzuchtige belastingheffing, hun werk zouden verwaarlozen en in plaats daarvan gingen golfen als hun belastingdruk niet verlicht werd.

Het feit dat zo'n argument überhaupt opkomt, toont aan hoe sterk de beschermingskosten die door democratische welvaartsstaten worden opgelegd, afwijken van een competitieve marktwerking. De modaliteiten van progressieve inkomstenbelasting, die in de loop van de twintigste eeuw in elke democratische welvaartsstaat werden ingevoerd, verschillen drastisch van de prijsbepalingsregels die klanten zouden prefereren. Dit wordt duidelijk wanneer men de belastingen vergelijkt die worden opgelegd om een monopolistische beschermingsvoorziening te ondersteunen met de tarieven voor telefonie, die tot voor kort op de meeste plaatsen een monopolie vormden. Klanten zouden uit het dak gaan als een telefoonmaatschappij zou proberen de kosten voor gesprekken op dezelfde wijze in rekening te brengen als waarop inkomstenbelastingen worden geheven. Stel je voor dat de telefoonmaatschappij een rekening van $50.000 zou sturen voor een gesprek naar Londen, simpelweg omdat je tijdens een gesprek een overeenkomst ter waarde van $125.000 had gesloten. Noch jij, noch een andere klant in zijn volle verstand, zou dat betalen. Maar dat is precies de basis waarop in elke democratische welvaartsstaat inkomstenbelastingen worden geheven.

Als je eens goed nadenkt over de voorwaarden waaronder industriële democratieën hebben gefunctioneerd, is het logischer om ze te zien als een vorm van regering die door haar werknemers wordt beheerd. Het beschouwen van massademocratie als een regering die door haar werknemers wordt gecontroleerd, helpt de moeilijkheid van het wijzigen van overheidsbeleid te verklaren. De overheid lijkt in veel opzichten te worden gerund voor het voordeel van de werknemers. Zo lijken de overheidscholen in de meeste democratische landen structureel te falen en zonder oplossing te blijven. Als de klanten werkelijk achter het stuur zaten, zouden zij gemakkelijker nieuwe beleidsrichtingen bepalen. Degenen die voor de democratische overheid betalen, stellen zelden de voorwaarden vast voor overheidsuitgaven. In plaats daarvan functioneert de overheid als een coöperatie die enerzijds buiten particulier eigenaarschap opereert en anderzijds als een natuurlijk monopolie fungeert. Prijzen hebben weinig betrekking op de kosten. De kwaliteit van de dienstverlening is over het algemeen laag vergeleken met die in de private sector. Klachten van klanten zijn moeilijk te verhelpen. Kortom, massademocratie leidt tot de controle van de overheid door haar 'werknemers.'

Maar wacht. Je zou kunnen zeggen dat er in de meeste rechtsgebieden veel meer kiezers zijn dan er mensen op de loonlijst van de overheid staan. Hoe kan het dan mogelijk zijn dat werknemers zo'n dominante rol spelen? De verzorgingsstaat ontstond juist om dit dilemma op te lossen. Omdat er anders niet genoeg werknemers waren om een werkende meerderheid te vormen, werden steeds meer kiezers effectief op de loonlijst gezet om allerlei soorten overdrachtsuitkeringen te ontvangen. In feite werden de ontvangers van die uitkeringen en subsidies pseudo-overheidsmedewerkers, die het dagelijkse gedoe van naar het werk gaan konden overslaan. Dit was een gevolg van de megapolitieke logica van het industriële tijdperk.

Wanneer de omvang van de dwangkracht belangrijker is dan de efficiënte inzet van middelen – zoals het geval was voor 1989 – is het vrijwel onmogelijk dat de meeste overheden door hun klanten worden gecontroleerd. Zoals het voorbeeld van de laat overleden Sovjet-Unie zo treffend aantoonde, was het tot enkele jaren geleden mogelijk dat staten enorme macht uitoefenden in de wereld, zelfs terwijl zij op grote schaal middelen verspilden. Wanneer de opbrengsten van geweld hoog en stijgend zijn, weegt omvang zwaarder dan efficiëntie. Grotere entiteiten hebben de neiging de overhand te krijgen op kleinere. Overheden die effectiever zijn in het mobiliseren van militaire middelen – zelfs als dat veel verspilling inhoudt – overtreffen doorgaans degenen die middelen efficiënter inzetten.

Bedenk wat dit betekent. Het impliceert onvermijdelijk dat wanneer omvang belangrijker is dan efficiëntie, overheden die door hun klanten worden beheerst niet kunnen zegevieren en vaak zelfs niet kunnen overleven. Onder dergelijke omstandigheden zijn de entiteiten die militair het meest effectief zijn diegenen die de meeste middelen voor oorlog in beslag nemen. Maar overheden die daadwerkelijk door hun klanten, de betaalders, worden gecontroleerd, zullen hoogstwaarschijnlijk niet de vrije hand hebben om iedereen in de zak te graaien en middelen af te rommelen.

Klanten willen immers dat de prijzen die zij betalen voor elk product of elke dienst – inclusief bescherming – worden verlaagd en onder controle blijven. Als de westerse democratieën tijdens de Koude Oorlog daadwerkelijk door klanten waren beheerst, zou dat alleen al hebben betekend dat zij militair zwakkere concurrenten waren, omdat vrijwel zeker de toestroom van middelen naar de overheid zou zijn ingeperkt. Onthoud: waar klanten regeren, mogen zowel prijzen als kosten streng gecontroleerd worden. Maar dat is vrijwel niet gebeurd. De verzorgingsstaten bleken tijdens de Koude Oorlog duidelijk de winnaars van de uitgavenwedstrijd te zijn. Commentatoren van allerlei pluimage wezen er wel eens op dat een factor in hun triomf het vermogen was om de Sovjet-Unie in faillissement te spenderen.

Het is precies dit feit dat aantoont op welke wijze de inefficiënties van de democratie ervoor zorgden dat zij in een periode van stijgende opbrengsten uit geweld megapolitiek de overhand kreeg. Enorme militaire uitgaven, met al hun verspilling, vertegenwoordigen een duidelijk suboptimale inzet van kapitaal voor particuliere winst. We suggereerden eerder dat, hoewel verzorgingsstaten economisch efficiënt waren vergeleken met statssocialistische systemen, zij ver onderdoen in efficiëntie bij het creëren van welvaart in vergelijking met laissez-faireenclaves, zoals Hongkong. Ironisch genoeg was het juist deze inefficiëntie van de democratische verzorgingsstaat, in vergelijking met een meer onbelemmerd vrijemarktsysteem, die haar succesvol maakte in de megapolitieke omstandigheden van het industrialisme.

Hoe werd de door de democratie bevorderde inefficiëntie een factor in haar succes tijdens het tijdperk van geweld? De sleutel tot het ontrafelen van deze ogenschijnlijke paradox ligt in het erkennen van twee punten:

1. Het succes van een soevereiniteit in de moderne periode lag niet in het creëren van welvaart, maar in het vormen van een militaire macht die in staat was overweldigend geweld in te zetten tegen elke andere staat. Er was geld voor nodig, maar geld zelf kon een veldslag niet winnen. De uitdaging lag er niet in een systeem te creëren met de meest efficiënte economie of de snelste groeisnelheid, maar in een systeem te vormen dat meer middelen kon onttrekken en deze naar het leger kon leiden. Van nature zijn militaire uitgaven een domein waarin de financiële rendementen op zich laag of niet-bestaand zijn.

2. De eenvoudigste manier om toestemming te verkrijgen om geld te investeren in activiteiten met weinig of geen directe financiële opbrengst, zoals belastingbetalingen, is om toestemming te vragen van iemand anders dan de persoon van wiens geld begeerd wordt. Een van de redenen dat de Nederlanders Manhattan konden kopen voor kralen ter waarde van drieëntwintig dollar, is dat de specifieke Indianen aan wie zij hun aanbod deden niet de rechtmatige eigenaren waren. 'Getting to yes', zoals de marketeers zeggen, gaat onder die voorwaarden veel gemakkelijker. Stel bijvoorbeeld dat wij als auteurs van dit boek van u zouden verlangen, in plaats van de reguliere prijs, 40 procent van uw jaarlijkse inkomen te betalen voor een exemplaar. We zouden veel eerder toestemming verkrijgen om dat te doen als we iemand anders zouden vragen in plaats van u. Sterker nog, we zouden veel overtuigender overkomen als we in plaats daarvan konden rekenen op de toestemming van meerdere mensen die u zelfs niet kent. We zouden een ad-hoc verkiezing kunnen houden, zoals H. L. Mencken, met minder overdrijving dan hij mogelijk had gedacht, omschreven als 'een geavanceerde veiling van gestolen goederen'. En om het voorbeeld realistischer te maken, zouden we ermee instemmen een deel van het geld dat we van u innen te delen met deze anonieme toeschouwers in ruil voor hun steun.

Dat is de rol die de moderne democratische verzorgingsstaat is geëvolueerd om te vervullen. Het was in het industriële tijdperk een ongeëvenaard systeem omdat het daar waar het belangrijk telde zowel efficiënt als inefficiënt was. Het combineerde de efficiëntie van privébezit en de prikkels voor het creëren van welvaart met een mechanisme dat in wezen onbeperkte toegang tot die welvaart mogelijk maakte. De democratie hield de zakken van de welvaartscheppers open. Militair slaagde het tijdens de hoogtijdagen van de periode van stijgende opbrengsten uit geweld in de wereld, juist omdat het voor de burgers moeilijk werd gemaakt om effectief de belastingen, die de overheid introk, of andere financieringsmethoden voor de uitgaven aan het leger – zoals inflatie – te beperken.

### Waarom klanten niet konden domineren

Zij die in de moderne periode voor ‘bescherming’ betaalden, waren niet in de positie om, zelfs niet collectief, de staat de middelen te ontzeggen, omdat dat hen simpelweg het risico zou hebben opgeleverd om door andere, mogelijk vijandigere staten overweldigd te worden. Dit was een duidelijke overweging tijdens de Koude Oorlog. De klanten, oftewel belastingbetalers, die een onevenredig groot deel van de overheidskosten in de vooraanstaande westerse industriestaten droegen, waren geenszins in staat om hoge belastingen te weigeren. Het gevolg zou zijn geweest dat zij zich volledig hadden blootgesteld aan confiscatie door de Sovjet-Unie of een andere agressieve groep die in staat was om geweld te organiseren.

### Industrialisme en democratie

Op de lange termijn kan massademocratie een anakronisme blijken te zijn dat niet lang zal overleven na het einde van het industriële tijdperk. Zeker, massademocratie en de natiestaat ontstonden gelijktijdig met de Franse Revolutie aan het einde van de achttiende eeuw, vermoedelijk als reactie op een sterke stijging van het reële inkomen. Rond 1750 begonnen de inkomens in West-Europa aanzienlijk te stijgen, deels als gevolg van milder weer. Dit viel samen met een periode van technologische innovatie, waarin de vakbekwame beroepen van ambachtslieden werden vervangen door apparatuur die door ongeschoolde arbeiders – zelfs vrouwen en kinderen – bediend kon worden. Deze nieuwe industriële uitrusting verhoogde de lonen van ongeschoolde arbeiders, waardoor de inkomensverdeling egaler werd.

De doorslaggevende aanleiding voor een revolutie was mogelijk niet, zoals vaak wordt gedacht, het perverse idee dat mensen de neiging hebben in opstand te komen wanneer de omstandigheden verbeteren. Belangrijker is misschien het feit dat, zodra de inkomens een bepaald niveau hadden bereikt, het voor de vroegmoderne staat eindelijk haalbaar werd om de particuliere tussenpersonen en machtige magnaten waarmee zij voorheen middelen hadden bedongen, te omzeilen en over te stappen op een systeem van ‘direct bestuur’, waarbij een nationale overheid rechtstreeks met individuele burgers omging, hen steeds hoger belaste en slecht vergoede militaire dienst eiste in ruil voor het verlenen van diverse voordelen.[^174]

Omdat de opkomende middenklasse al snel genoeg geld bezat om te belasten, was het voor heersers niet langer essentieel, zoals voorheen, om te onderhandelen met machtige landeigenaren of grote kooplieden die, zoals historicus Charles Tilly schreef, "in staat waren te voorkomen dat er een machtige staat ontstond die hun bezittingen in beslag nam en hun transacties belemmerde."[^175] Het is gemakkelijk te zien waarom overheden succesvoller middelen onttrokken wanneer zij met miljoenen burgers individueel omgingen in plaats van met een relatief handvol heren, hertogen, graven, bisschoppen, contract-huurlingen, vrije steden en andere semi-soevereine entiteiten met wie de heersers van Europese staten vóór het midden van de achttiende eeuw verplicht waren te onderhandelen.

Stijgende reële inkomens stelden overheden in staat een strategie te hanteren die meer middelen onder hun controle bracht. Kleine bedragen die van miljoenen aan belastingen werden geheven, konden meer inkomsten genereren dan de grotere sommen die door enkele machtige personen werden betaald. Bovendien waren de velen veel gemakkelijker om mee om te gaan dan de weinigen, die over het algemeen niet bereid waren hun geld af te staan en veel beter in staat waren weerstand te bieden.

Tenslotte beschikte de typische boer, kleine koopman of arbeider over vrijwel onbeduidende middelen vergeleken met de staat zelf. Het was zelfs niet mogelijk dat de gemiddelde particulier in West-Europa op de vooravond van de Franse Revolutie effectief met de staat had kunnen onderhandelen om zijn belastingtarief te verlagen of effectieve weerstand bood tegen overheidsplannen en -beleid die zijn belangen bedreigden. Maar dit is precies wat machtige particuliere magnaten al eeuwenlang deden en zouden blijven doen. Zij boden effectieve weerstand en onderhandelden met de heersers, waardoor hun vermogen om middelen in beslag te nemen werd beperkt.

> "De oorlogsvoering versnelde de overgang van indirecte naar directe heerschappij. Bijna elke staat die oorlog voert, ontdekt dat zij de inspanning niet kan bekostigen met haar opgebouwde reserves en actuele inkomsten. Bijna alle oorlogvoerende staten lenen in ruime mate, verhogen de belastingen en grijpen de middelen van de strijd – inclusief mannen – weg van terughoudende burgers die andere toepassingen voor hun middelen hadden."[^176] - Charles Tilly

Het voorbeeld van Polen in het midden van de achttiende eeuw illustreert dit perfect. In 1760 telde het Poolse nationale leger achttien duizend soldaten. Dit was een magere strijdmacht vergeleken met de legers die werden geleid door de heersers van naburige Oostenrijk, Pruisen en Rusland, van wie de minste in staat was een staand leger van 100.000 soldaten te controleren. In feite was het Poolse nationale leger in 1760 zelfs klein vergeleken met andere bewapende eenheden binnen Polen. De gecombineerde strijdkrachten van de Poolse adel bedroegen dertig duizend man.[^177]

Als de Poolse koning rechtstreeks contact had kunnen leggen met miljoenen individuele Polen en hen direct had kunnen belasten, in plaats van beperkt te zijn tot het indirect onttrekken van middelen via de bijdragen van de machtige Poolse magnaten, bestaat er weinig twijfel dat de Poolse centrale regering in staat zou zijn geweest om veel meer inkomsten te genereren en daarmee een groter leger te bekostigen.

Tegenover gewone individuen, die niet in staat waren in samenwerking met miljoenen andere gewone individuen op te treden, bleken de centrale autoriteiten overal onweerstaanbaar machtig te zijn. Maar de Poolse koning had in 1760 niet de optie om zijn burgers direct te belasten. Hij moest via de heren, rijke kooplieden en andere vooraanstaanden te werk gaan, een kleine, hechte groep die gezamenlijk kon en deed optreden om te voorkomen dat de koning zonder hun toestemming hun middelen zou onteigenen. Aangezien de Poolse adel veel meer troepen beschikbaar had dan hij, was de koning geenszins in de positie om hierop aan te dringen.

Zoals bleek, was het militaire nadeel van het niet kunnen omzeilen van de invloed van de rijke en machtige partijen bij het vergaren van middelen doorslaggevend in het Tijdperk van Geweld. Binnen enkele jaren hield Polen op te bestaan als een onafhankelijk land. Het werd veroverd door invallen vanuit Oostenrijk, Pruisen en Rusland, drie landen waarvan elk leger vele malen groter was dan de kleine Poolse strijdmacht. In elk van die landen hadden de heersers manieren gevonden om de weerstand van de rijke kooplieden en de adel tegen de onteigening van hun middelen te omzeilen.

### Na de Franse Revolutie

De Franse Revolutie leidde tot een nog grotere toename in de omvang van legers, hetgeen de kracht van de democratische strategie aantoonde in een tijd waarin de opbrengsten van geweld toenamen. De overeenkomst die de regeringen vanaf de Franse Revolutie sloten, hield in dat zij een ongekende mate van betrokkenheid in het leven van gewone mensen boden, in ruil voor hun deelname aan oorlogen ter vervanging van huurlingen, en dat zij hen belastten met een steeds zwaardere belastingdruk als gevolg van hun stijgende inkomens.

Zoals Tilly zei,

> De reikwijdte van de staat breidde zich ver buiten haar militaire kern uit, en haar burgers begonnen aanspraken op een breed scala aan bescherming, rechtspraak, productie en distributie te maken. Naarmate de nationale parlementen hun bevoegdheden ver uitstrekten, veel verder dan slechts het goedkeuren van belastingen, werden zij al snel het doelwit van aanspraken van alle goed georganiseerde groepen wier belangen door de staat werden beïnvloed of hadden kunnen worden beïnvloed. Rechtstreekse heerschappij en massale nationale politiek ontwikkelden zich gelschakeld en versterkten elkaar krachtig.[^178]

Dezelfde logica die in de achttiende eeuw gold, bleef van toepassing tot 1989, toen de Berlijnse Muur viel. Naarmate het industriële tijdperk vorderde, bleven de inkomens voor ongeschoold werk stijgen, waardoor massademocratie een nog effectievere methode werd om de winning van middelen te optimaliseren. Als gevolg daarvan groeide de overheid gestaag, zodat haar totale aanspraken op het jaarlijkse inkomen in het gemiddelde industriële land over de twintigste eeuw met ongeveer 0,5 procent toenamen.

In het industriële tijdperk voorafgaand aan 1989 bleek de democratie de militair gezien meest effectieve vorm van regering te zijn, juist omdat democratie het moeilijk of onmogelijk maakte effectieve grenzen te stellen aan de inbeslagname van middelen door de staat. Het genereuze verstrekken van sociale zekerheidsuitkeringen aan iedereen nodigde de meerderheid van de kiezers uit om in feite werknemers van de overheid te worden. Dit werd de overheersende politieke eigenschap van alle leidende industriële landen, omdat kiezers in de rol van klanten voor beschermingsdiensten in een zwakke positie verkeerden om de overheid effectief te controleren. Zij stonden niet alleen oog in oog met de agressieve dreiging van communistische systemen, die enorme middelen voor militaire doeleinden konden mobiliseren doordat de staat de gehele economie beheerste, maar ook een daadwerkelijke controle door belastingbetalers over de overheid was om een andere reden onpraktisch.

Miljoenen gewone burgers kunnen niet effectief samenwerken om hun belangen te beschermen. Omdat de obstakels voor samenwerking groot zijn en de opbrengst voor een individu dat succesvol de gemeenschappelijke belangen verdedigt minimaal is, zullen miljoenen gewone burgers minder succesvol hun bezittingen voor de overheid weten af te schermen dan kleinere groepen met gunstiger prikkels.

Alle andere zaken gelijk, zou men daarom verwachten dat een hoger aandeel van de totale middelen door de overheid in beslag wordt genomen in een massademocratie dan in een oligarchie, of in een systeem van gefragmenteerde soevereiniteit waarin magnaten militaire macht uitoefenden en hun eigen legers op de been brachten, zoals dat in heel het vroegmoderne Europa gebeurde vóór de achttiende eeuw.

Zo is een cruciale, hoewel zelden onderzochte, reden voor de groei van de democratie in de westerse wereld het relatieve belang van onderhandelingskosten in een periode waarin de opbrengsten van geweld toenamen. Het was altijd kostbaarder om middelen aan de weinigen te onttrekken dan aan de velen.

Een relatief kleine, elitegroep van rijken vormt een coherenter en effectiever geheel dan een grote massa burgers. De kleine groep heeft sterkere prikkels om samen te werken. Zij zal bijna onvermijdelijk effectiever zijn in het beschermen van haar belangen dan een massagroep.[^179] En zelfs als de meeste leden van de groep ervoor kiezen niet mee te werken aan een gezamenlijke actie, kunnen enkelen die rijk zijn wellicht voldoende middelen inzetten om de klus te klaren.

Met democratische besluitvorming kon de natiestaat haar macht veel vollediger uitoefenen over miljoenen mensen, die niet eenvoudigweg gezamenlijk in hun eigen belang konden handelen, danwel in het omgaan met een veel kleiner aantal dat gemakkelijker de organisatorische moeilijkheden van het verdedigen van zijn geconcentreerde belangen kon overwinnen. De democratie had bovendien het overtuigende voordeel dat zij een legitimerende beslissingsregel creëerde, waardoor de staat de middelen van de welgestelden kon aanwenden zonder dat er rechtstreeks over hun toestemming hoefde te worden onderhandeld. Kortom, de democratie als besluitvormingsmechanisme paste uitstekend bij de megapolitieke omstandigheden van het industriële tijdperk. Zij vulde de natiestaat aan doordat zij de concentratie van militaire macht in de handen van de bestuurders mogelijk maakte in een tijd waarin de omvang van de toegepaste kracht belangrijker was dan de efficiëntie waarmee deze werd gemobiliseerd.

Dit werd ondubbelzinnig aangetoond door de Franse Revolutie, die de omvang van de militaire kracht op het slagveld vergrootte. Daarna hadden andere concurrerende natiestaten weinig keuze dan over te gaan op een vergelijkbare organisatie, waarbij de legitimiteit uiteindelijk verbonden was met democratische besluitvorming. Samengevat slaagde de democratische natiestaat in de afgelopen twee eeuwen dankzij deze verborgen redenen:

1. Er was sprake van toenemende opbrengsten uit geweld, waardoor de omvang van het geweld belangrijker werd dan efficiëntie als bestuursprincipe.  
2. De inkomens stegen zodanig boven het overlevingsniveau dat de staat in staat was grote hoeveelheden middelen te innen zonder te hoeven onderhandelen met machtige magnaten die weerstand konden bieden.  
3. De democratie bleek zodanig compatibel met de werking van vrije markten dat zij de totstandbrenging van een steeds grotere hoeveelheid welvaart mogelijk maakte.  
4. De democratie stelde haar ‘ambtenaren’ in staat de overheid te domineren, waardoor het lastig werd om de uitgaven – inclusief de militaire – te beperken.  
5. De democratie als besluitvormingsprincipe bleek een effectief tegengif voor het vermogen van de rijken om gezamenlijk op te treden en daarmee de capaciteit van de natiestaat te beperken om hen te belasten of om op een andere wijze hun bezittingen tegen invasie te beschermen.

De democratie werd de militair zegevierende strategie omdat zij het mogelijk maakte om meer middelen in handen van de staat te concentreren. Vergeleken met andere vormen van soevereiniteit die hun legitimiteit ontleenden aan andere principes, zoals de feodale heffing, het goddelijk recht van koningen, de collectieve religieuze plicht of de vrijwillige bijdragen van de rijken, bleek de massale democratie militairal gezien de krachtigste, omdat zij de zekerste manier vormde om in een industriële economie middelen bijeen te brengen.

> 'De natie, als een cultureel gedefinieerde gemeenschap, vertegenwoordigt de hoogste symbolische waarde van de moderniteit; zij is uitgerust met een quasi-heilig karakter dat slechts door de religie geëvenaard wordt. Inderdaad, dit quasi-heilige karakter vindt zijn oorsprong in de religie. In de praktijk is de natie ofwel de moderne, seculiere vervanger van de religie geworden, ofwel haar machtigste bondgenoot. In de moderne tijd worden de door de natie opgewekte gemeenschappelijke sentimenten hoog gewaardeerd en nagestreefd als basis voor groepsloyaliteit... Dat de moderne staat vaak de begunstigde is, zou gezien haar overweldigende macht geenszins verrassend moeten zijn.'[^180] - JOSEPH R. LLOBERA

### Nationalisme

Hetzelfde geldt voor het nationalisme, dat een logisch gevolg werd van de massale democratie. Staten die het nationalisme konden benutten, ontdekten dat zij grotere legers konden mobiliseren tegen lagere kosten. Nationalisme was een uitvinding waardoor een staat in staat werd gesteld de schaal van haar militaire effectiviteit te vergroten. Net als de politiek zelf is nationalisme grotendeels een moderne uitvinding. Zoals socioloog Joseph Llobera aantoont in zijn rijk gedocumenteerde boek over de opkomst van het nationalisme, is de natie een denkbeeldige gemeenschap die in grote mate is ontstaan als een middel om de staatsmacht te mobiliseren tijdens de Franse Revolutie. Zoals hij het verwoordt, 'In de moderne zin van het begrip heeft nationaal bewustzijn pas bestaan sinds de Franse Revolutie, sinds de tijd dat in 1789 de Constituerende Vergadering het volk van Frankrijk gelijkstelde aan de Franse natie.'[^181]

Nationalisme maakte het eenvoudiger om macht te mobiliseren en grote aantallen mensen te beheersen. Natiestaten werden gevormd door de kenmerken die mensen gemeen hadden – in het bijzonder de gesproken taal – te benadrukken. Dit maakte bestuur zonder tussenpersonen mogelijk en vereenvoudigde de taken van de bureaucratie. Erloven die slechts in één taal hoeven te worden uitgevaardigd, kunnen sneller en met minder verwarring worden verstuurd dan die welke in een babel aan talen vertaald moeten worden. Nationalisme verlaagde derhalve de kosten van het beheersen van grotere gebieden. Vóór het nationalisme had de vroegmoderne staat de hulp nodig van heren, hertogen, graven, bisschoppen, vrije steden en andere corporatieve en etnische tussenpersonen, variërend van belastingverzamelaars tot militaire contracthandelaars en huurlingen, om inkomsten te innen, troepen op te richten en andere overheidsfuncties uit te voeren.

Nationalisme verlaagde ook beslissend de kosten van de mobilisatie van militair personeel door de groepsidentificatie met de belangen van de staat te stimuleren. Er was zo’n aanzienlijk voordeel te behalen bij het aanwakkeren van een collectief gevoel in dienst van de staat, dat de meeste staten – zelfs de zogenaamd internationalistische Sovjet-Unie – zich op nationalisme als aanvullende ideologie instelden.

In een breder perspectief gezien is nationalisme evenzeer een anomalie als de staat zelf. Zoals historicus William McNeill heeft aangetoond, waren polyetnische soevereiniteiten in het verleden de norm.[^182]

Volgens McNeill zelf: ‘Het idee dat een regering rechtmatig slechts over burgers van één etnische groep zou moeten heersen, begon zich tegen het einde van de middeleeuwen in West-Europa te ontwikkelen.’[^183] Een vroege nationalistische entiteit was de Pruisische Bond (Preussicher Bund), die in 1440 werd opgericht als verzet tegen de heerschappij van de Teutoonse Orde. Enkele kenmerken van de orde werden eerder benadrukt als een duidelijk voorbeeld van een soevereiniteit die sterk afwijkt van de natiestaat. De Teutoonse Orde was een soort charterbedrijf waarvan vrijwel geen van de leden inheemse Pruisenaren waren. Haar hoofdkantoor verschoof in de loop der tijd van Bremen en Lübeck naar Jeruzalem, vervolgens naar Acre, naar Venetië en daarna naar Marienberg aan de Wisła. Op een gegeven moment regeerde zij ook over het district Burzenland in Transsylvanië. Het is dan ook niet verwonderlijk dat een soevereiniteit die zo radicaal verschilt van een staat, het doelwit werd van een van de eerste pogingen om het nationale gevoel als machtfactor te mobiliseren. Als aanwijzing voor hoe verschillend het vroege nationalisme was ten opzichte van latere vormen, dienden de Duitssprekende edelen van de Pruisische Bond een petitie in bij de Poolse koning om Pruisen onder Poolse heerschappij te brengen – grotendeels omdat de Poolse koning, zelfs toen al, een relatief zwakke monarch bleek te zijn die niet naar verwachting met dezelfde strengheid zou regeren als de Teutoonse Orde.

Nationalisme in zijn vroege vormen trad in beeld net voorafgaand aan de buskruitrevolutie. Het bleef zich ontwikkelen naarmate de vroegmoderne staat vorm kreeg en maakte een enorme sprong in belang tijdens de Franse Revolutie. Wij zijn van mening dat nationalisme als krachtidee inmiddels begonnen is af te nemen. Het bereikte waarschijnlijk zijn hoogtepunt met Woodrow Wilsons poging om aan elke etnische groep in Europa aan het einde van de Eerste Wereldoorlog een eigen staat te gunnen. Tegenwoordig is het een reactionaire kracht die, vooral op plekken met dalende inkomens en verslechterende vooruitzichten – zoals in Servië – oplaait.

Zoals we later zullen bespreken, verwachten wij dat nationalisme een belangrijk verzamelthema zal worden voor mensen met beperkte vaardigheden die heimwee hebben naar een samenleving waarin dwang een rol speelde, nu de verzorgingsstaat instort in de westerse democratieën. Je hebt nog niets gezien. Voor de meeste mensen in het Westen leek de nasleep van de dood van het communisme relatief goedaardig: je hebt een daling in de militaire uitgaven gezien, een scherpe ineenstorting van de aluminiumprijzen en een nieuwe bron van hockeyspelers voor de NHL. Dat is het goede nieuws – nieuws waarover de meeste mensen die volwassen werden in de twintigste eeuw voor konden applaudisseren, zeker als ze hockeyfans zijn. Het merendeel van het nieuws dat minder populair zal blijken te zijn, moet nog komen.

Met het voorbijgaan van het industriële tijdperk verdwijnen de megapolitieke voorwaarden waaraan de democratie voldeed in rap tempo. Daarom is het twijfelachtig of de massademocratie en de verzorgingsstaat lang zullen voortbestaan in de nieuwe megapolitieke omstandigheden van het informatietijdperk.

> 'Het congres was geen tempel van democratie, het was een markt voor het ruilen van wetten.' - Alberto Fujimori, president van Peru

Inderdaad, toekomstige historici zouden kunnen melden dat we al getuige zijn geweest van de eerste postmoderne staatsgreep – de opmerkelijke vergrendeling van het congres in Peru in 1993. Dit was nauwelijks een gebeurtenis die in de toonaangevende industriële democratieën gunstig werd opgemerkt. Maar het zou uiteindelijk meer kunnen betekenen dan conventionele analisten suggereren. De weinigen die erover hebben nagedacht, zien het meestal als nog een machtsgreep van de soort die in de geschiedenis van Latijns-Amerika deprimerend bekend is geworden. Wij zien het echter als mogelijk de eerste stap richting de delegitimatie van een bestuursvorm waarvan de onmiddellijke megapolitieke bestaansreden met de overgang naar het informatietijdperk begon te verdwijnen. Fujimori’s sluiting van het congres is een symptoom van de uiteindelijke devaluatie van politieke beloften. Een soortgelijk lot kan andere wetgevende organen te wachten staan wanneer hun krediet is uitgeput.

De technologische verschuiving die het industrialisme ondermijnt, heeft veel landen gevangen die worden bestuurd door regeringen die niet meer functioneren – of slecht functioneren. Wetgevende organen lijken in het bijzonder steeds disfunctioneler te worden. Zij produceren wetten die vijftig jaar geleden wellicht simpelweg dom waren, maar tegenwoordig gevaarlijk blijken te zijn. Dit werd in Peru op spectaculaire wijze duidelijk, waar de interne soevereiniteit van de staat in 1993 bijna instortte.

> 'Aanvallen, ontvoeringen, verkrachtingen en moorden gingen gepaard met steeds agressievere rijgewoonten en onveilige straten. De politie verloor geleidelijk de controle over de situatie en enkele van haar leden raakten betrokken bij schandalen en werden doorgewinterde criminelen… Mensen raakten er geleidelijk aan gewend buiten de wet te leven. Diefstal, illegale inbeslagname en bedrijfsovernames werden aan de orde van de dag.'[^184] - Hernando de Soto

### Peru in ruïnes

In zekere zin was Peru in 1993 geen moderne natiestaat meer. Het had nog een vlag en een leger, maar de meeste van haar instituties lagen in puin. Zelfs de gevangenissen waren door de gedetineerden overgenomen. Deze desintegratie had verschillende oorzaken, maar de meeste pogingen van deskundigen om het te verklaren, missen de kern. Peru was een vroeg slachtoffer van de technologische veranderingen die gesloten economieën disfunctioneel maken en overal de centrale autoriteit ondermijnen. Deze megapolitieke spanningen worden verergerd doordat besluitvormingsinstellingen zoals het Peruaanse congres door perverse prikkels gedwongen worden om juist de problemen te verergeren die zij eigenlijk zouden moeten oplossen.

De representatieve democratie in Peru was als een paar geladen dobbelstenen. Als mechanisme om de staat te vergroten was ze onovertroffen. Maar wanneer nieuwe omstandigheden om een verschuiving van macht vroegen, maakten de inherente vooringenomenheden die de democratie onder de oude megapolitieke omstandigheden zo nuttig hadden gemaakt, het systeem steeds disfunctioneler. De wetten die door het congres werden aangenomen, ondermijnden in rap tempo elke basis voor waarde en respect voor de wet. Zoals de Soto het verwoordde in The Other Path, "Kleine belangengroepen ruziën met elkaar, veroorzaken faillissementen en betrekken ambtenaren. Overheden schenken privileges toe. De wet wordt gebruikt om veel meer te geven en af te nemen dan de moraal toelaat." [^185] Een congres als dat in Peru, volledig in de ban van belangengroepen, heeft dezelfde morele status als een bende vuilkopers die gestolen goederen veilen. Het maakte de vrije markt illegaal, waardoor de wet belachelijk werd. Zoals de Soto schrijft over de periode voor Fujimori:

> Een volledige ommekeer van doelen en middelen heeft het leven in de Peruaanse samenleving op zijn kop gezet, tot op het punt dat er handelingen plaatsvinden die, hoewel officieel strafbaar, niet langer door het collectieve bewustzijn worden veroordeeld. Smokkelen is daar een treffend voorbeeld van. Iedereen, van de aristocratische dame tot de nederigste man, verwerft gesmokkelde goederen. Niemand heeft er scrupules over; integendeel, het wordt gezien als een soort uitdaging voor de individuele vindingrijkheid of als wraak op de staat. Deze infiltratie van geweld en criminaliteit in het dagelijks leven gaat gepaard met een toenemende armoede en ontbering. In algemene zin was het reële gemiddelde inkomen van de Peruanen de afgelopen tien jaar gestaag gedaald en bevindt het zich nu op het niveau van twintig jaar geleden. Aan alle kanten hopen bergen afval zich op. Dag en nacht omsingelen legioenen bedelaars, autowassers en aaseters de voorbijgangers, op zoek naar geld. De geestelijk zieken zwermen naakt door de straten, stinkend van urine. Kinderen, alleenstaande moeders en gehandicapten bedelen op elke straathoek om aalmoezen. Het traditionele centralisme van onze samenleving heeft duidelijk niet voldaan aan de vele behoeften van een land in transitie.[^186]

De Soto omschreef het loslaten van de groteske juridische economie ten gunste van de zwarte markt – een ontwikkeling die al in gang was gezet vóórdat Fujimori het congres op slot sloot – als "een onzichtbare revolutie."

Wij zijn positief over de voordelen van de vrije markt, maar veel minder enthousiast over de belofte van een samenleving waarin de wet net zo vervallen is als het geld. De wereld die de Soto in Peru beschreef, vóór 1993, was een 'Clockwork Orange'-wereld, waarin overmatig gecentraliseerde en dysfunctionele overheidsinstellingen letterlijk de burgermaatschappij vernietigden.

Dit was wat Fujimori wilde veranderen. Hij had de inflatie drastisch verlaagd door de geldpersen stil te leggen. Ook slaagde hij erin vijftigduizend overheidsmedewerkers te ontslaan en enkele subsidies terug te schroeven. Hij had een begin gemaakt met het in evenwicht brengen van de begroting. Zijn hervormingsprogramma omvatte uitgebreide plannen om vrije markten te realiseren en de industrie te privatiseren. Maar, zoals in de voormalige Sovjet-Unie, waren in 1993 de meeste belangrijke elementen van Fujimori's hervorming nog niet aangenomen, waaronder de eerste ronde van grootschalige privatisering van staatsbanken, mijnbouwbedrijven en nutsbedrijven. In plaats van deze noodzakelijke voorstellen door te voeren, trachtte het congres van Peru, net als het Russische congres dat Yeltsins hervormingen in Moskou uitdaagde, een stap terug te zetten. Hun plan: subsidies herstellen vanuit een lege schatkist, de loonlijst opblazen en alle gevestigde belangen beschermen, vooral de bureaucratie—precies wat je zou verwachten van een regering die door haar eigen werknemers wordt beheerst.

Fujimori beweerde dat het congres van Peru aarzelend en corrupt was, een bewering waar bijna iedereen het mee eens was. Hij stelde verder dat deze aarzelende en corrupte gang van zaken in het congres het onmogelijk maakte om de ineenstortende economie van Peru te hervormen of een gewelddadige aanval van narco-terroristen en nihilistische guerrilla's van het Sendero Luminoso (Shining Path) te bestrijden.

### De 70-procentoplossing

Dus sloot Fujimori het congres, een daad die zou kunnen aantonen dat hij net zo autoritair was als vele eerdere Latijns-Amerikaanse leiders. Maar wij waren van mening – en zeiden dat destijds – dat Fujimori een fundamenteel obstakel voor hervorming correct had geïdentificeerd. De uitbundige officiële lofzangen op het Peruaanse congres, geprezen door Amerikaanse opiniemakers en functionarissen van het Ministerie van Buitenlandse Zaken, werden door het Peruaanse volk niet gedeeld. Terwijl Noord-Amerikanen in hun gang doorgingen alsof het congres van Peru de belichaming van vrijheid en beschaving was, juichte het Peruaanse volk. De populariteit van president Fujimori schoot boven de 70 procent uit toen hij het congres naar huis stuurde. Later werd hij met een verpletterende meerderheid herkozen voor een tweede termijn. De meeste burgers beschouwden hun wetgevende macht blijkbaar meer als een hindernis voor hun welzijn dan als een uiting van hun rechten. In 1994 behaalde de reële economische groei in Peru 12,9 procent, het hoogste ter wereld.

### Deflatie van politieke beloften

We zagen de onrust in Peru minder als een terugkeer naar dictatorschappen uit het verleden dan als een eerste episode van een bredere transitiecrisis. Je kunt verwachten dat in veel landen wanbestuurcrises zullen ontstaan naarmate politieke beloften leeglopen en regeringen door hun krediet heen zijn. Uiteindelijk zullen nieuwe institutionele vormen moeten opduiken die in staat zijn de vrijheid te bewaren onder de nieuwe technologische voorwaarden, terwijl ze tegelijkertijd de gemeenschappelijke belangen die alle burgers delen, tot uitdrukking brengen en levend houden.

Weinigen zijn begonnen na te denken over de onverenigbaarheid tussen enkele instituties van het industriële bestuur en de megapolitiek van de postindustriële samenleving. Of deze tegenstellingen nu expliciet worden erkend of niet, hun gevolgen zullen steeds duidelijker worden naarmate voorbeelden van politiek falen zich wereldwijd opstapelen. De in de moderne periode voortgekomen regeringsinstellingen weerspiegelen de megapolitieke condities van één of meerdere eeuwen geleden. Het informatietijdperk zal nieuwe representatiemechanismen vereisen om chronische disfunctie en zelfs maatschappelijk verval te voorkomen.

Toen de Berlijnse Muur in 1989 viel, betekende dit niet alleen het einde van de Koude Oorlog; het was tevens het uiterlijke teken van een stille aardbeving in de fundamenten van de mondiale machtsstructuur. Het markeerde het einde van een lange periode waarin de opbrengst van geweld gestaag toenam. De val van het communisme – voorspeld door ons in 1987 in Blood in the Streets en zelfs eerder in onze maandelijkse nieuwsbrief Strategic Investment – was niet louter een afwijzing van een ideologie. Het was het zichtbare teken van de belangrijkste ontwikkeling in de geschiedenis van geweld in de afgelopen vijf eeuwen. Als onze analyse klopt, zal de organisatiestructuur van de samenleving onvermijdelijk veranderen om de groeiende diseconomieën van schaal in het gebruik van geweld te weerspiegelen. De grenzen waarbinnen de toekomst vorm moet krijgen, zijn hertekend.

[^163]: Geciteerd in Tilly, op. cit., p.84.

[^164]: Zie John Keegan, *A History of Warfare* (London: Hutchinson, 1993), p.321.

[^165]: Jim Taylor en Watts Wacker, The 500-Year Delta: What Happens After What Comes Next. New York: HarperCollins, 1997, pp. 38-39.

[^166]: Ibid., p. 39.

[^167]: The Cambridge Ancient History, op. cit., pp.263-64.

[^168]: Cook et al., op. cit., p.268.

[^169]: Voor meer over de logica van hydraulische samenlevingen, zie Karl A. Wittfogel, *Orientaal despotisme: Een vergelijkende studie van totale macht* (New Haven: Yale University Press, 1957).

[^170]: Tilly, op. cit., p.28.

[^171]: Lane, ‘Gevolgen van georganiseerd geweld’, op. cit., p.406.

[^172]: Ibid.

[^173]: Ibid., p.412.

De inhoud van het boek dat vertaald moet worden is: 

[^174]: Tilly, op. cit., pp.96-126.

[^175]: Ibid., p.130.

[^176]: Ibid., p.110.

[^177]: Dit voorbeeld in ibid., p.139.

[^178]: Ibid., p.115.

[^179]: Zie Mancur Olson, *The Logic of Collective Action* (Cambridge: Harvard University Press, 1965).

[^180]: Josep R. Llobera, *The God of Modernity: The Development of Nationalism in Western Europe* (Oxford: Berg Publishers, 1994), pp. ix-x.

[^181]: Ibid., p. xiii.

[^182]: Zie William McNeill, *Polyethnicity and National Unity in World History* (Toronto: University of Toronto Press, 1986).

[^183]: Ibid., p.7.

[^184]: Hernando de Soto, *The Other Path* (New York: Harper & Row, 1989).

[^185]: Ibid.

[^186]: Ibid., p.6.