# DE MEGAPOLITIEK VAN HET INFORMATIETIJDPERK

::: {.content-hidden when-format=latex}
*De triomf van efficiëntie boven macht*
:::

> '...het is gecomputeriseerde informatie, niet arbeidskracht of massaproductie, die steeds meer de Amerikaanse economie aandrijft en die oorlogen zal winnen in een wereld die is verbonden met 500 tv-kanalen. De gecomputeriseerde informatie bestaat in cyberspace - de nieuwe dimensie die is gecreëerd door de eindeloze reproductie van computernetwerken, satellieten, modems, databases en het publieke internet'[^187]: - NEIL MUNRO

Op 30 december 1936 grepen autowerkers, die op zoek waren naar hogere lonen, met geweld twee van de hoofdvestigingen van General Motors in Flint, Michigan in beslag. Zij legden de machines stil, schakelden de lopende banden uit en maakten het zich thuis. Werknemers, die waren aangesteld om de fabrieken te bedienen, gingen in een zitstaking zitten, een industriële confrontatie die vele weken zou duren. Het was een drama, gekenmerkt door gewelddadige rellen en wisselende loyaliteiten van de politie, de militie van Michigan en politieke figuren op alle overheidsniveaus. Toen de vakbond weinig vooruitgang boekte in het afdwingen van hun eisen, sloeg zij op 1 februari 1937 opnieuw toe.

Vakbondsactivisten namen met geweld de Chevrolet-fabriek van GM in Flint in beslag. Door de belangrijkste fabrieken van General Motors te bezetten en te sluiten, verlamden de arbeiders effectief de productiecapaciteit van het bedrijf. In de tien dagen na de inbeslagname van de derde fabriek produceerde GM slechts 153 auto's in de Verenigde Staten.

We blikken opnieuw terug op deze nieuwsflits van zestig jaar geleden om de revolutie in de megapolitieke omstandigheden die zich nu ontvouwen in een helderder perspectief te plaatsen. De bezettingsstaking bij GM vond plaats binnen de levensspanne van sommige lezers van dit boek. Toch zijn wij ervan overtuigd dat bezettingsstakingen in het informatietijdperk net zo anachronistisch zullen blijken als slaven, ploeterend door de woestijn en met gigantische stenen achter zich sleepend om begrafenispiramides voor de farao’s te bouwen. Terwijl vakbonden en hun intimidatietactieken tijdens de industriële periode zo vertrouwd raakten dat zij onbetwist onderdeel werden van het sociale landschap, waren zij afhankelijk van bijzondere megapolitieke omstandigheden die in rap tempo verdwijnen. Er zullen op de Information Superhighway geen Chevrolets zijn en ook geen UAW die in staking gaat.

Het fortuin van regeringen zal in verval raken, net als dat van hun tegenhangers, de vakbonden. Geginstitutionaliseerde dwang, die een cruciale rol speelde in de samenleving van de twintigste eeuw, zal niet langer mogelijk zijn. Technologie brengt een ingrijpende verandering teweeg in de logica van afpersing en bescherming.

> " ... er is geen eigendom, geen heerschappij, geen duidelijk onderscheid tussen 'de mijne en de jouwe'; maar slechts datgene dat iedere man kan bemachtigen, en zolang hij het kan behouden."[^188]: -THOMAS HOBBES

### Afpersing en Bescherming

Door de geschiedenis heen is geweld als een dolk op het hart van de economie gericht geweest. Zoals Thomas Schelling scherpzinnig opmerkte: "De macht om te kwetsen – om dingen te vernietigen die iemand dierbaar zijn, om pijn en verdriet toe te brengen – is een soort onderhandelingsmacht, niet eenvoudig te hanteren, maar vaak gebruikt. In de onderwereld vormt het de basis voor chantage, afpersing en ontvoering, in de commerciële wereld voor boycots, stakingen en lock-outs... Het is vaak de basis voor discipline, zowel civiel als militair; en goden gebruiken het om discipline af te dwingen."[^189]

De capaciteit van een overheid om belastingen te heffen, hangt af van dezelfde kwetsbaarheden als die ten grondslag liggen aan particuliere afpersing en chantage. Hoewel we dit niet zo benaderen, geeft de verhouding van bezittingen die op dwang worden gecontroleerd en besteed – door middel van criminaliteit en door de overheid – een ruwe maatstaf voor de megapolitieke balans tussen afpersing en bescherming. Als technologie de bescherming van bezittingen moeilijk zou maken, zou criminaliteit wijdverspreid zijn, en zou ook de activiteit van vakbonden toenemen. Onder dergelijke omstandigheden zou bescherming door de overheid derhalve een premie vergen. De belastingen zouden hoog zijn. Waar belastingen lager zijn en de loonprijzen op de werkvloer bepaald worden door marktwerking in plaats van door politieke interventie of dwang, heeft technologie de balans in het voordeel van bescherming doen verschuiven.

De technologische scheefgroei tussen afpersing en bescherming bereikte een extreem niveau aan het einde van het derde kwartaal van de twintigste eeuw. In sommige geavanceerde westerse samenlevingen werden meer dan de helft van de middelen door regeringen in beslag genomen. De inkomens van een groot deel van de bevolking werden óf op fiat vastgesteld, óf bepaald onder invloed van dwang, bijvoorbeeld door stakingen en bedreigingen met geweld in andere vormen. De verzorgingsstaat en de vakbond waren allebei producten van technologie, die de buit deelden van de triomf van macht boven efficiëntie in de twintigste eeuw. Zij hadden niet kunnen bestaan indien niet de militaire en civiele technologieën hadden bestaan die in het industriële tijdperk het gebruik van geweld lonender maakten.

Het vermogen om activa te creëren ging altijd gepaard met een zekere kwetsbaarheid voor afpersing. Hoe groter de gecreëerde of in bezit zijnde activa, des te hoger de prijs die op de een of andere manier betaald moet worden. Ofwel betaalde je iedereen die de macht had om geweld in te zetten voor afpersing, ofwel betaalde je voor een militaire macht die iedere poging tot afpersing met brute kracht kon verijdelen.

> 'Geweld zal niet langer in uw land te horen zijn, noch verwoesting binnen uw grenzen...' - ISAIAH 60:1

### De wiskunde van bescherming

Nu kon de dolk van geweld spoedig getemperd worden. Informatie­technologie belooft de balans tussen bescherming en afpersing drastisch te veranderen, waardoor de bescherming van activa in veel gevallen veel gemakkelijker wordt en afpersing moeilijker. De technologie van het informatietijdperk maakt het mogelijk activa te creëren die buiten het bereik liggen van vele vormen van dwang. Deze nieuwe asymmetrie tussen bescherming en afpersing rust op een fundamentele waarheid van de wiskunde: vermenigvuldigen is eenvoudiger dan delen. Hoe fundamenteel deze waarheid ook is, de verstrekkende gevolgen ervan waren tot aan de komst van microprocessors nog verborgen. Highspeedcomputers hebben in het afgelopen decennium miljarden malen meer berekeningen uitgevoerd dan in de gehele voorgaande geschiedenis van de wereld. Deze sprong in rekenkracht heeft ons voor het eerst in staat gesteld enkele universele kenmerken van complexiteit te doorgronden. Wat de computers aantonen, is dat complexe systemen alleen van onderaf opgebouwd en begrepen kunnen worden. Het vermenigvuldigen van priemgetallen is eenvoudig, maar het ontleden van complexiteit door te proberen het product van grote priemgetallen te ontwarren, is bijna onmogelijk. Kevin Kelly, hoofdredacteur van Wired, verwoordt het als volgt: 'Het vermenigvuldigen van enkele priemgetallen tot een groter product is eenvoudig; elk basisonderwijs­kind kan dat doen. Maar de supercomputers van de wereld raken overbelast bij de poging een product te ontwarren in zijn eenvoudige priemgetallen.'[^190]

### De logica van complexe systemen

De cybereconomie zal onvermijdelijk worden gevormd door deze diepgaande wiskundige waarheid. Dit komt al duidelijk tot uiting in krachtige encryptie-algoritmen. Zoals we later in dit hoofdstuk zullen onderzoeken, zullen deze algoritmen de creatie mogelijk maken van een nieuw, beschermd domein van cyberhandel, waarin het gebruik van geweld sterk wordt beperkt. De balans tussen afpersing en bescherming zal drastisch kantelen in het voordeel van bescherming. Dit zal de opkomst van een economie bevorderen die meer berust op spontane, adaptieve mechanismen en minder op bewuste besluitvorming en middelenallocatie via bureaucratie. Het nieuwe systeem, waarin bescherming centraal staat, zal heel anders zijn dan dat wat ontstond uit de overwegende dwang in de industriële periode.

### Command-and-control systemen zijn primitief

We schreven in *The Great Reckoning* dat de computer ons in staat stelt de voorheen onzichtbare complexiteit te ‘zien’ die inherent is aan een heel scala van systemen.[^243] Geavanceerde rekenkracht stelt ons niet alleen in staat de dynamiek van complexe systemen beter te begrijpen, maar ook om deze complexiteiten op productieve wijze te benutten. In zekere zin is dit niet eens een keuze, maar een onvermijdelijkheid als de economie verder wil komen dan de inflexibele, centraal gestuurde ontwikkelingsfase. Een dergelijk systeem, dat afhankelijk is van lineaire relaties, is in wezen primitief. Overheidsinbeslagname van middelen leidt er onvermijdelijk toe dat deze worden afgetrokken van waardevolle, complexe toepassingen en verlegd naar laagwaardige, primitieve toepassingen. Het is een proces dat wordt beperkt door dezelfde wiskundige asymmetrie die het ontrafelen van het product van grote priemgetallen verhindert. Het verdelen van de buit kan nooit anders dan primitief zijn.

### Alles wordt complexer

Overal in het universum, waar je ook kijkt, zie je systemen die naarmate ze evolueren steeds complexer worden. Dit geldt ook in de astrofysica. Het geldt zelfs in een plas. Laat regenwater op een laaggelegen plek met rust, en het zal complexer worden. Gevorderde systemen van alle soorten zijn complexe, adaptieve systemen zonder een centrale autoriteit. Elk complex systeem in de natuur – waarvan de markteconomie de meest duidelijke sociale manifestatie is – is afhankelijk van verspreide capaciteiten. Systemen die het meest effectief werken onder de breedste reeks omstandigheden, ontlenen hun veerkracht aan een spontane orde die nieuwe mogelijkheden mogelijk maakt. Het leven zelf is zo'n complex systeem. Miljarden potentiële combinaties van genen produceren een enkel menselijk individu. Het sorteren ervan zou elke bureaucratie de kop uitslaan.

Vijfentwintig jaar geleden kon dat slechts een intuïtie zijn. Tegenwoordig is dat aantoonbaar. Hoe dichter computers ons brengen bij het begrijpen van de wiskunde van kunstmatig leven, des te beter begrijpen we de wiskunde van het echte leven, namelijk die van biologische complexiteit. Dankzij informatietechnologie worden deze geheimen van complexiteit benut en stellen ze economieën in staat om te worden heringericht in complexere vormen. Het internet en het world wide web hebben al kenmerken aangenomen van een organisch systeem, zoals Kevin Kelly suggereert in *Out of Control: The New Biology of Machines, Social Systems, and the Economic World.*[^191]:  
In zijn woorden: de natuur is 'een ideeënfabriek. Levendige, postindustriële paradigma’s zijn in elke mierenhoop in de jungle verborgen... De grootschalige overdracht van biologie naar machines zou ons met ontzag vervullen. Wanneer de unie van het natuurlijke en het door de mens gemaakte voltooid is, zullen onze creaties leren, zich aanpassen, zichzelf helen en evolueren. Dit is een kracht waarvan we nog nauwelijks hebben gedroomd.'[^192]

Inderdaad, de gevolgen van de 'grootschalige overdracht van biologie naar machines' zullen verregaand zijn. Er is altijd een sterke neiging geweest dat sociale systemen de kenmerken van de heersende technologie nabootsen. Hierin had Marx gelijk. Gigantische fabrieken vielen samen met het tijdperk van de grote overheid. Microprocessing zorgt voor de miniaturisering van instellingen. Als onze analyse klopt, zal de technologie van het informatietijdperk uiteindelijk een economie creëren die beter in staat is de voordelen van complexiteit te benutten.

Toch zijn de megapolitieke dimensies van zo'n verandering zo weinig begrepen dat zelfs de meesten van degenen die het wiskundige belang ervan hebben erkend, dit op een anachronistische wijze hebben gedaan. Het is eenvoudigweg moeilijk om volledig te bevatten en te internaliseren hoe waarschijnlijk het is dat technologische veranderingen in de komende jaren de meeste politieke vormen en concepten van de moderne wereld achterhaald zullen maken. Zo schreef de overleden natuurkundige Heinz Pagels in zijn vooruitziende boek, *The Dreams of Reason*, 'Ik ben ervan overtuigd dat de naties en volkeren die de nieuwe wetenschap van complexiteit beheersen, de economische, culturele en politieke supermachten van de volgende eeuw zullen worden.'[^193]  
Het is een indrukwekkende voorspelling. Maar wij geloven dat het onvermijdelijk fout zal blijken te zijn, niet omdat het verkeerd wordt begrepen, maar juist omdat het waarschijnlijk nog meer correct zal blijken te zijn dan Dr. Pagels durfde te stellen. Samenlevingen die zich herstructureren tot complexere, adaptieve systemen zullen inderdaad bloeien. Maar wanneer dat gebeurt, zullen het waarschijnlijk geen naties zijn, laat staan 'politieke supermachten'. De meest waarschijnlijke directe begunstigden van de toegenomen complexiteit van sociale systemen zullen de soevereine individuen van het nieuwe millennium zijn.

Zoals Pagels' voorspelling nu staat, is het vergelijkbaar met een sjamaan van een jachtgroep van vijfhonderd generaties geleden die tegen zijn mannen zei, terwijl ze rond het kampvuur hurkten: 'Ik ben ervan overtuigd dat de eerste jachtgroep die de nieuwe wetenschap van geïrrigeerde teelt onder de knie krijgt, meer vrije tijd zal hebben om verhalen te vertellen dan zelfs die mannen bij het meer die de grote vis vangen.' Hoe terecht hij ook was over het belang van complexiteit, Pagels overzag het meest fundamentele feit van allemaal. Wanneer de logica van geweld verandert, verandert de samenleving.

## De logica van geweld

Om te begrijpen hoe en waarom is het noodzakelijk om ons te richten op diverse facetten van de megapolitiek die zelden onder uw aandacht komen. Dit zijn vraagstukken die werden onderzocht door historicus Frederic C. Lane, wiens werk over geweld en de economische betekenis van oorlog elders in dit boek wordt besproken. Toen Lane midden in deze eeuw schreef, was de informatiesamenleving nergens in zicht. Onder deze omstandigheden zou hij er terdege van overtuigd kunnen zijn geweest dat de competitie om geweld in de wereld in zijn definitieve fase was beland met de opkomst van de natiestaat. In zijn werken komt niet naar voren dat hij microverwerking had voorzien of dat hij geloofde dat het technologisch haalbaar was om activa in cyberspace te creëren, een rijk zonder fysieke existentie. Lane had niets te zeggen over de implicaties van de mogelijkheid dat grote handelsvolumes vrijwel immuun zouden kunnen worden gemaakt voor de invloed van geweld.

Hoewel Lane de technologische revoluties die zich nu ontvouwen niet had voorzien, waren zijn inzichten in de verschillende stadia van de monopolisatie van geweld in het verleden zo helder dat ze duidelijk toepasbaar zijn op de opkomende informatierevolutie. Lanes studie van de gewelddadige middeleeuwse wereld vestigde zijn aandacht op vraagstukken die conventionele economen en historici vaak verwaarlozen. Hij zag dat de wijze waarop geweld wordt georganiseerd en gecontroleerd een grote rol speelt bij het bepalen van het gebruik van schaarse middelen.[^194] Lane erkende daarnaast dat, hoewel de productie van geweld doorgaans niet wordt beschouwd als onderdeel van de economische output, de beheersing van geweld cruciaal is voor de economie. De primaire taak van de overheid is het bieden van bescherming tegen geweld. Zoals hij het verwoordde,

"Elke economische onderneming heeft bescherming nodig en betaalt ervoor, bescherming tegen de vernietiging of gewapende inbeslagname van haar kapitaal en de gewelddadige verstoring van haar arbeid. In sterk georganiseerde samenlevingen is de productie van dit nut, bescherming, een van de taken van een speciale vereniging of onderneming die men overheid noemt. Inderdaad, een van de meest onderscheidende kenmerken van overheden is hun poging om wet en orde te creëren door zelf kracht te gebruiken en door op verschillende wijzen het gebruik van geweld door anderen te beheersen."[^195]

Dat is een punt dat kennelijk te fundamenteel is om in leerboeken voor te komen of om deel uit te maken van de burgerlijke discussie die naar verluidt de koers van de politiek bepaalt. Maar het is ook te fundamenteel om te negeren als men de zich ontvouwende informatierevolutie wil begrijpen. De bescherming van leven en eigendom is immers een cruciale behoefte die iedere samenleving die ooit heeft bestaan, heeft geteisterd. Het afweren van gewelddadige agressie is het centrale dilemma in de geschiedenis. Het kan niet eenvoudig worden opgelost, ondanks het feit dat bescherming op meer dan één manier kan worden geboden.

### Het einde van een tijdperk

Terwijl we schrijven, beginnen de megapolitieke gevolgen van het informatietijdperk nog maar net voelbaar te worden. De economische verschuivingen van de afgelopen decennia hebben ons weggeleid van de dominantie van de industrie naar die van informatie en berekening, van machinale kracht naar microverwerking, van fabrieken naar werkstations, van massaproductie naar kleine teams, of zelfs naar individuen die zelfstandig werken. Naarmate de schaal van ondernemingen afneemt, verslapt ook de mogelijkheid voor sabotage en chantage op de werkvloer. Kleinere bedrijven zijn veel lastiger door vakbonden te organiseren.

Microtechnologie stelt ondernemingen in staat om kleiner en mobieler te opereren. Velen leveren diensten of producten die nauwelijks natuurlijke hulpbronnen vereisen. In principe zouden deze ondernemingen bijna overal op aarde kunnen functioneren. Ze zijn niet gebonden aan een specifieke locatie, zoals een mijn of een haven. Daarom zullen zij op den duur veel minder vatbaar zijn om belast te worden, zowel door vakbonden als door politici. Een oude Chinese volkswijsheid luidt: 'Van alle zesendertig manieren om uit de problemen te komen, is de beste manier: vertrek.'[^196]

In het informatietijdperk zal die oosterse wijsheid zijn vruchten afwerpen. Als de bedrijfsvoering onaangenaam wordt door buitensporige eisen op één locatie, is verhuizen veel eenvoudiger. Inderdaad, zoals we hieronder zullen bespreken, zal het in het informatietijdperk mogelijk zijn om virtuele ondernemingen op te richten waarvan het domicilie in een jurisdictie volledig afhankelijk is van de spotmarkt. Een plotselinge toename van pogingen tot afpersing, hetzij door overheden of anderen, kan ertoe leiden dat de activiteiten en activa van de virtuele onderneming met de snelheid van het licht uit die jurisdictie verdwijnen.

De groeiende integratie van microtechnologie in industriële processen betekent dat zelfs die bedrijven die nog steeds vervaardigde producten met grote schaalvoordelen aanbieden, niet langer zo kwetsbaar zijn voor het misbruik van geweld als vroeger. Een illustrerend voorbeeld hiervan is de instorting van de langdurige staking door de beperkte vakbond van autowerkers tegen Caterpillar, die eind 1995 na bijna twee jaar werd stopgezet. In tegenstelling tot de lopende banden uit de jaren dertig heeft de huidige Caterpillar-fabriek aanzienlijk meer geschoolde werknemers in dienst. Onder druk van buitenlandse concurrentie besteedde Caterpillar een groot deel van het laaggeschoolde werk uit, sloot inefficiënte fabrieken en investeerde bijna 2 miljard dollar in het computeriseren van machinegereedschappen en de installatie van assemblagerobots. Zelfs de staking zelf stimuleerde arbeidsbesparende efficiëntieverbeteringen. Het bedrijf beweert nu dat het twee duizend werknemers minder nodig heeft dan toen de staking begon.[^197]

De megapolitiek van het productieproces is drastischer veranderd dan de meesten zich realiseren. Deze verandering is nog niet duidelijk zichtbaar, mede omdat er altijd sprake is van een vertraging tussen een revolutie in megapolitieke omstandigheden en de institutionele veranderingen die daar onvermijdelijk uit voortvloeien. Daarnaast betekent de snelle evolutie van de microprocessortechnologie dat er nu producten aan de horizon staan waarvan de megapolitieke consequenties al verwacht kunnen worden, nog voordat ze bestaan. Zij zullen zorgen voor een totaal andere wereld.

## Uitbuiting van de kapitalisten door de arbeiders

Het karakter van de technologie gedurende het grootste deel van de twintigste eeuw maakte het voor eigenaren of managers buitengewoon moeilijk om krachtig tegen te gaan wanneer een fabriek met geweld in beslag werd genomen, bijvoorbeeld door een sit-downstaking. Zoals historicus Robert S. McElvaine verwoordde, "maakte een sit-downstaking het voor werkgevers moeilijk om de staking te doorbreken zonder hetzelfde met hun eigen apparatuur te moeten doen."[^198] In feite hielden de arbeiders het kapitaal van de eigenaren als losgeld vast. Om redenen die we hieronder zullen onderzoeken, bleken grotere industriële bedrijven gemakkelijkere doelwitten te zijn voor vakbonden dan kleinere ondernemingen. In 1937 was General Motors wellicht de toonaangevende industriële onderneming ter wereld. Zijn fabrieken behoorden tot de grootste en meest kostbare concentraties van machines die ooit zijn samengebracht, en telden duizenden arbeiders in dienst. Elke uur, elke dag dat de GM-installaties gedwongen stil kwamen te liggen, kostte dit het bedrijf een klein fortuin. Een staking die wekenlang onopgelost bleef – zoals in de winter van 1936-37 – resulteerde in snel oplopende verliezen.

### Het trotseren van vraag en aanbod

Na de inbeslagname van haar derde fabriek en het onvermogen om auto's te produceren, gaf GM zich al snel over aan de vakbond. Dit was geenszins een economisch besluit gebaseerd op de wet van vraag en aanbod op de arbeidsmarkt. Integendeel. Toen General Motors voldeed aan de eisen van de vakbond, waren er in de Verenigde Staten negen miljoen mensen werkloos, goed voor 14 procent van de beroepsbevolking. De meesten van de werklozen hadden met plezier bij GM een baan aangenomen. Zij beschikten zeker over de vaardigheden om banen aan de assemblagelijn te vervullen, al zou je dat uit de meeste hedendaagse verslagen niet opmaken. Een delicate etiquette verhulde een directe analyse van de arbeidsverhoudingen in de industriële periode. Een van die voorwendselen was het idee dat fabrieksbanen, met name in het midden van de twintigste eeuw, gespecialiseerd werk waren. Dit bleek echter onwaar. De meeste fabrieksbanen hadden door bijna iedereen uitgevoerd kunnen worden die gewoon op tijd opdook. Ze vereisten weinig tot geen opleiding, zelfs niet de vaardigheid om te lezen of te schrijven. Nog in de jaren tachtig was een groot deel van het personeelsbestand van General Motors analfabeet, rekenkundig onkundig of beide. Tot aan de jaren negentig ontving de typische medewerker op de assemblagelijn bij GM slechts één dag oriëntatie, alvorens hij zijn plaats innam. Een baan die in één dag te leren is, is geen gespecialiseerd werk.

Toch, in 1937, toen zowel ongeschoolde als geschoolde arbeiders in de rij stonden en smekend op zoek waren naar werk, slaagden de fabrieksarbeiders van GM erin hun werkgevers te dwingen tot een loonsverhoging. Hun succes had veel meer te maken met de dynamiek van geweld dan met vraag en aanbod op de arbeidsmarkt.

In maart 1937, de maand na de afwikkeling van de confrontatie bij GM, vonden er in de Verenigde Staten nog eens 17 sit-downstakingen plaats. De meeste waren succesvol. Vergelijkbare episodes deden zich voor in elk geïndustrialiseerd land. De arbeiders namen eenvoudigweg de fabrieken over en eisten daarna losgeld van de eigenaren. Het was een tactiek van grote eenvoud, die in de meeste gevallen zowel winstgevend als plezierig bleek voor de betrokkenen. Eén sit-downstaker schreef: "Ik heb de tijd van mijn leven, iets nieuws, iets anders, veel eten en muziek."[^199]:

De sit-downstaking bij GM in 1936–37 en de andere gewelddadige inbeslagnames van fabrieken in die tijd waren voorbeelden van een verschijnsel dat wij in Blood in the Streets beschreven als "de uitbuiting van de kapitalisten door de arbeiders." Dit was niet de visie die Pete Seeger in zijn droevige liederen muzikaal verwoordde. Maar tenzij je een carrière als folkmuzikant in een arbeiderswijk ambieert, is het belangrijk je niet te richten op de populaire interpretatie, maar op de onderliggende werkelijkheid. Waar je ook in de geschiedenis kijkt, is er doorgaans een laag van rationalisaties en schijnpremissen die de ware megapolitieke fundamenten van elke systematische afpersing verhult. Als je deze rationalisaties voor waar aanneemt, zul je waarschijnlijk niet doorhebben wat er werkelijk gaande is.

## HET ONTCIJFEREN VAN DE LOGICA VAN AFPERSING

Om de megapolitieke implicaties van de huidige verschuiving naar het informatietijdperk te doorgronden, moet je de holle retoriek wegstrepen en je concentreren op de werkelijke logica van geweld in de samenleving. Het is alsof je de lagen van een overrijpe ui verwijdert. Het kan je aan het huilen maken, maar kijk niet weg. We onderzoeken eerst de logica van afpersing op de werkvloer en breiden vervolgens de analyse uit naar bredere vraagstukken, zoals het creëren en beschermen van activa en de aard van de moderne overheid. In veel grotere mate dan de meeste mensen zich voorstellen, was de welvaart van de overheid, net als die van de vakbonden, rechtstreeks verbonden met de hefboomwerking die beschikbaar was voor afpersing. Die hefboom was in de negentiende eeuw veel lager dan in de twintigste eeuw. In het volgende millennium zal deze bijna tot het verdwijnpunt zakken.

De gehele logica van de overheid en de aard van macht zijn getransformeerd door de opkomst van microprocessoren. Dit lijkt misschien overdreven als je er in eerste instantie over nadenkt. Maar kijk goed. De welvaart van regeringen ging in de twintigste eeuw hand in hand met die van de vakbonden. Voor deze eeuw namen de meeste regeringen veel minder middelen in beslag dan de militante verzorgingsstaten waaraan we nu gewend zijn. Evenzo waren vakbonden vóór deze eeuw kleine of onbeduidende spelers in het economische leven. Het vermogen van arbeiders om hun werkgevers te dwingen boven marktconforme lonen te betalen, hing af van dezelfde megapolitieke voorwaarden die het mogelijk maakten voor regeringen om 40 procent of meer van de economische output in belastingen te innen.

### Afpersing op de werkvloer vóór de twintigste eeuw

De opkomst en ondergang van de afpersing door vakbonden van de kapitalisten kan gemakkelijk worden verklaard door de veranderende megapolitiek binnen het productieproces. In 1776, toen Adam Smith The Wealth of Nations publiceerde, waren de omstandigheden voor afpersing op de werkvloer dermate ongunstig dat ‘combinaties’ van arbeiders om de prijs van hun arbeid te verhogen zelden houdbaar bleken. De meeste productiebedrijven waren klein en door families gerund, en industriële activiteiten van grotere schaal stonden nog in de kinderschoenen. Dit sloot de mogelijkheden tot geweld niet uit, maar bood er weinig hefboomwerking voor. Inderdaad, in de tijd van Smith en tot ver in de negentiende eeuw werden vakbonden in Groot-Brittannië, de Verenigde Staten en andere common-law-landen algemeen beschouwd als illegale combinaties. Adam Smith omschreef de poging tot stakingen als volgt: ‘Hun gebruikelijke voorwendselen zijn soms de hoge prijs van levensmiddelen; soms de grote winst die hun meester maakt met hun werk…. Zij grijpen altijd terug op het luidste tumult, en soms op het meest schokkende geweld en de meest gruwelijke beledigingen.’[^200] Desalniettemin haalden de arbeiders ‘zeer zelden enig voordeel uit die tumultueuze combinaties,’ behalve ‘de bestraffing of ondergang van de aanvoerders.’[^201]

De schaalvoordelen in de industrie en de omvang van ondernemingen groeiden tijdens de negentiende eeuw. Toch bleven de meeste mensen voor zichzelf werken als boeren of kleine eigenaren, en eindigden pogingen tot vakbondsorganisatie, zoals door Adam Smith beschreven, ‘over het algemeen in niets.’[^202] De juridische en politieke status van vakbonden veranderde pas toen de schaal van ondernemingen toenam. De eerste vakbonden die slaagden in organisatie waren ambachtsvakbonden van hoogopgeleide werknemers, die zich doorgaans zonder uitgebreid geweld organiseerden. Zij namen vaak genoegen met loonstijgingen die in overeenstemming waren met de marginale kosten om hen te vervangen. Vakbonden voor ongeschoolde arbeiders waren een ander verhaal. Zij maakten vaak gebruik van de verschuiving naar grotere ondernemingen door juist die sectoren te targeten die bijzonder vatbaar waren voor dwang, hetzij omdat zij op grotere schaal opereerden, hetzij omdat de aard van hun activiteiten de eigenaren blootstelde aan fysieke sabotage. Dit patroon liet zich zien van Newcastle tot Argentinië.[^203]

Een vroeg voorbeeld van gewelddadige arbeidersbewegingen in de Verenigde Staten was een aanval op het Chesapeake and Ohio-kanaal in 1834. In tegenstelling tot de meeste ondernemingen aan het begin van de negentiende eeuw was het C&O-kanaal geen afgesloten en gemakkelijk te bewaken operatie. Oorspronkelijk was het, volgens het plan, 342 mijl lang te worden, met een hoogteverschil van 3.000 voet van de lager gelegen Potomac naar de hoger gelegen Ohio.[^204] Het graven van zo’n greppel was een enorme klus die nooit helemaal afgerond werd. Desalniettemin werden er veel arbeiders ingezet om dit te proberen, en enkelen herkenden al snel dat het kanaal gemakkelijk verlamd kon worden. Zonder regelmatig onderhoud kon het bijvoorbeeld gesaboteerd worden door muskratten die onder het sleeppad groeven. Tijdens de werking konden de sluizen en kanalen van het kanaal eenvoudigweg verwoest worden door onzorgvuldig gebruik, overstromingen door zware regenval of door aanvaring van niet-gesleepte boten. Het was voor stakers een simpele opgave om de waterweg te blokkeren met gezonken boten of ander puin. Begin 1834 leidden rellen tussen rivaliserende bendes Ierse arbeiders op het C&O-kanaal tot een poging om van dit potentieel voordeel te maken en het kanaal in bezit te nemen. De poging mislukte echter, waarbij vijf personen omkwamen, nadat president Andrew Jackson federale troepen van Ft. McHenry had gestuurd om de arbeiders uiteen te drijven.

Mijnen en spoorwegen boden eveneens vroege aantrekkelijke doelwitten voor vakbondsactivisme in Amerika. Net als het C&O-kanaal waren ook zij zeer kwetsbaar voor sabotage. Mijnen konden bijvoorbeeld ondergelopen worden of bij de ingang worden geblokkeerd. Het eenvoudige feit dat men de muilezels die de ertscarrières uit de ondergrondse mijnen sleepten vermoordde, bracht de eigenaren in een lastige en onaangename situatie. Evenzo waren de spoorwegbeddingen, die over vele mijlen verspreid lagen, slechts met moeite te bewaken. Het was relatief eenvoudig voor de handlangers van vakbonden om mijnen en spoorwegen aan te vallen en daarmee aanzienlijke economische schade toe te brengen. Dergelijke aanvallen kwamen regelmatig voor tijdens pogingen om effectieve vakbonden op te richten. Deze inspanningen waren doorgaans het meest intens tijdens perioden waarin reële lonen stegen door deflatie. Wanneer eigenaren probeerden de nominale lonen aan te passen, leidde dit vaak tot protesten die uitliepen op geweld. Dergelijke incidenten waren wijdverspreid tijdens de depressie die volgde op de Paniek van 1873.

In december 1874 brak er een openlijke oorlog uit in de anthracietkolenvelden van oostelijk Pennsylvania. De vakbonden organiseerden een gewelddadige stakingstroep, vermomd als een geheim genootschap genaamd de Ancient Order of Hibernians. Ook wel bekend als de 'Molly Maguires', vernoemd naar een Ierse revolutionair, stond deze groep erom bekend de kolenvelden te terroriseren en mijnwerkers die wilden werken te verhinderen. Sabotage en vernieling van eigendom, regelrechte moord en moordaanslagen werden allemaal aan haar leden toegeschreven.[^205]:

Ook onder het personeel van de spoorwegen kwam er herhaaldelijk geweld voor. In juli 1877 ontstonden er ernstige incidenten die erop gericht waren de eigendommen van zowel de Pennsylvania- als de Baltimore & Ohio-spoorwegen te vernietigen. Werknemers namen wissels over, rukten de rails eruit, sloten de wagenparken af, legden locomotieven buiten gebruik, pleegden sabotage en plunderden treinen, en nog veel meer. In Pittsburgh werden de draaihuizen van de Pennsylvania Railroad in brand gestoken, met honderden mensen binnenin. Tientallen mensen kwamen om, tweeduizend spoorwagens werden in brand gestoken en geplunderd, en de werkplaats werd verwoest, samen met een graanelevator en 125 locomotieven. Federale troepen grepen in om de orde te herstellen.[^206]:

Hoewel deze vroege stakingen door socialistische en vakbondsactivisten met sympathie werden geïnterpreteerd, kregen ze weinig publieke steun. Ondanks de inherente kwetsbaarheid van sectoren zoals mijnen en spoorwegen waren de algehele megapolitieke omstandigheden nog niet gunstig voor de afpersing van de kapitalisten door de arbeiders. De omvang van de ondernemingen was te klein om systematische afpersing mogelijk te maken. Hoewel er kwetsbare sectoren waren, werkten deze voor slechts een te klein deel van de bevolking om de voordelen van de dwangmaatregelen tegen werkgevers breed te kunnen delen. Zonder die brede steun waren de stakingen niet houdbaar, omdat de eigenaren konden rekenen op bescherming door de overheid. Terwijl vakbonden soms via intimidatie probeerden te voorkomen dat lokale functionarissen gerechtelijke bevelen uitvoerden, waren ook die pogingen zelden succesvol. Zelfs de meest gewelddadige stakingen werden doorgaans binnen enkele dagen of weken met militaire middelen onderdrukt.

### Chantage eenvoudig gemaakt

Er is een les te trekken voor het informatietijdperk uit het feit dat vakbondsproberen om lonen te realiseren die boven het markt-clearingniveau lagen, zelden succesvol waren wanneer de omvang van de ondernemingen klein was. Zelfs die bedrijfssectoren die duidelijk kwetsbaar waren voor sabotage, zoals kanalen, spoorwegen, trams en mijnen, lieten zich niet eenvoudig onder controle krijgen. Dit komt niet doordat de vakbonden schuw waren voor geweld. Integendeel, geweld werd royaal ingezet, soms tegen prominente personen. Zo werd, in een in de Amerikaanse arbeidersbeweging gevierde zaak als 'wraak van de mijnwerkers', de gouverneur Frank Steunenberg van Idaho, die zich had verzet tegen een poging van mijnwerkers om eigendommen in Coeur d'Alene te blokkeren, vermoord door een bom die door een huurmoordenaar, ingehuurd door de vakbond, werd gegooid.[^207]: Maar zelfs moord en moorddreigingen bleken doorgaans onvoldoende om vakbondelijke erkenning te verkrijgen, voorafgaand aan de opkomst van grootschalige fabrieken en massaproductiebedrijven in de twintigste eeuw.

Om te begrijpen waarom de omstandigheden voor vakbonden in de twintigste eeuw zo ingrijpend veranderden, moet u kijken naar de kenmerken van de productietechnologie. Er is duidelijk iets veranderd met de snelle opkomst van fabrieksbanen voor arbeiders in de vroege decennia van de twintigste eeuw. Deze verandering maakte ondernemingen aan de voorhoede van de economie bijzonder kwetsbaar voor afpersing. Sterker nog, de fysieke kenmerken van de industriële technologie leken de arbeiders bijna uit te nodigen om met dwang de kapitalisten om te persen. Overweeg het volgende:

1. *Er zat een hoog natuurhulpbronnengehalte in de meeste industriële producten*. Dit zorgde ervoor dat de productie verankerd raakte op een beperkt aantal locaties, bijna zoals mijnen zich moeten bevinden waar de ertslagen liggen. Fabrieken die dicht bij transportknooppunten waren gevestigd en gemakkelijke toegang boden tot onderdelenleveranciers en grondstoffen, genoten aanzienlijke operationele voordelen. Dit maakte het voor dwingende organisaties, zoals overheden en vakbonden, gemakkelijker om een deel van die voordelen voor zichzelf te onttrekken.

2. *Stijgende schaalvoordelen leidden tot zeer grote ondernemingen*. Fabrieken uit het begin van de negentiende eeuw waren relatief klein. Maar naarmate de schaalvoordelen toegenomen met de introductie van de lopende band in de twintigste eeuw, namen de omvang en de kosten van faciliteiten in de voorhoede van het productieproces snel toe. Dit maakte hen op verschillende manieren kwetsbaarder doelwit. Zo gaan aanzienlijke schaalvoordelen vaak gepaard met lange productcycli. Lange productcycli zorgen voor stabielere markten en nodigen op hun beurt roofzuchtige activiteiten tegen ondernemingen uit, omdat dit impliceert dat er langetermijnvoordelen te behalen zijn.

3. *Het aantal concurrenten in de toonaangevende industrieën daalde scherp. Het was in de industriële periode niet ongewoon dat slechts een handvol bedrijven streden om markten ter waarde van miljarden dollars*. Dit maakte deze bedrijven tot doelwit van vakbondsafpersing. Het is veel eenvoudiger om vijf bedrijven aan te vallen dan vijfduizend. De concentratie binnen de industrie was zelf al een factor die afpersing vergemakkelijkte. Dit voordeel werkte zichzelf versterkend, omdat de bedrijven die gedwongen werden om monopolistische lonen te betalen, vrijwel geen hevige concurrentie uitten van anderen die niet eveneens belast waren met bovenmarktconforme arbeidskosten. Vakbonden konden daardoor een aanzienlijk deel van de winst van dergelijke bedrijven afpersen zonder hen direct in faillissement te storten. Uiteraard zou er weinig winst zijn als werkgevers routinematig failliet gingen wanneer zij gedwongen werden lonen boven het marktconforme niveau te betalen.

4. *De kapitaaleisen voor vrije investeringen stegen in verhouding tot de schaal van de onderneming*. Dit vergrootte niet alleen de kwetsbaarheid van het kapitaal en versterkte de kosten bij het sluiten van fabrieken, maar maakte het ook steeds onwaarschijnlijker dat een moderne fabriek in handen kon zijn van één individu of familie, behalve door erfenis van iemand die het bedrijf op een kleinere schaal was gestart. Om de enorme kosten voor gereedschappen en het exploiteren van een grote fabriek te financieren, moest het vermogen van honderden of duizenden mensen worden samengebracht op de kapitaalmarkten. Dit maakte het voor de versnipperde en vrijwel anonieme eigenaren moeilijker hun eigendom te verdedigen. Ze hadden geen andere keuze dan te vertrouwen op professionele managers die zelden meer dan een minimale chemische spoor van de uitstaande aandelen van het bedrijf bezaten. Het vertrouwen op ondergeschikte managers verzwakte het verzet van ondernemingen tegen afpersing. De managers hadden weinig sterke prikkels om hun leven en gezondheid te riskeren om het eigendom van de onderneming te beschermen; hun inspanningen benaderden zelden de militantie die vaak werd waargenomen bij eigenaren van slijterijen en andere kleine bedrijven wanneer hun eigendom onder druk kwam te staan.

5. *Grotere bedrijfsgrootte betekende ook dat een groter deel van de totale beroepsbevolking in minder bedrijven werd ingezet dan ooit tevoren*. In sommige gevallen vonden tienduizenden werknemers onderdak bij één onderneming. In militaire termen werden de eigenaren en managers scherp overschaduwd door het aantal personen in lagere functies. Verhoudingen van dertig tegen één of slechter waren gebruikelijk. Dit nadeel nam toe met de grootte van de onderneming, omdat massaal verzamelde werknemers gemakkelijker anoniem geweld konden gebruiken. Onder zulke omstandigheden hadden de arbeiders waarschijnlijk weinig zinvolle contacten of relaties met de eigenaren van de fabriek. Het anonieme karakter van deze relaties maakte het ongetwijfeld eenvoudiger voor de arbeiders om het belang van de eigendomsrechten van de eigenaren terzijde te schuiven.

6. *Gecentraliseerde werkgelegenheid in een klein aantal ondernemingen was een wijdverbreid sociaal fenomeen*. Dit versterkte de megapolitieke voordelen die vakbonden genoten in vergelijking met de negentiende eeuw in Amerika, toen de meeste mensen zelfstandig waren of in kleine ondernemingen werkten. In 1940 had 6 procent van de Amerikaanse beroepsbevolking een baan in de industrie.[^208] Als gevolg hiervan verspreidde de steun voor het gebruik van afpersing om lonen te verhogen zich onder een groot aantal mensen die dachten er mogelijk baat bij te hebben. Dit werd geïllustreerd door een studie uit 1938-39 over de opvattingen van 1.700 mensen in Akron, Ohio, over ondernemingsbezit. De enquête wees uit dat 68 procent van de CIO Rubber Workers weinig tot geen sympathie had voor het concept ondernemingsbezit, terwijl slechts één procent tot de categorie van sterke steun voor de rechten van ondernemingsbezit behoorde.[^209] Aan de andere kant viel geen enkele zakenman, zelfs niet een kleine ondernemer, in dezelfde categorie van ‘sterke afwijzing van ondernemingsbezit’; 94 procent kreeg beoordelingen in de reeks van extreem hoge steun voor eigendomsrechten.[^210]

7. *Lopende bandtechnologie was inherent sequentieel*. Het feit dat het gehele productieproces afhankelijk was van de beweging en assemblage van onderdelen in een vaste volgorde creëerde extra kwetsbaarheden voor verstoringen. In feite was de lopende band als een spoorweg binnen de muren van de fabriek. Als het spoor geblokkeerd kon worden of de beschikbaarheid van een enkel onderdeel wegviel, kwam het hele productieproces tot stilstand.

8. *Lopende bandtechnologie standaardiseerde het werk*. Dit verminderde de variabiliteit in de uitkomst bij personen met verschillende vaardigheden die met dezelfde gereedschappen werkten. Sterker nog, een cruciaal doel van het ontwerpen van fabrieken was om een systeem te creëren waarin zowel een genie als een nietsnut op opeenvolgende diensten van de lopende band hetzelfde product voortbrachten. Wat men ‘domme’ machines zou kunnen noemen, werd zodanig ontworpen dat zij slechts één soort output konden produceren. Hierdoor was het zelfs voor de koper van een Cadillac niet nodig navraag te doen naar de identiteit van de lijnarbeiders die zijn voertuig vervaardigden. Alle producten waren bedoeld identiek te zijn, ongeacht de verschillen in vaardigheden en intelligentie tussen de arbeiders die ze produceerden.

Het feit dat ongeschoolde arbeiders op de lopende band hetzelfde product konden maken als meer bekwame personen, droeg bij aan de egalitaire agenda door het schijnbaar gelijkwaardig maken van ieders economische bijdrage. Ondernemersvaardigheden en mentale inspanning leken minder belangrijk, en de magie van de moderne productie leek in de machines zelf te liggen. Ook al hadden de machines in werkelijkheid niet door iedereen ontworpen kunnen worden, ze leken intellectueel toegankelijk voor bijna iedereen. Dit gaf meer geloofwaardigheid aan de fictie dat ongeschoolde arbeid werd 'uitbuit' door fabriekseigenaren, die daardoor zelf uit de vergelijking verwijderd konden worden zonder dat er iemand anders nadelige gevolgen ondervond. 'We hebben geleerd dat we de fabriek kunnen overnemen,' verwoordde een streiker van GM. 'We wisten al hoe we ze moesten runnen. Als General Motors niet oppast, leggen we twee en twee bij elkaar.'[^211]

Deze kenmerken van de industriële technologie leidden er unaniem toe dat vakbonden werden opgericht om de kwetsbaarheid voor afpersing uit te buiten en tot grotere overheden die profiteerden van de hoge belastingen die op grootschalige industriële faciliteiten konden worden geheven. Dit gebeurde niet eenmalig of tweemaal, maar overal waar grootschalige industrie voet aan de grond kreeg. Steeds weer ontstonden vakbonden die geweld inzette om lonen ver te boven het marktconforme niveau te bereiken. Zij konden dit doen omdat industriële fabrieken doorgaans duur, opvallend, immobiel en kostbaar waren. Ze konden nauwelijks verborgen blijven. Ze konden niet verplaatst worden. Elk moment dat zij buiten gebruik waren, betekende dat hun torenhoge kosten niet werden afgeschreven.

Al deze factoren maakten hen tot makkelijke prooi voor dwingende afpersing, een feit dat in de geschiedenis van de vakbonden veel duidelijker is dan de heersende ideologie van de twintigste eeuw zou doen vermoeden. De bekende econoom Henry Simons verwoordde de kwestie in 1944:

Arbeidsorganisatie zonder grote machten van dwang en intimidatie is een onwerkelijke abstractie. Vakbonden beschikken nu over zulke machten; dat hadden ze altijd en zullen ze altijd hebben, zolang zij in de huidige vorm blijven bestaan. Wanneer de macht klein of niet stevig verankerd is, moet zij openlijk en uitgebreid worden uitgeoefend; wanneer zij groot en onbevochten is, lijkt zij op de macht van de overheid: vol vertrouwen in bezit, met respect behandeld en zelden opvallend tentoongesteld.[^212]:

Hoe nauwkeurig Simons' analyse ook is, hij zat echter op een cruciaal punt fout.

Hij veronderstelde dat vakbonden ‘altijd zullen beschikken over’ wat hij omschreef als ‘grote machten van dwang en intimidatie.’ In werkelijkheid raken vakbonden aan het verdwijnen, niet alleen in de Verenigde Staten en Groot-Brittannië, maar ook in andere volwassen industriële samenlevingen. De reden dat zij verdwijnen – hetgeen Simons over het hoofd zag en wat zelfs veel vakbondenorganisatoren niet begrijpen – is dat de verschuiving naar een informatiesamenleving de megapolitieke omstandigheden op cruciale wijze heeft veranderd, waardoor de veiligheid van eigendom aanzienlijk toeneemt. Microtechnologie begint al subversief te werken tegen de afpersing die de verzorgingsstaat ondersteunt, omdat zij zelfs in het commerciële domein geheel andere prikkels creëert dan in het industriële tijdperk.

1. *Informatietechnologie heeft een verwaarloosbare inhoud aan natuurlijke hulpbronnen*. Het biedt weinig, zo niet geen, inherente locatievoordelen. De meeste informatietechnologie is zeer draagbaar. Omdat zij onafhankelijk van een vaste locatie kan functioneren, verhoogt informatietechnologie de mobiliteit van ideeën, personen en kapitaal. General Motors kon haar drie assemblagelijnen in Flint, Michigan, niet inpakken en wegvliegen. Dat kan een softwarebedrijf wel. De eigenaren kunnen hun algoritmen downloaden op draagbare computers en de volgende vlucht nemen. Zulke ondernemingen hebben bovendien een extra prikkel om hoge belastingen of vakbondseisen voor monopolistische lonen te ontvluchten. Kleinere bedrijven hebben doorgaans meer concurrenten. Als je tientallen of zelfs honderden concurrenten hebt die je klanten proberen weg te lokken, kun je het je niet veroorloven politici of je werknemers veel meer te betalen dan zij daadwerkelijk waard zijn. Als jij dat in je eentje zou proberen, zouden je kosten hoger uitvallen dan die van je concurrenten en zou je failliet gaan. Het ontbreken van significante operationele voordelen op een bepaalde locatie betekent dat dwangorganisaties, zoals overheden en vakbonden, onvermijdelijk minder invloed hebben om deze voordelen voor zichzelf te benutten.

2. *Informatietechnologie verlaagt de schaal van ondernemingen*. Dit resulteert in een kleinere bedrijfsgrootte, wat impliceert dat er meer concurrenten zijn. Toegenomen concurrentie vermindert de potentiële mogelijkheid tot afpersing doordat het aantal doelen dat fysiek gecontroleerd moet worden om lonen of belastingtarieven boven competitieve niveaus te verhogen, toeneemt. De sterke daling in de gemiddelde omvang van bedrijven, mogelijk gemaakt door informatietechnologie, heeft al geleid tot een vermindering van het aantal personen dat in ondergeschikte posities werkt. In de Verenigde Staten suggereren algemeen gerapporteerde schattingen bijvoorbeeld dat in 1996 maar liefst 30 miljoen mensen alleen in hun eigen bedrijf werkten. Het is duidelijk dat deze 30 miljoen nauwelijks in staking gaan tegen zichzelf. Het is nog net iets minder aannemelijk dat de extra miljoenen die in kleine bedrijven met een handje werknemers werken, zouden proberen hun werkgevers te dwingen om lonen boven het marktniveau te betalen. In het informatietijdperk zullen werknemers die via afpersing hun lonen willen verhogen niet beschikken over het militair overweldigende aantal dat hen in de fabriek formidabel maakte. Hoe minder mensen er in een bedrijf werken, des te minder mogelijkheden er zijn voor anonieme geweldpleging. Om deze reden alleen al zouden tienduizend werknemers, verdeeld over vijfhonderd bedrijven, een kleinere bedreiging vormen voor het eigendom van die ondernemingen dan tienduizend werknemers in één enkel bedrijf, zelfs als de verhouding tussen werknemers en eigenaars/management precies hetzelfde zou zijn.

3. *Afname in schaal binnen ondernemingen impliceert tevens dat pogingen om bovenmarktlonen veilig te stellen minder snel op brede maatschappelijke steun kunnen rekenen, zoals dat in de industriële periode wel het geval was.* Vakbonden die erop uit zijn werkgevers af te persen, bevinden zich veel sneller in de situatie van de kanaalarbeiders, spoorwegarbeiders en mijnwerkers uit de negentiende eeuw. Zelfs wanneer enkele bedrijven met grootschalige economische voordelen als overblijfsel uit het industriële tijdperk blijven bestaan, gebeurt dit in een context van wijd verspreide werkgelegenheid in kleine ondernemingen. De overheersing van kleine bedrijven en kleinschalige producenten duidt op een groter maatschappelijk draagvlak voor eigendomsrechten, ook als de wens om inkomsten te herverdelen onveranderd blijft.

4. *Informatietechnologie verlaagt de kapitaalkosten, wat tevens de concurrentie bevordert door ondernemerschap te faciliteren en meer mensen in staat te stellen zelfstandig te werken.* Lagere kapitaaleisen verlagen niet alleen de toetredingsdrempels; ze verminderen ook de 'drempels voor uittreden.' Met andere woorden, dit impliceert dat ondernemingen naar alle waarschijnlijkheid minder activa zullen hebben ten opzichte van hun inkomsten, en dus minder in staat zijn verliezen te dragen. Daarnaast zullen zij minder vaak bij banken aankloppen voor leningen, daar ondernemingen in het informatietijdperk naar alle waarschijnlijkheid ook minder fysieke activa hebben die als onderpand kunnen dienen.

5. *Informatietechnologie verkort de productcyclus.* Dit leidt tot een snellere veroudering van producten. Ook zorgt dit er doorgaans voor dat de mogelijke winsten door het afpersen van bovenmarktlonen slechts van korte duur zijn. In sterk concurrerende markten kunnen te hoge lonen rechtstreeks leiden tot een snel banenverlies en zelfs tot het faillissement van een onderneming. Het najagen van tijdelijk hogere lonen ten koste van het in gevaar brengen van je baan is als je meubels in brand steken om het huis een paar graden warmer te maken.

6. *Informatietechnologie is niet sequentieel, maar simultaan en verspreid.* In tegenstelling tot de lopende band kan informatietechnologie tegelijkertijd meerdere processen ondersteunen. Het verspreidt activiteiten over netwerken, waardoor redundantie en vervanging tussen werkplekken mogelijk is die in de duizenden of zelfs miljoenen kunnen lopen en overal ter wereld aanwezig kunnen zijn. Bij een groeiend aantal activiteiten is het mogelijk dat mensen samenwerken zonder ooit fysiek contact met elkaar te hebben. Naarmate virtual reality en videoconferenties geavanceerder worden, zal de trend naar de verspreiding van functies en telewerken versnellen. Dit is het informatiele tijdperk-equivalent van 'putting out', dat de macht van de middeleeuwse gilden verbrak. Het feit dat steeds minder mensen samen in rokerige fabrieken zullen werken, ontnemen niet alleen een belangrijk voordeel dat arbeiders vroeger hadden bij het afdwingen van hogere lonen van kapitalisten; het maakt het ook steeds moeilijker om onderscheid te maken tussen afperspraktijken en racketeering van de vorm van afpersing die op de werkvloer acceptabel werd geacht. Tot nu toe mochten alleen personen die gezamenlijk hadden gewerkt en in een gemeenschappelijke setting bij een onderneming in dienst waren, geweld gebruiken in een poging hun inkomsten te verhogen. Maar als de 'werkplek' niet langer als centrale locatie bestaat en de meeste functies worden uitbesteed aan onderaannemers en telewerkers, valt er nauwelijks onderscheid te maken tussen een afperskartel en hun pogingen om geld af te persen van hun cliënten of 'werkgevers.'

Bijvoorbeeld, is een telewerker die extra contant geld eist onder dreiging de computers van het bedrijf met een virus te infecteren, een stakende werknemer? Of een internetafperser?

Of hij nu het een of het ander is, zal blijken dat het een onderscheid is zonder verschil. De reactie van de bedrijven die het doelwit zijn, zal in elk geval waarschijnlijk ongeveer hetzelfde zijn. Technische oplossingen tegen informatiesabotage, zoals verbeterde encryptie en netwerkbeveiliging, die de dreiging van een externe hacker zouden moeten afwenden, zouden ook de mogelijkheid ontnemen voor een ontevreden werknemer of onderaannemer om schade toe te brengen aan partijen met wie hij regelmatig of sporadisch zaken doet. Natuurlijk zou men kunnen stellen dat de werknemer of thuiswerker altijd naar het kantoor kan gaan en daar een meer traditionele staking kan organiseren. Maar zelfs dat is wellicht niet zo eenvoudig als het in het informatietijdperk lijkt. De capaciteit van informatietechnologie om lokale grenzen te doorbreken en economische functies te verspreiden, betekent dat werknemers en werkgevers voor het eerst niet eens in hetzelfde rechtsgebied hoeven te verblijven. Hier gaat het niet om het verschil tussen het zijn in de stadsdelen Mayfair en Peckham, maar om werkgevers op Bermuda en thuiswerkers in New Delhi.

Bovendien, als mensen uit India gecharmeerd zouden raken van verhalen over de grote GM-stakingen van 1936–37 en besluiten om naar Bermuda te reizen om te picketten, zouden ze bij aankomst wellicht helemaal geen fysiek kantoor aantreffen. Chiat/Day, een groot reclamebureau, is al begonnen met het ontmantelen van haar hoofdkantoor. Haar werknemers, of onderaannemers, blijven in contact via doorschakeling van oproepen en het internet. Wanneer het nodig wordt om talentteams samen te stellen om het werk aan klantprojecten te coördineren, huren zij vergaderruimtes in hotels. Wanneer het project voorbij is, checken zij uit. Het feit dat microprocessing helpt om het productieproces los te koppelen en te verspreiden van de vaste volgorde van de assemblagelijn, verkleint aanzienlijk de invloed die dwingende instellingen zoals vakbonden en overheden voorheen hadden. Als de assemblagelijn te vergelijken zou zijn met een spoorweg binnen de muren van een fabriek die gemakkelijk door een bezettingsstaking veroverd kon worden, is cyberspace een grenzeloos domein zonder fysieke aanwezigheid. Het kan niet met geweld bezet worden of als gijzeling worden gehouden voor losgeld. De positie van werknemers die geweld willen gebruiken als hefboom om een hoger loon te verkrijgen, zal in het informatietijdperk veel zwakker zijn dan die van de bezettingsstaking bij General Motors in 1936–37.

7. *Microprocessing individualiseert werk, industriële technologie standaardiseerde werk*

Iedereen die dezelfde instrumenten gebruikt, zou hetzelfde resultaat behalen. Microtechnologie is begonnen met het vervangen van ‘domme’ machines door intelligentere technologie die een zeer variabele output kan leveren. De toegenomen variabiliteit in output bij personen die dezelfde hulpmiddelen gebruiken, heeft diepgaande implicaties, waarvan we er vele in de komende hoofdstukken behandelen. Onder de belangrijkere is het gegeven dat, waar de output varieert, ook de inkomens verschillen. Het merendeel van de waarde in domeinen waar vaardigheden uiteenlopen, zal doorgaans door een klein aantal personen worden gecreëerd. Dit is een kenmerk dat vaak voorkomt in de meest concurrerende markten. Dit blijkt bijvoorbeeld in de sport. Wereldwijd spelen miljoenen jonge mensen verschillende varianten van voetbal. Maar 99 procent van het geld dat wordt uitgegeven om voetbalwedstrijden te bekijken, wordt betaald om de optredens van een piepklein deel van het totaal aantal spelers te zien. Evenzo is de wereld vol aspirant-acteurs en -actrices, maar slechts een relatief klein aantal wordt een ster. Evenzo worden jaarlijks tienduizenden boeken uitgegeven, terwijl het merendeel van de royalty's naar een klein aantal bestverkopende auteurs gaat die hun lezers écht kunnen vermaken. Helaas behoren wij niet tot hen.

De enorme variabiliteit in output tussen personen die met dezelfde middelen werken, vormt nog een obstakel voor afpersing. Het creëert een groot onderhandelingsprobleem over hoe de opbrengst verdeeld dient te worden. Waar een relatief klein deel van de deelnemers aan een bepaalde activiteit het grootste deel van de waarde creëert, is het vrijwel wiskundig onmogelijk dat zij er beter op uitkomen door een afgedwongen uitkomst die de inkomens gemiddeld. Eén softwareprogrammeur kan een algoritme bedenken voor het aansturen van een robot dat miljoenen waard blijkt te zijn, terwijl een ander, die met identieke apparatuur werkt, een programma kan schrijven dat niets waard is. De meer productieve programmeur is evenmin geneigd zijn inkomen te laten koppelen aan dat van zijn collega dan dat Tom Clancy akkoord zou gaan om zijn boekroyalty's met de onze te middelen.

Zelfs de vroege fasen van de informatierevolutie hebben het veel duidelijker gemaakt dan in 1975 dat vaardigheden en mentale capaciteiten cruciale variabelen zijn in de economische productie. Dit heeft de eens zo trotse rechtvaardiging voor het afpersen van de kapitalisten door de arbeiders, die tijdens de industriële periode gangbaar was, al doen verdwijnen. De fantasie dat ongeschoolde arbeid daadwerkelijk de waarde creëert die onevenredig in de zakken van de kapitalisten en ondernemers wordt gestoken, is inmiddels een anachronisme. In het geval van informatietechnologie is het niet eens een geloofwaardige fictie. Wanneer de programmeur gaat zitten om code te schrijven, is er een te directe koppeling tussen zijn vaardigheid en zijn product om ruimte te laten voor twijfel over wie verantwoordelijk is. Het is overduidelijk dat een analfabeet of halfgeleide geen computer kan programmeren, en het is dan ook evenzeer duidelijk dat enige waarde in programma's die door anderen zijn samengesteld, niet van hem gestolen kon zijn. Dit is dan ook de reden waarom de roep om ‘uitbuiting’ door werknemers tegenwoordig voornamelijk onder schoonmakers te horen is.

Informationstechnologie maakt duidelijk dat het probleem waarmee mensen met weinig vaardigheden geconfronteerd worden, niet is dat hun productieve vermogens oneerlijk worden uitgebuit; maar eerder de angst dat zij niet in staat zijn een echte economische bijdrage te leveren. Zoals Kevin Kelly suggereert in Out Of Control, zou het 'upstart'-autobedrijf van het informatietijdperk wel eens het geesteskind kunnen zijn van 'een dozijn mensen', die het grootste deel van hun onderdelen zullen uitbesteden en toch auto's produceren die nauwkeuriger op maat zijn gemaakt en volledig afgestemd op de wensen van hun kopers dan alles wat we tot nu toe in Detroit of Tokyo hebben gezien: "Auto's, elk klantgericht op maat gemaakt, worden besteld door een netwerk van klanten en verzonden zodra ze gereed zijn. Mallen voor de carrosserie van de auto worden razendsnel gevormd door door computers aangestuurde lasers en gevoed met ontwerpen die voortkomen uit klantrespons en gerichtemarketing. Een flexibele lijn van robots assembleert de auto's. Het repareren en verbeteren van robots wordt uitbesteed aan een robotbedrijf." [^213]

### Gereedschappen met een stem

In toenemende mate kan ongeschoold werk worden verricht door geautomatiseerde machines, robots en computationele systemen, zoals digitale assistenten. Toen Aristoteles slaven beschreef als "gereedschappen met een stem", had hij het over mensen. In de nabije toekomst zullen "gereedschappen met een stem", zoals de geesten uit fabels, kunnen spreken, instructies opvolgen en zelfs complexe opdrachten uitvoeren. De snel toenemende rekenkracht heeft reeds geleid tot een aantal primitieve toepassingen van spraakherkenning, zoals handsfree telefoons en computers die wiskundige berekeningen uitvoeren op basis van mondelinge instructies. Computers die spraak naar tekst omzetten, werden al eind 1996 op de markt gebracht terwijl wij dit schrijven. Naarmate de patroonherkenningsmogelijkheden verbeteren, zullen computers die gekoppeld zijn aan spraaksynthesizers via netwerken functioneren om tal van taken over te nemen die voorheen werden uitgevoerd door telefonisten, secretaresses, reisagenten, administratieve assistenten, schaakkampioenen, schadebehandelaars, componisten, obligatiehandelaren, cyberoorlogspecialisten, wapenanalisten of zelfs door straatwijze flirters die de telefoons op 900-nummers beantwoorden.

Michael Mauldin van de Carnegie-Mellon Universiteit heeft een kunstmatige persoonlijkheid geprogrammeerd genaamd Julia, die in staat is bijna iedereen voor de gek te houden met wie zij op het internet converseert. Volgens persberichten is Julia een geestige dame die haar leven uitleeft in een rollenspel op het internet. Ze is slim, grappig en houdt van flirten. Ook is ze een soort hockeyexpert en kan zij op een ogenblik de perfecte sarcastische opmerking verzinnen. Julia is echter geen dame. Zij is een bot, een kunstmatige intelligentie die uitsluitend in de ether van het internet bestaat. [^214] De verbluffende vooruitgang die reeds is geboekt in het programmeren van kunstmatige intelligentie en digitale bedienden laat weinig twijfel bestaan dat er nog vele praktische toepassingen zullen volgen. Dit heeft ingrijpende megapolitieke gevolgen.

### Het individu als ensemble

De ontwikkeling van hulpmiddelen met een stem voor diverse toepassingen creëert de mogelijkheid dat het individu wordt verspreid over meerdere gelijktijdige activiteiten. Het individu zal niet langer enkelvoudig zijn, maar potentieel een verzameling van tientallen of zelfs duizenden activiteiten vormen, uitgevoerd door intelligente agenten. Dit zal niet alleen het productieve vermogen van de meest getalenteerde individuen aanzienlijk vergroten; het zal bovendien het soevereine individu potentieel op militair gebied veel formidabeler maken dan ooit tevoren.

Niet alleen zal een individu duidelijk in staat zijn om zijn activiteiten te vermenigvuldigen door een in wezen onbeperkt aantal intelligente agenten in te zetten, hij of zij zal zelfs in staat zijn om na de dood te handelen. Voor het eerst zal een individu in staat zijn om uitgebreide taken uit te voeren, zelfs als hij biologisch dood is. Het zal voor een vijand in oorlog of een crimineel niet langer mogelijk zijn om de mogelijkheid tot vergelding van een individu, door hem te doden, volledig uit te schakelen. Dit is een van de revolutionairste innovaties in de logica van geweld uit de hele geschiedenis.

### Inzichten voor het informatie-tijdperk

De grootste veranderingen in het leven hebben betrekking op variabelen waar niemand op let. Of anders gezegd: we beschouwen als vanzelfsprekend dat variabelen al eeuwen, zo niet honderden generaties, nauwelijks veranderen. Gedurende het grootste deel van de geschiedenis – zo niet voor het grootste deel van het menselijk bestaan – schommelde de balans tussen bescherming en afpersing binnen een smal bereik, waarbij afpersing altijd de overhand had. Dat staat nu op het punt te veranderen. Informatietechnologie legt de basis voor een fundamentele verschuiving in de factoren die de kosten en beloningen bepalen van het gebruik van geweld. Het feit dat intelligente agenten beschikbaar zullen zijn om op de een of andere wijze onderzoek te doen naar, en wellicht vergelding te geven aan, degenen die geweld inzetten, is slechts een voorproefje van dit nieuwe perspectief op bescherming. Vijfentwintig jaar geleden zou de volgende uitspraak niet meer zijn geweest dan de tirade van een gestoorde: 'Als je me doodt, zal ik het geld van je bankrekeningen wegvegen en het aan liefdadigheidsinstellingen in Nepal schenken.' Na de eeuwwisseling kan dit echter wel werkelijkheid worden. Of het daadwerkelijk een praktische dreiging zou blijken te zijn, zou afhangen van factoren als tijd en plaats. Zelfs als de rekeningen van de potentiële misdadiger ondoordringbaar bleken te zijn, zou er ongetwijfeld nog andere kostbare schade kunnen worden aangericht door een leger van intelligente agenten als vergelding voor een misdrijf. Denk er eens over na.

### Nieuwe alternatieven in bescherming

Dit is slechts een van de vele manieren om de bescherming te verbeteren die door de technologie van het informatietijdperk worden ontsloten, waarvan de meeste de bijna monopolistische positie op bescherming en afpersing ondermijnen die regeringen de afgelopen twee eeuwen hebben genoten. Zelfs zonder de nieuwe technologische toeters en bellen zijn er altijd alternatieven geweest voor bescherming, die niet allemaal door de overheid zijn gemonopoliseerd.

Een persoon die zich bedreigd voelt, kan er simpelweg voor kiezen weg te vluchten. Toen de wereld nog jong was en de horizonten wijd open stonden, werd die optie vaak benut. Wanneer mensen zich zorgen maken over verliezen door diefstal of vandalisme, kunnen zij ervoor kiezen om verzekeringspolissen af te sluiten ter compensatie van deze risico’s. Vloeken en betoveringen, al zijn het zwakkere vormen van bescherming, hebben ook levens gered en diefstallen afgewend. Ze werken soms in samenlevingen waar rovers bijgelovig zijn. Waardevolle bezittingen kunnen bovendien beschermd worden door ze te verbergen. Dit is soms een effectieve methode wanneer dat toegepast kan worden. Bezittingen kunnen begraven, beveiligd met sloten, achter hoge muren geplaatst en uitgerust met sirenes en elektronische bewakingsapparatuur. Maar het verbergen van personen en eigendommen is niet altijd praktisch gebleken.

Van alle verschillende methoden voor bescherming die in de loop der tijd zijn toegepast, heeft één methode de overhand: de mogelijkheid om geweld met geweld te beantwoorden, om een grotere kracht in te roepen die iedereen overweldigt die jou zou aanvallen of je eigendom probeert te beroven. De vraag is waar je voor zo’n dienst terecht kunt en hoe je iemand kunt motiveren om zijn leven en ledematen op het spel te zetten om je te helpen tegen schurken die met geweld op zoek zijn naar een kans om jou aan te vallen. Soms hebben naaste familieleden de roep beantwoord. Soms hebben stam- en clangroepen als een onofficiële politie gediend, die reageerden op geweld tegen hun leden met bloedige wraakacties. Soms werden huurlingen of particuliere bewakers ingezet om aanvallen af te weren, maar niet altijd zo effectief als gewenst. De nieuwe intelligente agenten van het informatietijdperk, hoewel hun activiteiten grotendeels beperkt blijven tot de cyberruimte, bieden een nieuw alternatief. Hun loyaliteit, in tegenstelling tot die van huurlingen, particuliere bewakers en zelfs verre neven, is onbetwistbaar.

### De paradoxen van de macht

Het gebruik van geweld om zich tegen geweld te beschermen, zit vol paradoxen. Onder de omstandigheden zoals ze tot nu toe hebben bestaan, zou elke groep of instantie die je zou kunnen inschakelen om je leven en vermogen tegen aanvallen te beschermen, ook noodzakelijk de capaciteit hebben om diezelfde aanvallen uit te voeren. Dat is een nadeel waarvoor geen eenvoudig antwoord bestaat. Normaal gesproken kun je vertrouwen op concurrentie om te voorkomen dat aanbieders van een economische dienst de wensen van hun klanten negeren. Maar wanneer het op geweld aankomt, heeft directe concurrentie vaak perverse uitkomsten. In het verleden leidde dit doorgaans tot een toename van geweld. Wanneer twee potentiële beschermingsinstanties hun strijdkrachten naar elkaar sturen, lijkt het meer op een burgeroorlog dan op bescherming. Wanneer je bescherming zoekt tegen geweld, wil je normaal gesproken niet dat het geweld toeneemt, maar juist dat het wordt onderdrukt. En dat op een wijze die de plundering van de klanten, die in eerste instantie voor de beschermingsdienst betalen, niet toelaat.

> "...tijdens de tijd dat mensen leven zonder een gemeenschappelijke macht die hen allen in vrees houdt, bevinden zij zich in die toestand die men oorlog noemt: zo'n oorlog waarin elke mens tegen elke mens strijdt en waarin men geen andere zekerheid geniet dan wat hun eigen kracht en vindingrijkheid hen verschaft" – THOMAS HOBBES

### Monopolie en anarchie

Daarom is anarchie, ofwel 'de oorlog van allen tegen allen', zoals Hobbes het beschreef, zelden een bevredigende situatie geweest. Lokale concurrentie in het gebruik van geweld heeft er doorgaans toe geleid dat men hogere kosten voor bescherming moest betalen en er minder van kon genieten. Af en toe hebben vrijdenkende voorstanders van de markt gesuggereerd dat marktmechanismen op zich voldoende zouden zijn om de handhaving van eigendomsrechten en de bescherming van het leven te verzorgen, zonder enige nood aan een soevereiniteit.[^215]: Sommige analyses waren elegant, maar de feiten laten zien dat de vrijemarktaanbieding van politie- en justitiediensten niet levensvatbaar is gebleken onder de megapolitieke omstandigheden van het industrialisme. Alleen primitieve samenlevingen, waarin het gedrag sterk gestandaardiseerd is en de bevolkingen klein en homogeen, hebben het overleefd zonder overheden die de dienst van lokaal gemonopoliseerde bescherming middels geweld leveren.

Voorbeelden van anarchistische samenlevingen boven het niveau van de jagers- en verzamelaarsstam zijn weinige en uit vervlogen tijden. Ze behoren allemaal tot de eenvoudigste economieën van geïsoleerde regenwaterboeren. De Kafirs in het pre-islamitische Afghanistan. Enkele Ierse stammen in de donkere middeleeuwen. Enkele Indiase groepen in Brazilië, Venezuela en Paraguay. Andere inheemsen in verspreide delen van de wereld. Hun methoden om bescherming zonder overheid te organiseren, zijn slechts bekend bij kenners van extreme gevallen. Als u er meer over wilt leren, verwijzen we in onze aantekeningen naar diverse boeken die meer details bevatten.[^216]: Primitieve groepen konden functioneren zonder een aparte organisatie die gespecialiseerd was in geweld, simpelweg omdat zij kleine, gesloten samenlevingen waren. En ze waren geïsoleerd. Ze konden rekenen op hechte familiebanden om zich op beperkte schaal te verdedigen tegen de meeste gewelddadige bedreigingen, die in hun omgeving de eenzame soort waren. Wanneer ze met grotere bedreigingen werden geconfronteerd, georganiseerd door staten, werden ze overweldigd en onderworpen aan een door externe groepen gemonopoliseerde heerschappij. Dit gebeurde keer op keer. Waar samenlevingen op een schaal groter dan stammen en familienetwerken zich vormden, vooral daar waar handelsroutes verschillende volkeren samenbrachten, doemden er altijd gewelddadige specialisten op te duiken om elk overschot dat vreedzamere mensen konden voortbrengen, uit te plunderen. Toen technologische omstandigheden de opbrengst van geweld verhoogden, veroordeelden zij samenlevingen die niet georganiseerd waren om grote middelen in oorlogvoering te steken.

> "Welke vorsten verleenden de politiedienst? Welke waren afpersers of zelfs plunderaars? Een plunderaar kon feitelijk de politiechef worden zodra hij zijn 'buit' ordende, deze afstemde op de draagkracht, zijn domein verdedigde tegen andere plunderaars en zijn territoriale monopolie lang genoeg in stand hield om door gewoonte legitiem te worden."[^217]: – FREDERIC C. LANE

Overheid als verkoper van bescherming

Zoals we op verschillende punten hebben aangegeven, is de voornaamste economische functie van de overheid, vanuit het perspectief van de belastingbetalers, het bieden van bescherming voor leven en eigendom. Toch functioneert de overheid vaak als georganiseerde misdaad, waarbij zij binnen haar invloedssfeer middelen van mensen afneemt als tribuut of plundering. De overheid is niet alleen een beschermingsdienst; zij fungeert tevens als een beschermingsracket. Hoewel de overheid bescherming biedt tegen geweld dat door anderen wordt geïnitieerd, rekent zij – net als bij een beschermingsracket – ook kosten in rekening voor bescherming tegen schade die zij anders zelf zou toebrengen. De eerste handeling vormt een economische dienst; de tweede is een racket. In de praktijk kan het onderscheid tussen de twee vormen van ‘bescherming’ moeilijk te maken zijn. Overheden, zoals Charles Tilly heeft opgemerkt, kunnen wellicht het best worden begrepen als ‘onze grootste voorbeelden van georganiseerde misdaad.’[^218]

Zelfs de activiteiten van de best functionerende overheid omvatten gewoonlijk een mengeling van economische beschermingsdiensten in combinatie met afpersing. Historisch gezien konden beide bezigheden optimaal worden uitgevoerd als de overheid binnen de gebieden waarin zij opereert een vrijwel monopolie op dwang wist op te leggen. In situaties waarin een enkele gewapende groep de dominantie in het gebruik van geweld kon vestigen, was de kwaliteit van de beschermdienst die zij bood doorgaans ver superieur aan wat men kon verkrijgen van een van de verscheidene concurrerende beschermingsinstanties die in dezelfde regio met elkaar in de strijd waren.

Een natuurlijk monopolie op land

Het realiseren van een lokaal monopolie op dwang stelde de overheid niet alleen in staat om haar potentiële klanten effectiever te beschermen tegen door anderen geïnitieerd geweld, maar verlaagde ook aanzienlijk haar operationele kosten. Zoals Lane het verwoordde: ‘De industrie die geweld gebruikt en controleert was een natuurlijk monopolie, althans op land. Binnen territoriale grenzen kon de verleende dienst veel goedkoper worden geproduceerd door een monopolie.’[^219] Zo stelde een ‘monopolie op het gebruik van geweld binnen een aaneengesloten gebied’ een bescherming producerende onderneming in staat haar product te verbeteren en de kosten te verlagen.[^220] Een dergelijke bestuursorganisatie kon tegen lagere kosten meer bescherming bieden, omdat zij niet voortdurend militaire acties hoefde te voeren om concurrerende groepen af te weren die beschermingsgelden van haar klanten wilden innen.

De vooruitzichten dat informatietechnologie zal helpen de veronderstelling te versoepelen dat soevereiniteit gebaseerd moet zijn op een territoriaal monopolie, hebben al de aandacht getrokken van politieke theoretici. Het is het thema van *Beyond Sovereignty: Territory and Political Economy in the Twenty-First Century*, van David J. Elkins. Elkins sluit aan bij onze these dat regeringen met een monopolie op soevereiniteit, net zoals religieuze monopolieën in de jaren na 1500, gedoemd zijn om hun tussenpersonen te verliezen. Hij schrijft: “Vroeger gingen we ervan uit dat religies hun eigen grondgebied of ‘turf’ moesten hebben. Toen naties de universele religies vervingen als soevereine rechters over leven en dood, maakten de ‘compactheid’ en ‘afgebakendheid’ van religie plaats voor de nu zo vertrouwde vermenging van gelovigen binnen één gebied. In plaats daarvan weigeren wij de vermenging van naties – of evenmin die van provincies – te tolereren, al geloof ik dat deze veronderstelling in een proces van ontbinding verkeert.”[^221]

Hij vervolgt, in overeenstemming met onze opvatting, dat territoriale monopolieën op soevereiniteit zonder anarchie kunnen worden ontmanteld, zoals blijkt uit de verdeling van soevereiniteit tussen nationale en provinciale overheden in een federaal systeem als dat van Canada, en uit de condominiumregering – met gedeelde Franse en Britse soevereiniteit – die een groot deel van deze eeuw enkele Pacifische eilanden kenmerkte. Dus, hoewel territoriale monopolieën op soevereiniteit zelden met geweld zijn afgebroken, kunnen zij door middel van overeenstemming worden losgemaakt.

Volgens Elkins – en daar zijn wij het mee eens – “is de territoriale natie een bundel of mand waarin andere facetten van ons leven passen. Het is vergelijkbaar met het economische concept van een ‘mand’ vol goederen: je kunt de onderdelen niet gemakkelijk afzonderlijk verkrijgen, maar moet ze collectief verwerven. In een restaurant kun je ‘à la carte’ bestellen; maar wat onze identiteit betreft, moeten we nemen wat naties als bundel aanbieden, wat neerkomt op ‘table d'hote.’ … Een regering *à la carte* zal voor burgers in de eenentwintigste eeuw volkomen natuurlijk lijken.”[^222]

Er is geen ontwikkeling die zo dramatisch bijdraagt aan de ontkoppeling van soevereiniteit en de opkomst van een regering à la carte als de opkomst van een cybereconomie die de fysieke grenzen volledig overstijgt.

> “Nu frequenties stijgen en golflengten afnemen, verbetert de digitale prestatie exponentieel. De bandbreedte stijgt, het energieverbruik slinkt, de antennegrootte neemt af, interferentie stort in en de foutpercentages kelderen.” – George Gilder

## DE WET VAN DE TELECOSM SCHRAPPT DE WETTEN VAN NATIES

We zijn niet de enigen die inzien dat bandbreedte (oftewel de draagkracht van communicatiemedia) voorbestemd is het territoriale statelijke systeem te overtreffen. Jim Taylor en Watts Wacker, auteurs van *The 500-Year Delta: What Happens After What Comes Next*, definiëren hun argument niet op dezelfde wijze als wij, maar zij erkennen dat “toegang globalisme creëert, en globalisme verstoort politieke systemen, waardoor het begrip grenzen overbodig wordt. Naarmate grenzen verdwijnen, wordt het concept van belastingheffing – dat de overheden ondersteunt – steeds fragieler… Naarmate grenzen verdwijnen, valt ook het idee van aanspraak – het geloof dat je, omdat je op een bepaalde plaats geboren bent, recht hebt op de economische voordelen die met die plaats samenhangen – uiteen, en zodra dat uiteenvalt, vallen evenzo de voordelen van het natie-zijn in duigen. En terwijl dit alles gebeurt, worden de idealen die aan het natie-zijn ten grondslag liggen – patriotisme, democratie, de staat, de smeltkroes, eenwording, verantwoordelijk burgerschap, wat het ook moge zijn in welke natie men ook leeft – gedegradeerd tot de vuilnisbelt van de geschiedenis.”[^223]

Zonder het expliciet te benoemen, voelen ook zij dat de geschiedenis richting de bevrijding van het soevereine individu beweegt. Zoals zij zeggen: “Aan de horizon wacht een veel zuiverder vorm van individualisme dan de democratie, zoals wij die nu begrijpen, toestaat.”[^224] Hoe zal dit gebeuren? Taylor en Wacker zien een krachtige dynamiek in werking.

Het simpele feit is dat het bredere gevoel van patriottisme – een liefde voor de natie, een gevoel van filiale plicht jegens die natie – geen bijzonder nuttige aanleg meer is. Burgers die floreren in de mondiale samenleving zullen hun keuzes niet meer baseren op nationale identiteit, maar op hun politieke, sociale en economische identiteiten. Zij laten zich niet leiden door de vraag “Wie zijn mensen zoals ik?”, maar door hoe die keuzes op henzelf van toepassing zijn. Zij zullen de vrijheid maximaliseren om te weten, te reizen, te handelen en zichzelf te zijn. Naties en ondernemingen die dit nalaten – die vasthouden aan achterwaartse acties, gevoed door nostalgie – zullen verzwakken.[^225]

De devaluatie van fysieke grenzen, zoals geïmpliceerd door de jaarlijkse verdrievoudiging van de bandbreedte en de exponentiële groei van het internet en het World Wide Web, zal het proces versnellen waarbij de traditionele bureaucratische tussenlagen van de overheid verdwijnen. Inderdaad, een voortzetting van de jaarlijkse verdrievoudiging van de bandbreedte tot het jaar 2012 zou een miljardvoudige toename betekenen sinds 1993, toen George Gilder voor het eerst suggereerde dat bandbreedte zelfs nog sneller zou groeien dan de capaciteit van microprocessors. Als dit werkelijkheid wordt – wat wij, naar aanleiding van recente doorbraken in de geïntegreerde optica, verwachten – zal de overvloed aan communicatiemogelijkheden resulteren in een fantastische toename van cyberhandel. Met golfdelingsmultiplexing kan een enkele glasvezeldraad, zo dun als een mensenhaar, een capaciteit hebben van één biljoen bits per seconde.[^226] Met andere woorden, een enkele glasvezelkabel zou vijfentwintig keer meer bits kunnen vervoeren dan de totale capaciteit van alle communicatienetwerken ter wereld samen. De uitbreidingsmogelijkheden zijn verbijsterend. Met zoveel ongekende communicatiewaarde zal er aanzienlijk meer geld worden uitgegeven aan communicatie, omdat het zo goedkoop zal zijn. En gevestigde media, zoals vaste telefonie en televisie, zullen anachronismen worden. Het World Wide Web zal elke computer een rijker assortiment aan signalen leveren dan consumenten tegenwoordig ervaren met netwerktelevisie. Naarmate de bandbreedterevolutie zich ontvouwt, zal zij mensen steeds meer aantrekken in de grensloze virtuele wereld van online gemeenschappen en cyberhandel, een wereld met voldoende grafische dichtheid om te transformeren in de 'metaverse' – de soort alternatieve cyberspace-realiteit die de sciencefictionschrijver Neal Stephenson zich voorstelde. Stephenson's 'metaverse' is een virtuele gemeenschap met eigen wetten, vorsten en schurken.[^227] Naarmate steeds meer economische activiteiten naar cyberspace worden verplaatst, zal de waarde van de staatsmonopoliekracht binnen grenzen krimpen, waardoor staten een groeiende prikkel krijgen om hun soevereiniteit te verhuren en te fragmenteren.

Net zoals natiestaten tegenwoordig prikkels hebben om vrije havens, vrijhandelszones en zona franca's te huisvesten, zullen zij ook prikkels hebben om hun soevereiniteit te verhuren. We hebben reeds de vergevorderde onderhandelingen besproken tussen de negenhonderd jaar oude Suvereine Militaire Hospitaller Orde van Sint-Jan van Jeruzalem, van Rhodos en van Malta – beter bekend als de Ridders van Malta – en de Republiek Malta, om de soevereiniteit over Fort St. Angelo aan de orde terug te geven. Wij verwachten dat deze onderhandelingen met succes zullen worden afgerond. Anderen zullen volgen. Sommige natiestaten zullen de soevereiniteit over kleine enclaves en afgelegen gebieden afstaan aan geheel nieuwe affiniteitsgroepen en virtuele gemeenschappen. Het is inderdaad niet onwaarschijnlijk dat commerciële entiteiten, zoals beveiligingsbureaus en hotelketens, zullen bieden op soevereiniteit over kleine delen grondgebied. Wackenhut, Pinkerton en Argenbright zouden in de toekomst hybride omheinde pensioenresidenties en belastingvrije zones in aantrekkelijke klimaten over de hele wereld kunnen aanbieden. Religieuze entiteiten – vergelijkbaar met de Ridders van Malta, maar representatief voor elke denkbare denominatie – zullen op hun eigen wijze proberen om de hemel te laten belichamen in bepaalde afgelegen hoekjes van de aarde. Zelfs vermogende individuen en families zullen hun eigen percelen in bezit hebben waarop zij een beperkte soevereiniteit uitoefenen, hun eigen postzegels en paspoorten uitgeven en een website onderhouden.

## Monopolie en plundering

Let op dat de prikkels om soevereiniteit te delen of te verhuren tegen een vergoeding heel anders zijn dan die waarmee heersers in het verleden geconfronteerd werden, wanneer zij militaire concurrentie ervoeren binnen hun lokale dwangmonopolie. Verhuurde soevereiniteit is niet destabilisender dan het huisvesten van een vrijhandelszone. Integendeel, de militaire machtconcurrentie – zoals gevoerd door strijdende krijgsheren en guerrillabendes – beïnvloedt direct of de potentiële regering sterkere prikkels heeft om de mensen binnen haar invloedssfeer te beschermen of om hen uit te plunderen. Waar strijdende groepen in een onstabiele balans ringen en manoeuvreren, nemen de prikkels om roofzuchtig geweld te gebruiken toe. Plundering wordt aantrekkelijker. Omdat de macht minder stabiel is en het lokale dwangmonopolie minder zeker, verkorten de tijdshorizonten van degenen die in staat zijn geweld te gebruiken. De 'koning van de berg' kan op zo'n gladde helling staan dat hij niet lang genoeg zal overleven om te profiteren van een deel van de aanzienlijke winsten die uiteindelijk voortvloeien uit het beteugelen van geweld. In dat geval is er weinig dat voorkomt dat degenen die fungeren als overheid hun macht gebruiken om de samenleving te terroriseren en te plunderen.

De logica van geweld leert je daarom dat hoe meer concurrerende gewapende groepen er in een gebied actief zijn, des te groter de kans is dat zij tot roofzuchtig geweld grijpen. Zonder een enkele overweldigende macht om het willekeurige geweld te onderdrukken, heeft dit de neiging zich te verspreiden, en gaan veel van de voordelen van economische en sociale samenwerking in rook op.

De schade die kan ontstaan wanneer geweld de vrije loop krijgt in een toestand van anarchie, wordt aangetoond door het lot van China onder de krijgsheren in de jaren 1920. Het is een verhaal dat we vertelden in **The Great Reckoning**. De concurrerende krijgsheren richtten enorme schade aan in gebieden waar geen enkele allesoverheersende macht was om hen in toom te houden. Vergelijkbare verhalen die hetzelfde punt illustreren, zijn in volle kleur uitgezonden naar de wereld door CNN-nieuwsploegen die de straten van Mogadishu, Somalië trotseren. De strijdkrachten van de krijgsheren in Somalië, bijgenaamd de "technicals", brachten anarchie over dat trieste land voordat de Verenigde Staten een grootschalige militaire interventie leidden om hen in te dammen. Toen de overwichtige macht van de Amerikaanse troepen werd teruggetrokken, haalden de technicals hun wapens weer tevoorschijn en hervatte de anarchie.

Een verslag in de Washington Post merkte op:

> [P]ickuptrucks uitgerust met luchtafweergeschut ploegen opnieuw door de stoffige, met puin bezaaide straten. Ook de zelfverzekerde jongemannen in T-shirts, met Kalashnikov-geweren over hun schouders, zijn weer terug en persen geld af van passerende auto's en bussen bij geïmproviseerde wegblokkades. Een door milities gecontroleerde buurt is hier zo zwaar bewapend dat de lokale bevolking het "Bosnië-Herzegovina" noemt. Reizen door de straten van deze stad doet vandaag sterk denken aan de dagen van 1992, toen chaotische gevechten tussen rivaliserende milities Somalië in anarchie stortten en een hongersnood uitbrak die leidde tot een door de VS geleide militaire interventie. Nogmaals, om door Mogadishu te komen, moeten reizigers een auto vol gewapende bandieten inhuren, in de hoop dat zij bescherming bieden voor honderd dollar per dag, plus een pauze voor de lunch.[^228]:

De voorbeelden van Somalië, Rwanda en andere landen, die u spoedig op televisie zult zien, leveren een bewijs in volle kleur dat gewelddadige concurrentie om territoriale controle niet dezelfde directe economische opbrengsten oplevert als andere vormen van concurrentie. Integendeel. De rondtrekkende bandieten en plunderaars die in anarchie opereren, hebben zelfs niet de zwakke prikkels om productieve activiteiten te beschermen, prikkels die soms zelfs de harde hand van dictatoren temperen wanneer hun bewind veilig is.

> "De samenleving van wat wij het moderne tijdperk noemen wordt, vooral in het Westen, gekenmerkt door een bepaald niveau van monopolievorming. Het vrije gebruik van militaire wapens wordt de individu ontzegd en voorbehouden aan een centrale autoriteit van welke aard dan ook, en evenzo wordt de belasting van het eigendom of inkomen van individuen geconcentreerd in de handen van een centrale sociale autoriteit. De financiële middelen die aldus in deze centrale autoriteit stromen, handhaven haar monopolie op militaire kracht, terwijl dit op zijn beurt het belastingmonopolie behoudt. Geen van beide heeft op enige wijze voorrang op de ander; het zijn twee kanten van hetzelfde monopolie. Als de ene verdwijnt, volgt de andere automatisch; het monopoliebestel kan soms aan de ene kant sterker wankelen dan aan de andere."[^229]
- Norbert Elias

## De evolutie van bescherming

Lane ontwikkelde een betoog dat we voor onze doeleinden verkeerd hebben overgenomen bij het voorstellen van hoe het informatietijdperk zich zou kunnen ontvouwen. Hij betoogde dat de geschiedenis van de westerse economieën sinds de donkere middeleeuwen geïnterpreteerd kan worden in vier fasen van concurrentie en monopolie in de organisatie van geweld. Hoewel Lane grotendeels stil blijft over de megapolitieke factoren die wij aanwijzen als bepalend voor de schaal waarop overheden opereren, komt zijn verkenning van de economie van geweld nauw overeen met het betoog dat we uiteenzetten in *Blood in the Streets* en **The Great Reckoning**; en elders in dit volume.

We hebben al enkele van de megapolitieke factoren geanalyseerd die een rol speelden in de evolutie van de westerse samenleving na de val van Rome. Lane onderzocht ook deze periode, met de nadruk op de economische gevolgen van de strijd om een monopolie op geweld te vestigen. Hij onderscheidde vier belangrijke fasen in het functioneren van economieën in de afgelopen duizend jaar, waarbij elke fase een ander stadium in de organisatie van geweld vertegenwoordigde.[^244]

### Uit de donkere middeleeuwen

De eerste fase is er een van “anarchie en plundering” die de feodale revolutie van duizend jaar geleden kenmerkte. Hoewel Lane geen specifieke data geeft voor zijn samenvattende perioden, stellen eenvoudige berekeningen de grens van zijn eerste periode overduidelijk vast, en lijkt zijn beschrijving van de fase van “anarchie en plundering” overeen te komen met de omstandigheden tijdens de overgang uit de donkere middeleeuwen, toen het gebruik van geweld “zeer competitief, zelfs op land” was.[^230]: Hij zegt niet waarom, maar wanneer geweld “zeer competitief” is, betekent dit gewoonlijk dat er aanzienlijke obstakels bestaan voor de projectie van macht over enig afstand. In militaire termen domineert de verdediging de aanval.

Om redenen die we in hoofdstuk 3 hebben toegelicht, viel deze fase van “anarchie en plundering” samen met een daling van de landbouwproductiviteit als gevolg van ongunstige klimaatveranderingen. Aangezien de technologie destijds maar weinig effectieve schaalvoordelen bood om een monopolie op geweld veilig te stellen, was de concurrentie tussen potentiële machthebbers wijdverspreid. De economische activiteit werd verstikt.

De zwakte van de economie verergerde het probleem om een stabiele orde te vestigen. Het creëren van een lokaal geweldsmonopolie ging gepaard met te hoge militaire kosten in verhouding tot de geringe waarde van de economische omzet. Zonder de capaciteit om een effectief monopolie af te dwingen over een economisch levensvatbaar grondgebied terroriseerden en plunderden de gewapende ridders te paard, terwijl zij nauwelijks enige 'bescherming' boden aan hun klanten.

### Feodalisme

"De tweede fase begint wanneer kleine regionale of provinciale monopolies worden gevestigd. De landbouwproductie stijgt dan en het grootste deel van het overschot wordt geïncasseerd door recent opgerichte geweldsmonopolisten."[^231]: Toch is het overschot in deze tweede fase, die wij met de vroege middeleeuwen identificeren, relatief gering. De economische groei wordt gebremsd door het ontbreken van schaalvoordelen in de organisatie van geweld, wat de militaire kosten voor het handhaven van lokale monopolies hoog houdt. Maar terwijl de kosten hoog blijven, stijgt de prijs die kleine soevereiniteiten voor bescherming in rekening kunnen brengen, aangezien de economische activiteit toeneemt wanneer de anarchie wordt beperkt.

Tijdens een late fase van de tweede fase trekken veel tributennemers klanten aan met speciale aanbiedingen voor landbouw- en handelsbedrijven. Zij bieden bescherming tegen lage prijzen aan degenen die nieuwe gronden in gebruik nemen en leveren speciale politiediensten om de handel te stimuleren, zoals die georganiseerd door de graven van Champagne voor kooplieden die naar hun markten komen."[^232]: Met andere woorden, wanneer lokale oorlogsheersers erin slaagden voldoende controle over het grondgebied te verwerven om geloofwaardig te kunnen onderhandelen, deden zij precies wat kooplieden doen wanneer zij hun marktaandeel willen vergroten: zij gaven korting op hun diensten om klanten aan te trekken. De oorlogsheersers gebruikten later de extra middelen uit de toegenomen economische activiteit om hun controle over grotere gebieden te versterken. Zodra die controle stevig was gevestigd, begonnen zij te profiteren van meer monopolistische voordelen. Hun militaire kosten voor het handhaven van de orde daalden en zij konden tevens de prijs verhogen die zij in rekening brachten, zonder zich zorgen te maken dat dit hun dienst minder aantrekkelijk maakte voor de klanten.

In deze gecompliceerde fase van de westerse geschiedenis nemen degenen die geweld toepassen – de middeleeuwse heren en vorsten – het grootste deel van het overschot boven het bestaansniveau voor hun rekening. Er zijn weinig kooplieden. De meest succesvolle zijn degenen die het beste in staat zijn de belastingen, heffingen en andere kosten te ontwijken of te minimaliseren die door degenen worden opgelegd die geld vragen voor 'beschermingsdiensten'.

### De vroegmoderne periode

Een derde fase wordt bereikt wanneer de kooplieden en landeigenaren, die niet tevens specialisten in geweld zijn, 'meer van het overschot van de economie ontvangen dan de leenheren en monarchen.... In deze derde fase ontvangen de ondernemingen die gespecialiseerd zijn in het gebruik van geweld minder van het overschot dan ondernemingen die bescherming van de overheid inkopen.'[^233]: Aangezien succesvolle kooplieden eerder geneigd zijn hun winsten te herinvesteren dan te consumeren, leidde de hogere winst van de kooplieden in die fase van de geschiedenis tot een zichzelf versterkende groei.

### Het tijdperk van de fabrieken

Lane duidt de overgang van de derde naar de vierde fase aan als samenhangend met de opkomst van technologische en industriële innovaties, die belangrijker bleken te zijn voor het behalen van winsten dan het verlagen van de kosten voor bescherming. Daarmee lijkt Lane te verwijzen naar de periode vanaf 1750. Vanaf die tijd begon de aard van technologie een duidelijk overheersende rol te spelen in de welvaart van regio's. Om een extreem voorbeeld te nemen, zouden zelfs gebieden waar helemaal geen overheid bestond – zoals in sommige delen van Nieuw-Zeeland voorafgaand aan 1840 – niet bijzonder welvarend worden louter omdat zij geen belastingen betaalden. In dat stadium van de geschiedenis waren innovaties in de industriële technologie belangrijker voor het realiseren van winsten dan welke besparingen dan ook die verkregen konden worden door de kosten voor bescherming te verlagen, zelfs tot nul. Naarmate de omvang van de overheid toenam, werden de krediet- en financieringsmechanismen, die aanvankelijk door overheden waren geïntroduceerd om middelen te vergaren voor militaire operaties, beschikbaar gesteld voor de financiering van bedrijfsactiviteiten op grotere schaal.

Hoewel Lane dat niet expliciet vermeldt, verminderde de concentratie van technologische voordelen in een bepaald gebied de concurrentie tussen rechtsgebieden en stelde dit 'ondernemingen die gespecialiseerd zijn in het gebruik van geweld' – oftewel overheden – in staat hogere prijzen te vragen. Wanneer er grote technologische verschillen bestaan tussen de concurrenten in het ene rechtsgebied en het andere, zoals tijdens het industriële tijdperk het geval was, hebben ondernemers in de rechtsgebieden met de beste technologie de neiging meer winst te maken, ook al moeten zij wellicht hogere belastingen en andere kosten aan hun overheid betalen.

### Plunderen met een glimlach

Regeringen in het industriële tijdperk genoten van een heerlijk monopolie op uitbuiting. Hun werkelijke kosten voor het bieden van bescherming van leven en ledematen waren verwaarloosbaar klein vergeleken met de tarieven (belastingen) die zij hanteerden. Toch bevonden zij zich in een sfeer waarin de concurrentie zo pervers was dat zij veel meer konden doen aan plundering dan aan bescherming, en bleef dat feit vrijwel onopgemerkt. Het was een zeldzaam moment in de geschiedenis.

De nadelen van anarchie onder de megapolitieke omstandigheden van het industrialisme maakten concurrentie in beschermingsdiensten binnen hetzelfde grondgebied technologisch onhaalbaar. De enige manier om onder die omstandigheden effectieve bescherming te waarborgen was door over een grotere capaciteit tot het inzetten van geweld te beschikken. Daarom had men nauwelijks te winnen bij het trachten een duidelijk onderscheid te maken tussen dat deel van de belastingen dat, in Lanes woorden, 'als betaling voor de geleverde dienst' was en 'een ander deel dat men geneigd is plundering te noemen.'[^234] De onderscheiding was reëel genoeg. Maar aangezien men toch gedwongen was de belastingen te betalen, had een volledige uitwerking ervan weinig te bieden, behalve het bevredigen van morbide nieuwsgierigheid. Zoals Lane zei, ongeacht welk deel van de belastingen plundering bleek te zijn, waren het prijzen die men moest betalen 'om ernstigere verliezen te voorkomen.'[^235]

### De stijging van inkomens onder het industrialisme

Een van de redenen waarom dit dilemma gedurende de afgelopen twee eeuwen van heerschappij door de natiestaat verdraaglijk was, was dat de inkomens dramatisch stegen, vooral in de rechtsgebieden waar de meeste industriële ontwikkeling plaatsvond. Degenen die de regeringen van de OESO aanstuurden, haalden bijna elk jaar een hoger percentage van de inkomens. Maar de toename van de plundering ging desondanks gepaard met een veel grotere welvaart en een grotere ongelijkheid in rijkdom ten opzichte van de rest van de wereld. Onder dergelijke omstandigheden waren bezwaren tegen de belastingverhogingen onvermijdelijk marginaal en ontoereikend om de logische gang van zaken te keren. Inderdaad, om redenen die in eerdere hoofdstukken zijn uiteengezet, hing het militaire voortbestaan van een industrieel natiestaat grotendeels af van het feit dat er geen effectieve grenzen konden worden gesteld aan haar aanspraken op de hulpbronnen van haar burgers.

In elke industriële staat ontwikkelden de beleidsmaatregelen zich min of meer in dezelfde richting. Op het hoogtepunt van het industrialisme na de Tweede Wereldoorlog bereikte het marginale belastingtarief op inkomen 90 procent of meer. Dit was een veel agressievere claim op het recht van de staat om middelen te onttrekken dan zelfs de oosterse despoten van de vroege hydraulische beschavingen doorgaans stelden. Toch volgde de industriële vorm van plundering een eigen logica. Een groot deel hiervan werd bepaald door het karakter van de industriële technologie in de eerste helft van de twintigste eeuw, zoals we eerder beschreven.

Deze technologie maakte het nagenoeg onvermijdelijk dat de staat een groot deel van het inkomen zou inbeslagnemen en herverdelen, waarbij een aanzienlijk deel van de last van de plundering op een klein segment van de kapitalisten viel. De meeste industriële processen waren sterk afhankelijk van natuurlijke hulpbronnen en dus nauw verbonden met de locaties waar deze middelen zich bevonden. Een staalfabriek, een mijn of een haven kon alleen tegen torenhoge kosten verplaatst worden, of zelfs helemaal niet. Zulke faciliteiten vormden derhalve vaste doelwitten die gemakkelijk belast konden worden. De belastingen op eigendom, vennootschappen en op het onttrekken van natuurlijke hulpbronnen stegen de afgelopen eeuw sterk. Ook de inkomstenbelastingen namen toe, aanvankelijk voor de kapitalisten, maar uiteindelijk ook voor de arbeiders zelf. De opkomst van grootschalige industriële werkgelegenheid maakte een breed gedragen inkomstenbelasting praktisch uitvoerbaar. Lonen konden reeds bij de bron worden ingehouden, waarbij de belastingautoriteiten de inning coördineerden met de boekhoudafdelingen van industriële bedrijven. Wij beschouwen dit tegenwoordig als vanzelfsprekend, maar het innen van de inkomstenbelasting bij de fabriekspoort was een stuk eenvoudiger dan door het hele platteland te trekken om een deel van de winst van miljoenen onafhankelijke ambachtslieden en boeren te onttrekken.

Kortom, de industriële technologie zorgde er doorgaans voor dat belastingen meer routineus, voorspelbaarder en minder persoonlijk gevaarlijk vielen dan in veel eerdere perioden. Niettemin onttrok deze wijze van belastingheffing een hoger percentage van de middelen van de samenleving dan welke vorm van soevereiniteit daarvoor ooit had gedaan.

### Wat wordt beschermd?

Het gegeven dat samenlevingen rijker konden worden, terwijl het totale percentage van het inkomen dat door belastingen werd opgeslokt aanzienlijk steeg, roept de vraag op over de aard van de bescherming die overheden aan industriële economieën boden. Wat beschermden zij? Ons antwoord: in de eerste plaats industriële installaties met hoge kapitaalkosten en een aanzienlijke kwetsbaarheid voor aanvallen. De aanwezigheid van grootschalige industriële bedrijven zou niet mogelijk zijn geweest in een wanordelijke omgeving waar het geweld van de concurrentie sterker aanwezig was, zelfs als het resultaat van die concurrentie leidde tot een krimp van het totale aandeel van de productie dat door de overheid werd genomen.

Dit is de reden waarom kapitaalintensieve operaties economisch niet rendabel zijn in de Amerikaanse sloppenwijken, evenals in samenlevingen in de Derde Wereld waar ad hoc geweld endemisch is. De industriële samenleving als geheel kon zich ontwikkelen omdat een bepaalde orde werd gevestigd en gehandhaafd. Ondernemingen werden onderworpen aan regelmatige, voorspelbare afpersingen in plaats van aan grillig geweld.

Zelfs tijdens de hoogtijdagen van het industrialisme was het altijd overdreven om te spreken van een overheid die een 'monopolie op kracht' uitoefent. Alle regeringen proberen zo’n monopolie te handhaven, maar zoals we hebben gezien, ontdekten werknemers van industriële bedrijven doorgaans dat zij in staat waren geweld te gebruiken tegen hun werkgevers. Zolang het algemene publiek toegang heeft tot wapens of een ongeregelde menigte het fysieke vermogen behoudt om een bus om te keren of stenen naar de politie te gooien, monopoliseren degenen die de overheid beheersen de kracht niet volledig. Zij beheersen slechts een overheersende vorm van geweld, in een mate dat het voor de meeste mensen economisch niet rendabel is om onder de bestaande omstandigheden met hen te concurreren.

> Een op het net gebaseerde overheid kan alleen functioneren met instemming van de geregeerden. Elke netregering moet haar burgers daarom echte voordelen bieden als zij wil dat zij blijven. Die voordelen hoeven niet enkel persoonlijke goederen of diensten te omvatten, maar kunnen ook de bredere voordelen van een reguleringsregime inhouden: een schone, transparante markt met vaste regels en consequenties, of een toezicht houdende gemeenschap waarin kinderen de mensen die zij ontmoeten kunnen vertrouwen en waarin de privacy van individuen beschermd wordt. [^236]: - Esther Dyson

### Het informatietijdperk

Het informatietijdperk luidt de aanvang in van een vijfde fase in de evolutie van de competitie in het gebruik van geweld in het Westen. Deze fase was niet voorzien door Lane. De vijfde fase betreft de concurrentie in cyberspace, een arena die niet gekweld wordt door een monopolisering door welke 'geweldsprekende onderneming' dan ook. Het is niet onderhevig aan monopolisering omdat het geen territorium vormt.

Hoewel Lanes betoog de conventionele naoorlogse veronderstellingen over de onvermijdelijkheid van de natiestaat bevat, erkende hij een punt dat voor het begrijpen van de toekomst cruciaal zal blijken te zijn, mogelijk belangrijker dan veertig of vijftig jaar geleden leek. Dat is het feit dat regeringen nooit stabiele dwangmonopolies op de open zee hebben gevestigd. Denk er eens over na. Geen enkele wet van een regering is daar ooit uitsluitend van toepassing geweest. Dit is van het grootste belang om te begrijpen hoe de organisatie van geweld en bescherming zal evolueren naarmate de economie migreert naar cyberspace, dat helemaal geen fysieke bestaan heeft. Om dezelfde redenen die Lane opmerkte toen hij constateerde dat geen enkele regering ooit in staat is geweest om geweld op zee te monopoliseren, is het des te onwaarschijnlijker dat een regering met succes een oneindig domein zonder fysieke grenzen zou kunnen monopoliseren.

## Concurrentie zonder anarchie

In het verleden, toen de omstandigheden het voor een enkele gewelduitoefenende entiteit moeilijk maakten een monopolie te vestigen, waren de consequenties anarchie en plundering. Het informatietijdperk heeft daarentegen de technologische voorwaarden waaronder geweld wordt georganiseerd ingrijpend veranderd. In tegenstelling tot vroeger, toen het onvermogen om bescherming in een bepaald gebied te monopoliseren leidde tot hogere militaire kosten en lagere economische opbrengsten, impliceert het feit dat regeringen cyberspace niet kunnen monopoliseren juist lagere militaire kosten en hogere economische opbrengsten. Dit komt doordat informatietechnologie een nieuwe dimensie in bescherming creëert. Voor het eerst in de geschiedenis maakt informatietechnologie het mogelijk om activa te creëren en te beschermen die zich volledig buiten het territoriale monopolie op geweld van enige regering bevinden.

> 'Landen waarin de eenheden van politieke macht en bestuur meervoudig zijn en die geen centrale, stabiele en onaangevochten toezichthoudende bron van rechtsmacht en macht hebben, moeten hun eigen werkbare oplossingen bedenken voor het omgaan met de problemen die door dergelijke grenzen worden opgeworpen.'[^237]: - REES DAVIES

### De analogie met de grens

Cyberspace is in zekere zin het equivalent van een technologisch beveiligd grensgebied, zoals dat in de middeleeuwen in de grensstreken bestond. In het verleden, toen het gezag van heren en koningen zwak was en de aanspraken van één of meerdere machten elkaar op de grens kruisten, bestond er iets wat op concurrerend bestuur leek. Een blik op de manier waarop deze grensgebieden functioneerden, kan inzicht bieden in hoe 'grenswetten' of iets dergelijks naar cyberspace zouden kunnen migreren.

Andorra bestaat voort als een soort gefossiliseerd grensgebied tussen Frankrijk en Spanje, een relikwie van megapolitieke omstandigheden die het voor geen van beide koninkrijken mogelijk maakten de ander te overheersen in dat koude en bijna ontoegankelijke gebied van 190 vierkante mijl in de Pyreneeën. In 1278 werd een overeenkomst gesloten waarin de suzerainiteit over Andorra werd verdeeld tussen de lokale Franse en Spaanse feodale heren, namelijk de Franse graaf van Foix en de Spaanse bisschop van Urgell. Beiden benoemden één van de twee “viquiers”, die spaarzaam het minimale gezag van de overheid in Andorra uitoefenden, voornamelijk door de kleine Andorraanse militia – tegenwoordig een politie-eenheid – aan te sturen. De rol van de graaf is lang geleden door de geschiedenis opgeëist; de Franse overheid vertegenwoordigt hem nu vanuit Parijs. Tot haar taken behoort onder meer het innen van de helft van de jaarlijkse tribuut die Andorra betaalt, een bedrag dat lager is dan de huur van een goedkoop appartement voor één maand. De bisschop van Urgell ontvangt nog steeds zijn deel van de tribuut, net zoals zijn voorgangers in de middeleeuwen deden.

Zoals de gesplitste tribuut impliceert, waren er in Andorra niet één, maar twee bronnen van ‘toezichthoudende jurisdictie en macht’. Beroepen tegen Andorraanse civiele rechtszaken werden traditioneel ingediend bij het Episcopaals College van Urgell of bij het Hof van Cassatie in Parijs.

Een gevolg van Andorra’s ambigue positie was dat er bijna geen wetten werden aangenomen. Andorra heeft meer dan zevenhonderd jaar lang een vrijwel onbestaande overheid en geen belastingen gekend. Tegenwoordig geeft dat het een toenemende aantrekkingskracht als belastingparadijs, maar tot een generatie geleden was Andorra bekend als arm. Ooit dichtbegroeid met bossen, werd het in de loop der eeuwen ontdaan van zijn bomen door inwoners die probeerden warm te blijven in de bittere winters. Het hele gebied is elk jaar van november tot en met april door sneeuw afgesloten. Zelfs in de zomer is het in Andorra zo koud dat gewassen alleen op de zuidelijke hellingen groeien. Als onze beschrijving het onaantrekkelijk doet lijken, hebt u zojuist het geheim van zijn succes ontdekt. Andorra overleefde als een feodaal enclave in het tijdperk van de natiestaat omdat het zowel afgelegen als extreem arm was.

Er waren ooit talloze middeleeuwse grensgebieden of ‘march-regio’s’ waarin soevereiniteiten in elkaar overvloeiden. Deze vaak gewelddadige grensstreken hielden decennialang of soms zelfs eeuwenlang stand in de grensgebieden van Europa, en de meeste daarvan waren arm. Zoals eerder vermeld, werden er grensgebieden gevormd tussen gebieden onder Keltische en Engelse heerschappij in Ierland; tussen Wales en Engeland, tussen Schotland en Engeland, tussen Italië en Frankrijk, tussen Frankrijk en Spanje, tussen Duitsland en de Slavische grensstreken van Centraal-Europa en tussen de christelijke koninkrijken van Spanje en het islamitische koninkrijk Granada. Net als Andorra ontwikkelden deze grensgebieden unieke institutionele en juridische vormen die we waarschijnlijk opnieuw zullen zien in het komende millennium.

Vanwege de concurrerende positie van de twee autoriteiten, die allebei zwak waren, vroegen overheden soms zelfs vrijwilligers onder hun onderdanen om zich in grensgebieden te vestigen, zodat hun gezag verder reikte. Bijna vanzelfsprekend werden de onderdanen verleid om zich in deze grensstreek te vestigen doordat zij vrijgesteld waren van belastingen.

Gezien de fragiele marges waarop zij concurreerden, zou het opleggen van belastingen door een van de autoriteiten in een grensgebied niet alleen voor hun volgelingen het overleven bemoeilijken, maar ook iedereen een reden geven om zich bij de concurrent aan te sluiten. Daarom hadden inwoners van een grensgebied doorgaans de keuze welke wetten zij zouden gehoorzamen. Deze keuze was gebaseerd op de zwakte van de concurrerende autoriteiten; het was geen ideologische geste.

Niettemin ontstonden er praktische moeilijkheden die moesten worden opgelost. Onder het feodalisme stonden landeigenaren die aan beide zijden van een symbolische grens bezittingen hadden, voor een ernstig belangenconflict. Zo kon een heer aan de grens van Schotland en Engeland, die in beide koninkrijken land bezat, in geval van oorlog theoretisch voor beide dienstplichtig zijn. Om deze schijnbare tegenstrijdigheid te verhelpen, kon vrijwel iedereen in de feodale hiërarchie via een juridische procedure, die avowal wordt genoemd, bepalen welk recht hij in acht zou nemen.

Informatietechnologie zal gelijke kansen bieden voor een concurrerende keuze bij het vestigen van economische activiteiten, zij het met belangrijke verschillen. Ten eerste is – in tegenstelling tot de middeleeuwse grensgemeenschappen – cyberspace naar alle waarschijnlijkheid op termijn het rijkste van de economische domeinen. Het zal derhalve eerder een groeiende dan een krimpende grens vormen. Weinigen in de kernregio’s van de middeleeuwse samenleving zouden zonder sterke prikkels – vaak inclusief religieuze imperatieven – naar grensgebieden verhuizen, omdat deze streken doorgaans gewelddadig en arm waren. Zij fungeerden dan ook niet als magneten die middelen uit de controle van de autoriteiten wegtrekken. Cyberspace zal dat wel doen.

Ten tweede zal de nieuwe grens geen duopolie vormen dat uitnodigt tot collusie tussen twee autoriteiten om compromissen te sluiten over hun grensclaims. Dergelijke compromissen bleken in de middeleeuwen om twee redenen niet effectief te zijn: er waren vaak scherpe culturele kloven tussen de rivaliserende autoriteiten en, belangrijker nog, zij beschikten niet over de fysieke capaciteit om een onderhandelde oplossing af te dwingen, doordat hun militaire macht ter plaatse ontoereikend was. Tijdens het tijdperk van de natiestaat, toen nationale autoriteiten wel over voldoende militaire kracht beschikten om oplossingen op te leggen, verdwenen de meeste grensstreken en vage grenzen. Grensafbakening werd de norm. Dit is een stabiele oplossing wanneer gewelddadige duopolisten geconfronteerd worden met het vooruitzicht hun gezag over aaneengesloten gebieden te moeten verdelen. Maar de concurrentie bij het vestigen van transacties in de cybereconomie zal niet tussen twee autoriteiten plaatsvinden, maar tussen honderden autoriteiten wereldwijd. Voor de territoriale staten zal het vrijwel onmogelijk zijn een effectief kartel te vormen om de belastingtarieven hoog te houden. Dat is precies hetzelfde als het feit dat collusie om monopolistische prijzen te genieten in markten met honderden concurrenten niet werkt.

Als bewijs, overweeg de stap van de Seychellen, een klein land in de Indische Oceaan, om een nieuwe investeringswet vast te stellen die volgens Amerikaanse regeringsfunctionarissen wordt omschreven als een 'verwelkom criminalen'-wet. Onder deze wet krijgt iedereen die 10 miljoen dollar investeert in de Seychellen niet alleen bescherming tegen uitlevering gegarandeerd, maar wordt er ook een diplomatiek paspoort uitgegeven. In tegenspraak met de beweringen van de Amerikaanse regering zijn de beoogde begunstigden overigens geen drugshandelaren – die sowieso doorgaans onder de bescherming vallen van belangrijkere regeringen – maar onafhankelijke ondernemers die als politiek incorrect worden beschouwd. De eerste potentiële begunstigde van de Seychellenwet is een blanke Zuid-Afrikaan die rijk werd door de economische sancties tegen het voormalige apartheidsregime te omzeilen. Nu loopt hij het risico op economische vergelding door de nieuwe Zuid-Afrikaanse regering en is hij bereid de Seychellen te betalen voor bescherming.[^238]

Ongeacht de verdiensten van een individueel geval, toont dit voorbeeld aan waarom de pogingen van overheden om een kartel voor bescherming op de grond te handhaven gedoemd zijn te mislukken.

In tegenstelling tot de middeleeuwse grens, waar de concurrentie slechts tussen twee autoriteiten plaatsvond, zal de grens in de cyberhandel bestaan uit honderden rechtsgebieden, waarvan het aantal waarschijnlijk snel zal oplopen tot duizenden.

In het tijdperk van de virtuele onderneming zullen individuen ervoor kiezen hun inkomstengenererende activiteiten te vestigen in een rechtsgebied dat de beste service biedt tegen de laagste kosten. Met andere woorden, soevereiniteit zal gecommercialiseerd worden.

In tegenstelling tot middeleeuwse grensgemeenschappen, die in de meeste gevallen arm en gewelddadig waren, zal cyberspace dat niet zijn. De concurrentie die informatietechnologie overheden dwingt aan te gaan, is geen militaire concurrentie, maar een concurrentie op het gebied van kwaliteit en prijs van een economische dienst – echte bescherming. Kortom, overheden zullen verplicht zijn de klanten te geven wat zij wensen.

### De afgenomen effectiviteit van geweld

Dit wil natuurlijk niet zeggen dat overheden afzien van het inzetten van geweld. Integendeel. Wat we stellen, is dat geweld een aanzienlijk deel van zijn hefboomwerking verliest.

Een mogelijke reactie van overheden zou kunnen zijn om hun gebruik van geweld op lokaal niveau te intensiveren in een poging de dalende mondiale betekenis ervan te compenseren. Wat overheden ook doen, zij zullen echter niet in staat zijn om cyberspace met geweld te verzadigen zoals zij in de moderne wereld de gebieden, die zij met geweld monopoleerden, hebben verzadigd.

Ongeacht hoeveel overheden proberen cyberspace te betreden, zullen zij in dat domein niet capabeler of machtiger zijn dan wie dan ook.

Ironisch genoeg zullen pogingen van natiestaten om ‘informatieoorlogen’ te voeren – met als doel de dominantie over of het blokkeren van de toegang tot cyberspace – waarschijnlijk alleen maar hun eigen ondergang versnellen. De neiging tot de afbraak van grote systemen is al sterk, mede door het wegvallen van schaalvoordelen en de stijgende kosten om gefragmenteerde sociale groepen bijeen te houden. De ironie van informatieoorlogen is dat ze wel eens een grotere schok kunnen veroorzaken voor de broze systemen die uit het industriële tijdperk zijn overgebleven dan voor de opkomende informatie-economie zelf.

Zolang de essentiële informatietechnologie blijft functioneren, kan cybercommerce gelijktijdig bestaan met de strijd in de informatieoorlog op een wijze die in een territoriale oorlog volstrekt onmogelijk zou zijn. Je kunt je niet voorstellen dat er miljoenen commerciële transacties plaatsvinden aan het front van een oorlog uit de twintigste eeuw. Maar virtuele oorlogen zullen de capaciteit van cyberspace om meerdere activiteiten te ondersteunen niet uitputten. En omdat virtuele realiteit niet bestaat, is er weinig gevaar van nabijheid en vrijwel geen risico dat je wordt geraakt door exploderende virtuele granaatfragmenten.

### Kwetsbaarheid van grootschalige systemen

De gevaren van een informatieoorlog vormen vooral een bedreiging voor grootschalige industriële systemen die opereren met een centraal bevel en controle. Militaire autoriteiten in de Verenigde Staten en andere leidende natiestaten bereiden zich zowel voor op als vrezen daden van informatiesabotage die ernstige gevolgen kunnen hebben voor het uitschakelen van grote systemen. Een daad van cyberoorlogvoering zou een telefoonwisselstation kunnen sluiten, het luchtverkeersbeheer kunnen verstoren of een pompsysteem dat de watertoevoer naar een stad reguleert, kunnen saboteren. Een geprogrammeerd virus zou zelfs conventionele of nucleaire stroomopwekkers kunnen laten uitvallen, waardoor delen van het elektriciteitsnet worden stilgelegd. Zogenaamde logic bombs kunnen een enorme hoeveelheid informatie vernielen, waarvan de meest gevoelige zich bevindt in de centrale controlesystemen die de kwetsbare grootschalige systemen uit het industriële tijdperk aansturen. Tenzij er een massale en allesomvattende vernietiging van alle informatietechnologie plaatsvindt – wat de wereldeconomie letterlijk tot stilstand zou brengen – zullen cybercommerce en virtuele realiteit buiten het bereik blijven van enige overheid om te onderdrukken, laat staan te monopoliseren.

Zelfs één van de opvallende nadelen van informatietechnologie – de schijnbare kwetsbaarheid van informatiestoragesystemen voor bederf en vernietiging – is grotendeels opgelost door nieuwe archiveringstechnologie. Een nieuw systeem, genaamd High-Density Read-Only Memory of HD-ROM, maakt gebruik van een ionmolen, vergelijkbaar met die in computerondersteunde productie, om archieven in een vacuüm te creëren. De opslagcapaciteit bedraagt nu maar liefst 25.000 megabytes per vierkante inch. In tegenstelling tot eerdere systemen die kwetsbaar waren voor vroegtijdig bederf en verstoring door schokken, belooft data die in HD-ROM wordt opgeslagen, voor de gehele duur beschikbaar te blijven. Eén van de ontwikkelaars van HD-ROM, Bruce Lamartine, zegt: 'Het is vrijwel ondoordringbaar voor de verwoestende effecten van tijd, thermische en mechanische schokken of de elektromagnetische velden die zulke schade aanrichten aan andere opslagmedia.'[^239]: Zelfs de detonatie van een explosie door nucleaire terroristen zou niet per se vitale informatie – zoals de codes voor digitaal geld, waarop het soepele functioneren van een cybereconomie berust – verstoren of vernietigen.

> "Moderne legers zijn zo afhankelijk van informatie dat het mogelijk is hen te verblinden en doof te maken, zodat men de overwinning kan behalen zonder op de conventionele wijze te vechten."[^240]: - COL. ALAN CAMPEN, U.S.A.F (Ret.)

## Supermachten van virtuele oorlogsvoering

Naarmate het belang van informatie in de oorlogsvoering toeneemt, zullen de aannames van de natiestaat in oorlog steeds minder megapolitieke betekenis hebben. Omdat cyberspace geen fysieke aanwezigheid heeft, is het geen domein waarin de grootheden, zoals we die in de fysieke wereld kennen, enige doorslaggevende betekenis hebben. Het maakt niet uit hoeveel programmeurs betrokken waren bij het vaststellen van een reeks commando's; het enige dat telt, is of het programma functioneert. Het soevereine individu kan in cyberspace net zoveel betekenis hebben als een natiestaat, met haar zetel bij de Verenigde Naties, eigen vlag en een op het grondgebied gestationeerd leger. In puur economische termen genereren sommige soevereine individuen al investeerbare inkomens in de honderden miljoenen per jaar, bedragen die de discretionaire bestedingsruimte van enkele failliete natiestaten overschrijden. Maar dat is nog niet alles. Op het gebied van virtuele oorlogsvoering, gevoerd door middel van de manipulatie van informatie, kunnen sommige individuen even prominent of zelfs prominenter zijn dan veel van de wereldstaten. Één bizarre genie, die samenwerkt met digitale dienaren, zou in theorie in een cyberoorlog dezelfde impact kunnen bereiken als een natiestaat. Bill Gates zou dat zeker kunnen.

In die zin is het tijdperk van het soevereine individu niet louter een slogan. Een hacker, of een kleine groep wiskundigen, om nog maar te zwijgen over een bedrijf als Microsoft, of vrijwel elk computersoftwarebedrijf, zou in principe al dan niet alles kunnen doen wat de Cyber War Task Force van het Pentagon in petto heeft. Er zijn honderden bedrijven in Silicon Valley en elders die al over een grotere capaciteit beschikken om een cyberoorlog te voeren dan 90 procent van de bestaande natiestaten.

De veronderstelling dat regeringen het leven op de grond zullen blijven monopoliseren, nu er van alle kanten alternatieve wegen voor bescherming opengaan, is een anachronisme. Een veel waarschijnlijker scenario is dat natiestaten opnieuw ingedeeld moeten worden om hun kwetsbaarheid voor computervirussen, logische bommen, geïnfecteerde draden en achterdeurprogramma's te verkleinen, die gemonitord zouden kunnen worden door de Amerikaanse National Security Agency of een tienerhacker.

De megapolitieke logica van cyberspace suggereert dat centrale commando‑ en controlesystemen, die momenteel de grootschalige infrastructuur van de wereld domineren, vervangen moeten worden door multicentrische beveiligingsmodellen met gedistribueerde capaciteiten, zodat ze niet gemakkelijk door een computervirus kunnen worden overgenomen of geblokkeerd. Nieuwe soorten software, bekend als agorische open systemen, zullen de commando‑ en controlesoftware uit de Industriële Tijd vervangen. Die oudere software deelde de computercapaciteit toe op basis van starre prioriteiten, bijna op dezelfde wijze als de centrale planners van het Gosplan in de voormalige Sovjet-Unie goederen toewijzen aan goederentreinen volgens vaste regels. De nieuwe systemen worden bestuurd door algoritmen die markmechanismen nabootsen om middelen efficiënter toe te wijzen via een intern biedproces dat de competitieve processen in de hersenen imiteert. In plaats van dat gigantische computermonopolies belangrijke commando‑ en controlefuncties uitvoeren, zullen deze in het nieuwe millennium gedecentraliseerd worden.

Er is geen beter voorbeeld van de veerkracht van gedistribueerde netwerken ten opzichte van commando‑ en controlesystemen dan dat geschetst door Digital Equipment in het Palo Alto-onderzoekscentrum. Een ingenieur opende de deur van een kast waarin het eigen computernetwerk van het bedrijf was gehuisvest. Zoals Kevin Kelly vertelt, trok de ingenieur dramatisch een kabel uit zijn binnenste. Het netwerk schakelde de breuk moeiteloos om en aarzelde geen moment.[^241]:

Het Informatietijdperk zal niet alleen competitie zonder anarchie in cyberspace mogelijk maken; het zal onvermijdelijk leiden tot een herinrichting van belangrijke systemen die nog hun wortels hebben in het industrialisme. Zo’n herconfiguratie is essentieel om deze systemen minder kwetsbaar te maken voor kattenkwaad van wie dan ook of van waar dan ook. Net zoals de Industriële Tijd onvermijdelijk leidde tot de herstructurering van instituties die nog uit de middeleeuwen voortkwamen, zoals scholen en universiteiten, zullen de overgebleven instellingen van de Industriële Tijd waarschijnlijk in verkleinde vorm vervallen op manieren die de logica van microtechnologie weerspiegelen.

De noodzaak om zich te beschermen tegen bandieten op de informatieweg zal een wijdverbreide invoering vereisen van encryptie-algoritmen met publieke en privésleutels. Deze stellen elke individuele gebruiker van een pc in staat om berichten veiliger te coderen dan het Pentagon nog een generatie geleden zijn lanceercodes had kunnen verzegelen. Deze krachtige, onbreekbare vormen van encryptie zullen noodzakelijk zijn om financiële transacties te beveiligen tegen hackers en dieven.

Ze zullen ook om een andere reden noodzakelijk zijn. Private financiële instellingen en centrale banken zullen onbreekbare encryptie-algoritmen gaan gebruiken zodra zij beseffen dat de Amerikaanse regering – en zij is mogelijk niet de enige – in staat is om de huidige banksystemen en computersoftware binnen te dringen om letterlijk een land failliet te laten gaan of de bankrekening van iedereen, vrijwel overal, leeg te vegen. Er is geen technologische reden waarom enig individu of enig land zijn financiële deposito’s of transacties zou moeten overlaten aan de genade van de Amerikaanse National Security Agency of de opvolgers van de KGB, of van enige vergelijkbare organisatie, legaal of illegaal.

Encryptie-algoritmen die voor overheden ondoordringbaar zijn, zijn geen dagdromen. Ze zijn reeds beschikbaar als shareware via het internet. Wanneer lage-orbit satellietsystemen volledig operationeel zijn, zullen individuen die met geavanceerde personal computers werken met antennes die niet groter zijn dan die van draagbare telefoons, overal ter wereld kunnen communiceren zonder zelfs maar gebruik te maken van het telefoonsysteem. Het zal voor een overheid evenmin mogelijk zijn om cyberspace te monopolizeren – een rijk dat geheel geen fysieke existentie kent – dan het voor middeleeuwse ridders mogelijk zou zijn geweest om in de industriële periode transacties te beheersen terwijl zij op een zwaar rijdier reden.

### Bescherming door onopvallendheid

Informatiesamenlevingen zullen enorme middelen buiten het bereik van roof leggen. Wanneer cyberspace steeds vaker het toneel wordt van financiële transacties en andere vormen van handel, zullen de daar gebruikte middelen min of meer immuun zijn voor gewone afpersingen en diefstal. Daardoor zullen plunderaars niet in staat zijn een even groot aandeel van de middelen te bemachtigen als dat vandaag de dag het geval is en gedurende een groot deel van de twintigste eeuw is gebeurd.

Onvermijdelijk zal de overheidsbescherming van een aanzienlijk deel van de wereldwijde rijkdom overbodig worden. De overheid zal niet beter in staat zijn om een banksaldo in cyberspace te beveiligen dan u. Aangezien de overheid minder noodzakelijk zal zijn, zal de relatieve prijs ervan waarschijnlijk om die reden alleen al dalen – en daar spelen nog andere factoren mee.

Nu, in het nieuwe millennium, een groot en groeiend deel van de financiële transacties in cyberspace plaatsvindt, zullen individuen de mogelijkheid hebben om deze onder te brengen in verschillende rechtsgebieden. Dit zal leiden tot een felle concurrentie om de tarieven van overheidsdiensten (de belastingen die zij heft) op een niet-monopolistische basis vast te stellen. Dit is revolutionair. Zoals George Melloan in The Wall Street Journal betoogde, is de enige instelling die de krachten van de mondiale concurrentie het meest succesvol heeft weerstaan de verzorgingsstaat. ‘Een studie van onderzoekers van de Wharton School en de Australian National University besprak de krachten die van invloed zijn op inkomensoverdrachten. Geoffrey Garrett en Deborah Mitchell concludeerden dat er vrijwel geen bewijs is dat een toegenomen marktintegratie neerwaartse druk heeft uitgeoefend op hun meest fundamentele welzijnsprogramma’s.’ Integendeel, schrijven zij, ‘hebben overheden steevast gereageerd op een toegenomen integratie in internationale markten door de inkomensoverdrachten te verhogen.’ 

De opkomst van de cybereconomie zal de verzorgingsstaat eindelijk blootstellen aan échte concurrentie. Het zal de aard van soevereiniteiten veranderen en economieën transformeren, aangezien de balans tussen bescherming en afpersing steeds meer zal verschuiven in het voordeel van bescherming dan ooit tevoren.

[^187]: Neil Munro, 'The Pentagon's new nightmare: an electronic Pearl Harbor', Washington Post, 16 juli 1995, p. C3.

[^188]: Thomas Hobbes, Leviathan, hoofdstuk 13 van 'De natuurlijke toestand van de mens betreffende hun gelukzaligheid en ellende.'

[^189]: Thomas Schelling, Arms and influence (New Haven: Yale University Press, 1966).

[^190]: Kevin Kelly, Out of control: the new biology of machines, social systems, and the economic world (Reading, Mass.: Addison~Wesley, 1995), pp.45-46.

[^191]: Ibid., pp.2-4.

[^192]: Ibid., p.4.

[^193]: Heinz Pagels, the dreams of reason (New York: Bantam Books, 1989), geciteerd in Roger Lewin, complexity: life at the edge of chaos (New York: Macmillan, I992), p. 10.

[^194]: Lane, 'economic consequences of organized violence," op. cit, p.402.

[^195]: Frederic C. Lane, "the economic meaning of war and protection," in Venice and history: the collected papers qf Frederic C. Lane (Baltimore: The Johns Hopkins Press, 1966), pp.383-84.

[^196]: Shi Mai'an and Lao Guanzhong, outlaws of the marsh, vertaald door Sidney Shapiro (Bloomington: Indiana University Press, 1981), p.12.

[^197]: George E Will, 'Vaarwel aan de welvaartsstaten,' Washington Post, 17 december 1995, p. C7.

[^198]: Robert S. MeElvaine, De grote depressie: Amerika, 1929-1941 (New York: Times Books, 1984), p.292.

[^199]: Ibid., p.293.

[^200]: Smith, op. cit., p.75.

[^201]: Ibid., p.76.

[^202]: Ibid.

[^203]: Een van de eerste Argentijnse vakbonden die zich organiseerden, was de spoorwegvakbond in 1887. Zie Carmelo Mesa-Lago, *Social Security in Latin America: Pressure Groups, Stratification, and Inequality* (Pittsburgh: University of Pittsburgh Press, 1978), p.161.

[^204]: Voor details over de planning en de bouw van het C&O-kanaal, zie Robert J. Brugger, *Maryland: A Middle Temperament 1634-1980* (Baltimore: The Johns Hopkins Press, 1990), pp. 202-3f.

[^205]: Irving J. Sloan, *Our Violent Past: An American Chronicle* (New York: Random House, 1970), p.177

[^206]: Voor details over het geweld tijdens de spoorwegstakingen van 1877, zie ibid., en Brugger, op. ciL, pp. 341-44.

[^207]: Sloan, op. cit., p.202. Zie ook S. S. Boynton, "Miners' vengeance," Overland Monthly, vol.22 (1893), pp.303-7

[^208]: Benjamin Schwartz, "American inequality: its history and scary future," New York Times, 19 december 1995, p. A25.

[^209]: MeElvaine, op. cit., p.293.

[^210]: Ibid.

[^211]: Ibid.

[^212]: Henry C. Simons, 'Enkele overpeinzingen over syndicalisme', Journal of Political Economy, maart 1944, p. 22.

[^213]: Kelly, op. cit., pp.191-92.

[^214]: Gayle Ni. Hanson, 'Een meeslepend verslag van "het leven" in de postmodernistische cyberspace', Washington Times, 24 december 1995, p. B7.

[^215]: Een beknopte inleiding tot het academische onderzoek naar anarchie is te vinden in Gordon Tullock (red.), Explorations in the Theory of Anarchy (Blacksburg, Va.: Virginia Polytechnic Institute and State University, 1972). Zie ook Murray N. Rothbard, Power and Market.. Government and the Economy (Menlo Park, Calif., 1970); en Robert Nozick, Anarchy, State and Utopia (New York: Basic Books, 1974).

[^216]: Zie Pierre Clastres, Society Against the State: The Leader as Servant and the Humane Uses of Power Among the Indians of the Americas (New York: Urizen Books, 1977); en Jones, op. cit.

[^217]: Lane, *economische gevolgen van georganiseerd geweld*, op. cit., p.403.

[^218]: Charles Tilly, *oorlogsvoering en staatsvorming als georganiseerde misdaad*, in Peter B. Evans, Dietrich Rueschemeyer en Theda Skoepol, *de staat weer betrekken* (Cambridge: Cambridge University Press, 1985), p.169.

[^219]: Ibid.

[^220]: Lane, *economische gevolgen van georganiseerd geweld*, op. ciL, p.402.

[^221]: David J. Elkins, *voorbij soevereiniteit: territorium en politieke economie in de eenentwintigste eeuw*. Toronto: University of Toronto Press, 1995, pp. 13-14.

[^222]: Ibid., p. 29

[^223]: Jim Taylor en Watts Wacker, *The 500-year delta: what happens after what comes next.* New York: HarperCollins, 1997, p. 40.

[^224]: Ibid., p. 67

[^225]: Ibid., pp. 41-42

[^226]: George Gilder, *Fiber keeps its promise: get ready. Bandwidth will triple each year for the next 25, creating trillions in new wealth.* Forbes ASAP, 7 april 1997

[^227]: Zie Neal Stephenson, Snow Crash. New York: Bantam Books, 1993

[^228]: Keith B. Richburg, 'Twee jaar na de landing van de VS in Somalië is het weer chaotisch,' Washington Post, 4 december 1994, p. Al.

[^229]: Geciteerd in Tilly, coercion, capital and european states, op. cit., p. 85.

[^230]: Lane, 'Economische gevolgen van georganiseerd geweld,' op. ciL, p. 411.

[^231]: Ibid.

[^232]: Ibid.
[^233]: Ibid., p.412.
[^234]: Ibid., p.403.
[^235]: Ibid., p.404.
[^236]: Esther Dyson, *Release 2.1: een ontwerp voor het leven in het digitale tijdperk*. New York: Broadway Books, 1998, p. 131

[^237]: Rees Davies, *Frontier arrangements in fragmented societies: Ireland and Wales*, in Robert Bartlett en Angus MacKay (red.), *Medieval frontier societies* (Oxford: Oxford University Press, 1992), p.80.

[^238]: Zie Thomas W. Lippman, *Seychelles offers investors safe haven for $10 million*, Washington Post, 31 december 1995, p. A27.

[^239]: Zie *ROM of ages*, Wired, januari 1996, p.52.

[^240]: Geciteerd in James Adams, *Dawn of the cyber soldiers*, The Sunday Times (London), 15 oktober 1995, pp.3–5.

[^241]: Kelly, op. cit., p.19.

[^242]: George Melloan, 'Hervorming van de welvaartsstaat is grotendeels mythologisch', The Wall Street Journal. 14 oktober 1996, p. A19.

[^243]: Zie hoofdstuk 8 van *The Great Reckoning*, 'Lineaire verwachtingen in een niet-lineaire wereld: hoe de telescoop ons leerde rekenen; hoe de computer ons kan helpen te zien.'

[^244]: Merk op dat Lane's vier fasen van concurrentie en monopolie in het gebruik van geweld verschillen van de vier fasen in de organisatie van het economisch leven die wij onderscheiden, namelijk: jagen en verzamelen, landbouw, industrialisme en het informatietijdperk.