# Plaatsgebondenheid overstijgen

:::{.content-hidden when-format=latex}

*De opkomst van de cybereconomie*

:::

> 'Het echte vraagstuk is controle. Het internet is te wijdverspreid om gemakkelijk door één enkele regering beheerst te worden. Door een naadloze, wereldwijde economische zone te creëren, anti-soeverein en onreguleerbaar, stelt het internet het idee van een natiestaat ter discussie.'[^245] - John Perry Barlow

De informatie-snelweg is een van de bekendste metaforen uit de vroege dagen van het digitale tijdperk geworden. Hij valt op, niet alleen door zijn alomtegenwoordigheid, maar ook door het veelvoorkomende misverstand dat hij over de cybereconomie onthult. Immers, een snelweg is een industriële versie van een voetpad, een netwerk voor de fysieke verplaatsing van mensen en goederen. De informatie-economie is niet te vergelijken met een snelweg, een spoorlijn of een pijpleiding. Hij vervoert of verplaatst informatie niet van punt naar punt op dezelfde manier als de Trans-Canada Highway zware vrachtwagens van Alberta naar New Brunswick vervoert. Wat de wereld de 'informatie-snelweg' noemt, is niet louter een verbindingsroute; het is de bestemming.

Cyberspace overstijgt plaatsgebondenheid. Het houdt in dat gegevens onmiddellijk overal en nergens tegelijk worden gedeeld. De opkomende informatie-economie is gebaseerd op de verbindingen die miljoenen gebruikers van miljoenen computers met elkaar verbinden en opnieuw verbinden. De essentie ervan schuilt in de nieuwe mogelijkheden die uit deze verbindingen voortvloeien. Zoals John Perry Barlow zei: 'Wat het net ons biedt, is de belofte van een nieuwe sociale ruimte, globaal en anti-soeverein, waarin iedereen, overal, zonder angst kan uitdrukken wat hij of zij gelooft. In deze nieuwe media is al een voorbode te ontdekken van de intellectuele en economische vrijheid die alle autoritaire machten op aarde zou kunnen ontmantelen.'[^246]

Cyberspace, net als het denkbeeldige rijk van Homers goden, is een rijk dat losstaat van de vertrouwde aardse wereld van boerderijen en fabrieken. Toch zullen de gevolgen niet denkbeeldig zijn, maar reëel. In veel grotere mate dan velen zich nu realiseren, zal het onmiddellijke delen van informatie vergelijkbaar zijn met een oplosmiddel dat grote instellingen doet oplossen. Het zal niet alleen de logica van geweld veranderen, zoals we al hebben betoogd; het zal de informatie- en transactiekosten, die bepalen hoe bedrijven zich organiseren en op welke wijze de economie functioneert, radicaal wijzigen. Wij verwachten dat microverwerking de economische organisatie van de wereld zal transformeren.

> 'Het is tegenwoordig, in veel grotere mate dan ooit in de geschiedenis van de wereld, mogelijk voor een bedrijf zich overal te vestigen, overal middelen te benutten om een product te vervaardigen dat overal verkocht kan worden.' - MILTON FRIEDMAN

## De tirannie van de plaats

Het feit dat de eerste poging van het vervagende industriële tijdperk om de informatiemaatschappij te begrijpen bestaat uit het zien ervan als een gigantisch openbaar werkproject, toont aan hoe diep ons denken verankerd is in de paradigma’s van het verleden. Het is alsof je aan het einde van de achttiende eeuw boeren hoort spreken, die een fabriek omschrijven als 'een boerderij met een dak.' Toch is de metafoor van de 'snelweg' nog onthullender. Zij onthult tevens in hoeverre wij gevangen zitten in de tirannie van de plaats. Zelfs wanneer technologie ons in staat stelt de beperkingen van een specifieke locatie te overstijgen, krijgt het middel van onze bevrijding een bijnaam die aanduidt dat het een route is van plaats naar plaats. Net zoals zalmen, gemarkeerd door hun heimatdrang, is ons bewustzijn nog steeds diep gevormd door begrippen van localiteit.

In de gehele geschiedenis tot nu toe waren economieën gebonden aan een lokaal geografisch gebied. De meeste mensen die vóór de twintigste eeuw leefden, brachten hun dagen door als feitelijke gevangenen onder huisarrest, en waagden zich zelden verder dan een paar dagen lopen van de plaats waar zij geboren waren. Een reis over enige afstand was het werk van generaties. Slechts sporadisch zorgden een crisis, oorlog, pest of een ongunstige klimaatverandering voor een brede migratie. Om mensen uit een erbarmelijk dorp weg te lokken, was iets spectaculairs en dringends nodig. Niets minder kon hen ertoe aanzetten hun bezittingen in te pakken en op zoek te gaan naar een beter leven.

Tot voor kort werden de weinigen die buiten hun eigen omgeving naar kansen zochten, vaak beroemd. Denk eraan dat Marco Polo nog steeds bekendstaat om zijn omzwervingen over het Euraziatische continent om het hof van de Grote Khan te bezoeken. Hij was in zijn tijd de uitzondering. Er zijn maar weinig andere reisverslagen bewaard gebleven uit de premoderne periode. Onder de meer gelezen werken is *Mandeville's Travels*, geschreven in het Frans in 1357, opmerkelijk omdat het door iemand is samengesteld die Europa waarschijnlijk nooit heeft verlaten. Mandeville geeft verrukkelijke en vaak fantasierijke details over het leven in de wereld weer, waaronder de suggestie dat veel Ethiopiërs maar één voet hebben: “[D]e voet is zo groot dat hij het hele lichaam overschaduwt tegen de zon wanneer zij gaan liggen en rusten.”[^247]: Het is overduidelijk dat maar weinig van Mandeville’s tijdgenoten, die zijn populaire verhaal lazen, vermoedelijk wisten dat zijn Ethiopische “Bigfoot” niet bestond.

Pas toen de moderne tijd begon met de ontdekkingsreizen aan het einde van de vijftiende eeuw kwamen er duurzame contacten tussen de continenten. Onverschrokken kapiteins als Christopher Columbus en Vasco da Gama, die op zoek gingen naar de specerijenhandel, waren zo buitengewoon dat zij in vrijwel elk geletterd huishouden gedurende het grootste deel van vijf eeuwen zijn herinnerd.

Vanaf het ontstaan van de landbouw tot in de recente generaties werd het leven gekenmerkt door immobiliteit. Dit is tegenwoordig bijna vergeten, vooral in de Europese vestigingskolonies van de ‘Nieuwe Wereld’, waar beweging vloeiender is en iedereen zijn perspectief hanteert vanuit het oogpunt van een immigrant. Een thema in het basisonderwijs in Noord-Amerika is dat de kolonisten uit Europa kwamen op zoek naar vrijheid en kansen, wat waar is. Wat echter zelden wordt verteld, is hoe terughoudend de meesten waren om de reis te maken, zelfs wanneer zij thuis met armoede geconfronteerd werden. De weinigen die wel migreerden, moesten onvoorstelbare ontberingen doorstaan om zich te vestigen – zoals wij dat nu nauwelijks kunnen voorstellen. Alleen de meest ondernemende of de meest wanhopige armen ondernamen de reis. Midden in de zeventiende eeuw kwamen de gevangenen die opgesloten zaten in Bridewell, het beruchte correctiehuis van Londen, in opstand om te laten zien “hoe onwillig zij waren om naar Virginia te gaan.”[^248]: In 1720 woedden er rellen in de straten van Parijs om zwervers, dieven en moordenaars, die bestemd waren voor deportatie naar Louisiana, vrij te laten.

### Smalle horizonnen

Fysieke belemmeringen in communicatie en transport, die op de meeste momenten en plaatsen werden verergerd door beperkte taalkennis, hielden de menselijke activiteiten beperkt en lokaal. Nog aan het begin van de twintigste eeuw was het gebruikelijk dat Chinese dorpen, die op slechts vijf mijl van elkaar lagen, dialecten spraken die elkaar totaal niet verstaan, zelfs langs de kust. De lokale organisatie van bijna alle economieën legde daarmee de basis voor kleine markten en gemiste kansen. De kosten van de productiefactoren bleven hoog door de beperkte concurrentie. De toegang tot gespecialiseerde vaardigheden was minimaal. Met inkomens zo laag dat men nauwelijks boven de bestaansgrens uitstak, en zonder toegang tot extern kapitaal of efficiënte verzekeringsmarkten, zaten kleine boeren in grote delen van de wereld gevangen in armoede. We hebben enkele van de moeilijkheden onderzocht waarmee boeren werden geconfronteerd door het beperkte dorpsleven. Zelfs nu, terwijl we dit schrijven, worstelt minstens een miljard mensen, voornamelijk in Azië en Afrika, om te overleven op minder dan een dollar per dag.

## 'All politics is local'

In veel grotere mate dan vaak wordt beseft, heeft de beperkte mobiliteit van mensen en hun bezittingen onze kijk op de wereld bepaald. Zelfs degenen die het meest bereid lijken te beamen dat de aarde een kleine plek is aan het einde van de twintigste eeuw, denken nog steeds in termen die worden beperkt door verouderde opvattingen over industriële politiek. Dit wordt benadrukt door een slogan die in de jaren tachtig populair werd bij milieubewuste mensen: 'Denk globaal maar handel lokaal.' Het is een aansporing die de logica van de politiek weerspiegelt, een logica die altijd draaide om lokale machtsvoordelen.

De lokale denkwijze is altijd bepaald door de megapolitiek van alle vroegere samenlevingen. Alle topografische kenmerken die als barrières of als bevorderaars van machtsuitoefening dienen, zijn lokaal. Elke rivier, elke berg en elk eiland is lokaal. Het klimaat is lokaal. Temperatuur, neerslag en groeicondities variëren naarmate je een berg opklimt en oversteekt. Iedere microbe die circuleert, doet dat ergens, en niet op een andere plaats.

Het is dus niet verwonderlijk dat de tirannie van de plaats doordringt in onze opvattingen over hoe de samenleving georganiseerd moet zijn en moet functioneren. De machtsvoordelen die een bepaalde groep een lokaal monopolie op geweld hebben verschaft, zijn altijd ergens ontstaan en vervaagden langs de megapolitieke randen waar grenzen worden getrokken. Daarom is er nooit een wereldregering geweest.

Hoewel het belang van de plaats voor de uitoefening van macht zelden expliciet wordt benoemd, begonnen enkele pleitbezorgers van gedwongen herverdeling van de uitkomsten van menselijke activiteit al in de jaren dertig de afnemende invloed van de plaats te merken. Zij zagen in het moderne vervoer een verdeling van de sociale ruimte tussen de hoogbetaalde en de armen. Deze vrees werd treffend verwoord door John Dos Passos in The Big Money: 'De zwerver zit aan de rand van de snelweg, gebroken, hongerig. Boven hem vliegt een transcontinentaal vliegtuig vol hoogbetaalde leidinggevenden. De hogere klasse heeft zich in de lucht begeven, de lagere klasse op de weg: er is geen band meer tussen hen, het zijn twee naties.'[^249] Dit is een andere manier om te zeggen dat verbeterd vervoer de hefboomwerking van afpersing verminderde, simpelweg doordat het de keuze aan plaatsen vergrootte waar succesvolle mensen zich konden vestigen. Zeker, de zwerver op de weg beneden was geenszins in de positie om een schenking af te dwingen van degenen die boven hem vlogen. De tendensen die Dos Passos zestig jaar geleden opmerkte, zijn alleen maar meer uitgesproken geworden.

### Massatransport

In 1995 staken dagelijks, ergens ter wereld, een miljoen mensen de grenzen over. Dit vertegenwoordigt een verbluffende verandering ten opzichte van het verleden. Voor de twintigste eeuw was reizen zo zeldzaam dat de meeste grenzen louter als grensgebieden werden gezien en geen belemmering vormden voor doorgang. Paspoorten waren onbekend. De ontwikkeling van oceaanstomers, treinen en andere verbeterde vormen van vervoer zorgde voor een dramatische toename van de verplaatsingen. Echter, deze beweging werd steeds strenger gereguleerd door staten, waarvan de bevoegdheden werden uitgebreid door dezelfde verbeteringen in transport en communicatie die het reizen voor burgers goedkoper en gemakkelijker maakten. De opkomst van films en, vooral, televisie heeft daarnaast in belangrijke mate bijgedragen aan het verbreden van horizonnen en het stimuleren van reizen en immigratie. Toch zijn de fundamentele uitgangspunten van de sociale en economische organisatie tot op heden verankerd in de lokale context.

> '... om dat falen in lef te voorkomen, waarvoor de geschiedenis zo meedogenloos een straf eist. We moeten de moed hebben om alle technische extrapolaties tot hun logische conclusie te volgen.'[^250]: - Arthur C. Clarke

## De fout van minimale verwachtingen

De geografische beperking van de verbeelding is nog steeds zo strak dat enkele experts, die in 1995 het internet onderzochten, concludeerden dat het weinig commercieel potentieel heeft en vrijwel geen betekenis kent, behalve als elektronisch medium voor chat en als uitlaatklep voor pornografie. De vele twijfelaars over het economische belang van cyberspace zijn de kolonelblimps van het informatietijdperk. Hun zelfgenoegzaamheid evenaart die van het Britse establishment, dat in de jaren dertig geconfronteerd werd met de achteruitgang van het rijk. Elke keer dat elites zich bedreigd voelen, is hun eerste reactie ontkenning. Dit blijkt uit de hoop dat het internet nooit veel zal worden, soms onderschreven door autoriteiten die beter hadden moeten weten. We verwezen eerder naar het werk van David Kline en Daniel Burstein, *Road Warriors: Dreams and Nightmares Along the Information Highway*. Hun afwijzing van het economische potentieel van het net is een extra bewijs dat technisch goed geïnformeerd zijn niet synoniem is met het begrijpen van de gevolgen van technologie.[^251]

Zelfs de technisch meest deskundige waarnemers in het verleden slaagden er vaak niet in de implicaties van nieuwe technologieën te doorgronden. Een Brits parlementair comité, bijeengeroepen in 1878 om de vooruitzichten voor Thomas Edison's gloeilamp te beoordelen, verklaarde dat Edison's ideeën 'goed genoeg zijn voor onze trans-Atlantische vrienden, … maar de aandacht van praktische of wetenschappelijke mannen niet waard' waren.[^252]  
[^252]: Thomas Edison zelf was een man van grote visie, maar volgens hem zou de door hem uitgevonden fonograaf vooral door zakenmensen voor dictaten worden gebruikt.

Nog maar kort voordat de gebroeders Wright bewezen dat vliegtuigen konden vliegen, toonde de vooraanstaande Amerikaanse astronoom Simon Newcomb op gezaghebbende wijze aan waarom vliegen met een zwaarder-dan-lucht voertuig onmogelijk was. Hij concludeerde: 'De aantoonbaarheid dat geen enkele mogelijke combinatie van bekende stoffen, bekende vormen van machinebouw en bekende vormen van kracht samengebracht kan worden in een praktische machine waarmee mensen grote afstanden door de lucht kunnen vliegen, lijkt volgens de schrijver zo volledig als het is mogelijk om enig natuurkundig feit aan te tonen.'[^253]  
[^253]: 

Kort nadat vliegtuigen begonnen te vliegen, legde een andere gerenommeerde astronoom, William H. Pickering, aan het publiek uit waarom commercieel reizen nooit van de grond zou komen: 'De populaire geest beeldt zich vaak gigantische vliegende machines in die razendsnel de Atlantische Oceaan doorkruisen en een ontelbaar aantal passagiers vervoeren, op een wijze die vergelijkbaar is met onze moderne stoomschipvaart. … [I]t is duidelijk dat met onze huidige apparaten geen hoop bestaat om qua racesnelheid te concurreren met noch onze locomotieven, noch onze automobielen.'[^254]  
[^254]:

Eerder hebben we al een andere buitengewoon onjuiste voorspelling over het potentieel van een nieuwe technologie genoemd – de prognose van het begin van de twintigste eeuw door de makers van Mercedes dat er wereldwijd nooit meer dan een miljoen auto's zouden zijn. Zij wisten, bijna meer dan wie dan ook, veel van auto's, maar konden niet fouter zijn geweest in hun inschatting van de impact van auto's op de samenleving.

Gezien deze traditie van onwetend misverstand is het nauwelijks verwonderlijk dat veel waarnemers traag zijn in het doorgronden van de belangrijkste implicaties van de nieuwe informatietechnologie – namelijk dat deze de tirannie van de plaats overstijgt. De nieuwe technologie creëert voor het eerst een oneindig, niet-aards domein voor economische activiteiten. Het biedt de mogelijkheid om de nieuwe grenzen van de cybereconomie te verkennen, om 'wereldwijd te denken en wereldwijd te handelen'. Dit hoofdstuk verklaart waarom.

## Voorbij de plaatsgebondenheid

De verwerking en het gebruik van informatie vervangt in rap tempo fysieke producten als de belangrijkste bron van winst. Dit heeft ingrijpende gevolgen. Informatietechnologie koppelt het vermogen om inkomen te genereren niet langer aan de woonplaats in een specifieke geografische locatie. Aangezien een steeds groter deel van de waarde van producten en diensten wordt gecreëerd door ideeën en kennis toe te voegen aan het product, zal een steeds kleiner deel van de toegevoegde waarde binnen lokale rechtsgebieden terechtkomen. Ideeën kunnen overal worden geformuleerd en wereldwijd met de snelheid van het licht worden overgedragen. Dit betekent onvermijdelijk dat de informatie-economie radicaal anders zal zijn dan de economie van het fabrieks tijdperk.

We geven de critici toe dat een opsomming van de taken die je via het internet in 1996 had kunnen uitvoeren, wellicht alledaags lijkt. Er is tenslotte niets baanbrekends aan het lezen van een artikel over tuinieren op het net of aan het op afstand kopen van een kist wijn. Het potentieel van de cybereconomie kan echter niet louter worden beoordeeld op basis van haar vroege beginfase, net zoals het potentieel van de auto om de samenleving te transformeren niet kon worden ingeschat op wat er in 1900 om je heen te zien was. Wij verwachten dat de cybereconomie zich in verschillende stadia zal ontwikkelen.

1. De meest primitieve manifestaties van het informatietijdperk zien het internet louter als een medium voor informatie dat gewone transacties uit de industriële tijd faciliteert. Op dit moment is het internet niet meer dan een exotisch bezorgingssysteem voor catalogi. Virtual Vineyards, bijvoorbeeld één van de eerste cyberhandelaars, verkoopt eenvoudigweg wijn via een pagina op het World Wide Web. Zulke transacties ondermijnen de oude instituties nog niet direct, omdat ze gebruikmaken van industriële valuta en plaatsvinden binnen herkenbare rechtsgebieden. Dit gebruik van het internet heeft weinig megapolitieke impact.

2. In een tussenstadium van internetcommercie zal informatietechnologie op manieren worden ingezet die in de industriële era onmogelijk waren, zoals op het gebied van verre boekhouding of medische diagnose. Meer voorbeelden van deze nieuwe toepassingen van geavanceerde rekenkracht worden hieronder toegelicht. Het tweede stadium van netcommercie zal nog steeds functioneren binnen het oude institutionele kader, waarbij nationale valuta worden gebruikt en men zich onderwerpt aan de jurisdictie van natiestaten. De handelaren die het internet voor verkoop inzetten, zullen het nog niet gebruiken om hun winsten te beheren, maar uitsluitend om inkomsten te genereren. Deze winsten uit internettransacties zullen nog steeds aan belastingheffing onderworpen zijn.

3. Een meer gevorderd stadium zal de overgang markeren naar echte cybercommercie. Niet alleen zullen transacties via het internet plaatsvinden, maar ze zullen ook buiten de jurisdictie van natiestaten vallen. Betalingen zullen worden verricht in cybervaluta, winsten worden geboekt in cyberbanken en investeringen zullen worden gedaan via cybermakelaardijen. Veel transacties zullen niet aan belastingheffing onderworpen zijn. In dit stadium zal cybercommercie beginnen met significante megapolitieke gevolgen, zoals eerder geschetst. De macht van overheden over traditionele economische domeinen zal door de nieuwe logica van het internet worden getransformeerd. Extraterritoriale regelgevende macht zal instorten, jurisdicties zullen worden gedecentraliseerd en de structuur van bedrijven zal veranderen, evenals de aard van werk en tewerkstelling. Dit overzicht van de stadia van de informatierevolutie is slechts de bleekste schets van wat wellicht het meest ingrijpende economische transformatiegebeurtenis zou kunnen worden.

## De globalisering van handel

In het informatietijdperk zullen de meeste huidige jurisdictievoordelen door technologische ontwikkelingen snel worden uitgehold. Nieuwe soorten voordelen zullen ontstaan. Dalende communicatiekosten hebben al de noodzaak voor nabijheid als voorwaarde voor zakendoen verminderd. In 1946 was het technisch mogelijk voor een investeerder in Londen om via een makelaar in New York een order te plaatsen, maar alleen de grootste en meest overtuigende transactie zou dit hebben gerechtvaardigd: een telefoongesprek van drie minuten tussen New York en Londen kostte toen $650. Tegenwoordig kost zo'n gesprek slechts $0,91. De prijs van een intercontinentaal telefoongesprek is in een halve eeuw met meer dan 99 procent gedaald.

### Convergente communicatie

Binnenkort zou het verschil tussen intercontinentale chat en een lokaal telefoongesprek minimaal kunnen zijn. Evenzo zouden de verschillen tussen je telefoon, je computer en je televisie gering kunnen zijn. Ze zullen allemaal interactieve communicatieapparaten zijn, die je eerder op basis van ergonomie dan op functionaliteit onderscheidt. Je zult via het internet een spraakgesprek kunnen voeren met behulp van microfoons en luidsprekers op je persoonlijke computer. Of een film kunnen bekijken. Je zult ook met je televisie kunnen communiceren en enorme hoeveelheden data kunnen uitwisselen via het netwerk dat door de televisie-entertainmentmedia wordt aangeboden. Naarmate het tijdens het industriële tijdperk bestaande onderscheid tussen verschillende vormen van communicatie verdwijnt en de kosten kelderen, zullen steeds meer diensten je per gebruikstijd in rekening brengen in plaats van op basis van de bestemming van je berichten. Zowel gesprekken als datatransmissies, overal ter wereld, zullen nauwelijks meer kosten dan een lokaal telefoongesprek in de meeste rechtsgebieden in 1985.

### Internet onbedraad

Lage-baan satellieten en andere benaderingen van draadloze technologie zullen signalen heen en weer verzenden, rechtstreeks naar een beeper in je zak, een draagbare computer of een werkstation, zonder dat er verbinding gelegd hoeft te worden met een lokaal telefonienet of een kabel-tv-systeem. Kortom, het internet zal onbedraad zijn. De eerste stappen in die richting zullen ongetwijfeld stroef verlopen vanwege de relatief trage snelheid van datatransmissie in de vroege draadloze media en de moeilijkheden met het opvangen van zwakke signalen die worden uitgezonden door abonneetoestellen, waarvan sommige mobiel zijn en op batterijen werken. Niettemin zullen deze technische problemen worden aangepakt en opgelost.

### Zakendoen zonder grenzen

De voortdurende uitbreiding van de rekenkracht zal leiden tot een verbeterde compressietechnologie, waardoor de gegevensstroom versnelt. De wijdverspreide toepassing van bestaande algoritmes voor encryptie met publieke en private sleutels zal aanbieders, zoals satellietsystemen, in staat stellen de factureringsfunctie in de dienst te integreren, wat de kosten verlaagt. Tegelijkertijd zullen leveranciers in staat zijn om accounts die op persoonlijke computers zijn geladen te debiteren, op dezelfde wijze als France Telecom de 'smartcards' in de telefoonhokjes in Parijs debiteert.

### De telefoon wordt een bank

Het verschil is dat je in de nabije toekomst credits op je rekening zult verdienen via allerlei transacties en dat je jouw telefooncel altijd met je mee kunt nemen. Je pc zal fungeren als het filiaal van je bank en als een wereldwijde geldbemiddelaar, evenals als het equivalent van het Parijse loket waar je je anonieme telefoonkaart aanschaft. En net als de 150 betaaltelefoons met smartcards, die voor dieven waardeloos zijn als ze met een koevoet worden opengebroken, kan jouw computer alleen worden gehackt door iemand die in staat is om geavanceerde computercode te kraken of te manipuleren. Dat zou veel rakkers, die wel met een koevoet kunnen werken, buiten spel laten.

Met de juiste encryptie kan niets op je computer worden ontcijferd of misbruikt.

Tegen het millennium zul je bijna overal, ten noorden van Antarctica, in staat zijn om zaken te doen. Overal waar bedrade of digitale mobiele telefonie beschikbaar is, overal waar interactieve kabeltelevisiesystemen in gebruik zijn, en overal waar een satelliet in zicht is of andere draadloze transmissiesystemen operationeel zijn. Je zult in staat zijn om te spreken, data over te dragen en via virtual reality vrij over grenzen en barrières te reizen. Telefoonnummers die de locatie van de beller aangeven aan de hand van netnummers zullen waarschijnlijk worden vervangen door universele toegangsnummers, waarmee je de partij bereikt met wie je overal ter wereld wilt communiceren.

### Chinees begrijpen

U zult niet alleen kunnen praten en een fax sturen. Na verloop van tijd zult u in staat zijn om een leerproces van meerdere jaren te verkorten en in het Chinees te converseren met een voorman in een fabriek in Shanghai. Het zal minder uitmaken dat u zijn taal of dialect niet spreekt. Zijn woorden mogen in het Chinees zijn, maar u zult ze horen als ‘transcending locality i 8’, grofweg vertaald naar het Engels. Hij zal uw gesprek in het Chinees horen. Na verloop van tijd zal het vermogen om onmiddellijke vertaling toe te passen de concurrentie in regio’s waar taal- en uitdrukkingsobstakels tot dusver significant waren, aanzienlijk verhogen. Wanneer dat gebeurt, zal het nauwelijks of helemaal niet uitmaken dat de Chinese regering mogelijk niet wil dat de oproep wordt geplaatst.

### Gepersonaliseerde media

Naarmate de wereld steeds dichter naar elkaar toe groeit, krijgt u meer mogelijkheden dan ooit tevoren om uw specifieke plaats daarin aan te passen. Zelfs de informatie die u regelmatig van de media ontvangt, zal informatie zijn die u zelf kiest. De massamedia zal veranderen in gepersonaliseerde media. Als u boven alles geïnteresseerd bent in schaken of een fervent kattenliefhebber bent, zult u uw avondnieuwsuitzending kunnen programmeren zodat deze informatie bevat die voor u belangrijk is over katten of schaken. U bent dan niet langer overgeleverd aan Dan Rather of de BBC voor het nieuws dat u bereikt. U zult in staat zijn nieuws te selecteren dat volgens uw instructies is samengesteld en bewerkt.

### Van massa naar op maat gemaakte productie

Als het nieuws traag verloopt, kunt u een virtuele catalogus raadplegen op het World Wide Web. Als u een broek ziet die u bijna bevalt, kunt u de breedte van de pijpen aanpassen wanneer u uw bestelling plaatst. De broek wordt op maat gesneden en door robots in Maleisië aangepast aan uw lichaam, op basis van foto's die in uw computer zijn ingescand en via het net zijn verzonden.

### Cyberbroking

Je zult in staat zijn om cybergeld te gebruiken om te investeren en om te betalen voor diensten en producten. Als je in een rechtsgebied woont zoals de Verenigde Staten, dat je investeringsmogelijkheden sterk reguleert, kun je ervoor kiezen om je activiteiten te vestigen in een rechtsgebied dat de vrijheid biedt om een volledig scala aan investeringsopties na te streven. Of je nu in Cleveland of Belo Horizonte woont, je kunt je investeringszaken doen in Bermuda, de Kaaimaneilanden, Rio de Janeiro of Buenos Aires. Waar je je ook bevindt, zal het gebruik van digitale middelen toenemen naarmate de cybereconomie zich ontwikkelt. Je zult expertssystemen kunnen inzetten om je investeringen te selecteren en cyberaccountants en -boekhouders om de voortgang van je portefeuille in realtime te monitoren.

### Virtuele cultuur

Wanneer je geen winst- en verliesgegevens bekijkt, kun je een virtueel bezoek brengen aan het Louvre. Voor je bezoek kan het nodig zijn een royalty te betalen ter waarde van een derde van een cent aan Bill Gates, of aan iemand met een vergelijkbare vooruitziende blik die de rechten op virtuele realiteit voor een museumbezoek heeft verworven. Terwijl je je afvraagt of de Mona Lisa problemen met haar tanden had, kan je computer ondertussen S. I. Hsiung’s vertaling van De romance van de westerse kamer downloaden. Op momenten van jouw keuze zal je persoonlijke communicatiesysteem de tekst voorlezen, zoals een bard uit weleer. Multitaskingprogramma’s stellen je in staat om vele functies gelijktijdig uit te voeren.

### Het uitkiezen van rechtsgebieden op het internet

Als je door je dosis klassiekers geïnspireerd bent, kun je een virtuele onderneming oprichten om dramatische producties van beroemde literatuur op de markt te brengen voor weergave via een driedimensionale netvliesweergave. In plaats van in de lucht geprojecteerd te worden, zullen de beelden rechtstreeks op de netvliezen van kijkers worden geprojecteerd met laagenergetische lasers die vijftigduizend keer per seconde fluctueren. Deze technologie, die al in ontwikkeling is door MicroVision uit Seattle, Washington, zal veel mensen die wettelijk blind zijn in staat stellen te zien. Voordat je aan het project begint, kun je je digitale assistent opdracht geven om de huidige contractaanbiedingen voor de bescherming van productiefaciliteiten in Maleisië, China, Peru, Brazilië en Tsjechië in kaart te brengen. Wanneer je een locatie kiest, kun je dankzij de St. George's Trust Company je bedrijf in één uur laten registreren in de Bahama’s. Je instructies zullen alle liquide activa van het bedrijf onderbrengen in een cyberrekening bij een cyberbank die tegelijkertijd is gevestigd in Newfoundland, de Kaaimaneilanden, Uruguay, Argentinië en Liechtenstein. Als een van deze rechtsgebieden probeert de operationele bevoegdheid in te trekken of de activa van de depositohouders in beslag te nemen, zullen de activa automatisch met de lichtsnelheid naar een ander rechtsgebied worden overgeheveld.

## Kwalitatieve vooruitgang

Veel van de transacties die je binnenkort in cyberspace zult kunnen uitvoeren, zouden in het industriële tijdperk onmogelijk zijn geweest, en dat niet alleen omdat ze een taalbarrière oversteken. Het inzetten van je digitale assistenten om onvertaalde artikelen te verzamelen uit Hongaarse wetenschappelijke tijdschriften is kwalitatief anders dan een gesprek voeren met een bibliothecaris. Het deelnemen aan een Oxford-tutorial over een afstand van vijfduizend mijl is niet hetzelfde als het volgen van de tutorial terwijl je binnen zes mijl van Carfax slaapt. En roulette spelen in het Hotel de Paris in Monte Carlo is een geheel nieuwe ervaring wanneer je dit via virtual reality kunt doen vanuit een feest in Punte del Este, Uruguay.

### Een cyberbezoek aan de cyberdokter

In korte tijd, sneller dan veel experts nu denken dat mogelijk is, zullen activiteiten naar de cybereconomie migreren, waarbij technologieën op vernieuwende manieren worden gecombineerd om de tirannie van de plaats en de verouderde instituties van de industriële economie te overstijgen. Binnenkort, als je buikpijn hebt, zul je een digitale dokter kunnen raadplegen, een expertsysteem met een encyclopedische kennis van symptomen, kwalen en tegengif. Deze zal je medische geschiedenis, in versleutelde vorm, raadplegen en vragen of je pijn optreedt na het eten of vóór de maaltijd. Of je pijn nu scherp of dof is, constant of episodisch, wat voor vragen artsen ook stellen, de digitale dokter zal ze stellen. Het kan concluderen dat je te veel wijn drinkt, of juist te weinig. Mogelijk word je doorverwezen naar een cyberspecialist. Als je een operatie nodig hebt, kan een cyberschirurg in Bermuda de ingreep op afstand uitvoeren met behulp van gespecialiseerde apparatuur die micro-incisies maakt.

### Leven-en-dood informatieverwerking

Dit klinkt misschien als sciencefiction. Maar veel componenten van cyberchirurgie zijn al aanwezig. Andere zullen functioneel zijn tegen de tijd dat je dit boek leest. General Electric heeft een nieuwe machine voor magnetische resonantietherapie (MRT) geïntroduceerd in vijftien ziekenhuizen over de hele wereld. Er wordt verwacht dat de machine een driejarig onderzoeks‑ en ontwikkelingstraject zal doorlopen, maar daarna zal zij waarschijnlijk snel verspreid raken en de norm worden voor vele soorten operaties. Het is een voorbeeld, en een goed voorbeeld, van hoe technologie de samenleving verandert.

De meesten van ons kennen MRI‑machines, waarin magnetische resonantietechnieken worden ingezet om artsen beelden van zacht weefsel voor diagnostische doeleinden te verschaffen. Zij leveren betere beelden van zacht weefsel dan röntgenfoto’s of echografie, en zijn een onmisbaar onderdeel geworden van de moderne diagnostiek, met name bij kanker. Ze hebben echter op dit moment twee belangrijke beperkingen. De buis laat geen vrije toegang tot de patiënt toe, en bovendien zijn de machines niet erg krachtig.

### Cyberchirurgie

General Electric heeft de magnetische resonantiemachines zodanig herontworpen dat ze niet alleen voor diagnose, maar ook voor behandeling ingezet kunnen worden. De kracht is vijfmaal verhoogd. De buis is in feite in tweeën gesneden, waardoor de patiënt tussen twee donutvormige eenheden komt te liggen in plaats van volledig omsloten te worden. In plaats van eerst een beeld vast te leggen en op basis daarvan de operatie uit te voeren, zal de chirurg direct kunnen zien wat hij doet terwijl hij bezig is. De MRT zal worden gecombineerd met niet‑invasieve, of minder invasieve, chirurgie met behulp van microtechnieken. In plaats van grote incisies met een scalpel te moeten maken, zal de chirurg kleine incisies zetten met sonderingsinstrumenten en in real‑time kunnen zien wat deze onthullen tijdens de operatie. Hij voert de operatie uit op basis van het beeld in plaats van er direct in te kijken. In principe kunnen de sonderingsinstrumenten op afstand bediend worden. Ze zullen in staat zijn tumoren met uiterste precisie te vernietigen met behulp van laser‑, of cryogene warmte‑ en vriesapparaten.

This will permit operations that are now impossible, particularly in neurosurgery, where tumors often lie very close to essential parts of the brain.  
This will also permit repeated operations, when the trauma of the traditional surgical operation cannot be repeated without unacceptable damage.  
Some researchers believe that the knife for soft-tissue surgery may be looked back on as an obsolete relic by 2010.  
A lot of fear, and much of the aftershock, will be taken out of surgery if that is true.  
Obviously, this is very good news for the patient.  
Operations which now take hours to perform, and have to be followed by days or weeks in the hospital, will take only half an hour, and may not require hospitalization at all.  
Indeed, the surgeon and the patient may never even be in the same room.  
But what will this do to hospitals and surgeons?

Dit zal operaties mogelijk maken die nu onmogelijk zijn, met name op het gebied van neurochirurgie, waar tumoren zich vaak zeer dicht bij vitale delen van de hersenen bevinden.  
Het zal ook herhaalde operaties mogelijk maken, wanneer het trauma van de traditionele chirurgische ingreep niet herhaald kan worden zonder onaanvaardbare schade.  
Sommige onderzoekers zijn van mening dat het mes voor weke delenchirurgie tegen 2010 als een verouderd relikwie zal worden beschouwd.  
Er zal veel van de angst én de naschokken uit de chirurgie worden gehaald als dat waar blijkt te zijn.  
Uiteraard is dit zeer goed nieuws voor de patiënt.  
Operaties die nu uren duren en gevolgd moeten worden door dagen of weken in het ziekenhuis, zullen nog maar een half uur in beslag nemen en mogelijk helemaal geen ziekenhuisopname vereisen.  
Inderdaad, de chirurg en de patiënt zullen misschien nooit eens in dezelfde ruimte aanwezig zijn.  
Maar wat zal dit betekenen voor ziekenhuizen en chirurgen?

### Minder microsurgen die meer operaties uitvoeren

Er staat een revolutie in de chirurgie voor de deur.  
Tijdens de opleiding is een derde van de jonge chirurgen er niet in geslaagd de vaardigheden voor microscopische chirurgie onder de knie te krijgen.  
Eén derde beheerst het net zo, en één derde wordt uitmuntend.  
Vergelijkbare verhoudingen worden gevonden in omscholingscursussen voor ervaren chirurgen.  
Minder chirurgen zullen in staat zijn meer operaties in een kortere tijd uit te voeren.  
Het is waarschijnlijk dat zorgverzekeraars en patiënten die een operatie ondergaan zullen aandringen op prestatiestatistieken per chirurg, die behoorlijk uiteen kunnen lopen.  
Patiënten zullen de voorkeur geven aan chirurgen die de beste resultaten behalen, zeker als hun toestand levensbedreigend is.  
In sommige gevallen zullen de beste chirurgen op afstand opereren.  
Zij kunnen de gehele operatie uitvoeren vanuit een ander rechtsgebied waar de belastingen lager zijn en waar de rechtbanken buitensporige claims wegens medische fouten niet honoreren.

### Digitale juristen

Voordat de bekwame chirurg instemt met het uitvoeren van een operatie, zal hij of zij waarschijnlijk de hulp inroepen van een digitale jurist om een direct contract op te stellen waarin de aansprakelijkheid wordt gespecificeerd en beperkt op basis van de grootte en kenmerken van de tumor zoals die in de beelden van de magnetische resonantiemachine worden getoond.  
Digitale juristen zullen functioneren als systemen voor informatieopvraging die automatisch de keuze voor contractbepalingen regelen, waarbij zij gebruikmaken van kunstmatige-intelligentietechnologieën zoals neurale netwerken om particuliere contracten op maat te maken die voldoen aan transnationale juridische voorwaarden.  
Deelnemers aan de meeste waardevolle of belangrijke transacties zullen niet alleen op zoek gaan naar geschikte partners om zaken mee te doen; zij zullen ook zoeken naar een geschikt vestigingsadres voor hun transacties.

### Spoedconsultatie

Om het voorbeeld van cybersurgery voort te zetten zal de technologie van het informatietijdperk de allerbeste chirurgische vaardigheden extra waarde geven, zoals in vrijwel elke andere onderneming ook het geval zal zijn. Patiënten zijn altijd bereid geweest om zo’n meerprijs te betalen, al zolang er messen bestaan. Beperkingen in informatie en de moeilijkheid om in een noodsituatie in een specifieke regio naar een chirurg te zoeken, hebben de markt voor chirurgie zeer onvolmaakt gemaakt. In het informatietijdperk zal deze markt minder onvolmaakt zijn. Een patiënt die binnen 24 uur – of misschien zelfs al binnen 45 minuten – een operatie nodig heeft, zou digitale assistenten kunnen inzetten om de tien beste chirurgen wereldwijd te vinden die op afstand een dergelijke ingreep kunnen uitvoeren, hun slagingspercentages in vergelijkbare gevallen te beoordelen en via geschikte digitale bedienden aanbiedingen voor zijn specifieke geval in te winnen. Dit alles kan binnen enkele ogenblikken worden geregeld. Als gevolg hiervan zal de best bevoordeelde 10 procent van de chirurgen een veel groter aandeel veroveren op de wereldwijde markt voor chirurgie. De MRT-machine, samen met technieken voor microchirurgie, zal de meerprijs voor hun werk verder verhogen. Chirurgen met minder bekwaamheid zullen zich richten op de sprake overgebleven lokale markten.

Dit leven-en-doodvoorbeeld suggereert enkele van de revolutionaire gevolgen van het bevrijden van economieën van de dwang van plaatsgebondenheid. Iemand zou kunnen aanvoeren dat de MRT-machine van General Electric niet bedoeld was voor gebruik op lange afstand. Wellicht, maar dat raakt de kern van de zaak niet. Het apparaat – of een dergelijk vergelijkbaar toestel – zal dat spoedig worden. Wanneer operaties beter worden uitgevoerd door chirurgen die via een scherm werken in plaats van de patiënt rechtstreeks te bekijken, zal het minder uitmaken waar de chirurg en zijn scherm zich bevinden dan we nu veronderstellen. Steeds meer diensten zullen zodanig worden heringericht dat rekening wordt gehouden met het feit dat informatietechnologie mensen overal ter wereld in staat stelt zelfs in zo’n delicate aangelegenheid als chirurgie met elkaar in verbinding te treden. In activiteiten waarbij minder precieze apparatuur nodig is en de kans op mislukking lager is, zal de cybereconomie nog sneller floreren.

> 'Het financiële beleid van de verzorgingsstaat vereist dat er voor de bezitters van rijkdom geen enkele mogelijkheid is om zichzelf te beschermen.' - Alan Greenspan

## Devaluatie van dwang

In bijna elk concurrerend gebied, inclusief het merendeel van 's werelds multitriljoen-dollar investeringsactiviteiten, zal de migratie van transacties naar cyberspace worden gedreven door een bijna hydraulische druk – de drang om roofzuchtige belastingen te ontwijken, waaronder de belasting die inflatie oplegt aan iedereen die zijn vermogen in een nationale munteenheid aanhoudt.

### Ontsnappen aan het beschermingsracket

Je hoeft niet lang na te denken over de megapolitiek van het informatietijdperk om te beseffen dat roofzuchtige belastingen en inflatie, zoals die door de rijkste geïndustrialiseerde landen als vanzelfsprekende zaak aan hun burgers worden opgelegd, belachelijk onconcurrerend zullen zijn op de nieuwe grens van cyberspace. Kort na de millenniumwisseling zal iedereen die momenteel inkomstenbelasting betaalt, uit eigen keuze 50 procent betalen. Zoals Frederic C. Lane opmerkte, toont de geschiedenis aan dat 'aan de grenzen en op de hoge zeeën, waar niemand een blijvend monopolie had op het gebruik van geweld, handelaren de betaling van heffingen vermeden die zo hoog waren dat bescherming op andere, goedkopere wijze verkregen kon worden.' [^255]:

De cybereconomie biedt precies zo'n alternatief. Geen overheid zal erin slagen deze te monopoliseren. Bovendien zullen de daarbij behorende informatietechnologieën een goedkopere en effectievere bescherming bieden voor financiële activa dan de meeste overheden ooit hadden kunnen bieden.

### De zwarte magie van samengestelde rente

Onthoud: elke jaarlijkse belastingbetaling van $5.000, gedurende veertig jaar, verlaagt je nettovermogen met $2,2 miljoen – ervan uitgaande dat je op je kapitaal slechts een rendement van 10 procent behaalt. Bij een rendement van 20 procent groeit het samengestelde verlies tot ongeveer $44 miljoen. Voor hoogverdieners in een land met hoge belastingen zijn de cumulatieve verliezen door roofzuchtige belastingheffing over een levenweg adembenemend. De meesten zullen meer verliezen dan zij ooit hebben bezeten.

Dit klinkt onmogelijk, maar de wiskunde is glashelder. Je kunt het zelf gemakkelijk verifiëren met een zakrekenmachine. De top 1 procent van de belastingbetalers in de Verenigde Staten betaalt gemiddeld meer dan $125.000 aan federale inkomstenbelasting per jaar. Voor een fractie van dat bedrag – $45.000 per jaar – zou je welkom zijn om onder een particulier belastingverdrag in Zwitserland te leven en te profiteren van de orde en veiligheid, die wordt geboden door wat wel gezegd mag worden dat het meest integrale politie- en rechtssysteem ter wereld is. Vanuit dat oogpunt zou de extra $80.000 aan inkomstenbelasting die jaarlijks boven dit royale niveau wordt betaald, reëel als tribuut of plundering kunnen worden bestempeld. Vijfenveertigduizend dollar is immers een aanzienlijke bijdrage aan het in stand houden van orde en veiligheid, aangezien politiebescherming als een publiek goed wordt beschouwd. In theorie kunnen publieke goederen zonder extra marginale kosten aan meer gebruikers worden aangeboden. De Zwitsers zijn er dan ook blij mee dat je een onderhandelde vaste belasting van $45.000 (50.000 Zwitserse frank) per jaar betaalt, want op elke miljonair die zich aanmeldt, maken zij jaarlijks een winst van $45.000.

In vergelijking met de Zwitserse variant zouden de levenslange verliezen voor een belegger die gemiddeld een rendement van 20 procent behaalt, als gevolg van het betalen van federale inkomstenbelasting tegen Amerikaanse tarieven, $705 miljoen bedragen. Onthoud wel dat dit uitgaat van een jaarlijkse belastingbetaling van $45.000. Vergeleken met een belastingparadijs als Bermuda, waar de inkomstenbelasting nihil is, zou het levenslange verlies voor belastingen tegen Amerikaanse tarieven ongeveer $1,1 miljard bedragen.

Je zou kunnen aanvoeren dat een jaarlijks rendement van 20 procent bijzonder hoog is. Dat heb je ongetwijfeld gelijk in. Maar gezien de opvallende groei in Azië in de afgelopen decennia hebben veel beleggers wereldwijd dat rendement – of zelfs meer – behaald. Het samengestelde rendement op Hongkongse vastgoedbeleggingen bedraagt sinds 1950 meer dan 20 procent per jaar. Zelfs economieën die minder bekend staan om hun groei hebben vaak makkelijke kansen voor hoge winsten geboden. Je had de afgelopen drie decennia een reëel gemiddeld rendement van meer dan 30 procent per jaar kunnen behalen met deposito’s in Amerikaanse dollars bij Paraguayaanse banken. Hoge investeringsrendementen zijn op sommige plaatsen makkelijker te realiseren dan elders, maar bekwame beleggers kunnen in goede jaren zeker winsten van 20 procent of meer behalen, zelfs als ze niet telkens de prestaties van George Soros of Warren Buffett evenaren.

Het is overduidelijk: hoe hoger het rendement dat je op je kapitaal kunt behalen, des te groter de opportuniteitskosten die door roofzuchtige inkomsten- en vermogenswinstbelastingen worden opgelegd. Toch berust de conclusie dat het verlies enorm is – zelfs meer dan de totale rijkdom die je ooit zou kunnen vergaren – niet op het feit dat je buitensporige rendementen behaalt. Sommige in de Verenigde Staten opererende beleggingsfondsen hebben al meer dan een halve eeuw een gemiddeld jaarlijks rendement van meer dan 10 procent geboekt. Als dit het beste is wat je kunt behalen en je behoort tot de top 1 procent van de Amerikaanse verdieners, dan wordt je nettovermogen met meer dan $33 miljoen verminderd, enkel door de inkomstenbelasting die je boven de $45.000 per jaar betaalt. In vergelijking met een jurisdictie zonder inkomstenbelasting is dat verlies zelfs $55 miljoen.

$55 in plaats van $55 miljoen

Als de winstmaximaliserende veronderstellingen van economen kloppen – zoals wij over het algemeen aannemen – is een van de zekerste voorspellingen dat de meeste mensen $55 miljoen zouden proberen te redden als ze dat konden. Dat is onze voorspelling. 

Wanneer de zwarte magie van samengestelde rente duidelijker wordt in de hoofden van succesvolle mensen in landen met hoge belastingen, zullen zij beginnen om serieus tussen rechtsgebieden te winkelen, net zoals zij nu auto's kopen of verzekeringspremies vergelijken. 

Als je er aan twijfelt, houd dan gewoon willekeurig mensen op de straten van New York of Toronto tegen en vraag of ze voor $55 miljoen naar Bermuda zouden verhuizen. De vraag beantwoordt zichzelf. 

Het dilemma dat hierbij opkomt, doet denken aan de keuze die Mark Twain zich ooit voorstelde: of hij de nacht doorbracht met Lillian Russell, volledig naakt, of met generaal Grant in vol ornaat uniform. Hij aarzelde niet lang. 

Bewoners van gevestigde verzorgingsstaten, met name in de Verenigde Staten, zullen wellicht wat langzamer reageren – dat komt er immers alleen door dat zij zich nog niet bewust zijn van de keuze die hen te wachten staat. In de loop der tijd zal dat veranderen. 

Jij, of wie dan ook die streeft naar een beter leven, zal de aantrekkingskracht inzien om de verliezen die jij lijdt door roofzuchtige belastingheffing te beperken. 

Je hoeft alleen maar je transacties in cyberspace te deponeren. Dit zal natuurlijk in veel rechtsgebieden illegaal zijn. Maar oude wetten kunnen zich zelden verzetten tegen nieuwe technologie. 

In de jaren tachtig was het in de Verenigde Staten illegaal een faxbericht te versturen. Het Amerikaanse postkantoor beschouwde faxen als eersteklas post, waarop het een eeuwenoud monopolie claimde. Er werd een bevelschrift uitgegeven waarin werd benadrukt dat alle faxtransmissies via het dichtstbijzijnde postkantoor moesten worden geleid voor levering met gewone post. 

Na miljarden faxberichten is het onduidelijk of iemand ooit aan die wet heeft voldaan – en zo ja, dan was die naleving slechts van korte duur. De voordelen van het opereren in de opkomende cybereconomie zijn nog overtuigender dan het soms omzeilen van het postkantoor bij het versturen van een fax.

De wijdverspreide adoptie van public-key/private-key-encryptietechnologieën zal binnenkort veel economische activiteiten op elke gewenste locatie mogelijk maken. Zoals James Bennet, technologie-redacteur van Strategic Investment, schreef:

> De handhaving van wetten en met name belastingwetgeving is sterk afhankelijk geworden van het toezicht op communicatie en transacties. Zodra de volgende logische stappen zijn gezet en offshorebanken de dienst aanbieden van communicatie via hard RSA-versleutelde e-mail met rekeningnummers afgeleid van public-key-systemen, zullen financiële transacties bijna onmogelijk te monitoren zijn, zowel bij de bank als in de communicatie. Zelfs als de belastingautoriteiten een mol in de offshorebank zouden plaatsen, of in de bankadministratie zouden inbreken, zouden zij niet in staat zijn de rekeninghouders te identificeren.[^256]

Tot op een niveau dat nog nooit eerder mogelijk was, zullen individuen kunnen bepalen waar zij hun economische activiteiten vestigen en hoeveel inkomstenbelasting zij willen betalen. Veel transacties in het informatietijdperk hoeven helemaal niet binnen een territoriale soevereiniteit te worden ondergebracht. Degenen die dat wel moeten, zullen steeds vaker terechtkomen in plaatsen als Bermuda, de Kaaimaneilanden, Uruguay of vergelijkbare rechtsgebieden die geen inkomstenbelastingen of andere kostbare transactielasten opleggen aan de handel.

### Van monopolie naar concurrentie

Overheden zijn eraan gewend geraakt om 'beschermingsdiensten' op te leggen die, om in de woorden van Frederic C. Lane te zeggen, 'van slechte kwaliteit en belachelijk overprijsd' zijn.[^257] Deze gewoonte om veel meer te vragen dan de werkelijke waarde van overheidsdiensten, is in de loop van eeuwen van monopolievorming ontstaan. Belastingen werden meedogenloos geheven bij iedereen die naar schijn in staat was te betalen – juist omdat overheden een monopolie of bijna-monopolie op dwang hadden. Deze traditie van monopolie zal ingrijpend botsen met de nieuwe megapolitieke mogelijkheden van cyberhandel.

Encryptie zal het makkelijk maken om transacties in de cybersfeer te beschermen. De kosten van een effectief encryptiesoftwareprogramma, zoals PGP, zijn lager dan de commissie die een full-service makelaar rekent op een transactie van honderd aandelen. Toch zal het vrijwel elke transactie onzichtbaar en onaantastbaar maken voor zowel overheden als dieven, nog vele jaren lang. De nieuwe technologie van het informatietijdperk zal cyberactiva tegen een verwaarloosbaar lage kost effectief beveiligen. Voor $55 in plaats van $55 miljoen zullen deelnemers aan de cybereconomie daadwerkelijk betere bescherming van hun activa genieten dan tijdens het industriële tijdperk of op enig ander moment in de geschiedenis. Gebruiksvriendelijke encryptie-algoritmes en de mogelijkheid om tussen verschillende vestigingsplaatsen op aarde te kiezen voor transacties bieden effectieve bescherming tegen de grootste bron van roof: de natiestaten zelf.

Dat wil niet zeggen dat territoriale overheden geheel te slim af zullen zijn. Zij zullen nog steeds in staat zijn kwetsbaarheden te benutten om hoofdbelastingen op te leggen of misschien zelfs rijke individuen voor losgeld te houden. Ook zullen zij de heffing van verbruiksbelastingen kunnen afdwingen. Maar bescherming, de belangrijkste dienst die overheden leveren, zal op een vrijwel concurrerende basis aangeboden worden. Minder van de kosten die productieve mensen betalen voor bescherming zal beschikbaar zijn om door politieke autoriteiten gegrepen en herverdeeld te worden. Technologische innovaties zullen een groot en groeiend deel van de wereldwijde rijkdom buiten het bereik van overheden plaatsen. Dit zal de risico's van handel verminderen en, om het in de woorden van historicus Janet Abu-Lughod te zeggen, ‘de verhouding van alle kosten’ die anders aan transittarieven, tribuut of simpele afpersing zouden moeten worden toegewezen, scherp verlagen.[^258]

Het is in de geschiedenis zeldzaam geweest om overheden te vinden die werkelijk door concurrentie worden beperkt. In de weinige gevallen waarin zoiets zich enigszins voordeed, waren overheden zwak en waren de technologieën tussen jurisdicties vergelijkbaar. Zoals Lane stelde, blijkt dat de voornaamste factor die de winstgevendheid onder dergelijke omstandigheden beïnvloedt, de verschillen in beschermingskosten zijn die door verschillende ondernemers gedragen worden. De middeleeuwse koopman die twintig tolgelden moest betalen om zijn goederen op de markt te brengen, kon niet concurreren met een koopman die slechts vier tolgelden betaalde om dezelfde goederen bij de klant te leveren. Vergelijkbare omstandigheden zijn voorbestemd terug te keren met het informatietijdperk. Winstgevendheid zal opnieuw niet zozeer bepaald worden door technologische voorsprong, maar door het succes in het minimaliseren van de kosten die men gedwongen is te betalen voor bescherming.

Deze nieuwe economische dynamiek staat in directe tegenspraak met het verlangen van de overheid, overgebleven uit het industriële tijdperk, om voor haar beschermingsdiensten monopolistische prijsstelling op te leggen. Maar of je het nu wilt of niet, het oude systeem zal in de nieuwe competitieve omgeving van het informatietijdperk niet levensvatbaar blijken te zijn. Elke overheid die erop volhardt haar burgers te belasten met zware belastingen die haar concurrenten niet hoeven te betalen, zorgt er immers alleen maar voor dat winst en rijkdom ergens anders naartoe trekken. Daarom zal het falen van de volwassen verzorgingsstaten om op de lange termijn de belastingen te beperken zichzelf corrigeren. Overheden die te veel heffen, zullen het wonen binnen hun gebied eenvoudigweg tot een financiële last maken die tot faillissement kan leiden.

> '... want zoals de koning door zijn prerogatief naar zijn believen geld kan slaan van welk materiaal en in welke vorm hij ook maar wil en daarvoor de norm kan vaststellen, zo kan hij ook het geld in substantie en afdruk wijzigen, de waarde ervan verhogen of verlagen, of het geheel afwijzen en annuleren'[^259]: - Uit een Engels rechtsbesluit, 1604

## De dood van seigniorage

Overheden zullen niet alleen hun macht verliezen om vele vormen van inkomen en kapitaal te belasten; zij zijn ook voorbestemd hun dwangbevoegdheid over geld te verliezen. In het verleden gingen megapolitieke overgangen gepaard met veranderingen in de aard van geld.

- De introductie van munten hielp de vijfhonderdjarige expansiecyclus in de oude economie op gang te brengen, die culmineerde met de geboorte van Christus en de laagste rentetarieven van vóór de moderne periode.

- De intrede van de donkere eeuwen viel samen met de vrijwel volledige sluiting van de munthallen. Hoewel het Romeinse geld in omloop bleef, nam de hoeveelheid geld, samen met de handel, af in een zichzelf versterkende neerwaartse spiraal.

- De feodale revolutie viel samen met een herintroductie van geld, munten, wisselbrieven en andere instrumenten voor het afwikkelen van commerciële transacties. In het bijzonder leidde een toename in de Europese zilverproductie uit nieuwe mijnen in Rammelsberg, Duitsland, tot een grotere circulatie van munten die de handel vlotter deed verlopen.

- De grootste revolutie in geld vóór het informatietijdperk ging gepaard met de opkomst van het industrialisme. De vroegmoderne staat consolideerde haar macht tijdens de buskruitrevolutie. Naarmate haar controle toenam, stelde de staat haar macht over geld vast en ging zij sterk vertrouwen op de kenmerkende technologie van het industrialisme, de drukpers. Dit eerste instrument van massaproductie is in de moderne periode door overheden op grote schaal gebruikt om papieren geld massaal te produceren.

Papiergeld is een duidelijk industrieel product. Het zou vóór de boekdrukkunst onpraktisch zijn geweest om kwitanties of certificaten te dupliceren die tot papiergeld werden omgevormd. Zeker, monniken in de scriptoria zouden hun tijd niet hebben besteed aan het opmaken van vijftigpondbiljetten. Papiergeld droeg ook aanzienlijk bij aan de macht van de staat, niet alleen door winst te genereren via de waardevermindering van de valuta, maar ook door de staat een hefboom te geven over wie vermogen kon vergaren. Zoals Abu-Lughod het verwoordde: 'wanneer door de staat gesteund papiergeld de goedgekeurde valuta wordt, worden de kansen om kapitaal te vergaren in verzet tegen of onafhankelijk van de staatsmachine ernstig beperkt.' [^260]:

## Cybercash

Nu impliceert de intrede van het informatietijdperk een nieuwe revolutie in het karakter van geld. Naarmate de cyberhandel op gang komt, zal dit onvermijdelijk leiden tot cybergeld. Deze nieuwe vorm van geld zal de verhoudingen herdefiniëren, waardoor de mogelijkheid van de wereldwijde natiestaten afneemt om te bepalen wie een soeverein individu wordt. Een cruciaal onderdeel van deze verandering is het effect van informatietechnologie, dat de bezitters van rijkdom bevrijdt van onteigening door inflatie. Binnenkort zul je voor bijna elke transactie via het Net of World Wide Web op hetzelfde moment betalen als dat je deze plaatst, met cybercash.

Deze nieuwe digitale vorm van geld is voorbestemd om een sleutelrol te spelen in de cyberhandel. Het zal bestaan uit versleutelde reeksen priemgetallen met honderden cijfers. Uniek, anoniem en verifieerbaar zal dit geld de grootste transacties mogelijk maken. Het zal tevens deelbaar zijn tot in de kleinste waarde-eenheid. Met een enkele toetsaanslag zal het verhandelbaar zijn in een grenzeloze groothandelsmarkt ter waarde van meerdere triljoenen dollars.

### Dialing without dollars

Onvermijdelijk zal dit nieuwe cybergeld worden ontnationaliseerd. Wanneer soevereine individuen grensoverschrijdend kunnen handelen in een wereld zonder fysieke realiteit, hoeven zij de alom bekende praktijk van regeringen die de waarde van hun geld door inflatie verminderen niet langer te tolereren. Waarom zouden ze dat wel moeten? De controle over geld zal verschuiven van de zalen van de macht naar de wereldwijde marktplaats. Elk individu of elke onderneming met toegang tot cyberspace zal moeiteloos kunnen overstappen van elke valuta waarvan de waarde dreigt te dalen. In tegenstelling tot vandaag is het niet langer noodzakelijk om transacties in wettig betaalmiddel te verrichten. Inderdaad, als transacties de hele wereld beslaan, zal het waarschijnlijk zo zijn dat ten minste één partij in elke transactie handelt in een valuta die voor hen niet wettig betaalmiddel is.

### Verminderde nadelen van ruilhandel

Je zult in de cybereconomie in elk gewenst medium kunnen handelen. Zoals de inmiddels overleden Nobelprijswinnende econoom E. A. Hayek betoogde, is er 'geen duidelijk onderscheid tussen geld en niet-geld.' Schreef hij: "Hoewel we er doorgaans van uitgaan dat er een scherpe scheidslijn bestaat tussen wat geld is en wat dat niet is — en de wet doorgaans zo'n onderscheid tracht te maken — is er, wat betreft de causale effecten van monetaire gebeurtenissen, geen dergelijk duidelijk verschil. Wat we aantreffen is eerder een continuüm waarin objecten met uiteenlopende mate van liquiditeit, of met waarden die onafhankelijk van elkaar kunnen fluctueren, in elkaar overlopen naarmate zij functioneren als geld." [^261]: Digitale valuta op wereldwijde computernetwerken zullen elk object op Hayeks continuüm van liquiditeit meer liquide maken — met uitzondering van overheidspapier.

Een gevolg zal zijn dat ruilhandel veel praktischer wordt. Steeds meer objecten en diensten zullen in specifieke ruilaanbiedingen worden aangeboden voor de inruil van andere objecten en diensten. Deze potentiële transacties zullen wereldwijd op het internet breed geadverteerd worden, wat hun liquiditeit in veelvoud zal vergroten.

Een van de voornaamste nadelen van ruilhandel is altijd al geweest dat het moeilijk is om een persoon met een specifieke vraag te koppelen aan iemand die precies dat te bieden heeft en die voor zichzelf exact zoekt wat de eerste persoon voorstelde te ruilen. De primitieve ruilhandel stuitte op de ontmoedigende onwaarschijnlijkheid om twee partijen, die in een lokale markt wilden ruilen, precies op elkaar af te stemmen. Contant geld heeft de beperkingen van ruilhandel overstegen en zijn voordelen zullen bij de meeste transacties overtuigend blijven. Maar de enorme toename in rekenkracht en de globalisering van de handel in cyberspace verkleinen ook de nadelen van ruilhandel. De kans om iemand te vinden met precies wederzijdse wensen als de jouwe neemt dramatisch toe wanneer je direct over de hele wereld kunt zoeken in plaats van je te beperken tot degenen die je lokaal zou kunnen tegenkomen.

### Niet vatbaar voor vervalsing

Terwijl papiergeld ongetwijfeld in omloop blijft als een restvorm van ruilmiddel voor de armen en computeronbekwame mensen, zal geld voor transacties met hoge waarde geprivatiseerd worden. Cybergeld zal niet langer uitsluitend in nationale eenheden worden genoteerd, zoals het papiergeld uit het industriële tijdperk. Waarschijnlijk zal het worden gedefinieerd in termen van gram of ounce goud, zo fijn deelbaar als goud zelf, of het kan worden gedefinieerd in termen van andere reële opslagmiddelen van waarde. Zelfs als er verschillende prijsmaatstaven worden gehanteerd, of als bepaalde transacties nog steeds in nationale valuta worden genoteerd, zal cybergeld de consumenten aanzienlijk beter bedienen dan genationaliseerd geld ooit deed. De snel groeiende rekenkracht zal de moeilijkheden bij het aanpassen van prijzen aan diverse ruilmiddelen tot een verwaarloosbaar niveau reduceren. Elke transactie zal gepaard gaan met de overdracht van versleutelde reeksen priemgetallen met honderden cijfers. In tegenstelling tot de papiergeldontvangstbewijzen die regeringen tijdens het tijdperk van de goudstandaard uitgaven en die naar believen gekopieerd konden worden, zal de nieuwe digitale goudstandaard – of de ruilequivalenten daarvan – bijna onmogelijk te vervalsen zijn, simpelweg omdat het nagenoeg onmogelijk is om het product van priemgetallen met honderden cijfers te ontrafelen. Alle ontvangstbewijzen zullen verifieerbaar uniek zijn.

De namen van traditionele valuta, zoals de 'pond' en de 'peso', weerspiegelen dat zij oorspronkelijk als gewichtseenheden voor specifieke hoeveelheden edele metalen zijn ontstaan. Het pond sterling was ooit een pond sterlingzilver. Het papiergeld in het Westen is ontstaan als ontvangstbewijzen voor de opslag van hoeveelheden edele metalen in magazijnen of kluizen. Regeringen die deze ontvangstbewijzen uitgaven, ontdekten al snel dat zij er veel meer konden drukken dan zij er daadwerkelijk voor konden inwisselen uit hun voorraad ruwgoud. Dit was eenvoudig. Geen enkele persoon die in het bezit was van een goud- of zilvercertificaat kon enige informatie over de werkelijke voorraad edele metalen afleiden uit zijn ontvangstbewijs. Afgezien van de serienummers zagen alle ontvangstbewijzen er identiek uit, een feit dat zowel bij vervalsers als bij politici en bankiers in de smaak viel, die wilden profiteren van het opblazen van de geldvoorraad.

Cybergeld zal op deze wijze, zowel officieel als informeel, bijna onmogelijk te vervalsen zijn. De verifieerbaarheid van de digitale ontvangstbewijzen sluit deze klassieke truc voor het onteigenen van rijkdom door inflatie uit. Het nieuwe digitale geld van het informatietijdperk zal de controle over het ruilmiddel teruggeven aan de eigenaren van rijkdom, die hun vermogen willen behouden, in plaats van aan natiestaten die het van hen willen afnemen.

### de transactiekosten van "vrij" geld

Het gebruik van dit nieuwe cybergeld zal u aanzienlijk bevrijden van de macht van de staat. Eerder hebben we het sombere trackrecord aangehaald van de natiestaten wereldwijd bij het handhaven van de waarde van hun valuta in de afgelopen vijftig jaar. Geen enkele valuta heeft sinds de Tweede Wereldoorlog een kleinere waardevermindering door inflatie ondergaan dan de Duitse mark. Toch is 71 procent van haar waarde verdwenen tussen 1 januari 1949 en eind juni 1995. De wereldreserverende valuta in deze periode, de Amerikaanse dollar, verloor 84 procent van haar waarde.[^262]

[^262]: Dit is een maatstaf voor de rijkdom die regeringen hebben onteigend door hun territoriale monopolie op wettig betaalmiddel te benutten.

Let op dat er geen inherente noodzaak bestaat dat valuta in waarde dalen of dat de nominale kosten van levensonderhoud elk jaar stijgen. Integendeel. De technische uitdaging om de koopkracht van spaargeld te behouden is triviaal. Dit blijkt al door simpelweg naar de langetermijnkoopkracht van goud te kijken.

Tussen 1 januari 1949 en eind juni 1995, terwijl de beste nationale valuta bijna driekwart van hun waarde verloren, steeg de koopkracht van goud daadwerkelijk. Zoals gedocumenteerd door professor Roy W. Jastrom in zijn boek The Golden Constant heeft goud, met slechts geringe schommelingen, zijn koopkracht behouden, zover betrouwbare prijsgegevens beschikbaar zijn – in het geval van Engeland tot 1560.

Ook hebben nationale valuta die aan goud gekoppeld zijn, hun koopkracht behouden in tijden waarin militaire urgenties geen doorslaggevend belang hadden. De waarde van de Britse pond sterling steeg, in plaats van te dalen, tijdens de relatief vreedzame negentiende eeuw, ook al was deze slechts zwak aan goud gekoppeld. De nieuwe megapolitieke omstandigheden van het informatietijdperk maken niet een zwakke schakel, zoals de goudstandaard, maar een sterke schakel mogelijk, die voor het eerst wordt versterkt door aanzienlijk verbeterde informatie- en rekencapaciteiten in handen van consumenten.

> 'De dreiging van het snelle verlies van hun volledige onderneming als zij er niet in slaagden de verwachtingen waar te maken (en hoe elke overheidsorganisatie ongetwijfeld misbruik zou maken van de kans om met grondstofprijzen te spelen!) zou een veel sterkere waarborg bieden dan wat er bedacht zou kunnen worden ter bestrijding van een staatsmonopolie'[^263]: - FRIEDRICH A. VON HAYEK

### Privatisering van geld

In 1976 betoogde Friedrich von Hayek dat het gebruik van concurrerende, particuliere valuta de inflatie zou uitroeien.[^264] Zonder wettelijke verplichtingen die de aanvaarding van een inflatoire valuta binnen een rechtsgebied afdwingen, zou, zo voerde Hayek aan, de concurrentie op de markt particuliere emittenten van valuta dwingen de waarde van hun ruilmiddelen te behouden. Iedere uitgever van een particuliere valuta die er niet in slaagt haar waarde te handhaven, zou al snel haar klanten verliezen. De evolutie van versleutelde cybercontanten zal de logica van Hayek op levendige wijze tot leven brengen.

De theorie van 'vrij bankieren', zoals het genoemd wordt, is niet louter een hypothetische academische speculatie. Particuliere concurrerende valuta circuleerden in Schotland vanaf het begin van de achttiende eeuw tot 1844. In die periode had Schotland geen centrale bank. Er waren weinig regels of beperkingen voor toetreding tot het bankwezen. Particuliere banken namen deposito’s in en gaven hun eigen valuta uit, gedekt door goudstaven. Zoals professor Lawrence White heeft gedocumenteerd, werkte dit systeem goed. Het was stabieler en kende minder inflatie dan het sterker gereguleerde en politisierde bank- en geldsysteem dat in Engeland in dezelfde periode werd gehanteerd.[^265] Michael Prowse van de Financial Times vatte de ervaring met vrij bankieren in Schotland samen: 'Er was weinig fraude. Er waren geen aanwijzingen voor overmatige uitgifte van biljetten. Banken hielden doorgaans noch te veel noch te weinig reserves aan. Bankruns waren zeldzaam en niet besmettelijk. De vrije banken genoten het respect van de burgers en boden een solide basis voor economische groei die in de meeste perioden Engeland ver overtrof.'[^266]

Wat onder de technologische omstandigheden van de achttiende en negentiende eeuw goed werkte, zal met de technologie van de eenentwintigste eeuw nog beter functioneren. Binnenkort zult u in digitale valuta kunnen handelen van een particulier bedrijf, uitgegeven op dezelfde wijze als American Express reischeques uitgeeft als ontvangstbewijzen voor contant geld. Een instelling met een grotere reputatie dan welke overheid dan ook, zoals een toonaangevend mijnbedrijf of de Swiss Bank Corporation, zou versleutelde ontvangstbewijzen voor hoeveelheden goud, of zelfs voor unieke goudbaren, kunnen creëren, geïdentificeerd aan de hand van moleculaire signatures en mogelijk zelfs versierd met hologrammen. Deze ontvangstbewijzen zullen vervolgens als geld verhandeld worden, met vrijwel geen mogelijkheid tot vervalsing of inflatie.

Het nieuwe digitale goud zal veel van de praktische problemen oplossen die in het verleden het directe gebruik van goud als geld belemmerden. Het zal niet langer onhandig, omslachtig of gevaarlijk zijn om met grote hoeveelheden goud te handelen. Digitale ontvangstbewijzen zullen niet te zwaar zijn om mee te nemen; hun enige fysieke bestaan zal bestaan uit uitgebreide patronen van computercode. Ook zal het niet moeilijk zijn om digitale ontvangstbewijzen op te splitsen in eenheden zo klein dat zelfs aankopen van geringe waarde betaald kunnen worden. Een plakje fysiek goud, zo klein dat het net voldoende is voor een chiclet, zou al snel verloren gaan of verward worden met een plakje dat net genoeg is voor twee chiclets. Maar het zal voor de computer net zo gemakkelijk zijn om deze denominaties van digitaal geld uit elkaar te houden alsof het gaat om de grootte van een chipmunk en een neushoorn.

Het vermogen van digitaal geld om micropayments uit te voeren, zal de opkomst van nieuwe soorten bedrijven faciliteren, die voorheen niet hadden kunnen bestaan, gespecialiseerd in het organiseren van de distributie van informatie van geringe waarde. De verkopers van deze informatie zullen voortaan worden vergoed via directe incasso-royaltyregelingen die de voorheen ontmoedigende transactiekosten overwinnen. Wanneer de kosten voor facturatie de waarde van een transactie overschrijden, zal deze hoogstwaarschijnlijk niet plaatsvinden. Het gebruik van cybergeld maakt zeer goedkope, gelijktijdige facturering mogelijk, waarbij rekeningen met het gebruik worden afgeschreven. Bovenstaand voorbeeld illustreerde dat u bijvoorbeeld een royalty ter waarde van een derde van een cent kunt betalen aan Bill Gates, of aan degene die de virtual-realityrechten bezit voor een rondleiding door het Louvre. Vermenigvuldig dit op duizend manieren. Virtual reality zal bijna onbeperkte licentiekansen creëren, die desalniettemin slechts microroyaltybetalingen vereisen. Op een dag zult u de derde wedstrijd van de World Series van 1969 opnieuw kunnen beleven en microroyalty's betalen aan de spelers wiens beelden worden gebruikt om uw virtual reality echt te doen lijken.

## Inflatie uitroeien

Zoveel mogelijkheden er ook zijn, zal ongetwijfeld de meest ingrijpende consequentie van het nieuwe digitale geld het einde van de inflatie en de vermindering van de financiële hefboomwerking zijn. De economische implicaties zijn diepgaand. De opkomst van de inflatie in de twintigste eeuw, zoals we in *Blood in the Streets* en *The Great Reckoning* betoogden, was nauw verbonden met de machtsverhoudingen in de wereld. De groeiende opbrengsten uit geweld leidden tot drastisch hogere militaire uitgaven, wat op zijn beurt steeds agressievere pogingen vereiste om rijkdom te onteigenen. Overheden ontdekten dat zij effectief een jaarlijkse vermogensbelasting konden heffen op iedereen die tegoeden in hun nationale valuta aanhield. Deze jaarlijkse vermogensbelasting op valutahouders kan ook worden gezien als een transactiekost voor het gemak waarmee gebruikers hun vermogen in een handige vorm kunnen aanhouden, zoals die door de uitgevers wordt verschaft.[^269]

Inflatie beschouwen als een transactiekost voor het gemak van het aanhouden van valuta lijkt misschien ongebruikelijk, maar overweeg het eens goed. Tijdens het industriële tijdperk raakten we zo gewend aan de gedachte dat de verstrekking van valuta een dienst was waarvoor men niet direct betaalt, dat we gemakkelijk vergaten dat de uitgevers van dollars, pesos, ponden en franken – namelijk de overheden – wel degelijk eisten dat we betaalden, en dat tegen een hoge prijs – namelijk via inflatie. Het tarief van deze inflatoire transactiekost varieerde in de afgelopen halve eeuw van een dieptepunt van 2,7 procent per jaar voor de Duitse mark tot tarieven die gevaarlijk dicht bij de 100 procent kwamen. Zo verwijderde inflatie, tussen 1960 en 1991 toen president Menem de hervorming van het valutaboard in Argentinië lanceerde, zeventien nullen van opeenvolgende versies van de Argentijnse munt. Als in 1960 alle rijkdom van de wereld in Argentijnse pesos was omgezet en begraven, zou het in 1991 de moeite niet waard zijn geweest om het op te graven.

Het voorbeeld van Argentinië is een belangrijke indicator voor het komende millennium. Valuta zal niet meer worden opgeblazen, omdat andere staten er niet langer mee weg kunnen komen, net zoals Argentinië dat niet meer kan. Tijdens de industriële periode, toen prijzen en lonen naar beneden toe inflexibel waren, had inflatie bovendien een bijkomende aantrekkingskracht. Matige inflatie verhoogde de productie doordat de reële lonen daalden, terwijl prijzen schade konden oplopen door een in andere landen geïmporteerde kredietkrimp. Privégeld zal niet inflateerbaar zijn door de kracht van concurrentiedruk.

De ondergang van de inflatie zal de verborgen winsten wegnemen die inflatie voorheen bood aan diegenen die monopolistisch optraden als uitgevers van valuta. Als al deze verborgen winsten bij het uitgeven van geld zouden verdwijnen, zou een nieuwe betaalmethode nodig zijn om de uitgevers van valuta rechtstreeks te compenseren. Het gebruik van het nieuwe monetaire systeem zal daarom waarschijnlijk gepaard gaan met een explicietere transactiekost, mogelijk een vergoeding van ongeveer 1 procent per jaar. Dit zal een kleine prijs zijn in vergelijking met de jaarlijkse inflatoire last van 2,7 tot 99 procent die door staten wordt opgelegd, des te meer omdat het waarschijnlijk is dat de algemene prijzen in de toekomst zullen dalen naarmate monopolies afbrokkelen en de concurrentie wereldwijd toeneemt.

### Afnemende hefboomwerking

De opkomst van digitaal geld zal niet alleen de inflatie eens en voor altijd verslaan, maar ook de hefboomwerking in de banksystemen wereldwijd verkleinen. De mogelijkheid voor mensen overal om de toezichthoudende autoriteiten te omzeilen en hun fondsen rechtstreeks via het internet te verplaatsen, is een geheel ongekende consequentie van de globalisering van de markten. Het zal buiten de macht van elke overheid liggen om dit te reguleren. Wanneer overheden niet langer in staat zijn om de valuta te devalueren door geld te drukken of spaarders te bedriegen door naar believen krediet uit te breiden via captive banksystemen, zullen zij een groot deel van hun indirecte mogelijkheden verliezen om middelen naar hun hand te zetten.

### Hogere rentetarieven

Dit zal een duidelijk dilemma scheppen voor de meeste westerse regeringen. Zij zullen geconfronteerd worden met scherpe dalingen in de belastinginkomsten en de vrijwel volledige eliminatie van hefboomwerking in het monetaire systeem. Tegelijkertijd zullen zij de ongedekte verplichtingen en opgeblazen verwachtingen voor sociale uitgaven blijven dragen die zij uit het industriële tijdperk hebben geërfd. Het te verwachten gevolg is een intense fiscale crisis met veel onaangename sociale neveneffecten, die in latere hoofdstukken zullen worden behandeld. De economische consequentie van deze transitiecrisis zal waarschijnlijk een eenmalige piek in de reële rentetarieven omvatten. Debiteuren zullen onder druk komen te staan naarmate de langlopende verplichtingen, aangegaan onder het oude systeem, worden terugbetaald en concessiekredieten opdrogen.

### Veranderd door concurrentie

Overheden die geconfronteerd worden met serieuze concurrentie voor hun valutamonopolies zullen waarschijnlijk trachten de tegen vergoeding aangeboden cybervaluta te onderprijzen door het krediet aan te scherpen en spaarders hogere reële opbrengsten op hun contante saldi in nationale valuta te bieden. Sommige overheden zouden zelfs kunnen proberen goud te remonetariseren als een extra middel om de concurrentie van particuliere valuta het hoofd te bieden. Zij zouden er goed in kunnen redeneren dat zij met een los gecontroleerde goudstandaard uit de negentiende eeuw hogere zegnaturiewinsten kunnen behalen dan wanneer zij toestaan dat hun nationale valuta geheel wordt verdrongen door commercieel cybergeld. Maar niet alle overheden zullen op dezelfde wijze reageren. Degenen in regio's waar het computergebruik en de deelname aan het internet beperkt zijn, kunnen er in de vroege stadia van de cybereconomie voor kiezen ouderwetse hyperinflatie in te zetten. Dit zal deze overheden niet in staat stellen de contante saldi van de rijken te veroveren, maar het zal juist middelen uitpersen van degenen met weinig vermogen of toegang tot de cybereconomie. Overheden die dergelijke tactieken hanteren, zouden desondanks internationaal in cybergeld kunnen lenen.

Andere overheden zouden zich juist kunnen aanpassen aan de kansen die de informatie-economie biedt en lokale transacties in cybergeld faciliteren. Die rechtsgebieden die als eerste de geldigheid van digitale handtekeningen erkennen en de lokale gerechtelijke handhaving van terugvordering bij niet-betaling van cyberschulden waarborgen, zullen waarschijnlijk profiteren van een onevenredige toename in langlopende kapitaalleningen. Uiteraard zal er in gebieden waar lokale rechtbanken straffen opleggen of schuldenaren toestaan in gebreke te blijven zonder rechtsmiddelen, geen cybergeld beschikbaar zijn voor langlopende kredieten.

### Yield gap

De combinatie van kredietcrisissen, competitieve aanpassingen door nationale muntautoriteiten en vroege overgangsbelemmeringen bij het verstrekken van kredieten in cybergeld zal in de beginfase van de informatie-economie leiden tot een opbrengstkloof. Cybergeld zal naar verwachting lagere rentetarieven bieden dan nationale valuta en waarschijnlijk ook expliciete transactiekosten met zich meebrengen. Het compenseren van deze schijnbare nadelen van het aanhouden van saldi in digitaal geld zal gebeuren door een verbeterde bescherming tegen verliezen als gevolg van roofzuchtige belastingen en inflatie. Omdat het waarschijnlijk aan goud gekoppeld zal zijn, zal cybergeld ook profiteren van de waardestijging van goud. De prijs van goud zal vermoedelijk aanzienlijk stijgen ten opzichte van andere grondstoffen, ongeacht welke alternatieve overheidsmaatregel de overhand krijgt. Waarom? De reële prijs van goud stijgt bijna altijd tijdens een deflatie. Een deflatie weerspiegelt immers een tekort aan liquiditeit. Goud is de ultieme vorm van liquiditeit.

### De deflatie van het industriële tijdperk

Hogere reële rentevoeten overal zullen leiden tot de liquidatie van dure, onproductieve activiteiten en tijdelijk de consumptie verminderen. We hebben de logica van de kredietcyclus en de daaropvolgende afwikkeling ervan onderzocht in *Blood in the Streets* en *The Great Reckoning*, dus zullen we die argumenten hier niet herhalen. Voldoende is te zeggen dat de deflatoire omgeving enige tijd kan aanhouden, met meer nadelige gevolgen in de dure industriële economieën van Noord-Amerika en West-Europa dan in de goedkope economieën van Azië en Latijns-Amerika.

### Lagere rentes op lange termijn

Hoewel de vroege gevolgen van de opkomst van de cybereconomie waarschijnlijk hogere rentetarieven zullen inhouden, zal het langetermijneffect precies het tegenovergestelde zijn. De rendementen na belasting voor spaarders zullen fors stijgen naarmate middelen aan de greep van de overheden ontsnappen. Dramatische verbeteringen in de efficiëntie van het gebruik van hulpbronnen en de bevrijding van kapitaal om wereldwijd de hoogste rendementen te behalen, zouden de in het begin van de transitiecrisis verloren productie snel moeten compenseren.

### Investeerderscontrole over kapitaal

Conventionele denkers die ons betoog op dit punt beoordelen, zouden concluderen dat het instorten van de inkomensherverdeling in de leidende natiestaten de wereld ten onder zou brengen in een economische catastrofe. Geloof dat niet. We ontkennen niet dat een transitiecrisis waarschijnlijk is. Maar de opvatting dat de staat de werking van de economie verbetert door een massale herallocatie van middelen is een anachronisme, een geloofsartikel dat ruwweg gelijkstaat aan de wijdverspreide bijgelovigheden aan het einde van de Middeleeuwen, waarin men geloofde dat vasten en lijfstraffen voordelig waren voor een gemeenschap. Men moet niet vergeten dat overheden op grote schaal middelen verspillen. Het verspillen van middelen maakt je arm. Een dramatische verbetering in de efficiëntie van het gebruik van hulpbronnen zal ontstaan wanneer de inkomsten die historisch door overheden zijn opgeslokt, in handen komen van mensen met werkelijk talent.

Tientallen miljarden, en uiteindelijk zelfs honderden miljarden dollars, zullen beheerd worden door honderdduizenden – later miljoenen – soevereine individuen. Deze nieuwe beheerders van de mondiale rijkdom blijken waarschijnlijk veel capabeler te zijn dan politici in het benutten van middelen en het inzetten van investeringen. Voor het eerst in de geschiedenis zullen megapolitieke omstandigheden de beste investeerders en ondernemers – en niet degenen die gespecialiseerd zijn in geweld – de uiteindelijke controle over het kapitaal geven. Het is niet onredelijk te verwachten dat de rendementen op deze verspreide, marktgestuurde investeringen twee- tot driedubbel zo hoog kunnen zijn als de magere opbrengsten van de politiek gedreven budgettoewijzingen uit het tijdperk van de natiestaat. In de laatste decennia van de twintigste eeuw was het niet ongebruikelijk om in elk land voorbeelden te vinden van overheidsinvesteringen die in wezen negatief waren. In de herziene versie van *The Great Reckoning* uit november 1992 haalden wij officiële Russische statistieken aan, waaruit bleek dat de hele Russische economie "slechts $30 miljard waard was, minder dan een derde van de waarde van haar grondstofinvoer. Impliciet zou de output van de Russische economie meer dan verdrievoudigen als de binnenlandse productie- en diensteneconomie volledig zou worden stilgelegd. In plaats van waarde toe te voegen, onttrekt zij die." [^267]:

Hoewel het voorbeeld van Rusland na de ineenstorting van het communisme een extreem geval is, is er voldoende bewijs dat het verminderen van staatscontrole over middelen de economische efficiëntie ten goede komt. De groeicijfers die door The Economist worden geciteerd, suggereren dat economische vrijheid sterk samenhangt met economische groei, waarbij de snelste groeipercentages in de vrijste landen worden gemeten. De cybereconomie van het informatietijdperk zal vrijer zijn dan enig ander commercieel domein in de geschiedenis. Het is dus redelijk te verwachten dat de cybereconomie snel de belangrijkste nieuwe economie van het nieuwe millennium zal worden. Haar succes zal nieuwe deelnemers uit alle delen van de wereld aantrekken, op dezelfde wijze als het wijdverbreide gebruik van faxapparaten het telecopiëren steeds aantrekkelijker maakte voor niet-gebruikers. Maar nog belangrijker: de afwezigheid van roofzuchtig geweld zal de cybereconomie in staat stellen te groeien met veel hogere samengestelde groeipercentages dan conventionele economieën die door natiestaten worden gedomineerd.

Dat is wellicht het belangrijkste punt bij het voorspellen van de economische impact van de waarschijnlijke ineenstorting van het monopolistische vermogen van de overheid om belastingen te heffen en inflatie te creëren. Als we de overgangsproblemen, die decennialang kunnen duren, even terzijde schuiven, zouden de langetermijnvooruitzichten voor de wereldeconomie uiterst optimistisch moeten zijn. Telkens wanneer omstandigheden het mensen mogelijk maken om beschermingskosten te verlagen en de tribuut aan degenen die het georganiseerde geweld beheersen te minimaliseren, groeit de economie doorgaans dramatisch. Zoals Lane zei: "Ik wil graag suggereren dat de belangrijkste enkele factor in de meeste groeiperioden – als er nu één factor het zwaarst heeft meegewogen – de vermindering is van het aandeel middelen dat aan oorlog en politie wordt besteed." [^268]:

Er zouden grote efficiëntiewinsten kunnen worden behaald door het verminderen van de middelen die aan roofzucht en aan het profiteren van de buit worden besteed. Als de prijsstelling van bescherming op een competitieve basis zou worden geregeld, waarbij lokale monopolies op basis van prijs en kwaliteit met elkaar concurreren, zouden potentieel enorme efficiëntiewinsten mogelijk zijn. Het te verwachten resultaat zou leiden tot veel lagere belastingtarieven en tot minder verlies van middelen en inspanning in politieke activiteiten, die hun voorheen enorme rendementen niet langer zouden opleveren.

Zouden kiezers bereid zijn om afstand te doen van de politieke meevallers waaraan zij gewend zijn geraakt? Dat is een kwestie die we elders uitvoerig behandelen. Een eenvoudig antwoord is echter dat we wellicht geen keuze hebben. Tegen regenachtig weer of droogte demonstreren tegenwoordig immers niemand, hoe economisch schadelijk of onaangenaam deze omstandigheden ook mogen zijn. Niemand, hoe crimineel gesind ook, gijzelt een arme door met de dood te dreigen en een enorme betaling te eisen. Als het voor politici onmogelijk wordt om middelen te verkrijgen om te herverdelen, kan het publiek op een rationele wijze reageren en de politiek vergeten, net zoals goedbedoelende mensen stopten met het organiseren van boetemarsen toen de middeleeuwen ten einde kwamen.

[^245]: Perry Barlow, 'Thinking Locally, Acting Globally', Time, 15 januari 1996, p.57.

[^246]: Ibid.

[^247]: M. C. Seymour, red., Mandeville:' Travels (Oxford: Oxford University Press, 1968), p.122.

[^248]: R. C. Johnson, 'The Transportation of Vagrant Children from London to Virginia, 1618-1622', in H. S. Reinmuth, red., Early Stuart Studies (Minneapolis: University of Minnesota Press, 1970), pp. ~43-44, geciteerd in Jutte, op. cit., p.168.

[^249]: John Dos Passos, The Big Money (New York: Harcourt, Brace & Co., 1936).

[^250]: Clarke, op. cit., p.29.

[^251]: Geciteerd in Kline en Burstein, op. cit., p. ~05.

[^252]: Clarke, op. cit., p.20.

[^253]: Ibid.

[^254]: Ibid., p.21.

[^255]: Lane, "Economische gevolgen van georganiseerd geweld," op. cit., p.404.

[^256]: James Bennet, "De informatierevolutie en de ondergang van de inkomstenbelasting," Strategic Investment, november 1994, pp.11-12.

[^257]: Lane, "Economische gevolgen van georganiseerd geweld," op. cit., p.404.

[^258]: Abu-Lughod, op cit.. p.177.

[^259]: Geciteerd in Henry Mark Holzer, het geldmonopolie van de overheden (New York: Books in Focus, 1981), p.4.

[^260]: Abu-Lughod, op. cit., p.332.

[^261]: Friedrich A. von Hayek, de denationalisatie van geld (London: Institute of Economic Affairs, 1976), p.47.

[^262]: Zie hoofdstuk 1, noot 6.

[^263]: Hayek, op. cit., p.40.

[^264]: Ibid.

[^265]: Zie Lawrence White, *Free banking in britain* (Londen: Institute of Economic Affairs, 1995).

[^266]: Michael Prowse, *Bring back gold*, Financial Times, 5 februari 1996, p.12.

[^267]: Davidson and Rees-Mogg, op. cit., p.203.

[^268]: Lane, *economic consequences of organized violence*, op. ciL, p.413.

[^269]: Inflatie had tijdens de industriële periode nog een andere aantrekkingskracht, toen prijzen en lonen naar beneden niet flexibel waren. Bescheiden inflatie verhoogde de productie door de reële lonen en prijzen te verlagen.

::: {.content-visible when-format=latex}
\setsubtitle{De revolutie van het verdienvermogen in een wereld zonder banen}
:::