# Het einde van egalitaire economie

::: {.content-hidden when-format=latex}
*De revolutie in verdienvermogen in een wereld zonder banen*
:::

> 'God laat zich niet spotten: want wat een mens zaait, zal hij ook oogsten.' - Galaten 6:7

Grote veranderingen in de dominante vormen van productie of defensie veranderen de structuur van de samenleving en de verhouding van rijkdom en macht tussen verschillende groepen. Het informatietijdperk betekent meer dan slechts een toenemend gebruik van krachtige computers. Het betekent een revolutie in levensstijlen, instellingen en de verdeling van middelen. Omdat de rol van verborgen geweld bij het beheersen van middelen sterk zal afnemen, zal zich een nieuwe configuratie van rijkdom ontwikkelen, zonder de dwangmatige bemiddeling door de overheid die de twintigste eeuw kenmerkte. Omdat locatie in de informatiesamenleving veel minder van belang zal zijn, zullen organisaties die binnen geografische grenzen opereren in de toekomst een minder grote rol spelen dan die welke daarbuiten werkzaam zijn. Politici, vakbonden, gereguleerde beroepen, lobbyisten en overheden per se zullen minder belangrijk zijn. Omdat de door overheden opgedrongen gunsten en handelsbeperkingen minder waardevol zullen worden, zal er minder verspilling van middelen plaatsvinden om lobbyactiviteiten te bevorderen of juist tegen te gaan.

Degenen die dwang en lokaal voordeel hebben ingezet om inkomens te herverdelen, zijn voorbestemd om een groot deel van hun macht te verliezen. Dit zal de controle over de middelen veranderen. Privé-gegenereerde rijkdom die tot nu toe door de natiestaat in beslag is genomen, zal in plaats daarvan in de handen blijven van degenen die het verdienen. Steeds grotere hoeveelheden rijkdom zullen hun weg vinden naar de meest bekwame ondernemers en durfkapitalisten wereldwijd. Globalisering, samen met andere kenmerken van de informatie-economie, zal ertoe leiden dat de inkomens van de meest getalenteerde individuen in elk vakgebied toenemen. Omdat de marginale waarde die door uitmuntende prestaties wordt gegenereerd zo enorm zal zijn, zal de verdeling van het verdienvermogen in de gehele wereldeconomie grotendeels dezelfde vorm aannemen als die nu in prestatieberoepen als atletiek en opera wordt waargenomen.

## Een omvang die verder gaat dan Pareto's wet

Pareto's wet stelt dat 80 procent van het voordeel afhankelijk is van of toekomt aan 20 procent van de betrokkenen. Dit mag ongeveer kloppen, hoewel opvallender is dat 1 procent van de bevolking van de Verenigde Staten 28,7 procent van de inkomstenbelasting betaalt, wat erop wijst dat naarmate samenlevingen vooruitgang boeken in het informatietijdperk, zij een nog schevere verdeling van inkomens en vaardigheden zullen ervaren dan wat Vilfredo Pareto aan het eind van de vorige eeuw opmerkte.

Mensen zijn inmiddels aardig gewend aan aanzienlijke ongelijkheden in rijkdom. In 1828 werd aangenomen dat 4 procent van de New Yorkers 62 procent van alle rijkdom in de stad bezat. In 1845 bezat de top 4 procent ongeveer 81 procent van zowel bedrijfs- als niet-bedrijfsgerelateerde rijkdom in New York City. Algemeen bezat de top 10 procent van de bevolking in 1860 ongeveer 40 procent van de rijkdom van de gehele Verenigde Staten. In 1890 suggereren gegevens dat de rijkste 12 procent toen ongeveer 86 procent van de rijkdom van Amerika bezat.[^270]

De cijfers van 1890 komen redelijk overeen met hetgeen Pareto voor ogen had. Ze wijken van zijn 80-20-verhouding omdat aan het einde van de negentiende eeuw een enorme instroom van hulpeloze immigranten Amerika binnenkwam. Het aandeel van deze immigranten in de totale rijkdom was verwaarloosbaar; hun komst maakte de vermogensverdeling daardoor automatisch ongelijker. Dit is een treffende illustratie van het feit dat elke oprechte toename van kansen bijna onvermijdelijk ten minste tijdelijk leidt tot een toename van ongelijkheid. In 1890 vertegenwoordigden immigranten ongeveer 15 procent van de totale bevolking van de VS, maar in sommige noordoostelijke staten, waar het grootste deel van de inkomsten en rijkdom werd gegenereerd, liep dat aandeel op tot meer dan 40 procent.[^271] Als men de toename van immigratie meerekent, paste het Amerika van eind negentiende eeuw nagenoeg even goed in Pareto's formule als het Zwitserland van die periode, waar hij woonde.

Het informatietijdperk heeft de verdeling van rijkdom al veranderd, met name in de Verenigde Staten, en is een van de oorzaken van de bitterheid in de moderne Amerikaanse politiek, waar we in het volgende hoofdstuk dieper op ingaan. Het informatietijdperk vereist een behoorlijk hoog niveau van geletterdheid en rekenvaardigheid voor economisch succes. Een grootschalige enquête van het Amerikaanse ministerie van Onderwijs, "Adult Literacy in America", heeft aangetoond dat maar liefst 90 miljoen Amerikanen ouder dan vijftien schrijnend onbekwaam zijn. Of, om het kleurrijker te zeggen zoals de Amerikaanse expat Bill Bryson het verwoordt: 'Ze zijn zo dom als varkenskwallen.'[^272] Concreet bleek dat 90 miljoen Amerikaanse volwassenen niet in staat waren een brief te schrijven, een busrooster te doorgronden of op te tellen en af te trekken – zelfs niet met behulp van een rekenmachine. Degenen die geen schot kunnen maken van een gewoon busrooster, zullen waarschijnlijk ook niet veel weten met de informatiesnelweg. Uit dit derde deel van de Amerikanen, die zich niet hebben voorbereid op de elektronische informatiewereld, wordt een boze onderklasse gerekruteerd. Aan de top van de samenleving bevindt zich een kleine groep – wellicht 5 procent – van hoogopgeleide informatiewerkers of kapitaalbezitters, die het equivalent vormen van de landeigen aristocratie uit de feodale tijd, met als cruciaal verschil dat de elite van het informatietijdperk specialisten in productie zijn, en niet in geweld.

### De megapolitiek van innovatie

Zonder een goede reden hebben de meeste sociologen uit de twintigste eeuw aangenomen dat technologische vooruitgang er vanzelf toe zou leiden dat samenlevingen steeds egalitairder worden. Dit was echter niet zo vóór ongeveer 1750. Vanaf die tijd begon innovatieve nieuwe industriële technologie banen te openen voor ongeschoolden en de schaal van ondernemingen te vergroten. De nieuwe technologie van de fabriek verhoogde niet alleen de reële verdiensten van de armen zonder dat zij enige inspanning hoefden te leveren; ze had ook de neiging om de macht van politieke systemen te vergroten, waardoor deze beter in staat waren inkomen te herverdelen en onrust te weerstaan. Als men het op de lange termijn bekijkt, is er geen fundamentele reden om aan te nemen dat technologie altijd de verschillen in menselijke talenten en motivatie verbloeit in plaats van juist te benadrukken. Sommige technologieën bleken relatief egalitair te zijn, omdat ze bijdragen vereisten van vele onafhankelijke arbeiders met ongeveer gelijke waarde; andere technologieën legden de macht of rijkdom in de handen van een paar heren, terwijl de meeste mensen nauwelijks meer waren dan horigen. Zowel de geschiedenis als de technologie hebben verschillende naties op uiteenlopende wijze gevormd. Het fabriekstijdperk leidde tot een bepaalde vorm, terwijl het informatietijdperk een andere vorm voortbrengt, minder gewelddadig en daardoor meer elitair en minder egalitair dan die welke het vervangt.

## Ammon’s raap

Aan het einde van de negentiende eeuw begonnen een aantal economen, waarvan William Stanley Jevons in Engeland de meest vooraanstaande was, met het ontwikkelen van de mathematische economie. Een van de eersten die de kansrekening toepaste op een belangrijke sociale vraag was de Duitse econoom Otto Ammon, wiens werk voor het eerst in het Engels werd vertaald door Carlos C. Closson in een artikel in het *Journal of Political Economy* in 1899. Het artikel droeg de titel "Some Social Applications of the Doctrine of Probability."[^273] Men zou kunnen denken dat zo'n artikel louter van antiquarisch belang was. In werkelijkheid behandelt het een economisch probleem dat weer in de belangstelling komt en doet dat op een nog steeds stimulerende wijze.

Otto Ammon was geïnteresseerd in de verdeling van bekwaamheid in de samenleving en in de relatie daarvan met de verdeling van inkomen en status. Hij nam als uitgangspunt de waarschijnlijke uitkomst van de totaalscores bij het werpen van vier dobbelstenen, elk met zes zijden. Van de 1.296 mogelijke worpen zullen sommige totalen vaker voorkomen dan andere.

*De som van 24 punten zal één keer voorkomen.

De som van 23 punten zal 4 keer voorkomen.

De som van 22 punten zal 10 keer voorkomen.

De som van 21 punten zal 20 keer voorkomen.

De som van 20 punten zal 35 keer voorkomen.

De som van 19 punten zal 56 keer voorkomen.

De som van 18 punten zal 80 keer voorkomen.

De som van 17 punten zal 104 keer voorkomen.

De som van 16 punten zal 125 keer voorkomen.

De som van 15 punten zal 140 keer voorkomen.

De som van 14 punten zal 146 keer voorkomen.

De som van 13 punten zal 140 keer voorkomen.

De som van 12 punten zal 125 keer voorkomen.

De som van 11 punten zal 104 keer voorkomen.

De som van 10 punten zal 80 keer voorkomen.

De som van 9 punten zal 56 keer voorkomen.

De som van 8 punten zal 35 keer voorkomen.

De som van 7 punten zal 20 keer voorkomen.

De som van 6 punten zal 10 keer voorkomen.

De som van 5 punten zal 4 keer voorkomen.

De som van 4 punten zal één keer voorkomen.*

Het is onmiddellijk duidelijk dat zowel hoge als lage scores relatief zeldzaam zijn. Er zijn twee mogelijke totalen, maar de hoogste vier hiervan komen slechts vijfendertig keer voor. De middelste groep van zeven scores kan naar verwachting 884 keer voorkomen; de middelste derde van alle mogelijke scores is het resultaat in meer dan tweederde van alle worpen. Dit leidt tot de kenmerkende concentratie in het centrum van de kansrekening.

Otto Ammon betoogde dat deze willekeurige verdeling van dobbelsteenworpen weerspiegeld werd in de verdeling van menselijke vermogens. Hij schreef dit voordat intelligentietesten en IQ’s werden ontwikkeld en baseerde zich op het eerdere werk over intelligentie van Francis Galton. Ammon ging er niet van uit dat maatschappelijk nut, of succes in het leven, louter afhankelijk is van intelligentie. Hij onderscheidde ‘drie groepen mentale eigenschappen die grotendeels bepalend zijn voor de positie die een man in het leven zal innemen.’ Deze waren:

1. Intellectuele eigenschappen; waaronder ik alles opnam dat behoort tot de rationele kant van de mens, zoals snel begrip, geheugen, beoordelingsvermogen, vindingrijkheid en al het andere dat tot dit domein behoort.

2. Morele eigenschappen; namelijk zelfbeheersing, wilskracht, ijver, doorzettingsvermogen, matigheid, respect voor gezinsverplichtingen, eerlijkheid en dergelijke.

3. Economische eigenschappen; zoals zakelijk inzicht, organiserend talent, technische bekwaamheid, voorzichtigheid, slimme berekening, vooruitziendheid, zuinigheid enzovoort.

Aan deze mentale eigenschappen voegde hij het volgende toe:

4. Lichamelijke eigenschappen; arbeidscapaciteit, uithoudingsvermogen, het vermogen inspanningen te doorstaan en opwindingen van alle aard te weerstaan, vitaliteit, een goede gezondheid, enz.

Volgens Otto Ammon leek de waarschijnlijke verdeling van deze kwaliteiten van intelligentie, karakter, talent en lichaam op die van worpen met dobbelstenen. Hij ging nog een stap verder en betoogde dat er feitelijk veel meer dan vier variabelen waren en dat deze in meer dan zes gradaties varieerden. Als men in plaats van vier dobbelstenen acht gooit, zijn er niet minder dan 1.679.616 mogelijke worpen, en toch kan de hoogste score, achtenveertig, naar verwachting slechts één keer voorkomen. De man of vrouw die op alle factoren die de positie in het leven bepalen zeer hoog scoort, is veel zeldzamer dan de kans op het gooien van vier zessen zou doen vermoeden; misschien zo zeldzaam als het gooien van acht zessen. Toch merkt Ammon op dat een mengeling van hoge en lage scores in deze menselijke kwaliteiten kan leiden tot “personen met onevenwichtige, onharmonieuze gaven, die, ondanks enkele briljante kwaliteiten, de beproevingen van het leven niet met succes doorstaan.”

> “Als een eenzame bergtop, of liever de spits van een kathedraal, rijzen de mannen van hoog talent en genie boven de brede massa van middelmatigheid… Het aantal hoogbegaarden is in elk geval zo klein dat het onmogelijk is dat er ‘vele’ van zulke mensen in lagere klassen zijn gehouden door de onvolledigheid van sociale instellingen.” – OTTO AMMON

### Eigenschappen en Inkomens

Ammon wendt zich vervolgens tot de inkomensverdeling. Natuurlijk waren de statistieken van de jaren 1890 veel minder adequaat dan nu, maar de Duitse bureaucratie was al goed ontwikkeld, en Otto Ammon vond in Saksen, Pruisen, Baden en andere Duitse staten inkomenscurves die hij zowel vergelijkbaar achtte met de door hem waargenomen verdeling van menselijke capaciteiten als met de kansen van de dobbelstenen. Hij vond vergelijkbare cijfers in Charles Booth’s Life and Labour of the People of London (1892). Inderdaad, de sociale verdeling van Booth lijkt precies wat men op basis van Ammons waarschijnlijkheidstheorie zou verwachten. Booth constateerde in Londen dat 25 procent arm of erger was, 51,5 procent het goed had en 15 procent welvarend of beter was; als men de twee laagste categorieën van Booth samenneemt, komt dat op 9,5 procent. Vóór de verzorgingsstaten van de twintigste eeuw werd het niet ongebruikelijk de minst welvarenden de “ondergedoken tiende” te noemen.[^274] De twee hoogste categorieën van Booth vormen samen 7 procent.

Uit dit alles trok Otto Ammon een aantal interessante conclusies. Hij meende dat de capaciteiten van mensen, in brede zin gedefinieerd, hun plaats in de samenleving en hun inkomen bepaalden. Hij was ervan overtuigd dat hoge capaciteiten er op natuurlijke wijze toe leiden dat mensen qua inkomen en sociale status stijgen. ‘Zoals een eenzame bergtop, of liever gezegd, zoals de torenspits van een kathedraal, steken de mannen met hoog talent en genie boven de brede massa van middelmatigheid uit…’ Hij geloofde ook dat de ‘ware vorm van de zogenaamd sociale piramide’ gelijk is aan die van een tamelijk platte ui of rap – een rap met een smalle steel aan de bovenkant en een smalle wortel aan de onderkant. Zo’n sociale rap is als metafoor te verkiezen boven de sociale piramide, omdat zij – net als de moderne industriële samenleving – haar massa in het midden heeft, terwijl de piramide die aan de onderkant concentreert.

### De vorm van de rap

Moderne industriële samenlevingen zijn inderdaad allemaal rapen, met aan de top een kleine klasse van de rijken en hooggekwalificeerden, een grotere middenklasse en onderaan een minderheid van de armen. In het hedendaagse Londen, zo niet in Washington, zijn er zeker meer miljonairs dan daklozen.

Al dit is intrigerend, maar de onmiddellijke relevantie van Ammons werk ligt in de ingrijpende langetermijnverandering die we ervaren in de financiële en politieke relaties tussen de top en de middenklasse. De vaardigheden die nodig waren in het fabriekstijdperk, dat nu ten einde gaat, zijn onmiskenbaar anders dan die welke door het informatietijdperk worden vereist. De meeste mensen zouden de vaardigheden kunnen beheersen die nodig waren om de machines van het midden van de twintigste eeuw te bedienen, maar die functies zijn inmiddels vervangen door slimme machines die in feite zichzelf besturen. Een heel segment van laag- en middenkwalificeerde banen is reeds verdwenen. Als we gelijk hebben, is dit een voorbode van het verdwijnen van het merendeel van de werkgelegenheid en de herstructurering van arbeid op de spotmarkt.

> "Toch is het een feit, officieel maar stilletjes erkend, dat de meeste werkloze jongeren totaal geen kwalificaties hebben..."[^275] - Clive Jenkins en Barrie Sherman

## Minder mensen zullen meer werk verrichten

Stel dat we de eenvoudige verdeling van menselijke bekwaamheid met vier dobbelstenen als uitgangspunt nemen en veronderstellen dat mensen in het tijdperk van de fabrieken een score van 4 x 2 of hoger konden behalen. Dat zou betekenen dat meer dan 95 procent van de bevolking boven wat Charles Booth 'de laagste grens van positieve maatschappelijke bruikbaarheid' noemde, scoorde. In feite werd 3 procent als de norm voor volledige werkgelegenheid vastgesteld in de jaren veertig en vijftig. Stel dat in het informatietijdperk de vereiste score is gestegen naar 4 x 3 en dat het vereiste minimum is toegenomen van 8 naar 12. Dat zou betekenen dat bijna 24 procent onder deze grens van 'maatschappelijke bruikbaarheid' zou vallen.

Iets soortgelijks zou gebeuren aan de bovenkant van de schaal. In het tijdperk van de fabrieken was de vereiste mate van hoge bekwaamheid wellicht 4 x 4; veronderstel dat deze in het informatietijdperk is gestegen naar 4 x 5. In dat geval zou het aandeel mensen dat in aanmerking komt voor de topfuncties – die tevens de best betaalde banen zijn – dalen van 34 procent naar 5 procent.

Deze cijfers zijn puur hypothetisch. Natuurlijk weten we niet wat de verschuiving in de vaardigheidseisen zal zijn – of al is geweest – maar er is zeker sprake van een stijging. Vanwege de vorm van de rap zou zelfs een vrij bescheiden stijging van de minimale vaardigheidseis een groot aantal mensen buiten een betekenisvolle economische rol plaatsen. Evenzo zou een zo'n kleine verhoging van de hogere vaardigheidseis het aantal mensen dat in aanmerking komt voor de hogere functies zeer drastisch doen afnemen. Er is enige verschuiving gaande: we weten nog niet hoe groot die zal zijn.

Er ontbreekt inderdaad niet aan sociaal en politiek bewijs dat deze verschuiving zich in alle geavanceerde industriële samenlevingen voltrekt, dat het tempo versnelt en dat de beweging al groot is. De beloningen voor zeldzame vaardigheden zijn toegenomen en blijven toenemen. Dit is met ongenoegen opgemerkt door conventionele denkers. Neem bijvoorbeeld *The Winner-Take-All Society* van Robert H. Frank en Philip J. Cook.[^276] Het documenteert de groeiende tendens dat de meest getalenteerde concurrenten in vele vakgebieden in de Verenigde Staten zeer hoge inkomens vergaren. Evenzo nemen de kansen voor mensen met middelmatige vaardigheden af; een aanzienlijk aantal mensen met weinig vaardigheden valt nu buiten de inkomensbandbreedte die een comfortabel bestaan mogelijk maakt, al vinden zij nog vaak een plaats in kleinschalige dienstverlening.

Als het informatietijdperk hogere vaardigheden eist aan zowel de top als de onderkant, zal iedereen, behalve de top 5 procent, relatief benadeeld zijn, terwijl de top 5 procent enorm zal profiteren. Zij zullen zowel een groter aandeel van het inkomen vergaren als een groter deel van wat zij verdienen behouden. Tegelijkertijd zullen zij een groter deel van het werk ter wereld verrichten dan ooit tevoren. Velen zullen zich ontwikkelen tot soevereine individuen. In het informatietijdperk zal de knol van de inkomensverdeling er meer uitzien als in 1750 dan in 1950.

Samenlevingen die geïndoctrineerd zijn om inkomensgelijkheid en hoge consumptie voor mensen met weinig of bescheiden vaardigheden te verwachten, zullen te maken krijgen met demotivatie en onzekerheid. Naarmate de economieën van meer landen de informatietechnologie dieper in zich opnemen, zullen zij de opkomst — al zo evident in Noord-Amerika — ervaren van een min of meer niet inzetbare onderklasse. Precies dit is wat er gebeurt. Dit zal leiden tot een reactie met een nationalistische, antitechnologische inslag, zoals we in het volgende hoofdstuk toelichten.

De fabrieksleeftijd zou wel eens een unieke periode kunnen blijken te zijn waarin halfdomme machines een zeer winstgevende niche voor ongeschoolde mensen openlieten. Nu de machines voor zichzelf kunnen zorgen, stort het informatietijdperk zijn geschenken op de top 5 procent van Otto Ammon's knol. Het informatietijdperk zag er al veel beter uit voor de top 10 procent, de zogenoemde cognitieve elite. Toch zal het allerbeste zijn voor de top 10 procent van de top 10 procent, de cognitieve dubbele top. In de feodale tijd was er honderd halfgeschoolde boeren nodig om één hoogopgeleide krijgsheer (of ridder) op paard te ondersteunen. De soevereine individuen van de informatie-economie zullen geen krijgsheren zijn, maar meesters in gespecialiseerde vaardigheden, waaronder ondernemerschap en investeringen. Toch lijkt de feodale verhouding van honderd tegen één weer terug te keren. Voor wat het ook moge brengen, zullen de samenlevingen van de eenentwintigste eeuw waarschijnlijk ongelijker zijn dan die waarin we in de twintigste eeuw hebben geleefd.

## De meeste mensen zullen profiteren van de dood van de politiek

Het is onwaarschijnlijk dat de egalitaire economie en de naties die zij ondersteunt, zonder crisis zullen verdwijnen. Hoewel een crisis per definitie slechts van korte duur kan zijn, stellen we ons toch voor dat het trauma van het verdwijnen van naties jarenlang zal doorwerken. Zonder dat trauma – waarvan we de omvang later in meer detail behandelen – uit het oog te verliezen, is het belangrijk niet te vergeten dat in veel delen van de wereld de overgang naar de informatieeconomie zal leiden tot een enorme stijging van de productie, met hogere inkomens voor iedereen. Inderdaad, in die gebieden die nooit volledig hebben geprofiteerd van de voordelen van het industrialisme maar nu openstaan voor de vrije markt, stijgen de inkomens – of zullen ze stijgen – onder alle lagen van de bevolking.

De deflatie van dwang als kenmerk van het economische leven stelt producenten in staat om activa te behouden die tot nu toe in beslag zijn genomen en herverdeeld. Herverdeling betekende doorgaans dat activa werden overgeheveld naar toepassingen met een lagere waarde, waardoor de productiviteit van het kapitaal verminderde. Vermogen dat onevenredig werd ontnomen aan personen die het meest bedreven waren in het investeren van middelen, werd door politici herverdeeld ten gunste van degenen die minder bedreven waren. In de meeste gevallen werd het herverdeelde inkomen aangewend in economische activiteiten van lagere orde. De effecten van het bevrijden van middelen uit systematische dwang zullen per rechtsgebied sterk variëren. Deze ‘bevriezing’ van middelen zal welvaartsstaten failliet maken en de schaalnadelen versterken die grote overheden en alle door hen gesubsidieerde instellingen ondermijnen. Aan de andere kant zal de verschuiving naar de cybereconomie de economische nadelen verminderen die mensen ervaren onder soevereiniteiten in regio’s die traditioneel te kampen hebben gehad met het onvermogen om zich op grote schaal te organiseren.

> 'Als de wereld functioneert als één grote markt, zal iedere werknemer concurreren met iedere persoon, overal ter wereld, die in staat is hetzelfde werk te verrichten. Er zijn er veel en velen van hen hebben honger.'[^277] - ANDREW S. GROVE, PRESIDENT, INTEL CORP.

## Verschuivende locatievoordelen

Omdat er geen stijgende rendementen op geweld meer zullen zijn, zal er geen voordeel zijn om onder een regering te leven die hiervan kan profiteren. Regeringen die ooit bekwaam waren, zullen niet langer de bondgenoten van vermogensopbouw zijn, maar juist hun vijanden. Hoge belastingen, zware reguleringskosten en ambitieuze verplichtingen tot inkomensherverdeling zullen de gebieden onder hun controle onaantrekkelijke plekken maken om zaken te doen.

Degenen die wonen in rechtsgebieden die tijdens de industriële periode arm of onderontwikkeld bleven, hebben het meest te winnen bij de bevrijding van economieën uit de beperkingen van de geografie. Dit is in tegenstelling tot wat u zult horen. De voornaamste controverse rond de opkomst van de informatie-economie en de opkomst van het soevereine individu zal zich richten op de vermeende nadelige effecten voor 'billijkheid' die voortvloeien uit de dood van de politiek. Het is zeker waar dat de komst van de mondiale informatie-economie een fatale klap zal toebrengen aan grootschalige inkomensherverdeling. De belangrijkste begunstigden van inkomensherverdeling in het industriële tijdperk waren inwoners van welvarende rechtsgebieden, waarvan het consumptieniveau twintig keer hoger lag dan het wereldgemiddelde. Enkel binnen de OESO-landen heeft inkomensherverdeling merkbare effecten gehad bij het verhogen van de inkomens van laaggeschoolde personen.

De grootste inkomensongelijkheden zijn waargenomen tussen rechtsgebieden. Inkomensherverdeling heeft weinig bijgedragen om deze te verminderen. Sterker nog, wij zijn van mening dat buitenlandse hulp en internationale ontwikkelingsprogramma’s het perverse effect hebben gehad dat de reële inkomens van arme mensen in arme landen verlaagd werden door incompetente regeringen te subsidiëren. Dit is een onderwerp dat we uitvoeriger behandelen bij de analyse van de impact van de informatierevolutie op de moraal.

Een eeuw van stijgende inkomensongelijkheid

Tijdens de industriële periode was het politieke rechtsgebied waarin een gewoon mens woonde de belangrijkste factor die zijn levenslange inkomen bepaalde. In tegenstelling tot de gangbare indruk in de welvarende economieën van vandaag, steeg de inkomensongelijkheid in die periode snel. Een schatting, aangehaald door de Wereldbank, suggereert dat het gemiddelde inkomen per hoofd in de rijkste landen uitgroeide van elf keer dat van de armste landen in 1870 tot tweeënvijftig keer in 1985.[^278] Hoewel de ongelijkheid op wereldschaal dramatisch toenam, leek dit voor de mensen in de rijke industriële landen vaak niet zo te zijn: de inkomensongelijkheid nam vooral toe tussen rechtsgebieden in plaats van binnen deze rechtsgebieden.

Om redenen die we al eerder hebben besproken, zorgde de aard van de industriële technologie er zelf voor dat de inkomenskloof binnen rechtsgebieden verkleinde waar redelijk competente regeringen de macht op grote schaal beheersten. Toen de opbrengsten van geweld toenamen, zoals dat tijdens het industriële tijdperk het geval was, werden grootschalige regeringen vaak gecontroleerd door hun eigen medewerkers. Dit maakte het in de praktijk vrijwel onmogelijk om beperkingen op te leggen aan de aanspraken die deze regeringen op middelen maakten. Hun onbelemmerde controle over middelen bood een belangrijk militair voordeel, zolang de omvang van de macht zwaarder woog dan de efficiëntie waarmee die werd benut. Een niet toevallige consequentie van regeringen die door hun eigen medewerkers werden gecontroleerd, was een scherpe versnelling van inkomensherverdeling. Bijna elke samenleving kent enige vorm van inkomensherverdeling, zij het tijdelijk in uitzonderlijke omstandigheden. Een nadere beschouwing van de geschiedenis van de hulpverlening aan de armen toont echter aan dat 'welfare'-uitkeringen de neiging hebben genereuzer te zijn wanneer armoede minimaal is. Inkomensherverdeling wordt eerder beperkt wanneer de inkomens voor grote groepen afnemen. De omstandigheden in de rijke industriële samenlevingen in de laatste helft van de twintigste eeuw waren bijna perfect voor inkomensherverdeling. Dit leidde tot veel hogere beloningen voor laaggeschoold werk binnen deze bevoorrechte rechtsgebieden. Uiteindelijk zorgde het er zelfs voor dat ook degenen die helemaal niet werkten een hoog niveau van consumptie konden bereiken.

### De paradox van industriële rijkdom

De ironie is dat juist in deze rechtsgebieden meer mensen rijk werden. Deze schijnbare paradox is volkomen logisch zodra je de dynamiek van de megapolitiek, zoals in eerdere hoofdstukken besproken, begrijpt. Toonaangevende sectoren van de industriële economie vereisten een grootschalige handhaving van orde om optimaal te kunnen functioneren. Dit maakte hen bijzonder kwetsbaar voor afpersing door vakbonden en overheden die erop gebrand waren het aantal personen onder hun invloed te maximaliseren. Toch verhinderde de wijdverspreide herverdeling van inkomens het functioneren van de industriële economie niet volledig. Wie het geluk had geboren te worden in West-Europa, in de voormalige Britse koloniën of in Japan tijdens de hoogtijdagen van de industrialisatie, was dan ook waarschijnlijk een stuk rijker dan iemand met vergelijkbare vaardigheden in Zuid-Amerika, Oost-Europa, de late Sovjet-Unie, Afrika of op het Aziatische vasteland. De positieve impact van informatietechnologie zal onder meer helpen veel ontwikkelingsobstakels te overwinnen, obstakels die gedurende een groot deel van de moderne periode de meerderheid van de wereldbevolking ervan weerhielden te genieten van de voordelen van vrije markten.

> 'De inheemse kenmerken van arme landen zijn opvallend ongunstig voor een effectieve grootschalige organisatie, in het bijzonder voor grootschalige organisaties die – zoals overheden – over een groot geografisch gebied moeten opereren.'[^279] - MANCUR OLSON

## Schaalnadelen en vertraagde groei

Zoals Mancur Olson heeft aangetoond, was de achterstand in de twintigste eeuw niet per se te wijten aan een gebrek aan kapitaal of aan gespecialiseerde vaardigheden. In 'Schaalnadelen en ontwikkeling', een essay dat in 1987 werd gepubliceerd, twee jaar voor de val van de Berlijnse Muur, schreef Olson: 'Als kapitaal immers schaars was in de arme landen, zouden de ‘marginale productiviteit’ en de daarmee samenhangende winstgevendheid van het gebruik ervan groter moeten zijn dan in de welvarende landen. De lage groeipercentages van veel landen die niet te verwaarlozen buitenlandse hulp ontvingen en de lage productiviteit van enkele moderne fabrieken in arme landen hebben bovendien de geloofwaardigheid van de verklaring ‘schaarste aan kapitaal’ voor onderontwikkeling verder ondermijnd.'[^280] Dit moet kloppen. Als het tekort aan kapitaal of vaardigheden de voornaamste tekortkoming zou zijn geweest, dan zouden de opbrengsten in arme rechtsgebieden hoger zijn geweest dan in ontwikkelde landen. Zowel gekwalificeerd personeel als kapitaal zouden massaal naar deze regio's zijn gestroomd totdat de opbrengsten zich hadden genormaliseerd. In feite was vaak het tegenovergestelde het geval. Er was sprake van een aanzienlijke uitstroom van opgeleide mensen uit achtergestelde rechtsgebieden. En de enkelen die erin slaagden kapitaal te vergaren, exporteerden dat zo snel mogelijk naar Zwitserland en andere ontwikkelde landen.

Beter bestuur kon niet worden geïmporteerd

Olson stelt – en wij zijn het daarmee eens – dat het ware obstakel voor de ontwikkeling in achterblijvende landen de enige productiefactor was die niet makkelijk geleend of geïmporteerd kon worden uit het buitenland, namelijk het bestuur. Dit is een probleem dat verergerde naarmate de twintigste eeuw vorderde. In 1900 waren Groot-Brittannië en Frankrijk, samen met enkele andere Europese landen, actief in het exporteren van bekwaam bestuur naar regio's waar inheemse machten niet in staat waren op grote schaal effectief te functioneren. Maar veranderende megapolitieke omstandigheden in de twintigste eeuw zorgden ervoor dat de kosten voor deze activiteit stegen en dat de opbrengsten daalden. Kolonialisme – of imperialisme, zoals het minder graag werd genoemd – bleek geen lonende onderneming meer te zijn. Technologische ontwikkelingen verhoogden de kosten om macht vanuit het centrum naar de periferie uit te stralen en verlaagden tegelijkertijd de militaire kosten van een effectieve weerstand. Daardoor trokken de imperialistische machten zich terug, of bleven zij slechts in kleine enclaves aanwezig, zoals op Bermuda of de Kaaimaneilanden.

> 'Als de postkoloniale natiestaat een belemmering voor vooruitgang was geworden, zoals tegen het einde van de jaren tachtig steeds meer critici in Afrika leken te beamen, kon de voornaamste reden vrijwel onbetwistbaar zijn. De staat bevrijdde en beschermde zijn burgers niet, ongeacht wat haar propaganda beweerde; integendeel, haar algehele effect was beperkend en uitbuitend, of dan wel functioneerde zij simpelweg in geen enkele maatschappelijke zin.'[^281] – BASIL DAVIDSON

De inheemse regeringen die de koloniale overheersing vervingen in de landen waarin Europeanen zich niet hadden gevestigd, putten hun leiders en bestuurders uit bevolkingsgroepen die weinig ervaring of bekwaamheid hadden in het besturen van enige vorm van grootschalige onderneming. In veel gevallen – met name in Afrika – werd de infrastructuur die was geërfd van de vertrekkende koloniale machten snel geplunderd, vernietigd of in verval achtergelaten. Telefoonlijnen werden door schavelaars neergehaald en tot armbanden gesmeed. Wegen werden niet langer onderhouden. Spoorwegen raakten nutteloos doordat de spoorbeddingen uit elkaar vielen en de locomotieven stukgingen. In Zaïre was de uitgebreide transportinfrastructuur, aangelegd door de Belgen, tegen 1990 bijna volledig verdwenen. Slechts een paar piepende rivierschepen bleven nog functioneren, waarvan er één door de dictator als een soort drijvend paleis werd overgenomen.

Onbetrouwbare communicatie en transport weerspiegelen de onbekwaamheid van achterblijvende natiestaten in het handhaven van de orde. Zij hebben de prijzen hoog gehouden en de kansen voor het grootste deel van de wereldbevolking tot een minimum beperkt. Zoals Olson benadrukt:

> Ten eerste dwingen gebrekkige transport- en communicatiesystemen een onderneming om hoofdzakelijk op lokale productiefactoren te vertrouwen. Naarmate de omvang van een onderneming toeneemt, zal zij ver moeten reiken om de benodigde productiefactoren te bemachtigen, en hoe slechter de transport- en communicatiesystemen, des te sneller zullen de kosten van deze factoren stijgen bij het uitbreiden van de productie. De tweede, en nog belangrijkere, reden waarom gebrekkige transport- en communicatiesystemen contraproductief zijn voor effectieve grootschalige ondernemingen, is dat ze de effectieve coördinatie van zulke ondernemingen aanzienlijk bemoeilijken.[^282]

### Het verlichten van de last van slecht bestuur

De ambitieuze armen van de wereld zullen in het bijzonder profiteren nu informatietechnologie de mogelijkheden om inkomen te genereren loskoppelt van de woonplaats. Nieuwe technologieën, zoals de digitale mobiele telefoon, stellen communicatie in staat onafhankelijk te functioneren van het vermogen van de lokale politie om elke telefoonpaal binnen een rechtsgebied te bewaken tegen koperdieven. Nu draadloze fax- en internetverbindingen beschikbaar komen, doet het er minder toe of noodlijdend arme postmedewerkers de post bemachtigen enkel om het postzegel te stelen.

In veel gevallen vervangt effectieve communicatie zelfs de noodzaak om goederen en diensten fysiek te vervoeren. Betere communicatiemiddelen en een enorm toegenomen rekenvermogen maken de coördinatie van complexe activiteiten niet alleen goedkoper en effectiever; ze doen ook de voordelen van schaalvergroting afnemen en maken grote organisaties overbodig. Deze veranderingen verminderen allen de last die mensen in achtergestelde landen hebben geleden door te leven onder incompetente overheden. De informatierevolutie zal het veel minder belangrijk maken of overheden capabel functioneren, waardoor het voor mensen in traditioneel arme landen gemakkelijker wordt om de obstakels te overwinnen die hun overheden tot nu toe in de weg hebben gestaan van economische groei.

### Gelijke kansen in het informatietijdperk

In het informatietijdperk zullen bekende locatievoordelen snel door technologie worden getransformeerd. De verdiencapaciteit van mensen met vergelijkbare vaardigheden zal veel gelijker worden, ongeacht in welk rechtsgebied zij wonen. Dit is al begonnen te gebeuren. Omdat instellingen die dwang en lokale voordelen hebben ingezet om het inkomen te herverdelen macht verliezen, zal de inkomensongelijkheid binnen rechtsgebieden toenemen. Wereldwijde concurrentie zal er tevens toe leiden dat de inkomsten van de meest getalenteerde individuen in elk vakgebied, waar zij ook wonen, toenemen, zoals het nu gebeurt in de professionele atletiek. De marginale waarde die door superieure prestaties op een wereldwijde markt wordt gegenereerd, zal enorm zijn.

Terwijl het publieke debat zich zal richten op de groeiende 'ongelijkheid' in de OESO-landen, zullen mensen overal veel meer gelijke kansen hebben. Ze hoeven niet langer in een rechtsgebied te wonen dat op grote schaal goed functioneert om succesvol te zijn. Aangeboren talenten en de bereidheid om ze te ontwikkelen, zullen op een veel gelijker speelveld worden beoordeeld dan ooit tevoren. De jurisdictievoordelen die tijdens de industriële periode leidden tot toenemende ongelijkheid tussen rijke en arme economieën, zullen drastisch veranderen.

### Hogere rendementen in arme gebieden

De belemmeringen die regeringen in armere regio’s opwerpen voor het functioneren van vrije markten, zullen aanzienlijk afnemen naarmate de cybereconomie in werking treedt. Als gevolg hiervan zullen kapitaal en vaardigheden, die schaars zijn, in veel van de momenteel arme gebieden inderdaad hogere rendementen opleveren, zoals de ontwikkelingstheoretici van de jaren vijftig postuleerden dat het zou moeten. En zowel kapitaal als vaardigheden zullen veel gemakkelijker geïmporteerd kunnen worden. Opkomende economieën zullen niet langer zo sterk afhankelijk zijn van lokale productiefactoren als in het industriële tijdperk. Hun verbeterde vermogen om op afstand kapitaal en expertise aan te trekken, zal leiden tot hogere groeipercentages. Dit zal gebeuren, ongeacht of incompetente regeringen eerlijker worden of beter in staat zijn om eigendomsrechten te beschermen. Door gebrek aan macht over de cyberruimte zullen slechte regeringen eenvoudigweg minder in staat zijn om te voorkomen dat mensen in hun rechtsgebieden profiteren van economische vrijheid.

### Positieve versterking

In de nieuwe cybereconomie zal de bijna volledige draagbaarheid van informatietechnologie het hamsteren van veel van de jurisdictievoordelen, die in het industriële tijdperk zijn ontstaan, onmogelijk maken. De toenemende concurrentie tussen steeds meer jurisdicties zal afhangen van nieuwe vormen van lokaal voordeel. Soevereiniteit zal vercommercialiseerd worden in plaats van roofzuchtig te zijn. Overheden zullen door de kracht van de concurrentie gedwongen worden beleid te voeren dat gericht is op degenen in hun klantenkring die de grootste bijdrage leveren aan het economische welzijn, en niet op diegenen die weinig bijdragen of zelfs een negatieve economische bijdrage hebben.

Dit zal een enorme verandering betekenen ten opzichte van de gangbare praktijk in de twintigste eeuw. De ideologie van de natiestaat hield in dat het leven op een positieve wijze geregeld kon en moest worden door ongewenste uitkomsten te subsidiëren en gewenste uitkomsten te bestraffen. Arm zijn is ongewenst; daarom werden de armen gesubsidieerd. Rijk worden is wenselijk; daarom werden de rijken getroffen met hoge, bestraffende belastingen om het leven 'eerlijker' te maken.

Omdat deze gehele beleidsaanpak geworteld was in een megapolitieke basis waartegen geen beroep gedaan kon worden, maakte het weinig uit wat de perverse gevolgen waren van het subsidiëren van disfunctie. Er werd ook nauwelijks rekening gehouden met de vaardigheid, het harde werk of de vindingrijkheid die nodig waren om de rijkdom te vergaren die vervolgens werd herverdeeld. Uitkomsten werden gemeten in termen van aanspraken. De politieke visie van de twintigste eeuw ging ervan uit dat, om uitkomsten 'eerlijk' te laten zijn, zij gelijk moesten zijn.

### Het nieuwe paradigma

De nieuwe megapolitieke omstandigheden van de eenentwintigste eeuw zullen het mogelijk maken dat marktproeven worden ingezet om uitkomsten te reguleren op terreinen die voorheen door de politiek werden beheerst. Het marktparadigma veronderstelt dat resultaten beter geregeld kunnen worden door gewenste uitkomsten te belonen en ongewenste uitkomsten te bestraffen. Arm zijn is ongewenst en rijk worden is wenselijk. Daardoor zouden prikkels de creatie van rijkdom moeten belonen en mensen aanmoedigen te betalen voor de middelen die zij verbruiken. Het leven is 'eerlijker' wanneer mensen een groter deel van wat zij verdienen mogen behouden.

Dit is een opvatting die in het nieuwe millennium vaker aan bod zal komen dan in de eeuw die nu ten einde loopt. Bovendien zal het overtuigender zijn dan ooit tevoren, omdat het gestoeld zal zijn op grootschalige politieke grondslagen. Het kapitaal in het informatietijdperk wordt met de minuut mobieler. De mogelijkheid om een hoog inkomen te verwerven is niet langer gekoppeld aan het wonen op specifieke locaties, zoals het geval was toen de meeste rijkdom werd gecreëerd door het exploiteren van natuurlijke hulpbronnen. Met elke dag die verstrijkt, wordt het voor mensen die gebruikmaken van uiterst draagbare informatietechnologie gemakkelijker om activa te creëren die veel minder vatbaar zijn voor de invloed van geweld dan welke vorm van rijkdom dan ook ooit is geweest.

Willekeurige politieke regelgeving die kosten oplegt zonder evenredige marktvoordelen te bieden, zal al snel onhoudbaar blijken. Krachtige concurrentiekrachten zorgen ervoor dat de prijzen van goederen, diensten, arbeid en kapitaal over de hele wereld gelijk worden. Overheden zullen minder ruimte hebben om willekeurige beleidsmaatregelen op te leggen dan zij voorheen gewend waren. Elke overheid die zwaardere regelgeving voor een bepaalde activiteit probeert op te leggen dan andere soevereine staten, zal die activiteit eenvoudigweg naar andere jurisdicties wegjagen. In sommige gevallen zal het weglokken van ongewenste activiteiten juist de markt behagen en die jurisdicties des te populairder en welvarender maken. In dit opzicht kunnen bepaalde regels vergeleken worden met de huisregels die door de eigenaren van een hotelketen worden opgelegd. Als zij het lopen blootsvoets of het roken in de lobby verbieden, zullen zij ongetwijfeld bepaalde klanten verliezen. Maar het afwijzen van die klanten hoeft de jurisdictie niet noodzakelijkerwijs van klanten te beroven, noch haar totale opbrengsten te verminderen. Goed beschoede niet-rokers kunnen daardoor juist meer betalen. Eveneens kunnen regels die het duur of onmogelijk maken om een renderingfabriek in een bepaalde jurisdictie te exploiteren, de verwerking eldersheen drijven zonder dat de gehele jurisdictie van inkomsten wordt beroofd.

Deze voorbeelden tonen aan hoe regelgeving in zeldzame gevallen een positieve in plaats van een negatieve marktwaarde kan hebben, vooral in een wereld met een snel groeiend aantal jurisdicties. Regels die hoge normen op het gebied van volksgezondheid, schone lucht en schoon water handhaven, zullen in veel regio’s zeer gewaardeerd worden. Eveneens zullen andere, soms meer exotische, regelgevingen en convenanten – van de soort die door vastgoedontwikkelaars of hotels die zich op bepaalde marktsegmenten richten worden opgelegd – hoog in aanzien staan.

### Geen douanehuis in cyberspace

Wij verwachten dat de commercialisering van soevereiniteit snel zal leiden tot de decentralisatie van vele grote territoriale soevereiniteiten. Het feit dat informatietechnologie niet onderworpen kan worden aan grenscontroles, zoals die nog steeds de handel in vervaardigde goederen en landbouwproducten kunnen belemmeren, heeft belangrijke implicaties. Het betekent dat protectionisme in de loop van de tijd minder effectief zal blijken, nu de handel in informatie fysieke producten verdringt in de totstandbrenging van rijkdom. Tevens betekent het dat kleinere regio’s steeds minder afhankelijk zullen zijn van het handhaven van omvangrijke politieke jurisdicties om toegang te garanderen tot markten waarop zij inkomsten kunnen genereren.

Information technology stelt mensen die in voorheen beschermd werkende dienstensectoren werkzaam zijn bloot aan buitenlandse concurrentie. Twintig jaar geleden moest een bedrijf in Toronto, als het een boekhouder wilde inhuren, erop letten dat die persoon zich fysiek in Toronto of in een nabijgelegen gemeente binnen redelijke pendelafstand bevond. In het informatietijdperk kan een boekhouder in Boedapest of in Bangalore, India, de klus klaren en alle benodigde materialen in versleutelde vorm downloaden via het internet. Directe communicatie via satellietverbindingen zorgt ervoor dat elk deel van de wereld slechts een moment verwijderd is via modem en fax. Iemand die op zoek is naar aandelenanalisten, zou er in India zevenentwintig kunnen inhuren voor de prijs van één op Wall Street. Naarmate de informatietechnologie elke achttien maanden met een orde van grootte of meer verbetert (volgens de wet van Moore), zullen steeds meer werknemers in de dienstensector worden blootgesteld aan prijsconcurrentie die in wezen buiten het bereik ligt van wat politici kunnen tegenhouden. Deze concurrentie zal uiteindelijk net zo volledig gelden voor de geleerde beroepen als voor boekhouders. Digitale advocaten en cyberdokters zullen in de informatie-economie in rap tempo toenemen.

### Natiestaten op de doodsklok

Nu de economische voordelen die voorheen binnen de grenzen van natiestaten werden vastgehouden wegvallen, zullen de natiestaten zelf uiteindelijk instorten onder hun zware lasten. Maar het feit dat alle natiestaten op de doodsklok staan, betekent niet dat zij allemaal op hetzelfde moment zullen vergaan. Helemaal niet. De druk tot decentralisatie zal doorgaans het sterkst zijn in grote politieke entiteiten waar de inkomens van het merendeel van de bevolking stagneren of dalen. Regeringsgebieden in Latijns-Amerika en Azië, waar het inkomen per hoofd van de bevolking snel stijgt, kunnen generaties lang standhouden – of tot het levenslange inkomensperspectief daar gelijk is aan dat in de voorheen rijke industriële landen. Op dat moment zullen er geen eenvoudige kostenbesparende winsten meer te behalen zijn en zal de groeipolitiek uitdagender worden.

Wij vermoeden ook dat natiestaten met één dominante metropool langer coherent blijven dan landen met meerdere grote steden, aangezien die meerdere centrum van belangen en bijbehorende hinterlanden impliceren.

Een andere stimulans voor decentralisatie zal de hoge schuldenlast van de centrale overheid zijn. De drie welvarende industriële landen met de hoogste relatieve schulden – Canada, België en Italië – zijn niet toevallig natiestaten met geavanceerde separatistische bewegingen. Alle drie de landen kampen met chronische begrotingstekorten en hebben nu nationale schulden die meer dan 100 procent van het BBP bedragen. Naarmate de nationale schuld in elk land is opgelopen, is ook de aantrekkingskracht van separatistische bewegingen toegenomen. In Italië is de Lega Nord opgekomen als een dynamische en populaire regionale politieke beweging. Haar programma steunt op een eenvoudige wiskundige constatering: Noord-Italië, of Padonia, zou rijker zijn dan Zwitserland als grote delen van zijn inkomen niet werden afgetapt om Rome en het armere zuiden te subsidiëren. De Lega Nord stelt een voor de hand liggende oplossing voor: afscheiding van Italië om zo aan enkele schrijnende gevolgen van samengestelde rente te ontsnappen. Evenzo manoeuvreren in België – waar de nationale schuld meer dan 130 procent van het BBP bedraagt – Vlamingen en Walen als een vijandig koppel voorafgaand aan een scheiding. Een groeiende minderheid onder de Vlamingen stelt dat zij de Walen oneerlijk subsidiëren en dat zij hun economische positie kunnen verbeteren door België in tweeën te splitsen.

Canadas situatie verschilt in dat Frans Canada, de voornaamste regio die zich nu inzet voor afscheiding, historisch gezien gesubsidieerd werd door Engelstalig Canada. Maar nu de federale schuld en het tekort blijven groeien, wordt in Quebec steeds duidelijker dat deze vorm van inkomensherverdeling zal afnemen. De Bloc Québécois flirt daarom met een aansporing die een decennium geleden nog ontbrak – de belofte om het inkomen na belastingen te verhogen door de betaling van de Canadese federale belasting af te schaffen. Separatistische leiders suggereren bovendien dat Quebec Canada zou moeten verlaten zonder een evenredige last van de federale schuld op zich te nemen.

Engelstalige Canadezen verzetten zich tegen dit argument en voelen hun afkeer tegenover de implicaties ervan, omdat zij zich scherp bewust zijn van de grote geldstromen die in de loop der jaren naar Quebec zijn overgeheveld. Desalniettemin is de aantrekkingskracht van het Parti Québécois sterk, en het lijkt slechts een kwestie van tijd voordat een afscheidingsreferendum Canada doet uiteenvallen. Een vergelijkbaar lot wacht ook andere natiestaten wanneer hun financiële situatie verslechtert.

Een andere factor die niet veel goeds belooft voor het langetermijnbestaan van Canada is het feit dat het een dunbevolkt land is met een uitgestrekte infrastructuur uit de industriële tijd, die onderhouden moet worden. De overgang naar het informatietijdperk zorgt er onvermijdelijk voor dat fysieke infrastructuur in waarde daalt. Nu thuiswerkers fabrieksarbeiders en kantoormedewerkers vervangen, zal het minder uitmaken of snelwegen en andere belangrijke transportroutes opnieuw worden aangelegd en goed onderhouden. Terwijl fiscale crises van alle kanten toeslaan, zullen steeds meer groepen in het Canadese leven zich terugtrekken naar de exclusieve achttiende-eeuwse visie op de financiering van publieke goederen zoals door Adam Smith bepleit werd. Hij schreef in *The Wealth of Nations*:

> Indien de straten van Londen verlicht en betegeld zouden worden ten laste van de (nationale) schatkist, is er dan enige kans dat zij zo goed verlicht en betegeld zouden zijn als nu, of zelfs tegen zo’n geringe kost? Bovendien, in plaats van dat de kosten worden opgehaald via een lokale belasting op de inwoners van iedere specifieke straat, parochie of wijk in Londen, zouden deze in dat geval uit de algemene staatsinkomsten worden bekostigd en bijgevolg via een belasting op alle inwoners van het koninkrijk worden opgehaald, van wie het grootste deel geen enkel voordeel haalt uit de verlichting en betegeling van de Londense straten.[^283]

Vervang Londen door Toronto, en je bevindt je in een vergelijking die door velen in Alberta en British Columbia hun manier van denken zal beïnvloeden. De logica van devolutie zal aanstekelijk blijken te zijn.

When Canada breaks apart, this will lead to a marked increase in secessionist activity in the Pacific Northwest of the United States. Residents of Alaska, Washington, Oregon, Idaho, and Montana would find themselves at a distinct disadvantage in competition with Alberta and British Columbia as independent sovereignties.

Wanneer Canada uiteenvalt, zal dit leiden tot een duidelijke toename van afscheidingsbewegingen in het pacifisch noordwesten van de Verenigde Staten. Bewoners van Alaska, Washington, Oregon, Idaho en Montana zouden als onafhankelijke staten duidelijk achtergesteld zijn ten opzichte van Alberta en British Columbia.

## AFTER THE NATIONSTATE

NA DE NAATIENSTAAT

In the place of nationstates you will see, at first, smaller jurisdictions at the provincial level, and ultimately, smaller sovereignties, enclaves of various kinds like medieval city-states surrounded by their hinterlands. As strange as it may seem to people inculcated with the importance of politics, policies of these new ministates will in many cases be informed more by entrepreneurial positioning than by political wrangling. These new, fragmented sovereignties will cater to different tastes, just as hotels and restaurants do, enforcing specific regulations within their public spaces that appeal to the market segments from which they draw their customers. This is not to say, of course, that there are not special problems arising from the organization of protection on a nomadic basis. We address these in the next chapter.

In plaats van natienstaten zul je aanvankelijk kleinere rechtsgebieden op provinciaal niveau zien, en uiteindelijk kleinere soevereiniteiten – enclaves van allerlei soorten, die doen denken aan middeleeuwse stadstaten omgeven door hun achterland. Hoe vreemd het ook lijkt voor mensen die van jongs af aan het belang van politiek bijgebracht hebben gekregen, zullen de beleidskeuzes van deze nieuwe ministaten in veel gevallen meer worden bepaald door ondernemend positioneringsinzicht dan door politieke strijd. Deze nieuwe, gefragmenteerde soevereiniteiten zullen inspelen op uiteenlopende smaken, net zoals hotels en restaurants dat doen, door specifieke regels in hun openbare ruimtes af te dwingen die aansluiten bij de marktsegmenten waar zij hun klanten uit halen. Dit wil natuurlijk niet zeggen dat er geen bijzondere problemen ontstaan bij het organiseren van bescherming op een nomadische basis; deze behandelen we in het volgende hoofdstuk.

> "Stadslucht brengt vrijheid." - MIDDELEEUWSE GEWOONHEID

### Non citizens of the Pale

Niet-burgers van het Bleke

Ondanks deze moeilijkheden vindt de menselijke vindingrijkheid doorgaans een manier om instellingen te creëren die winstgevende kansen benutten, zelfs wanneer de vraag afkomstig is van personen die nauwelijks kunnen betalen. Waar de potentiële klanten tot de rijkste mensen ter wereld behoren, zou die neiging nog sterker moeten zijn. Exit, ofwel ‘stemmen met je voeten’, is altijd een optie wanneer gedateerde producten, organisaties of zelfs regeringen hun aantrekkingskracht verliezen en weinig vooruitzicht op directe verbetering lijken te bieden. Denk bijvoorbeeld aan de opkomst van middeleeuwse steden die als toevluchtsoord dienden voor lijfeigenen die de feodale onderdrukking ontvluchtten. Hun rol zou vergelijkbaar kunnen blijken te zijn met die van nieuwe rechtsgebieden die de aanstaande uittreding uit natiestaten opvangen. De aanvaarding van vreemdelingen die bij een heer ontsnapten als ‘burgers van het Pale’ tartte de heersende conventies van het feodale recht en de bisschoppelijke autoriteit. Desalniettemin bleek het voor degenen die het toepasten een over het algemeen succesvolle alternatieve oplossing te zijn, die in belangrijke mate bijdroeg aan het verzwakken van de greep van het feodalisme. Zoals de middeleeuwse historicus Fritz Rorig het verwoordde, zou een lijfeigenen van een seculiere heer ‘na een jaar en een dag een vrije burger van de stad’ worden.[^284] Het is redelijk te verwachten dat er nieuwe institutionele toevluchtsoorden zullen ontstaan, gebaseerd op ‘nieuwe juridische principes’, om fiscale bescherming te bieden aan de burgers van de staat, vergelijkbaar met de manier waarop de middeleeuwse stad onderdanen die in de schaduw van haar muren leefden, schuiling bood.

De econoom Albert O. Hirschman, die de theoretische subtiliteiten van ‘stemmen met je voeten’ onderzochte in *Exit, Voice, and Loyalty*, dat voor het eerst werd gepubliceerd in 1969, voorzag dat technologische vooruitgang de kans op uittreding als strategie om met staten in verval om te gaan, zou vergroten. Hij schreef: “Pas wanneer landen door de vooruitgang in communicatie en de algehele modernisering op elkaar gaan lijken, zal het gevaar van vroegtijdige en buitensporige uittredingen ontstaan …”[^285] Precies dat is wat er nu gebeurt. Informatietechnologie verkleint in rap tempo vele verschillen tussen rechtsgebieden, waardoor uittreding een veel aantrekkelijkere optie wordt. Natuurlijk worden ‘vroegtijdige en buitensporige uittredingen’ in Hirschmans terminologie begrepen vanuit het oogpunt van wat optimaal is voor de staat die wordt verlaten. Ongetwijfeld waren de heren in het middeleeuwse Europa van mening dat zij te maken hadden met ‘vroegtijdige en buitensporige uittredingen’ van hun lijfeigenen naar steden waar deze vrijheid genoten.

Terugkomend op ons eerdere voorbeeld is het niet zo vergezocht als het lijkt te veronderstellen dat er een aantal ministaten zullen ontstaan die toevlucht bieden aan ballingen die vluchten voor de stervende natiestaten. Deze soevereiniteiten zullen concurreren op de voorwaarden van ballingschap. Sommigen, wellicht aan de westkust van Noord-Amerika, zullen inspelen op mensen die niet roken en geen enkele tolerantie hebben voor passief roken. Duidelijk zou zo’n regime niet populair zijn bij rokers. Regels die hun gewoonte verbieden, zullen voor veel rokers als een willekeurige opgelegde maatregel overkomen.

In het industriële tijdperk van de massale politiek werden dergelijke meningsverschillen uitgevochten in politieke campagnes, die uiteindelijk de ene of de andere groep dwongen zich te onderwerpen aan de wensen van de machtiger partij. Maar het is geenszins noodzakelijk dat geschillen over wederzijds exclusieve keuzes op een wijze worden beslecht die inhoudt dat de voorkeuren van grote groepen mensen onderdrukt moeten worden.

Sommige mensen eten graag foie gras, anderen houden van hotdogs en weer anderen eten tofu. Zij hoeven doorgaans niet over hun dieetvoorkeuren te ruziën, omdat hun culinaire keuzes niet met elkaar verbonden zijn. Niemand dwingt iedereen om hetzelfde maal te nuttigen. Megapolitieke omstandigheden dwongen echter wel tot een gedeeld gebruik van allerlei soorten collectieve en zelfs particuliere goederen, verschaft door overheden in het industriële tijdperk. Waarom? Omdat er grote economische voordelen te behalen waren door op grote schaal te opereren. Het was daarom onpraktisch om uitgestrekte rechtsgebieden op te splitsen in enclaves waar iedereen zijn eigen gang kon gaan, zelfs niet in belangrijke zaken. De door Adam Smith bepleitte uitsluitende benadering van het leveren van publieke goederen kan veel gemakkelijker worden toegepast wanneer het aantal rechtsgebieden met een factor tien of zelfs honderd toeneemt. In het informatietijdperk zullen steeds meer soevereiniteiten kleine enclaves zijn in plaats van continentale rijken. Sommigen zullen Noord-Amerikaanse inheemse stammen zijn die, net zoals zij nu al het recht claimen om gokcasino’s te exploiteren of te vissen in strijd met beperkingen, aanspraak maken op belastingjurisdictie over hun reservaten en gebied.



Doordat informatietechnologie vele nadelen wegneemt van het decentraliseren van handelsgebieden, zal het praktisch zijn dat de nieuwe soevereiniteiten meer opereren volgens de principes van clubs of affiniteitsgroepen dan volgens de uitgangspunten van territoriale natiestaten. Net zoals het niet essentieel is dat elke potentiële klant dezelfde smaak in kleding heeft of dezelfde televisieprogramma’s bekijkt, zal het minder belangrijk zijn dan het lijkt dat iedereen het eens is over de affiniteitspunten die de bestuursstijl van gefragmenteerde soevereiniteiten bepalen.

Wijdverspreide smaakvoorkeuren zullen resulteren in sterk uiteenlopende vormen van gefragmenteerde soevereiniteit, vergelijkbaar met de steeds grotere keuzemogelijkheden in kledingstijlen of televisie-uitzendingen. Sommige microstaten kunnen zelfs met elkaar verbonden zijn, zoals hotelketens in franchises, of samenwerken om voordelen te behalen op het gebied van politietaken en andere resterende overheidsdiensten. Degenen die van schone straten houden en het irritant vinden om kauwgom onder tafel te vinden, zullen Singapore aantrekkelijk vinden. Fans van Beavis en Butthead daarentegen niet. Wie van een wild nachtleven houdt, zal waarschijnlijk de voorkeur geven aan Macao of Panama, of een soortgelijke plek. Klanten die zich niet thuis voelen bij de gebruiken in één rechtsgebied, zullen in andere gebieden welkom worden geheten. Hoewel Salt Lake City mogelijk rookvrij is, zal de nieuwe stadstaat in Havana, wellicht hernoemd Monte Cristo, waarschijnlijk gehuld zijn in een wolk sigarenrook.

> 'Het betekent dat alle monopolies, hiërarchieën, piramides en machtsnetwerken van de industriële samenleving zullen oplossen onder de voortdurende druk om intelligentie naar de randen van alle netwerken te verspreiden. Bovenal zal de wet van Moore de essentiële concentratie, de fundamentele fysieke samenklontering van macht in Amerika van vandaag, omverwerpen: de grote stad – dat grote geheel van industriële steden dat nu steunt op ondersteuningssystemen – zo'n 360 miljard aan directe subsidies van de rest van ons ieder jaar. Grote steden zijn overgebleven bagage uit het industriële tijdperk.'[^286] - GEORGE GILDER

Een merkwaardige ironie bij de heropleving van micro-soevereiniteiten of 'stadstaten' is dat dit samen zou kunnen vallen met het leegtrekken van veel steden. De grote stad was grotendeels een bijproduct van het industrialisme in het Westen. Zij ontstond met het fabrieksysteem om schaalvoordelen te benutten in de productie van goederen met een hoog natuurlijk grondstofgehalte.

Toen de negentiende eeuw aanbrak, werden steden met meer dan 100.000 inwoners als enorm beschouwd, en buiten Azië, waar de bevolkingsstatistieken twijfelachtig waren, bestonden er geen steden met meer dan een miljoen inwoners. De grootste stad in de Verenigde Staten in 1800 was Philadelphia, met een bevolking van 69.403. New York had slechts 60.489 inwoners. Baltimore was de op twee na grootste stad in Amerika met 26.114 inwoners.[^287] De meeste steden die later uitgroeiden tot de grote metropolen van Europa, hadden populaties die, volgens de maatstaven van de twintigste eeuw, zeer klein waren. Londen, met een bevolking van 864.845, was waarschijnlijk de grootste stad ter wereld. Parijs, met 547.756 inwoners, was de enige andere stad in Europa met meer dan een half miljoen inwoners in 1801.[^288] De bevolking van Lissabon bedroeg 350.000.[^289] Wenen telde 252.000 inwoners.[^290] Berlijn had in 1819 amper meer dan 200.000 inwoners.[^291] Madrid was de thuisbasis van 156.670 inwoners.[^292] De bevolking van Brussel in 1802 bedroeg 66.297. Boedapest had slechts 61.000 inwoners.[^293]

Er is een duidelijke neiging om te denken dat de groei van grote steden een directe functie is van bevolkingsgroei. Maar dat hoeft niet per se zo te zijn. Iedereen op aarde zou in Texas kunnen worden gepropt, met elk gezin dat in een vrijstaand huis met tuin woont, en toch zou er nog steeds ruimte overblijven in Texas. Zoals Adna Weber betoogde in de klassieke studie The Growth of Cities in the Nineteenth Century, verklaart bevolkingsgroei op zich niet waarom mensen in stedelijke omgevingen leven in plaats van verspreid over het platteland. In 1890 had Bengalen ongeveer dezelfde bevolkingsdichtheid als Engeland. Toch bestond de stedelijke bevolking in Bengalen uit slechts 4,8 procent, terwijl die in Engeland 61,7 procent bedroeg.[^294]

Historisch werden steden door muren gescheiden van het platteland om rovers en de lagere klassen buiten te houden. De groei van de industriële werkgelegenheid in de negentiende en twintigste eeuw leidde tot de opkomst van grote steden. Nu is de grote stad bijzonder kwetsbaar geworden voor instorting, nu het industrialisme afneemt. Een perfect voorbeeld van deze ontwikkeling is Detroit, de toonaangevende industriële stad van de midden twintigste eeuw. Ooit ging een aanzienlijk deel van de industriële productie van de wereld via Detroit. Nu is het een uitgehold omhulsel, geteisterd door criminaliteit en wanorde. In vele straten in het centrum van Detroit zijn één of meerdere vervallen gebouwen tot de grond afgebrand of gesloopt, wat de indruk wekt dat de stad een reeks aanvallen door bomwerpers uit de Tweede Wereldoorlog heeft doorstaan.

Detroit herinnert ons eraan dat veel industriële steden niet langer levensvatbaar zijn. Ze zullen instorten nu informatie en ideeën belangrijker worden als waarde-impacterende factoren dan het vervaardigen van goederen uit natuurlijke hulpbronnen. In veel gevallen is de grote stad al te omvangrijk geworden om zijn eigen gewicht te dragen. Om een metropool draaiende te houden, is het noodzakelijk dat een aanzienlijk aantal ondersteunende systemen op grote schaal effectief functioneert. De concentratie van miljoenen mensen brengt immers een enorme toename met zich mee in de kwetsbaarheid voor criminaliteit, sabotage en willekeurig geweld. Tijdens het industriële tijdperk werd de prijs voor het handhaven van de orde tegen deze risico’s terugverdiend door de schaalvoordelen in de productie.

In het informatietijdperk zullen alleen steden die hun onderhoudskosten compenseren door een hoge levenskwaliteit te bieden, levensvatbaar blijven. Mensen buiten de stad zullen niet langer verplicht zijn om deze te subsidiëren. Een goede indicator voor de levensvatbaarheid van een stad is of de bewoners in haar centrum rijker zijn dan die in de randwijken. Buenos Aires, Londen en Parijs blijven uitnodigende plaatsen om in te wonen en zaken te doen, lang nadat het laatste goede restaurant in South Bend, Louisville en Philadelphia zijn deuren sluit.

### Country states

Sommige stadsstaten kunnen uiteindelijk blijken slechts enclaves te zijn, zonder aangrenzende steden. Misschien zouden zij beter kunnen worden gezien als dorpsstaten of landstaten.

Ook zullen natuurlijke hulpbronnen op verschillende manieren gewaardeerd worden. Wanneer je overal zaken kunt doen, kies je er wellicht voor om je te vestigen op een mooie plek waar je diep kunt ademhalen zonder al te veel kankerverwekkende vervuiling in te ademen. Communicatietechnologieën die taalbarrières minimaliseren, zullen het steeds eenvoudiger maken om bijna overal te verblijven, mits de omgeving aantrekkelijk is. Dunbevolkte regio's met een gematigd klimaat en een ruime hoeveelheid vruchtbaar land per inwoner, zoals Nieuw-Zeeland en Argentinië, zullen eveneens een comparatief voordeel genieten omdat zij hoge standaarden in openbare gezondheid hanteren en lage productiekosten hebben voor voedingsmiddelen en hernieuwbare producten. Dergelijke producten zullen profiteren van een toegenomen vraag naarmate de levensstandaarden van miljarden mensen in Oost-Azië en Latijns-Amerika stijgen.

### Het inequivalentietheorema

Veel van de aannames die economen doen over gedrag zijn geworteld in de tirannie van de plaats. Een duidelijk voorbeeld is Ricardo’s ‘Equivalence Theorem’, die suggereert dat burgers in een land met enorme begrotingstekorten hun verwachtingen zullen aanpassen in afwachting van hogere belastingtarieven die in de toekomst nodig zijn om de schuld af te lossen. In die zin bestaat er een ‘equivalentie’ tussen het financieren van uitgaven via belastingheffing en via schulden. Tenminste, er bestond zo’n equivalentie in het begin van de negentiende eeuw, toen Ricardo schreef. In het informatietijdperk zal de rationele persoon daarentegen niet reageren op de vooruitzichten van hogere belastingen voor het financieren van tekorten door zijn spaarratio te verhogen; hij zal zijn woonplaats verplaatsen of zijn transacties elders uitvoeren. Om dezelfde reden als dat producenten leveranciers selecteren op zoek naar de laagste kosten, zullen zij des te sterker gemotiveerd zijn alternatieve leveranciers van bescherming te zoeken. De voordelen hiervan zullen de marges die behaald kunnen worden door over te schakelen op een nieuwe leverancier van plastic buizen ruimschoots overschaduwen. Het te verwachten resultaat is dat soevereine individuen en andere rationele mensen zullen vluchten voor rechtsgebieden met grote niet-gefinancierde verplichtingen.

Goedkope overheden, die weinig verplichtingen hebben en lage lasten voor hun klanten opleggen, zullen de voorkeurslocaties worden voor het creëren van welvaart in het informatietijdperk. Dit impliceert veel aantrekkelijkere vooruitzichten voor het zakendoen in gebieden waar de schuldenlast laag is en waar de overheden al zijn hervormd, zoals Nieuw-Zeeland, Argentinië, Chili, Peru, Singapore en andere delen van Azië en Latijns-Amerika. Deze gebieden zullen tevens superieure platformen vormen voor zakendoen vergeleken met niet-gereformeerde, dure economieën in Noord-Amerika en West-Europa.

### De afname van lokale prijsafwijkingen

Sterk gereduceerde informatiekosten zullen de meeste lokale prijsvoordelen tenietdoen. Kopers zullen namelijk niet alleen in staat zijn om een enorm aantal verkooppunten te doorzoeken op zoek naar de laagste prijzen voor verhandelbare goederen; ze zullen ook gebruik kunnen maken van externe diensten om over jurisdictiegrenzen heen te winkelen. Dit maakt het veel eenvoudiger voor mensen om de kenmerken van moeilijk te analyseren producten, zoals verzekeringen, te vergelijken. Bovendien omzeilt het beperkingen in de handel die worden opgelegd door lokale vergunningprocedures. Naar verwachting zullen de winstmarges dalen in elk gebied waar lokale prijsafwijkingen door extra informatie en concurrentie kunnen worden weggenomen.

## Nieuwe organisatorische imperatieven

De cybereconomie zal wezenlijk verschillen van de industriële economie in de manier waarop de deelnemers met elkaar omgaan. Informatietechnologie zal veel van de langetermijnorganisatorische voordelen van bedrijven, die ontstaan door hoge transactie- en informatiekosten, doen vervagen. Het informatietijdperk zal het tijdperk van de ‘virtuele onderneming’ zijn.

Veel analisten, die meer deskundig zijn op het gebied van informatietechnologie dan wij, hebben volstrekt niet ingezien dat deze technologie voorbestemd is om de logica van economische organisatie te transformeren. De nieuwe technologie overstijgt immers niet alleen grenzen en barrières, maar revolutioneert ook de ‘interne’ rekenkosten.

Zelfs de weinige bedrijven die door verbeteringen in informatie- en communicatietechnologie niet worden blootgesteld aan toegenomen concurrentie over landsgrenzen, zullen worden geconfronteerd met nieuwe organisatorische imperatieven. Razendsnel dalende informatie- en transactiekosten zullen de schaalvoordelen aanzienlijk verlagen, waardoor veel van de prikkels die in de industriële periode leidden tot grote, langdurige ondernemingen en loopbaangerichte werkgelegenheid, teniet worden gedaan.

### Waarom bedrijven?

De klassieke economen, zoals Adam Smith, waren vrijwel stil over de vraag naar de omvang van bedrijven. Ze gingen niet in op wat de optimale grootte van bedrijven bepaalt, waarom bedrijven de vorm aannemen die ze doen, of zelfs waarom bedrijven überhaupt bestaan. Waarom nemen ondernemers medewerkers in dienst in plaats van elke benodigde taak via een veiling onder onafhankelijke aannemers uit te besteden? De Nobelprijswinnende econoom Ronald Coase hielp een nieuwe richting in de economie op gang te brengen door enkele van deze belangrijke vragen te stellen. De antwoorden die hij hielp formuleren, wijzen op de revolutionaire gevolgen van informatietechnologie voor de structuur van bedrijven. Coase betoogde dat bedrijven een efficiënte manier waren om informatiegebreken en hoge transactiekosten te overwinnen.[^295]

### Informatie- en transactiekosten

Om te begrijpen waarom, bedenk de obstakels waarmee je geconfronteerd zou zijn als je een assemblagelijn uit het industriële tijdperk wilde laten draaien zonder dat één enkel bedrijf de activiteiten coördineert. In principe had een auto geproduceerd kunnen worden zonder dat de productie gecentraliseerd werd onder toezicht van één enkel bedrijf. Econoom Oliver Williamson is, samen met Coase, een andere pionier in het ontwikkelen van de theorie van het bedrijf. Williamson definieerde zes verschillende methoden van werking en controle. Hiervan is er de 'ondernemende modus', waarbij elk werkstation eigendom is van en wordt beheerd door een specialist.[^296] Een andere is wat Williamson de 'gefedereerde werkstations' noemt, waarbij een tussentijds product door iedere werknemer van fase naar fase wordt overgedragen.[^297] Er is geen fysieke reden waarom de duizenden werknemers niet vervangen hadden kunnen worden door een stel onafhankelijke aannemers, die elk ruimte huren op de fabrieksvloer, meedingen naar onderdelen en aanbieden de as te monteren of de spatborden op het chassis te lassen. Toch zul je tevergeefs zoeken naar een voorbeeld van een automobielfabriek uit het industriële tijdperk, georganiseerd en gerund door onafhankelijke aannemers.

### Coördinatieproblemen

Het exploiteren van een industriële faciliteit zonder de coördinatievoordelen van één enkel bedrijf zou het merendeel van de schaalvoordelen, die bij grootschalige exploitatie gerealiseerd zouden worden, hebben doen vervagen. Gigantische transactionele problemen bij het coördineren van een lappendeken van kleine bedrijven zouden in feite de werking van de assemblagelijn ongedaan hebben gemaakt. Om überhaupt te kunnen functioneren, zou een dergelijk systeem voortdurend onderhandelen tussen de individuele aannemers vereisen. In plaats van zich op de productie te richten, zouden de talloze aannemers of ondernemers hun tijd en aandacht hebben moeten besteden aan het vaststellen van de prijzen voor onderdelen en het uitwerken van de voorwaarden van hun constant wisselende interacties. Zelfs het louter bewaken van de productie zou een moeilijke opgave zijn geweest.

### De bevoegdheid om op te treden

Als zo'n verzameling onafhankelijke organisaties moeite had om een auto in elkaar te zetten, zou het ontwikkelen en herontwerpen van de modellen een regelrechte nachtmerrie zijn geweest. Je hoeft je alleen maar voor te stellen met welke moeilijkheden de ontwerper geconfronteerd zou worden wanneer hij de honderden onafhankelijke aannemers moet overtuigen van de veranderingen die nodig zijn om een nieuw model te introduceren. In de praktijk zou vrijwel unanieme instemming vereist zijn geweest. Wie ook maar terughoudend was of bezwaar maakte tegen enige wijziging in de productspecificatie, zou de modelverbetering effectief hebben kunnen tegenhouden of de kosten van de introductie hebben doen stijgen, waardoor de voordelen van grootschalige exploitatie nog verder in gevaar zouden komen.

### Onnodige onderhandelingen

Een assemblagelijn die door onafhankelijke aannemers wordt gehuurd (of afzonderlijk eigendom is) zou onderhevig zijn geweest aan talrijke kwetsbaarheden die worden vermeden wanneer binnen één enkel bedrijf wordt gewerkt. De dood, ziekte of het financiële falen van individuele aannemers zou té vaak voorkomen in ondernemingen waarbij de samenwerking van duizenden mensen nodig is om één product onder één dak te realiseren. De veilingmarkt zou deze aannemers ongetwijfeld hebben kunnen vervangen, maar elke opvolging zou een onderhandelde regeling hebben vereist, zoals de overname van de vorige exploitant door zijn vervanger. Daarbij zou ook een overeenkomst nodig zijn geweest voor het overnemen van de huur van de fabrieksruimte, en misschien een nieuw leasecontract voor de lasmachine of de pers die wordt gebruikt voor het stansen van de achterlichtkappen. Al deze zaken zouden bijzonder ingewikkeld zijn geweest.

### Incentive Traps

Een ander cruciaal probleem bij een lopende band van onafhankelijke opdrachtnemers onder de omstandigheden van het Industriële Tijdperk was dat de kapitaaleisen voor de individuele opdrachtnemers radicaal zouden verschillen. Een kunststof mal die nodig is om een dashboardschakelaar te produceren, zou bijvoorbeeld relatief goedkoop kunnen zijn, terwijl de apparatuur die nodig is om een motorblok te gieten of plaatwerk voor een spatbord uit te stansen, miljoenen zou hebben gekost. Het hoge grondstoffengehalte en het opeenvolgende karakter van assemblagelijnproductie maakten de problemen als gevolg van hoge kapitaalkosten onvermijdelijk, om de redenen die in het vorige hoofdstuk zijn geanalyseerd. Opdrachtnemers met kapitaalintensieve taken zouden in wezen afhankelijk zijn geweest van de medewerking van anderen om hun investeringen te amortiseren. Het vermogen van de opdrachtnemers met hogere kapitaaleisen om kapitaal op te halen en winstgevend te opereren, zou afhangen van het verkrijgen van de medewerking van vele andere deelnemers in het proces, van wie de kapitaalkosten ver veel lager waren. In veel gevallen zou die medewerking uitblijven.

Er zou een aanzienlijke prikkel zijn geweest voor de kleintjes om de groten te exploiteren. Degenen die minder geld nodig hadden om hun specifieke functie op de lopende band te vervullen, zouden hebben geprofiteerd door op cruciale momenten niet mee te werken. Net als stakende arbeiders konden zij de assemblagelijn op het een of andere voorwendsel stilleggen, waarbij zij zichzelf weinig kosten oplegden maar de partijen met grotere kapitaalinvesteringen veel ellende veroorzaakten. Het productieproces zou voortdurend onderhevig zijn geweest aan spelletjes, waarbij kleinschalige opdrachtnemers de partijen met hogere kapitaalkosten onder druk konden zetten door de productie te verstoren. De manoeuvres van de kleinere opdrachtnemers om van de groten zijwaartse betalingen af te dwingen, zouden de efficiëntie van het systeem hebben verminderd.

### The Firm Solution

Kortom, veel van de schaalvoordelen die tijdens het industriële tijdperk behaald hadden kunnen worden door op grote schaal een lopende band te exploiteren, zouden teniet zijn gedaan als de productie was verdeeld over een veelheid van individuele opdrachtnemers. Het enkele grote bedrijf bleek een efficiënte manier om deze nadelen te overwinnen, ondanks zijn andere beperkingen. Het grote bedrijfsleven was bureaucratisch. Maar in zekere mate waren bureaucratie en hiërarchie precies wat tijdens het Industriële Tijdperk nodig was. Administratieve en managementteams hielden de productie nauwgezet in de gaten en coördineerden deze, waarbij talloze middenmanagers bevelen naar beneden in de hiërarchie doorgaven en informatie weer omhoog in de bevelsketen terugvoerden. De ondernemingsbureaucratie verzorgde tevens de boekhoudkundige controles en minimaliseerde de principaal-agentproblemen, waarbij werknemers niet altijd in het beste belang van het bedrijf handelden. Het voeren van een geavanceerde boekhouding onder de omstandigheden van het Industriële Tijdperk vereiste het werk van veel mensen. Het inrichten van zo'n administratieve bureaucratie was kostbaar en moest betaald worden, ongeacht of de productie actief draaide of stil lag. Omdat deze bestuurders over cruciale kennis beschikten die noodzakelijk was voor de bedrijfsvoering, werden zij doorgaans tegen een premie betaald, bovenop wat hun vaardigheden op de vrije markt waard zouden zijn geweest.

### Organisatorische speling

Het grote aantal professionele managers en bestuurders had ook het nadeel dat zij de neiging hadden het bedrijf voor hun eigen belang te 'kapen' in plaats van voor de aandeelhouders. Het was in het industriële tijdperk niet ongebruikelijk om bedrijven aan te treffen die royaal uitgaven deden aan kantoormeubilair, clublidmaatschappen en andere extraatjes waarvan het management kon profiteren, maar die wellicht geen direct rendement voor de investeerders opleverden. In een complexe onderneming was het van buitenaf vaak onmogelijk om gemakkelijk vast te stellen welke overheaduitgaven essentieel waren en welke louter verzuchtingen waren voor de werknemers. Daarnaast was het moeilijk te voorkomen dat een soms aanzienlijk deel van de bedrijfsarbeiders hun werkzaamheden verwaarloosde. Het feit dat het technologisch gezien lastig was om de prestaties te monitoren, maakte een omvangrijk middenkader noodzakelijk en maakte het tegelijkertijd moeilijk ditzelfde middenkader te controleren. Al deze omstandigheden droegen bij aan wat bekend kwam te staan als 'organisatorische speling', een term die in 1963 werd bedacht door Richard Cyert en James March in *A Behavioral Theory of the Firm*.[^298] Uit zorgvuldig onderzoek bleek dat talrijke bedrijven hun potentiële prestaties aanzienlijk niet haalden.

> 'Of je nu resultaten behaalt of niet, het salaris blijft hetzelfde.
> 
> 'Of je nu hard werkt of niet, het salaris blijft hetzelfde.
> 
> 'Of je nu om je werk geeft of niet, het salaris blijft hetzelfde.'[^299] – Chris Dray

### Dat is niet mijn taak

Als entiteit die streeft naar continuïteit kampte het grote industriële bedrijf met het reeds beschreven nadeel dat het vatbaar was voor afpersing door vakbonden. Het deelde bovendien enkele kenmerken van bureaucratie, zoals die in overheidskantoren in nog overdreven mate werden aangetroffen. Opdrachten stroomden van bovenaf. Taken werden gestandaardiseerd en strikt opgedeeld in compartimenten. Deze taken werden vaak rigide gedefinieerd. Er ontstonden duidelijke grenzen tussen functiecategorieën, vergelijkbaar met die die werden gehandhaafd door de kartels die de geleerde beroepen reguleerden. Het was in het industriële tijdperk voor velen net zo vreemd te verwachten dat een boekhouder een doorgebrande gloeilamp in een lamp op zijn bureau zou vervangen als dat men een advocaat inschakelde om de griep te verhelpen. Van de werknemers werd noch verwacht, noch werd het in veel gevallen zelfs toegestaan, om de strikt afgebakende grenzen tussen de verschillende functies te overschrijden.

"dat is niet mijn taak" was een veel gehoorde slogan die de "organisatorische loomheid" van het industriële tijdperk onderstreepte. Ieders taak was nauwkeurig afgebakend in termen van gestandaardiseerde taken, waarvan afwijken niet was toegestaan, hoe de productiviteit ook verbeterd zou kunnen worden. Elk medewerker in de bedrijfsbureaucratie werd aangenomen op basis van 'kwalificaties' die geacht werden de prestaties in zijn specifieke functie te voorspellen. Met weinig uitzonderingen werd iedereen betaald op basis van een functieclassificatie, met min of meer uniforme beloning door de hele organisatie. Omdat specifieke prestaties in de administratieve hiërarchieën van het grote bedrijfsleven – net als in staatsbureaucratieën – vaak niet werden gemeten, verliep het werk in een rustig tempo. Dus, hoewel het bedrijf de schaalvoordelen van massaproductie wel wist te benutten, ging dit ten koste van andere inefficiënties.

> In een markt doe je niets simpelweg omdat iemand het je opdraagt of omdat het op pagina dertig van het strategisch plan staat. Een markt kent geen taakgrenzen. . . . Er zijn geen bevelen, geen vertaling van signalen van bovenaf, niemand die het werk in porties verdeelt. In een markt heb je klanten, en de relatie tussen een leverancier en een klant is fundamenteel niet-organisatorisch, omdat die plaatsvindt tussen twee onafhankelijke entiteiten.[^300] William Bridges

### Nieuwe imperatieven

De nieuwe megapolitieke omstandigheden van het informatietijdperk zullen de logica van de bedrijfsorganisatie aanzienlijk veranderen. Een deel hiervan is duidelijk. Als informatietechnologie verder niets doet, verlaagt het dramatisch de kosten voor het verwerken, berekenen en analyseren van informatie. Een effect van deze technologie is dat de noodzaak om grote aantallen middenmanagers in te huren om productieprocessen te bewaken, afneemt. In veel gevallen vervangen geautomatiseerde werktuigmachines, mogelijk gemaakt door geavanceerde rekenkracht, werknemers op uurloon. En waar het productieproces nog steeds door mensen bemand wordt, is het controle- en coördinatieproces grotendeels geautomatiseerd. Apparatuur uitgerust met microprocessors kan de voortgang van de lopende band veel effectiever volgen dan managers ooit konden. Niet alleen kan de nieuwe apparatuur de snelheid en nauwkeurigheid waarmee mensen werken meten, maar het kan ook automatisch de administratie opmaken en onderdelen opnieuw bestellen zodra deze uit de voorraad worden gehaald. De kleinste ondernemingen kunnen zich nu financiële beheersystemen veroorloven die hun financiën met grotere snelheid en verfijning bijhouden dan zelfs de grootste bedrijven via hun productiehiërarchieën enkele decennia geleden hadden kunnen bereiken.

Het feit dat informatietechnologie de verspreide, niet-sequentiële productie van goederen met een verminderd gebruik van natuurlijke hulpbronnen mogelijk maakt, verlaagt de kwetsbaarheid voor manipulatie en afpersing drastisch, zoals we al eerder hebben besproken. Dit zijn echter niet de enige kenmerken van informatietechnologie die het steeds aantrekkelijker maken om functies, die voorheen door werknemers werden vervuld, uit te besteden. De kapitaalkosten zijn lager. Productcycli zijn korter. De zelfstandige opdrachtnemers zelf, waaronder eenmanszaken, beschikken over veel geavanceerdere informatienetwerken tot hun beschikking. Spoedig zullen zij kunnen vertrouwen op een scala aan digitale bedienden om een breed scala aan kantoorfuncties uit te voeren, van het beantwoorden van de telefoon tot aan secretariaatsdiensten. Digitale bedienden zullen secretarissen, reclameagenten, reisagenten, bankbedienden en bureaucraten zijn.

### Het verdwijnen van goede banen

Naarmate steeds meer individuen, die in staat zijn om aanzienlijke economische waarde te creëren, het grootste deel van die waarde voor zichzelf zullen behouden, zal de dynamiek op de arbeidsmarkt fundamenteel veranderen. Ondersteunend personeel, dat voorheen een groot deel van de omzet opslokte die werd gegenereerd door de belangrijkste inkomstenbronnen van een onderneming, zal worden vervangen door goedkope geautomatiseerde agenten en informatiesystemen. Dit betekent dat een organisatie haar dienstverlening van de hoogste kwaliteit beter kan garanderen door deze uit te besteden, in plaats van de functie binnen het bedrijf te behouden, waar het relatief moeilijker zal zijn om mensen terecht te belonen voor het goed uitvoeren van hun taken. Een virtueel bedrijf zal de meeste ‘organisatie-overbodigheden’ elimineren door de organisatie zelf af te schaffen.

‘Goede banen’ behoren tot het verleden. Een ‘goede baan’, zoals de Princeton-econoom Orly Ashenfelter verwoordde, is een baan die meer betaalt dan je waard bent.[^301] In het industriële tijdperk bestonden er veel ‘goede banen’ vanwege de hoge informatie- en transactiekosten. Bedrijven groeiden en internaliseerden een breder scala aan functies omdat dit hen in staat stelde schaalvoordelen te benutten. Ook werd de opblussing van bedrijfsstructuren gesubsidieerd door belastingwetten. De hoge belastingen die in de late fase van het industriële tijdperk de overhand hadden, vergrootten op kunstmatige wijze de voordelen van het vormen van een langdurig bedrijf en het in dienst nemen van vaste werknemers. In de meeste landen verhoogden belastingwetten en -regelgeving aanzienlijk de kosten voor het oprichten en ontbinden van bedrijven op projectbasis. Bovendien dwongen zij ondernemers er vaak toe om zelfstandige contractanten als werknemers in te nemen. Juridische ingrepen drukten daarnaast tijdelijk de schaarste aan ‘goede banen’ op, doordat het kostbaar en moeilijk werd gemaakt om een werknemer te ontslaan, hoe gering ook zijn bijdrage aan de productiviteit van het bedrijf.

Onvermijdelijk en logisch garandeerde het karakter van bedrijfsorganisatie in het industriële tijdperk dat de meest hooggekwalificeerde en getalenteerde mensen—die een onevenredig groot aandeel van de toegevoegde waarde in een organisatie creëerden—proportioneel minder werden beloond dan hun bijdrage waard was. Dit zal veranderen in het informatietijdperk.

De microprocesrevolutie zorgt voor een scherpe toename in de beschikbaarheid van informatie en verlaagt de transactiekosten. Dit leidt tot de decentralisatie van het bedrijf. In plaats van een permanente bureaucratie zullen activiteiten rondom projecten worden georganiseerd, vergelijkbaar met de werkwijze van filmmaatschappijen. De meeste voorheen ‘interne’ functies van het bedrijf zullen worden uitbesteed aan zelfstandige contractanten. De werknemers uit het industriële tijdperk, die ‘goede banen’ hadden maar weinig bijdroegen en vertrouwden op collega’s om hun tekortkomingen op te vangen, zullen zich spoedig in de positie bevinden om te bieden op contracten op de spotmarkt. Ook vele loyale en ijverige werknemers zullen dat overkomen. ‘Goede banen’ zullen een anachronisme zijn, omdat banen in het algemeen anachronistisch zullen worden.

Bij de grootste Japanse bedrijven verwachtte men dat werknemers een baan voor het leven zouden hebben. Zelfs wanneer zij geen productieve taak te vervullen hadden, bleven zij in dienst – soms simpelweg door op te dagen en plaats te nemen achter een kaal bureau in een hoek van een fabriek. Zelfs in Japan wordt de opgeblazen kantoormedewerkerspopulatie nu teruggeschaald. De kop van een artikel in de International Herald-Tribune vertelde het verhaal: "Afscheid nemen is zo bitter: Japans baan-voor-het-levencultuur loopt pijnlijk ten einde."[^302]

In de postindustriële periode zullen banen taken zijn die je uitvoert, in plaats van iets wat je simpelweg "hebt." Vóór het industriële tijdperk was vaste tewerkstelling vrijwel onbekend. Zoals William Bridges het verwoordde: "Vóór 1800 – en in veel gevallen zelfs lang daarna – verwees *job* altijd naar een specifieke taak of onderneming, nooit naar een rol of positie binnen een organisatie. ... Tussen 1700 en 1890 vindt de Oxford English Dictionary talloze toepassingen van termen als *job-coachman, job-doctor en job-gardener* – allen verwijzend naar mensen die op een eenmalige basis werden aangenomen. Jobwork (een andere veelgebruikte term) betrof incidenteel werk, niet reguliere tewerkstelling."[^303] In het informatietijdperk zullen de meeste taken, die voorheen binnen bedrijven werden georganiseerd om informatie- en transactiekosten te verlagen, terugkeren naar de spotmarkt. 'Just in time'-voorraadbeheer en outsourcing zijn beide mogelijk geworden dankzij informatietechnologie. Zij vormen stappen in de richting van het verdwijnen van banen. Reeds hebben grote ondernemingen zoals AT&T alle vaste functiecategorieën afgeschaft – de posities in dat bedrijf zijn nu tijdelijk en op voorwaardelijke basis. In de woorden van Bridges: "Werkgelegenheid wordt weer tijdelijk en situationeel, en categorieën verliezen hun grenzen."[^304] In de nieuwe cybereconomie zullen 'zelfstandige contractanten' over continenten heen op afstand werken en zich verzamelen op het informatietijdperk-equivalent van de lopende band.

### Hollywood neemt het over

De ideale bedrijfsorganisatie in de nieuwe informatie-economie zou een filmproductiemaatschappij kunnen zijn. Dergelijke ondernemingen kunnen zeer verfijnd zijn, met budgetten van honderden miljoenen dollars. Al zijn het vaak grote operaties, van aard zijn ze tijdelijk. Een filmmaatschappij die een film produceert voor 100 miljoen dollar kan zich een jaar lang vormen en daarna weer ontbinden. Hoewel de mensen die aan de productie werken getalenteerd zijn, verwachten zij niet dat werk vinden aan een project gelijkstaat aan het hebben van een vaste baan. Wanneer het project voorbij is, gaan de lichttechnici, cameramensen, geluidsingenieurs en kledingspecialisten elk hun eigen weg. Zij kunnen in een volgend project weer samenkomen, of juist niet.

Naarmate de schaalvoordelen afnemen en de kapitaaleisen voor vele informatie-intensieve activiteiten tegelijkertijd dalen, ontstaat er een sterke prikkel voor bedrijven om op te heffen. Bedrijfsactiviteiten zullen meer ad hoc en tijdelijk worden, en ondernemingen zullen over het algemeen korter bestaan. Virtuele bedrijven die talenten samenbrengen voor specifieke doeleinden zullen efficiënter zijn dan al lang bestaande bedrijven. Naarmate encryptie wijdverspreid raakt en de belasting op kapitaal door concurrentie wordt verlaagd, zullen kunstmatige schaalvoordelen – die het voortbestaan van "vaste" bedrijven ondersteunen – verdwijnen. Dit zal gebeuren, ongeacht of de belastingen snel of langzaam worden verlaagd. Worden ze snel verlaagd, verdwijnen de kunstmatige kosten van werken op projectbasis sneller; wordt dit langzaam gedaan, dan rust de voornaamste last van het betalen van de anachronistisch hoge belastingen op de bestaande ondernemingen, terwijl nieuwe bedrijven als virtuele organisaties opereren en daardoor beter in staat zijn de kostbare lasten te ontvluchten die door de stervende natiestaat worden opgelegd.

Hoewel speciale vaardigheden en talenten belangrijker zullen worden dan ooit in de informatie-economie, zullen de meeste kunstmatige grenzen tussen beroepen vervagen. Geavanceerde technologieën voor het opslaan en opvragen van informatie maken de bedrijfsgeheimen en gespecialiseerde informatie van beroepen zoals recht, geneeskunde en accountancy voor iedereen toegankelijk. De economische waarde van memorisatie als vaardigheid zal afnemen, terwijl het belang van synthese en het creatief toepassen van informatie zal toenemen.

De volledige implicaties van deze verandering zullen worden vertraagd door verouderde regelgeving. Maar op de lange termijn zal de macht van overheden om de cybereconomie te reguleren afbrokkelen tot een verwaarloosbaar niveau. Elke kunstmatige regulering van professionele monopolen die de kosten verhoogt zonder voordelen te bieden die door de markt worden gewaardeerd, zal uiteindelijk genegeerd worden.

Er zijn nog andere implicaties van de verschuiving naar een informatie-economie:

- Lokale regelgeving die hogere kosten oplegt, zal worden omgevormd tot een marktconforme basis.
- Er zal een intensere concurrentie ontstaan tussen rechtsgebieden om economische activiteiten met hoge toegevoegde waarde aan te trekken die in principe overal gevestigd zouden kunnen worden. Geen enkele vestigingsplaats is per definitie aantrekkelijker dan een andere.
- Zakelijke relaties zullen neigen naar het vertrouwen op "circles of trust." Door encryptie, die individuen in staat stelt om onopgemerkt te stelen, zal eerlijkheid een meer gewaardeerde eigenschap van zakenpartners worden.
- Patent- en auteursrechtregelingen zullen veranderen als gevolg van de gemakkelijke toegang tot bepaalde informatie.
- Bescherming zal steeds meer technologisch worden in plaats van juridisch. De lagere lagen zullen buitengesloten worden. De verschuiving naar afgesloten woonwijken is nagenoeg onvermijdelijk. Het buitensluiten van onruststokers is een effectieve én traditionele manier om crimineel geweld te minimaliseren in tijden van zwakke centrale autoriteit.
- Bulkgoederen zullen zwaar belast worden en lokaal verzonden worden, zoals in de middeleeuwen, terwijl luxe goederen licht belast worden en over grote afstanden worden verscheept.[^305]
- Politiefuncties zullen steeds vaker worden overgenomen door particuliere bewakers die verbonden zijn aan koopmansverenigingen.
- Er kan een tijdelijke voorsprong zijn voor particuliere bedrijven ten opzichte van beursgenoteerde ondernemingen, omdat particuliere bedrijven meer speelruimte zullen hebben om overheidskosten te ontkomen.
- Een "baan voor het leven" zal verdwijnen, omdat banen steeds meer taken of "stukloonwerk" worden in plaats van posities binnen een organisatie.
- De controle over economische hulpbronnen zal verschuiven van de staat naar mensen met superieure vaardigheden en intelligentie, aangezien het steeds gemakkelijker wordt om rijkdom te creëren door kennis toe te voegen aan producten.
- Veel hoogopgeleide professionals zullen worden verdrongen door interactieve systemen voor informatieopvraging.
- Nieuwe overlevingsstrategieën voor personen met een lagere intelligentie zullen zich ontwikkelen, waarbij meer nadruk komt te liggen op de ontwikkeling van vrijetijdsvaardigheden, sportcompetenties en het plegen van criminaliteit, alsook op het bieden van diensten aan de groeiende aantallen soevereine individuen, naarmate de inkomensongelijkheid binnen rechtsgebieden toeneemt.

Politieke systemen die zijn ontstaan in een tijd waarin geweld steeds winstgevender werd, moeten ingrijpende aanpassingen ondergaan. Nu efficiëntie steeds belangrijker wordt ten opzichte van de omvang van de macht die een systeem bezit, zullen kleine, efficiënte soevereine staten, die hun klanten meer bescherming bieden tegen lagere kosten, steeds levensvatbaarder worden.

Net als in de middeleeuwse periode doen zich opnieuw toenemende nadelen van schaalvergroting voor in de organisatie van geweld. Dit blijkt al uit het groeiende aantal soevereiniteiten sinds de val van het communisme. Wij verwachten dat het aantal soevereiniteiten in de wereld zich snel zal vermenigvuldigen naarmate de logica van het informatietijdperk door de praktijk wordt bevestigd.

Macht zal wederom op kleine schaal worden uitgeoefend. Enclaves en provincies zouden zelfs aanzienlijke voordelen kunnen hebben ten opzichte van landen die zich over continenten uitstrekken, wanneer zij concurrerende voorwaarden bieden aan hun 'klanten' voor soevereiniteitsdiensten. Dit zal heel anders zijn dan in de snel ten onder gaande moderne periode, waarin geen enkele entiteit kon overleven, tenzij zij in staat was een militaire macht te beheersen die voldoende was om een koninkrijk te controleren. Vroeger, toen nadelen van schaalvergroting in de uitoefening van macht de norm waren, beheersten degenen die het meest profiteerden van de bescherming – zoals de welgestelde kooplieden in de laatmiddeleeuwse stadstaten – de regering. Naar onze mening is er weer ruimte voor iets dergelijks. Het verlagen van roofzuchtige lasten en een efficiëntere inzet van middelen zouden moeten leiden tot een snelle groei in gebieden waar klanten daadwerkelijk de controle uitoefenen over de lokale soevereiniteiten.

Zoals we hierna zullen onderzoeken, zal de vraag of deze ontwikkelingen ondanks de tegenstand van legioenen verliezers kunnen of zouden moeten doorgaan, behoren tot de belangrijkere controverses van het informatietijdperk.

[^270]: Benjamin Schwarz, '~American Inequality: Its History and Scary Future,' New York Times, 19 december 1995, p. A25.

[^271]: Adna Ferrin Weber, The Growth of Cities in the Nineteenth Century (New York: Macmillan, 1899; herdrukt door Cornell University Press, 1963), p.249.

[^272]: Bill Bryson, The Lost Continent (New York: Harper Perennial, 1989), p.72.

[^273]: Dit artikel is herdrukt in vol. 4 van Adrian Darnell's verzameling Early Mathematical Economists, 6 delen (London: Pickering & Chatto, 1991).

[^274]: Bijvoorbeeld, zie Weber, op. cit., p.2.

[^275]: Clive Jenkins en Barrie Sherman, The Collapse of Work (London: Methuen, 1979), p. 103.

[^276]: Robert H. Frank en Philip J. Cook, The Winner-Take-All Societv (New York: The Free Press, 1995).

[^277]: Clay Chandler, 'Buchanans succes schrikt het bedrijfsleven af', *Washington Post*, 22 februari 1996, p. D12.

[^278]: Stephanie Flanders en Martin Wolfe, "Haunted by the Trade Spectre," *Financial Times*, 24 juli 1995, p. 11. Zij citeren uit het meest recente wereldontwikkelingsrapport van de Wereldbank over werknemers in een zich integrerende wereldeconomie.

[^279]: Zie Mancur Olson, "Diseconomies of scale and development," *Cato Journal*, vol. 7, nr. 1 (lente/zomer 1987).

[^280]: Ibid.

[^281]: Basil Davidson, *The Black Mans' Burden: Africa and the Curse of the Nation State* (New York: Times Books, 1992), p. 290.

[^282]: Olson, op. cit.

[^283]: Adam Smith, The Wealth of Nations, p.724. Dit punt werd gesuggereerd door een argument van Edwin G. West in zijn Adam Smith and Modern Economics (Aldershot, Engeland: Edward Elgar Publishing, 1990), pp.88-89.

[^284]: Fritz Rorig, The Medieval Town (Berkeley: University of California Press, 1967), p.28.

[^285]: Albert 0. Hirschman, Exit, Voice, and Loyalty (Cambridge: Harvard University Press, 1969), p.81.

[^286]: Tom Peters en George Gilder, 'City vs. country: Tom Peters & George Gilder debat over de impact van technologie op locatie,' Forbes, februari 1995.

[^287]: Weber, op. cit., p.21.

[^288]: Ibid., p.46 voor Londen, p.73 voor Parijs.

[^289]: Ibid., p.120.

[^290]: Ibid., p.95.

[^291]: Ibid., p.84.

[^292]: Ibid., p.119.

[^293]: Ibid., p.101.

[^294]: Ibid., p.5.

[^295]: Zie Ronald Coase, *The Nature of the Firm*, herdrukt in Louis Putterman en Randall S. Kroszner, red., *The Economic Nature of the Firm: A Reader* 2e editie (Cambridge: Cambridge University Press, 1996), pp.89-104.

[^296]: Geciteerd door West, op. cit., p.58; zie ook Oliver E. Williamson, *The Organization of Work: A Comparative Insititutional Assessment*, Journal of Economic Behaviour and Organisation, vol. 1, nr. 1.

[^297]: Geciteerd door West, op. cit., p. 59; zie ook Williamson, op. cit.

[^298]: Richard Cyert en James March, A Behavioral Theory of the Firm (Englewood Cliffs, N.J.: Prentice-Hall, 1983).

[^299]: Chris Dray~ 'Civil servants lead lives of quiet collusion,' Globe and Mail, 2 februari 1996, p. A14.

[^300]: William Bridges, Jobsh ft: How to Prosper in a Workplace Without Jobs (Reading, Mass.: Addison-Wesley, 1994), pp. 62, 64.

[^301]: Zie Al Ehrbar, 'Re-engineering geeft bedrijven nieuwe efficiëntie, werknemers de ontslagbrief,' Wall Street Journal, 22 juli 1992, p. A14, geciteerd door Bridges, op. cit., p. 39.

[^302]: Sheryl WuDunn, 'Parting Is Such Sour Sorrow: Japan's Job-for-Life Culture Painfully Expires,' International Herald Tribune, 13 juni 1996, p.13.

[^303]: Bridges, op. cit., pp.31-32.

[^304]: Ibid., p.58.

[^305]: Abu-Lughod, op. cit., p.186.

::: {.content-visible when-format=latex}

\setsubtitle{}

:::