# De schemering van de democratie

> 'Democratische politieke systemen zijn in historische termen een recent fenomeen. Ze hadden een korte bestaansperiode in Griekenland en Rome, waarna ze in de 18e eeuw weer opkwamen, minder dan 200 jaar geleden. ... Een cyclus van afwijzing is nu mogelijk opnieuw begonnen.'[^430] - William Pfaff

Het is geen geheim dat de democratie in de geschiedenis van regeringen relatief zeldzaam en vluchtig is geweest. In die tijden – zowel in de oudheid als in de moderne tijd – waarin de democratie de overhand had, was haar succes afhankelijk van megapolitieke omstandigheden die de militaire macht en het belang van de massa's versterkten. Historicus Carroll Quigley onderzocht deze kenmerken in Weapons Systems and Political Stability.[^431]

Hiervoor behoren:

1. **Goedkope en wijdverspreide wapens**. De democratie bloeit doorgaans op wanneer de kosten voor het aanschaffen van nuttige wapens laag zijn.

2. **Wapens die effectief door amateurs gebruikt kunnen worden**. De kans op democratie is groter wanneer iedereen effectieve wapens kan gebruiken zonder langdurige training.

3. **Een militair voordeel voor een groot aantal infanteristen in de strijd**. Zoals Quigley opmerkt: '[P]erioden waarin de infanterie domineerde, waren perioden waarin de politieke macht ruimer werd verspreid binnen de gemeenschap en waarin de democratie een betere kans had om te zegevieren.'[^432]

Dit is geenszins een allesomvattende catalogus van de voorwaarden waaronder democratie kan bestaan. Als dat wel zo was, zou de democratie aan het einde van de twintigste eeuw niet als een triomfantelijk systeem zijn doorgebroken. Wapens waren in de schemering van het industriële tijdperk waarschijnlijk duurder dan ooit tevoren. En veel van de meest effectieve wapens vereisten ongetwijfeld specialisten om ze daadwerkelijk effectief in te zetten. Bovendien heeft de Golfoorlog tussen de Verenigde Staten, hun bondgenoten en Irak aangetoond hoe kwetsbaar grote contingenten infanterie zijn, zelfs wanneer zij zich bevinden in loopgraven en diep ingegraven verdedigingswerken. Dus waarom lijkt de democratie te gedijen onder deze omstandigheden nu de twintigste eeuw ten einde loopt?

## Democratie, de broederlijke tweeling van het communisme?

In hoofdstuk 5 hebben we een paradoxale verklaring gegeven, namelijk dat de democratie als broederlijke tweeling van het communisme floreerde juist omdat zij een onbelemmerde controle van middelen door de staat mogelijk maakte. Deze conclusie kan belachelijk lijken voor het 'gezond verstand' van het industriële tijdperk. We ontkennen niet dat binnen de voorwaarden van de industriële samenleving democratische systemen en het communisme bittere tegenpolen waren. Maar bekeken vanuit een megapolitiek perspectief, zoals zij waarschijnlijker worden gezien vanuit het oogpunt van het informatietijdperk, hadden de twee systemen meer gemeen dan je zou vermoeden.

Onder omstandigheden waarin wapens grotesk duur waren, werd de democratie het besluitvormingsmechanisme dat de controle over de middelen door de staat maximaliseerde. Net als het staatssocialisme zorgden democratische systemen voor enorme bedragen om een massale militaire vestiging te financieren. Het verschil was dat de democratische verzorgingsstaat nog meer middelen in handen van de staat legde dan de staatssocialistische systemen konden; dat zegt wel wat, want de staatssocialistische of communistische systemen claimden praktisch elk bezit dat de moeite waard was.

Objectief gezien als louter een mechanisme om middelen te verzamelen, bleek de democratische staat superieur te zijn aan het staatssocialisme als middel om de staat te verrijken. Zoals we eerder uitlegden, stelde de democratie de militairen aanzienlijk meer geld beschikbaar omdat deze verenigbaar was met particulier eigendom en kapitalistische productiviteit.

Het staatssocialistische systeem was gebaseerd op de doctrine dat de staat alles bezat. De democratische verzorgingsstaat daarentegen legde aanvankelijk slechts beperkte aanspraken vast. Ze deed alsof particulier eigendom was toegestaan – zij het in een voorwaardelijke vorm – en wist daarmee de betere prikkels te benutten om de productie te stimuleren. In plaats van vanaf het begin alles verkeerd te beheren, stelden democratische regeringen in het Westen individuen in staat eigendom te bezitten en vermogen op te bouwen. Pas nadat het vermogen was gecreëerd, grepen de democratische natiestaten in om er een Large fractie van te belasten.

Het woord "Large" moet met een hoofdletter worden geschreven. Bijvoorbeeld, in 1996 bedroeg het levenslange federale belastingtarief in de Verenigde Staten 73 cent per dollar. Voor eigenaren van ondernemingen, die hun inkomen via dividenden ontvingen, was het tarief 83 cent per dollar. En voor iedereen die geld wilde nalaten of aan kleinkinderen wilde geven, bedroeg het federale belastingtarief 93 cent per dollar. Wanneer ook staats- en lokale belastingen in overweging worden genomen, confisqueert de democratische overheid op alle niveaus het grootste deel van elke verdiende dollar in de Verenigde Staten. Roofdierachtige belastingtarieven maakten van de democratische staat een de facto partner met een aandeel van drie-kwarten tot negen-tenths in alle inkomsten. Dit was zeker niet hetzelfde als staatssocialisme, maar het was er nauw mee verwant.

De democratische staat overleefde langer omdat zij flexibeler was en prodigieuze hoeveelheden middelen verzamelde vergeleken met wat beschikbaar was in Moskou of Oost-Berlijn.

Inefficiëntie, waar het telde

Wij hebben de megapolitieke voordelen van democratie als besluitregel voor een machtige regering omschreven als ‘inefficiëntie, waar het telde.’ Vergeleken met het communisme bleek de verzorgingsstaat immers een veel efficiënter systeem te zijn. Maar in vergelijking met een echte laissez‑faire-enclave als Hongkong was de verzorgingsstaat inefficiënt. De groeicijfers in Hongkong waren fantastisch, maar hun superioriteit sloeg juist op in het feit dat de inwoners van Hongkong, en niet de overheid, in staat waren om 85 procent van de voordelen van een snellere groei voor zichzelf te behouden.

Hongkong is natuurlijk geen democratie. Integendeel, het is een mentaal model van het soort rechtsgebied waarvan we verwachten dat het zal floreren in het informatietijdperk. In het industriële tijdperk had Hongkong immers geen behoefte aan democratie, omdat het gespaard bleef van de onaangename noodzaak om middelen te vergaren voor de ondersteuning van een formidabele militaire macht. Hongkong werd van buitenaf verdedigd, waardoor het zich een werkelijk vrije economie kon veroorloven.

Juist het vermogen om middelen te vergaren maakte de democratie tijdens de megapolitieke omstandigheden van het industriële tijdperk superieur. Massademocratie ging hand in hand met industrialisme. Zoals Alvin Toffler heeft gesteld, is massademocratie ‘de politieke uitdrukking van massaproductie, massadistributie, massaconsumptie, massaal onderwijs, massamedia, massavermaak en al het overige.’[^433]

Nu informatietechnologie de massaproductie verdringt, is het logisch te verwachten dat het tijdperk van massademocratie ten einde loopt. Het cruciale megapolitieke imperatief dat massademocratie tijdens het industriële tijdperk deed triomferen, is verdwenen. Het is daarom slechts een kwestie van tijd voordat de massademocratie hetzelfde lot ondergaat als haar broederlijke tweeling, het communisme.

Massademocratie onverenigbaar met het informatietijdperk

Een moment van overdenking toont aan dat de technologie van het informatietijdperk op zichzelf geen massatechnologie is. In militaire zin, zoals al aangegeven, opent het de mogelijkheid voor 'slimme wapens' en 'informatieoorlog', waarbij 'logische bommen' gecentraliseerde commando- en controlesystemen zouden kunnen saboteren. Niet alleen wijst informatietechnologie duidelijk op de perfectie van wapens die door specialisten worden bediend; het vermindert ook de beslissendheid van oorlogvoering, waardoor de relatieve positie van de verdediging verbetert. Microtechnologie maakt dramatische verhogingen in de militaire macht van individuen mogelijk, terwijl het belang van geconcentreerde infanterieformaties afneemt. Zoals de Rand Corporation aan de minister van Defensie rapporteerde: 'Onderling verbonden netwerken kunnen worden aangevallen en verstoord, niet alleen door staten, maar ook door niet-statelijke actoren, waaronder verspreide groepen en zelfs individuen.'[^434] Bovendien impliceert dit dat cyberoorlog de inherente diseconomieën van massaal gecentraliseerde systemen ten uitvoer zal leggen.

In de woorden van de Rand-experts: 'Informatiegebaseerde technieken maken geografische afstand irrelevant; doelwitten in de continentale Verenigde Staten zijn net zo kwetsbaar als agenten in het operationele gebied.'[^435] Waar het vroeger als veilig werd beschouwd om binnen de grenzen van grote supermachtstaten zoals de Verenigde Staten te verblijven, kan in het informatietijdperk de logica van machtsconcentratie omgekeerd worden. Peoria mag ver verwijderd zijn van een mogelijk militair front, maar het zal niet langer veilig zijn tegen cyberaanvallen van vrijwel elke potentiële tegenstander. Wonen binnen de grenzen van een supermacht betekent dat je jezelf in het vizier plaatst. In plaats van te federeren, kunnen lokale gemeenschappen zichzelf beter beveiligen door te decentraliseren. De opkomst van cyberoorlog zal de kwetsbaarheid van gecentraliseerde commando- en controlesystemen vergroten, terwijl de competitieve levensvatbaarheid van verspreide systemen toeneemt.

De feedbackmechanismen die hierdoor worden gestimuleerd, kunnen het proces van decentralisatie verder versnellen. Zoals de Rand-experts suggereren, zal de overheid, om de kwetsbaarheid voor cyberaanvallen van de commando- en controlesystemen die zich in de latere stadia van de natiestaat hebben ontwikkeld te verminderen, genoodzaakt zijn 'de exploitatie van nieuwe softwareversleutelingstechnieken' te intensiveren. Dit zal deze, grotendeels privésector-systemen, veel minder vatbaar maken voor sabotage, terwijl het de commerciële verspreiding van sterke encryptie versnelt, wat hen zal helpen zich los te maken van staatsdominantie. Ook dit zal de decentralisatie stimuleren. Zoals eerder betoogd, zal het bovendien de spreiding van middelen in cyberspace verder bevorderen, waar ze buiten het bereik van de politiek zullen liggen.

Uiteindelijk betekent dit het einde van massademocratie, vooral in haar overheersende vorm van representatief wanbestuur, hetzij van het congres- of parlementaire type.

## De megapolitiek van misvertegenwoordiging

Wanneer de megapolitieke omstandigheden ingrijpend veranderen, zoals nu het geval is, verandert ook de organisatie van de overheid onvermijdelijk. Sterker nog, de vorm van de representatieve overheid is van oudsher een afspiegeling van de verdeling van ruwe macht. Dit blijkt uit het feit dat vertegenwoordigers op geografische basis worden gekozen in plaats van op een andere manier.

Bedenk eens: in principe zou een wetgevend orgaan net zo democratisch zijn als haar leden worden gekozen volgens een willekeurige verdeling van de bevolking. Parlementswijken of kiesdistricten zouden gebaseerd kunnen worden op verjaardagen of zelfs op alfabetische indelingen. Iedereen die op 1 januari geboren is, zou uit één kandidatenlijst kunnen stemmen. Degenen die op 2 januari geboren zijn, uit een andere lijst. Of elke persoon wiens naam begint met “Aa” tot “Af” zou uit één kandidatenlijst kunnen kiezen. Degenen wiens naam begint met “Ag” zouden uit een andere lijst kiezen. En zo verder.

Zo’n systeem bestaat tegenwoordig om verschillende redenen niet. Een eerste en voldoende reden is dat het in de achttiende eeuw technologisch onhaalbaar was. Maar nog belangrijker is dat kiesdistricten gebaseerd op verjaardagen of alfabetische indelingen de verdeling van ruwe macht, zoals die bij verkiezingen tot uiting moest komen, niet hadden kunnen weerspiegelen of zelfs benaderen. Personen die niet meer gemeen hadden dan eenzelfde verjaardag of de eerste paar letters van hun naam, zouden uiterst moeilijk te organiseren zijn in een samenhangende machtsbasis.

### Waarom wegen geografische indelingen zwaarder?

De stemming is in feite ontstaan als vervanging voor een militaire strijd. En zo is het nog steeds het geval, zij het op een verhulde wijze. Dergelijke conflicten kunnen langs geografische lijnen worden georganiseerd, en minder vaak op basis van verwantschap of religie. Ze kunnen niet worden georganiseerd op basis van verjaardagen of de eerste letters van namen. Ook kunnen ze niet effectief worden georganiseerd op basis van beroepen, tenzij deze beperkt zijn tot erfelijke gilden – zoals de kasten in India – of zich lokaal clusteren, zoals boeren in Iowa.

Het hele idee achter de huidige representatieformules is dat zij belangen vertegenwoordigen die geografisch geworteld zijn, in plaats van langs een andere dimensie. Historisch gezien was het beheersen van grondgebied de sleutel tot militair succes. Alle militaire dreigingen zijn lokaal ontstaan. Representatieve systemen zijn erop gericht een andere arena te bieden voor de uitdrukking van die macht. Het feit dat zij onvermijdelijk de neiging hebben lokale gevestigde belangen te bevoordelen, is een gevolg van de representatieformule. Geografische kiesdistricten zorgen ervoor dat vertegenwoordigers gunsten gaan toekennen aan specifieke groepen, ten koste van de gemeenschappelijke belangen die alle inwoners van een land delen.

### Nieuwe mogelijkheden in het verschiet

Zoals analyses door Public Choice-economen hebben aangetoond, hebben schijnbaar kleine verschuivingen in de wijze waarop een verkiezing is gestructureerd, of in de manier waarop de stemming wordt geteld, grote en voorspelbare gevolgen voor de uitkomst.[^436] Dit is de reden waarom serieuze politicastudenten tegenwoordig ook serieuze studenten van grondwetten moeten zijn. En het is een van de overwegingen die ons ertoe hebben geleid verder te kijken dan grondwetten, naar de ultieme metagrondwet, zoals bepaald door de overheersende megapolitieke factoren in een bepaalde omgeving.

Technologische veranderingen hebben al enkele van de fundamenten weggevaagd die ervoor zorgden dat de stemming beperkt bleef tot geografische kiesdistricten. Toen moderne representatieve systemen in de achttiende en negentiende eeuw ontstonden, was bijna alle communicatie lokaal. De meeste mensen leefden en stierven binnen enkele mijlen van hun geboorteplaats, en al hun handelsactiviteiten en communicatie vonden lokaal plaats. Tegenwoordig is er onmiddellijke communicatie wereldwijd. Je kunt vrijwel even gemakkelijk zaken doen met iemand die vijfduizend mijl ver weg is als met een buurman. In toenemende mate overstijgt de economie geografische beperkingen. De samenleving is veel mobieler.

En zo geldt dat ook voor rijkdom in het informatietijdperk. In tegenstelling tot een staalfabriek kan een computerprogramma niet eenvoudig als gijzelaar worden gehouden door het lokale politieke proces. Een staalfabriek kan nauwelijks worden verplaatst wanneer wetgevers besluiten het te belasten of de eigenaars ervan te reguleren. Een computerprogramma kan via een modem met lichtsnelheid overal ter wereld worden overgedragen. De eigenaar kan zijn laptop inpakken en wegvliegen. Ook dit ondermijnt de megapolitieke fundamenten van geografische kiesdistricten.

Een belangrijk probleem dat alle representatieve democratische systemen volgens onze analyse delen, is dat hun geografische kiesdistricten inherent de gevestigde belangen van ondernemingen uit het industrieel tijdperk oververtegenwoordigen. De 'losers' of 'achterblijvers' zijn ideale kiezers, geografisch geconcentreerd en politiek behoeftig. De geschiedenis van de industriële democratie bevestigt dit. 'Winnaars' uit nieuwe industrieën waren structureel ondervertegenwoordigd in de wetgevende beraadslagingen, zelfs tijdens de hoogtijdagen van het industriële tijdperk in de jaren dertig.[^437] De neiging van politici om de bestaande, gevestigde concurrenten te vertegenwoordigen – en niet de nieuwe ondernemingen die zouden kunnen ontstaan of de potentiële klanten van die ondernemingen – is waarschijnlijk een inherent kenmerk van het representatieve bestuur. Zoals Mancur Olson betoogde in The Rise and Decline of Nations, hebben langlevende industrieën de neiging effectievere 'distributieve coalities' te vormen om te lobbyen en te strijden om de politieke buit.[^438]

Dit probleem wordt onmeetbaar vergroot in de economie van het informatietijdperk. De creatievere deelnemers aan de nieuwe economie zijn geografisch verspreid. Zij zullen daarom waarschijnlijk nooit een voldoende geconcentreerde groep vormen om de aandacht van wetgevers te trekken, zoals zalmvissers in Schotland of tarweboeren in Saskatchewan dat doen. Inderdaad, veel van de dynamische persoonlijkheden van de nieuwe economie zullen waarschijnlijk geen burgers zijn van zelfs de meest alomvattende jurisdictie. Zij hebben dus nauwelijks 'stem' in de wetgevende beraadslagingen van representatieve democratieën. Als treffend voorbeeld kunnen de dubieuze pogingen van Amerikaanse wiskunde‐PhD’s worden genoemd om buitenlandse wiskundigen te beletten banen in de Verenigde Staten te bemachtigen.[^439] Hun xenofobische betogen aan het Congres om werkgevers te blokkeren bij het aannemen op basis van verdienste, zullen allang worden opgevolgd. De verouderde geografische vertegenwoordiging die uit het industrieel tijdperk is blijven hangen, schenkt geen aandacht aan buitenlandse wiskundigen of andere cruciale bijdragers aan welvaart die geen kiezers zijn.

'Waarom geloven mensen in de legitimiteit van democratische instituties? Het beantwoorden van die vraag is bijna net zo moeilijk als uitleggen waarom mensen in bepaalde religieuze dogma's geloven, want zoals bij religieuze overtuigingen varieert het niveau van begrip, scepsis en geloof sterk binnen de samenleving en in de loop der tijd.'[^440] JUAN J. LINZ

Weinigen zijn op een gecoördineerde wijze gaan nadenken over de gevolgen van technologische veranderingen die het industrialisme ondermijnen en inkomensverdelingen drastisch wijzigen. Het is duidelijk dat de democratie waarschijnlijk niet veel meer zal zijn dan een recept voor wettelijk parasitisme als de inkomens zo ver uiteen lopen als zij in de informatie-economie kunnen doen. Nog weiniger hebben de impliciete onverenigbaarheid opgemerkt tussen enkele instituties van de industriële overheid en de megapolitiek van de postindustriële samenleving. Of deze tegenstellingen nu expliciet worden erkend of niet, hun gevolgen zullen echter steeds duidelijker worden naarmate voorbeelden van politiek falen zich wereldwijd opstapelen. Overheidsinstellingen die in de moderne periode zijn ontstaan, weerspiegelen de megapolitieke omstandigheden van één of meer eeuwen geleden. Zij hebben de overgang van een agrarische samenleving naar stedelijk industrialisme overleefd. Maar het informatietijdperk kan nieuwe representatiemechanismen vereisen om chronische disfunctie en zelfs een ineenstorting in Sovjetstijl te voorkomen.

U kunt verwachten dat in veel landen crises van slecht bestuur zullen opspelen, nu politieke beloften leeg blijken te zijn en regeringen hun krediet en institutionele steun kwijtraken. Uiteindelijk zullen nieuwe institutionele vormen moeten ontstaan die in staat zijn de vrijheid in de nieuwe technologische omstandigheden te waarborgen en tegelijkertijd uitdrukking te geven aan de gemeenschappelijke belangen die individuen delen.

Dit alles wijst op het einde van de massademocratie zoals we die in de twintigste eeuw kenden. De vraag is: wat zal haar plaats innemen? Als het enige alternatief voor massademocratie een dictatuur zou zijn waarin het individu geen zeggenschap heeft over zijn eigen lot, dan zou men wellicht in de verleiding komen zich bij de neo-Luddieten ‘opstand tegen de toekomst’ aan te sluiten.

### Nieuwe instellingen

Gelukkig is dictatuur echter niet het enige alternatief voor massademocratie. Informatietechnologie maakt keuze mogelijk. In plaats van een collectieve keuze binnen de beperkende context van ‘massaproductie, massaconsumptie, massaal onderwijs, massamedia, massaal vermaak en al het andere’ zal informatietechnologie een echte consumentgerichte keuze faciliteren voor op maat gemaakte soevereiniteitsdiensten. Dat wordt mogelijk omdat het opereren op massale schaal niet langer noodzakelijk zal zijn. Wij zijn ervan overtuigd dat de technologie van het informatietijdperk zal leiden tot nieuwe vormen van bestuur – net zoals de agrarische revolutie en later het industriële tijdperk hun eigen specifieke vormen van sociale organisatie voortbrachten.

Wat zouden zulke nieuwe instellingen kunnen zijn? Om dat te begrijpen, vergeet alles wat u leest in verkeerd benoemde politicologieteksten. De nieuwe bestuursinstellingen voor het informatietijdperk zullen de grenzen van conventioneel denken overschrijden. De vooruitgang richting dergelijke instellingen is al begonnen. Het gaat om nauwelijks erkende improvisaties gericht op het herstructureren van onderbenutte activa, namelijk de voordelen van soevereiniteit. De natiestaten van de wereld, bezorgd om de afscheidingsbewegingen en de krachtige krachten van devolutie, hebben zich verenigd tot het sterkste grensvaststellende kartel dat zij in stand kunnen houden. Hoewel het aantal nieuwe staten in de wereld in de jaren negentig is toegenomen, gebeurde dit vooral in twee clusters, dankzij de ineenstorting van multietnische communistische dictaturen in de voormalige Sovjet-Unie en Joegoslavië. Het is opmerkelijk dat andere toonaangevende natiestaten, waaronder de Verenigde Staten, manoeuvreerden om de Sovjet-Unie zo lang mogelijk in stand te houden. En weinig regeringen waren te spreken over de ontbinding van Joegoslavië. De onafhankelijkheid van de voormalige Joegoslavische republieken werd pas erkend nadat afscheiders met hun eigen militaire inspanningen de controle hadden overgenomen. De leidende machten schikten zich in het zien van ongewapende of slecht bewapende separatisten, die door hun Servische onderdrukkers werden afgeslacht. Zelfs het verre China, een machtige natiestaat zonder direct belang bij het behoud van het restje Joegoslavië, verzette zich krachtig tegen de pogingen tot zelfbeschikking voor de onderdrukte etnische Albanezen in Kosovo. Ironisch genoeg zal deze obsessie met het vaststellen van grenzen eerder de weg bepalen naar een versplinterde soevereiniteit dan dat zij de devolutie daadwerkelijk zal voorkomen. De felle weerstand van kwetsbare natiestaten over de hele wereld tegen open afscheiding en politieke desintegratie maakt erkende soevereiniteit tot een waardevolle vorm van transcendent kapitaal dat de staten die het bezitten vrijwillig kunnen fragmenteren en onderverhuren.

Een voorbeeld van hoe soevereiniteit vrijwillig kan worden gefragmenteerd om in wezen een particuliere, belastingvrije jurisdictie te creëren, is de Agulhas Bay Concession Free Zone, die vijftig vierkante kilometer van het eiland Principe voor de kust van West-Afrika beslaat. Hoewel het grondgebied binnen de grenzen van de Democratische Republiek São Tomé en Principe blijft, is de administratie van de zone geprivatiseerd. Het bestuur daar wordt geregeld volgens een contract, beheerd door WADCO, de West African Development Corporation Ltd., een particulier bedrijf dat in Zuid-Afrika is opgericht. De voertaal in de zone is niet het officiële Portugees van São Tomé en Principe, maar Engels. De valuta die wordt gehanteerd is niet het lokale monopoliegeld van São Tomé, maar de dollar – het wereldgeld, de Amerikaanse dollar. De veiligheid wordt niet gewaarborgd door de politie van de Democratische Republiek São Tomé en Principe, maar door private politiediensten die door WADCO in dienst zijn genomen. Het commerciële recht van São Tomé is niet van toepassing op de handel binnen de zone en de rechtbanken van São Tomé hebben geen rechtsmacht. Alle geschillen dienen te worden opgelost via transnationale arbitrage, conform de Parijse ICC-regels. Met een paar strikt geregelde en triviale uitzonderingen zijn de belastingen van São Tomé niet van toepassing binnen de zone en bestaan officiële monopolies daar ook niet. Telecommunicatie, bijvoorbeeld, wordt automatisch gedereguleerd binnen de zone. Onder voorbehoud van de betaling van huur en naleving van de overige concessievoorwaarden heeft WADCO het recht om haar huurcontract op de private, gefragmenteerde soevereiniteit automatisch en herhaaldelijk voor vijftig jaar te verlengen, gerekend vanaf de eerste verlengingsdatum in 2047.

Wat WADCO in São Tomé en Principe bereikt heeft, kan en zal in vele verschillende rechtsgebieden door anderen worden nagebootst. Een van de ware pioniers van de ontwikkeling in de eenentwintigste eeuw, Joaquin Aguirre, heeft in de Centrale Aguirre Portuaria in oostelijk Bolivia een vergelijkbare zone van private soevereiniteit gecreëerd. Aguirre, multimiljonair, romanschrijver en uitvinder, medeoprichter van de Verenigde Naties en voormalig senator van de Boliviaanse Republiek, is in vele opzichten een pionier. Een halve eeuw nadat hij heeft meegeholpen bij de oprichting van de Verenigde Naties, is Aguirre nu een prototype van het soevereine individu van de eenentwintigste eeuw. Zijn Zona Franca, die vrij is van de meeste Boliviaanse belastingen, heffingen en regelgevende beperkingen, wijst de weg naar de nieuwe vorm van geprivatiseerde stadstaten die steeds meer door succesvolle individuen in het informatietijdperk gerealiseerd zullen worden. Het toont ook onomstotelijk aan dat het leven van de massa’s, zo vaak bezongen door de apologeten van een grote overheid, drastisch verbeterd kan worden door de economische ontwikkeling die wordt gestimuleerd door vrijhandelszones zoals die gelanceerd door Señor Aguirre. In de loop der tijd zal het aantal de facto stadsstaten in de wereld aanzienlijk toenemen. Inderdaad, als je als individu voldoende financiële onafhankelijkheid bereikt, zul je in staat zijn ultieme onafhankelijkheid te bereiken, net als Joaquin Aguirre. Mocht het geval zich voordoen dat een gefragmenteerde, gecommercialiseerde soevereiniteit van een ander je geen comfortabele thuisbasis biedt, dan kun je je eigen ministaat opzetten, zo onafhankelijk als elk hertogdom uit de middeleeuwen. In plaats van te touwtrekken met demagogen en politieke opportunisten om te voorkomen dat je bezittingen worden weggeharkt en verdeeld onder de vele kravende handen van de massademocratie, zul je in staat zijn je eigen particuliere domein van bestuur te vestigen.

De dramatische faseovergang van massademocratie naar de ultieme vorm van zelfbestuur – het soevereine individu – hoeft niet te vergezeld te gaan van een radicale verschuiving in de publieke opinie, noch van een miraculeuze stemming waarbij ontgoochelde kiezers massademocratie afschaffen. Een dergelijke revolutie kan immers al onzichtbaar zijn begonnen met de verhuur van soeverein grondgebied voor gebruik als belastingvrije zones, “Zona Francas”, en vrije havens. Uiteindelijk zal soevereiniteit herhaaldelijk gefragmenteerd worden, totdat deze zo volledig onderverdeeld is dat verdere opsplitsing niet leidt tot een waarde die voldoende is om de transactiekosten van de devolutie te compenseren. Gezien de wet van Moore en Gilder’s corollarium, volgens welke de bandbreedte elk jaar verdrievoudigt, is er op dit moment geen reden om te verwachten dat de trend van devolutie vroegtijdig zal eindigen. Integendeel, we voorzien dat de ogenschijnlijk solide macht van de natiestaten die momenteel aanspraak maken op massademocratie, zal uiteenvallen in tienduizenden fragmenten, in een systeem dat meer doet denken aan de middeleeuwen dan aan het moderne industriële tijdperk.

Op termijn zullen zelfs natiestaten die nog restanten van de massademocratie behouden, een significante beleidsverschuiving ondergaan om aan te sluiten bij de nieuwe metaconstitutionele realiteiten. Zoals William Keech, een trouwe voorstander van democratie, betoogt in *Economic Politics: The Costs of Democracy*:[^441] ‘Mensen leren te willen wat ze zien dat ze kunnen krijgen, maar ze kunnen ook van gedachten veranderen als ze merken dat ze niet houden van wat ze wilden en wat ze kregen.’ Met andere woorden, het feit dat massademocratie met conventionele instituties van een representatieve regering overal wordt geprezen nu de twintigste eeuw ten einde loopt, zou een ‘verkoopsignaal’ kunnen zijn. Dit garandeert geenszins dat dergelijke besluitvormingsregels de tand des tijds zullen doorstaan, zelfs niet volgens hun eigen criteria. Bedenk dat, wanneer je buiten de politieke sfeer kijkt, er nauwelijks bewijs is dat bestuurders, beheerders, coaches of andere professionele leiders democratisch worden gekozen. Integendeel, de meest succesvolle leiders worden routinematig aangesteld door eigenaars via selectieprocessen, waarbij degenen met het grootste belang een ongelijke en onevenredig grote stem hebben bij het bepalen van de uitkomst. Als democratische selectie werkelijk een universele methode zou zijn om capabele leiders te identificeren, zou je verwachten dat dit bijna uitsluitend in de politieke sfeer plaatsvindt. Kortom, het is op basis van de huidige gegevens aannemelijker te veronderstellen dat de levering van soevereiniteitsdiensten wordt belemmerd door de dominantie van democratische besluitvorming, dan dat bedrijfs- en handelsorganisaties lijden doordat zij worden geleid door door eigenaars aangestelde bestuurders in plaats van door een stemming.

Tegen de helft van de eenentwintigste eeuw is het waarschijnlijk dat de proliferatie van particuliere jurisdicties gebaseerd op gefragmenteerde soevereiniteit onomstotelijk de voordelen van particuliere administratie zal aantonen. Kiezers zullen inzien dat zij lijden onder de last van massademocratie. Daarom zullen zij, zoals Professor Keech suggereert, tot de conclusie komen dat de voordelen van werknemerscontrole over de overheid niet opwegen tegen de kosten. Zij zullen de overstap maken naar hervorming. Zelfs kieskringen in Europa en Noord-Amerika, die momenteel schijnbaar fel tegen hervorming zijn, zouden uiteindelijk kunnen stemmen om hun regio’s meer open te stellen voor particuliere bestuursvormen. Meerderheden zullen mogelijk vrijwillig, ja zelfs graag, de schijnvertoning van de politiek opgeven ten gunste van een particuliere bestuursvorm van de overheid, die er werkelijk op gericht is de optimale voorwaarden te scheppen voor het sluiten en afdwingen van contracten.

Voor zover de overheid, met haar vertrouwde toebehoren, nog blijft bestaan, kan zij op geheel nieuwe manieren geïnformeerd worden. Ergens, in een bepaald rechtsgebied, nog voor de eindtijd, zal iemand het potentieel van computertechnologie inzien dat het mogelijk maakt een werkelijk representatieve overheid tot stand te brengen. Het vermeende probleem van buitensporige campagne-uitgaven en de onmiskenbare irritatie van chronische politieke campagnevoering zou in een oogwenk opgelost kunnen worden. In plaats van verkozen te worden, zouden vertegenwoordigers volledig willekeurig door trekking geselecteerd kunnen worden, met een hoge statistische waarschijnlijkheid dat hun talenten en zienswijzen overeenkomen met die van de algemene bevolking.

Dit zou slechts een moderne versie zijn van het oude Griekse systeem van selectie door loting. Zoals E. S. Staveley beschrijft in zijn gezaghebbende geschiedenis *Greek and Roman Voting and Elections*, werden talrijke functies in Athene — van de magistraten tot de archons — door middel van trekking geselecteerd als vervanging van verkiezingen.[^442] Dit werd op een slimme wijze bereikt, ondanks mechanische beperkingen bij het willekeurig maken van kansen, door het gebruik van een toewijzingsmachine, 'of, zoals deze door de Atheners werd genoemd, de cleroterion.'

Een reeks zwart-witte bonen werd gebruikt als willekeurige tellers om te bepalen wie geselecteerd zou worden om diverse ambten te bekleden, evenals 'om de volgorde te bepalen waarin de tribale afdelingen in de Raad aan de beurt zouden komen als prytaneis.'[^443] De klassieke herkomst van dit idee kan het een extra mate van geloofwaardigheid geven. Maar de voornaamste aantrekkingskracht ervan is juist dat het de nadelen van zelfselectie in de politiek zou vermijden. Het zou er statistisch voor zorgen dat minder advocaten en egomaniakken de publieke aangelegenheden domineren.

Wetgevende lichamen zouden kunnen worden samengesteld uit ware vertegenwoordigers. Aangezien zij niet bijeen zouden worden gebracht door het najagen van macht, en in elk geval een verwaarloosbare kans zouden hebben om opnieuw door trekking geselecteerd te worden, zouden zij vrij zijn om de staatszaken te regelen en beleid te formuleren op basis van een rationele analyse van de kwesties.

### Rechtstreekse commissie

Tegenwoordig hebben politici, die er alles aan doen om stemmen te winnen, weinig motivatie om problemen op een samenhangende manier te analyseren. Het is derhalve nauwelijks verrassend dat hun staat van dienst in het daadwerkelijk oplossen van problemen zo armzalig is vergeleken met die van ondernemers, bedrijfsleiders en sportcoaches, die naar prestaties beloond worden. Een beloningssysteem op basis van prestaties voor wetgevers zou niemand, die op willekeurige wijze gekozen wordt, net zo effectief maken als Lee Kuan Yew. Maar er is alle reden te geloven dat de prestaties sterk zouden verbeteren als het salaris van de wetgevers gekoppeld zou worden aan een objectieve maatstaf, zoals de groei van het inkomen per hoofd van de bevolking na belastingen. Beloon hen op basis van prestaties, en de kans dat zij goed presteren, zal duizendmaal toenemen.

De winst voor de samenleving uit beleid dat het reële inkomen na belastingen verhoogt, kan enorm zijn. Waarom zouden premier en presidenten niet zelfs een klein deel van die winst ontvangen? De financiering voor dergelijke betalingen zou verkregen kunnen worden middels een kleine, onopvallende belasting. Zo'n regeling zou de samenleving bevrijden van de bedreiging waarmee zij momenteel geconfronteerd wordt door ambitieuze mannen met specialistisch politiek talent, zoals Richard Nixon en Bill Clinton.

> 'Ze brachten hem goud, zilver en kleding; maar de "Christus" deelde al deze zaken uit aan de armen. Wanneer er geschenken werden aangeboden, wierpen hij en zijn vrouwelijke metgezel zich op de knieën en spraken zij gebeden uit; maar zodra hij weer overeind kwam, beval hij de menigte hem te aanbidden. Later organiseerde hij een gewapende bende, die hij door het platteland leidde, reizigers op de loer liggend en beroofde hen onderweg. Ook hier was zijn ambitie niet om rijk te worden, maar om aanbeden te worden. Hij verdeelde de hele buit onder hen die niets hadden – waaronder, naar men aanneemt, ook zijn eigen volgelingen.' [^444] NORMAN COHN

### Messiaanse persoonlijkheden

Er is te weinig aandacht besteed aan het feit dat verkiezingspolitiek wanordelijke, messiaanse persoonlijkheden in machtsposities lokt. Dergelijke personen hebben bestaan en vormden vaak een serieuze bedreiging voor de sociale orde, zelfs in agrarische samenlevingen voordat democratische politieke systemen ontstonden. Wanneer men de loopbanen bekijkt van Eudo de Stell, de Bretonse Christus, Adelbert in de achtste eeuw, Eon in de elfde eeuw, Tanchelm uit Antwerpen, Melchior Hoffman en Bernt Rothmann en soortgenoten, vallen een aantal aspecten op. Hoe duidelijker hun politieke talenten leken, des te groter de schade die zij leken te hebben aangericht. Omdat de staat zich nog niet bezighield met het organiseren van grootschalige, systematische dwang, namen deze vroege protopolitici vaak het initiatief om te plunderen en te beroven om zo contant geld te verkrijgen, dat zij vervolgens onder hun volgelingen – de armen – konden verdelen.

### Protopolitici in actie

De verhalen over hun capriolen wekken de indruk van talenten die hun tijd ver achter zich hebben gelaten, alsof je leest over mannen van zeven voet die over een veld rennen, lang voordat basketbal werd uitgevonden. Tegenwoordig verdienen de ongewoon lange mannen, dankzij de NBA, miljoenen met dribbelen en dunkelen. Als basketbal zou verdwijnen, zouden zij weer verdwijnen in de kieren van de samenleving, waarschijnlijk vooral als circusacts en in bijvoorstellingen.

Demagogen, in de tijd voordat de politiek bestond, lieten zich aantrekken door de dichtstbijzijnde benadering van politiek die de agrarische wereld kon bieden: rondtrekkende prediking. Zij preekten tot menigten en beloofden, net als politici, op welbespraakte wijze een beter leven aan degenen die hen zouden volgen. Zowel toen als nu waren de armen het voornaamste doelwit van demagogen. Norman Cohns grootse geschiedenis van millenaristische bewegingen, *The Pursuit of the Millennium*, beschrijft de loopbanen van talrijke messiaanse leiders in een tijd nog vóór de invoering van verkiezingen. In zijn beschrijvingen valt het op hoe sterk hun persoonlijkheidstype overeenkomt met dat van de charismatische moderne politicus.

> De leider heeft – net als farao's en vele andere 'goddelijke koningen' – alle eigenschappen van een ideale vader: hij is volmaakt wijs, hij is volmaakt rechtvaardig, hij beschermt de zwakken. Maar aan de andere kant is hij ook de zoon wiens taak het is de wereld te transformeren, de Messias die een nieuw hemelrijk en een nieuwe aarde zal stichten en die over zichzelf kan zeggen: 'Zie, ik maak alle dingen nieuw!' Zowel als vader als als zoon is deze figuur kolossaal, bovenmenselijk, almachtig. Er wordt hem een overvloed aan bovennatuurlijke krachten toegekend, waardoor men hem zich voorstelt als licht dat in stralen naar buiten stroomt. Bovendien, doordat hij zo vervuld is van deze goddelijke geest, beschikt de eschatologische leider over unieke wonderkrachten. Zijn legers zullen steevast en triomfantelijk zegevieren, zijn aanwezigheid zal de aarde vruchtbaar maken en zijn heerschappij zal een tijdperk van zo perfecte harmonie zijn als de oude, corrupte wereld nog nooit gekend heeft.

> Deze voorstelling was natuurlijk puur fantastisch, in de zin dat zij geen betrekking had op de werkelijke aard en bekwaamheid van enig menselijk wezen dat ooit heeft bestaan of ooit zou kunnen bestaan. Het was desalniettemin een beeld dat op een levend mens geprojecteerd kon worden; er waren altijd mannen die meer dan bereid waren zo'n projectie te accepteren, die in feite hartstochtelijk verlangden om gezien te worden als onfeilbare, wonderwerkende redders. En het geheim van de opmars die zij uitoefenden lag nooit in hun geboorte, noch in hoge mate in hun opleiding, maar altijd in hun persoonlijkheden. Hedendaagse verslagen van deze messiaanse figuren van de armen benadrukken doorgaans hun welbespraaktheid, hun indrukwekkende uitstraling en hun persoonlijke magnetisme. Bovengenoemd krijgt men de indruk dat, zelfs als sommige van deze mannen zich bewust voordeden als bedriegers, de meesten zichzelf werkelijk beschouwden als geïncarneerde goden. En deze volledige overtuiging werkte zich gemakkelijk uit naar de menigten waarvan het diepste verlangen juist uitging naar een eschatologische redder. [^445]

Hoewel deze passage op bewonderenswaardige wijze beknopt de vermeende millenaristische redders beschrijft die de middeleeuwse samenleving zo vaak verstoorden, kan zij de volledige lading van Cohns magisteriale overzicht niet overbrengen. Men kan het hele werk niet lezen zonder in de capriolen van deze profeten de bekende kenmerken van de moderne demagoog te herkennen: de welbespraaktheid, het 'persoonlijke magnetisme', de 'messiaanse pretenties' en het terugkerende verlangen om als vertegenwoordiger van de armen aanbeden te worden.

Het voornaamste verschil dat men opmerkt tussen de wijze waarop de middeleeuwse samenleving met deze bedriegers omging en de behandeling die de democratie aan het eind van de twintigste eeuw hen verleent, is dat zulke personen in de middeleeuwen doorgaans werden geëxecuteerd, terwijl de moderne democratische politiek aan het eind van de twintigste eeuw een open kanaal biedt waardoor zij op legitieme wijze de macht in de natiestaat kunnen grijpen.

Een systeem dat routinematig de controle over de grootste, meest dodelijke ondernemingen ter wereld toevertrouwt aan de winnaar van populariteitswedstrijden tussen charismatische demagogen, zal hier op den duur onvermijdelijk de gevolgen van ondervinden.

### Betaal leiders om goed werk te leveren

Zoals hierboven gesuggereerd, zou het eenvoudig zijn om een superieure methode vast te stellen voor het veiligstellen van getalenteerd leiderschap binnen een organisatie: door hen aan te stellen. Dit is de methode die het meest breed en succesvol wordt toegepast in concurrerende economieën. 

Een rationeel selectieproces, gecombineerd met een constructieve prikkelstructuur om positief leiderschap te belonen, zou bekwame mensen aan het roer van de overheid brengen. Het zou ook nieuwe soorten talent mobiliseren, die anders gewoonlijk weinig interesse zouden tonen in de problemen van bestuur.

De meest getalenteerde topfunctionarissen ter wereld zouden bereid zijn om wanpresterende regeringen te leiden als zij betaald konden worden op basis van de resultaten die zij daadwerkelijk voor de samenleving bewerkstelligen. 

Een leider die het reële inkomen in elk vooraanstaand Westers land aanzienlijk zou kunnen verhogen, zou terecht veel meer betaald mogen worden dan Michael Eisner. In een betere wereld zou elke succesvolle regeringsleider multimiljonair zijn.

### Elektronische plebiscieten

Een andere voor de hand liggende alternatieve oplossing voor representatief wanbestuur zou elektronische plebiscieten kunnen zijn, waarbij burgers – mogelijk een representatieve fractie geselecteerd via een manipulatiebestendige loting – hun stem direct uitbrengen over wetgevende voorstellen. Computertechnologie maakt het mogelijk om beslissingen democratisch vast te stellen via elektronische plebiscieten. Plebiscieten kunnen eenvoudig worden gecombineerd met een toewijzingssysteem om het aantal stemmers per specifiek vraagstuk te beperken. Hoe dan ook, in principe is het veel minder een uitdaging voor potentiële kiezers om politieke kwesties te begrijpen dan om te proberen politici te doorgronden en hun beoordelingen van dezelfde kwesties te evalueren, om nog maar te zwijgen van het daadwerkelijk weten wat die politici zouden doen zodra zij aan de macht komen. Dit wordt des te ingewikkelder doordat politici en hun medewerkers steeds bedrevener worden in het verpakken en manipuleren van de beelden die zij aan het publiek presenteren.

## Gecommercialiseerde soevereiniteit

Wij verwachten dat er iets nieuws zal ontstaan dat de politiek vervangt. Hoewel elk van de bovengenoemde mogelijkheden met enig voordeel kan worden geprobeerd, is onze verwachting niet dat de politiek hervormd of verbeterd zal worden, maar dat zij verouderd raakt en in de meeste opzichten wordt verlaten. Hiermee bedoelen wij niet dat wij een dictatuur verwachten, maar eerder een ondernemende overheid – de commercialisering van soevereiniteit.

In tegenstelling tot dictatuur, of zelfs democratie, zal gecommercialiseerde soevereiniteit de keuzevrijheid niet uitsluiten. Zij zal ieder individu meer ruimte bieden om zijn opvattingen te uiten. En voor degenen die het talent hebben om hiervan te profiteren, zal gecommercialiseerde soevereiniteit een praktischere ruimte bieden voor besluitvorming en zelfbepaling dan welke vorm van sociale organisatie die tot nu toe heeft bestaan.

### Op maat gemaakte overheid

Opdat dit niet millenarieus klinkt, bedenk dat microtechnologie zaken miniaturiseert en uit elkaar haalt. Het maakt maatwerk mogelijk in plaats van massaproductie. U kunt nu een winkel bezoeken en een spijkerbroek kopen die uit een op uw maten aangepast patroon wordt gesneden en halverwege de wereld genaaid. Wanneer nieuwe instituties eindelijk evolueren om te voldoen aan de nieuwe megapolitieke realiteiten van het informatietijdperk, zult u een bestuur kunnen verkrijgen dat minstens net zo goed is afgestemd op uw persoonlijke behoeften en smaken als spijkerbroeken.

Alvin Toffler, van alle mensen, heeft kritiek geuit op het idee dat informatietechnologie burgers tot klanten zou kunnen maken. Toffler stelt, wat volgens ons onterecht is, 'Dat is een veel te beperkt model. Of we het nu willen of niet, er is een wereld van religie en gevoel die niet eenvoudigweg kan worden gereduceerd tot contractuele relaties.'[^446] Om redenen die we eerder hebben besproken, zijn we het ermee eens dat het moeilijk zal zijn om 'de wereld van nationalistisch gevoel' te reduceren tot 'contractuele relaties.' Maar dat te zeggen betekent niet dat we beweren dat het onmogelijk is, laat staan dat het een slechte regeling zou zijn. Een iets minder irrationeel enthousiasme voor nationalisme zou miljoenen levens kunnen redden.

### Toetreding, uittreding en inspraak

Natuurlijk is de commercialisering van soevereiniteit een onbekend concept, kennelijk zelfs voor Alvin Toffler. Maar het centrale idee – de economische wijze van uitdrukking – is alledaags in het leven van mensen aan het einde van de twintigste eeuw. In elke enigszins vrije economie kunnen consumenten hun wensen direct uitdrukken door diensten en producten aan te schaffen, of door af te zien van hun aankopen. Wanneer u ontevreden raakt over een bepaalde uitvoering van een product of over een dienstverlener, kunt u uw ongenoegen direct kenbaar maken door middel van 'exit.' Met andere woorden, u kunt uw klandizie elders onderbrengen.

In de voorgaande hoofdstukken hebben we geanalyseerd hoe de vooruitgang in informatietechnologie het binnenkort mogelijk zal maken om activa in cyberspace te creëren die vrijwel immuun zijn voor roofzuchtige inmenging door natiestaten. Dit zal een *de facto* metaconstitutionele vereiste tot stand brengen, namelijk dat overheden je eerst daadwerkelijk bevredigende dienstverlening moeten bieden voordat je hun rekeningen betaalt. Waarom? Omdat de inkomstenbelasting in de praktijk bijna net zo vrijwillig zal worden als verondersteld in de theorie.

### Het vermijden van logge politieke kanalen

In feite, als de informatietechnologie zich ontwikkelt zoals verwacht, zal dit ervoor zorgen dat overheden daadwerkelijk door hun klanten worden gecontroleerd. Als klant zul je eerst honderden, daarna duizenden opties hebben om je beschermingskosten direct te verlagen, hetzij door een particuliere belastingovereenkomst te sluiten met een natiestaat, hetzij door je volledig af te keren van natiestaten en over te stappen op opkomende mini-soevereiniteiten. Deze contractuele 'toetredings'- en 'exit'-opties zijn economische uitdrukkingen van jouw wensen als klant. Met je voeten en je geld stemmen heeft het grote voordeel dat het leidt tot de resultaten die je verlangt.

Hoe verhouden jouw 'toetredings'- en 'exit'-opties als klant zich tot de politieke uitingsvorm in een democratie? Personen die ontevreden raken over een product of dienst – vooral eentje die door de overheid wordt geleverd of zwaar gereguleerd is – kunnen hun stem laten horen door brieven te schrijven aan de president van de Verenigde Staten, of door een afspraak te maken met hun parlementslid of een andere geschikte gekozen functionaris elders. Soms werken dergelijke liefdesbrieven. Maar niet altijd. Meestal niet. Als deze pogingen in eerste instantie geen succes hebben, kunnen mensen die hun stem voor verandering willen laten horen vervolgens een demonstratie organiseren, een hele pagina adverteren in een krant of zelfs zelf een politieke functie nastreven.

De politieke uitingsvorm biedt weliswaar een kanaal voor welsprekende verklaringen en retoriek, maar het heeft als nadeel dat je zelden voldoening bereikt of je positie verbetert door uitsluitend zelf actie te ondernemen. Wanneer je geconfronteerd wordt met een inferieur product of een dienst van de overheid, ben je immers gedwongen ervoor te blijven betalen totdat je het gehele politieke proces ervan kunt overtuigen in te stemmen met jouw verzoek tot verandering.

In westerse landen, en nu in vrijwel de gehele wereld, betekent dit de noodzaak om de meerderheidsondersteuning voor een democratisch politiek systeem te waarborgen. De eis om een meerderheid te betrekken brengt enorme transactiekosten met zich mee tussen u en het bereiken van wat hoogstwaarschijnlijk een relatief eenvoudig en rationeel doel is.

Milton Friedman besprak de verdiensten van de economische, in tegenstelling tot de politieke, wijze van uitdrukking bij het formuleren van zijn voorstel voor schoolvouchers in Capitalism and Freedom:

> Ouders zouden in veel grotere mate hun mening over scholen direct kunnen uiten door hun kinderen uit de ene school te halen en naar een andere te sturen dan nu mogelijk is. Over het algemeen kunnen zij deze stap momenteel slechts zetten door van woonplaats te veranderen. Verder kunnen zij hun mening alleen uiten via omslachtige politieke kanalen.[^447]

Albert O. Hirschman, die als voorvechter van de politiek sprak, maakte bezwaar tegen Friedman's voorkeur voor 'exit' als de 'directe' manier om ongunstige meningen over een organisatie te uiten. Iemand die minder geschoold is in economie zou naïef kunnen suggereren dat de directe manier om zijn mening te uiten is om die gewoon te geven![^448]

Of het nu directer of effectiever is om uw mening kenbaar te maken via marktmechanismen – zoals door als klant uw steun te verlenen of in te trekken – dan wel via 'omslachtige politieke kanalen', is een complexe en controversiële kwestie. Verschillende personen zullen hier verschillend op antwoorden. Voor degenen wiens primaire betrokkenheid bij politieke expressie bestaat uit het eisen van voordelen ten koste van anderen, kan de verschuiving naar de economische wijze van uiten inderdaad als een trieste vervanging overkomen in plaats van een brief te schrijven aan een politicus en meer te eisen.

Economische expressie en "wederkerige socialiteit"

Voor wie voornemens is zijn medemensen te betrekken bij "wederkerige" in plaats van "dwangmatige" of parasitaire socialiteit, opent de economische wijze van uitdrukken de mogelijkheid om met minder tijd en moeite een veel grotere voldoening te behalen. Ongeacht wat professor Hirschfield ervan beweert, is dit gemakkelijk aan te tonen.

Elke reeks economische uitingen – bestaande uit toetredingen, lopende contracten en uittredingen – kan worden omgezet in een uiting van politieke "stem" door simpelweg een menigte mensen bij het besluitvormingsproces te betrekken. Probeer het eens als experiment. Voor het experiment heb je slechts enkele honderden mensen nodig die vinden dat er te weinig politiek in hun leven is. In plaats van hun beschikbare inkomen gedurende een jaar te spenderen aan duizenden afzonderlijke aankopen, zouden zij deze veelvuldige economische besluiten omzetten in een handvol politieke beslissingen.

Aanvankelijk zouden allen ermee instemmen hun beschikbare inkomen te bundelen en daarna af te zien van individuele aankopen. In plaats van dat iedereen duizenden dollars individueel uitgeeft op talloze manieren, krijgt iedere persoon één stem, of wellicht enkele stemmen, afhankelijk van het aantal te vervullen functies. In plaats van direct geld uit te geven om op elk gewenst moment te verkrijgen wat men wil, besteedt men zijn stem op de weinige momenten waarop verkiezingen worden gehouden om vertegenwoordigers te kiezen die vervolgens bepalen hoe de nu gigantische gezamenlijke geldpot wordt besteed.

Jij, samen met de anderen, zou daarna deelnemen aan de consumptie van die goederen – en uitsluitend die goederen die door de besturende commissie in naam van de meerderheid zijn goedgekeurd.

Is dat al wat lijkt op een “omslachtige politieke uitlaatklep” voor expressie? Wacht maar. Dit model heeft alle potentie voor welsprekendheid en overtuigingskracht die men in de nationale politiek aantreft, en ook het grootste deel van de frustratiepotentie.

Bijvoorbeeld, als je van verse broccoli houdt en de groep een gemiddelde spreiding in smaakvoorkeuren heeft, zit je in de problemen. De kans is groot dat enkelen of de meesten van de anderen in je groep liever een groter deel van het gezamenlijke voedingsbudget besteden aan rood vlees dan aan verse groenten. Om te voorkomen dat de kantinecommissie naar een magazijnwinkel gaat en het volledige jaarlijkse groentebudget verkwist op ingeblikte erwten en maïs, moet je wellicht naar voren treden en je mening laten horen. Je zou de aandacht van de groep kunnen vestigen op de relatieve voordelen van het consumeren van meer vitamines en fytonutriënten – zoals sulforaphaan in broccoli – in vergelijking met de verzadigde vetten en het cholesterol in rood vlees.

Hoe je dit of welk ander punt dan ook duidelijk maakt, zal natuurlijk in dit geconstrueerde politieke model net zo’n raadsel zijn als voor voorstanders van eender welke politieke zaak of kandidatuur. Je zou een toespraak kunnen houden, maar dat vereist uiteraard dat een aanzienlijk deel van de groep die je wilt overtuigen al ergens is verzameld en bereid is te luisteren. Je zou flyers kunnen laten drukken, mits een dergelijke “campagne-uitgave” is toegestaan volgens de huisregels van jouw politieke spel. Je zou brieven kunnen schrijven. Maar beide opties hangen ervan af dat de andere deelnemers voldoende geletterd zijn om te lezen.

> "Het schetst een beeld van een samenleving waarin de overgrote meerderheid van de Amerikanen niet weet dat zij niet beschikken over de vaardigheden die nodig zijn om in onze steeds technologisch wordende samenleving en op de internationale marktplaats in hun levensonderhoud te voorzien."  
> Richard Riley; VS-secretaris van onderwijs, in "Adult Literacy in America"

### Negentig miljoen Alzheimerpatiënten?

Als de groep waarmee je deze modelpolitieke oefening uitvoert toevallig uit Amerikanen bestond, zou het buitengewoon lastig zijn om een overtuigende boodschap te laten doordringen, zeker als de groepsleden vergelijkbaar zijn met het Amerikaanse electoraat als geheel. De opvatting dat een onevenredig groot aantal burgers van de machtigste natiestaat ter wereld onderpresteerders is, is somber bevestigd door het meest grondige onderzoek ooit naar de competentie van Amerikaanse volwassenen. De studie “Adult Literacy in America” toont aan dat het vinden van een geletterd publiek voor eender welk politiek betoog allesbehalve eenvoudig is. Een groot deel, misschien zelfs de meerderheid, van de Amerikanen van vijftien jaar en ouder beschikt niet over de basisvaardigheden die essentieel zijn om ideeën te beoordelen en oordelen te vormen. Volgens het Amerikaanse Ministerie van Onderwijs kunnen 90 miljoen Amerikanen geen brief schrijven, een bustijdschema doorgronden of zelfs optellen en aftrekken met een rekenmachine. Dat is precies wat men zou verwachten als 90 miljoen Amerikanen door de verschillende stadia van de ziekte van Alzheimer gingen. Dertig miljoen werden zodanig incompetente bevonden dat zij zelfs niet in staat waren om op vragen te antwoorden.

Dus als je gezondheidsboodschap het tij niet heeft kunnen keren – terwijl het zich anders vanzelf op een bepaald niveau zou stabiliseren – zou je hulp kunnen inroepen bij dierenrechtenactivisten. Misschien kun je hen zover krijgen dat zij je tegenstanders gaan picketten in de kantinecommissie of opschudding veroorzaken over het kwaad van het doden van koeien bij de huizen van invloedrijke personen.

Dit voorbeeld zou oneindig uitgebreid kunnen worden, wat waarschijnlijk veel langer is dan het geduld van rationele mensen toestaat. Het toont duidelijk aan dat (1) elke economische uiting van instap of uitstap kan worden omgezet in een politieke uiting van stem door er een collectieve beslissing van te maken; en (2) dat collectieve beslissingen, ondanks de uitnodiging tot welsprekendheid die zij bieden, des te logzamer en vaak onbuigzaam zijn.

Precies dat heeft de praktijk aangetoond. Het is verre van eenvoudig om de inspanning te mobiliseren die nodig is om de loop van een democratie te veranderen. Om het nog eens te benadrukken: dat zou wel eens de reden kunnen zijn dat democratische verzorgingsstaten eeuwenlang hebben kunnen concurreren met alternatieve bestuursvormen en aan het einde van het industriële tijdperk de overhand kregen. Democratie slaagde als politiek systeem juist omdat de werking ervan het moeilijk maakte voor burgers om de overheid te controleren of de aanspraken van de staat op middelen te beperken.

Maar aangezien een onbeperkte betrokkenheid van de staat bij jouw zaken in het informatietijdperk geen militair voordeel meer oplevert, zullen vindingrijke mensen betere manieren vinden om de weinige waardevolle diensten die overheden daadwerkelijk leveren te verkrijgen. Het is waarschijnlijk dat de daadwerkelijke macht zal worden uitbesteed aan collectieve mechanismen die zichzelf niet langer kunnen bekostigen. Wij verwachten dat efficiëntie de overhand krijgt boven geconcentreerde macht. Zoals Neil Munro beknopt verwoordde: “[H]et is geautomatiseerde informatie, niet mankracht of massaproductie, die de Amerikaanse economie steeds meer aandrijft en die oorlogen zal winnen in een wereld die is toegerust op 500 tv-zenders. De geautomatiseerde informatie bestaat in cyberspace – de nieuwe dimensie gecreëerd door de eindeloze reproductie van computernetwerken, satellieten, modems, databanken en het publieke internet.” [^449]

Massale legers zullen in zo’n wereld weinig betekenen. Efficiëntie zal belangrijker zijn dan ooit tevoren. Omdat microtechnologie een nieuwe dimensie aan bescherming creëert, zoals we in hoofdstuk 6 en elders hebben behandeld, zullen individuen voor het eerst in de menselijke geschiedenis in staat zijn om activa te creëren en te beschermen die volledig buiten de reikwijdte vallen van het territoriale geweldmonopolie van welke individuele overheid dan ook. Deze activa zullen derhalve zeer vatbaar zijn voor individuele controle. Het zal volkomen redelijk zijn voor jou en voor een aanzienlijk aantal toekomstige soevereine individuen om met 'je voeten te stemmen' door je af te melden bij leidende natiestaten en in plaats daarvan een persoonlijke beschermingsdienst af te nemen bij een perifere natiestaat of een nieuwe mini-soevereiniteit, die slechts een commercieel draaglijk bedrag rekent in plaats van het merendeel van je nettovermogen. Kortom, je zou waarschijnlijk $50 miljoen accepteren om naar Bermuda te verhuizen.

Eerst uitstappen, later contracteren

De vroege impuls voor de commercialisering van soevereiniteit zal moeten komen van personen die via vertrek hun economische keuze kenbaar maken. Deze optie zal in de Verenigde Staten het moeilijkst te realiseren zijn, terwijl hij daar tegelijkertijd het meest waardevol zal blijken. De 'Berlijnse Muur' voor kapitalisten, opgelegd door president Bill Clinton en het Republikeinse Congres, staat haaks op de slogan 'hou ervan of verlaat het' die in de jaren zestig zo vol vertrouwen door Amerikaanse nationalisten werd uitgesproken. Door strafbelastingen op te leggen aan degenen die vertrekken, is de exitbelasting bedoeld om loyaliteit af te dwingen. Toch zou deze wraakzuchtige wetgeving – die doet denken aan de straffen die in de laatste dagen van het Romeinse Rijk aan vluchttende landeigenaars werden opgelegd – onbedoeld de basis kunnen leggen voor een meer rationeel beleid in het latere informatietijdperk.

Op een gegeven moment, wanneer voldoende bekwame personen zijn vertrokken en aanzienlijk grote fortuinen offshore hebben opgebouwd, zal het aantrekkelijk worden voor de Amerikaanse autoriteiten om burgers of houders van een groene kaart toe te staan zich uit toekomstige belastingverplichtingen uit te kopen door een exitbelasting te betalen, zonder daadwerkelijk te vertrekken. Met andere woorden, de exitbelasting zou wel eens het model kunnen worden voor een eenmalige afkoop. De overheid die een exitbelasting oplegt, zou veel meer baat hebben bij het toestaan dat degenen die vertrekken hun verblijf hervatten onder de voorwaarden van een privaat verdrag, zoals dat tegenwoordig in Zwitserland en elders beschikbaar is.

Dergelijke stappen van de Verenigde Staten of andere regeringen zouden rationele, inkomensoptimaliserende gebaren zijn. Uiteindelijk zal de concurrentie op het gebied van beschermingsdiensten de belastingtarieven naar beneden dwingen en de voorwaarden voor belastingheffing aanpassen aan meer beschaafde normen. In plaats van te vertrouwen op wetgevende lichamen om aanvaardbare belastingregimes in te voeren, zullen toekomstige soevereine individuen in staat zijn om via privaat verdrag aanvaardbare, op maat gemaakte beleidsvoorwaarden te onderhandelen.

## Het beledigen van de ware gelovigen

Natuurlijk beweren we geen moment dat veel hiervan populair zal zijn. De denationalisering van het individu en de commercialisering van soevereiniteit die dit met zich meebrengt, zullen de overgebleven ware gelovigen in de clichés van de politiek van de twintigste eeuw beledigen. Net als de overleden Christopher Lasch zien zij het verval van de politiek als een bedreiging voor het welzijn van de meerderheid van de bevolking. Naar hun mening zou een heropleving van de politiek uit het industriële tijdperk, met haar inzet voor inkomensherverdeling, een oplossing kunnen bieden voor de problemen die velen ervaren door de competitieve druk die door de informatietechnologie wordt uitgeoefend.

E. J. Dionne, Jr. is een politiek verslaggever voor de *Washington Post*. Net als Lasch kijkt hij nostalgisch terug naar de politiek. Hij vertegenwoordigt tevens een sociaal-democratische egalitaire impuls die in de komende decennia een steeds luider stem zal krijgen nu de nieuwe megapolitieke realiteiten van het informatietijdperk de overgebleven instituties uit de moderne wereld steeds krachtiger ondermijnen. Dionne ziet de materiële verbeteringen in de levensstandaarden, die in de twintigste eeuw breed werden gedeeld binnen rijke rechtsgebieden, hoofdzakelijk te danken aan democratische politiek in plaats van aan technologische of economische ontwikkeling. Zijn boodschap luidt dat hoop voor de toekomst vereist dat het gezag van de politiek wordt uitgebreid over de technologieën van het informatietijdperk:

> De overwegende noodzaak in de Verenigde Staten en in de hele democratische wereld is een nieuwe inzet voor democratische hervorming, de politieke motor die het industriële tijdperk zo succesvol maakte. De technologieën van het informatietijdperk zullen op zichzelf geen succesvolle samenleving opbouwen, net zo min als industrialisme, aan zichzelf overgelaten, de wereld beter zou hebben gemaakt. ... Zelfs de meest opmerkelijke doorbraken in de technologie en de meest geniale toepassingen van het internet zullen ons niet redden van sociale ontwrichting, criminaliteit of onrecht. Alleen de politiek – de kunst van hoe wij ons organiseren – kan zelfs maar beginnen om zulke taken op zich te nemen.[^450]

Dionne en anderen zoals hij begrijpen niet dat de omstandigheden die het leven in de twintigste eeuw bijzonder bevorderlijk maakten voor systematische dwang, niet door enig menselijk handelen waren gekozen. De ‘kunst van hoe wij ons organiseren’ is een uitspraak die vóór de moderne tijd niet begrijpelijk zou zijn geweest. Samenlevingen zijn te complex om terecht te worden beschouwd als het resultaat van een opzettelijke inspanning tot zelforganisatie. De natiestaten van de moderne periode zijn spontaan ontstaan als een toevallig bijproduct van de industriële technologie, die de opbrengsten van geweld verhoogde. Nu vermindert informatietechnologie die opbrengsten. Dit maakt de politiek anachronistisch en onherstelbaar, hoe oprecht mensen er ook naar zouden verlangen haar te behouden voor het volgende millennium.

> 'Niet van vandaag, noch van gisteren hetzelfde  
> Zij leven door alle tijden; en waar zij vandaan kwamen  
> Dat weet niemand.'  - SOPHOCLES, Antigone

## 'Ze maken ze niet zoals vroeger'

De vurige wens om 'wetten te maken', die zo'n integraal onderdeel lijkt te zijn van het gezond verstand in de politiek van de twintigste eeuw, is geenszins universeel in alle culturen. Het verdwijnen ervan in de toekomst zou gezien kunnen worden als onderdeel van een cyclus die door de eeuwen heen op en neer is gegaan. Zo geloofden onder andere de oude Grieken dat wetten niet gemaakt konden worden. In de woorden van de filosoof Ernst Cassirer geloofden de Grieken dat 'de ongeschreven wetten, de wetten van de rechtvaardigheid, geen begin in de tijd hebben.'[^451] Net als andere pre-politieke volkeren waren zij van mening dat niemand de natuurlijke, 'geometrische' wetten van de rechtvaardigheid kon verbeteren, wetten die door geen enkele menselijke macht waren gecreëerd.

Zij geloofden niet in een 'wetgever.' Zoals Cassirer het verwoorde: 'Het is door rationeel denken dat wij de normen voor moreel gedrag vinden, en het is enkel de rede, en alleen de rede, die hen hun autoriteit kan verlenen.' In die zin zou elke poging om wetten door middel van wetgeving aan de samenleving op te leggen gelijkstaan aan het proberen de geometrie door wetgeving te veranderen.

### Wetgeving als heiligschennis

Om zeer uiteenlopende redenen heerste gedurende een groot deel van de middeleeuwen een vergelijkbare weerstand tegen het 'maken van wetten'. Zoals John B. Morrall schrijft: '[V]oor de Germanen bestond de wet al van oudsher.' Het was 'een garantie voor de rechten' van de individuele stamleden.[^452] Koningen en raden

> hadden vooralsnog niet de intentie nieuwe wetten te maken. Zo'n voornemen zou in die vroege middeleeuwse tijden niet alleen overbodig zijn geweest, maar zelfs enigszins godslasterlijk, want zowel de wet als het koningschap bezaten hun eigen heilige uitstraling. In plaats daarvan zagen koning en raadslieden zichzelf louter als uitleggers of verduidelijkers van de ware betekenis van het reeds bestaande en volledige wetgevingssysteem. De Germaanse traditie schonk de middeleeuwse geest een idee dat het nooit wist te vergeten, zelfs als de praktijk er anders uitzag. Dat idee was dat goede wetten opnieuw werden ontdekt of herformuleerd, maar nooit opnieuw werden gemaakt.[^453]

Na de excessen van de wetgeving in de twintigste eeuw heeft die oude houding een zekere ouderwetse charme. De wens om de dwingende macht van de staat in te zetten voor privédoeleinden, in het bijzonder voor de herverdeling van inkomsten, werd bijna vanzelfsprekend.

### Regrets

Het is dan ook weinig verwonderlijk dat er trieste liederen bestaan over de politiek in haar laatste dagen. Ze zijn geheel voorspelbaar. En dat niet alleen omdat ze de blindheid van de meeste denkers voor de eisen van megapolitiek weerspiegelen. Weinige politieke verslaggevers, zoals Dionne, zijn bereid de schijnbare verdroging en ondergang van de politiek te accepteren, ook al zou dat hen weer in de nabijheid van misdaadzaken brengen. Aan het einde van de middeleeuwen werd opgeroepen tot een heropleving van de ridderlijkheid. Neem bijvoorbeeld *Il Libro del Cortegiano*, of *The Book of the Courtier*, geschreven door graaf Baldassare Castiglione in 1514 en in 1528 in Venetië door Aldus uitgegeven.

Castiglione's verlangen naar een terugkeer naar de deugden van ridderlijkheid werd diep gevoeld, maar een verlangen naar een uitgestorven levenswijze kon die niet terugbrengen in de zestiende eeuw. Evenmin zal dat in de eenentwintigste eeuw gebeuren.

Zoals wij hebben geprobeerd over te brengen in onze uitleg van de theorie van megapolitiek, zijn het de technologische imperatieven – en niet de publieke opinie – die de belangrijkste bronnen van verandering vormen. Als onze theorie van megapolitiek klopt, is de reden dat het moderne tijdperk, met zijn concept van burgerschap en een politiek die rondom de staat is georganiseerd, het feodale systeem en de ridderlijkheid, die gebaseerd waren op persoonlijke eden en relaties, heeft vervangen niet te vinden in ideeën, maar in verschuivingen in kosten en baten die voortkomen uit nieuwe technologie.

Ridderlijkheid stierf niet omdat Castiglione of anderen er niet in slaagden een onverschillige bevolking, die in ieder geval geen zeggenschap had over deze aangelegenheid, ervan te overtuigen dat er geen behoefte was aan eer of moraliteit in staatszaken.

Integendeel, Castiglione's *Courtier* is kritisch over vorsten en over het soort gedrag dat zijn tijdgenoot Niccolo Machiavelli prees in zijn *Il Principe*, oftewel *The Prince*.

Maar wat dan? Machiavelli bereikte uiteindelijk een groter publiek met zijn boek, niet omdat zijn betoog in *The Prince* welsprekender was, maar omdat zijn adviezen beter aansloten bij de megapolitieke omstandigheden van het moderne tijdperk.

Zoals de vooraanstaande twintigste-eeuwse filosoof Ernst Cassirer zei in zijn bespreking van 'het morele probleem in Machiavelli',

> Het boek beschrijft, met volledige onverschilligheid, de manieren en middelen waarmee politieke macht verkregen en behouden dient te worden. Over het juiste gebruik van deze macht zegt het geen woord. ... Niemand had ooit getwijfeld dat het politieke leven, zoals het ervoor staat, vol misdaden, verraderij en zware misdrijven zat. Maar geen enkele denker vóór Machiavelli had ooit de kunst van deze misdaden onderwezen. Deze daden werden wel verricht, maar zij werden niet onderwezen. Het feit dat Machiavelli beloofde een leermeester te worden in de kunst van sluwheid, verraderij en wreedheid was ongehoord.

Kortom, *The Prince* was een radicaal werk dat een modern recept uiteenzette waarmee een aspirant-heerser er in kon slagen zijn carrière op de kosten van anderen te bevorderen. Machiavelli keurde gedragingen goed die nauw aansloten bij de aard van de politiek in een tijdperk van macht. Maar de kunst van het dubbelspel, die voor politici in de moderne tijd als een slimme strategie bleek te zijn, was schandalig en subversief ten opzichte van de in voorgaande eeuwen gegroeide cultuur van ridderlijkheid.

Zoals we eerder hebben onderzocht, hielden de deugden van de ridderlijkheid onder meer in dat er nadrukkelijk werd aangedrongen op uiterste trouw aan eden. Dit was noodzakelijk in een samenleving waarin bescherming werd geregeld in ruil voor persoonlijke diensten. De afspraken waarop de feodale samenleving was gebaseerd, waren niet zo van aard dat zij spontaan opnieuw zouden ontstaan onder mensen die onder dwang hun eigen belangen zouden bepalen. Daarom moesten de feodale verplichtingen, die de basis vormden van de ridderlijkheid, worden ondersteund door een sterk gevoel van eer. In die context kon niets subversiever zijn geweest dan Machiavelli’s suggestie dat de vorst niet zou moeten aarzelen om te liegen, bedriegen en stelen wanneer dit in zijn belang was.

Toen de twintigste eeuw ten einde liep, werden Machiavelli’s argumenten nog steeds onderzocht vanwege hun belang voor het begrijpen van de moderne politiek en van allerlei misdaden en tirannieën in de twintigste eeuw. Het werk van Castiglione daarentegen is nagenoeg vergeten. Over een jaar zal *Il Libro del Cortegiano* misschien van kaft tot kaft gelezen worden door een handjevol literatuurstudenten op masterniveau en een paar kenners van de etiquettegeschiedenis.

Binnen de komende decennia zal de nieuwe megapolitiek van het informatietijdperk *De vorst* achterhaald raken. Het soevereine individu zal een nieuw recept voor succes vereisen, een recept dat sterk de nadruk legt op eer en rechtschapenheid bij het inzetten van middelen buiten de greep van de staat. We kunnen voorspellen dat dergelijk advies niet met genoegen zal worden gelezen door E. J. Dionne, Jr. en de overige nog levende sociaaldemocraten.

### Door klanten vastgesteld beleid

Dit zal met name het geval zijn in de vroege fase van de overgang, wanneer de meeste rechtsgebieden nog steeds gebukt gaan onder de noodzaak om beleid op te stellen waarvan de voorstanders het gros van de bevolking kunnen bekoren. Later, naarmate de democratie vervaagt en de markt voor soevereiniteitsdiensten verdiept, zullen de marktomstandigheden die het 'beleid' beperken breder worden begrepen.

What we now think of as 'politiek' leiderschap, dat altijd wordt voorgesteld in termen van een natiestaat, zal in toenemende mate ondernemend worden in plaats van politiek. In deze omstandigheden wordt het werkbare keuzepalet om een 'beleidsregime' voor een rechtsgebied samen te stellen, effectief verkleind op dezelfde wijze als de reeks opties die ondernemers hebben bij het ontwerpen van een eersteklas resorthotel of een soortgelijk product of dienst – bepaald door wat mensen bereid zijn ervoor te betalen. Een resorthotel zou bijvoorbeeld zelden trachten te opereren onder voorwaarden die vereisen dat gasten hard lichamelijk werk verrichten om de faciliteiten te repareren en uit te breiden. Zelfs een resorthotel dat in eigendom is van of wordt gecontroleerd door haar werknemers, net als de typische moderne democratie, zou tevergeefs proberen klanten te dwingen aan dergelijke eisen te voldoen, vooral nadat betere accommodaties beschikbaar kwamen. Als klanten liever golfen dan zwaar lichamelijk werk verrichten in de hete zon, biedt de markt op dat punt in ieder geval weinig ruimte om willekeurige alternatieven op te leggen. Onder dergelijke omstandigheden zullen de op dit moment 'politieke' kwesties wijken voor ondernemende oordelen, terwijl rechtsgebieden trachten te ontdekken welke beleidsbundels klanten zullen aantrekken.

### Het verval van de politiek

Wanneer dit eenmaal begrepen is, zal er een ingrijpende verandering in de houdingen plaatsvinden. Bevolkingen in rechtsgebieden waarbij bevoegdheden worden gedeeld, zullen niet langer verwachten te kiezen uit hetzelfde assortiment wensvervullende beleidsopties dat de politieke debatten in de twintigste eeuw beheerste. Nu de inkomstencapaciteit sterker ongelijk verdeeld is dan in het industriële tijdperk, zullen rechtsgebieden geneigd zijn tegemoet te komen aan de behoeften van die klanten wiens economische activiteit het meest waardevol is en die de meeste keuzevrijheid hebben in waar zij hun middelen besteden.

Onder dergelijke omstandigheden zal het waarschijnlijk veel minder van belang zijn, dan we gewend zijn te veronderstellen, of beleidsmaatregelen die commercieel optimaal zijn voor een rechtsgebied ook aanslaan bij de 'mediaankiezer' in een focusgroep. Kortom, de commercialisering van soevereiniteit zal de controle van overheden door hun klanten faciliteren. Dit zal ertoe leiden dat de meningen van niet-klanten irrelevant – of minder relevant – worden, net zoals de meningen van Big Mac-eters over foie gras geen rol spelen bij het succes van drie-sterren Franse restaurants, zoals L'Arpege in Parijs.

## 'De verraad van de democratie'

Net als de overleden Christopher Lasch zullen tegenstanders niet alleen klagen dat informatietechnologie banen vernietigt, maar ook dat het de democratie tenietdoet omdat het individuen in staat stelt hun middelen buiten het bereik van politieke dwang te plaatsen. Om die reden zullen de reactionairen van het nieuwe millennium de financiële privacy die door informatietechnologie wordt gefaciliteerd als bijzonder bedreigend ervaren. Zij zullen terugdeinzen bij het vooruitzicht dat inkomsten- en vermogensbelastingen werkelijk zouden moeten berusten op 'vrijwillige naleving'. Zij zullen nieuwe en zelfs drastische methoden ondersteunen om middelen uit te persen van iedereen die welvarend lijkt, zoals 'presumptieve belasting' en het letterlijk gijzelen van vermogende personen.

### Gemeenschappelijk eigendom

Hints van wat nog komen gaat, liggen al nabij het oppervlak terwijl we schrijven. Vroege bewijzen dat het vermogen van regeringen om internationale markten te beheersen wegvaagt, stoten degenen tegen die geloven dat individuen van rechtswege activa van natiestaten zijn. Zij willen hun vermogen afdwingen om de burgers van een land als activa te behandelen, en niet als klanten. De reactionairen zijn van mening dat alle inkomens moeten worden beschouwd als opbrengsten van de gemeenschap, wat betekent dat deze ter beschikking van de staat zouden moeten staan.[^455]

We hebben de argumenten die Lasch aanvoerde in *Revolt of the Elites* en *Betrayal of Democracy* al besproken. Maar zijn tirade is niet de enige in steun van de natiestaat. De politicoloog van Harvard University, Michael Sandel, betoogt in *Democracy in Discontent* dat 'democratie van vandaag niet mogelijk is zonder een politiek die de mondiale economische krachten kan beheersen, want zonder die controle maakt het niet uit op wie mensen stemmen, de bedrijven zullen regeren.'[^456] Met andere woorden, de staat moet haar parasitaire macht over individuen behouden, om te waarborgen dat politieke uitkomsten kunnen afwijken van marktuitkomsten. Anders zouden collectieve besluiten om economisch nadelige resultaten af te dwingen zinloos zijn.

Volgens ons is Sandels klaagzang, net als die van Lasch, niet meer dan half correct. We geven toe dat de democratie veel van haar betekenis zal verliezen als regeringen niet de macht hebben individuen te dwingen zich te gedragen zoals politici eisen. Dat is vanzelfsprekend. Inderdaad, de democratie zoals wij die in de negentiende en twintigste eeuw kenden, is gedoemd te verdwijnen. Maar Sandel mist de werkelijke betekenis van de triomf van de markten boven de dwang. Zijn oproep tot 'corporate rule' als een met het verval van de natiestaat gepaard gaande gevaar is opvallend anachronistisch.

Bedrijven zullen nauwelijks in staat zijn om de markten van de nieuwe wereldeconomie te beheersen. Inderdaad, zoals we al suggereerden, is het allesbehalve vanzelfsprekend dat bedrijven zelfs in hun bekende moderne vorm zullen voortbestaan. Helemaal niet. Bedrijven zullen vrijwel onvermijdelijk worden getransformeerd in de megapolitieke revolutie die gepaard gaat met de komst van het informatietijdperk. Zoals we eerder hebben besproken, zal microprocessering de ‘informatiekosten’ veranderen die mede bepalen wat het ‘nexus van contracten’ is dat bedrijven definieert. Zoals economen Michael C. Jensen en William H. Meckling aangeven, zijn bedrijven slechts één juridische vorm die ‘een nexus voor een geheel van contractuele relaties tussen individuen’ biedt.[^457]

Of de onderneming überhaupt kan overleven, om nog maar te zwijgen van ‘besturen’ als ‘een domein van bureaucratische sturing dat afgeschermd is van marktkrachten’, zal waarschijnlijk worden bepaald – in de woorden van economen Louis Putterman en Randall S. Kroszncr – door ‘de volledigheid van de marktkrachten en het vermogen van die krachten om doordringen in intrafirmale relaties.’[^458]

Zoals we eerder betoogden, is het twijfelachtig of bedrijven de toenemende penetratie van marktkrachten in wat voorheen ‘intrafirmale relaties’ waren, kunnen overleven. Daartoe zullen bedrijven waarschijnlijk uiteenvallen, aangezien informatietechnologie het aantrekkelijker maakt om taken uit te voeren via het prijmechanisme en de veilingsmarkt, in plaats van deze intern te organiseren binnen een formele structuur. Naarmate informatietechnologie het productieproces steeds meer automatiseert, zal dit een deel van de *raison d'être* van het bedrijf wegnemen, namelijk de noodzaak om managers in te zetten en te motiveren om individuele werknemers te controleren.

### “Waarom bestaan bedrijven?”

Bedenk dat de vraag “Waarom bestaan bedrijven?” niet zo triviaal is als op het eerste gezicht lijkt. De micro-economie gaat er doorgaans van uit dat het prijmechanisme het meest effectieve middel is om middelen te coördineren voor hun meest waardevolle toepassingen. Zoals Putterman en Kroszner opmerken, impliceert dit dat organisaties zoals bedrijven geen inherente “economische raison d'être” hebben.[^459] In dit opzicht zijn bedrijven hoofdzakelijk artefacten van informatie- en transactiekosten, die door informatietechnologieën drastisch worden verlaagd.

Daarom zal het informatietijdperk waarschijnlijk het tijdperk worden van zelfstandige ondernemers zonder 'banen', maar met langdurige 'ondernemingen'. Naarmate technologie de transactiekosten verlaagt, zal datzelfde proces dat individuen in staat stelt te ontsnappen aan de dominantie van politici, tevens voorkomen dat bedrijven de markt gaan beheersen. Ondernemingen zullen wedijveren met 'virtuele ondernemingen' van over de hele wereld, in een mate die alle, op enkele uitzonderingen na, zal verontrusten en bedreigen. De meeste ondernemingen als instellingen zullen geluk hebben te overleven in een steeds intensievere concurrentie, naarmate de markten completer worden.

De te verwachten consequentie is niet dat individuen aan de wil van ondernemingen zullen worden overgeleverd. Integendeel, ondernemingen hebben op zich niet meer macht om markten te manipuleren dan politici. Het is juist zo dat individuen eindelijk vrij zullen zijn om hun eigen lot te bepalen in een werkelijk vrije markt, die noch door grote overheden, noch door bedrijfsstructuren wordt geregeerd.

Deze afname van transactiekosten zal tevens de recent in de mode geraakt opvattingen over 'stakeholderkapitalisme' weerleggen. Dergelijke opvattingen, dierbaar aan Tony Blair van de Britse Labour Party en aan enkelen rond Bill Clinton, zijn gebaseerd op het idee dat de staat in staat zou zijn ondernemingen te manipuleren. Nu het socialisme is ingestort, dromen interventionisten ervan de doelen van het socialisme te bereiken via meer marktefficiënte middelen door ondernemingen zwaar te reguleren. Volgens deze nieuwe, herverdelende theorie behoren het management, de aandeelhouders, de werknemers en de 'gemeenschap' allen tot de 'stakeholders' van ondernemingen. Het argument luidt dat zij allen voordeel halen uit langdurige ondernemingen en zelfs afhankelijk zijn van deze voordelen. Daarom zou regelgeving de belangen moeten beschermen die managers, werknemers en lokale belastingautoriteiten hebben bij het voortbestaan van hun historische banden met de ondernemingen.

'Stakeholderkapitalisme' is een doctrine die uiteindelijk niet alleen veronderstelt dat de staat de besluitvorming binnen ondernemingen kan manipuleren, maar nog fundamenteler uitgaat van het bestaan van ondernemingen als langdurige organisaties die in staat zijn onafhankelijk van prijssignalen in de veilingmarkt te functioneren.

Wij vermoeden dat de verdieping van markten niet alleen de belastingcapaciteit van de natiestaat zal verminderen, maar ook de mogelijkheid van politici om hun wil arbitrair op te leggen aan de eigenaren van middelen via regelgeving zal ondermijnen. In een wereld waarin jurisdictievoordelen aan marktproeven onderhevig zullen zijn en vele lokale markten voor concurrentie van overal geopend worden, is het nauwelijks te verwachten dat lokale 'gemeenschappen' effectieve methoden zullen vinden om bevoorrechte ondernemingen af te schermen van de mondiale concurrentiedruk. Zij zullen dus maar weinig mogelijkheden hebben om ervoor te zorgen dat ondernemingen die door extra kosten – bijvoorbeeld voor het in dienst houden van overtollige werknemers en management of het openhouden van overtollige faciliteiten om tegemoet te komen aan lokale politieke druk – worden belast, deze kosten kunnen compenseren en in bedrijf blijven.

In het industriële tijdperk konden politici markten afsluiten en de toetreding beperken tot enkele bevoorrechte ondernemingen om zo te voldoen aan werkgelegenheids- en andere doelstellingen. In de toekomst, wanneer informatie overal ter wereld vrij verhandelbaar zal zijn, zal de macht van overheden om lokale bedrijven te isoleren van de wereldwijde concurrentiedruk minimaal zijn.

Evenmin is het waarschijnlijk dat oproepen tot een 'nieuw sociaal contract', gericht op een zogenaamde onafhankelijke of vrijwillige sector om de tijd van anderszins werkloze of gemarginaliseerde arbeiders 'in de gemeenschap' op te vangen, haalbaar zullen blijken.[^460] Jeremy Rifkin stelt zich een 'nieuw partnerschap tussen de overheid en de derde sector' voor om de sociale economie te herbouwen. ... De armen voeden, basisgezondheidszorg verlenen, de jeugd van het land onderwijzen, betaalbare woningen bouwen en het milieu beschermen... [^461]

### De ondergang van openbare goederen

Natuurlijk zullen de voorstanders van dwang betogen dat het afnemende staatsgezag zal leiden tot een onvermogen om openbare goederen te leveren of ervan te genieten. Dit is om zowel competitieve als andere redenen onwaarschijnlijk. Ten eerste, nu plaatsgebonden voordelen grotendeels door technologie zijn weggenomen, zullen rechtsgebieden die essentiële openbare goederen, zoals het handhaven van wet en orde, niet kunnen bieden, al snel hun klanten verliezen. In de meest extreme gevallen, zoals reeds aangetoond in Somalië, Liberia, Rwanda en het voormalige Joegoslavië, is het waarschijnlijk dat hordes blutvluchtelingen de landsgrenzen zullen overschrijden op zoek naar een meer bevredigende waarborging van wet en orde. Deze extreme voorbeelden van deserteeractie, of 'stemmen met de voeten', verschillen qua urgentie nauwelijks van gewoon rechtsgebiedswinkelen. In elk geval zullen ondernemingen lokale rechtsgebieden dwingen om aan de behoeften van hun klanten te voldoen.

### Competitieve territoriale clubs

Dit is meer dan louter een theorie, zoals voor het eerst verwoord door econoom Charles Tiebout in 1956.[^462] Zoals econoom Fred Foldvary heeft gedocumenteerd in *Public Goods and Private Communities: The Market Provision of Social Services*, is er geen wezenlijke reden waarom sociale diensten en vele openbare goederen uitsluitend via politieke middelen verstrekt moeten worden. Foldvary's voorbeelden bevestigen bovendien de controversiële stelling van de Nobelprijswinnende econoom Ronald Coase, namelijk dat 'overheidsinterventie niet nodig is om externaliteiten op te lossen', zoals problemen door vervuiling.[^463] Ondernemers kunnen collectieve goederen via marktmechanismen leveren; velen doen dit inmiddels al in reële gemeenschappen. Foldvary's casestudy's tonen aan hoe de privatisering van gemeenschappen kan leiden tot nieuwe methoden om openbare goederen en diensten te leveren en te financieren.[^464]

### De weg naar voorspoed

Microtechnologie zal nieuwe manieren van financiering en regulering mogelijk maken voor de levering van goederen die tot nu toe als publieke goederen werden beschouwd. Achteraf gezien zal blijken dat sommige van deze goederen in werkelijkheid private goederen waren. Snelwegen vormen daar een belangrijk voorbeeld van. Zolang congestie een gering probleem was, konden wegen en snelwegen als publieke goederen worden behandeld, al was dit onderhevig aan de kritiek van Adam Smith, die stelde dat zij onevenredig veel voordeel opleveren voor de mensen die in de buurt wonen, ten koste van degenen in afgelegen gebieden die gedwongen worden te betalen terwijl zij nauwelijks profiteren.

In het informatietijdperk zal het technologisch haalbaar worden om tolheffing — inclusief congestieheffingen — op te leggen die de toegang tot snelwegen, start- en landingsbanen en andere infrastructuur nauwkeurig prijst, zonder de verkeersstroom te onderbreken. Op die manier kan de levering van transportinfrastructuur discreet worden geprivatiseerd en rechtstreeks worden gefinancierd door degenen die de dienst gebruiken. Econoom Paul Krugman schat dat marktgebaseerde prijsstelling van de Amerikaanse transportinfrastructuur jaarlijks tussen de 60 miljard en 100 miljard dollar zou toevoegen aan de CIDP in de Verenigde Staten, terwijl het de efficiëntie in het gebruik van hulpbronnen verbetert en de vervuiling vermindert.[^465]

Verder mag men niet vergeten dat het duurste onderdeel van wat moderne natiestaten doen — namelijk inkomensherverdeling — helemaal niet de levering van een publiek goed betreft, maar juist de levering van private goederen ten koste van degenen die belasting betalen. Met ‘publieke kost’ wordt hier immers bedoeld ‘ten koste van de belastingbetalers’.

Hoe zit het met een werkelijk publiek goed, zoals het onderhouden van een militaire macht die in staat is om een aanval door een grootmacht af te schrikken? Zo’n macht is traditioneel gezien duur. Natuurlijk, zoals we al hebben besproken, zou een regering die niet onbeperkt het recht heeft om de inkomens en eigendommen van haar burgers te confisqueren, niet in staat zijn om deelname aan een volgende conflict tussen grootmachten — vergelijkbaar met de Tweede Wereldoorlog — te financieren.

Toch vormt deze fiscale limiet minder een bedreiging dan de reactionairen zullen doen geloven, om de simpele reden dat er geen conflicten meer zullen plaatsvinden zoals de Tweede Wereldoorlog. De technologie die individuen bevrijdt, zal daarvoor zorgen.

Up from Politics

In plaats van de kwaliteit en het karakter van dergelijke diensten aan de grillen van de politiek over te laten, kunnen “regeringen” op ondernemende wijze worden bestuurd en worden omgevormd tot wat Foldvary beschrijft als “concurrerende territoriale clubs.” Wij vermoeden dat uiteindelijk het besluitvormingsproces waarmee dergelijke “concurrerende territoriale clubs”[^466] worden georganiseerd, veel minder van belang zal blijken te zijn dan hun succes in het doorstaan van marktproeven op prestatiegebied. Tegenwoordig maakt het voor de meeste consumenten nauwelijks uit of het bedrijf dat een product of dienst verkoopt een eenmanszaak, een besloten vennootschap of een vennootschap is die wordt gecontroleerd door externe bestuurders, voorgedragen door pensioenfondsen. Evenmin twijfelen wij eraan dat de rationele afnemer van soevereiniteitsdiensten in het informatietijdperk zich druk zal maken over de vraag of Singapore een massademocratie is of een particulier bezit van Lee Kwan Yew.

[^430]: John Dunn, *Western Political Theory in the Face of the Future*, Cambridge, Eng.: Cambridge University Press. 1979, p. 2.

[^431]: Carroll Quigley, *Weapons Systems and Political Stability* (Washington, D.C.: University Press of America, 1983).

[^432]: Ibid., p.56.

[^433]: Geciteerd in Kelly, *op. cit.*, p.46.

[^434]: Molander, et al. Strategic Information Warfare, op. cit., p. xv.

[^435]: Ibid., p. xiv.

[^436]: Dennis C. Mueller, *Public Choice*, vol.2 (Cambridge: Cambridge University Press, 1989), pp.43-226.

[^437]: Michael A. Bernstein, *de grote depressie: uitgesteld herstel en economische verandering in amerika, 1929–1939* (Cambridge: Cambridge University Press, 1987).

[^438]: Mancur Olson, *de opkomst en ondergang van naties: economische groei, stagflatie en sociale rigiditeiten* (New Haven: Yale University Press, 1982).

[^439]: Michael M. Phillips, 'wiskunde-ph.d.'s dragen bij aan de anti-vreemdelingengolf: geleerden die geconfronteerd worden met hoge werkloosheid zoeken immigratiebeperkingen,' *Wall Street Journal*, 4 september 1996, p. A2.

[^440]: Juan J. Linz en Alfred Stepan, red., *de ineenstorting van democratische regimes* (Baltimore, Md.: The Johns Hopkins University Press, 1978), p. 18.

[^441]: William Keech, economische politiek: de kosten van de democratie. Cambridge: Cambridge University Press, 1995, p. 221.

[^442]: E.S. Staveley, *Grieks en Romeins stemmen en verkiezingen* (Ithaca, N.Y.: Cornell University Press, 1972), p. 62.

[^443]: Ibid., p.65.

[^444]: Norman Cohn, *De zoektocht naar het millennium* (Oxford: Oxford University Press, 1970), p. 41.

[^445]: Ibid., pp.84-85.

[^446]: Geciteerd in Kelly, *op. cit.*, p.46.

De inhoud van het te vertalen boek is:

[^447]: Milton Friedman, *Capitalism and Freedom* (Chicago: University of Chicago Press, 1962), p. 91. Besproken door Hirschman, *op. cit.*, pp. 16–17.

[^448]: Hirschman, *op. cit.*, p. 17.

[^449]: Neil Munro, 'De nieuwe nachtmerrie van het Pentagon: een elektronische Pearl Harbor,' *Washington Post*, 16 juli 1995, p. C3.

[^450]: E. J. Dionne, 'Waarom rechts het mis is,' *Utne Reader*, juni 1996, p. 32.

[^451]: Ernst Cassirer, *The Myth of the State* (New Haven: Yale University Press, 1946), p. 81.

[^452]: John B. Morrall, *politiek denken in de middeleeuwen* (New York: Harper Torchbooks, 1962), p.15.

[^453]: Ibid., p.16.

[^454]: Cassirer, *op. cit.*, pp.142, 150.

[^455]: Robert I Shapiro, 'volledig mis: nieuwe belastingregelingen kunnen niet tippen aan oude progressieve waarheden,' *Washington Post*, 24 maart 1996, p.C3, en Thomas L. Friedman, 'politiek in het tijdperk van NAFTA,' *New York Times*, 7 april, p. Eli.

[^456]: geciteerd door Friedman, *op. cit.*

[^457]: Zie Louis Putterman en Randall S. Kroszner, 'The Economic Nature of the Firm: A New Introduction,' in Louis Putterman en Randall S. Kroszner, red., *The Economic Nature of the Firm: A Reader* (Cambridge: Cambridge University Press, 1996), p.17.
[^458]: Ibid.
[^459]: Ibid., p.9.
[^460]: Zie Jeremy Rifkin, *The End of Work: The Decline of the Global Labor Force and the Dawn of the Post-Market Era* (New York: G.P. Putnam's Sons, 1995).
[^461]: Ibid., p.250.

[^462]: Zie Charles M. Tiebout, 'A Pure Theory of Local Expenditure,' Journal of Political Economy 64 (1956), pp. 416-24

[^463]: Mueller, *op. cit.*, pp. 28-29.

[^464]: Fred Foldvary, *Public Goods and Private Communities: The Market Provision of Social Services* (Aldershot, Hants, Engeland: Edward Elgar Publishing, Ltd., 1994).

[^465]: Paul R. Krugman, 'The Tax-Reform Obsession,' *New York Times Magazine*, 7 april 1996, p. 37.

[^466]: Foldvary, *op. cit.*, pp. 66f.