# Moraliteit en misdaad in de 'natuurlijke economie' van het informatietijdperk

> “Corruptie… is veel verder verspreid en universeel dan voorheen werd gedacht. Bewijs daarvan is overal te vinden, zowel in ontwikkelingslanden als, steeds vaker, in geïndustrialiseerde landen. . . . Prominente politieke figuren, waaronder staatshoofden en ministers, zijn beschuldigd van corruptie. . . . Op een bepaalde manier betekent dit een privatisering van de staat, waarbij haar macht niet naar de markt verschuift, zoals privatisering normaliter impliceert, maar naar overheidsfunctionarissen en bureaucraten.”[^467] – VIRO TANZI

Wij zijn van mening dat, naarmate de moderne natiestaat uiteenvallen wordt, hedendaagse barbariërs steeds meer feitelijke macht achter de schermen zullen gaan uitoefenen. Groepen als de Russische maffia’s die de botten van de voormalige Sovjet-Unie oprapen, andere etnische misdaadbendes, nomenklaturen, drugskartels en afvallige geheime diensten zullen steeds meer hun eigen wetten hanteren. Dat doen ze nu al.

Veel meer dan algemeen wordt begrepen, hebben de moderne barbariërs de vormen van de natiestaat al geïnfiltreerd zonder dat haar uiterlijke verschijning wezenlijk is veranderd. Het zijn microparasieten die zich voeden met een stervend systeem. Net zo gewelddadig en meedogenloos als een staat in oorlog, passen deze groepen de technieken van de staat op een kleinere schaal toe. Hun groeiende invloed en macht is onderdeel van de verkleining van de politiek. Microprocessing vermindert de omvang die groepen moeten bereiken om effectief te zijn in het gebruik van en de controle over geweld. Naarmate deze technologische revolutie zich ontvouwt, zal roofzuchtig geweld steeds meer buiten de centrale controle worden georganiseerd. Pogingen om geweld te beteugelen zullen eveneens zodanig decentraliseren dat zij meer steunen op efficiëntie dan op de omvang van de macht.

De toename van geheime criminele activiteiten en corruptie binnen natiestaten zal een belangrijke onderliggende verhaallijn vormen te midden van de veranderingen in de wereld. Wat je zult zien, kan wel een geheime en sinistere versie zijn van een slechte film, Invasion of the Body Snatchers. Nog voordat de meeste natiestaten zichtbaar instorten, zullen ze gedomineerd worden door hedendaagse barbariërs. Zoals in de beroemde B-film uit de jaren vijftig zullen zij vaak in vermomming optreden. De Pod People van de toekomst zullen echter geen buitenaardse wezens zijn, maar criminelen van diverse achtergronden die officiële posities bekleden terwijl hun loyaliteit ten minste gedeeltelijk buiten de constitutionele orde ligt.

Het einde van een tijdperk is meestal een periode van intense corruptie. Naarmate de banden van het oude systeem vergaan, vervaagt ook de sociale ethos, waardoor een omgeving ontstaat waarin hooggeplaatste personen publieke doeleinden kunnen combineren met private criminele activiteiten.

Helaas kun je niet rekenen op de gebruikelijke informatiekanalen om je een nauwkeurig en actueel inzicht te geven in het verval van de natiestaat. Dat 'aanhoudende verzinsel' – van het soort dat de val van het Romeinse Rijk verhulde – is waarschijnlijk een typisch kenmerk van de ontbinding van grote politieke entiteiten. Tegenwoordig verdoezelt en maskeert het de ineenstorting van de natiestaat. Om diverse redenen kun je de nieuwsmedia niet altijd vertrouwen om je de waarheid te vertellen. Velen zijn conservatief in die zin dat zij de partij van het verleden vertegenwoordigen. Sommigen worden verblind door anachronistische ideologische toewijdingen aan het socialisme en de natiestaat. Anderen zullen, om concretere redenen, bang zijn om de corruptie te onthullen die naar verwachting steeds meer zal opdoemen in een vervallend systeem. Weer anderen zullen de fysieke moed missen die voor zo'n taak vereist is. Daarnaast vrezen sommigen voor hun baan of schromen om zich uit te spreken uit angst voor andere vergeldingsmaatregelen. En uiteraard is er geen reden te vermoeden dat verslaggevenden en redacteuren minder vatbaar zijn voor corrupte prikkels dan bouwinspecteurs of Italiaanse bestratingsaannemers. In veel grotere mate dan je zou verwachten, kunnen belangrijke informatiebronnen – die schijnbaar alles willen rapporteren – minder betrouwbaar blijken te zijn dan algemeen wordt aangenomen. Velen hebben andere motieven, zoals het versterken van de steun voor een wankelend systeem, die zij boven het eerlijk informeren van jou stellen. Ze zullen weinig zien en nog minder uitleggen.

## Voorbij de realiteit

Naarmate de technologieën voor kunstmatige realiteit en computerspellen blijven verbeteren, zul je zelfs in staat zijn om een avondnieuwsbericht te bestellen dat het nieuws nabootst dat je graag zou willen horen. Wil je een verslag zien waarin jij als winnaar van de tienkamp op de Olympische Spelen in de schijnwerpers staat? Geen probleem. Het zou het hoofdverhaal van morgen kunnen zijn. Je zult elk verhaal dat je wenst – of het nu waar of onwaar is – op je televisie of computer zien ontvouwen met een grotere schijn van echtheid dan wat NBC of de BBC op dit moment kunnen voortbrengen.

We bewegen ons in een rap tempo naar een wereld waarin informatie net zo volledig bevrijd zal zijn van de grenzen van de realiteit als de menselijke vindingrijkheid dit kan bewerkstelligen. Zeker, dit zal enorme gevolgen hebben voor de kwaliteit en de aard van de informatie die je ontvangt. In een wereld waar kunstmatige realiteit en de onmiddellijke overdracht van alles overal samenkomen, zullen de integriteit van het oordeel en het vermogen om het ware van het valse te onderscheiden nog belangrijker worden.

Maar dit zal minder een verandering zijn ten opzichte van onze huidige omstandigheden dan veel mensen zich zouden voorstellen. De verschillen tussen waar en onwaar zijn vaak vervaagd door factoren die door de technologie verder versterkt zijn. We zeggen dit in de wetenschap dat veel van de consequenties van de informatie-revolutie bevrijdend zijn geweest.

Technologie is al begonnen geografische nabijheid en politieke overheersing te overstijgen. Overheden kunnen barrières opwerpen om de handel in goederen te belemmeren, maar ze kunnen veel minder doen om de overdracht van informatie te stoppen. Bijna elke gast in elk restaurant in Hong Kong is via een mobiele telefoon verbonden met de hele wereld. De hardline staatsgreepcomplotters in Moskou in augustus 1991 konden Jeltsins communicaties niet stilleggen, omdat hij mobiele telefoons had.

### Meer informatie, minder begrip

Naarmate de barrières voor de overdracht van informatie zijn weggevallen, is er meer informatie beschikbaar – wat goed is. Maar er is ook meer verwarring ontstaan over wat het betekent. De moderne technologie die informatie bevrijdt van politieke controle en de beperkingen van tijd en plaats, verhoogt tevens de waarde van ouderwetse oordeelsvorming. Het soort inzicht dat helpt te onderscheiden wat belangrijk en waar is te midden van de berg feiten en fantasieën, wordt bijna dagelijks kostbaarder. Dit geldt om ten minste drie redenen:

1. De overvloed aan beschikbare informatie legt de nadruk op beknoptheid.

Beknoptheid leidt tot afkorting. Afkortingen laten weg wat onbekend is. Wanneer je veel feiten te verwerken hebt en talloze telefoontjes nog moet terugbellen, is de natuurlijke wens om ieder informatieverwerkingsmoment zo beknopt mogelijk te houden. Helaas biedt afgekorte informatie vaak een zwakke basis voor begrip. De diepere en rijkere lagen van de geschiedenis zijn precies die delen die doorgaans worden weggelaten in de vijfenentwintig seconden durende soundbites en verkeerd worden weergegeven op CNN. Het is veel eenvoudiger een boodschap over te brengen als een variatie op een reeds begrepen thema dan een nieuw paradigma van begrip te verkennen. Je kunt een score van honkbal of cricket veel gemakkelijker melden dan uitleggen hoe honkbal of cricket precies wordt gespeeld en wat het betekent.

2. De snel veranderende technologie ondermijnt de megapolitieke basis van de sociale en economische organisatie. Daardoor raken brede paradigma-inzichten, oftewel onuitgesproken theorieën over hoe de wereld functioneert, sneller achterhaald dan voorheen. Dit vergroot het belang van een overkoepelend overzicht en doet afbreuk aan de waarde van individuele 'feiten' van het soort dat vrijwel voor iedereen met een informatieopzoeksysteem direct beschikbaar is.

3. De toenemende tribalisering en marginalisering van het leven hebben een belemmerend effect op het discours en zelfs op het denken. Velen zijn daardoor gewend geraakt conclusies te mijden die duidelijk blijken uit de feiten waarover zij beschikken. Een recent psychologisch onderzoek, vermomd als een opiniepeiling, toonde aan dat leden van afzonderlijke beroepsgroepen bijna unaniem niet bereid waren om enige conclusie te aanvaarden die voor hen een inkomensverlies impliceerde, hoe sluitend de logica erachter ook was. Gezien de toegenomen specialisatie is het merendeel van de interpretatieve informatie over de meest gespecialiseerde beroepsgroepen erop gericht de belangen van die groepen te dienen. Zij hebben weinig interesse in opvattingen die onbeschoft, onrendabel of politiek incorrect zouden kunnen zijn. Er is geen beter voorbeeld van deze algemene neiging dan de voortdurende herhaling van opvattingen die rooskleurige vooruitzichten voor investeringen in de aandelenmarkt suggereren. Het merendeel van die informatie wordt door effectenmakelaars gegenereerd, waarvan er maar weinig u zullen vertellen dat aandelen overgewaardeerd zijn. Hun inkomen is namelijk afhankelijk van transacties waarbij de meerderheid van de klanten bereid is te kopen. Onafhankelijke, afwijkende stemmen worden zelden gehoord.

Om deze en andere redenen is het informatie-tijdperk nog geen tijdperk van begrip geworden. Integendeel, er is een scherpe afname opgetreden in de strengheid van het publieke discours. De wereld zou nu meer kunnen weten dan ooit in het verleden, maar er is vrijwel geen publieke stem meer die de betekenis van gebeurtenissen kan beoordelen en kan zeggen wat waar is. Dit is de reden waarom wij gefascineerd zijn geweest door de lauwe belangstelling, met name in de Amerikaanse media, voor het rapporteren van aanwijzingen voor sensationele corruptie op hoge niveaus binnen de Amerikaanse overheid.

Een centraal thema waar we in dit boek mee hebben geworsteld, is hoe veranderende technologie en andere 'megapolitieke' factoren de 'natuurlijke economie' veranderen. De 'natuurlijke economie' is de darwinistische 'toestand van de natuur', waarin de uitkomsten – soms oneerlijk – worden bepaald door fysieke kracht. In de 'natuurlijke economie' is een belangrijke gedragsvorm wat biologen 'interferentieconcurrentie' noemen.

### interferentieconcurrentie

«Interference competitors,» zoals Jack Hirshleifer het verwoordde, «verkrijgen en behouden de controle over middelen door hun rivalen rechtstreeks af te weren of te hinderen.»[^468] Hoezeer we ook zouden wensen dat menselijk gedrag altijd onderworpen was aan de rechtsstaat en «andere maatschappelijk afgedwongen spelregels» («politieke economie»), er is overvloedig bewijs dat veel mensen «naar de regels spelen» slechts wanneer het hen uitkomt. Hirshleifer, een autoriteit op het gebied van conflicten, verwoordde het als volgt: «[D]e volharding van criminaliteit, oorlog en politiek leert ons dat de feitelijke menselijke aangelegenheden nog steeds grotendeels onderhevig zijn aan de onderliggende druk vanuit de natuurlijke economie.»[^469]

Met andere woorden, economische uitkomsten worden slechts gedeeltelijk bepaald door het vreedzame en wettige gedrag van de Homo economicus zoals in de leerboeken beschreven, die eigendomsrechten respecteert «en niet zomaar neemt wat niet van hen is.»[^470] De werkelijke uitkomsten worden ook gevormd door conflicten, waaronder openlijk geweld. Zoals econoom Hirshleifer opmerkt: «Zelfs onder gezag van wet en regering zal het rationele, eigenbelanghebbende individu een balans vinden tussen wettige en onwettige middelen om middelen te verkrijgen – tussen productie en ruil aan de ene kant en diefstal, fraude en afpersing aan de andere kant.»[^471]

## Overval in het informatietijdperk

Michelle R. Garfinkel en Stergios Skaperdas onderzoeken dit in een nuttig boek over geweld, misdaad en politiek, *The Political Economy of Conflict and Appropriation*: «Individuen en groepen kunnen óf produceren en daarmee rijkdom creëren, óf de door anderen gecreëerde rijkdom in beslag nemen.»[^472] Zij citeren een verhaal over moderne interferentieconcurrentie, oorspronkelijk gerapporteerd door The Economist. «Een Amerikaanse zakenman, die onlangs in Moskou was aangekomen om een kantoor te openen, werd bij zijn hotel opgewacht door vijf mannen met gouden horloges, pistolen en een afdruk van de nettowaarde van zijn bedrijf. Zij eisten 7% van toekomstige inkomsten. Hij nam de eerstvolgende vlucht naar New York, waar overvallers minder geraffineerd zijn.»[^473] Dit verhaal over overvallen in het informatietijdperk is meer te danken aan nieuwe technologie dan aan het eenvoudige feit dat schurken in Rusland via het internet toegang hebben tot financiële profielen en kredietrapporten van hun slachtoffers.

### Dalende beslissendheid van militaire macht

Voor goed en kwaad, door de grootschalige militaire macht minder doorslaggevend te maken, heeft informatietechnologie de capaciteit van de natiestaat om haar gezag op te leggen in een woelige wereld radicaal verminderd. Als het ooit, zoals Voltaire zei, 'God aan de kant van grotere bataljons' was, lijkt er met elke dag die verstrijkt minder goddelijke steun te zijn voor het genereren van grote opbrengsten uit geweld. In plaats daarvan zien we het tegenovergestelde – meer bewijs van afnemende rendementen op geweld – wat er sterk op wijst dat grote conglomeraten, zoals de natiestaat, hun enorme vaste kosten niet langer zullen kunnen rechtvaardigen.

Het meest voor de hand liggende bewijs van de afnemende doeltreffendheid van gecentraliseerde macht is de opkomst van terrorisme. Hooggeplaatste bomaanslagen in de Verenigde Staten in het midden van de negentiger jaren tonen aan dat zelfs de militaire supermacht der wereld niet immuun is voor aanvallen.

Een andere belangrijke manifestatie van dalende rendementen op geweld is de wereldwijde groei van gangsterisme en georganiseerde misdaad, samen met de bijbehorende politieke vriendjespolitiek en corruptie. Ze weerspiegelen een over het algemeen amorale sfeer waarin de staat weliswaar kan dwingen, maar niet kan beschermen. Naarmate haar geweldsmonopolie afbrokkelt, dringen nieuwe concurrenten zich op, zoals de pestkoppen die geprobeerd hebben hun eigen particuliere belastingen op te leggen aan de Amerikaanse zakenman in Moskou.

Kleine groepen, stammen, triaden, bendes, gangsters, mafia’s, milities en zelfs eenlingen hebben een toenemende militaire effectiviteit verworven. Zij zullen in de 'natuurlijke economie' van het volgende millennium veel meer reële macht uitoefenen dan in de twintigste eeuw. Wapens die microchips gebruiken, hebben de neiging de machtsbalans naar de verdediging te verschuiven, waardoor beslissende agressie minder winstgevend en daardoor minder waarschijnlijk wordt. Slimme wapens, zoals bijvoorbeeld Stinger-raketten, neutraliseren effectief een groot deel van het voordeel dat grote, welvarende staten vroeger genoten bij het inzetten van dure luchtmacht om armere, kleinere groepen aan te vallen.

### Informatieoorlog in het verschiet

Wat aan de horizon opdoemt, is de veelbesproken maar nauwelijks begrepen mogelijkheid van een ‘informatieoorlog’. Het wijst ook op dalende meeropbrengsten van geweld. ‘Logische bommen’ kunnen luchtverkeersleidingssystemen, wisselmechanismen voor spoorwegen, stroomgeneratoren en distributienetwerken, water- en rioleringssystemen, telefonische relais en zelfs de communicatiesystemen van het leger uitschakelen of saboteren. Naarmate samenlevingen steeds afhankelijker worden van geautomatiseerde besturingssystemen, zouden ‘logische bommen’ bijna evenveel schade kunnen aanrichten als fysieke explosies.

In tegenstelling tot conventionele bommen kunnen ‘logische bommen’ op afstand tot ontploffing worden gebracht, niet alleen door vijandige overheden maar ook door groepen freelance programmeurs en zelfs door getalenteerde individuele hackers. Merk op dat een Argentijnse tiener in 1996 werd gearresteerd omdat hij herhaaldelijk Pentagoncomputers had gehackt. Hoewel hackers tot op heden er zelden voor hebben gekozen om computergestuurde systemen op destructieve wijze te saboteren, komt dat niet doordat er werkelijk effectieve methoden zijn om hen te stoppen.

Wanneer het tijdperk van de informatieoorlog eindelijk aanbreekt, is het onwaarschijnlijk dat de tegenstanders uitsluitend overheden zullen zijn. Een bedrijf als Microsoft heeft zeker een grotere capaciteit om een informatieoorlog te voeren dan 90 procent van de natiestaten wereldwijd.

### De tijd van het soevereine individu

Dit is gedeeltelijk de reden waarom wij dit boek *het soevereine individu* hebben getiteld. Naarmate de schaal van de oorlogsvoering afneemt, zullen defensie en bescherming op kleinere schaal worden georganiseerd. Daarom zullen deze steeds meer als particuliere in plaats van publieke goederen worden geleverd, tegen winstbejag door private aannemers. Dit blijkt al duidelijk uit de privatisering van de politiezorg in Noord-Amerika. Een van de snelst groeiende beroepen in de Verenigde Staten is die van de ‘beveiliger’. Prognoses geven aan dat het aantal particuliere beveiligers in 2005 met 24 tot 40 procent zal stijgen ten opzichte van het niveau van 1990.[^474]

De privatisering van politietaken is al een duidelijk omschreven trend. Toch, zoals de Anglo-Ierse guru Hamish McRae opmerkt, is dit nauwelijks het resultaat van een weloverwogen beslissing van de overheid. Hij schrijft in The World in 2020:

> Geen enkele overheid heeft een specifieke beslissing genomen om zich terug te trekken uit bepaalde politietaken, noch hebben er daadwerkelijk overheden zich teruggetrokken; de private sector heeft juist hun plaats ingenomen. Gedeeltelijk als gevolg van de vermeende tekortkomingen van de politie, deels door andere maatschappelijke veranderingen, hebben particuliere beveiligingsbedrijven geleidelijk het grootste deel van de taak overgenomen om gewone burgers in hun kantoren of winkelcentra te beschermen. Zoals de ommuurde woonwijken in Los Angeles aantonen, bewegen mensen zich zelfs enigszins terug naar het middeleeuwse concept van een stad, waarin de burgers leven achter stadsmuren die door bewakers worden gepatrouilleerd en waar toegang uitsluitend mogelijk is via gecontroleerde poorten.[^475]

Wij zijn van mening dat dit slechts een voorproefje is van een meer omvattende privatisering van bijna elke functie die in de twintigste eeuw door overheden werd uitgevoerd. Omdat informatietechnologie de capaciteit van gecentraliseerde autoriteiten heeft ondermijnd om macht uit te oefenen en fysieke veiligheid te bieden voor systemen die op grote schaal opereren, neemt de optimale omvang van bijna elke onderneming in de 'natuurlijke economie' af.

Om op deze technologische verandering te reageren, zal een enorme investering (lees: kans) nodig zijn om kwetsbare systemen te herontwerpen met gedistribueerde in plaats van geconcentreerde capaciteiten. Als grootschalige kwetsbaarheden niet worden verholpen, zullen de systemen die deze bezitten onderhevig zijn aan catastrofale storingen.

Vroeg of laat, zo goed als vanzelf als niet opzettelijk, zullen de diensten en producten die door grote bureaucratische instanties en bedrijven worden geleverd, evolueren naar zeer competitieve markten, die niet vanuit een 'hoofdkantoor' worden beheerd, maar via een gedistribueerd, decentraal netwerk. De onderneming met een hoofdkantoor dat omsingeld kan worden door betogers of gesaboteerd door terroristen, zal kwetsbaar zijn totdat zij uiteindelijk verandert in een 'virtuele onderneming' zonder vaste locatie, 'tegelijkertijd op vele plaatsen aanwezig', zoals Kevin Kelly, uitvoerend redacteur van *Wired* magazine, schrijft in *Out Of Control*. Kelly begrijpt dat technologie de noodzaak heeft veranderd om productieprocessen onder gecentraliseerde controle te brengen. 'Gedurende het grootste deel van de industriële revolutie werd aanzienlijke rijkdom vergaard door productieprocessen onder één dak te brengen. Groter was efficiënter.' Nu is dat niet zo.

Kelly voorziet de mogelijkheid dat een auto van de toekomst, de Upstart Car, ontworpen en in productie genomen zou kunnen worden door slechts een dozijn mensen die samenwerken in een virtuele onderneming.

In de toekomst zou een te grote schaal niet alleen contraproductief, maar ook gevaarlijk kunnen zijn. Grotere ondernemingen vormen verleidelijkere doelwitten. Zoals beoefenaars van de ondergrondse economie aantonen, is één van de geheimen om belastingen te ontwijken het vermijden van opsporing. Dit zal veel eenvoudiger zijn voor kleinschalige, 'virtuele ondernemingen' dan voor gevestigde ondernemingen die vanuit een wolkenkrabber als hoofdkantoor opereren met hun naam in lichten. Zij zullen onvermijdelijk vatbaarder zijn voor de aandacht van 'mannen met gouden horloges, pistolen en een print-out van de nettowaarde van het bedrijf', de gangsters die in andere delen van de wereld – zoals in Rusland – hun eigen particuliere vorm van belasting zullen opleggen. Ondernemingen van elke omvang zullen kwetsbaar zijn voor criminele afpersing en opgelegde lasten door georganiseerde misdaadbendes.

> 'Beschouw de definitie van een racketeer als iemand die een bedreiging creëert en vervolgens kosten in rekening brengt voor het wegnemen ervan. De bescherming die door regeringen wordt geboden, kwalificeert volgens deze norm vaak als afpersing.'[^477] - CHARLES TILLY

### Natuur haat monopolies

Naarmate het geweldmonopolie dat wordt genoten door de 'grotere bataljons' afbrokkelt, is één van de eerste verwachte gevolgen een groeiende voorspoed voor de georganiseerde misdaad. Immers, de georganiseerde misdaad vormt de belangrijkste concurrent van natiestaten in het inzetten van geweld voor roofzuchtige doeleinden. Hoewel het onbeleefd is om dat te zeggen, mogen we niet vergeten, zoals politicoloog Charles Tilly ons eraan herinnert, dat regeringen zelf — 'het toonbeeld van beschermingsafpersingen met het voordeel van legitimiteit' — kwalificeren als onze grootste voorbeelden van georganiseerde misdaad.

Als je verder niets over de wereld wist behalve dat een belangrijk monopolie instortte, is een van de eenvoudigste en zekerste voorspellingen die je kunt doen dat de naaste concurrenten het meeste zullen profiteren. Het is dan ook geen toeval dat drugskartels, bendes, mafia’s en triaden van allerlei soorten wereldwijd in opkomst zijn.

### Sistema del potere

Van Rusland tot Japan tot de Verenigde Staten is georganiseerde misdaad een veel belangrijkere factor in de werking van economieën dan economische leerboeken doen vermoeden. Wat de Sicilianen 'sistema del potere', het 'systeem van macht' van de georganiseerde misdaad, noemen, speelt een steeds belangrijkere rol bij het bepalen van hoe economieën functioneren.

Europese politiefunctionarissen melden dat internationale misdaadsyndicaten, waaronder Russische en Italiaanse mafia’s, een ‘dominante rol’ hebben gespeeld bij het financieren van de genocidale oorlogen die de Balkan de afgelopen jaren teisterden.

Ook drugssmokkelaars hebben een sleutelrol gespeeld bij het financieren van recente burgeroorlogen en opstanden in andere delen van de wereld. Julio Fernandez, chef van de drugseenheid van de Spaanse nationale politie in Catalonië, zegt: ‘Van 1986 tot 1988 werd 80 procent van de heroïne in Spanje vervoerd door Tamil Tiger-guerrilla’s die samenwerkten met Pakistaanse inwoners in Barcelona of Madrid. Zodra we dat netwerk met arrestaties hadden opgeruimd, werd het vervangen door Koerden uit Turkije, die het de daaropvolgende twee jaar volledig domineerden.’[^479] De kans is groot dat, wanneer een nieuwe burgeroorlog of opstand uitbreekt, de wanhopig arme strijders hun militaire inspanningen financieren door het leveren van drugs en het witwassen van drugsgeld.

### Door drugs gefinancierde prijsverlaging

De activiteiten van georganiseerde criminele syndicaten hebben een neerwaartse druk op de prijzen van goederen, anders dan drugs, uitgeoefend. Op microniveau subsidiëren deze criminele syndicaten schijnbaar legitieme bedrijven met de buit uit hun criminele ondernemingen. Zij kunnen drugswinst en andere illegale gelden witwassen door gewone producten onder de kostprijs te verkopen, waardoor zij de prijzen van hun legitieme concurrenten ondermijnen en vele ondernemingen failliet laten gaan.

### Yakuza-deflatie

In Japan speelden de machtige Yakuza-bendes een sleutelrol in de hyperactieve vastgoedzeepbel van de late jaren tachtig. Ondanks dat negentigduizend Yakuza jaarlijks tussen de $10,19 miljard (officiële schatting) en $71,35 miljard (schatting van professor Takatsugu Nato) genereren, werden een groot deel van de oninbare leningen, die de solvabiliteit van de Japanse banken bedreigden, aangegaan voor deals die door de Yakuza werden gesteund.[^480] De deflatoire druk – ‘prijsvernietiging’, zoals de Japanners het noemen – die de Japanse economie kenmerkt, is daar een gevolg van.

### Een blind oog

De Russische maffia’s, zoals Yeltsin zelf heeft toegegeven, zijn samengesmolten met 'commerciële organisaties, administratieve instanties, organen van het ministerie van Binnenlandse Zaken en gemeentelijke overheden... [^481] Door de immuniteit die de maffia’s hebben verkregen doordat zij zich met de politie hebben verbonden, kunnen zij met flagrant geweld de inning van hun particuliere belastingen afdwingen. Betrouwbare bronnen geven aan dat vier van de vijf Russische bedrijven nu afpersingsgeld betalen. 'Volgens sommige rapporten moeten lokale kleine bedrijven in Rusland 30 tot 50 procent van hun winst afstaan aan racketeers, niet slechts de magere 7 procent die van de Amerikaanse zakenman wordt geëist.'[^482]

In 1993 werden in Rusland 355.500 misdrijven officieel aangemerkt als voorbeelden van 'afpersing', waaronder bijna '30.000 voorbedachte moorden', grotendeels huurmoorden als gevolg van conflicten in de commerciële en financiële sector. Volgens een voormalige minister van Binnenlandse Zaken, generaal Viktor Yerin, waren het merendeel huurmoorden. In de meeste gevallen keken de autoriteiten de andere kant op. Criminele organisaties, 'door hun controle over dwang en corruptie', zoals economen Gianluca Fiorentini en Sam Peltzman schrijven in The Economics of Organized Crime, spelen een sleutelrol in de economie.[^483] In theorie kan deze invloed soms gunstig zijn, omdat zij regelgeving beperkt en overheden kan aansporen de levering van publieke goederen te verbeteren. De aanwezigheid van een machtige maffia 'beperkt de monopolistische rol van de overheidsinstanties.'[^484] Overheden in gebieden met machtige georganiseerde misdaadgroepen kunnen met grote moeite beleid voeren dat door de maffia’s wordt tegengewerkt.

### Collusie

Het valt op hoe zelden de meeste overheden bereid zijn de maffia’s — hun voornaamste concurrenten in het gebruik van georganiseerde dwang — direct te confronteren. In strikt economische termen is dit niet verwonderlijk. De meest winstgevende regeling die 'de gekozen leden van het openbaar bestuur' kunnen treffen, is een 'collusieakkoord' met de georganiseerde misdaad. Fiorentini en Peltzman merken op dat 'er aanwijzingen zijn voor grootschalige overeenkomsten waarbij de georganiseerde misdaad politieke steun waarborgt voor groepen kandidaten, terwijl laatstgenoemden de gunst beantwoorden door een gunstig beheer van overheidsopdrachten en de levering van overheidsdiensten of subsidies.'[^485]

In tegenstelling tot de indruk die Hollywood wekt, lijkt het binnendringen in en oplichten van overheden nu een van de voornaamste aandachtspunten te zijn van criminele organisaties zoals de Siciliaanse maffia. 'De meeste geleerden denken dat de grootste business van de Siciliaanse maffia tegenwoordig precies bestaat uit het toe-eigenen van de verschillende bronnen van overheidsuitgaven en het organiseren van fraude met betrekking tot de lokale, nationale en Europese subsidieregelingen.'[^486]

### Narco republieken

Zoals we in *The Great Reckoning* waarschuwden, zijn veel regeringen wereldwijd volledig gecorrumpeerd door drugsherren. Mexico is daar een onbetwistbaar voorbeeld van. Voormalig Mexicaans federaal adjunct-aanklager Eduardo Valle Espinosa plaatste het Mexicaanse systeem in perspectief in zijn ontslagverklaring: 'Niemand kan een politiek project opzetten waarin de kopstukken van de drugshandel en hun geldschieters niet voorkomen. Want als je dat wel doet, sterf je.' Valle gaf aan dat steekpenningen het dienen als Mexicaanse politiechef zo lucratief maken dat kandidaten tot $2 miljoen betalen om aangenomen te worden. In een strikte winst- en verliesrekening kan het kopen van een plaats in de lokale politie een winstgevende investering blijken te zijn. Drugskartels zijn bereid fortuinen te betalen aan zelfs laaggeplaatste Mexicaanse ambtenaren, omdat dat geld hen immuniteit tegen vervolging voor hun misdaden verschaft.

Colombia is een ander land waar de hoogste regionen van de overheid gedomineerd worden door drugsherren. De Amerikaanse autoriteiten hebben onlangs het visum van de Colombiaanse president Ernesto Samper voor de Verenigde Staten ingetrokken op grond van het feit dat hij opzettelijk politieke bijdragen van drugsdealers heeft aangenomen in ruil voor gunsten.

### De pot verwijt de ketel dat hij zwart ziet

Wie de rapporten in onze nieuwsbrief Strategic Investment in de jaren negentig heeft gevolgd, zal onmiddellijk de ironie herkennen in de houding van de Clinton-administratie ten aanzien van Samper. Er is geloofwaardig bewijs dat de Amerikaanse president Bill Clinton alles heeft gedaan waarvan Samper wordt beschuldigd en nog erger. Ook als u ons woord niet zou aannemen, wordt Clintons achtergrond in opzichtig detail belicht in twee goed onderzochte boeken door auteurs aan weerszijden van het politieke spectrum.

Roger Morris, die over het algemeen een linkse visie hanteert, was een functionaris op het gebied van nationale veiligheid in het Nixon-tijdperk en tevens een belangrijke medewerker van Dean Acheson, president Lyndon Johnson en Walter Mondale. Morris beschikt over een doctoraat van de Harvard University. In zijn boek *Partners in Power* onthult hij een smerig verleden van Clinton, waardoor Samper op een padvinder lijkt.

Morris hervertelt Clinton’s vaderloze jeugd in Hot Springs, Arkansas, een centrum van gokken, prostitutie en georganiseerde misdaad waarmee bijna zijn hele familie verbonden was. Clintons stiefoom, Raymond Clinton, naar wie Bill Clinton verwees als een 'vadersfiguur', stond naar verluidt bekend als een vooraanstaand 'peetvader'-figuur in de Dixie-maffia. Morris beweert dat Bill Clinton als rekruté bij de CIA kwam en zijn studententijd aan Oxford doorbracht met het observeren van anti-Vietnamoorlogactivisten. Volgens Morris bleef Clinton tijdens zijn periode als gouverneur een instrument van de CIA, door een operatie voor het smokkelen van drugs en wapens te faciliteren, gecentreerd in Mena, Arkansas. Morris lijkt de CIA als geheel te beschuldigen van drugshandel, in plaats van de mogelijkheid te overwegen dat Clinton zich had aangesloten bij een corrupte factie binnen het agentschap, wat voor ons waarschijnlijker lijkt. Beide interpretaties suggereren echter dat de belangrijkste geheime inlichtingenorganisatie van de Amerikaanse overheid, al dan niet direct, op grote schaal deelneemt aan georganiseerde drugssmokkel. Als de CIA geen aanvulling is op de georganiseerde misdaad, dan komt zij gevaarlijk dicht in de buurt van 50. [^487]

### Eén kans op 250.000.000

Toch bevat *Partners in Power* details die elke student van de corruptie in de moderne Amerikaanse politiek zouden interesseren. En de vingers van Morris zijn geenszins uitsluitend op Bill Clinton gericht; ook zijn vrouw krijgt kritische aandacht. Overweeg bijvoorbeeld dit fragment uit Morris’ verslag over Hillary Clintons wonderbaarlijke handel in grondstoffen: 'In 1995 lieten economen van de Auburn University en de North Florida University een geavanceerd statistisch computermodel draaien op basis van de handelsactiviteiten van de eerstedame, voor publicatie in het Journal of Economics and Statistics, waarbij zij alle beschikbare gegevens en marktinformatie uit de Wall Street Journal gebruikten. Zij berekenden dat de kans dat Hillary Rodham haar transacties op legitieme wijze had verricht, minder was dan één op 250.000.000.' [^488]

Morris verzamelt tal van belastende details over de drugssmokkel- en witwasoperatie die in Arkansas onder Clinton floreerde. 'Door de enorme hoeveelheden drugs en geld die met zijn vluchten werden gegenereerd, werd het kleine Mena, Arkansas, in de jaren tachtig één van de wereldcentra’s van de narcoticahandel.' [^489] Morris citeert een vertrouweling die over Clinton getuigde met de woorden: 'Hij wist het.'

Clinton wist niet alleen van de cocaïnesmokkel, hij vertelde ook aan staatspolitieagent L. D. Brown, een voormalige lijfwacht aan wie Clinton hielp een functie bij de CIA te bemachtigen, dat het drugsvervoer geen CIA-operatie was. 'Oh, nee,' zei Clinton, 'dat is Lasater's zaak.' [^490]

Dan Lasater, veroordeelde cocaïnedistributeur, was een van Clinton's belangrijkste financiële supporters, een man die miljoenen verdiende met het staatsbedrijfsleven in Arkansas en naar verluidt eens $300.000 contant in een bruine papieren zak overhandigde aan de toenmalige gouverneur van Kentucky, John Y. Brown. Volgens Morris was Lasater 'nooit louter een grote donor die speciale eerbied verdiende, maar een buitengewoon vertrouweling die Clinton regelmatig bezocht in zijn makelaarskantoor en die naar het landhuis kwam wanneer hij maar wilde.' [^491] Morris vertelt dat Lasater's chauffeur, die hem vaak naar het landhuis bracht, 'een veroordeelde moordenaar was die een wapen droeg en erom bekend stond naastbei drugs te verhandelen.' [^492] Volgens Morris leek de president van de Verenigde Staten op warmere voet te hebben gestaan met een drugshandelaar dan de vermeende band tussen de Colombiaanse president Ernesto Samper en het Cali-cartel.

> 'Poeh! Bob zegt dingen over Bill Clinton die zelfs Hillary niet zou zeggen' - P.J. O'ROURKE

R. Emmett Tyrell, Jr., hoofdredacteur van *The American Spectator*, is geen links-liberaal zoals Morris. Maar zijn verslag *Boy Clinton* bevat veel van dezelfde details die Morris aanhaalde om een portret van Clinton te schetsen als een corrupte politicus, nauw verbonden met drugshandel en andere misdaden. Inderdaad, de proloog van *Boy Clinton* citeert L. D. Brown, Clinton's voormalige lijfwacht, die de sensationele bewering doet dat Clinton medeplichtig was aan de activiteiten van een doodsdienst die was opgezet om getuigen met kennis van de drugshandel in Mena uit te schakelen.

Specifiek getuigt Brown dat hij op 18 juni 1986 persoonlijk naar Puerto Vallarta, Mexico, werd gestuurd met een in België vervaardigd F.A.L. licht automatisch geweer. Onder het pseudoniem Michael Johnson zou Brown de opdracht hebben gekregen om Terry Reed neer te schieten en te vermoorden.

Reed, zoals u zich misschien herinnert, kwam in 1994 in de openbaarheid te staan als co-auteur van *Compromised: Clinton, Bush en de CIA*. De stelling van *Compromised* is dat de CIA het presidentschap in haar macht heeft gekregen en dat haar 'zwarte operaties, als een kanker, de organen van de overheid hebben gemetastasiseerd'. Meer specifiek beweren Reed en zijn mede-auteur dat zowel Clinton als Bush door hun betrokkenheid bij illegale activiteiten in Arkansas – onder meer drugshandel – diep gecompromitteerd raakten.

Brown heeft Reed niet vermoord, zoals hem was opgedragen. Hij en Reed slaagden erin te overleven om ten minste een deel van hun verhalen te vertellen, wat hen gelukkiger maakt dan anderen die destijds en later met Clinton in verband stonden. Neem bijvoorbeeld de overleden Jerry Parks, die in 1992 de beveiliging verzorgde voor het hoofdkwartier van Clinton-Gore en in september 1993 in een gangland-stijl aanslag doodgeschoten werd. In een andere bizarre wending in dit verwrongen verhaal heeft de Londense Sunday Telegraph, op basis van exclusieve informatie verstrekt door de weduwe van Parks, onthuld dat Parks door de overleden Vincent Foster was ingehuurd om op Bill Clinton te spioneren.

Waarom Foster een dossier met compromitterende informatie over Clinton wilde samenstellen, is voor niemand te zeggen. (Hij zei dat hij het voor Hillary deed.) Maar in ieder geval weerlegt dit de officiële beschrijving van Foster als een naïeve jongen van het platteland, die zo geschokt was door de meedogenloze werkwijzen van Washington dat hij zichzelf uit wanhoop van het leven beroofde. Dat altijd ongeloofwaardige verhaal wordt met iedere nieuwe onthulling minder geloofwaardig.[^493]

### De president van de maffia

Hoewel de wereld als geheel afstand neemt van de verontrustende conclusie dat de president van de Verenigde Staten aangetast is door nauwe banden met de georganiseerde misdaad en criminelen, wijst het bewijs precies in die richting. Morris citeert een voormalig Amerikaanse aanklager die criminele figuren en hun belangen in de gaten hield. Hij beweert dat Clintons verkiezing als gouverneur in 1984 'de verkiezing was waarop de maffia echt binnenkwam in de politiek van Arkansas, de jongens van de hondenbaan en de renbaan, de profiteurs die een mooie kans zagen... het ging verder dan onze oude Dixie-maffia, die in vergelijking daarmee een kleinigheid was. Dit was crimineel geld uit het oosten en de Westkust dat, net als de legitieme ondernemingen, de kansen zag.'[^494]

Blijkbaar hebben andere gelijkgestemden de mogelijkheden bij Clinton blijven opmerken. *New York* magazine, volgend op een eerder artikel in *Readers' Digest*, meldt dat "de belangrijkste bondgenoten van de president binnen de vakbondsbeweging tevens mannen zijn die gelieerd zijn aan wat naar alle aanzichten enkele van de viesste, meest door de georganiseerde misdaad geïnfiltreerde vakbonden in Amerika lijken te zijn."[^495] Van bijzonder belang is de nauwe band van Clinton met Arthur Coia. Coia, die tot de "prima fondsenwervers" van Clinton behoort, is voorzitter van de Laborers International Union of North America, "een van de meest opzichtig corrupte vakbonden in de geschiedenis van de vakbeweging."[^496]

Blijkbaar sloeg het ministerie van Justitie onder Clinton, wat *New York* omschrijft als een "merkwaardig genereuze deal", met Coia om zijn functie te behouden, ondanks de overtuigende beschuldigingen van datzelfde ministerie dat hij al lange tijd bevriend is met figuren uit de georganiseerde misdaad.[^497]

Of de these van Terry Reed dat "de CIA de presidentsfunctie heeft gekaapt" nu correct is of niet, er bestaat duidelijk een sterke verleiding voor personen binnen een geheime organisatie, gemachtigd tot het uitvoeren van "zwarte operaties", om zich over te geven aan professor Hirshleifer’s rationele keuze om "onwettige middelen in te zetten voor het verkrijgen van hulpbronnen."

Gezien de technologische veranderingen die de beslissende kracht van geconcentreerde militaire macht in de wereld doen afnemen, zou men wellicht een toename van corruptie mogen verwachten, zo niet zelfs de volledige overname van regeringen door georganiseerde criminele ondernemingen.

Hirshleifer betoogt, en wij stemmen daarmee in, dat "de instituties van de politieke economie nooit zo perfect kunnen zijn dat ze de onderliggende realiteiten van de natuurlijke economie volledig verdringen."[^498] De macht verschuift binnen de "natuurlijke economie." Dit impliceert ingrijpende veranderingen in de interne machtsverhoudingen binnen de samenleving.

Politieke corruptie, zoals Vito Tanzi scherp opmerkte, 'vertegenwoordigt een privatisering van de staat waarbij haar macht niet naar de markt verschuift, zoals privatisering normaal gesproken impliceert, maar naar overheidsfunctionarissen en bureaucraten.'[^499] In feite is dit gebeurd bij de FBI en andere politiediensten onder Clinton. De 'rechtsstaat' wordt wat Clinton en zijn vriendjes er maar van willen maken. Tot nu toe lijkt er weinig bewijs te zijn dat details over deze corrupte verbindingen enige invloed op de kiezers hebben, zelfs als ze door de massamedia worden opgepakt en besproken. Integendeel, er lijkt weinig bezorgdheid te bestaan over aanwijzingen dat de president van de Verenigde Staten medeplichtig is aan drugshandel, witwassen en erger.

Dit doet denken aan de vrees van de overleden Walter Lippmann dat kiezers niet over het inzicht beschikken om door te dringen tot wat hij 'fictieve persoonlijkheden' noemde. Hij vond dat kiezers 'slecht bediend worden door vleierij en bewondering. En dat zij verraden worden door de slaafse hypocrisie die hen vertelt dat wat waar is en wat onwaar, wat juist is en wat onjuist, kan worden bepaald door hun stem.'[^500]

Lippmann zag een 'inbreuk op de constitutionele orde' die de oorzaak kon zijn van de plotselinge en catastrofale achteruitgang van de westerse samenleving. We zijn in korte tijd ver gevallen. ... Wat we hebben gezien is niet alleen verval – al lost een groot deel van de oude structuur op – maar iets wat een historische catastrofe genoemd kan worden.[^501]

Het probleem is dat politieke oordelen minder een reactie lijken op de echte wereld dan op een schijnrealiteit die het algemene publiek heeft geconstrueerd over fenomenen die buiten zijn directe kennis liggen.[^502] Maar het is een vergissing om je te laten leiden door de grenzen van wat anderen zien. Zelfs als het je niets kan schelen of Vincent Foster vermoord is en zijn moord is doodgebootst door de hoogste politiediensten en verantwoordelijke functionarissen van de Amerikaanse regering – inclusief de huidige speciale aanklager, Kenneth Starr – wil je wellicht bewijzen overwegen van het bredere patroon van banden tussen georganiseerde misdaad en het Witte Huis.

Op de lange termijn maakt politieke corruptie op het hoogste niveau de conventionele viering van de mogelijkheden van de democratie voor het doelbewust beheersen van publieke problemen zinloos. In het informatietijdperk zal het veel minder belangrijk zijn dat de overheid groot en machtig is, dan dat ze eerlijk is. De meeste diensten die overheden historisch verleenden, zullen in het komende millennium naar de private markt overgaan. Maar op basis van bewijzen van over de hele wereld is het twijfelachtig of je langdurig kunt rekenen op een gecorrumpeerd systeem met corrupte leiders voor de veiligheid van je familie en investeringen.

Zoals Morris zegt, "[D]e Clintons zijn niet louter symptomatisch, maar staan symbool voor het bredere tweepartijenstelsel dat aan het einde van de eeuw op een doodlopende weg stuit."[^503] Vito Tanzi toont in zijn essay over corruptie aan dat "de enige manier om corruptie te weren is door de omvang van overheidsinterventie aanzienlijk te verminderen."[^504] De informatierevolutie zal de "omvang van overheidsinterventie" aanzienlijk verkleinen en biedt op die basis hoop op een wedergeboorte van moraliteit en eerlijkheid. De andere voor de hand liggende implicatie van de informatierevolutie voor de moraliteit is een toegenomen kwetsbaarheid die voortvloeit uit de mogelijkheid dat cyberhandel en virtuele ondernemingen met onbreekbare encryptie communiceren. Interne dieven binnen een organisatie, zelfs binnen een virtuele organisatie, zullen moeilijker opgespoord worden en het zal vrijwel onmogelijk zijn om geld terug te vorderen dat gestolen is of in het geheim verkregen wordt door de verkoop van bedrijfsgeheimen, patenten of andere waardevolle economische activa.

Misdaad loont, en velen vinden het aantrekkelijk om legale, productieve bezigheden aan te vullen met illegale, roofzuchtige ondernemingen. In tegenstelling tot de gebruikelijke situatie die in westerse samenlevingen gedurende het grootste deel van de afgelopen twee eeuwen heerste, zijn criminelen niet louter buitenbeentjes zonder sociale status. Wanneer misdaad lonend is, komt er doorgaans een betere klasse criminelen tevoorschijn, omdat er nauwelijks enige sociale afkeuring aan misdaad kleeft. De Siciliaanse maffia, bijvoorbeeld, samen met vele drugsdealers die lokaal personeel tegen opgeblazen tarieven in dienst nemen, geniet op eigen grondgebied van respect en populaire steun.

## DE MORELE ORDE EN HAAR VIJANDEN

Alle sterke samenlevingen hebben een stevige morele basis. Elke studie naar de geschiedenis van economische ontwikkeling toont de nauwe relatie tussen morele en economische factoren aan. Landen en groepen die succesvolle ontwikkeling bereiken, doen dit deels omdat zij een ethiek hanteren die de economische deugden van zelfredzaamheid, hard werken, gezins- en maatschappelijke verantwoordelijkheid, een hoge besparingsgraad en eerlijkheid bevordert. Dit geldt ook voor sociale subgroepen. Het zakelijk succes van Joden, in het bijzonder van religieuze Joden, van de Puriteinen in New England, van de Quakers in de Britse zakenwereld in de achttiende en negentiende eeuw, of van de Mormonen in het moderne Amerika, toont allen de economische voordelen aan die voortvloeien uit culturen met een sterk moreel fundament.

Als voorbeeld kunnen we de Quakers aanhalen. De Quakers werden zakelijk succesvol en waren om verschillende redenen met name befaamd als bankiers. Zij stelden voor zichzelf de hoogst mogelijke norm voor betrouwbaarheid: zij legden geen eden af, maar beschouwden iedere zakelijke toezegging als even bindend als een eed. "Mijn woord is mijn borg" was voor hen een absoluut principe. Zij geloofden in een rustige levensstijl, fatsoenlijk maar zuinig. Als religieuze plicht vermeden zij geld uit te geven aan de ijdelheden van deze wereld. Zij schuwden ruzies en waren van mening dat oorlog altijd zondig was. Zij vonden dat de zakenman een morele plicht had om eerlijke waarde te bieden en ontwikkelden als kooplieden een reputatie voor het leveren van hoge kwaliteit tegen gematigde prijzen. "Caveat emptor" – laat de koper oppassen – volstond voor hen niet. In een tijdperk waarin de meeste kooplieden een handelstheorie volgden die gebaseerd was op hoge prijzen en hoge marges, leidde de Quaker-moraliteit hen vanzelfsprekend naar een beleid van lage marges en hoge omloopsnelheid. Zoals Henry Ford later aantoonde, kan dit potentieel veel winstgevender zijn. Zij volgden deze bedrijfsstrategie omdat zij menen dat het hun plicht was hun klant niet te bedriegen, maar het bleek de beste manier te zijn om hun zaken uit te breiden. De Quakers bleken goede zakenpartners te zijn, waardoor hun klanten keer op keer terugkeerden; er was aan beide zijden winst te behalen. Als een gemeenschap met een hoge besparingsgraad die haar verplichtingen eerde, hadden de Quakers bovendien een voorsprong als bankiers, en het lidmaatschap van de Quakers vormde op zich al een bedrijfsmiddel dat vertrouwen wekte.

Helaas kunnen dergelijke zakelijke voordelen worden uitgehold door het succes dat ze zelf teweegbrengen. Landen doorlopen een cyclus, die de basis vormde voor de sociologische theorie van Adam Ferguson in de achttiende eeuw, van armoede en hard werken, naar rijkdom, naar luxe, naar decadentie en vervolgens naar achteruitgang. De oude Romeinen keken zelf terug op de deugden van de republikeinse periode, toen het Rijk werd opgebouwd, en betreurden de luxe en luiheid die zij als oorzaak van hun ondergang beschouwden. Deze ondermijning van de ijverige deugden door welvaart kan verrassend snel plaatsvinden. De Duitsers zijn nog steeds een capabel en efficiënt volk, maar ze werken bij uitstek niet meer zo hard als zij deden toen ze hun land herbouwden na de verwoestende nederlaag in 1945. In twee generaties zijn zij overgegaan van lange uren werken, bijna met blote handen, onder omstandigheden van acute armoede, naar korte werktijden voor het hoogste loon en de duurste sociale voorzieningen op aarde. In oktober 1995 werd de Petersburg-verklaring ondertekend door zestien Duitse werkgeversverenigingen. Het is een overzicht van goed onderbouwde klachten, die de achteruitgang van de industriële moraal in Duitsland weerspiegelen.

> De belastingdruk in Duitsland bereikte in 1995 recordhoogten, vooral door de solidariteitstoeslag en de bijdragen aan de langdurige zorgverzekering. Met een totale belasting op ondernemingen van meer dan 60 procent ligt Duitsland ver boven het internationale vergelijkingsniveau van 35 tot 40 procent. Gewoonten in de publieke sector, zoals gereguleerde promoties, een baan voor het leven en hogere pensioenuitkeringen, moeten worden vervangen door de vrijemarkregels van meritocratische promotie en beloning. Doordat Duitsland de hoogste arbeidskosten ter wereld heeft, moet het loonbeleid bijdragen aan de vermindering van de werkloosheid door de kosten voor ondernemingen te verlagen... Loonstijgingen zouden moeten worden gemeten op basis van concurrentievermogen en productiviteit.... Het gedrag van de vakbonden moet veranderen. Het jaarlijkse ritueel van campagnes, eisen, werknemersmobilisatie, dreigementen en waarschuwingsstakingen is schadelijk.

Deze zorg dat de Duitsers – in het bijzonder de jongeren en de erfgenamen van de welvaart – de gewoonte van hard werken zijn kwijtgeraakt, wordt gedeeld door bondskanselier Kohl.

Het bestaande arbeidscontract bij Volkswagen kent het hoogste loon toe voor autowerkers ter wereld, waaraan ook sociale zekerheidsbelastingen moeten worden toegevoegd, in ruil voor een werkweek van 28 uur – vier dagen van elk zeven uur. Het naoorlogse Duitsland is nu een massale exporteur van banen. In het midden van de negentiende eeuw werden de Britten beschouwd als de meest efficiënte industriële natie, een reputatie die zij zeker een eeuw later hadden verloren. De cyclus van welvaart ondermijnt ongetwijfeld de deugden van hard werken en bescheiden verwachtingen, die bestaan in de vroege fasen van een succesvolle industriële ontwikkeling. Naties zijn niet in staat hun aanvankelijke deugden te behouden, net zoals individuen hebberig en lui kunnen worden bij een te gemakkelijke vorm van succes.

Wereldwijde investeringen belonen ongetwijfeld deze ijverige deugden en straffen degenen die hebberig en lui worden, zoals het betaamt. Inderdaad, men zou kunnen stellen dat een degelijke investering zowel op morele als zuiver financiële gronden moet worden beoordeeld. De Engelsman in de achttiende eeuw die in het kapitaal van een Quakerbank investeerde, deed het al naar alle waarschijnlijkheid erg goed. In de negentiende eeuw investeerden de Quakers in chocoladebedrijven, omdat zij aannamen dat cacao gezonder was dan alcohol. Waarschijnlijk is dat zo. Toch was een investering in Fry's of Cadbury's zeker een goede zet. Investeerders moeten erop toezien de perioden van decadentie te vermijden. Ook al behoudt Duitsland een sterke positie op de Europese markt en beschikt het over hoge industriële vaardigheden, hoge arbeidskosten en korte werktijden hebben al het toekomstige potentieel van Duitsland verminderd.

Sociale moraliteit en economisch succes zijn onlosmakelijk met elkaar verbonden. Maar welke factoren helpen de sociale moraliteit te behouden, of juist ondermijnen? Arnold Toynbee, de grote filosofisch-historicus van de eerste helft van de twintigste eeuw, formuleerde de theorie van uitdaging en respons. Samenlevingen worden verkwikt door uitdagingen en ontwikkelen deugdzaamheid waarvan ze niet eens wisten dat ze die bezaten.

Er is altijd al een besef geweest dat moeilijke tijden vaak gezondere reacties teweegbrengen dan periodes van welvaart. In ons persoonlijke leven proberen we het allemaal comfortabel te hebben; we hopen in een huis te wonen waar we van genieten, een baan te hebben die ons bevalt, genoeg geld op de bank te hebben, enzovoort. De strijd om deze doelen te bereiken is belonend. We studeren op school, we trainen onszelf, we werken hard; en ons loonbeleid moet bijdragen aan het terugdringen van de werkloosheid door de kosten voor ondernemingen te verlagen. Loonstijgingen zouden gemeten moeten worden naar concurrentiekracht en productiviteit. Het gedrag van de vakbonden moet veranderen. Het jaarlijkse ritueel van campagnes, eisen, mobilisaties van werknemers, dreigementen en waarschuwingsstakingen is schadelijk.

Bij veel mensen zorgt het bereiken van deze doelen juist voor een soort valkuil. De strijd blijkt aantrekkelijker dan de prestatie zelf. De grote Zwitserse psycholoog Carl Jung had begin deze eeuw een Amerikaanse zakenman als patiënt. Die zakenman had als jongeman dezelfde ambities. Hij had gewerkt om zijn eigen bedrijf op te richten en om voldoende geld te verdienen zodat hij met veertig met pensioen kon gaan. Hij trouwde met een jonge en aantrekkelijke vrouw, kocht een prachtig huis, kreeg een jong gezin, zijn bedrijf was zeer succesvol en tegen zijn veertigste was hij er werkelijk in geslaagd zijn bedrijf te verkopen en met pensioen te gaan, als een rijke en onafhankelijke man met ogenschijnlijk niets om zich zorgen over te maken. In eerste instantie genoot hij van zijn vrijheid en kon hij doen wat hij zichzelf al lang had beloofd. Hij nam zijn gezin mee naar Europa; ze bezochten kunstgalerijen en dergelijke. Maar geleidelijk aan begonnen die interesses, en zijn gevoel van vrijheid zelf, te vervagen. Hij ging terugkijken op de periode dat hij niet vrij was, toen hij dag en nacht aan zijn bedrijf werkte en alle gebruikelijke zakenzorgen had, en beschouwde die tijd als de gelukkigste periode van zijn leven. Hij raakte in een depressie, waardoor zijn vrouw hem bij Jung als patiënt bracht. Jung stelde in wezen vast dat hij geen uitlaatklep had voor zijn creatieve energie, die naar binnen gekeerd was en hem verwoestte. De diagnose was wellicht correct, maar leidde niet tot een genezing. De zakenman herstelde nooit van zijn zenuwinzinking.

Voor mensen is de strijd belangrijker dan de prestatie zelf; wij zijn gemaakt voor actie en succes kan uiteindelijk een grote teleurstelling blijken te zijn. De ambitie, wat die ook moge zijn, zet de strijd in gang, maar de strijd is aangenamer dan het uiteindelijke resultaat, zelfs wanneer het doel volledig wordt bereikt. En natuurlijk kunnen de meeste mensen hun doelen slechts gedeeltelijk verwezenlijken. De meesten van ons hebben niet zoveel geld als we zouden willen en wonen niet in ons droomhuis. We moeten genoegen nemen met minder.

Het besef dat deugdzaamheid dynamisch is, dat zij vooral bestaat uit de inspanning in plaats van het resultaat, ontwikkelde zich op verschillende manieren in de negentiende eeuw. Er is een bekend gedicht van Arthur Hugh Clough dat veel mensen troost bood in de strijd om leven en dood tijdens de Tweede Wereldoorlog. Het is opmerkelijk dat het zelfmoordcijfer in de strijdende landen tijdens de Tweede Wereldoorlog daalde; zelfs de strijd van oorlog kan beter zijn dan de depressie van inactiviteit.

> *Zeg niet: de strijd is vergeefs,\
Het werk en de wonden zijn tevergeefs,\
De vijand zakt niet in, noch verzwakt,\
En zoals het was, blijft het bestaan.*

> *Als hoop misleidt, kunnen angsten ook leugenaars zijn;\
Misschien is het zo, verborgen in die rook daar,\
Dat je kameraden nu de vluchtenden achtervolgen,\
En, ware het niet voor jou, het veld in bezit hebben.*

> *Want terwijl de vermoeide golven, tevergeefs brekend,\
Lijken hier geen pijnlijke duim vooruit te komen,\
Komt ver weg, door kreken en inhammen gevormd,\
Stil binnenstromend, overspoelend de zee.*

> *En niet slechts via oosterse ramen,\
Wanneer het daglicht doorbreekt, treedt het binnen in het licht,\
Voorin klimt de zon langzaam, oh zo langzaam,\
Maar naar het westen, kijk: het land is helder.*

Deze actieve competitie spreekt nog steeds de moderne gevoeligheid aan. Immers, zo leiden vele moderne mannen en vrouwen hun leven, in een voortdurende strijd om de kansen van een mogelijk vijandige omgeving te grijpen. We leven allemaal in een competitieve wereld, en de meesten van ons kiezen er niet voor er buiten te blijven. Natuurlijk is er het contemplatieve, spirituele temperament, maar dat is zeldzaam.

Een vergelijkbare negentiende-eeuwse opvatting van deze dynamische moraal ontwikkelde William James, de grootste van de Amerikaanse filosofen, in een toespraak voor de Yale Philosophical Club in 1891:

> Het diepste verschil, praktisch gezien, in het morele leven van de mens is het verschil tussen de ontspannen en de inspannende stemming.  
> Wanneer we in de ontspannen stemming verkeren, is het afwijken van het huidige kwaad onze doorslaggevende overweging.  
> De inspannende stemming daarentegen maakt ons geheel onverschillig voor het huidige kwaad, mits het hogere ideaal wordt bereikt.  
> Het vermogen voor de inspannende stemming sluimert waarschijnlijk in iedere mens, maar bij sommigen wordt het moeilijk gewekt.  
> Het verlangt naar wildere passies om gewekt te worden, naar grote angsten, liefdes en verontwaardiging; of naar de diep doordringende roep van een van de hogere trouwswaarden, zoals rechtvaardigheid, waarheid en vrijheid.  
> Een sterke verlichting is een noodzaak voor haar visie; en een wereld waarin alle bergen neerstorten en alle valleien worden verheven, is geen gastvrije woonplaats voor die stemming.  
> Dit is de reden dat bij een eenzame denker deze stemming voor eeuwig kan sluimeren zonder te ontwaken.  
> Zijn verschillende idealen, waarvan hij weet dat het louter zijn persoonlijke voorkeuren zijn, hebben vrijwel dezelfde symbolische waarde: hij kan er naar hartenlust mee jongleren.  
> Dit is ook de reden dat, in een louter menselijke wereld zonder God, de oproep tot onze morele energie tekortschiet in haar maximaal stimulerende kracht.  
> Het leven is, weliswaar, zelfs in zo'n wereld een oprechte ethische symfonie; maar het wordt gespeeld binnen het bereik van een paar arme octaven, en de oneindige schaal van waarden slaagt er niet in zich open te stellen.

William James geloofde dat de dynamische moraal – die bestaat uit doen in plaats van louter zijn, uit handelen in plaats van afzien van actie – uitgebreid kan worden naar de religieuze sfeer. Ook in het werk van Adam Smith (1776) komt een krachtige ontwikkeling tot uiting in de moraal van competitie en overleving – de morele doctrine van de hedendaagse wereldwijde economische orde – een centraal thema dat zorgvuldig opnieuw overwogen dient te worden.

De overheersende gedachte binnen het darwinisme is dat soorten overleven door zich aan te passen aan hun omgeving en dat dit proces van natuurlijke selectie de kenmerken van de soorten vormt. Bij dieren is dit proces het resultaat van willekeurige mutaties, waarvan nu bekend is dat ze behoren tot een genetisch proces waar Darwin zelf slechts op kon raden. Het voortbestaan van menselijke samenlevingen hangt daarentegen af van culturele keuzes die gebaseerd zijn op menselijke intelligentie. Cultuur verandert de menselijke samenleving op dezelfde wijze als genen andere soorten veranderen. Verandering kan daarom veel sneller plaatsvinden in onze samenlevingen; het hoeft niet door vele generaties te gaan, zoals wanneer het afhangt van willekeurige genetische mutaties.

In plaats van de natuurlijke selectie bij dieren hebben mensen culturele selectie ontwikkeld, waarbij sommige culturen in een bepaald stadium van de menselijke geschiedenis nieuwe technologieën introduceerden die hen een beslissende voorsprong gaven in het vergaren van rijkdom of het verwerven van macht. Het culturele voordeel van nieuwe technologieën – zoals de mens in het ijzertijdperk ten opzichte van de mens in het bronzen tijdperk, of de elektronische mens tegenover de mechanische mens – is doorslaggevend. Adam Smith was misschien niet de eerste schrijver op economisch gebied die het welzijn van naties reduceerde tot de handelingen van individuen, maar hij verwoordde het het meest beknopt en met het grootste gezag:

> Elk individu spant zich voortdurend in om de meest voordelige bestemming te vinden voor het kapitaal dat hij tot zijn beschikking heeft. Het is immers zijn eigen voordeel – en niet dat van de samenleving – dat hij voor ogen heeft. Maar de bespiegeling over zijn eigen voordeel leidt hem, natuurlijk of eigenlijk noodzakelijk, ertoe te verkiezen datgene wat het meest voordelig is voor de samenleving.

Thomas Malthus, de grondlegger van de bevolkingsstudies, zag dat het argument van Adam Smith niet alleen op de ontwikkeling van de economieën van naties van toepassing was, maar ook op het voortbestaan van menselijke populaties. Hij is vooral bekend om zijn stelling dat ‘de bevolking, wanneer zij niet wordt ingeperkt, toeneemt volgens een geometrische verhouding, terwijl het levensonderhoud slechts volgens een rekenkundige verhouding toeneemt. Een lichte kennismaking met getallen zal de immensiteit van de eerste macht vergeleken met de tweede aantonen.’

Malthus zag al, lang voor Darwin, dat hetzelfde principe in de hele natuur van toepassing is:

> Door de dieren- en plantenrijken heeft de natuur de zaden des levens met de meest overvloedige en royale hand verspreid. Zij is betrekkelijk zuinig geweest met de beschikbare ruimte en de voeding die nodig is om hen groot te brengen. De kiemen van het bestaan, vervat in dit stukje aarde, met overvloedig voedsel en ruime uitbreidingsmogelijkheden, zouden in de loop van enkele duizenden jaren miljoenen werelden vullen. De noodzaak, die alomvattende en allesbepalende wet van de natuur, houdt hen binnen de vastgestelde grenzen.

De wijze waarop de wereld zich ontwikkelt, al in de tijd van Adam Smith en Malthus, werd tegen het einde van de achttiende eeuw al erkend als dynamisch, wat in feite altijd zo is geweest. De menselijke soort, slechts één van de velen, wordt gedwongen te concurreren door de kloof tussen haar onbeperkte voortplantingscapaciteit en haar beperkte vermogen om voedsel te produceren. Het voortbestaan van menselijke samenlevingen, net als dat van diersoorten, hangt af van een succesvolle aanpassing aan de omgeving. Een dynamische moraliteit houdt zich dan ook bezig met het overwinnen van de problemen van aanpassing. Dit wordt het best bereikt door individuen die hun eigen handelingen afstemmen op de kansen die de omgeving biedt en zo de in de samenleving beschikbare middelen optimaal benutten.

Malthus zag al dat de ideeën van Adam Smith de wereld hadden veranderd en schreef dat zijn nieuwe betoog over de bevolking niet nieuw was: "De principes waarop het berust, zijn deels uitgelegd door Hume en deels door Dr. Adam Smith." Hij bemerkte tevens dat deze voortdurende strijd om te overleven een morele, en niet louter een praktische, zaak was. De laatste alinea van het "Essay" uit 1798 luidt als volgt:

> Het kwaad bestaat in de wereld, niet om wanhoop te zaaien, maar om tot actie aan te zetten. Wij moeten het niet passief ondergaan, maar ons inspannen om het te vermijden. Het is niet alleen in het belang, maar ook de plicht van ieder individu, om met alle macht het kwaad van zichzelf en van een zo groot mogelijke kring waarop hij invloed kan uitoefenen te verwijderen; en hoe meer hij zich in deze plicht inzet, hoe wijzer hij zijn inspanningen richt en hoe succesvoller die zijn; hoe meer hij waarschijnlijk zijn eigen geest zal verbeteren en verheffen, en hoe vollediger hij lijkt te voldoen aan de wil van zijn Schepper.

Misschien kan men Darwins gevoel voor het belang van dit betoog illustreren aan de hand van zijn samenvatting van de inhoud van hoofdstuk 3 van zijn baanbrekende boek On the Origin of Species, dat voor het eerst werd gepubliceerd in 1859. Hij noemde dit cruciale hoofdstuk "*Struggle for Existence*." De onderwerpstitels luiden als volgt: "Betekenis van natuurlijke selectie – de term in brede zin gebruikt – geometrische vermenigvuldigingskracht – snelle toename van ingeburgerde dieren en planten – de aard van de remmingen op groei – universele concurrentie – effecten van het klimaat – bescherming door het aantal individuen – complexe relaties tussen alle dieren en planten in de natuur – de strijd om het leven, het meest hevig tussen individuen en variëteiten van dezelfde soort; vaak heviger tussen soorten van hetzelfde geslacht – de relatie tussen organismen, de belangrijkste van alle relaties."

Sinds 1776 is het duidelijk dat de beste manier om de welvaart van naties te optimaliseren is door individuen de ruimte te geven hun eigen rendement op kapitaal te maximaliseren onder voorwaarden van vrije concurrentie. Sinds 1798 is gebleken dat het relatieve voortbestaan van populaties afhankelijk is van samenlevingen die voldoende economisch en politiek succes hebben om zichzelf te voeden, zich te beschermen tegen infectieziekten en hun bevolking in oorlogstijd te verdedigen. Sinds 1859 is duidelijk geworden dat het gehele drama van het leven, in het menselijke, het dierlijke of het plantaardige rijk, bestaat uit een voortdurende strijd om te overleven, waarbij de soorten of culturen die het dichtst bij elkaar staan de grootste rivalen kunnen zijn. Deze strijd vereist een dynamische moraliteit, die actief het kwaad afweert en er niet louter op reageert wanneer het zich voordoet.

Deze ideeën zijn zo krachtig gebleken dat het sinds hun ontstaan voor niemand mogelijk is geweest om over de aard van de mensheid of de vraagstukken van moraliteit na te denken zonder er tegelijkertijd op te reageren. Karl Marx geloofde net zo sterk in de strijd om te overleven als Charles Darwin, maar hij zag het als een oorlog tussen sociale klassen, die zelf door economische krachten tot stand kwamen. Adolf Hitler geloofde eveneens in de strijd om te overleven en beschouwde zijn eigen politieke loopbaan bijna uitsluitend in die termen. Hij was echter van mening dat de strijd werd gestreden tussen verschillende rassen. Marx, Lenin, Stalin, Mao en Hitler kunnen allen als sociaal-Darwinisten worden bestempeld, omdat zij de strijd om te overleven – ‘Mein Kampf’, zoals Hitler het noemde – als de centrale politieke kwestie zagen. De marxisten beschouwden sociale klassen als afzonderlijke soorten; de nazi’s zagen rassen op dezelfde wijze.

Dit leidt echter niet tot een dynamische moraliteit, zoals Malthus voor ogen had, maar tot een dynamische immoraliteit. Zowel het marxisme als het nazisme wilden hetzelfde probleem oplossen – de strijd om te overleven – maar dan door de concurrentie te vernietigen. Zij vielen vreemde gebieden binnen en zaaiden conflicten tussen verschillende klassen die streden om sociale macht, of tussen uiteenlopende rassen die werden gezien als economische uitbuiters (de gangbare beschuldiging van anti-semiten jegens joden) of als een gevaarlijke onderklasse (de angst die hun blanke vijanden voor zwarten koesterden). De Tweede Wereldoorlog was een poging van Adolf Hitler – die mislukte – om voor het Duitse volk een overlevingsvoordeel te behalen door potentiële concurrentie, in het bijzonder Slavische volkeren en joden, uit te schakelen. Paradoxaal genoeg bleek nederlaag in oorlog voordeliger voor Duitsland te zijn dan een nazi-overwinning ooit had kunnen zijn.

Het alternatief voor destructieve ‘interferentie’-concurrentie is samenwerkende concurrentie, en die vormt het centrale idee van Adam Smith, maar ook van Malthus en William James. Het archetype van destructieve concurrentie is de veroveraar, die zijn concurrenten vernietigt om hun bezittingen te bemachtigen – wat kan inhouden dat hij hun landen overneemt en zelfs hun volk tot slaaf maakt. Het archetype van samenwerkende concurrentie is de handelaar. Het is in het belang van de handelaar dat de klant tevreden is over de transactie, want alleen een tevreden klant komt terug voor meer handel. Eveneens is het voordelig als de klant welvarend is, want een welvarende klant heeft de middelen om meer te kopen. Verovering impliceert de vernietiging van de ander, terwijl handel draait om het bevredigen van de ander. Nu moderne technologie verovering tot een buitengewoon gevaarlijk beleid heeft gemaakt, is handel de enige rationele benadering van de overlevingskwesties geworden.

Deze onderlinge afhankelijkheid wordt versterkt door nog een centraal idee van Adam Smith – niet nieuw bij hem – namelijk de specialisatie van functies. De rijkdom der naties begint met een beroemde passage waarin Adam Smith opmerkt dat ‘de grootste vooruitgang in de productieve krachten van arbeid, en het grootste deel van de vaardigheid, behendigheid en oordeelsvermogen dat ergens op wordt toegepast, schijnbaar het resultaat is van de arbeidsverdeling.’ Hij wijst erop dat ‘het belangrijke ambacht van het vervaardigen van een speld op deze wijze is onderverdeeld in ongeveer achttien afzonderlijke handelingen, die in sommige fabrieken door verschillende arbeiders worden verricht.’ Hoe volkomener de specialisatie van functies, des te efficiënter de productie, maar zo’n economie is vanzelfsprekend ook sterk afhankelijk van samenwerking. Om succesvol te zijn, moet zij collectief opereren.

Een succesvolle sociale moraliteit moet daarom aan bepaalde criteria voldoen. Ze moet krachtig zijn – een zwakke moraliteit is kwetsbaar en ineffectief. Ze moet bijdragen aan de strijd om te overleven, maar dan op een samenwerkende in plaats van moorddadige wijze. Hitler bezat een sterke overlevingsmoraliteit, maar zijn destructieve karakter heeft bijna zijn eigen samenleving verwoest. Een goede sociale moraliteit moet bovendien dynamisch zijn, zodat ze aansluit bij de voortdurende veranderingen in de moderne technologie en in alle hedendaagse sociale systemen, en economisch efficiënt opereren. De combinatie van egalitaire en autoritaire ideeën in het Leninistische systeem werkte simpelweg niet. Toch zijn dat niet alle kenmerken waaraan men een sociale moraliteit zou moeten toeschrijven. Ze heeft ook als bredere doelstelling de samenleving aangenaam en saamhorig te maken. Bovendien moeten moraliteiten zich kunnen aanpassen en overleven; een broze moraliteit mag in onze generatie acceptabel lijken, maar in de volgende verworpen worden, terwijl een traditionele sociale moraliteit juist te inflexibel kan blijken om mee te bewegen met opeenvolgende veranderingen in de sociale structuur. Aan de andere kant is een puur relativistisch systeem helemaal geen moraliteit, omdat het geen duidelijke richtlijnen biedt voor gewenst gedrag.

Allereerst kunnen we alle sociale moraal in een context plaatsen. Een sterke gemeenschap, zelfs een virtuele gemeenschap, is afhankelijk van een breed aanvaarde moraal. De meest succesvolle periodes in de geschiedenis van samenlevingen lijken die te zijn waarin de collectieve moraal volledig wordt gedeeld. Zo'n moraal vervult niet alleen specifieke functies – zoals het verminderen van criminaliteit en het ondersteunen van familie- en sociale structuren – maar geeft burgers ook een gevoel van doelgerichtheid en richting. Een historische consensus over moraal lijkt afhankelijk te zijn van het bestaan van een dominante religie, of dat nu een staatsgodsdienst is die in de vroege periode voor de overleving van een verspreid volk zorgde; de islam met haar sociale regels; het katholicisme van de middeleeuwen; of het protestantisme van het vroege New England. De drie begrippen van een volk, een moraal en een religie zijn onlosmakelijk met elkaar verbonden en versterken elkaar.

In zo'n morele samenleving is de individuele burger in staat om binnen een kader van sociale steun te werken aan persoonlijke doelstellingen. Het is waar dat de morele wetten wat arbitrair kunnen lijken – of in ieder geval als zodanig worden ervaren door buitenstaanders. De orthodoxe jood verliest de vrijheid om varkensvlees of schelpdieren te eten en om op de sabbat te werken. De trouwe katholiek kan de vrijheid verliezen om kunstmatige anticonceptiva te gebruiken, om nog maar te zwijgen van de mogelijkheid tot abortus. De moslim kan de vrijheid verliezen om alcohol te drinken. De vrome confuciaan moet mogelijk een oncomfortabel lange rouwperiode voor zijn eerbiedwaardige vader doorstaan – zelfs Confucius waarschuwde dat rouwrituelen overdreven konden worden. Toch beschouwt iedere volgeling van deze geloofssystemen deze opvattingen als een kleine prijs voor een gedeeld en samenhangend gevoel van wereldorde, waarin het individu een vaste plaats heeft. Een orthodoxe jood zou er bijvoorbeeld goed voor kunnen pleiten dat het in acht nemen van de sabbat een geringe opoffering is voor de voordelen van de wet of de kracht van het joodse gezin. Een gedeelde moraal in een tolerante samenleving was het ideaal van John Locke en van de vroege filosofen van vrijheid. Zij geloofden zeker niet dat een samenleving – van welke aard dan ook – zonder regels in stand gehouden kan worden, maar vonden dat de regels onderworpen moesten zijn aan de hoogste rede en dat mensen slechts gedwongen zouden moeten worden de essentiële regels te aanvaarden. Zij erkenden dat dwang onvermijdelijk is in de sociale moraal, met name bij de bescherming van het leven en het eigendom, omdat zij van mening waren dat geen enkele samenleving kan overleven als er geen veiligheid is. Tegelijkertijd hanteerden zij een vrijwel absolute tolerantie ten aanzien van persoonlijke keuzes die het welzijn van anderen niet beïnvloeden. De confuciaan, die veertig dagen rouwde om zijn vader, kon naast de jood wonen – die de sabbat eerde – zonder elkaar te hinderen of te proberen de ander te dwingen zijn eigen religieuze praktijken te volgen.

Uit deze gecombineerde leer van sociale moraal inzake essentiële zaken en tolerantie in persoonlijke beslissingen ontstaat een kernmoraal die op alle burgers moet worden opgelegd, evenals een vrijwillige ethiek die zij als individuen of als leden van subgroepen binnen de samenleving accepteren. Wanneer een benedictijner monnik geloften van armoede, kuisheid en gehoorzaamheid aflegt, doet hij dat als lid van zo'n subgroep. Hij roept niet alle katholieken – laat staan al zijn medeburgers – op om dezelfde geloften af te leggen of dezelfde regels na te leven. Hij gehoorzaamt de bevelen van zijn abt, maar verwacht niet dat iemand buiten zijn klooster hier aandacht aan besteedt. Het naleven van deze optionele aspecten van de sociale moraal hoeft niet universeel te zijn, maar de kernmoraal moet wel gedeeld worden; degenen die deze kernmoraal niet accepteren, schaden zowel de samenleving als henzelf. In het extreme geval biedt een samenleving die overspoeld wordt door rovers die niet aarzelen te vermoorden – zoals grote delen van Europa ná de val van het Romeinse Rijk – niemand een bevredigend bestaan, zelfs de rovers zelf niet, want zij worden voortdurend bedreigd door andere moordenaars. Dit geldt in gelijke mate voor sommige binnenstedelijke gebieden in de Verenigde Staten van vandaag. Anarchie is immers geen ideaal model van samenleving, want zonder handhaving van de wet is er geen menselijke veiligheid.

Wanneer men de krachten bekijkt die vijandig staan tegenover de moraal van de samenleving, moet men deze kernmoraal als uitgangspunt nemen – een moraal die in de meeste moderne religieuze systemen globaal gezien vergelijkbaar is. Ten minste twee van de Tien Geboden uit het Oude Testament – voor christenen – of de Thora – voor joden – kunnen als universeel worden beschouwd voor alles wat men als religie zou kunnen herkennen: ‘Gij zult niet doodslaan’ en ‘Gij zult niet stelen.’ Men kan zelfs nog verder gaan. Bijna alle serieuze agnosten zouden zowel moord als diefstal – de ultieme bedreigingen voor het leven en voor eigendom – als verboden beschouwen en accepteren dat de samenleving het recht heeft mensen te straffen die vermoorden of beroven. Over de passende straf voor een specifieke misdaad kunnen zij wellicht van mening verschillen, maar niet over het fundamentele recht van de samenleving om als zodanig te straffen.

John Locke formuleerde het precies: iedereen heeft recht op ‘leven, vrijheid en bezit.’ In 1776 voegde Thomas Jefferson nog een van Locke’s uitdrukkingen toe, ‘het nastreven van geluk.’ Dat is een zeer mooie uitdrukking en een nobel streven, maar ‘leven, vrijheid en bezit’ is praktischer en meer gegrond dan ‘leven, vrijheid en het nastreven van geluk.’ De samenleving is in hoge mate afhankelijk van het recht op leven en het recht op eigendom. In de praktijk leert de geschiedenis dat deze rechten uitsluitend beschermd kunnen worden in een vrije samenleving. Is de staat alomtegenwoordig en almachtig, dan wordt zij de grote vijand van het leven – zoals in agressieworlogen – en van individueel eigendom, doordat zij een onevenredig deel van de nationale rijkdom opeist voor haar eigen, vaak ongewenste en altijd verspillende doeleinden.

De kernmoraal staat echter onder vuur in de meest geavanceerde naties, deels door de krachten van de moderniteit die deze landen hun technologische voorsprong verschaffen. De Verenigde Staten zijn de toonaangevende technologische macht ter wereld. Veel mensen, waaronder de meeste Amerikanen, zouden de Verenigde Staten tot een moreel voorbeeld voor de rest van de wereld hebben gerekend tot ver in de vroege jaren zestig. Tegenwoordig wordt die opvatting zelden meer geuit, zelfs niet door Amerikanen die trots op hun land zijn. Men kon, zoals de wereld deed, niet naar het proces tegen O.J. Simpson luisteren en de Verenigde Staten beschouwen als de eenvoudige, deugdzame republiek waarmee het ooit begon.

Als men terugdenkt aan de benamingen van het oude Amerika, dan weerspiegelden deze de behoeften van een grensmaatschappij die, zelfs in de grote steden, de houding van haar burgers beïnvloedde. Grensgebieden zijn democratische plekken: mensen voelen zich gelijkwaardig en de vroege Amerikanen wierpen de klassehiërarchieën van Europa overboord. Zelfs gebonden dienaren, vanuit Engeland als gevangenen gestuurd, vestigden zich als onafhankelijke ambachtslieden, boeren of vrije arbeiders zodra hun contractperiode ten einde was. De lonen waren hoger dan in Europa en de kosten van levensbehoeften laag, hoewel geïmporteerde vervaardigde goederen duur waren. In de grensgebieden was men sterk op elkaar aangewezen, en hoewel het leven hard was, bleek het in Europese termen voorspoedig. Immigranten begonnen wellicht als laagbetaalde arbeiders in de sloppenwijken van Boston en New York, maar ze wisten daar meestal al snel aan te ontsnappen en generatie na generatie vonden zij voorspoed. Na de burgeroorlog zagen de zwarten zichzelf alsof zij tot een andere groep immigranten behoorden, en velen van hen deelden deze Amerikaanse waarden en doelstellingen. Hieruit ontwikkelde zich de zwarte middenklasse.

Deze aspiratie, versterkt door de daadwerkelijke ervaring op de grens en de invloed van zowel protestantse als katholieke kerken, vormde het patriottisme van de Amerikanen. Zij geloofden dat zij in Gods eigen land leefden, een opvatting die op unieke wijze werd geleid door democratische idealen en het christelijk geloof – de eerste en meest succesvolle van 's werelds democratieën. Dit beeld is bekend; het wordt belichaamd in de afbeelding die wij bijna allen van Abraham Lincoln hebben, al vinden sommigen in het Zuiden hem nog steeds de man die de gruwelen van de eerste moderne oorlog ontketende om te voorkomen dat vrije staten een unie verlieten die zij niet langer vertrouwden.

Niettemin blijft het beeld van Lincoln – ruig, eenvoudig, eerlijk en welbespraakt – het hoogste Amerikaanse ideaal, en is het in wezen een moreel voorbeeld. Veel Amerikanen blijven de levendige oorspronkelijke tegenstelling voelen tussen de democratische energie van het nieuwe land en de versleten hiërarchieën van Europa. Dit ideaal van een in wezen dynamische meritocratie is voor de buitenlander moeilijk te herkennen in het hedendaagse Los Angeles, New York, Houston of Washington, hoewel er in de grote voorstedelijke gebieden en op het platteland nog meer dan slechts sporen van te vinden zijn. De Amerikaanse puriteinse ethiek, met al haar historische betekenis, houdt het best stand ten noorden van de sneeuwgrens, terwijl het ondernemende dynamisme breder verspreid is.

Amerikanen wijzen vaak op het verval van de grote steden, die tot broedplaatsen voor criminaliteit – met name de narco-industrie – zijn geworden, als het ernstigste symptoom van het afnemende gemeenschappelijke morele besef. De meesten erkennen ook dat er een botsing plaatsvindt tussen diverse morele culturen, die allemaal wedijveren om hun aanspraak en gezag. De 'politiek correcte' cultuur wijst veel, maar niet alle, morele principes die de oude cultuur staarden af. Zij benadrukt fel de rol en de rechten van groepen die historisch gezien zijn uitgebuit door een dominante witte mannencultuur en verwerpt die cultuur, ondanks dat deze de oprichtingscultuur van de Verenigde Staten is.

De dominante mannencultuur van de eerste helft van de twintigste eeuw draaide om het voortbestaan van het kerngezin. Historisch gezien gaf dit de echtgenoot en vader ten minste een symbolische dominantie in huis, alhoewel het huishouden in de praktijk vaak door de echtgenote en moeder werd gerund, met de vaak onderdanige acceptatie van de nominale meester. Het verleende de mannelijke baas een reële dominantie op de werkvloer, een dominantie die de feministische beweging tot op heden weliswaar heeft betwist, maar niet heeft omgekeerd. Het belang van het gezin en de historische christelijke leer verboden abortus. De oude moraal beschouwde abortus als onrechtmatige doding, volstrekt ontoelaatbaar, en de aanhangers van de traditionele moraal denken dat nog steeds. Aanhangers van de nieuwe moraal denken het tegendeel. In *Roe v. Wade* baseerde het Hooggerechtshof het grondwettelijke recht op abortus – dat voorheen als een aangelegenheid voor de individuele staten werd beschouwd – op de doctrine van het recht op privacy, een recht dat zelf ver verwijderd is van enige bewoording die daadwerkelijk in de Grondwet of haar amendementen voorkomt.

De privacy van een vrouw werd zo geïnterpreteerd dat zij het recht had om wel of geen kinderen te krijgen, ongeacht de consequenties voor het embryo. Het Hooggerechtshof beschouwde het embryo niet als genieter van enige grondwettelijke rechten — embryo’s bleken in de late twintigste eeuw dezelfde extraconstitutionele entiteiten te zijn als slaven in de eerste helft van de negentiende eeuw. 'Leven, vrijheid en de zoektocht naar geluk' was niet van toepassing op slaven, en de bewoordingen van de verklaring van onafhankelijkheid werden door de rechters in *Roe v. Wade* niet op embryo’s toegepast.

Het debat over abortus is het uiterste voorbeeld van het conflict tussen de oude en de nieuwe moraal, hoewel er in andere domeinen eveneens opmerkelijke conflicten zijn waarin de oude sociale organisatie met haar moraal door de nieuwe wordt uitgedaagd. De traditionele christelijke moraal, zowel in protestantse als katholieke kerken, legde grote nadruk op seksuele rollen: geen heteroseksuele gemeenschap buiten of vóór het huwelijk; geen genitale homoseksuele relaties. Lesbianisme werd minder nadrukkelijk benadrukt, omdat de samenleving het bestaan ervan nauwelijks erkende. Toen koningin Victoria er voor het eerst van hoorde, weigerde zij koppig te geloven dat dergelijke zaken tussen vrouwen plaatsvonden. Politieke correctheid is de moraal van zogenaamd onderdrukte groepen. Homoseksuelen claimden een gelijke geldigheid voor hun levensstijl en daagden de traditionele afkeuring van hun seksuele gedrag uit. 'Homofobie' werd op zich gezien als een schandalige vorm van vooroordeel, vergelijkbaar met rassendiscriminatie. Het bekritiseren van homoseksuelen wordt door de nieuwe moraal gezien als even onaanvaardbaar als kritiek op zwarten, joden of vrouwen.

Tegelijkertijd werden ook andere seksuele taboes afgebroken of afgeschaft. In de jaren zestig kwam er een nieuwe golf van vrije liefde, deels gebaseerd op de schijnbare betrouwbaarheid van de anticonceptiepil voor vrouwen, maar ook gestimuleerd door stemmingsveranderende drugs en popmuziek. Dit leidde tot een groeiende mate van samenwonen buiten het huwelijk. Tegen de jaren negentig werd het in Groot-Brittannië – een samenleving die wat ouderwets was vergeleken met de meeste delen van de Verenigde Staten – als volstrekt normaal beschouwd dat prins Edward in Buckingham Palace met zijn vriendin sliep, in een stabiele maar ongehuwde relatie, vergelijkbaar met de wijze waarop studenten in de jaren zestig in hun studentenvertrekken met elkaar samenloften. Weinigen vonden het vreemd dat koningin Elizabeth II, het hoofd van de Church of England, het gedrag van haar jongste zoon tolereerde, daar de huwelijken van haar drie oudere kinderen al waren verbroken. Degenen die klaagden, werden gezien als hopeloos ouderwets en betweterig. Toch waren er nog steeds velen die de oude moraal als te verkiezen beschouwden, ook al leefden zij er niet naar en verwachtten zij niet dat hun kinderen dat na een vrij jonge leeftijd zouden doen.

De politiek correcte beweging kende ook een puriteinse zijde. Omdat deze voortkwam uit de vermeende belangen van vrouwen – gezien als de grootste van de onderdrukte groepen – ontwikkelde zij een zekere vijandigheid tegenover de mannelijke seksualiteit, zowel in agressieve als in voorheen als onschadelijk beschouwde vormen. Sommige vrouwen waren van mening dat alle mannen van nature verkrachters waren, en de natuurlijke afschuw voor verkrachting werd overdreven tot een algemene veroordeling van het mannelijk geslacht. Anderen concentreerden zich op seksuele intimidatie, een terechte klacht – vele mannen hebben zeer grove seksuele manieren – die in sommige triviale gevallen belachelijk werd. Er werd zelfs gesteld dat seksuele intimidatie al kon plaatsvinden door louter te kijken, zonder dat er een woord werd gezegd, laat staan fysiek contact. Daardoor kon de nieuwe moraal behoorlijk censurerend zijn. Witte mensen konden beschuldigd worden van raciale vooroordelen, niet omdat zij bevooroordeeld waren, maar omdat zij wit waren. Mannen konden beschuldigd worden van seksuele intimidatie omdat hun uitingen aantasten dat zij een vrouw aantrekkelijk vonden, iets wat in een eerdere generatie als een compliment werd gezien in plaats van als een belediging.

De politiek correcte en de fundamentalistische christelijke groepen oefenen bittere kritiek op elkaar uit, maar in de moderne wereld lijken ze opvallend veel op elkaar. Beiden beschouwen de autoriteit van een specifieke morele doctrine als universeel, ook al verschillen hun morele leerstellingen wezenlijk. Zij kunnen immers allebei bekritiseerd worden wegens een overdreven en zelfverzekerde moraliteit die ontbreekt aan diepgang, historisch perspectief en tolerantie. Men wijst hen de vermeende gelijkenis met het zeventiende-eeuwse puritanisme op, met zelfverzekerde moralisten zoals Oliver Cromwell in Engeland – die bijna naar Nieuw-Engeland emigreerde – of met de heksenjagers van Salem. Noch de vrouwenbeweging, in haar meer dogmatische vorm, noch de conservatieve predikanten van de Bible Belt kan verweten worden dat zij moreel tekortschieten; integendeel, hun moraliteit is juist overontwikkeld en star. Het hart van deze moraliteiten lijkt soms tot steen te zijn verworden. Zo’n verharding van de morele aders is net zo schadelijk voor de gedeelde moraliteit van de samenleving als de «alles mag»-anarchie waartegen zij protesteert.

Het is een vertekening van de morele krachten, een verharding tot zelfgerechtigdheid. Het farizeïsme – het geloof dat men uitzonderlijk deugdzaam is – is zo oud als de mensheid en was bijzonder verwerpelijk voor Jezus Christus. De erosie van de moraliteit – het geloof dat ethische keuzes louter een kwestie van persoonlijke voorkeur zijn, net zo individueel als de keuze van kleding – is een recenter fenomeen. Dit geloof weerspiegelt de afwezigheid van een gedeelde moraliteit. Het tilt de klassieke leer over vrijheid naar een geheel nieuw niveau en verandert «het nastreven van geluk» – zoals John Locke het oorspronkelijk bedoelde en Jefferson het in 1776 opvatte – in een hedonisme dat roekeloos is ten aanzien van de gevolgen.

De uitdrukking «het nastreven van geluk» is ontleend aan John Locke’s *Essay on Human Understanding* (1691). «De hoogste volmaaktheid van de intellectuele natuur ligt in een zorgvuldige zoektocht naar waarachtig en solide geluk, zodat de zorg voor onszelf – opdat wij het denkbeeldige niet verwarren met het reële – de noodzakelijke basis van onze vrijheid vormt.» Hij vervolgt door te stellen: «Niet iedereen vindt zijn geluk in hetzelfde… de geest heeft een andere smaak dan het gehemelte… Mensen mogen voor verschillende dingen kiezen, maar allen maken de juiste keuze, indien men hen beschouwt als een gezelschap arme insecten, waarvan sommigen bijen zijn, die zich verheugen over bloemen en hun zoetheid, en anderen kevers, die genieten van andere soorten kost.» Toch betoogt hij dat het verkiezen van ondeugd boven deugd «duidelijk een verkeerd oordeel» is. Hij hecht daarbij bijzondere nadruk aan het religieuze argument, maar menen tevens dat «de slechten hier het grootste nadeel hebben.» Hij is ervan overtuigd dat «moraliteit, wanneer deze op ware fundamenten is gevestigd, onvermijdelijk de keuze van iedereen zal bepalen die erover nadenkt.»

De Lockeniaanse doctrine van vrijheid geeft ongetwijfeld een bredere ruimte voor menselijke voorkeuren dan meer autoritaire morele systemen die trachten alle mensen gelijk te behandelen en uniformiteit in gedrag op te leggen. Toch erkent de klassieke leer van vrijheid al snel de noodzaak van collectieve morele imperatieven, waaronder het respect voor andere mensen in de samenleving – in het bijzonder voor hun leven en het vreedzaam bezit van hun eigendommen volgens de wet. Een algemene erosie van de collectieve moraliteit vormt een bedreiging voor de vrijheid, zowel direct, doordat het een element van anarchie introduceert, als indirect, doordat het de meest autoritaire krachten in de samenleving in de hand werkt. We kunnen de geschiedenis van de publieke moraliteit zien als een cyclus tussen wanorde en autoritarisme; de moderne autoritaire morele stromingen, zowel het feminisme als het fundamentalisme, zijn ontstaan als een cyclische reactie op het hedonisme van de jaren zestig.

We hebben al enkele kenmerken beschreven van de nieuwe wereld van de volgende eeuw. Deze zal worden bepaald door twee hoofdkrakten: de technologische verschuiving die de economieën van Azië opengaat en de nieuwe wereldwijde elektronische communicaties die de burger steeds minder afhankelijk maken van de lokale overheid. De nieuwe technologie vervangt – of heeft al vervangen – vele middelmatige menselijke vaardigheden, zoals de productielijnwerker, de kantoormedewerker en, in toenemende mate, de middenmanager. Maar het heeft tevens de zeldzamere vaardigheden beloond door een internationale cognitieve elite van hoogopgeleide mensen te creëren, voor wie de nieuwe communicatiemiddelen de breedst mogelijke markt voor hun talenten openen. Net als de meeste elites is de cognitieve elite geneigd zichzelf als beter te beschouwen, is ze nogal arrogant en meent ze haar eigen normen te kunnen stellen. Daardoor raken zij vervreemd van de samenleving.

Tijdens de eerste helft van het volgende eeuw zal er een enorme overdracht van rijkdom plaatsvinden van het oude Westen naar het nieuwe Oosten. Politieke mislukkingen – en China is nog steeds een politiek achterhaald land – kunnen deze overdracht van rijkdom en strategische macht vertragen, maar zullen deze vrijwel zeker niet verhinderen. Ze kunnen het niet terugdraaien.

Deze verschuiving in rijkdom zal in ieder geval de grootst mogelijke druk uitoefenen op de door blanken gedomineerde landen van het noordelijk halfrond, op Europa en Noord-Amerika. Momenteel behoren ongeveer 750 miljoen mensen tot de geavanceerde landen in dit gebied; tot voor kort was Japan het enige Aziatische, niet-blanke land dat de Euro-Amerikaanse levensstandaard had bereikt, hoewel er etnisch Europese populaties waren in Nieuw-Zeeland, in Australië en in de blanke bevolking van zuidelijk Afrika. Zelfs in 1990 was de totale bevolking van de geavanceerde industriële landen slechts ongeveer 15 procent van de wereldbevolking van 5 miljard. De verdeling van de wereldwijde rijkdom was 15 procent rijk en 85 procent arm, wat sterk lijkt op de inkomensverdeling in geavanceerde industriële samenlevingen van honderd jaar geleden. Tegen 2050 is, in een versneld proces, de verwachting dat de geavanceerde economieën ongeveer 3 miljard mensen zullen omvatten uit een wereldbevolking die mogelijk is gestegen tot 7 miljard, oftewel een rijkdomsverdeling van 40 procent rijk en 60 procent arm. Tegen het einde van de eeuw zouden deze cijfers zelfs omgekeerd kunnen zijn, met een verdeling van 60 procent rijk en 40 procent arm, waarbij armoede met name geconcentreerd zal zijn in Afrika. De verschuiving tussen naties zal leiden tot een grotere gelijkheid in rijkdom, maar binnen landen zal het waarschijnlijk juist resulteren in een grotere ongelijkheid. De efficiënte gebruikers van talent en kapitaal zullen een beslissend voordeel hebben ten opzichte van mensen met matige vaardigheden of weinig kapitaal. Deze rijkdom zal uiterst mobiel zijn. De armen in de ontwikkelde wereld zullen de rijken niet kunnen belasten op de schaal van de twintigste eeuw; die landen die dat proberen, zullen achterop raken in een intens competitieve race.

Natuurlijk zal de totale productiviteit van de wereldeconomie blijven groeien, wellicht met een gemiddelde van 3 procent wereldwijd, mits er geen wereldoorlogen plaatsvinden. Als dat klopt, zal het totale wereldproduct elke vijfentwintig jaar verdubbelen, waardoor het in 2050 meer dan vier keer zo groot is als nu en tegen 2100 zestien tot twintig keer zo groot. Zelfs als de wereldbevolking tegen 2100 is gestegen tot 8 miljard, zal dat het wereld-BBP per hoofd tegen het einde van de eeuw tien keer het huidige niveau opleveren. Een dergelijke toename in rijkdom kan zowel de opkomst van de nieuwe industriële samenlevingen als de multimiljoeneninkomens van de cognitieve elite opvangen, en tegelijkertijd voor de rest van de geavanceerde arbeidskrachten een fatsoenlijke en stijgende levensstandaard bieden. Maar de inkomensverschillen zullen heel anders zijn dan die van de twintigste eeuw. In wereldtermen zullen de arme naties hun inkomens veel sneller zien groeien dan die van de rijke landen; nationaal gezien zullen de inkomens van de rijken, zoals in het Amerika van de jaren negentig, veel sneller stijgen dan die van midden- of lage inkomens. In de volgende eeuw zullen we getuige zijn van de opkomst van een wereld-superklasse, wellicht bestaande uit 500 miljoen zeer rijke mensen, waarvan 100 miljoen rijk genoeg zullen zijn om zich als soevereine individuen te onderscheiden.

Dit proces zal een onvermijdelijk gevolg hebben. Samenlevingen zullen veel minder homogeen worden; de natiestaat zal zwakker worden of geheel uiteenstorten; de cognitieve elite zal zichzelf als kosmopolitisch beschouwen. Al mensen die in dezelfde mondiale functies werken, ontwikkelen een cultuur die veel dichter bij die van hun collega’s in andere delen van de wereld ligt dan bij hun medeburgers in de oude natiestaten. Een investeringsbankier uit Londen zal zich waarschijnlijk meer thuis voelen in Seoel dan in Glasgow; een ambtenaar uit Washington voelt zich wellicht meer op zijn gemak in Bonn dan in de zwarte wijken van Washington zelf. We zijn al getuige van het fragmenterende effect dat dit proces heeft op morele waarden. De moraliteit van het individu wordt deels gevormd door de opvoeding, door wat iemand als kind geleerd heeft, en deels door de levenservaringen. Zowel de opleiding als de ervaringen van de cognitieve elite zullen kosmopolitisch zijn en mensen losmaken van hun lokale gemeenschappen.

Naarmate we de volgende eeuw ingaan, heeft een groot deel van de mensen in de groeiende cognitieve elite nauwelijks enige religieuze of morele opvoeding binnen het gezin gekregen. De meest voorkomende levensbeschouwing onder de elite is een agnostisch humanisme. Veel van deze families worden zelf verscheurd door echtscheidingen, hertrouw en daaropvolgende derde huwelijken. Het huwelijksmodel in Hollywood is niet universeel in de Verenigde Staten, maar de cognitieve elite in Euro-Amerika kent een hoog percentage echtscheidingen, waarschijnlijk gemiddeld een derde of meer. De kinderen van deze gescheiden ouders krijgen zelden een basisreligieuze opleiding en zijn zich bewust van de variaties in morele opvattingen tussen ouders, stiefouders en stiefbroers en -zussen. Als men de initiële morele vorming van deze groep vergelijkt met die in een Iers of Pools dorp, valt op dat de boerenopvoeding duidelijk een veel sterkere religieuze vorming biedt. Een goddeloze, wortelloze en rijke elite zal waarschijnlijk niet gelukkig zijn of geliefd worden.

Deze tekortkoming in de vroege morele opvoeding van wat de dominante economische groep van de volgende eeuw zal worden, zal waarschijnlijk door hun levenservaring nog verder worden versterkt. Deze mensen zullen de discipline van een gevorderde technische opleiding hebben, van de ene of de andere aard, om zich voor te bereiden op hun nieuwe rol als leiders van het nieuwe elektronische universum. Maar zij zullen daaruit slechts enkele van de morele lessen oppikken die historisch gezien de basis hebben gevormd voor menselijk sociaal gedrag. Volgens de maatstaven van Confucius, Boeddha of Plato (500 v.Chr.), van Sint-Paul (50 n.Chr.) of van Mahomet (600 n.Chr.) zouden zij morele analfabeten kunnen zijn. Zij leren de lessen van economische efficiëntie, het gebruik van hulpbronnen en het nastreven van geld, maar worden niets bijgebracht over de deugden van nederigheid of zelfopoffering, laat staan kuisheid. In wezen zullen de meesten van hen als heidenen worden opgevoed, met een waardenstelsel dat dichter bij dat van de late Romeinse Republiek ligt dan bij het christendom. Zelfs deze waarden zullen sterk individualistisch zijn in plaats van gedeeld. Zoals we hebben betoogd, kunnen samenlevingen alleen sterk zijn als echte morele waarden breed worden gedeeld. De ontwikkelde naties bewegen al richting een situatie waarin velen zwakke of beperkte morele waarden aanhangen, terwijl anderen dit compenseren door een felle vasthoudendheid aan irrationele waarden, en slechts weinige waarden door de gehele samenleving gemeenschappelijk worden gedragen. Zonder twijfel zullen sommige van de eerder beschreven ‘concurrerende territoriale clubs’ strenge morele normen opleggen aan wie er mag wonen.

Verschillen in rijkdom hebben op zichzelf historisch gezien geen fundamentele verschillen in religieuze waarden opgeleverd. In dichtbevolkte en stabiele samenlevingen met sterke tradities kan een steile hiërarchische structuur – ‘de rijke man in zijn kasteel, de arme man bij zijn poort’ – waarden verbergen die door de hele hiërarchie lopen, maar dit hangt af van de kracht van het gemeenschapsgevoel van zowel de rijken als de armen en van de sterkte van de sociale tradities. Geen van deze voorwaarden bestaat nu, en zowel het gemeenschapsgevoel als de traditie worden verzwakt door de economische en technologische revolutie die aan de gang is. Het leven van de velen en dat van de weinigen raakt steeds verder uit elkaar. De technologische revolutie is bereikt door een breuk met de oude manieren van werken. In elk domein wint de radicaal, terwijl de conventionele denker achterblijft en letterlijk uit de race valt. Onze politiek wordt misschien geleid door conventionele denkers – Bill Clinton, Helmut Kohl, John Major – maar onze meest succesvolle bedrijven worden geleid door radicalen met een scherp inzicht in de nieuwe technologische wereld; het archetype hiervan is Bill Gates. Het conventionele denken is in diskrediet geraakt door zijn onvermogen om met de snelheid en de schiere kracht van veranderingen om te gaan.

Toch werkt moraliteit anders. Als we de ‘wetenschap’ van Mozes, ontstaan rond 1000 v.Chr., onder de loep nemen, heeft die ons zeer weinig te vertellen. Het scheppingsverhaal in het Bijbelboek Genesis bevat weliswaar een theologische waarheid – dat God het universum en de mensheid heeft geschapen – maar biedt geen wetenschappelijke beschrijving van de daadwerkelijke ontwikkeling van fysieke structuren. Maar als we kijken naar de moraliteit van Mozes – de Tien Geboden – dan heeft dat ons veel te vertellen.

Respect voor ouders en trouw in het huwelijk zijn de beste manieren om het gezinsleven te behouden; gezinsleven is de beste manier om moreel gezonde kinderen op te voeden. Stelen schaadt zowel de dief als de slachtoffers en biedt een afschrikmiddel tegen arbeid en sparen. De maatschappelijke orde is afhankelijk van de oprechtheid van getuigen. Het is verkeerd om te vermoorden, enzovoort.

Op het gebied van wetenschap hebben drie duizend jaar de menselijke kennis volledig getransformeerd; op het gebied van moraliteit zijn we daarentegen mogelijk achteruitgegaan. De gemiddelde psychotherapeut geeft de patiënt waarschijnlijk minder goed moreel advies over hoe hij zijn leven moet leiden dan de gemiddelde jood in de periode van Mozes van zijn leraar zou hebben gekregen. Natuurlijk is het christendom zelf nog beschikbaar, maar voor het grootste deel van de wereld is het een schim van wat het ooit was. Weinigen hebben het geloof van vroegere tijden, of zelfs dat van minder verfijnde gemeenschappen; men zoekt geen heiligen op Park Avenue.

De vernietiging van traditie is een noodzakelijke voorwaarde geweest voor wetenschappelijke vooruitgang. Als we nog steeds zouden geloven dat de zon om de aarde draaide, dan hadden we geen satellietcommunicatie kunnen ontwikkelen. Immers, wat wij als wetenschap beschouwen, is slechts een reeks hypothesen, onvolmaakte verklaringen die vervangen zullen worden door andere, sterkere maar toch onvolmaakte verklaringen. Toch is de vernietiging van traditie een ramp geweest voor de morele orde van de wereld.

Confucius leerde dat we ons altijd met mate moeten gedragen (hij noemde de gulden middenweg 'chum yum', althans zoals die term door zeventiende-eeuwse geleerden werd vertaald). Hij leerde ook dat we autoriteit moeten respecteren en anderen moeten behandelen zoals wijzelf behandeld zouden willen worden. Die leer is tweeduizend vijfhonderd jaar oud. Als traditie heeft zij China gedurende de hele opgeschreven geschiedenis beïnvloed, maar het confucianisme lijkt voor vele moderne Chinezen een verouderde traditie, die geen waarde hechten aan gematigdheid, kracht respecteren boven autoriteit en zeker anderen niet behandelen zoals zij zelf behandeld zouden willen worden. Met het verlies van traditie kunnen samenlevingen het volledige vocabulaire van hun morele consensus verliezen. China, met al haar toenemende macht, is nu een moreel achterhaald land vergeleken met Tibet, zo arm en onderdrukt als de Tibetanen.

Een goede sociale moraliteit heeft bepaalde kenmerken. Zij moet bijdragen aan het voortbestaan van zowel de samenleving als van individuen, op een dynamische in plaats van statische wijze. Zij moet tolerantie omvatten en zelfgerechtigheid vermijden. Zij moet religieus zijn, in plaats van louter agnostisch. Zij moet niet doen alsof zij in staat is om wetenschappelijke feiten vast te stellen. Zij mag noch anarchistisch, noch autoritair zijn. Zij moet breed gedeeld en diepgeworteld zijn. Een dergelijke sociale moraliteit is bijzonder belangrijk voor het gezin en voor de opvoeding van kinderen tot onafhankelijke en verantwoordelijke volwassenen. Zij vormt de kern van een goede samenleving.

We constateren dat een dergelijke moraliteit wordt ondersteund door de logica van onderlinge afhankelijkheid die voortkomt uit handel en medemenselijkheid, maar bedreigd wordt door de aanvallen van een oppervlakkig scientisme, door de vervreemding van een superklasse en een subklasse, en door het verlies van de geworteldheid van de oude geografische economieën. Misschien zal zich een reactie tegen deze trends voordoen. Zij moeten worden erkend als uiterst gevaarlijk voor de samenlevingen van de volgende eeuw.

Nu, terwijl wat Isaiah Berlin 'het meest verschrikkelijke eeuw in de westerse geschiedenis' noemde ten einde loopt, komt ook het tijdperk van gigantisme in de sociale structuur tot een einde. De laatste dagen van de twintigste eeuw zullen een periode worden van inkrimping, decentralisatie en reorganisatie. Het zal de tijd zijn van de sociale dinosauriërs, gevangen in de teerpit, en een tijd van aaseters. Vogels zullen de beenderen van de dinosauriërs rapen. Overheden, bedrijven en vakbonden zullen zich, tegen hun eigen voorkeur, moeten aanpassen aan nieuwe metaconstitutionele condities, vastgesteld door het binnendringen van microtechnologie. Deze heeft de grenzen waarbinnen geweld wordt uitgeoefend ingrijpend verschoven. De wereld van vandaag is al meer veranderd dan wij gewoonlijk verstaan, meer dan CNN en de kranten ons vertellen. En het is veranderd in precies de richtingen die worden aangegeven door een studie van megapolitieke condities. Zoals wij eerst betoogden in Blood in the Streets en later in *The Great Reckoning*, wanneer er veranderingen plaatsvinden in technologie of in andere factoren die de grenzen bepalen waarbinnen geweld wordt uitgeoefend, verandert het karakter van de samenleving onvermijdelijk mee. Alles wat verbonden is met de manier waarop mensen met elkaar omgaan, inclusief moraliteit en het alledaagse gezond verstand waarmee wij de wereld zien, zal eveneens veranderen. Na een periode van verslapte moraliteit, wat het einde van een tijdperk aangeeft, zullen we de ontwaking zien van een strengere moraliteit, met veeleisendere eisen om te voldoen aan de strengere vereisten van een wereld van concurrerende soevereiniteit.

Verschillende kenmerken van de nieuwe moraliteit zijn te voorzien. Enerzijds zal de nadruk liggen op het belang van productiviteit en op de rechtmatigheid dat verdiensten worden behouden door degenen die ze genereren. Een ander gevolgpunt is het belang van efficiëntie bij investeringen. De moraliteit van het informatietijdperk prijst efficiëntie en erkent het voordeel van middelen die worden ingezet voor hun meest waardevolle toepassingen. Met andere woorden, de moraliteit van het informatietijdperk zal de moraliteit van de markt zijn. Zoals James Bennett heeft betoogd, zal de moraliteit van het informatietijdperk ook een moraliteit van vertrouwen zijn. De cybereconomie zal een gemeenschap met hoog vertrouwen vormen. In een situatie waarin onbreekbare encryptie een verduisteraar of dief in staat stelt om de opbrengsten van zijn misdrijven veilig buiten bereik van herstel te plaatsen, zal er een zeer sterke prikkel bestaan om verliezen te vermijden door in eerste instantie geen zaken te doen met dieven en verduisteraars. Net als in het eerder aangehaalde voorbeeld van de Quakers zal een reputatie van eerlijkheid een belangrijk bezit zijn in de cybereconomie. In de anonimiteit van cyberspace hoeft deze reputatie niet altijd aan een bekende persoon te worden gekoppeld, maar zal ze betrouwbaar verifieerbaar zijn door middel van de identificatie van cryptografische sleutels. De mogelijkheid van verregaande problemen wanneer de encryptie of de certificering van versleutelde identiteiten corrupt raakt door gangsters of anderen, is al ontmoedigend genoeg om sterk tegen het aannemen van iemand te pleiten wiens gedrag duidt op een gebrek aan vertrouwenwekkendheid. Bennett voorziet een 'gentleman’s club in cyberspace', beschermde zones die verhoogde veiligheidsmaatregelen voor deelname vereisen, 'mogelijk met biometrische validatie zoals stemprintidentificatie'. De beheerders zouden de verantwoordelijkheid op zich nemen om de identiteit van de deelnemers – en tot op zekere hoogte hun betrouwbaarheid – te garanderen, waarmee zij een 'gentleman’s club in cyberspace' realiseren (hoewel dames tegenwoordig uiteraard welkom zijn). Binnen deze zones kunnen mensen transacties verrichten met meer zekerheid en vertrouwen dan in het algemene domein van cyberspace. Zo zou de eenentwintigste eeuw een terugkeer kunnen zien naar een op Victoriaanse waarden lijkende nadruk op vertrouwen en karakter in een omgeving die geen enkele Victoriaan had kunnen voorzien.

De beschermde zones binnen cyberspace kunnen ook garanties bieden om risico's te beperken, vergelijkbaar met de extraterritoriale waarborgen die de graven van Champagne aanboden om kooplieden te beschermen die naar en van Champagne-markten reisden. Andere rechtsgebieden vergoedden zelfs reisende kooplieden tegen eventuele verliezen die zij konden lijden tijdens het passeren van het grondgebied dat onder de jurisdictie van de betreffende edelman viel.

'Guards of the Fair', ambtenaren die oorspronkelijk door de graven waren aangesteld, zorgden voor beveiliging en fungeerden als een 'tribunaal van gerechtigheid' voor kooplieden op de markt. Zij ontwikkelden zich uiteindelijk tot meer zelfstandige entiteiten, met een eigen zegel, die contracten notariseerden en de uitvoering ervan afdwongen, met de bevoegdheid om 'een handelaar die schuldig wordt bevonden aan het niet betalen van zijn schulden of het niet nakomen van zijn contractuele beloftes, van toekomstige markten te weren.' Dit was kennelijk zo'n zware straf dat maar weinig mensen bereid waren het risico te lopen op deze ontzegging van toekomstige winstkansen. Als minder ingrijpende maatregel konden de bewakers echter de goederen in beslag nemen van een wanbetaler en deze verkopen ten behoeve van zijn schuldeisers. [^505]

Het uitsluiten van personen als middel tot handhaving van contracten verloor aan belang naarmate het aantal alternatieve markten toenam. Met de nieuwe informatietechnologie die nu beschikbaar is, zou het uitsluiten van oplichters en degenen die tekortschieten in hun contractuele verplichtingen echter opnieuw een krachtig handhavingsmechanisme kunnen vormen binnen de gefragmenteerde soevereiniteiten van de volgende fase van de samenleving. Computernetwerken kunnen cyberspace controleren met onvervalsbare informatie over kredietwaardigheid en fraude. Aangezien de wereld in dit opzicht een bijzonder hechte gemeenschap zal vormen, zullen oplichters en fraudeurs worden ontmoedigd.

Naast het benadrukken van de moraliteit van verdiensten en efficiëntie en het hernieuwd accentueren van karakter en vertrouwen, zal de nieuwe moraliteit hoogstwaarschijnlijk ook de afschuw voor geweld beklemtonen, in het bijzonder ontvoering en afpersing, die steeds belangrijker zullen worden als middel om mensen, wiens middelen anders niet zo gemakkelijk doelwit van criminaliteit zouden zijn, af te persen.

Nog een mogelijke stimulans voor strengere moraliteit zal het einde betekenen van uitkeringen en inkomensherverdeling. Wanneer de hoop op hulp voor de achterblijvers hoofdzakelijk berust op een beroep op particuliere personen en liefdadigheidsinstellingen, zal het belangrijker zijn dan in de twintigste eeuw dat de begunstigden van de liefdadigheid moreel welverdiend overkomen in de ogen van degenen die de hulp vrijwillig verlenen.

> "Subsidies, windfalls en de vooruitzichten op economische kansen nemen de urgentie weg om te moeten besparen. De mantra’s van democratie, herverdeling en economische ontwikkeling verhogen zowel de verwachtingen als de vruchtbaarheid, wat de bevolkingsgroei stimuleert en daarmee een neerwaartse milieu- en economische spiraal versnelt." [^506] - VIRGINIA ABERNATHY

Op sommige vlakken zal de nieuwe informatiewereld beter gepositioneerd zijn om ernst te geven aan morele kwesties. De beloften van inkomensherverdeling, die de verwachtingen deden oplaaien onder de ongelukkigen en minder succesvolle mensen in de Verenigde Staten, Canada en West-Europa, hebben ook internationaal een perverse uitwerking gehad. Er is sterk bewijs dat buitenlandse hulp en toezeggingen van interventie om hongersnood te voorkomen en de levensstandaard te verhogen belangrijke factoren zijn geweest die de bevolkingsgroei stimuleren, waarbij deze de draagkracht van achterblijvende economieën overtreft. De opzienbarende groei van de wereldbevolking sinds de Tweede Wereldoorlog, met de vaak destructieve impact op bossen, bodems en watervoorraden, is terug te voeren op interventies op wereldschaal. Deze interventies hebben de negatieve terugkoppelingsmechanismen, die lokale bevolkingen lange tijd in evenwicht hielden met de benodigde hulpbronnen, tenietgedaan.

Natuurlijk waren velen die in lokale omgevingen leefden met weinig hulpbronnen en nauwelijks of geen groei bijzonder tevreden dat de beperkende aspecten van hun dorpsleven opzijgezet konden worden. Zij namen met enthousiasme de optimistische boodschap over, verkondigd door internationale hulpverleners, vrijwilligers van het Peace Corps, lokale revolutionairen en de concurrerende ideologen van de Koude Oorlog, die iedereen vertelden dat er betere tijden zouden komen. Dit was precies de verkeerde boodschap.

Een belangrijk gevolg van herverdeling tussen culturen is dat degenen die in niet-industriële beschavingen leefden en vasthielden aan niet-industriële waarden, kunstmatig competitief zijn gemaakt. Internationale hulp, reddingsoperaties om hongersnood en ziekten tegen te gaan, en technische interventies hebben velen voor de gek gehouden, waardoor zij gingen geloven dat hun vooruitzichten drastisch waren verbeterd, zonder dat zij hun waarden hoefden bij te stellen of hun gedrag wezenlijk te veranderen.

Internationale inkomensherverdeling heeft niet alleen een onhoudbare bevolkingsgroei in de wereld aangewakkerd, maar heeft ook op belangrijke wijze bijgedragen aan cultureel relativisme en wijdverspreide verwarring over de cruciale rol van cultuur bij het in staat stellen van mensen om in hun lokale omgeving te floreren. Tegenwoordig geloven de meeste mensen dat culturen meer een kwestie van smaak zijn dan bronnen van richtlijnen voor gedrag, die zowel kunnen misleiden als informeren. We zijn te snel geneigd te denken dat alle culturen gelijk zijn en te traag om de nadelen van contraproductieve culturen te herkennen. Dit geldt in het bijzonder voor de hybride culturen die in deze eeuw in veel delen van de wereld opbloeien als gevolg van subsidies en overheidsinterventies. Net als de criminele subculturen van de binnensteden in Amerika, behouden zij onsamenhangende fragmenten van culturen die passend waren voor eerdere stadia van economische ontwikkeling en combineren deze met waarden die gedrag in het informatietijdperk sturen.

De informatie-revolutie zal dus niet alleen de geest van genialiteit bevrijden, maar ook de geest van vergelding ontketenen. Beide zullen strijden als nooit tevoren in het komende millennium.

De verschuiving van een industriële naar een informatiemaatschappij belooft adembenemend te worden. De overgang van het ene stadium van economisch leven naar het andere ging altijd gepaard met een revolutie. Wij menen dat de informatie-revolutie waarschijnlijk de meest ingrijpende van allemaal zal zijn. Zij zal het leven grondiger herstructureren dan zowel de agrarische als de industriële revolutie, en de impact zal in een fractie van de tijd voelbaar zijn. Zet uw gordels vast.

[^467]: Vito Tanzi, 'Corruption: Arm's-length Relationships and Markets,' in Gianluca Fiorentini en Sam Peltzman, eds., The Economics of Organized Crime (Cambridge: Cambridge University Press, 1995), pp.167, 170.

[^468]: Hirshleifer, op. cit., p.176.

[^469]: Ibid., p.169.

[^470]: Michelle R. Garfinkel en Stergios Skaperdas, red., De politieke economie van conflict en toe-eigening (Cambridge: Cambridge University Press, 1996), p.1.

[^471]: Hirshlcifer, op. cit., p.173.

[^472]: Garfinkel en Skaperdas, op. cit., p.1.

[^473]: Ibid.

[^474]: Hamish McRae, The World in 2020 (London: Harper Collins, 1995), p.188.

[^475]: Ibid., pp.188-89.

[^476]: Kevin Kelly, Out of Control (Reading, Mass.: Addison-Wesley, 1994), p.189

[^477]: Tilly, 'War Making and State Making as Organized Crime,' in Evans, Rueschemeyer, and Skoepol, op. cit., p.171.

[^478]: Ibid., p.169.

[^479]: Frank Viamo, 'De nieuwe maffiaorde,' Mother Jones, mei/juni 1995, p.55.

[^480]: Zie Velisarios Kattoulas, 'Japans yakuza nemen hun plaats in de criminele elite,' Washington Times, 25 november 1994, p. A22.

[^481]: Viamo, op. cit., p.49.

[^482]: Garfinkel en Skaperdas, op. cit., p.2.

[^483]: Fiorentini en Peltzman, op. cit., p.15.

[^484]: Ibid.

[^485]: Ibid., p.16.

[^486]: Ibid.

[^487]: Voor aanvullend expliciet bewijs van CIA-compliciteit in de drugshandel, zie Michael Levine, *The Big White Lie: The Deep Cover Operation That Exposed the CIA Sabotage of the Drug War* (New York: Thunder's Mouth Press, 1994).

[^488]: Roger Morris, *Partners in Power* (New York: Henry Holt, 1996), p.233.

[^489]: Ibid., p.393.

[^490]: Ibid., p.411.

[^491]: Ibid., p.418.

[^492]: Ibid.

[^493]: Voor een grondige bespreking van het Foster-verhaal, zie Christopher Ruddy, Vincent Foster: The Ruddy Investigation, verkrijgbaar voor $19,95 via 1-800-711-1968.

[^494]: Morris, op. cit., p.331.

[^495]: Zie Jeffrey Goldberg, "Sommige van de nieuwe vakbondsvrienden van de president lijken hun eigen verdachte vrienden te hebben," New York, 9 juli 1996, p.17.

[^496]: Ibid., p.19.

[^497]: Ibid.

[^498]: Hirshleifer, op. cit., p.173.

[^499]: Tanzi, op. cit., pp. 167, 170.

[^500]: Walter Lippmann, *The Public Philosophy* (New Brunswick, N.J.: Transaction Publishers, 1989), p. 14.

[^501]: Ibid., p. 15.

[^502]: Paul Roazen, *inleiding*, in Lippmann, op. cit., p. xv.

[^503]: Morris, op. cit., p. 469.

[^504]: Fiorentini en Peltzman, op. cit., p.16.

[^505]: James Bennett, *Cyberspace and the Return of Trust*, Strategic Investment, oktober 1996.

[^506]: Virginia Abernethy, *Optimisme en overbevolking*, Atlantic Monthly, december 1994, p.88.