# THE TRANSITION IN THE YEAR 2000

> "It feels like something big is about to happen: graphs show us the yearly growth of populations, atmospheric concentrations of carbon dioxide, Web addresses, and Mbytes per dollar. They all soar up to an asymptote just beyond the turn of the century: The Singularity. The end of everything we know. The beginning of something we may never understand" [^1] - Danny Hillis

## PREMONITIONS

The coming of the year 2000 has haunted the Western imagination for the past thousand years. Ever since the world failed to end at the turn of the first millennium after Christ, theologians, evangelists, poets, and seers have looked to the end of this decade with an expectation that it would bring something momentous. No less an authority than Isaac Newton speculated that the world would end with the year 2000. Michel de Nostradamus, whose prophecies have been read by every generation since they were first published in 1568, forecast the coming of the Third Antichrist in July 1999.[^2] Swiss psychologist Carl Jung, connoisseur of the "collective unconscious," envisioned the birth of a New Age in 1997. Such forecasts may easily be ridiculed. And so can the sober forecasts of economists, such as Dr. Edward Yardeni of Deutsche Bank Securities, who expects computer malfunctions on the millennial midnight to "disrupt the entire global economy."[^3] But whether you view the Y2K computer problem as groundless hysteria ginned up by computer programmers and Information Technology consultants to stir up business, or as a mysterious instance of technology unfulding in concert with the prophetic imagination, there is no denying that circumstances at the eve of the millennium excite more than the usual morbid doubt about where the world is tending.

A sense of disquiet about the future has begun to color the optimism so characteristic of Western societies for the past 250 years. People everywhere are hesitant and worried. You see it in their faces. Hear it in their conversation. See it reflected in polls and registered in the ballot box. Just as an invisible, physical change of ions in the atmosphere signals that a thunderstorm is imminent even before the clouds darken and lightning strikes, so now, in the twilight of the millennium, premonitions of change are in the air. One person after another, each in his own way, senses that time is running out on a dying way of life. As the decade expires, a murderous century expires with it, and also a glorious millennium of human accomplishment. All draw to a close with the year 2000.

> For there is nothing covered that shall not be revealed, neither hid that shall not be known." - Matthew 10:26

# MORALITY AND CRIME IN THE "NATURAL ECONOMY" OF THE INFORMATION AGE

> "Corruption... is far more widespread and universal than previously thought. Evidence of it is everywhere, in developing countries and, with growing frequency, in industrial countries. . . . Prominent political figures, including presidents of countries and ministers, have been accused of corruption. . . . In a way this represents a privatization of the state in which its power is not shifted to the market, as privatization normally implies, but to government officials and bureaucrats."[^467] - VIRO TANZI

We believe that as the modern nationstate decomposes, latter-day barbarians will increasingly come to exercise real power behind the scenes. Groups like the Russian mafiyas that pick the bones of the former Soviet Union, other ethnic criminal gangs, nomenklaturas, drug lords, and renegade covert agencies will increasingly be laws unto themselves. They already are. Far more than is widely understood, the modem barbarians have already infiltrated the forms of the nationstate without greatly changing its appearances. They are microparasites feeding on a dying system. As violent and unscrupulous as a state at war, these groups employ the techniques of the state on a smaller scale. Their growing influence and power is part of the downsizing of politics. Microprocessing reduces the size that groups must attain in order to be effective in the use and control of violence. As this technological revolution unfolds, predatory violence will be organized more and more outside of central control. Efforts to contain violence will also devolve in ways that depend more upon efficiency than magnitude of power.

# TRANSCENDING LOCALITY

:::{.content-hidden when-format=latex}
*The Emergence of the Cybereconomy*
:::

> "The real issue is control. The Internet is too widespread to be easily dominated by any single government. By creating a seamless global-economic zone, anti-sovereign and unregulatable, the Internet calls into question the very idea of a nationstate."[^245] - JOHN PERRY BARLOW

The Information Superhighway has become one of the more familiar metaphors of the early days of the digital age. It is remarkable not only for its pervasiveness, but also for the common misunderstanding it betrays about the cybereconomy. A highway, after all, is an industrial version of a footpath, a network for the physical transit of people and goods. The information economy is not like a highway, a railroad, or a pipeline. It does not haul or transport information from point to point the way the Trans-Canada Highway carries heavy trucks from Alberta to New Brunswick. What the world calls the "Information Superhighway" is not merely a transit link. It is the destination.

Cyberspace transcends locality. It involves nothing less than the instantaneous sharing of data everywhere and nowhere at once. The emerging information economy is based in the interconnections linking and relinking millions of users of millions of computers. Its essence lies in the new possibilities that arise from these connections. As John Perry Barlow put it, "What the Net offers is the promise of a new social space, global and anti-sovereign, within which anybody, anywhere can express to the rest of humanity whatever he or she believes without fear. There is in these new media a foreshadowing of the intellectual and economic liberty that might undo all the authoritarian powers on earth."[^246]:

Cyberspace, like the imaginary realm of Homer's gods, is a realm apart from the familiar terrestrial world of farm and factory. Yet its consequences will not be imaginary, but real. To a far greater extent than many now understand, the instantaneous sharing of information will be like a solvent dissolving large institutions. It will not only alter the logic of violence, as we have already explored; it will radically alter information and transaction costs that determine how businesses organize and the way the economy functions. We expect microprocessing to change the economic organization of the world.

> "It is today possible, to a greater extent than at any time in the worlds' history, for a company to locate anywhere, to use resources from anywhere to produce a product that can be sold anywhere." - MILTON FRIEDMAN

## THE TYRANNY OF PLACE

The fact that the fading industrial era's first stab at conceiving the information economy is to think of it in terms of a gigantic public works project tells you how grounded our thinking is in the paradigms of the past. It is rather like hearing farmers at the end of the eighteenth century describe a factory as "a farm with a roof." Yet the "superhighway" metaphor is more revealing than that. It also betrays the extent to which we are hostage to the tyranny of place. Even when technology enables us to transcend locality, the instrument of our deliverance is given a nickname describing it as a route from place to place. Like salmon marked by their homing instinct, our consciousness is still deeply etched by notions of locality.
