# DE OVERGANG IN HET JAAR 2000

> “Het voelt alsof er iets groots op het punt staat te gebeuren: grafieken tonen de jaarlijkse groei van bevolkingsaantallen, de concentraties koolstofdioxide in de atmosfeer, het aantal webadressen en Mbytes per dollar. Ze schieten allemaal omhoog tot een grens die net voorbij de millenniumwisseling ligt: de Singulariteit. Het einde van alles wat we kennen. Het begin van iets wat we misschien nooit zullen doorgronden.” [^1] – Danny Hillis

## VOORVOELINGEN

De komst van het jaar 2000 achtervolgt de westerse verbeelding al duizend jaar. Sinds de wereld niet eindigde met de eerste millenniumwisseling na Christus, keken theologen, evangelisten, dichters en zieners met grote verwachting naar het einde van dit decennium, in de hoop op een ingrijpende gebeurtenis. Geen minder dan Isaac Newton speculeerde er zelfs op dat de wereld in 2000 zou eindigen. Michel de Nostradamus, wiens profetieën sinds 1568 door elke generatie worden gelezen, voorspelde dat de Derde Antichrist in juli 1999 zou opdagen.[^2] De Zwitserse psycholoog Carl Jung, expert op het gebied van het “collectieve onbewuste”, voorzag in 1997 het aanbreken van een nieuw tijdperk. Zulke voorspellingen roepen al snel spot op. En dat geldt ook voor de nuchtere prognoses van economen, zoals Dr. Edward Yardeni van Deutsche Bank Securities, die verwacht dat computerstoringen op millennialus middernacht “de gehele wereldeconomie zullen ontwrichten.”[^3] Of je het Y2K-computerprobleem nu ziet als ongegronde hysterie, opgeblazen door programmeurs en IT-consultants om business te genereren, of als een mysterieus fenomeen waarin technologie samenvalt met profetische verbeelding, niemand kan ontkennen dat de omstandigheden op de drempel van het nieuwe millennium meer opwinding veroorzaken dan de gebruikelijke morbide twijfels over de koers van de wereld.

Het groeiende onbehagen over de toekomst begint de optimistische sfeer te kleuren die de afgelopen 250 jaar zo kenmerkend is voor westerse samenlevingen. Overal zien we mensen terughoudend en bezorgd. Je leest het aan hun gezichten, hoort het in hun gesprekken en ziet het terug in peilingen en stembiljetten. Net zoals een onzichtbare wijziging in atmosferische ionen al aangeeft dat een onweersbui op komst is, nog voordat de wolken donker worden en de bliksem slaat, hangen in de schemering van het millennium nu voorgevoelens van verandering in de lucht. Steeds meer mensen, ieder op zijn eigen manier, ervaren dat de tijd dringt voor een levenswijze die aan het verdwijnen is. Met het verstrijken van dit decennium vervaagt ook een bloedig eeuwperk, evenals een glorieus millennium vol menselijke prestaties. Alles loopt af met het jaar 2000.

> “Want er is niets verborgen dat niet onthuld zal worden, noch geheim dat niet bekend zal worden.” – Matteüs 10:26