# DE OVERGANG IN HET JAAR 2000

> “Het voelt alsof er iets groots op het punt staat te gebeuren: grafieken tonen ons de jaarlijkse groei van populaties, de concentraties kooldioxide in de atmosfeer, het aantal webadressen en megabytes per dollar. Ze stijgen allemaal steil tot een asymptoot net na de jaarwisseling: de Singularity. Het einde van alles wat we kennen. Het begin van iets wat we misschien nooit zullen begrijpen.” [^1] – Danny Hillis

## VOORGEVOELENS

De komst van het jaar 2000 heeft de westerse verbeelding al duizend jaar doen sidderen. Sinds de wereld niet eindigde bij de omslag van het eerste millennium na Christus, kijken theologen, evangelisten, dichters en zieners met een verwachting naar het einde van dit decennium, omdat zij ervan uitgaan dat er iets merkwaardigs zal gebeuren. Niemand minder dan Isaac Newton speculeerde dat de wereld een einde zou maken met het jaar 2000. Michel de Nostradamus, wiens profetieën elke generatie hebben beziggehouden sinds ze in 1568 werden gepubliceerd, voorspelde de komst van de Derde Antichrist in juli 1999.[^2] De Zwitserse psycholoog Carl Jung, bekend om zijn kennis van het “collectieve onbewuste”, voorzag de geboorte van een Nieuwe Tijd in 1997. Zulke voorspellingen kunnen zomaar belachelijk lijken. En zo worden ook de ingetogen profetieën van economen zoals Dr. Edward Yardeni van Deutsche Bank Securities belachelijk gemaakt, die verwacht dat computerstoringen op middernacht van de millenniumwisseling “de hele wereldeconomie zullen ontwrichten.”[^3] Of je nu het Y2K-probleem beschouwt als ongegronde hysterie, aangewakkerd door computerprogrammeurs en IT-consultants om zaken te stimuleren, of als een mysterieus verschijnsel van technologie die samenwerkt met de profetische verbeelding, één ding valt niet te ontkennen: de omstandigheden in de aanloop naar het millennium wekken meer opwinding dan de gebruikelijke sombere twijfels over de richting waarin de wereld opgaat.

Het onbehagen over de toekomst begint het optimisme, dat de afgelopen 250 jaar zo kenmerkend is voor westerse samenlevingen, te overschaduwen. Overal zien mensen aarzelende, bezorgde blikken. Je leest het op hun gezicht, hoort het in hun gesprekken, en het blijkt uit opiniepeilingen en stembiljetten. Net zoals een onzichtbare, fysieke verandering in de ionen in de atmosfeer aangeeft dat er een onweersbui op komst is – nog voor de wolken verduisteren en de bliksem inslaat – hangen er in de schemering van het millennium voorgevoelens van verandering in de lucht. De een na de ander voelt op zijn eigen manier dat de tijd dringt voor een levenswijze die ten dode opgeschreven is. Met het verstrijken van dit decennium vervaagt ook een moordend tijdperk en een glorieus millennium van menselijke prestaties. Alles komt tot een einde met het jaar 2000.

> “Want er is niets dat verborgen blijft wat niet onthuld wordt, noch geheim wat niet bekend zal worden.” – Matthew 10:26