# DE TRANSITIE IN HET JAAR 2000

> “Het voelt alsof er iets groots op het punt staat te gebeuren: grafieken tonen ons de jaarlijkse groei van de bevolking, de atmosferische concentraties van kooldioxide, het aantal webadressen en megabytes per dollar. Ze stijgen allemaal richting een asymptoot net na de millenniumwisseling: de Singularity. Het einde van alles wat we kennen. Het begin van iets dat we misschien nooit zullen begrijpen.” [^1]  
> – Danny Hillis

## VOORVOORZICHTEN

De komst van het jaar 2000 spookt al duizend jaar door de westerse verbeelding. Sinds de wereld niet eindigde bij de millenniumwisseling van Christus hebben theologen, evangelisten, dichters en zieners met de verwachting gekeken naar het einde van dit decennium. Ze verwachtten dat het iets baanbrekends mee zou brengen. Niemand minder dan Isaac Newton speculeerde dat de wereld in het jaar 2000 tot een einde zou komen. Michel de Nostradamus, wiens profetieën sinds de eerste publicatie in 1568 door iedere generatie worden gelezen, voorspelde de komst van de Derde Antichrist in juli 1999.[^2] De Zwitserse psycholoog Carl Jung, expert op het gebied van het “collectieve onbewuste”, zag in 1997 de geboorte van een New Age. Zulke voorspellende uitspraken leveren natuurlijk gemakkelijk spot op. Eveneens kunnen de nuchtere voorspellingen van economen, zoals Dr. Edward Yardeni van Deutsche Bank Securities – die rekent op computerstoringen op middernacht van het millennium die de wereldeconomie compleet zouden ontwrichten[^3] – belachelijk doen lijken. Of je het Y2K-probleem nu afdoet als ongegronde hysterie, aangewakkerd door programmeurs en IT-consultants om de zaken op te stoken, of als een mysterieus fenomeen waarbij technologie samenvalt met een profetische verbeelding, niemand kan ontkennen dat de omstandigheden op de vooravond van het millennium meer opwinding losmaken dan de gebruikelijke morbide twijfel over de richting waarin de wereld zich begeeft.

Een gevoel van ongerustheid over de toekomst kleurt het optimisme dat de afgelopen 250 jaar zo kenmerkend is voor westerse samenlevingen. Overal zien we mensen aarzelend en bezorgd. Je herkent het in hun gelaat, hoort het in hun gesprekken en ziet het terug in opiniepeilingen en de stembiljetten. Net zoals een onzichtbare, fysieke verandering in de ionen in de atmosfeer aanduidt dat een onweersbui op komst is – nog voordat de wolken verduisteren en de bliksem slaat – hangen nu, in de schemering van het millennium, voorgevoelens van verandering in de lucht. Ieder voor zich voelt iemand dat de tijd om is voor een leefwijze die aan het vervagen is. Terwijl het decennium ten einde loopt, gaat er ook een moorddadige eeuw ten onder – en daarmee tevens een glorieuze millennium van menselijke prestaties. Alles komt tot een einde in het jaar 2000.

> “Want er is niets verborgen dat niet onthuld zal worden, en niets geheim dat niet bekend zal worden.”  
> – Matthew 10:26