# THE TRANSITION IN THE YEAR 2000

> "It feels like something big is about to happen: graphs show us the yearly growth of populations, atmospheric concentrations of carbon dioxide, Web addresses, and Mbytes per dollar. They all soar up to an asymptote just beyond the turn of the century: The Singularity. The end of everything we know. The beginning of something we may never understand" [^1] - Danny Hillis

## PREMONITIONS

The coming of the year 2000 has haunted the Western imagination for the past thousand years. Ever since the world failed to end at the turn of the first millennium after Christ, theologians, evangelists, poets, and seers have looked to the end of this decade with an expectation that it would bring something momentous. No less an authority than Isaac Newton speculated that the world would end with the year 2000. Michel de Nostradamus, whose prophecies have been read by every generation since they were first published in 1568, forecast the coming of the Third Antichrist in July 1999.[^2] Swiss psychologist Carl Jung, connoisseur of the "collective unconscious," envisioned the birth of a New Age in 1997. Such forecasts may easily be ridiculed. And so can the sober forecasts of economists, such as Dr. Edward Yardeni of Deutsche Bank Securities, who expects computer malfunctions on the millennial midnight to "disrupt the entire global economy."[^3] But whether you view the Y2K computer problem as groundless hysteria ginned up by computer programmers and Information Technology consultants to stir up business, or as a mysterious instance of technology unfulding in concert with the prophetic imagination, there is no denying that circumstances at the eve of the millennium excite more than the usual morbid doubt about where the world is tending.

A sense of disquiet about the future has begun to color the optimism so characteristic of Western societies for the past 250 years. People everywhere are hesitant and worried. You see it in their faces. Hear it in their conversation. See it reflected in polls and registered in the ballot box. Just as an invisible, physical change of ions in the atmosphere signals that a thunderstorm is imminent even before the clouds darken and lightning strikes, so now, in the twilight of the millennium, premonitions of change are in the air. One person after another, each in his own way, senses that time is running out on a dying way of life. As the decade expires, a murderous century expires with it, and also a glorious millennium of human accomplishment. All draw to a close with the year 2000.

> For there is nothing covered that shall not be revealed, neither hid that shall not be known." - Matthew 10:26

We believe that the modern phase of Western civilization will end with it. This book tells why. Like many earlier works, it is an attempt to see into a glass darkly, to sketch out the vague shapes and dimensions of a future that is still to be. In that sense, we mean our work to be apocalyptic in the original meaning of the word. Apokalypsis means "unveiling" in Greek. We believe that a new stage in history - the Information Age - is about to be "unveiled."

> We are watching the beginnings of a new logical space, an instantaneous electronic everywhereness, which we may all access, enter into, and experience. We have, in short, the beginnings of a new kind of community. The virtual community becomes the model for a secular Kingdom of Heaven; as Jesus said there were many mansions in his FAther's Kingdom, so there are many virtual communities, each reflecting their own needs and desires. - Michael Grasso[^4]

## THE FOURTH STAGE OF HUMAN SOCIETY

The theme of this book is the new revolution of power which is liberating individuals at the expense of the twentiethcentury nationstate. Innovations that alter the logic of violence in unprecedented ways are transforming the boundaries within which the future must lie. If our deductions are correct, you stand at the threshold of the most sweeping revolution in history. Faster than all but a few now imagine, microprocessing will subvert and destroy the nationstate, creating new forms of social organization in the process. This will be far from an easy transformation.

The challenge it will pose will be all the greater because it will happen with incredible speed compared with anything seen in the past. Through all of human history from its earliest beginnings until now, there have been only three basic stages of economic life. (1) hunting-and-gathering societies; (2) agricultural societies; and (3) industrial societies. Now, looming over the horizon, is something entirely new, the fourth stage of social organization: information societies.

Each of the previous stages of society has corresponded with distinctly different phases in the evolution and control of violence. As we explain in detail, information societies promise to dramatically reduce the returns to violence, in part because they transcend locality. The virtual reality of cyberspace, what novelist William Gibson characterized as a "consensual hallucination," will be as far beyond the reach of bullies as imagination can take it. If the new millennium, the advantage of controlling violence on a large scale will be far lower than it has been at any time since before the French Revolution. This will have profound consequences. One of these will be rising crime. When the payoff for organizing violence at a large scale tumbles, the payoff from violence at a smaller scale is likely to jump. Violence will become more random and localized. Organized crime will grow in scope. We explain why.

Another logical implication of falling returns to violence is the eclipse of politics. There is much evidence that adherence to the civic myths of the twentiethcentury nationstate is rapidly eroding. The death of Communism is merely the most striking example. As we explore in detail, the collapse of morality and growing corruption among leaders of Western governments is not a random development. It is evidence that the potential of the nationstate is exhausted. Even many of its leaders no longer believe the platitudes they mouth. Nor are they believed by others.

### History Repeats Itself

This is a situation with striking parallels in the past. Whenever technological change has divorced the old forms from the new moving forces of the economy, moral standards shift, and people begin to treat those in command of the old institutions with growing disdain. This widespread revulsion often comes into evidence well before people develop a new coherent ideology of change. So it was in the late fifteenth century, when the medieval Church was the predominant institution of feudalism. Notwithstanding popular belief in "the sacredness of the sacerdotal office," both the higher and lower ranks of clergy were held in the utmost contempt-not unlike the popular attitude toward politicians and bureaucrats today. [^5]

We believe that much can be learned by analogy between the situation at the end of the fifteenth century, when life had become thoroughly saturated by organized religion, and the situation today, when the world has become saturated with politics. The costs of supporting institutionalized religion at the end of the fifteenth century had reached a historic extreme, much as the costs of supporting government have reached a senile extreme today.

We know what happened to organized religion in the wake of the Gunpowder Revolution. Technological developments created strong incentives to downsize religious institutions and lower their costs. A similar technological revolution is destined to downsize radically the nationstate early in the new millennium.

> Today, after more than a century of electronic technology, we have extended our central nervous system itself in a global embrace, abolishing both space and time as far as our planet is concerned.[^6]

### The Information Revolution

As the breakdown of large systems accelerates, systematic compulsion will recede as a factor shaping economic life and the distribution of income. Efficiency will rapidly become more important than the dictates of power in the organization of social institutions. This means that provinces and even cities that can effectively uphold property rights and provide for the administration of justice, while consumding few resources, will be viable sovereignties in the Information Age, as they generally have not been during the last five centures. An entirely new realm of economic activity that is not hostage to physical violence will emerge in cyberspace. The most obvious benefits will flow to the "cognitive elite," who will increasingly operate outside political boundaries. They are already equally home in Frankfurt, London, New York, Buenos Aires, Los Angeles, Tokyo, and Hong Kong. Incomes will become more unequal within jurisdictions and more equal between them.

The Sovereign Individual explores the social and financial consequences of this revolutionary change. Our desire is to help you to take advantage of the opportunities of the new age and avoid being destroyed by its impact. If only half of what we expect to see happens, you face change of a magnitude with few precedents in history.

The transformation of the year 2000 will not only revolutionize the character of the world economy, it will do so more rapidly than any previous phase change. Unlike the Agricultural Revolution, the Information Revolution will not take millennia to do its work. Unlike the Industrial Revolution. its impact will not be spread over centuries. The Information Revolution will happen within a lifetime.

What is more, it will happen almost everywhere at once. Technical and economic innovations will no longer be confined to small portions of the globe. The transformation will be all but universal. And it will involve a break with the past so profound that it will almost bring to life the magical domain of the gods as imagined by the early agricultural peoples like the ancient Greeks. To a greater degree than most would now be willing to concede, it will prove difficult or impossible to preserve many contemporary institutions in the new millennium. When information societies take shape they will be as different from industrial societies as the Greece of Aeschylus was from the world of the cave dwellers.

## PROMETHEUS UNBOUND: THE RISE OF THE SOVEREIGN INDIVIDUAL

> I know of no more encouraging fact than the unquestionable ability of man to elevate his life by conscious endeavour - Henry David Thoreau

The coming transformation is both good news and bad. The good news is that the Information Revolution will liberate individuals as never before. For the first time, those who can educate themselves will be almost entirely free to invent their own work and realize the full benefits of their own productivity. Genius will be unleashed, freed from both the oppression of government and the drags of racial and ethnic prejudice. In the Information Society, no one who is truly able will be detained by the ill-formed opinions of others. It will not matter what most of the people on earth might think of your race, your looks, your age, your sexual proclivities, or the way you wear your hair. In the cybereconomy, they will never see you. The ugly, the fat, the old, the disabled will vie with the young and beautiful on equal terms in utterly color-blind anonymity on the new frontiers of cyberspace.

### Ideas Become Wealth

Merit, wherever it arises, will be rewarded as never before. In an environment where the greatest source of wealth will be the ideas you have in your head rather than physical capital alone, anyone who thinks clearly will potentially be rich. The Information Age will be the age of upward mobility. It will afford far more equal opportunity for the billions of humans in parts of the world that never shared fully in the prosperity of industrial society. The brightest, most successful and ambitious of these will emerge as truly Sovereign Individuals.

At first, only a handful will achive full financial sovereignty. But this does not negate the advantages of financial independence. The fact that not everyone attains an equally vast fortune does not mean that it is futile or meaningless to become rich. There are 25,000 millionaires for every billionaire. If you are a millionaire and not a billionaire, that does not make you poor. Equally, in the future, one of the milestones by which you measure your financial success will be not just how many zeroes you can add to your net worth, but whether you can structure your affairs in a way that enables you to realize full individual autonomy and independence. The more clever you are, the less propulsion you will require to achieve financial escape velocity. Persons of even quite modest means will soar, as the gravitational pull of politics on the global economy weakens. Unprecedented financial independence will be a reachable goal in your lifetime or that of your children.

At the highest plateau of productivity, these Sovereign Individuals will compete and interact on terms that echo the relations among the gods in Greek myth. The elusive Mount Olympus of the next millennium will be in cyberspace-a realm without physical existence that will nonetheless develop what promises to be the world's largest economy by the second decade of the new millennium. By 2025, the cybereconomy will have many millions of participants. Some of them will be as rich as Bill Gates, worth over $10 billion each. The cyberpoor may be those with an income of less than $200,000 a year. There will be no cyberwelfare. No cybertaxes and no cybergovernment. The cybereconomy, rather than China, could well be the greatest economic phenomenon of the next thirty years.

The good news is that politicians will no more be able to dominate, suppress, and regulate the greater part of commerce in this new realm than the legislators of the ancient Greek city-states could have trimmed the beard of Zeus. That is good news for the rich. And even better news for the not so rich. The obstacles and burdens that politics imposes are more obstacles to becoming rich than to being rich. The benefits of declining returns to violence and devolving jurisdictions will create scope for every energetic and ambitious person to benefit from the death of politics. Even the consumers of government services will benefit as entrepreneurs extend the benefits of competition. Consequently, much of the ingenuity of interjurisdictional competition was channeled into military endeavor. But the advant of the cybereconomy will bring competition on new terms to provision of sovereignty services. A proliferation of jurisdictions will mean proliferating experimentation in new ways of enforcing contracts and otherwise securing the safety of persons and property. The liberation of a large part of the global economy from political control will oblige all remaining forms of government to operate on more nearly market terms. They will ultimately have little choice but to treat populations in territories they serve more like customers, and less in the way that organized criminals treat the victims of a shakedown racket.

### Beyond Politics

What mythology described as the province of the gods will become a viable option for the individual -- a life outside the reach of kings and councils. First in scores, then in hundreds, and ultimately in the millions, individuals will escape the shackles of politics. As they do, they will transform the character of governments, shrinking the realm of compulsion and widening the scope of private control over resources.

The emergence of the sovereign individual will demonstrate yet again the strange prophetic power of myth. Conceiving little of the laws of nature, the early agricultural peoples imagined that "powers we should call supernatural" were widely distributed. These powers were sometimes employed by men, sometimes by "incarnate human gods" who looked like men and interacted with them in what Sir James George Frazer described in The Golden Bough as "a great democracy".[^7]

When the ancients imagined the children of Zeus living among them they were inspired by a deep belief in magic. They shared with other primitive agricultural peoples an awe of nature, and a superstitious conviction that nature's works were set in motion by individual volition, by magic. In that sense, there was nothing self-consciously prophetic about their view of nature and their gods. They were far from anticipating microtechnology. They could not have imagined its impact in altering the marginal productivity of individuals thousands of years later. They certainly could not have foreseen how it would shift the balance between power and efficiency and thus revolutionize the way that assets are created and protected. Yet what they imagined as they spun their myths has a strange resonance with the world you are likely to see.

### Alt.Abracadabra

The "abracadabra" of the magic invocation, for example. bears a curious similarity to the password employed to access a computer. In some respects, high-speed computation has already made it possible to mimic the magic of the genie. Early generations of "digital servants" already obey the commands of those who control the computers in which they are sealed much as genies were sealed in magic lamps. The virtual reality of information technology will widen the realm of human wishes to make almost anything that can be imagined seem real. Telepresence will give living individuals the same capacity to span distance at supernatural speed and monitor events from afar that the Greeks supposed was enjoyed by Hermes and Apollo. The Sovereign Individuals of the Information Age, like the gods of ancient and primitive myths, will in due course enjoy a kind of "diplomatic immunity" from most of the political woes that have beset mortal human beings in most times and places.

The new Sovereign Individual will operate like the gods of myth in the same physical environment as the ordinary, subject citizen, but in a separate realm politically. Commanding vastly greater resources and beyond the reach of many forms of compulsion, the Sovereign Individual will redesign governments and reconfigure economies in the new millennium. The full implications of this change are all but unimaginable.

### Genius and Nemesis

For anyone who loves human aspiration and success, the Information Age will provide a bounty. That is surely the best news in many generations. But it is bad news as well, The new organization of society implied by the triumph of individual autonomy and the true equalization of opportunity based upon merit will lead to very great rewards for merit and great individual autonomy. This will leave individuals far more responsible for themselves than they have been accustomed to being during the industrial period. It will also reduce the unearned advantage in living standards that has been enjoyed by residents of advanced industrial societies throughout the twentieth century. As we write, the top 15 percent of the world's population have an average per-capita income of $21,000 annually. The remaining 85 percent of the world have an average income of just $1,000. That huge, hoarded advantage from the past is bound to dissipate under the new conditions of the Information Age.

As it does, the capacity of nationstates to redistribute income on a large scale will collapse. Information technology facilitates dramatically increased competition between jurisdictions. When technology is mobile, and transactions occur in cyberspace, as they increasingly will do, governments will no longer be able to charge more for their services than they are worth to the people who pay for them. Anyone with a portable computer and a satellite link will be able to conduct almost any information business anywhere, and that includes almost the whole of the world's multitrillion-dollar financial transactions.

This means that you will no longer be obliged to live in a high-tax jurisdiction in order to earn high income. In the future, when most wealth can be earned anywhere, and even spent anywhere, governments that attempt to charge too much as the price of domicile will merely drive away their best customers. If our reasoning is correct, and we believe it is, the nationstate as we know it will not survive in anything like its present form.

## THE END OF NATIONS

Changes that diminish the power of predominant institutions are both unsettling and dangerous. Just as monarchs, lords, popes, and potentates fought ruthlessly to preserve their accustomed privileges in the early stages of the modern period, so today's governments will employ violence, often of a covert and arbitrary kind, in the attempt to hold back the clock. Weakened by the challenge from technology, the state will treat increasingly autonomous individuals, its former citizens, with the same range of ruthlessness and diplomacy it has heretofore displayed in its dealing with other governments. The advent of this new stage in history was punctuated with a bang on August 20, 1998, when the United States fired about $200 million worth of Tomahawk BGM-109 sea-launched cruise missiles at targets allegedly associated with an exiled Saudi millionaire, Osama bin Laden. Bin Laden became the first person in history to have his satellite phone targeted for attack by cruise missiles. Simultaneously, the United States destroyed a pharmaceutical plant in Khartoum, Sudan, in Bin Laden's honor. The emergence of Bin Laden as the enemy-in-chief of the United States reflects a momentous change in the nature of warfare. A single individual, albeit one with hundreds of millions of dollars, can now be depicted as a plausible threat to the greatest military power of the Industrial era. In statements reminiscent of propaganda employed during the Cold War about the Soviet Union, The United States president and his national security aides portrayed Bin Laden, a private individual, as a transnational terrorist and leading enemy of the United States.

The same military logic that has seen Osama bin Laden elevated to a position as chief enemy of the United States will assert itself in governments' internal relations with their subjects. Increasingly harsh techniques of exaction will be a logical corollary of the emergence of a new type of bargaining between governments and individuals. Technology will make individuals more nearly sovereign than ever before. And they will be treated that way. Sometimes violently, as enemies, sometimes as equal parties in negotiation, sometimes as allies. But however ruthlessly governments behave, particularly in the transition period, wedding the IRS with the CIA will avail them little. They will be increasingly required by the press of necessity to bargain with autonomous individuals whose resources will no longer be so easily controlled.

The changes implied by the Information Revolution will not only create a fiscal crisis for governments, they will tend to disintegrate all large structures. Fourteen empires have disappeared already in the twentieth century. The breakdown of empires is part of a process that will dissolve the nationstate itself. Government will have to adapt to the growing autonomy of the individual. Taxing capacity will plunge by 50~70 percent. This will tend to make smaller jurisdictions more successful. The challenge of setting competitive terms to attract able individuals and their capital will be more easily undertaken in enclaves than across continents.

We believe that as the modern nationstate decomposes, latter-day barbarians will increasingly come to exercise power behind the scenes. Groups like the Russian mafiya, which picks the bones of the former Soviet Union, other ethnic criminal gangs, nomenklaturas[^27], drug lords, and renegade covert agencies will be laws unto themselves. They already are. Far more than is widely understood, the modern barbarians have already infiltrated the forms of the nationstate without greatly changing its appearances. They are microparasites feeding on a dying system. As violent and unscrupulous as a state at war, these groups employ the techniques of the state on a smaller scale. Their growing influence and power are part of the downsizing of politics. Microprocessing reduces the size that groups must attain in order to be effective in the use and control of violence. As this technological revolution unfolds, predatory violence will be organized more and more outside of central control. Efforts to contain violence will also devolve in ways that depend more upon efficiency than magnitude of power.

### History in Reverse

The process by which the nationstate grew over the past five centuries will be put into reverse by the new logic of the Information Age. Local centers of power will reassert themselves as the state devolves into fragmented, overlapping sovereignties. [^8] The growing power of organized crime is merely one reflection of this tendency. Multinational companies are already having to subcontract all but essential work. Some conglomerates, such as AT&T, Unisys, and ITT, have split themselves into several firms in order to function more profitably. The nationstate will devolve like an unwieldy conglomerate, but probably not before it is forced to do so by financial crises.

Not only is power in the world changing, but the work of the world is changing as well. This means that the way business operates will inevitably change. The "virtual corporation" is evidence of a sweeping transformation in the nature of the firm, facilitaed by the drop in information and transaction costs. We explore the implications of the Information Revolution for dissolving corporations and doing away with the "good job." In the Information AGe, a "job" will be a task to do, not a position you "have." Microprocessing has created entirely new horizons of economic activity that transcend territorial boundaries. This transcendence of frontiers and territories is perhaps the most revolutionary development since Adam and Eve straggled out of paradise under the sentence of their Maker: "In the sweat of thy face shalt thou eat bread." As technology revolutionizes the tools we use, it also antiquates our laws, reshapes our morals, and alters our perceptions. This book explains how.

Microprocessing and rapidly improving communications already make it possible for the individual to choose where to work. Transactions on the Internet or the World Wide Web can be encrypted and will soon be almost impossible for tax collectors to capture. Tax-free money already compounds far faster offshore than onshore funds still subject to the high tax burden imposed by the twentiethcentury nationstate. After the turn of the millennium, much of the world's commerce will migrate into the new realm of cyberspace, a region where governments will have no more dominion than they exercise over the bottom of the sea or the outer planets. In cyberspace. the threats of physical violence that have been the alpha and omega of politics since time immemorial will vanish. In cyberspace, the meek and the mighty will meet on equal terms. Cyberspace is the ultimate offshore jurisdiction. An economy with no taxes. Bermuda in the sky with diamonds.

When this greatest tax haven of them all is fully open for business, all funds will essentially be offshore funds at the discretion of their owner. This will have cascading consequences. The state has grown used to treating its taxpayers as a farmer treats his cows, keeping them in a field to be milked. Soon, the cows will have wings.

### The Revenge of Nations

Like an angry farmer, the state will no doubt take desperate measures at first to tether and hobble its escaping herd. It will employ covert and even violent means to restrict access to liberating technologies. Such expedients will work only temporarily, if at all. The twentiethcentury nationstate, with all its pretensions, will starve to death as its tax revenues decline.

When the state finds itself unable to meet its committed expenditure by raising tax revenues, it will resort to other, more desperate measures. Among them is printing money. Governments have grown used to enjoying a monopoly over currency that they could depreciate at will. This arbitrary inflation has been a prominent feature of the monetary policy of all twentiethcentury states. Even the best national currency of the postwar period, the German mark, lost 71 percent of its value from January 1, 1949, through the end of June 1995. In the same period, the U.S. dollar lost 84 percent of its value.[^9] This inflation had the same effect as a tax on all who hold the currency. As we explore later, inflation as revenue option will be largely foreclosed by the emergence of cybermoney. New technologies will allow the holders of wealth to bypass the national monopolies that have issued and regulated money in the modern period.  Indeed, the credit crises that swept through Asia, Russia, and other emerging economies in 1997 and 1998 attest to the fact that national currencies and national credit ratings are anchronisms inimical to the smooth operation of the global economy. It is precisely the fact that the demands of sovereignty require all transactions within a jurisdiction to be denominated in a national currency that creates the vulnerability to mistakes by central bankers and attacks by speculators which precipitated deflationary crises in one jurisdiction after another. In the Information Age, individual will be able to use cybercurrencies and thus declare their monetary independence. When individuals can conduct their own monetary policies over the World Wide Web it will matter less or not at all that the state continues to control the industrial-era printing presses. Their importance for controlling the world's wealth will be transcended by mathematical algorithms that have no physical existence. In the new millennium, cybermoney controlled by private markets will supersede flat money issued by governments. Only the poor will be victims of inflation and ensuing collapses into deflation that are consequences of the artificial leverage which fiat money injects into the economy.

Lacking their accustomed scope to tax and inflate, governments, even in traditionally civil countries, will turn nasty. As income tax becomes uncollectable, older and more arbitrary methods of exaction will resurface. The ultimate form of withholding tax -- de facto or even overt hostage-taking will be introduced by governments desperate to prevent wealth from escaping beyond their reach. Unlucky individuals will find themselves singled out and held to ransom in an almost medieval fashion. Businesses that offer services that facilitate the realization of autonomy by individuals will be subject to infiltration, sabotage, and disruption. Arbitrary forfeiture of property, already commonplace in the United States, where it occurs five thousand times a week, will become even more pervasive. Governments will violate human rights, censor the free flow of information, sabotage useful technologies, and worse. For the same reasons that the late, departed Soviet Union tried in vain to suppress access to personal computers and Xerox machines, western governments will seek to suppress the cybereconomy by totalitarian means.

## RETURN OF THE LUDDITES

Such methods may prove popular among some population segments. The good news about individual liberation and autonomy will seem to be bad news to many who are not among the cognitive elite. The greatest resentment is likely to be centered among those of middle talent in currently rich countries. They particularly may come to feel that information technology poses a threat to their way of life. The beneficiaries of organized compulsion, including millions receiving income redistributed by governments, may [^9] resent the new freedom realized by Sovereign Individuals. Their upset will illustrate the truism that "where you stand is determined by where you sit."

> Sometimes I wondered how I could experience such deep misery over the fate of a handful of men I did not know, playing a game against another group of strangers in a ballpark hundreds of miles away. The answer is simple. I loved my teams. Although risky, caring was worth its price. Sports fired up my blood, excited me, made my heart pound. I liked having something at stake. Life was more vivid during a contenst. -- Craig Lambert
