# TRANSFORMATIONS MÉGAPOLITIQUES DANS UNE PERSPECTIVE HISTORIQUE

> « Dans l’histoire comme dans la nature, la naissance et la mort s’équilibrent en parts égales » – JOHAN HUIZINGA[^29]

## LE DÉCLIN DU MONDE MODERNE

De notre point de vue, vous êtes le témoin de rien de moins que du déclin de l’ère moderne. C’est une évolution dictée par une logique implacable mais cachée. Plus qu’on ne le croit généralement, bien plus que ce que CNN et les journaux nous disent, le prochain millénaire ne sera plus “moderne”. Nous ne disons pas cela pour insinuer que vous ferez face à un avenir sauvage ou arriéré (même si c’est possible), mais pour souligner que la période historique qui s’ouvre sera qualitativement différente de celle dans laquelle vous êtes né.

Quelque chose de nouveau est en train d’arriver. De la même manière que les sociétés agricoles différaient en nature des bandes de chasseurs-cueilleurs, et que les sociétés industrielles se distinguaient radicalement des systèmes féodaux ou de petits exploitants, le Nouveau Monde à venir marquera une rupture profonde avec tout ce qui a précédé.

Dans le nouveau millénaire, la vie économique et politique ne sera plus organisée à grande échelle sous la domination de l’État-nation, comme ce fut le cas au cours des siècles modernes. La civilisation qui vous a apporté la guerre mondiale, la chaîne de montage, la sécurité sociale, l’impôt sur le revenu, le déodorant et le four grille-pain est en train de mourir. Le déodorant et le four grille-pain survivront peut-être. Les autres pas. Telle un vieil homme jadis puissant, l’État-nation ne peut plus compter ses années et jours qu’en petit nombre, et non plus en siècles et décennies.

Les gouvernements ont déjà perdu une grande partie de leur pouvoir de régulation et de coercition. L’effondrement du communisme a marqué la fin d’un long cycle de cinq siècles durant lequel l’ampleur de la puissance surpassait l’efficacité dans l’organisation gouvernementale. C’était une époque où la violence rapportait gros, et de mieux en mieux. Ce n’est plus le cas désormais. Une transition de phase d’une ampleur historique a déjà commencé. De fait, le futur « Gibbon », qui racontera la décadence et la chute de l’Âge autrefois moderne dans le millénaire prochain, pourra déclarer qu’il était déjà achevé au moment même où vous lisiez ce livre. Rétrospectivement, il pourra affirmer, comme nous le faisons, que tout s’est terminé avec la chute du mur de Berlin en 1989. Ou bien avec la disparition de l’Union soviétique en 1991. L’une ou l’autre date pourra être considérée comme un événement déterminant de l’évolution de la civilisation, symbolisant la fin de ce que nous nommons aujourd’hui l’Âge moderne.

La quatrième étape du développement humain approche, et l’un de ses aspects les plus imprévisibles est le nouveau nom sous lequel elle sera connue. Appelez-la « Post-moderne ». Appelez-la « Société cybernétique » ou « Ère de l’information ». Ou bien inventez votre propre terme. Personne ne sait encore quelle étiquette finira par coller à la prochaine phase de l’histoire.

Nous ne savons même pas si les cinq siècles d’histoire qui s’achèvent continueront à être vus comme « modernes ». Si les historiens du futur connaissent un tant soit peu la linguistique, ils abandonneront peut-être ce terme. Un titre plus descriptif serait « l’Époque de l’État » ou « l’Ère de la violence ». Mais une telle appellation sortirait du cadre temporel qui définit aujourd’hui les grandes périodes historiques. Selon le *Oxford English Dictionary*, « moderne » se réfère à ce qui est « relatif à l’époque actuelle et récente, par opposition au passé éloigné… Historiquement, on l’applique couramment (par opposition à l’Antiquité et au Moyen Âge) à l’époque postérieure au MOYEN ÂGE ».[^30]

Les Occidentaux s’identifient consciemment comme « modernes » principalement depuis qu’ils ont compris que la période médiévale était révolue. Avant 1500, nul ne songeait à décrire les siècles féodaux comme étant une période « intermédiaire » de la civilisation occidentale. La raison en est évidente si l’on y réfléchit : avant qu’une ère puisse raisonnablement être considérée comme « centrale » entre deux autres périodes historiques, elle doit déjà avoir pris fin. Les hommes ayant vécu à l’époque féodale n’auraient pas pu s’imaginer habiter une sorte de sas entre l’Antiquité et la civilisation moderne, tant qu’ils n’avaient pas conscience, d’une part, que la période médiévale était achevée et, d’autre part, qu’elle différait profondément des Âges sombres ou de l’Antiquité.[^31]

Les cultures humaines ont des angles morts. Nous ne disposons d’aucun vocabulaire permettant de décrire les changements de paradigme se produisant dans les limites les plus vastes de l’existence, particulièrement quand ces évolutions nous entourent. Malgré la quantité de changements spectaculaires qui ont eu lieu depuis Moïse, rares sont les hérétiques qui se sont intéressés aux modalités de transition d’une phase de civilisation à l’autre.

Comment ces transitions sont-elles déclenchées ? Qu’ont-elles en commun ? Quels schémas nous aident à discerner leur commencement et à savoir quand elles prennent fin ? Quand la Grande-Bretagne ou les États-Unis disparaîtront-ils ? Voici des questions auxquelles il serait ardu de trouver une réponse conventionnelle.

### Le tabou sur la prévision

Voir « au-delà » d’un système existant, c’est un peu comme être un machiniste tentant d’engager le dialogue avec un personnage de théâtre. Cela enfreint une convention qui permet à ce système de perdurer. Tout ordre social incorpore parmi ses tabous centraux l’idée selon laquelle les gens qui y vivent ne devraient pas réfléchir à la manière dont cet ordre prendra fin, ni aux règles qui pourraient s’appliquer dans le nouveau système amené à le remplacer. Implicitement, tout système en place se présente comme le dernier ou l’unique système qui existera jamais. Ce n’est évidemment pas énoncé d’une façon si crue ; rares sont ceux qui, ayant lu un livre d’histoire, trouveraient cela plausible si c’était formulé ouvertement. Et pourtant, c’est la convention qui régit le monde. Chaque système social, qu’il tienne le pouvoir fermement ou faiblement, feint que ses règles ne seront jamais supplantées. Elles sont la parole ultime. Ou peut-être la seule qui vaille. Les sociétés primitives considèrent leur organisation comme la seule possible. Dans des systèmes plus complexes, intégrant une notion d’histoire, on se conçoit généralement à son sommet. Qu’il s’agisse des mandarins chinois à la cour de l’empereur, de la nomenklatura marxiste au Kremlin de Staline, ou des membres de la Chambre des représentants à Washington, les puissants ne s’imaginent pas d’autre histoire possible, ou bien se placent au pinacle de l’Histoire : ils estiment être en position supérieure à toutes les époques antérieures et en tête de file de tout avenir à venir.

Ce phénomène s’explique presque inévitablement. À mesure qu’il devient clair qu’un système approche de sa fin, les gens se montreront de moins en moins enclins à en respecter les lois. Par conséquent, tout ordre social aura tendance à décourager ou à atténuer les analyses qui prévoient sa disparition. Rien que pour cette raison, les grandes transitions de l’Histoire passent rarement pour telles au moment où elles surviennent. Si vous cherchez une certitude sur l’avenir, retenez au moins ceci : les changements majeurs ne seront ni annoncés ni accueillis favorablement par les penseurs dominants.

Vous ne pouvez pas compter sur les sources d’information conventionnelles pour vous alerter de façon impartiale et en temps opportun quant à l’évolution du monde et à ses raisons d’être. Si vous voulez appréhender la grande transition en cours, vous disposez de peu d’options : vous devez l’analyser par vous-même.

### Au-delà de l’évidence

Cela implique de regarder au-delà de l’évidence. Les faits montrent que même lorsqu’une transition est indéniablement réelle a posteriori, elle peut ne pas être reconnue avant des décennies, voire des siècles. Observons la chute de Rome. C’est probablement l’événement historique le plus marquant du premier millénaire de l’ère chrétienne. Et pourtant, longtemps après la disparition de Rome, l’illusion de sa survie a été exhibée aux yeux de tous, à l’image du cadavre embaumé de Lénine. Nul qui dépendait des prétextes officiels pour comprendre « l’actualité » n’aurait appris la chute de Rome qu’une fois cette information devenue sans intérêt pratique.

La lenteur des communications dans l’Antiquité n’en est pas la seule cause. Les choses se seraient déroulées de façon semblable même si, par miracle, CNN avait existé, diffusant ses reportages vidéo en septembre 476. Cette année-là, le dernier empereur romain d’Occident, Romulus Augustulus, fut capturé à Ravenne puis forcé de se retirer dans une villa de Campanie, avec une pension. Même si Wolf Blitzer s’était trouvé là, caméra au poing, en 476, il est peu probable qu’il ou quiconque eût osé affirmer que ces événements marquaient la fin de l’Empire romain. Et pourtant, c’est précisément ce que les historiens diront plus tard.

Les rédacteurs de CNN n’auraient sans doute pas envisagé une manchette proclamant : « Rome est tombée ce soir ». Les pouvoirs en place niaient cette possibilité. Les diffuseurs d’« actualités » ne se montrent guère enclins à la controverse si elle doit leur nuire commercialement. Ils peuvent bien sûr être partisans, voire outrageusement partis pris. Mais ils rapportent rarement des conclusions qui pousseraient leurs abonnés à résilier leur abonnement et à fuir dans les montagnes. Voilà pourquoi presque personne n’aurait parlé de la chute de Rome, même si la technologie l’avait permis. Les experts auraient déclaré qu’il était ridicule de parler de la chute de Rome. Or affirmer le contraire aurait été néfaste, tant pour les affaires que pour la sécurité des rapporteurs. Le pouvoir, à la fin du Ve siècle, était détenu par des barbares qui niaient la fin de Rome.

Mais ce n’était pas qu’une affaire de censure du type « Ne diffuse pas cela ou tu mourras ». En vérité, Rome était déjà si dégénérée dans les dernières décennies du Ve siècle que sa « chute » était passée inaperçue aux yeux de la plupart des contemporains. En réalité, il fallut une génération de plus pour que le comte Marcellinus formule le premier l’idée que « L’Empire romain d’Occident a péri avec cet Augustulus ».[^32] Bien des décennies, voire des siècles, s’écoulèrent avant qu’on admette collectivement que l’Empire romain d’Occident n’existait plus. Assurément, Charlemagne estimait encore être un empereur romain légitime en l’an 800.

Le constat n’est pas que Charlemagne et tous ceux qui raisonnaient en termes conventionnels sur l’Empire romain après 476 étaient des idiots. Bien au contraire. La caractérisation des évolutions sociales est fréquemment ambiguë. Quand la puissance d’institutions dominantes vient renforcer une conclusion commode — même fondée en grande partie sur des simulacres —, seuls des individus de caractère et d’avis tranchés oseraient la contester. Si vous vous placez dans la peau d’un Romain du Ve siècle finissant, il devient aisé d’imaginer l’attrait qu’il y avait à conclure que rien n’avait changé. C’était la vision la plus optimiste. Penser autrement aurait été effrayant. Et pourquoi adopter une telle angoisse quand une explication rassurante est à portée de main ?

Après tout, on pouvait arguer que tout continuerait comme avant. Il y avait eu des précédents. L’armée romaine, surtout les garnisons frontalières, s’était « barbarisée » depuis plusieurs siècles.[^33] Dès le IIIe siècle, l’armée avait l’habitude de proclamer un nouvel empereur. Au IVe siècle, même ses officiers étaient germanisés et souvent illettrés.[^34] Il y avait eu de multiples renversements violents d’empereurs avant le retrait de Romulus Augustulus. À l’époque, sa déposition passait sans doute pour un bouleversement de plus dans un contexte chaotique. Il avait d’ailleurs été chassé avec une pension. Le simple fait qu’il ait touché une pension, même pour une brève période avant son assassinat, pouvait rassurer quant à la continuité du système. Dans l’esprit d’un optimiste, Odoacre, qui avait déposé Romulus Augustulus, ne détruisait pas l’empire : il le réunifiait. Fils d’Edecon, allié d’Attila, Odoacre était un homme rusé. Il ne se proclama pas empereur. Il convoqua plutôt le Sénat et les persuada, trop facilement, d’offrir la fonction impériale, et donc la souveraineté sur l’ensemble de l’empire, à Zénon, empereur d’Orient, installé au lointain Byzance. Odoacre n’était censé n’être que le *patricius* de Zénon, gouvernant l’Italie.

Comme l’écrit Will Durant dans *The Story of Civilization*, ces changements ne paraissaient pas constituer la « chute de Rome » mais de simples « ajustements mineurs à la surface du paysage national ».[^35] Lorsque Rome tomba, Odoacre proclama sa survie. Avec presque tout le monde, il tenait à maintenir l’illusion qu’il ne s’était rien passé. Chacun savait que « la gloire de Rome » valait bien mieux que la barbarie qui la remplaçait. Même les barbares le reconnaissaient. Comme le note C. W. Previte-Orton dans *The Shorter Cambridge Medieval History*, la fin du Ve siècle, lorsque « les empereurs avaient été supplantés par des rois barbares germaniques », fut une ère de « supercherie persistante ».[^36]

### « Supercherie persistante »

Cette « supercherie » consistait à maintenir la façade de l’ancien système, même quand il était « déformé par la barbarie ».[^37] Les structures de gouvernement demeurèrent en place après le remplacement du dernier empereur par un « lieutenant » barbare. Le Sénat siégeait encore. « La préfecture du prétoire et d’autres hautes fonctions perdurèrent, aux mains de notables Romains ».[^38] Les consuls continuaient à être nommés pour un an. « L’appareil civil romain survivait intact ».[^39] Effectivement, il resta formellement en place jusqu’à l’émergence du féodalisme, à la fin du Xe siècle. Lors des cérémonies publiques, on utilisait toujours l’ancien apparat impérial. Le christianisme demeurait religion d’État. Les barbares affichaient encore une supposée allégeance à l’empereur d’Orient à Constantinople, et aux traditions du droit romain. En réalité, comme le souligne Durant, « en Occident, le grand Empire n’existait plus ».[^40]

### Et alors ?

L’exemple lointain de la chute de Rome nous éclaire de plusieurs manières sur la situation actuelle dans le monde. La plupart des ouvrages sur l’avenir sont en réalité des livres sur le présent. Nous essayons d’éviter cet écueil en proposant ici, avant tout, une réflexion sur le futur qui est aussi un ouvrage sur le passé. Nous estimons que vous pourrez mieux appréhender l’avenir si nous illustrons les points mégapolitiques essentiels relatifs à la « logique de la violence » avec des exemples concrets du passé. L’histoire est un professeur stupéfiant. Ses récits sont plus captivants que tout ce que nous pourrions inventer, et nombre des épisodes les plus intéressants se rapportent à la chute de Rome. Ils exposent des leçons importantes qui pourraient toucher à votre avenir dans l’Ère de l’information.

En premier lieu, l’effondrement de Rome illustre de manière saisissante ce qui se produit dans le cadre d’une grande transition, lorsque l’échelle de gouvernement s’effondre. Les transformations de l’an mil ont aussi impliqué la disparition d’une autorité centrale, tout en augmentant la complexité et l’ampleur de l’activité économique. La « Révolution de la poudre à canon » à la fin du XVe siècle a engendré des modifications institutionnelles importantes qui ont plutôt gonflé, au lieu de les restreindre, les dimensions du pouvoir politique. Aujourd’hui, pour la première fois en un millénaire, les conditions mégapolitiques en Occident saperont et anéantiront les gouvernements et un nombre d’autres institutions fonctionnant à grande échelle.

Bien sûr, la décélération de la gouvernance à la fin de l’Empire romain n’a pas les mêmes causes que la montée en puissance de la Société de l’information. Une partie des raisons pour lesquelles Rome est tombée découle simplement du fait qu’elle s’était étendue au-delà de ce que permettaient les économies de la violence. Le coût de maintien de son immense frontière dépassait largement les avantages économiques qu’une économie agricole antique pouvait supporter. Le fardeau des impôts et de la régulation, destiné à financer l’effort militaire, avait fini par excéder les capacités de l’économie. La corruption généralisée n’arrangeait rien. Comme l’a documenté l’historien Ramsay MacMullen, une partie considérable de l’activité des commandants militaires consistait à rechercher les « profits illicites du commandement ».[^41] Ils y parvenaient en pressurant la population. Synésius, observateur du IVe siècle, décrivit cette situation comme « la guerre en temps de paix, presque pire que la guerre barbare, née de l’indiscipline des soldats et de l’avidité des officiers ».[^42]

Un autre facteur décisif dans l’effondrement romain fut la chute démographique provoquée par les pestes antonines. Le déclin de la population romaine dans de nombreuses régions contribua évidemment à la faiblesse économique et militaire. Aujourd’hui, nous ne connaissons rien de semblable, du moins pas encore. À plus longue échéance, il est possible que l’humanité doive affronter de nouvelles « pandémies » susceptibles d’aggraver les défis liés à la dévolution technologique dans le nouveau millénaire. L’explosion démographique inédite au XXe siècle constitue une cible de choix pour des germes en mutation rapide. Les craintes de voir le virus Ebola (ou un autre) contaminer les centres urbains n’ont peut-être rien d’extravagant. Mais ce n’est pas ici le sujet que nous traitons. Notre propos n’est pas d’établir pourquoi Rome s’est effondrée ni de comparer nos vulnérabilités actuelles à celles de l’Empire romain. Nous souhaitons souligner autre chose : la façon dont les grandes transitions de l’Histoire sont perçues, ou plutôt méconnues, au moment même où elles surviennent.

Partout et à tout moment, l’humain présente un certain conservatisme inné, avec un petit « c ». Cela se traduit par une réticence à imaginer la disparition de conventions sociales anciennes, l’effondrement des institutions établies, et le rejet des lois et principes qui définissaient leur cadre de référence. Peu de gens sont enclins à croire que quelques infimes variations climatiques ou technologiques, ou tout autre paramètre, pourraient suffire à rompre le lien avec le monde de leurs aïeux. Les Romains répugnaient à reconnaître la métamorphose qui les entourait. Nous sommes pareils.

Que nous l’admettions ou non, nous vivons un changement d’ère historique, une mutation dans la manière dont les gens organisent leur subsistance et se protègent, si profonde qu’elle métamorphosera inévitablement la société tout entière. Elle sera si radicale qu’il faudra envisager un réexamen complet de nos certitudes. On vous invitera à presque chaque détour à croire que les futures Sociétés de l’information ressembleront à la société industrielle de votre enfance. Nous en doutons. La micro-informatique sapera le ciment reliant les briques. Elle changera à ce point la logique de la violence qu’elle modifiera profondément les modes d’organisation économique et de défense. Et pourtant, on aura tendance à minimiser l’inéluctabilité de ces bouleversements ou à en débattre comme si les institutions industrielles pouvaient, par un décret, décider de l’orientation de l’Histoire.

### La grande illusion

Même des auteurs plus informés que nous risquent de vous égarer lorsqu’ils abordent le futur, car ils restent trop superficiels dans leur analyse du fonctionnement des sociétés. Par exemple, David Kline et Daniel Burstein ont rédigé un ouvrage très documenté intitulé *Road Warriors: Dreams and Nightmares Along the Information Highway*. Il contient maints détails fort intéressants, mais une grande partie de ces informations sert à soutenir une illusion : l’idée « que les citoyens peuvent s’unir, consciemment, pour façonner les processus économiques et naturels spontanés qui se déroulent autour d’eux ».[^43] Cela équivaut, sans que cela soit évident, à affirmer que le féodalisme aurait pu se perpétuer si tout le monde avait redécouvert l’esprit de chevalerie. Personne, à la cour de la fin du XVe siècle, n’aurait trouvé à redire à un tel sentiment. Il aurait même été blasphématoire de le faire. Mais ce constat n’en reste pas moins trompeur : c’est le serpent qui tente de ramener l’avenir à l’exiguïté de sa vieille peau.

Les causes fondamentales du changement sont précisément celles qui échappent au contrôle conscient. Ce sont les facteurs qui altèrent les conditions dans lesquelles la violence est rentable. Ils sont si éloignés de toute possibilité de manipulation qu’ils ne se prêtent même pas à la joute politique, dans un monde pourtant saturé de politique. Personne n’a jamais défilé en scandant : « Augmentons les économies d’échelle dans le processus de production ». Aucun panneau n’a jamais exigé : « Inventons une arme renforçant l’infanterie ». Aucun candidat n’a fait campagne en promettant « d’ajuster l’équilibre entre efficacité et volume en matière de protection contre la violence ». Ces slogans seraient absurdes, précisément parce que leurs objectifs échappent à toute influence humaine directe. Et pourtant, comme nous allons le détailler, ces variables déterminent dans une large mesure le fonctionnement du monde, bien plus que n’importe quel programme politique.

À bien y réfléchir, il devrait vous paraître évident que les transitions majeures de l’Histoire ne sont généralement pas dictées par les désirs humains. Elles ne surviennent pas parce qu’un peuple se lasse soudainement d’un mode de vie et lui préfère un autre. Une brève réflexion indique pourquoi. Si pensées et désirs humains étaient les uniques moteurs des événements, toutes les mutations historiques radicales devraient s’expliquer par des revirements d’humeur collectifs dépourvus d’ancrage dans la réalité. Or, cela n’arrive jamais. Seules des anomalies médicales, touchant quelques personnes, peuvent générer des fluctuations d’humeur sans cause externe évidente.

En règle générale, un grand nombre d’individus ne vont pas abandonner subitement et tous ensemble leur mode de vie juste pour se distraire. Aucun chasseur-cueilleur ne s’est jamais exclamé : « J’en ai assez de la Préhistoire, je préfère être un paysan. » Les changements importants de comportements et de valeurs résultent invariablement d’une évolution concrète des conditions de vie. En ce sens au moins, l’homme reste réaliste. S’il se met à changer brusquement d’opinion, c’est probablement parce qu’il a subi un choc : invasion, épidémie, variation climatique soudaine ou révolution technologique bouleversant ses moyens de subsistance ou ses modalités de défense.

Bien loin d’exaucer les espoirs humains, les virages historiques majeurs contredisent le plus souvent le désir largement répandu de stabilité. Lorsqu’ils se produisent, ils provoquent en général une grande désorientation, surtout parmi ceux qui se retrouvent déclassés ou perdent un revenu. Les sondages d’opinion ou autres baromètres du moral collectif n’éclaireront guère le déroulement probable de la transition mégapolitique actuelle.

## VIVRE SANS VISÉE PROSPECTIVE

Si nous ne percevons pas la grande transition qui se déroule sous nos yeux, c’est en partie parce que nous ne voulons pas la voir. Nos ancêtres chasseurs-cueilleurs faisaient peut-être preuve de la même mauvaise volonté, mais ils pouvaient se prévaloir d’une meilleure excuse. Il y a dix mille ans, nul n’aurait pu prévoir les suites de la Révolution agricole. En effet, on ne pouvait envisager grand-chose au-delà de la recherche du prochain repas. Quand l’agriculture a fait son apparition, il n’y avait ni archives ni recul sur l’Histoire permettant d’envisager l’avenir. Et il n’existait pas encore cette conception occidentale du temps segmenté en unités récurrentes (secondes, minutes, heures, jours, etc.) pour organiser les années. Les chasseurs-cueilleurs vivaient dans un « prés éternel », dépourvu de calendrier, et bien sûr d’écrits. Ils ne disposaient d’aucune science, ni d’aucun autre outil intellectuel pour comprendre la causalité au-delà de leur seule intuition. En matière d’anticipation, nos ancêtres préhistoriques étaient aveugles. Pour reprendre l’allégorie biblique, ils n’avaient pas encore goûté le fruit de la connaissance.

### Apprendre du passé

Heureusement, nous disposons aujourd’hui d’une meilleure perspective. Cinq cents générations nous ont légué des moyens d’analyse qui faisaient totalement défaut à nos lointains prédécesseurs. La science et les mathématiques nous ont permis d’arracher à la nature bien des secrets, nous donnant une compréhension de la causalité qui confinerait presque à la magie, comparée à celle des chasseurs-cueilleurs. Les algorithmes de calcul, développés à l’ère des ordinateurs, fournissent un nouvel éclairage sur la dynamique des systèmes complexes, tels que l’économie humaine. Le laborieux développement de l’économie politique, quoique très imparfait, a amélioré notre compréhension des motivations humaines. Parmi ces dernières, se trouve l’idée que, de tout temps et en tout lieu, l’homme réagit généralement aux incitations. Pas toujours de façon aussi automatique que certains économistes l’imaginent, mais il réagit ; coûts et récompenses comptent. Les changements externes qui rendent certains comportements plus ou moins rentables en modifient la fréquence, toutes choses égales par ailleurs.

### Les incitations comptent

Le fait que les hommes réagissent généralement aux coûts et aux bénéfices constitue un point capital pour toute prévision. On peut affirmer avec un degré élevé de certitude que si vous laissez tomber un billet de cent dollars dans la rue, quelqu’un finira par le ramasser, que vous soyez à New York, Mexico ou Moscou. Cela peut sembler trivial, mais prouve que ceux qui affirment l’impossibilité de prévoir quoi que ce soit se trompent. Toute prédiction qui anticipe correctement l’impact des incitations sur le comportement sera probablement globalement juste. Et plus l’évolution prévue des coûts et des bénéfices est importante, plus la prévision conséquente sera de grande ampleur.

Les prévisions les plus vastes viennent précisément de la compréhension des changements concernant les variables mégapolitiques. La violence constitue la limite ultime qui encadre le comportement. Ainsi, si vous discernez de quelle façon la logique de la violence va se modifier, vous pouvez prévoir où les gens laisseront tomber ou ramasseront l’équivalent de billets de cent dollars dans le futur.

Cela ne signifie pas que vous pouvez deviner l’indéchiffrable. Nous ne vous dirons pas comment trouver les bons numéros de loterie ni prévoir un événement réellement aléatoire. Nous ignorons si un attentat atomique frappera Manhattan, ni quand. Ou bien si un astéroïde s’écrasera sur l’Arabie saoudite. Nous ne pouvons prédire l’arrivée d’une nouvelle période glaciaire, une éruption volcanique soudaine ou l’éclosion d’une maladie inédite. Les événements inconnaissables susceptibles de modifier le cours de l’Histoire sont innombrables. Mais distinguer l’indéchiffrable du simple fait d’examiner les tenants et aboutissants de ce que l’on sait déjà fait toute la différence. Si vous apercevez un éclair au loin, vous pouvez prédire avec une bonne probabilité de succès qu’un coup de tonnerre suivra. Cerner les conséquences des transitions mégapolitiques se situe dans une temporalité plus étendue et selon des corrélations moins fermes, mais relève du même exercice.

Les catalyseurs mégapolitiques de la transformation se manifestent souvent bien avant que leurs effets ne soient tangibles. Il a fallu cinq mille ans pour que la Révolution agricole révèle pleinement ses implications. Le passage de la société rurale à la société industrielle, basée sur la production manufacturière et la force chimique, s’est opéré plus rapidement : cela a pris des siècles. La transition vers la Société de l’information sera plus rapide encore, probablement sur une seule génération. Pourtant, même en tenant compte de la condensation historique, des dizaines d’années s’écouleront sans doute avant que s’exprime toute la portée mégapolitique de la technologie déjà existante.

### Paliers majeurs et mineurs de la transition mégapolitique

Le présent chapitre analyse certaines caractéristiques communes aux transitions mégapolitiques. Dans les chapitres suivants, nous évoquerons plus en détail la Révolution agricole et la transition de la ferme à l’usine, la seconde grande mutation historique. Dans la période agricole, de nombreuses transitions mégapolitiques de moindre envergure ont eu lieu, comme la chute de Rome et la révolution féodale autour de l’an 1000. Elles ont correspondu aux variations du rapport de force, à mesure que les gouvernements se formaient puis se délitaient, et que les bénéfices de l’agriculture passaient de l’une à l’autre. Les grands propriétaires terriens sous l’Empire romain, les fermiers indépendants durant le Haut Moyen Âge européen, et les seigneurs et serfs de la période féodale, tous se nourrissaient des mêmes céréales mais vivaient sous des gouvernements très différents, reflet des modifications cumulées de la technologie, du climat et des maladies.

Notre objectif n’est pas d’expliquer intégralement toutes ces évolutions. Nous ne prétendons pas à cette exhaustivité, même si nous en exposons quelques illustrations révélatrices de l’influence des fluctuations mégapolitiques sur l’exercice du pouvoir dans le passé. Les gouvernements grandissaient ou se réduisaient en fonction du coût d’extension et de la rentabilité de la mainmise.

Retenez quelques points synthétiques pour appréhender la Révolution de l’information :

1. Un changement dans les fondements mégapolitiques du pouvoir surgit habituellement bien avant les révolutions effectives dans l’utilisation de la force.  
2. Les revenus sont en général en baisse quand commence une grande transition, souvent parce qu’une société s’est elle-même fragilisée, par exemple en saturant ses ressources du fait de la pression démographique.  
3. Il est souvent tabou de « sortir » du système. Les gens ne voient généralement pas la logique de la violence qui prévaut dans leur société ; par conséquent, ils sont presque toujours aveugles aux évolutions de cette logique, latentes ou manifestes. Les transitions mégapolitiques passent rarement pour telles avant leur concrétisation.  
4. Les grandes mutations s’accompagnent toujours d’une révolution culturelle et se traduisent généralement par des conflits entre les partisans de l’ancien et du nouveau système de valeurs.  
5. Les transitions mégapolitiques ne suscitent jamais l’enthousiasme populaire, car elles décrédibilisent tout un capital intellectuel patiemment accumulé et contredisent les impératifs moraux consacrés. Elles ne résultent pas d’une demande populaire, mais sont imposées par des transformations extérieures qui modifient la logique de la violence dans l’environnement considéré.  
6. Les nouvelles façons d’organiser la subsistance ou de gouverner commencent à se développer localement dans les zones soumises aux catalyseurs mégapolitiques.  
7. À l’exception peut-être des débuts de l’agriculture, les transitions passées se sont toujours accompagnées de chaos social et d’une hausse de la violence, conséquence de la désorientation et de la désintégration de l’ancien ordre.  
8. La corruption, la décadence morale et l’inefficacité semblent être les traits distinctifs de la phase finale d’un système.  
9. L’importance grandissante de la technologie dans le façonnement de la logique de la violence a accéléré la cadence de l’Histoire, et chaque transition successive bénéficie d’un temps d’adaptation moindre qu’auparavant.

### L’Histoire s’accélère

Avec des événements progressant bien plus vite qu’au cours des révolutions précédentes, comprendre suffisamment tôt les changements qui se profilent pourrait vous être bien plus utile que ça ne l’aurait été à vos ancêtres dans la même situation. Même si les premiers agriculteurs avaient miraculeusement saisi toute la portée mégapolitique de la culture des terres, ce savoir leur aurait été quasiment inutile car il s’est écoulé plusieurs millénaires avant l’achèvement de la transition à la nouvelle forme de société.

Il n’en va pas de même aujourd’hui. Le rythme historique s’est accéléré. Des prévisions intelligentes sur l’impact mégapolitique des nouvelles technologies vaudront sans doute beaucoup plus cher à notre époque. Si nous parvenons à dégager les conséquences actuelles de la transition vers la Société de l’information avec la même acuité que pourrait le faire quelqu’un de notre temps appliquant son savoir aux anciennes transitions vers la ferme ou l’usine, ces informations seront démultipliées par l’effet d’une histoire condensée. En d’autres termes, l’horizon d’action des prévisions mégapolitiques se réduit à un intervalle idéal, dans la durée d’une seule vie humaine.

> "Looking back over the centuries, or even f looking only at the present, we can clearly observe that many men have made their living, Often a very good living, from their special skill in applying weapons of violence, and that their activities have had a very large part in determining what uses were made of scarce resources."[^44] FREDERIC C. LANE

Notre étude de la mégapolitique s’efforce précisément de dégager les conséquences des facteurs susceptibles de changer les frontières où s’exerce la violence.

Ces facteurs mégapolitiques déterminent en grande partie l’endroit et la manière dont il est rentable d’employer la force. Ils font aussi partie intégrante de la répartition économique des revenus. Comme l’a clairement exprimé l’historien de l’économie Frederic Lane, la façon dont la violence est utilisée et contrôlée joue un rôle crucial dans la destinée des « ressources rares ».[^44][^45]

## LEÇON DE MÉGAPOLITIQUE EXPRESS

Le concept de mégapolitique est très puissant. Il éclaire certaines énigmes majeures de l’Histoire : l’avènement et la chute des gouvernements, leurs formes institutionnelles, la chronologie et l’issue des guerres, ou encore les cycles de prospérité et de déclin économiques. En augmentant ou en réduisant les coûts et les gains potentiels de la coercition, la mégapolitique détermine la possibilité pour les uns d’imposer leur volonté aux autres. C’est vrai depuis les sociétés humaines les plus anciennes. Et ça l’est toujours. Nous avons déjà exposé dans *Blood in the Streets* et *The Great Reckoning* divers facteurs mégapolitiques clés qui façonnent l’évolution de l’Histoire. La clef permettant d’anticiper les conséquences d’une fluctuation mégapolitique est de comprendre les variables qui déclenchent les révolutions dans l’usage de la force. On peut, de façon un peu artificielle, regrouper ces variables en quatre catégories : topographie, climat, microbes et technologie.

1. La **topographie** est un facteur crucial, comme le montre le fait que la domination de la violence en haute mer n’a jamais été aussi facilement monopolée qu’à terre. Aucune loi gouvernementale ne s’y est appliquée à titre exclusif. C’est un aspect de la plus haute importance pour comprendre comment l’organisation de la violence et de la protection évoluera à mesure que l’économie migrera vers le cyberespace.

   La topographie, conjointement au climat, a joué un grand rôle dans l’Antiquité. Les premiers États virent le jour dans des plaines alluviales bordées de déserts, comme en Mésopotamie et en Égypte : il y avait de l’eau pour irriguer, mais les régions alentour, trop arides, ne pouvaient faire vivre des paysans indépendants. Ces conditions imposaient un coût énorme à quiconque refusait de collaborer, car sans irrigation, qui nécessitait une gestion à grande échelle, les récoltes ne poussaient pas ; sans récolte, on mourait de faim. C’est ainsi que ceux qui contrôlaient l’eau dans le désert se retrouvaient en position de force, suscitant des gouvernements riches et despotiques.

   Comme nous l’analysions dans *The Great Reckoning*, la topographie a aussi joué un rôle majeur dans la prospérité des petits exploitants en Grèce antique, ce qui a fait de cette région le berceau de la démocratie occidentale. Étant donné l’état primitif des transports en Méditerranée il y a trois millénaires, il était pratiquement impossible pour des populations vivant à plus de quelques kilomètres du littoral d’être compétitives dans la production de raisins et d’olives — produits phares de l’époque. Les frais de portage devenaient prohibitifs dès qu’il fallait transporter l’huile ou le vin loin. L’extrême découpage du littoral grec faisait qu’une grande partie du territoire se trouvait à moins de trente kilomètres de la mer, conférant un avantage considérable aux agriculteurs grecs face à leurs concurrents de l’intérieur.

   Grâce à cet avantage commercial pour des produits à forte valeur ajoutée, les fermiers grecs pouvaient dégager de hauts revenus sur de petites parcelles. Ils pouvaient ainsi se payer une armure coûteuse. Les fameux hoplites de la Grèce antique étaient des agriculteurs ou des propriétaires qui s’équipaient à leurs frais. Bien armés et très motivés, ils se montraient redoutables au combat et impossibles à négliger. Cette situation liée à la géographie sous-tendait la démocratie grecque, de la même manière qu’un autre type de conditions dans les zones orientales y avait engendré despotisme.

2. Le **climat** fixe également les bornes à l’expansion de la force brutale. Un épisode climatique est à l’origine de la première grande transition, de la cueillette à l’agriculture.

   La fin de la dernière période glaciaire, il y a environ treize millénaires, s’accompagna d’une transformation marquée de la végétation. Au Proche-Orient, la hausse graduelle des températures et des précipitations entraîna un recul rapide de la steppe au profit de la forêt. En particulier, l’essor massif des hêtraies réduisit fortement l’offre alimentaire pour les humains. Comme l’explique Susan Alling Gregg dans *Foragers and Farmers* :

   > « L’établissement de la hêtraie dut avoir des conséquences majeures pour les populations humaines, végétales et animales locales. Le couvert d’une chênaie est relativement ouvert et laisse passer beaucoup de lumière au sol. Un sous-bois foisonnant de buissons, plantes herbacées et graminées s’y développe, formant un milieu très diversifié apte à héberger quantité d’animaux. En revanche, le couvert d’une hêtraie est fermé ; le sol forestier est fortement ombragé. Hormis une floraison d’annuelles au printemps, avant l’apparition des feuilles, seules certaines fougères, des graminées d’ombre et quelques plantes de sous-bois s’y épanouissent. »[^46]

   Petit à petit, les forêts denses ont grignoté les plaines de toute l’Europe jusqu’aux steppes orientales.[^47] Le recul des pâturages disponibles pour le gros gibier a rendu la vie des chasseurs-cueilleurs plus difficile. La population humaine, alors nombreuse grâce à la prospérité de l’ère glaciaire, ne parvenait plus à se nourrir, d’autant que certains grands mammifères avaient disparu du fait d’une chasse excessive. L’agriculture s’imposa sous la contrainte, pour compenser les pénuries alimentaires. La cueillette subsista dans les zones nordiques où le réchauffement n’avait pas altéré l’habitat des grands mammifères, et dans les forêts tropicales, où le réchauffement ne réduisait pas l’offre alimentaire. Depuis la révolution agricole, il est bien plus courant que les grandes transitions soient provoquées par des refroidissements climatiques plutôt que par des réchauffements.


   Une compréhension, même modeste, des dynamiques climatiques dans les civilisations passées peut se révéler précieuse si le climat continue de varier fluctuellement. Sachant par exemple qu’une baisse moyenne de température de un degré Celsius raccourcit la saison de croissance de trois ou quatre semaines et abaisse d’environ 150 mètres l’altitude maximale de culture, on cerne mieux les contraintes futures.[^48] On peut s’appuyer sur cette connaissance pour anticiper l’influence sur les prix du grain ou la valorisation foncière, voire tirer des conclusions sur l’atteinte possible aux revenus réels et sur la stabilité politique. Par le passé, plusieurs gouvernements ont été renversés à la suite d’incuries agricoles successives provoquant de fortes flambées des prix alimentaires et une réduction des revenus disponibles.

   Il n’est pas anodin que le XVIIe siècle, le plus froid de la période moderne, ait aussi connu un cycle mondial de révolutions. Une cause mégapolitique cachée résidait dans ce net refroidissement, au point que le “Roi-Soleil” vit geler son vin à Versailles. Le raccourcissement de la saison de croissance provoqua des récoltes médiocres et attisa la baisse des revenus réels. Une longue dépression mondiale commença vers 1620. Elle engendra des troubles considérables. Durant cette crise économique du XVIIe siècle, la planète fut submergée de soulèvements, nombre d’entre eux survenant en 1648, pile deux cents ans avant un autre cycle révolutionnaire célèbre. Entre 1640 et 1650, on assista à des révoltons en Irlande, en Écosse, en Angleterre, au Portugal, en Catalogne, en France, à Moscou, Naples, Sicile, au Brésil, en Bohême, Ukraine, Autriche, Pologne, Suède, aux Pays-Bas, en Turquie, sans oublier la Chine et le Japon.

   Rien d’étonnant si le mercantilisme triompha au XVIIe siècle, dans un contexte de baisse des échanges commerciaux. La fermeture économique atteignit probablement son paroxysme à la fin du siècle, « lorsqu’une famine majeure se produisit ».[^49] Au XVIIIe siècle, surtout après 1750, des températures plus élevées augmentèrent les rendements en Europe de l’Ouest, rehaussant le niveau de vie et élargissant la demande de biens manufacturés. L’on adopta alors des mesures plus favorables au libre-échange. Cela aboutit à une croissance économique soutenue, à mesure que l’industrie se développait massivement, phénomène souvent associé à la Révolution industrielle. L’importance grandissante de la technologie et de la production manufacturière atténua le rôle des conditions climatiques dans les cycles économiques.

   Néanmoins, il ne faut pas sous-estimer l’éventualité que des refroidissements brusques abaissent les revenus réels, même dans des régions riches comme l’Amérique du Nord. Les sociétés tendent à se rendre structurellement vulnérables quand leur modèle institutionnel a épuisé son potentiel. Dans le passé, cela se traduisait souvent par la surpopulation, saturant la capacité des terres. Ce fut le cas avant la transition de l’an 1000 et de nouveau à la fin du XVe siècle. Dans ces deux contextes, la chute des revenus — liée aux mauvaises récoltes et à l’instabilité — avait joué un rôle majeur dans l’anéantissement des institutions dominantes. Aujourd’hui, c’est le marché du crédit à la consommation qui se retrouve dans une situation fragile. Si un net refroidissement climatique réduisait les rendements agricoles et les revenus, cela déclencherait des défauts de paiement et de possibles mouvements de révolte fiscale. Comme par le passé, on pourrait assister à un repli économique et à des soulèvements politiques.

3. Les **microbes** procurent le pouvoir de nuire ou l’immunité, et peuvent influencer significativement l’exercice du pouvoir. On le voit nettement dans la conquête européenne du Nouveau Monde, comme nous l’avions expliqué dans *The Great Reckoning*. Les colons européens, issus de sociétés agricoles denses et très exposées aux épidémies, bénéficiaient d’une immunité relative contre des maladies infantiles comme la rougeole. Les peuples autochtones, vivant en petites tribus de chasseurs-cueilleurs, en étaient dépourvus et furent décimés. Bien souvent, la mortalité la plus élevée survenait avant même l’arrivée des Européens : des autochtones, ayant eu un premier contact avec les nouveaux venus sur les côtes, transportaient les germes en voyageant vers l’intérieur des terres.

   Il existe aussi des limites microbiologiques à l’extension de la puissance. Dans *Blood in the Streets*, nous avions évoqué l’impact des souches virulentes du paludisme, qui rendirent longtemps l’Afrique tropicale imperméable à l’invasion des Européens. Avant la découverte de la quinine au milieu du XIXe siècle, les armées blanches ne pouvaient subsister dans les zones impaludées, quelles que soient leurs armes.

   Les relations entre humains et microbes ont également entraîné des fluctuations démographiques influant sur le coût-bénéfice de la violence. Là où la mortalité fluctuait beaucoup (maladie, famine, etc.), prendre le risque de la guerre revenait proportionnellement moins cher. À partir du XVIe siècle, la fréquence des pics de mortalité (catastrophes épidémiques) a décliné, favorisant la réduction de la taille des familles puis celle de la tolérance à la mort immédiate dans les conflits. Les sociétés à faible taux de natalité ont peu de patience pour les pertes, même modestes, sur les champs de bataille, ce qui élève le prix de la violence. Tandis qu’à l’aube de l’ère moderne, la plupart des parents avaient de nombreux enfants, dont certains devaient inévitablement mourir de maladie avant l’âge adulte. Dans un monde où la mort précoce était un phénomène fréquent, soldats et familles affrontaient les horreurs de la guerre sans trop rechigner.

> "Machinery is aggresive. The weaver becomes a web, the machinist a machine. If you do not use tools, they use you." - Emerson

4. **La technologie** s’est imposée au cours des siècles modernes comme la variable la plus déterminante pour le coût-bénéfice de l’usage de la force. C’est la colonne vertébrale de notre argument : elle perdurera dans ce rôle. La technologie comporte divers axes cruciaux :

   A. **Équilibre entre offensive et défensive**. L’équilibre entre ces deux volets, dicté par l’arme dominante du moment, aide à déterminer l’ampleur de l’organisation politique. Quand les capacités offensives augmentent, la faculté de projeter la puissance à distance progresse, favorisant la consolidation des États à large échelle. À l’inverse, quand la défense l’emporte, il devient plus coûteux de s’étendre hors de ses bases. Les gouvernements tendent alors à se fragmenter.

   B. **Égalité et vigueur de l’infanterie**. Un paramètre essentiel régissant l’égalité entre citoyens est la nature de la technologie militaire. Les armes bon marché, accessibles à des non-professionnels et renforçant le rôle de l’infanterie, ont tendance à égaliser la distribution du pouvoir. Quand Thomas Jefferson a écrit que « tous les hommes naissent égaux », cette phrase était bien plus exacte que si elle avait été rédigée quelques siècles auparavant. Un fermier muni d’un fusil de chasse était souvent mieux armé que le soldat britannique équipé d’un *Brown Bess*, car il tirait de plus loin et plus précisément. Cette situation contrastait avec celle du Moyen Âge, où un paysan doté d’une simple fourche, faute de mieux, ne pouvait rien contre un chevalier pesamment équipé. Personne n’aurait proclamé en 1276 que « tous les hommes naissent égaux », une évidence démentie par le fait qu’un seul chevalier surpassait aisément en force physique des dizaines de manants.

   C. **Avantages ou inconvénients de l’échelle dans la violence**. Un autre facteur qui détermine si les gouvernements sont peu nombreux ou pléthoriques touche au niveau d’organisation nécessaire pour manier l’arme dominante du moment. Quand la violence génère des rendements croissants, mieux vaut des gouvernements de grande taille, poussés à l’expansion. À l’inverse, si de petits groupes peuvent efficacement se défendre contre de plus grands, comme c’était le cas au Moyen Âge, la souveraineté se morcelle. De nombreux organismes indépendants exercent alors certaines fonctions régaliennes. Nous pensons, dans les chapitres qui suivront, que l’Âge de l’information amènera l’émergence de « cybersoldats ». Un petit groupe, voire un individu, pourra déployer ces cybersoldats ; les guerres du millénaire à venir comprendront des batailles presque sans effusion de sang, menées avec des ordinateurs.

   D. **Économies d’échelle dans la production**. Une autre dimension cruciale se situe dans la taille des unités productives. Lorsque le fonctionnement optimal de l’industrie nécessite un territoire large et intégré, un gouvernement qui fédère un espace suffisamment vaste pourra en tirer assez de profit (par la taxation ou d’autres moyens) pour financer une structure politique de grande envergure. Dans ces conditions, l’économie mondiale trouve un avantage à se trouver sous la tutelle d’une puissance dominante, comme le fit l’Empire britannique au XIXe siècle. Mais il arrive que les mêmes variables mégapolitiques induisent des rendements d’échelle décroissants. Les grands gouvernements, dont la prospérité reposait sur l’exploitation d’immenses zones économiques, peuvent dès lors se désagréger — même si l’équilibre balistique entre attaque et défense ne varie pas fondamentalement.

   E. **Diffusion des technologies**. Un facteur supplémentaire dans l’équation de puissance est le degré de diffusion des avancées cruciales. Les armes ou les outils de production pouvant être monopolisés ou dissimulés confèrent souvent un pouvoir très centralisé. Même si une technologie est fondamentalement défensive, comme la mitrailleuse, elle s’est révélée être un outil offensif décisif qui a participé à la montée des grands États quand elle était entre les mains de quelques-uns.

   Quand, à la fin du XIXe siècle, les puissances européennes disposaient presque seules de la mitrailleuse, elles ont pu se servir de cette supériorité pour agrandir considérablement leurs empires coloniaux. Mais au XXe siècle, après la Seconde Guerre mondiale, lorsque la mitrailleuse se répandit, on s’en servit pour démanteler ces empires. Toute autre condition égale, plus la technologie se dissémine, plus le pouvoir lui-même se disperse, et plus l’échelle optimale des gouvernements se réduit.

## VITESSE DES MUTATIONS MÉGAPOLITIQUES

Si, de nos jours, la technologie est de loin la composante la plus importante, et semble le devenir davantage encore, retiendrons-nous le même constat pour l’avenir ? Un facteur clé de réponse réside dans la prise de conscience que ces variables évoluent à des rythmes radicalement différents.

La **topographie** est quasi immuable à l’échelle de l’Histoire. Hormis des phénomènes locaux de sédimentation, d’érosion ou autres, le relief de la planète est grosso modo identique à l’époque d’Adam et Ève. Et il restera tel quel jusqu’à ce qu’une ère glaciaire en re-sculpte les territoires ou qu’un autre cataclysme géologique s’en mêle. À plus long terme, sur des dizaines de millions d’années, la surface de la Terre se transforme sans doute sous l’effet des chutes de météorites de grande envergure. Le cas échéant, on peut être certain que saisons de baseball ou de cricket n’y survivraient pas.

Le **climat** varie plus activement que la topographie. Au cours du dernier million d’années, la plupart des changements géomorphologiques sont liés aux oscillations climatiques. Les glaciations, pendant les ères glaciaires, ont creusé de nouvelles vallées, détourné des fleuves, fait émerger ou disparaître des isthmes par abaissement du niveau des mers.

Ces variations climatiques ont joué un rôle important dans l’Histoire : d’abord, elles ont déclenché la Révolution agricole à la fin de la dernière ère glaciaire, puis elles ont, à maintes reprises, déraciné des régimes politiques durant les périodes de refroidissement et de sécheresse.

On s’inquiète, depuis peu, d’un éventuel « réchauffement climatique ». Ce n’est pas à écarter complètement. Toutefois, dans une perspective longue, une tendance froide est probablement plus redoutable qu’une tendance chaude. Les analyses isotopiques dans les carottes océaniques montrent que la période actuelle est la deuxième plus chaude depuis plus de deux millions d’années.[^50] Un rafraîchissement, analogue à celui du XVIIe siècle, pourrait engendrer un bouleversement mégapolitique. Les craintes actuelles de réchauffement ont, à ce stade, au moins l’avantage de laisser présumer que les températures continueront d’osciller à l’intérieur d’une fourchette relativement clémente, semblable à celle des trois derniers siècles.

La vitesse des mutations liées aux **microbes** est plus difficile à cerner. Les micro-organismes, surtout les virus, évoluent très rapidement. Songez au rhume, qui se modifie sans cesse. Néanmoins, malgré le rythme élevé de ces permutations, leur impact sur les zones de contrôle du pouvoir est resté bien moins brutal que celui des révolutions technologiques. Pourquoi ? Une partie de la réponse réside dans la régulation « naturelle » : il est avantageux pour un microbe d’infecter un hôte sans systématiquement l’éliminer. Les maladies trop létales s’auto-annihilent rapidement en tuant tous leurs hôtes et en s’éteignant par la même occasion.

Bien sûr, cela n’empêche pas l’émergence d’infections terriblement destructrices, qui bouleversent un ordre sociétal. La Peste noire, par exemple, a anéanti une large part de la population eurasienne, brisant l’économie internationale du XIVe siècle.

### Ce qui aurait pu se passer

On peut regarder l’Histoire à la lumière de ce qui aurait pu advenir. On ne voit aucune raison pour que les microparasites n’aient pas continué à jouer des tours à la société humaine durant l’ère moderne. Par exemple, il aurait très bien pu exister dans les eaux africaines, au moment où les premiers navigateurs portugais s’y sont aventurés, un rétrovirus ultra virulent, plus contagieux que le VIH, qui aurait instantanément stoppé cette route commerciale avant même son ouverture. De la même façon, Christophe Colomb et la cohorte de colons qui l’ont suivi auraient pu croiser de nouveaux pathogènes en Amérique, provoquant une hécatombe des Européens semblable à celle qui a frappé les autochtones, vulnérables aux maladies infantiles occidentales. Mais rien de tout cela ne s’est produit, un enchaînement qui peut nourrir ce sentiment vague selon lequel l’Histoire semblait « destinée ».

Au cours de l’ère moderne, les microbes ont moins entravé la montée des États qu’ils ne l’ont favorisée. Les armées occidentales, en plus de leur supériorité technologique, possédaient un atout biologique aux colonies : une relative immunité aux pathologies infantiles, dévastatrices pour des autochtones moins densément peuplés. Les Occidentaux se trouvaient ainsi dotés d’une arme invisible qui manquait à leurs adversaires.

Il n’y a pas eu d’échange symétrique de maladies entre périphérie et centre. Certains avancent que la syphilis serait la seule infection importée depuis le Nouveau Monde. La chose n’est pas tranchée. Mais, si c’est vrai, cela n’a pas entravé la projection de la puissance. L’impact de la syphilis a surtout été de faire évoluer les mœurs sexuelles en Occident. Globalement, depuis la fin du XVe siècle jusqu’au dernier quart du XXe siècle, les facteurs microbiologiques ont exercé une influence assez bénigne sur l’évolution des sociétés industrielles. Malgré les drames et souffrances occasionnés par la tuberculose, la poliomyélite ou différentes grippes, aucune maladie nouvelle ne s’est hissée, durant la période moderne, au niveau mégapolitique de la peste antonine ou de la Peste noire. L’amélioration de l’hygiène publique, les campagnes de vaccination et l’invention de traitements ont graduellement réduit l’impact des microbes, accentuant d’autant plus l’influence de la technologie sur les limites où se déploie la puissance.

L’apparition récente du SIDA et la médiatisation de virus exotiques laissent imaginer que ce ne sera pas toujours aussi paisible. Mais nous ignorons si une prochaine pandémie bouleversera ou non notre monde autant que des variations climatiques ou topographiques. Parmi ces grandes inconnues, l’explosion brute d’un agent pathogène serait sans doute ce qui pourrait le plus relativiser la primauté technologique.

Ne pouvant surveiller ou anticiper tous les scénarios extrêmes, nous misons qu’au cours du prochain millénaire, la technologie occupera la première place dans la hiérarchie mégapolitique, à moins d’un coup de malchance pour l’humanité. Ce qui n’a pas toujours été le cas, comme le rappelle la première grande mutation mégapolitique : la Révolution agricole.

[^29]: Huizinga, op. cit., p. 7.  

[^30]: *The Compact Edition of the Oxford English Dictionary*, vol. 1 (Oxford : Oxford University Press, 1971), p. 1828.  

[^31]: Michael Hicks, *Bastard Feudalism* (Londres : Longmans, 1995), p. 1.  

[^32]: Ibid., p. 102.  

[^33]: Voir S. A. Cook et al., éd., *The Cambridge Ancient History*, vol. 12 (Cambridge : Cambridge University Press, 1971), p. 208-22.  

[^34]: Ibid., p. 209-20.  

[^35]: Will Durant, *The Story of Civilization*, vol. 4, *The Age of Faith* (New York : Simon & Schuster, 1950), p. 43.  

[^36]: C. W. Previte-Orton, *The Shorter Cambridge Medieval History*, vol. 1 (Cambridge : Cambridge University Press, 1971), p. 102.  

[^37]: Ibid., p. 131.  

[^38]: Ibid., p. 137.  

[^39]: Ibid.  

[^40]: Durant, op. cit., p. 43.  

[^41]: Ramsay MacMullen, *Corruption and the Decline of Rome* (New Haven : Yale University Press, 1988), p. 192.  

[^42]: Cité in ibid., p. 193.  

[^43]: Cité dans David Kline et Daniel Burstein, « Is Government Obsolete ? » *Wired*, janvier 1996, p. 105.  

[^44]: Lane, « Economic Consequences of Organized Violence », op. cit.  

[^45]: Ibid.  

[^46]: Susan Alling Gregg, *Foragers and Farmers : Population Interaction and Agricultural Expansion in Prehistoric Europe* (Chicago : University of Chicago Press, 1988), p. 9.  

[^47]: Stephen Boyden, *Western Civilization in Biological Perspective* (Oxford : Clarendon Press, 1987), p. 89. Voir aussi Marvin Harris, *Cannibals and Kings* (New York : Vintage, 1978), p. 29-32.  

[^48]: Geoffrey Parker et Lesley M. Smith, éd., *The General Crisis of the Seventeenth Century* (Londres : Routledge & Kegan Paul, 1985), p. 8.  

[^49]: Voir Charles Woolsey Cole, *French Mercantilism : 1683-1700* (New York : Octagon Books, 1971), p. 6.  

[^50]: Chris Scarre, éd., *Past Worlds: The Times Atlas of Archaeology* 314 (New York : Random House, 1995), p. 58.

::: {.content-visible when-format=latex}
\setsubtitle{Sous-titre}
:::
