# LA Mégapolitique À L’Ère De L’Information

:::{.content-hidden when-format=latex}
*Le triomphe de l’efficacité sur le pouvoir*
:::

> « …c’est l’information informatisée, et non la main-d’œuvre ou la production de masse, qui alimente de plus en plus l’économie américaine et qui remportera les guerres dans un monde relié par 500 chaînes de télévision. L’information informatisée existe dans le cyberespace – la nouvelle dimension créée par la prolifération sans fin de réseaux informatiques, de satellites, de modems, de bases de données et de l’Internet public »[^187] – NEIL MUNRO

Le 30 décembre 1936, des ouvriers de l’automobile en quête de salaires plus élevés s’emparèrent par la force de deux usines principales de General Motors à Flint, dans le Michigan. Ils arrêtèrent les machines, coupèrent les chaînes de montage et s’installèrent sur place. Les travailleurs, qui avaient été employés pour faire fonctionner ces usines, s’assirent et enclenchèrent un conflit industriel qui allait durer de nombreuses semaines. Ce fut un affrontement rythmé par des émeutes violentes et par des retournements d’alliances impliquant la police, la milice du Michigan et des figures politiques à tous les niveaux de l’État. Constatant peu de progrès pour faire aboutir leurs revendications, les syndicalistes firent de nouveau grève le 1er février 1937.

Les militants syndicaux s’emparèrent par la force de l’usine Chevrolet de GM à Flint. En occupant et en fermant les principales usines de General Motors, les ouvriers paralysèrent efficacement la capacité de production de l’entreprise. Dans les dix jours qui suivirent la prise de cette troisième usine, GM ne produisit que 153 automobiles aux États-Unis.

Nous rappelons ce bulletin d’information vieux de soixante ans pour éclairer sous un angle plus net la révolution des conditions mégapolitiques qui se déroule aujourd’hui. La grève sur le tas de General Motors s’est produite au cours de la vie de certains lecteurs de ce livre. Pourtant, nous estimons que les grèves sur le tas deviendront aussi anachroniques à l’ère de l’information que des esclaves traversant le désert, tirant d’immenses pierres pour ériger des pyramides funéraires pour les pharaons. À l’époque industrielle, syndicats et tactiques d’intimidation étaient devenus si familiers qu’on les considérait presque comme un pan incontesté du paysage social. Or, cela reposait sur des conditions mégapolitiques spécifiques qui s’effacent rapidement. Sur l’Autoroute de l’Information, il n’y aura ni Chevrolet, ni UAW pour faire grève.

La chance des gouvernements suivra celle de leurs homologues syndicaux : ils déclineront. L’usage institutionnalisé de la coercition, si crucial au XXe siècle, ne sera plus possible. La technologie est en train de provoquer un changement radical dans la logique de l’extorsion et de la protection.

> « … il n’y a ni Propriété, ni Domaine, ni “À moi” ni “À toi” distinct ; simplement ce que chacun peut se procurer et pour aussi longtemps qu’il peut le garder. »[^188] – THOMAS HOBBES

### Extorsion et protection

Tout au long de l’histoire, la violence a été comme une dague pointée sur le cœur de l’économie. Comme l’a finement analysé Thomas Schelling, « le pouvoir de nuire — de détruire ce à quoi autrui tient, d’infliger douleur et tristesse — constitue une forme de pouvoir de négociation, peu aisée à employer mais souvent employée. Dans le monde souterrain, c’est la base du chantage, de l’extorsion et du kidnapping ; dans le domaine commercial, c’est la base des boycotts, des grèves et des lockouts. (…) Il sert souvent de fondement à la discipline, qu’elle soit civile ou militaire ; et les dieux l’emploient pour exiger des comptes. »[^189] La capacité d’un gouvernement à se taxer lui-même dépend des mêmes vulnérabilités que les rackets et extorsions privés. Bien que nous n’en ayons pas toujours conscience, la proportion de richesses contrôlées et dépensées de manière coercitive (par la criminalité et les gouvernements) présente un indicateur brut de l’équilibre mégapolitique entre extorsion et protection. Si la technologie rend la protection des biens difficile, la criminalité tend à être répandue, et l’activité syndicale aussi. Dans un tel contexte, la protection offerte par l’État aurait alors plus de valeur et la fiscalité serait élevée. Là où les impôts sont plus faibles et où les salaires se déterminent sur le marché plutôt que par l’intervention politique ou la coercition, la technologie a fait pencher la balance vers la protection.

Le déséquilibre technologique entre extorsion et protection atteignit un pic extrême vers la fin du troisième quart du XXe siècle. Dans certains pays occidentaux avancés, plus de la moitié des ressources étaient réquisitionnées par les gouvernements. Une large partie de la population voyait ses revenus fixés par décret ou déterminés sous l’influence de la coercition, comme via des grèves ou d’autres formes de menaces violentes. L’État-providence et le syndicat sont tous deux des produits de la technologie, partageant le fruit de la victoire du pouvoir sur l’efficacité au XXe siècle. Ils n’auraient pas pu exister sans les technologies, militaires et civiles, qui, à l’ère industrielle, ont accru le rendement de la violence.

La capacité de créer des richesses a toujours entraîné une certaine vulnérabilité à l’extorsion. Plus vous créez ou possédez de biens, plus vous risquez de devoir payer un lourd tribut. Soit vous versiez des pots-de-vin à tous ceux qui pouvaient menacer de violence, soit vous subventionniez des forces militaires capables de repousser toute tentative de racket par la force brute.

> « La violence ne sera plus entendue dans ton pays, ni ravages ni destructions dans tes frontières… » – ISAÏE 60:1

### Les mathématiques de la protection

Désormais, la lame de la violence pourrait bientôt s’émousser. La technologie de l’information promet de modifier radicalement l’équilibre entre protection et extorsion ; elle facilite dans bien des cas la protection des biens tout en rendant l’extorsion plus ardue. Les techniques de l’ère de l’information permettent de créer des biens qui échappent à de nombreuses formes de coercition. Cette nouvelle asymétrie entre protection et extorsion s’appuie sur une vérité fondamentale des mathématiques : il est plus simple de multiplier que de diviser. Même si cette vérité est élémentaire, ses conséquences considérables étaient restées voilées tant que nous ne disposions pas de microprocesseurs. Les ordinateurs à grande vitesse ont accepté plusieurs milliards de fois plus de calculs au cours de la dernière décennie que pendant toute l’histoire de l’humanité. Cet essor du calcul nous a permis, pour la première fois, de sonder certaines caractéristiques universelles de la complexité. Les ordinateurs nous révèlent que les systèmes complexes ne peuvent être construits et compris que de façon progressive et ascendante. Multiplier des nombres premiers est simple. Mais décomposer la complexité en s’attaquant au produit de grands nombres premiers est quasiment impossible. Kevin Kelly, rédacteur en chef de Wired, l’explique ainsi : « Multiplier plusieurs nombres premiers pour obtenir un produit plus important est à la portée du premier écolier venu ; mais les superordinateurs du monde s’étranglent quand il s’agit d’identifier les nombres premiers à partir de ce produit. »[^190]

### La logique des systèmes complexes

L’économie cybernétique sera inévitablement façonnée par cette vérité mathématique profonde. Elle a d’ores et déjà une manifestation concrète dans les algorithmes de chiffrement puissants. Comme nous l’examinerons plus loin, ces algorithmes permettront la création d’un nouveau domaine commercial protégé, le cybercommerce, dans lequel l’influence de la violence va considérablement décliner. La balance entre extorsion et protection basculera de façon marquée du côté de la protection. L’émergence d’une nouvelle économie, basée sur des mécanismes adaptatifs spontanés et moins dépendante d’une prise de décisions et d’une allocation centralisées, en sera facilitée. Ce nouveau système, où la protection sera primordiale, diffèrera profondément du précédent, né de la prépondérance de la contrainte à l’époque industrielle.

### Les systèmes de commande et contrôle sont primitifs

Nous avions écrit dans *The Great Reckoning* que l’ordinateur nous permet de « voir » la complexité jusqu’alors invisible dans un large éventail de systèmes[^243]. Non seulement ses capacités de calcul avancées nous aident à mieux comprendre les systèmes complexes, mais elles nous permettent aussi de mettre à profit ces complexités de façon productive. En un sens, il ne s’agit même pas d’un choix, mais d’une nécessité si l’économie veut dépasser le stade primitif du contrôle centralisé. Un pareil système, fondé sur des relations linéaires, est fondamentalement rudimentaire. Quand l’État s’approprie des ressources, il les déplace inévitablement d’usages complexes et à forte valeur ajoutée vers des utilisations primaires peu productives. Ce procédé se heurte à la même asymétrie mathématique qui empêche la décomposition du produit de grands nombres premiers. Diviser le butin ne peut jamais être qu’un acte approximatif et grossier.

### Tout gagne en complexité

Partout où nous posons le regard dans l’univers, nous constatons que les systèmes deviennent plus complexes à mesure qu’ils se développent. C’est le cas en astrophysique. Et c’est vrai même dans une flaque d’eau. Laissez de l’eau de pluie au fond d’un creux et elle se complexifiera. Les systèmes avancés de toutes sortes sont des systèmes adaptatifs complexes dépourvus d’autorité centrale. Tout système complexe de la nature, dont l’économie de marché est la manifestation sociale la plus évidente, repose sur des capacités décentralisées. Les systèmes qui fonctionnent de manière optimale sous un large éventail de conditions doivent leur résistance à l’ordre spontané, lequel s’adapte aux possibilités novatrices. La vie elle-même est un de ces systèmes complexes. Des milliards de combinaisons génétiques potentielles aboutissent à un seul individu humain. Aucun organisme central ne saurait trier tout cela.

Il y a vingt-cinq ans, cela ne pouvait être qu’une intuition. Aujourd’hui, c’est avéré. Plus l’informatique nous rapproche des mathématiques de la vie artificielle, mieux nous comprenons les mathématiques de la vie réelle, à savoir celles de la complexité biologique. Ces secrets de la complexité, exploités via la technologie de l’information, permettent de remanier l’économie pour la rendre plus complexe. L’Internet et le World Wide Web adoptent déjà des traits de système organique, comme le suggère Kevin Kelly dans *Out of Control: The New Biology of Machines, Social Systems, and the Economic World*[^191]. Selon lui, la nature est « une fabrique d’idées. Des paradigmes vitaux, post-industriels, sont dissimulés dans chaque fourmilière de la jungle… L’adaptation de la biologie dans la sphère mécanique devrait nous émerveiller. Quand l’alliance du né et du fabriqué sera totale, nos créations sauront apprendre, s’adapter, s’auto-réparer et évoluer. Il s’agit là d’un pouvoir que nous n’avons pas encore même rêvé. »[^192]

De fait, les conséquences de cette « transposition massive du biologique dans les machines » seront certainement considérables. Il existe depuis toujours une forte tendance à ce que les systèmes sociaux imitent les caractéristiques de la technologie dominante d’une époque. C’est un aspect sur lequel Marx ne s’est pas trompé. Les larges usines ont coïncidé avec l’âge des super-États-nations. À l’inverse, la micro-informatique miniaturise les institutions. Si notre analyse est correcte, la technologie de l’ère de l’information favorise l’émergence d’une économie mieux adaptée à exploiter les bénéfices de la complexité.

Pourtant, les conséquences mégapolitiques d’un tel changement sont à ce point mal comprises que même ceux qui entrevoient son importance mathématique le font souvent de manière anachronique. Il est difficile d’assimiler pleinement l’idée que les changements technologiques des prochaines années vont rendre obsolètes la plupart des conceptions et institutions politiques contemporaines. Par exemple, le regretté physicien Heinz Pagels écrivait dans son livre très perspicace, *The Dreams of Reason* : « Je suis convaincu que les nations et les peuples qui maîtriseront la nouvelle science de la Complexité deviendront les superpuissances économiques, culturelles et politiques du prochain siècle. »[^193] Cette prévision est impressionnante. Mais selon nous, elle sera inévitablement contredite, non parce qu’elle est conceptuellement erronée, mais au contraire parce qu’elle se révèlera encore plus juste que Pagels ne le laissait entendre. Les sociétés qui se reconfigureront pour devenir de véritables systèmes adaptatifs complexes prospéreront. Mais en le faisant, elles auront peu de chances d’être des nations et encore moins des « superpuissances politiques ». Les premiers à profiter de l’accroissement de la complexité des systèmes sociaux seront vraisemblablement les « individus souverains » du nouveau millénaire.

Dans la forme où elle est exprimée, la prédiction de Pagels équivaut à la remarque d’un chaman, il y a cinq cents générations, affirmant à son groupe de chasseurs rassemblés autour du feu : « Je suis certain que la première tribu de chasseurs qui maîtrisera l’irrigation aura plus de temps libre pour raconter des histoires que ceux qui pêchent là-bas sur le grand lac. » Aussi pertinent soit-il quant à l’importance de la complexité, Pagels passait à côté d’un fait fondamental : quand la logique de la violence change, la société se transforme.

## La logique de la violence

Pour comprendre comment et pourquoi, il est nécessaire d’étudier plusieurs facettes de la mégapolitique qui ne sont que rarement mises en avant. Il s’agit de points examinés par l’historien Frederic C. Lane, dont les travaux sur la violence et le sens économique de la guerre sont abordés ailleurs dans ce volume. À l’époque où écrivait Lane, dans la première moitié du XXe siècle, l’émergence d’une Société de l’Information ne se profilait pas. Il supposait peut-être que la compétition pour mobiliser la violence avait trouvé son aboutissement final dans la forme de l’État-nation. Il ne laisse aucunement entendre qu’il anticipait la micro-informatique ou qu’il imaginait possible de créer des richesses dans un univers sans existence physique. Lane n’avait rien à dire non plus sur la perspective que d’importants pans du commerce deviennent pratiquement immunisés contre toute pression violente.

Bien que Lane n’ait pas prévu les révolutions technologiques actuelles, ses réflexions sur les stades successifs de la monopolisation de la violence dans le passé sont si limpides qu’elles s’appliquent évidemment à l’ère de l’information. Ses travaux sur le Moyen Âge violent attirèrent son attention sur des éléments que les historiens et économistes traditionnels avaient tendance à négliger. Lane comprit que la manière dont la violence est organisée et contrôlée influence fortement l’emploi des ressources rares[^194]. Il reconnut aussi que si la production de la violence n’est pas considérée comme un volet habituel de la production économique, la maîtrise de la violence est cruciale pour l’économie. La fonction première du gouvernement est de protéger les individus contre la violence. Pour reprendre ses mots :

« Toute entreprise économique a besoin de protection et la paie : protection contre la destruction ou la confiscation armée de son capital, et contre l’entrave violente de sa main-d’œuvre. Dans les sociétés fortement structurées, la production de cette “utilité” qu’est la protection incombe à une association ou organisation spécial(isées) appelée gouvernement. En fait, l’un des attributs les plus caractéristiques d’un gouvernement est son emploi de la force pour créer la loi et l’ordre, ainsi que son contrôle, de diverses manières, de l’usage de la violence par autrui. »[^195]

Il s’agit là d’un point si fondamental qu’il n’apparaît guère dans les manuels scolaires ni dans la discussion civique qui, en théorie, oriente la politique. Mais il est tout aussi fondamental pour qui souhaite comprendre l’actuelle révolution de l’information. La protection des biens et des personnes est un besoin de première importance, qui a tourmenté toutes les sociétés de l’histoire. Comment résister à l’agression violente est le problème central de l’histoire. On ne peut pas y remédier facilement, même si plusieurs voies existent pour obtenir protection.

### La fin d’une époque

Au moment où nous écrivons, les conséquences mégapolitiques de l’ère de l’information commencent à peine à se faire sentir. L’économie a muté depuis quelques décennies : la production d’informations et le calcul l’emportent sur la fabrication de produits manufacturés, la micro-informatique supplante l’énergie mécanique, le poste de travail succède à l’usine, et la production de masse laisse place à de petites équipes, voire à des individus travaillant seuls. Alors que l’échelle de l’entreprise se réduit, la menace de sabotage et de chantage sur le lieu de travail s’amenuise. Les entreprises de plus petite taille sont beaucoup plus difficiles à organiser pour les syndicats.

La micro-informatique permet aux entreprises d’être plus petites et plus mobiles. Nombre d’entre elles proposent des services ou des produits requérant très peu de ressources naturelles. Sur le principe, elles pourraient s’implanter presque n’importe où sur la planète. Elles ne sont pas “clouées” à un endroit précis comme une mine ou un port. À terme, elles seront donc bien moins exposées à l’impôt, qu’il soit revendiqué par un État ou par d’autres formes de pression. Un ancien adage populaire chinois énonce : « Parmi les trente-six façons de fuir les ennuis, la meilleure consiste à partir. »[^196]

À l’ère de l’information, cet adage oriental trouvera d’autant plus facilement à s’appliquer. Si les choses deviennent inconfortables à cause d’exigences excessives, qu’elles émanent de l’administration ou des syndicats, il sera bien plus simple de se délocaliser. En prime, comme nous le verrons plus bas, il sera même possible, avec l’ère de l’information, de fonder des entreprises virtuelles dont l’immatriculation sera totalement fonction d’un rapport coût-bénéfice sur le marché. Une augmentation surprise des exigences d’extorsion, publiques ou non, pourrait faire migrer les activités et le patrimoine de l’entreprise virtuelle loin de la juridiction concernée à la vitesse de la lumière.

La généralisation de la microtechnologie dans l’industrie, y compris dans les grands groupes, leur donne aussi plus de flexibilité face à la menace de la violence. Le cas de la longue grève du syndicat des travailleurs de l’automobile (UAW) contre Caterpillar, qui s’est terminée fin 1995 après presque deux ans, en illustre le propos. Contrairement aux chaînes de montage des années 1930, celles de Caterpillar emploient aujourd’hui bien plus d’ouvriers qualifiés. Mises sous pression par la concurrence étrangère, l’entreprise a sous-traité des tâches peu qualifiées, fermé des usines peu rentables et investi près de deux milliards de dollars dans la robotique et la commande numérique. Même la grève a encouragé l’automatisation. Selon la compagnie, deux mille salariés de moins suffisent à présent pour tenir la production après ce mouvement social[^197].

La mégapolitique du processus de production a changé bien plus radicalement qu’on ne se l’imagine. Ce changement n’a pas encore surgi en pleine lumière, d’abord parce qu’il y a toujours un décalage entre un bouleversement des conditions mégapolitiques et ses répercussions institutionnelles, et aussi parce que le secteur de la micro-informatique évolue si vite qu’il est possible d’anticiper la naissance de produits ayant d’importantes conséquences mégapolitiques avant même leur commercialisation. Ils contribueront à un monde bien différent.

## L’exploitation des capitalistes par les ouvriers

Le caractère même de la technologie tout au long du XXe siècle rendait la prise d’une usine par la force — la « grève sur le tas » — difficile à contrer pour ses propriétaires ou ses dirigeants. Comme le souligne l’historien Robert S. McElvaine, une grève sur le tas « empêchait les employeurs de la casser sans renoncer au même coup à leurs propres équipements »[^198]. De fait, les salariés prenaient littéralement les biens de l’employeur en otage. Comme nous le verrons, les grandes entreprises industrielles se révélaient plus vulnérables que les plus petites. En 1937, General Motors était peut-être la première entreprise au monde dans l’industrie. Ses usines, parmi les plus vastes complexes mécaniques jamais construits, comptaient des milliers d’ouvriers. Chaque heure d’arrêt représentait un lourd manque à gagner. Une grève durait des semaines, comme ce fut le cas en 1936-1937, et les pertes, déjà élevées, grimpaient en flèche.

### Un défi à l’offre et à la demande

Incapable de construire la moindre voiture après la prise de sa troisième usine, GM capitula vite face aux revendications syndicales. Ce choix n’avait aucun lien avec l’équilibre entre l’offre et la demande de travail, loin de là. Au moment où General Motors céda aux exigences du syndicat, il y avait neuf millions de chômeurs aux États-Unis, 14 % de la population active. La plupart de ces chômeurs auraient volontiers accepté un poste chez GM, d’autant qu’ils en avaient les compétences ou pouvaient les acquérir. De nombreux témoignages de l’époque colportaient certes l’idée que les emplois en usine demandaient un véritable savoir-faire, mais la réalité est tout autre. Presque n’importe qui sachant se présenter à l’heure pouvait tenir ce type de poste, dont l’accès ne nécessitait ni formation avancée, ni même la lecture ou l’écriture. Encore dans les années 1980, un pourcentage assez élevé des salariés de General Motors était illettré ou manquait de bases en calcul. Jusqu’aux années 1990, un débutant typique sur une chaîne d’assemblage GM ne recevait qu’une seule journée “d’intégration” avant d’être placé au poste. Lorsqu’un métier s’apprend en une matinée, il n’est pas très spécialisé.

Pourtant, en 1937, avec un vivier de main-d’œuvre non qualifiée et qualifiée largement disponible, les ouvriers engraissèrent leurs salaires par la contrainte. Leur réussite tenait bien plus aux lois de la violence qu’à celles du marché de l’emploi. En mars 1937, mois ayant suivi le compromis obtenu chez GM, on compta 17 grèves sur le tas supplémentaires aux États-Unis, pour la plupart victorieuses. Des faits similaires se produisirent dans tous les pays industrialisés. Les ouvriers se contentaient de confisquer les usines pour se les faire payer. C’était une tactique on ne peut plus simple et, dans l’ensemble, lucrative et plutôt sympathique auprès de ceux qui l’exerçaient. Un ouvrier raconta : « Je m’amuse beaucoup, c’est nouveau, différent, y’a à manger en abondance et de la musique. »[^199]

La grève sur le tas de GM entre 1936 et 1937, comme d’autres occupations forcées d’usines, illustre ce que nous décrivions déjà dans *Blood in the Streets* comme « l’exploitation des capitalistes par les ouvriers ». Cette idée contraste fortement avec la représentation popularisée par Pete Seeger dans certains folksongs. Mais quiconque souhaite faire carrière ailleurs que chanteur militant doit aller au-delà de l’interprétation habituelle pour saisir la logique sous-jacente. À toutes les époques, l’extorsion pratiquée de manière systématique est recouverte d’une couche de rationalisation et de faux-semblants qui masquent ses racines mégapolitiques. Pour en cerner la réalité, il faut savoir écarter ces justifications.

## Déchiffrer la logique de l’extorsion

Pour mesurer les enjeux mégapolitiques du basculement vers l’ère de l’information, il faut ôter le voile du discours idéologique et disséquer la véritable logique de la violence en société. C’est un exercice semblable à l’épluchage d’un oignon trop mûr. Cela peut faire pleurer, mais il ne faut pas détourner le regard. Nous examinerons d’abord la logique de l’extorsion au travail, puis nous l’étendrons à des problématiques plus générales concernant la création et la protection de la richesse, ainsi que la nature du pouvoir moderne. Dans une mesure plus forte qu’imaginé, la prospérité des États, à l’instar de celle des syndicats, dépendait de la marge de manœuvre en termes d’extorsion. Cette marge était moindre au XIXe siècle qu’au XXe. Dans le prochain millénaire, elle sera presque inexistante.

La logique d’ensemble de l’État et l’essence du pouvoir ont été transformées par la micro-informatique. Ceci peut paraître emphatique à première vue. Pourtant, si l’on regarde bien, l’essor des gouvernements est allé de pair avec celui des syndicats au XXe siècle. Avant cela, la plupart des nations recouraient à un pourcentage plus faible de la production qu’aujourd’hui. Tout comme les syndicats, ils jouaient un rôle réduit ou quasi nul dans la vie économique. La possibilité pour les ouvriers de contraindre leurs employeurs à payer des salaires supérieurs au marché reposait sur les mêmes conditions mégapolitiques qui permettaient aux gouvernements de ponctionner plus de 40 % de la production nationale en impôts.

### L’extorsion en milieu professionnel avant le XXe siècle

La montée puis la chute des extorsions syndicales s’expliquent aisément par les mutations des conditions mégapolitiques du processus de production. En 1776, quand Adam Smith publia *La Richesse des Nations*, l’environnement était si défavorable aux revendications ouvrières que les « combinaisons », c’est-à-dire les rassemblements de travailleurs pour faire monter les salaires, étaient rarement viables. La plupart des entreprises manufacturières étaient de petite taille et gérées par des familles. Les grands ensembles industriels commençaient à peine à voir le jour. Les occasions de violence existaient, mais elles étaient moins porteuses. De fait, pendant cette période et une bonne partie du XIXe siècle, les syndicats étaient considérés comme illégaux au Royaume-Uni, aux États-Unis et dans d’autres pays de common law. Adam Smith décrivit les tentatives de grève de la façon suivante : « Leur prétexte coutumier est parfois la cherté des vivres ; parfois les grands profits que le patron fait grâce à leur travail… Ils en reviennent toujours à des clameurs tapageuses, voire à des violences et des actes choquants. »[^200] Pourtant, ajoutait-il, ces regroupements « finissent très rarement à l’avantage des ouvriers », hormis « le châtiment ou la ruine des meneurs »[^201].

Le XIXe siècle vit grandir les économies d’échelle et la taille des entreprises. Cependant, la plupart des individus gardaient un statut d’indépendant ou travaillaient pour de petites structures. Ainsi, les actions syndicales, comme celles décrites par Smith, « aboutissaient en général à un échec »[^202]. L’évolution légale et politique des syndicats ne se produisit qu’avec l’accroissement de l’échelle des entreprises. Les premiers syndicats à s’implanter durablement furent ceux d’ouvriers qualifiés, dont l’organisation impliquait peu de violence. Les syndicats de travailleurs non qualifiés, eux, fondaient leurs actions sur le potentiel coercitif né de la forte échelle ou du risque de sabotage dans tel ou tel secteur. Ce schéma se reproduisit de Newcastle jusqu’en Argentine[^203].

Un exemple précoce est l’attaque du canal Chesapeake & Ohio (C&O) en 1834. Contrairement aux petites entreprises de l’époque, le canal C&O s’étendait sur plus de 300 miles et nécessitait la manutention de déblais colossaux[^204]. Nombre d’ouvriers comprirent vite qu’un tel ouvrage pouvait facilement être mis hors service. Il suffisait d’inonder un segment, de bloquer l’écluse avec un bateau, ou de commettre quelques dégâts. Les grévistes pouvaient éventuellement couler des péniches ou entasser des débris pour fermer le passage. Début 1834, des rivalités entre gangs irlandais aboutirent à une tentative de prise de contrôle du canal. Elle échoua et se solda par cinq morts ; le président Andrew Jackson envoya des troupes fédérales depuis Ft. McHenry pour disperser les ouvriers.

Les mines et les chemins de fer étaient eux aussi des proies tentantes. Comme le canal, ils étaient vulnérables aux sabotages et autres blocages. Dans une mine, il suffisait de l’inonder, d’obstruer l’entrée ou même simplement de tuer les mules qui acheminaient les wagonnets. Les voies ferrées, s’étendant sur des centaines de kilomètres, ne pouvaient être totalement gardées. Il devenait aisé pour des briseurs de grève d’occasionner de lourds dommages. De tels faits se produisirent souvent dans le cadre de conflits sociaux. Ils furent fréquents durant la dépression post-Panique de 1873.

En décembre 1874, la guerre éclata dans les bassins houillers de l’est de la Pennsylvanie. Les militants syndicaux y formèrent une société secrète, l’Ancient Order of Hibernians, surnommée les « Molly Maguires », s’illustrant par des actes d’intimidation, de sabotages et de meurtres[^205]. Les employés des compagnies de chemin de fer se mobilisèrent eux aussi. En juillet 1877, des insurrections visèrent les Pennsylvania et Baltimore & Ohio Railroads. Les ouvriers prirent possession des aiguillages, arrachèrent les rails, sabotèrent et pillèrent du matériel roulant, etc. À Pittsburgh, des rotondes furent incendiées avec des centaines de personnes à l’intérieur. On dénombra des dizaines de morts, 2 000 wagons se firent piller et détruire ; l’atelier de maintenance fut anéanti, de même qu’un silo à grain et 125 locomotives. L’armée fédérale finit par rétablir l’ordre[^206].



Bien que ces tentatives anciennes de grèves insurrectionnelles suscitent la sympathie de certains milieux socialistes, elles ne rencontrèrent guère d’appui populaire. En dépit de la forte vulnérabilité de secteurs comme les mines ou le ferroviaire, les conditions mégapolitiques globales restaient défavorables à l’extorsion systématique. Quelques industries étaient fragiles, mais l’essentiel de la population était dispersée dans de petites entreprises ou sur des lopins que le sabotage ne touchait pas. Sans soutien massif, ces tentatives ouvrières s’en remettaient aux autorités pour réprimer ces conflits. Même en recourant à la violence, les syndicats étaient le plus souvent vaincus dans les plus brefs délais par les forces armées.

### Un chantage aisé

La leçon pour l’ère de l’information est la suivante : tant que la taille des entreprises est restée modeste, les grèves visant à imposer des salaires au-dessus de l’équilibre du marché furent rarement concluantes, même dans les entreprises instables au sabotage (canaux, chemins de fer, mines, etc.). Ce n’est pas que les syndicats rechignaient à verser dans la violence. Au contraire. Ils y recouraient souvent de manière spectaculaire, parfois contre des personnalités publiques. Ainsi, dans un épisode célèbre du mouvement ouvrier américain évoquant la « vengeance des mineurs », le gouverneur Frank Steunenberg fut assassiné à la bombe par un tueur engagé par le syndicat, parce qu’il avait déjoué la tentative de blocus du district minier de Coeur d’Alene[^207]. Mais ni les meurtres ni les menaces de meurtre ne parvenaient à imposer durablement l’organisation syndicale, en l’absence de grandes entités industrielles et de production de masse, jusque dans la première moitié du XXe siècle.

Pour expliquer le sort plus favorable des syndicats au XXe siècle, on se penchera sur la nature même de la technologie industrielle. Quelque chose changea avec l’ascension spectaculaire des ateliers de fabrication au début du XXe siècle. Les grandes firmes, phares de l’économie, se trouvèrent spécialement vulnérables aux pressions ; les caractéristiques de la technologie industrielle incitaient presque les travailleurs à exercer la coercition pour « faire cracher » le patronat. Parmi ces caractéristiques :

1. *Les produits industriels intégraient une forte part de matières premières.* Cela rattachait la production à un nombre restreint de sites liés à l’extraction ou à l’acheminement. Un emplacement idéalement situé (proche de sources de pièces ou de ressources, à un bon carrefour de transport) apportait un gain substantiel de compétitivité. Or ce type de sédentarité géographique facilitait la tâche d’entités coercitives (États ou syndicats) qui pouvaient vouloir s’approprier une partie de ces avantages.
2. *L’essor des économies d’échelle poussa la taille des entreprises à des niveaux inédits.* Au début du XIXe siècle, les usines étaient plus modestes. Mais à l’ère de la production de masse, au début du XXe siècle, elles devinrent gigantesques. Cette croissance profitait à l’extorsion à plusieurs égards. Par exemple, de fortes économies d’échelle vont de pair avec de longs cycles de production, ce qui tend à stabiliser les marchés. Cette stabilité suscite les convoitises, puisqu’on peut espérer retirer sur le long terme des bénéfices de tout chantage exercé.
3. *Le nombre de concurrents dans les secteurs de pointe diminua fortement.* Le XXe siècle vit souvent une poignée seulement d’entreprises se partager des marchés valant des milliards. Cette concentration les exposait à la menace syndicale : quelques entreprises à cibler plutôt que des milliers. L’existence de grandes oligopoles favorisait l’extorsion, car les firmes pouvaient être rackettées pour payer des salaires supérieurs au marché sans sombrer aussitôt. Sans cela, aucune n’aurait subsisté en cas de trop forte charge.
4. *Les dépenses d’investissement se hissèrent au niveau de cette nouvelle échelle.* Cela renforçait la vulnérabilité du capital et aggravait les coûts d’une éventuelle fermeture. En outre, il devenait improbable qu’une unique personne ou une même famille puisse être propriétaire d’une grosse usine, sauf par héritage. Le financement colossal requis pour monter et gérer une gigantesque usine supposait le découpage du capital entre des milliers d’actionnaires sur les marchés. Du coup, ces apporteurs de capitaux, pour la plupart inconnus les uns des autres, comptaient sur des gestionnaires professionnels qui, souvent, ne détenaient qu’une part infime du capital. Ils n’avaient donc qu’un incitatif limité à prendre des risques personnels ou même vitaux pour défendre matériellement la propriété qu’ils administraient.
5. *Toute cette concentration faisait qu’une partie importante de la population active se retrouvait employée par un nombre réduit de firmes.* Nombreuses étaient les usines comptant plusieurs milliers, voire dizaines de milliers de salariés. Du point de vue militaire, cadres et propriétaires étaient largement surpassés en effectif par leurs subordonnés, qui restaient maîtres de la violence potentielle grâce à leur nombre. L’anonymat lié à la massification, et la méconnaissance mutuelle entre employés et employeurs, pouvaient rendre plus faciles les actions collectives musclées.
6. *Cette concentration affectait la société entière.* Cela renforçait encore l’ascendant des syndicats, par comparaison avec l’Amérique du XIXe siècle, où la majorité était indépendante ou répartie en petites firmes. En 1940, 6 % de la population active américaine occupait des emplois d’ouvriers en usine[^208]. Cela procurait un large soutien aux pressions pour arracher des hausses salariales. Une étude menée en 1938-1939 auprès de 1 700 personnes à Akron (Ohio) démontre que 68 % des syndiqués de la CIO Rubber Workers n’éprouvaient que très peu, voire aucune empathie envers la notion de propriété d’entreprise, alors qu’à l’inverse, 94 % des commerçants et artisans témoignaient d’un fort appui à la défense de la propriété privée[^209][^210].
7. *Les chaînes d’assemblage étaient séquentielles par essence.* L’ensemble de la production reposait sur l’approvisionnement et l’assemblage des pièces dans un ordre strict. Il suffisait donc de perturber le flux à un point, par exemple en retenant un composant crucial, pour bloquer toute la chaîne. Cette vulnérabilité rendait l’employeur plus fragile face aux grèves.
8. *La production sur chaîne uniformisait le travail.* Elle réduisait à la portion congrue la variabilité de la production entre différents ouvriers, même si leurs compétences différaient. L’un des buts de la conception d’une usine était de rendre possible la même voiture, que l’ouvrier de la chaîne soit plus ou moins compétent. Cette « machine stupide », axée sur une seule tâche, n’exigeait pas de qualification pointue pour sortir un produit standardisé, si bien qu’un client achetant une Cadillac n’avait nul besoin de s’enquérir des ouvriers qui l’avaient assemblée. Tout était supposé identique, indépendamment du niveau de formation.

L’uniformisation du travail en usine a alimenté un discours égalitariste suggérant que toute la valeur provenait de la machine elle-même et qu’il suffisait d’appuyer sur des boutons pour fabriquer un produit vendable. Les habiletés entrepreneuriales et intellectuelles semblaient négligeables. Les ouvriers peu qualifiés pouvaient se persuader qu’ils « créaient » la valeur perçue par le propriétaire et que celui-ci s’en accaparait injustement. Comme le disait un gréviste de GM : « On a appris qu’on pouvait prendre l’usine. On sait déjà les faire marcher. Si GM ne fait pas attention, on mettra deux et deux ensemble. »[^211]

Ces caractéristiques de la technologie industrielle ont abouti systématiquement à la construction de syndicats capables de piller les capitalistes et à de plus gros gouvernements, eux aussi gagnants sur les impôts visant ces grandes entités industrielles. Ces faits se reproduisirent chaque fois que l’industrie à grande échelle s’implanta. À chaque fois, des syndicats purent émerger et exercer la violence pour exiger plus que le salaire d’équilibre. Ils s’appuyaient certes sur la présence d’usines coûteuses, immenses, visibles, difficiles à déplacer. L’immobilisation même du capital augmentait son exposition. Ce stock considérable, s’il cessait de tourner, amputait rapidement les bénéfices.

Le phénoménologue Henry Simons formula le problème en 1944 :  
« Sans une vaste capacité de coercition et d’intimidation, imaginer la création d’un syndicat relève de la pure abstraction. Les syndicats ont aujourd’hui ce pouvoir ; ils l’ont toujours eu et l’auront toujours, aussi longtemps que leur forme demeurera la même. Lorsqu’il est faible et mal assuré, il doit se montrer au grand jour et souvent ; s’il s’amplifie et devient incontesté, il ressemble au pouvoir d’un État, reconnu et craint à tel point qu’il n’a pas besoin de s’exhiber en continu. »[^212]

Si l’argument de Simons se révèle pertinent, il se trompait cependant sur un point décisif.

Il supposait que les syndicats « auront toujours », selon lui, ces « grandes capacités de coercition et d’intimidation ». Or, ces derniers sont en train de disparaître, pas seulement aux États-Unis ou au Royaume-Uni, mais dans la plupart des nations industrielles. La raison, que Simons n’avait pas envisagée et que bien des militants syndicaux ignorent encore, tient au basculement vers la Société de l’Information, qui modifie radicalement les conditions mégapolitiques, au bénéfice d’une protection accrue de la propriété. Dans l’espace commercial lui-même, la micro-informatique crée des incitations radicalement différentes de celles de l’ère industrielle.

1. *La technologie de l’information possède un contenu négligeable en ressources naturelles.* Elle n’offre que peu, voire aucun, avantage géographique inhérent. La plupart des technologies de l’information sont hautement portables. Puisqu’elles peuvent fonctionner indépendamment d’un lieu précis, elles accroissent la mobilité des idées, des personnes et du capital. General Motors ne pouvait pas mettre ses trois chaînes de montage de Flint, dans le Michigan, dans ses valises et s’envoler. Une entreprise de logiciels le peut. Les propriétaires peuvent transférer leurs algorithmes dans des ordinateurs portables et prendre le premier avion. De telles firmes sont en outre incitées à fuir les impôts élevés ou les revendications syndicales de salaires monopolistiques. Les petites entreprises ont tendance à être plus nombreuses sur un marché. Si vous avez des dizaines ou même des centaines de concurrents prêts à séduire vos clients, vous ne pouvez pas vous permettre de verser aux politiciens ou à vos employés davantage que ce qu’ils valent réellement. Si vous étiez seul à le faire, vos coûts dépasseraient ceux de vos concurrents et vous feriez faillite. L’absence d’avantages opérationnels significatifs liés à un site particulier signifie que les organisations coercitives, comme les gouvernements et les syndicats, disposeront inévitablement de moins de leviers pour s’approprier une partie de ces avantages.

2. *La technologie de l’information diminue l’échelle des entreprises.* Cela se traduit par une taille plus réduite de chaque firme, ce qui implique un nombre plus important de concurrents. L’intensification de la concurrence limite les possibilités d’extorsion parce qu’il y a davantage de cibles à contrôler physiquement pour faire grimper salaires ou impôts au-dessus des niveaux concurrentiels. La forte diminution de la taille moyenne des entreprises, facilitée par la technologie de l’information, a déjà réduit le nombre de personnes occupant des emplois subalternes. Aux États-Unis, par exemple, selon certaines estimations largement citées, jusqu’à 30 millions de personnes travaillaient seules dans leur propre entreprise en 1996. Évidemment, il est peu probable que ces 30 millions de personnes se mettent en grève contre elles-mêmes. Il est à peine moins improbable que les millions de salariés qui travaillent dans de petites entreprises comptant quelques employés tentent de contraindre leur patron à leur verser des salaires supérieurs au marché. À l’ère de l’information, les travailleurs souhaitant hausser leurs salaires par l’extorsion n’auront pas l’avantage militaire d’une supériorité numérique accablante, qui les rendait redoutables dans les usines. Moins il y a de personnes employées dans chaque firme, moins il y a d’occasions de recourir à une violence anonyme. Ne serait-ce que pour cette raison, dix mille travailleurs répartis dans cinq cents entreprises menaceront bien moins la propriété de ces sociétés que dix mille employés dans une seule structure, même si le ratio employés/propriétaires-directeurs demeure identique.

3. *Une baisse de l’échelle des entreprises implique aussi que les tentatives visant à obtenir des salaires supérieurs au marché ont moins de chances de bénéficier d’un large soutien social, comme ce fut le cas durant l’ère industrielle.* Les syndicats voulant racketter les employeurs se retrouveront davantage dans la situation des ouvriers des canaux, des chemins de fer et des mines du XIXe siècle. Même là où subsistent quelques grandes firmes héritées de l’ère industrielle, elles opèreront dans un environnement marqué par une multitude d’emplois dispersés dans de petites entités. La prédominance de petites entreprises et de petits propriétaires suggère un soutien social plus marqué aux droits de propriété, même si le désir de redistribuer les revenus demeure inchangé.

4. *La technologie de l’information abaisse le coût du capital, ce qui tend également à accroître la concurrence en facilitant l’entrepreneuriat et en permettant à davantage de personnes de travailler de façon indépendante.* Des besoins moindres en capital réduisent non seulement les barrières à l’entrée, mais aussi les « barrières à la sortie ». En d’autres termes, cela implique que les firmes auront vraisemblablement moins d’actifs en proportion de leurs revenus, et donc moins de capacité à absorber des pertes. Elles recourront aussi moins souvent aux banques pour emprunter ; à l’ère de l’information, les sociétés risquent également de posséder moins d’actifs matériels susceptibles d’être saisis.

5. *La technologie de l’information raccourcit le cycle de vie des produits.* Elle accélère ainsi l’obsolescence des biens. Cet élément tend également à rendre de courte durée tout gain obtenu par l’extorsion de salaires supérieurs au marché. Sur des marchés très concurrentiels, des salaires trop élevés peuvent entraîner directement de rapides suppressions d’emplois, voire la faillite de l’entreprise. Chercher à obtenir temporairement des salaires plus élevés au risque de perdre son travail revient à brûler ses meubles pour gagner quelques degrés de chaleur dans la maison.

6. *La technologie de l’information n’est pas séquentielle, mais simultanée et dispersée.* Contrairement à la chaîne d’assemblage, elle peut prendre en charge de multiples processus simultanément. Elle distribue les activités sur des réseaux, autorisant la redondance et la substitution entre postes de travail qui peuvent se compter par milliers, voire par millions, et se situer partout dans le monde. Un nombre croissant de tâches peut s’effectuer en coopération sans jamais de contact physique entre les participants. À mesure que la réalité virtuelle et la visioconférence progresseront, la tendance au fractionnement des fonctions et au télétravail va s’accélérer. C’est l’équivalent, à l’ère de l’information, du « domestic system », qui mit à mal la puissance des corporations médiévales. Le fait que de moins en moins de gens travaillent ensemble dans des usines enfumées prive les travailleurs d’un avantage majeur qu’ils avaient pour contraindre les capitalistes ; cela rend aussi de plus en plus difficile de distinguer leur extorsion d’un simple racket. Jusqu’à présent, seules les personnes travaillant ensemble et employées par la même firme dans un même lieu pouvaient recourir à la violence pour obtenir une hausse de revenus. Mais si le « lieu de travail » n’existe plus en tant qu’espace central et que la plupart des fonctions sont confiées à des sous-traitants ou des télétravailleurs, leurs tentatives d’extorquer de l’argent à leurs clients ou « employeurs » ressemblent fort à un racket.

    À titre d’exemple, un télétravailleur menaçant de contaminer les ordinateurs de l’entreprise avec un virus s’il n’obtient pas une prime supplémentaire est-il un travailleur en grève ? Ou un racketteur sur Internet ?

    Qu’il s’agisse de l’un ou de l’autre importe peu en pratique. La réaction des firmes visées sera sensiblement la même dans tous les cas. Les réponses techniques au sabotage informatique, comme l’amélioration du chiffrement et de la sécurité des réseaux, conçues pour parer la menace d’un pirate extérieur, devraient aussi neutraliser la capacité d’un employé ou sous-traitant mécontent à causer des dommages aux entités avec lesquelles il collabore régulièrement ou occasionnellement. Bien sûr, on pourrait imaginer que le salarié ou le télétravailleur aille « piqueter » de manière plus traditionnelle sur le site de l’entreprise. Mais même cela peut s’avérer moins évident à l’ère de l’information. La capacité de la technologie de l’information à transcender la localisation et à disséminer les activités économiques signifie que, pour la première fois, employeurs et employés n’ont pas besoin de résider dans les mêmes juridictions. Ici, il ne s’agit pas simplement de la différence entre deux quartiers comme Mayfair et Peckham, mais plutôt du cas d’employeurs basés aux Bermudes et de télétravailleurs installés à New Delhi.

    En outre, si ces travailleurs indiens en venaient à idéaliser les récits des grandes grèves de General Motors de 1936-1937 et décidaient de partir aux Bermudes pour manifester, ils pourraient ne trouver aucun bureau physique à leur arrivée. La société de publicité Chiat/Day, par exemple, a déjà engagé le démantèlement de son siège social. Ses salariés, ou sous-traitants, communiquent via le transfert d’appels et Internet. Quand il devient nécessaire de réunir des équipes talentueuses pour coordonner le travail d’un projet, ils louent une salle de réunion d’hôtel. Une fois la tâche accomplie, ils rendent les clés. Le fait que la micro-informatique libère et disperse le processus de production, autrefois confiné à la suite ordonnée d’une chaîne d’assemblage, réduit considérablement l’influence dont jouissaient jadis les institutions coercitives comme les syndicats et les gouvernements. Si la chaîne d’assemblage était comparable à un chemin de fer à l’intérieur même de l’usine, aisément bloqué par une grève sur le tas, le cyberespace est un domaine illimité sans existence physique. On ne peut pas l’occuper par la force ni le prendre en otage. La position des salariés qui voudraient user de violence pour forcer une hausse de salaires sera infiniment plus fragile à l’ère de l’information que celle des grévistes occupant les usines de General Motors en 1936-1937.

7. *La micro-informatique individualise le travail, tandis que la technologie industrielle le standardisait.* Toute personne utilisant les mêmes outils obtenait autrefois un résultat identique. La microtechnologie commence à remplacer les « machines stupides » par des technologies plus intelligentes, capables de produire des résultats beaucoup plus variés. L’accroissement de la variabilité de la production pour des individus utilisant pourtant les mêmes outils a des implications considérables, dont plusieurs seront abordées dans les chapitres suivants. Parmi les plus importantes : lorsque la production varie, les revenus varient également. Dans nombre de secteurs où la compétence fluctue sensiblement d’une personne à l’autre, la plus grande part de la valeur créée proviendra d’une minorité d’individus. C’est une caractéristique courante des marchés très concurrentiels. On le voit clairement dans le sport, par exemple. Des millions de jeunes dans le monde pratiquent diverses formes de football, mais 99 % de l’argent dépensé pour regarder ce sport rémunère une infime poignée de joueurs d’élite. De la même façon, il existe une multitude d’acteurs et d’actrices aspirants, alors que peu d’entre eux deviennent des stars. Chaque année, on publie des dizaines de milliers de livres, mais la majeure partie des droits d’auteur est versée à un petit nombre d’auteurs à succès qui savent réellement captiver leurs lecteurs. Hélas, nous n’en faisons pas partie.

    L’énorme variabilité de la production entre personnes utilisant les mêmes équipements crée un nouvel obstacle à l’extorsion. Cela soulève un problème majeur de répartition des gains. Lorsque la majeure partie de la valeur au sein d’une activité est créée par une fraction réduite des participants, il est presque mathématiquement impossible que ces derniers en ressortent gagnants avec un partage uniformisé des revenus. Un programmeur peut concevoir un algorithme pour contrôler un robot, algorithme qui vaudra des millions. Un autre, utilisant pourtant le même matériel, peut créer un programme sans valeur. Le programmeur plus productif n’aura guère envie de voir son revenu dépendre de celui d’un collègue, pas plus que Tom Clancy n’accepterait de mutualiser ses droits d’auteur avec les nôtres.

    Même les débuts de la révolution de l’information ont déjà montré bien plus clairement qu’en 1975 que les compétences et la capacité intellectuelle sont des variables déterminantes dans la production économique. Cela a déjà réduit en cendres l’ancienne justification, issue de l’ère industrielle, selon laquelle le prolétariat extorquait les capitalistes. L’idée que les travailleurs non qualifiés généraient réellement toute la valeur dont les capitalistes et les entrepreneurs s’emparaient ensuite en proportions excessives est désormais un anachronisme. Ce n’est même plus une fiction crédible lorsqu’il est question de technologies de l’information. Quand un programmeur s’assoit pour écrire du code, la corrélation entre son talent et son produit est trop directe pour entretenir l’illusion sur qui en est responsable. Il est évident qu’un individu illettré ou quasi illettré serait incapable de programmer un ordinateur. Il l’est tout autant que la valeur des programmes conçus par d’autres ne saurait avoir été « volée » à celui qui ne sait pas coder. C’est pourquoi les plaintes d’« exploitation » émanent désormais surtout des agents d’entretien.

    La technologie de l’information rend plus clair le fait que les personnes peu qualifiées ne sont pas victimes d’un abus sur leur capacité de production, mais craignent plutôt de ne pas être en mesure d’apporter une réelle contribution économique. Comme le suggère Kevin Kelly dans *Out Of Control*, l’entreprise automobile « Upstart » de l’ère de l’information pourrait n’être conçue que par « une douzaine de personnes », sous-traitant la plupart de leurs pièces, tout en produisant des voitures encore plus finement adaptées aux désirs de leurs clients que ce que l’on a pu observer jusqu’ici à Detroit ou Tokyo : « Des voitures, chacune personnalisée, commandées via un réseau de clients et expédiées dès qu’elles sont prêtes. Les moules pour la carrosserie sont façonnés à l’aide de lasers pilotés par ordinateur, intégrant des designs issus des retours clients et du ciblage marketing. Une chaîne flexible de robots assemble les voitures. L’entretien et l’amélioration des robots sont délégués à une entreprise spécialisée. »[^213]

### « Des outils qui parlent »

De plus en plus, les tâches peu qualifiées sont prises en charge par des machines, robots et systèmes numériques. En reprenant la formule d’Aristote, définissant jadis les esclaves comme « des outils doués de parole », nous pourrons bientôt disposer de véritables assistants virtuels, dotés de parole et obéissant à des consignes complexes. La computation rapide autorise déjà quelques applications balbutiantes de reconnaissance vocale, par exemple le mains libres ou les systèmes de calcul sur commande orale. Les outils qui convertissent la parole en texte ont déjà trouvé le chemin du marché en 1996, quand nous écrivons ces lignes. À mesure que les algorithmes de reconnaissance de motifs s’améliorent, on verra surgir, sans doute avant longtemps, des systèmes couplés à des synthétiseurs vocaux capables de réaliser bien plus : opérateurs téléphoniques virtuels, secrétaires, courtiers automatisés, compositeurs de musique, traders obligataires, analystes militaires, etc.

Michael Mauldin, de l’université Carnegie-Mellon, a ainsi développé un bot baptisé « Julia », personnalité artificielle assez persuasive pour duper presque n’importe qui dans un échange sur Internet. Cet alter ego a l’humour vif, manie la répartie et semble passionné de hockey. Selon la presse, « Julia est une “femme” de fiction en ligne capable de plaisanter et de sortir l’annotation sarcastique parfaite. Mais Julia n’a rien d’humain ; c’est un programme spécialisé, dénué de toute incarnation, qui n’existe que dans la toile du Net. »[^214] Les progrès déjà remarquables de l’IA et des « services numériques » laissent peu de doutes sur l’importance potentielle d’autres usages. Avec d’importantes conséquences mégapolitiques.

### L’individu comme « ensemble »

Grâce à ces « outils qui parlent », un individu pourra se démultiplier en étant engagé dans de multiples activités simultanées. L’« individu », dans cette vision, ne sera plus réductible à une singularité, mais deviendra potentiellement un ensemble extrêmement large d’actions gérées par des agents intelligents. Non seulement cela augmentera la productivité des plus talentueux, mais cela rendra aussi, d’un point de vue militaire, l’« Individu Souverain » bien plus redoutable que jamais.

Un individu pourra recourir à un nombre potentiellement infini d’agents intelligents. Il ou elle pourra même continuer d’agir après sa propre mort biologique. Pour la première fois dans l’histoire, l’individu aura la possibilité de mener des actions même au-delà de son décès. Il ne sera plus possible de simplement tuer quelqu’un pour annihiler entièrement ses capacités de représailles. Voilà une véritable révolution dans la logique de la violence.

### Vers plus de lucidité pour l’ère de l’information

Les plus grands changements concernent des variables oubliées. Ou, pour le dire autrement : depuis de nombreux siècles, nous n’avions plus besoin de nous soucier du rapport des forces entre extorsion et protection, tant il était stable dans sa tendance à favoriser l’extorsion. Mais l’ère de l’information altère ce rapport. Le fait qu’un individu puisse désormais survivre par une armée d’agents virtuels modifie déjà l’équation.

C’est un exemple notable, mais non l’unique. Si un voleur croit pouvoir tout rafler en assassinant sa victime, il pourrait être menacé de représailles après le meurtre, comme la suppression électronique de ses comptes, un sabotage ou autre. Ce qui relevait de la science-fiction « si tu me tues, je viderai tes comptes, je ferai ceci ou cela » sera partiellement réalisable. Peut-être que les comptes en banque du coupable seraient hermétiques ou difficilement accessibles, mais les moyens de rétorsion n’en resteraient pas moins nombreux. Cela mérite réflexion.

### De nouvelles manières de se protéger

Voilà un aperçu des formes de protection rendues possibles par l’ère de l’information, dont la plupart affaiblissent le monopole d’État sur la protection et l’extorsion qui régnait depuis deux siècles. Même avant ces technologies, il y avait toujours plusieurs manières d’assurer sa défense ; toutes ne relevaient pas de l’État.

Un individu menacé peut s’en aller. Quand de nouveaux horizons s’offraient à eux, beaucoup optaient pour la fuite. Pour faire face aux vols et dégradations, on recourt à l’assurance. Les malédictions et sortilèges, bien que peu efficaces d’un point de vue rationnel, ont parfois servi dans des sociétés superstitieuses. Autre technique, la dissimulation : enfouir ses biens, ériger des murs, ajouter verrous et systèmes d’alarme. Mais ces solutions ne conviennent pas toujours.

Malgré tout, la dissuasion la plus puissante a toujours été la capacité de répondre à la violence par une violence supérieure, de trouver quelqu’un ou quelque chose pour neutraliser un agresseur. De là la question : à qui peut-on se fier pour engendrer une riposte, et par quels moyens le motiver à exposer sa vie au nom de notre sécurité ? Parfois c’est la parenté ; parfois des mercenaires ou des gardes privés ; ou parfois des groupes tribaux qui mènent des vendettas. Mais leur loyauté n’a jamais été garantie. Les agents intelligents de l’ère de l’information, eux, ne nous trahiront pas.

### Les Paradoxes du Pouvoir

L'utilisation de la violence pour se protéger de la violence est truffée de paradoxes. Dans les conditions qui ont prévalu jusqu'à présent, tout groupe ou agence que vous pourriez employer pour protéger efficacement votre vie et votre patrimoine contre une attaque aurait également nécessairement la capacité de passer à l'offensive. C'est un inconvénient pour lequel il n'existe pas de solution facile. Normalement, vous pourriez compter sur la concurrence pour empêcher les prestataires d'un service économique d'ignorer les souhaits de leurs clients. Mais en matière de violence, la concurrence directe produit souvent des résultats pervers. Par le passé, elle a généralement conduit à une intensification de la violence. Quand deux agences censées offrir protection envoient leurs forces pour s'arrêter mutuellement, le résultat ressemble davantage à une guerre civile qu'à une protection. Lorsque vous cherchez à vous protéger de la violence, vous ne souhaitez normalement pas accroître sa production, mais la supprimer, et la supprimer selon des modalités qui n'autorisent pas le pillage des clients qui paient, en premier lieu, pour ce service de protection.

> « ...pendant le temps où les hommes vivent sans un pouvoir commun pour les tenir en respect, ils se trouvent dans cet état que l'on appelle guerre : une guerre de chacun contre chacun, où les hommes ne jouissent d'aucune sécurité autre que celle que leur propre force et leurs inventions leur procurent. » - THOMAS HOBBES

### Monopole et Anarchie

C'est pourquoi l'anarchie, ou « la guerre de tous contre tous », comme l'a décrite Hobbes, a rarement constitué un état de choses satisfaisant. La concurrence locale dans l'usage de la violence impliquait généralement des coûts plus élevés pour la protection et une moindre efficacité de celle-ci. Parfois, des enthousiastes du marché et d'esprit libre ont suggéré que les seuls mécanismes du marché suffiraient à assurer la surveillance des droits de propriété et la protection de la vie, sans qu'aucune souveraineté ne soit requise.[^215] : Certaines analyses ont été élégantes, mais le fait demeure que la fourniture, par le marché libre, des services de police et de justice ne s'est pas révélée viable dans les conditions mégapolitiques de l'industrialisme. Seules les sociétés primitives, où les comportements sont fortement stéréotypés et où les populations sont minuscules et homogènes, ont pu survivre sans gouvernements chargés d'assurer le monopole local de la protection par la violence.

Les exemples de sociétés anarchiques dépassant le niveau de la tribu de chasseurs-cueilleurs sont rares et anciens. Ils relèvent tous des économies les plus simples d'agriculteurs isolés dépendant de la pluie. Les Kafirs dans l'Afghanistan pré-musulman. Certaines tribus irlandaises aux Âges Obscurs. Quelques bandes indiennes au Brésil, au Venezuela et au Paraguay. D'autres peuples autochtones dans des régions éparses du monde. Leurs méthodes d'organiser la protection sans gouvernement ne sont connues que des connaisseurs de cas extrêmes. Si vous souhaitez en savoir plus à leur sujet, nous citons plusieurs ouvrages dans nos Notes qui fournissent davantage de détails.[^216] : Les groupes primitifs ont pu fonctionner sans une organisation distincte spécialisée dans la violence uniquement parce qu'ils formaient de petites sociétés fermées et isolées. Ils pouvaient s'appuyer sur des liens de parenté étroits pour se défendre contre des menaces violentes, sur une échelle limitée, lesquelles étaient les seules auxquelles ils étaient susceptibles d'être confrontés. Lorsqu'ils rencontraient des menaces plus importantes, organisées par des États, ils étaient submergés et soumis à un régime monopolistique imposé par des groupes extérieurs. Cela s'est reproduit à maintes reprises. Partout où des sociétés se sont constituées à une échelle supérieure à celle des bandes et des tribus, notamment lorsque les routes commerciales mettaient en contact divers peuples, des spécialistes de la violence ont toujours émergé pour piller tout surplus que des peuples plus pacifiques pouvaient produire. Lorsque les conditions technologiques ont accru les retours sur l'usage de la violence, elles ont condamné les sociétés qui n'étaient pas organisées pour canaliser d'importantes ressources en vue de faire la guerre.

> « Quels princes procuraient un vrai service de police ? Lesquels n’étaient que des racketteurs ou des pillards ? Un pillard pouvait devenir chef de police de facto dès l’instant où il régularisait son “tribut”, l’adaptait à la capacité de paiement, protégeait son territoire contre les concurrents, et maintenait longtemps assez sa domination pour qu’elle devienne légitime par la coutume. »[^217] - FREDERIC C. LANE

### L’État comme vendeur de protection

Comme nous l’avons rappelé, la fonction économique fondamentale d’un État, pour ses contribuables, réside dans la garantie de la sécurité. Toutefois, l’État opère également à la façon d’une mafia, prélevant un tribut sur les individus implantés dans sa sphère. L’État ne se contente pas d’un service légitime contre la violence extérieure, mais aussi d’une protection payante contre sa propre violence potentielle. La première prestation est un service économique, la seconde s’apparente à un racket. Dans la pratique, il est parfois difficile de les distinguer. Comme le dit Charles Tilly, les gouvernements peuvent « s’analyser comme la plus vaste forme de criminalité organisée »[^218].

Même l’État le plus respectable mêle ces deux pans – protection utile et extorsion. Tous deux sont optimisés quand le gouvernement s’assure un quasi-monopole de la violence sur le territoire où il opère. Quand une entité s’arroge la force légitime en un lieu, elle peut protéger efficacement ses « clients » contre la plupart des violences péremptoires émanant de tiers.

### Un monopole naturel sur la terre

Détenir un monopole territorial de la force donne aussi à l’État un avantage colossal : les coûts de protection baissent. Comme l’expliquait Lane : « L’industrie de l’usage et du contrôle de la violence constituait un monopole naturel, du moins sur la terre ferme. À l’intérieur de certaines frontières, un service unifié revient bien moins cher qu’une concurrence anarchique »[^219]. Ainsi, « un monopole local absolu de l’usage de la force permettra à l’organisation en charge de la protection d’améliorer cette dernière et d’en réduire drastiquement les coûts »[^220]. L’État peut être plus protecteur à moindre coût s’il n’a pas à affronter continuellement d’autres factions concurrentes.

La possibilité que la souveraineté cesse de s’appuyer sur un monopole territorial a déjà attiré l’attention de divers penseurs politiques, dont David J. Elkins, auteur de *Beyond Sovereignty: Territory and Political Economy in the Twenty-First Century*. Il rejoint notre thèse selon laquelle cette souveraineté, à l’image du monopole religieux, est sur le point d’éclater. Dans son ouvrage, Elkins écrit : « Nous nous sommes habitués à l’idée que toute religion devait s’implanter sur un territoire. Or le mouvement national a supplanté l’universel religieux au rang de souverain ultime, ce qui s’est traduit par l’“interpénétration” actuelle de différentes communautés religieuses dans le même espace. Mais en guise de contrepartie, nous refusons toute interpénétration de souverainetés nationales ou provinciales, alors même que cela semble être en train de se défaire. »[^221] Et il ajoute, dans le même sens que nous, que « la nation a toujours fonctionné comme un “panier composite” dans lequel nous rangeons tous les attributs de nos vies. À l’instar d’un combo-plat dans un menu de restaurant, on ne peut guère commander à la carte. Cependant, je pense que ce principe est en train de décliner… Dans la société du XXIe siècle, on attendra que les gouvernements proposent du “sur-mesure” »[^222]. Rien ne contribuera plus à cette décomposition de la souveraineté centralisée et à l’avènement d’un « gouvernement à la carte » que la croissance du cybercommerce, transcendant les frontières physiques.

> « Au fur et à mesure que la fréquence augmente et la longueur d’onde diminue, la performance numérique s’accroît de manière exponentielle. La bande passante augmente, la consommation électrique s’affaisse, la taille de l’antenne diminue, les interférences disparaissent, le taux d’erreur chute. » – George Gilder

## La loi du « télécosme » abroge les lois des nations

Nous ne sommes pas seuls à penser que la hausse de la bande passante (la capacité des supports de communication) va surpasser la puissance des États et leurs frontières. Dans *The 500-Year Delta: What Happens After What Comes Next*, Jim Taylor et Watts Wacker disent, sans employer nos mots exacts, que « l’accès [à l’information] génère le globalisme, lequel perturbe les systèmes politiques et rend obsolètes les frontières. À mesure que les frontières se dissolvent, la notion de fiscalité s’effrite – ce qui sapait la ressource vitale de l’État… Et la disparition des frontières sape aussi l’idée d’“être né quelque part” qui conférait certains avantages économiques, faisant s’évanouir les privilèges nationaux. Par conséquent, tout l’édifice patriotique, démocratique ou étatique tombe aux oubliettes. »[^223] Sans l’exprimer littéralement, ces auteurs semblent eux aussi percevoir un glissement vers la libération de l’« Individu Souverain ». Comme ils l’écrivent : « À l’horizon se profile une forme d’individualisme plus résolue encore, que la démocratie telle que nous la concevons de nos jours n’autorise pas. »[^224] Comment ? Taylor et Wacker distinguent une dynamique puissante.

« En réalité, le patriotisme sous sa forme la plus large – l’amour d’une nation, le devoir filial à son égard – n’est plus une disposition très utile. Pour s’épanouir dans la société mondialisée, les citoyens ne se choisiront plus une identité nationale, mais des appartenances politiques, sociales et économiques selon leurs objectifs personnels. Ils optimiseront leur accès à la connaissance, à la mobilité, à l’action et à la réalisation de soi. Les nations et les entreprises qui continueront à défendre un cadre figé par nostalgie péricliteront. »[^225]

La dépréciation des frontières physiques, du fait du triplement annuel de la bande passante et de la croissance géométrique d’Internet et du Web, va accélérer la « désintermédiation » des gouvernements. Si cette croissance se maintient jusqu’en 2012, on aura multiplié la bande passante par un facteur d’un milliard depuis 1993, date à laquelle George Gilder a prévu sa montée exponentielle, plus forte encore que celle des microprocesseurs. Si cela se confirme (et cela semble probable, vu les progrès récents de l’optique intégrée), le flot titanesque de capacité de transmission généré permettra un bond prodigieux du cybercommerce. Grâce au multiplexage en longueurs d’onde, un unique brin de fibre optique aussi mince qu’un cheveu peut véhiculer un trillion de bits par seconde[^226]. Autrement dit, un seul câble en fibre peut acheminer vingt-cinq fois plus de bits que tout le réseau de communications mondial actuel. Le potentiel d’expansion est démesuré. Avec un tel foisonnement de bande passante, le trafic prendrait des proportions colossales, et les médias traditionnels comme le téléphone et la TV deviendraient obsolètes. Le Web diffuserait un éventail de contenus plus riche que la télévision hertzienne actuelle. À mesure que se déploiera cette « révolution de la bande passante », les gens basculeront dans l’univers immatériel des communautés en ligne et du cybercommerce, lequel pourra atteindre un niveau graphique suffisant pour engendrer un « métavers », un monde virtuel alternatif comme l’a imaginé l’auteur de science-fiction Neal Stephenson. Dans son roman *Snow Crash*, ce « métavers » est une communauté constituée de lois, de princes et de criminels[^227]. Plus l’activité économique émergera dans cet univers, plus la valeur du contrôle territorial se réduira, et plus les États se verront incités à concéder ou céder des bribes de souveraineté.

Comme les États-nations créent aujourd’hui des paradis fiscaux, des zones franches, etc., ils loueront leur souveraineté. Nous avons déjà mentionné les négociations en cours entre l’Ordre Souverain Militaire Hospitalier de Saint-Jean de Jérusalem, de Rhodes et de Malte (plus connu sous le nom de l’Ordre de Malte, neuf siècles d’existence) et la République de Malte pour rétrocéder la souveraineté du Fort Saint-Ange. Nous parions que ce terrain aboutira. D’autres États feront de même : franchiser un petit territoire ou une enclave à des groupes ou « communautés virtuelles ». Certaines firmes de sécurité ou des chaînes hôtelières pourraient mettre la main sur des parcelles pour proposer leur propre mixte : villages de retraite « gated communities » + zones franches. Les entités religieuses de toute obédience se livreront à des essais similairement utopiques en des lieux reculés. Même des familles riches ou des individus aisés pourraient s’offrir un fief — émettre leurs timbres, leurs passeports, disposer d’un site Web sous leur juridiction.

## Monopole et pillage

Notons surtout que les motivations d’un État pour « affermer » des parcelles de souveraineté sont fort différentes de celles qui prévalent lorsque des factions rivales entament une lutte armée. Réserver la souveraineté d’une zone n’est pas de nature à déstabiliser le monopole d’une force installée, comme le ferait une guérilla. Dans les affrontements classiques, le contrôle réel du monopole coercitif décide s’il vaut mieux protéger les populations ou les rançonner. Là où sévissent plusieurs groupes rivaux se disputant le territoire, l’incitation à saisir la richesse par la force croît. Quand le pouvoir est trop instable pour être durable, on lui préfère la rapine. Trop incertain de conserver assez longtemps la place, le chef d’une milice penche pour maximiser le pillage sur le court terme plutôt que d’organiser la sécurité, laquelle pourrait rapporter plus à long terme.

On voit donc qu’en règle générale, plus il y a de groupes armés en concurrence, plus la violence s’étend, détruisant une grande partie des bénéfices de la coopération économique et sociale

L’exemple de la Chine « des seigneurs de la guerre » dans les années 1920, ou celui de la Somalie des milices, illustre précisément comment l’anarchie détruit la création de valeur. Comme on l’a vu sur CNN, les armées locales (« technicals » en Somalie) sèment la désolation jusqu’à ce qu’une force nettement supérieure, comme les troupes américaines, intervienne, puis le cycle se répète dès qu’elle se retire. Comme le décrivait le Washington Post :

> « Des pick-up équipés de mitrailleuses anti-aériennes arpentent à nouveau les rues poussiéreuses et jonchées de gravats. Des jeunes hommes, fusil à l’épaule, réclament de l’argent à chaque barrage sauvage. Un quartier tenu par une milice a été surnommé “Bosnie-Herzégovine”. Pour circuler, il faut souvent louer les services de voyous armés pour cent dollars par jour, plus le temps de la pause-déjeuner. »[^228]

Des exemples analogues, au Rwanda ou ailleurs, viennent rappeler qu’une pluralité d’acteurs armés ne va pas dans le sens d’un ordre pacifique rentable. Les bandes itinérantes qui se livrent au pillage n’ont même pas les faibles motivations qu’aurait un dictateur quand son pouvoir est relativement sécurisé.

> « La société moderne, en particulier en Occident, se caractérise avant tout par une certaine tendance à la monopolisation. L’usage privé de la force est interdit et réservé à une autorité publique centrale, de quelque type qu’elle soit. De même, la fiscalité sur les biens ou sur les revenus est monopolisée par cette autorité. Ces deux monopoles s’autoentretiennent. À l’instant où l’un disparaît, l’autre suit aussitôt. Il se peut que, par moments, un côté soit plus ébranlé. »[^229] – NORBERT ELIAS

## L’évolution de la protection

Dans nos ouvrages précédents (*Blood in the Streets* et *The Great Reckoning*), nous avons souvent mis l’accent sur ce que Frederic C. Lane appela les « conséquences économiques de la violence organisée ». Lane, ignorant l’aube de l’ère de l’information, propose une vision linéaire de quatre stades dans l’histoire de l’Occident. Nous avons nous-mêmes utilisé ce cadre pour éclairer l’évolution des sociétés occidentales depuis la chute de Rome, même si Lane passe relativement sous silence les facteurs mégapolitiques à l’origine de l’échelle à laquelle la violence est menée.

We have already analyzed some of the megapolitical factors that played a role in the evolution of Western society following the fall of Rome. Lane also examined this period, focusing on the economic consequences of that competition to monopolize violence. He discerned four important stages in the functioning of economies over the past thousand years, each involving a different phase in the organization of violence.[^244]

### Au sortir des ténèbres

Lane décrit le premier stade comme un temps d’« anarchie et de pillage » qui rappelle la révolution féodale il y a un millénaire. Il ne fixe pas de date précise, mais vu ses allusions, on se situe dans la transition après les Âges Obscurs, période où « l’usage de la violence était très concurrentiel, même à l’échelon local »[^230]. Si la violence était « très concurrentielle », c’est que l’offensive restait coûteuse et la défense plus facile. Comme nous l’avons avancé au chapitre 3, cette époque se confond également avec une productivité agricole déclinante, aggravée par des aléas climatiques défavorables. Sans avantages d’échelle en termes militaires, la concurrence entre potentats pullulait. Les activités économiques en pâtissaient sévèrement.

N’ayant pas la capacité de fédérer militairement de vastes territoires, les chevaliers régnaient par sporadiques rapines, à grand-peine organisées.

### Le féodalisme

"The second stage begins when small regional or provincial monopolies are established. Agricultural production then rises, and most of the surplus is collected by recently established monopolists of violence."[^231]: Still, the surplus is relatively meager during this second stage, which we identify with the early Middle Ages. Economic growth is held down by the absence of advantages of scale in the organization of violence, which keeps the military costs of enforcing local monopolies high. But while the costs remain high, the price that minisovereignties can charge for protection rises, since economic activity expands when anarchy is curtailed.

During a late phase of the second stage many tribute takers attract customers by special offers to agricultural and commercial enterprise. They offer protection at low prices for those who will bring new lands into cultivation, and special policing services to encourage trade such as that organized by the Counts of Champagne for merchants coming to their fairs."[^232]: In other words, when they were able to establish a sufficient control over territory to negotiate credibly, local warlords did what local merchants do when they need to increase market share: they discounted their services to attract customers. The warlords later used the added resources from additional economic activity to consolidate their control over larger territories. Once that control was firmly established, they began to enjoy more of the advantages of monopoly. Their military costs for policing tended to fall, and they could also increase the price they charged without worrying that this made their service less attractive to customers.

In this complicated stage in Western history, those who employ violence, the medieval lords and monarchs, take most of the surplus above subsistence. There are few merchants. The most successful are those who are best able to evade or minimize the taxes, fees, and other costs imposed by those demanding money for "protection services."

### La période moderne

Le troisième stade, selon Lane, se produit lorsque les marchands et propriétaires terriens qui ne sont pas dans la sphère militaire récupèrent la portion majoritaire du surplus médité par l’économie, davantage que le prélèvement des rois et féodaux[^233]. Ces marchands, investissant leurs bénéfices, génèrent de la croissance. Ce fut la fin du Moyen Âge et le début de l’ère mercantile.


### L’ère de la grande usine

Lane situe le passage au quatrième stade autour de 1750, avec la généralisation des nouveaux procédés techniques et la révolution industrielle. Dès lors, la technologie joua un rôle capital dans les profits, surpassant le gain que l’on pouvait obtenir d’une meilleure sécurité. Ainsi, des zones vierges de tout État n’attiraient pas spécialement l’industrie, malgré l’absence d’impôts, car l’innovation était plus déterminante que la charge fiscale. De plus, la centralisation de l’autorité facilita la création de marchés de capitaux, issus parfois de l’effort de guerre, offrant un solide soutien aux grosses opérations industrielles.

La concentration de la technologie et du savoir-faire industriel dans un nombre restreint de pays permit aux gouvernements d’augmenter substantiellement leur pression fiscale, sans crainte de faire fuir les capitalistes. Le décalage technologique a permis aux industries d’être rentables malgré la fiscalité obligée. Et c’est ainsi qu’on aboutit à un monopole de la violence plus systématique.

### Un pillage feutré

Les gouvernements de l’âge industriel ont profité d’un monopole d’extorsion fort juteux. Les coûts réels de la « protection » étaient faible au regard de leurs revenus (impôts). Ils opéraient dans un univers où la concurrence en matière d’utilisation du territoire était minime, voire nulle, car l’anarchie n’était pas une option. L’État réclamait de plus en plus, au point de rendre la limite entre service public et spoliation quasi théorique. Lane soulignait qu’une fraction de l’impôt correspondait bien à la « protection » rendue, tandis qu’une autre se rapprochait du pillage pur[^234]. Mais il était vain de s’en formaliser, car la taxe était obligatoire quoi qu’il en soit. Personne ne pouvait se soustraire au pouvoir régalien[^235].



### L’élévation des revenus sous l’industrialisme

La prospérité grandissante des nations industrialisées rendit le phénomène tolérable : malgré les spoliations croissantes, la richesse augmentait, particulièrement dans les pays de l’OCDE, et l’écart de niveau de vie avec le reste du monde ne cessa de se creuser. Cette dynamique laissait peu de doutes quant au résultat final. En effet, comme nous l’avons vu plus haut, l’État industriel avait besoin de contrôler de manière quasi illimitée les ressources de ses ressortissants pour subsister dans la compétition internationale.

Dans tous les pays industrialisés, les politiques se déroulèrent suivant un même schéma, l’impôt sur les revenus atteignant des sommets (au-delà de 90 % pour les tranches hautes après la Seconde Guerre). Des taux plus élevés que ceux des despotes orientaux de l’Antiquité ! Mais ce modèle de pillage s’explique encore une fois par la nature de la technologie au XXe siècle.

Cette technologie, fortement connectée aux ressources naturelles, localisait les usines et facilitait leur imposition. L’impôt sur la société, sur les biens fonciers, sur les extractions se répandit. L’impôt sur le revenu, d’abord appliqué aux capitalistes, fut vite étendu aux ouvriers, la main-d’œuvre de masse rendant aisée la “retenue à la source”. Recenser les propriétaires agricoles autonomes pour prélever l’impôt eût été plus compliqué. Mais il était simple de fiscaliquement « ponctionner » les grandes usines avec leur service comptable.

L’existence d’une énorme industrie facilita donc la recette, la rendant moins risquée pour l’État que dans l’Antiquité ou au Moyen Âge, même si elle fut, en proportion, bien plus lourde pour les contribuables.

### Protéger quoi ?

Mais qu’est-ce que l’État protégeait donc, quand l’explosion des impôts n’empêchait pas l’essor de la richesse ? Principalement, il protégeait les installations industrielles à forts coûts de capital et dont la vulnérabilité était avérée. Des aciéries, des raffineries, etc., ne peuvent tenir fonctionnement normal dans un environnement de violence désorganisée. Les grandes unités de production avaient besoin de la police publique, fût-ce au prix d’un chantage routinisé sous forme d’imposition légale.

Même au sommet de l’industrialisation, le mythe du « monopole parfait de la force » restait en partie illusoire. L’État dominait largement, mais la pratique courante de la « grève sur le tas » prouvait que les ouvriers, bien organisés, pouvaient se montrer violents eux aussi. Cependant, cette violence était cadrée, réduite à la revendication de salaires supérieurs. On peut la dire « prévisible » ou « grande gueule » plutôt que de type guérilla, dans la plupart des cas.



> « Un gouvernement basé sur le Net ne peut agir qu’avec le consentement des gouvernés. Il doit donc fournir de réels avantages à ses administrés pour qu’ils restent. Il peut s’agir de biens ou de services personnalisés, ou plus largement d’un cadre réglementaire net et transparent : un marché propre, des règles claires, ou une plateforme sociale où la vie privée de chacun est respectée. »[^236] – Esther Dyson

### L’ère de l’information

Nous voyons émerger un cinquième stade dans l’évolution de la concurrence violente en Occident. Lane ne l’avait pas imaginé : c’est l’étape où la compétition s’exerce dans le cyberespace, territoire non monopolistique. On ne peut pas façonner un monopole sur ce qui n’a pas d’existence physique.

Lane postulait, à la lumière de son époque, la perpétuation de l’État-nation. Il remarquait toutefois un point crucial : aucun État n’a jamais exercé de monopole sur les hautes mers. Cela n’a l’air de rien, mais si la mer demeurait hors de portée d’un monopole de violence, il en ira de même pour le cyberespace, où il n’y a même pas de limites géographiques.

## Une concurrence sans anarchie

Dans le passé, l’incapacité à instaurer un monopole local signifiait l’anarchie et le pillage, comme au début du Moyen Âge. Aujourd’hui, l’ère de l’information redistribue les cartes. Alors qu’autrefois, la non-monopolisation de la protection coûtait cher (plus de guerres, impossible d’assurer son avenir), aujourd’hui, avec l’informatique, l’impossibilité d’un monopole dans le cyberespace entraîne de moindres coûts militaires et une productivité accrue.

> « Les pays où les structures de pouvoir et de gouvernance sont multiples, où les conflits d’autorité ne se tranchent pas sous un arbitre central stable, doivent élaborer leurs propres solutions face aux problèmes soulevés par une telle frontière. »[^237] – REES DAVIES

### L’analogie avec la frontière

Le cyberespace est, sous un certain angle, l’équivalent d’une « marche » protégée par la technologie, comme celles qui existaient dans les zones frontalières au Moyen Âge. Autrefois, lorsque l’influence des seigneurs et des rois était limitée et que les prétentions de plusieurs d’entre eux se chevauchaient sur une frontière, un système gouvernemental concurrentiel existait de facto. L’examen du fonctionnement de ces « marches » médiévales pourrait fournir des éclairages sur la manière dont des lois analogues pourraient migrer vers le cyberespace.

L’Andorre subsiste comme une forme de « marche » fossilisée entre la France et l’Espagne : un vestige des conditions « mégapolitiques » qui rendaient difficile, pour l’un ou l’autre des royaumes, de dominer cette zone froide et presque inaccessible de 190 milles carrés dans les Pyrénées. En 1278, un accord fut conclu pour diviser la suzeraineté de l’Andorre entre deux seigneurs féodaux, l’un français et l’autre espagnol : le comte de Foix, côté français, et l’évêque d’Urgel, côté espagnol. Chacun nomma l’un des deux « viquiers » qui exerçaient parcimonieusement le minimum d’autorité gouvernementale en Andorre, principalement en commandant la minuscule milice andorrane, devenue aujourd’hui une force de police. Le rôle du comte a été depuis longtemps supplanté par l’histoire : le gouvernement français le remplace dorénavant depuis Paris. Parmi ses obligations figure le fait de recevoir la moitié du tribut annuel payé par l’Andorre, un montant inférieur au loyer mensuel d’un logement miteux. L’évêque d’Urgel continue, lui, de percevoir sa part du tribut, comme ses prédécesseurs au Moyen Âge.

Comme l’illustre ce tribut éclaté, il existait donc, en Andorre, deux sources de « pouvoir et de juridiction » de tutelle, plutôt qu’une seule. Les appels sur les affaires civiles andorranes étaient traditionnellement adressés soit à l’Université épiscopale d’Urgel, soit à la Cour de cassation de Paris.

En conséquence, l’ambiguïté du statut de l’Andorre a fait que presque aucune loi n’y fut promulguée. L’Andorre bénéficie depuis plus de sept cents ans d’un gouvernement minimal et d’une absence d’impôts. Aujourd’hui, cela ajoute d’ailleurs à son attrait croissant en tant que paradis fiscal. Cependant, il y a encore une génération, l’Andorre était tristement célèbre pour sa pauvreté. Autrefois couverte de forêts denses, elle fut déboisée au fil des siècles par ses habitants qui cherchaient à se chauffer durant les hivers rigoureux. Les chutes de neige y bloquent tout de novembre à avril chaque année. Même en été, Andorre reste si froide que les récoltes ne poussent que sur les versants sud. Si cette description la rend peu attrayante, vous venez de comprendre le secret de sa réussite : l’Andorre a subsisté comme enclave féodale à l’époque de l’État-nation parce qu’elle était isolée et misérable.

À une époque, de nombreuses régions médiévales frontalières ou « marches » voyaient ainsi l’entremêlement de différentes souverainetés. Ces frontières souvent violentes ont perduré pendant des décennies, voire des siècles, dans les zones frontalières d’Europe. La plupart étaient pauvres. Comme nous l’avons signalé précédemment, on trouvait des « marches » entre les zones celtiques et anglaises en Irlande ; entre le pays de Galles et l’Angleterre, l’Écosse et l’Angleterre, l’Italie et la France, la France et l’Espagne, l’Allemagne et les frontières slaves d’Europe centrale, ainsi qu’entre les royaumes chrétiens d’Espagne et le royaume islamique de Grenade. À l’instar de l’Andorre, ces « marches » développèrent des formes institutionnelles et juridiques particulières, dont nous serons probablement à nouveau témoins au cours du prochain millénaire.

En raison de la situation concurrentielle à laquelle étaient confrontées ces deux autorités, chacune étant faible, les dirigeants sollicitaient parfois des volontaires parmi leurs sujets pour s’installer dans ces « marches » afin d’étendre leur pouvoir. Presque systématiquement, on persuadait les sujets de s’y établir en leur accordant une exemption fiscale. Étant donné les marges délicates sur lesquelles reposait cette concurrence, si l’une des autorités tentait de lever un impôt, elle compliquait la vie de ses partisans et leur donnait par la même occasion une raison de rejoindre le camp adverse. Ainsi, les habitants d’une « marche » pouvaient généralement choisir à quelles lois ils obéiraient. Ce choix reposait sur la faiblesse des autorités concurrentes, plutôt que sur un quelconque idéal idéologique.

Cependant, des difficultés pratiques se posaient et devaient être traitées. Dans le système féodal, les propriétaires terriens possédant des biens de part et d’autre d’une frontière nominale étaient confrontés à un sérieux conflit d’obligations. Ainsi, un seigneur installé à la frontière entre l’Écosse et l’Angleterre, et qui détenait des terres dans les deux royaumes, pouvait être, en théorie, redevable d’un service militaire dans chaque camp en cas de guerre. Pour résoudre cette contradiction, presque tous les échelons de la hiérarchie féodale pouvaient choisir les lois auxquelles ils se soumettraient par un processus juridique appelé « avowal ».

Les technologies de l’information créeront des possibilités similaires de choix concurrentiels quant au lieu où seront domiciliées les activités économiques, mais avec des différences notables. D’une part, contrairement aux sociétés frontalières médiévales, le cyberespace deviendra probablement, à terme, le plus prospère des domaines économiques. Il s’agira donc d’une frontière qui se développera plutôt que de reculer. Peu de gens, dans les régions centrales de la société médiévale, auraient souhaité s’aventurer dans les marches sans incitation majeure, souvent d’ordre religieux, car ces zones étaient à la fois violentes et pauvres. Elles n’agissaient donc pas comme aimant pour capter des ressources hors de la sphère d’influence des autorités. Au contraire, le cyberespace le fera.

Ensuite, la nouvelle frontière ne sera pas un duopole, qui favoriserait une collusion entre deux autorités pour se partager la frontière. Pendant la période médiévale, de tels compromis se révélaient rarement efficaces pour deux raisons : on observait souvent de forts écarts culturels entre les autorités rivales ; et, surtout, elles ne disposaient pas de la capacité militaire suffisante pour faire appliquer de force tout accord négocié. Durant l’ère de l’État-nation, lorsque les autorités nationales ont acquis la puissance militaire nécessaire pour imposer leurs solutions, la plupart des régions de marche et des frontières floues ont disparu. C’est alors que s’est imposée la délimitation rigide des frontières. Cette solution demeure stable si deux pouvoirs violents peuvent envisager de se partager des territoires contigus. Toutefois, la concurrence pour domicilier les transactions de la cyberéconomie ne se jouera pas entre deux autorités, mais entre des centaines d’autorités dans le monde entier. Créer un cartel efficace pour maintenir des taux d’imposition élevés sera quasiment impossible pour les États territoriaux, pour la même raison qui fait échouer toute entente visant à imposer des prix monopolistiques sur un marché comptant des centaines de concurrents.

À titre d’illustration, considérons la décision des Seychelles, un minuscule pays de l’océan Indien, d’adopter une nouvelle loi sur l’investissement que les autorités américaines ont qualifiée de « Bienvenue aux criminels ». Selon ladite loi, quiconque investit 10 millions de dollars aux Seychelles sera non seulement protégé de l’extradition, mais recevra en plus un passeport diplomatique. Contrairement aux affirmations du gouvernement américain, les premiers bénéficiaires visés ne sont pas des trafiquants de drogue (qui, en général, sont sous la protection de gouvernements bien plus puissants), mais plutôt des entrepreneurs indépendants devenus « politiquement incorrects ». Le premier bénéficiaire potentiel de la loi seychelloise est un Sud-Africain blanc qui s’est enrichi en contournant les sanctions économiques contre l’ancien régime d’apartheid. Maintenant, il fait face au risque de représailles économiques de la part du nouveau gouvernement sud-africain et il est prêt à payer aux Seychelles cette protection.[^238]:

Quelles que soient les circonstances de chaque affaire, cet exemple prouve que les tentatives gouvernementales de préserver un cartel de « protection » sur le terrain sont vouées à l’échec.

Contrairement à la frontière médiévale, où la concurrence n’opposait que deux autorités, la frontière du cybercommerce se jouera entre des centaines de juridictions, dont le nombre pourrait rapidement atteindre des milliers.

À l’ère de la société virtuelle, les individus choisiront de domicilier leurs activités génératrices de revenus dans la juridiction leur offrant le meilleur service au coût le plus bas. En d’autres termes, la souveraineté sera commercialisée. À la différence des sociétés médiévales frontalières, la plupart du temps pauvres et violentes, le cyberespace ne sera ni l’un ni l’autre. La concurrence à laquelle les technologies de l’information contraignent les gouvernements n’est pas de nature militaire, mais se joue sur la qualité et le prix d’un service économique : une réelle protection. En clair, les gouvernements devront offrir aux « clients » ce qu’ils désirent.

### L’utilité décroissante de la violence

Cela ne signifie bien sûr pas que les gouvernements renonceront à l’usage de la violence. Bien au contraire. Nous avançons plutôt que la violence perd beaucoup de son influence. Il est possible que certains gouvernements réagissent en intensifiant leur recours à la violence au niveau local, pour compenser la baisse de son poids à l’échelle mondiale. Quoi qu’ils fassent, les gouvernements seront de toute façon incapables d’imposer la violence dans le cyberespace, comme ils l’ont fait sur les territoires dont ils détenaient le monopole au monde moderne. Peu importe le nombre de gouvernements qui souhaitent pénétrer le cyberespace, ils n’y seront ni plus aptes ni plus puissants que n’importe quel autre acteur.

Paradoxalement, les tentatives des États-nations de mener des « guerres de l’information » pour dominer ou restreindre l’accès au cyberespace ne feraient sans doute qu’accélérer leur propre déclin. La tendance à la dévolution des grands systèmes est déjà puissante, en raison de la réduction des économies d’échelle et de la hausse des coûts liés au maintien de groupes sociaux fragmentés. L’ironie de ces guerres de l’information est qu’elles risqueraient d’infliger davantage de dégâts aux systèmes fragiles hérités de l’ère industrielle qu’à l’économie de l’information en cours d’émergence.

Tant que les technologies de l’information essentielles continueront de fonctionner, le cybercommerce pourra se poursuivre en parallèle des conflits de la guerre de l’information, chose inconcevable dans une guerre territoriale. Il serait impossible d’imaginer des millions de transactions commerciales se déroulant sur un champ de bataille au XXe siècle. Pourtant, les guerres virtuelles ne suffiront pas à épuiser la capacité du cyberespace à héberger de multiples activités simultanées. Et étant donné que la réalité virtuelle n’existe pas réellement, il n’y a guère de risque dû à la proximité, ni de menace de retombées virtuelles destructrices.

### Vulnérabilité des systèmes de grande envergure

Les risques de la guerre de l’information concernent essentiellement les systèmes industriels de grande taille, axés sur un commandement et un contrôle centralisés. Les autorités militaires des États-Unis et d’autres grandes puissances craignent et prévoient des actes de sabotage informatiques susceptibles de perturber gravement ces vastes infrastructures. Une guerre informatique pourrait, par exemple, provoquer la fermeture d’un central téléphonique, perturber le contrôle du trafic aérien ou saboter le fonctionnement d’une station de pompage approvisionnant une ville en eau. Un virus programmé pourrait même entraîner l’arrêt de générateurs conventionnels ou nucléaires, interrompant l’approvisionnement électrique sur certains réseaux. Des « bombes logiques » pourraient anéantir un grand volume de données, et les renseignements les plus sensibles se trouvent souvent dans des systèmes centraux de contrôle, qui demeurent vulnérables et issus de l’ère industrielle. Sans aller jusqu’à la destruction massive et totale de toutes les technologies de l’information – ce qui mettrait littéralement l’économie mondiale à l’arrêt –, le cybercommerce et la réalité virtuelle resteront hors de portée de tout gouvernement cherchant à les étouffer ou à en monopoliser l’usage.

Même l’un des inconvénients majeurs de la technologie de l’information – la vulnérabilité apparente des systèmes de stockage de données face à la détérioration et à la destruction – a été largement résolu grâce à une nouvelle technique d’archivage. Un système appelé « High-Density read-only Memory » (HD-ROM) emploie un usinage ionique semblable à ceux des systèmes de fabrication assistés par ordinateur pour créer des archives sous vide. La capacité de stockage atteint désormais 25 000 mégaoctets par pouce carré. Contrairement aux systèmes antérieurs, qui se dégradaient rapidement et étaient fragiles en cas de choc, les données stockées en HD-ROM promettent de durer très longtemps. L’un des développeurs de la HD-ROM, Bruce Lamartine, déclare : « C’est pratiquement imperméable au temps, aux chocs thermiques et mécaniques, ou encore aux champs électromagnétiques qui sont pourtant si néfastes pour les autres supports de stockage. »[^239]: Même une explosion d’origine nucléaire, déclenchée par des terroristes, ne détruirait pas nécessairement les informations vitales, comme les codes monétaires numériques indispensables au bon fonctionnement d’une cyberéconomie.

> « Les armées modernes dépendent tellement de l’information qu’il est possible de les aveugler et de les rendre sourdes afin de remporter la victoire sans combattre au sens conventionnel. »[^240]: – COL. ALAN CAMPEN, U.S.A.F. (retraité)

## SUPERPUISSANCES DE LA GUERRE VIRTUELLE

Les suppositions associées à l’État-nation en guerre perdront de plus en plus de leur pertinence « mégapolitique » alors que l’information joue un rôle croissant dans les conflits armés. N’ayant aucune existence physique, le cyberespace n’est pas un domaine où les ordres de grandeur, tels que nous les connaissons dans le monde tangible, exercent une importance décisive. Peu importe combien de programmeurs ont travaillé à définir une suite de commandes : seul compte le bon fonctionnement du programme. L’« individu souverain » peut réellement valoir autant dans le cyberespace qu’un État-nation siégeant à l’ONU, doté de son propre drapeau et d’une armée déployée sur le terrain. D’un strict point de vue économique, certains « individus souverains » possèdent déjà des revenus mobilisables qui se chiffrent en centaines de millions de dollars annuels, ce qui dépasse le pouvoir de dépense discrétionnaire de certains États-nations en faillite. Mais ce n’est pas tout. Concernant une guerre virtuelle menée par manipulation de l’information, certains individus peuvent occuper une place au moins aussi prépondérante que beaucoup de pays à travers le monde. Un génie excentrique, épaulé par des « serviteurs » numériques, pourrait théoriquement exercer la même influence qu’un État-nation dans une guerre informatique. C’est sans doute le cas de Bill Gates.

À cet égard, l’« ère de l’individu souverain » n’est pas qu’un simple slogan. Un hacker ou un petit groupe de mathématiciens (sans parler d’une entreprise comme Microsoft, ou encore n’importe quelle société de logiciels) pourrait en principe réaliser tout ou une partie des opérations que la « Cyber War Task Force » du Pentagone envisage. Des centaines de firmes de la Silicon Valley et d’ailleurs possèdent déjà une plus grande capacité de guerre informatique que 90 % des États-nations existants.

L’idée selon laquelle les gouvernements continueront à monopoliser l’organisation de la vie « terrestre » alors même que s’ouvriront de toutes parts des voies alternatives de protection, relève de l’anachronisme. Le scénario le plus probable est que les États-nations devront se réorganiser pour réduire leur vulnérabilité face aux virus informatiques, bombes logiques, câbles infectés, ou programmes à « portes dérobées » susceptibles d’être surveillés par la National Security Agency américaine ou par n’importe quel adolescent hacker.

La logique « mégapolitique » du cyberespace donne à penser que les systèmes de commandement et contrôle centralisés, qui dominent actuellement les grandes infrastructures mondiales, devront être remplacés par des modèles de sécurité multicentriques, dotés de capacités distribuées, de sorte qu’un virus informatique ne puisse les paralyser ou les détourner aisément. De nouveaux types de logiciels, dits « systèmes ouverts agoriques », viendront remplacer les logiciels de commandement et contrôle hérités de l’ère industrielle. Les anciens logiciels répartissaient la capacité de calcul selon des priorités rigides, un peu à la façon des planificateurs centraux de Gosplan, dans l’ex-Union soviétique, qui répartissaient les marchandises dans les wagons selon des règles inflexibles. Les nouveaux systèmes, eux, sont régis par des algorithmes reproduisant les mécanismes de marché : ils allouent les ressources de manière plus efficace par un processus d’enchère interne qui imite la concurrence neuronale du cerveau. Au lieu de gigantesques monopoles informatiques pilotant les fonctions de commandement et de contrôle, ces systèmes seront décentralisés dans le nouveau millénaire.

Nulle démonstration n’illustre mieux la robustesse d’un réseau distribué en comparaison d’un système centralisé que l’exemple rapporté par Digital Equipment dans son laboratoire de recherche de Palo Alto. Un ingénieur a ouvert la porte d’un placard abritant le réseau informatique interne de la société. Selon Kevin Kelly, l’ingénieur a « brutalement arraché un câble de ses entrailles. Immédiatement, le réseau s’est réorganisé autour de cette défaillance et a continué à fonctionner sans la moindre interruption. »[^241]:

L’ère de l’information non seulement permettra une concurrence sans anarchie dans le cyberespace, mais aboutira également à la refonte des systèmes majeurs hérités de l’industrie. Une telle reconfiguration est indispensable pour les rendre moins vulnérables aux actes malveillants, qui peuvent surgir de n’importe où et de n’importe qui. De la même manière que l’ère industrielle a mené une refonte d’organismes légués par la période médiévale (comme les écoles et les universités), il est probable que les institutions de l’ère industrielle s’adaptent, sous une forme réduite, en phase avec la logique de la microtechnologie.

La nécessité de se prémunir contre les bandits sur l’« autoroute de l’information » imposera une large adoption des algorithmes de cryptage à clé publique et clé privée. Ceux-ci permettent déjà à un simple utilisateur d’ordinateur personnel de chiffrer un message avec plus de sûreté que le Pentagone n’aurait pu protéger ses codes de lancement il y a seulement une génération. Ces systèmes puissants et inviolables de cryptage deviendront indispensables pour garantir la sécurité des transactions financières face aux pirates et aux voleurs.

Une autre raison justifie leur usage : les institutions financières et les banques centrales s’orienteront vers des algorithmes de cryptage inviolables le jour où elles prendront conscience que le gouvernement américain (et peut-être pas seulement lui) dispose des moyens de pénétrer les logiciels et systèmes informatiques bancaires actuels, au point de ruiner un pays ou de vider le compte bancaire de n’importe quel individu, où qu’il soit. Rien ne justifie qu’un pays ou un particulier laissent à la merci de la NSA ou d’agences semblables, licites ou illicites, leurs placements et transactions financières.

Des algorithmes de chiffrement imperméables aux gouvernements ne sont pas un simple fantasme. Ils sont d’ores et déjà disponibles sur Internet en tant que progiciels gratuits. Lorsque les constellations de satellites à orbite basse fonctionneront pleinement, chaque individu équipé d’un ordinateur personnel poussé, muni d’une antenne à peine plus grande qu’un téléphone portable, pourra communiquer partout sur la planète sans même passer par le réseau téléphonique. Pour un gouvernement, il sera donc tout aussi impossible de monopoliser le cyberespace – un espace sans existence physique – qu’il l’aurait été pour un chevalier médiéval de contrôler des échanges industriels à califourchon sur son destrier.

### La protection dans l’ombre

Les sociétés de l’information mettront d’immenses ressources hors de portée du pillage. À mesure que le cyberespace hébergera davantage de transactions financières et commerciales, les ressources qu’il mobilise seront plus ou moins immunisées contre l’extorsion et le vol. Les prédateurs ne pourront donc pas mettre la main sur une masse de richesses comparable à celle qu’ils sont parvenus à capter au cours du XXe siècle.

Ainsi, protéger une grande partie de la richesse mondiale par le biais de l’État deviendra inutile. Les gouvernements ne seront pas mieux placés que n’importe qui pour assurer la protection d’un compte bancaire dans le cyberespace. Dès lors que l’implication de l’État se révélera moins nécessaire, son prix relatif devrait baisser, pour cette raison seule. Et il y en a d’autres.

Avec une part toujours plus importante de transactions financières se déroulant dans le cyberespace durant le nouveau millénaire, chacun aura le choix de la juridiction où stocker ses avoirs. Une concurrence féroce naîtra alors quant à la tarification des services étatiques (les impôts). Il s’agit là d’un fait révolutionnaire. Comme l’a souligné George Melloan dans le Wall Street Journal, l’une des rares institutions à avoir échappé à la mondialisation de la concurrence est l’État-providence. « Une étude menée par des chercheurs de la Wharton School et de l’Australian National University a analysé les forces qui pèsent sur les transferts de revenus. Geoffrey Garrett et Deborah Mitchell ont conclu qu’“il n’existe quasiment aucune preuve selon laquelle l’intégration accrue aux marchés internationaux exercerait une pression à la baisse sur leurs principaux programmes sociaux”. Au contraire, écrivent-ils, “les gouvernements ont pour la plupart réagi à l’intensification de l’intégration internationale en augmentant les transferts sociaux.” »[^242] L’avènement de la cyberéconomie mettra enfin à nu l’État-providence, le confrontant à une véritable compétition. Cela transformera la nature des souverainetés et modifiera les économies, car l’équilibre entre protection et extorsion penchera plus fortement que jamais du côté de la protection

[^187]: Neil Munro, « The Pentagon’s New Nightmare: An Electronic Pearl Harbor », Washington Post, 16 juillet 1995, p. C3.  

[^188]: Thomas Hobbes, *Leviathan*, chap. 13 « De la condition naturelle de l’homme… ».  

[^189]: Thomas Schelling, *Arms and Influence*, New Haven : Yale University Press, 1966.  

[^190]: Kevin Kelly, *Out of Control: The New Biology of Machines, Social Systems, and the Economic World*, Reading (Mass.) : Addison–Wesley, 1995, p. 45-46.  

[^191]: Ibid., p. 2-4.  

[^192]: Ibid., p. 4.  

[^193]: Heinz Pagels, *The Dreams of Reason*, New York : Bantam Books, 1989, cité dans Roger Lewin, *Complexity: Life at the Edge of Chaos*, New York : Macmillan, 1992, p. 10.  

[^194]: Lane, « Economic Consequences of Organized Violence », op. cit., p. 402.  

[^195]: Frederic C. Lane, « The Economic Meaning of War and Protection », in *Venice and History: The Collected Papers of Frederic C. Lane*, Baltimore: The Johns Hopkins Press, 1966, p. 383-384.  

[^196]: Shi Mai’an et Lao Guanzhong, *Outlaws of the Marsh*, trad. Sidney Shapiro, Bloomington : Indiana University Press, 1981, p. 12.  

[^197]: George F. Will, « Farewell to Welfare States », Washington Post, 17 décembre 1995, p. C7.  

[^198]: Robert S. McElvaine, *The Great Depression: America, 1929–1941*, New York : Times Books, 1984, p. 292.  

[^199]: Ibid., p. 293.  

[^200]: Adam Smith, *The Wealth of Nations*, p. 75.  

[^201]: Ibid., p. 76.  

[^202]: Ibid.  

[^203]: En Argentine, le premier syndicat fut celui des chemins de fer en 1887 (voir Carmelo Mesa-Lago, *Social Security in Latin America: Pressure Groups, Stratification, and Inequality*, Pittsburgh : University of Pittsburgh Press, 1978, p. 161).  

[^204]: Pour plus de détails sur la construction du canal Cheseapeake & Ohio, voir Robert J. Brugger, *Maryland: A Middle Temperament 1634–1980*, Baltimore : The Johns Hopkins Press, 1990, p. 202-203.  

[^205]: Irving J. Sloan, *Our Violent Past: An American Chronicle*, New York : Random House, 1970, p. 177.  

[^206]: Ibid., et Brugger, op. cit., p. 341-344.  

[^207]: Sloan, op. cit., p. 202. Voir aussi S. S. Boynton, « Miners’ Vengeance », *Overland Monthly*, vol. 22 (1893), p. 303-307.  

[^208]: Benjamin Schwartz, « American Inequality: Its History and Scary Future », New York Times, 19 décembre 1995, p. A25.  

[^209]: McElvaine, op. cit., p. 293.  

[^210]: Ibid.  

[^211]: Ibid.  

[^212]: Henry C. Simons, « Some Reflections on Syndicalism », *Journal of Political Economy*, mars 1944, p. 22.  

[^213]: Kelly, op. cit., p. 191-192.  

[^214]: Gayle Ni. Hanson, « A Riveting Account of ‘Life’ in Postmodernist Cyberspace », Washington Times, 24 décembre 1995, p. B7.  

[^215]: Pour une introduction concise de la théorie de l’anarchie dans la science économique, voir Gordon Tullock (dir.), *Explorations in the Theory of Anarchy*, Blacksburg (VA) : Virginia Polytechnic Institute and State University, 1972. Voir aussi Murray N. Rothbard, *Power and Market: Government and the Economy*, Menlo Park (CA), 1970 ; et Robert Nozick, *Anarchy, State, and Utopia*, New York : Basic Books, 1974.  

[^216]: Voir Pierre Clastres, *Society Against the State: The Leader as Servant and the Humane Uses of Power Among the Indians of the Americas*, New York : Urizen Books, 1977 ; et Jones, op. cit.  

[^217]: Lane, « Economic Consequences of Organized Violence », op. cit., p. 403.  

[^218]: Charles Tilly, « War Making and State Making as Organized Crime », in Peter B. Evans, Dietrich Rueschemeyer, et Theda Skocpol, *Bringing the State Back In*, Cambridge : Cambridge University Press, 1985, p. 169.  

[^219]: Ibid.  

[^220]: Lane, « Economic Consequences of Organized Violence », op. cit., p. 402.  

[^221]: David J. Elkins, *Beyond Sovereignty: Territory and Political Economy in the Twenty-First Century*, Toronto : University of Toronto Press, 1995, p. 13-14.  

[^222]: Ibid., p. 29.  

[^223]: Jim Taylor et Watts Wacker, *The 500-Year Delta: What Happens After What Comes Next*, New York : HarperCollins, 1997, p. 40.  

[^224]: Ibid., p. 67.  

[^225]: Ibid., p. 41-42.  

[^226]: George Gilder, « Fiber Keeps Its Promise: Get Ready. Bandwidth Will Triple Each Year for the Next 25, Creating Trillions in New Wealth. », *Forbes ASAP*, 7 avril 1997.  

[^227]: Neal Stephenson, *Snow Crash*, New York : Bantam Books, 1993.  

[^228]: Keith B. Richburg, « Two Years After U.S. Landing in Somalia, It’s Back to Chaos », Washington Post, 4 décembre 1994, p. A1.  

[^229]: Cité dans Tilly, *Coercion, Capital and European States*, op. cit., p. 85.  

[^230]: Lane, « Economic Consequences of Organized Violence », op. cit., p. 411.  

[^231]: Ibid.  

[^232]: Ibid.  

[^233]: Ibid., p. 412.  

[^234]: Ibid., p. 403.  

[^235]: Ibid., p. 404.  

[^236]: Esther Dyson, *Release 2.1: A Design for Living in the Digital Age*, New York : Broadway Books, 1998, p. 131.  

[^237]: Rees Davies, « Frontier Arrangements in Fragmented Societies: Ireland and Wales », in Robert Bartlett et Angus MacKay (dir.), *Medieval Frontier Societies*, Oxford : Oxford University Press, 1992, p. 80.  

[^238]: Thomas W. Lippman, « Seychelles Offers Investors Safe Haven for $10 Million », Washington Post, 31 décembre 1995, p. A27.  

[^239]: Voir « ROM of Ages », *Wired*, janvier 1996, p. 52.  

[^240]: Cité dans James Adams, « Dawn of the Cyber Soldiers », *The Sunday Times* (Londres), 15 octobre 1995, p. 3-5.  

[^241]: Kelly, op. cit., p. 19.  

[^242]: George Melloan, « Welfare State Reform Is Mostly Mythological », *The Wall Street Journal*, 14 octobre 1996, p. A19.  

[^243]: Voir le chapitre 8 de *The Great Reckoning* : « Linear Expectations in a Nonlinear World: How the Telescope Led Us to Compute; how the Computer Can Help Us to See. »  

[^244]: Notons que les quatre stades de Lane sur la concurrence et le monopole de la violence ne coïncident pas avec les quatre grands systèmes économiques que nous décrivons (cueillette, agriculture, industrialisation, information).