# TRANSCENDER LA LOCALISATION

:::{.content-hidden when-format=latex}
*The Emergence of the Cybereconomy*  
:::

> « Le véritable enjeu, c’est le contrôle. Internet est trop étendu pour qu’un seul gouvernement puisse facilement le dominer. En créant une zone économique mondiale harmonieuse, anti-souveraine et impossible à réglementer, Internet remet en question la notion même d’État-nation. »[^245] — JOHN PERRY BARLOW

L’autoroute de l’information est devenue l’une des métaphores les plus familières des débuts de l’ère numérique. Ce qui frappe, ce n’est pas seulement sa popularité, mais aussi l’erreur de compréhension qu’elle révèle à propos de la cyberéconomie. Une autoroute, après tout, est une version industrielle d’un sentier, un réseau pour le transport physique de personnes et de biens. Or, l’économie de l’information n’est pas comme une autoroute, un chemin de fer ou un pipeline. Elle ne « transporte » pas l’information d’un point à un autre comme la Transcanadienne transporte des camions lourds de l’Alberta au Nouveau-Brunswick. Ce que le monde appelle « l’Autoroute de l’information » n’est pas seulement un lien de transit. C’est la destination.

Le cyberespace transcende la notion de lieu. Il implique rien de moins que le partage instantané de données partout et nulle part à la fois. La nouvelle économie de l’information repose sur l’interconnexion reliant et reliant à nouveau des millions d’utilisateurs de millions d’ordinateurs. Son essence réside dans les possibilités inédites qu’offrent ces connexions. Comme l’a formulé John Perry Barlow : « Ce que le Net propose, c’est la promesse d’un nouvel espace social, à la fois mondial et anti-souverain, où chacun, où qu’il soit, peut exprimer à l’humanité entière ses croyances sans crainte. Ces nouveaux médias laissent entrevoir la liberté intellectuelle et économique susceptible de mettre à bas tous les pouvoirs autoritaires de la planète. »[^246]:

Le cyberespace, à l’instar du royaume imaginaire des dieux d’Homère, forme un univers séparé du monde terrestre familier des fermes et des usines. Ses conséquences, en revanche, ne seront pas imaginaires, mais bien réelles. Dans une mesure bien plus grande qu’on ne l’imagine, le partage instantané de l’information agira à la manière d’un solvant qui dissoudra de grandes institutions. Il ne fera pas qu’altérer la logique de la violence, comme nous l’avons déjà exploré ; il modifiera radicalement les coûts de l’information et de la transaction, qui déterminent la structuration des entreprises et le fonctionnement de l’économie. Nous anticipons que la micro-informatique transformera l’organisation économique du monde.

> « Aujourd’hui, il est possible, plus qu’à n’importe quelle autre époque de l’histoire, pour une entreprise de s’implanter n’importe où, de puiser ses ressources à n’importe quel endroit, pour fabriquer un produit qui peut être vendu partout. » — MILTON FRIEDMAN

## LA TYRANNIE DU LIEU

Le fait que les premiers efforts de l’ère industrielle pour imaginer l’économie de l’information la décrivent sous forme d’un gigantesque projet de travaux publics illustre à quel point notre pensée est enracinée dans les paradigmes du passé. C’est un peu comme entendre des fermiers de la fin du XVIIIᵉ siècle décrire une usine comme « une ferme couverte d’un toit ». Mais la métaphore de « l’autoroute » en dit plus que cela. Elle révèle aussi dans quelle mesure nous sommes prisonniers de la tyrannie du lieu. Même lorsque la technologie nous permet de transcender la localisation, l’instrument de notre libération est baptisé d’un surnom qui évoque un itinéraire allant d’un endroit à un autre. À l’image des saumons soumis à leur instinct de retour au nid, notre conscience est encore profondément marquée par la notion de localité.

De tout temps jusqu’à aujourd’hui, les économies ont été ancrées à une zone géographique. La plupart des personnes ayant vécu avant le XXᵉ siècle passaient leurs journées comme en résidence surveillée de facto, s’aventurant rarement à plus de quelques jours de marche de leur lieu de naissance. Un voyage de grande distance relevait du périple s’étalant sur plusieurs générations. Seule une crise ponctuelle — guerre, épidémie, changement climatique défavorable — suscitait parfois une migration de grande ampleur. Il fallait rien de moins qu’un événement spectaculaire et pressant pour inciter les individus à regrouper leurs biens et partir en quête d’une vie meilleure.

Jusqu’à récemment, ceux qui cherchaient leur chance au-delà de leur localité étaient souvent devenus célèbres. Ainsi, Marco Polo reste connu pour avoir traversé le continent eurasien afin de visiter la cour du Grand Khan. Il était l’exception à son époque. Peu d’autres récits de voyage, antérieurs à l’ère moderne, nous sont parvenus. Parmi les plus largement lus, *Les Voyages de Mandeville*, rédigés en français en 1357, se distingue par le fait que son auteur ne quitta probablement jamais l’Europe. Mandeville relate des détails délectables et souvent fantaisistes sur la vie dans le monde entier, dont l’idée que de nombreux Éthiopiens ne posséderaient qu’un seul pied : « [P]ied si grand qu’il ombrage tout le corps contre le soleil quand ils veulent s’allonger et se reposer. »[^247]: De toute évidence, parmi les contemporains de Mandeville qui lisaient son récit à succès, peu étaient susceptibles de savoir que cet « Éthiopien pied-géant » n’existait pas.

Ce n’est qu’avec les voyages d’exploration de la toute fin du XVe siècle que commencèrent les contacts soutenus entre continents. Des capitaines intrépides, comme Christophe Colomb ou Vasco de Gama, qui partirent conquérir le commerce des épices, furent assez hors normes pour être retenus en mémoire dans pratiquement tous les foyers lettrés pendant cinq siècles.

Depuis l’avènement de l’agriculture jusqu’aux générations récentes, l’immobilité a caractérisé la vie de la plupart. On l’oublie presque aujourd’hui, surtout dans les colonies d’installation européennes du « Nouveau Monde », où la mobilité est plus aisée et où chacun a tendance à envisager le monde sous l’angle d’un immigrant. Dès l’école primaire, en Amérique du Nord, on enseigne que les colons sont venus d’Europe pour rechercher la liberté et de meilleures opportunités — c’est vrai. On omet cependant le plus souvent de préciser à quel point la plupart d’entre eux répugnaient à effectuer ce voyage, même face à la misère dans leur pays d’origine. Ceux qui ont finalement émigré ont dû vivre des épreuves inimaginables selon les critères actuels pour s’installer. Seuls les plus entreprenants ou les plus désespérés parmi les miséreux ont franchi le pas. Au milieu du XVIIᵉ siècle, les détenus incarcérés à Bridewell, la sinistre maison de correction de Londres, se révoltèrent pour montrer « qu’ils ne voulaient pas être envoyés en Virginie ».[^248]: En 1720, des émeutes éclatèrent dans les rues de Paris afin de libérer mendiants, voleurs et meurtriers promis à la déportation en Louisiane.

### Des horizons limités

Les difficultés matérielles de communication et de transport, souvent aggravées par le manque généralisé de connaissances linguistiques, ont longtemps circonscrit les actions humaines à un horizon restreint et local. Aussi récemment qu’au début du XXᵉ siècle, il n’était pas rare de trouver des villages chinois, séparés de moins de huit kilomètres, s’exprimant dans des dialectes mutuellement inintelligibles, même le long du littoral. L’organisation locale de pratiquement toutes les économies imposait une sanction sous forme de marchés limités et d’opportunités perdues. Les facteurs de production se retrouvaient à des coûts élevés en raison d’une concurrence étroite. L’accès aux compétences spécialisées était minime. Avec des revenus si bas qu’ils frôlaient la misère, et sans accès à un capital extérieur ni à des marchés d’assurance efficaces, les petits agriculteurs de vastes pans du globe se retrouvaient prisonniers de la pauvreté. Nous avons déjà étudié certaines difficultés auxquelles les paysans faisaient face dans un contexte de vie villageoise fermée. Même de nos jours, au moment où nous écrivons ces lignes, au moins un milliard de personnes, principalement en Asie et en Afrique, luttent pour survivre avec moins d’un dollar par jour.

## « TOUTE POLITIQUE EST LOCALE »

Bien plus qu’on ne l’admet souvent, l’immobilité des personnes et de leurs biens a façonné notre vision du monde. Ceux-là mêmes qui paraissent disposés à reconnaître que la planète est petite à la fin du XXᵉ siècle raisonnent encore sous l’emprise de notions dictées par la politique industrielle traditionnelle. C’est ce qu’illustre un slogan devenu populaire chez les écologistes dans les années 1980 : « Penser globalement, agir localement. » C’est une injonction reflétant la logique du politique, une logique depuis toujours fondée sur des avantages de pouvoir à l’échelle locale.

L’habitude de penser local est imposée par la mégapolitique de toutes les sociétés passées. Les caractéristiques topographiques (obstacles ou facilitateurs de l’exercice de la force) sont ancrées dans le local. Chaque fleuve, chaque montagne, chaque île est local. Le climat est local. La température, les précipitations et les conditions de croissance varient à mesure qu’on gravit ou franchit une montagne. Tout microbe se propage quelque part, et pas ailleurs.

Il n’y a donc rien d’étonnant à ce que la tyrannie du lieu imprègne nos concepts d’organisation et de fonctionnement de la société. Les avantages en matière de puissance, grâce auxquels un groupe ou un autre pouvait détenir un monopole local de la violence, ont jusqu’ici toujours pris naissance quelque part et se sont estompés à la périphérie mégapolitique, là où se dessinent les frontières. C’est pourquoi il n’a jamais existé de gouvernement mondial.

Si l’importance du lieu dans l’exercice du pouvoir a rarement été explicitement formulée, certains partisans du recours à la coercition pour redistribuer les fruits de l’action humaine ont commencé à pressentir le déclin de la prépondérance du lieu dès les années 1930. Leur vision considérait les transports modernes comme un clivage séparant l’espace social en deux : les très bien payés et les pauvres. Cette crainte s’illustre par John Dos Passos dans *The Big Money* : « Le vagabond est assis au bord de l’autoroute, épuisé, affamé. Dans le ciel, un avion transcontinental vole, rempli de cadres grassement rémunérés. La classe supérieure a pris l’air, la basse classe la route : il n’y a plus de lien entre elles, ce sont deux nations. »[^249]: En d’autres termes, l’amélioration des transports réduit l’emprise de l’extorsion simplement en multipliant les lieux potentiels où les personnes prospères peuvent s’établir. De fait, le vagabond sur la route n’avait guère de moyens d’extorquer de l’argent à ceux qui volaient au-dessus de sa tête. Les tendances qu’observait Dos Passos il y a soixante ans ne se sont que renforcées.

### Le transport de masse

En 1995, un million de personnes traversaient une frontière quelque part dans le monde chaque jour. C’est un changement stupéfiant par rapport au passé. Avant le XXᵉ siècle, les voyages étaient si rares que la plupart des frontières étaient simplement des zones frontalières, non des obstacles. Les passeports n’existaient pas. L’apparition de paquebots, de trains et d’autres transports améliorés a multiplié les déplacements. Mais ceux-ci se sont retrouvés davantage réglementés par les États, dont le pouvoir a augmenté grâce aux mêmes progrès en matière de transport et de communication qui rendaient les voyages civils moins coûteux et plus accessibles. L’avènement du cinéma et, surtout, de la télévision a également beaucoup contribué à ouvrir les horizons et à encourager voyages et immigration. Néanmoins, jusqu’à présent, les fondements de l’organisation sociale et économique sont restés ancrés dans la localité.

> « … pour éviter cette Perte de Courage à laquelle l’histoire impose une sanction si impitoyable. Nous devons avoir le courage de poursuivre toutes les extrapolations techniques jusqu’à leur conclusion logique. »[^250] — ARTHUR C. CLARKE

## L’ERREUR DES FAIBLES ATTENTES

L’ancrage géographique de l’imagination est si tenace que certains experts examinant Internet en 1995 ont conclu qu’il avait peu de potentiel commercial et à peine d’importance, hormis celle d’un canal électronique pour le bavardage ou la pornographie. Les nombreux sceptiques quant à la portée économique du cyberespace sont comme les colonels Blimp de l’ère de l’information. Leur sérénité n’a d’égale que celle de l’establishment britannique face à la décadence de l’Empire dans les années 1930. Dès que les élites se sentent menacées, leur première réaction est le déni. On voit cette posture dans l’espoir que l’Internet ne deviendra jamais important, un vœu parfois soutenu par des autorités qui devraient pourtant savoir. Nous avons évoqué plus haut le travail de David Kline et Daniel Burstein, *Road Warriors : Dreams and Nightmares Along the Information Highway*. Leur rejet du potentiel économique du Net confirme une fois de plus qu’une solide expertise technique ne s’accompagne pas nécessairement de la compréhension des conséquences de la technologie[^251].

Même les observateurs les mieux informés sur le plan technique, dans le passé, n’ont pas forcément saisi la portée des nouvelles technologies. Une commission parlementaire britannique, réunie en 1878 pour examiner l’ampoule à incandescence de Thomas Edison, la qualifia de « bonne assez pour nos amis d’outre-Atlantique, … mais indigne de l’attention d’hommes pratiques ou scientifiques ».[^252]: Thomas Edison lui-même, doté d’une grande vision, pensait que le phonographe qu’il venait d’inventer servirait principalement aux hommes d’affaires pour la dictée. Peu de temps avant que les frères Wright montrent que les avions pouvaient voler, l’éminent astronome américain Simon Newcomb avait prouvé de manière fort convaincante que le vol d’aéronefs plus lourds que l’air était impossible. Il conclut : « La démonstration qu’il est impossible de combiner, de manière pratique, des substances, des types de machines et des forces connues pour permettre à l’homme de voler sur de longues distances dans les airs semble à l’auteur aussi irréfutable que peut l’être la démonstration d’un fait physique. »[^253]: Peu après que les avions ont commencé à voler, un autre astronome célèbre, William H. Pickering, expliqua au public pourquoi le transport aérien commercial ne décollerait jamais : « L’imaginaire populaire se figure souvent d’immenses machines volantes traversant l’Atlantique, transportant un grand nombre de passagers comme nos grands bateaux à vapeur modernes. … [I]l est évident qu’avec nos dispositifs actuels, il est inutile d’espérer concurrencer en termes de vitesse nos locomotives ou nos automobiles. »[^254]: Nous avons déjà rappelé une autre prédiction largement erronée portant sur un nouveau procédé technique, à savoir la prévision faite au début du XXᵉ siècle par les fabricants de Mercedes soutenant qu’il ne pourrait jamais y avoir plus d’un million d’automobiles à l’échelle mondiale. Certes, ils en savaient plus que quiconque au sujet de l’automobile, mais on ne pouvait se tromper davantage quant à son impact sur la société.

Dans la droite ligne de ces incompréhensions passées, il n’est guère surprenant que nombre d’observateurs n’aient toujours pas conscience des répercussions majeures de la nouvelle technologie de l’information : le fait qu’elle transcende la tyrannie du lieu. Pour la première fois, elle crée un champ infini, non terrestre, où se déroulent les activités économiques. Elle offre la possibilité d’explorer de nouveaux espaces dans la cyberéconomie, de « penser globalement et agir globalement ». Nous allons expliquer pourquoi dans ce chapitre.

## AU-DELÀ DE LA LOCALISATION

Le traitement et l’utilisation de l’information supplantent progressivement (ou modifient en profondeur) les produits matériels comme principale source de profit. Cela revêt des conséquences considérables. La technologie de l’information déconnecte le potentiel de revenus de la résidence en un lieu géographique précis. Dans la mesure où la valeur des produits et services reposera de plus en plus sur l’ajout d’idées et de connaissances, la part de valeur ajoutée soumise à capture par les juridictions locales diminuera. Les idées peuvent naître n’importe où et voyager sur la planète à la vitesse de la lumière. Cela signifie inéluctablement que l’économie de l’information fonctionnera d’une manière très différente de l’économie de l’ère industrielle.

Les détracteurs avanceront que la liste des opérations possibles via Internet en 1996 a de quoi paraître banale. Après tout, il n’y a rien de révolutionnaire à lire un article de jardinage sur le Net ou à acheter un carton de vin à distance. Toutefois, il serait bien superficiel de juger le potentiel de la cyberéconomie sur la seule base de ses débuts, pas plus qu’on ne pouvait évaluer, vers 1900, la capacité de l’automobile à transformer la société en observant le monde de l’époque. Nous pensons que la cyberéconomie évoluera en plusieurs phases.

1. Les premières manifestations de l’ère de l’information se caractérisent par l’usage du Net à titre de média informatif pour faciliter des transactions somme toute ordinaires de l’ère industrielle. À ce stade, le Net n’est guère plus qu’un moyen exotique de diffuser des catalogues. Par exemple, Virtual Vineyards, un des premiers acteurs du e-commerce, vendait simplement du vin depuis une page du World Wide Web. De telles transactions ne remettent pas encore en cause directement les vieilles institutions. Elles emploient la monnaie de l’ère industrielle et s’opèrent dans le cadre d’une juridiction identifiable. Ces usages d’Internet ne provoquent pas d’impact mégapolitique majeur.

2. Une deuxième étape du commerce sur Internet emploie les technologies de l’information à des fins autrefois impossibles, comme la comptabilité à distance ou le diagnostic médical en ligne. Nous détaillons plus bas d’autres exemples de ces nouvelles applications, rendues possibles par l’informatique avancée. À la deuxième étape, le commerce sur le Net reste ancré dans l’ancienne structure institutionnelle, utilise les monnaies nationales et se soumet aux États-nations. Les vendeurs y gagnent des revenus, mais gèrent encore leurs bénéfices dans le cadre habituel. Les profits générés par les transactions effectuées sur Internet restent donc soumis à l’impôt.

3. Une étape plus avancée verra la transition vers le véritable cybercommerce. Non seulement les transactions se dérouleront en ligne, mais elles migreront en dehors du ressort des États-nations. Le règlement se fera en cybermonnaie. Les bénéfices iront sur des comptes bancaires en ligne, situés dans des cyberbanques. Les investissements transiteront par des cybercourtiers. Nombre de transactions échapperont à l’impôt. À ce stade, le cybercommerce commencera à avoir des répercussions mégapolitiques importantes, du type de celles que nous avons décrites. Le pouvoir des gouvernements sur les secteurs économiques traditionnels en sera transformé par la nouvelle logique du Net. Le pouvoir extraterritorial de réglementation s’effondrera. Le concept de juridiction se délitera, la structure des entreprises se modifiera, ainsi que la nature de l’emploi et du travail. Ce schéma des phases de la révolution de l’information n’est qu’une ébauche de ce qui s’annonce comme la transformation économique la plus radicale des temps à venir.

## LA MONDIALISATION DU COMMERCE

Dans l’ère de l’information, la plupart des avantages actuels liés aux juridictions vont s’effriter rapidement sous l’effet des progrès technologiques. De nouveaux types d’avantages émergeront. La chute spectaculaire des coûts de communication a déjà amoindri la nécessité de la proximité. En 1946, un investisseur basé à Londres pouvait, en théorie, passer un ordre auprès d’un courtier new-yorkais, mais seules les grosses opérations justifiaient un tel dispositif : trois minutes de conversation téléphonique entre New York et Londres coûtaient 650 $. Aujourd’hui, parler trois minutes entre New York et Londres revient à 0,91 $. Le coût d’un appel téléphonique intercontinental a donc chuté de plus de 99 % en un demi-siècle.

### La convergence des communications

Bientôt, la différence entre un appel intercontinental et un appel local risque d’être négligeable. De même, les différences entre votre téléphone, votre ordinateur et votre télévision pourraient devenir minimes. Tous seront des dispositifs de communication interactifs, qu’on distinguera surtout par leur ergonomie plutôt que par leur fonction. Vous pourrez converser via Internet grâce au micro et aux haut-parleurs de votre ordinateur. Ou bien regarder un film. Vous pourrez répondre à votre télévision et transmettre une grande quantité de données via le réseau que fournissent les services de télévision de divertissement. À mesure que s’effacent les clivages hérités de l’ère industrielle entre les différents modes de communication et que les coûts dégringolent, de plus en plus de services vous seront facturés en fonction du temps d’utilisation plutôt que de la destination des messages. Discuter ou transférer des données à l’autre bout du monde coûtera guère plus cher qu’un appel local n’était facturé dans la plupart des juridictions en 1985.

### L’Internet sans fil

Des satellites en orbite basse, parmi d’autres solutions de transmission sans fil, diffuseront des données aller-retour directement vers le récepteur que vous avez dans la poche, votre ordinateur portable ou votre station de travail, sans passer par l’opérateur téléphonique local ou le réseau de câbles TV. En bref, l’Internet sera libéré des fils. Les premiers pas dans cette direction seront forcément hésitants, car le débit des premières liaisons sans fil sera relativement lent et les signaux en provenance d’appareils mobiles à batterie, parfois en déplacement, seront difficiles à « entendre ». Néanmoins, on s’attaquera à ces problèmes techniques pour les résoudre.

### L’entreprise sans frontières

L’augmentation continue de la puissance de calcul permettra d’optimiser la compression des données, accélérant encore la circulation de l’information. La généralisation des algorithmes de chiffrement reposant sur la cryptographie à clé publique/clé privée laissera la possibilité aux fournisseurs, par exemple des systèmes satellite, d’intégrer directement la facturation au service, réduisant les coûts. Parallèlement, les vendeurs pourront débiter instantanément les comptes de leurs clients installés sur des ordinateurs personnels, un peu à la manière dont France Télécom débite les « cartes intelligentes » des cabines téléphoniques à Paris.

### Le téléphone devient une banque

La différence, c’est que, dans un avenir très proche, il vous sera possible d’alimenter ces comptes en y versant le produit de toutes sortes de transactions, tout en emportant partout votre « cabine téléphonique ». Votre ordinateur personnel deviendra à la fois l’agence de votre banque et de votre courtier en devises, ainsi que l’équivalent parisien du kiosque où vous achetez votre carte téléphonique anonyme. Et, à l’instar de ces 150 cabines payantes à carte à puce qui ne servent à rien pour les voleurs s’ils les forcent au pied-de-biche, votre ordinateur ne sera accessible qu’à celui qui saura manipuler ou contourner un code informatique évolué. Cela exclura un grand nombre de malfrats qui savent manier le pied-de-biche. Grâce à un chiffrement bien conçu, rien dans votre ordinateur ne pourra être déchiffré ou détourné à votre insu.

Aux alentours de l’an 2000, vous pourrez réaliser des transactions commerciales quasiment partout, hormis l’Antarctique. Partout où vous disposerez d’un téléphone, filaire ou cellulaire numérique. Partout où existent des réseaux de télévision interactifs. Partout où un satellite survole votre région ou où fonctionnent d’autres modes de télécommunication sans fil. Vous pourrez parler, transférer des données, voyager virtuellement au-delà des frontières, à votre guise. Les numéros de téléphone qui identifient l’appelant par l’indicatif d’une zone géographique laisseront sans doute place à des numéros d’accès universels permettant de joindre la personne souhaitée partout sur la planète.

### Comprendre le chinois

Non seulement vous pourrez téléphoner et envoyer un fax, mais vous pourrez, à terme, couper court à des années d’apprentissage et discuter en chinois avec un contremaître dans une usine de Shanghai. Peu importera alors que vous ne parliez pas sa langue ou son dialecte. Ses mots seront en chinois, mais vous les entendrez traduits, approximativement, en français. Inversement, il vous écoutera en chinois. À terme, ce dispositif de traduction instantanée favorisera la concurrence de régions jusque-là handicapées par la barrière linguistique ou culturelle. Lorsque cela arrivera, peu importera, ou pas du tout, que le gouvernement chinois désapprouve votre appel.

### Des médias personnalisés

Plus le monde se rapprochera, plus vous serez en mesure de façonner votre « place » à votre guise. Même les informations que vous recevez régulièrement des médias seront celles que vous aurez choisies. Les médias de masse se mueront en médias individualisés. Si, plus que tout, vous aimez les échecs ou que vous êtes passionné de chats, vous pourrez configurer votre journal télévisé du soir pour qu’il traite de votre sujet fétiche. Vous ne dépendrez plus de Dan Rather ou de la BBC pour vous tenir au courant. Vous pourrez sélectionner un bulletin d’information compilé et édité selon vos directives.

### De la production de masse à la production sur mesure

Si l’actualité est calme, vous pourrez consulter un catalogue virtuel sur le Web. Si vous voyez un pantalon qui vous plaît presque, vous pourrez ajuster la largeur du revers au moment de passer commande. Il sera coupé et cousu sur mesure par des robots en Malaisie à partir des photos scannées dans votre ordinateur, puis transmises via le Net.

### Cybercourtage

Grâce à la cybermonnaie, vous pourrez non seulement régler vos achats, mais aussi investir. Si vous vivez dans une juridiction comme les États-Unis, où vos options d’investissement sont étroitement encadrées, vous pourrez choisir de loger vos opérations dans un territoire plus libéral, vous laissant libre d’opter pour la totalité de la gamme d’investissements possibles. Que vous soyez à Cleveland ou Belo Horizonte, vous n’aurez qu’à domicilier vos placements aux Bermudes, aux îles Caïmans, à Rio, ou encore Buenos Aires. Quelle que soit votre localisation, l’usage grandissant des ressources numériques évoluera au rythme du déploiement de la cyberéconomie. Vous pourrez faire appel à des systèmes experts pour sélectionner vos investissements, et employer des cybercomptables et cybergestionnaires pour superviser au fil de l’eau l’état de vos avoirs.

### Culture virtuelle

Quand vous ne passerez pas au crible les données de vos comptes, vous pourrez vous offrir une visite virtuelle au Louvre. Il vous faudra peut-être verser une somme équivalant au tiers d’un centime à Bill Gates ou à un autre visionnaire qui aura acheté les droits de visite en réalité virtuelle du musée. Tandis que vous vous demanderez si la Joconde souffrait de problèmes dentaires, votre ordinateur pourra télécharger la traduction de *La Romance de la chambre de l’Ouest* par S. I. Hsiung. Vous pourrez la faire lire à haute voix par votre appareil quand vous le souhaiterez, à la manière d’un ménestrel. Des programmes multitâches vous permettront d’accomplir bien d’autres actions simultanément.

### Choisir sa juridiction sur le Net

Si l’envie vous en prend, inspiré par les classiques, vous pourrez créer une société virtuelle pour commercialiser des mises en scène de grandes œuvres littéraires en 3D, projetées en réalité virtuelle sur l’écran rétinien de vos utilisateurs. Plutôt que de « sortir » l’image dans l’air ambiant, on la projettera directement sur la rétine des spectateurs via lasers basse énergie oscillant à cinquante mille fois par seconde. Cette technologie, d’ores et déjà en développement chez MicroVision à Seattle, permettra même à certaines personnes « légalement » aveugles de recouvrer partiellement la vue. Une fois cette idée en tête, vous pourrez charger votre assistant numérique de comparer les contrats de protection actuellement offerts pour la production en Malaisie, en Chine, au Pérou, au Brésil et en Tchéquie. Vous ferez ensuite immatriculer votre société aux Bahamas en moins d’une heure, par l’intermédiaire de St. George’s Trust Company. Vos instructions placeront ensuite tous les actifs liquides de l’entreprise dans un cybercompte logé dans une cyberbanque qui aura sa « domiciliation » simultanément à Terre-Neuve, aux îles Caïmans, en Uruguay, en Argentine et au Liechtenstein. Si, dans l’une de ces juridictions, les autorités retirent le droit d’opérer ou tentent de saisir les fonds des déposants, ceux-ci seront transférés instantanément vers une autre juridiction, à la vitesse de la lumière.

## AVANCÉES QUALITATIVES

Bonne partie des transactions que vous réaliserez bientôt dans le cyberespace aurait été inimaginable à l’ère industrielle, et pas seulement pour des raisons de distance ou de barrière linguistique. Envoyer par exemple votre assistant numérique trouver des articles non traduits parus dans des revues scientifiques hongroises n’est pas la même chose que faire faire une recherche à un bibliothécaire. Assister d’où vous êtes, à cinq mille kilomètres, à un tutorat universitaire à Oxford n’a rien à voir avec le fait d’y participer quand vous logez à quelques pas de Carfax. Jouer à la roulette du casino de l’Hôtel de Paris à Monte-Carlo, alors que vous êtes virtuellement « invité » à une fête à Punta del Este, Uruguay, relève d’une expérience radicalement inédite.

### Une consultation numérique chez le médecin

Sous peu, et sans doute plus rapidement que ce que pensent la plupart des observateurs, certaines activités combineront les technologies de façon inédite pour s’affranchir de la tyrannie du lieu et des institutions trop figées de l’économie industrielle. Demain, si vous avez mal au ventre, vous irez consulter un « médecin numérique », un système expert doté d’une connaissance encyclopédique des symptômes, maladies et remèdes. Il accédera (sous forme chiffrée) à votre dossier médical, vous demandera si la douleur survient après le repas ou avant, si elle est aiguë ou diffuse, continue ou par intermittence. Tout ce que vous demanderait un médecin conventionnel, l’IA de diagnostic vous le demandera aussi. Il se peut qu’elle conclue que vous buvez trop de vin, ou pas assez. Peut-être vous dirigera-t-elle vers un « cyberspécialiste ». En cas de besoin chirurgical, un « cyberchirurgien » domicilié aux Bermudes pourrait pratiquement réaliser l’opération à distance, grâce à un équipement spécialisé permettant de réaliser des micro-incisions.

### La gestion de la vie et de la mort par le traitement de l’information

Cela semble relever de la science-fiction. Mais nombre des briques technologiques nécessaires à la « cyberchirurgie » existent déjà, et le reste sera sans doute prêt au moment où vous lisez ces lignes. General Electric a ainsi introduit une nouvelle machine de radiothérapie par résonance magnétique (MRT) dans une quinzaine d’hôpitaux. Son développement passera par une phase de R&D d’une durée de trois ans, mais ensuite, elle se généralisera rapidement et deviendra la norme pour certains types de chirurgie. C’est un bon exemple de la manière dont la technologie transforme la société.

Nous connaissons tous l’imagerie par résonance magnétique (IRM), où l’on emploie des techniques de résonance magnétique pour produire des images de tissus mous. Elles offrent un meilleur rendu des tissus mous que les rayons X ou les ultrasons, et sont devenues essentielles dans le diagnostic moderne, particulièrement en oncologie. Jusqu’à présent, l’IRM présente deux limitations importantes. Le patient est entravé par le tube qui l’entoure et la puissance du champ magnétique est modeste.

### La chirurgie dans le cyberespace

General Electric a repensé la configuration des machines de résonance magnétique afin d’en faire des outils permettant à la fois le diagnostic et le traitement. La puissance a été multipliée par cinq. Le tube a été scindé en deux, si bien que le patient reste entre deux anneaux en forme de beignets, au lieu d’être enclose dans une structure unique. Plutôt que de prendre un cliché avant de pratiquer l’opération, le chirurgien pourra voir ce qu’il fait, en temps réel. L’association de la RTM et de techniques de chirurgie non invasive, ou peu invasive, grâce à des équipements miniaturisés, remplacera le scalpel et les incisions profondes par des microanimations et des sondes. Le médecin filmera la scène, n’ayant plus besoin de regarder directement à l’intérieur du corps du patient. Techniquement, ces sondes pourront être pilotées à distance. Elles supprimeront les tumeurs au laser ou par cryogénisation (chaleur ou froid extrême), de manière extrêmement précise.

Le MRT offrira la possibilité d’opérations actuellement impossibles, surtout en neurochirurgie, où les tumeurs se logent parfois à proximité immédiate de zones vitales du cerveau. Il permettra également des interventions multiples, là où un véritable acte chirurgical à l’ancienne ne peut être répété sans conséquences sérieuses. Certains chercheurs estiment que le bistouri réservé aux tissus mous sera perçu comme un archaïsme d’ici 2010. Si cela se confirme, une bonne partie du stress et de la convalescence postopératoire disparaîtra. Certes, c’est une excellente nouvelle pour le patient. Les opérations qui prenaient des heures, suivies de journées ou de semaines d’hospitalisation, prendront à peine une demi-heure et pourront souvent être menées en ambulatoire. Le praticien et son patient n’auront peut-être même pas à être dans la même pièce. Mais quel impact cela aura-t-il sur les hôpitaux et les chirurgiens ?

### Moins de microchirurgiens pour plus d’opérations

Nous allons connaître une révolution chirurgicale. Dans la formation, un tiers des jeunes chirurgiens échoue à acquérir les compétences requises pour la microchirurgie. Un autre tiers y parvient tout juste, quand le dernier tiers y excelle. Des proportions similaires se retrouvent chez les chirurgiens confirmés qui suivent des sessions de recyclage. À l’avenir, moins de chirurgiens réaliseront davantage d’opérations en moins de temps. Les compagnies d’assurance santé, ainsi que les particuliers en quête d’une opération, exigeront probablement des statistiques précises sur les performances chirurgicales, et celles-ci ne seront pas toutes équivalentes. Les patients chercheront logiquement le praticien qui présente les meilleurs résultats, en particulier si leur pronostic vital est engagé. Dans certains cas, c’est le meilleur chirurgien qui opérera à distance, depuis une juridiction permettant une imposition fiscale réduite et interdisant les indemnisations judiciaires exorbitantes.

### Les avocats numériques

Avant de prendre un tel risque en salle d’opération, le chirurgien de renom pourrait justement faire appel à un avocat numérique, un système d’extraction d’informations couplé à de l’intelligence artificielle (réseaux neuronaux, par exemple), afin de rédiger un contrat instantané précisant et limitant la responsabilité civile, basé sur la taille et la nature de la tumeur révélée par la machine MRT. Pour beaucoup de transactions importantes, on ne se contentera pas de choisir soigneusement la partie contractante : on décidera aussi dans quelle juridiction localiser ladite transaction.

### Consultation d’urgence

Pour prolonger l’exemple de la cyberchirurgie, gardons à l’esprit que l’ère de l’information rendra la spécialisation chirurgicale encore plus précieuse qu’aujourd’hui, comme c’est le cas dans d’autres domaines. Dès qu’il existe un risque vital et un temps limité, la recherche rapide d’un chirurgien expert passera par des assistants numériques : si vous devez subir une intervention dans les 24 heures, voire 45 minutes, vous pourrez demander à vos « agents » d’identifier les dix meilleurs chirurgiens disponibles dans le monde, de vérifier leurs taux de succès dans des cas similaires et de négocier leurs offres grâce à leurs assistants correspondants. Tout cela s’effectuera en quelques instants. Il en résultera une forte concentration de la demande en faveur des 10 % de chirurgiens les plus compétents, qui occuperont dès lors une part bien plus large du marché mondial. L’association « MRT + microchirurgie » valorisera ces compétences d’élite. Quant aux chirurgiens moins doués, ils continueront d’opérer localement.

Cet exemple illustre à quel point l’émancipation de l’économie par rapport à la tyrannie du lieu est révolutionnaire. On objectera que la MRT de General Electric n’a pas été conçue pour la télémédecine. Peut-être, mais c’est passer à côté de l’essentiel. Elle, ou un dispositif comparable, y arrivera bientôt. Dès l’instant où l’on admet qu’une intervention chirurgicale peut être menée via un écran plutôt qu’en examinant directement le patient, la distance n’aura plus l’importance qu’on croyait. Un nombre croissant de services seront reconfigurés pour tirer parti du fait que la technologie de l’information permet, même pour la chirurgie, de collaborer à l’échelle planétaire. Les secteurs qui requièrent moins de précision ou présentent moins de risques évolueront vers la cyberéconomie encore plus vite.

> « La politique financière de l’État-providence suppose qu’il n’existe aucun moyen pour les détenteurs de richesses de se protéger. » — ALAN GREENSPAN

## LA DÉVALORISATION DE LA CONTRAINTE

Dans la plupart des segments soumis à concurrence, y compris le marché gigantesque des investissements internationaux (évalué à plusieurs milliers de milliards de dollars), la migration des transactions vers le cyberespace sera stimulée par un phénomène presque mécanique : la volonté d’échapper à l’imposition prédatrice, y compris l’inflation, que l’on peut considérer comme un impôt sur tous ceux qui détiennent leurs richesses en monnaie nationale.

### S’évader du racket de la protection

On n’a pas besoin de réfléchir longtemps à la mégapolitique de l’ère de l’information pour comprendre qu’il deviendra absurde de maintenir aux taux actuels l’impôt sur le revenu, ainsi que l’inflation, deux leviers dont usent les pays industrialisés pour puiser dans la poche de leurs citoyens. Passé la fin du millénaire, toute personne continuant à subir de tels taux le fera par choix. Comme l’a souligné l’historien Frederic C. Lane, le passé montre qu’« aux frontières et sur les mers, là où personne ne détenait un monopole durable de la violence, les commerçants refusaient de payer des taxes si élevées que la protection pouvait s’obtenir à meilleur marché par d’autres moyens ».[^255]:

La cyberéconomie offre précisément ce moyen d’y échapper. Aucun gouvernement ne peut la monopoliser. Et les technologies de l’information qui la composent fourniront une protection de la propriété financière à la fois meilleure et moins coûteuse que tout ce qu’avaient pu offrir la plupart des gouvernements.

### La magie noire des intérêts composés

On se souviendra que tout forfait fiscal annuel de 5 000 $ versé au fil de quarante années rogne votre patrimoine de 2,2 millions de dollars, à supposer un rendement annuel de 10 % sur votre capital. En considérant 20 %, la perte s’élève à environ 44 millions. Pour les grosses fortunes soumises à un taux d’imposition élevé dans un pays à forte pression fiscale, la somme cumulée de ces taxes sur une vie entière est tout simplement colossale. Au final, la plupart perdent davantage qu’ils n’ont jamais possédé.

Cela semble impossible, mais la démonstration mathématique est limpide. Vous pouvez le vérifier vous-même avec une simple calculatrice. Aux États-Unis, le 1 % des foyers les mieux imposés versent en moyenne plus de 125 000 $ d’impôt fédéral sur le revenu chaque année. Pour moins de 45 000 $ annuels, on vous accueillerait volontiers en Suisse, vous faisant bénéficier d’un accord fiscal individuel. C’est un montant suffisant (45 000 $) pour vivre sous la protection de ce qui est probablement la police et le système judiciaire les plus intègres du monde. De ce point de vue, les 80 000 $ supplémentaires payés aux États-Unis servent plus ou moins de rançon ou de butin. Quarante-cinq mille dollars demeurent une contribution substantielle pour le maintien de l’ordre public, censé être un « bien commun ». En théorie, un bien commun peut être étendu à davantage d’usagers pour un coût marginal nul. Les Suisses ont tout intérêt à ce que chaque millionnaire leur paie un impôt négocié de 45 000 $, car cela leur rapporte ces 45 000 $ chaque année.

Comparons cette solution suisse au fait de payer 125 000 $ : sur une vie, et à un rendement annuel de 20 %, la perte associée aux impôts américains par rapport au forfait suisse atteint 705 millions de dollars. Mais si vous vous établissez dans un paradis fiscal comme les Bermudes, où l’impôt sur le revenu est nul, la perte grimpe alors à 1,1 milliard.

Certes, un taux de rendement de 20 % est très élevé. La remarque est légitime. Pourtant, en Asie, de nombreux investisseurs ont pu enregistrer de tels résultats, voire davantage. Sur plusieurs décennies, l’immobilier à Hong Kong a généré plus de 20 % de rendement annuel. Même certains pays moins réputés pour leur prospérité ont connu des opportunités fort rentables. Un dépôt en dollars US dans des banques du Paraguay a dégagé une rentabilité réelle de plus de 30 % par an, en moyenne, ces trente dernières années. Les investisseurs chevronnés peuvent tout à fait atteindre les 20 % ou plus lors des bonnes années, sans forcément égaler la performance d’un George Soros ou d’un Warren Buffett.

Plus le rendement potentiel de votre capital est élevé, plus le coût d’opportunité de l’impôt sur le revenu et des taxes sur les gains en capital augmente. Même si vos ambitions sont modestes, certains fonds communs d’investissement installés aux États-Unis affichent plus de 10 % de croissance annuelle sur plus d’un demi-siècle. Partant de 10 % seulement et en admettant que vous faites partie du 1 % d’Américains les plus aisés, l’excédent d’impôt supérieur à 45 000 $ annuels vous aurait tout de même privé d’une fortune de 33 millions sur une vie. Par rapport à un territoire exempt d’impôt sur le revenu, cela représente 55 millions de manque à gagner.

### 55 $ plutôt que 55 millions

Si l’on admet la théorie économique selon laquelle l’acteur rationnel maximalise son profit, alors la prévision la plus sûre est que la plupart des gens chercheront à sauver ces 55 millions s’ils en ont la possibilité. Nous pensons que c’est ce qui va se passer. Lorsque la « magie noire » des intérêts composés sera mieux comprise des plus fortunés, ils se hâteront de comparer diverses juridictions, comme ils comparent aujourd’hui les marques de voitures ou les primes d’assurance. Pour le vérifier, arrêtez n’importe qui dans la rue à New York ou Toronto et demandez-lui s’il déménagerait aux Bermudes en contrepartie de 55 millions de dollars : la réponse est évidente. La situation évoque l’histoire de Mark Twain, se demandant s’il préférerait passer la nuit nu avec Lillian Russell ou vêtu d’uniforme de gala avec le général Grant. Son choix fut vite fait. Les habitants des États-providence, États-Unis compris, réagiront peut-être moins vite, car ils ignorent encore qu’ils ont le choix. Mais quand ils le sauront, ils décideront en conséquence. Tout individu cherchant à améliorer son existence verra l’intérêt de réduire l’hémorragie fiscale. Il suffira de localiser ses transactions dans le cyberespace. Bien entendu, ce sera illégal dans bien des États. Mais les vieilles lois peinent toujours à résister aux nouvelles technologies. Dans les années 1980, le fax était en principe illégal aux États-Unis : la Poste américaine considérait qu’un fax constitue un courrier de première classe, dont elle s’arrogeait le monopole séculaire. Une ordonnance enjoignait que tous les fax transitent par le bureau de poste le plus proche pour être distribués avec le courrier. Des milliards de fax plus tard, on ne sait pas si quiconque s’y est soumis. Et si c’est arrivé, ce fut bref. Les avantages d’opérer dans la nouvelle cyberéconomie sont encore plus évidents que de contourner la poste en envoyant un fax.

L’usage massif d’algorithmes de cryptographie à clé publique/clé privée permettra bientôt de réaliser de nombreuses opérations économiques depuis n’importe où. Pour reprendre les termes de James Bennet, rédacteur aux questions de technologie pour Strategic Investment :

> « L’application des lois, et en particulier des codes fiscaux, repose en grande partie sur la surveillance des communications et des transactions. Lorsque la logique suivra son cours et que les places bancaires offshore proposeront la messagerie électronique chiffrée RSA avec des numéros de compte dérivés de systèmes à clé publique, les opérations financières deviendront quasi impossibles à tracer, autant dans les banques qu’en transit. Même en infiltrant la banque offshore ou en volant ses registres, les autorités fiscales ne pourront identifier les déposants. »[^256]:

À un degré sans précédent, chacun pourra choisir le lieu de domiciliation de ses affaires et combien d’impôt sur le revenu il entend payer. De nombreuses opérations de l’ère de l’information n’auront même pas à être logées sous la juridiction d’un État. Celles qui y seront soumises iront dans des endroits comme les Bermudes, les îles Caïmans, l’Uruguay ou des pays comparables, où ni l’impôt sur le revenu ni d’autres charges transitoires coûteuses ne freinent le commerce.

### Du monopole à la concurrence

Les États ont pris l’habitude de vendre leurs « services de protection » (pour reprendre l’expression de Frederic C. Lane) « de mauvaise qualité et à un prix exorbitant ».[^257]: Des siècles de monopole ont forgé cette manie de taxer quiconque en avait la possibilité. Dans la plupart des cas, les gouvernements ont détenu un monopole, ou quasi. Cette tradition de monopole va se heurter frontalement aux opportunités qu’offre le cybercommerce.

Le chiffrement, en effet, protège facilement les transactions dans le cyberespace. Installer PGP, un outil de cryptographie efficace, coûte à peine plus que la commission d’un courtier traditionnel sur un lot de cent actions. Pourtant, grâce à lui, presque toutes les transactions deviennent invisibles et inaccessibles aux États ou aux voleurs, et ce pour un bon nombre d’années. Dans l’ère de l’information, on peut protéger efficacement ses actifs numériques pour un coût presque négligeable. Contre 55 $ et non 55 millions, les participants de la cyberéconomie obtiennent une sécurité supérieure à celle offerte par les gouvernements de l’ère industrielle, et par tous les régimes antérieurs. Les algorithmes de cryptographie, aisément utilisables, et la possibilité de choisir sa juridiction de domiciliation rendront la cyberpropriété étrangère aux exactions du principal prédateur historique : l’État.

Cela ne veut pas dire que le pouvoir territorial se rendra sans broncher. Ils pourront encore recourir au chantage contre les personnes présentes physiquement pour extorquer un impôt de capitation, voire organiser de véritables enlèvements avec rançon contre les plus riches. Ils pourront aussi percevoir des taxes sur la consommation. Malgré tout, la protection — principal « service » fourni par les gouvernements — sera mise en concurrence. Une moindre part de l’argent que gagnent les producteurs pourra être confisquée, puis redistribuée par les politiciens. Les innovations technologiques placeront une fraction croissante du patrimoine mondial hors de portée des États. On assistera à une réduction des risques commerciaux, et par conséquent des coûts de transit, du « tribut » ou de l’extorsion.[^258]

Dans l’histoire, de telles occasions de voir les États réellement limités par la concurrence ont toujours été rarissimes. Dans les périodes où cela s’est produit, les gouvernements étaient faibles et la technologie similaire d’un territoire à l’autre. Comme le dit Lane, le facteur déterminant de la rentabilité économique dans un tel contexte — si toutefois on peut en déterminer un — réside souvent dans les différences de frais de protection supportés par les entrepreneurs. Au Moyen-Âge, il suffisait de devoir payer vingt péages contre quatre pour être éliminé de la compétition. C’est ce qui nous attend à nouveau avec l’ère de l’information. C’est la capacité à minimiser ses frais de protection qui va conditionner la rentabilité.

Cette dynamique contredit radicalement la volonté traditionnelle des États d’imposer un « prix monopolistique » pour leur protection. Mais, qu’il le veuille ou non, l’ancien système sera inopérant dans l’environnement compétitif de l’ère de l’information. Les gouvernements taxant à outrance pousseront simplement talents et capitaux à fuir ailleurs. Ainsi, l’incapacité des États-providence à baisser nettement la fiscalité, sur le long terme, se soldera d’elle-même. Les gouvernements imposant trop de taxes transformeront en ruine le fait de vivre sur leur sol.

> « … comme le roi, par son prérogatif, peut frapper monnaie de la matière ou de la forme qui lui plaît et en établir la norme, il peut aussi transformer sa monnaie, et en accroître ou réduire la valeur, ou encore la déclarer entièrement nulle et non avenue. »[^259] — Extrait d’un arrêt de justice anglaise, 1604

## LA MORT DU SEigneuriage

Les États ne perdront pas seulement leur faculté de prélever l’impôt sur la plupart des revenus et capitaux ; ils risquent aussi de voir se briser leur monopole monétaire. Rappelons que les transitions mégapolitiques du passé se sont toujours accompagnées de transformations dans la nature de la monnaie.

- L’introduction de la monnaie frappée (pièces) a contribué au cycle d’expansion de cinq cents ans dans l’Antiquité, qui s’est achevé autour de la naissance du Christ, au moment où les taux d’intérêt atteignaient leur niveau le plus bas avant la période moderne.  
- L’apparition du « Moyen Âge sombre » coïncide avec le quasi-arrêt de la frappe. Bien que la monnaie romaine ait continué de circuler, sa quantité a diminué en même temps que le commerce, dans une spirale descendante.  
- La révolution féodale a surgi avec la réintroduction de la monnaie, du monnayage, des lettres de change et autres mécanismes destinés aux transactions. En particulier, l’exploitation de nouveaux filons d’argent en Europe (Rammelsberg, Allemagne) a accru l’émission de pièces, favorisant ainsi l’essor du commerce.  
- Avant l’ère de l’information, la plus grande révolution monétaire a été celle qui a accompagné l’industrialisation. L’État moderne, tirant sa puissance de la révolution de la poudre à canon, s’est fermement imposé et a pris la main sur la monnaie. Il a massivement exploité la grande invention de l’ère industrielle, la presse d’imprimerie, pour émettre de la monnaie papier.

La monnaie papier s’inscrit pleinement dans la dynamique industrielle. Il aurait été absurde avant l’imprimerie de recourir à des reçus ou certificats reproduits en série comme supports monétaires. On n’allait sûrement pas gaspiller le travail d’un scribe dans un scriptorium pour fabriquer cinquante billets de banque. Or, la monnaie papier a considérablement renforcé le pouvoir de l’État, non seulement en lui permettant de s’enrichir en dépréciant la monnaie, mais également en lui donnant la main sur qui pouvait accumuler des richesses. Comme l’explique Janet Abu-Lughod, « quand l’argent papier soutenu par l’État est érigé en principal moyen de paiement, les possibilités d’accumuler du capital en marge ou en opposition devenaient presque nulles ».[^260]:

## LA CYBERMONNAIE

À présent, l’avènement de l’ère de l’information laisse présager une nouvelle révolution dans la nature de la monnaie. Avec l’émergence d’un commerce en ligne, apparaîtra inévitablement la « cybermonnaie ». Cette forme inédite de monnaie sapera considérablement la capacité des États à décider qui deviendra un « Sovereign Individual ». En grande partie à cause du rôle de la technologie de l’information, qui libérera les détenteurs de patrimoine de la confiscation infligée par l’inflation. Ils n’auront plus aucune raison d’accepter une constante dépréciation de leur monnaie nationale. Bientôt, vous réglerez quasiment tout achat sur le Net ou le Web au moment même de la commande, à l’aide de monnaie numérique.

Cette version chiffrée de l’argent jouera un rôle crucial dans le cybercommerce. Elle se composera de suites de nombres premiers de plusieurs centaines de chiffres, à la fois uniques, anonymes et validables, pouvant servir aux plus importantes transactions mais aussi se fractionner à l’infini pour couvrir de microscopiques montants. Elle sera échangeable instantanément sur un marché mondial représentant plusieurs milliers de milliards de dollars, sans restrictions.

### Composer sans dollars

Inévitablement, cette cybermonnaie se dissociera des monnaies nationales. Quand les « Sovereign Individuals » peuvent nouer des transactions sans frontières, dans un univers immatériel, rien ne les oblige à subir l’inflation étatique caractéristique de la monnaie nationale. Pourquoi l’accepteraient-ils ? Le contrôle monétaire se déplacera des bureaux gouvernementaux vers le marché global. Quiconque aura accès à Internet pourra quitter aisément toute devise susceptible de se déprécier. Inutile de se soumettre à la « monnaie légale » imposée. D’ailleurs, si vos transactions parcourent la planète, il est probable qu’au moins une des deux parties n’utilise pas sa propre monnaie nationale.

### Réduction des inconvénients du troc

Vous pourrez choisir en ligne la monnaie que vous utiliserez. Comme l’économiste E. A. Hayek, lauréat du prix Nobel, le soulignait, « il n’y a pas de frontière nette entre ce qui est monnaie et ce qui ne l’est pas ». Il ajoutait : « même si l’on a tendance à établir une séparation binaire entre la monnaie et ce qui ne l’est pas — et la loi elle-même tente de le faire — au fond, la monnaie et les objets proches de la monnaie forment un continuum dont chaque élément occupe une certaine place en termes de liquidité ou fluctue librement par rapport à d’autres. »[^261]: Dans l’environnement numérique, tout le « continuum » d’objets liquides s’en trouvera accru, sauf la monnaie étatique. Cela aura notamment pour effet de rendre le troc plus exploitable. Les offres simultanées de tel service ou tel bien contre tel autre fleuriront à travers le Net mondial, améliorant de beaucoup la liquidité de ces échanges.

Le troc rencontre un handicap majeur depuis toujours : la difficulté de faire coïncider parfaitement, en un marché local, deux personnes dont l’une propose un bien précis que l’autre souhaite acquérir, et vice versa. La circulation monétaire surmonte cette limite, et ses atouts resteront d’actualité dans la plupart des transactions. Cependant, la puissance de calcul, combinée au maillage mondial du commerce en ligne, minimise les inconvénients du troc. Les chances de trouver quelqu’un qui corresponde exactement à votre offre et à votre demande sont bien plus élevées lorsqu’on trie en un clin d’œil sur la planète entière plutôt que sur quelques kilomètres.

### Résistante à la contrefaçon

Alors que la monnaie papier demeurera un moyen de règlement résiduel pour les catégories les plus modestes et les moins au fait de l’informatique, la véritable monnaie des grandes transactions se privatisera. La cybermonnaie n’aura plus pour seul étalon les unités nationales, comme c’était le cas pour la monnaie papier au temps de l’industrialisation. Elle sera probablement indexée sur l’or, en grammes ou en onces, autant divisible que celui-ci. Ou bien déterminée par rapport à d’autres réserves de valeur réelles. Même si d’autres systèmes d’évaluation se concurrencent, ou si certaines transactions sont encore exprimées en monnaies nationales, la cybermonnaie rendra un meilleur service aux consommateurs que ne l’a jamais fait l’argent émis par l’État. La puissance grandissante de l’informatique éliminera pratiquement les difficultés de conversion. Chaque échange se fera via le transfert de suites cryptées de nombres premiers de plusieurs centaines de chiffres. Contrairement aux tickets de banque d’autrefois, l’État ou les contrefacteurs ne pourront pas générer de faux billets. Ce serait pratiquement impossible, d’un point de vue mathématique, de factoriser ces nombres premiers colossaux. Tous les reçus seront vérifiables et uniques.

Le nom des anciennes monnaies, comme la « livre » ou le « peso », rappelle qu’il s’agissait initialement d’unités de poids d’or ou d’argent. La monnaie papier en Occident est née comme reçu d’entrepôt ou de coffre-fort, référant à des lingots. Les gouvernements, en tant qu’émetteurs de ces reçus, ont vite compris qu’ils pouvaient en imprimer davantage que ce que leur stock d’or couvrait… Personne ne pouvant distinguer les faux certificats des vrais, tant qu’on « faisait confiance », l’inflation était à portée de main.

La cybermonnaie, elle, sera infalsifiable à ce niveau, par des moyens légaux ou clandestins. La validité numérique associera définitivement l’outil de paiement à la réserve qu’il représente. L’astuce classique consistant à émettre plus de reçus que de métal disponible ne sera plus une option.

### Le coût d’une monnaie « gratuite »

De fait, l’essor de cette cybermonnaie vous libérera quasiment du pouvoir de l’État. Nous avons vu que la performance historique des États depuis la fin de la Seconde Guerre mondiale est médiocre en matière de stabilité monétaire. Entre janvier 1949 et fin juin 1995, la valeur du mark allemand (la moins malmenée) a baissé de 71 %. Durant la même période, la référence mondiale, le dollar américain, a vu son pouvoir d’achat s’effondrer de 84 %.[^262]: C’est autant de richesse arrachée par les gouvernements grâce à leur monopole juridictionnel.

Retenons qu’il n’existe pas de nécessité intrinsèque à ce qu’une monnaie se déprécie ou que le coût de la vie grimpe chaque année. Bien au contraire. Techniquement, préserver le pouvoir d’achat de l’épargne est chose banale. Il suffit d’observer la stabilité de l’or sur le long terme.

Entre janvier 1949 et fin juin 1995, alors que la meilleure des monnaies nationales tyrannisées par l’inflation perdait plus des deux tiers de sa valeur, l’once d’or voyait son pouvoir d’achat croître. Comme l’a prouvé Roy W. Jastrom dans *The Golden Constant*, l’or a maintenu son pouvoir d’achat, avec de légères fluctuations, aussi loin que remontent les relevés de prix fiables (jusqu’en 1560 pour l’Angleterre).

Pour peu qu’on lie la monnaie à l’or, même de façon imparfaite, on constate qu’elle maintient son pouvoir d’achat tant que le pays n’entre pas en guerre et que ses réserves ne sont pas siphonnées. Pendant le paisible XIXᵉ siècle, quand la livre sterling n’était que faiblement couverte en or, sa valeur s’est même appréciée. Or, les conditions mégapolitiques nouvelles de l’ère de l’information rendent possible un arrimage bien plus solide qu’autrefois, car le citoyen-consommateur, équipé d’un formidable potentiel de calcul, prendre le pas sur le contrôle gouvernemental traditionnel.

> « Le risque de perdre instantanément toute sa clientèle en cas de non-respect des attentes (et on imagine aisément les tentations de manipulation qu’aurait un monopole d’État sur le prix des matières premières !) serait une garantie bien plus forte que n’importe lequel des garde-fous dont pourrait se doter un monopole public. »[^263] — FRIEDRICH A. VON HAYEK

### Vers une monnaie privatisée

Friedrich von Hayek soutenait, en 1976, que l’usage simultané de monnaies privées concurrentes mettrait fin à l’inflation.[^264]: En l’absence de contrainte obligeant à accepter la monnaie nationale sur un territoire, une concurrence loyale imposerait en effet aux émetteurs de préserver leur valeur. Quiconque ne s’y conformerait pas perdrait ses clients. À mesure que se développe l’emploi d’une monnaie cryptée, le raisonnement d’Hayek va prendre corps.

La théorie du « free banking », ou banque libre, n’est pas qu’une spéculation universitaire. L’Écosse n’avait pas de banque centrale entre le début du XVIIIᵉ siècle et 1844. Une réglementation réduite y ouvrait l’accès à la création bancaire. Les banques indépendantes collectaient l’épargne et émettaient leurs propres billets privés, appuyés sur l’or. Comme l’a montré le professeur Lawrence White, ce système fonctionnait bien, plus stable et moins inflationniste qu’en Angleterre même époque, où l’État imposait plus de contrôles.[^265]: Michael Prowse, du Financial Times, l’a résumé ainsi : « Il y avait peu de fraudes. Nul signe de surémission de billets. Les banques ne maintenaient ni trop ni trop peu de réserves. Les paniques bancaires étaient rares et ne se propageaient pas. Les gens respectaient les “free banks” et elles ont constitué un socle fiable pour la croissance économique, dépassant souvent celle de l’Angleterre pendant cette période. »[^266]:

Ce qui a marché sous l’angle technologique des XVIIIᵉ et XIXᵉ siècles marchera d’autant mieux avec la puissance informatique du XXIᵉ. Un organisme privé d’une certaine réputation, tel un grand groupe minier ou la Société de Banque Suisse, pourrait émettre des « reçus » chiffrés en contrepartie d’une quantité définie d’or, ou même de lingots étiquetés (signature moléculaire et peut-être marquage holographique). Ces reçus se négocieraient alors comme de la monnaie, sans risque majeur de contrefaçon, du fait de leur incrustation dans des noyaux de chiffres premiers longs de plusieurs centaines d’unités.

La monnaie numérique en or résoudra bon nombre de problèmes pratiques ayant jusque-là freiné l’usage direct du métal précieux. Fini le temps de transporter de gros lingots, où de gérer la crainte de se faire agresser. Fini le temps où rendre la monnaie en or pouvait poser problème. Les reçus virtuels n’auront ni poids ni encombrement. En outre, la compression en fractions minuscules permettra des paiements inférieurs au centime. Dans le système scriptural classique, manipuler de telles nuances serait trop complexe ; or, un ordinateur sait immédiatement distinguer l’équivalent d’un louveteau (pour un mince trouvère…) d’un rhinocéros (pour une caravane, disons). 

La possibilité d’offrir de faciles « micropaiements » dynamisera l’émergence de nouveaux modèles économiques autrefois irréalisables, pour la collecte et la distribution d’informations de faible valeur unitaire. Les producteurs de contenu pourront recevoir un paiement direct ou un micro-prélèvement dès qu’un utilisateur ouvrira le document. Jusque-là, les coûts de facturation dépassaient la valeur transactionnelle. La cybermonnaie autorise une facturation simultanée, où le débit a lieu au même instant que l’utlisation du service. Nous avons plus haut imaginé que vous paieriez un tiers de centime à Bill Gates pour une visite virtuelle du Louvre. Les usages de la réalité virtuelle vont créer un nombre illimité de créneaux à micro-redevances. Un jour, vous pourrez revivre le troisième match des World Series 1969, en payant ces microsomme aux joueurs dont l’image sera employée pour recréer l’expérience.

## Éradiquer l’inflation

Mais la conséquence la plus décisive de cette monnaie numérique sera la fin de l’inflation et la réduction du levier financier. Les répercussions économiques sont immenses. L’essor de l’inflation au XXᵉ siècle, comme nous l’avais prédit dans *Blood in the Streets* et *The Great Reckoning*, était indissociable du renforcement du pouvoir mondial. Les gains exponentiels dans l’art de la guerre imposaient des budgets militaires toujours plus lourds, d’où la nécessité d’extraire des sommes de plus en plus importantes. Les États ont découvert qu’ils pouvaient lever un impôt annuel sur la richesse détenue en monnaie — une sorte d’impôt sur la détention de cash. Ce dernier peut être vu comme un coût de transaction lié à l’usage d’une monnaie que l’État met à disposition.[^269]

Penser l’inflation en ces termes (commission prélevée pour l’usage de la monnaie) est inhabituel, mais la démonstration est cohérente. Durant l’ère industrielle, nous nous sommes habitués à considérer la monnaie comme un service « gratuit » fourni par l’État. Mais en réalité, les États ont prélevé, très cher, son utilisation, par l’inflation. De 2,7 % à 99 % selon les époques et les pays, voilà à peu près la fourchette d’une ponction annuelle sur la seule détention de cash. Du point de vue macro, c’est un tribut sur les systèmes nationaux.

On remarquera qu’il n’y avait pas de fatalité à la dépréciation monétaire ou à la hausse durable des prix. Encore aujourd’hui, le contrôle de la masse monétaire est trivial lorsqu’on laisse agir les forces du marché. L’Argentine illustre parfaitement la transition probable qui attend bon nombre d’États-nations : l’hyperinflation a sonné le glas de l’autorité monétaire, et le pays a été contraint d’adopter un currency board. D’autres pays risquent d’emprunter la voie du surendettement et de l’hyperinflation, jusqu’à ce que leurs citoyens se détournent de leurs billets au profit de la cybermonnaie.



### Contraction du crédit

Non seulement la monnaie numérique mettra définitivement fin à l’inflation, mais elle sonnera également la fin du crédit à effet de levier, caractéristique des systèmes bancaires traditionnels. L’acteur de marché pourra contourner n’importe quelle banque locale par Internet. Les gouvernements ne pourront pas l’endiguer. Et lorsqu’il sera impossible, ou trop coûteux, pour les États d’imprimer de la monnaie ou de forcer l’offre de crédit via des banques soumises à leurs injonctions, c’est un volet important de leur emprise indirecte qui disparaîtra.

### Des taux d’intérêts plus élevés

Ce faisant, la plupart des gouvernements occidentaux se retrouveront face à un dilemme évident. Les recettes de l’impôt baisseront considérablement, tout comme l’effet de levier issu du système monétaire. Pendant le même temps, ils devront encore honorer les engagements non financés et les promesses sociales héritées de l’ère industrielle. Résultat probable : une crisis fiscale intense et des répercussions sociales peu agréables, abordées plus loin. D’un point de vue purement économique, cette crise de transition devrait provoquer un pic ponctuel des taux d’intérêt réels. Les débiteurs seront sous pression pendant que s’évaporeront d’anciens avantages, et que le crédit « subventionné » s’asséchera.

### Transformation via la concurrence

Dans leur concurrence avec la cybermonnaie payante, les pouvoirs monétaires nationaux pourraient répliquer en durcissant le crédit et en offrant un meilleur rendement réel à l’épargne pour encourager la détention de leur monnaie. Certains envisageront même de « remonétiser » l’or pour concurrencer les monnaies privées. La logique étant qu’un quasi-étalon-or conférerait plus d’usagers qu’une simple monnaie « en papier ». On peut également imaginer des gouvernements qui persistent dans l’hyperinflation au début de l’ère numérique pour ponctionner ceux qui n’ont pas accès à Internet ou ne maîtrisent pas l’outil. Ils emprunteraient alors sur les marchés en cybermonnaie, tout en faisant tourner la planche à billets « à l’ancienne » dans leur pays.

D’autres gouvernements miseront plutôt sur un cadre légal favorable à la monnaie numérique. Ceux qui reconnaîtront d’abord la légitimité des signatures numériques et organiseront la protection juridique des créanciers en cas de défaut obtiendront un flux important de capitaux à long terme. A contrario, dans les régions où les tribunaux imposent des contraintes ou refusent d’appliquer les contrats cybernétiques, le crédit en cybermonnaie ne se développera pas.

### Un écart de rendement

Au cours des premières étapes, la coexistence de la cybermonnaie et des monnaies nationales incitera à un phénomène de « duplication de système ». On peut s’attendre à ce que la première promette un taux d’intérêt plus faible, tout en comportant des frais de transaction explicites. En contrepartie, on jouira d’une protection contre la taxation confiscatoire et l’inflation. De plus, un arrimage à l’or pourrait profiter de l’augmentation attendue du prix du métal jaune. Quelles que soient les stratégies adoptées par les gouvernements, le prix de l’or a tendance à grimper en cas de déflation, situation où la monnaie se raréfie, et l’or étant la valeur-refuge ultime.

### La déflation de l’ère industrielle

Les taux réels plus élevés contribueront à liquider les secteurs de production à coûts exagérés et à réduire la consommation pendant un certain temps. Nous avons décrit ce phénomène (cycle du crédit et liquidation) dans *Blood in the Streets* et *The Great Reckoning*, inutile de nous y attarder ici. Retenons seulement que pendant cette phase déflationnaire, les économies à coûts élevés (l’Amérique du Nord et l’Europe occidentale) souffriront plus que celles d’Asie et d’Amérique latine, où la main-d’œuvre est moins chère.

### Taux plus bas sur le long terme

À plus longue échéance, cependant, on peut parier sur un mouvement inverse. À l’issue du choc initial qui poussera les taux d’intérêt à la hausse, les rendements nets de l’épargne grimperont, puisqu’une part croissante du capital échappera aux politiques confiscatoires de l’État. Les gains d’efficacité dans la gestion des ressources et la possibilité pour les capitaux de se diriger vers les zones les plus rentables sur la planète devraient compenser assez rapidement la stagnation de la production due à la crise de transition.

### Pouvoir accru des investisseurs sur le capital

Un raisonnement conventionnel prédit l’effondrement de l’économie mondiale, au motif que la fin de la redistribution étatique dans les pays clés serait drastique. Ce n’est pas notre position. Nous admettons qu’une crise de transition est probable. Mais l’idée que seul l’État, grâce à la redistribution massive, assure le bon fonctionnement économique relève d’un dogme dépassé, comparable à la croyance selon laquelle, à la fin du Moyen-Âge, il fallait jeûner et se flageller collectivement pour conjurer les épidémies. Rappelons juste que les gouvernements gaspillent à une énorme échelle. Gaspiller rend pauvre. Lorsque des décisions d’investissement sont rendues à des acteurs talentueux plutôt qu’à l’appareil politique, on s’attend logiquement à une meilleure productivité.

Des dizaines, puis des centaines de milliards de dollars seront sous le contrôle d’un nombre croissant de « Sovereign Individuals ». Ces nouveaux dépositaires de la richesse mondiale sont a priori plus compétents que les politiciens pour optimiser l’allocation de ressources. Pour la première fois dans l’histoire, les conditions mégapolitiques permettront aux individus et aux entrepreneurs talentueux, plutôt qu’aux spécialistes de la violence, de détenir le dernier mot sur le capital. On peut tabler sur des rendements économiques supérieurs, peut-être deux ou trois fois ceux, dérisoires, obtenus par les financements publics de l’ère des États-nations. Qui plus est, dans la plupart des pays, on peut citer des exemples frappants de gaspillage public. Nous avons signalé dans l’édition de novembre 1992 de *The Great Reckoning* que selon la statistique officielle russe, l’économie de Russie toute entière « ne valait que 30 milliards de dollars, à peine un tiers de la valeur de ses intrants en matières premières. Autrement dit, la production russe vaudrait trois fois plus si on fermait toutes les usines de transformation. »[^267]:

S’il s’agit d’un cas extrême, il n’en demeure pas moins excellente l’observation selon laquelle restreindre le rôle de l’État améliore l’efficacité économique. Les chiffres rapportés par *The Economist* donnent à croire que la croissance est intimement liée à la liberté économique ; les nations disposant du plus de libertés affichent aussi les taux de croissance plus élevés. Or, le cyberespace sera l’économie la plus libre jamais apparue. Logiquement, la cyberéconomie deviendra la plus dynamique du nouveau millénaire. Sans cesse plus de personnes la rejoindront, partout sur le Globe, de la même façon que la généralisation du fax a entraîné un effet d’entraînement sur ses utilisateurs potentiels. Mais, plus encore, l’absence de prédation violente dans la cyberéconomie devrait permettre à ce secteur de dépasser, et de loin, la croissance des économies traditionnelles soumises à l’influence des États-nations.

C’est peut-être le point le plus important à souligner sur l’impact économique de l’effacement des monopoles de taxation et d’émission monétaire. En mettant de côté les difficultés de transition, potentiellement longues de plusieurs décennies, nous entrevoyons un horizon très positif pour l’économie mondiale. L’histoire montre que chaque fois que les coûts de la protection et de la violence baissent, l’activité croît de façon spectaculaire. En termes de Frederic C. Lane : « Je suggérerais volontiers que le facteur peut-être le plus lourd dans la plupart des périodes de croissance a été la diminution de la proportion de ressources consacrées à la guerre et à la police. »[^268]:

L’allègement du tribut versé à la prédation pourrait bien conduire à un gain d’efficacité considérable. S’il devenait possible de « tarifer » la protection en situation de concurrence, où chaque monopole local rivalise en qualité-prix, on aurait accès à une grande efficacité potentielle. On peut s’attendre à un baisse drastique des obligations fiscales, une réduction des pertes de ressources et de temps en intrigues politiques, moins lucratives qu’autrefois.

Les électeurs abandonnant ces avantages politiques ne feraient-ils pas faillite ? Nous développerons cette question plus tard. La brève réponse est que la question ne se posera peut-être pas. Personne ne sort manifester contre la pluie ou la sécheresse, aussi nuisibles ou ennuyeuses soient-elles. Aucun bandit n’exige de rançon d’un miséreux. Là où il est impossible pour un État de prélever les ressources qu’il redistribuait, la population pourrait réagir, non sans bon sens, en se détournant de la politique, tout comme les processions de flagellants ont cessé après le Moyen-Âge.

[^245]: Perry Barlow, « Thinking Locally, Acting Globally », Time, 15 janvier 1996, p. 57.  

[^246]: Ibid.  

[^247]: M. C. Seymour, éd., *Mandeville’s Travels* (Oxford : Oxford University Press, 1968), p. 122.  

[^248]: R. C. Johnson, « The Transportation of Vagrant Children from London to Virginia, 1618-1622 », dans H. S. Reinmuth, éd., *Early Stuart Studies* (Minneapolis : University of Minnesota Press, 1970), pp. 143-44, cité dans Jutte, op. cit., p. 168.  

[^249]: John Dos Passos, *The Big Money* (New York : Harcourt, Brace & Co., 1936).  

[^250]: Clarke, op. cit., p. 29.  

[^251]: Cité dans Kline et Burstein, op. cit., p. 205.  

[^252]: Clarke, op. cit., p. 20.  

[^253]: Ibid.  

[^254]: Ibid., p. 21.  

[^255]: Lane, « Economic Consequences of Organized Violence », op. cit., p. 404.  

[^256]: James Bennet, « The Information Revolution and the Demise of the Income Tax », *Strategic Investment*, novembre 1994, pp. 11-12.  

[^257]: Lane, « Economic Consequences of Organized Violence », op. cit., p. 404.  

[^258]: Abu-Lughod, op. cit., p. 177.  

[^259]: Cité dans Henry Mark Holzer, *Governments’ Money Monopoly* (New York : Books in Focus, 1981), p. 4.  

[^260]: Abu-Lughod, op. cit., p. 332.  

[^261]: Friedrich A. von Hayek, *The Denationalization of Money* (Londres : Institute of Economic Affairs, 1976), p. 47.  

[^262]: Voir chapitre 1, note 6.  

[^263]: Hayek, op. cit., p. 40.  

[^264]: Ibid.  

[^265]: Voir Lawrence White, *Free Banking in Britain* (Londres : Institute of Economic Affairs, 1995).  

[^266]: Michael Prowse, « Bring Back Gold », *Financial Times*, 5 février 1996, p. 12.  

[^267]: Davidson et Rees-Mogg, op. cit., p. 203.  

[^268]: Lane, « Economic Consequences of Organized Violence », op. cit., p. 413.  

[^269]: L’inflation avait un autre attrait à l’ère industrielle, lorsque les prix et salaires résistaient aux baisses. Une inflation modérée stimulait l’activité en réduisant le salaire réel et les prix.

::: {.content-visible when-format=latex}
\setsubtitle{La révolution de la capacité de gain dans un monde sans emplois}
:::
