# LE CRÉPUSCULE DE LA DÉMOCRATIE

> « Les systèmes politiques démocratiques sont un phénomène récent à l’échelle de l’histoire. Ils ont existé brièvement en Grèce et à Rome, puis ont réémergé au XVIIIᵉ siècle, il y a moins de 200 ans. … Il se peut qu’un cycle de rejet ait à nouveau commencé. »[^430] – WILLIAM PFAFF

Il n’est un secret pour personne que la démocratie a été relativement rare et éphémère dans l’histoire des gouvernements. Dans les époques, anciennes et modernes, où elle a prévalu, il lui a fallu, pour triompher, des conditions mégapolitiques favorisant la puissance militaire et l’importance des masses. L’historien Carroll Quigley a exploré ces caractéristiques dans *Weapons Systems and Political Stability*[^431].

Elles incluent :

1. **Un armement peu coûteux et largement dispersé.** La démocratie a tendance à prospérer quand le coût d’acquisition d’armes utiles est faible.

2. **Des armes utilisables efficacement par des amateurs.** La démocratie est plus probable lorsque tout un chacun peut manier des armes efficaces sans avoir besoin d’une formation poussée.

3. **Un avantage militaire procuré par un grand nombre de participants à pied au combat.** Comme le souligne Quigley : « Les périodes où l’infanterie domine sont des périodes au cours desquelles le pouvoir politique est plus largement dispersé au sein de la communauté et où la démocratie a de meilleures chances de prévaloir.[^432] »

Ce catalogue n’est certes pas exhaustif pour établir les conditions dans lesquelles la démocratie peut exister. S’il l’était, la démocratie n’aurait pas triomphé à la fin du XXᵉ siècle. Les armes étaient sans doute plus onéreuses au crépuscule de l’ère industrielle que jamais auparavant. Et de nombreuses armes parmi les plus efficaces nécessitaient indéniablement des spécialistes pour être manipulées correctement. De plus, la guerre du Golfe entre les États-Unis, leurs alliés et l’Irak a prouvé à quel point de larges contingents d’infanterie, même retranchés derrière des tranchées et des fortifications, demeurent vulnérables. Pourquoi donc la démocratie semble-t-elle avoir prospéré sous ces conditions alors que se clôt le XXᵉ siècle ?

## LA DÉMOCRATIE, SŒUR JUMELLE DU COMMUNISME ?

Nous avons proposé, au chapitre 5, une explication paradoxale : la démocratie a prospéré comme la sœur jumelle du communisme précisément parce qu’elle facilitait le contrôle sans entraves des ressources par l’État. Cette conclusion peut sembler absurde au « bon sens » de l’ère industrielle. Nous ne nions pas que, dans les termes de la société industrielle, systèmes démocratiques et communisme constituaient des opposés tranchés. Mais d’un point de vue mégapolitique, et tels qu’ils pourraient plus probablement être perçus depuis l’Âge de l’Information, ces deux systèmes avaient plus en commun qu’on ne pourrait le soupçonner.

Dans un contexte où l’armement était exorbitamment coûteux, la démocratie est devenue le mécanisme de décision qui maximisait le contrôle de l’État sur les ressources. Tout comme le socialisme d’État, les systèmes démocratiques permettaient de mobiliser d’énormes sommes pour financer une armée gigantesque. La différence réside dans le fait que l’État-providence démocratique plaçait encore davantage de ressources à la disposition de l’État que ne le pouvaient les systèmes socialistes d’État. C’est dire, puisque ces derniers, ou systèmes communistes, s’appropriaient pratiquement tout actif ayant la moindre valeur.

En étant considérée avec sang-froid comme un simple mécanisme de collecte des ressources, l’État démocratique surpassait l’État socialiste dans sa capacité à enrichir l’État. Comme nous l’avons expliqué précédemment, la démocratie permettait de mettre substantiellement plus d’argent à la disposition de l’armée parce qu’elle était compatible avec la propriété privée et la productivité capitaliste.

Le système socialiste d’État reposait sur la doctrine de la propriété intégrale par l’État. L’État-providence démocratique, en revanche, formulait des revendications initiales plus limitées. Il prétendait autoriser la propriété privée, bien qu’il ne s’agisse que d’une forme de propriété conditionnelle, et mobilisait ainsi de meilleurs incitatifs à la production. Au lieu de tout mal gérer d’emblée, les gouvernements démocratiques occidentaux permettaient aux individus de posséder des biens et d’accumuler des richesses. Ce n’était qu’une fois la richesse créée que les États-nations démocratiques intervenaient pour en confisquer une large part via l’impôt.

Le mot « large » devrait être mis en majuscules. Par exemple, en 1996, le taux d’imposition fédéral, sur toute une vie, atteignait soixante-treize cents pour chaque dollar gagné aux États-Unis. Pour les propriétaires de sociétés recevant leurs revenus sous forme de dividendes, ce taux s’élevait à quatre-vingt-trois cents par dollar. Et pour ceux qui cherchaient à transmettre ou donner de l’argent à leurs petits-enfants, ce taux fédéral s’élevait à quatre-vingt-treize cents par dollar. En tenant compte des taxes étatiques et locales, les gouvernements démocratiques, à tous les niveaux, confisquaient la plus grande partie de chaque dollar gagné aux États-Unis. Des taux d’imposition aussi prédateurs faisaient de l’État démocratique un partenaire de fait, prélevant entre les trois quarts et les neuf dixièmes de tous les revenus. Bien sûr, ce n’était pas la même chose que le socialisme d’État. Mais c’en était un proche parent.

L’État démocratique a survécu plus longtemps parce qu’il se montrait plus souple et récoltait des quantités de ressources bien plus impressionnantes que celles dont disposaient Moscou ou Berlin-Est.

### « L’inefficacité là où c’était important »

Nous avons décrit les avantages mégapolitiques de la démocratie comme un mode de prise de décision au service d’un gouvernement puissant que l’on peut résumer par « l’inefficacité là où c’était important ». Comparée au communisme, l’État-providence était assurément un système bien plus efficace. Mais comparée à l’exemple authentiquement libéral de Hong Kong, l’État-providence se montrait inefficace. Les taux de croissance à Hong Kong étaient spectaculaires ; leur supériorité venait précisément du fait que le résident de Hong Kong, et non le gouvernement, empochait 85 % des bénéfices d’une croissance plus rapide.

Hong Kong, naturellement, n’est pas une démocratie. En effet, cela correspond bien à l’idée de ce type de juridiction dont nous prévoyons la prospérité à l’Âge de l’Information. Pendant l’ère industrielle, Hong Kong n’avait pas besoin d’être une démocratie puisqu’elle échappait à la contrainte fort peu plaisante de devoir rassembler des ressources pour financer une imposante armée. Hong Kong était protégée de l’extérieur, elle pouvait donc s’offrir le luxe de tenir une économie réellement libre.

C’est précisément la capacité de mobiliser des ressources qui a assuré le triomphe de la démocratie sous les conditions mégapolitiques de l’ère industrielle. La démocratie de masse allait de pair avec l’industrialisation. Comme l’a dit Alvin Toffler, la démocratie de masse « est l’expression politique de la production de masse, de la distribution de masse, de la consommation de masse, de l’éducation de masse, des médias de masse, des divertissements de masse et de tout le reste »[^433].

Maintenant que la technologie de l’information supplante la production de masse, il est logique de s’attendre à voir se profiler le crépuscule de la démocratie de masse. L’impératif mégapolitique crucial qui avait fait triompher la démocratie de masse au cours de l’ère industrielle a disparu. Il n’est donc plus qu’une question de temps avant que la démocratie de masse n’imite la destinée de sa sœur jumelle, le communisme.

### La démocratie de masse est-elle incompatible avec l’Âge de l’Information ?

Une brève réflexion montre que la technologie de l’Âge de l’Information n’est pas intrinsèquement une technologie de masse. Militairement parlant, comme nous l’avons indiqué, elle ouvre la voie aux « armes intelligentes » et à la « guerre de l’information », wherein des « bombes logiques » pourraient saboter des systèmes de commandement et contrôle centralisés. Non seulement la technologie de l’information oriente nettement vers la mise au point d’armes spécialisées, mais elle réduit également le caractère décisif de la guerre en améliorant la position relative de la défense. La microtechnologie rend possibles des gains considérables en matière de puissance militaire individuelle, tout en diminuant l’importance des grandes formations d’infanterie. Comme le signale la Rand Corporation dans un rapport destiné au secrétaire à la Défense : « Des réseaux interconnectés peuvent être la cible d’attaques et de perturbations non seulement de la part d’États, mais aussi d’acteurs non étatiques, y compris des groupes dispersés, voire des individus »[^434]. Qui plus est, cela implique que la cyberguerre mettra en évidence les déséconomies d’échelle inhérentes aux systèmes centralisés de masse.

Selon les experts de la Rand, « Les techniques fondées sur l’information rendent la distance géographique non pertinente ; des cibles sur le territoire continental des États-Unis sont tout aussi vulnérables que des agents en zone de conflit »[^435]. Alors qu’autrefois, la résidence sur le territoire d’un grand État-nation superpuissant comme les États-Unis impliquait une relative sécurité géographique, en revanche, à l’Âge de l’Information, la logique de l’agrégation du pouvoir pourrait basculer. Peoria est peut-être loin de tout front militaire potentiel, mais ne sera plus à l’abri d’une cyberattaque menée par presque n’importe quel adversaire possible. Résider dans les frontières d’une superpuissance, cela signifiera se localiser en plein cœur de la cible. En lieu et place de fédérations, on peut s’attendre à ce que les localités gagnent en sécurité en se désagrégeant. L’émergence de la cyberguerre augmentera la vulnérabilité des systèmes de commandement et de contrôle centralisés, tout en rendant plus compétitifs des systèmes dispersés.

Les mécanismes de rétroaction déclenchés par ces évolutions pourraient accélérer ce processus de décentralisation. Comme le suggèrent les experts de la Rand, pour réduire la vulnérabilité des systèmes de commandement et de contrôle face à la cyberattaque (systèmes développés durant les dernières étapes de l’État-nation), le gouvernement devra intensifier « l’exploitation des nouvelles techniques de chiffrement logiciel ». Cela rendra ces systèmes, majoritairement gérés par le secteur privé, bien moins vulnérables au sabotage et favorisera la large diffusion commerciale du chiffrement robuste, ce qui contribuera à les émanciper de la domination étatique. Cela aussi donnera un coup de fouet à la décentralisation. Comme nous l’avons fait valoir, ce phénomène propulsera davantage la dispersion des ressources dans le cyberespace, où elles s’affranchiront du poids de la politique.

En fin de compte, cela signifie la fin de la démocratie de masse, en particulier dans sa forme prédominante de gouvernement représentatif défaillant, qu’il soit de type parlementaire ou congressiste.

## LES MÉGAPOLITIQUES DE LA FALSIFICATION REPRÉSENTATIVE

Quand les conditions mégapolitiques se transforment radicalement, comme c’est le cas actuellement, l’organisation gouvernementale se trouve elle aussi inévitablement modifiée. De fait, la forme du gouvernement représentatif a toujours été liée à la répartition de la force brute. Cette réalité se manifeste lorsqu’on observe que les représentants sont désignés sur une base géographique, plutôt que selon un autre critère.

Réfléchissons-y. En principe, une assemblée législative serait tout aussi « démocratique » si ses membres étaient choisis selon n’importe quel découpage arbitraire de la population. Les circonscriptions législatives ou parlementaires pourraient se fonder sur les dates d’anniversaire, ou même sur un ordre alphabétique. Par exemple, tous ceux qui sont nés le 1ᵉʳ janvier pourraient voter parmi une liste de candidats ; ceux qui sont nés le 2 janvier parmi une autre ; ou bien, tous ceux dont le nom commence par « Aa » à « Af » pourraient voter pour une liste donnée, ceux dont le nom commence par « Ag » pour une autre, etc.

Aucun système de ce genre n’existe à ce jour pour plusieurs raisons. La première, suffisante à elle seule, est que c’était irréalisable sur le plan technologique au XVIIIᵉ siècle. Mais plus important encore, un découpage par dates d’anniversaire ou par initiales n’aurait pas rendu compte, ni même approché, la répartition de la force brute que le scrutin devait représenter à l’époque. Des personnes partageant seulement la même date de naissance ou les mêmes premières lettres de leur nom auraient été, et resteraient, extrêmement difficiles à organiser en un groupe cohérent, susceptible de constituer une base de pouvoir.

### Pourquoi un découpage géographique compte-t-il davantage ?

En fait, le vote est véritablement apparu comme un substitut aux affrontements militaires. Et il fonctionne encore ainsi, bien que de manière voilée. On peut aisément mener des combats en s’appuyant sur une organisation géographique, plus rarement sur des liens de parenté ou de religion. Mais on ne peut pas efficacement monter une armée en se basant sur des anniversaires ou des initiales ; ni même sur des métiers, sauf dans les cas où les métiers sont associés à des guildes héréditaires, comme dans les castes indiennes, ou quand ils se regroupent localement, à l’instar des agriculteurs de l’Iowa.

L’idée maîtresse des formules de représentation actuelles est la représentation d’intérêts ancrés dans une zone géographique, plutôt que dans un autre type de découpage. Dans l’histoire, l’élément clé de la réussite militaire a été le contrôle du territoire. Toutes les menaces militaires ont toujours pris forme localement. Les systèmes représentatifs sont conçus pour permettre à ce pouvoir de s’exprimer dans une autre arène. Le fait qu’ils aient inévitablement tendance à faire prévaloir les intérêts locaux est la conséquence directe de cette formule de représentation. Les circonscriptions géographiques poussent les représentants à accorder des faveurs ciblées à des groupes particuliers, au détriment des intérêts communs à tous les résidents d’un pays.

### De nouvelles possibilités à l’horizon

Comme les analyses des économistes du Public Choice l’ont montré, même de légères modifications dans la manière dont une élection est structurée ou dont le vote est décompté ont d’importantes conséquences prévisibles sur le résultat[^436]. C’est pourquoi toutes les personnes sérieuses dans l’étude des phénomènes politiques actuels doivent être également versées dans la connaissance des constitutions. Et c’est l’une des raisons qui nous ont incités à examiner non seulement les constitutions, mais aussi la métaconstitution, c’est-à-dire les facteurs mégapolitiques dominants dans un contexte donné.

Le progrès technique a déjà balayé certains des fondements du découpage géographique des électeurs. Quand les systèmes représentatifs modernes ont vu le jour entre le XVIIIᵉ et le XIXᵉ siècle, presque toutes les communications étaient locales. La plupart des gens naissaient et mouraient à quelques kilomètres de leur lieu de naissance, et l’ensemble de leur commerce et de leurs échanges restait cantonné à l’échelle locale. Désormais, la communication instantanée est mondiale. Vous pouvez traiter une affaire avec quelqu’un situé à plusieurs milliers de kilomètres presque aussi aisément qu’avec un voisin. De plus en plus, l’économie transcende les limitations géographiques. La société est bien plus mobile.

Et il en va de même pour la richesse à l’Âge de l’Information. Contrairement à une aciérie, un programme informatique ne peut guère être retenu en otage par le processus politique local. Une aciérie est pratiquement inamovible lorsque les législateurs décident d’augmenter les impôts ou de renforcer la réglementation. Un programme informatique, lui, peut être transféré en un éclair par modem n’importe où sur la planète. Son propriétaire peut fermer son ordinateur portable et s’envoler à l’autre bout du monde. Cela aussi fragilise les bases mégapolitiques du découpage géographique.

Un problème sérieux qui se pose dans tous les systèmes démocratiques actuels, au vu de notre analyse, est que leurs circonscriptions géographiques surreprésentent invariablement les intérêts enracinés dans l’ère industrielle. Les « perdants » ou les « laissés-pour-compte » représentent des électeurs parfaits, car ils sont géographiquement concentrés et politiquement en demande. L’histoire de la démocratie industrielle en apporte maintes preuves. Les « gagnants » issus des nouvelles industries ont systématiquement été sous-représentés dans les délibérations législatives, même au plus fort de l’ère industrielle, dans les années 1930[^437]. La tendance qu’ont les responsables politiques à représenter en priorité les concurrents déjà établis, plutôt que les nouvelles entreprises susceptibles d’émerger ou les futurs clients de ces entreprises, est sans doute inhérente au gouvernement représentatif. Comme l’a soutenu Mancur Olson dans *The Rise and Decline of Nations*, les industries en place de longue date ont tendance à former des « coalitions de répartition » plus efficaces pour faire du lobbying et se partager les dépouilles politiques[^438].

Ce problème prend une ampleur immense quand il s’agit de l’économie de l’Âge de l’Information. Les acteurs les plus créatifs de la nouvelle économie sont dispersés géographiquement. Par conséquent, il est peu probable qu’ils forment une masse suffisante pour attirer l’attention des législateurs, à l’inverse des pêcheurs de saumon d’Écosse ou des cultivateurs de blé de la Saskatchewan. Qui plus est, nombre de personnalités dynamiques participant à la nouvelle économie n’auront même pas la nationalité du plus vaste État-nation. Elles n’auront donc aucune « voix » officielle dans les délibérations législatives d’une démocratie représentative. À titre d’exemple éloquent, on peut citer l’effort douteux de certains docteurs en mathématiques américains, réclamant que l’on empêche l’accès des mathématiciens étrangers au marché de l’emploi aux États-Unis[^439]. Leurs représentations xénophobes auprès du Congrès pour interdire l’embauche sur la base du talent pourraient malheureusement être entendues. Le découpage géographique hérité de l’ère industrielle ne prend absolument pas en compte les mathématiciens étrangers ni tous les autres contributeurs essentiels à la prospérité qui ne disposent pas du droit de vote.

> « Pourquoi les gens croient-ils à la légitimité de ces institutions démocratiques ? Y répondre est presque aussi difficile qu’expliquer pourquoi des individus adhèrent à telle croyance religieuse : selon les cas, compréhension, scepticisme et foi varient considérablement au sein de la société et dans le temps. »[^440] - JUAN J. LINZ

Peu nombreux sont ceux qui ont entamé une réflexion sérieuse sur les conséquences des transformations technologiques affaiblissant l’industrialisation et modifiant les répartitions de revenus. De toute évidence, s’il est vrai que les écarts de revenus se mettront à diverger au point que la démocratie n’équivaut plus qu’à une méthode de parasitisme légalisé, la question se posera sous une forme aiguë. Plus rares encore sont ceux qui ont mesuré à quel point certaines institutions étatiques propres à l’ère industrielle pourraient se révéler incompatibles avec la réalité mégapolitique de la société postindustrielle. Que ces contradictions soient reconnues publiquement ou non, leurs conséquences n’en seront pas moins évidentes au fur et à mesure que de nouveaux exemples d’échec politique s’accumuleront un peu partout. Les États qui ont vu le jour à l’époque moderne sont le reflet de conditions mégapolitiques vieilles de plusieurs siècles. Ils ont traversé la transition d’une société agraire à une société urbaine et industrielle. Mais l’Âge de l’Information exigera peut-être de nouveaux mécanismes de représentation capables d’éviter la désorganisation chronique, voire un effondrement similaire à celui de l’Union soviétique.

On peut s’attendre à des crises de mauvaise gestion gouvernementale dans de nombreux pays, à mesure que les promesses politiques se dégonfleront et que les gouvernements épuiseront leurs crédits et leur soutien institutionnel. En fin de compte, de nouvelles formes institutionnelles devront émerger, susceptibles de préserver la liberté dans les conditions technologiques inédites, tout en donnant vie et expression à l’intérêt commun.

Tout cela annonce la fin de la démocratie de masse telle que nous l’avons connue au XXᵉ siècle. La question est : qu’est-ce qui va la remplacer ? Si la seule alternative à la démocratie de masse était la dictature, où l’individu n’a aucun mot à dire sur son destin, on pourrait être tenté de rejoindre les néo-luddites dans leur « révolte contre l’avenir ».

### De nouvelles institutions

Heureusement, la dictature n’est pas la seule alternative à la démocratie de masse. La technologie de l’information facilite le choix. Plutôt qu’un choix global et collectif, circonscrit par la « production de masse, la consommation de masse, l’éducation de masse, les médias de masse, les divertissements de masse et tout le reste », la technologie de l’information rend possible un choix véritablement individuel, proposant une « souveraineté » adaptée aux besoins de chacun. Cela deviendra possible parce que la grande échelle ne sera plus un impératif. Nous pensons que la technologie de l’Âge de l’Information fera apparaître de nouvelles formes de gouvernance, tout comme la révolution agricole et, plus tard, l’ère industrielle avaient fait émerger leurs propres formes distinctives d’organisation sociale.

Comment se manifesteront ces nouvelles institutions ? Pour comprendre, oubliez tout ce que vous avez lu dans les prétendus manuels de « science » politique. Les nouvelles institutions de gouvernance pour l’Âge de l’Information dépasseront le cadre conceptuel habituel. La progression vers ces institutions du nouvel âge a déjà commencé, bien que de façon peu discernable, par des bricolages visant à réagencer des actifs sous-exploités : les bénéfices de la souveraineté. Les États-nations de la planète, nerveux en voyant poindre des mouvements sécessionnistes et une forte poussée vers la décentralisation, se sont regroupés pour former le plus puissant « cartel de fixation des frontières » que l’on puisse imposer. Certes, le nombre d’États indépendants a augmenté dans les années 1990, mais cela est survenu principalement en deux salves, à la suite de l’effondrement de dictatures communistes pluriethniques en ex-URSS et en ex-Yougoslavie. Il faut noter que d’autres États-nations de premier plan, dont les États-Unis, ont manœuvré pour préserver l’Union soviétique aussi longtemps que possible. Et peu de gouvernements se sont réjouis du démantèlement de la Yougoslavie. L’indépendance des anciennes républiques yougoslaves n’a été reconnue qu’après que leurs partisans de la sécession eurent pris le contrôle par la force militaire. Les grandes puissances se contentaient de regarder, tandis que des séparatistes non ou mal armés se faisaient massacrer par leurs bourreaux serbes. Même la Chine, pays puissant sans intérêt direct dans la préservation de cette Yougoslavie résiduelle, s’est vigoureusement opposée à toute initiative visant à faire reconnaître l’autodétermination des Albanais opprimés du Kosovo. Ironiquement, cette obsession de la fixation des frontières est plus susceptible de façonner le cheminement de la décentralisation, par une souveraineté fragmentée, que de la freiner réellement. La résistance acharnée de tant d’États-nations, fragiles, à l’égard de la sécession affichée et de la désagrégation politique rend la souveraineté reconnue extrêmement précieuse ; celle-ci devient alors un capital transcendantal que les États qui la possèdent peuvent fragmenter et sous-louer volontairement.

Un exemple de fragmentation volontaire de la souveraineté, créant de fait une juridiction privée hors taxes, se retrouve dans le projet *Agulhas Bay Concession Free Zone*, qui recouvre cinquante kilomètres carrés de l’île de Principe, au large de l’Afrique de l’Ouest. Bien que ce territoire demeure placé sous la souveraineté de la République démocratique de Sao Tomé-et-Principe, l’administration de la zone est confiée au secteur privé. La gouvernance y est régie par contrat, sous la responsabilité de WADCO (*West African Development Corporation Ltd.*), une société privée enregistrée en Afrique du Sud. La langue officielle de la zone n’est pas le portugais (langue officielle de Sao Tomé-et-Principe) mais l’anglais. La monnaie autorisée n’est pas la devise locale (largement fantaisiste) du pays, mais bien la monnaie mondiale, le dollar américain. La sécurité est assurée non par les forces de police de la République démocratique de Sao Tomé-et-Principe, mais par la police privée de WADCO. La loi commerciale de Sao Tomé ne s’applique pas dans la zone, et les tribunaux sao-toméens n’ont aucune compétence sur les différends, lesquels sont tranchés par arbitrage transnational, selon les règles de l’ICC de Paris. Exception faite de quelques taxes minimes et strictement encadrées, la fiscalité de Sao Tomé n’entre pas en vigueur dans la zone, pas plus que ses monopoles officiels. Les télécommunications y sont, par exemple, automatiquement déréglementées. Sous réserve du paiement d’un loyer et du respect des autres dispositions de la concession, WADCO est en droit de renouveler automatiquement et de manière répétée son bail de souveraineté privée et fragmentée, par tranches de cinquante ans, à compter de la première échéance, en 2047.

Ce que WADCO a obtenu à Sao Tomé-et-Principe pourra être reproduit tôt ou tard par d’autres, dans des juridictions diverses. L’un des grands précurseurs du développement au XXIᵉ siècle, Joaquin Aguirre, a créé une zone similaire de souveraineté privée au *Central Aguirre Portuaria*, dans l’est de la Bolivie. Aguirre, multimillionnaire, romancier, inventeur, cofondateur de l’ONU, et ancien sénateur de la République bolivienne, a été un pionnier à de maintes reprises. Cinquante ans après sa participation fondatrice à l’ONU, Aguirre incarne désormais une figure exemplaire de l’Individu souverain du XXIᵉ siècle. Dans sa *Zona Franca*, qui échappe pour l’essentiel aux fiscalités, droits de douane et réglementations boliviens, il offre un modèle de cité-État privatisée qui, selon nous, se multipliera à l’Âge de l’Information. De plus, cela montre de façon indéniable que les classes populaires, dont on a tant chanté les louanges au service du « Big Government » (gros État), peuvent réellement voir leur sort s’améliorer grandement grâce à l’essor économique impulsé par ce type de zones franches, comme celle qu’a développée Aguirre. Avec le temps, de nombreuses cités-États de fait devraient ainsi voir le jour. Et si vous-même parvenez à acquérir une indépendance financière suffisante, vous pourrez atteindre l’ultime indépendance, à l’image de Joaquin Aguirre. Dans l’éventualité où aucun autre fragment de souveraineté commerciale ne vous offrirait un cadre de vie accueillant, vous disposerez de la possibilité de lancer votre propre micro-État propriétaire, indépendant au même titre que les duchés médiévaux. Plutôt que de livrer un bras de fer avec des démagogues et des politiciens avides pour les empêcher de vous prendre vos biens et de les redistribuer aux innombrables mains tendues qui composent la démocratie de masse, vous pourrez instaurer votre propre domaine de gouvernance privée.

Cette transition spectaculaire, de la démocratie de masse à la forme ultime d’autogouvernance, c’est-à-dire la souveraineté individuelle, n’exigera pas forcément un bouleversement radical de l’opinion publique ni un improbable vote révolutionnaire par lequel des électeurs désabusés décideraient de balayer la démocratie de masse. Une telle révolution peut émerger, et a déjà commencé de façon invisible, par la location de territoires souverains à usage de zones franches, de « Zona Francas », et de ports francs. Progressivement, la souveraineté se fragmentera à maintes reprises, jusqu’à ce qu’elle devienne si morcelée que tout fractionnement supplémentaire ne générerait pas un bénéfice suffisant pour justifier les coûts de transaction inhérents à la décentralisation. Étant donné la loi de Moore et la « corollaire de Gilder », selon lequel la puissance de la bande passante triple chaque année, rien ne laisse supposer qu’un frein rapide puisse s’opposer à la tendance à la dévolution. Au contraire, nous pensons que l’impressionnant pouvoir dont disposent actuellement les États-nations consacrés à la démocratie de masse se pulvérisera en milliers, voire en dizaines de milliers de fragments, dans un système plus proche de la période médiévale que de l’ère industrielle.

Tôt ou tard, même des États-nations conservant la forme résiduelle d’une démocratie de masse modifieront sensiblement leur politiques pour s’accorder aux nouvelles réalités métaconstitutionnelles. Ainsi que le relève William Keech, un fervent défenseur de la démocratie, dans *Economic Politics: The Costs of Democracy* : « Les gens apprennent à désirer ce qu’ils voient possible d’obtenir, mais ils peuvent aussi changer d’avis s’ils constatent que ce qu’ils ont obtenu leur déplaît »[^441]. En d’autres termes, le fait que, en cette fin de XXᵉ siècle, la démocratie de masse repose partout sur les plus grands éloges, pourrait bien constituer un « signal de vente ». Cela ne garantit en rien la survie de ces règles de décision, fût-ce selon leurs propres critères. Rappelons qu’en dehors du domaine politique, on ne voit guère d’indices attestant de la sélection de cadres dirigeants, d’administrateurs, d’entraîneurs ou d’autres professionnels par un vote démocratique. Bien au contraire, on recrute systématiquement les chefs les plus compétents à l’initiative des propriétaires, via des processus de sélection dans lesquels ceux qui possèdent le plus d’intérêts en jeu bénéficient d’une voix inégalée et beaucoup plus déterminante quant au choix final. Si la sélection démocratique était réellement la méthode universelle pour parvenir à sélectionner des leaders compétents, on la retrouverait confinée exactement là où elle est aujourd’hui : la sphère politique. En somme, à partir de l’information disponible, il est raisonnable de conclure que la fourniture de services de souveraineté est freinée par la primauté que s’est arrogée la démocratie dans le processus de décision, plutôt que l’inverse (c’est-à-dire que les organisations commerciales subiraient un handicap inacceptable du fait qu’elles seraient dirigées par des responsables nommés plutôt qu’élus).

Aux alentours du milieu du XXIᵉ siècle, la prolifération de juridictions propriétaires fondées sur une souveraineté fragmentée aura probablement démontré de façon irréfutable les avantages d’une administration de nature propriétaire. Les électeurs en viendront à réaliser qu’ils souffrent de la lourdeur de la démocratie de masse. Dès lors, comme Keech le suggère, ils reconnaîtront que les avantages qu’ils tirent d’un gouvernement sous le contrôle des fonctionnaires ne compensent pas ses inconvénients. Ils se dirigeront vers la réforme. Même les corps électoraux d’Europe et d’Amérique du Nord, aujourd’hui résolument hostiles aux réformes, pourraient, à terme, voter pour rendre leurs régions plus accueillantes à la gouvernance propriétaire. Des majorités pourraient accepter, voire accueillir avec joie, l’abandon de la farce politique au profit d’une gestion de nature propriétaire, dont l’objectif explicite serait d’optimiser la configuration nécessaire à la conclusion et l’exécution des contrats.

Pour ce qui est de la survie de l’État, dans sa forme plus ou moins habituelle, il pourrait encore perdurer, mais avec des contours complètement renouvelés. Quelque part, dans une juridiction quelconque, à un moment encore indéfini mais avant la fin des temps, certains verront l’opportunité qu’offrent les technologies informatiques pour rendre réelle une représentation gouvernementale effective. Le problème supposé des dépenses électorales excessives et la lassitude provoquée par d’interminables campagnes pourraient être résolus instantanément. Plutôt que d’être élus, les représentants pourraient être désignés par tirage au sort, ce qui assurerait une forte probabilité statistique que leurs talents et leurs opinions correspondent à ceux de la population en général.

Ce serait une version moderne du vieux système grec consistant à constituer un pouvoir par le lot. Comme le décrit en détail E. S. Staveley dans son histoire de référence, *Greek and Roman Voting and Elections*, diverses fonctions à Athènes, des magistratures aux archontes, étaient désignées par tirage au sort pour remplacer l’élection. Ce système s’appuyait sur une machine d’attribution, connue des Athéniens sous le nom de « cleroterion »[^442].

On utilisait une série de fèves noires et blanches comme compteurs aléatoires pour déterminer qui serait choisi pour remplir diverses fonctions, ainsi que « pour fixer l’ordre dans lequel les sections tribales au Conseil devaient se succéder dans le rôle de prytaneis »[^443]. L’ancienneté de ce modèle lui confère une solide légitimité. Mais son principal attrait est qu’il éviterait les écueils de l’auto-sélection en politique. Il garantirait statistiquement qu’un nombre moins disproportionné d’avocats et d’égomanes accaparent les affaires publiques.

Les corps législatifs pourraient ainsi se composer de représentants réellement « représentatifs ». Puisqu’ils ne se seraient pas rassemblés dans la poursuite du pouvoir, et qu’ils ne pourraient guère espérer être à nouveau tirés au sort, les élus pourraient s’acquitter librement de la conduite des affaires gouvernementales et élaborer leur politique sur la base d’analyses rationnelles des enjeux.

### Payer les élus à la commission

Aujourd’hui, les politiciens soucieux d’optimiser leurs voix ont peu d’intérêt à analyser sérieusement les défis à affronter. Il n’est pas étonnant que leur bilan dans la résolution concrète des problèmes soit si médiocre en comparaison de celui des entrepreneurs, des chefs d’entreprise ou des entraîneurs sportifs, qui sont rétribués sur la base de leurs résultats. Un système de rémunération indexé sur des critères de performance, appliqué aux législateurs, ne ferait pas de tous les tirés au sort des « Lee Kuan Yew ». Mais il accroîtrait probablement de mille fois la chance de voir un meilleur rendement, si la rétribution était proportionnelle à un indicateur objectif comme l’augmentation du revenu par habitant net d’impôt.

Le profit pour la société découlant de politiques de croissance meilleure (en termes de revenu réel après impôts) pourrait être énorme. Pourquoi ne pas rémunérer les Premiers ministres et Présidents selon, ne serait-ce, qu’une fraction des gains nets procurés par leurs initiatives ? Le budget de ces rémunérations pourrait être couvert par un petit impôt discret. Une telle formule libérerait la société de la menace que font peser aujourd’hui des ambitieux aux talents politiques spécifiques, tels que Richard Nixon ou Bill Clinton.

> « On lui apportait de l’or, de l’argent, des vêtements ; mais le ‘Christ’ redistribuait tout cela aux pauvres. Quand on lui offrait des présents, lui et sa compagne se prosternaient et prononçaient des prières ; puis, se relevant, il ordonnait à l’assemblée de l’adorer. Par la suite, il formait un groupe armé avec lequel il sillonnait la campagne, détroussant les voyageurs rencontrés sur sa route… Mais, là non plus, son ambition n’était pas de s’enrichir, mais de se faire adorer. Il redistribuait tout le butin à ceux qui n’avaient rien – y compris, on peut le présumer, à ses propres partisans. »[^444] – NORMAN COHN

### Des personnalités messianiques

On a trop peu souligné le fait que la politique électorale attire souvent des personnalités messianiques et déséquilibrées dans des postes de pouvoir. Ces personnes ont toujours existé et, même avant l’avènement des systèmes démocratiques modernes, elles ont déjà pu constituer une menace pour l’ordre social au sein des sociétés agraires. Quand on passe en revue les carrières d’Eudo de Stell, surnommé le Christ breton, d’Adelbert au VIIIᵉ siècle, d’Éon au XIᵉ, de Tanchelm d’Anvers, de Melchior Hoffman ou de Bernt Rothmann, plusieurs éléments ressortent. Plus leurs talents politiques paraissaient évidents, plus ils semblaient faire de dégâts. Parce que l’État n’exerçait pas encore de coercition généralisée, ces proto-politiques recouraient souvent eux-mêmes au vol et au pillage pour obtenir l’argent qu’ils distribuaient à leurs partisans, souvent pauvres.

### Les proto-politiques en action

Le récit de leurs frasques donne l’impression de personnes dotées de talents nés avant l’heure, comme si l’on lisait l’histoire d’hommes de plus de deux mètres courant sur un terrain avant l’invention du basketball. Aujourd’hui, grâce à la NBA, des hommes extrêmement grands peuvent gagner des millions en dribblant et en dunkant. Si le basketball n’existait pas, ils se fondraient à nouveau dans les marges de la société, apparaissant peut-être comme curiosités foraines dans diverses foires.

À l’époque où la politique n’existait pas en tant que telle, les démagogues se rabattaient sur ce qui s’en rapprochait le plus dans l’univers agraire : la prédication itinérante. Ils haranguaient la foule et, tels des politiciens mieux connus, promettaient éloquemment une vie meilleure à ceux qui les suivaient. Alors comme aujourd’hui, les populations pauvres constituaient la cible majeure de ces agitateurs. Dans son imposante histoire des mouvements millénaristes, *The Pursuit of the Millennium*, Norman Cohn relate de nombreux épisodes de chefs messianiques antérieurs à l’avènement du scrutin. En lisant cet ouvrage, on ne peut manquer de deviner un fort air de parenté entre ces *prophetae* et le politicien charismatique de l’ère moderne : la faconde, le « charisme personnel », les prétentions messianiques et le désir récurrent d’être adoré comme le porte-parole des pauvres.

> [T]he leader possède – à l'instar du pharaon et de bien d'autres « rois divins » – tous les attributs d'un père idéal : il est parfaitement sage, il est parfaitement juste, il protège les faibles. Mais, d'autre part, il est aussi le fils dont la mission est de transformer le monde, le Messie qui doit établir un nouveau ciel et une nouvelle terre et qui peut se déclarer lui-même : « Voici, je rends toutes choses nouvelles ! » Et, tant en tant que père qu'en tant que fils, cette figure est colossale, surhumaine, omnipotente. On lui attribue une telle abondance de pouvoirs surnaturels qu'on l'imagine émaner sous forme de lumière. ... De plus, étant ainsi rempli de cet esprit divin, le leader eschatologique possède des pouvoirs miraculeux uniques. Ses armées seront invariablement et triomphalement victorieuses, sa présence fera que la terre produira des récoltes, et son règne sera une ère d'une harmonie si parfaite que le vieux monde corrompu n'en a jamais connu.

> Cette image était, bien entendu, purement fantastique, dans la mesure où elle n'avait aucun rapport avec la nature réelle et la capacité de tout être humain ayant jamais existé ou pouvant jamais exister. Il s'agissait néanmoins d'une image que l'on pouvait projeter sur un homme vivant ; et il y avait toujours des hommes tout à fait disposés à accepter une telle projection, qui, en fait, désiraient ardemment être perçus comme des sauveurs infaillibles, capables d'opérer des miracles. ... Et le secret de l'ascendant qu'ils exerçaient ne résidait ni dans leur naissance, ni, dans une large mesure, dans leur éducation, mais toujours dans leurs personnalités. Les récits contemporains de ces messies des pauvres mettent couramment en avant leur éloquence, leur prestance et leur magnétisme personnel. Surtout, on a l'impression que, même si certains de ces hommes ont peut-être été des imposteurs conscients, la plupart d'entre eux se considéraient réellement comme des dieux incarnés. . . . Et cette conviction totale se communiquait aisément aux multitudes dont le désir le plus profond était précisément celui d'un sauveur eschatologique. [^445]

Bien que ce passage soit merveilleusement concis dans la description des prétendus sauveurs millénaristes qui perturbaient fréquemment la société médiévale, il ne peut rendre pleinement compte de toute la saveur de l'examen magistral de Cohn. On ne peut lire l'ensemble de l'œuvre sans reconnaître dans les pitreries de ces prophètes les caractéristiques familières du démagogue moderne : l'éloquence, « le magnétisme personnel », « les prétentions messianiques » et le désir récurrent d'être adoré en tant que tribune des pauvres.

La principale différence que l’on constate entre l’accueil que réservait la société médiévale à ces imposteurs et celui dont ils bénéficient dans la démocratie au tournant du XXᵉ siècle est qu’au Moyen Âge, de tels individus finissaient généralement exécutés, tandis qu’en fin de XXᵉ siècle, la politique démocratique leur offrait toutes les conditions légitimes pour prendre en main l’appareil d’État.

Un système qui confie régulièrement la direction de ses immenses et mortels appareils à l’homme le plus populaire, choisi selon un affrontement de talents démagogiques, est voué à en payer tôt ou tard les conséquences.

### Payer les dirigeants pour bien faire leur travail

Ainsi, comme nous l’avons suggéré plus haut, il serait relativement simple d’établir une méthode plus efficiente pour confier la direction à des personnes compétentes : leur proposer un poste remunéré. C’est le mode de recrutement le plus répandu et le plus fructueux dans toutes les économies concurrentielles. Allier une procédure rationnelle de sélection et un système d’incitations constructif incitant à viser l’excellence serait, pour l’appareil d’État, un moyen infaillible d’attirer des responsables chevronnés. De plus, cela permettrait de mettre en lice de nouveaux talents qui, autrement, ne prendraient jamais goût aux problèmes de gouvernance.

Les cadres les plus brillants au monde seraient tentés de relever les défis d’un gouvernement défaillant s’ils pouvaient se voir rémunérés en fonction des résultats qu’ils apportent concrètement à la société. Un responsable capable de stimuler sensiblement le revenu réel dans un État occidental pleinement développé pourrait justifier de toucher un salaire même plus élevé que Michael Eisner. Dans un monde parfait, tous les chefs de gouvernement performants deviendraient multimillionnaires.

### Les plébiscites électroniques

Une autre piste évidente, pour échapper au gouvernement représentatif défaillant, résiderait dans les plébiscites électroniques, où les citoyens, ou un échantillon représentatif choisi par un tirage au sort infalsifiable, voteraient directement les propositions législatives. Les technologies informatiques permettent de faire valider démocratiquement des décisions via des plébiscites électroniques. On pourrait aisément les combiner avec le mode de l’allotement pour restreindre le nombre de votants sur des mesures particulières. D’une certaine manière, il est moins exigeant pour l’électeur de se forger une opinion sur des questions politiques précises que de tenter de cerner la personnalité d’un candidat, ou d’évaluer l’évaluation faite par ce candidat, sans parler de deviner la conduite qu’il adoptera une fois élu. Cette complexité s’aggrave avec la capacité croissante qu’ont les politiciens et leurs équipes de mise en scène pour manipuler l’image qu’ils présentent au public.

## LA SOUVERAINETÉ COMMERCIALISÉE

Nous nous attendons à ce que quelque chose de totalement différent remplace la politique. Même si chacune des pistes énoncées plus haut pourrait s’avérer applicable ici ou là, nous pensons, pour notre part, que la politique ne sera pas « réformée » ou « améliorée », mais qu’elle va plutôt devenir obsolète, puis abandonnée pour l’essentiel. Toutefois, soulignons que nous ne songeons pas à une dictature, mais plutôt à un gouvernement entrepreneurial : la commercialisation de la souveraineté.

Contrairement à la dictature, ou même à la démocratie, la souveraineté commercialisée n’empêchera pas l’expression des choix. Au contraire, elle offrira à chaque individu davantage de possibilités de faire valoir son point de vue. Pour ceux qui disposent du talent nécessaire afin d’en tirer parti, cette forme de souveraineté autorisera davantage de marge d’action et d’autodétermination pratique que ne l’a fait aucune autre forme d’organisation sociale antérieure.

### Un gouvernement sur mesure

Si cela paraît millénariste, rappelez-vous que la microtechnologie favorise la miniaturisation et la décomposition. Elle permet de passer d’une production de masse à une offre personnalisée. Vous pouvez désormais acheter en magasin un jean taillé sur mesure d’après vos mensurations, et cousu à l’autre bout du monde. Lorsque les nouvelles institutions auront fini par s’adapter à la réalité mégapolitique de l’Âge de l’Information, vous pourrez obtenir une forme de gouvernance aussi parfaitement adaptée à vos besoins et à vos goûts personnels que vos jeans.

Pourtant, Alvin Toffler, de tous les observateurs, a critiqué l’idée selon laquelle la technologie de l’information pourrait faire de chaque citoyen un consommateur. Toffler affirme, à tort selon nous : « C’est un modèle bien trop restreint. Que cela nous plaise ou non, il existe un monde de religion et de sentiments qui ne saurait se réduire à la seule relation contractuelle »[^446]. En suivant les réflexions que nous avons présentées, nous lui concéderions volontiers qu’il n’est pas aisé de « réduire le sentiment nationaliste » à de simples « rapports contractuels ». Ceci étant dit, il n’est pas impossible non plus d’y parvenir, et ce n’a rien d’indésirable. Un nationalisme un peu moins fougueux éviterait, à n’en pas douter, des millions de morts.

### « Sortie », « entrée » et « voix »

Bien sûr, la commercialisation de la souveraineté est un concept étrange, du moins pour ceux qui ne l’ont jamais envisagé, y compris Alvin Toffler. Et pourtant, son principe fondamental – l’expression économique – est familier pour ceux qui vivent à la fin du XXᵉ siècle. Dans une économie quelque peu libre, les consommateurs peuvent exprimer directement leurs désirs en achetant produits et services ou bien en y renonçant. Lorsque vous êtes déçu par un produit ou un service, en particulier s’il est fourni ou fortement contrôlé par l’État, vous pouvez exprimer votre insatisfaction en optant pour la « sortie ». Autrement dit, vous allez dépenser votre argent ailleurs.

Dans les chapitres précédents, nous avons vu comment l’avance des technologies de l’information autorisera désormais la création de biens – et de richesses – placés hors de portée des États-nations. Cela instaurera bel et bien une contrainte métaconstitutionnelle : pour que les gouvernements reçoivent effectivement vos paiements, ils devront vous rendre service de manière satisfaisante. Pourquoi ? Parce que la taxation sur le revenu pourrait devenir presque aussi volontaire en pratique qu’elle l’était en théorie jusqu’ici.

### Échapper aux « canaux politiques lourds »

En réalité, si la technologie de l’information évolue dans les sens que nous soupçonnons, elle donnera la maîtrise effective des gouvernements à leurs clients. En tant que client, vous aurez la possibilité, d’abord par centaines, puis par milliers, de réduire le coût de votre protection en négociant un traité fiscal privé avec un État-nation ou en quittant purement et simplement ces États-nations pour aller dans de nouvelles mini-souverainetés facturant un tarif commercialement raisonnable au lieu de ponctionner la quasi-totalité de votre patrimoine. Ces modes d’« entrée » contractuelle, ou ces décisions de « sortie », constituent des expressions économiques de vos besoins en tant que client. Quitter un pays avec vos biens, ou renoncer à entrer dans sa sphère de souveraineté fiscale, est autrement plus efficace pour obtenir ce que vous voulez que de recourir aux « canaux politiques lourds ».

Comparons vos possibilités de « sortie » et d’« entrée » à l’expression « politique » de la démocratie. Les citoyens qui s’estiment lésés par un bien ou un service (en particulier lorsqu’il s’agit de biens publics financés ou réglementés par l’État) peuvent faire entendre leur « voix » en écrivant au président, aux États-Unis, ou en se rapprochant de leur député, ailleurs. Parfois, ces tentatives fonctionnent. Bien souvent, elles échouent. Alors, la solution est d’organiser une manifestation, d’acheter une pleine page publicitaire dans la presse, voire de briguer un mandat électif.

Le mode d’expression « politique » offre effectivement un débouché à l’éloquence et au sens de la formule. Mais il a l’inconvénient de rendre pratiquement impossible l’obtention de ce que vous espérez sans convaincre toute la structure politique de répondre à votre demande. Si le produit ou le service public vous paraît défaillant, vous restez contraint de financer l’État tant que vous n’avez pas rallié ce lourd processus politique à votre cause, ce qui implique généralement une majorité.

Dans les pays occidentaux, et désormais presque partout, cela signifie devoir recueillir un soutien majoritaire au sein d’un système de démocratie représentative. Ce besoin d’une majorité s’accompagne de coûts de transaction considérables. Entre vous et la réalisation de l’objectif, pourtant clarissime, que vous vous étiez fixé, se dresse un obstacle quasi infranchissable : mobiliser la volonté de tout un peuple.

Milton Friedman, dans *Capitalism and Freedom*, a évoqué les mérites relatifs de l’expression de type économique en opposition à l’expression de type politique, en défendant son idée de « bons scolaires » (vouchers) :

> « Les parents pourraient manifester généralement leurs préférences en retirant leurs enfants d’une école pour les envoyer dans une autre, nettement plus facilement qu’ils ne le peuvent aujourd’hui. Dans la configuration actuelle, pour accomplir un tel changement, il leur faudrait souvent déménager. Dans les autres cas, ils peuvent s’exprimer uniquement par l’intermédiaire de canaux politiques lourds.[^447] »

Albert O. Hirschman, qui était plus partisan de la politique, contesta le jugement de Friedman, lequel voyait dans la « sortie » une voie « directe » pour faire entendre son mécontentement envers une organisation. Selon Hirschman : « Une personne moins nourrie à l’économie naïvement suggérerait que la voie la plus directe pour faire connaître ses idées est de les exprimer ! »[^448]

La question de savoir s’il est plus direct ou plus efficace de faire valoir ses opinions par les mécanismes du marché (en maintenant ou retirant son soutien économique) ou bien par ces « canaux politiques lourds » est complexe et controversée. D’aucuns proposeront des réponses divergentes. Pour ceux dont l’essentiel de l’engagement politique consiste à exiger des bénéfices aux dépens d’autrui, l’abandon du canal politique au profit du mode économique de l’expression paraît en effet plus désolant que d’écrire à un responsable politique pour demander davantage.

### L’expression économique et la « socialité réciproque »

Pour ceux qui souhaitent s’inscrire dans une relation « réciproque » plutôt que « coercitive » ou parasitaire avec leurs semblables, l’expression économique ouvre la possibilité d’une satisfaction bien plus large et à moindre coût en temps et en efforts. Au risque de heurter le Professeur Hirschfield, c’est très facile à démontrer.

Il suffit de considérer que la série d’expressions économiques – nouvelle entrée, conclure un contrat, ou sortir du contrat – peut être convertie en une expression « politique » en faisant de la décision un choix collectif. Tentons l’expérience conceptuelle : trouvez quelques centaines de personnes qui jugent ne pas faire assez de politique. Plutôt que de dépenser chacune leurs revenus discrétionnaires sur des milliers d’achats individuels, elles décident de combiner tous leurs achats pour en faire quelques rares décisions politiques.

Pour commencer, elles acceptent de mettre en commun tout leur revenu disponible, et de renoncer à toute dépense personnelle. Au lieu de milliers de dollars à répartir individuellement selon mille besoins, chacun obtient une ou plusieurs voix, selon le nombre de postes à pourvoir. Plutôt que de dépenser au fur et à mesure votre argent pour acheter ce que vous désirez quand vous le souhaitez, vous dépenseriez votre voix ou vos voix à l’occasion de ces rares élections destinées à sélectionner les représentants qui choisiront la manière de dépenser l’immense budget collectif.

Ensuite, vous partageriez, avec les autres, uniquement ce que le comité dirigeant juge opportun d’acheter au nom de la majorité.

Y voyez-vous déjà un « canal politique lourd » ? Attendez, l’exemple n’est pas fini. Ce modèle conceptuel laisse une très large place à la rhétorique et à la persuasion, exactement comme dans la politique nationale. Mais aussi à la frustration…

Si vous êtes amateur de brocolis frais et que les autres, en majorité, préfèrent la viande rouge, que faire ? Vous risquez de devoir vous mobiliser pour empêcher la commission de ravitailler la cantine uniquement en conserves de petits pois et de maïs. Vous devrez peut-être intervenir, informer le groupe que les vitamins et phytonutriments tels que le sulforaphane contenus dans le brocoli sont bien préférables à un régime riche en graisses saturées et en cholestérol…

Bien sûr, c’est un travail de titan d’obtenir que le groupe vous écoute, ou même lise un tract, dans l’hypothèse où vous êtes autorisé à dépenser pour faire campagne, et à condition encore que tous soient réellement en mesure de lire.

> « Le tableau brosse une société dans laquelle la vaste majorité des Américains ignorent qu’ils n’ont pas les compétences exigées pour se faire une place dans notre société de plus en plus technologique, opérant à l’échelle du monde. » RICHARD RILEY, SECRÉTAIRE D’ÉTAT À L’ÉDUCATION, DANS *ADULT LITERACY IN AMERICA*

### Quatre-vingt-dix millions de cas Alzheimer ?

Si les membres du groupe de cette expérience politique étaient des Américains, vous seriez confronté à un défi de taille, surtout si le niveau d’instruction de ce groupe reflétait celui de l’ensemble de l’électorat américain. L’hypothèse selon laquelle une fraction considérable, sinon majoritaire, des citoyens de la société la plus puissante du monde se situe en deçà des minima requis dans ses accomplissements n’est pas nouvelle. Elle a été confirmée par l’enquête la plus complète jamais menée sur les compétences des adultes américains, *Adult Literacy in America*. On y apprend qu’une large partie – possiblement la majorité – des personnes de plus de quinze ans n’a pas les aptitudes de base pour comprendre un raisonnement ou formuler une opinion. Selon le ministère de l’Éducation, 90 millions d’Américains sont incapables d’écrire une lettre simple, de décrypter un horaire de bus ou de faire des additions et soustractions à l’aide d’une calculatrice. C’est l’équivalent de ce que l’on observerait si 90 millions d’Américains se trouvaient à divers stades de la maladie d’Alzheimer. Trente millions d’entre eux se sont révélés si défaillants qu’ils ne pouvaient même pas répondre aux questions.

Si, malgré tout, votre plaidoyer en faveur du brocoli n’emporte pas l’adhésion populaire, il vous reste la possibilité d’appeler des militants de la cause animale pour qu’ils vont piqueter devant chez ceux qui défendent le comité « viande rouge », ou tentent de leur démarcher à domicile.

On comprendra que cet exemple purement fictif pourrait s’étirer à l’infini. Il illustre clairement que tout mode d’expression économique – s’abstenir d’acheter ou acheter – peut être converti en une expression politique, à condition de rendre la décision collective, voire majoritaire. Et cela montre à quel point les décisions collectives, malgré toute la place faite à l’allocution, se révèlent souvent lourdes et insolubles.

C’est précisément ce que révèle l’expérience. Il est loin d’être simple de rassembler les moyens nécessaires pour infléchir le cours d’une démocratie. Répétons-le : c’est probablement ce qui a assuré la pérennité des États-providence démocratiques, leur permettant même de dominer en fin d’ère industrielle. La démocratie a fonctionné en tant que système politique parce qu’elle complique l’action des « clients » voulant brider la mainmise de l’État sur les ressources.

Cependant, comme l’appropriation illimitée des revenus, par l’État, ne confère plus d’avantage militaire à l’Âge de l’Information, des personnes ingénieuses trouveront des modes bien plus efficients d’acquérir ce que fournissent encore les gouvernements. Il y a de fortes chances que les véritables pouvoirs soient confiés, sous contrat, à des structures collectives qui cesseront de se justifier économiquement. Nous prévoyons que l’efficience se substituera lentement, mais sûrement, à l’effet de masse. Comme l’a dit Neil Munro : « C’est l’information numérisée, non la main-d’œuvre ou la production de masse, qui devient le moteur de l’économie américaine et remportera les conflits dans un monde où fleuriront 500 chaînes TV. Et cette information numérisée, elle, appartient au cyberespace, ce nouveau domaine né de la prolifération infinie des réseaux d’ordinateurs, satellites, modems, bases de données et de l’Internet public »[^449].

Une armée massive ne signifiera plus grand-chose dans un tel contexte. L’efficience aura plus de poids que jamais. Puisque la microtechnologie introduit une nouvelle dimension dans la protection (comme nous l’avons analysé au chapitre 6 et ailleurs), il deviendra possible, pour la première fois dans l’histoire humaine, de placer vos biens hors de tout monopole territorial de la violence. Des biens ainsi situés seront en grande partie invulnérables. Bref, ce sera un atout majeur pour l’individu qui, dorénavant, pourra voter « avec ses pieds » ou plutôt avec son argent, en s’échappant d’un État-nation pour passer un contrat privé de protection avec un autre État plus conciliant, ou une nouvelle mini-souveraineté, dont la facture sera moins exorbitante que la saisie de la plus grande partie de votre patrimoine. En somme, il est probable que vous accepteriez qu’on vous paie 50 millions de dollars pour déménager aux Bermudes.

### D’abord partir, ensuite négocier

L’impulsion initiale en faveur de la commercialisation de la souveraineté résultera des individus manifestant leur désaccord par la « sortie ». Ce choix sera le plus ardu aux États-Unis, là où, pourtant, il a sans doute le plus de valeur. Le « Mur de Berlin » imposé aux capitalistes par le président Bill Clinton et le Congrès républicain contredit le slogan nationaliste en vogue pendant les années 1960 : « Aimez-la ou quittez-la ». En réalité, la taxation punitive sur l’émigration est censée contraindre à la fidélité. Cette législation draconienne, qui rappelle la confiscation imposée aux propriétaires terriens en fuite dans la phase tardive de l’Empire romain, pourrait cependant, par inadvertance, jeter les bases d’une politique plus judicieuse durant l’Âge de l’Information.

À un certain stade, lorsque suffisamment de personnes auront quitté le territoire, emportant avec elles des fortunes considérables à l’étranger, les autorités américaines pourraient découvrir un intérêt économique à autoriser la réintégration de ces contribuables déserteurs en concédant un rachat forfaitaire de toute obligation fiscale future, plutôt que les voir partir réellement. En d’autres termes, la taxe de sortie pourrait devenir l’embryon d’une forme de rachat global. Les gouvernements imposant une telle taxation auraient tout intérêt à permettre à un individu d’y échapper ou de la payer pour renouer résidence, sur la base d’un traité privé, à l’image des dispositions censément en vigueur en Suisse.

De telles avancées s’avèreraient rationnelles du point de vue de la maximisation des recettes. À terme, la concurrence en matière de protection fera fondre les taux d’imposition et mènera des systèmes fiscaux plus civilisés. Au lieu de compter sur le « bon vouloir » du législateur, l’Individu souverain pourra négocier, par traité privé, un régime fiscal acceptable et personnalisé.

## OFFENSER LES VRAIS CROYANTS

Évidemment, tout cela ne sera guère apprécié de beaucoup. La dénationalisation de l’individu et la commercialisation qui l’accompagne heurteront les partisans des clichés politiques du XXᵉ siècle. À l’instar du regretté Christopher Lasch, ils verront dans l’atrophie de la politique un péril pour la majorité de la population. Selon eux, un renouveau de la politique industrielle, ciblant une redistribution des revenus, serait nécessaire pour soulager les détresses provoquées par l’âpreté concurrentielle de la technologie de l’information.

E. J. Dionne Jr., journaliste politique au *Washington Post*, partage, tout comme Lasch, une nostalgie pour la politique. Il défend également l’élan social-démocrate en faveur de l’égalisation qui, sans nul doute, se fera plus bruyant avec les contradictions que le nouvel environnement mégapolitique fera ressortir face aux institutions héritées du monde moderne. Dionne attribue, en effet, l’amélioration notable du niveau de vie dans les pays riches au XXᵉ siècle principalement à la politique démocratique, plutôt qu’aux changements économiques et technologiques. Son message, c’est que l’avenir ne peut être sauvé que si l’on y impose la politique :

> « Le besoin prioritaire, aux États-Unis et dans l’ensemble du monde démocratique, est de renouer avec la réforme démocratique, ce moteur politique qui a rendu l’ère industrielle aussi prospère. Les technologies de l’information, à elles seules, ne bâtiront pas une société viable, pas plus que l’essor industriel, livré à lui-même, n’aurait suffi à améliorer le monde. […] Même les plus formidables percées technologiques ou la plus ingénieuse application d’Internet ne nous préserveront pas de la désagrégation sociale, du crime ou de l’injustice. Seule la politique, l’art de s’organiser, serait capable d’accomplir cette tâche. »[^450]

Dionne et ses semblables ne perçoivent pas que les conditions qui ont rendu l’ère industrielle si favorable à l’usage systématique de la contrainte n’ont pas été choisies par une quelconque volonté. « L’art de s’organiser » est une formule qui n’aurait guère été compréhensible avant l’époque moderne ; la société est beaucoup trop complexe pour être considérée comme le fruit d’une action consciente et délibérée. Les États-nations de l’époque moderne ont surgi spontanément du fait de l’industrialisation, laquelle relevait des nouvelles possibilités conférées par la technologie et qui accroissaient les retours sur la violence. Aujourd’hui, la technologie de l’information diminue ces retours sur la violence. Cela fait de la politique une solution anachronique et irréversible, même si certains souhaiteront ardemment la préserver au XXIᵉ siècle.

> « Ce ne sont ni d’aujourd’hui ni d’hier ; ils sont de tout temps. Nul ne sait d’où ils sont venus. » – SOPHOCLE, *Antigone*

## « ON NE FAIT PLUS LES CHOSES COMME AVANT »

Le désir passionné de « fabriquer des lois », qui nous paraît incarner le simple « bon sens » de la politique du XXᵉ siècle, est loin d’être commun à toutes les époques. Sa prochaine disparition pourrait s’inscrire dans un cycle qui s’est déjà manifesté, disparaissant et réapparaissant au fil du temps. Par exemple, dans l’Antiquité grecque, il était admis, entre autres, que la législation n’était pas du ressort humain. Comme l’a écrit le philosophe Ernst Cassirer, les Grecs soutenaient que « les lois non écrites, les lois de la justice, sont sans origine dans le temps ».[^451] À l’instar d’autres sociétés pré-politiques, ils croyaient qu’aucune intervention humaine ne pourrait surpasser les lois naturelles, « géométriques », de la justice.

Ils ne croyaient donc pas en un « législateur ». Comme l’a formulé Cassirer : « C’est par la pensée rationnelle que nous découvrons les normes de la conduite morale, et c’est la raison, et la raison seule, qui peut leur conférer leur autorité. » En ce sens, tout projet de légiférer en vue de transformer la société reviendrait à légiférer pour changer la géométrie.

### Légiférer comme sacrilège

Pour des raisons pourtant bien différentes, on retrouve une réticence analogue à « faire des lois » durant une bonne partie du Moyen Âge. Comme l’indique John B. Morrall : « Pour les Germains, la loi était quelque chose d’intemporel. » Elle représentait « une garantie des droits » pour les individus au sein d’une tribu[^452]. Les rois et assemblées

> « ne songeaient nullement à créer de nouvelles lois. Une telle intention aurait été, aux yeux des premiers siècles médiévaux, à la fois inutile et plus ou moins blasphématoire, car la loi, à l’instar de la royauté, était chargée d’une aura sacrée. Les rois et leurs conseillers se percevaient plutôt comme des interprètes, voire des clarificateurs du sens véritable d’un ensemble législatif déjà existant et complet. La coutume germanique avait légué au Moyen Âge un principe que ce dernier n’allait jamais oublier, même s’il allait inévitablement s’en écarter parfois dans les faits. Ce principe voulait que les bonnes lois soient redécouvertes ou réaffirmées, mais jamais recréées. »[^453]

Après les dérives législatives du XXᵉ siècle, cette considération paraît tout à fait archaïque. L’envie d’exploiter la contrainte étatique au profit d’intérêts particuliers, notamment par la redistribution du revenu, est devenue presque un réflexe conditionné.

### Des regrets

Il n’est pas étonnant qu’en ces derniers jours de la politique, certains expriment une mélancolie. Cela est inévitable. Et pas seulement du fait de l’ignorance de la plupart des intellectuels vis-à-vis des contraintes mégapolitiques. Peu de chroniqueurs politiques, comme Dionne, se résoudraient à voir s’effondrer la politique, au risque de devoir se recycler chroniqueurs de faits divers. De la même manière, à la fin du Moyen Âge, divers auteurs se sont insurgés contre la fin de la chevalerie. Songeons à *Il Libro del Cortegiano* (*Le Livre du courtisan*), rédigé en 1514 par le comte Baldassare Castiglione, et publié à Venise en 1528 par Alde.

Le regret de Castiglione quant à la disparition progressive de la chevalerie était sincère, sans pourtant pouvoir infléchir la marche du monde au XVIᵉ siècle. Ceci ne se produira pas plus pour l’entrée du XXIᵉ siècle.

Selon notre théorie de la mégapolitique, ce ne sont pas les choix d’une majorité ou l’argumentation d’une élite qui font les bouleversements décisifs, mais essentiellement les impératifs technologiques. Si notre théorie est juste, la raison pour laquelle l’époque moderne, associée à l’idée de citoyenneté et à une politique organisée autour de l’État, a supplanté le système féodal médiéval et la chevalerie reposant sur des serments personnels, tient à l’évolution des coûts et bénéfices découlant d’une innovation technique. La chevalerie ne s’est pas éteinte parce que Castiglione ou d’autres n’auraient pas su persuader une population influente de la nécessité de conserver un certain sens moral et rappel à l’honneur dans les affaires de l’État. Bien au contraire, le *Courtisan* de Castiglione affiche une sévérité à l’égard des princes, critiquant la conduite que Niccolo Machiavelli, dans son *Il Principe*, recommandait pour qui voudrait gouverner un État.

Mais peu importait. Machiavel a été plus largement lu, non parce qu’il était plus brillant orateur, mais parce que les principes développés dans *Le Prince* correspondaient mieux aux conditions mégapolitiques de l’Âge moderne.

Le distingué philosophe du XXᵉ siècle Ernst Cassirer, s’interrogeant sur « Le problème moral dans Machiavel », fait remarquer :

> « Le livre expose, avec un parfait détachement, les voies et moyens par lesquels acquérir et entretenir un pouvoir politique. Il ne dit pas un mot de l’usage légitime ou non de ce pouvoir. […] Quiconque avait un peu de sens critique savait déjà que la vie politique, dans la réalité, fourmille de crimes, de trahisons et de félonies. Mais nul avant Machiavel n’avait jamais entrepris d’enseigner l’art de ces crimes. Ces actes se commettaient, mais on ne les enseignait pas. Que Machiavel ait ambitionné de devenir un pédagogue de la ruse, de la perfidie et de la cruauté, voilà qui était totalement inédit. »[^454]

En d’autres termes, *Le Prince* était une œuvre radicale qui dévoilait une recette de tour de force propre à la modernité, permettant à un chef ambitieux de maximiser sa réussite aux dépens du bien-être général. Machiavel y valide des mœurs qui, jusqu’alors, se heurtaient frontalement à la culture chevaleresque bâtie sur les siècles précédents.

Comme nous l’avons expliqué, l’éthique chevaleresque insistait sur l’extrême loyauté dans l’exécution des serments, laquelle était nécessaire dans une société structurée autour d’un échange de services personnels contre la protection. Les alliances qui soutenaient la structure féodale n’auraient pu en effet émerger spontanément si chacun avait simplement cherché son avantage dans une situation de contrainte. Le sentiment d’honneur devait combler le vide. Face à cela, rien ne pouvait être plus dévastateur que la recommandation de Machiavel, conseillant au Prince de mentir, tromper et voler, si la situation l’exigeait.

À la fin du XXᵉ siècle, *Le Prince* gardait encore une influence certaine pour analyser la politique moderne, et les tyrannies et crimes qui en sont issus. Par contraste, *Le Livre du courtisan* de Castiglione est pratiquement oublié. D’ici un an, il ne sera probablement parcouru en entier que par quelques étudiants de troisième cycle et quelques esthètes passionnés par l’histoire des mœurs.

D’ici quelques décennies, la révolution mégapolitique de l’Âge de l’Information aura rendu *Le Prince* lui aussi obsolète. L’Individu souverain aura besoin d’une nouvelle recette pour le succès, accordant cette fois-ci une place prépondérante à l’honneur et à la vertu dans la gestion de ressources situées hors d’atteinte du pouvoir de l’État. Nous pouvons prédire que des ouvrages prônant de tels préceptes ne seront pas du goût d’E. J. Dionne Jr., ou des autres sociales-démocraties vivantes.

### Une politique guidée par les clients

Cette divergence sera surtout tangible pendant la première phase de la transition, tant que la majorité des juridictions restera prisonnière des mauvaises habitudes de la décision collective, cherchant avant tout à plaire au grand nombre. Plus tard, lorsque la démocratie cédera la place et que le marché de la souveraineté prendra de l’ampleur, on comprendra que c’est une toute autre logique qui s’imposera.

La « politique » telle qu’on la conçoit aujourd’hui, associée à un État-nation, basculera vers une forme plus entrepreneuriale que politique. Dans ce nouveau contexte, les décideurs verront davantage leur marge de manœuvre rétrécie par ce que les gens sont disposés à payer, tout comme un entrepreneur sait qu’il ne peut vendre des nuitées dans un hôtel de luxe en imposant à sa clientèle de venir bricoler l’établissement sous un soleil de plomb. Là où les clients préfèrent profiter de prestations de qualité plutôt que se tuer à la tâche, l’offre du « prestataire » devra s’adapter. Les questions « politiques » perdront de leur acuité puisqu’elles seront ramenées à des considérations entrepreneuriales, les juridictions cherchant fébrilement les politiques les plus attractives pour la clientèle.

### L’atrophie de la politique

Quand cet état de fait deviendra explicite, l’on verra un changement de cap radical. Les populations dans des juridictions en pleine décomposition ne s’attendront plus à choisir parmi un vaste étalage d’objectifs plus ou moins utopiques que la politique de l’ère industrielle soumettait aux débats. Avec une distribution des revenus potentiellement plus inégale que jamais, les juridictions s’appliqueront davantage à fidéliser les clients dont elles estimeront la contribution cruciale et qui pourront aisément s’établir ailleurs.

Dans pareilles conditions, l’ampleur du « spectre des politiques possibles » ne sera plus dictée par les désirs du « vote médian » issu d’un sondage d’opinion. À terme, la souveraineté commercialisée signifiera la prise de contrôle effective des gouvernements par leurs clients. Il en résultera que les opinions des non-clients deviendront comparativement secondaires ou négligeables, exactement comme l’avis d’un utilisateur de Big Mac quant au foie gras est sans incidence sur le prestige d’un restaurant trois étoiles tel que L’Arpège à Paris.

## « LA TRAHISON DE LA DÉMOCRATIE »

Comme le regretté Christopher Lasch, certains objecteront que la technologie de l’information détruit non seulement l’emploi, mais réduit aussi à néant la démocratie en permettant aux individus de protéger leurs ressources de la contrainte politique. À ce titre, les réactionnaires du nouveau millénaire verront dans la confidentialité financière offerte par le numérique une menace gravissime. Ils frémiront à l’idée que la fiscalité sur les revenus et le patrimoine puisse désormais être vraiment « volontaire ». Ils soutiendront des mesures drastiques pour extorquer des capitaux à quiconque semble prospère, via des méthodes comme la « taxation présomptive » ou la rétention pure et simple d’individus fortunés en guise d’otages.

### Les biens de la communauté

Certains signes laissent d’ailleurs percevoir, à l’heure où nous écrivons, que la mainmise des gouvernements sur les marchés mondiaux faiblit, pour le plus grand mécontentement de ceux qui considèrent les individus comme propriétés de l’État-nation. Selon eux, tous les revenus devraient être assimilés à des recettes publiques, autrement dit à la disposition de l’État[^455].

Nous avons déjà abordé les arguments de Lasch dans *Revolt of the Elites* et *The Betrayal of Democracy*. Mais il n’est pas seul à défendre la légitimité quasi absolue de l’État-nation. Michael Sandel, théoricien politique de l’université Harvard, déclare dans *Democracy in Discontent* : « La démocratie n’a pas d’avenir sans un pouvoir politique contrôlant efficacement les forces économiques globales, car, sans ce contrôle, peu importe le vainqueur de l’élection : dans les faits, ce sont les grandes entreprises qui décideraient. »[^456] En d’autres termes, l’État doit à tout prix maintenir son pouvoir coercitif sur l’individu, s’il veut pouvoir s’écarter des lois du marché.

À nos yeux, la plainte de Sandel, tout comme celle de Lasch, n’est que partiellement fondée. Nous admettons que la démocratie perd l’essentiel de sa raison d’être si l’État manque de pouvoir pour contraindre les individus à obéir. Cela ne fait aucun doute. C’est précisément pourquoi la démocratie telle que nous l’avons connue au XIXᵉ et XXᵉ siècle est vouée à disparaître. Mais Sandel néglige la portée immense de la victoire du marché sur la contrainte. Son avertissement relatif à une prétendue « domination corporatiste » dans la configuration post-étatique témoigne d’un anachronisme frappant.

Les entreprises ne seront guère en mesure de dominer les marchés dans cette nouvelle économie globale. Comme nous l’avons déjà mentionné, il n’est même pas certain que les entreprises, du moins sous la forme moderne à laquelle nous sommes habitués, perdurent. Il est très probable qu’elles se transforment partout, en parallèle à la révolution mégapolitique qui accompagne l’Âge de l’Information. Comme nous l’avons dit plus tôt, la microtechnologie inversera les « coûts d’information » qui unissent aujourd’hui le « nœud de contrats » au cœur de l’entreprise. Parlant de l’entreprise, les économistes Michael C. Jensen et William H. Meckling nous rappellent qu’elle se conçoit déjà comme « un nœud de relations contractuelles entre des individus »[^457].

Dans quelle mesure l’entreprise (corporation) pourra-t-elle survivre à la profonde pénétration des forces du marché dans ses relations internes ? Comme le relèvent Louis Putterman et Randall S. Kroszner, cette question « dépend de la complétude du marché et de la capacité de ces forces du marché à saper les relations internes aux organisations »[^458].

Comme nous l’affirmions précédemment, il est douteux que les entreprises maintiennent leur structure actuelle face à l’intensification de la concurrence, dans un contexte où la microtechnologie facilitera l’externalisation de toutes les tâches sur le marché. Le fait que les process de production soient de plus en plus automatisés enlèvera à l’entreprise la fonction qu’elle exerçait pour motiver, coordonner, et surveiller un grand nombre d’employés.

### « Pourquoi des entreprises ? »

Rappelons que la question « Pourquoi des entreprises ? » n’est pas anodine. La microéconomie admet généralement que le mécanisme des prix est le moyen le plus efficace de coordonner les ressources pour en tirer la valeur maximale. Dans ce cadre, la raison d’être des organisations, entreprises ou autres, est loin d’être évidente. Comme le résument Putterman et Kroszner, une firme est avant tout un produit des coûts d’information et de transaction, lesquels tendent à se contracter avec la technologie[^459].

L’Âge de l’Information sera donc l’ère d’une armée de consultants indépendants, plutôt que l’ère des salariés au long cours dans de grandes entreprises. Alors que la technologie abaisse nettement les coûts de transaction, elle permettra aux individus de se libérer à la fois de l’étau des politiciens et du joug hiérarchique des grandes firmes.

Le résultat attendu n’est pas que les individus tomberont entre les griffes des mégacorporations, ni qu’ils subiront la dictature des actionnaires. Bien au contraire. Les sociétés, en tant que telles, n’auront pas davantage de pouvoir pour manipuler les marchés que les gouvernements. Les grands groupes seront, eux aussi, soumis à une rude concurrence, face à des « entreprises virtuelles » nées aux quatre coins du globe. Autant dire qu’elles auront déjà bien assez à faire pour continuer d’exister.

Au bout du compte, les individus constateront qu’ils gagnent une vraie liberté de choix dans un marché totalement libéré, affranchi aussi bien des grands gouvernements que des hiérarchies rigides du capitalisme industriel.

La disparition progressive de nombreuses formes de coûts de transaction sape aussi les nouvelles illusions relatives à ce que l’on appelle « l’économie des parties prenantes ». Soutenue par Tony Blair du Parti travailliste britrannique, ou par certains proches de Bill Clinton, cette théorie prétend que, le socialisme pur s’étant effondré, on peut retrouver via la régulation un compromis entre le marché et l’idéologie socialiste. Selon cette théorie, les dirigeants, actionnaires, salariés et la « communauté » sont tous des « parties prenantes » de l’entreprise. Ils possèdent un « intérêt » au maintien d’une structure de long terme. Il faudrait par conséquent employer l’appareil d’État pour contraindre la firme à maintenir en place des effectifs, des sites de production et à engager des dépenses locales, même si celle-ci doit en subir des surcoûts…

Ce raisonnement du « stakeholder capitalism » table sur l’existence d’institutions capables d’imposer aux entreprises ces obligations. Il implique que la firme soit capable de soutenir de tels surcoûts grâce à des rentes de situation préservées de la concurrence mondiale. Or, plus la globalisation des marchés s’accélère, plus il sera difficile pour un gouvernement local de préserver l’entreprise concernée des pressions concurrentielles planétaires. Des réglementations poussant une société à conserver un personnel excédentaire et à maintenir des usines peu rentables ne la sauveraient que provisoirement de la faillite, à moins qu’on ne ferme entièrement le marché intérieur à la concurrence extérieure, ce qui est de plus en plus irréalisable à l’ère de l’information instantanée.

En outre, il n’y a guère de chance de promouvoir victorieusement un « nouveau contrat social » axé sur un hypothétique « secteur associatif ou bénévole » afin d’occuper les travailleurs privés d’emplois « dans la communauté », comme le préconise Jeremy Rifkin[^460]. Rifkin rêve d’« un partenariat renouvelé entre l’État et le tiers secteur, visant à reconstruire l’économie solidaire… pour nourrir les pauvres, offrir des services de santé primaires, instruire la jeunesse, bâtir des logements abordables ou préserver l’environnement… »[^461].

### L’éclipse des biens publics

Bien sûr, les partisans de la coercition étatique rétorqueront que la chute de l’État-nation nous privera de biens publics. Or, ce n’est pas certain, et ce pour des raisons évidentes de concurrence. Quand la localisation ne sera plus un atout intrinsèque, les juridictions qui n’offriront pas un éventail minimal de biens publics – tels que la justice, la sécurité et l’ordre – perdront rapidement leurs « clients ». Dans les cas les plus extrêmes, tels ceux déjà observés en Somalie, au Liberia, au Rwanda ou dans l’ex-Yougoslavie, on voit bien que les populations délaissent ces États défaillants et fuient vers d’autres pays susceptibles de garantir ce bien fondamental qu’est l’ordre public. Mais même dans ces pays où la fuite est désespérée et ne concerne souvent que des réfugiés démunis, il existe déjà un précédent de cette « sortie », sans même évoquer des évolutions plus pacifiques.

D’autre part, il ne faut pas oublier le rôle imposant que peuvent jouer les entreprises multinationales pour forcer les gouvernements à rendre ces biens collectifs disponibles et de bonne qualité.

### « Des clubs territoriaux en concurrence »

Tout cela ne relève pas que de la théorie, formalisée dans la thèse de l’économiste Charles Tiebout en 1956[^462]. L’économiste Fred Foldvary, dans *Public Goods and Private Communities: The Market Provision of Social Services*, en a identifié des exemples concrets, démontrant qu’on peut fournir des biens collectifs sans recourir à la coercition publique. Les études de Foldvary corroborent également l’argument du prix Nobel Ronald Coase, selon lequel « l’intervention étatique n’est pas indispensable pour résorber les externalités »[^463]. Des entrepreneurs peuvent bel et bien proposer, via des mécanismes de marché, des biens qui ont l’apparence de biens publics. Ses illustrations concrètes montrent comment privatiser les communautés et inventer de nouveaux mécanismes de gestion et de financement de leurs biens et services[^464].

### La route vers la prospérité

Avec la microtechnologie, il sera envisageable d’inventer de nouveaux outils pour financer et réguler les biens publics considérés jusqu’ici comme indissociables de l’État. On découvrira même que certains d’entre eux n’en sont pas de « vrais » au sens strict. Les routes en constituent un exemple clé. Tant que leur fréquentation n’est pas trop forte, on peut feindre qu’elles relèvent du bien public (avec tous les doutes exprimés en leur temps par Adam Smith, qui dénonçait l’injustice faite aux habitants de régions reculées contraints de financer un réseau dont ils ne profitaient pas). Mais à partir du moment où le trafic sature l’infrastructure, il devient techniquement possible de facturer des péages variables sans ralentir la circulation. Dès lors, le financement peut reposer sur ceux qui utilisent « directement » le service. Selon l’économiste Paul Krugman, la pratique d’un péage routier en fonction des horaires et des flux rapporterait entre 60 et 100 milliards de dollars supplémentaires, chaque année, au PIB des États-Unis, tout en améliorant la gestion des ressources et en réduisant la pollution[^465].

Ne perdons pas de vue que la principale activité des grands États modernes – redistribuer les revenus – ne correspond pas du tout à la définition économique d’un bien public. Il s’agit de fournir des biens privés à autrui, mais aux frais de la collectivité. Entendons-nous : par « collectivité », on vise essentiellement les contribuables.

Enfin, il reste la « défense », enjeu plus délicat, car c’est un bien public par excellence (celui de la protection extérieure) et notoirement coûteux dès lors qu’on prétend défendre un territoire face à une autre grande puissance. Évidemment, un gouvernement très contraint budgétairement ne saurait mobiliser des moyens équivalant à ceux mis en jeu lors des grands conflits mondiaux, de l’ampleur de la Seconde Guerre mondiale.

Cependant, ce plafonnement n’est pas le terrible handicap que certains brandiront, car il n’y aura plus, dans les faits, de guerre ressemblant à 1939-1945. La technologie qui émancipe les individus sonne aussi la fin de ces grandes guerres intégrales.

### S’élever au-delà de la politique

Plutôt que de miser la qualité et la pérennité de ces services sur du rapport de force politique, on pourra développer une formule de gestion entrepreneuriale, et transformer l’État en ce que Foldvary appelle des « clubs territoriaux en concurrence »[^466]. Nous croyons que, à long terme, le dispositif institutionnel et la manière de prendre des décisions dans l’organisation de ces « clubs territoriaux » importeront peu par rapport à l’aptitude de ces derniers à satisfaire les exigences du marché. Aujourd’hui, un consommateur n’accorde aucune importance au statut juridique d’une entreprise qui lui vend un produit. Il se soucie seulement de la qualité du produit. De même, à l’Âge de l’Information, il est probable qu’un « client » de la future souveraineté se fiche de savoir si Singapour est une démocratie de masse ou la propriété de Lee Kwan Yew.

[^430]: John Dunn, *Western Political Theory in the Face of the Future*, Cambridge (R.-U.) : Cambridge University Press, 1979, p.2.  

[^431]: Carroll Quigley, *Weapons Systems and Political Stability* (Washington, D.C. : University Press of America, 1983).  

[^432]: Ibid., p.56.  

[^433]: Cité par Kelly, *op. cit.* p.46.  

[^434]: Molander et al., *Strategic Information Warfare*, *op. cit.*, p.xv.  

[^435]: Ibid., p.xiv.  

[^436]: Dennis C. Mueller, *Public Choice*, vol.2 (Cambridge : Cambridge University Press, 1989), p.43-226.  

[^437]: Michael A. Bernstein, *The Great Depression: Delayed Recovery and Economic Change in America, 1929–1939* (Cambridge : Cambridge University Press, 1987).  

[^438]: Mancur Olson, *The Rise and Decline of Nations: Economic Growth, Stagflation, and Social Rigidities* (New Haven : Yale University Press, 1982).  

[^439]: Michael M. Phillips, « Math Ph.D.s Add to Anti-Foreigner Wave : Scholars Facing High Jobless Rate Seek Immigration Curbs », *Wall Street Journal*, 4 septembre 1996, p.A2.  

[^440]: Juan J. Linz et Alfred Stepan (dir.), *The Breakdown of Democratic Regimes* (Baltimore, Md. : The Johns Hopkins University Press, 1978), p.18.  

[^441]: William Keech, *Economic Politics: The Costs of Democracy*, Cambridge : Cambridge University Press, 1995, p.221.  

[^442]: E. S. Staveley, *Greek and Roman Voting and Elections* (Ithaca, N.Y. : Cornell University Press, 1972), p.62.  

[^443]: Ibid., p.65.  

[^444]: Norman Cohn, *The Pursuit of the Millennium* (Oxford : Oxford University Press, 1970), p.41.  

[^445]: Ibid., p.84-85.  

[^446]: Cité par Kelly, *op. cit.*, p.46.  

[^447]: Milton Friedman, *Capitalism and Freedom* (Chicago : University of Chicago Press, 1962), p.91. Évoqué par Hirschman, *op. cit.*, p.16-17.  

[^448]: Hirschman, *op. cit.*, p.17.  

[^449]: Neil Munro, « The Pentagon’s New Nightmare : An Electronic Pearl Harbor », *Washington Post*, 16 juillet 1995, p.C3.  

[^450]: E. J. Dionne, « Why the Right Is Wrong », *Utne Reader*, juin 1996, p.32.  

[^451]: Ernst Cassirer, *The Myth of the State* (New Haven : Yale University Press, 1946), p.81.  

[^452]: John B. Morrall, *Political Thought in Medieval Times* (New York : Harper Torchbooks, 1962), p.15.  

[^453]: Ibid., p.16.  

[^454]: Cassirer, *op. cit.*, p.142, 150.  

[^455]: Robert I. Shapiro, « Flat Wrong : New Tax Schemes Can’t Top Old Progressive Truths », *Washington Post*, 24 mars 1996, p.C3, et Thomas L. Friedman, « Politics in the Age of NAFTA », *New York Times*, 7 avril, p.E11.  

[^456]: Cité par Friedman, *op. cit.*  

[^457]: Voir Louis Putterman et Randall S. Kroszner, « The Economic Nature of the Firm : A New Introduction », in Louis Putterman et Randall S. Kroszner (dir.), *The Economic Nature of the Firm: A Reader* (Cambridge : Cambridge University Press, 1996), p.17.  

[^458]: Ibid.  

[^459]: Ibid., p.9.  

[^460]: Voir Jeremy Rifkin, *The End of Work: The Decline of the Global Labor Force and the Dawn of the Post-Market Era* (New York : G.P. Putnam’s Sons, 1995).  

[^461]: Ibid., p.250.  

[^462]: Voir Charles M. Tiebout, « A Pure Theory of Local Expenditure », *Journal of Political Economy* 64 (1956), p.416‑424.  

[^463]: Mueller, *op. cit.*, p.28‑29.  

[^464]: Fred Foldvary, *Public Goods and Private Communities: The Market Provision of Social Services* (Aldershot, Hants, Angleterre : Edward Elgar Publishing, Ltd., 1994).  

[^465]: Paul R. Krugman, « The Tax-Reform Obsession », *New York Times Magazine*, 7 avril 1996, p.37.  

[^466]: Foldvary, *op. cit.*, p.66 sq.  